### ISSUE TITLE
video=no os:win window required? (no pun intended)

### ISSUE THREAD

**Issue by chapmanjacobd** [mpv-player/mpv#9913] opened 2022-02-24 22:59 UTC
### Important Information

Provide following Information:
- mpv v2021.11.01 (0.34.0)
- Windows 10 21H2 19044
- Source of the mpv binary: choco

### Reproduction steps

```bat
mpv.exe .\01.opus --no-config --video=no --audio-display=no
```

### Expected behavior

On linux no window is created

### Actual behavior

On Windows it seems like a window is required....?

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/8137066/output.txt)

**Comment by avih** [comment] 2022-02-24 23:14
> ### Expected behavior
> On linux no window is created

You're supposed to describe what you expect (e.g. "a window should open"). The fact that On linux a window is created does not necessarily mean that this is also what you expect on WIndows.

> ### Actual behavior
> On Windows it seems like a window is required....?

You're not supposed to ask a question here. You're supposed to describe what happens, which should make it obvious how it's different from what you expect.

> ### Reproduction steps
> 
> ```batchfile
> mpv.exe .\01.opus --no-config --video=no --audio-display=no
> ```

Your log says otherwise:
```
Command line options: '--player-operation-mode=pseudo-gui' 'D:\80_Now_Listening\08_The_Crush.opus' '--no-config' '--audio-display=no' '--log-file=output.txt'
```

So you explicitly enable pseudo-gui mode, which opens a window, and this is by design (not a bug).

I'll close this issue for now. If you still think there's a bug/issue, please post more accurate expectation, actual behavior, and log which matches your steps to reproduce.

**Closed by avih** 2022-02-24 23:14 UTC
Labels: os:win

**Comment by chapmanjacobd** [comment] 2022-02-24 23:24
hmm... I've never used `--player-operation-mode=pseudo-gui`

But looking more closely at the docs it looks like `player-operation-mode` is applied unconditionally to Windows

> if started from explorer.exe on Windows (technically, if it was started on Windows, and all of the stdout/stderr/stdin handles are unset)

```
mpv.exe D:\80_Now_Listening\08_The_Crush.opus --no-config  --audio-display=no --video=no --player-operation-mode=cplayer
```

this actually fixes my problem ! thanks... still kinda weird behavior... I guess it is not technically a bug though since it is documented in the middle

**Comment by chapmanjacobd** [comment] 2022-02-24 23:34
but maybe it should be considered a bug if the behavior is unknown to even the maintainer...

**Comment by avih** [comment] 2022-02-24 23:37
> still kinda weird behavior

If you launch it from explorer/desktop/shortcut, then without a window you will have no way to control it (pause, quit, seek, etc) except to kill it via the task manager. So a window is pretty much required in such case, which is why pseudo-gui is enabled.

If you run it from a console (cmd.exe or power shell) then you can control mpv via keypresses at the console, so by default a window opens only if there's a video/image to show.

**Comment by garoto** [comment] 2022-02-24 23:44
`C:\>mpv.com [args]` from a cmd.exe prompt won't create a window if there are no vid streams.

**Comment by avih** [comment] 2022-02-24 23:46
In the future, "steps to reproduce" means to list the exact steps so that someone which follows them will be able to see the problem which you have.

In your case, this:
> Reproduction steps
> mpv.exe .\01.opus --no-config --video=no --audio-display=no

Doesn't mention at all that you create a shortcut, and no one would be able to reproduce your problem, which completely defeats the purpose of this description.

**Comment by Hrxn** [comment] 2022-02-25 03:33
As garoto already mentioned, and as described in the opening post's steps to reproduce, you are using `mpv.exe`, *which **is not** the same* as just using `mpv <some opts>  <some file>` on Windows.

That's because on every standard Windows system, unless changed by the user, domain settings or some third-party program, the default value for the `PATHEXT` environment variable is this:
`.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL`

As you can see, `.COM` comes before `.EXE`, and this makes the difference here. 
To use the CLI "variant" of mpv on Windows, you must use `mpv.com` where all the handling for stdin, stdout etc. is properly set. This is not the case for `mpv.exe`, because this is always disabled there, and `mpv.exe` will also always spawn a window, even if you turn off video output (or simply deselect any video stream), or play an audio file.

**Comment by Hrxn** [comment] 2022-02-25 03:43
But one more thing..
 
> Your log says otherwise:
> 
> ```
> Command line options: '--player-operation-mode=pseudo-gui' 'D:\80_Now_Listening\08_The_Crush.opus' '--no-config' '--audio-display=no' '--log-file=output.txt'
> ```
> 
> So you explicitly enable pseudo-gui mode, which opens a window, and this is by design (not a bug).
> 

Yeah, the file in the log is not identical to what is mentioned in the STR, but, to be fair, I don't think any speculation about launching via Windows shortcut (?) is necessarily warranted here, simply because if you actually launch `mpv.exe` instead of `mpv.com` it will automatically activate pseudo-gui-mode, and that is why it is present in the log file here, I'd assume.

BTW, pseudo-gui-mode is actually awesome, you can set custom options here in your `mpv.conf` (syntactically, it's the same as any named options profile) that are ignored when using mpv from any console, for example I'm using the `keep-window` option when launching the "window-only" (mpv.exe) mpv variant, that is not active when using mpv from any terminal window, because it would be  nuisance then 😄
