### ISSUE TITLE
weston fullscreen toggle regression since  wayland: set fs mode on every configure

### ISSUE THREAD

**Issue by AndyFurniss** [mpv-player/mpv#2877] opened 2016-02-27 15:19 UTC
Using current weston/wayland testing outside X.
since -
commit eb6b2b6e50e6e3d3db41190ad818d8b966750734
wayland: set fs mode on every configure

Toggling between windowed and fullscreen fails to get back to the initial window size when returning from fullscreen. The window is still sized full screen dimensions with only a portion visible as it doesn't start at 0,0.

There is repeated -v logging output like

[vo/opengl/wayland] resizing 1920x1080 -> 1920x1080
[vo/opengl] Resize: 1920x1080
[vo/opengl] Window size: 1920x1080
[vo/opengl] Video source: 720x576 (64:45)
[vo/opengl] Video display: (0, 0) 720x576 -> (0, 0) 1920x1080
[vo/opengl] Video scale: 2.666667/1.875000
[vo/opengl] OSD borders: l=0 t=0 r=0 b=0
[vo/opengl] Video borders: l=0 t=0 r=0 b=0

**Comment by wm4** [comment] 2016-02-27 16:04
Duplicate of #2817.

**Closed by wm4** 2016-02-27 16:04 UTC
