### ISSUE TITLE
doesn't play youtube video

### ISSUE THREAD

**Issue by Max-Enrik** [mpv-player/mpv#7957] opened 2020-07-29 20:38 UTC
I drag and drop video from youtube and/or copy paste of the video link on mpv, but mpv shut down.
I removed and re-installed but still same. How can I play youtube video in mpv?

**Comment by Dudemanguy** [comment] 2020-07-29 20:48
If you are using wayland, this is a duplicate of #7954. If not, well make a proper issue next time.

**Closed by Dudemanguy** 2020-07-29 20:48 UTC
Labels: meta:question, priority:ignored-issue-template
