### ISSUE TITLE
[gpu-next] Assertion failure when playing using hwdec on vulkan

### ISSUE THREAD

**Issue by Carl-Robert** [mpv-player/mpv#10067] opened 2022-04-08 05:29 UTC
### Important Information

- mpv version: 0.34.0-242-g083ae8e736 (built on Sun Apr  3 00:43:21 UTC 2022)
- Windows Version: Windows 11 Enterprise build 22581 (have happened on previous insider builds too)
- Source of the mpv binary: Scoop
- If known which version of mpv introduced the problem: Have happened in all builds with gpu-next hwdec support.
- Possible screenshot or video of visual glitches: 
![image](https://user-images.githubusercontent.com/15616797/162367141-5ba20fdd-c456-4473-aab3-834a48d8a074.png)
Screenshot of the Windows' error message window that usually pops up when hwdec fails. Other times it successfully reverts to software decoding.

### Reproduction steps

Try to play a file with --vo=gpu-next --gpu-api=vulkan --hwdec=auto --hwdec-codecs=all (last not necessary, it happens on whitelisted formats too).

Sometimes the error message window appears when going fullscreen the first time, sometimes it appears after a while (speeding up or seeking around the file makes it jump up faster).

### Expected behavior

Smooth playback without hitches using hwdec.

### Actual behavior

The player freezes up when the Assertion failure pop-up appears or fails back to software decoding.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/8448785/output.txt)
The repeating lines in the end happened while the Assertion failure pop-up was already up.

**Comment by zhongfly** [comment] 2022-04-08 14:23
https://github.com/mpv-player/mpv/issues/9949
have fixed by https://github.com/mpv-player/mpv/commit/7f67a553f68a9df87997fdcb6484ffd243ca2162

**Comment by Carl-Robert** [comment] 2022-04-09 01:54
Doesn't seem fixed to me? The mpv-git from Scoop is built 20220403, meaning that fix should be a part of it.

**Comment by ValZapod** [comment] 2022-04-09 11:21
--hwdec=nvdec does not work with gpu-next, BTW. I see no HW decoding happening.

**Comment by hooke007** [comment] 2022-04-09 11:53
> --hwdec=nvdec does not work with gpu-next, BTW. I see no HW decoding happening.

You were drunk. 

> Try to play a file with --vo=gpu-next --gpu-api=vulkan --hwdec=auto --hwdec-codecs=all

> [   0.273][i][vd] Using hardware decoding (nvdec).

**Comment by ValZapod** [comment] 2022-04-09 12:01
> You were drunk.

Works with vulkan, which does not do color correctly.

**Comment by hooke007** [comment] 2022-04-09 12:06
> Does not work with --gpu-api=d3d11, the default.

He Did Not use d3d11 at all. Why talk sth off-topic here?

**Comment by ValZapod** [comment] 2022-04-09 12:10
Vulkan is buggy.

**Comment by haasn** [comment] 2022-04-09 13:23
cc @philipl this assertion is triggered by `cuda_ext_vk_wait` being called twice in a row without the texture being used by libplacebo. This is a case that's only prevent inside libplacebo for reason of it being completely untested and hard to get right. Though I wonder if there's something we're doing wrong which leads to a frame being re-waited on?

@Carl-Robert are you in a position to test patches to libplacebo?

**Comment by Carl-Robert** [comment] 2022-04-09 15:18
I don't unfortunately have a building setup for patches. I can of course test pre-compiled builds, if not too much of a hassle.

**Comment by ValZapod** [comment] 2022-04-09 15:22
> . I don't get GitHub sometimes...

The problem is with you not github.

**Closed** 2022-04-11 13:43 UTC
Labels: os:win
