### ISSUE TITLE
Certain Twitch Vods not playing correctly

### ISSUE THREAD

**Issue by TheRyuu** [mpv-player/mpv#2180] opened 2015-08-01 03:04 UTC
When viewing certain twitch vods such as (with mpv+youtube-dl):

```
mpv.exe --ytdl http://www.twitch.tv/riotgames/v/8926431
mpv.exe --ytdl http://www.twitch.tv/riotgames/v/9164950
```

Only the last 10 seconds (or what I believe to be the last 10 seconds) of the vod will play.  I am unsure whether this is a youtube-dl, mpv, or ffmpeg issue.  Using the "--hls-prefer-native" option correctly starts downloading the vod at the beginning when using just youtube-dl.

```
youtube-dl.exe --hls-prefer-native -f Source http://www.twitch.tv/riotgames/v/8926431
```

I believe this occurs regardless of the quality level (format), I tried Source and High and both times I had this problem when using mpv+youtube-dl.

mpv does not show the correct length and I cannot seek either.  Nothing shows up in the console.  It's as if they're being treated like a live stream.  Apologies if this is not actually a mpv issue but I'm unfamiliar with this stuff and I have to start somewhere.

Windows 8.1 Update 3 64-bit
mpv 2015-07-26 64-bit from http://mpv.srsfckn.biz/
youtube-dl 2015.07.28 Official Windows exe

**Comment by jaimeMF** [comment] 2015-08-01 10:36
It could be a Twitch problem, for that video the m3u8 file manifest without `#EXT-X-ENDLIST`:
```
#EXTINF:3.533,
index-0000005339-FBbU.ts?start_offset=41948064&end_offset=43457703
#EXTINF:4.000,
index-0000005339-FBbU.ts?start_offset=43457704&end_offset=45009831
#EXTINF:4.000,
index-0000005339-FBbU.ts?start_offset=45009832&end_offset=46582639
```
I assume that ffmpeg thinks it's a live stream because of this.
While for other vods (like http://www.twitch.tv/riotgames/v/9206159) it has the correct ending:
```
#EXTINF:4.000,
index-0000005368-3khB.ts?start_offset=19933076&end_offset=20766855
#EXTINF:4.000,
index-0000005368-3khB.ts?start_offset=20766856&end_offset=21552883
#EXTINF:4.000,
index-0000005368-3khB.ts?start_offset=21552884&end_offset=22334023
#EXTINF:4.000,
index-0000005368-3khB.ts?start_offset=22334024&end_offset=23113095
#EXT-X-ENDLIST
```

Using other formats allows to seek and see the duration:
* `--ytdl-format High` for http://www.twitch.tv/riotgames/v/8926431
* `--ytdl-format Medium` for http://www.twitch.tv/riotgames/v/9164950 (with High it has the same problem)

**Comment by wm4** [comment] 2015-08-01 13:40
Whether the stream is broken or uses non-standard extensions, it's an issue that can only be fixed in ffmpeg's HLS code.

**Comment by wiiaboo** [comment] 2018-01-15 19:40
Still there, still a twitch or particular stream issue. Couldn't reproduce with another VOD.

**Closed by wiiaboo** 2018-01-15 19:40 UTC
Labels: ffmpeg-bug
