### ISSUE TITLE
Instant quit

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#12563] opened 2023-10-04 23:00 UTC
+ `input.conf`: `q quit` + `MBTN_FORWARD playlist-next`
+ `mpv.conf`: `demuxer-max-bytes=20GiB`
+ [autoload.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua) with many files (not sure if they are have to be from a network drive)
+ Windows 10 + https://github.com/shinchiro/mpv-winbuild-cmake/releases

Current behavior:
Press `q` after `autoload.lua` added many files and used `MBTN_FORWARD` to skip a few files (and pausing on a `.png` or any other small file size) does not result in instant quit of mpv, even though the current RAM usage by mpv is low.

Suggested behavior:
Press `q` after `autoload.lua` added many files and used `MBTN_FORWARD` to skip a few files (and pausing on a `.png` or any other small file size) results in instant quit of mpv, because the current RAM usage by mpv is low.

More information:
I wasn't sure if to open it as a "feature" or as an "issue", because I vaguely remember mentioning it on IRC quite some time ago and the reason behind this behavior was mpv was clearing off the RAM slowly so it is to be expected because mpv uses 20GiB, but I don't think it's true because while mpv is paused on small file size mpv still slowly quit even though the RAM usage by mpv is currently low.

For comparison - closing mpv using the task manager is instantaneous. 
While I think instant quit is a good feature, I also think that there must be some delay to quit mpv for the simple reason that mpv must save to shader cache (which is on by default), but I do think that the current `quit` still needs improvements or optimizations.

**Comment by christoph-heinrich** [comment] 2023-10-04 23:12
mpv does provide a `pid` property, so if windows has something like the kill command on other platforms, you could create a key binding that kills that mpv instance instead of quitting normally.

**Comment by christoph-heinrich** [comment] 2023-10-04 23:34
Does `q run taskkill /IM “mpv.exe” /F` in `input.conf` not work for you?

**Comment by christoph-heinrich** [comment] 2023-10-04 23:43
I don't use windows so I can't debug this, but something like it should work.
Btw you can include the pid in your command with `${pid}`, in case you want to try something with that.

**Comment by dyphire** [comment] 2023-10-05 04:30
You should use this command of `run cmd /d /c taskkill /im mpv.exe` in your input.conf

**Comment by guidocella** [comment] 2023-10-05 06:43
Duplicate of https://github.com/mpv-player/mpv/issues/12294

**Closed as completed** 2023-10-05 12:43 UTC
Labels: meta:feature-request

**Comment by llyyr** [comment] 2023-10-12 17:18
Can you reproduce this issue with an older build? Especially one from before June 17th this year?

**Comment by llyyr** [comment] 2023-10-13 01:43
Yes, and can you also try the build artifact from #12566 to confirm whether it does fix this issue for you?
