### ISSUE TITLE
midi playback is buggy (sounds bad and/or crashes mpv)

### ISSUE THREAD

**Issue by dardoor** [mpv-player/mpv#8724] opened 2021-04-13 16:10 UTC
### Important Information

- mpv version: 0.33.0-107-gdd86f195a6 (mpv-x86_64-20210404-git-dd86f19)
- Windows Version: Windows 10 64bit
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20210404-git-dd86f19.7z/download

### Reproduction steps

1. open mpv
2. load a midi (.mid) file

### Expected behavior

It plays properly.

### Actual behavior

It either doesn't sound right or it crashes/exits mpv.

### Log file (for the crash)

[output.txt](https://github.com/mpv-player/mpv/files/6305132/output.txt)

### Sample files

This .mid file makes mpv crash/exit: [Simpsons.mid](https://bitmidi.com/uploads/94020.mid)
Other .mid files just don't sound right, like [toto-africa.mid](https://bitmidi.com/uploads/105027.mid)

Both of these play fine elsewhere, for example in foobar2000 with foo_midi.

**Comment by amariami** [comment] 2021-04-16 07:00
Yep same on Linux mint Ulyssa. Midi is broken
[rel_ulyssa_xfce.mpv.log](https://github.com/mpv-player/mpv/files/6323114/rel_ulyssa_xfce.mpv.log)

**Comment by sfan5** [comment] 2021-04-16 14:41
Firstly, your log doesn't show mpv "crashing". It exits with an error message after unsuccessfully trying to read the file.

mpv does not implement MIDI support itself but lets ffmpeg handle it, ffmpeg supports either [libopenmpt](https://lib.openmpt.org/libopenmpt/) or [libmodplug](https://github.com/Konstanty/libmodplug) for decoding. If something is wrong with that it's not our bug.

> This .mid file makes mpv <s>crash/</s>exit: Simpsons.mid

This file just happens to be smaller than 16k and you're using libmodplug so this will be a duplicate of #8466.

**Closed by sfan5** 2021-04-16 14:41 UTC
Labels: os:win

**Comment by kikuyan** [comment] 2021-04-20 08:43
I'm just interested in this issue and not insisting on using mpv to play MIDI, but libmodplug seems to be the only choice because libopenmpt doesn't support MIDI ([FAQ](https://lib.openmpt.org/libopenmpt/faq/)).

As you probably know and I apologize if you've done so already, you need to set up timidity.cfg and GUS patch files for libmodplug to play MIDI. By default, you need `/usr/local/share/timidity/timidity.cfg` and patch files in `instruments` subdirectory for Unix-like OS, `C:\TIMIDITY\TIMIDITY.CFG` and patch files in `INSTRUMENTS` subdirectory for Windows. (The location can be changed by setting environment variable `MMPAT_PATH_TO_CFG`.)

This is what I've managed to use [FreePats](https://freepats.zenvoid.org/SoundSets/general-midi.html) General MIDI sound set.
- Download "Old FreePats General MIDI sound set" from [FreePats](https://freepats.zenvoid.org/SoundSets/general-midi.html) (or [BitMidi author](https://github.com/feross/freepats)).
- Extract downloaded file, name the top directory `freepats`.
- Make `instruments` directory in `freepats`, move `Drum_000` and `Tone_000` into it.
- Open `freepats.cfg`, edit as below, save as `timidity.cfg`.  
Move `drumset 0` block (about 60 lines) to the bottom (under `bank 0` block).  
Remove `.pat` from every lines.

The directory structure should look like this:
```
freepats/
├── instruments/
│   ├── Drum_000/
│   │   └──(patch files)
│   └── Tone_000/
│       └──(patch files)
└── timidity.cfg
```
- Set `MMPAT_PATH_TO_CFG` to the path to `freepats` and run mpv (or ffplay).  
`MMPAT_PATH_TO_CFG=/path-to/freepats mpv toto-africa.mid`  
By setting `--demuxer-lavf-probescore=20` (#8474), Simpsons.mid can be played, too.  
`MMPAT_PATH_TO_CFG=/path-to/freepats mpv --demuxer-lavf-probescore=20 Simpsons.mid`

Sounds still may not be so good, though.

**Comment by kikuyan** [comment] 2021-04-21 04:23
I forgot to mention. While I was reading other issue reports, I noticed this commit https://github.com/mpv-player/mpv/commit/4f18e7927bacd2e887f8cca48a967804ce7adf86 which enables fluidsynth support (but reverted soon afterwards https://github.com/mpv-player/mpv/commit/16b44d93f7014b3abd8f21a4035fd4ebeed1d2c0).
If you have fluidsynth and soundfont installed, apply the changes, configure --enable-fluidsynth and build, mpv plays MIDI just fine. (Just run fluidsynth to play MIDI is easier, of course.)
