### ISSUE TITLE
AppImage request for more user friendliness

### ISSUE THREAD

**Issue by Tcll** [mpv-player/mpv#10951] opened 2022-12-02 02:49 UTC
After sadly having been forced to build an AppImage myself (more specifically an AppDir) for an older version that maintains A/V sync on vdpau

I'd like to just point out how easy it is to just pack everything into an AppDir and run appimagetool on with the proper AppRun to sandbox everything with
though for me, I've only built an AppDir:
https://jump.matthewevan.xyz/i2p/pxbcwxbhxj2wusliwhrb6ym4vcwpihztuf2tfjejrcdzqrmnjuoa.b32/_/3fd513c264c689208544c82fd601e6e622181536911c1bf3541b2761040cb80b

here's the version information reported:
https://jump.matthewevan.xyz/i2p/pxbcwxbhxj2wusliwhrb6ym4vcwpihztuf2tfjejrcdzqrmnjuoa.b32/_/26bd803b2ba2fa4eeb346c0019e74ed65645209b2298a8878cf439584df05e68

and everything works properly as shown here:
https://jump.matthewevan.xyz/i2p/pxbcwxbhxj2wusliwhrb6ym4vcwpihztuf2tfjejrcdzqrmnjuoa.b32/_/d746aecdcd7ac03f4839304803069c79621f063cd479e19a312ba932b2910671

the extra bit involving home.sh just makes it easier to store settings in a portable location and can be ignored
the AppRun itself is no different from executing a properly sandboxed AppImage

why not make it easier on your users to actually use mpv if I'm showing an AppImage can be built just fine :)
it's sad there wasn't an appimage of this version already

**Comment by CounterPillow** [comment] 2022-12-09 14:24
duplicate of #4056

**Closed** 2022-12-21 15:30 UTC
Labels: meta:feature-request
