### ISSUE TITLE
Correct-downscaling causes ewa_lanczossharp to introduce a half-pixel shift when downsampling sometimes

### ISSUE THREAD

**Issue by Artoriuz** [mpv-player/mpv#13405] opened 2024-02-03 21:26 UTC
### Important Information

- mpv version: mpv v0.37.0-234-g57d68262
- Platform and Version: Windows 11 Pro 22H2
- Source of the mpv binary: Shinchiro
- If known which version of mpv introduced the problem: No idea
- GPU model, driver and version: 6600XT Adrenalin 24.1.1
- Possible screenshot or video of visual glitches: All below

### Reproduction steps
`magick convert rei.png -filter lanczossharp -distort resize 75% im_ewa_lanczossharp.png`
![im_ewa_lanczossharp](https://github.com/mpv-player/mpv/assets/12078193/e18ebc7c-942e-4d6c-9ed9-320b121b2aca)

`mpv --no-config --vo=gpu-next --gpu-api=vulkan --no-hidpi-window-scale --pause=yes --screenshot-format=png --deband=no --dither-depth=no --screenshot-high-bit-depth=no --dscale=ewa_lanczossharp --linear-downscaling=no --window-scale=0.75 rei.png`
![mpv_ewa_lanczossharp](https://github.com/mpv-player/mpv/assets/12078193/f87c0214-8cf6-4973-96e0-8d678aa3f571)

`mpv --no-config --vo=gpu-next --gpu-api=vulkan --no-hidpi-window-scale --pause=yes --screenshot-format=png --deband=no --dither-depth=no --screenshot-high-bit-depth=no --dscale=ewa_lanczossharp --linear-downscaling=no --window-scale=0.75 --correct-downscaling=no rei.png`
![mpv_ewa_lanczossharp_incorrect](https://github.com/mpv-player/mpv/assets/12078193/e3d1e5aa-1f24-42ab-a2f0-a1dba5e8fb0f)

### Expected behavior
mpv's output should probably roughly match whatever ImageMagick is doing.

### Actual behavior
mpv's output with `correct-downscaling` turned on appears to have a half-pixel shift towards the top-left corner (rounding issue somewhere?). Screenshot with it turned off also provided to show that there's no shift in this case, so the problem seems related to turning it on. Filters with integer supports seem fine as well.

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/14154304/output.txt)

### Sample files
![rei](https://github.com/mpv-player/mpv/assets/12078193/e263fcb1-72c1-4cb2-8090-a5844efe2165)

**Comment by Artoriuz** [comment] 2024-03-03 18:21
Update: After talking to @llyyr about this he couldn't reproduce it on his system and I couldn't reproduce it with `gpu-api=opengl` either, so it's likely a driver problem.

**Comment by llyyr** [comment] 2024-03-03 18:37
I couldn't reproduce this on X11/Wayland or with a Windows build running through wine. Seems to be driver/Windows related since Artoriuz can only reproduce it with d3d11/vulkan as well.

**Comment by kasper93** [comment] 2024-03-03 20:16
I haven't tested myself, but I've seen recently similar issue. That could be related and explain on px offset. 

See:
https://github.com/Blinue/Magpie/pull/803
https://github.com/bjin/mpv-prescalers/commit/bfcf48a15562eda973f9713041a60eb31516586a

Maybe @bjin remembers more detail about it. But since it has 0.49 workaround, I think he didn't get to the root cause of it?

If we really have rounding issues around half values, well it should be fixed somehow, because it may produce weird issues here and there.

**Comment by kasper93** [comment] 2024-03-04 10:13
Will be fixed by https://code.videolan.org/videolan/libplacebo/-/merge_requests/647

**Closed** 2024-03-04 12:39 UTC
