### ISSUE TITLE
Geometry option not working

### ISSUE THREAD

**Issue by SiddharthMant** [mpv-player/mpv#13223] opened 2024-01-04 18:51 UTC
### Important Information

Provide following Information:
- mpv version : 0.36.0
- Linux Distribution and Version : Fedora 39 KDE (Wayland)
- Source of the mpv binary : Package Manager
- Window Manager and version : kwin 5.27.10
- GPU model, driver and version : Vega 7 iGPU, Mesa 23.3.1
- Possible screenshot or video of visual glitches : NA

### Reproduction steps
`mpv --no-config --geometry=0:0 --autofit=70% ~/Downloads/test.mp4`

### Expected behavior
- The window should appear on top left of screen due to geometry option

### Actual behavior
- The window appears at center of screen

### Log file
[log](https://github.com/mpv-player/mpv/files/13834356/mpv.txt)

### Sample files
- Use any file

**Comment by guidocella** [comment] 2024-01-04 18:52
Wayland doesn't allow applications to position themselves.

**Comment by SiddharthMant** [comment] 2024-01-04 18:54
Ahh any workaround ? (other than x11 :P)

**Comment by SiddharthMant** [comment] 2024-01-04 18:55
Should also be mentioned in docs.

**Comment by guidocella** [comment] 2024-01-04 18:58
Setting `--wayland-app-id` and configuring your compositor to position windows with that id.

**Comment by Dudemanguy** [comment] 2024-01-04 20:11
Duplicate of #8692.

>Should also be mentioned in docs.

Yeah guess I should add a wayland note.

**Closed by Dudemanguy** 2024-01-04 20:11 UTC
Labels: os:linux

**Comment by karlkliem** [comment] 2024-09-19 11:41
> Setting `--wayland-app-id` and configuring your compositor to position windows with that id.

Could you please give an example, what the configuration in ~/.config/wayfire.ini would look like and what the mpv command would look like to play a video in a window at position 100 100 740 580 for example?

**Comment by guidocella** [comment] 2024-09-19 12:29
I don't use wayfire.

**Comment by karlkliem** [comment] 2024-09-19 12:36
I am on the current Raspberry Pi OS bookworm, which uses wayfire.ini with Wayland, and need to play two videos from the 2 outputs of a Raspberry Pi 4. I guess I need to open another thread then. Thanks anyway.

**Comment by karlkliem** [comment] 2024-09-19 17:30
> > Could you please give an example, what the configuration in ~/.config/wayfire.ini would look like and what the mpv command would look like to play a video in a window at position 100 100 740 580 for example?
> 
> Ask on wayfire's issue tracker or IRC. I can tell you for sway or river, but that won't help you much. Also you don't need to set `--wayland-app-id` manually, it should be set to "mpv" by default.

Thanks for the suggestion. I got a [reply](https://github.com/WayfireWM/wayfire/issues/2468) and will try that.

**Comment by githubgitgit** [comment] 2025-08-03 18:29
Setting window position works in ffmpeg/ffplay/mplayer via command line arguments in Wayland/RPi.. Is it really not possible to get it working in mpv?
