### ISSUE TITLE
Framedrops at regular intervals with video-sync=display-resample

### ISSUE THREAD

**Issue by occivink** [mpv-player/mpv#3792] opened 2016-11-12 10:30 UTC
### mpv version and platform

archlinux
mpv 0.21.0
intel hd3000 (also reproducible with hd530 and same setup)
mesa 13.0

### Reproduction steps

`mpv --no-config --video-sync=display-resample any_video`

### Expected behavior

No framedrops, especially when frame timings are well below tolerances.

### Actual behavior

Noticable framedrops every ~10 seconds . Happens in the sample video at 8s, 18s, ...
Note that a "plateau" in the vsync jitter property happens at the same time.

### Log file

http://sprunge.us/NAiW

### Sample files

Video capture of stats.lua during playback to better illustrate the phenomenon.
http://0x0.st/2UU.mkv

**Comment by kevmitch** [comment] 2016-11-12 10:44
It looks like the measured (estimated) display fps is closer to 59.66 hz than the 60.0 hz reported by xrandr. I have found that manually setting the `display-fps` to the measured values helps.

    --display-fps=59.66

Unfortunately, sticking the equivalent in your `mpv.conf` is problematic if you use other displays that don't have this issue.

**Comment by occivink** [comment] 2016-11-12 10:50
I tried with 59.66 and it doesn't change anything, there are still framedrops every ~10 seconds.

**Comment by haasn** [comment] 2016-11-12 13:13
> It looks like the measured (estimated) display fps is closer to 59.66 hz than the 60.0 hz reported by xrandr.

That's most likely just a consequence of framedrops during rendering. On too slow hardware the estimated FPS will often be significantly below the reported FPS.

**Comment by wm4** [comment] 2016-11-12 13:28
Not if the difference is less than 1 Hz and the estimated fps is stable.

**Comment by occivink** [comment] 2016-11-15 18:28
So I can reproduce this issue on different hardware (intel hd530 and a display with correct specified fps) and same software. I'm pretty sure this bug is somewhat recent (<4 months) but my attempts at downgrading some of the software involved (ffmpeg, mesa and of course mpv) to see what causes it were unsuccessful. Is there anybody with a similar setup, in particular gpu, that can reproduce these results?

**Comment by lachs0r** [comment] 2016-11-18 17:46
I wonder… Are you using the modesetting DDX or the intel one? You should simply uninstall the intel DDX if you’re using it because it’s broken and most of its glaring issues remain unfixed after several years. And it keeps getting worse for some reason. I did notice some weird vsync jitter as well as random stuttering or GPU freezes with it, but not with modesetting, so give it a try.

**Comment by occivink** [comment] 2016-11-18 18:59
So it looks the ddx driver is provided on arch by the xf86-video-intel package, which I don't have installed so I'm going to guess modesetting.

**Comment by kevmitch** [comment] 2016-12-10 15:41
What kernel version are you using? It looks like I start to see the same things (mistimed frames and a 10-fold jump in vsync jitter every 2 or 3 seconds) with [this commit](http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=ea0000f0d369a59c2086fe9c489e0a2a86e080ba) (first released in linux-4.8). linux-4.7 does not have this problem.

**Comment by occivink** [comment] 2016-12-10 16:14
I'm on 4.8.12. The release date 4.8 looks like it may coincide with when my issue started, I'll try to downgrade to see if that changes anything.

**Comment by occivink** [comment] 2016-12-11 07:37
I can indeed confirm that this does not happen with version 4.7.6 of the kernel.

**Comment by kevmitch** [comment] 2016-12-11 09:46
I don't seem to notice any problems when running a simple vsync timer like glxgears. [vsynctester.com](https://www.vsynctester.com) doesn't seem to be affected by this change - it works quite well in chroimum with or without this change. I wonder what mpv is doing differently to trigger this?

**Comment by wm4** [comment] 2016-12-11 12:33
glxgears draws as fast as possible, so it should behave similar to mpv. Chromium most likely does something slightly different, like actually driving the render loop with a timer, but I haven't checked.

**Comment by lachs0r** [comment] 2017-07-22 02:03
Reopen if it’s still an issue. I can’t reproduce this on HD4600, kernel 4.11.8, Mesa 17.1.4.

**Comment by kevmitch** [comment] 2017-07-24 01:13
I'm still seeing this. 

[mpv <file.mkv> -log-file=log.txt'  --no-config --video-sync=display-resample --fs](http://sprunge.us/bjGa)

* HD4000 
* linux-4.11.11 (debian linux-image-amd64=4.11+83)
* Mesa 17.1.4-1
* mpv / ffmpeg today's git master.

consequently, I'm still running linux-4.7.10

**Comment by wm4** [comment] 2017-07-24 01:18
stats dump?

**Comment by kevmitch** [comment] 2017-07-24 01:22
[stats.txt](http://sprunge.us/dfeV)

**Comment by mattia-b89** [comment] 2019-08-13 15:49
Can't reproduce this issue.

CPU: i5-5200U
os: Arch Linux
kernel: 5.2.7
mesa: 19.1.4
modesetting driver (xorg server): 1.20.5

**Comment by Akemi** [comment] 2019-12-03 19:41
stale issue.

**Closed by Akemi** 2019-12-03 19:41 UTC
Labels: to-be-closed, upstream:intel
