### ISSUE TITLE
[Wayland] No borders on player's window

### ISSUE THREAD

**Issue by Jiehong** [mpv-player/mpv#4033] opened 2017-01-14 13:57 UTC
### mpv version and platform
Mpv at ddaab3349b28, on Archlinux.

### Reproduction steps
1. Build mpv;
2. log on to Gnome 3.20 or 3.22 on wayland;
3. launch a video file smaller than the screen size with mpv.

### Expected behaviour
Player opens, and video starts playing in its own window. The windows opens in the centre of the screen.

### Actual behaviour
Player opens, and video starts, but the player's window has no borders on any side. It also appears on the top left corner by default, never in the centre.

### Log file
See attachment.
[output.txt](https://github.com/mpv-player/mpv/files/705972/output.txt)

### Sample files

Happens with any file or stream (like youtube video).

**Comment by wm4** [comment] 2017-01-14 14:01
Duplicate of #139.

**Comment by atomnuker** [comment] 2017-01-14 14:01
Duplicate of #3646

**Closed** 2017-01-14 14:02 UTC
