### ISSUE TITLE
How to play all files in a windows directory?

### ISSUE THREAD

**Issue by EzeKees** [mpv-player/mpv#4799] opened 2017-08-24 19:47 UTC
### mpv Windows 10 64 bits

Good afternoon.
How do I have to write to the MPV command line in Windows to play all media files in a directory?
I try to write:
mpv.exe --dir="D:\Tiempo Libre\Informes" 
But it does not work, I know there is a way, but I can not do it. 

 Thank you very much to all.

**Comment by wiiaboo** [comment] 2017-08-24 20:45
Duplicate of https://github.com/mpv-player/mpv/issues/4711

**Closed by wiiaboo** 2017-08-24 20:45 UTC

**Comment by EzeKees** [comment] 2017-08-24 21:21
Thank you very much!
