### ISSUE TITLE
MPV 0.36.0 (latest) macOS builds by stolendata does not work on MacOS Sonoma 14.0.

### ISSUE THREAD

**Issue by rulingthehun** [mpv-player/mpv#12502] opened 2023-09-27 08:47 UTC
- MPV 0.36.0
- MacOS Sonoma 14.0 (M2Pro)
I just updated to MacOS Sonoma 14.0 and MPV is not working on this MacOS.

**Comment by Akemi** [comment] 2023-09-27 11:34
my guess, duplicate of #12116

**Closed by Akemi** 2023-09-27 11:34 UTC
Labels: os:mac, priority:ignored-issue-template
