### ISSUE TITLE
HEVC hardware decoder breaks after seeking in macOS 10.14 (Mojave)

### ISSUE THREAD

**Issue by LeoNatan** [mpv-player/mpv#6152] opened 2018-09-23 22:39 UTC
### mpv version and platform
git master

### Reproduction steps
`mpv --no-config -v --hwdec=auto file.mkv`
Seek by clicking on the OSC

### Expected behavior
Should seek without broken frames and hardware accelerator should not fail.

### Actual behavior
A broken image appears for a little bit (until a new keyframe is decoded), and hardware acceleration is broken.

### Log file
https://0x0.st/s3eo.log

Notice toward the end:

```
[ffmpeg/video] hevc: Could not find ref with POC 0
[ffmpeg/video] hevc: hardware accelerator failed to decode picture
[vd] Error while decoding frame!
[ffmpeg/video] hevc: Could not find ref with POC 5
[ffmpeg/video] hevc: hardware accelerator failed to decode picture
[vd] Error while decoding frame!
[ffmpeg/video] hevc: Could not find ref with POC 3
[ffmpeg/video] hevc: hardware accelerator failed to decode picture
[vd] Error while decoding frame!
[vd] Falling back to software decoding.
[vd] Detected 12 logical cores.
[vd] Requesting 13 threads for decoding.
[vd] DR failed - disabling.
[ffmpeg/video] hevc: Could not find ref with POC 0
[ffmpeg/video] hevc: Could not find ref with POC 2
[ffmpeg/video] hevc: Could not find ref with POC 3
[ffmpeg/video] hevc: Could not find ref with POC 5
```

### Sample files
Should reproduce with any HEVC file.

**Comment by LeoNatan** [comment] 2018-09-23 22:42
Interestingly, this only reproduced for me when seeking with the OSC, not the touch bar, and it doesn't happen every seek. But a few seeks are enough to reproduce.

Maybe I should mention that the file being played is on a network share.

I originally opened https://github.com/mpv-player/mpv/issues/6146 but was not sure what was going on. The issue only reproduced on IINA. With IINA it reproduces a lot quicker. But I have now managed to reproduce on mpv as well.

This issue does not reproduce for h264 files.

**Comment by LeoNatan** [comment] 2018-09-23 22:46
Here is a video of the reproduction:
https://0x0.st/s3eX.mov

Notice how low CPU turns into high CPU (along with a sudden window resize).

**Comment by Argon-** [comment] 2018-09-24 04:15
OSC seeks are exact seeks afaik.

**Comment by LeoNatan** [comment] 2018-09-24 08:30
In that case, exact seeks fail for HEVC content. For H264 they work. IINA sends commands for seeks which are not exact, and this issue reproduces still, so I am assuming there is an issue with seeks in general.

**Comment by Akemi** [comment] 2018-09-24 08:46
then it's probably a duplicate of the previously linked issue #5755. @tmm1 proposed a fix (ffmpeg) for this in the [last comment](https://github.com/mpv-player/mpv/issues/5755#issuecomment-390000020), though the OP never replied if it fixes this issues for him. it would be helpful if you can test with a patched ffmpeg again and report if it works or not.

**Closed by Akemi** 2018-09-24 08:46 UTC

**Comment by Akemi** [comment] 2018-09-24 08:56
could also be related to #5893, which also is most likely related to the other issue.

**Comment by LeoNatan** [comment] 2018-09-24 10:30
Could you please point me to how to test that fix? For my testing, I used brew to build from `--HEAD`.

**Comment by Akemi** [comment] 2018-09-24 11:28
i guess you would need to edit the ffmpeg hombrew formula (/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula) and add a patch like [this](https://github.com/Homebrew/homebrew-core/blob/8e016940ce965241fba195a651c5642f706eeb74/Formula/qt%405.5.rb#L29-L32) to it. as patch url you can use [this](https://github.com/tmm1/FFmpeg/commit/d5624b0401b6d65de9cdfd726f5c6e7a1496a494.patch), leave the sh256 checksum out and brew ffmpeg and mpv with `--HEAD`.

**Comment by Akemi** [comment] 2018-10-02 18:56
just wondering could you test it and if yes did it work?

**Comment by LeoNatan** [comment] 2018-10-02 19:04
Sorry, I've been busy with holidays here and work. Will test this weekend. Thank you
