### ISSUE TITLE
Click the right-seek, but the pause get triggered

### ISSUE THREAD

**Issue by twlz0ne** [mpv-player/mpv#2887] opened 2016-02-29 02:25 UTC
![mpv-seek-pause](https://cloud.githubusercontent.com/assets/2653486/13383569/7961765e-dec6-11e5-866c-5202d8be63c8.gif)

``` sh
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.9.5
BuildVersion:   13F1603

$ mpv --version
 built on Mon Feb 22 12:28:14 CST 2016
ffmpeg library versions:
   libavutil       55.17.103
   libavcodec      57.24.102
   libavformat     57.25.100
   libswscale      4.0.100
   libavfilter     6.31.100
   libswresample   2.0.101
ffmpeg version: 3.0
```

**Comment by wm4** [comment] 2016-02-29 11:52
Can't reproduce.

**Comment by twlz0ne** [comment] 2016-02-29 17:06
@wm4

1. `brew install mpv`
2. `mpv /path/to/file`
3. Click on any other window
4. Click right-seek button of mpv (then the pause get triggered)

**Comment by chrisaljoudi** [comment] 2016-03-01 09:56
Can’t reproduce on OS X 10.11.

@twlz0ne you look like you’re using `--no-border` in the GIF; what other options, if any?

**Comment by twlz0ne** [comment] 2016-03-02 01:01
@chrisaljoudi 

```sh
$ find ~/.config/mpv/ -type f | xargs -If sh -c "echo ==== f ====; cat f"
==== ~/.config/mpv//input.conf ====
= add sub-scale +0.1
- add sub-scale -0.1
F2 cycle_values video-aspect "16:9" "16:10" "4:3" "2.35:1" "-1"
==== ~/.config/mpv//lua-settings/osc.conf ====
valign=-0.98
==== ~/.config/mpv//mpv.conf ====
screenshot-format=png
screenshot-template=~/Desktop/%F_%wH.%wM.%wS.%wT
border=no
ontop=yes
softvol=yes
softvol-max=600
af=drc
osd-color=0.75/0.5
osd-border-color=0.1/0.75
sub-text-font="STHeiti"
sub-auto=fuzzy
slang=zh,cn,chs,chi,cht,en,eng,jp,jpn
```

**Comment by twlz0ne** [comment] 2016-04-01 08:33
@wm4 @chrisaljoudi

Nobody pays attention to this issue anymore?

All right, i think found the problem，it appears only in retina screen, see diagram below

![mpv-player-coordinate](https://cloud.githubusercontent.com/assets/2653486/14201865/32f218ca-f827-11e5-8d8c-7b1d3af328ad.png)

I also print some log when the function signalMousePosition is called

if valign < 0

    mouse location    { x:481.796875, y:423.132812 }
    bounds size       { w:848.000000, h:460.000000 }
    point to pixels   { x:963.593750, y:73.734375 }
    after clamp       { x:847.000000, y:73.734375 }

else

    mouse location    { x:480.667969, y:59.707031 }
    bounds size       { w:848.000000, h:460.000000 }
    point to pixels   { x:961.335938, y:800.585938 }
    after clamp       { x:847.000000, y:459.000000 }

I see the following code 39537f6

    p.x = MIN(MAX(p.x, 0), self.bounds.size.width-1);
    p.y = MIN(MAX(p.y, 0), self.bounds.size.height-1);

was added by @torque claims to `Prevents out-of-window coordinates`, but there is nothing wrong if delete those code, on my computer.

**Comment by wm4** [comment] 2016-04-01 08:36
Might be something with how the OSC dispatches mouse events?

CC @ChrisK2

**Comment by AirPort** [comment] 2016-04-01 11:52
Still can't reproduce on my MBP with retina screen, Os X 10.11.4. I tried mpv (`--no config`) with different monitor's resolutions and with the player both fullscreen and windowed, but the right seek, and every other UI's element, always shows the expected behaviour.

**Comment by torque** [comment] 2016-04-01 13:21
The mouse coordinate clamping code was something I wasn't sure about, but to my memory it got merged without much discussion. I'm not sure how this is handled on other platforms.

For what it's worth, I suspect this might be fixed for retina by using `[self convertRectToBacking:self.bounds]`, rather than simply removing it entirely, if keeping the current behavior is desired. Either way, my own script had some troubles with this change that I had to work around, so I wouldn't be entirely upset to see it gone. I think there should be some discussion of the "correct" behavior re: clamping mouse coordinates to window bounds.

**Comment by wm4** [comment] 2016-04-03 17:59
So...?

**Comment by Akemi** [comment] 2017-02-17 01:45
okay i think i kinda know what happened here, why the patch helped, and why it couldn't be reproduced by anyone/only a few. my recent mouse refactor (https://github.com/mpv-player/mpv/commit/9ac05a575ce6cffa679c79b6539a798a2d41efde) should fix it, not only because the clamping code was removed.

anyway it was an unfortunate combination of wrong mouse events and what @torque suspected  above.

**Closed by Akemi** 2017-02-17 01:45 UTC
Labels: info-needed, osx
