### ISSUE TITLE
Clarification on hidpi Vs. geometry / window-scale

### ISSUE THREAD

**Issue by forthrin** [mpv-player/mpv#12588] opened 2023-10-07 11:50 UTC
### Important Information

Provide following Information:
- mpv version 84fa7ea
- macOS Version 14.0
- Source of the mpv binary or bundle: Git
- If known which version of mpv introduced the problem: #12222
- Possible screenshot or video of visual glitches

### Reproduction steps

MacBook Air M1 with 2560x1600 real pixels scaled down by a factor of 16:9 to 1440x900 virtual pixels.

The window width becomes the commented number at the end of each line (measured in virtual pixels)

[480p test video](https://v3.cdnpk.net/videvo_files/video/free/2015-08/originalContent/cornfield_2.mp4)

### Actual behavior

```
$ mpv --hidpi-window-scale=yes --geometry=852x480 # 426  (852 / 2 = 426)
$ mpv --hidpi-window-scale=no  --geometry=852x480 # 426
$ mpv --hidpi-window-scale=yes --window-scale=1   # 852
$ mpv --hidpi-window-scale=no  --window-scale=1   # 426
```

### Expected behavior

```
$ mpv --hidpi-window-scale=yes --geometry=852x480 # 480  (852 / (16:9) = 480)
$ mpv --hidpi-window-scale=no  --geometry=852x480 # 852
$ mpv --hidpi-window-scale=yes --window-scale=1   # 852
$ mpv --hidpi-window-scale=no  --window-scale=1   # 852
```

I would expect mpv to interpret geometry values as real pixels when the `hidpi` option is yes.

And since `--window-scale` is a relative float multiplier, I wouldn't expect the `hidpi` option to have any effect at all.

Unless this is a bug or incomplete implementation -- or unless `hidpi` is something completely different than Apple's virtual pixels...? -- can someone explain the logic behind these options, as the manual doesn't make it very clear either?

### Log file

N/A

**Comment by Akemi** [comment] 2023-10-07 13:03
"Scale the window size according to the backing scale factor" from the documentation

your backing scale factor ist 2. geometry is not affected by it because it is always treated as pixels.
window-scale is affected because it scales the base size of the window, which changes with hidpi-window-scale.

the current behaviour is the currently expected behaviour.

i think this is a duplicate of https://github.com/mpv-player/mpv/issues/4218 and my feature request https://github.com/mpv-player/mpv/issues/5688. if implemented it would introduce proper behaviour.

on a side note, maybe a bit too much info and to clarify the terminology. Apple doesn't speak of 'virtual pixels' or 'real pixels'. it's either 'virtual screen', 'virtual resolution', 'points' or 'pixels'. see https://developer.apple.com/library/archive/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/Explained/Explained.html

1440x900, is the resolution how it will appear on screen or the 'virtual screen', always measured in 'points'
2, is the 'backing scale factor', the multiplier the get the resolution in pixels, or rather the relation/factor between 'pixels' and 'points'
2880x1800, is the actual resolution in pixels (or should be, it has been a while for me) of the rendering surface of the whole screen
2560x1600, is the resolution of the display in pixels and the target resolution the rendering surface of the screen gets downscaled to (if needed)

**Closed by Akemi** 2023-10-07 13:03 UTC
Labels: os:mac

**Comment by forthrin** [comment] 2023-10-07 13:23
So there are actually three coordinate systems:

1. Virtual pixels (mimicking previous Air models without Retina)
2. Double virtual pixels (Retina)
3. The actual display

Good thing there's already attention on it. I'm sure you'll find a good and logical solution.

Also, be sure to update the manual with these details.

PS! I must say I'm somewhat amazed that Apple are able to maintain this paradigm and make it look good.

**Comment by Akemi** [comment] 2023-10-07 15:08
a pretty simplified view is, in the Apple eco system there actually is only one system, eg only points exist and the backing store factor. all measurements are in points. the backing store factor is there to convert between points/pixel and is mostly used for (backwards) compatibility or the internal usage. every other system can be inferred by those informations and you don't need to care about anything else.

there obviously are edge cases like opengl, older none native Apple systems, etc and that's the reason why we have this mix within mpv.

i am not sure which informations to add and where exactly. maybe it's not appropriate for the manual and it should be added to the wiki.
