### ISSUE TITLE
I am using util.subprocess. How to detach it, so that i can start another

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#3600] opened 2016-09-29 13:19 UTC
I am trying to execute two bash commands using utils.subprocess.

1st will use ffmpeg to cut the vide.
2nd open the  cut video in new mpv.

its working fine. But i cant execute further till i close the mpv (the 2nd command produced)
how to push the subprocess to background

**Comment by rr-** [comment] 2016-09-30 16:03
Use `subprocess_detached` which is available in the newest version (you'll probably need to compile it yourself, or wait till it gets released)
Also dupe of #3588

**Closed** 2016-12-25 09:49 UTC
