### ISSUE TITLE
autoload.lua adds re-adds files to playlist if pressing "next" while using "script-message osc-playlist"

### ISSUE THREAD

**Issue by DoTheEvo** [mpv-player/mpv#8694] opened 2021-04-04 15:50 UTC
Very minor issue, but maybe the fix is also trivial and would prevent some other issues?

### Important Information

Provide following Information:
- mpv version v0.33.0
- autoload.lua version Feb 14, 2020
- arch Linux and windows

### Reproduction steps

use autoload.lua script
have assigned hotkeys for next/previous file in playlist
have them also show playlist
`PGUP playlist-prev; script-message osc-playlist`
`PGDWN playlist-next; script-message osc-playlist`

now load a playlist of 10 files
press and hold pagedown to go fast through files
press and hold pageup to go fast through files back up
watch as occasionally playlist grows on its own

### Expected behavior
just have 10 files in playlist and skipping between them

### Actual behavior
if holding the button and going fast through playlist
files already in playlist are re-added to it

### Log file

[logfile](https://0x0.st/-cqk.txt)

### video demonstration

[https://streamable.com/olvb93](https://streamable.com/olvb93)

Maybe just some check if the file is not already in playlist?
Or maybe turn off adding files to playlist on next/previous/event and just do it on start?

**Comment by Akemi** [comment] 2021-05-07 18:36
i believe this is most likely a duplicate of #8575. if not let me know and i will reopen this.

**Closed by Akemi** 2021-05-07 18:36 UTC
Labels: os:linux, scripting:autoload
