### ISSUE TITLE
Request for ability to show osc during seeks, either via new Input Command Prefix: osc (or osc-show, or similar), or cli/config option

### ISSUE THREAD

**Issue by AndydeCleyre** [mpv-player/mpv#3826] opened 2016-11-21 22:42 UTC
The use case I have in mind is seeking, while `osd-level=0` is set, and the user would like to see the progress via the `osc`.

So the behavior of a new Input Command Prefix would be similar to that of `osd-bar`, but displaying the `osc` instead of the `osd`.

I don't know if this would be desirable for other commands for other users, so I'll note that for my particular satisfaction, I would also consider a cli/config option to display the `osc` during seeks to solve this ticket as well.

@wiiaboo Has mentioned that this may depend on #2891.

**Comment by taz4hvn** [comment] 2017-09-03 10:21
I want this too ! An option to show osc on any seek command and pause/unpause would be useful and consistant.

**Comment by ersi-dnd** [comment] 2019-07-08 10:24
+1

**Comment by jaseg** [comment] 2020-07-19 10:38
Check out [python-mpv issue #124](https://github.com/jaseg/python-mpv/issues/124). The lua script there is a workaround until this gets solved in mpv.

**Comment by CrendKing** [comment] 2021-07-04 03:40
```
if mp.get_property_bool("osc") then
    for key, loader in pairs(package.loaders) do
        res = loader('@osc.lua')
        if type(res) == 'function' then
            res('@osc.lua')
            break
        end
    end

    -- show OSC at start to signify change of file
    mp.register_event("start-file", show_osc)
    -- show OSC at seek to know where we are
    mp.register_event("seek", show_osc)
end
```

**Comment by alexopus** [comment] 2022-04-16 08:36
@CrendKing after adding your suggested script the OSC on seek displays as desired.

But after adding it there is now a ~15% chance that the progress bar will stop responding to mouse clicks (neither for seek, nor for changing audio/subs). And the issue remains until the player is restarted.

Seems like some sort of race happens that puts OSC in a bad state?
Any idea how to fix/avoid that?

Adding this terrible workaround before your code seems to "fix" it:
```lua
function sleep(n)
  local t = os.clock()
  while os.clock() - t <= n do
    -- nothing
  end
end
sleep(0.01)
```

**Comment by CrendKing** [comment] 2022-04-16 11:47
No idea. I have this problem too. If it bothers too much, I guess try remove the "start-file" hook?

**Comment by alexopus** [comment] 2022-04-16 11:53
Yeah, I tried removing the `start-file` hook, but it didn't help. And I think the start-file hook is also nice :)

**Comment by CrendKing** [comment] 2022-04-16 12:23
So it is the loading of the osc.lua that puts it in a bad state? OK, what if we do
```lua
mp.register_event("file-loaded", function()
    if mp.get_property_bool("osc") then
        for key, loader in pairs(package.loaders) do
            res = loader('@osc.lua')
            if type(res) == 'function' then
                res('@osc.lua')
                break
            end
        end

        -- show OSC at start to signify change of file
        show_osc()

        -- show OSC at seek to know where we are
        mp.register_event("seek", show_osc)
    end
end)
```
`file-loaded` event is after playback is started. Hopefully it is late enough that the player's own OSC module has already fully loaded.

**Comment by CrendKing** [comment] 2022-04-16 12:32
So it is the loading of the osc.lua that puts it in a bad state? OK, what if we do
```lua
if mp.get_property_bool("osc") then
    mp.register_event("file-loaded", function()
        for key, loader in pairs(package.loaders) do
            res = loader('@osc.lua')
            if type(res) == 'function' then
                res('@osc.lua')
                break
            end
        end

        -- show OSC at start to signify change of file
        show_osc()
        -- show OSC at seek to know where we are
        mp.register_event("seek", show_osc)
    end)
end
```
`file-loaded` event is after playback is started. Hopefully it is late enough that the player's own OSC module has already fully loaded.

I don't have a way to consistently reproduce the problem though.

**Comment by rbx** [comment] 2022-04-16 16:01
> Hopefully it is late enough that the player's own OSC module has already fully loaded.

With this version I could not get mouse action to fail anymore (after 40 manual tries, I also don't have a reliable way of reproducing it, but with the original it would fail after ~10 restarts). *But*, now seeking with keyboard no longer shows the OSC. So, somehow that doesn't really do what it's supposed to.

**Comment by CrendKing** [comment] 2022-04-17 00:13
> Also, if it did work, I wonder if that would register an additional event handler on each new file? Or does it get overwritten?

You have a good point. It does double register. How about this:
```lua
local function load_and_show_osc()
    if show_osc == nil then
        for key, searcher in pairs(package.searchers) do
            res = searcher('@osc.lua')
            if type(res) == 'function' then
                res('@osc.lua')
                break
            end
        end
    end

    show_osc()
end

if mp.get_property_bool("osc") then
    -- show OSC at start to signify change of file
    mp.register_event("start-file", load_and_show_osc)

    -- show OSC at seek to know where we are
    mp.register_event("seek", load_and_show_osc)
end
```

**Comment by rbx** [comment] 2022-04-18 08:47
Not sure if that fixes the mouse actions, but with this there is no OSC, neither on seek nor on file change :/

**Comment by CrendKing** [comment] 2022-04-18 08:53
I have no idea why it doesn't work for you. Works perfectly for me. Anybody else can confirm? Do you see any error message from your console/terminal?

**Comment by rbx** [comment] 2022-04-18 09:46
Just tried it on Linux - there it works! But on Windows it doesn't 🤷‍♂️.

**Comment by rbx** [comment] 2022-04-18 09:48
Also on Linux I cannot get mouse to fail with your latest code piece. After ~50 tries.

**Comment by CrendKing** [comment] 2022-04-18 10:03
What about
```lua
local function load_and_show_osc()
    if show_osc == nil then
        require "@osc.lua"
    end

    show_osc()
end

if mp.get_property_bool("osc") then
    -- show OSC at start to signify change of file
    mp.register_event("file-loaded", load_and_show_osc)

    -- show OSC at seek to know where we are
    mp.register_event("seek", load_and_show_osc)
end
```

**Comment by rbx** [comment] 2022-04-18 10:16
Both versions show OSC on seek/file change on Windows. Second code failed on mouse movement on first try. First code works great so far - ~50 tries, no failures!

**Comment by muzzol** [comment] 2023-01-22 21:01
is this being added to internal code instad of script?
or should I assume it will be the official solution for a while?

**Comment by CrendKing** [comment] 2023-01-23 06:37
Feel free to use my code if it works for you. It is by no mean official solution though.

**Comment by EBADBEEF** [comment] 2024-01-12 19:39
I'll throw mine into the arena:
```
if mp.get_property_bool("osc") then
  require "@osc.lua"
  mp.register_event("start-file", function() process_event("mouse_move", nil) end)
  mp.register_event("seek", function() process_event("mouse_move", nil) end)
end
```
I have this in a file `~/.config/mpv/scripts/show_osc_on_seek.lua`. I also have `osd-bar=no` in `~/.config/mpv/mpv.conf`

I used 'process_event' instead of 'show_osc' because the 'show_osc' function depends on some internal state set by 'process_event'. See [osc.lua](https://github.com/mpv-player/mpv/blob/d56ad8f0329e973d4c41e93f8491b4d3ceac9793/player/lua/osc.lua#L2506) source for details.

I think ideally this would be added to the list of `user_opts` inside of osc.lua so it could be configured in `osc.conf`.

**Comment by CrendKing** [comment] 2024-01-12 21:12
`process_event("mouse_move")` does not work for me, because for example when I seek with a right arrow key, the mouse does not move, and I have `minmousemove=2`. It should work if `minmousemove=0`.

**Comment by kasper93** [comment] 2024-06-15 23:24
Fixed by: #14358

**Closed by kasper93** 2024-06-15 23:24 UTC
Labels: meta:feature-request, scripting:osc, core:option-param-conf

**Comment by AndydeCleyre** [comment] 2024-08-06 04:26
@kasper93 So can this now be done either via a new Input Command Prefix, or cli/config option?

Or is it necessary to add a new script?

**Comment by guidocella** [comment] 2024-08-06 05:57
You need this script:

```lua
mp.observe_property('seeking', 'native', function(_, seeking)
    if seeking then
        mp.command('script-message osc-show')
    end
end)
```
