### ISSUE TITLE
Deinterlace makes mpv segfault when using vaapi

### ISSUE THREAD

**Issue by linkmauve** [mpv-player/mpv#4678] opened 2017-07-27 21:35 UTC
### mpv version and platform
0.26.0-40-g81851febc4, on ArchLinux.

### Reproduction steps
`mpv --deinterlace=yes some-video.webm`

### Expected behavior
I would get the video without interlacing.

### Actual behavior
mpv crashes.

### Log file
```
[cplayer] Run command: cycle, flags=9, args=[deinterlace, (NULL)]              
[vf] Opening video filter: [vavpp]                                             
mpv: ../video/mp_image_pool.c:174: mp_image_pool_add: Assertion `mp_image_is_writeable(new)' failed.
```

### Sample files
Any.

**Comment by haasn** [comment] 2017-07-27 21:35
Duplicate of #4652

**Closed by haasn** 2017-07-27 21:36 UTC
