### ISSUE TITLE
Setting for multiple instances of mpv?

### ISSUE THREAD

**Issue by FatherOfAlways** [mpv-player/mpv#4950] opened 2017-10-02 22:31 UTC
A few days ago I upgraded to High Sierra and installed mpv 0.27.0. Previously (when I was running mpv 0.27.0 on Sierra), when a video was already playing in mpv and I opened another video from Finder, the newly opened video would start playing in the existing mpv window.
Now, however, if I open a new video when something is already playing, a new instance of mpv opens.

Is there a setting that I missed that would restore the old behaviour? I don't even know why the behaviour changed in the first place since I'm running the same version of mpv. Or was there something that changed with the new OS?

Any help would be appreciated.

**Comment by Akemi** [comment] 2017-10-02 22:34
#4926 duplicate of. will be fixed with #4936.

**Closed by Akemi** 2017-10-02 22:34 UTC
