### ISSUE TITLE
OSD: force line break instead of omitting the rests

### ISSUE THREAD

**Issue by mpvfeatures** [mpv-player/mpv#4377] opened 2017-04-27 00:01 UTC
### mpv version and platform
0.24.0
debisn-testing

### Reproduction steps
My input.conf:
```
i osd_show_property_text "${filename}"     # display filename in osd
I osd_show_property_text "${path}"     # display full filename in osd
```
I watch a video with this filename:
```
/var/share/video/show/DOCTOR.WHO/DOCTOR.WHO.[5th].[134].[3of4].[21x04].-.Resurrection.of.the.Daleks.-.3.avi
```

### Expected behavior
If i'd named the file:
```
DOCTOR WHO [5th] [134] [3of4] [21x04] - Resurrection of the Daleks - 3.avi
```
the osd would show:
```
DOCTOR WHO [5th] [134] [3of4] [21x04] - 
Resurrection of the Daleks - 3.avi
```

Even with dots instated of spaces I at least expect it to show:
```
DOCTOR.WHO.[5th].[134].[3of4].[21x04].-.Resurrecti
on.of.the.Daleks.-.3.avi
```
### Actual behavior
I only displays: 
```
/var/share/video/show/DOCTOR.WHO/DOCTOR.WHO.[
```

i only displays: 
```
DOCTOR.WHO.[5th].[134].[3of4].[21x04].-.Resurrecti
```

**Comment by wiiaboo** [comment] 2017-04-27 00:21
Not easily possible. Libass (what mpv uses to render OSD and text subtitles) doesn't support zero-width spaces, so there's no easy way to split non-space line-breakable characters other than adding a lot of text between them.

**Comment by wiiaboo** [comment] 2017-04-27 00:22
Also, duplicate of https://github.com/mpv-player/mpv/issues/4308

**Closed by wiiaboo** 2017-04-27 00:22 UTC
