### ISSUE TITLE
The color of HVC1 footage becomes abnormal with a specific nvdec option. --profile=default

### ISSUE THREAD

**Issue by serunis** [mpv-player/mpv#14515] opened 2024-07-10 07:24 UTC
### mpv Information

```bash
mpv 0.37.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
libplacebo version: v6.338.2
FFmpeg version: 6.1.1-3ubuntu5
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```

### Other Information

- Linux version:Ubuntu 24.04 LTS
- Kernel Version:Linux ubuntu-desktop 6.8.0-36-generic #36-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun 10 10:49:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- GPU Model:06:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA102 [GeForce RTX 3090] [10de:2204] (rev a1)
- Mesa/GPU Driver Version: driverInfo= 555.52.04, driverInfo= Mesa 24.0.5-1ubuntu1 (LLVM 17.0.6)
- Window Manager and Version: GNOME Shell
- Source mpv: apt install mpv
- Introduced in version:

### Reproduction Steps

sample file: https://github.com/serunis/hvc1_mpv_bugreport

It plays well with
ffplay -vcodec hevc_cuvid 20240710_121243.mp4
mpv --hwdec=nvdec ./20240710_121243.mp4 --profile=high-quality
mpv --hwdec=nvdec ./20240710_121243.mp4 --profile=fast

However it plays bad with
mpv --hwdec=nvdec ./20240710_121243.mp4 --profile=default

### Expected Behavior

the video plays with correct color.
![good_color](https://github.com/mpv-player/mpv/assets/53402902/e671f4b2-d7ce-4c9d-948a-1b4805a326a3)

### Actual Behavior

the video plays with strange color with --profile=default only
![bad_color](https://github.com/mpv-player/mpv/assets/53402902/89e2c57f-6cbd-4c9f-afcf-981bceaf6f86)

### Log File

[output.txt](https://github.com/user-attachments/files/16156813/output.txt)

### Sample Files

[20240710_121243.mp4](https://github.com/serunis/hvc1_mpv_bugreport/raw/main/20240710_121243.mp4)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by hooke007** [comment] 2024-07-10 08:11
https://github.com/mpv-player/mpv/issues/8223

@na-na-hi Did your PR fix it in vo_gpu? https://github.com/mpv-player/mpv/pull/13619

**Comment by kasper93** [comment] 2024-07-10 14:07
Duplicate of https://github.com/mpv-player/mpv/issues/8223

**Closed by kasper93** 2024-07-10 14:07 UTC
Labels: os:linux
