### ISSUE TITLE
vo_gpu-next: the peak detection of `hdr-compute-peak` causes unnaturally scene brightness changes

### ISSUE THREAD

**Issue by dyphire** [mpv-player/mpv#11412] opened 2023-03-06 02:32 UTC
### Important Information

Provide following Information:
- mpv version
https://github.com/mpv-player/mpv/commit/22e326465251a8324c138b0570217dd68ec57184
- Windows Version
Windows11 22H2
- Source of the mpv binary
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230306
- If known which version of mpv introduced the problem
https://github.com/haasn/libplacebo/commit/5c9575e5c54a219545cb2ce7dabb97b77bd1597d + https://github.com/haasn/libplacebo/commit/f61d10941402a47a334e690465809d554a7758e6
- Possible screenshot or video of visual glitches

### Reproduction steps

use `--no-config --vo=gpu-next --hdr-compute-peak` to playing HDR video.

### Expected behavior

The player should play video as usual when use peak detection.

### Actual behavior

https://github.com/haasn/libplacebo/commit/5c9575e5c54a219545cb2ce7dabb97b77bd1597d + https://github.com/haasn/libplacebo/commit/f61d10941402a47a334e690465809d554a7758e6 breaks the normal behavior. Now the scene brightness will flicker unnaturally when playing HDR video.

https://user-images.githubusercontent.com/61936050/223006102-516230d4-1409-4c8a-995c-5732bef44a89.mp4

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/10893785/mpv.log)

### Sample files

test video:  [The.Meg-test.zip](https://github.com/mpv-player/mpv/files/10891891/The.Meg-test.zip)

**Comment by haasn** [comment] 2023-03-06 12:42
I think this might be caused by 5c9575e5c54a219545cb2ce7dabb97b77bd1597d ?

**Comment by dyphire** [comment] 2023-03-06 13:25
> I think this might be caused by [haasn/libplacebo@5c9575e](https://github.com/haasn/libplacebo/commit/5c9575e5c54a219545cb2ce7dabb97b77bd1597d) + [haasn/libplacebo@f61d109](https://github.com/haasn/libplacebo/commit/f61d10941402a47a334e690465809d554a7758e6)

You are right. Bulid with  https://github.com/haasn/libplacebo/commit/995b0633327a6e636ed5bfe8b59b95acbc231e8f can work normally.
I have updated the description of the issue.

**Comment by haasn** [comment] 2023-03-08 17:22
Should be fixed by https://github.com/haasn/libplacebo/commit/7d685eb2e938279f749fc05a24f996e9b1941cf0 ? Can you confirm?

See also https://code.videolan.org/videolan/libplacebo/-/commits/histogram_v2

**Comment by dyphire** [comment] 2023-03-08 17:26
> Should be fixed by [haasn/libplacebo@7d685eb](https://github.com/haasn/libplacebo/commit/7d685eb2e938279f749fc05a24f996e9b1941cf0) ? Can you confirm?

Yes, In my last test, I found that it seems to fix this issue and expose another.

**Closed** 2023-03-08 18:18 UTC
Labels: os:win
