### ISSUE TITLE
Changing `vo` property does not reinit VO

### ISSUE THREAD

**Issue by haasn** [mpv-player/mpv#4755] opened 2017-08-13 01:37 UTC
### mpv version and platform

```
mpv 0.26.0-134-g7397e8ab4-dirty (C) 2000-2017 mpv/MPlayer/mplayer2 projects
```

### Reproduction steps

1. Bind `X cycle-values vo opengl null vdpau x11`

### Expected behavior

Pressing key cycles through VOs.

### Actual behavior

Pressing key does seemingly nothing.

### Log file

https://0x0.st/dnV.txt

### Notes

Changing a VO at runtime isn't the problem, the problem is that the VO never gets reinitialized. You can sort of work around it by doing this (to force VO reinit):

```
X cycle-values vo opengl null vdpau x11 ; cycle video ; cycle video
```

**Comment by wm4** [comment] 2017-08-14 10:28
Is this important? I mean, sure, we could recreate the VO in code if the vo option is changed...

**Comment by wm4** [comment] 2017-08-14 12:16
Looked at it... looks too annoying, and the use case is at best questionable and dumb (and you're probably asking for someone else), so I won't implement it.

**Comment by lachs0r** [comment] 2017-12-09 02:18
Duplicate of #4239

**Closed by lachs0r** 2017-12-09 02:18 UTC
Labels: feature request, low priority
