### ISSUE TITLE
mp.observe_property() causes "Illegal instruction: 4" in macOS

### ISSUE THREAD

**Issue by DervishD** [mpv-player/mpv#6489] opened 2019-02-11 11:09 UTC
### mpv version and platform

mpv 0.29.1 built on Fri Oct  5 00:01:23 CEST 2018
ffmpeg library versions:
  libavutil  56.14.100
  libavcodec  56.14.100
  libavformat  56.14.100
  libswscale  5.1.100
  libavfilter  7.16.100
  libswresample  3.1.100
ffmpeg version: 4.0.2

macOS Mojave 10.14.3

### Reproduction steps

1. Use an empty `$HOME/.config/mpv` directory, so the default configuration is used. It happens with my personal configuration too, but this way the logs are cleaner.
2. Create `$HOME/.config/mpv/scripts` directory
3. Put `pause-when-minimize.lua` in `$HOME/.config/mpv/scripts`, even though the problem arises with just a simple LUA script containing any `mp.observe_property()` call.
4. Launch mpv with any video (I've tested many of them, with various formats), by hand, from a terminal window.

### Expected behavior

The video should start playing and it should pause automatically when the window is minimized.

### Actual behavior

The video doesn't even start playing, mpv crashes with `Illegal instruction: 4` error.

### Log file

Here you have it, at [null pointer](https://0x0.st/zzBw.txt).

### Sample files

I'm using the github version of the LUA script, which you can find [here](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/pause-when-minimize.lua).

### Thanks a lot in advance and feel free to ask me for any other information you may need.

**Comment by deus0ww** [comment] 2019-02-11 12:57
I have the same problem with mp.observe_property('window-minimized'....). Opening a file while MPV is not running causes immediate crash. Opening a file while MPV is already running doesn't crash but the script also doesn't work.

Script: https://github.com/deus0ww/mpv-conf/blob/master/scripts/Mac_Integration.lua (the part that's commented out).

**Comment by deus0ww** [comment] 2019-02-11 14:09
Behavior of mp.observe_property('window-minimized', 'native', function(_, minimized)....

With vo=libmpv
- If MPV was already running:
  - doesn't crash
  - doesn't work (doesn't trigger at all)
- If MPV was not running
  - crash on launch

With vo=gpu
- Working as expected

**Comment by DervishD** [comment] 2019-02-11 14:09
Thanks, @deus0ww, for confirming. I have to repeat all my tests, then, because when I did them I could reproduce the problem with any property, not only with `window-minimized`. Anyway, it crashes with that property anyway, so...

**Comment by DervishD** [comment] 2019-02-11 14:18
> Behavior of mp.observe_property('window-minimized', 'native', function(_, minimized)....
> 
> With vo=libmpv
> 
> * If MPV was already running:
>   
>   * doesn't crash
>   * doesn't work (doesn't trigger at all)
> * If MPV was not running
>   
>   * crash on launch
> 
> With vo=gpu
> 
> * Working as expected

@deus0ww I just tested this and I can confirm it on a MacBook Air (2014) running Mojave.

**Comment by Akemi** [comment] 2019-02-11 18:35
#6491 will fix the minimising bug and also properly reports the window state now. i can only reproduce the this crash with the 'window-minimized' property. if any other properties are affected too please let me know, since from a quick test only that one property was a problem.

**Comment by DervishD** [comment] 2019-02-11 18:47
> #6491 will fix the minimising bug and also properly reports the window state now. i can only reproduce the this crash with the 'window-minimized' property. if any other properties are affected too please let me know, since from a quick test only that one property was a problem.

@Akemi, I repeated some of the tests I originally made and, so far, the only property causing the problem is `window-minimized` 🤷‍♂️ I don't know why others failed before, maybe the reason why only this one fails now is that I updated macOS yesterday, who knows.

If any other property fails for me I'll report it.

And thanks **A LOT** for the fix!!!

**Comment by deus0ww** [comment] 2019-02-11 20:05
I can confirm that the PR fixes this. Thank you, @Akemi!

**Comment by Forcer78** [comment] 2019-03-29 20:56
I'm still seeing "Illegal instruction: 4" crashes after applying the PR. In my case, I have a Lua script that removes images from the current playlist (since mpv started playing images at some point and I can't get it to stop, which is a pain when playing albums with cover art files). When an image comes up in the playlist and gets skipped, the next file will cause the crash.

This zip contains a jpg, an mp3, and the image.lua script: https://0x0.st/zPHm.zip
Add image.lua to mpv's scripts and then play the jpg and mp3 in order.
Log: https://0x0.st/zPHB.txt
Crash: https://0x0.st/zPHu.crash

This appears separate from https://github.com/mpv-player/mpv/issues/6191. Both types of crash disappeared for months after I recompiled with `--disable-swift`, but came back immediately when I recently removed that flag.

**Comment by Akemi** [comment] 2019-03-29 21:32
that is a separate issue and not related to this one, hence why it's not fixed by that PR. though the explanation here and on the PR should make that quite clear.

i am going to state the obvious. that crash is within the swift parts, hence why it won't crash without swift. i can reproduce that crash and will fix it.

**Comment by Akemi** [comment] 2019-03-30 20:41
@Forcer78 your problem will be fixed with PR #6595.

**Closed** 2019-04-01 22:51 UTC
Labels: osx

**Comment by valdotdev** [comment] 2019-04-15 16:40
After re-building, it seams `no-border` also triggers the error. Removed the setting on mine for now.

**Comment by Akemi** [comment] 2019-04-15 17:55
fixed with #6595. all those errors are fixed for good with that PR.

**Comment by valdotdev** [comment] 2019-04-16 08:34
Thanks!
