### ISSUE TITLE
MPV fails to start in gnome wayland session using Archlinux

### ISSUE THREAD

**Issue by Xenphor** [mpv-player/mpv#2136] opened 2015-07-14 01:03 UTC
Here is the log:

http://pastebin.com/aUjv6m1Q
short version:

    $ mpv Taylor\ Swift\ -\ Bad\ Blood\ ft.\ Kendrick\ Lamar-QcIy9NiNbmo.mkv 
    Playing: Taylor Swift - Bad Blood ft. Kendrick Lamar-QcIy9NiNbmo.mkv
     (+) Video --vid=1 (vp9)
     (+) Audio --aid=1 (*) (aac)
    wl_surface@3: error 0: Cannot commit a NULL buffer to an xdg_surface
    Using software decoding.
    [vo/opengl/wayland] error occurred on the display fd: closing file descriptor
    AO: [pulse] 44100Hz stereo 2ch float

Using vo=opengl hwdec=vaapi

**Comment by wm4** [comment] 2015-07-18 12:17
No idea. Something strange fails at an unknown location?

> hwdec=vaapi

This won't work at all on Wayland.

**Comment by kasei-wang** [comment] 2015-08-21 12:36
hey, try "--vo=x11".
It works on my Archlinux.

**Comment by rickysarraf** [comment] 2015-08-31 10:11
Yes. -vo=x11 works. But is wayland as a '-vo' supported ?

**Comment by ricardomv** [comment] 2015-10-19 14:59
I think this is fixed in 3.18.2 at least i don't have this issue anymore.

**Comment by giselher** [comment] 2016-02-07 14:56
Can't reproduce this issue. Is there any new information?

**Comment by Manouchehri** [comment] 2016-02-09 00:38
Using `-vo wayland` was working for me several months ago, haven't been able to reproduce this in Wayland.

**Comment by giselher** [comment] 2016-02-09 06:35
I am closing this issue, feel free to reopen it again if it still happens.

**Closed by giselher** 2016-02-09 06:35 UTC
Labels: info-needed, stalled, wayland
