### ISSUE TITLE
code of conduct in the multi-cultural user base - non-violent communication

### ISSUE THREAD

**Issue by PurryPlatypus** [mpv-player/mpv#13109] opened 2023-12-15 20:16 UTC
How do i start; i think, i should leave the template intact, annotate in-line, and append the actual focus of discussion at the end, see also below the logfile.

Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection. **check, done**

This template is meant for questions about the workings of mpv, to clarify about
unspecified behavior of options or command, _or anything else that is not well
described and needs clarification_.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion **checks out - no results for the provided link + the keywords _code of conduct_**

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt,
attach it to the issue, and replace this text with a link to it. 
**done** [output.txt](https://github.com/mpv-player/mpv/files/13689040/output.txt)

### here we go

I'd like to insist that this here issue is not meant as a continuation of a previously deemed **"too heated"** discussion. I'm quite new to the contributing to FOSS/FLOSS projects thing - so, if you dare to call it that, i'm _not quite broken in_, yet. Since the project Wiki, as well as the FAQ, and an additional search for "code of conduct" didn't yield useful results, I intent to establish a **code of conduct** by which no-one will have to endure an abrupt shut-down of their contribution attempts.

I've heard about "non-violent communication" and communication theory in general, which should be useful for everyone. In short; there's a sender and a recipient - one intends to send meaning, via their personal POV, kind of "encoding" the meaning into a public message, and the multi-coloured recipients (in this here scenario) try their best to translate _that intended meaning_ back into their _own POV / frame of reference_ - everyone has a _rather unique internal model of reality_ - i acknowledge this scientific fact. I'm by no means a communications expert, myself - my skills certainly require some honing. I'd like to leave these keywords here, for peaceful on-topic consideration.

I'm humbly asking, to take the issue #13082 as a case study - or any other **"too heated"** discussion - as an example.

How should we communicate with each other, in order to not unintentionally "slap someone in the face"?

**Comment by llyyr** [comment] 2023-12-15 20:43
Hi, I'm not really part of the mpv org so I can't speak on their behalf but I do contribute sometimes so I might be able to respond to this and the previous issue.

First of all, "too heated" is just the text that Github shows when an issue is locked for any reason. [[1](https://docs.github.com/en/communities/moderating-comments-and-conversations/locking-conversations)]
Based on previous history with such tickets, they have a high likelihood of onlooker trolling, which is why it was locked from what I can tell.

mpv does have a Code of Conduct that you can find in [DOCS/contribute.md](https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md#code-of-conduct).

As far as #13082 goes, I don't believe the Santa hat represents any religion but that's beside the point. mpv isn't opposed to other festive icons being added to the osc, including the santa hat, given someone cares enough about it to send a PR. mpv is the product of the culture that builds it, not the other way around. There just happen to be mpv users who care enough about the Santa hat to add it to mpv. mpv also has a ton of Chinese users and plenty of mpv's users are anime enjoyers, so if any of them wanted to add a logo for the Lunar New Year or anime icons, they would be welcome too.

There is no exclusion here, if a particular festive logo isn't there it just means that people who care about it just don't care enough about mpv to add it. I don't think a PR adding more festive logos for the osc idle screen would be rejected.

**Comment by PurryPlatypus** [comment] 2023-12-15 21:16
> mpv does have a Code of Conduct that you can find in [DOCS/contribute.md](https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md#code-of-conduct).

Thank you! Turns out, there is an established code of conduct - mildly occluded by the project structure: https://www.contributor-covenant.org/version/2/0/code_of_conduct/

I'll have to read this tomorrow - it's late here (local time). Please keep this issue open, until i had a chance to summarise what i might've done wrong - i'd like to do that. Meanwhile, please keep posting your thoughts - i intended this issue to be a calm learning experience, for me, and for the inclined reader. (I won't judge anyone else's behaviour [publicly] - that's for their consideration.)

**Comment by N-R-K** [comment] 2023-12-16 08:46
> I'm quite new to FOSS/FLOSS projects

Issue trackers are *mainly* meant for submitting bug reports and/or feature request. It's not a place for conducting "scientific experiment on <buzzword> communication" or whatever on earth you're trying to do in here. If you're trying to improve your social skills, then an issue tracker for a media player is certainly not the place for it.

> no-one will have to endure an abrupt shut-down of their contribution attempts.

If you want to contribute send a pull request fixing a bug or adding a feature that's been requested in the tracker (and not disapproved by any of the devs).

Opening an issue that's already been shut down multiple times before (talking about https://github.com/mpv-player/mpv/issues/13082) is not contributing anything, it's wasting time at best and annoying nagging at worse. Only thing that was shut down there was further waste of time. Which is the proper course of action for *this* issue as well.

**Comment by haasn** [comment] 2023-12-16 11:36
> If you want to contribute send a pull request fixing a bug or adding a feature

Fixed

**Comment by mia-0** [comment] 2023-12-16 13:10
So, my take on this, since it’s been on my mind…

One fundamental property of free software is that it takes shape through the people who build it. Conflict often arises when a vision of what it should and shouldn’t be is imposed on it—by project leaders, by people waging culture wars, by financial incentives…
#13082 imposes such a vision, not only making demands of programmers to make changes and additions to the code in a purely practical sense, but more crucially dictating cultural values to follow and in a wider sense how the project should understand itself and how it is to be operated and governed in order to meet these demands.

In an attempt to neutralize the source of this conflict (seeing as its resolution seemed impractical to say the least), I removed the accursed hat (which was intended not as a symbol of religious commemoration but as a fun, cute gimmick to make people smile). But even if it was done out of mere avoidance, not taking either “side” of the argument, this also was seen as a forceful intervention. I imposed my idea of where fun and playfulness are outweighed by the potential to provoke external hostility, and disregarded what that meant for people who enjoyed building something they like through free creative synthesis; who had put time and effort into something only to see it thrown out and declared harmful at a moment’s notice.

mpv itself, as mplayer-uau before it, is the result of irreconcilable conflict between contributors and the visions of people who reigned over the code, sometimes more or less as uncompromising gatekeepers. And mpv has already seen multiple incidents of that past threatening to repeat itself. The hat issue might appear rather insignificant, but it has the potential to set a precedent with far-reaching consequences for the future of the project.

So yeah, this is one of those cases where I believe “contributions welcome” is an appropriate response. If you want to make a difference here, you’ll have to be part of the change.

**Comment by qeeg** [comment] 2023-12-16 17:53
As an antitheist person who was raised by a pagan and an atheist, who has ALWAYS celebrated Christmas as a simple gift-giving holiday, with absolutely nothing religious about it, you're overreacting. There are TONS of atheists who celebrate Christmas in a completely non-religious way. Hell, a TON of American Christians celebrate Christmas without much religion in it too! Santa is NOT a religious figure, and hasn't been for literally a century of more. Fuck off with your high horse mate.

**Comment by CardealRusso** [comment] 2023-12-16 17:56
cringe

**Comment by paulguy** [comment] 2023-12-16 21:29
Could it be possible for external scripts to change/modify the existing icon in the way the santa hat is added? :p  Someone making a bunch of festive, with some maybe being time-sensitive icons/additions to the icon that can be optionally dropped in to the scripts directory would be fun.  Obviously this doesn't have to be any sort of official thing, just some third party thing that's maybe linked to from the wiki.

**Comment by TheAMM** [comment] 2023-12-17 00:18
Having osc.lua check the userdata property for a custom logo (or headwear) would be fairly trivial, yeah. Add a userscript to manage a directory of logos and probabilities, and get all the flavour you would want. As long as people are able to procure the ASS vector commands.

[![2023-12-13_21-22-51](https://github.com/mpv-player/mpv/assets/6820963/221a4aba-ac5c-47e6-bebd-e956d7c2d02e)](https://github.com/mpv-player/mpv/commit/584a2467baa673a15f589ac40358910a8cae827b)

**Comment by Dungeonseeker** [comment] 2023-12-25 12:38
Before I begin, I'm not a contributor or associate to this project, my comments are my own.....

@PurryPlatypus If you're trolling, go fuck yourself, if you're serious, also go fuck yourself. My message is pretty clear, fuck off somewhere else and waste someone elses time.

**Comment by exalented** [comment] 2023-12-26 09:44
Fork the project if you have a problem with mpv's logo. It's a non issue for the majority of it's user base.

**Comment by BurnyBoi** [comment] 2023-12-27 16:57
"I created a duplicate of an already-closed issue to make the same already-rejected argument again instead of forking the project so that I can feel better knowing I forced it on everyone else"

**Comment by joshqou** [comment] 2023-12-27 17:10
Open source projects are not the place to test your college thesis. Kindly go somewhere else

**Comment by paulguy** [comment] 2023-12-27 17:15
It's a shame brodie robertson had to cause this to flare up and some of his mouth breathing audience had to turn this absolute molehill that had resolved and nobody cared about in to some silly crusade.

**Comment by Dungeonseeker** [comment] 2023-12-27 18:01
> It's a shame brodie robertson had to cause this to flare up and some of his mouth breathing audience had to turn this absolute molehill that had resolved and nobody cared about in to some silly crusade.

Perhaps us mouthbreathers are sick of people pushing politics, ideology and "the message" onto things that don't need it, never asked for it and have better things to worry about than snowflakes who get triggered by everything. 

I swear to god, the world is getting more and more insane by the day.

**Comment by paulguy** [comment] 2023-12-27 18:32
Considering nothing came of the original post which isn't clear whether it was even serious or not, it's sounding to me like reactionary people are making something more "political' than it is out of some like, desire to keep the world intolerant (since yeah there are plenty of legitimate arguments to be made with respect to people just having issues with people for innocent things), but in this case, nobody's even talking about tolerance, it's just people being weird and reactionary to something they perceive as some threat.  There's nothing productive to be done further in response to this.

**Comment by MimaHakurei** [comment] 2023-12-27 19:15
Considering that the poster is a brand-new account with no actual commit-history whatsoever... and claims that something as secular as the modern-day Santa hat 🎅🏻 is a "Christian" symbol somehow....

Can we just close the issue and treat it like the spam it is?

**Closed** 2023-12-27 19:33 UTC
Labels: meta:question
