### ISSUE TITLE
Tearing when fullscreen with Intel GPUs on Windows

### ISSUE THREAD

**Issue by bodayw** [mpv-player/mpv#2913] opened 2016-03-07 19:25 UTC
I'm aware that in issues #2736 #2893 people mentioned "horizontal lines", not sure if that is related. Also @rossy said in #2451 he had tearing when in fullscreen, but I don't see it being discussed in detail, thus I opened this one.

With several of the latest Windows builds, namely since 2015-11-10, I can see very severe screen tearing when in fullscreen, but doesn't happen in windowed mode. Build 2015-10-29 seems fine.

The issue happens with both `vo=opengl` and `opengl-hq`. And I can reproduce the issue on both of my Windows machine, with either HD 5500 and HD 4600. But if I set mpv to use the discrete 970m on the HD 4600 machine, there is no screen tearing. Both machine are running Windows 10 with latest patches.

Another (weird) observation is that on the machine with HD 5500, I do NOT see screen tearing when I put mpv windowed/fullscreen on the external monitor, which is a 2560x1440 screen connected via DP. It only happens when fullscreen on the built-in display (it's a laptop).

A brief log file attached here, with the latest build when having screen tearing: https://dl.dropboxusercontent.com/u/3988935/mpv-log-20160307.txt

**Comment by rossy** [comment] 2016-03-07 22:53
It sounds a lot like the fullscreen exclusive mode detection added in b7d614a is not working, possibly due to Windows 10 updates.

Try ``--vo=opengl:dwmflush=windowed``

**Comment by kevmitch** [comment] 2016-03-07 23:03
I have also seen this in Win10 HD4000 with current drivers, but only with ```opengl:backend=win```. Neither ```opengl:backend=angle``` nor ```opengl:backend=dxinterop```  have any tearing issues.

**Comment by bodayw** [comment] 2016-03-07 23:12
>Try --vo=opengl:dwmflush=windowed

Thanks! It fixes the issue.

>Neither opengl:backend=angle nor opengl:backend=dxinterop have any tearing issues.

I don't set the backend in the config file so it should be using `win` as well. I haven't tested `angle`, though it's removed from the last build anyway...

But `dxinterop` should be irrelevant here as it doesn't work with Intel GPUs, right?

**Comment by rossy** [comment] 2016-03-07 23:17
> But dxinterop should be irrelevant here as it doesn't work with Intel GPUs, right?

I think Intel has fixed their drivers, so it might work now. Some of their driver releases are outdated, but I don't think you'll have any trouble with Windows 10 and a HD4000. The easiest way to tell if it's working is to resize the window. The buggy Intel drivers crash randomly when the window changes size, so resizing with the mouse should crash it pretty quickly if your drivers are affected.

**Comment by bodayw** [comment] 2016-03-07 23:23
>I think Intel has fixed their drivers, so it might work now. 

Confirmed. Just tried `backend=dxinterop` without `dwmflush=windowed`, no screen tearing, and no crashing when resizing the window.

**Comment by rossy** [comment] 2016-03-07 23:33
Great. ``backend=dxinterop`` is probably the best backend to use, as long as it works (it has better v-sync timing.)

If this tearing issue is common with ``backend=win``, it might be time to change the default ``dwmflush`` setting again (to 'windowed'?)

**Comment by mxalbert1996** [comment] 2016-03-08 07:39
Have the same issue on Windows 10 with HD4600. No problem when adding `backend=dxinterop`.

**Comment by kevmitch** [comment] 2016-03-08 08:21
I should add that ```--vo=opengl:backend=win:dwmflush=windowed``` eliminates tearing here too.

Also, as noted in [#2685](https://github.com/mpv-player/mpv/issues/2685#issuecomment-177566321), adding ```glfinish``` seems to help a lot with frame timings for ```backend=win``` on AMD, which I can confirm here on intel.

**Comment by bodayw** [comment] 2016-03-08 20:45
>Also, as noted in #2685, adding glfinish seems to help a lot with frame timings for backend=win on AMD, which I can confirm here on intel.

Thanks! I actually missed that part. I can also see a somewhat improvement on my Nvidia 970m...The Vsync jitter was not too bad without `glfinish` to begin with, as occasionally it could go up as high as 0.100.

**Comment by Hrxn** [comment] 2016-03-09 08:45
This sounds like always using `glfinish` together with `backend=win` is a good idea, if it works at all, I assume:
https://mpv.io/manual/master/#video-output-drivers-glfinish

BTW, the default for `dwmflush` (`auto`), basically results in using `yes`, as long as no Windows settings has been tampered with and drivers are working correctly etc. , right?

https://mpv.io/manual/master/#video-output-drivers-dwmflush

**Comment by DiddyKode** [comment] 2016-03-11 22:53
I just want to say that using `backend=dxinterop` fixed the tearing using a hd5500 for me too.

Thanks!

**Comment by wm4** [comment] 2016-04-03 17:56
Guess I'll  close this.

**Closed by wm4** 2016-04-03 17:56 UTC
Labels: ms-windows
