### ISSUE TITLE
[Windows] Volume Multimedia Keys Should Be Ignored By Default

### ISSUE THREAD

**Issue by Awakened0** [mpv-player/mpv#2041] opened 2015-06-12 22:30 UTC
Currently when you press one of the volume related multimedia keys (VOLUME_UP, VOLUME_DOWN or MUTE), both mpv and the system wide volume are effected at the same time. This is rather unwieldy.

**Comment by nyuszika7h** [comment] 2015-06-15 10:24
This seems to be a regression. It only increased the system volume on an earlier build, sadly I'm not sure which one.

**Comment by wm4** [comment] 2015-06-15 19:46
Do you happen to know since when?

**Comment by Awakened0** [comment] 2015-06-15 20:55
lachs0r's build page shows "add mappings for some multimedia keys" on the notable changes page for the 2015-05-31 build. That's the first build with this problem. So it must be a commit made between 05-05 and 05-31.

Probably this commit: fc9695e63b5baa1a478acb8e79c038571ee0e9b3

**Comment by wm4** [comment] 2015-06-20 11:50
Is there some program (preferably preinstalled) that grabs global media key shortcuts, so I can test this?

**Comment by wm4** [comment] 2015-06-20 12:43
Now I've tried with mpc-hc. It seems to grab the global key. If I press the pause/play key on the keyboard, mpc-hc toggles pause even if mpv is focused. If I terminate mpc-hc, mpv gets the key.

Closing as invalid.

**Closed by wm4** 2015-06-20 12:43 UTC
Labels: ms-windows

**Comment by kevmitch** [comment] 2015-06-21 01:07
I don't understand why this is invalid. Because whatever is controlling the system volume is supposed to trap the key and not pass it on? What is controlling the system volume via this key? If it is windows itself is this still invalid?

**Comment by wm4** [comment] 2015-06-21 16:52
For me, the system always grabs the volume keys, unless I kill the process which grabs them.

**Comment by Awakened0** [comment] 2015-06-21 18:58
I don't understand why you'd want both mpv's and the system volume to be changed by pressing the volume keys. It frustrated me when mpc used to do that, so I had to figure out how to disable it there too. But at some point they stopped defaulting to having the program's volume affected by those keys. At least in the build that comes with CCCP.

I think just having the 9 and 0 keys for changing mpv's volume and leaving the volume keys for system volume is a better default.

**Comment by kevmitch** [comment] 2015-06-21 22:21
> I don't understand why you'd want both mpv's and the system volume to be changed by pressing the volume keys.

If I understand correctly, wm4 is saying that when windows traps this key to change the system volume, it doesn't pass the key on to mpv. I can't test this myself since I don't have this key on my windows machine.

In your case, do you have something other than windows itself controlling the system volume (like OEM crapware?), or maybe there's a difference between versions of Windows.

**Comment by Awakened0** [comment] 2015-06-21 22:47
No, I don't have anything installed like that; I'm running a clean Windows 7 64-bit system. If I have mpv as the active window or fullscreen and press those keys, Window's volume mixer and mpv's volume both change. If I have mpv windowed and click on the taskbar, hitting those keys only changes Window's volume.

**Comment by MammothJerk** [comment] 2015-06-28 00:14
i have the same problem

it seems stupid to have the volume keys effect both windows AND mpv when you could just change the volume for mpv with 9 and 0

**Comment by Awakened0** [comment] 2015-06-28 03:14
You can change the volume keys to be ignored by creating an input.conf text file in the mpv folder where mpv.exe is (or Appdata\Roaming\mpv) and adding these lines to it:

VOLUME_UP ignore
VOLUME_DOWN ignore
