### ISSUE TITLE
Add the option to let users decide which stats will be saved or restored

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#8578] opened 2021-02-18 12:52 UTC
### Expected behavior of the wanted feature
The description of "--save-position-on-quit" make me confused. Actually it saves extra stats (vf, glsl, etc.), which make it like the function "watch_later".
I want the feature that users can choose which stats will be saved.
### Alternative behavior of the wanted feature
`--save-current-playback-time-only` ??
### Log file
It is really unnecessary.

**Comment by Akemi** [comment] 2021-02-18 13:20
duplicate of #4641

see also PRs that didn't lead to something we marged in the end. #6373 #6541 #8213

**Closed by Akemi** 2021-02-18 13:20 UTC
Labels: meta:feature-request

**Comment by butterw** [comment] 2021-02-22 17:01
quit-watch-later or --save-position-on-quit 
save vf but do not save the glsl-shaders config.

+1 to have the option to select what should be saved in addition to position.

**Comment by butterw** [comment] 2023-08-19 09:41
https://mpv.io/manual/stable/#watch-later
To add glsl-shaders to the watch_later save:
`--watch-later-options-append=glsl-shaders`

--watch-later-options            String list (default: `start,osd-level,speed,edition,pause,volume,mute,audio-delay,fullscreen,ontop,border,gamma,brightness,contrast,saturation,hue,deinterlace,vf,af,panscan,aid,vid,sid,sub-delay,sub-speed,sub-pos,sub-visibility,sub-scale,sub-use-margins,sub-ass-force-margins,sub-ass-vsfilter-aspect-compat,sub-ass-override,ab-loop-a,ab-loop-b,video-aspect-override`)
