### ISSUE TITLE
Window resize has a max limit?

### ISSUE THREAD

**Issue by d3x0r** [mpv-player/mpv#7426] opened 2020-02-02 16:12 UTC
### Important Information

Provide following Information:
- mpv version  : 1.0.32.0-1
- Linux Distribution and Version : Arch Latest (updated last night)
- Source of the mpv binary : prebuilt image from Arch package manager
- If known which version of mpv introduced the problem : Unknown
- Window Manager and version : weston/KWin/Plasma (all latest available)
- GPU driver and version : amdgpu
- Possible screenshot or video of visual glitches : n/a

### Reproduction steps

Start playing a video.  The window starts at the size of the video; I have 2 4k monitors, and most videos I get are like 360p... so I usually resize the window.  Grabbing the title bar towards the top of the window allows me to resize the window, however, once I reach about 2x the size of the current (unsized) window, the sizing stops, and snaps back to the starting size.  So to stretch most videos to a confortable size I have to click, drag bigger, move the mouse back a bit since I will inevitably stretch it larger than 2x to start, and eventually let go, and have to reclick the sizing and stretch it again... depending on how close to 2x I got in the irst place I can usally get a good display size, but often I only get to like 1.5x, so the second resize will still end up moving bigger than 2x the new size and have to re-adjust the mouse back to where it is resizing...

### Expected behavior

As long as the mouse is clicked and held, the resizing should work, without some sort of limit .

and basically all the resizes should be greater then the prior...

```
[  15.922][v][vo/gpu/wayland] Resizing due to xdg from 1841x1036 to 1838x1034
```

### Actual behavior

I don't see anything in the log about why the size drops back immediately to the small size.

```
[  16.169][v][vo/gpu/wayland] Resizing due to xdg from 1838x1034 to 1848x1040
[  16.177][v][vo/gpu/wayland] Resizing due to xdg from 1848x1040 to 1045x587

```

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/4144609/mpv.log)

### Sample files

I don't know that any specific video is required; it happens on all that I have; it might require a monitor big enough to stretch videos a couple times...

**Comment by Dudemanguy** [comment] 2020-02-02 16:30
I can't reproduce here (wayland/waylandvk with weston or sway) on my 4k monitor. Some blind guesses, but maybe check a few things real quick.

* Does it happen if you only have one monitor plugged in?
* Does it happen in vulkan?
* Does it happen in xorg?

**Comment by d3x0r** [comment] 2020-02-02 17:08
> I can't reproduce here (wayland/waylandvk with weston or sway) on my 4k monitor. Some blind guesses, but maybe check a few things real quick.
> 
> * Does it happen if you only have one monitor plugged in?

> * Does it happen in vulkan?
does do it with `-vo=wlshm`  [mpv.log](https://github.com/mpv-player/mpv/files/4144761/mpv.log)
```
[vo/wlshm/wayland] Resizing due to xdg from 1121x631 to 1130x636


```
am not sure how to enable vulkan ... `--gpu-api=vulkan` wouldn't seem to be an output

does NOT do it with `--vo=x11`
[mpv.log](https://github.com/mpv-player/mpv/files/4144759/mpv.log)

> * Does it happen in xorg?
I can't get xorg to start...

**Comment by Dudemanguy** [comment] 2020-02-02 18:15
On Arch you'll need `vulkan-radeon` installed for the vulkan context. Although I guess judging that it happens in `wlshm` (totally forgot about that; thanks for testing that one), I assume you'll probably have the same issue there.

>I can't get xorg to start...
You try it with xwayland (`--gpu-context=x11egl`). That should work unless you went out of your way to remove xorg completely (unlikely). Anyways, it's almost certainly a wayland issue on our end. Going to assume this has something to do with multimonitor although I don't remember this happening when I tested it way back when.

**Comment by bitraid** [comment] 2020-02-02 18:35
I've noticed that on wayland/sway (but not on xwayland), when a floating mpv window is resized with <kbd>Alt</kbd>-<kbd>0</kbd>, switching to another window resets the mpv window size.
There are also problems with with rotate and autofit: see https://github.com/swaywm/sway/issues/4094, which should be the same root cause as #6653, but it's not fixed by #6978.

**Comment by d3x0r** [comment] 2020-02-02 23:27
`--gpu-context=x11egl` does not have issues resizing.

**Comment by wm4** [comment] 2020-02-02 23:47
Sounds more like Wayland vs. x11?

**Comment by Dudemanguy** [comment] 2020-02-03 01:39
Yeah don't worry about vulkan. That's a totally separate thing.

Does this happen to you in single monitor Weston? I've definitely resized just fine in Plasma before.

**Comment by d3x0r** [comment] 2020-02-03 05:47
Yes, starting weston with a single monitor behaves the same way (dropping the resize drag)

**Comment by Dudemanguy** [comment] 2020-02-03 15:32
I can't reproduce it here. In one go, I can resize a video to much larger than 2x the size. No idea how this is happening to you.

**Comment by Dudemanguy** [comment] 2020-02-03 20:48
Try #7432? I don't think it will fix this issue, but maybe we got lucky.

**Comment by bitraid** [comment] 2020-02-04 11:27
> Try #7432? I don't think it will fix this issue, but maybe we got lucky.

For me, it didn't fix `window-scale`, either. Using `sway version 1.4-ffbf10d0 (Jan 31 2020, branch 'master')`

**Comment by Dudemanguy** [comment] 2020-02-04 18:01
Hmm, it looks like `VO_EVENT_RESIZE` doesn't send a configure event to the compositor for some reason. That might be the source of the problem.

**Comment by Dudemanguy** [comment] 2020-02-05 19:12
Ah, I had misunderstood how xdg_configure.toplevel was supposed to work. The compositor isn't supposed to send a configure event there. Okay, I know the right way to do this now.

**Comment by Dudemanguy** [comment] 2020-02-06 02:53
Okay, I updated #7432. I think that should fix `window-scale` as well as some other annoying window resize things I stumbled upon. Still not sure if this fixes @d3x0r's issue or not, but assuming everything else is good, I'll merge it.

**Comment by bitraid** [comment] 2020-02-06 08:38
`window-scale` fixed!
Any idea why `add video-rotate` causes problems when `autofit`/`autofit-larger` is set?

**Comment by Dudemanguy** [comment] 2020-02-06 16:17
Not sure what you mean. I just tried it and it seemed fine. Open up a new issue for it though.

**Comment by d3x0r** [comment] 2020-02-07 03:20
Sorry I haven't been able to test it until now. I see that the changes have been merged, and I just built mpv head and it still does the same thing; would you like a log?  If you make a private forked sort of branch I can test from that also...

**Comment by Dudemanguy** [comment] 2020-02-07 04:44
Hmm well if you got the resizing issue to happen with another client, I'm starting to think something else is the issue here. Presumably, terminator doesn't do anything particularly complicated in terms of rendering and it does use vte3 which does have native wayland support.

Wild guess here but since you use a 4k monitor do you use fractional scaling on your compositor?

**Comment by d3x0r** [comment] 2020-02-07 04:48
Weston didn't have scaling from what I saw.  kWin defaults to 2x scaling, which I reset to 1.0

**Comment by Dudemanguy** [comment] 2020-02-07 05:02
I think somehow the compositor is returning very bad `width` and `height` arguments in the toplevel listener to mpv. There's scenarios where those values can be wrong, but they should be predictable for the most part. And certainly, it shouldn't randomly go back to a small size in the middle of a resize. mpv might just happen to be a particularly easy client for you to produce this bug since we're constantly drawing frames. As for why this happens, this is beyond me. Across multiple wayland clients in multiple compositors suggests something relatively low level unfortunately (driver or something).

**Comment by d3x0r** [comment] 2020-02-07 13:37
> 
> Edit: Is it easier or harder to reproduce the resize bug while the video is paused?

Pause/Play doesn't have any difference.

**Comment by Dudemanguy** [comment] 2020-02-12 19:02
@d3x0r: Does the problem still occur with #7457?

**Comment by d3x0r** [comment] 2020-02-13 00:08
Uhmm... that's a leading question.
It does not work better.  Now, when I grab the top of the window to resize, it just drags the window up in the same size.

**Comment by Dudemanguy** [comment] 2020-02-13 00:42
>Now, when I grab the top of the window to resize, it just drags the window up in the same size.

Oh yeah, this part on Plasma I can reproduce. It looks like the compositor doesn't let mpv resize that way. Not too concerned about that honestly since the current resizing logic sucks and Plasma is known to have some geometry issues anyway. The rest sounds pretty bad though. I didn't expect it to get worse. Mind uploading a full log?

**Comment by d3x0r** [comment] 2020-02-13 08:59
[mpv.log](https://github.com/mpv-player/mpv/files/4197323/mpv.log)

**Comment by Dudemanguy** [comment] 2020-02-13 16:25
>0x0

Yeah, something is somehow wrong with calculating the width/height coordinates for resizing. If you don't mind, could you test this [branch](https://github.com/Dudemanguy/mpv/tree/wayland-resize-test-branch) I just made? Just try to resize again, make a log file and upload it. All it does is log some extra stuff so we can hopefully catch why exactly it's making those values 0.

**Comment by d3x0r** [comment] 2020-02-13 16:28
[mpv.log](https://github.com/mpv-player/mpv/files/4199486/mpv.log)  (plasma)
sized by lower right first (no sizing)
sized by top which just moves it still..

**Comment by Dudemanguy** [comment] 2020-02-13 16:44
Thanks, that was quick. Actually, now I see the source of your problem here. I should have spotted it earlier.

>[cplayer] VO: [gpu] 640x360 => 641x360 yuv420p

This line is in some of your older logs too. 641 is a prime number. Trying to resize this while preserving the aspect ratio will have weird behavior no matter what you do (could you confirm that the `--no-keepaspect` option resizes normally?) You can't reduce the size of course and the next greater size would be exactly double.

Does every single video behave like that for you? If possible, could you upload a sample so I could confirm whether or not it's just a bad file.

**Comment by d3x0r** [comment] 2020-02-13 16:56
--no-keepaspect allows resizing in any way and doesnt' seem to drop the drag...

I'm going to go with 'Every' video behaves the same way... I haven't of course played every, but I never saw one behave differently.
https://d3x0r.org:444/temporary/Arrow.S08E10.AAC.MP4-Mobile.mp4 (161M)

**Comment by Dudemanguy** [comment] 2020-02-13 17:08
Thanks, I can confirm that this file is also broken for me. I'll try to figure out why the width is reported as 641 instead of 640.

**Closed** 2020-02-13 20:29 UTC
Labels: os:linux, vo:gpu:wayland
