### ISSUE TITLE
Command to reinitialize playback

### ISSUE THREAD

**Issue by ashinan** [mpv-player/mpv#1548] opened 2015-02-01 22:54 UTC
Options can be changed during playback but some options only can be  applied after new playback.

In my case, in order to apply bunch of option changes (such as pereferences items which can be found in lots of GUI applications), I stop and play same file with previous start offset.

However, this requires additional check in client  to distinguish restart from usual playback (for instance, autoloading subtitle/audio features should be applied to only new playback).

Well, the best is to make it possible to apply options during playback, but if it's not possible, I think a new command to reinitialize playback to apply changed options would be convenient enough to practical usage.

If reinitialization is enabled, I thinks there's two possibilities:
1. immitate reinitialization without notification of MPV_EVENT_*_FILEs: in this case, a new event to notify reinitialization is helpful.
2. accually reinitialize playback: in this case, new end_file_reason to notify reinitialization for MPV_EVENT_END_FILE data is needed.

**Comment by wm4** [comment] 2015-02-02 11:12
I'd prefer 2.

Also, what settings exactly do you want to change which isn't possible yet? Some will always require a reload, but I want to work towards making most changeable at runtime.

**Comment by xylosper** [comment] 2015-02-02 11:27
For instance, hwdec-codecs, audio-device, audio-channels, sub-text-*. These can be changed but not applied till restart playback.

Btw, I found that some options declared as M_OPT_FIXED(vf, af, deinterlace) which can be changed during runtime(there exist counterparts of properties). How come? Is it intentional in order to make client use `af` property rather than `options/af` for instance?

**Comment by wm4** [comment] 2015-02-02 14:48
Normally properties are for changing things at runtime. Many options are mirrored as properties, and setting a property both sets the option, and makes the change effective.

Being able to set plain options at runtime (without going through properties) was added only later, and there's no explicit change handling mechanism. So changing an option may happen to work, but is not expected to. Some options are marked as M_OPT_FIXED, because setting them would cause synchronization problems (the struct containing all the options is shared between threads), or could somehow make the program logic inconsistent.

Eventually, I'd like to remove the difference between options and properties. But there are still some problems with this, like properties and options having subtle differences. There are quite some properties that are not options, too.

(In retrospect I don't understand why MPlayer separated these two. I've already made lots of changes to make sure that a property and an option with the same name refers to the same underlying thing.)

**Comment by xylosper** [comment] 2015-02-03 07:26
About M_OPT_FIXED, some properties can be changed only if playing something which causes some problem.

For instance, `deinterlace` property cannot be changed unless video filter is initalized,.
At the same time, `deinterlace` option is marked as M_OPT_FIXED, so it cannot be changed after client handle is initialized.
Therefore, I can changed `deinterlace` value only during playback.
This means that, if user changed deinterlace option, I have to keep the changed value and apply it after new playback is started which is quite inconvenient and cumbersome because there exists gap between mpv state and client state.

I don't know how many properties/options have such problem, but at least for `deinterlace`, M_OPT_FIXED should be removed, or the property can be changed anytime.

**Comment by wm4** [comment] 2015-02-03 13:03
Yeah, basically there are two things changing a config setting could do:
- apply it immediately, fail if it doesn't work
- just store the setting, and use it next time something is initialized
And it's not really clear what setting a property should do. Currently, it can do either of those, and often both.

**Comment by wm4** [comment] 2015-02-03 13:20
Likewise, reading settings could do things:
- return what is currently used (e.g. whether deinterlacing is active)
- return what the user requested to use (e.g. whether deinterlacing was requested, even if there's no deinterlacer that can be used)

Also, things like ``aid`` have an ``auto`` value as option. Then, if you play an audio file, the ``aid`` _property_ returns the auto-selected track ID, and if you play a video-only file, it will return ``no``.

**Comment by wm4** [comment] 2015-02-03 22:26
See the commit above; I enabled some more options for runtime setting.

**Comment by xylosper** [comment] 2015-02-03 22:30
Thank you! And, as you said in the commit log,
> changes do not get immediately applied, unlike with corresponding properties.

The original issue for this post is left: functionality to reinitialize playback.

**Comment by wm4** [comment] 2015-02-03 22:38
Yeah, we didn't really discuss this.

**Comment by wm4** [comment] 2015-02-07 12:58
Would you be ok with a version that doesn't reopen the stream? I'd use PT_RELOAD_DEMUXER. In general, this sort of thing is really annoying.

**Comment by xylosper** [comment] 2015-02-07 13:07
I'm ok as far as changed options applied. With a short look, I can see `stream_enable_cache()` call is located before `goto_reopen_demuxer` label. Doesn't this mean change of cache options won't be applied?

**Comment by xylosper** [comment] 2015-02-07 13:11
Btw, can this way gaurantee that non-changed other playback states such as track selection, playback speed, volume, etc. will be kept?

**Comment by wm4** [comment] 2015-02-07 13:16
>Doesn't this mean change of cache options won't be applied?

That is correct.

>Btw, can this way gaurantee that non-changed other playback states such as track selection, playback speed, volume, etc. will be kept?

Yes. Applying per-file options is done further up.

Would it be better if the loadfile command applied the options globally, instead of per-file?

**Comment by xylosper** [comment] 2015-02-07 13:23
> >    Doesn't this mean change of cache options won't be applied?
> That is correct.

Oh, sorry, my question was too ambiguous with double negative expression.
Again, more directly, will changed cache option be applied, too?

> Would it be better if the loadfile command applied the options globally, instead of per-file?

Do you mean that per-file option will be cleared in this way?

**Comment by wm4** [comment] 2015-02-07 13:27
>will changed cache option be applied, too?

No, not with this idea.

>Do you mean that per-file option will be cleared in this way?

Per-file options (like the argument to ``loadfile``) are reset to their previous value if the file is unloaded. The is done with the ``load_per_file_options()`` (the ``M_SETOPT_BACKUP`` flag), and the ``m_config_restore_backups()`` function. It actually exists mostly for MPlayer compatibility. My idea was removing this behavior (at least for ``loadfile``), so you can reload the file manually without losing settings.

**Comment by xylosper** [comment] 2015-02-07 13:40
> No, not with this idea.

Hm, that's not good.

> My idea was removing this behavior (at least for loadfile), so you can reload the file manually without losing settings.

Is this different with `file-local-options/*`?

**Comment by wm4** [comment] 2015-02-07 14:07
>Is this different with file-local-options/*?

No.

**Comment by xylosper** [comment] 2015-02-07 14:37
Well, in that case, the problem is not confined to loadfile command. I thought it's not too difficult to solve this problem but I now start thinking it's really hard...

**Comment by Dudemanguy** [comment] 2022-01-18 20:44
Writing a `watch-later` file and then loading the file again is basically re-initializing playback so I'll close this (plus it's old). Most things are runtime-configurable by now and you can even change vo's on the fly.

**Closed by Dudemanguy** 2022-01-18 20:44 UTC
Labels: meta:feature-request, priority:stalled, core:option-param-conf, core:api
