### ISSUE TITLE
mpv cannot stream from vimeo any more

### ISSUE THREAD

**Issue by gbstan** [mpv-player/mpv#4827] opened 2017-09-02 08:29 UTC
### mpv version and platform
mpv on macOS Sierra 10.12.6

mpv 0.26.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Mon Aug  7 22:10:40 BST 2017
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.3

### Reproduction steps
mpv https://player.vimeo.com/video/150608819

### Expected behavior
video is properly streamed using mpv and youtube-dl
This was working perfectly until a few weeks ago.

### Actual behavior
mpv https://player.vimeo.com/video/150608819
Playing: https://player.vimeo.com/video/150608819
[ytdl_hook] 
[ytdl_hook] stack traceback:
[ytdl_hook] 	[C]: in function 'len'
[ytdl_hook] 	@ytdl_hook.lua:71: in function 'edl_escape'
[ytdl_hook] 	@ytdl_hook.lua:139: in function 'edl_track_joined'
[ytdl_hook] 	@ytdl_hook.lua:171: in function 'add_single_video'
[ytdl_hook] 	@ytdl_hook.lua:454: in function 'fn'
[ytdl_hook] 	mp.defaults:518: in function 'handler'
[ytdl_hook] 	mp.defaults:339: in function 'handler'
[ytdl_hook] 	mp.defaults:458: in function 'call_event_handlers'
[ytdl_hook] 	mp.defaults:495: in function 'dispatch_events'
[ytdl_hook] 	mp.defaults:451: in function <mp.defaults:450>
[ytdl_hook] 	[C]: in ?
[ytdl_hook] 	[C]: in ?
[ytdl_hook] Lua error: @ytdl_hook.lua:71: bad argument #1 to 'len' (string expected, got nil)
Failed to recognize file format.

Exiting... (Errors when loading file)

### Log file
See above (Actual behaviour) for error messages

### Sample files
Any video on vimeo seems to trigger the problem
https://player.vimeo.com/video/230282582
https://player.vimeo.com/video/115435198

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by gbstan** [comment] 2017-09-02 16:51
Just to be clear and complete, I have the latest version of youtube-dl installed: 2017.09.02

**Comment by CrisBRM** [comment] 2017-09-02 17:11
Works on my machine with mpv-git, but then again, I'm using youtube-dl-2017.07.23. It's probably a youtube-dl issue.

**Comment by wiiaboo** [comment] 2017-09-02 17:28
Duplicate of https://github.com/mpv-player/mpv/issues/4728. See https://github.com/mpv-player/mpv/issues/4728#issuecomment-320725058 for a workaround.

**Closed by wiiaboo** 2017-09-02 17:28 UTC

**Comment by gbstan** [comment] 2017-09-02 17:54
Hi Wiiaboo, I understand that I can the workaround referenced above, but shouldn't this be fixed without any workaround being applied? It seems from the thread that this appears as fixed but with the version of youtube-dl 2017.09.02 it still isn't. Is the problem on the mpv or on the youtube-dl side? Is a release of mpv fixing this coming out soon?

**Comment by wiiaboo** [comment] 2017-09-02 17:57
The linked comment has the answers to all those questions.
Only @lachs0r knows when's the next release.

**Comment by timofonic** [comment] 2017-09-02 19:44
@gbstan Have you tried a really updated youtube-dl and mpv-git? You use Windows, I can't help you much at this moment (but soon I'll can test stuff).

**Comment by gbstan** [comment] 2017-09-02 20:13
For clarification:

  * I use macos Sierra 10.12.6
  * I use the very latest versions of mpv and youtube-dl from brew (all
    up-to-date as of today)

**Comment by CounterPillow** [comment] 2017-09-02 21:54
mpv 0.26.0 does not contain the fix, when you say very latest, make sure it's actually git HEAD.

**Comment by vitorgalvao** [comment] 2017-09-02 22:40
I’ve tried `mpv` `HEAD` yesterday (installed via `homebrew`) and it still wasn’t fixed.

**Comment by Hrxn** [comment] 2017-09-03 06:48
Log for running the link/URL with only youtube-dl?

**Comment by gbstan** [comment] 2017-09-03 06:53
Here is the output when using youtube-dl only:

youtube-dl https://player.vimeo.com/video/150608819
[vimeo] 150608819: Downloading webpage
[vimeo] 150608819: Extracting information
[vimeo] 150608819: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[vimeo] 150608819: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 150608819: Downloading fastly_skyfire m3u8 information
[vimeo] 150608819: Downloading akfire_interconnect_quic MPD information
[vimeo] 150608819: Downloading akfire_interconnect_quic MPD information
[vimeo] 150608819: Downloading fastly_skyfire MPD information
[vimeo] 150608819: Downloading fastly_skyfire MPD information
[dashsegments] Total fragments: 151
[download] Destination: Trail Of Hope Short-150608819.fdash-fastly_skyfire_sep-video-606502192.mp4
[download]   5.1% of ~248.57MiB at  1.17MiB/s ETA 03:33

and here is the same when trying to play the same link through mpv:
mpv https://player.vimeo.com/video/150608819
Playing: https://player.vimeo.com/video/150608819
[ytdl_hook] 
[ytdl_hook] stack traceback:
[ytdl_hook] 	[C]: in function 'len'
[ytdl_hook] 	@ytdl_hook.lua:71: in function 'edl_escape'
[ytdl_hook] 	@ytdl_hook.lua:139: in function 'edl_track_joined'
[ytdl_hook] 	@ytdl_hook.lua:171: in function 'add_single_video'
[ytdl_hook] 	@ytdl_hook.lua:454: in function 'fn'
[ytdl_hook] 	mp.defaults:518: in function 'handler'
[ytdl_hook] 	mp.defaults:339: in function 'handler'
[ytdl_hook] 	mp.defaults:458: in function 'call_event_handlers'
[ytdl_hook] 	mp.defaults:495: in function 'dispatch_events'
[ytdl_hook] 	mp.defaults:451: in function <mp.defaults:450>
[ytdl_hook] 	[C]: in ?
[ytdl_hook] 	[C]: in ?
[ytdl_hook] Lua error: @ytdl_hook.lua:71: bad argument #1 to 'len' (string expected, got nil)
Failed to recognize file format.


Exiting... (Errors when loading file)

**Comment by wiiaboo** [comment] 2017-09-03 09:25
Apparently vimeo's CDNs don't like relative URLs.
This doesn't work:
`https://skyfire.vimeocdn.com/1504434122-0x16c82c8e17c8e66565df5cdf8dd383866e4b297f/150608819/sep/video/606502191,606502196,606502193,606502192/../../audio/606502196/chop/segment-0.mp4`
but this does:
`https://skyfire.vimeocdn.com/1504434122-0x16c82c8e17c8e66565df5cdf8dd383866e4b297f/150608819/sep/audio/606502196/chop/segment-0.mp4`

**Comment by gbstan** [comment] 2017-09-03 09:43
Ok. But how to fix it? There might be other websites affected too. 2 weeks ago this was working perfectly.

**Comment by wiiaboo** [comment] 2017-09-03 09:45
I'm referring to the error in https://github.com/mpv-player/mpv/issues/4827#issuecomment-326773042.
I've answered your issue when I closed this. It's still the same solution. If you can't build git master yourself, use the workarounds listed  in https://github.com/mpv-player/mpv/issues/4728#issuecomment-320725058.

**Comment by vitorgalvao** [comment] 2017-09-03 11:33
@wiiaboo Again, I tried `mpv` from master (`brew install --HEAD mpv`). I’ve also tried [your other solution](https://github.com/mpv-player/mpv/issues/4728#issuecomment-320725058). It still isn’t fixed.

While all vimeo videos can be downloaded with `youtube-dl`, only some can be played with `mpv`.

Video that works: https://vimeo.com/130975566
Video that doesn’t: https://vimeo.com/230282582

**Comment by wiiaboo** [comment] 2017-09-03 12:45
@vitorgalvao it's a related but different issue. Should be fixed with d280b3db93.

**Comment by vitorgalvao** [comment] 2017-09-03 12:58
@wiiaboo Confirmed as fixed with that commit. Thank you.
