### ISSUE TITLE
macOS_swift 

### ISSUE THREAD

**Issue by boluomeng** [mpv-player/mpv#6733] opened 2019-05-22 08:31 UTC
### mpv version and platform

mpv master 6e4971f69738056376e0a0c22fb59bb32a0092f9
macOS 10.14.5
Xcode 10.2.1

### Reproduction steps
./bootstrap.py
./waf configure
./waf

### Expected behavior
./waf success
### Actual behavior
./waf failed
### Log file
Build failed
 -> task in 'osdep/macOS_swift.o,osdep/macOS_swift.h,osdep/macOS_swift.swiftmodule' failed with exit status 1 (run with -v to display more information)
[build.log](https://github.com/mpv-player/mpv/files/3206304/build.log)

**Comment by CounterPillow** [comment] 2019-05-22 12:15
Probably a duplicate of https://github.com/mpv-player/mpv/issues/6470

**Closed** 2019-05-22 16:02 UTC
