### ISSUE TITLE
Incorrect display of radio tags in Cyrillic

### ISSUE THREAD

**Issue by jezokshe** [mpv-player/mpv#10980] opened 2022-12-08 21:38 UTC
It's a small thing, but still, if it's easy to fix, I'd like to ask you to take a look. Tags in Cyrillic from this radio, displayed as question marks. Problems with Cyrillic, Latin letters are displayed normally. And it's not just in MPV.
  I think it is not necessary to upload the logs, because the problem is obvious and easy to reproduce. You just need to wait for the music with the name in Cyrillic. Thank you!
  
Here is the link to the stream: http://89.219.35.26:8000/radions

![изображение](https://user-images.githubusercontent.com/77186394/206572850-accfc736-becd-4a2e-a814-4d7ccc69235f.png)

**Comment by CounterPillow** [comment] 2022-12-08 22:52
Pretty sure this is a duplicate of #8844

**Comment by jezokshe** [comment] 2022-12-08 22:57
@CounterPillow Sorry, I searched but didn't find it. And what to do now, close the request?

**Comment by CounterPillow** [comment] 2022-12-09 00:01
Either you can close it youself or someone with the proper access to the issue tracker can close it.

**Comment by jezokshe** [comment] 2022-12-09 15:37
@CounterPillow Then I'd better leave it if possible. It is interesting that I informed the author of that appeal about this problem. He is an MPV based radio developer on Linux systems.

**Closed** 2022-12-11 16:59 UTC
Labels: meta:duplicate
