### ISSUE TITLE
Playlist playback stops when seeking forward at the end of video

### ISSUE THREAD

**Issue by mauricioquintela** [mpv-player/mpv#9009] opened 2021-07-14 14:45 UTC
### Important Information
- mpv 0.33.1
- Manjaro Linux, 5.12 kernel
- Source: official repository
- Issue was not present in mpv 0.32
- Both KDE Plasma and i3-gaps
- Both latest nvidia proprietary drivers (KDE Plasma) and iHD kernel module (i3-gaps), with either software or hardware decoding in each platform
- Screenshot at bottom of issue report

### Reproduction steps

Open a playlist. When a video is almost ending, use the skip keys to skip to a time that would be after the end of video (i.e., skip forward 10 seconds when less than 10 seconds are remaining). Video will end, and next item in the playlist will be opened. New item will be paused with mpv considering it to be playing (bottom left control will indicate that it is playing). Only way to get video to start playing is the skip forward (or, weirdly enough, backwards) which will allow the playback to resume.  

Occurs regardless of hwdec being used, or config itself being called.  Only mitigation appears to be setting `--gapless-audio=no` (inspired by #8904 ), but this however prevents seeking to the next playlist item (if one seeks forward to after the currently-playing item is over, playlist get stuck on the last frame of the current video without passing to the next item; to leave this state one needs to either skip to next item manually or seek backwards enough so that the current item ends by itself). Setting `--gapless-audio=yes` does not mitigate, leading me to believe this is related to this feature.

### Expected behavior

Next item in playlist starts playing immediately if previous item has ended via forward-skipping (via seek command). 

### Actual behavior

Next item is loaded but playback is paused without actually being paused. Visible in screenshot.

### Log file

[Log:](https://0x0.st/-O6d.txt). Seek to after EOF is called at around [15.176]. Stream gets stuck at [18.016], with the seek being called at [55.183] allowing it to get unstuck. 

Screenshot: 
![image](https://user-images.githubusercontent.com/39190784/125641157-d0a3a435-5361-4891-89de-cc899d3a3246.png)

**Comment by Dudemanguy** [comment] 2021-07-14 15:56
Looks like a duplicate of #8768 which should be fixed in git master. Feel free to reopen if it isn't.

**Closed by Dudemanguy** 2021-07-14 15:56 UTC
Labels: os:linux
