### ISSUE TITLE
Play multiple video files not separately

### ISSUE THREAD

**Issue by Max-Enrik** [mpv-player/mpv#8163] opened 2020-10-11 21:28 UTC
I believe this question already asked and answered but I didn't find any related forum/link about exactly this topic.
So I'd like to select multiple video files and just hit enter and then that video files will play in a single mpv window _(just not start to play at same time in a separately mpv windows)_ once one of them finished and next one could start to play and afterward next one and so on.

_(I hope I explained my concern clearly - English isn't my native language, and I learned English without studying it - thanks for your understanding.)_

**Comment by Akemi** [comment] 2020-10-11 21:57
duplicate of #3811. next time you should maybe name your platform.

**Closed by Akemi** 2020-10-11 21:57 UTC
Labels: meta:question
