### ISSUE TITLE
(Mac) full screen jerky; windowed mode smooth

### ISSUE THREAD

**Issue by ballo** [mpv-player/mpv#4295] opened 2017-04-02 03:07 UTC
### mpv version and platform

0.24 Mac

### Reproduction steps

Play a high FPS mp4 video in a window and compare to full screen. Zooming in (ctrl-scroll, enabled in Accessibility option in System Preferences) is still smooth. It almost works as a work-around except you still have the title bar.

### Expected behavior

Smooth video in full screen

### Actual behavior

Jerky. It's subtle yet highly annoying. The problem does not occur if I use the OS to zoom using accessibility options.

**Comment by Akemi** [comment] 2017-04-02 03:10
probably a duplicate of #3739. try with `--opengl-early-flush=no`.

**Comment by ballo** [comment] 2017-04-02 03:19
No difference using:

/ /Applications/mpv.app/Contents/MacOS  ./mpv --opengl-early-flush=no

0.24 seems to be a lot worse than 0.22. Fewer features, too (what happened to save location?) I'm going back

**Comment by Akemi** [comment] 2017-04-02 03:27
since you ignored the issue template mostly, i can't help you.

> Fewer features, too (what happened to save location?)

nothing, it's still there. if you mean the menu item, that was removed. you can still press Shift+Q or use the command line option.

**Comment by ballo** [comment] 2017-04-03 19:28
I found another work-around: using gfxCardStatus to switch to the discrete graphics.

**Comment by Akemi** [comment] 2017-04-03 20:10
or you can use `--cocoa-force-dedicated-gpu=yes`. though if you would provide more info we might be able to get to the core of the problem.

**Comment by ballo** [comment] 2017-04-03 20:59
The rest of the template seemed highly irrelevant, but good luck making use of this:


[cplayer] Command line options: '-v' 'UFC.Fight.Night.107.Prelims.720p.WEB-DL.H264.Fight-BB.mp4'
[cplayer] mpv 0.22.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Mon Nov 28 21:41:20 CET 2016
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.34.100
[cplayer]    libavcodec      57.64.101
[cplayer]    libavformat     57.56.100
[cplayer]    libswscale      4.2.100
[cplayer]    libavfilter     6.65.100
[cplayer]    libswresample   2.3.100
[cplayer] ffmpeg version: 3.2.1
[cplayer]
[cplayer] Configuration: waf configure --prefix=/Users/djinn/apps/homebrew/Cellar/mpv/0.22.0_1 --enable-zsh-comp --enable-libmpv-shared --confdir=/Users/djinn/apps/homebrew/etc/mpv --datadir=/Users/djinn/apps/homebrew/Cellar/mpv/0.22.0_1/share/mpv --mandir=/Users/djinn/apps/homebrew/Cellar/mpv/0.22.0_1/share/man --docdir=/Users/djinn/apps/homebrew/Cellar/mpv/0.22.0_1/share/doc/mpv --zshdir=/Users/djinn/apps/homebrew/Cellar/mpv/0.22.0_1/share/zsh/site-functions
[cplayer] List of enabled features: any-gl apple-remote asm atomics av-avpacket-int64-duration av-new-pixdesc av-pix-fmt-mmal av-subtitle-nopict av-version-info avcodec-chroma-pos-api avcodec-has-codecpar avcodec-new-codec-api avcodec-profile-name avframe-metadata avframe-skip-samples avutil-has-hwcontext avutil-hdr avutil-mastering-metadata bsd-fstatfs build-date c11-tls cocoa coreaudio cplayer debug-build dlopen encoding fchmod fnmatch gcc-tls gl gl-cocoa glob gnuc iconv jpeg lcms2 libass libass-osd libav libavdevice libavfilter libdl libm libmpv-shared libswresample lua nanosleep optimize osx-thread-name plain-gl posix posix-or-mingw posix-spawn pthreads resampler shm stdatomic subprocess termios tv videotoolbox-gl videotoolbox-hwaccel zlib zsh-comp
[global] config path: '' -> '/Users/ball/.config/mpv'
[global] config path: 'mpv.conf' -/-> '/Users/ball/.config/mpv/mpv.conf'
[global] config path: 'config' -/-> '/Users/ball/.config/mpv/config'
[global] config path: 'mpv.conf' -/-> '/Users/ball/.mpv/mpv.conf'
[global] config path: 'config' -/-> '/Users/ball/.mpv/config'
[global] config path: 'mpv.conf' -> '/Applications/mpv.app/Contents/Resources/mpv.conf'
[global] config path: 'config' -/-> '/Applications/mpv.app/Contents/Resources/config'
[global] config path: 'mpv.conf' -/-> '/Users/djinn/apps/homebrew/etc/mpv/mpv.conf'
[global] config path: 'config' -/-> '/Users/djinn/apps/homebrew/etc/mpv/config'
[cplayer] Reading config file /Applications/mpv.app/Contents/Resources/mpv.conf
[cplayer] Setting option 'player-operation-mode' = 'pseudo-gui' (flags = 4)
[cplayer] Setting option 'v' = '' (flags = 8)
[cplayer] Setting option 'terminal' = 'no' (flags = 260)
[cplayer] Setting option 'force-window' = 'yes' (flags = 260)
[cplayer] Setting option 'idle' = 'once' (flags = 260)
[cplayer] Setting option 'screenshot-directory' = '~~desktop/' (flags = 260)
[cplayer] Setting option 'player-operation-mode' = 'pseudo-gui' (flags = 4)
[global] config path: 'input.conf' -/-> '/Users/ball/.config/mpv/input.conf'
[global] config path: 'input.conf' -/-> '/Users/ball/.mpv/input.conf'
[global] config path: 'input.conf' -/-> '/Applications/mpv.app/Contents/Resources/input.conf'
[global] config path: 'input.conf' -/-> '/Users/djinn/apps/homebrew/etc/mpv/input.conf'

**Comment by ballo** [comment] 2017-04-03 21:00
0.24 version (which I stopped using since it jerks around when switching to full screen. Definitely a downgrade):

64 Fight-BB  /Applications/mpv-new.app/Contents/MacOS/mpv -v UFC.Fight.Night.107
[cplayer] Command line options: '-v' 'UFC.Fight.Night.107.Prelims.720p.WEB-DL.H264.Fight-BB.mp4'
[cplayer] mpv 0.24.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sun Feb 12 21:31:15 CET 2017
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.34.101
[cplayer]    libavcodec      57.64.101
[cplayer]    libavformat     57.56.101
[cplayer]    libswscale      4.2.100
[cplayer]    libavfilter     6.65.100
[cplayer]    libswresample   2.3.100
[cplayer] ffmpeg version: 3.2.4
[cplayer]
[cplayer] Configuration: waf configure --prefix=/Users/djinn/apps/homebrew/Cellar/mpv/0.24.0 --enable-zsh-comp --enable-libmpv-shared --enable-html-build --confdir=/Users/djinn/apps/homebrew/etc/mpv --datadir=/Users/djinn/apps/homebrew/Cellar/mpv/0.24.0/share/mpv --mandir=/Users/djinn/apps/homebrew/Cellar/mpv/0.24.0/share/man --docdir=/Users/djinn/apps/homebrew/Cellar/mpv/0.24.0/share/doc/mpv --zshdir=/Users/djinn/apps/homebrew/Cellar/mpv/0.24.0/share/zsh/site-functions
[cplayer] List of enabled features: any-gl apple-remote asm atomics bsd-fstatfs build-date c11-tls cocoa coreaudio cplayer debug-build dlopen encoding fchmod gcc-tls gl gl-cocoa glob gnuc iconv is_ffmpeg jpeg lcms2 libass libass-osd libav libavcodec libavdevice libdl libm libmpv-shared lua nanosleep optimize osx-thread-name plain-gl posix posix-or-mingw posix-spawn pthreads shm stdatomic subprocess termios tv videotoolbox-gl videotoolbox-hwaccel zlib zsh-comp
[global] config path: '' -> '/Users/ball/.config/mpv'
[global] config path: 'mpv.conf' -/-> '/Users/ball/.config/mpv/mpv.conf'
[global] config path: 'config' -/-> '/Users/ball/.config/mpv/config'
[global] config path: 'mpv.conf' -/-> '/Users/ball/.mpv/mpv.conf'
[global] config path: 'config' -/-> '/Users/ball/.mpv/config'
[global] config path: 'mpv.conf' -> '/Applications/mpv-new.app/Contents/Resources/mpv.conf'
[global] config path: 'config' -/-> '/Applications/mpv-new.app/Contents/Resources/config'
[global] config path: 'mpv.conf' -/-> '/Users/djinn/apps/homebrew/etc/mpv/mpv.conf'
[global] config path: 'config' -/-> '/Users/djinn/apps/homebrew/etc/mpv/config'
[cplayer] Reading config file /Applications/mpv-new.app/Contents/Resources/mpv.conf
[cplayer] Setting option 'player-operation-mode' = 'pseudo-gui' (flags = 4)
[cplayer] Setting option 'v' = '' (flags = 8)
[cplayer] Setting option 'terminal' = 'no' (flags = 260)
[cplayer] Setting option 'force-window' = 'yes' (flags = 260)
[cplayer] Setting option 'idle' = 'once' (flags = 260)
[cplayer] Setting option 'screenshot-directory' = '~~desktop/' (flags = 260)
[cplayer] Setting option 'player-operation-mode' = 'pseudo-gui' (flags = 4)
[global] config path: 'input.conf' -/-> '/Users/ball/.config/mpv/input.conf'
[global] config path: 'input.conf' -/-> '/Users/ball/.mpv/input.conf'
[global] config path: 'input.conf' -/-> '/Applications/mpv-new.app/Contents/Resources/input.conf'
[global] config path: 'input.conf' -/-> '/Users/djinn/apps/homebrew/etc/mpv/input.conf'
 ball@Balls-MacBook-Pro  ~/Downloads/UFC Fight Night 107 Prelims 720p WEB-DL H264 Fight-BB 

**Comment by Akemi** [comment] 2017-04-03 21:35
okay then you can help yourself.

**Closed by Akemi** 2017-04-03 21:35 UTC
Labels: osx
