### ISSUE TITLE
Video artifacts on "gpu" and "vaapi" VOs when using options "--no-input-default-bindings" and "--input-vo-keyboard=no"

### ISSUE THREAD

**Issue by pspot2** [mpv-player/mpv#6644] opened 2019-04-19 00:20 UTC
Running mpv with the options "--no-input-default-bindings" and "--input-vo-keyboard=no" introduces video artifacts (sample file: https://0x0.st/zqmv.mp4) - look at the white cowboy hat in the second half of the video. This is reproducible with any video with panning scenes.

This is observed with "--vo=gpu" or "--vo=vaapi". Using "--vo=xv" does not cause this issue. Removing the offending options fixes the issue for all VOs.

This issue was discovered because SMPlayer sets these options when embedding the mpv playback window into its own window. The workaround is to configure SMPlayer to start mpv in a separate window - then the options are not set and there are no artifacts.

### mpv version and platform

Reproducible with mpv-0.29.1 and mpv-0.27.2.

Linux nuc8 4.20.17-gentoo #9 SMP Tue Apr 9 22:48:18 CEST 2019 x86_64 Intel(R) Core(TM) i3-8109U CPU @ 3.00GHz GenuineIntel GNU/Linux

vainfo: Driver version: Intel i965 driver for Intel(R) Coffee Lake - 2.3.0

### Reproduction steps

Play any video file with large panning scenes.

### Expected behavior

Setting the options mentioned in the title should not introduce artifacts.

### Actual behavior

Setting the options mentioned in the title introduces artifacts.

### Log file

https://0x0.st/zqas.txt

### Sample files

https://0x0.st/zqmv.mp4 (this is not the actual file, this is a video of the video recorded with the smartphone to demonstrate the artifacts).

**Comment by wm4** [comment] 2019-10-24 10:48
Can't reproduce with vaapi on AMD.

"--no-input-default-bindings" does not affect the VO at all.
"--input-vo-keyboard=no" on X11 merely prevents that "KeyPressMask | KeyReleaseMask" is added to the window's event mask.

Are you sure this effect is real, rather than a random coincidence when testing? Try various versions of the vaapi and mesa drivers too.

Closing because too old.

**Closed by wm4** 2019-10-24 10:48 UTC
Labels: core, os:linux, vo:gpu, vo:vaapi
