### ISSUE TITLE
libmpv: OpenGL ES 2 support

### ISSUE THREAD

**Issue by deltabeard** [mpv-player/mpv#5397] opened 2018-01-14 10:41 UTC
Is there a possibility of adding OpenGL ES 2 support in libmpv?
libmpv currently requires OpenGL 2.1 or later. A number of low-end/embedded systems like the Raspberry Pi\* only have support for OpenGL ES 2. I would like to be able to use opengl-cb on the Pi whilst still maintaining hardware decoding features.

\* The Raspberry PI does support OpenGL 2.1 with mesa and the vc4 driver, but hardware decoding does not work with it.

**Comment by wm4** [comment] 2018-01-14 10:47
It already supports that and it works on RPI (with the default firmware which provides only ES 2). You just need to be careful about returning all symbols from the function pointer callback.

**Comment by deltabeard** [comment] 2018-01-14 10:50
That's excellent to hear. This issue I'm having must be due to the front-end then and not libmpv. I'll close this once I've got it working.

**Comment by thebombzen** [comment] 2018-01-14 15:58
Closing this since libmpv does support OpenGLES 2.

**Closed by thebombzen** 2018-01-14 15:58 UTC

**Comment by deltabeard** [comment] 2018-01-14 17:34
Well at least fix opengl_cb.h before closing this issue since it clearly says:
> Only "desktop" OpenGL version 2.1 or later is supported.

**Comment by thebombzen** [comment] 2018-01-14 19:24
I fail to see how that's inaccurate. "desktop" OpenGL refers to standard OpenGL for non-embedded devices.

**Comment by wm4** [comment] 2018-01-14 19:27
Well, it does fail to mention any GLES support.

**Comment by deltabeard** [comment] 2018-01-14 19:34
It does not say anything about OpenGL ES support which why I opened this issue. The fact the the comment says only desktop OpenGL is supported does not imply any support for OpenGL ES which is for embedded devices. However, now that we've established in this issue that OpenGL ES is in fact supported, the comment is inaccurate as OpenGL >=2.1 isn't the only support version.

Even if OpenGL 2.1 implies support for OpenGL ES 2, it was not helpful to leave that ambiguous. It may be helpful to mention what versions of OpenGL ES is supported.

Prematurely closing this issue was not helpful.

**Comment by thebombzen** [comment] 2018-01-14 20:05
This is already stated in the manpage.
```
       --gpu-api=<type>
              Controls which type of graphics APIs will be accepted:

              auto   Use any available API (default)

              opengl Allow only OpenGL (requires OpenGL 2.1+ or GLES 2.0+)
```

**Comment by deltabeard** [comment] 2018-01-14 20:08
The header file is incorrect and needs correcting.

Just because the information is correct elsewhere does not mean other misinformation should remain.

**Comment by thebombzen** [comment] 2018-01-14 20:13
This is true. See #5403.

**Comment by deltabeard** [comment] 2018-01-14 20:20
Thanks. Please don't close the issue prematurely next time.

**Comment by thebombzen** [comment] 2018-01-14 20:23
If the issue is that `mpv` does not support something it does support, I will close it.

**Comment by deltabeard** [comment] 2018-01-14 20:34
And to what purpose? There was still an issue here. There was no point in closing this when you did.

**Comment by thebombzen** [comment] 2018-01-14 21:01
There was still *a* problem but not *this* problem. It's common practice to open a new Issue if you have a new problem to report, rather than repurpose an existing one whose subject has already been resolved.

**Comment by deltabeard** [comment] 2018-01-14 21:33
No, it *was* this *exact* problem. I opened this issue after reading only OpenGL >=2.1 was supported in opengl_cb.h.

Kind Regards.

**Comment by thebombzen** [comment] 2018-01-14 23:00
I'm not sure what planet you live on but on Earth "libmpv does not support OpenGLES 2.0" and "libmpv does not document that it supports OpenGLES 2.0 despite supporting it" are not the same problem.

**Comment by deltabeard** [comment] 2018-01-14 23:21
The fact that opengl_cb.h did not say that libmpv supported OpenGL ES, suggested to me that OpenGL ES was not supported by libmpv.
The fact that OpenGL ES is in fact supported by mpv was established in this review, and thereby the misinformation in opengl_cb.h was the suggested fix.

You did not understand the issue for quite a while. But the fact that you *still* don't understand why the above facts are linked is actually getting irritating.

Why don't you bring yourself back to Earth, and accept that you did not understand the issue.

Anyway, regardless of what the issue was, the user should feel that their issue was resolved before closing the issue. "Does this resolve your issue?" for example, would have been nice before closing the issue. You misunderstood the issue and it's context, then closed the issue abruptly despite me saying that I would close it myself.

The fact that the issue was resolved after you closed the issue showed that you closed it prematurely.

**Comment by deltabeard** [comment] 2018-01-14 23:25
Now that the fix is merged https://github.com/mpv-player/mpv/commit/17e7f653d3228e078a6958fe1fce120679fff798, this issue should've now been closed.

**Comment by Hrxn** [comment] 2018-01-14 23:27
If I may chime in?

The question when an issue was closed on this tracker here, and if this timing has actually any deep and meaningful consequence, resulting in any bearing on like, the reality, is rather irrelevant.

This debate is getting irritating.
