### ISSUE TITLE
Exit code on quit and quit-watch-later is not respected

### ISSUE THREAD

**Issue by vitorgalvao** [mpv-player/mpv#7456] opened 2020-02-12 18:23 UTC
### Important Information

- **mpv version:** git master (5a45a4ca3985efaa01e372ee777a4efbe642fe34)
- **macOS Version:** 10.14.6 (18G3020)
- **Source of the mpv binary or bundle:** Homebrew formula
- **If known which version of mpv introduced the problem:** Unknown
- **Possible screenshot or video of visual glitches**: N/A

Note that I’ve been experiencing this for close to two years, so any recent version will do to reproduce.

### Reproduction steps

I can’t run it with `--no-config` because the issue depends on having a configuration. However, I’ve deleted `.config/mpv` and readded just the relevant option.

In `input.conf`, I have

```
q quit-watch-later 9
```

However, this works unreliably (it often exists with `0`). I’ve banged my head for months trying to reproduce it consistently, but every time I think I’ve discovered the cause, I can’t reproduce it on command. However, it happens so often that making it happen isn’t difficult.

Is this only an issue on macOS? https://github.com/mpv-player/mpv/issues/798 suggests it shouldn’t work at all, but it does work sometimes and the documentation makes no reference to it being buggy on macOS.

I’ll accept if this is a Cocoa issue that can’t be worked around. If you’re able to give me a few more details, I’ll also submit a PR to update the documentation. I’ve tried a ton of alternatives, including scripting, and so far (only built it today, so the jury’s still out) it seems that sending `KILL` (`TERM` isn’t enough) to mpv is the only method that works to get a predictable non-zero exit code. I’m doing so with:

```lua
function kill_watch_later()
  mp.commandv('write-watch-later-config')
  mp.command_native({ 'run', 'killall', '-9', 'mpv' })
end
```

I’d rather do `'kill', '-9', PID` so I only kill the current instance of mpv and not all of them, but so far I’ve had no success (`mp.utils.getpid()` always gives me an error), so I’d accept help there.

### Expected behavior

mpv should quit with provided exit code.

### Actual behavior

mpv *sometimes* exists with provided exit code; often exits with `0`.

### Log file

https://0x0.st/i-4a.txt

### Sample files

Any file or stream works to reproduce.

**Comment by wm4** [comment] 2020-02-12 18:31
This is probably just an OSX restriction (thanks to Apple's incompetence). Can you test with a Linux or Windows build?

**Comment by vitorgalvao** [comment] 2020-02-12 18:37
> Can you test with a Linux or Windows build?

I’ll try but I think I won’t be able to do so soon, as I only have one machine.

**Comment by wm4** [comment] 2020-02-12 18:48
Just tried it myself on Linux - works.

The root of the problem is roughly for the same reason as this: https://github.com/mpv-player/mpv-examples/issues/29#issuecomment-585246979

**Comment by vitorgalvao** [comment] 2020-02-12 22:47
> Just tried it myself on Linux

Thank you.

> The root of the problem is roughly for the same reason as this: [mpv-player/mpv-examples#29 (comment)](https://github.com/mpv-player/mpv-examples/issues/29#issuecomment-585246979)

So is this issue:

1. Fixable.
2. Fixable but not worth it because it would require too much work and/or has the potential to break more important things and/or make the code too convoluted.
3. Not fixable unless Apple changes something.

If it’s 2 or 3, I don’t mind closing the issue and submitting a PR to make a short note on the documentation for `quit` and `quit-watch-later`.

Also, as a way of having a better workaround, are you able to clarify my question on how to get the current PID inside `mp.command_native` (or something else, I can use another function)?

**Comment by avih** [comment] 2020-02-12 23:14
> Can you test with a Linux or Windows build?

Seems to work OK on windows for both `quit` and `quit-watch-later`.

> how to get the current PID

I don't think there's an mpv command for that, but from a script you can:
In lua: `require("mp.utils").getpid()`
in JS: `mp.utils.getpid()`

**Comment by wm4** [comment] 2020-02-13 00:39
I think we had this already, did you find anything in old issues?

**Comment by vitorgalvao** [comment] 2020-02-14 14:56
> I think we had this already, did you find anything in old issues?

You mean the way to get the PID? I only found https://github.com/mpv-player/mpv/issues/5208, the same that I found [in the docs](https://github.com/mpv-player/mpv/blob/master/DOCS/man/lua.rst#mputils-functions), but it wasn’t clear to me that to use it I had to `require("mp.utils").getpid()`. I tried variations of `mp.utils.getpid()` (like `mp.getpid` or `utils.getpid()`) but I always got different errors.

**Comment by Akemi** [comment] 2024-03-31 23:47
will be fixed in #13803

**Closed** 2024-04-01 20:13 UTC
Labels: os:mac

**Comment by vitorgalvao** [comment] 2024-04-02 15:51
Many thanks for your work on this, @Akemi. I have compiled from master, updated my config, and tested it a bunch of times in a row (so not real usage, more of a stress test) and so far so awesome. I’ll report back if I find an issue, but I’m optimistic and didn’t want to forget to thank you and assure you your work is appreciated. Thank you again!

**Comment by Akemi** [comment] 2024-04-02 17:18
you are welcome @vitorgalvao 👍
