### ISSUE TITLE
apply-profile not changing layout

### ISSUE THREAD

**Issue by Andreasvb** [mpv-player/mpv#4669] opened 2017-07-25 23:34 UTC
### mpv version and platform

mpv 0.26.0-9-g2378acc3b3
Windows 10 Pro x64

### Reproduction steps

_input.conf_
```
F1 apply-profile "osc1" 
F2 apply-profile "osc2"
F3 cycle-values apply-profile "osc1" "osc2" "osc3"
```
_mpv.conf_
```
[osc1]
profile-desc="OSC1"
script-opts=osc-layout=slimbox
border=no

[osc2]
profile-desc="OSC2"
script-opts=osc-layout=box
border=yes

[osc3]
script-opts=osc-layout=bottombar

```

### Expected behavior

F1 = no border, slimbox layout
F2 = border, box layout
F3 = toggle between profiles

According to manual it should work:

> **apply-profile "\<name>"**
> Apply the contents of a named profile. This is like using profile=name in a config file, except you can map it to a key binding to change it at runtime.

### Actual behavior

F1 = no border, layout unchanged
F2 = border, layout unchanged
F3 = layout unchanged, OSD: Unknown property: 'apply-profile'

### Log file

http://sprunge.us/IROW

**Comment by wiiaboo** [comment] 2017-07-25 23:40
scripts-opts is only evaluated once.

**Comment by wm4** [comment] 2017-08-08 09:59
In theory scripts could observe scripts-opts, but not sure if anyone would want to bother.

**Comment by Akemi** [comment] 2019-09-21 15:35
duplicate of #4513

**Closed by Akemi** 2019-09-21 15:35 UTC
Labels: core:api, core:option-param-conf, meta:feature-request, priority:low
