### ISSUE TITLE
autofit in auto-profile doesn't work for first item

### ISSUE THREAD

**Issue by escapezn** [mpv-player/mpv#9661] opened 2021-12-31 11:36 UTC
### Important Information

Provide following Information:
- mpv version 0.34
- Windows Version windows 10 1909
- Source of the mpv binary
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

I'd like to keep mpv window size roughly constant when playing music with albumart, so a section of profile added.
```
[audio]
profile-cond=not vid or get("current-tracks/video/albumart")
loop-playlist = inf
autofit-larger = 24%
autofit-smaller = 24%
autofit = 24%
# profile-restore = copy-equal
```

### Expected behavior
The width of mpv window is fixed at 24% of my screen as long as playing music.

### Actual behavior
Mpv window doesn't resize to 24% on the first music loaded, although this profile has indeed been applyed according to console. Since the second mpv normally adjusts its size.

And another question is that if `profile-restore` were configured, no matter as copy or copy-equal, autofit here will never take effect. Is this expected or not?

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/7796159/log.txt)

**Comment by escapezn** [comment] 2021-12-31 12:13
It's wired that autofit has no effect for some audio files at all.
[log1.txt](https://github.com/mpv-player/mpv/files/7796173/log1.txt)

**Comment by guidocella** [comment] 2021-12-31 13:28
Duplicate of #8379. Runtime changes of geometry and autofit have only been implemented on X11 and Wayland so far.

**Comment by escapezn** [comment] 2021-12-31 14:10
Thank you for replying. Also I understand why for some files it works while for others not. https://github.com/mpv-player/mpv/issues/8379#issuecomment-770252649

**Comment by Dudemanguy** [comment] 2022-01-19 04:47
Closing since it is a duplicate as noted. The fix would be to implement runtime geometry/autofit on Windows.

**Closed by Dudemanguy** 2022-01-19 04:47 UTC
Labels: os:win

**Comment by escapezn** [comment] 2024-06-23 15:26
https://github.com/mpv-player/mpv/pull/13626 solved
