### ISSUE TITLE
New OS X fullscreen behavior introduces delay

### ISSUE THREAD

**Issue by tonycpsu** [mpv-player/mpv#4063] opened 2017-01-24 21:06 UTC
a8347eb fixes a bunch of fullscreen-related bugs and inconsistencies, but it also introduces an annoying delay when quitting or switching from a fullscreen video while OS X does a slide animation.  This delay comes from the OS of course, not from mpv, but I've never found a way to eliminate it, and I would prefer the legacy behavior where mpv handles fullscreen properly.

Because the old fullscreen code was removed and not made an option, I'm guessing that it's been decided that it's not worth keeping, but for those of us who prefer the previous fullscreen behavior, it would be nice to have this available as a (non-default) configuration.

**Comment by Akemi** [comment] 2017-01-24 21:08
duplicate of #4014.

**Closed by Akemi** 2017-01-24 21:08 UTC
