### ISSUE TITLE
Can't set window position and size on Ubuntu 19.04

### ISSUE THREAD

**Issue by SemperPeritus** [mpv-player/mpv#6824] opened 2019-07-25 20:42 UTC
### mpv version and platform

Ubuntu 19.04 Unity Xorgs RTX 2060 with nvidia repository drivers.

<details>
   <summary>mpv -v</summary>

```
[cplayer] Command line options: '-v'
[cplayer] mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
[cplayer]  built on UNKNOWN
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       56.14.100 (runtime 56.22.100)
[cplayer]    libavcodec      58.18.100 (runtime 58.35.100)
[cplayer]    libavformat     58.12.100 (runtime 58.20.100)
[cplayer]    libswscale      5.1.100 (runtime 5.3.100)
[cplayer]    libavfilter     7.16.100 (runtime 7.40.101)
[cplayer]    libswresample   3.1.100 (runtime 3.3.100)
[cplayer] ffmpeg version: 4.1.3-0ubuntu1
[cplayer] 
[cplayer] Configuration: ./waf configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --confdir=/etc/mpv --zshdir=/usr/share/zsh/vendor-completions --enable-cdda --enable-dvdnav --enable-dvdread --enable-libmpv-shared --enable-libsmbclient --enable-sdl2 --enable-sndio --enable-zsh-comp --disable-build-date --enable-dvbin
[cplayer] List of enabled features: 52arch alsa asm atomics caca cdda cplayer cplugins debug-build drm drmprime dvbin dvdnav dvdread dvdread-common egl-drm egl-helpers egl-x11 fchmod ffmpeg gbm gbm.h gl gl-wayland gl-x11 glibc-thread-name glob glob-posix gnuc gpl iconv jack jpeg lcms2 libaf libarchive libass libass-osd libav-any libavcodec libavdevice libbluray libdl libm libmpv-shared librt libsmbclient linux-fstatfs lua optimize oss-audio plain-gl posix posix-or-mingw posix-spawn posix-spawn-native pthreads pulse rubberband sdl2 sndio stdatomic uchardet vaapi vaapi-drm vaapi-egl vaapi-glx vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vdpau-gl-x11 vt.h vulkan wayland wayland-protocols x11 xv zlib zsh-comp
[cplayer] Reading config file /etc/mpv/encoding-profiles.conf
[cplayer] Reading config file /etc/mpv/mpv.conf
[cplayer] Reading config file /home/platon/.config/mpv/mpv.conf
[cplayer] Warning: option --softvol-max was replaced with --volume-max and might be removed in the future.
[ifo] Opening /home/platon/.config/mpv/input.conf
[ifo_dvdnav] Opening /home/platon/.config/mpv/input.conf
[bdmv/bluray] Opening /home/platon/.config/mpv/input.conf
[file] Opening /home/platon/.config/mpv/input.conf
[input] Parsing input config file /home/platon/.config/mpv/input.conf
[input] Input config file /home/platon/.config/mpv/input.conf parsed: 12 binds
[cplayer] mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
[cplayer]  built on UNKNOWN
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       56.14.100 (runtime 56.22.100)
[cplayer]    libavcodec      58.18.100 (runtime 58.35.100)
[cplayer]    libavformat     58.12.100 (runtime 58.20.100)
[cplayer]    libswscale      5.1.100 (runtime 5.3.100)
[cplayer]    libavfilter     7.16.100 (runtime 7.40.101)
[cplayer]    libswresample   3.1.100 (runtime 3.3.100)
[cplayer] ffmpeg version: 4.1.3-0ubuntu1
[cplayer] 
[cplayer] Usage:   mpv [options] [url|path/]filename
[cplayer] 
[cplayer] Basic options:
[cplayer]  --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
[cplayer]  --no-audio        do not play sound
[cplayer]  --no-video        do not play video
[cplayer]  --fs              fullscreen playback
[cplayer]  --sub-file=<file> specify subtitle file to use
[cplayer]  --playlist=<file> specify playlist file
[cplayer] 
[cplayer]  --list-options    list all mpv options
[cplayer]  --h=<string>      print options which contain the given string in their name
[cplayer] 
[ytdl_hook] script-opts/ytdl_hook.conf not found. 
[ytdl_hook] lua-settings/ytdl_hook.conf not found. 
[stats] script-opts/stats.conf not found. 
[stats] lua-settings/stats.conf not found. 
[ytdl_hook] Exiting...
[stats] Exiting...
```
</details>

### Reproduction steps
1) Add to input.conf `Ctrl+Alt+Shift+F set geometry "1920x1080+0+0"`, run mpv and press those keys.
2) Add to input.conf `Ctrl+Alt+Shift+F set width "1920"` or `Ctrl+Alt+Shift+F set dwidth "1920"`, run mpv and press those keys.
3) Add to mpv.conf `geometry=1920x1080+0+0`

### Actual behavior
1) Message `geometry: 1920x1080+0+0` Nothing more happens.
2) Message `mpv failed to set property width` or Message `mpv failed to set property dwidth`.
3) Works fine.

### Logs file

1) https://0x0.st/zpDG.txt
2) https://0x0.st/zpDD.txt

**Comment by Akemi** [comment] 2019-07-25 21:06
duplicate of #3872.

**Closed by Akemi** 2019-07-25 21:06 UTC
