### ISSUE TITLE
`DRM modifier INTEL 0x2 not available for format r8` with `--hwdec=vaapi --gpu-api=vulkan`

### ISSUE THREAD

**Issue by ojab** [mpv-player/mpv#8702] opened 2021-04-07 09:19 UTC
### Important Information

```
mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: git-snapshot-20210323-rpmfusion
```
- Linux Distribution and Version: Fedora 34
- Source of the mpv binary: rpmfusion repo
- Window Manager and version: sway-1.5.1, wlroots-0.12.0
- GPU driver and version: mesa-21.0.1, `Intel(R) HD Graphics 515 (SKL GT2)`
- Possible screenshot or video of visual glitches:
![image](https://user-images.githubusercontent.com/153388/113842527-67ac4400-979b-11eb-8577-834ab65aab79.png)

### Reproduction steps

```
mpv --ytdl --no-config --hwdec=vaapi --gpu-api=vulkan 'https://www.instagram.com/p/CNVlfkYKZwN/'
 (+) Video --vid=1 (*) (h264 640x800 30.083fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

failed to open /usr/lib64/dri/hybrid_drv_video.so
Not using hybrid_drv_video.so
[vo/gpu/vulkan/libplacebo] DRM modifier INTEL 0x2 not available for format r8. Ignoring, but expect possible corruption. Available modifiers:
[vo/gpu/vulkan/libplacebo]     INVALID
[vo/gpu/vulkan/libplacebo]     LINEAR
[vo/gpu/vulkan/libplacebo] Using legacy hacks for DMA buffers without modifiers. May result in corruption!
Cannot load libcuda.so.1
Using hardware decoding (vaapi).
AO: [pulse] 44100Hz stereo 2ch float
VO: [gpu] 640x800 vaapi[nv12]
[vo/gpu/vaapi-egl] unsupported VA image format nv12
[vo/gpu] Initializing texture for hardware decoding failed.
```

### Expected behavior

It works!

### Actual behavior

Blue screen.

### Log file

https://0x0.st/-cER.txt

### Sample files

https://0x0.st/-cEF.mp4

**Comment by LaserEyess** [comment] 2021-04-07 11:58
Downgrading to mesa 20.3 should fix this, FYI.

**Comment by jbeich** [comment] 2021-04-08 22:40
Or upgrade Mesa to 21.1 (not released yet) which has [VK_EXT_image_drm_format_modifier on Intel](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/1466).

**Comment by ojab** [comment] 2021-04-15 09:34
Mesa-21.1 (mesa-vulkan-drivers-21.1.0-0.3.20210414.15.45ae0e9.fc34.x86_64) didn't helped, the same blue screen with different error message: 
```
$ mpv --no-config --hwdec=vaapi --gpu-api=vulkan https://0x0.st/-cEF.mp4 --log-file=/tmp/mpv.log
 (+) Video --vid=1 (*) (h264 640x800 30.083fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

failed to open /usr/lib64/dri/hybrid_drv_video.so
Not using hybrid_drv_video.so
[vo/gpu/vulkan/libplacebo] vk->CreateImage(vk->dev, &iinfo, PL_VK_ALLOC, &tex_vk->img): VK_ERROR_OUT_OF_DEVICE_MEMORY (../src/vulkan/gpu.c:1182)
[vo/gpu/vulkan/libplacebo] vk->CreateImage(vk->dev, &iinfo, PL_VK_ALLOC, &tex_vk->img): VK_ERROR_OUT_OF_DEVICE_MEMORY (../src/vulkan/gpu.c:1182)
…(th same error multiple times)
Cannot load libcuda.so.1
Using hardware decoding (vaapi).
AO: [pulse] 44100Hz stereo 2ch float
VO: [gpu] 640x800 vaapi[nv12]
[vo/gpu/vaapi-egl] unsupported VA image format nv12
[vo/gpu] Initializing texture for hardware decoding failed.
AV: 00:00:02 / 00:00:12 (20%) A-V:  0.000 Cache: 9.4s/1MB
```
Full log: http://0x0.st/-A-a.log
Not sure if it's mesa or mpv bug though.

**Comment by haasn** [comment] 2021-04-15 11:01
You can try with `--gpu-debug` to be sure. But that error message makes it still seems like this is unrelated to mpv, since it's complaining about `VK_ERROR_OUT_OF_DEVICE_MEMORY`.

(Presumably, you aren't *actually* running out of device memory)

**Comment by ojab** [comment] 2021-04-15 20:59
Filled https://code.videolan.org/videolan/libplacebo/-/issues/147 about this, let's see what libplacebo devs think, looks like it could be libplacebo issue. Will report to mesa if it isn't.

**Comment by philipl** [comment] 2021-04-15 21:59
@haasn  _is_ the libplacebo dev...

**Comment by tokyovigilante** [comment] 2021-04-15 22:28
On the contrary this has actually just started working for me again with mesa from git `HEAD` (ANV DRM modifier support merged) and the Fedora 34 `intel-media-driver` package from rpm-fusion.

**Comment by ojab** [comment] 2021-04-16 08:14
>@haasn is the libplacebo dev...

:facepalm: Actually reading names helps.

**Comment by ojab** [comment] 2021-04-16 08:40
Ok, filled https://gitlab.freedesktop.org/mesa/mesa/-/issues/4653.

**Comment by andersk** [comment] 2021-04-19 23:08
`git bisect` on libplacebo implicates haasn/libplacebo@3f197a346a99ef2592d07c5a418350d1bd8eb962 “vulkan: fix vk_tex_handle_caps”.

**Comment by haasn** [comment] 2021-04-20 08:17
@andersk That check is no longer present in master though.

**Closed** 2021-05-03 22:00 UTC
Labels: os:linux

**Comment by mattst88** [comment] 2021-07-21 20:47
Did we determine that this was a bug in libplacebo rather than a bug in Mesa?

**Comment by ojab** [comment] 2021-07-21 20:55
Nah, basically I should debug mesa to determine why it fails and ain't no time for that so far, unfortunately.
libplacebo says that it's mesa, mesa doesn't react to the ticket (or do you from mesa ticket with intent to close it? Feel free to do so), no certain info to prove that someone is guilty.

But it's still reproducible on mesa-21.1.5/libplacebo-3.120.3/mpv-0.33.1.

**Comment by paulcarroty** [comment] 2021-07-22 07:47
So reopen this issue then.
Can reproduce it on mesa-21.1.4/libplacebo-3.120.3/mpv-master.

**Comment by paulcarroty** [comment] 2021-07-25 14:02
Update: recompiled mpv-master today and it's working.
