### ISSUE TITLE
MPV can’t play YouTube audio only streams (140, 251, etc.) after updating yt-dlp to 2023.03.03 (No video or audio streams selected)

### ISSUE THREAD

**Issue by Trit34** [mpv-player/mpv#11404] opened 2023-03-04 09:37 UTC
### Important Information

Provide following Information:
- mpv version: 0.35.1
- Platform and Version: Kinux, Arch Linux, up to date (2023-3-4)
- Source of the mpv binary: Arch Linux official repository (pacman)

### Reproduction steps

Copy the videos tab URL of a YouTube channel, and make it play with MPV, as `mpv --ytdl-format=140 --shuffle https://www.youtube.com/@FireflyAMVEntertainment/videos`

### Expected behavior

MPV should play the audio streams of the YT playlist in random order.

### Actual behavior

Error messages since I have updated yt-dlp to version 2023.03.03 (which fixes a throttling YT behaviour, as mentioned on these issues:
https://github.com/yt-dlp/yt-dlp/issues/6369
https://github.com/yt-dlp/yt-dlp/issues/6400

```
$ mpv --ytdl-format=140 --shuffle https://www.youtube.com/@FireflyAMVEntertainment/videos

Playing: https://www.youtube.com/watch?v=jSnIFVRjl2E
EDL specifies no segments.'
EDL parsing failed.
Error in EDL.
No video or audio streams selected.

Playing: https://www.youtube.com/watch?v=QWi5oKitpUs
EDL specifies no segments.'
EDL parsing failed.
Error in EDL.
No video or audio streams selected.

Playing: https://www.youtube.com/watch?v=A7B0LXpC96A
EDL specifies no segments.'
EDL parsing failed.
Error in EDL.
No video or audio streams selected.
```

Choosing one of the non-throttled streams (18 or 22) still works.

Plus (but it’s certainly related), drag’n’dropping YT videos thumbnails on a MPV window will result with only the best video stream played, with no audio (while both best video and audio were played fine before updating yt-dlp to 2023.03.03).

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

[output.txt](https://github.com/mpv-player/mpv/files/10887964/output.txt)

**Comment by N-R-K** [comment] 2023-03-04 09:38
Duplicate of https://github.com/mpv-player/mpv/issues/11392

**Comment by Trit34** [comment] 2023-03-04 09:41
> Duplicate of #11392

Oh? OK, thanks. Well, I just noticed it, but it’s a good thing that it is already a known bug. o/

**Closed** 2023-03-04 15:21 UTC
