### ISSUE TITLE
MacOS - Audio device underrun detected. (Audio stutter when using vo=gpu-next)

### ISSUE THREAD

**Issue by LampPrinter** [mpv-player/mpv#13676] opened 2024-03-10 02:02 UTC
### Important Information

**mpv Version**
mpv v0.37.0-525-gc7d341a7c4 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Mar 10 2024 20:29:55
libplacebo version: v6.338.2
FFmpeg version: 6.1.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100

**macOS Version:** macOS Sonoma 14.0

**Source of the mpv binary or bundle:** homebrew

**If known which version of mpv introduced the problem**
Not sure.

**hardware:**
M1 Macbook Air

### Reproduction steps
When any video is playing and if I go into some other app leaving MPV in background, there is 0.5 sec audio skip like a stutter.

It only happens when using "vo = gpu-next"
"vo = libmpv" no stutter is there.

### Expected behavior
Play without dropped audio frames.

### Actual behavior
Brief stutter in audio playback.

### Log file

[   6.881][w][cplayer] Audio device underrun detected.
[   6.887][w][cplayer] 
[   6.887][w][cplayer] Audio/Video desynchronisation detected! Possible reasons include too slow
[   6.887][w][cplayer] hardware, temporary CPU spikes, broken drivers, and broken files. Audio
[   6.888][w][cplayer] position will not match to the video (see A-V status field).
[   6.888][w][cplayer] Consider trying `--profile=fast` and/or `--hwdec=auto-safe` as they may help.
[   6.888][w][cplayer] 
[   6.888][v][cplayer] restarting audio after underrun

### Sample files
Happens on playing any local media file.

**Comment by Akemi** [comment] 2024-03-10 11:46
that's not a log file. please follow the instructions of the issue template.

**Comment by LampPrinter** [comment] 2024-03-10 15:06
> that's not a log file. please follow the instructions of the issue template.

I have modified the original post according to the template.

**Comment by Akemi** [comment] 2024-03-29 12:03
a whole log file of the problem occurring is still missing and would be helpful.

**Comment by LampPrinter** [comment] 2024-03-29 16:06
> a whole log file of the problem occurring is still missing and would be helpful.

[mpv.log](https://github.com/mpv-player/mpv/files/14806133/mpv.log)

[  10.107][w][cplayer] Audio device underrun detected.
[  10.113][v][cplayer] Change display sync audio drift: 1
[  10.114][v][cplayer] restarting audio after underrun
[  10.226][v][cplayer] Change display sync audio drift: 0
[  10.226][v][cplayer] Compensation factor: 0.990442
[  10.376][v][cplayer] Change display sync audio drift: 1

Setting "audio-buffer = 1", mitigates it to a level barely noticeable.

**Comment by Akemi** [comment] 2024-04-19 22:59
for now i am assuming this is a duplicate of #13189

**Closed by Akemi** 2024-04-19 22:59 UTC
Labels: os:mac
