### ISSUE TITLE
gpu-next: . skips alternating zero and two frames at a time when interpolating (on Wayland?)

### ISSUE THREAD

**Issue by Hello71** [mpv-player/mpv#10107] opened 2022-04-17 20:12 UTC
### Important Information

- mpv version: master (305332f8a06e174c5c45c9c4547293502ac7ecdb)
- Linux Distribution and Version: Gentoo Linux
- Source of the mpv binary: Gentoo packages
- Window Manager and version: sway 1.7 + wlroots 0.15.1
- GPU driver and version: amdgpu
- Display: 1x HDMI, 1920x1200 @ 59.950 Hz

### Reproduction steps

1. ffmpeg -f lavfi -i testsrc=duration=10:size=1280x720:rate=24:n=2 testsrc.mkv
2. mpv testsrc.mkv --no-config --vo=gpu-next --video-sync=display-resample --interpolation=yes
3. Press . repeatedly.
4. Unpause or restart, and allow video to play at least 3 seconds.
5. Press . repeatedly.

### Expected behavior

In both step 3 and step 5, displayed time increases by 4 or 5 for each press.

### Actual behavior

In step 3, displayed time increases by 4 or 5 for each press. In step 5, displayed time increase alternates between none and rapidly increasing by 4 or 5 for each press; the latter appears to be playing two frames at normal speed (24 fps).

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/8502345/output.txt). mpv was started with `--pause`, then <kbd>.</kbd> was pressed roughly once per second, then unpaused with <kbd>space</kbd>, then paused after several seconds, then <kbd>.</kbd> was pressed roughly once per second, then <kbd>q</kbd> was pressed.

### Sample files

File generated in step 1.

### Additional information

The issue persists whether using --gpu-api=opengl or --gpu-api=vulkan. It does not occur when interpolation is not enabled. I only tested --gpu-context=wayland and waylandvk, not x11. I only tested sway, not other compositors.

On my machine, the issue does not occur (within 10 seconds) when the video is set to 10 fps.

**Comment by Dudemanguy** [comment] 2022-04-18 00:01
I can't seem to reproduce this.

**Comment by Hello71** [comment] 2022-04-18 00:49
> I can't seem to reproduce this.

are you using all of the software in the description? additionally, what is your display frequency? can you try varying the frame rate? i can reproduce it with 22 fps video, but not 9, 13, or 30 fps. 28 fps changes the pattern: 6 single-frame advances, then one double-frame advance, then no frame advance, then repeat. changing the display frequency to ~75 Hz (and lowering the resolution, this is a very old monitor) fixes 22 fps but breaks 33 fps, which works at ~60 Hz.

**Comment by Dudemanguy** [comment] 2022-04-18 01:54
> using all of the software in the description?

I'm not on Gentoo but otherwise yes. amdgpu as well over here.

>what is your display frequency

59.997 Hz

>i can reproduce it with 22 fps video, but not 9, 13, or 30 fps. 28 fps changes the pattern: 6 single-frame advances, then one double-frame advance, then no frame advance, then repeat.

I've only tried a few different fps's, but I don't see this. The one thing that *might* happen is the frame step not appearing to change the number for the first press (I assume this just because it was paused at a weird time; doesn't always happen) but after that it consistently steps forward.

**Comment by Hello71** [comment] 2022-04-18 22:01
> The one thing that _might_ happen is the frame step not appearing to change the number for the first press (I assume this just because it was paused at a weird time; doesn't always happen) but after that it consistently steps forward.

I have this issue too but didn't report it because I thought it is a minor issue. I also cannot reproduce the original issue on my Arch Linux machine with iris driver. However, I have discovered that this "missing first step" is potentially more severe, and probably related: on the Arch Linux iris machine, the first step sometimes doesn't work, but then further steps work, but then certain redraws, such as displaying auto OSD, or adjusting settings (e.g. 1/2 contrast), or unfocusing and refocusing the window will sometimes cause the frame to advance without any playback control inputs.

**Comment by Dudemanguy** [comment] 2022-04-19 00:18
>but then certain redraws [. . .] will sometimes cause the frame to advance without any playback control inputs

I definitely haven't seen that happen either. If calling a redraw does indeed cause the playback to actually advance, that would be a pretty bad bug. I'd expect to to happen on any platform though since making mpv redraw is pretty trivial.

**Comment by Dudemanguy** [comment] 2023-08-09 01:24
Do know if this still occurs for you?

**Comment by Hello71** [comment] 2023-08-09 02:52
> Do know if this still occurs for you?

I can still reproduce substantially the same problem with the original instructions on Gentoo with mpv 0.36.0, sway 1.8.1, wlroots 0.16.2, and mesa 23.1.5 amdgpu, as well as Arch with the same except mesa iris. Previously, it was not always reproducible and the two frames were usually delayed by 1/24 sec, whereas now it almost always advances either zero or two frames alternately and instantly (the first of the two frames is not visible). I only tested 24 fps, not other speeds.

**Comment by Dudemanguy** [comment] 2023-08-09 03:00
That's weird. I still can't reproduce it at all. I hope I'm not misunderstanding something here, but it always adds 4 or 5 to the number for me (24 fps).

**Comment by Hello71** [comment] 2024-12-12 19:43
I haven't reproduced this in my day-to-day usage for a while now, and the previous test case is also working normally for me now. I'm happy to close this for now if nobody else is experiencing it.

**Comment by Dudemanguy** [comment] 2024-12-12 20:37
I've never been able to see this, so I will go ahead and close it.

**Closed by Dudemanguy** 2024-12-12 20:37 UTC
Labels: vo:gpu:wayland, os:linux
