### ISSUE TITLE
New UI has overlapping issues

### ISSUE THREAD

**Issue by Profpatsch** [mpv-player/mpv#3804] opened 2016-11-16 17:03 UTC
![screenshot](https://cloud.githubusercontent.com/assets/3153638/20357034/c1820204-ac26-11e6-941f-205f78525d1e.png)

On a tiling window manager, it seems to think it still uses the whole screen and doesn’t adapt the size.
Whole screen:

![screenshot](https://cloud.githubusercontent.com/assets/3153638/20357102/efdfede6-ac26-11e6-8f37-52b250dfffe5.png)

```
mpv 0.21.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.28.100
   libavcodec      57.48.101
   libavformat     57.41.100
   libswscale      4.1.100
   libavfilter     6.47.100
   libswresample   2.1.100
ffmpeg version: 3.1.4
```

**Comment by wiiaboo** [comment] 2016-11-16 17:05
Duplicate of https://github.com/mpv-player/mpv/issues/3728 and fixed in git master.

**Closed by wiiaboo** 2016-11-16 17:05 UTC
