### ISSUE TITLE
Extremely high peak frame times with hwdec=d3d11va on vo=gpu-next.

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#11863] opened 2023-06-30 05:07 UTC
### Important Information
- mpv version: [shinchiro 20230630 915701939](https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230630)
- Windows Version: WIndows 11 22621.1928
- Source of the mpv binary: [shinchiro](https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230630)
- If known which version of mpv introduced the problem: unknown.
- Possible screenshot or video of visual glitches: multiple, see below.

### Reproduction steps
Watch a video with all four combinations of `vo=gpu` vs `vo=gpu-next` and `hwdec=no` vs  `hwdec=d3d11va`.  Bring up the info panel and observe the frame times, with particular notice to the peak times.

### Expected behavior
The choice of `vo` should not affect frame times much with no shaders to compile, or at least `vo=gpu-next` should be better.

### Actual behavior
`vo=gpu-next` has worse timings than `vo=gpu` with or without hardware decoding, and in particular seems to have some bad interaction with `hwdec=d3d11va` that is 10x-ing the peak times. My video recorder is broken but these results are typical. The same behavior is observed with multiple codecs. Using `gpu-api=vulkan` with `vo=gpu-next` yeilds timings that are more normal.
`vo=gpu` + `hwdec=no` https://pomf2.lain.la/f/ahbirm2s.jpg - 1x 1x 1x
`vo=gpu` + `hwdec=d3d11va` https://pomf2.lain.la/f/38o80h1.jpg - 1.3x 1.7x 6.7x
`vo=gpu-next` + `hwdec=no` https://pomf2.lain.la/f/tkgi515a.jpg - 3.3x 2.9x 1.5x
`vo=gpu-next` + `hwdec=d3d11va` https://pomf2.lain.la/f/p2zbg4ko.jpg - 5.9x 3.6x **43.9x**
`vo=gpu-next` + `gpu-api=vulkan` https://pomf2.lain.la/f/dk8rumnb.jpg - 7.1x 3.7x 2.6x

### Log file
`vo=gpu` + `hwdec=no` https://pomf2.lain.la/f/tvrgfgr1.log
`vo=gpu` + `hwdec=d3d11va` https://pomf2.lain.la/f/ivdxevpe.log
`vo=gpu-next` + `hwdec=no` https://pomf2.lain.la/f/dzzqyugd.log
`vo=gpu-next` + `hwdec=d3d11va` https://pomf2.lain.la/f/b0rha70l.log
`vo=gpu-next` + `gpu-api=vulkan` https://pomf2.lain.la/f/e30ktl96.log

### Sample files
https://pomf2.lain.la/f/0kgbbkah.mp4
https://pomf2.lain.la/f/k1fahjqe.webm

**Comment by haasn** [comment] 2023-06-30 12:50
Can you try forcing your GPU into highest power state?

**Comment by kasper93** [comment] 2023-06-30 14:22
I will look into it, actually I were debugging unrelated issue with `hwdec-copy` variant and have some insight why this happen. I also have seen the spikes in latency when using d3d11va.

So quick recap:
* There is "delay queue" to defer reading back frames from hardware decoder. 
* This queue were restricted to `-copy` variant only in unrelated commit. Just side-tracked the change.
* While I strongly believe the queue will help with pipelining to avoid stalling on queue readback.
* Also note while peak times are spiking sometimes, you are likely not dropping/delaying any frames

I'm not sure when I will have time to test it properly. But I feel like I have good understanding what's going on.

In the meantime use `hwdec=d3d11va-copy` as it works correctly.

**Comment by sizumam** [comment] 2023-06-30 14:33
> Can you try forcing your GPU into highest power state?

As far as I know I am already doing everything I can to that end in BIOS/Windows/AMD control panel. But the test machine is a laptop, albeit plugged in, so a repro from a desktop user would be nice. I ran a bunch more tests to be sure and about 10% of the time maybe, `vo=gpu-next` with `hwdec=d3d11va` doesn't get the spikes, and also about 10% of the time `vo=gpu` with `hwdec=d3d11va` does get the spikes. So it's maybe just a driver/firmware bug on my end.

> In the meantime use `hwdec=d3d11va-copy` as it works correctly.

Indeed it does. Thank you! Frame times still seem to be about 2x on `vo=gpu-next` vs `vo=gpu`, but down to sane levels comparable to using `vo=gpu-next` and `hwdec=no`.

**Comment by kasper93** [comment] 2023-06-30 17:32
@sizumam: Could you try build from https://github.com/mpv-player/mpv/actions/runs/5425435502 (artifact at the bottom after it finishes building) 

For me it is hard to reproduce the issue, I'm interested if you see a difference with your test scenario.

**Comment by sizumam** [comment] 2023-06-30 19:00
That change does not seem to have done much of anything.
`vo=gpu` + `hwdec=no` - https://pomf2.lain.la/f/szwdurv6.png - https://pomf2.lain.la/f/h3nmydkz.txt
`vo=gpu` + `hwdec=d3d11va` - https://pomf2.lain.la/f/2wv66vik.png - https://pomf2.lain.la/f/qov34ox4.txt
`vo=gpu` + `hwdec=d3d11va-copy` - https://pomf2.lain.la/f/79jm11o.png - https://pomf2.lain.la/f/icddhqn.txt
`vo=gpu-next` + `hwdec=no` - https://pomf2.lain.la/f/smz772t1.png - https://pomf2.lain.la/f/00ow2dp1.txt
`vo=gpu-next` + `hwdec=d3d11va` - https://pomf2.lain.la/f/49b4frvo.png - https://pomf2.lain.la/f/yi6dt99l.txt
`vo=gpu-next` + `hwdec=d3d11va-copy` - https://pomf2.lain.la/f/qqfmsmd6.png - https://pomf2.lain.la/f/pzc21cni.txt
Frame times are still worse across the board (but especially with peaks) with `hwdec=d3d11va` compared to `hwdec=d3d11va-copy`  regardless of `vo`, and all the numbers are approximately the same as well. Given that, and that you can't repro, it's likely a driver issue on my end. I don't know anything about debugging drivers (if that's even possible on Windows) to tell you if it has anything to do with frame queueing issues in the first place.

**Comment by Isaacx123** [comment] 2023-07-01 03:44
Cannot reproduce on Windows 10 with a nvidia GPU even with a 1080p high bitrate video:

mpv --no-config --vo=gpu-next --gpu-api=d3d11 --hwdec=no --log-file=hwdec-no.log 0kgbbkah.mp4

![mpv-shot0002](https://github.com/mpv-player/mpv/assets/75648063/a5c5bb04-7cc3-4fd4-8899-ade0d36c1e07)

[hwdec-no.log](https://github.com/mpv-player/mpv/files/11924277/hwdec-no.log)

mpv --no-config --vo=gpu-next --gpu-api=d3d11 --hwdec=d3d11va --log-file=hwdec-yes.log 0kgbbkah.mp4

![mpv-shot0003](https://github.com/mpv-player/mpv/assets/75648063/83e7d679-0ee3-4441-8c46-0d1b1b655abf)

[hwdec-yes.log](https://github.com/mpv-player/mpv/files/11924331/hwdec-yes.log)

High bitrate video:

mpv --no-config --vo=gpu-next --gpu-api=d3d11 --hwdec=no --log-file=hwdec-no.log "Nisemonogatari NCOP 3.mkv"

![mpv-shot0001](https://github.com/mpv-player/mpv/assets/75648063/6d52cfa4-1a6e-41b0-b125-464eb24d29b9)

[hwdec-no.log](https://github.com/mpv-player/mpv/files/11924338/hwdec-no.log)

mpv --no-config --vo=gpu-next --gpu-api=d3d11 --hwdec=d3d11va --log-file=hwdec-yes.log "Nisemonogatari NCOP 3.mkv"

![mpv-shot0003](https://github.com/mpv-player/mpv/assets/75648063/9c3369c5-1f6f-4b34-9eb9-52e789bcd391)

[hwdec-yes.log](https://github.com/mpv-player/mpv/files/11924344/hwdec-yes.log)

**Comment by Jules-A** [comment] 2023-07-01 04:40
I can replicate it but the issue seems to have started after updating to KB5027293 Win10 preview driver rather than an MPV update or driver update. From your Win11 build it looks like you have the W11 version of the update. That Windows update also caused other issues with MPV like aligning the window to -1 x pixel.

**Comment by Isaacx123** [comment] 2023-07-01 05:24
Both @Jules-A and @sizumam are using an AMD GPU, could be a hardware/driver specific issue.
We need someone else on Windows with a NVIDIA GPU besides me to confirm it.

**Comment by sizumam** [comment] 2023-07-01 05:31
If it was indeed caused by a Windows update that's only three days old that would explain why I only just noticed it. Could you post your Windows version, Isaac? Want to rule out you simply not having the update yet.

**Comment by Isaacx123** [comment] 2023-07-01 05:35
Windows 10 21H2 Build 19044.3086

**Comment by sizumam** [comment] 2023-07-01 05:48
You don't have the KB5027293. If you did, you would have 19044.3155: https://support.microsoft.com/en-us/topic/june-27-2023-kb5027293-os-build-19045-3155-preview-1c50b938-6a65-4e7e-9fdd-967f391c846f

**Comment by Isaacx123** [comment] 2023-07-01 20:22
What AMD driver version are you using @sizumam and @Jules-A? I am going to try to reproduce the issue with a Vega 64.

**Comment by sizumam** [comment] 2023-07-01 20:29
31.0.14057.5006

**Comment by Jules-A** [comment] 2023-07-01 22:54
> What AMD driver version are you using @sizumam and @Jules-A? I am going to try to reproduce the issue with a Vega 64.

https://www.amd.com/en/support/kb/release-notes/rn-rad-win-23-10-01-41-vlk-extn

It's a preview driver, I installed it because it has Vulkan video extensions but Polaris didn't get them anyway... I installed it a day before the Windows update but didn't notice anything until the Windows update installed.

**Comment by Isaacx123** [comment] 2023-07-02 03:46
So I installed Windows 11 in another disk on my system and I am still not able to reproduce the issue with my NVIDIA GPU:

`Edition	Windows 11 Enterprise`
`Version	22H2`
`Installed on	‎7/‎1/‎2023`
`OS build	22621.1928`
`Experience	Windows Feature Experience Pack 1000.22644.1000.0`

`mpv --no-config --vo=gpu-next --gpu-api=d3d11 --hwdec=no --autofit=1920x1080 --log-file=hwdec-no.log "Nisemonogatari NCOP 3.mkv"`

![mpv-shot0001](https://github.com/mpv-player/mpv/assets/75648063/cd1135ca-9292-4e9a-81da-83366e5b4dcf)

[hwdec-no.log](https://github.com/mpv-player/mpv/files/11928647/hwdec-no.log)

`mpv --no-config --vo=gpu-next --gpu-api=d3d11 --hwdec=d3d11va --autofit=1920x1080 --log-file=hwdec-yes.log "Nisemonogatari NCOP 3.mkv"`

![mpv-shot0002](https://github.com/mpv-player/mpv/assets/75648063/214415ac-c3f0-40c3-882f-b7108c3a1781)

[hwdec-yes.log](https://github.com/mpv-player/mpv/files/11928650/hwdec-yes.log)

Tomorrow morning I will do some tests on the same Windows 11 install with a Vega 64 and the 23.5.2 drivers.

**Comment by Isaacx123** [comment] 2023-07-02 19:59
Well, it seems like it is an AMD related issue, maybe Microsoft botched something in the AMD driver stack with the latest update.

### **Vega 64 running 23.5.2 drivers on Windows 11 22621.1928:**

`mpv --no-config --vo=gpu-next --gpu-api=d3d11 --hwdec=no --autofit=1920x1080 --log-file=hwdec-no.log "Nisemonogatari NCOP 3.mkv"`

![mpv-shot0001](https://github.com/mpv-player/mpv/assets/75648063/0e78d3ad-ca60-4e29-8cae-b5a5c637f973)

[hwdec-no.log](https://github.com/mpv-player/mpv/files/11931249/hwdec-no.log)

`mpv --no-config --vo=gpu-next --gpu-api=d3d11 --hwdec=d3d11va --autofit=1920x1080 --log-file=hwdec-yes.log "Nisemonogatari NCOP 3.mkv"`

![mpv-shot0002](https://github.com/mpv-player/mpv/assets/75648063/0e514856-733b-47d4-8a83-be692839c6f8)

[hwdec-yes.log](https://github.com/mpv-player/mpv/files/11931253/hwdec-yes.log)

### **RTX 3060 Ti running 536.40 drivers on the same Windows 11 machine:**

`mpv --no-config --vo=gpu-next --gpu-api=d3d11 --hwdec=no --autofit=1920x1080 --log-file=hwdec-no.log "Nisemonogatari NCOP 3.mkv"`

![nv-no](https://github.com/mpv-player/mpv/assets/75648063/f991cb3a-c3ac-472f-ab83-b3302b226cfe)

[nv-hwdec-no.log](https://github.com/mpv-player/mpv/files/11931256/nv-hwdec-no.log)

`mpv --no-config --vo=gpu-next --gpu-api=d3d11 --hwdec=d3d11va --autofit=1920x1080 --log-file=hwdec-yes.log "Nisemonogatari NCOP 3.mkv"`

![nv-yes](https://github.com/mpv-player/mpv/assets/75648063/21958657-3a3e-4b3f-9eaa-6e97e5ba1f58)

[nv-hwdec-yes.log](https://github.com/mpv-player/mpv/files/11931260/nv-hwdec-yes.log)

**Comment by kasper93** [comment] 2023-07-02 20:09
Can you check if you have enabled GPU hardware scheduling, and try with it disabled?

**Comment by Isaacx123** [comment] 2023-07-02 20:24
I already swapped out the Vega 64 but yes, hardware scheduling is enabled on the Windows 11 install. 
On the Windows 10 install (see [this](https://github.com/mpv-player/mpv/issues/11863#issuecomment-1615437377) post above)  is disabled but it is an old version of Windows so it may not be relevant.
@sizumam could you check if you have GPU hardware scheduling enabled?

**Comment by sizumam** [comment] 2023-07-02 20:47
If anything that seems to have made it worse. Now I'm consistently getting peaks of ~50kus instead of 20.

**Comment by Jules-A** [comment] 2023-07-03 01:18
> Can you check if you have enabled GPU hardware scheduling enabled, and try with it disabled?

It's not even possible to enable on Win10 with Polaris at least.

>Well, it seems like it is an AMD related issue, maybe Microsoft botched something in the AMD driver stack with the latest update.

Figured as much, now I need to work out how to revert this damn update... Not sure why it's worse with gpu-next though :/

**Comment by haasn** [comment] 2023-09-03 20:03
Apparently fixed on latest AMD drivers

**Closed by haasn** 2023-09-03 20:03 UTC
Labels: os:win, down-upstream:amd

**Comment by Jules-A** [comment] 2023-09-04 04:14
> Apparently fixed on latest AMD drivers

No idea if that's what fixed it vs some libplacebo change but yeah I can't reproduce it anymore. I do have higher and less stable vsync jitter though now but it doesn't seem enough to cause delays/mistimes or A/V drift enough to be noticeable.
