### ISSUE TITLE
No picture (stays black)

### ISSUE THREAD

**Issue by spirulin** [mpv-player/mpv#5311] opened 2017-12-29 14:42 UTC
Downloaded the 2017-12-25 | 64-bit and have no picture. Black screen. Sound is working. Tried with different videos and files (mkv, avi, mpg - same thing). Downloaded the previous version from 2017-09-13 and no problems there. 

Windows 10.

**Comment by CounterPillow** [comment] 2017-12-29 15:03
thanks for not posting a log

**Comment by rossy** [comment] 2017-12-30 04:35
This might be the same issue as #5293, but it's hard to tell without a log file. Please follow the issue template.

**Comment by rossy** [comment] 2018-01-08 12:39
I'll assume this is a duplicate of #5293. @spirulin Please let us know if this is not the case.

**Closed** 2018-01-08 12:40 UTC
Labels: ignored issue template, info-needed, ms-windows
