### ISSUE TITLE
mpv with libplacebo-v6.338.1 fails when used with -hwdec=cuda -gpu-api=vulkan on Wayland

### ISSUE THREAD

**Issue by YuvrajTalukdar** [mpv-player/mpv#13031] opened 2023-12-02 22:48 UTC
- mpv- v0.37.0
- Linux Distribution- Arch
- Source of the mpv binary- flatpak
- Window Manager- Wayland
- GPU driver and version RTX3050 with nvidia-545.29.06
- screenshot
![image](https://github.com/mpv-player/mpv/assets/37207336/14625af0-8afa-4ed0-8da8-083bf8df6a56)

### Reproduction steps
I wanted to play some av1 encoded files. My igpu do not have av1 decoder so wanted to use my RTX 3050 Mobile for playing the video. I tried both in xord and wayland. Xorg works fine , even under xwayland it works fine, but under wayland libplacebo throws error. 
I have seen a similar issue posed https://github.com/mpv-player/mpv/issues/12103
The issue according to the post seemed to be resolved in libplacebo version 6.338.1. My mpv flatpak is used libplacebo 6.338.1 , still i am getting the error.
To reproduce the error just run this under wayland.
flatpak run io.mpv.Mpv test.webm -hwdec=cuda -gpu-api=vulkan 

Running 
flatpak run io.mpv.Mpv -v 
gives:-
```Not sharing "/usr/share/icons" with sandbox: Path "/usr" is reserved by Flatpak
[cplayer] Command line options: '-v'
[cplayer] mpv v0.37.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
[cplayer] libplacebo version: v6.338.1
[cplayer] FFmpeg version: n6.1
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       58.29.100
[cplayer]    libavcodec      60.31.102
[cplayer]    libavformat     60.16.100
[cplayer]    libswscale      7.5.100
[cplayer]    libavfilter     9.12.100
[cplayer]    libswresample   4.12.100
[cplayer] 
[cplayer] Configuration: meson configure build -Dprefix=/app -Dbuildtype=debugoptimized -Doptimization=2
[cplayer] List of enabled features: alsa av-channel-layout avif-muxer cdda cplugins cuda-hwaccel cuda-interop debug dmabuf-interop-gl dmabuf-wayland drm dvbin dvdnav egl egl-drm egl-helpers egl-wayland egl-x11 ffmpeg ffnvcodec gbm gl glibc-thread-name glob glob-posix gpl iconv jack javascript jpeg jpegxl lavu-uuid lcms2 libarchive libass libavdevice libbluray libdl libm libplacebo librt linux-fstatfs luajit memfd-create noexecstack pipewire posix posix-shm ppoll pulse rubberband rubberband-3 sdl2 sdl2-audio sdl2-gamepad sdl2-video shaderc sixel threads uchardet vaapi vaapi-drm vaapi-wayland vaapi-x11 vapoursynth vdpau vector vk-khr-display vt.h vulkan wayland wayland-protocols-1-27 wayland-protocols-1-31 wayland-protocols-1-32 x11 xv zimg zimg-st428 zlib
[cplayer] Reading config file /app/etc/mpv/encoding-profiles.conf
[ifo_dvdnav] Opening /app/etc/mpv/encoding-profiles.conf
[bdmv/bluray] Opening /app/etc/mpv/encoding-profiles.conf
[file] Opening /app/etc/mpv/encoding-profiles.conf
[cplayer] Applying profile 'default'...
[cplayer] Reading config file /app/etc/mpv/mpv.conf
[ifo_dvdnav] Opening /app/etc/mpv/mpv.conf
[bdmv/bluray] Opening /app/etc/mpv/mpv.conf
[file] Opening /app/etc/mpv/mpv.conf
[cplayer] Applying profile 'default'...
[cplayer] Setting option 'screenshot-directory' = '~/.var/app/io.mpv.Mpv/Pictures/mpv' (flags = 4)
[cplayer] Setting option 'v' = '' (flags = 8)
[cplayer] mpv v0.37.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
[cplayer] libplacebo version: v6.338.1
[cplayer] FFmpeg version: n6.1
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       58.29.100
[cplayer]    libavcodec      60.31.102
[cplayer]    libavformat     60.16.100
[cplayer]    libswscale      7.5.100
[cplayer]    libavfilter     9.12.100
[cplayer]    libswresample   4.12.100
[cplayer] 
[cplayer] Usage:   mpv [options] [url|path/]filename
[cplayer] 
[cplayer] Basic options:
[cplayer]  --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
[cplayer]  --no-audio        do not play sound
[cplayer]  --no-video        do not play video
[cplayer]  --fs              fullscreen playback
[cplayer]  --sub-file=<file> specify subtitle file to use
[cplayer]  --playlist=<file> specify playlist file
[cplayer] 
[cplayer]  --list-options    list all mpv options
[cplayer]  --h=<string>      print options which contain the given string in their name
[cplayer] 
[cplayer] Set property: user-data/osc/visibility="auto" -> 1
[cplayer] Set property: user-data/osc/margins={"l":0,"r":0,"t":0,"b":0} -> 1
```

### Log file
[log_mpv_output.txt](https://github.com/mpv-player/mpv/files/13537542/log_mpv_output.txt)

**Comment by Dudemanguy** [comment] 2023-12-02 23:02
Does it work without `--hwdec=cuda`?

**Comment by YuvrajTalukdar** [comment] 2023-12-02 23:10
> Does it work without `--hwdec=cuda`?

Yes it works even if -gpu-api=vulkan is used

**Comment by Dudemanguy** [comment] 2023-12-02 23:34
Duplicate of #11711 then. tl;dr: blame nvidia

**Closed by Dudemanguy** 2023-12-02 23:34 UTC
Labels: os:linux
