### ISSUE TITLE
Stuttering on samba share when not launched through terminal

### ISSUE THREAD

**Issue by scj643** [mpv-player/mpv#8171] opened 2020-10-13 04:25 UTC
### Important Information

Provide following Information:
- mpv version: `0.32.0-750-ge1536193cb`
- macOS Version: Catalina 10.15.7
- Source of the mpv binary or bundle: https://github.com/jnozsc/mpv-nightly-build/releases/tag/0.32.0-750-ge1536193cb

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Launch mpv using the app bundle and drop an mkv file from finder from an SMB share. This also happens when clicking an MKV file when set as a default.

This only happens when using the app bundle. If mpv is launched through the terminal or mpv-bundle is launched through the terminal the issue does not happen.

### Expected behavior
Smooth playback

### Actual behavior
Playback stutters and has audio device underruns detected

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/5368915/mpv.log)

**Comment by scj643** [comment] 2020-10-13 04:27
Did some more testing and launching from Finder leads to a large amount of CPU usage (120% compared to 30% on the same file.)

**Comment by scj643** [comment] 2020-10-13 04:43
Also this seems to vary from file to file (sometimes it happens for a while at the beginning, and sometimes it will happen at certain spots in the video file)

**Comment by Akemi** [comment] 2020-10-13 05:29
duplicate of #7405 and/or #4434

**Closed by Akemi** 2020-10-13 05:29 UTC
Labels: os:mac

**Comment by scj643** [comment] 2020-10-13 05:43
Setting `cache=no` in my config seems to solve the issue.
