### ISSUE TITLE
Frames are dropped in 1080/24p mode with display-resample, yet 1080/60p doesn't drop frames

### ISSUE THREAD

**Issue by killerkalamari** [mpv-player/mpv#8796] opened 2021-05-01 00:43 UTC
### Important Information

- mpv version: 0.33.1 (most recent Release tag as of April 30, 2021) https://github.com/mpv-player/mpv/tree/v0.33.1
- Linux Distribution and Version: Debian Buster (10), amd64
- Source of the mpv binary: I built mpv from the following source tarball: https://github.com/mpv-player/mpv/archive/refs/tags/v0.33.1.tar.gz
- Window Manager and version: LXDE 0.10.0
- GPU driver and version: Intel Corporation UHD Graphics 630, /dev/dri/card0, Intel Open Source Technology Center (0x8086), Mesa Project and SGI
- CPU: Intel(R) Core(TM) i5-9400 CPU (2.90GHz, 6 cores) https://ark.intel.com/content/www/us/en/ark/products/134898/intel-core-i5-9400-processor-9m-cache-up-to-4-10-ghz.html
- Motherboard: ASRock H310CM-ITX/ac https://www.asrock.com/mb/Intel/H310CM-ITXac/index.asp#Specification
- Display: Sony XBR-65X900H, connected to the HDMI port. Also recreated on Panasonic PT-AE8000U. Jitter tests were done using mpv and the instructions here https://www.rtings.com/tv/tests/motion/24p to determine that the 24p mode was working correctly on the display devices, with no 24p jitter (as expected, the test showed jitter when the displays were in 60p mode).

### Reproduction steps

1. Set 1920x1080 resolution, 60.000 vertical refresh, progressive mode.
2. Play 23.976024 (24000/1001) fps video from ram drive: ```mpv --no-config --vo=gpu --video-sync=display-resample --fs --audio-device=alsa/hdmi:CARD=PCH,DEV=0 --audio-channels=5.1 --msg-level=all=debug /dev/shm/test.mkv >/dev/shm/mpv.log 2>&1```
3. Check log and verify that there are NO frame drops.
4. Set 1920x1080 resolution, 24.000 vertical refresh, progressive mode.
5. Play the same video with the same command.
6. Check log and there are multiple frame drops.
7. Try with hardware acceleration enabled (just as a test, IMO my CPU is sufficiently powerful enough not to need it, especially as it can do 60p just fine): ```mpv --no-config --vo=gpu --video-sync=display-resample --hwdec=auto --fs --audio-device=alsa/hdmi:CARD=PCH,DEV=0 --audio-channels=5.1 --msg-level=all=debug /dev/shm/test.mkv >/dev/shm/mpv.log 2>&1```
8. Check log and there are still multiple frame drops.

### Expected behavior

Expected that ```--video-sync=display-resample``` would have played back the 24000/1001 fps video as 24.000 fps and resampled the audio to compensate, with no dropped frames. Expectation based on my understanding of this page: https://github.com/mpv-player/mpv/wiki/Display-synchronization#user-content-display-sync

### Actual behavior

Multiple frame drops in 24p mode, while there were no frame drops in 60p mode.

### Log file

1920x1080x60p, no dropped frames: [mpv_60p.log.txt](https://github.com/mpv-player/mpv/files/6408668/mpv_60p.log.txt)

1920x1080x24p, 6 dropped frames: [mpv_24p.log.txt](https://github.com/mpv-player/mpv/files/6408666/mpv_24p.log.txt)

1920x1080x24p, with hwdec=auto, still 6 dropped frames: [mpv_24p_hwdec-auto.log.txt](https://github.com/mpv-player/mpv/files/6408667/mpv_24p_hwdec-auto.log.txt)

### Sample files

Source used is 23.976024 fps (24000/1001) with DTS-HD Master Audio from a MakeMKV backup of my Harry Potter 7 Blu-ray, then cut to a one minute duration using MKVToolNix GUI. I found it to be a good clip for testing because I don't need to seek the video, dropped frames cause visible hiccups in the slowly approaching WB logo, and the one minute length is also long enough for the frame drops to reliably pile up. I verified that the original Blu-ray looks good, and also verified that the mkv clip (as well as the mkv of the entire movie) plays without visual problems via USB on my LG BD630. https://mega.nz/file/cd0C2R4D#uz7gEBQYH5tXFMr10HLwDxqaTda2YD0tgV2NCUnLR88

**EDIT**: Renamed logs to have ".txt" suffix.

**Comment by killerkalamari** [comment] 2021-05-01 06:36
I tried it out on a different system running Ubuntu 18.04, which had 0.29.1, and there were no dropped frames on 24p. Then, I compiled 0.33.1 for it (using mpv-build), and that worked too (still Intel graphics, although different CPU and motherboard).

So then I compiled 0.33.1 again for Debian Buster on the HTPC (the system in my bug report), and it dropped frames on 24p just like before (so it wasn't related to the tarball). 

I then booted the HTPC off a Ubuntu 18.04 live image and installed 0.33.0 from a PPA: ```sudo add-apt-repository ppa:mc3man/mpv-tests```. Amazingly, there were no dropped frames on 24p!

I haven't yet narrowed down the exact cause, but apparently there is either an important difference between Debian Buster and Ubuntu 18.04, or I could possibly have a bad configuration on my HTPC. My current plan is to try a Debian live image, and if that fails, then I can try progressively newer versions of Ubuntu live and see if I can get the problem to appear in one of them.

**Comment by killerkalamari** [comment] 2021-05-01 09:23
Maybe not quite as solved as I thought, but now I might have an idea of whats going on. After switching to MATE I noticed screen tearing in a pan shot. Using MATE Tweak I switched from Marco (Adaptive compositor) to Marco (Compton GPU compositor). That fixed the screen tearing, but the dropped frames are back. Seems like the GPU compositor is interfering with mpv. Hopefully there's a way to have both no tearing and no dropped frames.

**Comment by ValZapod** [comment] 2021-05-04 03:35
> Expected that `--video-sync=display-resample` would have played back the 24000/1001 fps video as 24.000 fps

No, what, why? 😒😒😒

**Comment by ValZapod** [comment] 2021-05-04 03:50
> mkv clip (as well as the mkv of the entire movie) plays without visual problems via USB on my LG BD630.

Why mkv?? WHY NOT mp4? You mkv is VFR (variable framerate) and thus is not working and will never work. Use mp4, please. You can check for VFR by:

ffmpeg -i file -vf vfrdet -an -f null -

**Comment by killerkalamari** [comment] 2021-05-04 05:04
I believe I've solved this problem, although I'm going to monitor for a bit longer before closing. 

First I tried wayland (Gnome Shell and mutter). One thing I needed to fix in order to get wayland working was that I was getting a black screen post grub. I'd had intermittent problems in xorg in the past with this too with my TV coming through my AV receiver. I decided not to complicate my initial bug report with this detail, because xorg (and wayland too) were fine with the TV plugged into the HTPC directly and I was still getting the glitches that way (so the receiver was not a factor). But for a final solution I needed it to run through the receiver first.

This was solved by appending `video=HDMI-A-1:e` to `GRUB_CMDLINE_LINUX_DEFAULT` in /etc/default/grub and then running `update-grub` and rebooting. Wayland was pretty good on paper: it wasn't dropping frames in the log (display-resample was doing its job) and didn't have any tearing. However, it was still clearly glitching and jumping during logo playback, so it wasn't truly solved.

The reason I mention the black screen thing all is that I had tried the deprecated (obsolete) intel driver in the past (been using modesetting), but when I got the black screen I assumed it was due to the obsolete driver (my CPU and motherboard didn't even exist in 2016 when it was already deprecated). However, after fixing wayland with it, I decided on whim to try the intel driver again (by installing xserver-xorg-video-intel).

It worked! Under LXDE I now have no dropped frames, no tearing, and no visual glitching. This is with the command line options in step 2 of my original post. I was expecting to have to put various intel driver options in xorg.conf (DRI, TearFree, TripleBuffer, etc), but in my case I didn't need any of that. I'm not sure if I even need much in xorg.conf either, but since I do have one and things are working I figure why fix what isn't broken? So here are the contents of /etc/X11/xorg.conf for posterity (I realize you can use various files and directories for xorg settings... call it an oldschool option):

```
Section "Device"
	Identifier "Intel Graphics"
	Driver "intel"
EndSection

Section "Monitor"
	Identifier "HDMI-1"
	Option "DPI" "34 x 34"
	Option "DPMS" "false"
EndSection
```

It's my understanding that someday maybe the modesetting stuff will be improved to fix the screen tearing too. But for now, the obsolete drive seems to be doing what I need.

**Comment by Dudemanguy** [comment] 2022-01-18 22:46
Appears to be a duplicate of #7106 (same symptoms and fix).

**Closed by Dudemanguy** 2022-01-18 22:46 UTC
Labels: os:linux, vo:gpu:x11, vo:gpu:opengl

**Comment by killerkalamari** [comment] 2022-01-19 03:31
@Dudemanguy I briefly tried wayland while searching for a solution, but that was a glitchy mess. The fix in https://github.com/mpv-player/mpv/issues/8796#issuecomment-831684588 (above) is for vanilla xorg. It might ultimately still be a duplicate, but I thought it important to clarify that this fix is for xorg for anyone else who might stumble onto this bug report.
