### ISSUE TITLE
Default to video=no if in tty

### ISSUE THREAD

**Issue by 586697** [mpv-player/mpv#8772] opened 2021-04-24 18:25 UTC
Hi, whenever I play video files in the tty, it errors out with "Video: no video" (which is what it should do, I guess), but I'd like to play only the audio in this case. Are there any existing workarounds to do this, instead of passing the --no-video/video=no/vo=null flags everytime?

**Comment by Dudemanguy** [comment] 2021-04-25 17:13
Actually, I could argue that it should default to the drm context which should work just fine. That said, the drm context is explicitly coded to ignore autoprobing. Unsure if there's a reason for this though (nvidia)?

**Comment by StacktraceException** [comment] 2021-05-04 16:34
No, it should default then to the best vo which is suported by the terminal like vo=tct or at least vo=caca 
video=no is wrong,

**Comment by Akemi** [comment] 2021-05-07 18:57
possible duplicate of #7859?

**Comment by Dudemanguy** [comment] 2021-07-21 20:26
Well as for the feature request, the autoprobing behavior certainly won't change anytime soon so if you're in tty you'll hit whatever is first supported (possibly `displayvk`since the `drm` context is coded to ignore the autoprobe). If you don't always want to add `--no-video`, you could write a short lua script that turns the video off if the gpu-context and/or vo value is one of the backends you don't actually want (AKA not x11 or wayland).

**Closed by Dudemanguy** 2021-07-21 20:26 UTC
Labels: core:option-param-conf, core:video, meta:question, meta:rfc
