### ISSUE TITLE
Webdav videos not playing

### ISSUE THREAD

**Issue by SnarkySarky** [mpv-player/mpv#14191] opened 2024-05-20 19:57 UTC
### mpv Information

```bash
mpv v0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Apr 18 2024 06:31:17
libplacebo version: v6.338.2
FFmpeg version: n6.1.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```

### Other Information

- Linux version: Arch Linux
- Kernel Version: 6.9.1-arch1-1
- GPU Model: NVIDIA Corporation AD104 [GeForce RTX 4070 Ti] [10de:2782] (rev a1)
- Mesa/GPU Driver Version: 4.6.0 NVIDIA 550.78
- Window Manager and Version: KDE Plasma 6
- Source mpv: pacman
- Introduced in version: the one im using

### Reproduction Steps

I've mounted my Alldebrid webdav folder in Dolphin and try to play video files (mp4, mkv) but mpv only loads for like 3 second then closes

### Expected Behavior

video just playing like in windows ( also mounted the folder in windows)

### Actual Behavior

after starting video mpv loads for few second then loses

### Log File

[output.txt](https://github.com/mpv-player/mpv/files/15381289/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [ ] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [ ] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by kasper93** [comment] 2024-05-20 20:21
I unchecked two items for the checklist, please update log file according to the instructions.

**Comment by ruihe774** [comment] 2024-05-20 20:22
duplicate of #8731

**Comment by Dudemanguy** [comment] 2024-05-22 20:18
Shouldn't this have already worked? mpv.desktop includes webdav in the list of protocols already and supposedly KDE uses that.

**Closed** 2024-06-07 18:33 UTC
Labels: os:linux
