### ISSUE TITLE
Replace youtube-dl with a fork

### ISSUE THREAD

**Issue by NoakPalander** [mpv-player/mpv#9093] opened 2021-08-07 12:10 UTC
### Expected behavior of the wanted feature
For it to be able to play age restricted videos by running e.g `mpv https://youtube.com/etc/etc`. Currently doesn't work with youtube-dl that mpv relies on, however there's a fork called [yt-dlp](https://github.com/yt-dlp/yt-dlp) on github that solves this.

**Comment by sfan5** [comment] 2021-08-07 12:13
You can already change the executable mpv calls to `yt-dlp`, there's nothing we have to do for this to work.
duplicate of #8665

**Closed by sfan5** 2021-08-07 12:13 UTC
Labels: meta:feature-request

**Comment by snylonue** [comment] 2021-08-07 12:16
try [`--ytdl_path`](https://mpv.io/manual/master/#options-ytdl-path) though I don't know if it will work

**Comment by garoto** [comment] 2021-08-07 13:16
It's a script-opt: --script-opts=ytdl_hook-ytdl_path=yt-dlp

**Comment by NoakPalander** [comment] 2021-08-07 15:33
Was unaware that it was a duplicate, sorry for that. And also thank you for pointing out the script-opt flag.

**Comment by mradalbert** [comment] 2021-09-02 10:51
youtube-dl maintainers went silent for 3 months and developement is non existent right now. Many users and devs migrated to yt-dlp already, so it would be preferable if mpv at least tried to use yt-dlp in absence of youtube-dl by default without need of modifying scripts by user, as future of youtube-dl it uncertain at this point.

**Comment by mradalbert** [comment] 2021-09-02 10:54
https://github.com/ytdl-org/youtube-dl/issues/29753

**Comment by mradalbert** [comment] 2021-09-02 11:13
Linux users can install mpv + yt-dlp using GUI package manager (yt-dlp is at least in Arch User Repository) and modifying scripts or installing additional wrapper worsens experience for new/inexperienced users.
