### ISSUE TITLE
VA-API swapped colors when used with vo=opengl, possible fix.

### ISSUE THREAD

**Issue by roboman2444** [mpv-player/mpv#1821] opened 2015-04-15 05:12 UTC
I know this issue has been brought up before, and i know a temporary workaround is to use vaapi-copy.
However, cant this also be fixed by swapping the colors in the opengl shaders? This should be much more efficient than vaapi-copy.

**Comment by wm4** [comment] 2015-04-15 12:56
Did you try with latest git master?

Is this with the xvba driver?

No, I won't add a bad hack just because an unmaintained driver does it.

**Comment by haasn** [comment] 2015-04-15 14:39
Perhaps something to the effect of “override channel order” could be added to ```vf_format```? I mean, it's already the place for “override all metadata”.

**Comment by vliaskov** [comment] 2015-06-26 09:19
Was this fixed with a particular commit? I can't reproduce it with ATI/fglrx driver (--hwdec=vaapi --vo=opengl ) . I have another gstreamer application (gstreamer -based) that exhibits the color problem though. I was wondering if it's a driver/libva problem or if it was solved at the application level for mpv.

**Comment by wm4** [comment] 2015-06-26 09:25
We dropped the OpenGL interop (which was inefficient, caused lots of problems, never worked right), and replaced it with outputting the vaapi frame on a GL mapped pixmap. See commit a18dc01655b86de040b5a3a02ffcad694b843b17. This was applied only ten days before this issue was opened, but only to master. Assuming that the reporter used a release (and not git master), and considering that you seem to confirm that it works, I'll just close this and consider it fixed.

(I'm rather surprised that it doesn't work with gstreamer, though. Intel devs are using gstreamer, so support for vaapi tends to be best in gstreamer.)

**Closed by wm4** 2015-06-26 09:25 UTC

**Comment by vliaskov** [comment] 2015-06-26 10:04
thanks for the explanation. Well, ati vaapi (both radeon and fglrx) looks more unstable than intel vaapi, at least in my tests (gstreamer vaapi does work for intel drivers)
