### ISSUE TITLE
HEVC encoded videos with cscale=ewa_lanczos messes up color channels

### ISSUE THREAD

**Issue by spaghetti-** [mpv-player/mpv#4734] opened 2017-08-08 00:32 UTC
### mpv version and platform
mpv 12cafdc (C) 2000-2017 mpv/MPlayer/mplayer2 projects (`HEAD` as of now)
ffmpeg version: git-2017-08-07-1bef008

Platform: macOS 10.12.5 
### Reproduction steps
Play back an HEVC encoded video with `cscale=ewa_lanczos` inside your configuration.
### Expected behavior
Colors channels aren't swapped.

![screen shot 2017-08-08 at 8 25 05 am](https://user-images.githubusercontent.com/2093506/29051156-395db770-7c13-11e7-8292-5c75e4efce83.png)

### Actual behavior
In windowed mode

![screen shot 2017-08-08 at 8 24 53 am](https://user-images.githubusercontent.com/2093506/29051174-4c168cfc-7c13-11e7-8f40-3b9bda44e204.png)

In fullscreen mode
![screen shot 2017-08-08 at 8 25 17 am](https://user-images.githubusercontent.com/2093506/29051192-65b4f680-7c13-11e7-8849-dc1ecd0555af.png)

### Log file

https://bpaste.net/show/7c367e9e08a2 (with cscale)

http://bpaste.net/show/4368d674f982 (without cscale)

**Comment by haasn** [comment] 2017-08-08 00:40
Seems to be a duplicate of #4607.

**Closed by haasn** 2017-08-08 00:40 UTC
