### ISSUE TITLE
Blue flashing when playing HEVC video.

### ISSUE THREAD

**Issue by kkanungo17** [mpv-player/mpv#5839] opened 2018-05-18 01:11 UTC
### mpv version and platform
mpv d65b6cf
ffmpeg N-45717-g380ca1bc0
macOS High Sierra 10.13.4
Mid-2010 Unibody MacBook

### Reproduction steps
Play HEVC video.

### Expected behavior
Video plays normally.

### Actual behavior
Video plays with the screen flashing blue continuously.

### Log file
https://www.pastery.net/fjrcjt/

**Comment by tmm1** [comment] 2018-05-18 01:16
Duplicate of #5755 

Please try the ffmpeg patch listed there: https://github.com/mpv-player/mpv/issues/5755#issuecomment-390000020

**Closed by tmm1** 2018-05-18 01:16 UTC
