### ISSUE TITLE
mpv does not enter full screen on extended display

### ISSUE THREAD

**Issue by forthrin** [mpv-player/mpv#11364] opened 2023-02-24 11:27 UTC
### Important Information

Provide following Information:
- mpv version: 4f6d7a
- macOS Version: 13.2.1
- Source of the mpv binary or bundle: mpv-build
- If known which version of mpv introduced the problem: N/A
- Possible screenshot or video of visual glitches: N/A

### Reproduction steps

1. Extended display: MacBook Air M1
2. Main display: Apple Cinema Display 30"
3. `$ mpv --config=no <any-video-or-image>`
4. Drag window to extended display
5. Press `f`

### Expected behavior

Window should enter full screen on extended display.

### Actual behavior

Window pops back on the main display (and not in full screen to boot). PS! It seems to have the same X/Y position as it had on the extended display.

### Log file

[mpv.log.gz](https://github.com/mpv-player/mpv/files/10823545/mpv.log.gz)

### Sample files

N/A

**Comment by Akemi** [comment] 2023-02-24 16:29
duplicate of #9697

**Closed by Akemi** 2023-02-24 16:29 UTC
Labels: os:mac
