### ISSUE TITLE
Slow image rendering when using fixed size window (via --geometry)

### ISSUE THREAD

**Issue by smackesey** [mpv-player/mpv#9115] opened 2021-08-13 20:52 UTC
### Important Information

Provide following Information:
- mpv version: 0.33.1
- macOS Version: 11.5.2
- Source of the mpv binary or bundle: Homebrew

### Reproduction steps

Take a folder with a few jpg images `images`, and try with the following `--geometry` settings:

a. no setting ("none")
b. `--geometry=50+50` ("fixed pos")
c. `--geometry=1000x1000` ("fixed size")
d. `--geometry=1000x1000+50+50` ("fixed pos/size")

```
$ mpv --no-config --pause=yes <geometry> /path/to/images
```

Manually cycle through the images.

### Expected behavior

No matter the geometry setting, the images should render almost instantly.

### Actual behavior

Geometry settings "none" and "fixed pos" render successive images instantaneously. "fixed size" has some lag (maybe 500 ms) and "fixed pos/size" is slowest (maybe 750 ms).

### Log file

Here are logs for slowest case (fixed pos/size) and no geometry setting (none).

[fixed-pos-size.log](https://github.com/mpv-player/mpv/files/6985107/fixed-pos-size.log)
[none.log](https://github.com/mpv-player/mpv/files/6985109/none.log)

**Comment by avih** [comment] 2021-08-13 21:11
CC @Akemi 

Well, I don't think I can identify anything at the logs. Looks like the image is set quickly, but maybe for some reason is not visible on screen, and becomes visible after some time (without traces at the logs...)?

What if you save this as `osd-timer.lua`:
```lua
mp.add_periodic_timer(0.1, function() mp.osd_message(mp.get_time()) end)
```
And load it with `--script=osd-timer.lua` while doing the same images test with geometry position and size?

**Comment by smackesey** [comment] 2021-08-13 21:19
Thanks @avih (BTW, it immediately disconnected me off IRC as soon as I posted a pastebin link to a log-- not sure if that was just coincidence or for some reason it banned me for pasting a link)?

Weirdly, when I add this script it totally eliminates the lag issue. And I can confirm the issue still exists when I don't load the script. It must have something to do with the script drawing the time over the images?

**Comment by avih** [comment] 2021-08-13 21:24
> It must have something to do with the script drawing the time over the images?

Yeah. The thing is, as far as I can tell, the log shows that mpv displays the image instantly (hence mpv thinks the image is now displayed), but for some reason you don't see it. So adding the OSD messages every 100 ms forces mpv to redraw the window for each new OSD number - which includes the image in case it wasn't visible till now.

Could be some race condition, but weird that it only happens with geometry size. Anyway, hopefully @Akemi would know more - he's the mpv macOS maintainer.

**Comment by avih** [comment] 2021-08-13 21:31
> it immediately disconnected me off IRC as soon as I posted a pastebin link to a log-- not sure if that was just coincidence

Most probably coincidence. I don't think there's autoban, and people post links and logs frequently on IRC.

**Comment by smackesey** [comment] 2021-08-13 22:00
Thanks, is there a way to trigger the redraw without drawing anything (or maybe just drawing something maximally unobtrusive) over my images that I can use as a holdover until a fix?

**Comment by avih** [comment] 2021-08-13 22:22
You could try something like this (untested):
```lua
mp.register_event("file-loaded", function()
    mp.add_timeout(0.1, function()
        mp.osd_message(".")
        mp.osd_message("")
    end)
end)
```

Or maybe even without the internal timeout.

However, this will remove any OSD message you get when the file loads (like the file name).
You can address this by using `mp.create_osd_overlay` https://mpv.io/manual/master/#lua-scripting-mp-create-osd-overlay%28format%29 (which creates a new OSD "plane" independent of the main OSD) instead of using `mp.osd_message`.

You should read the scripting docs.

Regardless, that looks like a bug in mpv, and it should hopefully be fixed in mpv.

**Comment by smackesey** [comment] 2021-08-13 22:33
Thanks, for anyone else encountering this issue till its fixed, here is my current working solution:

```
local i = 0
local function blank_message()
  i = i + 1
  return i % 2 == 0 and ' ' or '  '
end
mp.add_periodic_timer(0.1, function() mp.osd_message(blank_message()) end)
```

It just alternates a double and single space, you have to alternate or it doesn't work.

**Comment by avih** [comment] 2021-08-13 23:02
> here is my current working solution:

It might works for you, but my guess is that it won't for most people, because it basically disables the OSD due to the never-ending dummy OSD messages - which overwrite/remove any real OSD message immediately.

**Comment by Akemi** [comment] 2024-02-29 17:58
is this still a problem? i am not able to reproduce this and tbh i thought it should have been fixed by https://github.com/mpv-player/mpv/commit/0cea7b9ffbcf23c774a881f5d1d14f2fbbd86d5b though this is included in the mpv version you tried.

**Comment by smackesey** [comment] 2024-03-01 18:58
No longer an active user of mpv and have forgotten context here so feel free to close.

**Comment by Akemi** [comment] 2024-03-01 19:04
okay, thank you for the reply. 

closing this, if this problem still occurs please open a new issue.

**Closed by Akemi** 2024-03-01 19:04 UTC
Labels: os:mac
