### ISSUE TITLE
Problem with playing 720p video while seeking forward/backward with VAAPI enabled.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#8198] opened 2020-10-22 16:28 UTC
### Important Information

Provide following Information:
- mpv version
mpv 0.32.0-781-gdc0e9644cd
- Linux Distribution and Version
```Name: Manjaro Linux
Version: 20.2 (Nibia)
Codename: Nibia
Kernel: 5.9.1-2-MANJARO
```
- Source of the mpv binary
http://aur.archlinux.org/packages/mpv-build-git
- If known which version of mpv introduced the problem
No
- Window Manager and version
mutter 3.38.1-1
- GPU driver and version
Mesa Gallium driver 20.2.1 for Radeon RX 580 Series (POLARIS10, DRM 3.39.0, 5.9.1-2-MANJARO, LLVM 10.0.1)
- Possible screenshot or video of visual glitches
https://youtu.be/hqysR609dsg
I forgot to add --no-config in this video, but it does happen with --no-config.
### Reproduction steps

1. Play 720p videos on 1080p screen with VAAPI enabled. (It both happens on full screen and window mode)
2. Seek forwark/backward.

### Expected behavior
No glitches.
### Actual behavior
It has glitches.
### Log file

https://0x0.st/iDkw.txt

### Sample files

Any 720p videos.

**Comment by CounterPillow** [comment] 2020-10-23 12:16
This is a recent AMD regression, I experience it too. Unrelated to mpv, happens inside any application using VAAPI acceleration.

**Comment by laichiaheng** [comment] 2020-10-23 12:33
@CounterPillow Thanks for the information, thanks.

**Comment by lukestateson** [comment] 2020-10-31 14:36
Is this related to Linux kernel?

**Comment by CounterPillow** [comment] 2020-10-31 23:02
No, it happens on both latest stable kernel and the LTS kernel. The problem is probably within mesa.

Judging by how long this has been around for, I'd assume this is a regression in mesa 20.2.0.

**Comment by CounterPillow** [comment] 2020-11-01 01:01
I've built a mesa 20.1.x and installed it, and can indeed confirm now that mesa 20.2.0 is the culprit.

**Comment by Akemi** [comment] 2020-11-01 11:00
can we close this issue or does anything speak against it?

**Comment by lukestateson** [comment] 2020-11-01 12:14
I think it's better to create a new issue in Arch Linux bugtracker: https://bugs.archlinux.org/?project=1&string=mesa

Manjaro Linux probably is using same builds of mesa from arch linux repos.

This is not related to mpv.

**Comment by CounterPillow** [comment] 2020-11-01 13:36
It's already been reported upstream https://gitlab.freedesktop.org/mesa/mesa/-/issues/3681

And no, reporting it to the distro bugtracker is pointless.

So yeah you can close this, Akemi.

**Closed** 2020-11-01 14:34 UTC
Labels: os:linux, upstream, upstream:mesa
