### ISSUE TITLE
stats' page 4 would cause crash

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#9227] opened 2021-09-20 13:21 UTC
### Important Information

Provide following Information:
- mpv version
mpv-x86_64-20210919-git-560e6c8
- Windows Version
win10 21h1
- Source of the mpv binary
shinchiro
- If known which version of mpv introduced the problem
0905 works well.

### Reproduction steps

1. run mpv
2. load stats' page 4

### Expected behavior
No crash.

### Actual behavior
mpv crashed.

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/7195966/mpv.log)

**Comment by avih** [comment] 2021-09-20 14:57
Thanks. I can reproduce with `mpv --no-config --idle --force-window`. It has issues with stats page 4, but not generally with libass, e.g. the OSC works fine.

This is _probably_ a new libass issue. I'm discussing it with the libass guys.

**Comment by avih** [comment] 2021-09-20 16:35
> Thanks. I can reproduce with `mpv --no-config --idle --force-window`. It has issues with stats page 4, but not generally with libass, e.g. the OSC works fine.
> 
> This is _probably_ a new libass issue. I'm discussing it with the libass guys.

So, what I was reproducing wasn't actully crash/exit, but rather a hang of the stats.lua script (but when a script hangs, mpv keeps working, but it can't quit).

This does not seem to be a libass issue, because I went back to a few months old libass commit, and the issue remains.

However, as far as I can tell, the hang was a luajit issue.

Luajit 27ee3bc (branch 2.1 HEAD about 6 hours ago) was hanging for me, while 28440544 (current 2.1 HEAD from about 2 hours ago) doesn't hang for me. I went back and forth at least twice, and was able to reproduce the hang/fix.

I don't know where the luajit issue started, because I don't build it daily. It's possible that it was introduced after 2021-09-05 (the last working shinchiro build) and 2021-09-12 (the first crashing shinchiro build).

@shinchiro can you try to reproduce the OP issue with your 2021-09-19 build, update to luajit 2.1 HEAD (I tested 28440544) and confirm that the issue is fixed?

**Comment by avih** [comment] 2021-09-20 22:08
> The crash is indeed a bug in libass

Right, but the luajit issue is also a thing regardless.

By quite some luck, I encountered both issues together, both only happen with stats page 4 and not with the osc, where the libass issue crashes mpv, and the luajit issue hangs stats.lua when displaying stats page 4 (and again, the osc works fine).

So it took us some time to figure out that there are actually two independent issues.

Thanks to the libass guys for figuring this out. A fix should hopefully posted soon at the libass repo, and the luajit issue got fixed already at the 2.1 branch.

**Comment by avih** [comment] 2021-09-22 00:37
Should be fixed at the next build.

@shinchiro we noticed that FreeType commits are somewhat fast and loose. The specific commit which changed the allocation and caused the libass crash is OK - it was libass fault, but there are other commits which could be buggy in master.

I suggest you build with FreeType release versions rather than master from now on.

**Closed by avih** 2021-09-22 00:37 UTC
Labels: os:win
