### ISSUE TITLE
[swresample] libswresample failed to initialize.

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#13669] opened 2024-03-08 14:33 UTC
### Important Information
- mpv version:
```
mpv v0.37.0-514-g78447c4b Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Mar  8 2024 12:17:49
libplacebo version: v7.347.0 (v6.338.0-97-g2f06c04-dirty)
FFmpeg version: N-114078-g71e871280
FFmpeg library versions:
   libavutil       59.1.100
   libavcodec      61.1.100
   libavformat     61.0.100
   libswscale      8.0.100
   libavfilter     10.0.100
   libswresample   5.0.100
```
- Windows Version:
```
Edition	Windows 10 IoT Enterprise LTSC
Version	21H2
Installed on	‎21/‎10/‎2023
OS build	19044.4046
Experience	Windows Feature Experience Pack 1000.19053.1000.0
```
- Source of the mpv binary: https://github.com/zhongfly/mpv-winbuild/releases
- If known which version of mpv introduced the problem:  Yes
```
mpv-x86_64-v3-20240308-git-78447c4 = Issue
mpv-x86_64-v3-20240307-git-a13a674 = No Issue
```
- GPU model, driver and version:  
```
NVIDIA GeForce GTX 1650
Studio Driver 551.61
```

### Reproduction steps
```
mpv --no-config test.mp4 --log-file=~~/Log.txt
```

### Expected behavior
Audio working

### Actual behavior
Audio not working
```
[ffmpeg] SWR: Input channel layout "" is invalid or unsupported.
[swresample] Cannot open Libavresample context.
[swresample] libswresample failed to initialize.
Cannot convert decoder/filter output to any format supported by the output.
```

### Log file
[Log.txt](https://github.com/mpv-player/mpv/files/14539306/Log.txt)

**Comment by llyyr** [comment] 2024-03-08 14:37
Duplicate of #13662 and fixed by #13665

**Closed** 2024-03-08 14:55 UTC
Labels: os:win
