### ISSUE TITLE
--vo=direct3d, direct3d_shaders

### ISSUE THREAD

**Issue by c384mb** [mpv-player/mpv#2436] opened 2015-10-30 17:37 UTC
Only one command: --vo=direct3d or --vo=direct3d_shaders mpv runs but there is no picture and not see mpv. But mpv have in the Task Manager. Mpv appears for one second and disappears from view but have mpv in tasks manager.

**Comment by c384mb** [comment] 2015-10-30 17:38
0.12.0-git-5b7d0fb

**Comment by kevmitch** [comment] 2015-10-30 21:24
duplicate of #2434.

**Closed by kevmitch** 2015-10-30 21:24 UTC
