### ISSUE TITLE
Adjust subtitle timing separately for secondary and primary tracks

### ISSUE THREAD

**Issue by ddevault** [mpv-player/mpv#5074] opened 2017-11-04 02:11 UTC

**Comment by timofonic** [comment] 2017-11-09 23:41
@SirCmpwn Would you please like to elaborate on it a bit more? I'm curious to understand what you mean about exactly :)

**Comment by SirCmpwn** [comment] 2017-11-09 23:41
If you speficy a secondary subtitle track (with --secondary-sid), you can play two subtitle tracks at once. I would like to adjust the subtitle delay for each track separately.

**Comment by CounterPillow** [comment] 2019-09-20 20:56
Duplicate of #2629

**Closed by CounterPillow** 2019-09-20 20:56 UTC
Labels: feature request
