### ISSUE TITLE
raspberry pi 3 B mouse disappears, ctrl + and alt 1/2/3 not working

### ISSUE THREAD

**Issue by enricoT** [mpv-player/mpv#3289] opened 2016-06-27 09:24 UTC
### mpv version and platform

 mpv
mpv git-9ca1592 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sat Jun 25 21:31:10 CEST 2016
ffmpeg library versions:
   libavutil       55.27.100
   libavcodec      57.48.101
   libavformat     57.40.101
   libswscale      4.1.100
   libavfilter     6.46.102
   libswresample   2.1.100
ffmpeg version: 3.1

Linux 4.4.14-1-ARCH #1 SMP Sun Jun 26 12:17:30 MDT 2016 armv7l GNU/Linux
### Reproduction steps

any movie
### Expected behavior

automatic detection of threads/core and sync audio according with hardware limits,  if i touch movie with mouse i should see pointer and controls in x system and should be posssible to resize window.
### Actual behavior

i must run mpv from console, if run from file manager i cannot control the job until is done, no pause no control keyboard, if video is full screen only possible to wait until movie is done, keyboard control is possible only if mouse focus on free screen, impossible to resize window only original or full screen from shortcut f alt 1 alt2 disabled, if i touch with mouse movie,  mouse disappears.
### Log files

Make a log file made with -v or --log-file=output.txt, paste it to sprunge.us,
and replace this text with a link to it.

**Comment by lachs0r** [comment] 2016-11-06 01:26
Duplicate of #2532.

**Closed by lachs0r** 2016-11-06 01:26 UTC

**Comment by ghprod** [comment] 2017-08-08 04:59
#2532 is closed too :(
