### ISSUE TITLE
Caching next song from the playlist for a gapless network playback. 

### ISSUE THREAD

**Issue by ZaxonXP** [mpv-player/mpv#7436] opened 2020-02-05 12:27 UTC
If I create a playlist of songs from YouTube links, then the playback will not be gapless as the next song has to be downloaded/cached, which takes some time (depends on the internet connection speed). Is it possible to run the MPV player in such way that it will always precache the next song from the playlist if playlist contains network accessible resources?

**Comment by CounterPillow** [comment] 2020-02-05 13:39
Use `--prefetch-playlist`. See https://mpv.io/manual/master/#options-prefetch-playlist

**Comment by CounterPillow** [comment] 2020-02-05 13:40
Though I guess this doesn't work with YouTube URLs, hmmm.

**Comment by snylonue** [comment] 2020-02-16 11:43
`--merge-files` may of some help

**Comment by wm4** [comment] 2020-02-16 11:57
That will work even less in this case.

**Comment by zaza42** [comment] 2020-04-05 02:19
Try  [ytdl prefetch resolver.lua](https://gist.github.com/bitingsock/f9a87ea158035d4a36899b559d611228) script.

**Comment by allanlaal** [comment] 2021-02-05 22:21
this is a duplicate of #6437

**Comment by allanlaal** [comment] 2021-02-05 22:23
> Try [ytdl prefetch resolver.lua](https://gist.github.com/bitingsock/f9a87ea158035d4a36899b559d611228) script.

the author says this does not work:
https://github.com/mpv-player/mpv/issues/6437#issuecomment-483553486

**Comment by ZaxonXP** [comment] 2021-02-05 23:26
I could not use it directly with the mpv, but I found some [workaround](https://github.com/ZaxonXP/youtube-viewer-scripts) :)

**Comment by Akemi** [comment] 2021-04-29 19:29
duplicate.

**Closed by Akemi** 2021-04-29 19:29 UTC
Labels: meta:question
