### ISSUE TITLE
cycle video alters window position

### ISSUE THREAD

**Issue by chrisbgp** [mpv-player/mpv#4193] opened 2017-02-28 13:17 UTC
the "cycle video" command (invoked via input.conf) does not remember the previous window position. Instead it always resets to the center of the screen.

**Comment by Akemi** [comment] 2017-02-28 14:25
don't ignore the issue template otherwise we can't help you.

**Comment by Akemi** [comment] 2017-02-28 15:44
since the window is being deallocated when cycling to "no video" we can't keep track of the previous position. try it with `--force-window` and it should work.

**Comment by wm4** [comment] 2017-03-01 04:28
That's going to happen with all backends. I'm inclined to say WONTFIX and force the window size/position with --geometry as workaround.

**Comment by nextghost** [comment] 2017-06-25 12:42
@wm4 That workaround still doesn't work properly. Here's an example with resolutions as filenames:

`mpv --geometry=0:0 --force-window-position 400x720.mp4 1280x720.mp4 640x480.mp4`

Despite --geometry and --force-window-position, the mpv window will jump around the screen on every resize, occasionally returning back to 0:0 where it should stay at all times. The first resize in particular (400x720 -> 1280x720) throws the window completely off screen every time (screen resolution 1366x768). It seems that big aspect ratio change causes the biggest jumps.

My system: Gentoo Linux, mpv 0.25.0 (and all previous versions I've ever used), KDE 17.04 (and all previous versions I've ever used). Same behavior using Xv, VAAPI and OpenGL.

**Comment by wm4** [comment] 2017-06-25 14:17
Works here. It's either your window manager, or some sort of race condition.

**Comment by nextghost** [comment] 2017-06-25 17:04
@wm4 Or maybe a bug in resize code related to aspect ratio. Because after running mpv with verbose output and a little bit of poking around in the code, I've noticed that `--no-keepaspect` or `--no-keepaspect-window` fixes the issue. Either one works. Could you try to reproduce the issue with `--keepaspect`? Also make sure that mpv resizes from narrow aspect to wide aspect. Resize in the other direction (or keeping the same aspect) seems to work correctly.

Here's why I think this is a bug in mpv:

    [vo/opengl] Window size: 406x720
    [vo/opengl] Video source: 1280x720 (1:1)
    [vo/opengl] Video display: (0, 0) 1280x720 -> (0, 246) 406x228
    [vo/opengl] Video scale: 0.317188/0.316667

The verbose output above is produced by `mp_get_src_dst_rects()` in `video/out/aspect.c`. Notice the number 246 on the third line and the video scale below it.

246/0.317188 = 775.57
246/0.316667 = 776.84

My window manager helpfully reports that the mpv window after resize always lands at 0:774. I doubt that KDE would somehow come up with that number on its own, given that the whole "Video display" calculation done by mpv is nonsensical in the first place.

Full output produced by the window resize:

    [cplayer] VO: [opengl] 1280x720 yuv420p
    [cplayer] VO: Description: Extended OpenGL Renderer
    [vo/opengl] Resize: 406x720
    [vo/opengl] Window size: 406x720
    [vo/opengl] Video source: 1280x720 (1:1)
    [vo/opengl] Video display: (0, 0) 1280x720 -> (0, 246) 406x228
    [vo/opengl] Video scale: 0.317188/0.316667
    [vo/opengl] OSD borders: l=0 t=246 r=0 b=246
    [vo/opengl] Video borders: l=0 t=246 r=0 b=246
    [vo/opengl] Testing FBO format 0x805b
    [vo/opengl] Create FBO: 16x16 (16x16)
    [vo/opengl] Using FBO format 0x805b.
    [vo/opengl] No advanced processing required. Enabling dumb mode.
    [vo/opengl] Texture for plane 0: 1280x720
    [vo/opengl] Texture for plane 1: 640x360
    [vo/opengl] Texture for plane 2: 640x360
    [cplayer] set video colors output-levels=0
    [vo/opengl] Resize: 1280x720
    [vo/opengl] Window size: 1280x720
    [vo/opengl] Video source: 1280x720 (1:1)
    [vo/opengl] Video display: (0, 0) 1280x720 -> (0, 0) 1280x720
    [vo/opengl] Video scale: 1.000000/1.000000
    [vo/opengl] OSD borders: l=0 t=0 r=0 b=0
    [vo/opengl] Video borders: l=0 t=0 r=0 b=0
    [cplayer] first video frame after restart shown
    [cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding2]
    [cplayer] starting audio playback
    [cplayer] playback restart complete

**Comment by Akemi** [comment] 2018-02-17 15:57
with [cocoa-cb](https://github.com/mpv-player/mpv/commit/c5e4538bc4b63f02bf89f62aa25a37b9eb0c0316) it actually remembers the window position now, since the backend is now reversed.

otherwise i will label it as a wontfix for the other platforms. it can be reopened and discussed if there is more demand.

**Closed by Akemi** 2018-02-17 15:57 UTC
Labels: wontfix

**Comment by milanecode** [comment] 2019-06-26 14:48
This happens with clean XFCE in Xubuntu (Tried in my machine and VM with nothing but mpv). I would like to add my grain of sand to the demand pile.
