### ISSUE TITLE
Reconnect if disconnected on network stream.

### ISSUE THREAD

**Issue by shinctl** [mpv-player/mpv#5793] opened 2018-05-03 14:01 UTC
Hello guys,

Is there a command line option on MPV to automatically reconnect to a network stream?

Sometimes I get some network hiccups and the file stops playing, but if I just restart, it continues the playback normally.
I've tried with the "loop" option, but I keep getting unable to seek error.

Thanks.

**Comment by shinctl** [comment] 2018-05-03 14:03
Current command line (I've tried lots of cache options also)

mpv --cache-pause-initial=yes --cache-pause=no --cache-default=15360 --cache-initial=256 --demuxer-thread=yes --demuxer-readahead-secs=30 --framedrop=vo --sid=1 -cache-secs=30 URL

**Comment by dnmTX** [comment] 2018-05-03 16:53
@shinctl  i've had the same problem when leaving the player paused for longer time and then went away.It's basically server's fault,if you go trough terminal: mpv --h=network-timeout you'll see that is set to 0.000 aka to never expire.

**Comment by shinctl** [comment] 2018-05-10 16:34
Network timeout option does not cover some errors, sadly :(
A option like VLC's "--http-reconnect" would be awesome.

**Comment by wm4** [comment] 2018-05-10 16:46
There's already reconnection code. You're providing too little information to do anything. This should just be closed.

**Comment by shinctl** [comment] 2018-05-10 16:50
If there is, how could I use it? 
About the error I receive sometimes (Yes, I know it's the streams fault), but a reconnect after this error would be nice.
Error: [ffmpeg] NULL: missing picture in access unit

**Comment by shinctl** [comment] 2018-05-12 23:36
ATM mpv uses the "reconnect 1" option from ffmpeg right?
These other flags should help also... 

-reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1

**Comment by porsager** [comment] 2018-09-21 11:03
I'm curious if these options solved the disconnect issue for you?

**Comment by shinctl** [comment] 2018-09-21 11:51
Nope... I just gave up and used another player.

**Comment by porsager** [comment] 2018-09-21 12:45
Oh ok.. Which one if I may ask?

**Comment by rudevdr** [comment] 2018-10-08 23:11
@shinctl which other player?

**Comment by wm4** [comment] 2019-11-09 17:38
Still not clear what this issue is even about. Not a single log, not even a description of ma use case. Closing.

**Closed by wm4** 2019-11-09 17:38 UTC
Labels: core, core:stream

**Comment by porsager** [comment] 2019-11-09 18:21
In my case I'm seeing Radio streams just stopping (no audio) without any information. It'll happen after several hours/days playback, and it's very sporadic. I was thinking of setting up a test case that could check for audio activity, and record once it stopped. Then set up multiple players starting some at the same time, and some later to figure out if it's a disconnect from the source causing it, or something for the single player. Either way, it's hard to debug when it occurs with no output, but audio just stops. 

I'd be willing to set up test, if you have ideas so we can open the issue again?

**Comment by wm4** [comment] 2019-11-09 18:26
Is that just a mp3/ogg stream (typical web radio)?
Does it show "buffering" on the status line when it gets stuck?
This doesn't sound like disconnection, just being stuck, which I've sometimes observed too.

**Comment by porsager** [comment] 2019-11-09 20:13
Yeah, In my case a regular mp3 cast link like : http://live-icy.gss.dr.dk/A/A05H.mp3.m3u

It's been a while since I looked in to it, so I honestly can't remember about buffering, but I'd love to look at it again since it's a recurring issue for us that we've just "learned to live with".

I'll try to set up a test with some verbose logging the coming week. Do you have any solution for solving the "stuck" situation you've encountered?

**Comment by wm4** [comment] 2019-11-09 20:27
The case I encountered was with HLS, so potentially completely different.

I suspect there's something broken with ffmpeg's network timeout handling.

You can just reopen the stream.

If it's stuck, you may also get some information by dumping the ``demuxer-cache-state`` property, or by attaching a debugger and making a back trace on all threads.

**Comment by wm4** [comment] 2019-11-09 23:01
There's also ``--network-timeout``. This may or may not do something. Maybe you can test this by temporarily disconnecting the network cable or so.

**Comment by wm4** [comment] 2019-11-14 12:59
It turns out FFmpeg does not set a network timeout by default (anymore?), and since mpv explicitly makes FFmpeg use its default by default, mpv didn't have a timeout either.

I've changed this in git master. Now it uses a 60 second timeout. So instead of getting stuck in "Buffering" for a longer time, it should exit after 1 minute. I had to add a workaround for the cursed RTSP issue (it doesn't set a timeout for RTSP).

Regarding reconnecting, this is tricky too. HTTP normally reconnects, but only if the server accepts range requests. This is because for "static" streams, you want to continue where it left off, instead of starting from the start again.

mp3 web radio (aka icy/shoutcast/etc.) will not accept range requests, so mpv won't reconnect by default. You can force this with ``--stream-lavf-o=reconnect_streamed=1``. I'm hesitant to enable this by default, because sometimes media is delivered without support for range requests, which could lead to very irritating behavior, especially with HLS/DASH.

I don't know if HLS is affected by these changes.

**Comment by porsager** [comment] 2019-11-14 13:02
Uh, great work wm4 ! I've unfortunately been too bogged down by other tasks this week, but once I get to it I'll set up tests with git master and last release! Very interesting!

**Comment by voidzero** [comment] 2020-09-10 23:34
Here's an issue I've been having:

```
A: 00:00:33 / 00:00:39 (82%) Cache: 6.5s/121KB
[ffmpeg] tls: Error in the pull function.
[ffmpeg/demuxer] aac: Packet corrupt (stream = 0, dts = NOPTS).
A: 00:00:39 / 00:00:39 (98%) Cache: 0.3s/4KB
[ffmpeg/audio] aac: Input buffer exhausted before END element found
Error decoding audio.
A: 00:00:39 / 00:00:39 (98%) Cache: 0.0s


Exiting... (End of file)
```

I'd like mpv to try everything to reconnect on issues like this one. I listen to a lot of talk radio and interruptions suck. This mainly happens on my mobile (mpv with termux) fairly often, maybe due to wifi, I'm not sure.

**Comment by alexishuxley** [comment] 2024-01-19 17:40
I encounter the same problem. Here's the output:
```
pirohy$ mpv http://live.slovakradio.sk:8000/FM_128.mp3
 (+) Audio --aid=1 (mp3 2ch 44100Hz)
[W][72817.559382] pw.conf      | [          conf.c:  939 try_load_conf()] can't load config client.conf: No such file or directory
[E][72817.559490] pw.conf      | [          conf.c:  963 pw_conf_load_conf_for_context()] can't load default config client.conf: No such file or directory
AO: [pulse] 44100Hz stereo 2ch float
A: 00:00:00 / 00:00:05 (18%) Cache: 4.0s/144KB
File tags:
 icy-title: * Radio_FM * www.radiofm.sk * Baláž & Hubinák *
A: 00:03:27 / 00:03:31 (98%) Cache: 3.7s/131KB
File tags:
 icy-title: The Black Keys - Beautiful People (Stay High)
A: 00:06:07 / 00:06:12 (99%) Cache: 3.9s/139KB
File tags:
 icy-title: Tolstoys - Real
A: 00:09:05 / 00:09:10 (99%) Cache: 3.8s/136KB
File tags:
 icy-title: Eva KOSTOLÁNYIOVÁ, SBOR LUBOMÍRA PÁNKA, Tanecný orchester Slovenského rozhlasu - Leto
A: 00:13:03 / 00:13:08 (99%) Cache: 3.9s/140KB
File tags:
 icy-title: * Radio_FM * www.radiofm.sk * Baláž & Hubinák *
A: 00:15:26 / 00:15:26 (100%) Cache: 0.0s
Audio device underrun detected.
A: 00:15:26 / 00:15:26 (100%) Cache: 0.1s/2KB
[ffmpeg/audio] mp3float: invalid new backstep -1

Exiting... (End of file)
pirohy$ 
```
During the daytime this error has not occurred, but as evening draws on then it occurs several times per hour, presumably as the server gets more loaded.

This is easy to reproduce so if you'd like more logs just let me know what command line options to add.

**Comment by guidocella** [comment] 2024-01-20 17:49
You can try the options suggested in https://github.com/mpv-player/mpv/issues/8779#issuecomment-1000702539

**Comment by alexishuxley** [comment] 2024-01-26 10:28
I re-reviewed all the comments above and, crosschecking with other options mentioned here, I see there is a typo in one of the comments:  `reconnect_at_eof=yes` should be `reconnect_on_eof=yes` . With that corrected my problem is solved: BBC radio still glitches but it recovers:
```
damson$ mpv --loop --stream-lavf-o-append=reconnect_on_http_error=4xx,5xx --stream-lavf-o-append=reconnect_delay_max=30 --stream-lavf-o-append=reconnect_streamed=yes --stream-lavf-o-append=reconnect_on_network_error=yes --stream-lavf-o-append=reconnect_on_eof=yes http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_fourfm/bbc_radio_fourfm.isml/bbc_radio_fourfm-audio%3d96000.norewind.m3u8
 (+) Audio --aid=1 (aac 2ch 48000Hz)
[W][40591.342398] pw.conf      | [          conf.c:  939 try_load_conf()] can't load config client.conf: No such file or directory
[E][40591.342434] pw.conf      | [          conf.c:  963 pw_conf_load_conf_for_context()] can't load default config client.conf: No such file or directory
AO: [pulse] 48000Hz stereo 2ch float
A: 00:23:21 / 00:23:34 (99%) Cache: 12s/299KB
[ffmpeg] http: Will reconnect at 0 in 0 second(s).
A: 00:00:00 / 00:33:48 (0%) Cache: 2028s/48MB
[ffmpeg] http: Will reconnect at 0 in 0 second(s).
[ffmpeg/demuxer] hls: skipping 220 segments ahead, expired from playlists
[ffmpeg] http: Will reconnect at 0 in 0 second(s).
A: -00:00:00 / 00:33:55 (0%) Cache: 2035s/48MB
[ffmpeg] http: Will reconnect at 0 in 0 second(s).
A: 00:34:01 / 00:58:14 (58%) Cache: 1452s/1MB
Invalid audio PTS: 2041.600000 -> 3449.600000
A: 00:57:35 / 00:58:14 (99%) Cache: 38s/932KB
```
I hope that helps somebody!

**Comment by pcgeek86** [comment] 2024-08-02 15:57
This issue is really bothersome ... I wish MPV would automatically reconnect to my security camera's RTSP streams, when they hang. I have to exit and start a new MPV process, and then resize the window again. 

Please fix the player so that it automatically reconnects.

**Comment by alexishuxley** [comment] 2024-08-03 06:46
> Please fix the player so that it automatically reconnects.

perhaps '--loop-playlist=force' helps you.

Alexis

**Comment by char101** [comment] 2024-11-23 03:21
So far this lua script works for me for restarting the stream when it is disconnected.

```lua
local prev_pos = -1

function reload_if_disconnected()
  local pos = mp.get_property_number('time-pos')
  if pos == nil or pos == prev_pos then
    mp.commandv('loadfile', mp.get_property('path'), 'replace')
  else
    prev_pos = pos
  end
end

mp.add_periodic_timer(30, reload_if_disconnected)
```

**Comment by Woynert** [comment] 2025-04-23 22:58
For the record, in addition to char101's excellent answer ultimately this were the flags that worked for me:

```console
mpv http://host:port/hls/stream --scripts-append=./mpv-reconnect.lua --keep-open=yes --keep-open-pause=no --auto-window-resize=no
```
