### ISSUE TITLE
"save-position-on-quit" shouldn't save the position after you've finished the video

### ISSUE THREAD

**Issue by epitron** [mpv-player/mpv#2045] opened 2015-06-15 04:44 UTC
Enabling these two options causes an edge case:
- keep-open=yes
- save-position-on-quit=yes

This causes the mpv window to stay open after the video ends, and that mpv should save the position when you quit. The result is that whenever you quit after finishing a video, the end becomes the saved position, and when you re-open the video, it starts at the end.

Ideally, quitting the video after it's finished should clear the saved position.

**Comment by wm4** [comment] 2015-06-15 19:45
Technically, it never finishes the video with --keep-open. So it works as designed.

**Comment by epitron** [comment] 2015-06-16 07:06
Hmm... So, what would you suggest for a someone in my situation? It would be great if I could use both of those features at the same time, while avoid this whole "never finishing the video" mess!

**Comment by wm4** [comment] 2015-07-18 16:32
>So, what would you suggest for a someone in my situation?

Not sure, really. Not writing the resume config in this situation would break resuming from playlists.

**Comment by wm4** [comment] 2015-10-23 16:14
I wonder whether it'd be reasonable to skip writing the watch later file if these conditions are true:
- Playback is at the end of the file in "keep open" mode (would have to be detected explicitly)
- it's the last file on the playlist

But I'm still a bit hesitant, because it's like a hack to make a specific use-case work.

**Comment by epitron** [comment] 2015-10-23 16:17
Heh, well, usability is all about lots of little hacks to make specific cases work. :)

**Comment by epitron** [comment] 2015-10-23 16:22
Okay, I get what the problem is now. Maybe playlists should be treated like one long concatenated video, with a single position. If you're at the end of the playlist, it doesn't save your position

**Comment by wm4** [comment] 2015-10-23 16:34
> If you're at the end of the playlist, it doesn't save your position

So I guess this could work. Now I only need to think of a good way to detect the keep-open state.

**Comment by NintendoManiac64** [comment] 2022-05-12 06:27
So um, it's been many many years and, AFAICT, this is still a problem and I'm very much running into it myself.

I was a user of MPC-HC on Windows for... gosh, a decade now? And had this very behavior where it remembers position and the program window stays open when the video is finished but, when you do in fact finish a video, the "remembered" playback position is discarded.

**Comment by felagund** [comment] 2022-05-12 08:17
Hm, thinking about this, I actually quite like this beahviour. Sometimes I am not sure if I have watched a video or not - so when I open it and it is at the end, I know I have watched it.

**Comment by Dudemanguy** [comment] 2022-05-12 13:53
Actually you can use conditional auto-profiles now to deal with this edge case. Something like:

```
# save position by default
save-position-on-quit=yes

[don't save position on quit]
profile-cond=eof_reached
save-position-on-quit=no
```

Going to go ahead and close this.

**Closed by Dudemanguy** 2022-05-12 13:53 UTC
Labels: meta:feature-request, priority:low, core:option-param-conf

**Comment by NintendoManiac64** [comment] 2022-05-13 01:59
While playing around with the function described in Dudemanguy's previous comment, I must say that while it generally "just works", I've discovered a quirk where it doesn't.

Basically, if you let a video naturally play to the end on its own then, yes, it will behave as intended and discard the saved position.

However, if you're something like 15 seconds from the end and skip 1 minute forward and then close the video, when you re-open the video it will still "resume" the video at the very end rather than restarting.

**Comment by Dudemanguy** [comment] 2022-05-13 02:14
It looks like the auto profile condition isn't evaluated in that particular case for some reason (might be a bug/race possibly). In theory if you use a script to do the same thing by observing the `eof-reached` property, it should work since mpv does register `eof-reached` as being true after you seek.

**Comment by Dudemanguy** [comment] 2022-05-13 03:14
The PR I just linked fixes that final issue so the profile condition works correctly. That's indeed a bug. That's for pointing it out.

**Comment by epitron** [comment] 2022-06-01 13:28
Thank you! Wow, I'm impressed that you got around to fixing this. Most projects just delete 7 year old issues. I will try it out!

**Comment by NintendoManiac64** [comment] 2022-06-02 19:22
Related question - using Dudemanguy's configuration suggestion involving auto-profiles that, as I mentioned "just works", is there a way to have it additionally have it exit fullscreen while keeping the window open when you've reached the end of the video? (this would farther replicate how MPC-HC behaves)

Basically I'm trying to have it return to a maximized, non-fullscreen window but, well, [that might not be possible at this time](https://github.com/mpv-player/mpv/issues/10229) and I might just have to settle for a non-maximized window for the time being.

**Comment by Dudemanguy** [comment] 2022-06-02 20:07
This is kind of hacky but it should work.

```
# save position by default
save-position-on-quit=yes

[don't save position on quit]
profile-cond=eof_reached
save-position-on-quit=no
fullscreen=no

[maximize]
profile-cond=eof_reached and not fullscreen
window-maximized=yes
```

Of course, that will always maximize the window for you even if it was not originally fullscreen so it might be the perfect solution.

**Comment by Dudemanguy** [comment] 2022-06-02 20:47
Ideally, the window being in a maximized state should indeed be independent of whether or not it is fullscreen. How this works can vary alot depending on the window-manager, xorg/wayland, etc. I'd have to look at the code again to see how we're currently handling it. That hack works since you just first get out of fullscreen, and then maximize later (i.e. two separate steps). The "correct" solution would be to be able to do both at once.
