### ISSUE TITLE
Ubuntu Sound Menu Indicator Integration?

### ISSUE THREAD

**Issue by orschiro** [mpv-player/mpv#3767] opened 2016-11-04 08:25 UTC
Dear all, 

Coming from [this conversation on AskUbuntu](http://askubuntu.com/questions/845387/how-can-i-integrate-mpv-media-player-into-the-ubuntu-sound-menu?noredirect=1#comment1296589_845387), can we somehow integrate mpv into the Ubuntu Sound Menu Indicator?

Thankfully,

-Robert

**Comment by haasn** [comment] 2016-11-04 08:53
IMO the right way to handle this would be with a user script providing MPRIS integration. It should be relatively straightforward. I haven't looeked at the MPRIS spec but I imagine all of the commands and properties provided by MPRIS map directly to commands and properties provided by mpv.

The user script would just have to take care of dbus integration, which is extremely unlikely to end up in mpv itself.

**Comment by orschiro** [comment] 2016-11-04 11:27
Dear @haasn,

Thanks! This external script, can I just follow its README and I am done?

Or do I need to do anything else?

-Robert

**Comment by haasn** [comment] 2016-11-04 11:39
I don't know. I haven't tested it.

**Comment by orschiro** [comment] 2016-11-04 11:57
Sadly it's not working on Ubuntu 16.10: https://github.com/dodo/lua-mpris/issues/7

:-(

**Comment by mc4man** [comment] 2016-11-04 20:17
You are - 
1. using wrong include path for DBUS_ARCH_INCDIR, it should be /usr/lib/x86_64-linux-gnu/dbus-1.0/include
2. you are using sudo for a local install, no reason for that
3. likely you only need to do the mpv half on instructions though I guess the top half won't hurt

As far as how it works, (16.04),  barely.. Can open an idle mpv window, can start a paused mpv. Doesn't seem to be able to pause or switch tracks..

**Comment by orschiro** [comment] 2016-11-05 08:51
Thanks for trying it out!

Sadly for me this is too complicated and I ended up switching to VLC which
provides sound menu indicator integration.

**Comment by lachs0r** [comment] 2016-11-06 03:55
Duplicate of #661.

**Closed by lachs0r** 2016-11-06 03:55 UTC
