### ISSUE TITLE
Video play becomes very lag when OSC shows up on OSX 

### ISSUE THREAD

**Issue by hkenneth** [mpv-player/mpv#903] opened 2014-07-02 22:27 UTC
I'm using ChrisK's latest build on OSX 10.9.3. I use Nvidia Web Driver instead of the vanilla OSX driver. Video play becomes really lag when OSC shows up. I got the following in Terminal:

[stream] Video (+) --vid=1 (h264)
[stream] Audio (+) --aid=1 --alang=eng (*) (dts)
[stream] Subs  (+) --sid=1 --slang=eng (*) (subrip)
AO: [coreaudio] 48000Hz stereo 2ch float
AV: 00:00:00 / 00:57:36 (0%) A-V:  0.000
VO: [opengl] 1280x720 => 1280x720 yuv420p
AV: 00:00:05 / 00:57:36 (0%) A-V:  2.789 Late: 51

           *************************************************
           **** Audio/Video desynchronisation detected! ****
           *************************************************

This means either the audio or the video is played too slowly.
Possible reasons, problems, workarounds:
- Your system is simply too slow for this file.
     Transcode it to a lower bitrate file with tools like HandBrake.
- Broken/buggy _audio_ driver.
     Experiment with different values for --autosync, 30 is a good start.
     If you have PulseAudio, try --ao=alsa .
- Slow video output.
     Try a different --vo driver (--vo=help for a list) or try --framedrop!
- Playing a video file with --vo=opengl with higher FPS than the monitor.
     This is due to vsync limiting the framerate.
- Playing from a slow network source.
     Download the file instead.
- Try to find out whether audio/video/subs are causing this by experimenting
  with --no-video, --no-audio, or --no-sub.
- If you swiched audio or video tracks, try seeking to force synchronization.
If none of this helps you, file a bug report.

**Comment by wm4** [comment] 2015-07-18 13:02
Duplicate of: https://github.com/libass/libass/issues/186

**Closed by wm4** 2015-07-18 13:02 UTC
Labels: not our bug
