### ISSUE TITLE
JSON IPC - get_property geometry

### ISSUE THREAD

**Issue by krlklm** [mpv-player/mpv#5426] opened 2018-01-20 23:39 UTC
### mpv version and ffmpeg version
mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Fri Jan  5 13:35:23 GMT 2018
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4.1

### Platform
Mac OS 10.11.6 El Capitan

### Reproduction steps
- in the CLI / (terminal window nr. 1) type `mpv /path/to/movie.mpg --geometry=30%+20+10 --input-ipc-server=/tmp/mpvsocket1`
- in the CLI (terminal window nr. 2) type `echo '{ "command": ["get_property", "geometry"] }' | socat - /tmp/mpvsocket1`
- it will output the geometry of the movie when it was created
- move and scale the window with the mouse
- in the CLI type `echo '{ "command": ["get_property", "geometry"] }' | socat - /tmp/mpvsocket1` again.
- it will still output the old values

### Expected behavior
When sending `echo '{ "command": ["get_property", "geometry"] }' | socat - /tmp/mpvsocket1` in the CLI it should output the current geometry of the window (size, position x, position y) after it was dragged and resized with the mouse.

### Actual behavior
The CLI outputs the size and position of the movie window when it was created, not the current values.

(I do get the current value of the volume setting when i use 'get_property volume' instead of 'get_property geometry')

### Log file
http://www.dienststelle.de/projekte/2017/videoplayer/mpv/output.log

**Comment by Akemi** [comment] 2018-01-21 01:45
from our side this is expected behaviour, as in this wasn't meant to work. if you just need the size of the window there are the `dwidth` and `dheight` properties, i believe.

do you need the (new) position? also what is your use-case?

**Comment by krlklm** [comment] 2018-01-21 08:14
Thanks for the hint `dwith` with and `dheight`. Yes, I would need the new position as well. 

Use case:

This is for an art installation. Several movies should open and play at predefined positions and window sizes over time. The score will be run by Ableton Live (www.ableton.com). Audio loops in Ableton live will be synchronised to video loops with IINA (https://github.com/lhc70000/iina), which is based on mpv. We are using IINA instead of mpv, as the windows should look like regular Quicktime Player windows. The IINA player will be controlled via a Max4Live instrument / patch that can send commands via CLI (www.ableton.com/en/live/max-for-live/).

For a convenient way to design the layout of the score over time it would be good (or even necessary) to be able to drag the movie windows, resize them and then get these values to store them.

Ideally we could even control the position and size of the windows after creation, but I learned that this is not possible (at least at the moment).

Thanks!

**Comment by Akemi** [comment] 2018-01-21 10:39
then you should open an issue on the iina issue tracker, since iina controls window size and position in that case. mpv only knows about the size in this case since it needs to know the size of the rendering surface.

so even if we add support for it, it most likely won't work with iina (at first). since they also, most likely, need to support that mechanism, if they even would want that.

it's a duplicate of #3872.

**Closed by Akemi** 2018-01-21 10:39 UTC

**Comment by krlklm** [comment] 2018-01-26 12:31
Collider Li from IINA just answered:

> IINA is ready for it. Once mpv implemented this feature, we'll update IINA accordingly.

Would you be able to implement requesting the current window size and position via JSON IPC? Thanks!
