### ISSUE TITLE
SRT subtitles clipped when playing widescreen video in fullscreen

### ISSUE THREAD

**Issue by ebichu-man** [mpv-player/mpv#7557] opened 2020-03-25 17:59 UTC
### Important Information

- mpv version
```
mpv 0.32.0-288-gee70e8ce50 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Mar 22 12:56:50 +08 2020
FFmpeg library versions:
   libavutil       56.42.101
   libavcodec      58.76.100
   libavformat     58.42.100
   libswscale      5.6.101
   libavfilter     7.77.100
   libswresample   3.6.100
FFmpeg version: git-2020-03-21-ea46b45e9
```

- Windows Version 10.0.17763

- Source of the mpv binary
https://sourceforge.net/projects/mpv-player-windows

- Possible screenshot or video of visual glitches

![2020-03-26 00_36_50-Blade Runner 2049 (2017) BDRip 720p - mpv](https://user-images.githubusercontent.com/24250446/77567830-4f53e900-6efa-11ea-81e8-a5651dcdab2c.png)

### Reproduction steps

1. Start widescreen video in fullscreen with srt subtitles. 
2. Start Changing subtitle position to smaller values.

### Expected behavior

Subtitles should move up and not dissapper.

### Actual behavior

Subtitiles start clipping with small value (around 30 in my case) and completely dissappear with smaller values.

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/4382583/log.txt)

**Comment by Akemi** [comment] 2020-03-25 18:10
a sample file would be nice.

**Comment by ebichu-man** [comment] 2020-03-25 18:39
Sample file
[sample.mkv.zip](https://github.com/mpv-player/mpv/files/4382828/sample.mkv.zip)

**Comment by wm4** [comment] 2020-03-25 21:50
Technically that's a libass issue. I guess these problems with margins were never really solved.

**Comment by Akemi** [comment] 2020-08-30 11:43
apparently fixed by https://github.com/libass/libass/pull/385. i can't reproduce it with that sample. if it still persists please open a new issue.

**Closed by Akemi** 2020-08-30 11:43 UTC
Labels: core:subtitle, os:win
