### ISSUE TITLE
Weird video tearing in VAAPI with kernel 5.19 

### ISSUE THREAD

**Issue by rei-nert** [mpv-player/mpv#10654] opened 2022-09-17 19:09 UTC
### Important Information

Provide following Information:
- mpv version: 0.34.1
- Linux Distribution and Version: Debian Testing
- Source of the mpv binary: Debian Repository
- Window Manager and version KDE Plasma 5.25
- GPU driver and version: Intel i965 driver for Intel(R) CherryView - 2.4.1
- Possible screenshot or video of visual glitches:
   - With kernel 5.10 OR software rendering: https://0x0.st/oOhc.jpg
   - With kernel 5.19 and VAAPI rendering: https://0x0.st/oOhT.jpg

### Reproduction steps
Opening a h264/mp4 file with mpv in kernel 5.10 OR with --no-config, results in a smooth video experience, without  any rendering problem.
In the same machine, if I boot with kernel 5.19 and use --hwdec=auto (or vaapi), there's a bad rendering experience, without any possibility to watch the video (online or local files). 
With the 5.10 kernel, I can use --hwdec=vaapi with no problem at all.

### Expected behavior
A smooth experience in kernel 5.19 with VAAPI

### Actual behavior
Bad rendering, with a lot of screen tearing and unwatchable experience (https://0x0.st/oOhT.jpg)

### Log file
[logfile](https://0x0.st/oOhB.txt)

**Comment by lavilao** [comment] 2022-09-18 01:53
hello fellow intel hd user! I already reported this issue long time ago https://github.com/mpv-player/mpv/issues/10547 the only thing I can recommend you is use another non 5.19.x kernel (like 5.15 lts). There are multiple reports of this on reddit so if you can report a kernel bug (its a kernel bug not an mpv bug) you are very welcome.

**Comment by thebombzen** [comment] 2022-09-18 05:22
Duplicate of #10547

**Closed by thebombzen** 2022-09-18 05:22 UTC
Labels: os:linux
