### ISSUE TITLE
Blinking video while interacting with OS

### ISSUE THREAD

**Issue by valera5505** [mpv-player/mpv#4161] opened 2017-02-17 20:18 UTC
### mpv version and platform
mpv 0.24 on macOS Sierra 10.12.3

### Reproduction steps
Launch mpv and interact with OS (change volume via hotkeys, drag window and so on)
[Video on YouTube](https://youtu.be/fPKg4uFjr6A)

### Expected behavior
Video is playing as usual

### Actual behavior
Video is blinking where animation occurs

### Log file

http://sprunge.us/dNTT

**Comment by Akemi** [comment] 2017-02-17 20:40
probably a duplicate of #3746. try setting `--opengl-pbo=yes` and let me know if it fixes it. if not i will reopen this.

**Closed by Akemi** 2017-02-17 20:40 UTC
Labels: osx

**Comment by valera5505** [comment] 2017-02-17 20:42
Yes, `--opengl-pbo=yes` fixes it. Thank you.
