### ISSUE TITLE
Mac MPV crash on launch

### ISSUE THREAD

**Issue by etienned** [mpv-player/mpv#4445] opened 2017-05-22 14:21 UTC
### mpv version and platform

0.25 installed from homebrew cask (source: https://laboratory.stolendata.net/~djinn/mpv_osx/mpv-0.25.0.tar.gz). As ask by @stolendata, I tried to install it directly from https://laboratory.stolendata.net/~djinn/mpv_osx/mpv-0.25.0.tar.gz. Same results.

This is on a fresh install of El Capitan 10.11.6.

Could be linked to issue #3488 

### Reproduction steps

Double-click MPV icon to start the application.

### Expected behavior

MPV running.

### Actual behavior

MPV crash mostly instantly.

### Log file

Crash dump: http://dpaste.com/0EN1FF4
Log file: http://dpaste.com/322BJMW

**Comment by Akemi** [comment] 2017-05-22 14:33
yeah definitely duplicate of #3488.

**Closed by Akemi** 2017-05-22 14:33 UTC
