### ISSUE TITLE
cycle aspect ratio crash on macOS dual screen

### ISSUE THREAD

**Issue by minusf** [mpv-player/mpv#4252] opened 2017-03-18 17:11 UTC
In a dual HDMI monitor setup ("Use As Separate Display"),
when I drag the movie window to the external display,
cycling through the aspect ratios (`A`) core dumps.

here is the crash report:
http://pastebin.com/aZRTGUUD

**Comment by Akemi** [comment] 2017-03-18 18:56
pls don't ignore the issue template. i can't reproduce this. does it always reproducible happen? does it happen with older versions of mpv? anything else you do when starting mpv or how you start it? what is in your config?

**Comment by minusf** [comment] 2017-03-18 19:44
sorry about the template, will keep in mind.

hm, very strange, no matter what i do, i can't seem to reproduce this anymore...
yesterday, every single try resulted in core dump.  does the trace i included
give any clue what might have happened?

otherwise i am sorry, seems like a heisenbug :/

**Comment by Akemi** [comment] 2017-03-18 20:04
i only have a hunch what could have happened, but if you can't reproduce it we can't confirm if it's fixed with a possible change.

**Comment by jstuyck** [comment] 2017-03-28 09:50
Can't reproduce it on a MacOS Sierra 10.12.3 
mpv: stable 0.24.0
ffmpeg library versions:
   libavutil       55.34.101
   libavcodec      57.64.101
   libavformat     57.56.101
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.4

**Comment by minusf** [comment] 2017-03-31 13:38
i'll try to reproduce this weekend one last time, then the ticket can be closed.

**Closed** 2017-04-03 15:29 UTC
Labels: osx
