### ISSUE TITLE
TrueHD audio not playing - Assignment of matrix channel 0 to invalid output channel -22 is not implemented

### ISSUE THREAD

**Issue by mibby** [mpv-player/mpv#9380] opened 2021-11-02 03:01 UTC
### Important Information

- mpv 0.33.0-397-g4a80de90d2
- Windows 11 (OS Build 22489.1000)
- shinchiro sourceforge 64bit builds

First breaking build - mpv-x86_64-20211003-git-5304e9f.7z
```
mpv 0.33.0-349-g5304e9fe31 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Oct  3 12:09:03 +08 2021
FFmpeg library versions:
   libavutil       57.7.100
   libavcodec      59.10.100
   libavformat     59.5.100
   libswscale      6.1.100
   libavfilter     8.11.100
   libswresample   4.0.100
FFmpeg version: git-2021-10-02-db7bd99eb
```

Last working build - mpv-x86_64-20210919-git-560e6c8.7z
```
mpv 0.33.0-337-g560e6c8709 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Sep 19 11:38:27 +08 2021
FFmpeg library versions:
   libavutil       57.5.101
   libavcodec      59.7.103
   libavformat     59.5.100
   libswscale      6.1.100
   libavfilter     8.9.100
   libswresample   4.0.100
FFmpeg version: git-2021-09-19-73a59ed1c
```

### Reproduction steps

* Use latest MPV build.
* Open video file with TrueHD audio embedded in the mkv.
* Audio does not play.

### Expected behavior

TrueHD audio to play back without issue.

### Actual behavior

Audio does not play. Something changed in ffmpeg upstream possibly causing a breaking change?

### Log file

```
[   0.126][v][cplayer] Starting playback...
[   0.127][d][osc] osc_init 
[   0.127][w][ffmpeg/audio] truehd: Assignment of matrix channel 0 to invalid output channel -22 is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[   0.127][w][ffmpeg/audio] truehd: If you want to help, upload a sample of this file to https://streams.videolan.org/upload/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
[   0.127][e][ffmpeg/audio] truehd: No restart header present in substream 0.
[   0.128][e][ffmpeg/audio] truehd: No samples to output.
[   0.128][e][ad] Error decoding audio.
[   0.128][d][vd] DR parameter change to 1920x1088 yuv420p10 align=64
[   0.128][d][vd] Allocating new DR image...
[   0.128][e][ffmpeg/audio] truehd: No restart header present in substream 0.
[   0.128][e][ffmpeg/audio] truehd: No samples to output.
[   0.128][e][ad] Error decoding audio.
[   0.128][d][vd] ...failed..
[   0.128][v][vd] DR failed - disabling.
[   0.128][e][ffmpeg/audio] truehd: No restart header present in substream 0.
[   0.128][e][ffmpeg/audio] truehd: No samples to output.
[   0.129][e][ad] Error decoding audio.
[   0.129][e][ffmpeg/audio] truehd: No restart header present in substream 0.
[   0.129][e][ffmpeg/audio] truehd: No samples to output.
[   0.129][e][ad] Error decoding audio.
```

[output.txt](https://github.com/mpv-player/mpv/files/7457457/output.txt)

### Sample files

Audio track extracted out of the mkv container.
https://anonfiles.com/reXbf3S0u0/TrueHD_track02_truehd

**Comment by ValZapod** [comment] 2021-11-10 02:31
Update ffmpeg to https://github.com/FFmpeg/FFmpeg/commit/57f0b36367d4e5ccd4d2da7f69c3cac45b6236ee. This is a regression due to genious commit https://github.com/FFmpeg/FFmpeg/commit/cd7e25b14a2a27b73874b5f79a04ae5db738f7f6 from Paul, I complained about that here. 

https://trac.ffmpeg.org/ticket/6216#comment:8

**Comment by richardpl** [comment] 2021-11-10 08:24
Please ignore entries from this entity ValZapod he have serious problems with self.

**Comment by richardpl** [comment] 2021-11-10 08:25
Your upload is not accessible, reports 502 error here.

**Comment by ValZapod** [comment] 2021-11-10 09:33
> reports 502 error here.

Use Tor/Orbot.

> problems with self.

This is not proper English even.

**Comment by richardpl** [comment] 2021-11-10 09:58
I vote for banning ValZapod from github.

**Comment by ValZapod** [comment] 2021-11-10 10:18
> banning

You are banned now.

**Comment by ValZapod** [comment] 2021-11-11 08:42
wget https://cdn-103.anonfiles.com/reXbf3S0u0/8abd3b0f-1636620610/TrueHD%20track02.truehd

works

**Comment by richardpl** [comment] 2021-11-11 08:54
What a genius!

**Comment by ValZapod** [comment] 2021-11-12 14:37
Should be fixed with [946493eb3e072b499909f606625480c928834a44](https://github.com/FFmpeg/FFmpeg/commit/946493eb3e072b499909f606625480c928834a44), will test.

**Comment by ValZapod** [comment] 2021-12-19 03:30
Decoder is now producing garbage after https://github.com/FFmpeg/FFmpeg/commit/a8a7c5d502a851d16c4668e03bff12d0e16c32b8

**Comment by richardpl** [comment] 2021-12-19 20:44
works just fine here

**Comment by ValZapod** [comment] 2022-01-24 06:51
So are you going to fix it or what? Mono.mlp sample is also broken now, not that it was fully well even before that.
>works just fine here

That is BS.

**Comment by Dudemanguy** [comment] 2024-01-21 17:06
Is this still a problem?

**Closed** 2024-09-30 13:10 UTC
Labels: meta:info-needed
