### ISSUE TITLE
BBC news videos not playing via youtube-dl

### ISSUE THREAD

**Issue by adskankster** [mpv-player/mpv#2216] opened 2015-08-11 16:04 UTC
Hello,

I have an issue using the youtube-dl hook on the BBC news website. 
For example: http://www.bbc.co.uk/news/world-us-canada-33840279

If I download the video using youtube-dl it plays fine with mpv. That's using default youtube-dl options.
If I try and access it directly using mpv it seems to hang until I kill it, then I get the following error:

> Playing: http://www.bbc.co.uk/news/world-us-canada-33840279
> Failed to open rtmp://cp45413.edgefcs.net/ondemand?auth=daEc4dpaFa2dAc.dmdxandDcua1dXcwaBdx-bvYHHa-bWG-HqqDBnAqLDpHpzF&aifp=v001&slist=public/mps_h264_med/public/news/world/1185000/1185378_h264_800k.mp4;public/mps_h264_hi/public/news/world/1185000/1185378_h264_1500k.mp4;public/mps_h264_lo/public/news/world/1185000/1185378_h264_496k.mp4.
> EDL: Could not open source file 'rtmp://cp45413.edgefcs.net/ondemand?auth=daEc4dpaFa2dAc.dmdxandDcua1dXcwaBdx-bvYHHa-bWG-HqqDBnAqLDpHpzF&aifp=v001&slist=public/mps_h264_med/public/news/world/1185000/1185378_h264_800k.mp4;public/mps_h264_hi/public/news/world/1185000/1185378_h264_1500k.mp4;public/mps_h264_lo/public/news/world/1185000/1185378_h264_496k.mp4'.
> No video or audio streams selected.

This is the youtube-dl output:

> youtube-dl -F http://www.bbc.co.uk/news/world-us-canada-33840279
> [bbc] world-us-canada-33840279: Downloading webpage
> [bbc] p02z4vbt: Downloading media selection XML
> [download] Downloading playlist: Emergency landing for US plane as hail shatters windscreen
> [bbc] playlist Emergency landing for US plane as hail shatters windscreen: Collected 1 video ids (downloading 1 of them)
> [download] Downloading video 1 of 1
> [info] Available formats for p02z4vbt:
> format code                                     extension  resolution note
> journalism_ukpublic_stream_h264_flv_lo_akamai   flv        384x216    h264@ 496k, 2.71MiB
> journalism_ukpublic_stream_h264_flv_med_akamai  flv        640x360    h264@ 800k, 4.64MiB
> journalism_ukpublic_stream_h264_flv_hi_akamai   flv        688x384    h264@1500k, 8.61MiB (best)

mpv and youtube-dl work fine on, for example, youtube for me.

**Comment by wm4** [comment] 2015-08-11 16:27
It just works here. But it adds a http URL, not a rtmp one.

@ChrisK2: the EDL has only 1 entry. This is less than ideal; it would be better to just return the URL directly. EDL was not made for network use, and slow/hanging network can hang mpv as well when used in EDL.

**Comment by adskankster** [comment] 2015-08-11 16:59
> It just works here. But it adds a http URL, not a rtmp one.

Thanks for the very quick reply. Is this likely to be an issue with my config/setup then?

**Comment by wm4** [comment] 2015-08-11 17:06
No idea. What youtube-dl are you using? Could also be region dependent.

**Comment by adskankster** [comment] 2015-08-11 17:14
> $ youtube-dl -v
> [debug] System config: []
> [debug] User config: []
> [debug] Command-line args: ['-v']
> [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2015.07.28
> [debug] Python version 3.4.3 - Linux-4.1.4-1-ARCH-x86_64-with-arch
> [debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
> [debug] Proxy map: {}

**Comment by mc4man** [comment] 2015-08-11 17:19
update ytdl to current, (version 2015.08.09 ), then should work via mpv cli or the Firefox mpv extension directly on the site

**Comment by adskankster** [comment] 2015-08-11 17:37
Ah, thanks. I hadn't spotted that it was out of date. It updates so regularly I had stupidly assumed it was up to date. Bad idea in summer. I'll look into updating.

**Comment by ChrisK2** [comment] 2015-08-11 17:49
> @ChrisK2: the EDL has only 1 entry. This is less than ideal; it would be better to just return the URL directly. EDL was not made for network use, and slow/hanging network can hang mpv as well when used in EDL.

Yes, but the BBC extractor returns a playlist with one entry ... so "technically" the hook does everything as intended. Handling one-entry playlists as a single video will require a bit of special treatment ... (I'll look into it – later.)

**Comment by adskankster** [comment] 2015-08-18 09:55
> update ytdl to current, (version 2015.08.09 ), then should work via mpv cli or the Firefox mpv extension > directly on the site

The latest version of youtube-dl fixed it. Sorry for the noise.
I haven't closed this yet though as I don't know if you want to keep it open for the EDL stuff?

**Comment by wm4** [comment] 2015-08-18 10:07
That's strictly speaking a separate issue. Closing.

**Closed by wm4** 2015-08-18 10:07 UTC
