### ISSUE TITLE
MPV crashes and can't force quit

### ISSUE THREAD

**Issue by glottore** [mpv-player/mpv#5180] opened 2017-12-05 00:19 UTC
Using mpv 0.27 and on iMac 5k Retina, macOS High Sierra 10.13.1

Sometimes when I click a video file it won't play and instead after a 5 second delay I get a window saying 'You can't open the application "mpv" because it isn't responding'. There is no longer an mpv window I can cycle to through Command+Tab. When I go to Force Quit mpv nothing happens. I can't find the process on Activity Monitor either. I end up having to turn off my computer manually via the Power Button. I don't think there is a way of getting a log file.

**Comment by Akemi** [comment] 2017-12-05 00:33
most likely duplicate of duplicate of #4926. has been fixed in git master.

**Closed by Akemi** 2017-12-05 00:33 UTC
