### ISSUE TITLE
Weird seeking behavior of HDR images (Gain Map)

### ISSUE THREAD

**Issue by Silver-Fullbuster** [mpv-player/mpv#13976] opened 2024-04-23 23:34 UTC
### Important Information

Provide following Information:
- mpv version:
  ```
  mpv v0.37.0-739-g3c1e9833 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
   built on Apr  7 2024 00:04:16
  libplacebo version: v7.349.0 (v6.338.0-120-g7b29435-dirty)
  FFmpeg version: N-114700-g0dbf45120
  FFmpeg library versions:
     libavutil       59.13.100
     libavcodec      61.5.101
     libavformat     61.3.100
     libswscale      8.2.100
     libavfilter     10.2.101
     libswresample   5.2.100
  ```
- Windows Version - Windows 11 23H2 (OS Build 22631.3296)
- Source of the mpv binary - Shinchiro weekly builds
- GPU model, driver and version - AMD Radeon 7800 XT, Adrenalin version: 24.3.1 (DxDiag driver version: 31.0.24027.1012)
- Possible screenshot or video of visual glitches:
mpv rendering the gain map of the image, in HDR (screenshot taken from mpv)
![mpv-shot0001](https://github.com/mpv-player/mpv/assets/22327220/b9945971-f8e8-4fc3-be40-2402b73904cf)

### Reproduction steps

- mpv --no-config --keep-open=always image.jpg

### Expected behavior

The image renders normally with HDR

### Actual behavior

The gain map shows in HDR, trying to seek via keyboard shortcuts would sometimes show the SDR image (rendered in SDR), the gain map (rendered in HDR), or the correct combined image (rendered in HDR)

### Log file

[mpvlog.txt](https://github.com/mpv-player/mpv/files/15084062/mpvlog.txt)

### Sample files
[04](https://github.com/mpv-player/mpv/assets/22327220/47d23035-29bd-479b-b8da-d585c9c54b51) (from the Adobe [resources](https://helpx.adobe.com/camera-raw/using/gain-map.html#resources))

**Comment by Silver-Fullbuster** [comment] 2024-04-23 23:40
Another thing to note is that using gpu-next, the image simply never renders in HDR.

Log file: [mpvlog.txt](https://github.com/mpv-player/mpv/files/15084106/mpvlog.txt)

**Comment by kasper93** [comment] 2024-04-23 23:47
Already fixed, update to recent version.

Duplicate of #13192

**Closed by kasper93** 2024-04-23 23:47 UTC
Labels: os:win

**Comment by Silver-Fullbuster** [comment] 2024-04-24 00:50
FFmpeg ticket for future tracking: https://trac.ffmpeg.org/ticket/10974#ticket
