### ISSUE TITLE
after resuming play, video freezes on Wayland

### ISSUE THREAD

**Issue by ya-isakov** [mpv-player/mpv#5914] opened 2018-06-10 14:42 UTC
### mpv version and platform
master (starting from commit a743fef837bcab206b1e576db7e7a64b02890449), Gentoo Linux

### Reproduction steps
Under Gnome wayland session, start some video, then pause it, then switch to e.g. chrome, use it a little bit, then switch back to mpv, and unpause.
### Expected behavior
Video continue playing

### Actual behavior
Image frozen, only audio plays

### Log file
http://0x0.st/s_0h.log

### Sample files
Any file is reproducing such behaviour

I've found that commit a743fef837bcab206b1e576db7e7a64b02890449 caused this regression

**Comment by ya-isakov** [comment] 2018-06-19 19:51
@atomnuker I think that was your commit, so do you need any other details to fix it?

**Comment by atomnuker** [comment] 2018-06-20 04:29
That's a mutter regression. This used to work, as it was developed on gnome in the first place. Report it to them and report back on this thread if they say otherwise (if they even respond, they have a history of not doing so, fixing bugs, and not closing issues or even saying they did that).

**Closed by atomnuker** 2018-06-20 04:29 UTC

**Comment by ya-isakov** [comment] 2018-06-20 18:56
@atomnuker I've downgraded gnome-shell and mutter to 3.24, and there is no such problem, so it is a regression, but not in mpv :) Sorry for blaming you and mpv

**Comment by jnsh** [comment] 2019-01-28 03:51
@ya-isakov Did you ever report this to gnome developers?

The issue is still present on with gnome 3.31.*, and I can confirm it appeared at a743fef837bcab206b1e576db7e7a64b02890449. Yet, I couldn't find any open or closed bug reports from gnome's issue trackers.
