### ISSUE TITLE
Glitch of showing asian language subtitles on slower machines

### ISSUE THREAD

**Issue by bodayw** [mpv-player/mpv#2357] opened 2015-09-28 16:43 UTC
*original title: Glitch of showing external subtitles on slower machines

I am using a Mac mini (base model of late 2014, i5-4260U/1.4 GHz/4 GB/500 GB) as HTPC, and I've noticed that sometimes the movie will pause for a brief moment (like 100-200 ms) right before a subtitle line is shown.

Some observations:
~~1. The problem only happens when the subtitle being used is a external ASS file, and never happened with subtitles embedded in the MKV file;~~
2. The problem only happens on my Mac mini and I've never seen it on my other machines with much better CPU, higher memory and SSDs;
3. Usually, after there is no lines to be shown for a few seconds, the problem appears, so you won't see the problem when there are heavy conversations going on, but at the beginning of the movie or after a silent moment;
4. If you go back right after the problem happens, it won't happen again at the same time point.
5. If the CPU usage is high (i.e. if I'm using `vo=opengl-hq:interpolation`), or when the system memory is relatively low (i.e. there are several other apps running), the problem seems more likely to happen (not sure), but I've seen the problem happened when I started playing a movie with lower settings after a fresh reboot.

My naive hunch is that the problem should be related with some kind of caching...

Not sure if this is relevant: All of the external ASS subtitles here happened to be in Chinese, and all of the embedded subtitles are in English with font files embedded as well. However, I'm pretty sure this problem existed on my set up before the recent change of font select in libass.

Is there any config commands that I should try to fix this?

**Comment by wm4** [comment] 2015-09-28 16:47
It's most likely subtitle text rendering or font loading. There is no fix, although libass git might be faster. I hope this can actually be fixed as soon as libass gets refcounting (then it can run in a separate thread and preload frames independently).

**Comment by bodayw** [comment] 2015-09-29 21:17
Alright, after I tested with a few more examples and actually tried muxing the external subtitle into the mkv file, I can confirm now that this problem has nothing to do with subtitles being embedded or not.

AFAIK for now, this problem only happens with Chinese and Japanese text subtitles. Maybe it's just because asian font files are much bigger thus will take much longer to load?

Anyway, thanks for answering and I'm looking forward to the libass update.

**Comment by wm4** [comment] 2015-09-29 21:52
Yes, that's possible. They're large and have e.g. read from the disk in the first place. And again, font fallbacks can make this slower too, and libass git with coretext backend might make it slightly faster (I hope).

**Comment by bodayw** [comment] 2015-09-30 21:47
>libass git with coretext backend might make it slightly faster (I hope).

I'm using the latest OS X build from Chris, which I believe is already using Coretext...so yeah maybe still not fast enough :(

**Comment by bodayw** [comment] 2016-01-22 12:55
>I hope this can actually be fixed as soon as libass gets refcounting (then it can run in a separate thread and preload frames independently).

Is this gonna be implemented soon (like in a few months)? Just curious to ask and not intend to rush you, but this issue is bugging me a lot lately as I can't help noticing it now, and I'm considering to get my htpc an upgrade if it won't be fixed soon.

**Comment by wm4** [comment] 2016-01-22 13:00
>Is this gonna be implemented soon (like in a few months)?

No signs of it.

**Comment by bodayw** [comment] 2016-01-22 19:09
Got it. Thanks!

**Comment by wm4** [comment] 2016-01-22 19:57
PS: I'll also take a look at implementing this by copying the rendered subtitle data, but no promises.

**Comment by wm4** [comment] 2016-01-23 19:42
@bodayw: I've made an experimental branch with what I talked about: https://git.io/vzrMX

Try --sub-render-ahead=50.

**Comment by bodayw** [comment] 2016-01-24 01:24
Sorry but I have no experience compiling branches other than git master...Can I use homebrew for it?

**Comment by bodayw** [comment] 2016-01-24 16:05
...And it works like a charm!

I copied my build to my HTPC and tested with/without ``sub-render-ahead=50`` in the config file, and for each test I rebooted the machine to prevent the system to cache anything related. I could reproduce the small glitch 100% of the time without the new setting, while with it the glitch is gone 100% of the time.

Many many many thanks!

**Comment by wm4** [comment] 2016-01-24 16:13
Interesting. This still has problems though. (Notably, it interferes with frame dropping, which makes behavior worse if the subtitles are simply too slow to be rendered in realtime.)

**Comment by bodayw** [comment] 2016-01-24 16:49
I think the subtitle files I have all have quite simple styles so it should be fine in most cases. I will keep using this build for a while, though, see if I can catch anything bad or wrong.

Also, due to the performance issue on 10.11 (El Capitan) I'm not using any of the ``video-sync=display*`` options at the moment, which in theory should make the problem you described more obvious (causing noticeable video-audio desync), I guess?

(The only pity is that I can't use ``interpolation`` with this build until the 10.11 performance issue is fixed, and actually I was using 0.13.0 before just because of this. But, I'll definitely opt to have the subtitle issue solved if I have to make a trade-off here!)

**Comment by bodayw** [comment] 2016-01-25 01:16
OK...After watching a few episodes tonight I have to agree that this still has problems.

I noticed very brief glitches like before quite a few times while watching, but now they happen at "random" time points instead of happening right before a subtitle line is shown. I further tested with the most obvious/worst case I've seen and it happens roughly 2 s before a subtitle line, which makes sense since 50 frames is just a bit more than 2 s for a 24 fps video.

Interestingly I can reproduce this worst case of sudden heavy drop of frames 100% of the time without rebooting the system. This is not like before where once I see a glitch and then go back a few seconds, mostly likely I won't see the glitch again at the same time point of the video. Is this expected? e.g. normally mpv will try to use the rendered subtitle data computed before and somehow cached by the system, and now with this test branch it always compute everything from scratch?

Also thought and tried a few things:

1. Usually I have a bit torrent client running in the background which typically has a constant 1 Mbyte/s disk read. Tried pausing all the active transfer in the client and make sure disk I/O in the Activity Monitor is zero most of the time, doesn't seem to affect the issue.

2. Could it caused by high memory pressure? 4 GB of memory is a bit tight for OS X nowadays, but since I usually only use very few programs on this machine, this is unlikely to be the case. Also I already tried rebooting the system and only run mpv alone yet still able to reproduce the issue, while there is plenty (~2 GB) of memory left (no compressed memory).

3. Is font fallback taking too long? Tried a) ``ass-force-style=FontName=`` and b) ``sub-text-font=`` with ``ass-style-override=force`` to prevent font fallback, same result; also tried modifying the styles defined in the ASS script with the same system built-in font, same result as well.

4. Is ASS rendering taking too long? Tried ``no-sub-ass``, still same result.

5. Is the traditional spinning hard disk just too slow for mpv to stream video, audio and subtitle-related data at the same time? I guess it's possible that it'll get better if I replace the hard disk with a SSD, but Apple has made it a lot harder to replace the hard disk for this generation of Mac mini, also I still have ~10 months of warranty and don't want to break it yet...

6. Is the CPU/GPU just too weak for this usage? I know that i5-4260U/HD 5000 is by no means powerful, but it's still reasonably "new" (theoretically is even able too handle lower bit-rate 4k video with the help of hardware decoding). However, I tried commenting out ``vo=opengl-hq:icc-profile-auto:icc-cache-dir=~/.config/mpv/icc-cache`` in the config file, still have the same issue.

I'm aware that I have very limited knowledge about the details in the whole process and things I've tried above are based on my naive and probably over-simplified understanding, thus it's hard to draw any conclusions yet. Just write them out and hope they can do a little help.

Further suggestions are welcomed. Also I'm happy to do further test if new commits are made in the test branch.

**Comment by wm4** [comment] 2016-01-25 09:26
I don't know either. There's a small chance that the subtitles are just too heavy for your system to render in realtime at all. Do you have a sample file?

**Comment by bodayw** [comment] 2016-01-25 20:48
I crossed out part of the comment above because that "worst case" I took for testing was actually caused by a bug introduced in the test branch: with ``sub-render-ahead`` mpv will always drop a lot of frames at that particular time point no matter what, even there is no subtitle being rendered (pressed v to hide all subtitles). No idea why this happens, though.

I can upload a sample ASS script but I don't think it's the complexity of the ASS styles are the culprit here. As I already tried using ``no-sub-ass`` yesterday, I just tried to convert the ASS into SRT, discarding all the special styles, yet still have the same issue.

However, I reverted mpv back to 0.13.0 and tried No. 6 above again and then I actually saw some improvements. I used a long horizontal panning scene for this test so that I can notice even very minor frame drops or any motion judder. Disabling ``interpolation`` and color management will make it somewhat better, and if I comment out the whole ``vo=opengl-hq`` line (only use ``vo=opengl`` by default), although I can still see a tiny glitch right before a line is shown, it's almost negligible.

So now I tend to believe that it's just the CPU/GPU are just not powerful enough, and probably the performance issue of 10.11 ( #2392 ) made it worse.

**Comment by wm4** [comment] 2016-01-25 20:58
>even there is no subtitle being rendered (pressed v to hide all subtitles). No idea why this happens, though.

Are you using newest libass? Also, just shuffling the subtitle packets can be a problem, because there can be thousands of packets per second in insane cases. (Whereas normally you'd only have at most 1 packet every 2 seconds or so.)

**Comment by bodayw** [comment] 2016-01-25 21:50
Checked my homebrew cache and it's libass 0.13.1, which should be the version used for that test build.

I didn't shuffle the sub tracks, but just turned them off altogether.

**Comment by bodayw** [comment] 2016-01-26 01:41
New observation: I manually replaced a few lines in the ASS script with English, reboot the machine, and got no glitch at all when those few lines were shown. Looks like Latin letters can just be rendered much faster than Chinese/Japanese characters, even when using the same font type. So it has nothing to do with the size of the font files.

Note that I need to reboot the machine every time to make sure the glitch can be reproduced 100% of the time. Actually after every reboot, the glitch will first happen a few times in a row, then it will very unlikely to happen for a while, even I quit mpv, then open it again and start playing other files with different ASS scripts with different sentences, but has the same fallback font. I guess it's because the OS just cached at least part of the font file in the memory, thus make libass render characters from the font much faster? If this is true, is there a way to let mpv try to cache the font file before the playback starts (instead of the current render-ahead-and-copy approach)?

**Comment by wm4** [comment] 2016-01-26 11:19
Right, so it sounds like the OS is just slow at loading the fonts. I restarting mpv doesn't reproduce the slow behavior, it could be that either OSX CoreText has a system-wide font cache, or that actually reading the font files from the disk is slow.

>is there a way to let mpv try to cache the font file before the playback starts

No.

**Comment by wm4** [comment] 2016-01-26 11:20
PS: with `sub-render-ahead=50` will still render subtitles 50 video frames ahead, which can be as much as 2 seconds. Just how long does that glitch pause you?

**Comment by bodayw** [comment] 2016-01-26 17:33
>it could be that either OSX CoreText has a system-wide font cache

Just tried this: reboot the system, first open the ASS file in the text editor, set the whole script to the fallback font, scroll down to the end to make sure it rendered every single character in the document once, then quit the editor. And then open the video with mpv, NO glitches!

>Just how long does that glitch pause you?

Like I said in the first post, feels like about 100-200 ms. This could be easily off as it's not a "measured" value, but it's safe to say the glitch never last longer than half a second.

Also, I think I've found the reason for that "worst case" which happens every time with ``sub-render-ahead=50". The point it happens is right at the transition of ordered chapters when mpv needs to read another file in the same directory.

**Comment by bodayw** [comment] 2016-01-26 18:21
Tried with the test build again and played around with the value for ``sub-render-ahead``. 24 or even 12 is already good enough in my test case. I looked really carefully but I don't think I noticed any glitch happen 1/0.5 second before a line is shown (I said two days ago that I noticed something wrong "quite a few times, it's probably just me seeing things, or at least those should be irrelevant).

As for the ordered chapter bug I've got interesting observations as well: changing the frame number for ``sub-render-ahead`` to something like 100 or 200 will fix it (not that I can notice it anymore), and so does changing it to a smaller value like 12. With 24 I can still see a little bit of frame drop, but much better than 50. Don't know why 50 is the magic number here.

**Comment by wm4** [comment] 2016-01-26 18:29
>As for the ordered chapter bug I've got interesting observations as well: changing the frame number for sub-render-ahead to something like 100 or 200 will fix it 

It doesn't accept values larger than 50, and should print an error somewhere.

**Comment by wm4** [comment] 2016-01-26 18:29
PS: which also means it's disabled with a larger number.

**Comment by bodayw** [comment] 2016-01-26 18:48
>It doesn't accept values larger than 50, and should print an error somewhere.
PS: which also means it's disabled with a larger number.

I see. Was confused when I saw glitches again with 200...Usually I don't run mpv from the Terminal so I can't see the error messages.

**Comment by bodayw** [comment] 2016-01-26 23:26
Sorry, I feel like I'm just keep reporting stuff to confuse you...I just saw glitches again with ``sub-render-ahead=12`` with some other files, and they happened right 0.5 s before a line is shown. Changed the value to ``24`` and they became happening 1 s before accordingly.

So...it seems the render-ahead-and-copy approach does help the issue to a certain extent, but doesn't fix it completely in my case. Other factors are probably involved as well, for one I can think of here is the file I just watched has higher bitrate: as this glitch is a performance issue after all, higher pressure on the CPU/GPU side can only make it worse.

**Comment by wm4** [comment] 2016-01-27 19:02
The ordered chapter case is complicated; there might be a chance that it gets fixed some day (maybe).

Other than that, I'm still not sure what exactly is going wrong in your case.

**Comment by bodayw** [comment] 2016-01-28 16:56
>I'm still not sure what exactly is going wrong in your case.

I thought we came to sort of a conclusion already:

>Right, so it sounds like the OS is just slow at loading the fonts.

And given that the render-ahead approach can't completely fix the problem, I'm not sure it's still worth going further and looking into the ordered chapter issue. Maybe we should just leave this for now until we're on implementing refcounting for libass?

**Comment by wm4** [comment] 2016-01-28 17:14
This explanation seems likely, but it could be something else too. It also could be a combination of factors.

Btw., I just repushed the sub_render branch, and raised the limit to 500 frames. (Might use a lot of memory.)

**Comment by bodayw** [comment] 2016-01-30 17:21
Recompiled and tried with ``120``, but I don't think there is a difference compared with ``24``, except the glitch happens at a different time point of the video.

With ``500`` mpv will take 1.7 GB of memory and will freeze for about 1 s in the beginning and after seeking.

To summarize, in the case of my test clip, without ``sub-render-ahead`` I get 4-5 glitches while playing, and with ``sub-render-ahead`` I get only one, but I still can't get rid of this one from happening.

**Comment by thebombzen** [comment] 2018-01-13 17:32
Is this still a problem with mpv 0.28.0?

**Comment by bodayw** [comment] 2018-01-14 05:40
Sorry but I no longer have the said Mac mini for quite a while. I actually tried to boot from an external USB 3.0 SSD, and I don't recall seeing this issue again after that. It's likely that I even tested it intentionally after I got the SSD, but I'm not sure.

Anyway, it's quite possible that using an SSD fixes this issue, and I don't see much point digging into this further...

**Comment by kevmitch** [comment] 2018-01-14 05:59
Ok, closing since the only person who ever reproduced the issue can no longer do so. Someone can open a new bug if there are still problems.

**Closed by kevmitch** 2018-01-14 05:59 UTC
Labels: osx
