### ISSUE TITLE
the F8 and F9 keys (broken on the terminal)

### ISSUE THREAD

**Issue by requiredregistration** [mpv-player/mpv#7779] opened 2020-05-30 19:03 UTC
will these be fixed soon?

**Comment by CounterPillow** [comment] 2020-05-30 19:06
Your issue has been closed because you have ignored the issue template. Issue templates will appear when you open a new issue, and choose which category of issue you want to report. Currently, a GitHub bug prevents this choice from appearing if you're not logged in at the time you click on the new issue button, so if you never saw any template, that may be why.

Our closing of this issue does not mean that the problem you are experiencing is not real or that we somehow are being rude to you, it's simply a matter of issue triage to separate those we can do something about (ones that fill out the issue template) from those that waste everyone's time by not providing us with the information we explicitly and very clearly ask for (yours).

Following our established processes helps you get your issue resolved quicker, and helps us in identifying the issue. If you are unwilling to follow this simple process we are unwilling to have you on our issue tracker.

**Closed by CounterPillow** 2020-05-30 19:06 UTC
Labels: priority:ignored-issue-template

**Comment by requiredregistration** [comment] 2020-05-31 02:26
a template is not required for this.

it is in the manual.

https://github.com/mpv-player/mpv/blob/master/DOCS/man/mpv.rst
F8
Show the playlist and the current position in it (useful only if a UI window is used, broken on the terminal).
F9
Show the list of audio and subtitle streams (useful only if a UI window is used, broken on the terminal).

as in, you know about it already.

**Comment by CounterPillow** [comment] 2020-05-31 05:21
```
$ mpv --idle --input-test
[input] Key F8 is bound to:
[input] 1.  'show_text ${playlist}' in <builtin>:1 (default)
Key F8 is bound to:
1.  'show_text ${playlist}' in <builtin>:1 (default)
Key F8 is bound to:
1.  'show_text ${playlist}' in <builtin>:1 (default)
[input] Key F9 is bound to:
[input] 1.  'show_text ${track-list}' in <builtin>:1 (default)
Key F9 is bound to:
1.  'show_text ${track-list}' in <builtin>:1 (default)
Key F9 is bound to:
1.  'show_text ${track-list}' in <builtin>:1 (default)
```
they work fine

**Comment by CounterPillow** [comment] 2020-05-31 05:27
if you mean that the function they are mapped to is not producing output in the terminal, then you should have mentioned this in the issue, which is part of the issue template (hence why we have an expected behaviour heading)

**Comment by Argon-** [comment] 2020-05-31 09:55
> as in, you know about it already

I know that it works for me.

**Comment by requiredregistration** [comment] 2020-06-04 18:52
yes, the keys do work. so, the manual needs updating there (both are useful and not broken on the terminal).

now, about the output.

useless white space after the last parentheses in the stream info and that "{\alpha&HFF}", "{\r}", "�", "ý", and "þ" stuff.

xterm:
```
F9
Video: �{\alpha&HFF}➜ {\r}�(1) 

Audio: ��� �(1) (eng) 

Sub: ��� �(1) (eng) 
```
```
F8
��� �archive://Superman.rar|/Superman.avi
�{\alpha&HFF}➜ {\r}�Superman.rar
```
urxvt:
```
F9
Video: ý{\alpha&HFF}➜ {\r}þ(1) 

Audio: ý➜ þ(1) (eng) 

Sub: ý➜ þ(1) (eng) 
```
```
F8
ý➜ þarchive://Superman.rar|/Superman.avi
ý{\alpha&HFF}➜ {\r}þSuperman.rar
```

**Comment by requiredregistration** [comment] 2020-06-11 04:59
i am not sure i understand why this cannot be fixed.

the subtitles are displayed properly in the terminal and in the OSD.

if --video=no is specified or there is no video stream, then output to terminal.
