### ISSUE TITLE
How to hide mpv from dock?

### ISSUE THREAD

**Issue by miagile** [mpv-player/mpv#6338] opened 2018-11-24 14:21 UTC
### mpv version and platform
v0.29.1, OSX

### Reproduction steps
mpvPath  --input-ipc-server=socketPath --idle 
### Expected behavior
   Run mpv in background, do not display it in the dock
### Actual behavior
  mpv icon is always displayed in the dock

===========
I'm running mpv embedded in an app and I would like to display only the my app icon in the dock and hide mpv icon. Is there any option to hide it from dock? I've tried several things such using `LSUIElement` in Info.plist but it has no effect.  It seems the app itself should use something like    [NSApp.setActivationPolicy(.accessory)](https://developer.apple.com/documentation/appkit/nsapplicationactivationpolicy?language=objc).  I think on windows there is an equivalent method( [ShowInTaskbar]( https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.form.showintaskbar?redirectedfrom=MSDN&view=netframework-4.7.2#System_Windows_Forms_Form_ShowInTaskbar) ) to remove it from task bar.

**Comment by Akemi** [comment] 2018-11-24 14:32
`mpv --idle` doesn't create a Dock icon till a window is spawned, eg a video is played.

you have to explain your use case better, since i don't really know what you are doing and what your expected behaviour is. if you embedded mpv into an app why not use libmpv?

**Comment by miagile** [comment] 2018-11-24 15:35
> mpv --idle doesn't create a Dock icon till a window is spawned, eg a video is played.

I understand, still in my case it would be better to run mpv as an "accessory" app without displaying any icon in the Dock regardless if the video is played or not. It confuses the end user as it is expecting to see only one app running, not two. The main app keeps mpv open in fullscreen(see full command below[1] ) and manages the app focus/screen switching (i.e. when the client is indicating that is done playing video <via a remote control> I switch to the main / UI app).

> you have to explain your use case better, since i don't really know what you are doing and what your expected behaviour is. if you embedded mpv into an app why not use libmpv?

- mpv player works as stand alone app (started in idle mode) almost perfectly for my use case(except I need to hide the dock icon). 
- Implementing libmpv would require additional effort and perhaps expertise I do not have yet. 
- The language(Go) that I'm using for the main app does not have good bindings support for libmpv so I think I would have to write bug free bindings myself which may not be trivial. Go does not usually play nice with C GUI libs which is the reason why there is no production ready GUI lib(AFAIK). 
- I'm afraid that by using libmpv  I would have to reinvent things that are already implemented in the stand alone app such support for youtube-dl or other plugins.

As mpv is designed to work as a background process (--idle, controlled through IPC) I believe a feature to hide the Dock icon & menu would only make it a stronger candidate for this use case. Background apps/processes are not supposed to be displayed in the Dock.


[1] 
```
	cmd := exec.CommandContext(cx, mpvPath,
		"--input-ipc-server="+socketPath,
		"--idle",
		"--keep-open=yes",
		"--force-window=immediate",
		"-fs",
		//"--no-ytdl",
		"--no-input-default-bindings",
		"--input-appleremote=no",
		"--input-media-keys=no",
		"--input-vo-keyboard=no",
		//"--vo=gpu",
		"--demuxer-thread=yes",
		"--demuxer-readahead-secs=3600",
		// 10GB cache
		"--cache=10737418",
		"--msg-level=all=error",
		"--log-file="+logFile,
	)

```

**Comment by Akemi** [comment] 2018-11-24 16:37
> - I'm afraid that by using libmpv  I would have to reinvent things that are already implemented in the stand alone app such support for youtube-dl or other plugins.

nope.

> As mpv is designed to work as a background process (--idle, controlled through IPC)...

no mpv isn't designed as a background app. that would be a service or daemon. `--idle` isn't implying that either.

two suggestions:
1. if you build mpv yourself just change this [line](https://github.com/mpv-player/mpv/blob/master/video/out/cocoa_cb_common.swift#L91) to use `.accessory` like you mentioned.
2. use `wid` embedding instead of the libmpv render API. it's a lot easier to [implement](https://github.com/mpv-player/mpv-examples/blob/master/libmpv/cocoa/cocoabasic.m). unfortunately this isn't supported with the new cocoa-cb backend only with the old cocoa one. libmpv is available exactly for your use case.

what we could do:
1. implement `wid` embedding for cocoa-cb. quite a bit of work and you seem to not want to use libmpv.
2. add an option for the activation policy. this might never work properly in all cases (eg starting mpv without a video will always be `.accessory`).

**Comment by jeeb** [comment] 2018-11-24 16:47
>     * The language(Go) that I'm using for the main app does not have good bindings support for libmpv so I think I would have to write bug free bindings myself which may not be trivial. Go does not usually play nice with C GUI libs which is the reason why there is no production ready GUI lib(AFAIK).
For the record, using C libraries from golang has been a primary thing for a long time, and while there's been some rough edges, after one of the people I know complained about not having documented the life times of things, the [documentation](https://golang.org/cmd/cgo/) was supposed to be improved.

I really don't see GUI stuff as any different to anything else, just that golang is mostly utilized in server contexts so people just don't build too many wrappers around GUI things. I would definitely give it a pop if nothing else for a thought experiment. The [examples repo](https://github.com/mpv-player/mpv-examples/tree/master/libmpv) has some example code to look for how to initialize things etc.

**Comment by Akemi** [comment] 2020-01-22 14:22
are you still interested in this feature, eg defining the activation policy with an option?

**Comment by Akemi** [comment] 2020-01-26 11:15
closing this for now, since imo it's out of scope for us and if there is no further need for it.

**Closed by Akemi** 2020-01-26 11:15 UTC
Labels: os:mac
