### ISSUE TITLE
Ass drawing freezes for the first time on Windows 10.

### ISSUE THREAD

**Issue by franzf** [mpv-player/mpv#2443] opened 2015-11-02 00:51 UTC
Regression I've noticed since upgrading from mpv 0.10.0-git-181e137 "2015-09-03" to mpv 0.12.0-git-5b7d0fb "2015-10-29" from http://mpv.srsfckn.biz. Drawing the progress bars, etc make the player freeze and skip a bunch of frames for the first time. Here's a screen recording:

![y mp4](https://cloud.githubusercontent.com/assets/869168/10872441/d458884a-80cf-11e5-8f3b-1f6dab423727.gif)

In this recording, first I drag a video on version "2015-09-03", then press `o` for the position bar. It all goes well. Then I do the same thing with "2015-10-29", and the video freezes for a couple seconds (the position bar flashes when it starts moving again, but seems this screen recorder didn't capture it). Subsequent OSD draws work normally, no freeze. I have no configuration files on AppData. 

Maybe related to #2392 ? I should try an older version on OS X too.

mpv 0.12.0-git-5b7d0fb "2015-10-29", Windows 10

**Comment by haasn** [comment] 2015-11-02 00:52
Just mentioning that I have the same problem, on Linux; but on my end it's *significantly* shorter. Might be due to fontconfig then?

(I was not aware of it being a regression, either)

**Comment by shinchiro** [comment] 2015-11-02 01:14
I also experience same problem. Using windows 8 here. Pressing `o` freeze the video awhile. I think its related with my problem as #2431

**Comment by wm4** [comment] 2015-11-02 08:25
This is an issue with the DirectWrite backend in libass git, and it's being resolved.

@haasn: you could test if libass before the fonts merge had such a problem.

**Comment by shinchiro** [comment] 2015-11-08 01:53
this issue seem fixed in latest libass commit

you can try my build (compile using lachs0r's script)
http://ow.ly/UnhPd

**Comment by lachs0r** [comment] 2015-11-10 19:00
Should be fixed with the latest build.

**Closed by lachs0r** 2015-11-10 19:00 UTC
