### ISSUE TITLE
Subtitles sometimes don't keep sync

### ISSUE THREAD

**Issue by ANDREW007CZ** [mpv-player/mpv#7567] opened 2020-03-30 12:41 UTC
### Important Information

Provide following Information:
- mpv version: 20200329
- Windows Version: 1909
- Source of the mpv binary: Windows builds by shinchiro
- If known which version of mpv introduced the problem: don't know
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

### Expected behavior
After proper delaying, subtitles go in sync through the whole movie. (As in MPC-HC they do).

### Actual behavior
After few seconds in sync subtitles start to drag themselves late, and become gradually behind.

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.
omg, how do I make one? See, I am merely a user. There is no advice anywhere how to do this...?!

The issue will be closed for ignoring the issue template.

### Sample files
Actually I cant give direct link to download the show. We could PM.. ?

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by mia-0** [comment] 2020-04-26 18:50
Well, you haven’t given us the information we ask for in the issue template. Without it, we cannot even begin to identify the cause of your problem.

The stuff with `--log-file=output.log` goes on mpv’s command line. If you don’t know how to do that, I suggest learning about it. This is not arcane computer wizardry but rather basic literacy, and without it, you are not going to have a fun time trying to use and configure mpv.

I am closing this issue for now. Feel free to open a new one when you are able to provide all the required information.

**Closed by mia-0** 2020-04-26 18:50 UTC
Labels: os:win, priority:ignored-issue-template
