### ISSUE TITLE
v0.18.0 crashes on opening on OS X 10.8.5

### ISSUE THREAD

**Issue by PacoH** [mpv-player/mpv#3309] opened 2016-07-03 17:43 UTC
v0.18.0 crashes on opening on OS X 10.8.5
### command line output

```
/Applications/mpv.app/Contents/MacOS/mpv 
dyld: Symbol not found: _kCTLanguageAttributeName
  Referenced from: /Applications/mpv.app/Contents/MacOS/lib/libharfbuzz.0.dylib
  Expected in: /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
 in /Applications/mpv.app/Contents/MacOS/lib/libharfbuzz.0.dylib
```
### mpv version and platform

v0.18.0
### Reproduction steps

`cmd-o` on app in Finder
### Expected behavior

opens
### Actual behavior

crashes
### Log files

http://sprunge.us/EiIW

**Comment by Cpuroast** [comment] 2016-07-05 16:37
The OSX builds referenced here: https://mpv.io/installation are for 10.9 and up.

As you may or may not know Apple has dropped support for 10.6, 10,7 and 10.8. Many applications including Google Chrome and Firefox are doing the same.

I would highly recommend upgrading to at least OS X 10.9 which is still supported.

**Comment by PacoH** [comment] 2016-07-05 17:41
Oh, well why didn't you say so? Fortunately the latest build from the Coalgirls still works. I have been putting off upgrading the OS since, when I do, I will start from scratch, a daunting undertaking. I have years of accumulated apps and scripts, etc. Thanks for the heads up.

**Comment by Cpuroast** [comment] 2016-07-05 17:53
If you are talking about http://sva.wakku.to/~chris/mpv_builds

Those probably still work, but the person who used to build them, at least for the time being, isn't any more. The latest build there is somewhere between 0.14.0 and 0.15.0.

So as long as it works for you and you are happy to use the older build, it should be fine until you do end up grading your OS.

The alternative is to use homebrew to build mpv for 10.8 yourself.

**Comment by PacoH** [comment] 2016-07-05 19:02
Yes, those builds. I tried building it with `brew` but had nothing but problems, including a sha256 error, so I gave up. Thanks for you help.

**Comment by PacoH** [comment] 2016-07-06 00:49
I could attempt to build it myself. Is there any documentation about building it on OS X? Also, I ran into problems building `mplayer` itself with `brew` because the developer disabled all `X11` support, so there was no `OSD` functionality. I even found and  posted a workaround and he immediately closed the thread , and when I complained, he locked it. He told me to contact `mplayer` developers to ask them to stop relying on `X11`. Does `mpv` bypass that requirement?

**Comment by Argon-** [comment] 2016-07-06 04:02
>I could attempt to build it myself. Is there any documentation about building it on OS X?

Yes: `brew install mpv`. Done.
You don't even have to compile it as there is a bottle (binary, in homebrew slang).

>Does mpv bypass that requirement?

mpv doesn't need X11. But I don't get the problem, when you need it just install it: https://www.xquartz.org/

**Comment by Argon-** [comment] 2016-07-06 04:10
Also, I can totally see why your "thread" (it's an issue btw, this is not a discussion forum but a bug tracker) was closed as they considered the bug invalid. You basically provided a half-assed patch introducing X11 as requirement. As the guy said, homebrew has a rule of not including stuff OSX doesn't provide as a requirement. Either you follow that rule or search for a different package manager when discussion is not desired.

As for why you didn't just go for an optional requirement, I don't know. I assume an optional requirement sent as proper pull request might be successful. (See mpv: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpv.rb#L36)

**Comment by stolendata** [comment] 2016-07-10 17:53
As cross-version-SDK compiling is no longer supported in the OS X dev environment I unfortunately can't supply "native" 10.8 builds, and building with 10.8 as the deployment target just doesn't want to work. Admittedly I haven't dug deeper into why deploying for 10.8 under 10.11 is a no-go, but I wouldn't bet on it changing, so for those of you still on 10.8 I think that `brew install mpv` as mentioned a few posts earlier is the only option.

**Comment by PacoH** [comment] 2016-07-10 18:13
My "half-assed patch", as you so quaintly call it, has the distinct advantage of working. The brew build itself _requires_ X11 in order for the OSD and subtitles to work. What 'optional requirement' are you talking about, and what is all that about 'an optional requirement sent as proper pull request'. I don't know how to do that but would it work?

As for installing a `bottle`, you skipped a few steps. In any case I am having problems installing even the pre-compiled version. `brew` installed python3 as one of the dependencies and I am getting error messages about it:

    Your PYTHONPATH points to a site-packages dir for Python 2.x but you are running Python 3.x!
         PYTHONPATH is currently: "/usr/local/lib/python2.7/site-packages"
         You should `unset PYTHONPATH` to fix this.
I tried fixing this but have not yet succeeded. Any suggestions?

**Comment by stolendata** [comment] 2016-07-10 18:15
What exactly requires X11 when you brew it on 10.8? Are you brewing with a certain option, or are you brewing any of the dependencies (ffmpeg, mplayer etc.) separately? On 10.11 it does -not- require X11.

**Comment by PacoH** [comment] 2016-07-10 18:35
No, I'm talking about the default installation. It does not support OSD or subtitles and I found out others had that problem because the latest builds are built with the `--disable-x11` option that can't be overridden except by altering the `rb` file itself. See [No OSD in mplayer · Issue \#49861 · Homebrew/legacy\-homebrew](https://github.com/Homebrew/legacy-homebrew/issues/49861#issuecomment-193694505).

Now, are you able to get OSD and subtitles in your installed `mplayer`? If 10.11 doesn't require X11, then what has replaced it? maybe I could install whatever the replacement for X11 is.

**Comment by stolendata** [comment] 2016-07-10 18:44
OSD/subs works fine in mpv. X11 is not involved in this. I have no idea about mplayer as I don't use it, nor is it needed for mpv; mpv is a fork of mplayer, not a "frontend" for it. Try cleaning out your brewery and rebuilding, or perhaps just do a local installation solely for mpv, like so:

`mkdir -p isolated/homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C isolated/homebrew
<add relevant PATH, close and reopen your terminal>
brew tap homebrew/core
brew update
brew install --with-bundle mpv`

**Comment by wm4** [comment] 2016-07-10 18:46
mpv certainly doesn't require x11 for OSD. It uses libass for OSD rendering, which in turn requires fribidi, freetype, and harfbuzz, all of which can be built and used without x11.

**Comment by Argon-** [comment] 2016-07-10 18:46
@stolendata 
> 10.8 as the deployment target just doesn't want to work

10.8 is officially no longer supported. I could imagine it being an artificial restriction from Apple, they sometimes do such shit.

@PacoH 
> has the distinct advantage of working

Yeah but you might have noticed that they do not want this (kind of hard-coded) solution. A lot of stuff works, doesn't mean it should get implemented. In this particular case there is a cleaner solution.

> The brew build itself requires X11 in order for the OSD and subtitles to work.

Yes but it does not require X11 in order to compile a working player. You'll get one working just fine without. Apparently they do not consider the OSD as a mandatory feature.

> What 'optional requirement' are you talking about, and what is all that about 'an optional requirement sent as proper pull request'. I don't know how to do that but would it work?

It is possible to make X11 an optional requirement. That means you are not required to have it to install/compile the formula but you can optionally request a build with X11. If you do not know how to do this then I kindly refer you to the homebrew docs, you could also take a look at the mpv formula. 
Once you've done this send them a pull request instead of pasting the diff into an issue.

It's actually all pretty simple. They do not want mandatory requirements on X11 in formulas and mplayer is able to compile without X11. Additionally they do not consider the OSD/subs as crucial part. So, now there's pretty much one option left: include X11 into the mplayer formula as an optional dependency. I don't see any other solution they might accept. But apparently you don't accept this but that's kind of... your problem.

Just use mpv. Subs and OSD work fine without X11 here.

**Comment by PacoH** [comment] 2016-07-10 22:28
> OSD/subs works fine in mpv. X11 is not involved in this. I have no idea about mplayer as I don't use it, nor is it needed for mpv; mpv is a fork of mplayer, not a "frontend" for it.

Well, the version of `mpv` I have requires me to create a config file and hardcode the **duration** of the OSD, which is not what I want. I should be able to toggle it on and off just like I can in `mplayer` WITH X11 support only, as I have mentioned already more than once. Of course `mpv` is not a GUI for `mplayer`. But what is it using instead of X11?

> Try cleaning out your brewery and rebuilding, or perhaps just do a local installation solely for mpv

OK, I ran `brew cleanup` but that didn't help. As far as making a separate `brew` installation, I'd be better off submitting an issue and trying to straighten out the problem. It's probably some environment variable or path problem.

**Comment by wm4** [comment] 2016-07-10 22:38
>Well, the version of mpv I have requires me to create a config file and hardcode the duration of the OSD, which is not what I want. I should be able to toggle it on and off just like I can in mplayer WITH X11 support only, as I have mentioned already more than once. 

Sounds like you want shift+o or so?

>Of course mpv is not a GUI for mplayer. But what is it using instead of X11?

Cocoa? I don't know what part of mplayer supposedly needs X11 here, since mplayer also has a Cocoa backend. At worst mplayer is going to need fontconfig, but that doesn't really need X11. Maybe I'm missing something here.

**Comment by PacoH** [comment] 2016-07-10 22:51
`mplayer` uses `o` to cycle through the OSD.

There's no 'supposedly'. As I have indicated _ad nauseam_, `mplayer` **definitely** requires X11 for OSD to work. That's the only thing I had to include to get that functionality. But I'd rather be able to install the latest `mpv` at this point.

**Comment by PacoH** [comment] 2016-07-10 22:56
> mpv certainly doesn't require x11 for OSD. It uses libass for OSD rendering

It seems it needs more than that, but not X11:

    $ brew deps mpv
    cairo
    ffmpeg
    fontconfig
    freetype
    fribidi
    gdbm
    gettext
    glib
    gobject-introspection
    harfbuzz
    icu4c
    jpeg
    lame
    libass
    libffi
    libpng
    libtiff
    libxml2
    little-cms2
    lua
    openssl
    pcre
    pixman
    pkg-config
    python
    python3
    readline
    sqlite
    x264
    xvid
    youtube-dl

**Comment by wm4** [comment] 2016-07-10 23:08
>There's no 'supposedly'. As I have indicated ad nauseam, mplayer definitely requires X11 for OSD to work.

That's false from what I remember, but whatever.

I'm not sure what pulls in cairo or why they apparently link harfbuzz to glib and icu (the _most_ bloated optional deps of harfbuzz), or why they link ffmpeg against xvid, or what even pulls in sqlite, but mpv doesn't use any of them directly.

**Comment by PacoH** [comment] 2016-07-10 23:18
>So, now there's pretty much one option left: include X11 into the mplayer formula as an optional dependency. I don't see any other solution they might accept. But apparently you don't accept this but that's kind of... your problem.

I don't know where you're getting the conclusion that `apparently you don't accept this`. The developer made it very clear that he doesn't intend to make X11 an option. He was very hostile to the idea.

The latest `mpv` is the obvious goal.

**Comment by PacoH** [comment] 2016-07-10 23:27
One thing that really irks me is that installing `mpv` reinstalls a number of modules, some that were custom built. Like `ffmpeg`. I'm sure it's leaving out many of the options I originally installed, so I'll probably have to reinstall it. It also re-installs `python`. That's probably what broke it to begin with. I can find no way to force brew to install only missing options. It's either all or none.

**Comment by Argon-** [comment] 2016-07-11 05:56
When installing something it will check for dependencies. When you do not have the latest version of the dependency installed then it will reinstall it (actually, install the latest version additionally). It will do so with the same options you used for the previous installation as you could've confirmed yourself by using `brew info ffmpeg` which lists installed versions along with the parameters/config used...

**Comment by Argon-** [comment] 2016-07-11 06:04
Side note:
wm4 is right, mplayer does _not_ need X11 for the OSD, it merely needs some things X11 pulls in.
This is the mplayer homebrew formula in an older version: https://github.com/Homebrew/homebrew-core/commit/d4a15fd569ef6302c9f905eacd83714e8fba12aa#diff-da3eb3290eae8c51a359390259074a8fL25
You can see that it had an optional dependency on X11. Needed was apparently the config option `--enable-menu` for mplayer and the dependencies `fontconfig`, `freetype`, `libpng` which could either get included directly or indirectly by including X11 (see line 33).

**Comment by stolendata** [comment] 2016-07-13 19:18
> One thing that really irks me is that installing mpv reinstalls a number of modules, some that were custom built. Like ffmpeg. I'm sure it's leaving out many of the options I originally installed, so I'll probably have to reinstall it. It also re-installs python. That's probably what broke it to begin with. I can find no way to force brew to install only missing options. It's either all or none.

@PacoH So why not just follow my advice and do a completely isolated, local brew of mpv? When you're done you can either keep the dir for updating to future releases of mpv, or just delete it.

**Comment by PacoH** [comment] 2016-07-13 22:59
Because I have to fix this `python` problem anyway. It affects many things having to do with `brew`.

**Comment by Akemi** [comment] 2017-01-20 01:21
i don't even know what this is about anymore. i won't support 10.8 anymore.

**Closed by Akemi** 2017-01-20 01:21 UTC
Labels: osx
