### ISSUE TITLE
Unexpected audio clipping when using audio filters

### ISSUE THREAD

**Issue by oakkitten** [mpv-player/mpv#9979] opened 2022-03-13 14:35 UTC
I wanted to have more 🅱️ass so I ran `mpv` with `-af=equalizer=f=55:width_type=o:w=1:g=16`. This (edit: assuming this adds 16dB gain to around 55Hz) resulted in some awful clipping. This wasn't entirely unexpected, but I noticed that my other audio player, foobar200, doesn't produce any clipping even at full loudness with a similar setting, and, what's more important, mpv was producing distorted audio even when master volume being very low.

Also tried adding `-af=format=float`, which did not help. The clipping can be remedied by adding `volume=-16dB` before *or after* the equalizer filter.

Asked about this on IRC and they could reproduce the issue on Linux.

### Important Information

- mpv version: 0.34.0-230-g7ac4b7dfe7 (issue reported on other versions as well)
- Platform and Version: Windows 10, 20H2 (reported on Linux also)
- Source of the mpv binary: [shinchiro builds](https://sourceforge.net/projects/mpv-player-windows/)

### Reproduction steps

~~Run `mpv file --no-config -af=volume=5 -volume 50`~~ (Edit: in *this* case `format=float` fixes the situation!)

Run `mpv file --no-config -af=equalizer=f=55:width_type=o:w=1:g=16 -volume 20` 

### Expected behavior

mpv does not clip. It should clip only if the master volume is high.

### Actual behavior

The audio is clipping, even if you reduce the master volume further.

<details><summary>
Log
</summary>

    mpv file.opus -af=format=float,equalizer=f=55:width_type=o:w=1:g=16 --no-config -v
    [cplayer] Command line options: 'file.opus' '-af=format=float,equalizer=f=55:width_type=o:w=1:g=16' '--no-config' '-v'
    [cplayer] mpv 0.34.0-100-g0e76372e86 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
    [cplayer]  built on Sun Dec 12 16:39:46 +08 2021
    [cplayer] FFmpeg library versions:
    [cplayer]    libavutil       57.11.100
    [cplayer]    libavcodec      59.14.100
    [cplayer]    libavformat     59.10.100
    [cplayer]    libswscale      6.1.101
    [cplayer]    libavfilter     8.19.100
    [cplayer]    libswresample   4.0.100
    [cplayer] FFmpeg version: git-2021-12-12-466441a0
    [cplayer]
    [cplayer] Configuration: /home/shinchiro/build64/packages/mpv-prefix/src/mpv/waf configure --enable-static-build --enable-pdf-build --disable-manpage-build --enable-libmpv-shared --enable-lua --enable-javascript --enable-sdl2 --enable-libarchive --enable-libbluray --enable-dvdnav --enable-uchardet --enable-rubberband --enable-lcms2 --enable-openal --enable-spirv-cross --enable-vulkan --enable-vapoursynth --prefix=/home/shinchiro/build64/install/mingw
    [cplayer] List of enabled features: asm build-date cplayer cuda-hwaccel cuda-interop d3d-hwaccel d3d11 d3d9-hwaccel debug-build direct3d dos-paths dvdnav egl-angle egl-angle-win32 egl-helpers ffmpeg ffmpeg-aviocontext-bytes-read ffnvcodec gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win32 gpl iconv javascript jpeg lcms2 libarchive libass libavdevice libbluray libm libmpv-shared libplacebo libplacebo-v4 lua luajit mingw noexecstack openal optimize plain-gl posix-or-mingw rubberband sdl2 sdl2-audio sdl2-gamepad sdl2-video shaderc shaderc-static spirv-cross spirv-cross-static static-build stdatomic uchardet vapoursynth vector vulkan wasapi win32-desktop win32-internal-pthreads zimg zlib
    [cplayer] Setting option 'af' = 'format=float,equalizer=f=55:width_type=o:w=1:g=16' (flags = 8)
    [cplayer] Setting option 'config' = 'no' (flags = 8)
    [cplayer] Setting option 'v' = '' (flags = 8)
    [cplayer] Waiting for scripts...
    [osd/libass] libass API version: 0x1502000
    [osd/libass] libass source: commit: c75017b4e7ad686009c0ac14b7d9b22db4811aa1
    [osd/libass] Shaper: FriBidi 1.0.11 (SIMPLE) HarfBuzz-ng 3.2.0 (COMPLEX)
    [osd/libass] Setting up fonts...
    [osd/libass] Using font provider directwrite (with GDI)
    [osd/libass] Done.
    [cplayer] Set property: shared-script-properties -> 1
    [cplayer] Set property: shared-script-properties -> 1
    [cplayer] Done loading scripts.
    [cplayer] Running hook: ytdl_hook/on_load
    [ytdl_hook] ytdl:// hook
    [ytdl_hook] not a ytdl:// url
    [cplayer] Set property: shared-script-properties -> 1
    [ifo_dvdnav] Opening file.opus
    [cplayer] Set property: shared-script-properties -> 1
    [bdmv/bluray] Opening file.opus
    [osd/libass] libass API version: 0x1502000
    [osd/libass] libass source: commit: c75017b4e7ad686009c0ac14b7d9b22db4811aa1
    [file] Opening file.opus
    [demux] Trying demuxers for level=normal.
    [osd/libass] Shaper: FriBidi 1.0.11 (SIMPLE) HarfBuzz-ng 3.2.0 (COMPLEX)
    [osd/libass] Setting up fonts...
    [osd/libass] Using font provider directwrite (with GDI)
    [osd/libass] Done.
    [lavf] Found 'ogg' at score=100 size=2048.
    [file] stream level seek from 131072 to 2920642
    [file] stream level seek from 2985949 to 15346
    [file] stream level seek from 15346 to 145
    [lavf] avformat_find_stream_info() finished after 32913 bytes.
    [demux] Detected file format: ogg (libavformat)
    [cplayer] Opening done: file.opus
    [find_files] Loading external files in .
    [cplayer] Running hook: ytdl_hook/on_preloaded
    [lavf] select track 0
    [cplayer]  (+) Audio --aid=1 --alang=eng (opus 2ch 48000Hz)
    [ad] Codec list:
    [ad]     opus - Opus
    [ad]     libopus (opus) - libopus Opus
    [ad] Opening decoder opus
    [ad] Requesting 1 threads for decoding.
    [ad] Selected codec: opus (Opus)
    [user_filter_wrapper] Setting option 'format' = 'float' (flags = 0)
    [af] User filter list:
    [af]   format (format.00)
    [af]   equalizer (equalizer.00)
    [cplayer] Starting playback...
    [af] [in] 48000Hz stereo 2ch floatp
    [af] [format] 48000Hz stereo 2ch floatp
    [autoconvert] inserting resampler
    [swresample] format change, reinitializing resampler
    [swresample] 48000Hz stereo floatp -> 48000Hz stereo float
    [af] [equalizer] 48000Hz stereo 2ch float
    [af] [userspeed] 48000Hz stereo 2ch floatp
    [af] [userspeed] (disabled)
    [af] [convert] 48000Hz stereo 2ch floatp
    [ao] Trying audio driver 'wasapi'
    [ao/wasapi] requested format: 48000 Hz, stereo channels, floatp
    [ao/wasapi] No device specified. Selecting default.
    [ao/wasapi] Selecting device '{958ca1b3-b27d-4050-a11f-b913e2bc3b54}' (Хитачя (2- High Definition Audio Device))
    [ao/wasapi] Monitoring changes in device {0.0.0.00000000}.{958ca1b3-b27d-4050-a11f-b913e2bc3b54}
    [ao/wasapi] Trying stereo float (32/32 bits) @ 48000hz (shared) -> ok
    [ao/wasapi] Accepted as stereo float @ 48000hz -> stereo float (32/32 bits) @ 48000hz (shared)
    [ao/wasapi] Device period: 10 ms
    [ao/wasapi] Buffer frame count: 2400 (50 ms)
    [ao/wasapi] IAudioClock::GetFrequency gave a frequency of 384000.
    [ao/wasapi] device buffer: 2400 samples.
    [ao/wasapi] using soft-buffer of 9600 samples.
    [cplayer] AO: [wasapi] 48000Hz stereo 2ch float
    [cplayer] AO: Description: Windows WASAPI audio output (event mode)
    [autoconvert] inserting resampler
    [swresample] format change, reinitializing resampler
    [swresample] 48000Hz stereo floatp -> 48000Hz stereo float
    [af] [out] 48000Hz stereo 2ch float
    [cplayer] audio ready
    [cplayer] starting audio playback
    [cplayer] playback restart complete @ 0.000000, audio=playing, video=eof
    [cplayer] Set property: shared-script-properties -> 1
    [statusline] A: 00:00:00 / 00:02:48 (0%)
    [cplayer] Set property: shared-script-properties -> 1
    [statusline] A: 00:00:02 / 00:02:48 (2%)
    [lavf] queuing seek to 7.538623
    [lavf] execute seek (to 7.538623 flags 32)
    [cplayer] hr-seek, skipping to 7.531123
    [file] stream level seek from 131217 to 2984924
    [file] stream level seek from 2985949 to 113349
    [file] stream level seek from 244421 to 96965
    [lavf] seek done

</details>

**Comment by haasn** [comment] 2022-03-13 14:42
`-af=volume=5 -volume 50`

(Should be `volume=8` for easier reproduction, which is the exact mathematical inverse of `-volume 50`)

**Comment by amariami** [comment] 2022-03-13 17:19
>mpv was producing distorted audio even when master volume being very low.

I'm on your side, sometimes i didn't success using some equalizer [ffmpeg audio filter](https://ffmpeg.org/ffmpeg-filters.html#toc-Audio-Filters). I don't know it's right asking here if that problem from FFmpeg or MPV itself.

>`--af=equalizer=f=55:width_type=o:w=1:g=16` https://ffmpeg.org/ffmpeg-filters.html#equalizer

Adding precision/r (`:r=auto` or `s16/s32/f32/f64`) does it help?

After browsing on the internet i found interesting article about [phase rotation](http://downloads.izotope.com/docs/rx6/49-phase/index.html#visual-example-of-phase-rotation). I see [stereotools on ffmpeg audio filter](https://ffmpeg.org/ffmpeg-filters.html#stereotools) then rotate to 360 degrees, 180 degrees or change up to your preference depending on stereo mode are set
 `stereotools=phasel=true:phaser=true:phase=360:mode=lr>lr` or `stereotools=phasel=true:phaser=true:phase=180:mode=lr>rl`

**Comment by richardpl** [comment] 2022-03-14 19:40
g=16 is going to clip no matter what, unless max peak of input audio is not exceeding -0.2/0.2 or audio have no bass to start with, g is gain multiplier, not in dB, if you want to adjust in dB, use g=16dB.

If you are lazy and do not want to do your homework, use `-af equalizer=w=1:t=o:f=55:g=16:r=f64,dynaudnorm=b=1:m=1`

dynaudnorm will act here as very big lookahead limiter, because m=1 will not try to do upward (>1.0) amplification of existing audio, experiment with g= and f= options of dynaudnorm filter, alternatively you could use alimiter filter instead of dynaudnorm.

Unrelated, but was mentioned, fixed angle phase rotation can be done with aphaseshift filter, stereotools phase option is for phase between left and right channels in stereo audio, and does not attempt to fix asymmetrical waves.

If your audio is very low on bass even after all this and you are on linux, use lv2 filter with lv2 plugin bassenhancer from Calf, there is even that one mentioned on ffmpeg documentation page: https://ffmpeg.org/ffmpeg-filters.html#lv2

You will probably need limiter filter after it also.

There is also generic firequalizer filter more sophisticated, but it is more complicated to use.

**Comment by amariami** [comment] 2022-03-15 18:46
based comment from @richardpl 
>There is also generic firequalizer filter more sophisticated, but it is more complicated to use.
```
--af-add=lavfi=[firequalizer=gain='gain_interpolate(f)':delay=0.027:accuracy=0:wfunc=bharris:gain_entry='entry(50,3.0);entry(100,3.0)':scale=linlin]
```

**Comment by oakkitten** [comment] 2022-03-17 13:48
Thanks for all the advice on the alternative equalizers, but adding `volume=-16dB` fixes the clipping for me and the result is exactly what I expected. I guess this is a wise thing to do either way.

I edited the issue to remove the repro step with `-af=folume=...` as this can get fixed using `format=float` after all, this is something that i forgot to check. I'm not entirely sure if this issue is still valid, but on the off chance that the equalizer should not clip horribly on very low master volume levels I won't be closing it myself. This conversation is a bit beyond my understanding anyway 🤯

> Adding precision/r (`:r=auto` or `s16/s32/f32/f64`, `width_type=h`) does it help?

This still clips, as does the `bass` filter: `mpv file.opus  --no-config -af=format=float,equalizer=frequency=55:width_type=h:width=40:g=19:precision=auto -volume=30`

> g=16 is going to clip no matter what, (...), g is gain multiplier, not in dB,

But the [documentation](https://ffmpeg.org/ffmpeg-filters.html#equalizer) says it's in dB, and `g=16` sounds exactly like adding 16dB in fb2k.

> gain, g
> &nbsp;&nbsp;&nbsp;&nbsp;Set the required gain or attenuation in dB. Beware of clipping when using a positive gain.

**Comment by haasn** [comment] 2022-03-17 21:31
[It's not a bug, it's a feature(tm)](https://github.com/mpv-player/mpv/commit/04257417)

**Comment by richardpl** [comment] 2022-03-18 08:44
I do not think that is valid reasoning at all.

**Comment by haasn** [comment] 2022-03-18 11:45
Yeah, I agree, I think we should revert that logic. No idea what other bugs it will re-introduce but those should be fixed properly.

**Comment by ValZapod** [comment] 2022-03-20 21:56
>libswresample doesn't do it - although it should, but the patch is stuck in limbo.

What patch does that refer too? Patchwork does not have history before 2016.

**Comment by berkley4** [comment] 2022-04-02 10:48
Perhaps https://github.com/mpv-player/mpv/issues/4716#issuecomment-321940937 might give a clue on the rationale for wm4's original commit?

**Closed** 2022-06-23 21:52 UTC
