### ISSUE TITLE
Scaling And Scaling Performance Issue with Video Playback using 'gpu-next'

### ISSUE THREAD

**Issue by CrHasher** [mpv-player/mpv#12607] opened 2023-10-09 05:24 UTC
### Important Information

**Information**:
- v0.36.0-502-g78719c14
- Windows 11 Version 10.0.22621 Build 22621
- https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/mpv-x86_64-v3-20231008-git-78719c1.7z/download
- If known which version of mpv introduced the problem: I honestly don't know

**Screenshots**:
![Screenshot 2023-10-09 073253](https://github.com/mpv-player/mpv/assets/834518/9e0ecdcc-d0d6-41fa-9fca-b62f182a7b1e)
![Screenshot 2023-10-09 073326](https://github.com/mpv-player/mpv/assets/834518/f4473f91-521f-4f7f-8475-9d1151253571)
(First 4k trailer I could find :D)

### Reproduction steps
- Start any 4k video with a similar config (notice I've cut it down to bare minimum compared to what I used in the screenshot):
```
vo=gpu-next
dscale=ewa_lanczos
```

- Start resizing the window downward until you notice a pink flash (sometimes its black or a freeze only), notice when you resize window back up RGB scaling is probably off (or my guess would be switched to bilinear) so something broke there. Notice also how `vo=gpu-next` is having a lot of freezes aka. pauses when resizing the window this way while stable `vo` works better and does not show same problem.

### Expected behavior
Same behavior as with stable `vo`.

### Log file
https://0x0.st/H4rB.txt

### Sample files
Any 4k video as far as I can tell.

**Comment by llyyr** [comment] 2023-10-26 06:32
This fails here https://github.com/haasn/libplacebo/blob/master/src/shaders/sampling.c#L783 when resizing a video while it is being downscaled by a polar filter. Doubling the capacity does fix the `[vo/gpu-next/libplacebo] Polar radius 24.292065 exceeds implementation capacity!` error but causes shaders to take 2+ seconds to compile. This is probably an issue elsewhere.

/cc @haasn

**Comment by kasper93** [comment] 2024-03-21 07:26
Recently polar dscale was optimized and the issue should be less noticeable, is this still a problem for you? Could you retest latest version?

**Comment by llyyr** [comment] 2024-03-21 09:03
I can't reproduce this anymore

**Comment by kasper93** [comment] 2024-03-21 11:40
Closing https://github.com/haasn/libplacebo/commit/989a436a26ca6c0fe054918a11dc7c7f7e6deca0 and https://github.com/haasn/libplacebo/commit/1ca94559f86f3af947c97dfd213251080694ff79 the supported radius is bigger, so the issue is not that noticeable.

**Closed by kasper93** 2024-03-21 11:40 UTC
Labels: os:win, vo:gpu-next
