### ISSUE TITLE
Fail to compile on MacOS 10.14

### ISSUE THREAD

**Issue by macdavis** [mpv-player/mpv#6220] opened 2018-10-20 05:31 UTC
### mpv version and platform
MacOS 10.14 (18A391)
mpv git 0f3e25c

### Reproduction steps
compile with `./bootstrap.py && ./waf configure && sudo ./waf build -v`

### Actual behavior
`Build failed
 -> task in 'osdep/macOS_swift.o osdep/macOS_swift.h osdep/macOS_swift.swiftmodule' failed with exit status 1: 
	{task 4407275224: osdep/macOS_swift.o osdep/macOS_swift.h osdep/macOS_swift.swiftmodule macOS_mpv_helper.swift,events_view.swift,video_layer.swift,window.swift,cocoa_cb_common.swift -> macOS_swift.o,macOS_swift.h,macOS_swift.swiftmodule}
''`
### Log file
[https://0x0.st/sElM.txt](https://0x0.st/sElM.txt)

**Comment by Akemi** [comment] 2018-10-20 06:49
as a workaround rename your mpv build folder to something with without a space, eg remove the " 2" at the end. this is probably caused by https://github.com/mpv-player/mpv/commit/4bf9a78b364483f2c4f0ee429510f32f891932bc, because the path is not escaped or quoted.

**Comment by macdavis** [comment] 2018-10-20 07:33
Thanks, this workaround works!

**Comment by Akemi** [comment] 2018-10-20 13:08
should be fixed by #6222.

**Closed** 2018-10-28 13:48 UTC
Labels: osx
