### ISSUE TITLE
Tone mapping clips in HDR passthrough regardless of settings

### ISSUE THREAD

**Issue by NotMithical** [mpv-player/mpv#11339] opened 2023-02-20 18:45 UTC
### Important Information

Provide following Information
- mpv version: 0.35.1
- Windows Version: Windows 10 22H2, Build 19045.2604
- Source of the mpv binary: https://github.com/zhongfly/mpv-winbuild
- If known which version of mpv introduced the problem: Latest from the above source. Likely from one of the commits on this repo between 2955a07 and a903556.
- Possible screenshot or video of visual glitches: ![IMG_20230220_133502](https://user-images.githubusercontent.com/95518825/220179366-3f582a62-e564-499d-b0a5-b6c10a813706.jpg) 
Compared to desired result from an earlier version: ![IMG_20230220_133444](https://user-images.githubusercontent.com/95518825/220179481-698b225f-5bbf-4c3d-9576-abf71ebe4fad.jpg) (both taken with a phone camera with soft focus because screenshotting in HDR is weird)

This change occurred overnight. The previous build from the same source does not have this issue.

### Reproduction steps
1. Install latest nightly release
2. Attempt to load HDR video with HDR passthrough to monitor with --tone-mapping set to something other than clip and --target-peak set appropriately

### Expected behavior
Video is tone mapped and retains highlight detail

### Actual behavior
Highlights are clipped

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/10787100/output.txt)

**Comment by zhongfly** [comment] 2023-02-21 05:56
I think it would be more helpful to provide a more detailed version: `mpv --version`

**Comment by NotMithical** [comment] 2023-02-21 07:17
I was going to, but running that command doesn't yield any output. That may be a separate issue with my system since that happens with a clean installation of an older version of MPV as well.

**Comment by NotMithical** [comment] 2023-02-21 16:28
Thanks. Version is 0.35.0-240-gd1cf89b6

**Comment by haasn** [comment] 2023-02-21 16:44
What is the version of `libplacebo` in use before vs after it broke for you?

**Comment by NotMithical** [comment] 2023-02-21 17:15
Currently using v5.229.1-223-g3dd5092. It broke after v5.229.1-246-g2f48906.

**Comment by haasn** [comment] 2023-02-21 19:12
Does `--hdr-compute-peak=no` fix it?

**Comment by haasn** [comment] 2023-02-21 19:18
Also, on the new version, can you use the option `--tone-mapping-visualize` and take a screenshot of what you get?

**Comment by NotMithical** [comment] 2023-02-21 22:24
> Does `--hdr-compute-peak=no` fix it?

It does not. Looks about the same actually.


> Also, on the new version, can you use the option `--tone-mapping-visualize` and take a screenshot of what you get?

The graph does not appear at all when `--target-trc` is set to any HDR curve (pq, hlg, v-log, or s-log). Only when set to bt.1886, srgb, linear, gamma, or prophoto. Also worth noting, tone mapping appears to work entirely fine when `--target-trc` is set to any of the latter curves, as shown here:
![mpvwatch_v=LXb3EKWsInQ00_00_00 000%](https://user-images.githubusercontent.com/95518825/220472270-fa61b2e5-2d37-452a-a8be-0123a206f00b.jpeg)

**Comment by haasn** [comment] 2023-02-22 08:44
If the graph does not appear, that means tone-mapping is definitely inactive (complete no-op). But then, it should be identical to the status quo from before. I'm confused by what prompted this change.

Is it possible it was caused by a44d91d6acba7d88b93cd675515d004b49158ed9 ?

cc @kasper93

**Comment by kasper93** [comment] 2023-02-22 11:09
> HDR passthrough

Everyone calls it "passthrough", but no one actually wants pass through. And in fact it is expected to tone map first.

 > Is it possible it was caused by a44d91d6acba7d88b93cd675515d004b49158ed9 ?
 
 Yes, this made so swapchain (target) is assumed to properly handle the reported metadata. And well... do some tone mapping...

I made some changes yesterday to how we store swapchain color information: https://code.videolan.org/videolan/libplacebo/-/merge_requests/381 (not the root cause of this issue, but improves situation in other cases)

What we need is to set `nominal_max` to actually say we know the target. Note that with above change, we should no longer override it in `apply_target_options` if it is set. (swapchain will report it properly) Will do proper patch with backward compatibility later.

It now properly tonemaps to selected peak. Of course when `target_peak frame` == `target_peak swapchain` we don't tone map, the infamous pass-through mode.

``` diff
diff --git a/video/out/vo_gpu_next.c b/video/out/vo_gpu_next.c
index 060b17a80b..fbdb9c8e30 100644
--- a/video/out/vo_gpu_next.c
+++ b/video/out/vo_gpu_next.c
@@ -820,7 +820,7 @@ static void apply_target_options(struct priv *p, struct pl_frame *target)
     if (opts->target_trc)
         target->color.transfer = mp_trc_to_pl(opts->target_trc);
     if (opts->target_peak)
-        target->color.hdr.max_luma = opts->target_peak;
+        target->color.nominal_max = target->color.hdr.max_luma = opts->target_peak;
     if (opts->dither_depth > 0) {
         struct pl_bit_encoding *tbits = &target->repr.bits;
         tbits->color_depth += opts->dither_depth - tbits->sample_depth;
@@ -895,6 +895,8 @@ static void draw_frame(struct vo *vo, struct vo_frame *frame)
             hint.primaries = mp_prim_to_pl(opts->target_prim);
         if (opts->target_trc)
             hint.transfer = mp_trc_to_pl(opts->target_trc);
+        if (opts->target_peak)
+            hint.hdr.max_luma = opts->target_peak;
         pl_swapchain_colorspace_hint(p->sw, &hint);
     } else if (!p->target_hint) {
         pl_swapchain_colorspace_hint(p->sw, NULL);
```

**Comment by kasper93** [comment] 2023-02-23 01:41
Will be fixed on mpv and libplacebo side
1. mpv will correctly hint the target peak
2. libplacebo better track metadata when override is enabled to not override the override by accident disabling tone mapping by accident

Sorry for the inconvenience.

**Closed** 2023-02-23 09:14 UTC
Labels: os:win
