### ISSUE TITLE
VDPAU over OPENGL is broken (Radeon OSS)

### ISSUE THREAD

**Issue by rphl321** [mpv-player/mpv#3714] opened 2016-10-23 14:52 UTC
### mpv version and platform

Gentoo 
mpv 0.21.0
kernel 4.5.0 and 4.8.3 tested
DE: Plasma 5.8.2 and Xfce4 4.12
Mesa 13.0.0-rc1
Videocard Radeon HD5850 OSS driver r600
### Reproduction steps

Enable hwdec=auto in mpv config file and launch some h264 8bit video
### Expected behavior

Expecting to see moving pictures.
### Actual behavior

Texture mess or black screen with subtitles rendered over it.
### Log file

MPV log:
" (+) Video --vid=1 (_) (h264)
 (+) Audio --aid=1 (_) (aac)
 (+) Subs  --sid=1 --slang=eng (*) 'English' (ass)
AO: [pulse] 44100Hz stereo 2ch float
Using hardware decoding (vdpau).
VO: [opengl] 1280x720 vdpau
radeon: The kernel rejected CS, see dmesg for more information (-22)."  <<---- and lots of these

Dmesg log:
"[50362.568807] radeon 0000:01:00.0: evergreen_cs_track_validate_texture:854 texture bo too small (layer size 122880, offset 614400, max layer 2, depth 1, bo size 737280) (512 120)
[50362.568833] [drm:radeon_cs_ioctl [radeon]] _ERROR_ Invalid command stream !"

Setting up mpv to use vdpau (--vo=vdpau) does not produce this! It works fine with vdpau.

Mpv 0.9.2 is not affected by this bug.
### Sample files

I am sure you have plenty h264 8bit videos! :)

**Comment by Jj0YzL5nvJ** [comment] 2016-10-24 04:27
I have exactly the same symptoms since September. I do not remember the exact date, but it all started with an update of Mesa.
 Not report it because I knew that it was caused by an update of mesa-vdpau-drivers, but since then it has updated many times and still does not work properly.

 I'm using Xubuntu 16.04.1 LTS and:
> GL_RENDERER   = Gallium 0.4 on AMD JUNIPER (DRM 2.43.0 / 4.4.0-45-generic, LLVM 4.0.0)
> GL_VERSION    = 3.0 Mesa 13.1.0-devel - padoka PPA
> GL_VENDOR     = X.Org

I use my own scripts when I want to use VDPAU, so it's not a big deal.

**Comment by rphl321** [comment] 2016-10-29 08:38
Not everyone is a script guru. Mesa-git doesn't help. Is this bug Mesa's fault? Or who's? Does it work okay with proprietary drivers? I wish this can be unbroken...

**Comment by Jj0YzL5nvJ** [comment] 2016-10-29 12:25
I'm not. But maybe I can help a little with that.

**Examples:**
mpv.conf
```
# Write your default config options here!

# vo=vdpau
vo=opengl
# vo=xv
# ao=alsa
ao=pulse
# hwdec=vaapi
# hwdec=vdpau
# hwdec=auto
hwdec=no
# profile=opengl-hq,pseudo-gui
profile=opengl-hq
screenshot-format=png
screenshot-png-compression=9
```

VDPAU script for local files
```
#!/bin/bash
mpv --autofit=33% --vo=vdpau --hwdec=vdpau "$@"
```

Default script for ytdl stream
```
#!/bin/bash
mpv --autofit=33% --no-border --ytdl=yes --ytdl-format=best "$@"
```

VDPAU script for ytdl stream
```
#!/bin/bash
mpv --autofit=33% --no-border --ytdl=yes --ytdl-format=best --vo=vdpau --hwdec=vdpau --user-agent="Mozilla/5.0 (Windows NT 6.3; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0" "$@"
```

 You can save your scripts with the name and path you want. Just apply a _chmod +x_ to run them in a terminal and appends the path to your PATH. For that, edit the file .bashrc and add something like this to the end:

> PATH=$PATH:$HOME/.local/share/cmpv

In your case replaces "$HOME/.local/share/cmpv" with your own script folder.
I don't know if in Gentoo this is same.

**Comment by jmcamp** [comment] 2016-10-31 17:41
I posted this to the [mesa bug tracker](https://bugs.freedesktop.org/show_bug.cgi?id=98512).

Christian König from AMD replied.  He thinks it's likely an issue with mesa, and is looking for someone to bisect.  I'm a newbie at this, so I'm hoping someone here can lend a hand.  If you can bisect, please let Christian know (and us too, by replying here and on the mesa bug tracker).

**Comment by wm4** [comment] 2016-10-31 17:52
Maybe @grigorig can help, not sure.

**Comment by jmcamp** [comment] 2016-11-01 02:10
Update:  I followed the Arch Linux wiki on how to git bisect mesa, and I think I found the offending mesa commit.  I posted this on information on the [mesa bug tracker](https://bugs.freedesktop.org/show_bug.cgi?id=98512#c3), so hopefully now the mesa devs can take it from here.

**Comment by Jj0YzL5nvJ** [comment] 2016-11-10 07:32
This is fixed with the current version of mesa.

**Closed** 2016-11-10 07:53 UTC
Labels: not our bug

**Comment by grigorig** [comment] 2016-11-10 13:17
It doesn't look like this is fixed. It depends on a pending change in LLVM:

https://reviews.llvm.org/D26348

Maybe it works again by sheer luck, but the underlying issue hasn't been solved properly yet!
