### ISSUE TITLE
hi444p10 h264 content does not decode properly 

### ISSUE THREAD

**Issue by LaserEyess** [mpv-player/mpv#4807] opened 2017-08-26 12:58 UTC
### mpv version and platform
OS: Linux 64-bit

mpv: 
```
 mpv --version
mpv 0.26.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Thu Jul 20 13:13:36 CEST 2017
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.3
```

ffmpeg: 
```
ffmpeg -V
ffmpeg version 3.3.3 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.1.1 (GCC) 20170630
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxvid --enable-shared --enable-version3
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
```
### Reproduction steps

For me the error is when this one particular format (hi444p10) is resumed on playback, it gives garbage decoding no matter the settings. Starting the file from the beginning gives no error. No seeking problems or decoding artifacts at all. Only when resuming from a non 0 start position. 

As I was making a test file to upload, I discovered that this test file, not starting at the beginning (because I can't figure out ffmpeg cutting), was doing the exact same thing. So my issue can be completely recreated with:

`mpv --no-config test.mkv`

other things that recreate it: 

`mpv --no-config --start=(some non 0 time) hi444p10.mkv`

### Expected behavior

normal decoding and playback

### Actual behavior

![](https://0x0.st/5A5.png)

### Log file

https://0x0.st/5ms.txt

### Sample files

https://0x0.st/5mz.mkv

this is the same 'test.mkv' I used above. I can provide the full file if needed, it was just too large to host so I'll have to host it myself.

**Comment by wiiaboo** [comment] 2017-08-26 13:03
Broken file. Whoever encoded it removed needed information from x264.

**Comment by wiiaboo** [comment] 2017-08-26 13:03
Also, duplicate of https://github.com/mpv-player/mpv/issues/4559.

**Closed by wiiaboo** 2017-08-26 13:03 UTC
Labels: invalid (broken file/hardware/drivers/etc)

**Comment by LaserEyess** [comment] 2017-08-26 13:15
I don't think SEI was stripped from this file, here's the settings from the original file: 

```
Writing library                          : x264 core 148 r2705kMod 3f5ed56
Encoding settings                        : cabac=1 / ref=16 / deblock=1:-1:0 / analyse=0x3:0x133 / me=tesa / subme=10 / psy=1 / fade_compensate=0.80 / psy_rd=0.80:0.00 / mixed_ref=1 / me_range=32 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=4 / threads=12 / lookahead_threads=3 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / fgo=0 / bframes=16 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=crf / mbtree=1 / crf=14.0000 / qcomp=0.65 / qpmin=0 / qpmax=81 / qpstep=4 / ip_ratio=1.40 / aq=3:0.80
```

Unless I'm misunderstanding what the other issue is I don't see how this is a duplicate. Though I would believe that the file is still broken.

**Comment by wiiaboo** [comment] 2017-08-26 13:27
It is missing from the sample at least. And if it's core 148 it means it's the old version of x264 that produced broken 4:4:4 files. If it's missing from the SEI ffmpeg can't fallback to the old behavior which tried to decode it correctly.

**Comment by LaserEyess** [comment] 2017-08-26 13:39
I didn't notice it was missing from the sample until afterwards, but yeah it is. But is there any particular reason why it should work from start but not on resume? Or is that just part of the file being made with a bad x264 version.

**Comment by wm4** [comment] 2017-08-26 13:43
It's possible that the required information (x264 version identifier) is only in the first packet, so resuming (or just using `--ss=60` in the command line) will result in broken decoding.

I have no interest in adding some shitty hack to work this around.

**Comment by LaserEyess** [comment] 2017-08-26 13:47
That's fine, just trying to understand this issue. If it's because their x264 is outdated that explains enough for me.

**Comment by haasn** [comment] 2017-08-26 15:53
Btw, as a rule of thumb, you should test these issues with `ffplay` first. If `ffplay` results in the same corruption (in this case: it does), then it's not an mpv bug report.

**Comment by wm4** [comment] 2017-08-26 16:52
If ffplay fails, it's generally a hint that the bug is in FFmpeg, but if ffplay succeeds, it doesn't necessarily mean there's a bug in mpv. Most important, ffplay always goes through libavformat, while mpv doesn't necessarily.

**Comment by wm4** [comment] 2017-12-31 15:21
There's a workaround for the playback resume failure with those files. All other cases can be handled with `--vd-lavc-assume-old-x264`.
