### ISSUE TITLE
Gibberish Closed Captioning subtitle

### ISSUE THREAD

**Issue by macdavis** [mpv-player/mpv#4493] opened 2017-06-08 11:29 UTC
### mpv version and platform
MacOS 10.12.5 (16F73)
MPV git bd603c2

### Reproduction steps
Play "wwdc_2017_1080_cc.m4v" with `-no-config`
### Expected behavior
Correct CC subtitle
### Actual behavior
Subtitle is garbled. The subtitle position is also inappropriate.
<img src="https://ws1.sinaimg.cn/large/8d5749ccgy1fge0fmvey4j21hc0m8q4f.jpg"/>
<img src="https://ws1.sinaimg.cn/large/8d5749ccgy1fge0m8ic8tj21hc0m83zv.jpg"/>
### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us/RAJM

### Sample files
http://podcasts.apple.com/apple_keynotes_1080p/2017/wwdc_2017_1080_cc.m4v

**Comment by wiiaboo** [comment] 2017-06-08 12:07
Could you submit this to http://trac.ffmpeg.org/? FFmpeg also fails to decode anything useful from it.

**Comment by macdavis** [comment] 2017-06-08 12:35
Already filed a report to FFmpeg, thanks for your reply, wiiaboo!

**Comment by wiiaboo** [comment] 2017-06-08 14:34
You should follow the instructions of their tracker though. Just run `ffmpeg -i http://podcasts.apple.com/apple_keynotes_1080p/2017/wwdc_2017_1080_cc.m4v -vn -an out.srt` and paste the output of it in the ticket, or else it'll probably be closed by the tracker maintainer.

**Comment by macdavis** [comment] 2017-06-08 15:15
Thanks wiiaboo. I have appended the output to the ticket.

**Comment by nuomi1** [comment] 2017-07-20 15:55
@macdavis @wiiaboo 

`ffmpeg -i in.mp4 -an -vn out.srt` failure
`ccextractor in.mp4 -o out.srt` success

[out.zip](https://github.com/mpv-player/mpv/files/1162896/out.zip)

**Comment by wiiaboo** [comment] 2017-08-16 10:14
For reference, the [FFmpeg trac bug](http://trac.ffmpeg.org/ticket/6448).

**Comment by MaddTheSane** [comment] 2019-08-05 22:21
FFmpeg bug 6448 has been marked as a duplicate of [bug 4616](http://trac.ffmpeg.org/ticket/4616).

**Closed** 2019-09-21 11:00 UTC
Labels: ffmpeg-bug
