### ISSUE TITLE
Flatpak/appimage/Snap etc.

### ISSUE THREAD

**Issue by Hasshu** [mpv-player/mpv#6933] opened 2019-09-12 10:45 UTC
https://flatpak.org/

I wonder if it would be more feasible than the AppImage format (#4056).

**Comment by wiiaboo** [comment] 2019-09-13 22:11
See https://github.com/mpv-player/mpv/issues/4056

**Comment by Khyber3737** [comment] 2019-09-15 02:49
https://github.com/flathub/flathub/pull/1057

**Comment by Hasshu** [comment] 2019-09-15 10:01
@Khyber3737 One of the main points of Flatpak, in my opinion, is the possibility to get installable software directly from the developer. I do not — and should not — trust some third-party "Flathub maintainers", hence this here issue.

Or were you referring to #2987?

**Comment by wm4** [comment] 2019-09-18 18:20
Like with AppImage, I don't think we want to maintain such a package. It requires time and care, and we'd have to handle all the bug reports too. Either someone of "us" needs to step in (but nobody seems to be interested in picking up such a task), or someone external has to do it.

In addition, it seems all the GPU API usage (especially hwdec) makes this tricky.

**Comment by wm4** [comment] 2019-09-28 11:16
This issue is hereby about all "distro-independent" packaging methods for Linux, since this comes up every so often.

**Comment by eszlari** [comment] 2019-12-06 06:52
I would like to help you with the flatpak. After the build manifest is written and tested, the ongoing maintenance burden should be low: in the most simple case, it means just updating the URL and SHA256 of the tarball for a new release through the Github UI.

Flathub uses buildbot (https://flathub.org/builds). Builds get triggered automatically when committing to master or when opening PRs. Preview release/beta builds are also supported.

So if you are interested, I can write the manifest and submit a PR to Flathub. Then mpv developers would get commit access to the repo with mpv's manifest.

Just to two things need to be decided:
1. What shoud be the app ID (reverse DNS)? `io.mpv.mpv`?
2. manifest format: JSON or YAML?

**Comment by wm4** [comment] 2019-12-06 18:31
Well, nice.

If the thing gets built in a transparent and public way, all the better I guess.

I hope this doesn't require any metadata or similar in the mpv repo itself?

> What should be the app ID (reverse DNS)? io.mpv.mpv?

Well, we currently own the domain (or rather one of the developers does), so I guess that's OK.

**Comment by Akemi** [comment] 2019-12-06 18:37
https://github.com/mpv-player/mpv/blob/master/TOOLS/osxbundle/mpv.app/Contents/Info.plist#L179-L180
**io.mpv** is what the mpv macOS bundle uses.

**Comment by eszlari** [comment] 2019-12-06 19:18
> I hope this doesn't require any metadata or similar in the mpv repo itself?

The single (small) metadata file, that is needed, could be put in either repo. But since it's not specific to flatpak, it would make more sense (and preferred by Flathub) to be put in the upstream repo. Software managers like GNOME Software or KDE Discover use it to display infos about an app, no matter if they are packaged as flatpak or traditional Linux packages formats.

> io.mpv is what the mpv macOS bundle uses.

It needs to have 3 elements, e.g.
io.mpv.mpv
io.mpv.MPV
io.mpv.Player
etc.

**Comment by PranavBhattarai** [comment] 2021-04-24 16:25
Any 2021 approach toward this!?

**Comment by jeeb** [comment] 2021-04-24 16:45
I tried to build a snap of mpv some time ago (https://github.com/jeeb/mpv/commits/le_snap) but the result was sub-optimal.

1. The graphics drivers.
2. pulseaudio worked for my laptop, but not for another person.

**Comment by philipl** [comment] 2021-04-24 17:00
AppImage would probably be the easiest as that doesn't involve any sandboxing.

**Comment by PranavBhattarai** [comment] 2021-04-25 04:24
Ubuntu 21.04 which was released 2 days ago still has the old 0.32.0 version.
MPV was not updated in the APT repo. So I was thinking maybe I should try other package management systems like Snap & Flatpak which are more popular. But sadly, Snap has an unofficial older build and Flaptak doesn't have MPV at all. PPA is barely maintained. 

It's too hard to get updated MPV these days unless you compile it yourself, which is kind of a bummer for the normal user to go through. I wish things were a bit easier.

**Comment by CounterPillow** [comment] 2021-04-25 06:17
> It's too hard to get updated MPV these days

My somewhat unhelpful suggestion is to use a better distro. mpv 0.33 was released in November. Someone [even told the debian-multimedia maintainers to package it](https://lists.debian.org/debian-multimedia/2021/02/msg00103.html), but they did not do so.

**Comment by Hasshu** [comment] 2021-04-25 15:07
> My somewhat unhelpful suggestion is to use a better distro. mpv 0.33 was released in November. Someone even told the debian-multimedia maintainers to package it, but they did not do so.

This issue was opened exactly in hopes of cutting out the middleman.

**Comment by danrobi11** [comment] 2021-04-25 21:55
About a binary release like youtube-dl does ? Users just need to chmod it like an appimage.

Otherwise why not a deb file then ?

**Comment by fastrizwaan** [comment] 2021-04-30 02:08
https://github.com/fastrizwaan/mpv_flatpak

**Comment by fastrizwaan** [comment] 2021-05-05 04:27
Congrats! MPV is now available at flathub https://flathub.org/apps/details/io.mpv.Mpv

**Comment by Hasshu** [comment] 2021-05-07 20:54
@fastrizwaan It's cool and all, but I'd rather wait for an official release.

**Comment by danrobi11** [comment] 2021-05-07 23:40
@Hasshu 
What do you mean by "official release" ? 
MPV is now availabe on [flathub](https://flathub.org/apps/details/io.mpv.Mpv)
You aint going to get more "official" than that tbh.
Dont expect MPV lead dev to maintain the flatpak.
More than half of the flatpaks are maintained by the community.
Same for [AppImages](https://appimage.github.io/apps/).

**Comment by garoto** [comment] 2021-05-08 14:42
So if fastrizwaan was to be made a member of the "mpv-player virtual organization", which is only a thing on this website alone, would that make it _official_ enough for you? I just don't get it.

**Comment by Akemi** [comment] 2021-05-08 15:35
we don't and won't provide 'official' binaries, pre-build packages, etc.. if anything changes on that stance, we will let you know.

**Comment by Hasshu** [comment] 2021-05-08 16:09
@garoto Is he a known contributor to the project? To me, it seems that he's just a random passerby (no offense).

> we don't and won't provide 'official' binaries, pre-build packages, etc.. if anything changes on that stance, we will let you know.

@Akemi I see. But what is the reasoning behind this stance? Perhaps, there is a relevant discussion I missed?

**Comment by Hasshu** [comment] 2021-05-08 18:53
@Akemi I see, thanks for the explanation.

**Comment by fastrizwaan** [comment] 2021-05-08 23:59
> Exactly that — a release done by the mpv developers themselves, and not some third party.

Why? The sources are **neither** patched **nor** modified, they can be verified by sha256sum, see yaml file https://github.com/flathub/io.mpv.Mpv/blob/master/io.mpv.Mpv.yml

**Comment by fastrizwaan** [comment] 2021-05-09 00:06
> You probably have been using Linux for a long enough time to get used to this asinine notion of random people packaging someone else's software, but no matter how you look at it, it's a bug — not a feature. Blame the package-format fragmentation and the NIH syndrome that led to it.

That's a weirdly beautiful thought. So, does Linus towards provide you kernel binary? Does Richard Stallman provide you core-utils binaries? BTW, which distro do you use? All Distros are created by Random guys who packages someone else's sources.

**Comment by fastrizwaan** [comment] 2021-05-09 00:16
> > Same for AppImages.
> 
> First-party AppImages are a thing, though.

First-party Appimages also include third-party binaries. Now, what will happen to your circle of trust? you want A to provide a, and B to provide b, but C want to provide a+b, then you have a problem. Whereas B providing a+b is also wrong as per your thinking. (A/B/C = devs ; a/b/c = software of A/B/C)

**Comment by Akemi** [comment] 2021-05-09 00:34
next time please just reply in one comment. also this is kinda off topic. so can we please stop discussion this, since it's off the table anyway..

**Comment by Hasshu** [comment] 2021-05-09 10:41
> next time please just reply in one comment.

Sorry, you mean without using a mention? Or that I didn't have to respond?

> also this is kinda off topic. so can we please stop discussion this, since it's off the table anyway.

Sure thing.

**Comment by Akemi** [comment] 2021-05-09 14:44
i meant merging those three comments into one, not one comment for each quote but one comment for all three.

**Comment by garoto** [comment] 2021-05-09 21:36
fastrizwaan did a couple comments, but I guess he deteted those. I assumed akemi was refering to those two comments.

**Comment by nathanfranke** [comment] 2021-05-16 09:25
Surprised this isn't closed and locked

**Comment by Akemi** [comment] 2021-05-16 10:42
i would say, close it if and when we put a link on our page. though the if and when is nothing i want to decide on my own.

**Comment by Hasshu** [comment] 2021-05-16 15:40
Did I miss something?

**Comment by Pentaphon** [comment] 2021-12-16 01:14
If flathub is looked down upon and distro repos are considered too out of date, what is the best way to install mpv on a Linux distro?

**Comment by nathanfranke** [comment] 2021-12-16 01:17
> If flathub is looked down upon and distro repos are considered too out of date, what is the best way to install mpv on a Linux distro? 

I guess PPAs on Ubuntu and the official arch repositories (updated often)

**Comment by Pentaphon** [comment] 2021-12-16 01:44
> I guess PPAs on Ubuntu and the official arch repositories (updated often)

But PPAs are basically looked down upon as well because of how often they break things and not everybody runs Arch. 

Flatpak seems like a good solution unless there is actually something better and always up to date.

**Comment by nathanfranke** [comment] 2021-12-16 01:46
> But PPAs are basically looked down upon as well because of how often they break things and not everybody runs Arch. 
> 
> Flatpak seems like a good solution unless there is actually something better and always up to date. 

Agree that Flatpak would be a great cross-platform solution

**Comment by MintMain21** [comment] 2022-01-13 23:47
I'm using the MPV Flatpak on Linux Mint 20.3, and while a few plugins I use have compatibility issues (mpv-bookmarker) it otherwise works as intended. That being said, I generally prefer Appimages as they use (in my experience) less space compared to Flatpaks, and can easily be integrated into the system. 

Seeing as it took a 3rd party to make the Flatpak a reality, I'll just say right here that there is an audience for a Appimage as well.

**Comment by Pentaphon** [comment] 2022-01-14 02:22
> I generally prefer Appimages as they use (in my experience) less space compared to Flatpaks, and can easily be integrated into the system.

It's a video player. It doesn't take that much space. It was hard enough to get somebody to work on a Flatpak. Don't hold your breath on an appimage, especially considering how well the flatpak is working. I don't see much of  a future for appimage anyway. It seems more and more like appimage is on its way out and flatpak and snap are here to stay.

**Comment by Hasshu** [comment] 2022-01-14 10:10
@MintMain21 See #4056.

**Comment by ssokolow** [comment] 2022-03-04 07:56
Quick question. Should I open another feature request specifically to ask that the unofficial Flathub release be added to the "All of these packages are unofficial." Linux section of https://mpv.io/installation/?

Also...

> That being said, I generally prefer Appimages as they use (in my experience) less space compared to Flatpaks

Appimages don't support deduplicating dependencies, while Flatpak aggressively deduplicates dependencies. While Flatpak may take more space for a single application, the cost is spread across all the applications you install.

(Part of the purpose of the Flatpak Runtimes, having the GNOME and KDE runtimes build on top of the Freedesktop Runtime, and having the BaseApp system of pre-built starters for what you *do* bundle is to ensure that as many of your dependencies as possible have identical file hashes, so the file-level deduplication can have maximum effect.)

Also, Appimages suffer from the same "Which dependencies should be bundled?" problem as GOG.com, but make it more difficult to delete "shouldn't have been bundled" `.so` files when a distro update introduces a segfault-on-startup bug.

**Comment by Pentaphon** [comment] 2022-03-04 10:20
> Quick question. Should I open another feature request specifically to ask that the unofficial Flathub release be added to the "All of these packages are unofficial." Linux section of https://mpv.io/installation/?

You should post it on the issues page for the website here: https://github.com/mpv-player/mpv.io/issues

**Comment by ssokolow** [comment] 2022-03-04 17:46
Thanks. Will do. :)

**Comment by Pentaphon** [comment] 2022-04-09 17:23
> anyway it has various reasons and everyone has different concerns. though at one point we might provide official builds, maybe through our CI.

@Akemi Is there anything that you and @fastrizwaan can do to make his Flathub builds official to the project? I think doing so would go a long way in building confidence in the Flathub builds, giving mpv users more install options and making sure that both the official releases and Flathub are totally in sync. Flatpak is being used more and more every year and embracing it sooner rather than later will only benefit the project in the long run.

**Comment by applecuckoo** [comment] 2023-04-11 09:28
Don't know if this conversation is still active, but another reason that Flatpak is a good idea is that Flatpak has a mechanism for plugins, here's an example with OBS Studio's official flatpak displaying in Mint's Software Manager.
![Software Manager_001](https://user-images.githubusercontent.com/113647417/231117325-d6259205-9237-40cb-a207-4a136f62066a.png)

**Comment by MintMain21** [comment] 2023-04-11 09:37
Distributing MPV Plugins as a Flatpack is an attractive option, so long as there remains an easy and accessible way to edit the Plugins either as if (or better than if) they were lua.scripts downloaded on the user's end.

**Comment by ssokolow** [comment] 2023-04-11 12:05
> Distributing MPV Plugins as a Flatpack is an attractive option, so long as there remains an easy and accessible way to edit the Plugins either as if (or better than if) they were lua.scripts downloaded on the user's end.

For all the other benefits, on that particular note, unfortunately, Flatpak is designed around the assumption that users will **not** be editing the contents of Flatpak packages but, instead, will either uninstall/disable them and install a plugin under `$HOME` or will use some application-provided overlay mechanism if they need patched versions.

That's why I don't install LibreOffice via Flatpak. Because the [only way I'm aware of](https://www.remembertheusers.com/2019/11/0580-libreoffice-nag-notices.html) to disable the periodic "Donate" and "Get Involved" nag-bars is to drop a file into `$BASEDIR/share/registry`, which is part of `/app` and, thus, not to be modified under Flatpak. (Whereas, with the distro packages, it's just a `sudo` away and won't get removed on update.)

**Comment by Hasshu** [comment] 2023-05-07 17:50
Apologies for the ranty bump, but this is getting frustrating...

mpv's official site [complains](https://mpv.io/installation/) that "distributions usually package outdated, unmaintained, and unsupported versions of mpv". Now, the distro I use (Fedora Linux) does provide an up-to-date version of mpv, but a full-featured version of FFmpeg has to be downloaded from RPM Fusion, a third-party repo. I strive to never have to deal with third parties (and RPM Fusion in particular) when it comes to software, so using their packages is not an option for me. Thus I tried to use some of the static FFmpeg builds [mentioned](https://www.ffmpeg.org/download.html) on the official site. I made sure that the bundled `ffmpeg` is the first thing under `whereis`, but it wouldn't to work for some reason: `Failed to initialize a decoder for codec 'hevc'.`

mpv's official site also hints at building everything yourself instead. I did try to compile FFmpeg once... By now I don't recall the details, but that littered my system with lots of unneeded packages, took many retries, and didn't even work in the end. Frankly, I don't want to deal with that ever again. And something tells me that *few would even bother to try*. They would rather use those "outdated, unmaintained, and unsupported versions of mpv", and then go on the bug tracker to complain.

But all of the above wouldn't be an issue, if there were an official way to get the most recent version of mpv, no matter the distro... Y'know, one build to rule them all. Oh, and the "official" part is as important as ever, since Flathub has introduced support for [verified apps](https://docs.flathub.org/docs/for-app-authors/verification) recently. Please, give it some thought.

Also, here's an inspirational example of how developers were hesitant about Flatpak at first, but ended up embracing it: https://github.com/keepassxreboot/keepassxc/issues/1524

**Comment by fastrizwaan** [comment] 2023-05-07 18:32
@Hasshu Does Linus Torvalds release an official binary Linux kernel package for you to install? It's Free OSS.

What is a Linux Distribution? 
A collection of compiled binaries from various sources which includes gnu tools and Linux kernel and other open source software. So, in this sense, whichever distro you are using, you are basically using unofficial packages bundled by third parties.

**Comment by ssokolow** [comment] 2023-05-07 18:41
@fastrizwaan

The Linux kernel is a massive anomaly, in that it's pretty much the only kernel developed independently from its userland. (Which is also why it's the only kernel of note with ABI-stable syscall numbers.)

FreeBSD, OpenBSD, NetBSD, DragonflyBSD, and every other major open-source project which produces an OS kernel does offer official builds.

> What is a Linux Distribution?
>
> A collection of compiled binaries from various sources which includes gnu tools and Linux kernel and other open source software. So, in this sense, whichever distro you are using, you are basically using unofficial packages bundled by third parties.

And Flatpak is designed to make it easy and comfortable for upstreams to offer a single official build while only having to test it against one target: the Flatpak runtime they specify in their build manifest.

To that end, not only does it take a Docker-like containerized approach, Flathub runs a [bot](https://github.com/flathub/flatpak-external-data-checker) that you can configure so that you just do your normal build process and the Flathub infrastructure will detect that you've made a release (or that one of your dependencies has done so), generate a test build (including running any automated tests you specify as part of the build process), and all you have to do (aside from any release testing you have yet to automate) is accept the PR the bot opens and, after a three-hour grace period to allow for realizing you've made mistakes, the new Flathub release goes live.

**Comment by Hasshu** [comment] 2023-05-07 19:44
@fastrizwaan While it makes sense for the Linux kernel (and certain [system software](https://en.wikipedia.org/wiki/System_software)) to be packaged by the distribution maintainers, there is no need to treat [application software](https://en.wikipedia.org/wiki/Application_software) the same way in this day and age. We have the technology.

**Comment by Dudemanguy** [comment] 2023-08-09 16:42
I think it's pretty obvious that none of us are going to maintain an official flatpak/appimage/whatever at this point. I know there's already an existing flatpak someone maintains, so if the author wants us to list it on the website feel free to open up a PR at mpv.io

**Closed by Dudemanguy** 2023-08-09 16:42 UTC
Labels: meta:feature-request, meta:rfc, priority:wontfix, meta:help-wanted

**Comment by fastrizwaan** [comment] 2023-08-10 10:51
@Dudemanguy 

Could you please look into this, https://github.com/mpv-player/mpv.io/pull/103 it fails.

I just added haml code
```haml
= package_row 'Flatpak (Flathub)', 'https://flathub.org/apps/io.mpv.Mpv'
```

https://github.com/fastrizwaan/mpv.io/commit/7df1aa5d9ec68219c7dd2bc3008a31a23ac8cbae

Thanks.

**Comment by AsciiWolf** [comment] 2024-06-18 15:38
Any update? Linux Mint [will hide](https://www.omgubuntu.co.uk/2024/06/linux-mint-will-hide-unverified-flatpaks) unverified Flatpak apps from search results (and other distributions will probably follow).

**Comment by PerAstraAdDeum** [comment] 2025-01-19 16:58
I'd really appreciate a Flatpak verification. I hope someday devs and maintainers can agree to this. :-)

**Comment by Hasshu** [comment] 2025-01-19 19:35
> I'd really appreciate a Flatpak verification. I hope someday devs and maintainers can agree to this. :-)

You people are missing the very point of verification.
