### ISSUE TITLE
Video playback artifacts in mpv on intel with 6.4.10 and newer kernels

### ISSUE THREAD

**Issue by tm4ig** [mpv-player/mpv#12257] opened 2023-08-26 14:03 UTC
### Important Information

- mpv version: 0.36.0
- Linux Distribution and Version: archlinux with 6.4.[10-12] kernel
- Source of the mpv binary: https://geo.mirror.pkgbuild.com/extra/os/x86_64/mpv-1:0.36.0-1-x86_64.pkg.tar.zst
- If known which version of mpv introduced the problem: I do not know, I am not sure that the bug is in mpv
- Window Manager and version: KDE plasma 5.27.7 with Wayland 1.22 session
- GPU driver and version: i915 kernel driver + mesa 23.1.6 + intel-media-driver 23.3.1
- Hardware: MSI Modern 15 B12M laptop with Intel i7-1255U CPU and Intel Alder Lake-UP3 GT2 (Iris Xe Graphics) GPU

### Reproduction steps
0) Use mpv with intel gpu, vaapi hardware decoder on KDE with wayland session,
base mpv config:
```
vo=gpu
hwdec=vaapi
gpu-api=opengl
gpu-context=wayland

ao=pulse
af=dynaudnorm=p=0.95
```
1) Upgrade linux kernel to 6.4.10 and newer kernel
2) Run any video with very hight resolution (for example 4k) and/or very hight quality (for example with gpu-hq profile and ewa_lanczossharp scale method)

### Expected behavior
Video must to play without visual artifacts

### Actual behavior
Video plays with visual artifacts: green vertical lines, squares and other
Also sometimes I have one CPU core 100% utilization

### Log file, screenshot and sample video for 4k resolution and default profile case
[example_4k.txt](https://github.com/mpv-player/mpv/files/12445467/example_4k.txt)
![example_4k](https://github.com/mpv-player/mpv/assets/28867534/8e14e164-3b2d-45b9-855b-ccc37a91597a)
https://youtu.be/LXb3EKWsInQ

### Log file, screenshot and sample video for 2k resolution and gpu-hq profile with ewa_lanczossharp scale case
[example_2k.txt](https://github.com/mpv-player/mpv/files/12445476/example_2k.txt)
![example_2k](https://github.com/mpv-player/mpv/assets/28867534/07796faf-1af9-4804-8529-9561bea5631e)
https://youtu.be/msN1o5j0yoE

### Additional Information
I have created same bug https://gitlab.freedesktop.org/drm/intel/-/issues/9118#note_2051613

**Comment by sfan5** [comment] 2023-08-26 14:04
duplicate of #12204

**Closed by sfan5** 2023-08-26 14:04 UTC
Labels: os:linux
