### ISSUE TITLE
It's possible to drag the borderless fullscreen window

### ISSUE THREAD

**Issue by UserNaem** [mpv-player/mpv#4751] opened 2017-08-11 17:38 UTC
### mpv version and platform
0.26.0, Windows 7 SP1
### Reproduction steps
Run mpv.
Press left mouse button, release it, then press and hold it. (mpv should recognize this as a double-click and go to fullscreen mode)
Move the mouse cursor.
### Expected behavior
The window shouldn't move, as it's in fullscreen mode.
### Actual behavior
The window moves.

**Comment by lachs0r** [comment] 2017-08-11 17:45
Duplicate of #1921.

**Closed by lachs0r** 2017-08-11 17:45 UTC
