### ISSUE TITLE
[MKV TAG] Crop Parameter Support

### ISSUE THREAD

**Issue by vslmc** [mpv-player/mpv#6017] opened 2018-07-25 21:20 UTC
mpv-x86_64-20180721-git-08a6827

https://i.imgur.com/N4ZZ6Q3.png

Problem explained by another user for Kodi: https://forum.kodi.tv/showthread.php?tid=254218&pid=2199514#pid2199514

**Comment by lachs0r** [comment] 2018-07-25 21:44
Duplicate of #79, but let’s revisit this issue.

**Comment by wingedonezero** [comment] 2018-07-27 06:45
I think this should be implemented to. I remux a lot of my movies with makemkv and i like to retain the quality but don't like black bars like many others. Now i know the counter argument is just encode the bars out but any form of encoding always creates quality loss. And also takes a lot longer to do than to just use mkvtoolnix to add crop parameters. I experimented with this before using mediaplayer classic and vlc i believe were the players i tested and it worked with both. Now what would be ideal is a auto crop feature that detects what it needs to crop when fullscreen which would remove the need for this feature. Similar to how handbrake detects the bars. But idk which would be easier to do. I think there was a script i tried before for mpv that attempted to do the latter but it wouldn't take when going full screen.

**Comment by sbruder** [comment] 2019-08-04 23:48
I wrote a script for this: https://github.com/sbruder/mpv-matroska-crop

It still suffers from the problems discussed in #79 (notably no support for hardware decoding), but it can be configured to disable hardware decoding when the Matroska file includes PixelCrop properties.
It also depends on mkvmerge (mkvtoolnix) to get the PixelCrop properties (meaning it only works for local files).

**Comment by wm4** [comment] 2019-10-25 11:35
Could be supported, but to be honest I never saw a file in the wild that uses it.

**Comment by Akemi** [comment] 2019-10-25 17:14
some years ago i had a few files like that. manly some direct rips of BD movies with a wider than 16:9 aspect ratio (black bars at bottom and top) and a few 4:3 BD rips (left and right black bars). those files had those crop tags set, but kinda useless when viewed on 16:9 TVs anyway.

**Comment by nvllsvm** [comment] 2019-10-25 19:15
This is especially useful for the minority of us who have a 21:9 display. Especially considering a number of movies are of the same, but with hardcoded black padding.

**Comment by qmega** [comment] 2019-10-26 01:30
> This is especially useful for the minority of us who have a 21:9 display. Especially considering a number of movies are of the same, but with hardcoded black padding.

Side note: For times like these a keybind for `no-osd cycle_values panscan 1 0` comes in really handy.

**Comment by Witchilich** [comment] 2023-03-27 21:15
> I wrote a script for this: https://github.com/sbruder/mpv-matroska-crop
> 
> It still suffers from the problems discussed in #79 (notably no support for hardware decoding), but it can be configured to disable hardware decoding when the Matroska file includes PixelCrop properties. It also depends on mkvmerge (mkvtoolnix) to get the PixelCrop properties (meaning it only works for local files).

Sadly this script does not work for me with the latest mpv.

**Comment by wiwaz** [comment] 2023-09-01 05:21
With https://github.com/mpv-player/mpv/commit/f3f1a79fe3ad9bdae344559ec5802c184af41112 merged, is this feature finally possible to implement?

**Closed** 2023-09-17 16:48 UTC
Labels: meta:feature-request, core:file
