### ISSUE TITLE
Crashes when dragging a folder onto mpv from a mounted Samba share

### ISSUE THREAD

**Issue by areographe** [mpv-player/mpv#8071] opened 2020-09-10 09:01 UTC
#### mpv version
```
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100 (runtime 56.51.100)
   libavcodec      58.54.100 (runtime 58.91.100)
   libavformat     58.29.100 (runtime 58.45.100)
   libswscale      5.5.100 (runtime 5.7.100)
   libavfilter     7.57.100 (runtime 7.85.100)
   libswresample   3.5.100 (runtime 3.7.100)
ffmpeg version: n4.3.1
```

#### Linux Distribution and Version
```
System:    Kernel: 5.8.6-1-MANJARO x86_64 bits: 64 compiler: N/A 
           parameters: initrd=\intel-ucode.img initrd=\initramfs-5.8-x86_64.img 
           root=UUID=1994ff72-5669-4485-9bc3-a572a917da5e rw 
           Distro: Manjaro Linux 
```

#### Source of the mpv binary
Manjaro Repo

#### Window Manager and version
```
           Desktop: Cinnamon 4.6.7 tk: GTK 3.24.23 info: plank wm: Muffin dm: LightDM 1.30.0 
```
- GPU driver and version
```
Graphics:  Device-1: Intel Skylake GT2 [HD Graphics 520] vendor: Lenovo driver: i915 v: kernel 
           bus ID: 00:02.0 chip ID: 8086:1916 
           Display: x11 server: X.Org 1.20.9 compositor: muffin driver: intel 
           unloaded: modesetting alternate: fbdev,vesa display ID: :0 screens: 1 
           OpenGL: renderer: Mesa Intel HD Graphics 520 (SKL GT2) v: 4.6 Mesa 20.1.7 
           direct render: Yes 
```

### Reproduction steps

Using Nemo on Cinnamon, mount a Samba share and find a folder with music files. Drag the folder onto a newly-opened mpv window.

*Reproduced with no-config.*

### Expected behavior

Dragging a folder of music stored locally adds all music files in the folder to a playlist and begins playing the first file, displaying album artwork if found. If I right-click the folder of music on the mounted Samba share in Nemo and choose 'Open with -> mpv' it works perfectly. However, dragging the folder from the Samba share crashes mpv.

### Actual behavior

mpv crashes with the following error:

```
Using netbios name <my hostname>.
Using workgroup WORKGROUP.
gensec_spnego_client_negTokenTarg_step: SPNEGO(ntlmssp) login failed: NT_STATUS_WRONG_CREDENTIAL_HANDLE
```

### Log file

https://0x0.st/i671.txt

**Comment by Akemi** [comment] 2021-05-01 09:34
your mpv didn't crash at all, it normally exited because it can't open the remote smb folder folder. 

your file browser, or whichever program you drag your folder from, passes an `smb://`(`smb://libreelec.local/storageworld/Music/Collarbones/Die%20Young`) url to mpv. mpv tried to open this via the smb protocol like asked to and can't because of the missing credentials. either you make your file browser prepend the credentials to the url (`smb://user:password@host`), which might be kinda bad, or make it pass the locally mounted file path instead.

duplicate of #1512

**Closed by Akemi** 2021-05-01 09:34 UTC
Labels: core:file, meta:needs-reproduction, os:linux
