### ISSUE TITLE
[Suggesion] Set af=scaletempo2 by default

### ISSUE THREAD

**Issue by All3xJ** [mpv-player/mpv#9315] opened 2021-10-16 14:11 UTC
if I open a video with mpv and I increase the speed of the video, the voice of the one who is talking seems "robotic". If I instead set "af=scaletempo2" option in "~/.config/mpv/mpv.conf", and I increase the speed, the voice is good.

### Expected behavior of the wanted feature
mpv should opens by default with af=scaletempo2, if there are not issues with that. it seems better.

**Comment by sfan5** [comment] 2021-10-16 14:13
duplicate of #8376, this was already done.

**Closed by sfan5** 2021-10-16 14:13 UTC
Labels: meta:feature-request

**Comment by All3xJ** [comment] 2021-10-16 16:59
> duplicate of #8376, this was already done.

ok, sorry. Can't believe I didn't realized that. I have also checked for duplicates.....
