### ISSUE TITLE
mpv fails to build with error of various swift errors

### ISSUE THREAD

**Issue by xanadu6291** [mpv-player/mpv#6619] opened 2019-04-07 08:27 UTC
### mpv version and platform

mpv version : commit 8b114e574abd08892612e21e784ea1872e1adf8c

platform : macOS 10.14.4

### Reproduction steps

cd ${CMPL}/mpv
git pull
./waf clean
./waf configure --prefix=${TARGET} --disable-debug-build --disable-manpage-build CC=/usr/bin/gcc AR=/usr/bin/ar
./waf build

Then build fails

### Expected behavior

Build mpv successfully

### Actual behavior

Build fails

### Log file

Below is the log of ./waf build command:
https://0x0.st/zZSp.txt

### Sample files

There's no sample file

**Comment by j605** [comment] 2019-04-07 08:41
Duplicate of #6614 which was also a duplicate. Search the issue tracker before posting the same issue over and over.

**Comment by Akemi** [comment] 2019-04-07 09:13
downgrade your xcode for now.

**Closed by Akemi** 2019-04-07 09:13 UTC
Labels: duplicate, osx
