### ISSUE TITLE
Erratic behavior with streams longer than 24 hours.

### ISSUE THREAD

**Issue by WuvorWenda** [mpv-player/mpv#6462] opened 2019-01-25 07:53 UTC
### mpv version and platform

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Load a file longer than 24 hours
### Expected behavior
Display the time correctly, 

### Actual behavior
File seeks bad and jumps around between time stamps.

I often record streams 24 hours a day.
Playback with MPV and seeking jumps a round the file.
The jumping start when the pts goes from 23:59:59 to 00:00:00.

**Comment by zc62** [comment] 2019-02-15 23:38
Cannot reproduce. Tried this 25 hours video: https://www.youtube.com/watch?v=vX-f0C_qW6k mpv worked as expected.

Make sure it is not the problem of the recorded file itself. Did you try other players to see if they work? Also, a full log file is always helpful. https://mpv.io/manual/master/#options-log-file

**Comment by wm4** [comment] 2019-10-24 11:49
This depends on the stream. The stream you tried probably rolls over after 24 hours, while others do not. Issue reporter isn't responding -> closing.

**Closed by wm4** 2019-10-24 11:49 UTC
Labels: core, core:stream
