### ISSUE TITLE
Crash ass.c:874: decode_font: Assertion on opening ASS subtitle

### ISSUE THREAD

**Issue by Ashkan4472** [mpv-player/mpv#8560] opened 2021-02-13 00:52 UTC
hi everyone. i have an issue with ASS subtitles. when i drag and drop a file into mpv, suddlen mpv would crash with this message
```
mpv https://fooUrl.mkv
 (+) Video --vid=1 (*) (h264 1280x720 23.976fps)
 (+) Audio --aid=1 --alang=jpn (*) (aac 8ch 48000Hz)
     Audio --aid=2 --alang=jpn (aac 2ch 48000Hz)
     Audio --aid=3 --alang=jpn (aac 2ch 48000Hz)
 (+) Subs  --sid=1 --slang=eng (*) 'English [Kaiji]' (ass)
     Subs  --sid=2 --slang=eng 'English [Lonely Hikikomori]' (ass)
File tags:
 Title: foo.mkv
AO: [pulse] 48000Hz 7.1 8ch float
VO: [gpu] 1280x720 yuv420p
mpv: ass.c:874: decode_font: Assertion `dsize == size / 4 * 3 + FFMAX(size % 4 - 1, 0)' failed.
[1]    7019 abort (core dumped)  mpv 
```
i am suspicion that there is a library that i didnt installed in arch. this happens with all players and all ASS files

### Important Information

mpv version:
```
mpv 0.33.0-dirty Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.51.100
   libavcodec      58.91.100
   libavformat     58.45.100
   libswscale      5.7.100
   libavfilter     7.85.100
   libswresample   3.7.100
FFmpeg version: n4.3.1
```

Linux Distribution and Version: `5.10.15-arch1-1`
Source of the mpv binary: installed with yay in arch
Window Manager and version : `Plasma 5.20.5` with `KWin`

### Reproduction steps
open a .mkv file and drag drop ASS file into it

### Expected behavior
render the subtitle

### Actual behavior
crashed with error

### Log file
https://0x0.st/-XPN.txt

### Sample files
any video with with ASS subtitle(https://0x0.st/-XPq.ass)

**Comment by TheOneric** [comment] 2021-02-13 02:09
That should be fixed by https://github.com/libass/libass/commit/017137471d0043e0321e377ed8da48e45a3ec632 *(the very first libass commit after `0.15.0`)*

It only affects files with a font embedded into the ASS-file; if you can't build/use a libass version with the above commit backported/included, as a workaround the font can be embedded into the mkv instead *(which likely also reduces overall file size)*

**Comment by Ashkan4472** [comment] 2021-02-13 02:33
Thank you so much it worked like a charm

> That should be fixed by [libass/libass@0171374](https://github.com/libass/libass/commit/017137471d0043e0321e377ed8da48e45a3ec632) _(the very first libass commit after `0.15.0`)_
It is shame that they dont released a patch for something like that, i think there are many ASS filea with embedded fonts

**Closed** 2021-02-13 03:00 UTC
Labels: os:linux, upstream:libass

**Comment by SSgumS** [comment] 2021-02-21 11:39
> That should be fixed by [libass/libass@0171374](https://github.com/libass/libass/commit/017137471d0043e0321e377ed8da48e45a3ec632) _(the very first libass commit after `0.15.0`)_
> 
> It only affects files with a font embedded into the ASS-file; if you can't build/use a libass version with the above commit backported/included, as a workaround the font can be embedded into the mkv instead _(which likely also reduces overall file size)_

There are ass subtitles with attached fonts. isn't it better to have a minor release on that commit or any commit after that?
We are a fansub group that our releases don't come with video and is just ASS files. Now our subs are all broken (at least in VLC 3.0.12 on linux and some mpv 0.33.0 releases on linux).
Thanks

**Comment by Akemi** [comment] 2021-02-21 11:50
maybe asked that on the libass issue tracker or their irc channel. at least there you can expect an answer for their release schedule.

**Comment by SSgumS** [comment] 2021-02-21 12:09
> maybe asked that on the libass issue tracker or their irc channel. at least there you can expect an answer for their release schedule.

You are right and I'm sorry. I saw TheOneric is a Member of libass repository. so I thought replying him here may be enough.
I will try there later if no success...
Thanks

**Comment by mrmoein** [comment] 2021-04-22 04:34
hello i have same problem in manjaro kde
receive same error in vlc, smplayer and mpv

full error in smplayer:
```
/usr/bin/mpv --no-config --no-quiet --terminal --no-msg-color --input-ipc-server=/tmp/smplayer-mpv-13f2e --msg-level=ffmpeg/demuxer=error --no-fs --hwdec=no --sub-auto=fuzzy --no-input-default-bindings --input-vo-keyboard=no --no-input-cursor --cursor-autohide=no --no-keepaspect --wid=65011742 --monitorpixelaspect=1 --osd-level=1 --osd-scale=1 --osd-bar-align-y=0.6 --sub-ass --embeddedfonts --sub-ass-line-spacing=0 --sub-scale=1 --sub-font=Arial --sub-color=#ffffffff --sub-shadow-color=#ff000000 --sub-border-color=#ff000000 --sub-border-size=0.75 --sub-shadow-offset=2.5 --sub-font-size=50 --sub-bold=no --sub-italic=no --sub-margin-y=8 --sub-margin-x=20 --sub-codepage=ISO-8859-1 --vid=1 --sid=1 --sub-file=/home/moein/Desktop/[AnimDL.ir] 86 EIGHTY-SIX - 02 [Mendokusai][ShiraRaminz].ass --sub-pos=100 --volume=110 --cache=auto --start=19 --screenshot-template=cap_%F_%p_%02n --screenshot-format=jpg --screenshot-directory=/home/moein/Pictures/smplayer_screenshots --audio-pitch-correction=yes --volume-max=110 --ytdl=no --term-playing-msg=MPV_VERSION=${=mpv-version:}
INFO_VIDEO_WIDTH=${=width}
INFO_VIDEO_HEIGHT=${=height}
INFO_VIDEO_ASPECT=${=video-params/aspect}
INFO_VIDEO_FPS=${=container-fps:${=fps}}
INFO_VIDEO_FORMAT=${=video-format}
INFO_VIDEO_CODEC=${=video-codec}
INFO_AUDIO_FORMAT=${=audio-codec-name}
INFO_AUDIO_CODEC=${=audio-codec}
INFO_AUDIO_RATE=${=audio-params/samplerate}
INFO_AUDIO_NCH=${=audio-params/channel-count}
INFO_LENGTH=${=duration:${=length}}
INFO_DEMUXER=${=current-demuxer:${=demuxer}}
INFO_SEEKABLE=${=seekable}
INFO_TITLES=${=disc-titles}
INFO_CHAPTERS=${=chapters}
INFO_TRACKS_COUNT=${=track-list/count}
METADATA_TITLE=${metadata/by-key/title:}
METADATA_ARTIST=${metadata/by-key/artist:}
METADATA_ALBUM=${metadata/by-key/album:}
METADATA_GENRE=${metadata/by-key/genre:}
METADATA_DATE=${metadata/by-key/date:}
METADATA_TRACK=${metadata/by-key/track:}
METADATA_COPYRIGHT=${metadata/by-key/copyright:}
INFO_MEDIA_TITLE=${=media-title:}
INFO_STREAM_PATH=${stream-path}
 --audio-client-name=SMPlayer --term-status-msg=STATUS: ${=time-pos} / ${=duration:${=length:0}} P: ${=pause} B: ${=paused-for-cache} I: ${=core-idle} VB: ${=video-bitrate:0} AB: ${=audio-bitrate:0} http://cf5.oyrbjdbfg.tk/Anime/2021/Spring/Shadows%20House/1080p/Shadows%20House%20-%2001%20%5B1080p%5D%20%5BAnimDL.ir%5D.mkv

 (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=jpn (aac 2ch 48000Hz)
 (+) Subs  --sid=1 --slang=eng (*) 'English subs' (ass)
     Subs  --sid=2 '[AnimDL.ir] 86 EIGHTY-SIX - 02 [Mendokusai][ShiraRaminz].ass' (ass) (external)
File tags:
 Title: Shadows House - 01 [AnimDL.ir]
AO: [pulse] 48000Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p
INFO_VIDEO_DSIZE=1920x1080
MPV_VERSION=mpv 0.33.1-dirty
INFO_VIDEO_WIDTH=1920
INFO_VIDEO_HEIGHT=1080
INFO_VIDEO_ASPECT=1.777778
INFO_VIDEO_FPS=23.976025
INFO_VIDEO_FORMAT=h264
INFO_VIDEO_CODEC=h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)
INFO_AUDIO_FORMAT=aac
INFO_AUDIO_CODEC=aac (AAC (Advanced Audio Coding))
INFO_AUDIO_RATE=48000
INFO_AUDIO_NCH=2
INFO_LENGTH=1432.022000
INFO_DEMUXER=mkv
INFO_SEEKABLE=yes
INFO_TITLES=
INFO_CHAPTERS=0
INFO_TRACKS_COUNT=4
METADATA_TITLE=Shadows House - 01 [AnimDL.ir]
METADATA_ARTIST=
METADATA_ALBUM=
METADATA_GENRE=
METADATA_DATE=
METADATA_TRACK=
METADATA_COPYRIGHT=
INFO_MEDIA_TITLE=Shadows House - 01 [AnimDL.ir]
INFO_STREAM_PATH=http://cf5.oyrbjdbfg.tk/Anime/2021/Spring/Shadows%20House/1080p/Shadows%20House%20-%2001%20%5B1080p%5D%20%5BAnimDL.ir%5D.mkv
INFO_TRACK_0: video 1 '' '' yes
INFO_TRACK_1: audio 1 'jpn' '' yes
INFO_TRACK_2: sub 1 'eng' 'English subs' yes
INFO_TRACK_3: sub 2 '' '[AnimDL.ir] 86 EIGHTY-SIX - 02 [Mendokusai][ShiraRaminz].ass' no
mpv: ass.c:874: decode_font: Assertion `dsize == size / 4 * 3 + FFMAX(size % 4 - 1, 0)' failed.

```

libass version: `Release 0.15.0`

**Comment by avih** [comment] 2021-04-22 05:40
> hello i have same problem in manjaro kde

This doesn't help anyone. The problem was in libass, and already fixed. The issue is not in mpv but rather at the distro package. I'm guessing then whenever libass creates a new release then the distro will upgrade it and the issue will be solved. If you have any complaints, please talk to the libass guys or to your distro libass maintainer.

**Comment by Akemi** [comment] 2021-04-22 05:41
i dunno what you expect? this issue has been closed because it's a problem that is not within mpv. it has already been fixed. if you have the same problem in different players why report it to mpv? we don't give support for smplayer.
