### ISSUE TITLE
Automatically disable interpolation when display FPS is a multiple of video FPS

### ISSUE THREAD

**Issue by mrnoname1000** [mpv-player/mpv#7467] opened 2020-02-17 02:49 UTC
### Expected behavior of the wanted feature
When running e.g. a 24 FPS video on a 120 FPS display, since 120 is a multiple of 24, interpolation should be automatically disabled. Also, for videos with variable FPS, interpolation should be enabled or disabled as the FPS changes. The `interpolation-threshold` option should also be used on the video FPS and its multiples, e.g. a 29.97 FPS video shouldn't be interpolated on a 60 FPS display with an `interpolation-threshold` setting of 0.01, since 29.97 * 2 is within 0.01 FPS of 60.
I only use interpolation to remove judder, so I prefer interpolation to be disabled when the video wouldn't judder without it.
Perhaps the interpolation option could have a value added that enables this, i.e. `interpolation=non-multiple` or something.
### Alternative behavior of the wanted feature
Right now, interpolation is either enabled or disabled. The user has to make the judgement that interpolation is unnecessary or too expensive.

**Comment by joaochrisostomo** [comment] 2020-03-29 19:32
Isn't it possible with scripts?

**Comment by ValZapod** [comment] 2020-09-14 23:05
> since 120 is a multiple of 24

No, it is not that simple. 120 can be either 119.88 or 120.000 and 24 can be 24.000 or 23.976 (24000/1001). In case of a mismatch it will be bad.

**Comment by mrnoname1000** [comment] 2020-09-15 08:09
From what I understand, when using `video-sync=display-*`, the video speed is changed to match the display within a certain threshold. What I'm proposing is an option to only enable interpolation when it's impossible to resolve judder. For example, a 29.97 Hz video played on a 60 Hz screen is adjusted to a 30 Hz video, which cleanly multiplies into 60. So if interpolation were disabled, there would be no judder. I don't think this new option would be relevant when not using `video-sync=display-*`, and I've always used the latter, so I forgot about it when writing the feature request.

I don't know if it's possible using scripts, but a built-in option would be cleaner for the user and potentially faster. I don't have much experience with Lua, but maybe someone could point me in the right direction.

**Comment by ValZapod** [comment] 2020-09-15 08:24
> 29.97 Hz video played on a 60 Hz screen

No, in most cases 60 Hz screen is actually 60000/1001 ~ 59.94 (and 60.000 is alternate clock) and this 29.97 (actually 30000/1001) evenly devides it. Nothing to do here.

**Comment by ValZapod** [comment] 2020-09-15 08:25
You can check your actual Vsync using https://www.vsynctester.com/ anc chrome.

**Comment by mrnoname1000** [comment] 2020-09-16 15:02
I was giving an example of a hypothetical situation. Obviously the refresh rate isn't going to be exactly 60 Hz in the real world, but my point was that mpv adjusts the video speed to match vsync when using `video-sync=display-*`. On my laptop, xrandr reports the refresh rate to be 60.01, and the site you linked seems to match up with that, so very few videos will actually divide it without adjustment.

What I'm saying is that when the video being displayed divides into vsync evenly (either due to mpv changing the speed, or, as in your example, the video rate happens to evenly divide the monitor rate) interpolation is unnecessary to remove judder. In my opinion, frame doubling looks better than simple interpolation, which in turn looks better than displaying some frames once and some frames twice.

**Comment by ValZapod** [comment] 2020-09-16 15:07
> xrandr reports the refresh rate to be 60.01

What is reported using https://www.displayhz.com/?

**Comment by mrnoname1000** [comment] 2020-09-16 15:12
It hovers around 60.008 Hz.

**Comment by wm4** [comment] 2020-09-16 15:16
Stop suggesting webshit for measuring display FPs, or I'll block you.

**Comment by ValZapod** [comment] 2020-09-16 16:09
That is what we use in chromium. https://bugs.chromium.org/p/chromium/issues/detail?id=467617

**Comment by wm4** [comment] 2020-09-16 16:24
That seems to be about using another function to wait for vsync (link from the issue: https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmthk/nf-d3dkmthk-d3dkmtwaitforverticalblankevent?redirectedfrom=MSDN).
That doesn't apply to mpv in this case. display-sync mode doesn't involve any timers (at least within mpv) to show the frame, instead it queues up as many frames as possible, and leaves the rest to the GPU API to block if too much work has been queued up.
In audio timing mode, it uses SleepConditionVariableSRW though.

**Comment by ValZapod** [comment] 2020-09-16 16:33
They guy has some kind of non standard 60.01 refresh rate and looks like it is confirmed by (very stable) javascript APIs in Chrome/Chromium THAT REPORTS actual refresh rate in the driver and not in xrandr or whatever. So, we cannot disable interpolation, right?

**Comment by ValZapod** [comment] 2020-09-16 16:35
Looks like this BTW. https://github.com/linuxhw/EDID/blob/16bc0afe546b07752d71bd7fb4ba0cecd763830f/Digital/Samsung/SEC3030/1F2DCA0DD7A5#L34

DTD 1:  1366x768    60.010 Hz 683:384  47.408 kHz  69.310 MHz (256 mm x 144 mm)

**Comment by wm4** [comment] 2020-09-16 16:43
I have no idea what you're trying to say. Whether the rate is 59.9 or 60.1 doesn't matter for interpolation. If you e.g. play 30 fps video on a 59.9 Hz display, display-sync will change the video speed so that 1 video frame is displayed each display frame (and if interpolation is enabled, 1 display frame will show an interpolated frame).

And no, these webshit things only display a web browser's idea about vsync. Stop suggesting it, or I'll block you.

**Comment by Dudemanguy** [comment] 2022-05-13 23:00
Old one here, but you can actually accomplish this with auto-profiles. For an example that uses `interpolation-threshold`:

```
video-sync=display-resample
interpolation=yes
[disable interpolation]
profile-cond= math.abs(display_fps / container_fps - math.ceil(display_fps / container_fps)) < interpolation_threshold
interpolation=no
```

Using `math.floor` instead of `math.ceil` may be better depending on your monitor (i.e. pick the one that is closer to an integer). Closing this one now since interpolation is a little bit different on `gpu-next` which makes it unlikely for anyone to change any of the interpolation options since it may affect things differently.

**Closed by Dudemanguy** 2022-05-13 23:00 UTC
Labels: meta:feature-request, core:video

**Comment by prez** [comment] 2022-05-15 11:26
So how will one accomplish this with `gpu-next`? Or will it just "do the right thing"?

**Comment by Dudemanguy** [comment] 2022-05-15 14:55
The same auto-profile works on `gpu-next` and you would still need to use it if you want this behavior (disabling interpolation on integer multiplies).
