### ISSUE TITLE
Accessing Properties via IPC API

### ISSUE THREAD

**Issue by mysteryx93** [mpv-player/mpv#8764] opened 2021-04-21 16:57 UTC
### Important Information

Provide following Information:
- mpv version v0.33.1
- Windows 10 x64
- Source of the mpv binary: MPV website

I'm using JSON IPC protocol to communicate with MPV. I'm having issues accessing some properties and would like some explanations.

Reading option `profile` gives this response.

    {"command":["get_property","profile"],"request_id":1}
    {"request_id":1,"error":"error accessing property"}

Option `reset-on-next-file` is a [List Option](https://mpv.io/manual/stable/#list-options) and should support this syntax according to doc

    {"command":["set_property","reset-on-next-file-add","volume"],"request_id":1}
    {"request_id":1,"error":"property not found"}

Maybe this way then? Neither.

    {"command":["set_property","reset-on-next-file","add","volume"],"request_id":1}
    {"request_id":1,"error":"invalid parameter"}

Anything I'm missing here? Most other properties are working fine.

**Comment by avih** [comment] 2021-04-21 17:14
> Reading option profile gives this response.

Most options are also mirrored by properties by the same name, but it seems the `profile` option is not one of those. This kind of makes sense, because its purpose is to set an initial set of configuration, and it cannot change in runtime after startup to replace the initial configuration.

> Option reset-on-next-file is a List Option and should support this syntax according to doc

It is a list option, but if you skip to the "General" section at the end of the list options section, then you'll see that you need to use the `change-list` command in order to change them at runtime.

I _think_ the NAME-add etc variants are used in config files, but shouldn't be used as runtime commands. Though I'm not 100% sure of that, and right now I can't find it referenced at the docs.

**Comment by avih** [comment] 2021-04-21 17:52
Actually, I think the documentation is correct, even if it's not 100% clear what applies where (PR for improving the docs is welcome).

The title is "List Options", i.e. they describe startup options syntax (at the command line or at a `mpv.conf` etc).

So you could use `--foo-add` to add an item to the list option `foo` on startup.

But at runtime the property name is only `foo`, and there's no property `foo-add` for instance. So in order to change a list property one should use the `change-list` command.

**Comment by mysteryx93** [comment] 2021-04-21 23:41
Thank you very much, that's working.

Another little bump, how can I set the values reliably? Setting the property directly is a SET in *most* cases, but sometimes it does an append instead, so I'm better to do a direct SET. However, it doesn't recognize this syntax.

    {"command":["change-list","reset-on-next-file","set",["volume","vid","aid"]],"request_id":1}
    {"request_id":1,"error":"invalid parameter"}

Sending "volume,vid,aid" does work though. What's a consistent way of escaping data, so that it works with values containing ',' and other special characters?

**Comment by avih** [comment] 2021-04-22 00:29
> What's a consistent way of escaping data, so that it works with values containing ',' and other special characters?

The straight answer is that I'm not sure off the top of my head, and you would have to search the docs, or the source code.

There are several way to "contain" sub elements, but I'm not sure which methods apply where. IIRC square brackets can be used in some cases, maybe double quotes, there's a `%N%VALUE-OF-N-BYTES` thingy, and possibly more.

But let me ask you another question in return: which property where set does append needs escaping of list items?

**Comment by avih** [comment] 2021-04-22 01:01
I also think that the reason the multi-value suffixes are "strongly discouraged" is exactly due to escaping shenanigans.

If (and it is an "if" which needs to be answered) there's value for atomic change of multiple items in the list, then perhaps the `change-list` command could support a `v` additional suffix to denote an arguments vector, so that multiple items can be specified as multiple arguments which are not escaped, for instance (input.conf syntax) `change-list foo setv bar baz` (and via JSON IPC it would simply be additional arguments - not one additional array of arguments like in your attempt).

However, even if we do answer that it has a value, someone still needs to implement it in a consistent way across all the relevant list suffixes and for all the lists types. I have no way to assess off the top of my head how big a task that would be.

**Comment by mysteryx93** [comment] 2021-04-22 05:17
I tried the syntax with change-list and several values as separate parameters -- not supported, but could be interesting to support.

`set_property` with multiple values *IS* supported. I think it's the best for me to stick to that.

I'm writing a generic class to handle all list properties, so a side-effect is that some properties will get a Append when calling Set; but in those cases you can always call Clear first so it's not a deal-breaker.

**Comment by mysteryx93** [comment] 2021-04-22 05:36
BUT -- is it really solving the problem? Calling Set or Add for a value of "Me, Myself and I" would interpret it wrongly (not sure what property can take that kind of value?)

So that's not really working better than joining the list myself...

**Comment by avih** [comment] 2021-04-22 05:45
I didn't suggest the solution is to join the list yourself, but rather than you should `append` the individual items one after the other in separate commands. This doesn't have the escape issue. Is that not good enough?

**Comment by mysteryx93** [comment] 2021-04-22 15:48
If I do that, I do not expose any of the properties with escaping at all: Add, Pre, Set .. Pre can be useful in some cases.

I got 2 options: exposing only methods that do not interpret escaping, or handle escaping on my side.

Looking at the escaping doc, it says to wrap special characters in "", but... how do you escape " itself?
https://mpv.io/manual/stable/#escaping-spaces-and-other-special-characters

**Comment by avih** [comment] 2021-04-22 16:55
I'm not sure if you're talking to yourself? Or asking anything?

Can we close this issue?

**Comment by mysteryx93** [comment] 2021-04-22 17:10
Even if I take your suggestion of ignoring methods that escape values... I come into the same issue with [Key/Value List Options](https://mpv.io/manual/stable/#key-value-list-options). All the methods use escaping.

So I got no choice but to handle escaping. Which I still have no information about. Doc talks about using "" and [] for escaping, which doesn't seem to work with IPC.

For script options (script-opts), it can potentially contain conflicting characters.

Got any other idea?

**Comment by avih** [comment] 2021-04-22 18:15
Idea for what _exactly_ ?

So, the original problem with `reset-on-next-file-add` is solved, and now you have the "same issue" with key-value list options?

Note that only the key accepts escaping. Did you consider or try the 100% unambiguous `%n%` escaping method which I mentioned before?

**Comment by mysteryx93** [comment] 2021-04-22 20:49
None of the escaping methods work. Is this a bug?

    {"command":["change-list","reset-on-next-file","set","%6%volume,%3%vid,%3%aid"],"request_id":1}
    {"data":null,"request_id":1,"error":"success"}
    {"command":["get_property","reset-on-next-file"],"request_id":2}
    {"data":["%6%volume","%3%vid","%3%aid"],"request_id":2,"error":"success"}

It's certainly an issue if there are no ways of using those methods reliably via API.

**Comment by avih** [comment] 2021-04-22 20:54
OK, we seem to be going in circles. Let's focus on one problem at a time. Please don't bring up different poblems until we conclude this one, OK? good.

Does using `append` for one item at each command solves the `reset-on-next-file` issue? If not, why?

**Comment by mysteryx93** [comment] 2021-04-22 20:59
Append works. It's not expected to escape anything. We can get things done with Append, Remove and Clear.

Except Dictionary-append key=value, what if key or value contain '=' ?

**Comment by avih** [comment] 2021-04-22 21:03
> Except Dictionary-append key=value

There is no except. `reset-on-next-file` does not take key-value. Can we conclude that list options which don't use key-value are solved, without any exception?

**Comment by mysteryx93** [comment] 2021-04-22 21:13
Option list can be solved that way.

Remains Option dictionary such as ytdl-raw-options and script-opts.

**Comment by avih** [comment] 2021-04-22 21:15
Great.

Now, with key-value lists, when using `append` to change one item at a time, is there any problem if the key does not contain `=`?

**Comment by mysteryx93** [comment] 2021-04-22 21:30
Ran some unit tests on Option List, with custom SET implementation where I call Clear and then Append repeatedly. It's all working.

My guess is that dictionary will only have issues if key contains '=', which normally shouldn't happen. Prohibiting '=' in key would be a solution. Let me run some tests.

**Comment by avih** [comment] 2021-04-22 21:32
> My guess is that dictionary will only have issues if key contains '='

Which is exactly why I excluded this case from my question. So can we conclude that when the key does not contain `=`, the problem is solved, without exceptions?

**Comment by mysteryx93** [comment] 2021-04-22 21:37
That approach is a bit hacky to my taste, but works. Ignore API that interprets ',' and prohibit '=' from key.

If escaping really isn't supported with the API, then so be it. I'll just do that and move on.

**Comment by avih** [comment] 2021-04-22 21:43
> works

Good. So don't use `=` in key names. The existing key-value list options don't have `=` at key names, and that's not expected to change.

> If escaping really isn't supported with the API, then so be it

Not sure where you got this idea from. I certainly never said anything which even resembles it.

I said I don't know the exact details, and you'll have to experiment and/or read the docs and/or read the source code.

Anyway, I'd consider the problem solved for now. Do correct me if I'm wrong.

**Closed by avih** 2021-04-22 21:43 UTC
Labels: os:win

**Comment by mysteryx93** [comment] 2021-04-22 22:20
> Not sure where you got this idea from. I certainly never said anything which even resembles it.

I tested it. None of the escaping methods are supported.

Anyway I got a good enough solution, thanks.

**Comment by avih** [comment] 2021-04-22 23:08
Well, I didn't try to explore it myself in this issue, because if there's a solution which doesn't involve escaping then it's just better than compound and escaped solutions. Additionally, we were first trying to establish ANY solution which is guaranteed to work, and avoiding escaping seemed like the shortest way to get there.

Optimally, a solution might include a structure, like you quoted the docs with MPV_FORMAT_NODE_MAP. I presume that if it's documented then you should be able to get it to work. It's just that my first priotity was to get a working solution, before determining what the best working solution is.

Feel free to experiment or learn the docs more, and if you reach any conclusion about a better way to solve it, feel free to post here for the benefit of others.

**Comment by mysteryx93** [comment] 2021-04-22 23:56
Surprise! Escaping on Append works for dictionaries, for both key and value! (contrary to documentation)

By adding %n% on both key and value, it works... mostly. Except for special characters.

    {"command":["change-list","ytdl-raw-options","add","%2%\u6F22\u5B57=a"],"request_id":1}
    {"request_id":1,"error":"error running command"}

So... let's put the encoded string length instead? Nope.

    {"command":["change-list","ytdl-raw-options","add","%12%\u6F22\u5B57=a"],"request_id":1}
    {"request_id":1,"error":"error running command"}

How do I get this query to work?

**Comment by avih** [comment] 2021-04-23 05:02
> How do I get this query to work?

You keep asking the same question, for which I've already replied twice, and now a third time: I don't know. You'll have to experiment.

However, this use case is pretty much the same as `=`, mpv doesn't have such key names, so it's not an issue you'll have to face in practice. In fact, I don't think key names are expected to hold anything other ascii letters and digits ([a-zA-Z0-9]), underscore, and dash (`-`).

**Comment by avih** [comment] 2021-04-23 07:09
> By adding %n% on both key and value, it works... mostly. Except for special characters.
> So... let's put the encoded string length instead? Nope.

You forgot the way which actually does work. Remember that the %n% syntax is for the number bytes, which is for the value, after the JSON was decoded. In this case each of those codepoints is 3 bytes, so you should have used %6%, or oculd even use `=` at the key like so `"%7%\u6F22=\u5B57=abc"`.

**Comment by mysteryx93** [comment] 2021-04-23 16:59
Byte count. OK that works. %n% format works quite well for escaping, so it can be used everywhere.

There are also inconsistencies as to which endpoints support escaping or not, so I'll open a bug report about that.
