### ISSUE TITLE
play videos from folder, one after another on pressing a key

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#3547] opened 2016-09-19 11:28 UTC
mpv git-b1893d2 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
built on Sun Nov 8 16:37:08 UTC 2015
ffmpeg library versions:
libavutil 54.31.100
libavcodec 56.60.100
libavformat 56.40.101
libswscale 3.1.101
libavfilter 5.40.101
libswresample 1.2.101
ffmpeg version: 2.8.7

I have a folder with lot of videos and other files(non video). It is possible i can play the videos one after another sorted as per date/name without need to go to the folder to play next one.

**Comment by wiiaboo** [comment] 2016-09-19 12:21
Put [this] in a script folder inside mpv's conf folder.

[this]: https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua

**Comment by sant527** [comment] 2016-09-19 13:28
how to sort by data rather than by name

**Comment by wiiaboo** [comment] 2016-09-19 15:21
You can't with just mpv and lua.
Try with [this] version of autoload.lua. Change the SORTBY value at the start to "date".

[this]: https://i.fsbn.eu/WK1x.txt

**Comment by JaKXz** [comment] 2016-10-08 16:52
This looks like a duplicate of #3530 - you can do `mpv ./` with options in the directory you want to play files in, but if you're on macOS Sierra it doesn't work atm.

**Comment by Hrxn** [comment] 2016-10-08 17:01
BTW, what about `mpv *`? (Works in Windows, for example..)

**Comment by wm4** [comment] 2016-10-14 22:13
Some shells support glogging with sorting by e.g. date, I think. But don't ask me.

For such advanced uses write a script.

**Closed by wm4** 2016-10-14 22:13 UTC
Labels: question

**Comment by haasn** [comment] 2016-10-14 23:58
`ls -rt | mpv -playlist -` would be a quick and dirty hack that works in any shell

**Comment by RallyQ** [comment] 2022-04-05 01:07
> 你不能只使用 mpv 和 lua。 试试 [这个 ](https://i.fsbn.eu/autoload.lua)版本的 autoload.lua。 将开头的 SORTBY 值更改为“日期”。

这个版本的可以按照日期排序，谢谢！但是播放列表中非英文字符是乱码，而原版autoload.lua没有这个问题。请问怎样更改才能正常显示非英文字符呢？

**Comment by RallyQ** [comment] 2022-04-05 01:09
> You can't with just mpv and lua. Try with [this](https://i.fsbn.eu/autoload.lua) version of autoload.lua. Change the SORTBY value at the start to "date".

This version can be sorted by date, thank you! But the non-English characters in the playlist are garbled, while the original autoload.lua has no such problem. How can I change it to display non-English characters normally?
