### ISSUE TITLE
winvk is not working

### ISSUE THREAD

**Issue by arm64-v9a** [mpv-player/mpv#11615] opened 2023-04-22 14:54 UTC
### Important Information

Provide following Information:
- mpv version 0.35.0-364-gc7a8e715
- Windows Version 10.0.25346 Build 25346
- [Source of the mpv binary](https://github.com/zhongfly/mpv-winbuild/releases/download/2023-04-22/mpv-x86_64-v3-20230422-git-c7a8e71.7z)
- If known which version of mpv introduced the problem
   The problem seems to be caused by libplacebo
- Possible screenshot or video of visual glitches
  Not applicable

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

`mpv --no-config --gpu-context=winvk`

### Expected behavior
Everything is fine
### Actual behavior
crash
### Log file

[log.txt](https://github.com/mpv-player/mpv/files/11301582/log.txt)
[vulkaninfo.txt](https://github.com/mpv-player/mpv/files/11301585/vulkaninfo.txt)

### Sample files

Not applicable

**Comment by haasn** [comment] 2023-04-22 15:49
Can you provide a backtrace somehow?

**Comment by kasper93** [comment] 2023-04-23 11:26
Uninstall Rivatuner Statistics Server and try again.

**Comment by kasper93** [comment] 2023-04-23 12:44
I recall that older RTSS vk layer was broken, not sure it is fixed with newer version. Can you try with latest version? 

Maybe @haasn have better idea what could trigger this bug, but ultimately it is their fault for trying to call nullptr (not loading something that they use), you should report it to RTSS developer.

**Comment by kasper93** [comment] 2023-04-29 12:10
I came to realization that shinchiro's mpv build is using own Vulkan loader build from the main branch. They frankly shouldn't build every single things and use GPU driver provided loader which is stable.

Crashes were not caused by any mpv or libplacebo change, but Vulkan loader.

Regressed by: https://github.com/KhronosGroup/Vulkan-Loader/commit/4be91725abb01e8004be966203b95a181c06e1a0
Workaround by: https://github.com/KhronosGroup/Vulkan-Loader/commit/23d4caea0d450b94fd96fa380307d755379df5a2

While ultimately this is a bug in RTSS (out of spec call and not checking for nullptr), developer refuses to fix it. Link for posterity: https://forums.guru3d.com/threads/vk_layer_rtss-crashes-on-vkcreateinstance.447674 (you can find more related discussion and links inside)

Current shinchiro's mpv on SF is from 23.04, which has the problematic Vulkan loader linked. You can use newer build which is not affected form: https://github.com/shinchiro/mpv-winbuild-cmake/releases 

Should any similar issue arise in the future you also have mentioned `DISABLE_RTSS_LAYER` environmental variable to exclude RTSS layer.

**Comment by sfan5** [comment] 2023-04-29 12:14
Still not mpv's bug.

**Closed by sfan5** 2023-04-29 12:14 UTC
Labels: os:win
