### ISSUE TITLE
Entering fullscreen with Vulkan freezes window content on AMD

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#8008] opened 2020-08-16 16:44 UTC
### Important Information

-mpv-x86_64-20200816-git-7f67c52
-Windows 10 2004
-shinchiro SF repo

### Reproduction steps

Play any video with `--gpu-api=vulkan` and enter fullscreen

### Expected behavior

Playback should continue normally in fullscreen

### Actual behavior

Playback freezes and shows the last frame from before entering fullscreen (playback returns normally after switching back into windowed mode). mpv fullscreen has always been rather problematic on AMD Windows, i.e. slow switching. But of course it always freezing makes it unusable. The AMD driver seems to treat it as "exclusive" fullscreen, and unfortunately no mpv config option seems to help to avoid that.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/5081005/output.txt)

### Sample files

Can be any video.

**Comment by h1z1** [comment] 2020-08-18 00:25
I don't know if this is specific to AMD nor Windows given I've seen the same thing in Linux and NVIDIA?  Vulkan can bring X to it's knees with a poorly encoded video

**Comment by Dudemanguy** [comment] 2020-08-18 01:20
>Linux and NVIDIA

Almost certainly a NVIDIA driver issue.

**Comment by Jules-A** [comment] 2020-08-18 11:19
Might not be related but I'm also using AMD (RX570) on Windows 1909 using Vulkan and fullscreen causes my monitor to switch from 75hz to 60hz (the process causes a black screen for ~5secs) and is very laggy afterwards.

**Comment by aufkrawall** [comment] 2020-08-18 11:40
> Almost certainly a NVIDIA driver issue.

Yep, switching into fullscreen on Windows worked fine with the Nvidia card that was installed before and Linux Xorg issues should be unrelated.

> Might not be related but I'm also using AMD (RX570) on Windows 1909 using Vulkan and fullscreen causes my monitor to switch from 75hz to 60hz (the process causes a black screen for ~5secs) and is very laggy afterwards but I don't recall it freezing completely.

I waited like 10 seconds or so and it didn't recover. I'm also using single refresh rate EDID, so it can't change it.

**Comment by Jules-A** [comment] 2020-08-19 11:39
> I waited like 10 seconds or so and it didn't recover. I'm also using single refresh rate EDID, so it can't change it.

What happens when you don't? Seems like it's forcing to run at 60hz for some reason like it's hardcoded, maybe since it can't it ends up failing?

**Comment by aufkrawall** [comment] 2020-08-19 16:30
It happens also with my default EDID that features only 60Hz.

**Comment by Provissy** [comment] 2020-08-24 12:55
My RX570 with a 60HZ display experience no issue. Same Windows 10 2004 & Vulkan are being used. When switching to fullscreen, the screen will turn black for about 2 seconds then enter exclusive mode, playback will then be resumed. 

Did you turn AMD FreeSync on? or flip it on and try again?

**Comment by aufkrawall** [comment] 2020-08-24 13:04
My display is not VRR capable. I also think that a 2s transition wouldn't be acceptable either. While this is certainly AMD's fault, it would still be nice to have a workaround (if possible).

**Comment by Jules-A** [comment] 2020-08-24 19:48
> While this is certainly AMD's fault, it would still be nice to have a workaround (if possible).
What makes you think it's AMD's fault? I haven't noticed anything like this in any other Vulkan app?

**Comment by aufkrawall** [comment] 2020-08-24 19:53
It works with Intel & Nvidia (without weird transition slowness) and fullscreen behavior can also be bad in other Vulkan fullscreen applications with AMD. E.g. it doesn't seem to "unredirect" DWM compositing when I alt + tab out and again into some games with DXVK on Windows when there are other windows at the same time, so ironically what would be more desirable for media players.

**Comment by Provissy** [comment] 2020-08-25 10:54
Comparing to freeze after switching to fullscreen, I think a short latency is totally acceptable! But it certainly could be better. 

I use the "pro" version of the AMD's Radeon Software. afaik, the "pro" version is proprietary and the normal one is open source(at least for Linux), there might be some difference between them, you could probably give it a try.

**Comment by Jules-A** [comment] 2020-08-25 10:55
Oh, I just realised MPV allows changing the swapchain mode, I can't really test it now but have you tried changing those settings? I have a feeling choosing another mode may solve this but it's just a theory.

**Comment by aufkrawall** [comment] 2020-08-28 15:41
Yes, that's what I meant ("freezes window content").
I tested with D3D11 -> Vulkan via DXVK and that way mpv can enter fullscreen normally.

**Comment by Jules-A** [comment] 2020-08-28 20:55
Yes, it works fine with DXVK and not only that but it has by far the lowest Vsync jitter I've seen. That said, the Anime4k shaders I'm trying to run give a green screen under DX11 and the same thing happens when using DXVK.

**Comment by Maikurosofuto** [comment] 2020-09-19 22:47
Same thing here...works with any other API, but just freezes on Vulkan when i use fullscreen. That's pretty sad, since vulkan don't even stress the GPU (RX 5700 XT in my case). And for some weird reason, this just started some days ago, before that i was able to use without a single freeze, even with 4K or astonishing overkill 8K videos.

**Comment by haasn** [comment] 2020-10-21 13:00
I don't think there's anything we can do to work around this, unfortunately. Until there's some sort of vulkan extension to control what happens when going into fullscreen. It's possible you can find some driver setting to disable it.

**Comment by lextra2** [comment] 2020-11-08 22:32
> 
> 
> Might not be related but I'm also using AMD (RX570) on Windows 1909 using Vulkan and fullscreen causes my monitor to switch from 75hz to 60hz (the process causes a black screen for ~5secs) and is very laggy afterwards but I don't recall it freezing completely.

Delete all resolutions except the one you're using [with CRU](https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU)

**Comment by tyler274** [comment] 2020-11-13 00:55
Only freezes on my non main monitors, fullscreening works fine on the main monitor.

**Comment by Jules-A** [comment] 2020-11-13 04:19
> Only freezes on my non main monitors, fullscreening works fine on the main monitor.

What about when you only have 1 monitor connected?

**Comment by PleaseFixThis1** [comment] 2020-11-28 14:30
RX 580
144hz monitor
no freesync
same issue

**Comment by PleaseFixThis1** [comment] 2020-11-28 14:34
**!FIXED!:** Run with mpvnet.exe instead of mpv.exe!

**Comment by lextra2** [comment] 2020-11-28 19:30
> 
> 
> **!FIXED!:** Run with mpvnet.exe instead of mpv.exe!

no thanks

**Comment by JensDA** [comment] 2020-12-15 15:49
I've found this in the nvidia driver's readme, could it be related?

> Vulkan applications crash when entering or leaving fullscreen, or when resized
> 
> Resizing a Vulkan application generates events that trigger an out-of-date swapchain. Fullscreen Vulkan applications are optimized for performance by the driver. This optimization also generates events that trigger an out-of-date swapchain upon entering or leaving fullscreen mode. This is commonly encountered when using the alt-tab key combination, for example. Applications that do not properly respond to the VK_ERROR_OUT_OF_DATE_KHR return code may not function properly when these events occur. The expected behavior is documented in section 30.8 of the Vulkan specification.

**Comment by haasn** [comment] 2020-12-15 16:39
Unlikely. We respect those events.

**Comment by Jules-A** [comment] 2021-04-05 05:56
This is partially fixed in the latest Shinchiro build with libplacebo v3.120.0. It is now able to play a file in fullscreen with working controls BUT it's dropping and delaying a tonne of frames, it's syncing to ~66hz instead of my monitor's 75hz... When launching the file it goes in and out of fullscreen 3 times in the first few seconds. It still does the same as thing as previous libplacebo versions when launching just the program without a video file.

Log (with current settings, haven't tested default): 
[output.txt](https://github.com/mpv-player/mpv/files/6256572/output.txt)

**Comment by haasn** [comment] 2021-04-05 11:13
Try with `--vulkan-async-transfer=no`? Testing recent-ish versions of AMD's official driver on Linux, I'm having massive issues with that option enabled. (Seems to be a regression, too)

**Comment by Maikurosofuto** [comment] 2021-04-05 11:24
**Update:** On Sep 19, 2020, I mentioned that it was impossible to use Vulkan API in full screen, since that day I never used Vulkan again, but a few months ago (Dec 29, 2020) I bought another GPU and managed to use Vulkan without major issues. I am not sure if it was an update that fixed it or just a type of incompatibility with my previous GPU or driver, but although it is apparently functional it is impossible to share the media through Discord or record it with programs like OBS, in both cases the video appears to be frozen in the recording with the audio playing, while the media itself still plays normally. 

My previous GPU was a RX 5700 XT, i'm currently using a RTX 3070.

**Comment by Jules-A** [comment] 2021-04-05 11:47
> Just to rule this out, try with `--vulkan-async-transfer=no`? Testing recent-ish versions of AMD's official driver on Linux, I'm having massive issues with that option enabled. (Seems to be a regression, too)

Previously I tested that without any luck, will try it again in a bit but I'm on Windows using the latest driver so might be a separate issue.

**Comment by aufkrawall** [comment] 2021-04-05 14:28
It indeed works with latest mpv Windows build and AMD GPU, playback is fine for me in fullscreen.

**Comment by Jules-A** [comment] 2021-04-05 16:43
> It indeed works with latest mpv Windows build and AMD GPU, playback is fine for me in fullscreen.

With what settings? It seems to play fine without interpolation but that's just because it's doing a lot less work which just hides the issue.

**Comment by lextra2** [comment] 2021-04-05 18:30
Works on my machine.
RX 5700, 21.3.1 WHQL, W10 Pro 19042.867, newest shinchiro build
https://drive.google.com/file/d/1Orcc1vP5i6FEQM0hQS4BxgNajXg2Dj44

**Comment by Jules-A** [comment] 2021-04-05 19:13
> Works on my machine.

What about when you just open MPV app without media content? 

I guess the lagg with Vulkan fullscreen + interpolation is out of scope of this bug but it would be nice if you could test it too 
```
tscale=oversample
video-sync=display-resample
interpolation
```

**Comment by lextra2** [comment] 2021-04-05 21:00
> > Works on my machine.
> 
> What about when you just open MPV app without media content?
> 
> I guess the lagg with Vulkan fullscreen + interpolation is out of scope of this bug but it would be nice if you could test it too
> 
> ```
> tscale=oversample
> video-sync=display-resample
> interpolation
> ```

https://drive.google.com/file/d/1XMsbfBxFkmdiiFWZlKBaIafAmp3Ph_Nz
Like I said, works on my machine.

**Comment by adisib** [comment] 2021-04-05 21:49
This stopped being an issue for me after updating to the 21.3.1 Windows AMD driver (on an RX 570). It works perfectly fine other than opening fullscreen being slightly slow and causing the following error message to be printed:
`[vo/gpu/vulkan/libplacebo] Failed presenting to queue 000001f4f184c508: VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT`

**Comment by haasn** [comment] 2021-04-06 00:53
@adisib That is a severe AMD driver bug. It violates the spec on two counts:

1. We do not enable `VK_EXT_full_screen_exclude`.
2. Even had we enabled it, that return value is only permitted when using `VK_FULL_SCREEN_EXCLUSIVE_APPLICATION_CONTROLLED_EXT`, which is not the default behavior.

**Comment by Jules-A** [comment] 2021-04-06 12:03
> Like I said, works on my machine.

You didn't test opening the MPV app without any content in that vid (it causes the same issue for me as previously but playing content works).

Maybe it's an issue for me because I have a 75hz monitor, technically I'm still getting over 60fps. Guess I will test setting my monitor to 60hz later.

>This stopped being an issue for me after updating to the 21.3.1 Windows AMD driver

That driver didn't change anything, it was the update to libplacebo v3.120.0. I've been using 21.3.1 and it wasn't until the libplacebo update in Shinchiro's build that this issue was partially fixed.

**Comment by lextra2** [comment] 2021-04-06 14:10
> You didn't test opening the MPV app without any content in that vid (it causes the same issue for me as previously but playing content works).

And how exactly do you want me to test performance without a video playing?
Here is another video. Again, works on my machine.
This time with 2560x1440@120Hz instead of 3840x2160@60Hz.

https://drive.google.com/file/d/18CONx9MiA0AwoTScZZmDuzVbPl8oUDwU

**Comment by lextra2** [comment] 2021-04-06 14:33
@haasn @adisib 
[I've reported the issue to AMD](https://community.amd.com/t5/graphics/vulkan-spec-violation-vk-error-full-screen-exclusive-mode-lost/td-p/462283)
Will probably take over 12 Months to get it fixed though.

**Comment by lextra2** [comment] 2021-04-07 15:51
https://github.com/doitsujin/dxvk/issues/1928#issuecomment-779521471
interesting read. most likely related to this issue.

**Comment by Jules-A** [comment] 2021-04-07 16:24
> [doitsujin/dxvk#1928 (comment)](https://github.com/doitsujin/dxvk/issues/1928#issuecomment-779521471)
> interesting read. most likely related to this issue.

Come to think about it I don't think anyone has reported seeing this bug on Linux (except for a guy using Nvidia). I'm installing a preview cumulative update right now that has a few fixes that could be related so here goes :P 

I don't recall DXVK capping to 60fps though, whatever they are doing it's working around this issue. I have had problems in the past with Vulkan apps being limited to 60fps though in fullscreen so that's not new.

**Comment by lextra2** [comment] 2021-04-07 16:32
I remember having the 60Hz issue in almost all exclusive fullscreen games, which is exactly why I've deleted all but 2 resolutions from my EDID.

**Comment by Hrxn** [comment] 2021-04-07 23:13
@lextra2 

By CRU, you mean this CRU? -> `https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU`

**Comment by lextra2** [comment] 2021-04-08 00:21
> @lextra2
> 
> By CRU, you mean this CRU? -> `https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU`

Yes.

**Comment by Jules-A** [comment] 2021-04-17 13:44
@haasn Dolphin just merged a workaround for the bug (linked above), what's your opinion on that if you don't mind?

**Comment by haasn** [comment] 2021-04-17 15:31
@Jules-A I'm not entirely sure what the work-around is doing here. Do they just treat that result as if it were `VK_SUCCESS`? (Which is what the code+comment seems to be implying?) I would expect it to make more sense to treat that error as `VK_ERROR_OUT_OF_DATE_KHR`.

Overall I'm more inclined to work around it by explicitly disabling exclusive full screen support, since I'm not sure why full screen exclusive mode makes any sense in the context of mpv/libplacebo.

**Comment by Jules-A** [comment] 2021-04-17 20:08
> @Jules-A I'm not entirely sure what the work-around is doing here. 

I didn't quite understand what it did from the comments which is why I was asking about it in-case something similar could be done for MPV.
> Overall I'm more inclined to work around it by explicitly disabling exclusive full screen support, since I'm not sure why full screen exclusive mode makes any sense in the context of mpv/libplacebo. (If anything, disabling full screen exclusive mode ought to make going in and out of fullscreen smoother)
That said, though, full screen exclusive might be required for HDR output?

I'm not sure of the advantages but I was hoping maybe it would offer better Vsync timing (currently it's really poor in comparison to DX). I can imagine there are quite a few people using dedicated media PCs who don't care much about leaving the app. If there is some advantages then an option to run in exclusive could be useful but I don't think it should be default. I don't have a HDR monitor to test unfortunately.

**Comment by haasn** [comment] 2021-04-17 20:12
Lack of vsync timing is [ awell-known vulkan issue](https://github.com/KhronosGroup/Vulkan-Docs/issues/370) that is still unresolved 5 years after Vulkan's release. Fullscreen exclusive mode does not help here.

**Comment by Jules-A** [comment] 2021-04-17 20:40
> Lack of vsync timing is [ awell-known vulkan issue](https://github.com/KhronosGroup/Vulkan-Docs/issues/370) that is still unresolved 5 years after Vulkan's release. Fullscreen exclusive mode does not help here.

Oh thanks but wow... is it still not solved with 1.2.175 which implemented VK_KHR_video_queue (although I don't think AMD supports that yet anyway) ?

**Comment by soredake** [comment] 2021-05-15 09:33
> Overall I'm more inclined to work around it by explicitly disabling exclusive full screen support, since I'm not sure why full screen exclusive mode makes any sense in the context of mpv/libplacebo. (If anything, disabling full screen exclusive mode ought to make going in and out of fullscreen smoother)

@haasn can mpv have similar to d3d11 option(d3d11-exclusive-fs) for vulkan?

**Comment by haasn** [comment] 2021-05-15 10:18
> @haasn can mpv have similar to d3d11 option(d3d11-exclusive-fs) for vulkan?

[VK_EXT_full_screen_exclusive](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_EXT_full_screen_exclusive) seems to be the right extension to poke at for this.

**Comment by hooke007** [comment] 2021-11-08 15:03
My amd gpu: pro 5600m
Unfortunately the latest driver for me is ver.21.11.1

Only set `vulkan-swap-mode=immediate` could avoid freezing when entering fullscreen.

**Comment by haasn** [comment] 2022-10-16 06:44
@aufkrawall @hooke007 can you help test https://code.videolan.org/videolan/libplacebo/-/merge_requests/308 please?

**Comment by aufkrawall** [comment] 2022-10-16 08:42
I unfortunately don't have a test system with Radeon at my disposal. I'd test Nvidia and Intel though if there were a test build.

**Closed** 2022-10-19 15:31 UTC
Labels: os:win, vo:gpu:vulkan

**Comment by Jules-A** [comment] 2022-10-19 19:13
@haasn Would it be possible to get an option to force enable it?

**Comment by haasn** [comment] 2022-10-21 09:41
> @haasn Would it be possible to get an option to force enable it?

What do you need it for? Can you explain the use case?

**Comment by Jules-A** [comment] 2022-10-21 10:07
> > @haasn Would it be possible to get an option to force enable it?
> What do you need it for? Can you explain the use case?

I don't have a "need" for it but as you suggested earlier it might be needed for HDR. It might provide some benefits now or in the future but without the option for users to even test it without compiling themselves I have a feeling we'll never know.
Also, this bug was already fixed for me a year and half ago but only if content is provided (it still occurred when opening just the exe which I never did).
That said, Vulkan still performs worse for me than DX11 and gpu-next still has bugs with shaders so I'm not even using Vulkan :/

**Comment by haasn** [comment] 2022-10-21 10:12
> I don't have a "need" for it but as you suggested earlier it might be needed for HDR.

From testing it appears that this is not the case, and from discussion with other developers it seems that fullscreen exclusive mode in general is something that's on its way out / considered deprecated.
