### ISSUE TITLE
Is the current mpv supports RTX HDR?

### ISSUE THREAD

**Issue by AyaseMitsukasa** [mpv-player/mpv#13761] opened 2024-03-24 10:32 UTC
If yes, please tell me how to configure it
If no, please tell me will it be added later and when will it be added

**Comment by CounterPillow** [comment] 2024-03-24 10:35
Duplicate of https://github.com/mpv-player/mpv/issues/13352

**Comment by AyaseMitsukasa** [comment] 2024-03-24 11:15
> Duplicate of #13352

I have tried inverse-tone-mapping but seems no effect at all
So is it currently not supported?

**Comment by CounterPillow** [comment] 2024-03-24 12:11
no

**Comment by AyaseMitsukasa** [comment] 2024-03-24 12:12
> no

Ok, thanks for the reply anyway

**Closed** 2024-04-14 19:43 UTC
Labels: meta:question
