### ISSUE TITLE
Fullscreen video not working on wayland with fractional scaling in gnome

### ISSUE THREAD

**Issue by semkath** [mpv-player/mpv#5342] opened 2018-01-02 19:34 UTC
### mpv version and platform

```
$ mpv -V
mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Fri Dec 15 18:31:42 CET 2017
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4.1
```

### Reproduction steps

When I run the following command to start a video from the command line and then try to switch to fullscreen (with the f shortcut), only the top left quarter of the screen gets filled. I'm running the wayland opengl backend because otherwise HW acceleration (VAAPI) doesn't work with because it's falling back to rendering to XWayland.

`mpv --vo=opengl --opengl-backend=wayland bbb_sunflower_2160p_60fps_normal.mp4`

![mpv_wayland_hidpi](https://user-images.githubusercontent.com/309355/34496627-791e305a-effa-11e7-8f20-3d7dd7bd7acf.png)

This is on a system with dual screen 4k monitors, running **Gnome Shell**, version 3.26 on **Wayland**. This version included an experimental feature to achieve fractional scaling (something like 150% or 175%). For instructions on how to activate this, see [here](http://www.omgubuntu.co.uk/2017/09/enable-fractional-scaling-gnome-linux). The issue disappears when I disable the fractional scaling in the Settings. Since the fractional scaling support in Gnome is relatively new it probably was never tested with mpv.

### Expected behavior

The video should go fullscreen

### Actual behavior

The video doesn't go fullscreen and only covers the top most left area of the screen.

### Log file

[diag.txt](https://github.com/mpv-player/mpv/files/1598490/diag.txt)

P.S.: I realize this has a lof of checkboxes for edge case behaviour (Wayland, Fractional Scaling, HiDPI Monitors, HW Acceleration) so I want to thank in advance the person that finds time to work on this 🙂

**Comment by atomnuker** [comment] 2018-01-06 12:38
Don't use this feature unless you like to see blurry crap video. For e.g. 1.5x scaling it asks mpv to render 3x the normal scale and then the compositor does a crap downscale by itself by 2x to get 1.5x final scaling. It wastes GPU usage and it makes things look like crap. It makes the scaling algorithms implemented pointless as it just does a bilinear scale on the final image. Won't fix.
Suggestion: use 2x scaling and decrease the font scaling if things are too large or use 1x scaling and increase font scaling if things are too small.

**Closed by atomnuker** 2018-01-06 12:38 UTC
Labels: wayland, wontfix

**Comment by semkath** [comment] 2018-01-06 15:33
Can I take this response to mean that you think that fractional scaling is a bad idea in general? There is a lot of support for it:

- [KDE](https://www.youtube.com/watch?v=EDAa32W3PY0) (link to a youtube video showing the setting in KDE)
- [macOS](http://www.eizoglobal.com/support/compatibility/dpi_scaling_settings_mac_os_x/index.html) (documentation from Eizo for scaling on macOS)
- [Windows 10](https://blogs.technet.microsoft.com/askcore/2015/12/08/display-scaling-in-windows-10/) (see section titled "Unified and extended scaling system")

There is also documentation for different screen sizes and scaling factors [here](https://wiki.gnome.org/action/edit/Projects/GnomeShell/ScaleFactorTests) that shows that non-integer scaling is not always feasable. For example for a 27" with 3840x2160 resolution both 1x and 2x scaling leads to unfortunate issues. While stuff like font size is easy enough to fix, I don't see that working for stuff like window decorations, task bars, dialogue boxes and so on (at least is doesn't work well on my screens, either everything is too small or too big) :(

Now granted, the presence of fractional scaling in general as part of the OS or the DE doesn't mean that mpv absolutely has to account for it (as you said, first scaling up 3x and then scaling down 2x leads to bluirry video at best). But I wonder if there is another solution. Might it be possible to exempt video playback from the OS scaling and rely on its (probably vastly superior) video scaling algorithms instead of applying the default OS scaling?

**Comment by wm4** [comment] 2018-01-06 15:48
The issue is with double scaling, not with fractional scaling in general.

I don't know if Wayland made yet another mistake and made the DPI scaling an integer, or if it's about Gnome.

**Comment by Argon-** [comment] 2018-01-06 15:52
> Might it be possible to exempt video playback from the OS scaling and rely on its (probably vastly superior) video scaling algorithms instead of applying the default OS scaling?

Mpv can do this for OSX: https://mpv.io/manual/master/#options-no-hidpi-window-scale
Maybe it can be extended.

**Comment by atomnuker** [comment] 2018-01-06 17:17
If you want proper fractional scaling ask the wayland people to accept a v3 of the wl_output protocol which gives fractional scale to clients. And adds a new call (or better yet an event) to tell the compositor what scale the output surface is at so it won't do its own scaling.
That does mean they'd have to admit they were wrong to think an integer is going to be good enough. And it does mean compositors will need to support that new protocol. Which in the case of gnome might be before its even stable and in the case of kde it'll be NEVER because they're lazy and have ice age long release periods.

**Comment by semkath** [comment] 2018-01-06 17:35
Thanks for the hints! I understand that fractional scaling on wayland might be a bit of an issue (I've been using 1.5x scaling since Gnome 3.26 was released, it was a definite step up as far as GUI experience is concerned). I will have to read the wayland protocol specification for a proper solution, I guess :)

However, fractional scaling (however it is achieved) is probably here to stay and the way it is implemented right now produces some issues for mpv, as far as I can see. I don't have a KDE or macOS available for testing but will try it on Windows 10 with 1.5x scaling.

The suggestion of ignoring any scaling by the OS and just render the video at its native (or scaled, depending on the users choices) resolution sound like a reasonable approach to me but I'm unsure of its feasability.

**Comment by atomnuker** [comment] 2018-01-06 18:06
You can't have that either, you'll need to change the protocols to allow that. And if you're changing the protocols you might as well do it properly and implement it in the way I suggested.
Best suggestion would be to play with the font scale and decorations and disable fractional scaling.

**Comment by semkath** [comment] 2018-01-07 11:54
Concerning HiDPI scaling on other OS: I tested mpv on Windows 10 with 1.5x scaling and didn't have any issues. This suggests that the problem lies with the the graphical envorinment in Linux (as was already mentioned, Wayland is maybe at fault here).

Just to make sue that I understand the issue correctly then: You're saying that the problem lies with the wayland protocol insofar as it only allows integer scaling. Given that constraint gnome decided to go for the "multiply by 2, divide by 3" approach which leads to unfortunate scaling issues on video playback (window decorations, fonts, icons, etc should be fine as long as they're vector based?).

At least Windows 10 doesn't have this problem (I'm unsure what exactly they do to achieve 1.5x scaling), don't know about macOS though. Any hints on who to talk to about this issue?

Oh and one final point: Even if fractional scaling would work in wayland, woudn't the same issue still present itself? Then just by scaling up the video 1.5x and not 2x up and 3x down like its currently implenented. That should still lead to scaling artifacts, shoudn't it? So disabling the OS scaling for video is still something that would be useful (like mpv does for macOS).
