### ISSUE TITLE
webm/vp9 decoder framedrop

### ISSUE THREAD

**Issue by tomty89** [mpv-player/mpv#1842] opened 2015-04-20 10:12 UTC
When I play webm/vp9 files downloaded with youtube-dl from youtube, the status line shows that there are consistently frames dropping by the decoder. It happens no matter the webm file contains audio stream or not.

**Comment by wm4** [comment] 2015-04-20 10:18
Duplicate of #1825.

**Closed by wm4** 2015-04-20 10:18 UTC
