### ISSUE TITLE
--loop doesn't work when --keep-open is also specified

### ISSUE THREAD

**Issue by proxypoke** [mpv-player/mpv#1458] opened 2015-01-12 04:57 UTC
When mpv is started with *--loop inf* or *--loop n* (n > 1), and *--keep-open* is also specified, the playback pauses after the first iteration. I suspect this is because *--keep-open* simply pauses at the end of playback.

I think the correct and expected behavior would be to pause at the end of the last iteration.

My mpv version is 0.3.10.

**Comment by wm4** [comment] 2015-01-12 04:59
>My mpv version is 0.3.10.

This is ancient, not supported, and the issue is fixed in newer mpv version. Stop using Ubuntu.

**Comment by wm4** [comment] 2015-01-12 04:59
PS: this may be of help: http://mpv.io/installation/

**Closed by wm4** 2015-01-12 04:59 UTC

**Comment by proxypoke** [comment] 2015-01-12 05:10
Oh, I was not aware I was using an old version. Never mind, then. Thanks for the quick reply and the great work going into mpv. Have a nice day/night.

P.S.: I'm using Gentoo, guess they fucked that one up.

**Comment by wm4** [comment] 2015-01-12 05:17
>P.S.: I'm using Gentoo, guess they fucked that one up.

Ah, I assumed it was Ubuntu, because they also package this old version. Gentoo has newer packages; they're just hardmasked.
