### ISSUE TITLE
Refuses to play youtube video that returns edl in a playlist

### ISSUE THREAD

**Issue by palindromos** [mpv-player/mpv#6130] opened 2018-09-17 13:53 UTC
### mpv version and platform
Debian, mpv 0.29.0

### Reproduction steps

Run the following command:
```
mpv 'https://www.youtube.com/watch?list=PLAIcZs9N4173mGoMZdzESghSW7qKYgwo4' --playlist-start=74
```

### Expected behavior

mpv plays video 74 in the playlist

### Actual behavior

mpv skips to video 75 with the error:
```
Refusing to load potentially unsafe URL from a playlist.
Use --playlist=file or the --load-unsafe-playlists option to load it anyway.
```

## Log file

https://paste.debian.net/1044719/

**Comment by sfan5** [comment] 2018-09-26 20:00
duplicate of #4541

**Comment by palindromos** [comment] 2018-09-26 20:35
I believe this is not a duplicate unless I'm doing not understanding the patch correctly: It's mpv 2.9 which is supposed to contain the fix and `dash` is listed in `demuxer-lavf-list`, yet the video still doesn't play.

**Comment by sfan5** [comment] 2018-09-26 20:45
works fine here despite using EDL instead of native DASH support (?!)
do you have a logfile?

**Comment by palindromos** [comment] 2018-09-26 21:13
Log file with `all=debug`: https://paste.debian.net/1044719/

**Comment by sfan5** [comment] 2018-09-26 21:36
Note that you need `--script-opts=ytdl_hook-use_manifests=yes` to make ytdl_hook attempt to load DASH using the native demuxer.
Not sure about the reported issue, I'll just keep this open.

**Closed** 2018-09-26 21:45 UTC
