### ISSUE TITLE
High CPU usage using video-sync=display-resample

### ISSUE THREAD

**Issue by Xenphor** [mpv-player/mpv#5674] opened 2018-03-23 03:46 UTC
### mpv version and platform

mpv 0.28.0-398-gfbcf2bf207

Windows 7 64bit SP1
8700k
Nvidia 1050 ti driver 391.01

### Reproduction steps

Play any video

### Expected behavior

Low cpu usage

### Actual behavior

CPU usage when using video-sync=display-resample is quite high, even when using hardware decoding. One core seems to be pinned at max frequency, 4.4ghz. I believe I may be having a similar problem as https://github.com/mpv-player/mpv/issues/4060. 

Specs are 8700k with a 1050 ti. 

I tried turning threaded optimizations off in the control panel as the solution but it did not help.

### Log file
https://pastebin.com/dwNK1fY6

**Comment by lachs0r** [comment] 2018-03-23 04:21
Are you enforcing a certain vsync mode in the NVIDIA control panel? Do not use the adaptive modes with mpv.

**Comment by dnmTX** [comment] 2018-03-23 04:44
I'm actually using "adaptive mode"(NVCP)+ d3d11(mpv)+video-sync=display-resample and my CPU usage doesn't get higher then 2.4%.I can see higher CPU usage only when codec is not supported like playing .avi files and mpv is using software for decoding but nowhere near OP's claims.Pretty sure the problem is not with MPV but in OP's system somewhere.

**Comment by Xenphor** [comment] 2018-03-23 05:10
Okay I tried d3d11 and get low cpu usage. I guess the problem is with opengl and vulkan. I notice that I am not able to use dxva2 with either of those, only dxva2-copy or nvdec. With d3d11 it will work with just dxva2.

**Comment by dnmTX** [comment] 2018-03-23 05:26
Why would you use dxva2? Use d3d11va instead.
vo=gpu
gpu-api=d3d11
gpu-context=d3d11
hwdec=d3d11va

**Comment by Xenphor** [comment] 2018-03-23 05:28
The manual says it's for windows 8+ only

**Comment by dnmTX** [comment] 2018-03-23 05:30
I see(i missed to check your OS).Yeah i guess you don't have too much of a choice.

**Comment by dnmTX** [comment] 2018-03-23 05:44
@Xenphor  you can close this if you want.In my opinion the issue was resolved.

**Comment by Xenphor** [comment] 2018-03-23 05:46
Well I would actually like to use vulkan because with display-resample it's the only way to not get screen tearing in window mode without using a compositor.

**Comment by Dudemanguy** [comment] 2022-01-18 18:58
Appears to be a driver issue and the issue is pretty old so closing.

**Closed by Dudemanguy** 2022-01-18 18:58 UTC
Labels: os:win, core, vo:gpu:opengl, core:video
