### ISSUE TITLE
Distorted subtitles in full screen while using vo=dmabuf-wayland

### ISSUE THREAD

**Issue by meelten** [mpv-player/mpv#13961] opened 2024-04-21 17:32 UTC
### Important Information

Provide following Information:
- mpv version: **0.38.0**
- Linux Distribution and Version: **Arch Linux (with KDE Plasma)**
- Source of the mpv binary: **official distro repository**
- Window Manager and version: **Kwin 6.0.4**
- GPU model, driver and version: **Intel HD520, Mesa 24.0.5**
- Possible screenshot or video of visual glitches:
![wrong](https://github.com/mpv-player/mpv/assets/37178862/ab985d2d-0cdc-498b-97f6-5308342bec5a)

### Reproduction steps

On Linux w/ Wayland play video file with subtitles (tried .ass and .srt) with `--vo=dmabuf-wayland` parameter. Enter full screen, don't move your mouse nor have any OSC elements displayed (like console). Wait for subtitles to appear.

### Expected behavior

Subtitles should be displayed correctly.

### Actual behavior

Subtitles are distorted and unreadable as seen on the screenshot above. Happens only when no OSC is present on screen, meaning subtitles are temporarily corrected instantaneously whenever mouse is moved or key pressed. Does not happen at all when windowed.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/15052884/output.txt)

**Comment by Dudemanguy** [comment] 2024-04-21 18:00
I'm not able to reproduce. Do you have a sample file?

**Comment by meelten** [comment] 2024-04-21 19:30
> I'm not able to reproduce. Do you have a sample file?

I tried various video and subtitle files from different sources and problem occurs with all of them for me, so files certainly are not to blame here but something with my configuration.

Do you use Plasma 6 as well?

**Comment by Dudemanguy** [comment] 2024-04-21 19:46
No, sway but weston works for me as well.

**Comment by llyyr** [comment] 2024-04-22 05:06
Can you try running Kwin without direct scan out? Idk how to achieve that but running with a software cursor should implicitly disable direct scan out. Set `KWIN_FORCE_SW_CURSOR=1` in your environment before launching Kwin

**Comment by Anty-Matter** [comment] 2024-04-22 20:21
Can confirm, on fedora 40/plasma 6.

Things I noticed on two devices, one intel the other ryzen:

- Happens more often at odds horizontal resolutions, as in resolution that end on a odd number.
- Full screen at a 1080p display is safe, but full screen at 768p is not.
- OSD elements are affected.
- The distortion only appears on the first 'sample' text, the subsequent text is rendered properly. If there's a pause on dialogue and there's no text for a few seconds the next text on screen will be affected.

**Comment by Dudemanguy** [comment] 2024-04-22 21:53
Can either of you confirm if it happens on another compositor like mutter or weston? I don't have a 768p screen.

**Comment by Anty-Matter** [comment] 2024-04-22 22:33
Gnome46/Mutter seems unaffected. And to clarify it also happens on 1080p displays at lower window sizes, its just that 1080p at fullscreen is safe, tested with autofit=1335.

**Comment by Dudemanguy** [comment] 2024-04-22 22:54
Going to assume this is a plasma bug in that case.

**Comment by meelten** [comment] 2024-04-22 23:54
> `KWIN_FORCE_SW_CURSOR=1`
That didn't change anything.

And it is in fact 768p screen.

**Comment by kasper93** [comment] 2024-04-23 00:14
@meelten: What if you try without aligning stride to 16?

``` diff
diff --git a/video/out/vo_dmabuf_wayland.c b/video/out/vo_dmabuf_wayland.c
index 35a4dac464..f34762c78e 100644
--- a/video/out/vo_dmabuf_wayland.c
+++ b/video/out/vo_dmabuf_wayland.c
@@ -455,7 +455,7 @@ static void create_shm_pool(struct vo *vo)
     struct vo_wayland_state *wl = vo->wl;
     struct priv *p = vo->priv;

-    int stride = MP_ALIGN_UP(vo->dwidth * 4, 16);
+    int stride = vo->dwidth * 4;
     size_t size = vo->dheight * stride;
     int fd = vo_wayland_allocate_memfd(vo, size);
     if (fd < 0)
```

**Comment by Anty-Matter** [comment] 2024-04-23 02:14
> -    int stride = MP_ALIGN_UP(vo->dwidth * 4, 16);
> +    int stride = vo->dwidth * 4;

Don't really understand what this change means, but it did fix the distortion or at the very least can't reproduce it anymore.

**Comment by Dudemanguy** [comment] 2024-04-23 03:35
That align was cargoculted from wlshm. Does `--vo=wlshm` have the same problem by any chance?

**Comment by Anty-Matter** [comment] 2024-04-23 03:44
With --vo=wlshm I can't find any distortion during playback at any resolution. Curiously, a very similar distortion is visible in both the text and the video while resizing the window with the mouse.

**Comment by Dudemanguy** [comment] 2024-04-23 04:03
Just a wild guess, but does anything change if we use the actual correct number for the align?

```
diff --git a/video/out/vo_dmabuf_wayland.c b/video/out/vo_dmabuf_wayland.c
index be8b0f1272..ae2cbab940 100644
--- a/video/out/vo_dmabuf_wayland.c
+++ b/video/out/vo_dmabuf_wayland.c
@@ -455,7 +455,7 @@ static void create_shm_pool(struct vo *vo)
     struct vo_wayland_state *wl = vo->wl;
     struct priv *p = vo->priv;
 
-    int stride = MP_ALIGN_UP(vo->dwidth * 4, 16);
+    int stride = MP_ALIGN_UP(vo->dwidth * 4, MP_IMAGE_BYTE_ALIGN);
     size_t size = vo->dheight * stride;
     int fd = vo_wayland_allocate_memfd(vo, size);
     if (fd < 0)
diff --git a/video/out/vo_wlshm.c b/video/out/vo_wlshm.c
index 0b63426a23..a0d5ba1dd4 100644
--- a/video/out/vo_wlshm.c
+++ b/video/out/vo_wlshm.c
@@ -85,7 +85,7 @@ static struct buffer *buffer_create(struct vo *vo, int width, int height)
     uint8_t *data;
     struct buffer *buf;
 
-    stride = MP_ALIGN_UP(width * 4, 16);
+    stride = MP_ALIGN_UP(width * 4, MP_IMAGE_BYTE_ALIGN);
     size = height * stride;
     fd = vo_wayland_allocate_memfd(vo, size);
     if (fd < 0)
```

If not, we could try removing it all together. `dmabuf-wayland` shouldn't need it since AFAIK, the align is for use with swscale (which it doesn't use).

**Comment by meelten** [comment] 2024-04-23 10:17
Do I need re-compile to check this?

Also confirm that there is no issue with wlshm.

**Comment by kasper93** [comment] 2024-04-23 12:41
> Dudemanguy removed the down-upstream:plasma label

Why? I don't see anything wrong in mpv. kwin is ignoring stride set by `wl_shm_pool_create_buffer`, there is nothing wrong in mpv. Indeed stride could be set to `w*4` to avoid this bug in kwin, but it should be reported and fixed upstream anyway.

**Comment by Dudemanguy** [comment] 2024-04-23 13:31
I'm not sure if it makes sense to align the stride in the first place for shm buffers though.

**Comment by kasper93** [comment] 2024-04-23 14:26
Fair, doesn't change the fact it is upstream bug and we are wasting resources by even diagnosing it.

**Comment by Dudemanguy** [comment] 2024-04-23 15:35
Yeah I guess it would be best if someone reported this to kwin regardless.

**Comment by llyyr** [comment] 2024-10-01 14:43
fixed by https://invent.kde.org/plasma/kwin/-/merge_requests/6267

**Closed** 2024-10-01 14:46 UTC
Labels: os:linux, vo:dmabuf-wayland
