### ISSUE TITLE
Separate secondary subtitle font (not fallback)

### ISSUE THREAD

**Issue by svenper** [mpv-player/mpv#7688] opened 2020-05-06 14:28 UTC
### Expected behavior of the wanted feature

Setting fonts and sizes separately for the secondary font. Currently it can fallback but fontconfig gets messy quickly, and you might not want to fallback at all if the main font is inappropriate (think punctuation and numbers shared across the world).

`secondary-sub-font` 
`secondary-sub-font-size` 
etc.

### Alternative behavior of the wanted feature

More elegant perhaps would be setting the secondary font by language. Possibly some web browser's code could be inpirational here. This could be inherited automatically from fontconfig configured something like:

```xml
<match>
  <test name="lang" compare="contains"><string>el</string></test>
  <edit name="family" mode="prepend" binding="strong">
    <string>Gentium Plus</string>
  </edit>
</match>
```

`sub-font-en`
`sub-font-ko`
`sub-font-ar`
etc.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/4587310/output.txt)

**Comment by wm4** [comment] 2020-05-07 10:26
I'm rather hesistant to duplicate all options for the secondary subtitle display. Maybe there will be a way to do this in a few months to a few years.

**Comment by Akemi** [comment] 2021-05-08 13:16
duplicate of #6441

**Closed by Akemi** 2021-05-08 13:16 UTC
Labels: core:option-param-conf, meta:feature-request
