### ISSUE TITLE
MPV 0.37.0 wipes a[v] time line with Exiting ... on Standard out

### ISSUE THREAD

**Issue by edAT70** [mpv-player/mpv#13417] opened 2024-02-06 00:13 UTC
MPV 0.37.0 wipes a[v] time line with Exiting ... on Standard out
mpv on my 6 dfferent systems same problem.
HAPPENS on audio or video files. 
Happens on tty or xterminal; not using mpv front end.
Changed from 0.36 to 0.37 [revered to 0.36 on main encode systems] 
When i need to find edit points on media, use mpv to play to time then "q" end.
Here is an av line: AV: 00:00:09 / 00:00:10 (99%)
Now the 0.37 outputs over AV line "Exiting... (Quit)"
Look at the git "ChangeLog" new option "--term-remaining-playtime "
did not make a difference YES/NO  on above
Did a clean  install[xterm icewm only] of Archlinux on a laptop,
 same problem.1/30/2024 Using Archlinux/artixlinux distros.
Archlinux  said to report upline, including mpv debug log. 
[BADav.txt](https://github.com/mpv-player/mpv/files/14173136/BADav.txt)

**Comment by Akemi** [comment] 2024-02-06 00:15
duplicate of #13416

**Closed by Akemi** 2024-02-06 00:15 UTC
Labels: os:linux
