### ISSUE TITLE
mac/vo_gpu_next: --target-colorspace-hint crash

### ISSUE THREAD

**Issue by m154k1** [mpv-player/mpv#13766] opened 2024-03-24 16:58 UTC
### Important Information

Provide following Information:
- mpv version
```
mpv v0.37.0-666-g77e1cfb85f-dirty Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Mar 24 2024 18:16:31
libplacebo version: v7.349.0 (v6.338.0-120-g7b294350)
FFmpeg version: git-2024-03-24-ac21582
FFmpeg library versions:
   libavutil       59.6.100
   libavcodec      61.2.100
   libavformat     61.0.100
   libswscale      8.0.100
   libavfilter     10.0.100
   libswresample   5.0.100
```
- macOS Version: 14.4
- Source of the mpv binary or bundle: git master
- If known which version of mpv introduced the problem: -
- Possible screenshot or video of visual glitches: N/A

### Reproduction steps
Run mpv with `--vo=gpu-next --target-colorspace-hint` with any HDR video. Sometimes it crashes at the start of the file but most likely it'll crash at the end.

```
mpv --no-config --vo=gpu-next --target-colorspace-hint <file>
```

### Expected behavior
No crashes.

### Actual behavior
mpv crashes.

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/14736161/log.txt)
[backtrace.txt](https://github.com/mpv-player/mpv/files/14736162/backtrace.txt)

### Sample files

[HDR10+ Dynamic Metadata Test 60fps](https://ff.de/hdr10plus-metadata-test/), source: https://kodi.wiki/view/Samples

**Comment by Akemi** [comment] 2024-03-24 17:18
duplicate of #12666

**Closed by Akemi** 2024-03-24 17:18 UTC
Labels: os:mac

**Comment by m154k1** [comment] 2024-03-24 17:32
Ah sorry, how could I miss that...
