### ISSUE TITLE
Next playlist image doesn't always get updated

### ISSUE THREAD

**Issue by anongit** [mpv-player/mpv#7247] opened 2019-12-12 15:40 UTC
### mpv version and platform

master (aee413d)
macOS Catalina (10.15.1)
Intel HD Graphics 4000

### Reproduction steps

```sh
#!/usr/bin/env sh

gen_image() {
    ffmpeg -f lavfi -i "color=$1:s=$2" -frames:v 1 "tmp/imgs/$2.jpg"
}

run_mpv() {
    ./build/mpv \
        --vo=libmpv \
        --video-unscaled=downscale-big  \
        --autofit-larger=90%x90% \
        --image-display-duration=inf \
        --config-dir tmp/cfg \
        "$@" \
        tmp/imgs
}

if [ ! -d tmp ]; then
    mkdir -p tmp/{imgs,cfg}

    gen_image "ff8800" "400x400"
    gen_image "88ff00" "600x600"
    gen_image "8800ff" "1200x1200"
    gen_image "0088ff" "2000x2000"

    printf 'LEFT playlist-prev\nRIGHT playlist-next' > tmp/cfg/input.conf
fi

run_mpv
run_mpv --geometry=600x600
```
Press left and right arrows.

### Expected behavior

Images change and get resized correctly.

### Actual behavior

Demonstration: https://0x0.st/zU3N.mp4 (17M)

`00:00:01.767 ` current file changes to `2000x2000.jpg`, but the image is the same
`00:00:03.433` the image gets updated when the osd shows up

`00:00:07.917` the image doesn't fit the window, there is black space around it
`00:00:09.817` I press "o" and resize happens

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/3956443/output.txt)

### Sample files

script: https://0x0.st/zU3K.sh
demo: https://0x0.st/zU3N.mp4 (17M)

### Additional info

With `--vo=gpu` doesn't happen.

It first breaks in this commit:  3b13a47
The following change "fixes" it:
```diff
diff --git a/player/loadfile.c b/player/loadfile.c
index 70fe0e42a7..60a74e1397 100644
--- a/player/loadfile.c
+++ b/player/loadfile.c
@@ -1079,7 +1079,7 @@ static void open_demux_reentrant(struct MPContext *mpctx)
     }
 
     if (!mpctx->open_active)
-        start_open(mpctx, url, mpctx->playing->stream_flags, false);
+        start_open(mpctx, url, mpctx->playing->stream_flags, true);
 
     // User abort should cancel the opener now.
     mp_cancel_set_parent(mpctx->open_cancel, mpctx->playback_abort);
```
Then it breaks the second time with: 4ad68d9
Finally `master` seemingly works okay if I change:
```diff
diff --git a/player/loadfile.c b/player/loadfile.c
index 2535e75617..707b7e9d5a 100644
--- a/player/loadfile.c
+++ b/player/loadfile.c
@@ -1101,7 +1101,7 @@ static void open_demux_reentrant(struct MPContext *mpctx)
     }
 
     if (!mpctx->open_active)
-        start_open(mpctx, url, mpctx->playing->stream_flags, false);
+        start_open(mpctx, url, mpctx->playing->stream_flags, true);
 
     // User abort should cancel the opener now.
     mp_cancel_set_parent(mpctx->open_cancel, mpctx->playback_abort);
diff --git a/player/video.c b/player/video.c
index 9dbe19cae4..8b314a4770 100644
--- a/player/video.c
+++ b/player/video.c
@@ -421,7 +421,7 @@ static int get_req_frames(struct MPContext *mpctx, bool eof)
 
     // On the first frame, output a new frame as quickly as possible.
     if (mpctx->video_pts == MP_NOPTS_VALUE)
-        return min;
+        return mpctx->opts->video_sync == VS_DEFAULT ? 1 : min;
 
     int req = vo_get_num_req_frames(mpctx->video_out);
     return MPCLAMP(req, min, MP_ARRAY_SIZE(mpctx->next_frames) - 1);
```
Or alternatively if `--video-latency-hacks` is enabled works this one:
```diff
diff --git a/player/loadfile.c b/player/loadfile.c
index 2535e75617..707b7e9d5a 100644
--- a/player/loadfile.c
+++ b/player/loadfile.c
@@ -1101,7 +1101,7 @@ static void open_demux_reentrant(struct MPContext *mpctx)
     }
 
     if (!mpctx->open_active)
-        start_open(mpctx, url, mpctx->playing->stream_flags, false);
+        start_open(mpctx, url, mpctx->playing->stream_flags, true);
 
     // User abort should cancel the opener now.
     mp_cancel_set_parent(mpctx->open_cancel, mpctx->playback_abort);
diff --git a/player/video.c b/player/video.c
index 9dbe19cae4..a87a6a12ca 100644
--- a/player/video.c
+++ b/player/video.c
@@ -1182,7 +1182,7 @@ void write_video(struct MPContext *mpctx)
     if (mpctx->video_status < STATUS_PLAYING) {
         mpctx->video_status = STATUS_READY;
         // After a seek, make sure to wait until the first frame is visible.
-        if (!opts->video_latency_hacks) {
+        if (true) {
             vo_wait_frame(vo);
             MP_VERBOSE(mpctx, "first video frame after restart shown\n");
         }
 ```
I have no idea what all this means, but I hope it's helpful.

**Comment by wm4** [comment] 2019-12-12 15:54
Can't reproduce on x11. Not inconceivable that vo_libmpv and/or the Swift code has some sort of race condition or similar.

What happens if you e.g. resize the window while the "wrong" image is displayed?

Also your test script is a bash script, not standard shell.

**Comment by anongit** [comment] 2019-12-12 15:59
> What happens if you e.g. resize the window while the "wrong" image is displayed?

It gets updated and resized to fit the window if needed.

**Comment by wm4** [comment] 2019-12-14 18:38
CC @Akemi

**Comment by Akemi** [comment] 2019-12-14 19:11
i will try to have a look at it soonish. cocoa-cb's window size switching on file switching is not completely error free in a few ways. due to the nature of the layer it could happen that the surface is stretched for a split second (mismatched aspect ratio) on file switching. i tried to counter that with an `https://github.com/mpv-player/mpv/blob/6d0f0546ee851f4106438c5b92c8d1d152937ea7/video/out/cocoa_cb_common.swift#L157` ([the layer function](https://github.com/mpv-player/mpv/blob/master/video/out/cocoa-cb/video_layer.swift#L186-L198)) in that case. that apparently doesn't work nicely either and has other side effects, eg it should also avoid those black border. anyway i was thinking of removing that anyway, since the condition to end the atomic drawing is sometimes lacks behind a bit but noticeable and Apple recommends against it now.

this might be one part of the issue. another one might be a missing force redraw on file switching, but i need to investigate a bit further.

**Comment by aerobounce** [comment] 2019-12-16 10:19
I can confirm this issue as I was thinking about opening an issue of this behavior.

My env: `10.14.6 (18G1012)` `mpv 0.30.0`

- Never experienced this with video files, but only with audio files with images embedded.
- When 'artwork / video' gets no update, just hovering the window of the app makes its state up-to-date (the state it should be at that time).
- `Hovering` I mean putting a mouse pointer onto mpv's window.

FYI.

**Comment by Akemi** [comment] 2020-01-19 19:37
i believe this issue was fixed by https://github.com/mpv-player/mpv/commit/1caa653f2d8a76f97a009cf329b9f37f2af69abb. please let me know if the issue still persists.

**Closed by Akemi** 2020-01-19 19:37 UTC
Labels: os:mac, vo:libmpv:cocoa-cb

**Comment by tonycpsu** [comment] 2020-08-08 18:39
@akemi I'm still seeing this on MacOS using the current head (bb23188) and the reproducer script above verbatim on MacOS Catalina 10.15.5.  Same behavior, where if the wrong image is displayed, a resize of the video window refreshes it to display the correct image.

**Comment by Akemi** [comment] 2020-08-09 09:37
works as expected here. are you sure you are using the correct mpv version? otherwise you might need to open a new issue.

**Comment by tonycpsu** [comment] 2020-08-09 22:57
@Akemi new issue opened as requested.
