### ISSUE TITLE
JPEG gets played as MP3

### ISSUE THREAD

**Issue by rr-** [mpv-player/mpv#3973] opened 2017-01-01 11:43 UTC
### mpv version and platform

```
mpv git-0067d1dbe (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sun Jan  1 11:58:48 CET 2017
ffmpeg library versions:
   libavutil       55.43.100
   libavcodec      57.70.100
   libavformat     57.61.100
   libswscale      4.3.101
   libavfilter     6.68.100
   libswresample   2.4.100
ffmpeg version: N-82927-gc6c888e996
```

### Sample files

https://0x0.st/pVG.jpg (**slighly NSFW** but it's the only sample I had)

### Reproduction steps

`mpv 1468861116228.jpg --loop=yes`

### Expected behavior

I should see a muscular girl in the JPEG file

### Actual behavior

I hear industrial music instead

### Workaround

Passing `--demuxer-lavf-hacks=no` seems to mitigate the issue (as pointed out by tyng on IRC).

### Log file

```
mpv 1468861116228.jpg --msg-level=ffmpeg=debug
Playing: 1468861116228.jpg
[ffmpeg] Probing jpeg_pipe score:6 size:2048
[ffmpeg] Probing jpeg_pipe score:6 size:4096
[ffmpeg] Probing jpeg_pipe score:6 size:8192
[ffmpeg] Probing jpeg_pipe score:6 size:16384
[ffmpeg] Probing jpeg_pipe score:6 size:32768
[ffmpeg] Probing jpeg_pipe score:6 size:65536
[ffmpeg] Probing mp3 score:25 size:98304
[ffmpeg] Probing mp3 score:25 size:98304
[ffmpeg/demuxer] mp3: Before avformat_find_stream_info() pos: 0 bytes read:1073905792 seeks:65543 nb_streams:1
[ffmpeg/audio] mp3: Header missing
[ffmpeg/audio] mp3: Header missing
[ffmpeg/audio] mp3: Header missing
[ffmpeg/audio] mp3: Header missing
[ffmpeg/audio] mp3: Header missing
[ffmpeg/audio] mp3: Header missing
[ffmpeg/audio] mp3: Header missing
[ffmpeg/demuxer] mp3: Estimating duration from bitrate, this may be inaccurate
[ffmpeg/demuxer] mp3: stream 0: start_time: 0.000 duration: 3.072
[ffmpeg/demuxer] mp3: format: start_time: 0.000 duration: 3.072 bitrate=256 kb/s
[ffmpeg/demuxer] mp3: After avformat_find_stream_info() pos: 98304 bytes read:1074004096 seeks:65543 frames:34
 (+) Audio --aid=1 (mp3)
[ffmpeg/audio] mp3: Header missing
Error decoding audio.
[ffmpeg/audio] mp3: Header missing
Error decoding audio.
[ffmpeg/audio] mp3: Header missing
Error decoding audio.
[ffmpeg/audio] mp3: Header missing
Error decoding audio.
[ffmpeg/audio] mp3: Header missing
Error decoding audio.
[ffmpeg/audio] mp3: Header missing
Error decoding audio.
[ffmpeg/audio] mp3: Header missing
Error decoding audio.
AO: [alsa] 48000Hz stereo 2ch s16
[ffmpeg] SWR: Using s16p internally between filters
[ffmpeg] SWR: Using s16p internally between filters
A: 00:00:00 / 00:00:03 (7%) Cache:  0s+0KB
[ffmpeg/audio] mp3: overread, skip -6 enddists: -5 -5
A: 00:00:00 / 00:00:03 (13%) Cache:  0s+0KB
[ffmpeg/audio] mp3: overread, skip -6 enddists: -5 -5
A: 00:00:00 / 00:00:03 (21%) Cache:  0s+0KB
Exiting... (End of file)
```

**Comment by Al-eXs** [comment] 2017-01-04 08:10
For some reason, that file IS both, a JPEG and MP3.

That could be done in windows with something like this: `copy /b someimage.jpg+someaudio.mp3 newimage.jpg` and that plays directly in MPV as the MP3.

In linux is something like: `cat someimage.jpg someaudio.mp3 > newimage.jpg`. (I extracted the audio from that file and merged into another image to test, the same error log in the MPV)

It's rather unusual to discover that kind of files, but it's one way of "hide" files.

**Comment by cehoyos** [comment] 2017-01-04 11:47
I thought the file was created by cutting the beginning of an mp3 containing cover art...

**Comment by Jj0YzL5nvJ** [comment] 2017-01-05 10:56
Very unusual file, I don't see the mp3 header anywhere.
If you only want the image, this does the trick:
`dd if=/tmp/pVG.jpg of=/tmp/solo.jpg bs=69812 count=1`

**Comment by lachs0r** [comment] 2017-01-05 18:38
mp3 has no header, that’s the joke (and why ffmpeg and other software is so bad at detecting mp3 when there’s no id3 tag).

**Comment by wm4** [comment] 2017-01-06 00:49
1. ffmpeg doesn't use the id3 tag to detect whether it's mp3 or not, because id3 can be used with other formats (like matroska), and ffmpeg supports this of course
2. an id3 tag is actually more likely to reduce the chance of detection: it's not skipped by the prober (I think), and it can be large, giving less real data to the prober
3. of course mp3 has some sort of header, just that it's not the kind of header that makes detection possible. however, if you see a bunch of very similar mp3 headers in a row with no garbage data between it, it's very likely that it's a real mp3 file

The main problem is IMHO that the ffmpeg mp3 prober is of bad quality full of nonsensical heuristics (instead of using heuristics that would hunt for "useful" features). It even detects ELF binaries as mp3.

**Comment by haasn** [comment] 2017-01-06 03:39
Am I the only one for who this file gets detected as a JPEG?

That said, using `dd if=pVG.jpg of=test.mp3 bs=1 skip=69812`, the resulting file does play as an MP3 - although it's only 0.855 seconds in duration. What's more, it sounds like an actual song, and not garbled noise: https://0x0.st/fsH.mp3

**Comment by Jj0YzL5nvJ** [comment] 2017-01-07 17:35
I have two theories of how this file could have been accidentally generated.
The exact size of the file is 98304 bytes = 96 KiB ("96 KB" for Windows users). Knowing this:

1. By a cache bug in a download manager that corrupted the end of file, trimming a fragment of the next file in the download list.
2. If the file was recovered after it was deleted, the MP3 residue could be part of a "slack space".

32 KiB is a common size, both cache and cluster.

**Comment by ieure** [comment] 2017-02-13 23:49
I gotta say, I installed mpv and downloaded the file, and I would *not* call this industrial music.

**Comment by Bodhizafa** [comment] 2017-02-14 00:03
Files like this used to be commonly used to exchange non-image file formats on internet boards that only allow posting images.

**Comment by rr-** [comment] 2017-02-14 08:07
>I gotta say, I installed mpv and downloaded the file, and I would not call this industrial music.

Have you played it with `--loop=yes`?

**Comment by marcan** [comment] 2017-02-14 08:19
The JPEG has size 0x110b4. That is padded out with zeros to 0x11200 (a multiple of the disk sector size), then the rest of the file is a chunk of an MP3 file. The total file size is 0x18000 (a multiple of the typical FAT32 cluster size, 32KB).

I bet this was either a lost cluster chain recovered by fsck/chkdsk, or a file that was written but its directory entry was not correctly updated with the size yet (e.g. unclean shutdown while writing it), followed by fsck/chkdsk guessing the filesize from the cluster chain length.

**Comment by wm4** [comment] 2017-02-14 13:43
Not sure if this was mentioned, but it could also just be a mp3 file that was appended to a (weirdly padded) jpg file. In that case, the file could be interpreted as both. But I think interpreting at jpg would be better, simply because the beginning is jpg.

**Comment by Ketsuban** [comment] 2017-02-14 14:05
While the hypotheses in this report as to how a file like this could be accidentally created are ingenious, I note that the filename given by the user (`1468861116228.jpg`) is typical of chan-style sites, which have in the past abused file format quirks (ZIP is a popular one) to "embed" one filetype in another and thus get around the site's inability to upload anything other than an image. The example given will be read as a JPEG by things which expect to be fed images, and as an MP3 by things looking for sound files (especially if the extension is changed to `mp3`).

**Comment by marcan** [comment] 2017-02-14 14:18
While 4chan is notorious for clever tricks like that (and indeed the filename points at 4chan or a similar site), this isn't a proper, complete MP3 file, but just a small, not-aligned, rather useless snippet that happens to exactly pad the file with an even number of sector-aligned blocks up to the most common FAT32 block size. And, of course, the JPEG content is typical of 4chan.

In other words, the most likely explanation is that a user had some filesystem corruption as I described, and then later uploaded the image to 4chan.

**Comment by rr-** [comment] 2017-02-14 14:40
(Actually the file's from 2chan)

**Comment by zatherz** [comment] 2017-02-14 15:09
Anime is degeneracy.

**Comment by annacrombie** [comment] 2017-02-14 15:53
@zatherz 
Anime is nice :)

**Comment by MiracleBlue** [comment] 2017-02-15 08:39
Thanks for that clarification.  We were all waiting with baited breath to know the source!  Now the question is, does anyone have good resources for us who would like to learn more about this technique of embedding (regardless of whether it was intentional or not in this case), it seems like a fascinating trick.

**Comment by wm4** [comment] 2017-02-15 08:44
Are you seriously asking how to create more broken files?

**Comment by MiracleBlue** [comment] 2017-02-15 09:11
I'm asking how it works, and where to read about it.  Seriously.

**Comment by MiracleBlue** [comment] 2017-02-15 09:12
Not to create, just to satisfy my own curiosity.

**Comment by marcan** [comment] 2017-02-15 09:13
@Al-eXs already explained how to make files like these, minus the convoluted padding caused by it happening by accident due to a filesystem issue. Just append an MP3 file to a JPEG. The reason why this works and confuses mpv is that MP3 doesn't really have file headers and an MP3 decoder will happily skip any other garbage it comes across, until it finds valid data.

Though if you really want to make trick files like these, there are better format choices. ZIP works better; you can append a ZIP file to almost any other format and it'll be a perfectly valid ZIP *and* a perfectly valid whatever else, because ZIP files are read from the end.

**Comment by MiracleBlue** [comment] 2017-02-15 09:17
Right, I did read that, I was hoping there were more detailed articles that I could read about why it works, and go down the rabbit hole of everything, it's just an interesting subject.  I dont' want to make them.  I just like learning.  If there's not much more to it than whats described above, then all good.

**Comment by MiracleBlue** [comment] 2017-02-15 09:26
Obviously in this case the filesystem did it by accident, but otherwise it's just a matter of writing the 2 sets of data where you want them in the same file, if I'm getting it right?  That's kind of amazing.  I'd always imagined file types to be some sort of sacred protected thing.  It's fun how computers can be made to do things they aren't expected to do.

**Comment by Flowdeeps** [comment] 2017-02-15 10:32
The technique is known as file steganography and can be used to create some really strange nested filetypes and images within images within images etc. The rabbit hole can get really rather deep.

**Comment by Argon-** [comment] 2017-02-15 10:37
> I could read about why it works, and go down the rabbit hole of everything

There's way less magic and depth involved in this process than you make it sound. Creating the mentioned image/zip is as easy as `cat image.png archive.zip > newfile.png`.

As for the mp3: as previously mentioned, ffmpeg "probes" such files. That is, it reads them until it finds a certain "data pattern", until it is certain enough to guess this is a file of type X (mp3 in this case). This process simply skipped the first bits of data (the image data), discarded it and finally found some mp3 data somewhere in the "middle" of the file.

**Comment by wm4** [comment] 2017-02-15 10:43
I guess all this barely ontopic chatter is from "other" people from reddit.

So I deleted the chatter and locked the thread.

This is a bug tracker, not a forum.

**Comment by lachs0r** [comment] 2017-07-22 04:15
I blame file systems and broken HBAs.

**Closed** 2017-07-22 04:14 UTC
Labels: invalid (broken file/hardware/drivers/etc)
