### ISSUE TITLE
Rapid flickering after toggling fullscreen and switching applications

### ISSUE THREAD

**Issue by j-james** [mpv-player/mpv#9748] opened 2022-01-23 14:29 UTC
### Important Information

Provide following Information:
- mpv version: 0.34.1
- Linux Distribution and Version: Arch Linux 5.15.16
- Source of the mpv binary: Arch Linux repos, should be similar to master and no patches are usually applied
- If known which version of mpv introduced the problem: N/A
- Window Manager and version: GNOME (I know), mutter 41.3
- GPU driver and version: Mesa Intel Xe Graphics (integrated?), mesa 21.3.4
- Possible screenshot or video of visual glitches: Difficult to record

### Reproduction steps

1. Enter full screen.
2. Exit full screen.
3. Switch focus (alt-tab) to another application.

### Expected behavior

The video to continue playing normally and smoothly.

### Actual behavior

The playing video flickers rapidly between a black screen and the video seemingly every frame.

This happens with a variety of formats: `mp4`, `webm`, `mkv`. It only happens with videos that are smaller than the width of the screen.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/7920664/output.txt)

### Sample files

Should be reproducible with any video small enough.

**Comment by Dudemanguy** [comment] 2022-01-23 15:15
I can reproduce this (RX 550), but my symptoms sound even worse than yours. The rendering completely stutters in addition to flickering. Some quick observations:

- This only happens in opengl (wlshm assumingly segfaults no clue if it's related or not).
- This doesn't happen if you use `video-sync=display-resample`.
- If you maximize instead of fullscreen, the bug still occurs.

I'm going to go out on a limb and say that this is probably an upstream issue but I don't know where. It's not clear to me what exactly is happening. I checked the usual suspects (frame callback, bad presentation timings) when we get issues like this and they all seemed OK. mpv on wayland has zero knowledge if it's in focus or not. We make a guess for one property, but it has zero impact on the rendering logic or code. mpv renders exactly the same way if it's in focus or not as long as it is still receiving frame callbacks (which it is in your case). I'm guessing somebody somewhere is screwing up the buffers but I don't know why.

**Comment by Mancooo** [comment] 2022-01-23 19:15
The issue is (probably) this: https://gitlab.gnome.org/GNOME/mutter/-/issues/2091

It will get fixed by mutter 41.4 (hopefully), but as you can see in the bugreport, the issue also needs to be solved client-side (aka mpv), because GTK also has this issue (and is getting a fix).

**Comment by Dudemanguy** [comment] 2022-01-23 19:23
Oh you're right, I didn't notice that in the log. I thought we actually ignored 0x0 resizes already but apparently we don't. I'll whip up a commit real quick.

**Comment by Mancooo** [comment] 2022-01-23 19:24
> Oh you're right, I didn't notice that in the log. I thought we actually ignored 0x0 resizes already but apparently we don't. I'll whip up a commit real quick.

Oh, that would be awesome! Instead of waiting for mutter 41.4... thanks!

**Closed** 2022-01-23 20:00 UTC
Labels: vo:gpu:wayland, os:linux
