### ISSUE TITLE
Lip-sync broken with AC3 TruHD

### ISSUE THREAD

**Issue by FCrane** [mpv-player/mpv#13439] opened 2024-02-07 23:26 UTC
### Important Information

Provide following Information:
- mpv version: libmpv-2.dll from 04.02.2024
- Windows Version: 11
- Source of the mpv binary: sinchiro build
- GPU model, driver and version: AMD RX570, latest drivers 24.1

### Reproduction steps
Play a video with AC3-THD sound. Confirmed for AC3 THD Atmos 7.1 an AC3 THD 5.1. The TruHD part seems to cause the issue, because E-AC3 Atmos 5.1 plays fine, for example. Other formats (AC3, DTS, DTS-MA 7.1, DTS-MA 5.1, etc.) seem to be ok, too.

### Expected behavior
Perfect lip-sync

### Actual behavior
Lip-Sync is sometimes way off (several 10 or even 100 ms) for videos containing an AC3 TruHD track! Confirmed for  AC3 THD Atmos 7.1 an AC3 THD 5.1. Sometimes not even constant during the playback. Sometimes adjusting the audio delay has no effect. Same for bit-streaming or not. Stopping and restarting the video at the same timecode results in different lip-sync! Completely unusable!

If switching to a different audio track in the same mkv (e.g. to AC3 or DTS in a different language), lip-sync is off too, so it seems that the issue occurs whenever an mkv (I could only test this file format) contains a THD track.

ALWAYS works perfectly with a dll from 30.04.2023 with the exact same configuration!

### Log file
[logs & conf.zip](https://github.com/mpv-player/mpv/files/14202651/logs.conf.zip)

**Comment by Traneptora** [comment] 2024-02-08 02:22
Can you provide a sample?

**Comment by FCrane** [comment] 2024-02-08 09:49
> Can you provide a sample?
These are all giant mkvs, ripped from UHD-BluRays. Cutting out a few seconds probably won't show the issue? Anyway it happens with ALL mkvs that have a THD track. However, it only seems to happen on my 7.1 HTPC setup - when I play the same files on a Stereo setup (computer with monitor and stereo speakers), lip-sync is correct!

**Comment by netExtra** [comment] 2024-02-08 10:03
> > This may be related to an issue I have read about. A patch to spdifenc.c in ffmpeg was added to "fix" problems with Dolby THD codecs seems to cause audio dropouts and other issues. If this is the issue you are experiencing then there is another patch by @gbooker which reverts the previous one and makes some changes that stops the audio dropouts. I'm not sure if the new patch has been added to the ffmpeg upchannel but I'm using a different ffmpeg build.
> 
> Where can I download the Windows dll that has this new patch for testing?

The issue is ffmpeg which would require a rebuild with a modified spdifenc.c file. But you can also download a version of mpv player with pre-built patched ffmpeg from [https://forums.plex.tv/t/dolby-truehd-passthrough-modified-mpv-build/802742/211](url)

**Comment by FCrane** [comment] 2024-02-08 11:57
Sorry, but I need a libmpv-2.dll for my tests, because I've programmed my own front-end. 

Looking at the link you provided, it seems as if this show-stopping bug exists since at least december? And ffmpeg developers (or whoever is responsible) did not care to fix this? Pfff, that's strange...

**Comment by netExtra** [comment] 2024-02-08 12:38
> Sorry, but I need a libmpv-2.dll for my tests, because I've programmed my own front-end.
> 
> Looking at the link you provided, it seems as if this show-stopping bug exists since at least december? And ffmpeg developers (or whoever is responsible) did not care to fix this? Pfff, that's strange...

The ffmpeg issue has been around much longer than December so this is probably not the cause. There were some older mpv-2.dll versions of the patch on the same page I linked, but they are no longer there. I also use mpv-2.dll for Plex HTPC but I build them myself from source.

**Comment by FCrane** [comment] 2024-02-08 17:00
Ok, I now tested "build-30.12.2023-ntruehd-clang.zip" from your link above and it works fine! No lip-sync issues! So the problem obviously comes from the faulty ffmpeg. So far so good (or actually bad). This version has issues with tone mapping, image brightness, etc. however, so I'll stick with my old version.

The last "good" version (no lip-sync, no brightness fluctuations, good tone mapping, no extreme startup delays, etc.) I have is "mpv-dev-x86_64-v3-20230903-git-67368ac.7z" so I'll be using this until the ffmpeg bug is fixed in the regular dev channel sinchiro builds. I hope this will be soon, because the latest versions seems to have better image quality (tone mapping). And I really hope the extreme delays at startup (obviously some shaders are precompilled, which takes eternally and seems to be completely unnecessary) will soon be fixed as well.

Please do notify us in this thread when a fixed version is available in the dev channel.

Regards!

**Comment by netExtra** [comment] 2024-02-08 17:37
I'm afraid that the issue has been known for quite some time so unless something is going on in the background I don't think there's an ETA for it.

Those test builds also have Plex features built in and maybe some of it affects tone mapping.  But you may want to download a December 2023 Shinchiro build to see if you have the same brightness and tone mapping issues.

**Comment by FCrane** [comment] 2024-02-08 19:47
Ok, here's something interesting: following netExtras tip (thanks!!!) I decided to download the last 20 or so shinchiro builds and go back to find out which one introduced the lip-sync issue. And to my surprise: the previous one (mpv-dev-x86_64-v3-20240128-git-c6ccabe.7z) works!!! No lip-sync problems at all!

So it seems it's only the latest build, (mpv-dev-x86_64-v3-20240204-git-fe0c181.7z) that has this issue! I hope this will help to fix this bug...

And please: fix the startup delay problem - it's really annoying ;-)

**Comment by kasper93** [comment] 2024-02-09 01:48
@FCrane: test this build https://github.com/zhongfly/mpv-winbuild/releases/tag/2024-02-08-a45518c

**Comment by FCrane** [comment] 2024-02-09 11:14
Yes, this version works!!! Lip-sync is correct, starts super fast! THANK YOU!!!!

**Comment by kasper93** [comment] 2024-02-09 13:25
Regressed by: 26a51464b68ce2571bdbe538da9c0a1c255b879f
Fixed by: 9254231175b21d7a7d7a3314b6dc1bedd062448d

**Closed** 2024-02-09 14:51 UTC
Labels: os:win

**Comment by FCrane** [comment] 2024-02-11 11:44
Sorry to open this again, but I cheered too early... :-(

The new version has lip-sync issues with all sound formats! Starting an mkv is fine, but after some minutes there's always a slight video stutter and after that, video is noticeably behind audio! Stopping and restarting fixes it, but after a few minutes, it happens again...

What could be the reason for that? Older versions did not show this issue...

**Comment by mitzsch** [comment] 2024-02-11 11:53
Can you please test the behavior with a minimal mpv config? Your mpv config is quite complex. It's also not a passthrough problem, as the issue seems to also occur without it. (Your config has passthrough disabled - so my linked build does nothing)

**Comment by FCrane** [comment] 2024-02-11 11:58
But your build fixed the TrueHD issue, even without pass-through!? It just seems to introduce a more general stutter/lip-sync issue...

What is considered to be a "minimal" config? I do't really see why my config is complex, because it just uses the "HDR" profile parameters (which is necessary for correct video) and one sharpness shader. Everything else seems to be standard anyway?

**Comment by mitzsch** [comment] 2024-02-11 12:03
`But your build fixed the TrueHD issue, even without pass-through!? `

No, my build only affects passthrough playback and yes there it sometimes adds a delay. That is how the (new) logic of passing through the audio data frames works. The desync is usually corrected during playback.

For plain TrueHD > 7.1 PCM playback it does nothing.


`What is considered to be a "minimal" config?`

I consider absolut minimal, something like this:

```
vo=gpu-next
hwdec=d3d11va
```

From this state, try adding options and test again. (Yes this will take a while...)

**Comment by llyyr** [comment] 2024-02-11 15:30
> What is considered to be a "minimal" config?

Try with no config at all, see if you can reproduce the issue. If you can't, then add back options in chunks and figure out what causes it

**Comment by FCrane** [comment] 2024-02-11 15:34
Problem is, that I absolutely need e.g. "audio-delay = 0.2" - otherwise lip-sync is generally far off.  I've now disabled the following:

video-sync = display-vdrop
deband = yes
cache = yes
scale = ewa_lanczos

and I've enabled bitstreaming. The first quick tests seem to be ok, but I need time (and some complete movies) of course to say more...

What could be the reason for lip-sync issues? Why was this never a problem before? Something must have changed in the last few versions that could affect this...

**Comment by kasper93** [comment] 2024-02-12 00:14
Since there is not much information that we can hold onto, we need your help. Please go to archival mpv builds, can use those https://sourceforge.net/projects/mpv-player-windows/files/,  and find the first build that is not working, to minimize range of changes that we should look at. You can bisect builds, you should find a breaking point if few steps.

**Comment by FCrane** [comment] 2024-02-13 20:37
With bitstreaming, the video stutters from time to time (heavily), but lip-sync stays correct. Without bitstreaming, video and audio are drifting apart, sometimes fast, sometimes slowly... Unfortunately, this is not really reproducible - sometimes it happens very soon, sometimes later, so testing is almost impossible :-( 

I wonder if it could be connected to a faster graphics card (AMD RX570 instead of the RX550) which I now need to use with the new mpv versions, because the GPU load increased 20-30% since the version from September 2023. The new versions don't work with my old graphics card, because it maxes out at 100% causing stutter...

**Comment by llyyr** [comment] 2024-02-13 21:52
> the GPU load increased 20-30% since the version from September 2023

`--profile=fast`

**Comment by kasper93** [comment] 2024-02-13 23:14
> With bitstreaming, the video stutters from time to time (heavily), but lip-sync stays correct. Without bitstreaming, video and audio are drifting apart, sometimes fast, sometimes slowly...

Can you try this build? https://github.com/zhongfly/mpv-winbuild/releases/tag/2024-01-20-5871ba8

**Comment by FCrane** [comment] 2024-02-16 22:12
This build behaves the same way as the newer ones: audio and video drift apart without bitstreaming. With bitstreaming, the new versions seem to work so far - however, I need more time to test.

**Comment by FCrane** [comment] 2024-02-18 20:17
I now tested it with 2 movies: with bistreaming, there's some stutter now and then, but lip-sync seems to stay more or less correct. It sometimes is noticeably off (especially after the stutters) but seems to resync again. At least there is no drift that then stays indefinitely.

Without bitstreaming, audio and video seem to drift apart over time and sometimes spontaneously. Once the lip-sync is off, it stays off until the video is stopped and restarted.

Last version I used that didn't show these issues was from September 3rd 2023. However, I didn't test other builds of last year so I cannot tell when it started...

**Comment by FCrane** [comment] 2024-02-20 21:03
> > the GPU load increased 20-30% since the version from September 2023
> 
> `--profile=fast`

What does that do exactly?? I could not find any documentation for it... Using it seems to reduce GPU load, even when I switch to my regular HDR profile immediately after. So what does it do and which disadvantages does it have? It must have some, because otherwise it would be applied by default internally...

**Comment by llyyr** [comment] 2024-02-20 21:22
> What does that do exactly?? I could not find any documentation for it... Using it seems to reduce GPU load, even when I switch to my regular HDR profile immediately after. So what does it do and which disadvantages does it have? It must have some, because otherwise it would be applied by default internally...

You can see the profile contents here https://github.com/mpv-player/mpv/blob/master/etc/builtin.conf#L43-L51

You can compare those with the defaults by searching for each option on the wiki, and reading the description for each option to understand what they do.

**Comment by kasper93** [comment] 2024-02-22 09:37
> Last version I used that didn't show these issues was from September 3rd 2023. However, I didn't test other builds of last year so I cannot tell when it started...

Take you time, but since you are the only user reporting this issue we need your help to narrow it down. We will not be able to guess what is not working for you without more information.

You have a working build and a not working build, divide the time between them and test build in the middle, you will be able to narrow find first not working build in few steps.

> sometimes it happens very soon, sometimes later, so testing is almost impossible :-(

Well, if it is impossible for you to test if you can reproduce, what can we say about this issue?
