### ISSUE TITLE
64-bit mpv will not run normally due to the existence of js files in the [scripts] folder 

### ISSUE THREAD

**Issue by 422658476** [mpv-player/mpv#8693] opened 2021-04-04 15:15 UTC
This problem began to appear in the version of mpv-x86_64-20210316. The version before February did not have this problem, and this problem did not occur on the 32-bit version. 

How to reproduce this problem ：
1.Create a shortcut for 64-bit mpv.exe 
2.Add the parameter with --config-dir to the shortcut, such as ：
"G:\mpv\mpv.exe" "F:\movie\xxxx.mkv" --config-dir="G:\diy-data"
3.Add files and folders in G:\diy-data, such as:
G:\diy-data\mpv.conf
G:\diy-data\scripts\xxx.js 
4、Run this shortcut, mpv will exit immediately after running。
5.     A====If you delete the js file in the [scripts] folder, mpv can run normally。
        B====Or instead of deleting the js file in the [scripts] folder, change the shortcut:
                "G:\mpv\mpv.exe" "F:\movie\xxxx.mkv" --config-dir="G:\diy-data"
                "G:\mpv\mpv.exe" "F:\movie\xxxx.mkv" --config-dir="G:\diy-data\"
                That is, add \ at the end of --config-dir="G:\diy-data, and mpv can run normally 

The content of the js file is arbitrary, even creating an empty js file will cause this problem
The content of the mpv.conf file is also arbitrary or empty. 

This problem has bothered me for a long time, thank you very much

**Comment by avih** [comment] 2021-04-04 15:16
Duplicate of #8667 .

**Closed by avih** 2021-04-04 15:16 UTC
Labels: os:win
