### ISSUE TITLE
Wrong colorspace in Dolby Vision video (expect HDR, actual SDR)

### ISSUE THREAD

**Issue by riverscn** [mpv-player/mpv#9761] opened 2022-01-25 05:35 UTC
### Important Information

Provide following Information:
- mpv version
mpv 0.34.0-142-g1ba0547bfb
- Platform and Version
Windows 11 21H2 22000.438
- Source of the mpv binary
https://downloads.sourceforge.net/project/mpv-player-windows/64bit/mpv-x86_64-20220116-git-1ba0547.7z

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
--vo=gpu-next --gpu-api=vulkan
enable DoVi and play a dolby vision video

### Expected behavior
Primaries: bt.2020
Colormatrix: ??
Gamma: ??

### Actual behavior
![image](https://user-images.githubusercontent.com/555062/150917235-b0008a92-fc81-4862-b1c3-5eee99e62bcd.png)

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by ValZapod** [comment] 2022-01-25 09:09
Yeah, well.

> Colormatrix: bt.2020-ncl

That would be false in any case scenario. It does not have any NCL matrix. The matrix is actually CL. :)

But yeah, it can be described as PQ and 2020 primaries for RGB matrix, I suppose, but still IPTPQc2 --> L'M'S' -> LMS --> RGB, so there is no R'G'B'!

**Comment by ValZapod** [comment] 2022-01-25 09:12
@haasn I think it should be linear transfer and 2020 primaries, matrix should be RGB.

**Comment by quietvoid** [comment] 2022-01-26 14:45
The default target is SDR, so I'm not sure how this is an actual issue?

If you want HDR, specify it in your config:
```
target-trc=pq
target-prim=bt.2020
```

**Comment by haasn** [comment] 2022-01-26 14:51
Maybe we should have separate properties for "tagged primaries" and "effective primaries". The latter notably also depends on the VO in use. At the moment only `--vo=gpu-next` will actually apply dolby vision.

What do you suggest should happen for something like profile 8.1?

**Comment by Natural-Harmonia-Gropius** [comment] 2022-01-26 15:01
> What do you suggest should happen for something like profile 8.1?

shows base layer's info, add somethings like a tag of dolbyvision, like when playing hdr it would shows peak after gamma

**Comment by Doofussy2** [comment] 2022-01-26 16:23
> The default target is SDR, so I'm not sure how this is an actual issue?
> 
> If you want HDR + 2020, specify it in your config:
> 
> ```
> target-trc=pq
> target-prim=bt.2020
> ```

That changes nothing. It still reads as SDR primaries.

**Comment by quietvoid** [comment] 2022-01-26 16:27
Right I hadn't understood that the issue refers to the OSD information.

**Comment by Doofussy2** [comment] 2022-01-26 17:05
Also, using pq ruins the picture. I run windows in HDR and the picture degrades when increasing the gamut and/or using pq transfer.

**Comment by ValZapod** [comment] 2022-01-26 21:39
> just tag everything as unspecified.

I will just point out AGAIN, thag this is actually the case with profile 5 files, they omit VUI info! So... BT.709 is just the default that mpv uses, it is not what is in use in libplacebo, which is not transparent.

**Comment by ValZapod** [comment] 2022-01-26 21:42
> It still reads as SDR primaries.

Yes, because you should use --vf=format for this.

**Comment by ValZapod** [comment] 2022-01-26 21:45
> using pq ruins the picture

I suppose tonemapper should be turned off.

**Comment by Doofussy2** [comment] 2022-01-26 21:53
> > using pq ruins the picture
> 
> I suppose tonemapper should be turned off. And you need to force HDR context d3d11-output-csp=pq

I don't think so. If I'm correct, there is no mechanism to hook the metadata to the windows swapchain, like the Dolby addon for windows. And no way to send the metadata to a DV enabled display. So tone mapping is all we have.

**Comment by ValZapod** [comment] 2022-01-26 22:01
> no mechanism to hook the metadata to the windows swapchain, like the Dolby addon for windows

Yes, dynamic metdata is not supported, but still you should force hdr to force 10 bit color and force absense of SDR--> HDR inverse tonemapping of windows 11.

**Comment by Doofussy2** [comment] 2022-01-26 22:06
> > no mechanism to hook the metadata to the windows swapchain, like the Dolby addon for windows
> 
> Yes, dynamic metadata is not supported, but still you should force hdr to force 10 bit color and force absense of SDR--> HDR inverse tonemapping of windows 11 and force absence of 709 --> 2020 primaries conversion windows does.

Agreed. That would be a good thing. 

I haven't upgraded to Win 11, yet. I don't have enough time to fix any breakages that might occur. So I'm waiting for a while.

**Comment by ValZapod** [comment] 2022-01-26 22:07
> fix any breakages that might occur

I though there was a breakage in icc, but apparently they just destroyed the icc profile in main screen of colorcpl.exe, the advanced menu there still works perfectly. :)

**Comment by ValZapod** [comment] 2022-01-26 23:01
Okay, I checked with HDR on. So not only it somehow select limited there and also it uses srgb though 10 bit surface is selected.

**Comment by Doofussy2** [comment] 2022-01-26 23:20
I currently have everything running with bt.2020 and pq, and I'm mostly satisfied with it. But with gpu-next, it isn't useable. I'm waiting to see what happens with the d3d11 PR. Hopefully it will sync up with Windows, like vo=gpu does. I can't really use DV tone mapping until that gets resolved, as there isn't a specific property for DV that allows me to create a profile to switch vo.

**Comment by ValZapod** [comment] 2022-02-03 01:30
> Hopefully it will sync up with Windows, like vo=gpu does

It did! --target-trc=pq --target-prim=bt.2020 --vo=gpu-next --gpu-context=d3d11 Build is here: https://github.com/ValZapod/mpv-winbuild/releases/tag/2022-02-03

```
[vo/gpu-next/d3d11] Using DXGI 1.2+
[vo/gpu-next/d3d11] Queried output: \\.\DISPLAY1, 3840x2160 @ 12 bits, colorspace: RGB_FULL_G2084_NONE_P2020 (12)
[vo/gpu-next/d3d11] Selected swapchain format R10G10B10A2_UNORM (24), attempting to utilize it.
[vo/gpu-next/d3d11] Selected swapchain color space RGB_FULL_G2084_NONE_P2020 (12), attempting to utilize it.
[vo/gpu-next/d3d11] Swapchain capabilities for color space RGB_FULL_G2084_NONE_P2020 (12): normal: yes, overlay: yes
[vo/gpu-next/d3d11] Swapchain successfully configured to color space RGB_FULL_G2084_NONE_P2020 (12)!
```

Also --target-trc=pq --target-prim=bt.2020 works, so THANKS @haasn!

**Comment by ValZapod** [comment] 2022-02-03 01:55
I think this should be closed because the OSD menu prints metadata in VUI. Fullstop. Metadata in VUI is indeed full range SDR and other unspecified.

**Comment by ValZapod** [comment] 2022-02-04 19:54
@haasn In HDR mode
```
[vo/gpu/d3d11] Queried output: \\.\DISPLAY1, 3840x2160 @ 12 bits, colorspace: RGB_FULL_G2084_NONE_P2020 (12)
[vo/gpu/d3d11] Selected swapchain format R10G10B10A2_UNORM (24), attempting to utilize it.
[vo/gpu/d3d11] Selected swapchain color space RGB_FULL_G2084_NONE_P2020 (12), attempting to utilize it.
[vo/gpu/d3d11] Swapchain capabilities for color space RGB_FULL_G2084_NONE_P2020 (12): normal: yes, overlay: yes
[vo/gpu/d3d11] Swapchain successfully configured to color space RGB_FULL_G2084_NONE_P2020 (12)!
```

the SWAPCHAIN color space RGB_FULL_G2084_NONE_P2020 defines what to target, not display's real capabilities, since the color management (and tonemapping ideally) MUST happen on display (WebOS). Yet it does not happen in gpu-next on Dolby Vision OR even HDR10 sources, why??? Manual  --target-trc=pq --target-prim=bt.2020  --vo=gpu-next --gpu-context=d3d11 does work on Dolby Vision and HDR10. Normal HDR sources are not affected. I thought it is logical that swapchain causes the auto target to be on and if does work with libplacebo then what is the problem?? I do not get it.

@jeeb To you too since you banned not collaborators under you pull.

**Comment by diannaojiang** [comment] 2022-02-17 19:50
> as there isn't a specific property for DV that allows me to create a profile to switch vo.

@Doofussy2   try this `profile-cond=(p["video-dec-params/gamma"] == "auto")`

**Comment by AstralStorm** [comment] 2022-03-13 08:29
On  mpv 0.34.0-221-g1c49d5735d still the same issue.
Also found that it interacts with inverse-tone-mapping option, which is incorrectly applied to the video that's definitely not SDR.

**Comment by AstralStorm** [comment] 2022-03-13 15:07
For reference, the check used Containers video from Demolandia, directly downloaded.

**Comment by ValZapod** [comment] 2022-03-23 20:09
> Obviously the DV is tonemapped back to HDR10 with the target settings, and the tonemap is

It can be tonemapped to hdr12 too, no peblem.

**Comment by AstralStorm** [comment] 2022-04-02 21:14
Of course mpv does not do 12-bit PQ, because it uses d3d11 rgb10_a2 mode. That gives 10-bit output.
It'd need a rgb16f scRGB output which it does not have yet.

There was no game mode peak bug, there was a case of someone not checking that the settings are vastly different. Rtings sucks.
(I've measured the peaks, they're exactly the same. Getting some 570 nit after calibration, 600 nit before - at 10%. LG CX 48" is a bit darker than bigger ones.)

Of course in some content what mpv does now won't work best - especially if metadata is used to touch up the video a lot. mpv does not use any metadata from DV so far I think.

**Comment by ValZapod** [comment] 2022-04-02 21:29
> It'd need a rgb16f scRGB output which it does not have yet.

Yes. We in Chrome have it, BTW and use it for display p3 sdr photos too. But I was thinking about 12 bit non float. There should be one, right?

>Rtings sucks.

I read it on avsforums. And it was mentioned by hdtvtest. It was fixed very fast.

>mpv does not use any metadata from DV so far I think

No, it does not use any dynamic meta. And no NLQ yet on top of alredy done MMR. As for example it is here (maybe fixed already, who knows, will check): https://github.com/mpv-player/mpv/pull/9677#issuecomment-1007884324

**Comment by Hrxn** [comment] 2022-04-02 22:40
> Of course mpv does not do 12-bit PQ, because it uses d3d11 rgb10_a2 mode. That gives 10-bit output. It'd need a rgb16f scRGB output which it does not have yet.
> 

Not necessarily, I think. I guess you need rgb16f half-float on the side of mpv, but you don't need another colorspace conversion, because, as far as I know, Windows' compositor does the conversion from any colorspace provided by the app to scRGB automatically?

**Comment by ValZapod** [comment] 2022-04-02 23:57
> colorspace provided by the app to scRGB automatically?

Android does that, not windows. And are you like being serious right now? HDMI uses PQ codepoints. And it needs XYZ for color managment on linear RGB. But no, scRGB is old technology and besides it uses old SDR curve and thus cannot be used for 10000 nits. No, we in chrome use for "HDR mode on" of windows 11 RGBA_16 backbuffer and transfer linear_HDR (slope 0.6250, SDR white point 128 nits), matrix RGB, range obviously full.

**Comment by Hrxn** [comment] 2022-04-03 04:30
Nah, I'm pretty sure that this applies to Windows.. well, a somewhat recent Windows 10, like 1903, or never, obviously

When "advanced color mode" is properly supported, the Windows compositor (DWM) does the conversion to scRGB before it then gets to the display color space..

Haven't tried this myself though, but if I remember correctly, that what's the Windows docs say..

**Comment by ValZapod** [comment] 2022-04-03 05:01
> the Windows compositor (DWM) does the conversion to scRGB before it then gets to the display color space..

I suppose you need to google what direct composition using SW overlays is. Certainly some older games' engines do use scRGB... But that is I think just WCG, nothing like 10000 nits. And I think there is support for YCbCr superwhite and in MPC-HC, at least in windows renderer. Intel driver also can passtrhough YCbCr untouched that allows for superwhite and even https://en.wikipedia.org/wiki/XvYCC

**Comment by ValZapod** [comment] 2022-04-03 15:15
> As for example it is here (maybe fixed already, who knows, will check): [#9677 (comment)](https://github.com/mpv-player/mpv/pull/9677#issuecomment-1007884324)

Checked, does not happen anymore on HDR display at least. Yeah!

**Comment by Hrxn** [comment] 2022-04-03 18:28
Found it... cause I like to back up what I'm saying...
https://docs.microsoft.com/en-us/windows/win32/direct3darticles/high-dynamic-range

**Comment by mnisius** [comment] 2022-07-19 21:51
I played with a lot of different config values and I think I have found the "correct" way to display Dolby Vision with MPV in HDR. Here is my config

```properties
profile=gpu-hq
vo=gpu-next
hwdec=auto-copy
target-colorspace-hint=yes
hdr-compute-peak=no
target-trc=pq
target-prim=bt.2020
target-peak=1500
```
Please set `target-peak` according to your display. I guess for something like the LG CX 800 should be good.

**Comment by AstralStorm** [comment] 2022-07-20 16:07
I'd recommend setting target-peak not to true peak but to 5% value or you will get noticeable dimming in enough bright scenes just due to total number of specular reflections. The newer screens are a bit better at it but will dim nonetheless.

The OLED being a true black screen is the real important piece anyway. In new mpv the tone mapping is set to something quite reasonable for bright conditions by default.

**Comment by Asinin3** [comment] 2023-06-02 05:10
Dobly Vision doesn't work for me. My LG C2 shows the HDR icon instead of Dobly Vision. I tried using a config file with only: 

```gpu-api=vulkan
profile=gpu-hq
vo=gpu-next
hwdec=auto-copy
target-colorspace-hint=yes```
And nothing else. But it just goes to normal HDR mode

**Comment by kasper93** [comment] 2023-08-16 11:35
I think everything is working as intended now? Can we close this issue?

**Closed** 2023-08-17 02:29 UTC
Labels: vo:gpu-next
