### ISSUE TITLE
can't change expected mediainfo encoding

### ISSUE THREAD

**Issue by fleshcraft** [mpv-player/mpv#1638] opened 2015-03-01 03:27 UTC
I doesn't found where can i change expected mediainfo encoding. As result player show window title with in wrong encoding.

**Comment by lachs0r** [comment] 2015-03-01 10:15
Duplicate of #1411.

No support for non-UTF-8. It’s 2015.

**Closed by lachs0r** 2015-03-01 10:15 UTC

**Comment by fleshcraft** [comment] 2015-03-03 09:26
Thanks.
