### ISSUE TITLE
mpv broken under MacOS Mojave.

### ISSUE THREAD

**Issue by MDMullins123** [mpv-player/mpv#5983] opened 2018-07-10 17:29 UTC
### mpv version and platform

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Any attempt to use mpv exits with 

Assertion failed: (self->_mk_tap_port != nil), function -[EventsResponder startMediaKeys]_block_invoke, file ../osdep/macosx_events.m, line 387.
Abort trap: 6

### Expected behavior

Obviously a video to play.

### Actual behavior

mpv crashes

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
https://0x0.st/ or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Akemi** [comment] 2018-07-10 17:42
duplicate of #5908.

**Closed by Akemi** 2018-07-10 17:42 UTC
