### ISSUE TITLE
mpv.app playback jittery but binary works fine

### ISSUE THREAD

**Issue by sheharyarn** [mpv-player/mpv#7405] opened 2020-01-28 01:59 UTC
### Important Information

- mpv version: `0.31.0`
- macOS Version: `10.15.1`
- Source of the mpv binary or bundle: `brew cask install mpv`
- If known which version of mpv introduced the problem: not exactly sure, possibly `0.30` onwards
- Possible screenshot or video of visual glitches:
  - Video: https://0x0.st/isz-.mov
  - Mirror: https://jmp.sh/1NLtUZJ
- My MPV configs:
  - [`mpv.conf`](https://github.com/sheharyarn/dotfiles/blob/master/Others/MPV/mpv.conf)
  - [`input.conf`](https://github.com/sheharyarn/dotfiles/blob/master/Others/MPV/input.conf)
  - [lua settings](https://github.com/sheharyarn/dotfiles/tree/master/Others/MPV/lua-settings)
  - [scripts](https://github.com/sheharyarn/dotfiles/tree/master/Others/MPV/scripts)

### Reproduction steps and actual behavior

 - Install mpv.app from homebrew
 - Associate a video file with mpv, double click to play it (or optionally open the app from terminal using `open`)
 - The video will lag, seeking will hang, will jitter, audio becomes noisy and out of sync with video (mostly happens with x265 videos, usually anime)

See:
  - Video: https://0x0.st/isz-.mov
  - Mirror: https://jmp.sh/1NLtUZJ

### Expected behavior

The video should play smoothly (It actually does when using the binary and not the app).

### Log file

mpv.app log: https://0x0.st/iszs.txt
mpv binary log: https://0x0.st/iszK.txt

**Comment by Akemi** [comment] 2020-01-28 11:11
since i can't reproduce this (not with any of my x265 encoded anime), do you have an example video with which it can be reproduced at all times? that way i can eliminate the file as the cause.

first of all try with --no-config so we can narrow down the cause. it might just be a config setting or script.
please try the following:
```
open -a /Applications/mpv.app test.mkv --args --no-config
```

then test with:
```
/Applications/mpv.app/Contents/MacOS/mpv --no-config test.mkv
```

and afterwards with (this is identically to the bundle, sans some system bundle things):
```
/Applications/mpv.app/Contents/MacOS/mpv-bundle --no-config test.mkv
```

can you reproduce the problem in all three cases? let me know where the problem persists and where it is gone.

also in case of the problem does it spam the system mpv log with messages? that one (will only show messages after mpv was closed again)
![Screenshot 2020-01-28 at 12 09 02](https://user-images.githubusercontent.com/680386/73258978-197ad880-41c7-11ea-8549-5517ea1bbdb7.png)

**Comment by Akemi** [comment] 2020-01-28 11:24
also @stolendata is there a reason why you build with `--disable-macos-media-player --disable-macos-10-12-2-features`, is there something i need to fix for building/downwards compatibility?

**Comment by sheharyarn** [comment] 2020-01-28 14:34
> since i can't reproduce this (not with any of my x265 encoded anime), do you have an example video with which it can be reproduced at all times? that way i can eliminate the file as the cause.

Here's the video file: https://0x0.st/isog.mkv (90.5MB)

---

> it might just be a config setting or script. please try the following:

MPV wouldn't start with the first command, so I tried a variant. These are all the commands I tried and the results:

First command:
 - `open -a /Applications/mpv.app video.mkv`: **Jittery**
 - `open -a /Applications/mpv.app video.mkv --args --no-config`: **MPV didn't start**
 - `open -a /Applications/mpv.app --args video.mkv`: **Jittery**
 - `open -a /Applications/mpv.app --args video.mkv --no-config`: **Smooth**

Second command:
 - `/Applications/mpv.app/Contents/MacOS/mpv --no-config video.mkv`: **Smooth**
 - `/Applications/mpv.app/Contents/MacOS/mpv video.mkv`: **Smooth**

Third command:
 - `/Applications/mpv.app/Contents/MacOS/mpv-bundle --no-config video.mkv`: **Smooth**
 - `/Applications/mpv.app/Contents/MacOS/mpv-bundle video.mkv`: **Smooth**

Looks like configs don't cause problems when using the binaries, even with the ones inside the `mpv.app`, but do play some role when using the app.

----

> also in case of the problem does it spam the system mpv log with messages? that one (will only show messages after mpv was closed again)

I do see that mpv previously spammed the `~/Library/Logs/mpv.log` with the `KAV` message like in your screenshot, but when I had the logs opened, the only message it would print (once or twice per video playback) was:

```
2020-01-28 19:04:49.525 mpv-bundle[69134:32124281] This NSLayoutConstraint is being configured with a constant that exceeds internal limits.  A smaller value will be substituted, but this problem should be fixed. Break on BOOL _NSLayoutConstraintNumberExceedsLimit(void) to debug.  This will be logged only once.  This may break in the future.
```

<img width="1003" alt="Screen Shot 2020-01-28 at 7 23 54 PM" src="https://user-images.githubusercontent.com/2355108/73272328-020e1080-4204-11ea-802e-cc5fff6d9985.png">

**Comment by Akemi** [comment] 2020-01-28 15:02
on a side note, `open -a /Applications/mpv.app --args video.mkv --no-config` this way around doesn't work for me only `open -a /Applications/mpv.app video.mkv --args --no-config`. seems like something changed from 10.14 to 10.15.

also had to do this to make it work, for whatever reason, `open -a mpv.app test.mkv --args --no-config --player-operation-mode=pseudo-gui`.

since `mpv-bundle` and `mpv` within the bundle work correctly i can conclude no bundle specific code on our side is causing the problem.

since `open -a /Applications/mpv.app --args video.mkv --no-config` works for you some setting or script is causing your problem. i guess you have to clear your `.config/mpv ` folder and activate one after another scripts and options and see which one causes it.

you can also try this bundle (https://0x0.st/isop.zip) i just compiled for testing and see if it might work. ignore the debug output about cursor hiding if you see any.

**Comment by sheharyarn** [comment] 2020-01-28 19:54
Thank you for all the help @Akemi. I tried the bundle you uploaded, but the video was still laggy. Then I tried disabling my configs and scripts like you said, and found the culprit:

https://github.com/sheharyarn/dotfiles/blob/baff4f690fd068fa5c1bcd817b10f89f0eebbd3a/Others/MPV/mpv.conf#L58

I've removed it from my config for now but it does raise more questions like why does it cause the video to lag and only when using the app and not the binaries. I tried a couple more variations (like keeping that line, and removing every other config) but the issue persists as long as the cache is enabled.

**Comment by Akemi** [comment] 2020-01-28 20:21
yeah that's weird. i can just assume but the system might do something weird. maybe related to sandboxing or code signing. i have no idea.

maybe you can get some more information about it when activating the stats (`shift+i`) and possibly when the stats are on screen entering the 3 page (hit `3` after activating the stats view). on page 1 there should be some cache info at the top ("Total Cache" + "Speed"), page 3 only has cache info. maybe there is a drastic difference in speed or something else.

**Comment by stolendata** [comment] 2020-01-28 21:50
> also @stolendata is there a reason why you build with `--disable-macos-media-player --disable-macos-10-12-2-features`, is there something i need to fix for building/downwards compatibility?

I only disable these features since I (at least for now) aim my builds at 10.10/Yosemite compatibility.

**Comment by Akemi** [comment] 2020-01-29 00:48
there are runtime checks that should make it work without disabling those features at build time.

if there are actual issues by keeping them enabled but not working on runtime i would like ti fix them.

**Comment by stolendata** [comment] 2020-01-29 14:18
> there are runtime checks that should make it work without disabling those features at build time.
> 
> if there are actual issues by keeping them enabled but not working on runtime i would like ti fix them.

Right, but if the executable links against the framework/library it will contain a Load command for the same, and then there's no starting it if the framework/library can't be found, which is what's happening.

I could be wrong but I suspect this could be fixed if it were possible to link them with `LC_LOAD_WEAK_DYLIB` instead of `LC_LOAD_DYLIB` (https://github.com/apple/darwin-xnu/blob/master/EXTERNAL_HEADERS/mach-o/loader.h#L273).

**Comment by Akemi** [comment] 2020-01-29 14:55
i was under the impression that should also work in the `LC_LOAD_DYLIB` case. i would test and try to fix it, though it's such a pain building for lower macOS versions.

**Comment by Akemi** [comment] 2020-01-29 17:31
@sheharyarn i have a feeling it might be related to #6389 and the granted accessibility permissions in the system preferences. if mpv has those permission try to remove them (see this comment for where it can be found https://github.com/mpv-player/mpv/issues/7062#issuecomment-578352787).

**Comment by stolendata** [comment] 2020-01-29 21:47
> i was under the impression that should also work in the `LC_LOAD_DYLIB` case. i would test and try to fix it, though it's such a pain building for lower macOS versions.

I wouldn't mind doing some tests as I'd love to be able to get the 10.12 features into my builds instead of having to omit them as I do now. I just don't know Waf well enough to know where I can modify its interaction with clang/ld to tell it to `-weak-l/-weak_framework` those imports.

**Comment by sheharyarn** [comment] 2020-01-30 01:42
> I have a feeling it might be related to #6389 and the granted accessibility permissions in the system preferences. if mpv has those permission try to remove them (see this comment for where it can be found #7062 (comment)).

@Akemi tried it with both with and without accessibility permissions, but still the same issue.

---

> maybe you can get some more information about it when activating the stats (shift+i) and possibly when the stats are on screen entering the 3 page

I compared the mpv stats while playing the mpv video with both the app and the binary and they were almost identical. The only minor difference I noted was that the "Total Cache" and "Forward RAM" values were always about 10-20MB higher when playing with the binary. When cache is disabled both values are always under 200KB but the video plays very smoothly as previously mentioned.

But this did give me an idea, and instead of using the default cache value or the value of 500mb previously set in my config, this time I used:

```
demuxer-max-bytes=50M
demuxer-max-back-bytes=50M
```

And the playback was super smooth (at least much smoother than before) though it would still sometimes hang for less than a second before going back to smooth. Not sure what this means.

**Comment by Akemi** [comment] 2020-01-30 13:52
i wonder if changing `--stream-buffer-size` would help in any way? can you also reproduce the same problem with older mpv versions (>0.25)?

**Comment by Akemi** [comment] 2020-02-08 10:02
since i noticed it in this issue, the auto selection of the title bar style has been fixed with 5d7f0edfebb9829eb167770f943970203bdf63c0.

**Comment by fightingdreamer** [comment] 2021-05-09 10:25
Continuation from https://github.com/mpv-player/mpv/issues/8820#issuecomment-835592523
@Akemi Sure, I don't mind testing patches.

I also trying to record issue (app vs console) via Instruments, maybe this will give us enough data to find the cause.

**Comment by Akemi** [comment] 2021-05-09 11:46
@fightingdreamer i can actually reproduce this now. though even after some testing i didn't find anything conclusive.

when i find a fix for it, i will let you know for the final testing.

**Comment by Akemi** [comment] 2021-05-09 12:40
just some data i gathered while playing back a file for 20 secs.

config:
```
no-config
cache=yes
cache-secs=3600
demuxer-max-bytes=4GiB
terminal=no
end=20
```

data:
```
binary:
elapsed: 0.048000ms read bytes: 65536 elapsed all: 716.220000ms num read: 25039 read bytes all: 2200mib
elapsed: 0.026000ms read bytes: 65536 elapsed all: 1355.275000ms num read: 49957 read bytes all: 4253mib

bundle:
elapsed: 0.015000ms read bytes: 65536 elapsed all: 830.584000ms num read: 25039 read bytes all: 2200mib

elapsed: time spent for the current read operation
read bytes: read bytes of the current read operation
elapsed all: sum of time spent in all read operations
num read: the iteration of the current read operation
read bytes all: sum of read bytes of all read operations
```

after 20 secs the binary reads 4253mib of data in 1355.275ms (~1.36secs), the bundle 2200mib in 830.584ms (~0.83secs). comparing the same read iteration 25039, the binary read 2200mib of data in  716.22ms (~0.72secs), which is the exact same amount of data as the bundle just ~0.11secs faster.

since the freezes can be several seconds long, i think we can conclude that the read operation isn't really the bottleneck but rather something is blocking between the read calls(?).

patch i used for the output, for the bundle i redirected the output to `~/Library/Logs/mpv.log`
```
diff --git a/osdep/macosx_application.m b/osdep/macosx_application.m
index bb8b67b575..880aa12968 100644
--- a/osdep/macosx_application.m
+++ b/osdep/macosx_application.m
@@ -312,6 +312,16 @@ static void init_cocoa_application(bool regular)
     });
 }
 
+static void macosx_redirect_output_to_logfile(const char *filename)
+{
+    NSAutoreleasePool *pool = [[NSAutoreleasePool alloc] init];
+    NSString *log_path = [NSHomeDirectory() stringByAppendingPathComponent:
+        [@"Library/Logs/" stringByAppendingFormat:@"%s.log", filename]];
+    freopen([log_path fileSystemRepresentation], "a", stdout);
+    freopen([log_path fileSystemRepresentation], "a", stderr);
+    [pool release];
+}
+
 static bool bundle_started_from_finder(char **argv)
 {
     NSString *binary_path = [NSString stringWithUTF8String:argv[0]];
@@ -355,6 +365,7 @@ int cocoa_main(int argc, char *argv[])
 
         if (bundle_started_from_finder(argv)) {
             setup_bundle(&argc, argv);
+            macosx_redirect_output_to_logfile("mpv");
             init_cocoa_application(true);
         } else {
             for (int i = 1; i < argc; i++)
diff --git a/stream/stream_file.c b/stream/stream_file.c
index 0ba12278ab..20843ca74b 100644
--- a/stream/stream_file.c
+++ b/stream/stream_file.c
@@ -66,6 +66,10 @@ struct priv {
     bool appending;
     int64_t orig_size;
     struct mp_cancel *cancel;
+
+    double time_spent_all;
+    uint64_t bytes_read_all;
+    uint64_t num_of_reads;
 };
 
 // Total timeout = RETRY_TIMEOUT * MAX_RETRIES
@@ -103,7 +107,18 @@ static int fill_buffer(stream_t *s, void *buffer, int max_len)
 #endif
 
     for (int retries = 0; retries < MAX_RETRIES; retries++) {
+        clock_t begin = clock();
         int r = read(p->fd, buffer, max_len);
+        clock_t end = clock();
+        double time_spent = (double)(end - begin) / (CLOCKS_PER_SEC / 1000);
+
+        p->time_spent_all = p->time_spent_all + time_spent;
+        p->bytes_read_all = p->bytes_read_all + r;
+        p->num_of_reads++;
+
+        //if (time_spent > 3)
+            //printf("elapsed: %fms read bytes: %d\n", time_spent, r);
+        printf("elapsed: %fms read bytes: %d elapsed all: %fms num read: %llu read bytes all: %llumib\n", time_spent, r, p->time_spent_all, p->num_of_reads, p->bytes_read_all/1000/1000);
         if (r > 0)
             return r;
```

**Comment by Akemi** [comment] 2021-05-09 20:14
before anyone else wastes their time. i bisected the problem to this commit 77021cf6fe6a1813b832c8927c288e958b6f6845. though it's not actually the reason for the problem, it just hid the problem because of the wrapper shell script it behaved like invoked from the terminal.

**Comment by fightingdreamer** [comment] 2021-05-09 20:27
In my case 226MiB was read in ~167ms total (app bundle).

Instruments > File Activity shows:
mpv file read operations: 2576, total: 161MiB, mostly 64KiB chunks
mpv mmap read opearations: 255, total: 64MiB (system page cache)
mpv disk read opearations: 357, total: 161MiB, mostly 512KiB chunks (ssd disk)

[vector graph in pdf](http://0x0.st/-B36.pdf) of each read duration / total read / total call count

I agree, read operations are not a bottleneck - something is happening before or after read call.

---

I was able to make profiling more reproducible by adding to config:
```ini
demuxer-cache-wait=yes
end=0
```

After playing with Instruments I noticed that demux_thread is mostly responsible for extra time in bundle app case.

```text
# bundle app
demux work: 13955.136000ms
demux wait: 292.704000ms

# console
demux work: 960.146000ms
demux wait: 182.156000ms
```

patch used:
```patch
diff --git a/demux/demux.c b/demux/demux.c
index 53ad455b46..bf77127891 100644
--- a/demux/demux.c
+++ b/demux/demux.c
@@ -2554,13 +2554,29 @@ static void *demux_thread(void *pctx)
 
     stats_register_thread_cputime(in->stats, "thread");
 
+    double time_work = 0;
+    double time_wait = 0;
     while (!in->thread_terminate) {
-        if (thread_work(in))
-            continue;
-        pthread_cond_signal(&in->wakeup);
-        struct timespec until = mp_time_us_to_timespec(in->next_cache_update);
-        pthread_cond_timedwait(&in->wakeup, &in->lock, &until);
+        {
+            double begin = clock();
+            if (thread_work(in)) {
+                time_work += (clock() - begin) / (CLOCKS_PER_SEC / 1000);
+                continue;
+            }
+            else {
+                time_work += (clock() - begin) / (CLOCKS_PER_SEC / 1000);
+            }
+        }
+        {
+            double begin = clock();
+            pthread_cond_signal(&in->wakeup);
+            struct timespec until = mp_time_us_to_timespec(in->next_cache_update);
+            pthread_cond_timedwait(&in->wakeup, &in->lock, &until);
+            time_wait += (clock() - begin) / (CLOCKS_PER_SEC / 1000);
+        }
     }
+    printf("demux work: %fms\n", time_work);
+    printf("demux wait: %fms\n", time_wait);
 
     if (in->shutdown_async) {
         pthread_mutex_unlock(&in->lock);
diff --git a/osdep/macosx_application.m b/osdep/macosx_application.m
index bb8b67b575..914e53acb6 100644
--- a/osdep/macosx_application.m
+++ b/osdep/macosx_application.m
@@ -312,6 +312,16 @@ static void init_cocoa_application(bool regular)
     });
 }
 
+static void macosx_redirect_output_to_logfile(const char *filename)
+{
+    NSAutoreleasePool *pool = [[NSAutoreleasePool alloc] init];
+    NSString *log_path = [NSHomeDirectory() stringByAppendingPathComponent:
+        [@"Library/Logs/" stringByAppendingFormat:@"%s.log", filename]];
+    freopen([log_path fileSystemRepresentation], "w", stdout);
+    freopen([log_path fileSystemRepresentation], "w", stderr);
+    [pool release];
+}
+
 static bool bundle_started_from_finder(char **argv)
 {
     NSString *binary_path = [NSString stringWithUTF8String:argv[0]];
@@ -353,6 +363,8 @@ int cocoa_main(int argc, char *argv[])
         ctx.argc     = &argc;
         ctx.argv     = &argv;
 
+        macosx_redirect_output_to_logfile("mpv2");
+
         if (bundle_started_from_finder(argv)) {
             setup_bundle(&argc, argv);
             init_cocoa_application(true);

```

**Comment by fightingdreamer** [comment] 2021-05-09 21:38
Measuring from demux/demux_mkv.c->demux_mkv_read_packet, time in seconds:

```txt
# bundle app
demux/demux_mkv.c read_next_block: 13.754655
demux/demux_mkv.c handle_block: 4.379475

# console
demux/demux_mkv.c read_next_block: 0.887549
demux/demux_mkv.c handle_block: 0.303200
```

**Comment by Akemi** [comment] 2021-05-09 21:48
that's interesting. i kinda came to the same point when analysing the pthreads and their QoS.

can you confirm that setting `demuxer-thread=no` fixes the issue?

**Comment by fightingdreamer** [comment] 2021-05-09 21:55
Adding `demuxer-thread=no` disables cache, so issue no longer exist (verified).

**Comment by fightingdreamer** [comment] 2021-05-09 22:34
Measuring from demux/demux_mkv.c->read_block, time in seconds:

```txt
# bundle app
demux/demux_mkv.c demux_mkv_read_block_lacing: 13.027755

# console
demux/demux_mkv.c demux_mkv_read_block_lacing: 1.019283
```

Instruments suggests stream_read > stream_read_patrial (from stream/stream.c)
and script_thread (blocked) > script_raw_wait_event > mpv_wait_event > wait_wakeup:pthread_cond_timedwait (from player/client.c).

I also noticed more (by ~25%) memory allocations/deallocations in bundle app, caused by demux_thread and script_thread.

**Comment by fightingdreamer** [comment] 2021-05-11 21:08
During profiling I noticed `memalign` lighted up, but didn't put much attention at the moment.
Can misaligned memory be the cause of different allocation plan?

**Comment by Akemi** [comment] 2021-05-11 22:17
i think i found a fix for this problem with the help of @ePirat. i will test some more in the upcoming days and will let you know.

**Comment by Akemi** [comment] 2021-05-12 17:53
opened a PR #8826 with the fix. if you want to test it. some explanation is on that PR and the commit description. the problem can also be reproduced on the terminal, like described on that PR.

let me know if this fixes it for you too.

**Comment by fightingdreamer** [comment] 2021-05-15 01:54
Yes, your patch fixed my problem. I also checked problematic (hard to demux) h265 files over NFS, everything works perfectly.

**Comment by Akemi** [comment] 2021-05-16 11:51
thanks for testing. the fix is now in master.

**Closed** 2021-05-16 11:50 UTC
Labels: os:mac
