### ISSUE TITLE
Add `--window-size`, `--window-position` and getter/setter/observer for them

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [mpv-player/mpv#10788] opened 2022-10-26 09:20 UTC
### Expected behavior of the wanted feature

Currently we have `--geometry` and `--autofit`, But changes to them do not respond at runtime.
Adding `--window-size` and `--window-position` will give us an ability to use the script to provide picture-in-picture mode and window-drag detection.

**Comment by hooke007** [comment] 2022-10-26 11:48
https://github.com/mpv-player/mpv/pull/8383

we could but no implement for windows

**Comment by stax76** [comment] 2022-10-26 13:50
On Windows, there is:

https://www.autohotkey.com/docs/commands/WinMove.htm

(I'm using it to work around a severe DropBox bug.)

(In mpv.net the C# and PowerShell script hosts can access the window object.)

**Comment by Dudemanguy** [comment] 2022-10-26 14:15
What you actually want is for `geometry` and `autofit` to update at runtime. This is already perfectly possible (x11/wayland have it), but someone needs to implement it for other platforms (namely, windows and macOS). This is basically a duplicate of #8379 so I'll close this.

**Closed by Dudemanguy** 2022-10-26 14:15 UTC
Labels: meta:feature-request
