### ISSUE TITLE
SDL video output hangs on low framerate

### ISSUE THREAD

**Issue by rom1v** [mpv-player/mpv#9194] opened 2021-09-07 14:36 UTC
### Important Information

Provide following Information:
- mpv version: current master (c2dec023b79ebb54160b5a7a1c5f2b609627f167)
- Linux Distribution and Version: Debian sid
- Source of the mpv binary: built manually
- Window Manager and version: xfce 4.16 / X11

```console
$ build/mpv --version
mpv 0.33.0-335-gc2dec023b7-dirty Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Mon Sep  6 19:10:28 CEST 2021
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: 4.4-5+b1
```

### Reproduction steps

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

```bash
# generate a 1-fps video
ffmpeg -f lavfi -i testsrc=duration=10:size=1280x720:rate=1 -pix_fmt yuv420p 1fps.mp4

# run it with the SDL video output
mpv --vo=sdl 1fps.mp4
# the video stops making any progress when there are no UI events (mouse moves or similar)

# run it with the default video output (or --vo=x11)
mpv 1fps.mp4
# it works
```

### Expected behavior

The video should play even when there are no input events.

### Actual behavior

The video does not make any progress unless there are input events.

**Comment by Dudemanguy** [comment] 2022-01-19 03:01
I'm not able to reproduce so closing. If the issue still exists, feel free to reopen with a log file.

**Closed by Dudemanguy** 2022-01-19 03:01 UTC
Labels: os:linux

**Comment by rom1v** [comment] 2022-01-19 09:34
I confirm that it works now.
