### ISSUE TITLE
mpv spanning multiple instances of itself and crashing

### ISSUE THREAD

**Issue by noraa** [mpv-player/mpv#5283] opened 2017-12-25 08:08 UTC
### mpv version and platform

0.27 on macOS High Sierra 10.13.2

### Reproduction steps

While mpv is already open, double clicking on a video file (doesn't matter the format) spawns another instance of mpv (instead of opening within the existing process). This second instance then crashes as it never fully opens. Force quitting the second instance is sometimes successful, but often times a reboot of the entire system is required.

The initial mpv process does not need to have a video file playing, it simply needs to be open

### Expected behavior

Either double clicking a video will open it in the existing mpv process, or the second process will open alongside the original and not crash.

### Actual behavior

The second mpv process never fully opens and crashes. The mpv icon will bounce in the dock for quite some time (~1 min or more), and eventually will stop - with the icon displayed in the dock, but without the running app indicator beneath the icon. Right clicking on the icon gives the option to force quit, but often times that is not successful. Even more confounding, Activity Monitor only displays one instance of mpv running (the original process). If the original instance of mpv has been quit, Activity Monitor doesn't show mpv running at all!

### Log file

Unfortunately the log file is rather useless, as no log is even created when the second instance spawns. This is the log info from when the initial instance is spawned by double clicking on the mpv icon.

[   0.008][v][cplayer] mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
[   0.008][v][cplayer]  built on Sat Sep 23 20:53:45 CEST 2017
[   0.008][v][cplayer] ffmpeg library versions:
[   0.008][v][cplayer]    libavutil       55.58.100
[   0.008][v][cplayer]    libavcodec      57.89.100
[   0.008][v][cplayer]    libavformat     57.71.100
[   0.008][v][cplayer]    libswscale      4.6.100
[   0.008][v][cplayer]    libavfilter     6.82.100
[   0.008][v][cplayer]    libswresample   2.7.100
[   0.008][v][cplayer] ffmpeg version: 3.3.4
[   0.008][v][cplayer] 
[   0.008][v][cplayer] Configuration: waf configure --prefix=/Users/djinn/apps/homebrew/Cellar/mpv/0.27.0 --enable-zsh-comp --enable-libmpv-shared --enable-html-build --confdir=/Users/djinn/apps/homebrew/etc/mpv --datadir=/Users/djinn/apps/homebrew/Cellar/mpv/0.27.0/share/mpv --mandir=/Users/djinn/apps/homebrew/Cellar/mpv/0.27.0/share/man --docdir=/Users/djinn/apps/homebrew/Cellar/mpv/0.27.0/share/doc/mpv --zshdir=/Users/djinn/apps/homebrew/Cellar/mpv/0.27.0/share/zsh/site-functions
[   0.008][v][cplayer] List of enabled features: 52 apple-remote asm atomics avutil-imgcpy-uc avutil-spherical bsd-fstatfs build-date cocoa coreaudio cplayer cplugins cuda-hwaccel debug-build encoding fchmod gl gl-cocoa glob glob-posix gnuc iconv is_ffmpeg jpeg lcms2 libass libass-osd libav libavcodec libavdevice libdl libm libmpv-shared lua nanosleep optimize osx-thread-name plain-gl posix posix-or-mingw posix-spawn pthreads shm stdatomic termios videotoolbox-gl videotoolbox-hwaccel videotoolbox-hwaccel-old zlib zsh-comp
[   0.008][v][osc] Loading lua script @osc.lua...
[   0.008][v][osc] loading mp.defaults
[   0.009][v][osc] loading @osc.lua
[   0.013][v][osc] lua-settings/osc.conf not found. 
[   0.013][v][cplayer] Run command: define-section, flags=0, args=[showhide, mouse_move script-binding osc/__keybinding1
[   0.013][v][cplayer] mouse_leave script-binding osc/__keybinding2
[   0.013][v][cplayer] , force]
[   0.013][v][cplayer] Run command: enable-section, flags=0, args=[showhide, allow-hide-cursor+allow-vo-dragging]
[   0.013][v][cplayer] Run command: define-section, flags=0, args=[input, mbtn_left script-binding osc/__keybinding3
[   0.013][v][cplayer] shift+mbtn_left script-binding osc/__keybinding4
[   0.013][v][cplayer] mbtn_right script-binding osc/__keybinding5
[   0.013][v][cplayer] wheel_up script-binding osc/__keybinding6
[   0.013][v][cplayer] wheel_down script-binding osc/__keybinding7
[   0.013][v][cplayer] mbtn_left_dbl ignore
[   0.013][v][cplayer] shift+mbtn_left_dbl ignore
[   0.013][v][cplayer] mbtn_right_dbl ignore
[   0.013][v][cplayer] , force]
[   0.013][v][cplayer] Run command: enable-section, flags=0, args=[input, ]
[   0.014][v][cplayer] Run command: define-section, flags=0, args=[input_osc, del script-binding osc/__keybinding8
[   0.014][v][cplayer] , default]
[   0.014][v][cplayer] Run command: enable-section, flags=0, args=[input_osc, allow-hide-cursor+allow-vo-dragging]
[   0.014][v][cplayer] Run command: define-section, flags=0, args=[input_forced_osc, , force]
[   0.014][v][cplayer] Run command: enable-section, flags=0, args=[input_forced_osc, allow-hide-cursor+allow-vo-dragging]
[   0.014][v][cplayer] Done loading @osc.lua.
[   0.014][v][ytdl_hook] Loading lua script @ytdl_hook.lua...
[   0.014][v][ytdl_hook] loading mp.defaults
[   0.014][v][cplayer] Run command: disable-section, flags=0, args=[input]
[   0.015][v][osd/libass] Shaper: FriBidi 0.19.7 (SIMPLE)
[   0.015][v][osd/libass] Setting up fonts...
[   0.015][v][ytdl_hook] loading @ytdl_hook.lua
[   0.016][v][ytdl_hook] lua-settings/ytdl_hook.conf not found. 
[   0.016][v][osd/libass] Using font provider coretext
[   0.016][v][osd/libass] Done.
[   0.016][v][cplayer] Run command: hook-add, flags=0, args=[on_load, 1, 10]
[   0.016][v][cplayer] Run command: hook-add, flags=0, args=[on_preloaded, 2, 10]
[   0.016][v][cplayer] Done loading @ytdl_hook.lua.
[   0.253][v][vo/opengl] Initializing OpenGL backend 'cocoa'
[   0.292][v][vo/opengl] GL_VERSION='4.1 NVIDIA-10.28.10 355.11.10.10.20.111'
[   0.292][v][vo/opengl] Detected desktop OpenGL 4.1.
[   0.292][v][vo/opengl] GL_VENDOR='NVIDIA Corporation'
[   0.292][v][vo/opengl] GL_RENDERER='NVIDIA GeForce GTX 780M OpenGL Engine'
[   0.292][v][vo/opengl] GL_SHADING_LANGUAGE_VERSION='4.10'
[   0.307][v][vo/opengl] Loaded extension GL_APPLE_rgb_422.
[   0.307][v][vo/opengl] Testing FBO format rgba16
[   0.307][v][vo/opengl] Create FBO: 16x16 (16x16)
[   0.318][v][vo/opengl] Using FBO format rgba16.
[   0.319][v][vo/opengl] No advanced processing required. Enabling dumb mode.
[   0.319][v][vo/opengl] Reported display depth: -1
[   0.319][v][vo/opengl] Assuming 59.950550 FPS for display sync.
[   0.355][v][vo/opengl] Resize: 960x480
[   0.355][v][vo/opengl] Window size: 960x480
[   0.355][v][vo/opengl] Video source: 960x480 (1:1)
[   0.355][v][vo/opengl] Video display: (0, 0) 960x480 -> (0, 0) 960x480
[   0.355][v][vo/opengl] Video scale: 1.000000/1.000000
[   0.355][v][vo/opengl] OSD borders: l=0 t=0 r=0 b=0
[   0.355][v][vo/opengl] Video borders: l=0 t=0 r=0 b=0
[   0.355][v][vo/opengl] Testing FBO format rgba16
[   0.355][v][vo/opengl] Create FBO: 16x16 (16x16)
[   0.355][v][vo/opengl] Using FBO format rgba16.
[   0.355][v][vo/opengl] No advanced processing required. Enabling dumb mode.
[   0.355][v][vo/opengl] Texture for plane 0: 960x480
[   0.355][v][vo/opengl] Texture for plane 1: 960x480
[   0.355][v][vo/opengl] Texture for plane 2: 960x480
[   0.473][v][vo/opengl] Resize: 960x480
[   0.473][v][vo/opengl] Window size: 960x480
[   0.473][v][vo/opengl] Video source: 960x480 (1:1)
[   0.473][v][vo/opengl] Video display: (0, 0) 960x480 -> (0, 0) 960x480
[   0.473][v][vo/opengl] Video scale: 1.000000/1.000000
[   0.473][v][vo/opengl] OSD borders: l=0 t=0 r=0 b=0
[   0.473][v][vo/opengl] Video borders: l=0 t=0 r=0 b=0
[   0.482][v][osd/libass] fontselect: (sans-serif, 400, 0) -> /System/Library/Fonts/Helvetica.ttc, -1, Helvetica
[   0.483][v][vo/opengl] Reallocating OSD texture to 512x256.
[   0.484][v][vo/opengl] new shader program:
[   0.484][v][vo/opengl] [  1] color = vec4(ass_color.rgb, ass_color.a * texture(osdtex, texcoord).r);
[   0.484][v][vo/opengl] [  2] // color mapping
[   0.524][v][cplayer] Run command: disable-section, flags=0, args=[showhide]
[   0.692][v][vo/opengl] Resize: 960x480
[   0.692][v][vo/opengl] Window size: 960x480
[   0.692][v][vo/opengl] Video source: 960x480 (1:1)
[   0.692][v][vo/opengl] Video display: (0, 0) 960x480 -> (0, 0) 960x480
[   0.692][v][vo/opengl] Video scale: 1.000000/1.000000
[   0.692][v][vo/opengl] OSD borders: l=0 t=0 r=0 b=0
[   0.692][v][vo/opengl] Video borders: l=0 t=0 r=0 b=0
[   5.969][v][vo/opengl] Resize: 960x480
[   5.969][v][vo/opengl] Window size: 960x480
[   5.969][v][vo/opengl] Video source: 960x480 (1:1)
[   5.969][v][vo/opengl] Video display: (0, 0) 960x480 -> (0, 0) 960x480
[   5.969][v][vo/opengl] Video scale: 1.000000/1.000000
[   5.969][v][vo/opengl] OSD borders: l=0 t=0 r=0 b=0
[   5.969][v][vo/opengl] Video borders: l=0 t=0 r=0 b=0

**Comment by Akemi** [comment] 2017-12-25 10:15
duplicate of #4926 and several others. fixed in git master and 0.28.

**Closed** 2017-12-25 10:20 UTC
