### ISSUE TITLE
Broken since MPV 0.31 Next spoken subtitles (CTRL+SHIFT LEFT/RIGHT ARROW)

### ISSUE THREAD

**Issue by j0sk** [mpv-player/mpv#7411] opened 2020-01-29 15:09 UTC
Hi,

On my Debian I found that next/previous spoken subtitles got broken after version 0.30. I tried to look Change Log but didn't find any reasons why it stopped working.

This CTRL+SHIFT+LEFT/RIGHT ARROW subtitle timing is the most important feature of the MPV for me. 

Here are the versions that I have tested on Debian:

0.30 version from **Debian Testing** repository **works**
0.31 version from **Debian Multimedia Testing** repository **doesn't work**
0.32 version from **Debian Unstable** repository **doesn't work**

On version 0.31 forward it shows SUBDELAY: xxxxx MS text on OSD but it doesn't affect at all to the subtitle timings. I hope you will have time look and fix this issue.

**Comment by Akemi** [comment] 2020-01-29 15:22
still works for me. since you ignored the issue template i am closing this.

**Closed by Akemi** 2020-01-29 15:22 UTC

**Comment by CounterPillow** [comment] 2020-01-29 16:37
Also can't reproduce.

**Comment by j0sk** [comment] 2020-01-29 18:49
Now I tested this also with OSX and same thing in there. If you press CTRL+SHIFT+LEFT/RIGHT ARROW you should see immediately the prev/next subtitle line. It works fine with MPV 0.30 but not 0.31+ . On those newest versions it only show the SUBDELAY: xxxxx MS on the OSD but that doesn't affect at all to the subtitles. Maybe I need to do video about this issue. This issue is real and I'm able to reproduce it on Linux and oSX.

**Comment by CounterPillow** [comment] 2020-01-29 19:00
>Maybe I need to do video about this issue. This issue is real and I'm able to reproduce it on Linux and oSX.

no you need to follow the issue template. the thing you ignored. the thing we want you to fill out so we can actually look into it.

**Comment by lazaronixon** [comment] 2021-09-12 04:44
ON OSX USE (LEFT CTRL) + (RIGHT OPTION) + LEFT/RIGHT
