### ISSUE TITLE
Videos with wmapro audio tracks glitch completely

### ISSUE THREAD

**Issue by Nogooduser** [mpv-player/mpv#8248] opened 2020-11-08 01:10 UTC
### Important Information

Provide following Information:
- mpv version being used is the latest version by shinchiro available [here](https://sourceforge.net/projects/mpv-player-windows/files/64bit/)
- OS: Windows 10
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/
- Unknown which version introduced the problem, but I can confirm the stable version available in the source above does not have the problem
- Screenshot. I believe one is enough, as it's always the same kind of visual glitch.

![](https://lewd.cat/64c582miydaq.jpg)

### Reproduction steps

Playing any .wmv file with wmapro audio causes the issue at some point. I have tested .wmv files with other audio codecs and the issue does not occur, which is what led me to conclude the audio format is the problem.

--no-config doesn't affect it, and as stated above, using a fresh stable release fixes it, meaning this is an issue that was later introduced, but I can't pinpoint when.

I can also guarantee the files are not corrupted because I played them with no problems in mpc-hc.

### Expected behavior

Video should play with no problems.

### Actual behavior

Video glitches out a lot with audio freezing/cutting and the image being obstructed by visual glitches.

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/5505722/log.txt)

### Sample files

I don't have any video files I can share because this was tested on pornographic content (the screenshot above is from a safe scene), but I am confident this issue should be reproducible if the wmv video contains a wmapro audio track.

**Comment by CounterPillow** [comment] 2020-11-08 01:24
Probably related to the audio refactoring.

> I don't have any video files I can share because this was tested on pornographic content

We've had people submit porn as samples before. We won't judge. You can use the first few megabytes or whatever to avoid sharing the whole thing.

**Comment by Nogooduser** [comment] 2020-11-08 02:26
Well, after looking around I managed to find a safe scene so [here](https://lewd.cat/kum9q1udo64n.wmv) (should be SFW but warning just in case) is a small clip from a file that's giving me issues. I confirmed that clip also causes the issue.

Reproducing the issue should be as simple as playing the file. Even if the videos plays normally at first, if you just seek around it should immediately start glitching out and not working properly.

**Comment by laichiaheng** [comment] 2020-11-08 03:47
Not only happens on Windows, but also happens on Linux.
CPU: Ryzen7 3700X
GPU: AMD RX580
Kernel: 5.9.6-1-MANJARO

**Comment by Akemi** [comment] 2020-11-08 11:09
i tired the commit before https://github.com/mpv-player/mpv/commit/b74c09efbf7c6969fc053265f72cc0501b840ce1 the audio refactor and i can still reproduce those glitches. they might be a bit less severe but i still get the audio jumping around and broken video frames. still get the invalid PTS and keyframe errors and warnings. maybe it's an ffmpeg issue?

```
Invalid audio PTS: 7.638079 -> 7.313000
(...) AV: 00:00:12 / 00:00:22 (56%) A-V:  0.000 DS: 2.000/0
Invalid audio PTS: 7.638079 -> 10.332000
Invalid audio PTS: 10.703519 -> 7.313000
(...) AV: 00:00:16 / 00:00:22 (73%) A-V:  0.000 DS: 2.000/0
Invalid audio PTS: 12.561079 -> 13.350000
Invalid audio PTS: 14.093039 -> 12.236000
AV: 00:00:08 / 00:00:22 (37%) A-V:  0.000 DS: 2.000/0
Invalid audio PTS: 7.638079 -> 18.227000
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
AV: 00:00:08 / 00:00:22 (37%) A-V:  0.000 DS: 3.000/0
Invalid audio PTS: 8.381079 -> 18.587000
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
AV: 00:00:07 / 00:00:22 (32%) A-V: -0.015 DS: 2.583/0
Invalid audio PTS: 7.638079 -> 19.016000

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:00:07 / 00:00:22 (33%) A-V: 11.362 DS: 2.615/0
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
AV: 00:00:08 / 00:00:22 (36%) A-V: -0.005 DS: 2.600/0
Invalid audio PTS: 8.381079 -> 7.313000

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:00:08 / 00:00:22 (39%) A-V: -0.001 DS: 4.529/0
Invalid audio PTS: 9.170519 -> 7.313000
(...) AV: 00:00:16 / 00:00:22 (71%) A-V:  0.000 DS: 2.000/0
Invalid audio PTS: 12.561079 -> 10.704000
Invalid audio PTS: 13.721519 -> 12.236000
(...) AV: 00:00:07 / 00:00:22 (32%) A-V:  0.000 DS: 3.000/0
Invalid audio PTS: 2.715079 -> 17.483000
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
(...) AV: 00:00:07 / 00:00:22 (32%) A-V:  0.000 DS: 2.000/0
Invalid audio PTS: 3.458079 -> 17.855000
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
(...) AV: 00:00:07 / 00:00:22 (32%) A-V:  0.000 DS: 3.000/0
Invalid audio PTS: 4.248079 -> 18.227000
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
(...) AV: 00:00:07 / 00:00:22 (32%) A-V:  0.000 DS: 2.000/0
Invalid audio PTS: 4.991079 -> 18.587000
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
(...) AV: 00:00:07 / 00:00:22 (32%) A-V:  0.000 DS: 3.000/0
Invalid audio PTS: 5.734079 -> 19.016000
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
(...) AV: 00:00:07 / 00:00:22 (32%) A-V:  0.000 DS: 2.000/0
Invalid audio PTS: 6.477079 -> 19.376000
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
(...) AV: 00:00:07 / 00:00:22 (32%) A-V:  0.000 DS: 3.000/0
Invalid audio PTS: 7.267079 -> 19.759000
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
AV: 00:00:07 / 00:00:22 (34%) A-V: -0.034 DS: 2.500/0
Invalid audio PTS: 7.998079 -> 20.131000

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:00:07 / 00:00:22 (34%) A-V: 12.109 DS: 3.000/0
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
AV: 00:00:08 / 00:00:22 (37%) A-V: -0.005 DS: 2.615/0
Invalid audio PTS: 8.741079 -> 20.502000

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:00:08 / 00:00:22 (37%) A-V: 11.756 DS: 2.571/0
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
AV: 00:00:09 / 00:00:22 (41%) A-V: -0.012 DS: 2.588/0
Invalid audio PTS: 9.542079 -> 2.390000
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
AV: 00:00:09 / 00:00:22 (44%) A-V: -0.002 DS: 2.786/0
Invalid audio PTS: 10.285079 -> 2.762000

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:00:10 / 00:00:22 (44%) A-V: -7.526 DS: 2.733/0
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
AV: 00:00:10 / 00:00:22 (47%) A-V: -0.004 DS: 2.600/0
Invalid audio PTS: 11.029079 -> 3.133000

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:00:10 / 00:00:22 (47%) A-V: -7.900 DS: 2.562/0
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
AV: 00:00:11 / 00:00:22 (50%) A-V: -0.011 DS: 2.667/0
Invalid audio PTS: 11.771079 -> 3.505000
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
AV: 00:00:12 / 00:00:22 (54%) A-V: -0.004 DS: 2.625/0
Invalid audio PTS: 12.561079 -> 3.923000
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
AV: 00:00:13 / 00:00:22 (57%) A-V: -0.012 DS: 2.667/0
Invalid audio PTS: 13.303079 -> 4.294000

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:00:13 / 00:00:22 (57%) A-V: -9.020 DS: 2.688/0
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
(...) AV: 00:00:16 / 00:00:22 (74%) A-V:  0.000 DS: 2.000/0
Invalid audio PTS: 12.561079 -> 4.666000
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
(...) AV: 00:00:16 / 00:00:22 (74%) A-V:  0.000 DS: 3.000/0
Invalid audio PTS: 13.303079 -> 5.037000
Reset playback due to audio timestamp reset.
(...) AV: 00:00:16 / 00:00:22 (74%) A-V:  0.000 DS: 2.000/0
Invalid audio PTS: 14.046079 -> 5.409000
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
(...) AV: 00:00:16 / 00:00:22 (74%) A-V:  0.000 DS: 3.000/0
Invalid audio PTS: 14.790079 -> 5.781000
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
(...) AV: 00:00:16 / 00:00:22 (74%) A-V:  0.000 DS: 2.000/0
Invalid audio PTS: 15.580079 -> 6.152000
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
(...) AV: 00:00:16 / 00:00:22 (74%) A-V:  0.000 DS: 3.000/0
Invalid audio PTS: 16.311079 -> 6.523000
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
(...) AV: 00:00:16 / 00:00:22 (74%) A-V:  0.000 DS: 2.000/0
Invalid audio PTS: 17.065079 -> 6.942000
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
AV: 00:00:17 / 00:00:22 (77%) A-V:  0.003 DS: 2.833/0
Invalid audio PTS: 17.808079 -> 7.313000
Reset playback due to audio timestamp reset.
[ffmpeg/video] wmv3: warning: first frame is no keyframe
```

**Comment by richardpl** [comment] 2020-11-08 11:20
Yes, certain FFmpeg developer likes to break things.

**Comment by Akemi** [comment] 2020-11-08 11:39
that's certainly not what i was implying. regressions are always possible and not wanted.

**Comment by jeeb** [comment] 2020-11-08 11:42
Funny, with my current build on Windows this seems to be OK? I do get one message about A/V desync around the 2 second mark, but otherwise a-OK with `mpv --no-config Video\mpv_8248_sample\kum9q1udo64n.wmv`

Build info:
```
[cplayer] mpv 0.32.0-791-g73be20143e Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sat Oct 31 02:24:29 EET 2020
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       56.60.100
[cplayer]    libavcodec      58.112.100
[cplayer]    libavformat     58.64.100
[cplayer]    libswscale      5.8.100
[cplayer]    libavfilter     7.88.100
[cplayer]    libswresample   3.8.100
[cplayer] FFmpeg version: N-99815-g45e3131c44
```

**Comment by Akemi** [comment] 2020-11-08 12:48
i tested it with an older mpv build i had lying around and there it worked. i built the same mpv version with my new dependencies and i could reproduce the problem. the ffmpeg version my old mpv version was linked to is:

```
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       56.23.101
[cplayer]    libavcodec      58.39.100
[cplayer]    libavformat     58.22.100
[cplayer]    libswscale      5.4.100
[cplayer]    libavfilter     7.43.100
[cplayer]    libswresample   3.4.100
[cplayer] ffmpeg version: git-2018-11-14-752659327d
```

the ffmpeg version my current mpv build is linked against.
```
[   0.009][v][cplayer] FFmpeg library versions:
[   0.009][v][cplayer]    libavutil       56.60.100
[   0.009][v][cplayer]    libavcodec      58.108.100
[   0.009][v][cplayer]    libavformat     58.59.100
[   0.009][v][cplayer]    libswscale      5.8.100
[   0.009][v][cplayer]    libavfilter     7.87.100
[   0.009][v][cplayer]    libswresample   3.8.100
[   0.009][v][cplayer] FFmpeg version: git-2020-10-01-13c7429
```

just built a current version of mpv and linked it against ffmpeg 752659327d and the issue doesn't occur.

so the regression was introduced in ffmpeg between https://github.com/FFmpeg/FFmpeg/commit/752659327d and https://github.com/FFmpeg/FFmpeg/commit/13c7429. maybe someone can bisect even further. marking this as an upstream problem for now.

**Comment by mkver** [comment] 2020-11-09 00:06
Bisecting leads me to [FFmpeg/FFmpeg@022a12b306ab2096e6ac9fc9b149828a849d65b2](https://github.com/FFmpeg/FFmpeg/commit/022a12b306ab2096e6ac9fc9b149828a849d65b2) as the first bad commit.

**Comment by jeeb** [comment] 2020-11-09 17:21
https://patchwork.ffmpeg.org/project/ffmpeg/patch/20201109131341.1699-1-jamrial@gmail.com/

seems to fix it for me, noted that on the mailing list.

**Comment by jeeb** [comment] 2020-11-09 20:49
This was now applied to FFmpeg master as FFmpeg/FFmpeg@d2dcb113f8e4e6e372007a354a600e6c2579ea8b . So this issue should now be fixed.

**Comment by Akemi** [comment] 2020-11-09 22:44
can confirm it being fixed.

**Closed by Akemi** 2020-11-09 22:44 UTC
Labels: os:win, upstream:ffmpeg
