### ISSUE TITLE
No audio output if I enable video-sync=display-resample

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#13664] opened 2024-03-08 03:17 UTC
### Important Information

Provide following Information:
- mpv version
```
mpv v0.37.0-514-g78447c4b91 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
libplacebo version: v7.347.0 (v6.338.0-97-g2f06c045)
FFmpeg version: N-114050-geb7d019b32
FFmpeg library versions:
   libavutil       59.0.100
   libavcodec      61.0.100
   libavformat     61.0.100
   libswscale      8.0.100
   libavfilter     10.0.100
   libswresample   5.0.100
```
- Linux Distribution and Version
Arch
- Source of the mpv binary
AUR
- If known which version of mpv introduced the problem
I don't remember
- Window Manager and version
Mutter 45.4
- GPU model, driver and version
Mesa Gallium driver 24.0.2-arch1.2 for AMD Radeon RX 6750 XT (radeonsi, navi22, LLVM 17.0.6, DRM 3.57, 6.7.8-zen1-1-zen)
- Possible screenshot or video of visual glitches
![圖片](https://github.com/mpv-player/mpv/assets/9532105/900525ef-ff21-4b16-b314-06664673a245)

### Reproduction steps

Play the video with --video-sync=display-resample

### Expected behavior
Normal audio output
### Actual behavior
No audio output
### Log file
[display-resample.txt](https://github.com/mpv-player/mpv/files/14532785/display-resample.txt)

### Sample files
Every video.

**Comment by CounterPillow** [comment] 2024-03-08 03:18
Duplicate of https://github.com/mpv-player/mpv/issues/13662

**Closed** 2024-03-08 03:33 UTC
Labels: os:linux
