### ISSUE TITLE
windows volume control

### ISSUE THREAD

**Issue by MammothJerk** [mpv-player/mpv#2077] opened 2015-06-27 23:25 UTC
i havent updated mpv for a while but when i did yesterday i noticed that when changing volume on my keyboard it changes the volume on mpv aswell if its in focus.

this results in BOTH windows and mpv changing volume at the same time.

i like the previous way much better where you changed the mpv volume on the 9 and 0 keys.

is there a way i can change this back?

**Comment by kevmitch** [comment] 2015-06-27 23:28
duplicate of #2041

**Comment by MammothJerk** [comment] 2015-06-28 00:15
that topic didnt seem to solve anything though

**Comment by MammothJerk** [comment] 2015-06-28 03:37
You can change the volume keys to be ignored by creating an input.conf text file in the mpv folder where mpv.exe is (or Appdata\Roaming\mpv) and adding these lines to it:

VOLUME_UP ignore
VOLUME_DOWN ignore

thanks to @Awakened0

**Comment by wm4** [comment] 2015-06-28 11:25
The mapping was removed again. You just need to wait for a new build.

**Closed by wm4** 2015-06-28 11:25 UTC
