### ISSUE TITLE
ytdl_hook lua script 

### ISSUE THREAD

**Issue by kaymio** [mpv-player/mpv#4728] opened 2017-08-07 16:37 UTC
### mpv version and platform
mpv 1:0.26.0-3 on Arch Linux

### Reproduction steps

Start a youtube link via CLI or D&D

### Expected behavior

Videostream is starting (playing files is no problem)

### Actual behavior

Going back to idle in most cases. After a reboot and after resuming to an earlier version of ffmpeg it works most of the times and after one or two videos it stops working again. 

Downgrading ffmpeg (1:3.3.3-1 => 1:3.3.2-2) helps.
pacman -U /var/cache/pacman/pkg/ffmpeg-1:3.3.2-2-x86_64.pkg.tar.xz

This worked for a few hours. Then the problem started again.

### Log file

Output with mpv -msg-level=ytdl_hook=debug https://pastebin.com/c2SFgL7M

Outputfile 

This time it worked -_- https://pastebin.com/PY5QSsLt

This time it didn't https://pastebin.com/KHPu1NAH

**Comment by CounterPillow** [comment] 2017-08-07 17:05
Probably related to https://github.com/mpv-player/mpv/commit/2b83f7e391ab68b23602e89b97ebc07ca09d8e7c so either try using the latest version of mpv from git or downgrade your youtube-dl.

**Comment by kaymio** [comment] 2017-08-07 17:10
This is output after downgrading youtube-dl

https://pastebin.com/PSd4KckH

**Comment by wiiaboo** [comment] 2017-08-07 17:14
Seems fine?

**Comment by wiiaboo** [comment] 2017-08-07 17:16
You can also download ytdl_hook.lua from git master and use it until there's a new release.

**Comment by kaymio** [comment] 2017-08-07 17:16
Yes I know, but before that I downgraded mpv, ffmpeg (because it coincidentally was the last related update). Now it's fine. Thank you.

**Comment by wiiaboo** [comment] 2017-08-07 17:18
Fixed in 2b83f7e391ab68b23602e89b97ebc07ca09d8e7c. Issue is from backwards-incompatible change in youtube-dl.

**Closed by wiiaboo** 2017-08-07 17:18 UTC

**Comment by Joseph65** [comment] 2017-08-10 17:34
how do i install with pip the youtube-dl v2017.08.06 i have the latest version 2017.08.09

**Comment by sebma** [comment] 2017-08-17 17:22
Where is the `scripts` on Ubuntu/Debian ?

If I add `no-ytdl` to `mpv.conf`, I won't be able to play videos from other sites then YouTube.

Is there a per site setting to disable ytdl only on YouTube ?

**Comment by kaistian** [comment] 2017-08-17 17:28
> Where is the scripts on Ubuntu/Debian ?

`~/.config/mpv/scripts` you probably need to create it.

**Comment by wiiaboo** [comment] 2017-08-17 17:41
`no-ytdl` is to avoid loading the broken built-in ytdl_hook.lua. That's why you download the fixed one and used meanwhile until there's a new release.

**Comment by rohieb** [comment] 2017-08-30 22:06
Just for the record and searchability, I came here because I only get `[ytdl_hook] Got empty playlist, nothing to play` when playing Youtube playlists, and the solution in https://github.com/mpv-player/mpv/issues/4728#issuecomment-320725058 also fixed this :)

**Comment by wiiaboo** [comment] 2017-08-30 22:08
What's the URL that returned that? Might be a different issue.

**Comment by rohieb** [comment] 2017-08-30 22:24
Huh, indeed another issue. It worked once, but when I wanted to test it again, it does no longer work. Downloaded ytldl_hook from master to `~/.config/mpv/scripts/ytdl_hook_from_master.lua`, then:
```
$ /usr/bin/mpv --no-ytdl --msg-level=ytdl_hook_from_master=trace https://www.youtube.com/c/clickspring
[ytdl_hook_from_master] Loading lua script /home/rohieb/.config/mpv/scripts/ytdl_hook_from_master.lua...
[ytdl_hook_from_master] loading mp.defaults
[ytdl_hook_from_master] loading file /home/rohieb/.config/mpv/scripts/ytdl_hook_from_master.lua
[ytdl_hook_from_master] reading options for ytdl_hook_from_master 
[ytdl_hook_from_master] lua-settings/ytdl_hook_from_master.conf not found. 
Playing: https://www.youtube.com/c/clickspring
[ytdl_hook_from_master] Running: youtube-dl --no-warnings -J --flat-playlist --sub-format ass/srt/best --no-playlist --format 95/94/93/22/18/http-720p/http-540p/http-360p/deu-h264-sd/eng-h264-sd/best[protocol!=f4m] --all-subs -- https://www.youtube.com/c/clickspring 
[ytdl_hook_from_master] youtube-dl succeeded! 
[ytdl_hook_from_master] ytdl parsing took 0.001007 seconds 
[ytdl_hook_from_master] Got empty playlist, nothing to play. 
[ffmpeg] tls: The TLS connection was non-properly terminated.
Failed to recognize file format.


Exiting... (Errors when loading file)
[ytdl_hook_from_master] Exiting...
```

I've had issues in the past with the "empty playlist" error, but it usually went away when I tried again.
With youtube-dl 2017.08.27.1, mpv 0.26.0, from Debian testing. ffmpeg library versions:
   * libavutil       55.58.100
   * libavcodec      57.89.100
   * libavformat     57.71.100
   * libswscale      4.6.100
   * libavfilter     6.82.100
   * libswresample   2.7.100
   * ffmpeg version: 3.3.3-1

**Comment by wiiaboo** [comment] 2017-08-30 22:31
With that playlist, even youtube-dl itself is returning an empty playlist, so it seems like a youtube-dl issue.

**Comment by rohieb** [comment] 2017-08-30 22:42
Mmh yes, there are multiple issues over at https://github.com/rg3/youtube-dl/issues relating to Youtube playlists/users not being able to be played, probably due to the recent design change for the web site.

**Comment by prog-amateur** [comment] 2018-02-11 12:22
Hello, first of all, thank you for your help, I have been able to solve the ytdl_hook lua. 

My intension is not to reopen this thread, but just to have clarify an information : 
I did `sudo pip install youtube_dl==2017.07.30.1`, now it works, but I am afraid that if one day, there is a security patch on youtube-dl, I will be forced to upgrade and not be able to watch all youtube videos like I am doing now. 

My question is about the first option : 

> download the fixed ytdl_hook.lua, place in your scripts directory and add `no-ytdl` to `mpv.conf`, so the fixed version gets used instead of the built-in

I don't have any folder called `script` : please, where shall I put the file ? is `~/.config/mpv/` correct ?

Thank you very much

**Comment by CounterPillow** [comment] 2018-02-11 12:30
@prog-amateur you create a folder called `scripts` inside `~/.config/mpv/`, and place the lua script inside there.

**Comment by prog-amateur** [comment] 2018-02-12 17:17
Thank you very much @CounterPillow ! I'll try that way.

**Comment by prog-amateur** [comment] 2018-02-18 15:50
Just a quick feedback, I have done as explained, but it doesn't work. So I stay with `sudo pip install youtube_dl==2017.07.30.1` which works well.

**Comment by potholiday** [comment] 2018-06-01 15:20
Mine was caused by `--ytdl-format=' '` playing with the format solved my problem

**Comment by RodrigoLeiteF** [comment] 2019-07-06 04:37
This is still an issue with the bleeding edge versions of both `mpv` and `youtube-dl` (git packages from the AUR). The workaround .lua file does not seem to work.

```
[rodrigo@rodrigo-arch ~]$ mpv --version
mpv 0.29.0-343-gc379950ce0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sat Jul  6 00:54:41 -03 2019
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: n4.1.3

[rodrigo@rodrigo-arch ~]$ youtube-dl --version
2019.07.02
```

**Comment by wiiaboo** [comment] 2019-07-06 12:48
What is still an issue?

**Comment by wiiaboo** [comment] 2019-07-06 12:50
Open a new issue then, don't ressurrect a two year old issue.
