### ISSUE TITLE
osc fails to start

### ISSUE THREAD

**Issue by dkociela** [mpv-player/mpv#1648] opened 2015-03-05 04:13 UTC
The moment I move the mouse cursor over the screen, this is my terminal output:

[cplayer] Run command: script_binding, flags=9, args=[osc/__keybinding1]
[osc]
[osc] stack traceback:
[osc]   mp.defaults:314: in function 'handler'
[osc]   mp.defaults:416: in function 'call_event_handlers'
[osc]   mp.defaults:452: in function 'dispatch_events'
[osc]   mp.defaults:409: in function <mp.defaults:408>
[osc]   [C]: in ?
[osc]   [C]: in ?
[osc] Lua error: mp.defaults:314: attempt to call global 'unpack' (a nil value)
[osc] Exiting...
[statusline] AV: 00:00:02 / 01:32:09 (0%) A-V: -0.000
[cplayer] Run command: script_binding, flags=9, args=[osc/__keybinding1]
[cplayer] Can't find script 'osc' when handling input.

Linux distro is SourceMage (smgl)  I've tried installing with the distro's package manager and manually with the same result. I've tried different versions and different tarballs, ditto for lua. Two other linux distros  and Windows 7 on the same box, all work fine. I've searched the internet with each line with no luck. I'm out of ideas.

**Comment by torque** [comment] 2015-03-05 04:56
Sounds like the problem is mpv was built against Lua 5.3. It changed a lot of things from Lua 5.2 and isn't well supported at the moment. 5.3 doesn't support the global `unpack` function, and 5.1 doesn't support `table.unpack` which is what it got moved to, so supporting both of them requires a shim. PR #1516 has some changes toward Lua 5.3 support, but it hasn't been merged yet and doesn't even appear to fix this particular issue.

I recommend complaining to whoever maintains the package for your distribution, and building it yourself with Lua 5.2 or 5.1.

**Comment by dkociela** [comment] 2015-03-05 15:13
Thanks for that suggestion but I did actually build it against Lua 5.2

**Comment by wm4** [comment] 2015-03-05 15:20
Can you post ldd mpv output?

**Comment by dkociela** [comment] 2015-03-05 15:21
Sorry for my ignorance, whats ldd?

**Comment by wm4** [comment] 2015-03-05 15:26
A command line tool that lists linked libraries.

**Comment by dkociela** [comment] 2015-03-05 15:29
linux-vdso.so.1 (0x00007fff352b1000)
        libdvdnav.so.4 => /usr/lib/libdvdnav.so.4 (0x00007f6e6c603000)
        libpthread.so.0 => /lib/libpthread.so.0 (0x00007f6e6c3e6000)
        libguess.so.1 => /usr/lib/libguess.so.1 (0x00007f6e6c1df000)
        libdvdread.so.4 => /usr/lib/libdvdread.so.4 (0x00007f6e6bfbf000)
        liblcms2.so.2 => /usr/lib/liblcms2.so.2 (0x00007f6e6bd71000)
        libjpeg.so.8 => /usr/lib/libjpeg.so.8 (0x00007f6e6bb24000)
        libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f6e6b90f000)
        libavutil.so.52 => /usr/lib/libavutil.so.52 (0x00007f6e6b6db000)
        libavcodec.so.55 => /usr/lib/libavcodec.so.55 (0x00007f6e6a80e000)
        libavformat.so.55 => /usr/lib/libavformat.so.55 (0x00007f6e6a4bd000)
        libswscale.so.2 => /usr/lib/libswscale.so.2 (0x00007f6e6a252000)
        libXv.so.1 => /usr/lib/libXv.so.1 (0x00007f6e6a04d000)
        libenca.so.0 => /usr/lib/libenca.so.0 (0x00007f6e69e1d000)
        libuuid.so.1 => /lib/libuuid.so.1 (0x00007f6e69c1a000)
        librt.so.1 => /lib/librt.so.1 (0x00007f6e69a12000)
        libavfilter.so.4 => /usr/lib/libavfilter.so.4 (0x00007f6e6971c000)
        libasound.so.2 => /usr/lib/libasound.so.2 (0x00007f6e6944b000)
        libswresample.so.0 => /usr/lib/libswresample.so.0 (0x00007f6e69237000)
        libm.so.6 => /lib/libm.so.6 (0x00007f6e68faa000)
        libXinerama.so.1 => /usr/lib/libXinerama.so.1 (0x00007f6e68da8000)
        libdl.so.2 => /lib/libdl.so.2 (0x00007f6e68ba4000)
        libavdevice.so.55 => /usr/lib/libavdevice.so.55 (0x00007f6e68991000)
        libXrandr.so.2 => /usr/lib/libXrandr.so.2 (0x00007f6e68786000)
        libXss.so.1 => /usr/lib/libXss.so.1 (0x00007f6e68583000)
        libvdpau.so.1 => /usr/lib/libvdpau.so.1 (0x00007f6e68380000)
        libz.so.1 => /lib/libz.so.1 (0x00007f6e6816a000)
        liblua.so => /usr/lib/liblua.so (0x00007f6e67f40000)
        libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f6e67c24000)
        libGL.so.1 => /usr/lib/libGL.so.1 (0x00007f6e678cc000)
        libass.so.5 => /usr/lib/libass.so.5 (0x00007f6e676b3000)
        libc.so.6 => /lib/libc.so.6 (0x00007f6e6734c000)
        /lib/ld-linux-x86-64.so.2 (0x00007f6e6c81c000)
        libmowgli.so.2 => /usr/lib/libmowgli.so.2 (0x00007f6e6713d000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f6e66f20000)
        libpthread-stubs.so.0 => /usr/lib/libpthread-stubs.so.0 (0x00007f6e66d1f000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f6e66b1c000)
        libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f6e66917000)
        libx264.so.142 => /usr/lib/libx264.so.142 (0x00007f6e665c3000)
        libopenjpeg.so.5 => /usr/lib/libopenjpeg.so.5 (0x00007f6e663a4000)
        libfaac.so.0 => /usr/lib/libfaac.so.0 (0x00007f6e66195000)
        libssl.so.0.9.8 => /usr/lib/libssl.so.0.9.8 (0x00007f6e65f4a000)
        libcrypto.so.0.9.8 => /usr/lib/libcrypto.so.0.9.8 (0x00007f6e65beb000)
        libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f6e659d6000)
        libpostproc.so.52 => /usr/lib/libpostproc.so.52 (0x00007f6e657c1000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f6e6553e000)
        libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007f6e65308000)
        libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0x00007f6e65102000)
        libcdio_paranoia.so.1 => /usr/lib/libcdio_paranoia.so.1 (0x00007f6e64efc000)
        libcdio_cdda.so.1 => /usr/lib/libcdio_cdda.so.1 (0x00007f6e64cf6000)
        libXrender.so.1 => /usr/lib/libXrender.so.1 (0x00007f6e64ae9000)
        libnvidia-tls.so.346.35 => /usr/lib/tls/libnvidia-tls.so.346.35 (0x00007f6e648e6000)
        libnvidia-glcore.so.346.35 => /usr/lib/libnvidia-glcore.so.346.35 (0x00007f6e61c0e000)
        libfribidi.so.0 => /usr/lib/libfribidi.so.0 (0x00007f6e619f8000)
        libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007f6e617b4000)
        libgmp.so.3 => /lib/libgmp.so.3 (0x00007f6e6156b000)
        libpng12.so.0 => /usr/lib/libpng12.so.0 (0x00007f6e61349000)
        libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f6e61062000)
        libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f6e60e0a000)
        libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007f6e60bea000)
        libcdio.so.15 => /usr/lib/libcdio.so.15 (0x00007f6e609c7000)

**Comment by wm4** [comment] 2015-03-05 15:58
Still can't see what Lua version it's using.

Anyway, I think I found the issue. The mpv code apparently relies on LUA_COMPAT_UNPACK being defined at compilation of Lua 5.2, which is enabled by default, but can be disabled.

**Comment by dkociela** [comment] 2015-03-05 16:05
Great, I'll try that and report back. Thank you.

**Comment by dkociela** [comment] 2015-03-05 16:18
Again, ignorance, but would I add LUA_COMPAT_UNPACK to the Lua Makefile and what value should it have?

**Comment by wm4** [comment] 2015-03-05 16:24
You need to change ``luaconf.h``.

**Comment by dkociela** [comment] 2015-03-05 16:29
@@ LUA_COMPAT_UNPACK controls the presence of global 'unpack'.
** You can replace it with 'table.unpack'.

Thanks for your patience, should I just add "table.unpack" to the file?

**Comment by wm4** [comment] 2015-03-05 16:43
That would work too. (As soon as it works for you and other potential issues are resolved, I'd add a compat-hack anyway.)

**Comment by dkociela** [comment] 2015-03-05 22:03
I couldn't figure out how to:
"** You can replace it with 'table.unpack'."
But I found this in a search:
"Check the versions of Lua you are using. In Lua 5.1, unpack was a global, but in 5.2 it's been moved to table.unpack"
So I took the coward's way out and rebuilt with lua 5.1...works fine with that.
I'd still like to know how to do it.

**Comment by torque** [comment] 2015-03-06 03:40
With the Lua 5.2.3 source downloaded from [the Lua ftp](http://www.lua.org/ftp/), it should build with 5.1 compatibility by default. `src/Makefile` has on line 10: `CFLAGS= -O2 -Wall -DLUA_COMPAT_ALL $(SYSCFLAGS) $(MYCFLAGS)`. The flag `-DLUA_COMPAT_ALL` enables `LUA_COMPAT_UNPACK`, but if you want to make completely super sure it is defined, you can add `-DLUA_COMPAT_UNPACK` to that line.


Otherwise, to fix this from the mpv end, you'd need to modify [`player/lua/defaults.lua` line 314](https://github.com/mpv-player/mpv/blob/master/player/lua/defaults.lua#L314) to be `handler(table.unpack(ev.args, 2))` (or if you want to be able to use 5.1 or 5.2, something like  `unpack = unpack or table.unpack` to the top of the file).

Hopefully that clears things up.

**Comment by dkociela** [comment] 2015-03-06 05:23
I've kept messing with this and I've been inching closer (slowly). That definitely clears things up. A couple of test runs and I'll close this issue. 

Thank you for that (and your first response), very much appreciated.

**Comment by wm4** [comment] 2015-03-06 09:29
> (or if you want to be able to use 5.1 or 5.2, just add something like unpack = unpack or table.unpack to the top of the file instead).

And that's what I'm going to do. (Unless you submit a PR?)

**Closed** 2015-03-06 11:29 UTC
