### ISSUE TITLE
vo=gpu-next with gpu-api=opengl creates artifacts and can't watch fullscreen

### ISSUE THREAD

**Issue by 0pLuS0** [mpv-player/mpv#11551] opened 2023-04-05 12:18 UTC
### Important Information

Provide following Information:
- mpv 0.35.1
- Slackware 15.0
- compiled mpv from source
- mpv 0.35.1
- Openbox 3.6.1
- nvidia-driver-525.78.01

### Reproduction steps

This issue doesn't happen with --no-config, this is an issue when using  ```vo=gpu-next``` with ```gpu-api=opengl```.

### Expected behavior

I should be able to use ```vo=gpu-next``` with ```gpu-api=opengl```?

### Actual behavior

Using ```vo=gpu-next``` with ```gpu-api=opengl```, mpv has artifacts displaying on the video during play, if I run the UI not fullscreen. If I try and run mpv fullscreen nothing appears, just a blank black screen.

```vo=gpu-next``` with ```gpu-api=vulkan``` works just fine!

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/11158548/output.txt)

### Screen shots

Here are a few screen shots, showing artifacts on the video when running mpv not fullscreen.

![1 mpv](https://user-images.githubusercontent.com/36190223/230076871-8b662725-b891-4e39-93b4-86c5c6ab83d9.jpg)

![2 mpv](https://user-images.githubusercontent.com/36190223/230076914-a3a6eca9-e885-4e08-a188-c630c3ed8137.jpg)

![3 mpv](https://user-images.githubusercontent.com/36190223/230076936-57108a22-b638-4a42-a814-47077ffaad42.jpg)

**Comment by haasn** [comment] 2023-04-05 13:49
Possibly duplicate of #11499?

**Comment by philipl** [comment] 2023-06-11 04:12
Yes, closing as a dupe.

**Closed by philipl** 2023-06-11 04:12 UTC
Labels: os:linux
