### ISSUE TITLE
YouTube stylized subtitles are not supported

### ISSUE THREAD

**Issue by Bokk0** [mpv-player/mpv#11798] opened 2023-06-16 16:24 UTC
YouTube stylized subtitles are displayed as "plain" ones
![1](https://github.com/mpv-player/mpv/assets/136835850/b52354da-671c-4d73-96bb-b82cdc5e1603)
Or should I report this to FFmpeg?

https://youtu.be/x8VYWazR5mE

**Comment by CounterPillow** [comment] 2023-06-16 16:25
likely duplicate of #7214

**Closed** 2023-06-16 18:45 UTC
Labels: meta:duplicate
