### ISSUE TITLE
not the whole frame is drawn when opening a video paused

### ISSUE THREAD

**Issue by codl** [mpv-player/mpv#4125] opened 2017-02-08 14:45 UTC
### mpv version and platform

git master on linux

```
mpv git-c94ede9e62 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Wed Feb  8 15:11:37 CET 2017
ffmpeg library versions:
   libavutil       55.34.100
   libavcodec      57.64.101
   libavformat     57.56.100
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.2
```

### Reproduction steps

Opening a video with pause=yes

```
$ mpv file.mp4 --no-config --pause=yes
```

### Expected behavior

The first frame of the video is shown.

### Actual behavior

Only the top left corner of the first frame is shown. This issue disappears as soon as the video is unpaused, the window is resized, or the osc is shown.

![c93f116f-f2d5-40d5-a000-d333d1f1b064](https://cloud.githubusercontent.com/assets/315139/22741676/4497d036-ee14-11e6-91ca-db27108675c4.png)

### Log file

https://gist.github.com/codl/ad5755c6ebe9db056e5c0c42a05e3466

**Comment by occivink** [comment] 2017-02-08 16:32
Looks like a duplicate of #4047

**Comment by lachs0r** [comment] 2017-07-22 04:42
Indeed.

**Closed by lachs0r** 2017-07-22 04:42 UTC
