### ISSUE TITLE
Constantly brightening and dimming of image, and "lagging" video on 4k content

### ISSUE THREAD

**Issue by Burt93** [mpv-player/mpv#6403] opened 2018-12-23 19:35 UTC
Video proof: https://streamable.com/347r2

### mpv version and platform

Windows 10, latest mpv-git : x86_64-20181216-git

Ryzen 2 2700, rx 580, 16gb ram

### Expected behavior

Smooth reproduction with this hardware

### Actual behavior

Images get abruptly brighter and dimmer on 4k content when scenes changes, also video lags as you can see when the girl walks

### Log file

https://pastebin.com/4mDYh5Xe

### Sample files

Samsung: Travel With My Pet HDR

**Comment by CounterPillow** [comment] 2018-12-23 19:52
A full log (generated with `--log-file=nameoflog.txt`) might help debug this further.

The flickering in brightness may be due to `hdr-compute-peak` misbehaving (try `--hdr-compute-peak=no` to see if it disappears), which could be related to the shader compilation error messages I guess?

**Comment by Burt93** [comment] 2018-12-23 20:17
> 
> 
> A full log (generated with `--log-file=nameoflog.txt`) might help debug this further.
> 
> The flickering in brightness may be due to `hdr-compute-peak` misbehaving (try `--hdr-compute-peak=no` to see if it disappears), which could be related to the shader compilation error messages I guess?

Ok i updated mai post with the rigth log https://pastebin.com/4mDYh5Xe . With --hdr-compute-peak=no there a re no more changes in brightness, but i think there are artifacts? [(look the dome in this pic)](https://imgur.com/U7rb7sB)

(Maybe out of topic) I noticed the same image is [really different between mpv and MPC-HC/VLC/MPC-BE](https://imgur.com/U7rb7sB), is this expected?

**Comment by CounterPillow** [comment] 2018-12-23 21:04
>(Maybe out of topic) I noticed the same image is really different between mpv and MPC-HC/VLC/MPC-BE, is this expected?

To some degree yes, to display HDR content on an SDR display a method called "tone mapping" is used, of which there are different variants. In mpv, you can fine-tune these with `--tone-mapping` and `--tone-mapping-param` as well as `--tone-mapping-desaturate`.

Looks like direct rendering is failing which may explain the performance issues at 40k60. Does anyone know whether this is normal with AMD GPUs on Windows?

**Comment by haasn** [comment] 2018-12-23 21:21
Primary issue is a duplicate of #5960.

**Closed by haasn** 2018-12-23 21:21 UTC

**Comment by CounterPillow** [comment] 2018-12-24 11:06
hwdec might also help due to the lack of DR, if I understand how it works correctly, since the decoded video frame will already be on the GPU.
