### ISSUE TITLE
[win]some problem on osd-border with  06033df

### ISSUE THREAD

**Issue by kesdoputr** [mpv-player/mpv#7900] opened 2020-07-11 11:40 UTC
### Important Information

Provide following Information:
- mpv version
mpv x64 git `06033df`
- Windows Version
windows7 SP1 x64
- Source of the mpv binary
https://sourceforge.net/projects/mpv-player-windows/files/64bit/
`mpv-x86_64-20200711-git-06033df.7z`
- If known which version of mpv introduced the problem
problem occur on 
`mpv-x86_64-20200711-git-06033df.7z`
it's normal on
`mpv-x86_64-20200705-git-8fbc4b1.7z`

### Reproduction steps
I found osd-border too slim when i use 06033df, so i try --no-config and found still the same
with 8fbc4b1
![mpv-shot0001](https://user-images.githubusercontent.com/16981364/87223202-8668e000-c3ad-11ea-8679-0c63dcf7bae9.jpg)
![mpv-shot0001](https://user-images.githubusercontent.com/16981364/87223228-ca5be500-c3ad-11ea-8288-f58de350cf15.jpg)

with 06033df
![mpv-shot0002](https://user-images.githubusercontent.com/16981364/87223204-9680bf80-c3ad-11ea-9afd-594d4e3c9bdf.jpg)
![mpv-shot0001](https://user-images.githubusercontent.com/16981364/87223257-df387880-c3ad-11ea-8dcb-49400d6fa492.jpg)

I can't see clear with the newest build with 06033df ,thanks for your reading.

**Comment by avih** [comment] 2020-07-11 11:57
>     * Source of the mpv binary
>       https://sourceforge.net/projects/mpv-player-windows/files/64bit/

I can confirm that mpv-x86_64-20200711-git-06033df from that location does have thinner OSD outline than my build, but then I updated my build to 06033df, and I don't see the same issue in it, so I don't think it's an mpv issue.

@shinchiro what changed between your 20200705-git-8fbc4b1 and 20200711-git-06033df builds other than mpv itself? maybe libass? freetype?

**Comment by CounterPillow** [comment] 2020-07-11 13:00
I also see a thinner OSD outline on Linux with 0.32.0-577-gb961efb0af compiled with mpv-build, possibly a libass issue?

**Comment by avih** [comment] 2020-07-11 13:12
That's the only libass commit since May, it's from 4 days ago, and does seem relevant:
https://github.com/libass/libass/commit/75b1e54634a1d7e0c3204b09e27a4f887a03e4f4

**Comment by shinchiro** [comment] 2020-07-11 13:26
I can confirm this is ffmpeg bug. I try build with https://github.com/FFmpeg/FFmpeg/commit/73757577cb6dbc08aa0b12294863a3cc9d91b26f and it didn't have thinner outline. So the faulty commit might start after that till today git commit

**Comment by avih** [comment] 2020-07-11 17:24
> I can confirm this is ffmpeg bug. I try build with [FFmpeg/FFmpeg@7375757](https://github.com/FFmpeg/FFmpeg/commit/73757577cb6dbc08aa0b12294863a3cc9d91b26f) and it didn't have thinner outline. So the faulty commit might start after that till today git commit

Are you 100% sure?

My I've updated only libass from `7959e61 compare: Fix millisecond zero padding` (committed June 15th) to `9f35fa9 Ignore leading space of lines in parsing` (current master, committed today), and I now get thinner OSD outline, while with the previous libass version it had thicker outline.

I.e. I'm pretty sure it's a libass thing and not an ffmpeg thing, unless by very unlikely coincidence recent ffmpeg also causes the same issue (I didn't try updating ffmpeg. my ffmpeg is `6c777a6 avformat/smoothstreaming: Forward errors from copying white/blacklists 2020-06-24`).

**Comment by avih** [comment] 2020-07-11 17:34
I've bisected it, and as far as I can tell the offending commit it https://github.com/libass/libass/commit/5575d2f727750966cb08502a3381e3441938f38f - which does seem exactly on point, and according to the commit message it fixes a compatibility issue with VSFilter.

**Closed** 2020-07-15 12:49 UTC
