### ISSUE TITLE
PNG screenshots differ in brightness/color from video.

### ISSUE THREAD

**Issue by z0z0z** [mpv-player/mpv#2051] opened 2015-06-16 20:18 UTC
mpv --no-config --screenshot-format=png video.mp4

Gives me this warning when saving a screenshot: "[ffmpeg] swscaler: full chroma interpolation for destination format 'rgb48be' not yet implemented"

The resulting screenshot has different brightness/color than the actual video. Here's an example: http://screenshotcomparison.com/comparison/131434

Tried both ffmpeg-2.7 and ffmpeg from git, same thing. Does not seem to make a difference what video/container format is being played, or what vo is being used.

**Comment by wm4** [comment] 2015-06-16 20:31
I think the warning means it loses precision, which is really not the point of this feature, but on the other hand should nothing have to do with the brightness change.

Does ``--screenshot-high-bit-depth=no`` change anything?
Does ``--screenshot-tag-colorspace=no``?

**Comment by z0z0z** [comment] 2015-06-16 20:43
screenshot-tag-colorspace=no

Gets rid of the issue.

**Comment by wm4** [comment] 2015-06-16 20:50
Then your browser/whatever doesn't support the corresponding tags correctly.

CC @haasn

**Comment by z0z0z** [comment] 2015-06-16 21:01
The difference in screenshots appears in Firefox, Chromium, and Eye of Gnome, but not GIMP, feh or mpv itself.

It might be the fault of that software for not supporting it, but should this be enabled by default?

**Comment by wm4** [comment] 2015-06-16 21:27
Yes, that's the big question.

**Comment by lachs0r** [comment] 2015-06-16 22:08
Note that if you set the suboptions `target-prim=bt.709:target-trc=srgb` to the opengl video output (i.e. pretend you have a true sRGB display), you should get the same result as with the screenshot function. If I recall correctly, anyway.

All of this actually works as intended and there isn’t a lack of compatibility in browsers—Firefox etc. do the right thing here. GIMP does not because GIMP disables color management by default.

The thing is that by supplying the colorspace tags, image viewers with support for color management have enough information to transform colors to your display’s colorspace—which is generally assumed to be sRGB if you do not have a color profile for it. Since software like GIMP does not do color management by default, it ignores the tags, and thus does not transform the colors.

So, if you do not set the options I’ve mentioned above, mpv is not configured to do any color management, which naturally results in different colors than what you would see if your display target had sRGB characteristics (which is what browsers assume).

Given properly color managed displays, screenshots taken with colorspace tags enabled will have consistent color reproduction everywhere, whereas without that option, there would be no guarantee.

This has little benefit for most users because most users have no idea what color management is. In that case, however, *both* results are wrong. You can’t get colors right if you don’t know how your monitor displays them.

**Comment by wm4** [comment] 2015-06-16 22:32
>All of this actually works as intended and there isn’t a lack of compatibility in browsers—Firefox etc. do the right thing here. GIMP does not because GIMP disables color management by default.

Oh, true. So what I said isn't entirely correct.

Still, you could argue that the png result, if displayed with something that reads the tag, is the correct reproduction of the output, because PC monitors are supposed to do sRGB.

**Comment by haasn** [comment] 2015-06-16 22:33
> Firefox etc. do the right thing here. GIMP does not because GIMP disables color management by default.

Notably, mpv does not color manage by default either. That's why you're seeing a difference - mpv itself is displaying the source video incorrectly, which is why the mpv output is too dark.

If you enable color management in mpv (eg. via target-prim=bt.709:target-trc=gamma2.2) then both images should appear identically in your browser.

**Comment by wm4** [comment] 2015-06-16 22:49
The 48 bit conversion warning was just fixed in ffmpeg.

**Comment by z0z0z** [comment] 2015-06-16 23:23
>mpv itself is displaying the source video incorrectly, which is why the mpv output is too dark.

I'm not saying this is incorrect, but the color managed output just looks like someone turned up the brightness and washed out the colors to me. I have a Dell U2212HM.

**Comment by haasn** [comment] 2015-06-18 04:35
> I'm not saying this is incorrect, but the color managed output just looks like someone turned up the brightness and washed out the colors to me. I have a Dell U2212HM.

That sounds like you were specifying a gamma curve that is a bad fit for your device. Values I suggest trying include ```gamma2.2```, ```bt.1886``` and ```srgb```. Chances are, one of the three will match your display.

**Comment by CounterPillow** [comment] 2015-06-20 16:04
Just to chime in about defaults and such: I've recently discovered while looking at my mpv screenshots that a lot of applications (notably Gwenview) ignore the PNG gAMA chunks which mpv appears to include in PNG screenshots by default.

**Closed** 2015-07-18 16:35 UTC

**Comment by Argon-** [comment] 2016-06-13 03:55
> (Or, on OS X, you can use gamma-auto to query available ambient light level sensor data to adjust the value automatically)

I just read that OSX is already doing this on its own in 10.11, so having mpv doing it as well might be diametrical.

It's hard to find detailed information about this... apparently in betas of 10.11 there used to be an `Ambient light compensation` option which was merged with `Automatically adjust brightness` before release. This is activated by default and it's no longer possible to disable the gamma adjustment without disabling the brightness adjustment (Well, removing the program doing the adjustment ofc works).

https://apple.stackexchange.com/questions/208433/why-is-auto-adjust-brightness-washing-out-my-retina-display-on-el-capitan

**Comment by haasn** [comment] 2016-06-13 04:22
Maybe. The behavior of gamma-auto in current mpv is sort of nonsensical either way. @pigoz and I had a talk about how to improve it but I don't think anything got merged yet in that regard.

The problem is that it's sort of arbitrary to really figure out what the “correct behavior” would be to begin with.

**Comment by G2G2G2G** [comment] 2021-08-17 11:42
@z0z0z  
> The difference in screenshots appears in Firefox, Chromium, and Eye of Gnome, but not GIMP, feh or mpv itself.
> 
> It might be the fault of that software for not supporting it, but should this be enabled by default?

yea it's still an issue, gimp doesn't have it because it ignores color tags. It's also an issue if you use just ffmpeg to extract a screenshot (which is probably where mpv gets the issue and what it originates from)

only way I've got it to actually work in all the programs is open it as gimp and re-save it with the "save color profile" works with jpg and png(lossless my ass)
So however ffmpeg saves the image, it doesn't have that "color profile" embedded or whatever, thus all the regular decoders (firefox, chromium, nomacs, gwenview, photos, etc) view it wrong
