### ISSUE TITLE
Fully hardware-accelerated thumbnail api support

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#11640] opened 2023-04-29 00:00 UTC

**Comment by hooke007** [comment] 2023-04-29 02:07
dup https://github.com/mpv-player/mpv/issues/6919 and more.

**Comment by Traneptora** [comment] 2023-04-29 11:23
I'm not going to mark it a duplicate of an issue that itself was closed as "I won't implement it" by wm4 since it's still a valid feature request.

**Comment by hooke007** [comment] 2023-04-29 18:03
So could we think the dev members changed their initial mind?

https://github.com/mpv-player/mpv/issues/3940#issuecomment-355507385

**Comment by Dudemanguy** [comment] 2023-04-30 21:54
The chances of anyone actually implementing this is pretty low, but it's a valid feature request imo.

**Closed as not planned** 2023-09-06 10:02 UTC
Labels: meta:feature-request

**Comment by GalaxySnail** [comment] 2023-09-06 13:35
What happened here? Why is this issue closed?
