### ISSUE TITLE
Linking libmpv with MSVC

### ISSUE THREAD

**Issue by dohisev** [mpv-player/mpv#5007] opened 2017-10-18 00:46 UTC
I downloaded the dev version from [http://mpv.srsfckn.biz/](http://mpv.srsfckn.biz/) and on VS2015 Developer Command Prompt I did this: `lib /def:../include/mpv/mpv.def /name:mpv-1.dll /out:mpv.lib /MACHINE:X86` the only problem is that I got a LOT of warnings:

```
../include/mpv/mpv.def(1) : warning LNK4017: mpv_client_api_version statement not supported for the target platform; ignored
../include/mpv/mpv.def(2) : warning LNK4017: mpv_client_name statement not supported for the target platform; ignored
../include/mpv/mpv.def(3) : warning LNK4017: mpv_command statement not supported for the target platform; ignored
../include/mpv/mpv.def(4) : warning LNK4017: mpv_command_async statement not supported for the target platform; ignored
../include/mpv/mpv.def(5) : warning LNK4017: mpv_command_node statement not supported for the target platform; ignored
../include/mpv/mpv.def(6) : warning LNK4017: mpv_command_node_async statement not supported for the target platform; ignored
../include/mpv/mpv.def(7) : warning LNK4017: mpv_command_string statement not supported for the target platform; ignored
../include/mpv/mpv.def(8) : warning LNK4017: mpv_create statement not supported for the target platform; ignored
../include/mpv/mpv.def(9) : warning LNK4017: mpv_create_client statement not supported for the target platform; ignored
../include/mpv/mpv.def(10) : warning LNK4017: mpv_detach_destroy statement not supported for the target platform; ignored
../include/mpv/mpv.def(11) : warning LNK4017: mpv_error_string statement not supported for the target platform; ignored
../include/mpv/mpv.def(12) : warning LNK4017: mpv_event_name statement not supported for the target platform; ignored
../include/mpv/mpv.def(13) : warning LNK4017: mpv_free statement not supported for the target platform; ignored
../include/mpv/mpv.def(14) : warning LNK4017: mpv_free_node_contents statement not supported for the target platform; ignored
../include/mpv/mpv.def(15) : warning LNK4017: mpv_get_property statement not supported for the target platform; ignored
../include/mpv/mpv.def(16) : warning LNK4017: mpv_get_property_async statement not supported for the target platform; ignored
../include/mpv/mpv.def(17) : warning LNK4017: mpv_get_property_osd_string statement not supported for the target platform; ignored
../include/mpv/mpv.def(18) : warning LNK4017: mpv_get_property_string statement not supported for the target platform; ignored
../include/mpv/mpv.def(19) : warning LNK4017: mpv_get_sub_api statement not supported for the target platform; ignored
../include/mpv/mpv.def(20) : warning LNK4017: mpv_get_time_us statement not supported for the target platform; ignored
../include/mpv/mpv.def(21) : warning LNK4017: mpv_get_wakeup_pipe statement not supported for the target platform; ignored
../include/mpv/mpv.def(22) : warning LNK4017: mpv_initialize statement not supported for the target platform; ignored
../include/mpv/mpv.def(23) : warning LNK4017: mpv_load_config_file statement not supported for the target platform; ignored
../include/mpv/mpv.def(24) : warning LNK4017: mpv_observe_property statement not supported for the target platform; ignored
../include/mpv/mpv.def(25) : warning LNK4017: mpv_opengl_cb_draw statement not supported for the target platform; ignored
../include/mpv/mpv.def(26) : warning LNK4017: mpv_opengl_cb_init_gl statement not supported for the target platform; ignored
../include/mpv/mpv.def(27) : warning LNK4017: mpv_opengl_cb_report_flip statement not supported for the target platform; ignored
../include/mpv/mpv.def(28) : warning LNK4017: mpv_opengl_cb_render statement not supported for the target platform; ignored
../include/mpv/mpv.def(29) : warning LNK4017: mpv_opengl_cb_set_update_callback statement not supported for the target platform; ignored
../include/mpv/mpv.def(30) : warning LNK4017: mpv_opengl_cb_uninit_gl statement not supported for the target platform; ignored
../include/mpv/mpv.def(31) : warning LNK4017: mpv_request_event statement not supported for the target platform; ignored
../include/mpv/mpv.def(32) : warning LNK4017: mpv_request_log_messages statement not supported for the target platform; ignored
../include/mpv/mpv.def(33) : warning LNK4017: mpv_resume statement not supported for the target platform; ignored
../include/mpv/mpv.def(34) : warning LNK4017: mpv_set_option statement not supported for the target platform; ignored
../include/mpv/mpv.def(35) : warning LNK4017: mpv_set_option_string statement not supported for the target platform; ignored
../include/mpv/mpv.def(36) : warning LNK4017: mpv_set_property statement not supported for the target platform; ignored
../include/mpv/mpv.def(37) : warning LNK4017: mpv_set_property_async statement not supported for the target platform; ignored
../include/mpv/mpv.def(38) : warning LNK4017: mpv_set_property_string statement not supported for the target platform; ignored
../include/mpv/mpv.def(39) : warning LNK4017: mpv_set_wakeup_callback statement not supported for the target platform; ignored
../include/mpv/mpv.def(40) : warning LNK4017: mpv_stream_cb_add_ro statement not supported for the target platform; ignored
../include/mpv/mpv.def(41) : warning LNK4017: mpv_suspend statement not supported for the target platform; ignored
../include/mpv/mpv.def(42) : warning LNK4017: mpv_terminate_destroy statement not supported for the target platform; ignored
../include/mpv/mpv.def(43) : warning LNK4017: mpv_unobserve_property statement not supported for the target platform; ignored
../include/mpv/mpv.def(44) : warning LNK4017: mpv_wait_async_requests statement not supported for the target platform; ignored
../include/mpv/mpv.def(45) : warning LNK4017: mpv_wait_event statement not supported for the target platform; ignored
../include/mpv/mpv.def(45) : warning LNK4017: mpv_wakeup statement not supported for the target platform; ignored
   Creating library mpv.lib and object mpv.exp
```

What is happening and how to solve this?

**Comment by rossy** [comment] 2017-10-18 01:18
Duplicate of #4656

I'm not entirely sure why our .def file is like this, but it's missing the header that MSVC requires. You might be able to fix it by adding the following lines to the start of the file:
```
LIBRARY MPV-1
EXPORTS
```

**Comment by dohisev** [comment] 2017-10-18 01:45
It worked but when I try to compile anything using the library I got a lot of unresolved external symbol errors like.

**Comment by rossy** [comment] 2017-10-18 01:57
Weird. I can't test locally at the moment, but could you post an example of one of these errors?

**Comment by dohisev** [comment] 2017-10-18 02:09
I'm just trying to compile the [https://github.com/cmdrkotori/mpc-qt](https://github.com/cmdrkotori/mpc-qt), I downloaded the libraries from the site that I said above, created the lib file and put everything inside the `libmpv.lib` folder, the only change I made was on the pro file that I changed `win32:LIBS += -L$$PWD/mpv-dev/lib/ -llibmpv -lpowrprof` to `win32:LIBS += -L$$PWD/mpv-dev/lib/ -lmpv -lpowrprof` cause I was getting an error saying that couldn't find `libmpv.lib`.

And then I got these errors:

```
win_qscreensaver.obj:-1: error: LNK2019: unresolved external symbol __imp_OpenProcessToken referenced in function "private: bool __cdecl QScreenSaver::canShutdown(void)" (?canShutdown@QScreenSaver@@AEAA_NXZ)
win_qscreensaver.obj:-1: error: LNK2019: unresolved external symbol __imp_AdjustTokenPrivileges referenced in function "private: bool __cdecl QScreenSaver::canShutdown(void)" (?canShutdown@QScreenSaver@@AEAA_NXZ)
win_qscreensaver.obj:-1: error: LNK2019: unresolved external symbol __imp_LookupPrivilegeValueW referenced in function "private: bool __cdecl QScreenSaver::canShutdown(void)" (?canShutdown@QScreenSaver@@AEAA_NXZ)
win_qscreensaver.obj:-1: error: LNK2019: unresolved external symbol __imp_ExitWindowsEx referenced in function "public: virtual void __cdecl QScreenSaver::logOff(void)" (?logOff@QScreenSaver@@UEAAXXZ)
win_qscreensaver.obj:-1: error: LNK2019: unresolved external symbol __imp_LockWorkStation referenced in function "public: virtual void __cdecl QScreenSaver::lockScreen(void)" (?lockScreen@QScreenSaver@@UEAAXXZ)
```

**Comment by avail** [comment] 2017-10-18 02:11
these errors aren't related to the mpv lib you've created, they're qt-related errors

**Comment by shinchiro** [comment] 2017-10-18 02:24
I think you forgot to link advapi32.lib, user32.lib (judging from the errors)

**Comment by rossy** [comment] 2017-10-18 02:28
Yeah, though it's strange that they're not linked by default (but I'm not familiar with how Qt works with MSVC.) Anyway, it seems like libmpv is linking, so I'll close this.

**Closed by rossy** 2017-10-18 02:28 UTC

**Comment by dohisev** [comment] 2017-10-18 10:44
You guys are awesome, it worked like a charm, keep up the good work, love you ♥
