### ISSUE TITLE
Compile error: 'AVIOContext' {aka 'struct AVIOContext'} has no member named 'bytes_read'

### ISSUE THREAD

**Issue by Maeyanie** [mpv-player/mpv#9185] opened 2021-09-05 12:52 UTC
### mpv version and platform versions

mpv version: git master, currently revision 8aef22e45debedc107917e674072976c55c07f0d
ffmpeg version: git master, currently revision 589cd58c858bb6b5c03cfcdb55cb8aa8acedefd7
Compiling environment: Debian 10 (buster), MinGW GCC 9.3.0
Based on jenkins/inbound-agent:4.7-1 Docker image with MXE revision 8b637cf11dcaacc9415a0e56c28a2ebcf69520af added.

### Reproduction steps

I've been running a Jenkins server which builds a Windows version of mpv with VapourSynth support for some time now. Recently compiles started failing with an error. I have it set to remove/revert all changed files each time, so it shouldn't be left-over invalid config or anything. I haven't changed the Jenkins project config in at least months, if not years.

Last compile which worked was mpv revision 88460b6f862f7328aa6285636325ff87a84dd99e, ffmpeg revision b492cacffd36ad4cb251ba1f13ac398318ee639a, build information here: https://jenkins.maeyanie.com/job/mpv/1417/
First fail was mpv revision 7314253180e7c5d06bec6d1fed79ce92bff4b6be, ffmpeg revision afeefb306e89b3ea3eb8ac8227996dc79589b669, build information here: https://jenkins.maeyanie.com/job/mpv/1418/
Considering the only change in the git history on mpv's side was license files, I presume the breaking change is on ffmpeg's side.

### Expected behavior
mpv compiles.

### Actual behavior
[194/228] Compiling demux/demux_edl.c
../demux/demux_lavf.c: In function 'update_read_stats':
../demux/demux_lavf.c:273:31: error: 'AVIOContext' {aka 'struct AVIOContext'} has no member named 'bytes_read'
  273 |         int64_t cur = nest->id->bytes_read;
      |    

### Log file

build/config.log: [config.log](https://github.com/mpv-player/mpv/files/7111596/config.log)
Full compile output: [consoleText.txt](https://github.com/mpv-player/mpv/files/7111598/consoleText.txt)
Historical compile information: https://jenkins.maeyanie.com/job/mpv/

**Comment by sfan5** [comment] 2021-09-05 12:53
duplicate of #9159, see there for a workaround

**Closed by sfan5** 2021-09-05 12:53 UTC
Labels: core:waf
