### ISSUE TITLE
Poor performance / micro-freezes during buffering

### ISSUE THREAD

**Issue by fightingdreamer** [mpv-player/mpv#8820] opened 2021-05-08 21:03 UTC
### Important Information

I experience poor performance / micro-freezes during buffering.

mpv: 0.33.1 (bundle)
macOS: 10.14.6

What I found interesting is that cache fills instantly to about 100MB and struggles to complete.
It takes about 20-30 seconds to load remaining 120MB of data.

Test was done from /tmp/ directory (issue is exactly the same) - usually I load file from NFS mount and use huge buffer to continue watching file when I no longer have access to NAS storage (change location outside wifi).

For me it looks like O(n) or similar memory reallocation / algorithm complexity issue.
It takes longer and longer time to load more data as loaded data size grows.

If I can help in any way (debug, profile) - please let me know.

### Reproduction steps

Play video using App (running from console works 100% perfect).

Config options that cause this issue.
```ini
cache=yes
cache-secs=3600
demuxer-max-bytes=4GiB
```

### Expected behavior

Smoothly video play during cache loading.
Cache loading should not impact playback, playback should always have priority.

### Actual behavior

Small freezes (1 frame ~ 1second) during cache loading.
Looks like caching have priority over playback.

### Log file

[log](https://0x0.st/-BJm.log)

### Sample files

There is no particular file that is responsible for this issue.

**Comment by Akemi** [comment] 2021-05-08 21:28
probably a duplicate of #4434 and fixed by #8266.

if it's not a duplicate i will re-popen this. in that case does it work when using the binary directly? do any earlier versions work, eg is it a regression?

**Comment by fightingdreamer** [comment] 2021-05-08 22:13
#8266 `check_stream_network` looks for remote filesystem, test was done in /tmp/ which is local filesystem.

I tried to compile mpv with your `read tracking` patch https://github.com/mpv-player/mpv/pull/8266#issuecomment-826094985, but currently I getting waf errors related to swift compiler, maybe 10.14 is not supported by waf. Need some time to investigate more.

Do you by any chance have os:mac build with this patch? I want to verify my local filesystem case in contrast to #4434.

**Comment by Akemi** [comment] 2021-05-08 22:23
i am on 10.14 too and building works without problems. no i don't have anything lying around atm.

yeah, this is for network only. sry i kinda only read NSF and assumed the rest.

if you can't build it yourself i will see what i can do. we probably need some more logging. let me know if you can't fix your build problem.

**Comment by fightingdreamer** [comment] 2021-05-08 23:44
Probably a duplicate of #7405.
_____
Proposed workaround https://github.com/mpv-player/mpv/issues/7405#issuecomment-580262887 was not effective:
```ini
stream-buffer-size=16MiB
# or
stream-buffer-size=32MiB
```

**Comment by Akemi** [comment] 2021-05-08 23:45
then it's probably a duplicate of #7405.

can you do the same thing as in this comment (https://github.com/mpv-player/mpv/issues/7405#issuecomment-579426114) and disable the cache? does it work?

**Comment by fightingdreamer** [comment] 2021-05-08 23:53
My issue is related to buffering, so disabling cache (aka buffering) will totally work (verified).
Because I can use console and buffering works correctly when launched from console, I consider that as a workaround.
Feel free to close / merge with #7405.

btw. mpv compiles in literally seconds, awesome work.

**Comment by Akemi** [comment] 2021-05-09 00:28
ok, just wanted to make sure it's really the same issue.

i would prepare some a patch for testing, if you don't mind building with it and testing? just let me know.

i am closing this issue and it would be nice if we could move the discussion to #7405 then.

**Closed by Akemi** 2021-05-09 00:28 UTC
Labels: os:mac
