### ISSUE TITLE
Behavior ontop-playback.lua in fullscreen

### ISSUE THREAD

**Issue by ww7** [mpv-player/mpv#4146] opened 2017-02-14 11:01 UTC
### mpv version and platform

0.24 on macOS Sierra, with ontop-level=window

### Reproduction steps

using ontop-playback.lua and go fullscreen

### Expected behavior

menubar visible in fullscreen

### Actual behavior

in fullscreen and ontop mpv overrides menubar

### Edited ontop-playback.lua

[try make changes](http://pastebin.com/p3eacYKt)

**Comment by Akemi** [comment] 2017-02-14 13:55
duplicate of #3974. fixed by https://github.com/mpv-player/mpv/commit/64b0d81c32d90fe29485bdb218fb76608b9aa31b. `ontop-level` is not part of 0.24 and is only on git master.

**Closed by Akemi** 2017-02-14 13:55 UTC
Labels: osx
