### ISSUE TITLE
Copy-text-to-clipboard feature (hotkey)

### ISSUE THREAD

**Issue by HumbleRes** [mpv-player/mpv#9044] opened 2021-07-25 14:34 UTC
### Expected behavior of the wanted feature

A feature (hotkey) that copies the current subtitles to my clipboard. 

### Alternative behavior of the wanted feature

Currently, it only copies one-line subtitles.

### Log file

Hi! I need help with a feature (hotkey) to copy the subtitles to my clipboard. 
I manage to come up with this: 

`c run "cmd.exe" "/d" "/c" "echo ${sub-text}|clip"`

But it only copies one-line subtitles (and ignores two-line subtitles). Can someone help me? 
Sorry if this is the wrong place to post it. I'm a bit clueless with GitHub and everything around it...

**Comment by Dudemanguy** [comment] 2021-07-25 14:44
Duplicate of #7361.

**Closed by Dudemanguy** 2021-07-25 14:44 UTC
Labels: meta:feature-request
