### ISSUE TITLE
Green tint with ra-d3d11 and HEVC 10 bit Rec.2020 HDR when using interpolation

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#4957] opened 2017-10-05 15:08 UTC
### mpv version and platform
mpv-x86_64-20171005-git-6a1eb22-branch-ra-d3d (precompiled by shinchiro)
Windows 10 x64 Anniversary Update

### Reproduction steps
Play a HEVC 10 bit Rec.2020 HDR video with interpolation enabled.
e.g. minimalist config:
gpu-api=d3d11
video-sync=display-resample
interpolation

### Expected behavior
Colors should look normal like without interpolation.

### Actual behavior
Colors have a heavy greenish tint during playback when interpolation is enabled.

### Log file
https://pastebin.com/98uNpprc

Btw: Incredible work done with the new D3D11 and Vulkan renderers! They already work amazingly well and finally D3D11VA without drawbacks. Really most amazing!

**Comment by jane1969** [comment] 2017-10-06 10:24
Hi,

In addition to this report, it seems that interpolation produces bad results with any renderer and backend with true hdr clips (just try with the redwoods sample). Conversion to sdr is wrong, and black areas are clipped, compared to playing without the option activated. Maybe some parameters used for color space transformation are ignored for interpolated frames, or a whole step of the process allowing high quality conversion of out of range pixels is skipped ?

**Comment by aufkrawall** [comment] 2017-10-06 11:33
I can't see a difference for black areas with interpolation on vs. off.
Could you describe it a bit more detailed how to reproduce?

What I do notice is that the default HDR conversion settings show very ugly banding with The Redwoods video because dark areas are overexposed, thus my proposol for different default settings. ;)

**Comment by jane1969** [comment] 2017-10-06 12:23
You can reproduce it by playing the video on a 8-bit display with alternatively interpolation on and off (other params do not change anything, I personnaly use software decoding, opengl renderer, dxinterop backend, hq profile). Look at the bushes towards the beginning of the video. There are totally black areas with interpolation on whereas color are fine without it. If you enable interpolation, pause video, play again and pause it another time, you will see that colors revert as they should be for a fragment of time before turning wrong again.

**Comment by aufkrawall** [comment] 2017-10-06 14:49
I can't confirm this. When I use
gpu-api=opengl
gpu-context=dxinterop
profile=gpu-hq
video-sync=display-resample
interpolation

there is no difference for me in The Redwoods VP9 10 bit HDR video with interpolation enabled or disabled (or playback paused and running).

**Comment by jane1969** [comment] 2017-10-06 17:57
Maybe the problem is system dependant.
Under Win 7 64 bits with a Nvidia card (but software decoding is used as it is a VP9 10 bit video), the problem occurs. Look at the bushes in the lef-bottom corner (time in video is 13s).

With interpolation (not a screenshot but a screen capture):
![with_interpolation](https://user-images.githubusercontent.com/30901105/31291356-e63e725a-aacf-11e7-8543-bca8e067962e.jpg)

Without interpolation (not a screenshot but a screen capture):
![without_interpolation](https://user-images.githubusercontent.com/30901105/31291365-ef0242a4-aacf-11e7-9fd5-fa1bec94994c.jpg)

Screenshot in both cases:
![screenshot](https://user-images.githubusercontent.com/30901105/31291478-44984ace-aad0-11e7-944d-0e69e51ecf83.jpg)

I hope it will help (sometimes, it is necessary to go backward then forward in video for the wrong colors to appear).

**Comment by haasn** [comment] 2017-10-06 18:07
@jane1969 what FBO format are you using?

**Comment by aufkrawall** [comment] 2017-10-06 18:12
I can confirm jane1969's finding: Interpolation leads to excessive banding. It's also there after pausing playback and it's also very visible directly after playback of The Redwoods video has started, when there is a fade-in effect with a vignette.

**Comment by jane1969** [comment] 2017-10-06 18:45
@haasn mpv uses default FBO format, rgba16, according to log: [vo/gpu] Using FBO format rgba16

Here are relevant parts of log:
[vo/gpu] Reported display depth: 8
[vo/gpu] Testing FBO format rgba16
[vo/gpu] Resizing texture: 16x16
[vo/gpu] Using FBO format rgba16.

**Comment by rossy** [comment] 2017-10-08 14:34
Yep I can repro this. It's quite green:
![image](https://user-images.githubusercontent.com/162837/31317710-9c7b64de-ac91-11e7-9423-be2aace7d457.png)

I'm not sure what's causing it, but it's probably a miscompiled shader.

**Comment by avih** [comment] 2017-10-08 14:48
> Yep I can repro this. It's quite green:

Groovy!

**Comment by rossy** [comment] 2017-10-08 14:56
@avih Buggy shaders always end up looking radical af 😎 

It looks like this is an issue with the cbuffer layout. Working on a fix now.

**Comment by rossy** [comment] 2017-10-11 06:24
KhronosGroup/SPIRV-Cross#304 should fix this.

I think @jane1969's issue is unrelated, so it should probably be raised in a separate issue.

**Comment by aufkrawall** [comment] 2017-10-11 12:23
Did it. :)
Is the fix SPIRV-Cross in shaderc?

**Comment by rossy** [comment] 2017-10-11 12:25
Thanks for making that issue. SPIRV-Cross and crossc have the fix in master now, so this issue should be fixed. I'm working on a new ra_d3d11 build but I have a bad internet connection at the moment, so it's taking a while.

**Comment by aufkrawall** [comment] 2017-10-11 12:30
Alright, thank you too. I'm gonna try it as soon as shinchiro compiles a build with it (btw. thx @ him for his builds, I'm not lucky with my own cross-compiles for Windows).

**Comment by rossy** [comment] 2017-10-11 13:59
Well, if you don't want to wait, I have a build with @shinchiro's scripts: https://files.jrg.systems/mpv-d3d11-x86_64-20171012-git-e272dcc.7z

This build is no longer affected by the bug, so I'm happy to close this.

**Closed by rossy** 2017-10-11 13:59 UTC

**Comment by aufkrawall** [comment] 2017-10-11 19:39
I can confirm that it's fixed and I haven't noticed any other issue so far, ra-d3d11 is really fun.
Just one minor oddity:
Is it to be expected that the results of d3d11 and opengl aren't fully pixel-equivalent? I disabled dither, deband and custom shaders and I reproducibly found minor different pixels with the same frame rendered d3d11 vs. opengl (both software decoding). When I render the same frame two times with the same API, there is zero pixel difference.
I was using win-backend for OGL and taking screenshots with print key in fullscreen.

**Comment by Hrxn** [comment] 2017-10-12 07:51
If this should be reproducible in a reliable way, it would probably be good to have the exact mpv config you're using here.
