### ISSUE TITLE
hevc: Could not find ref with POC error

### ISSUE THREAD

**Issue by shinchiro** [mpv-player/mpv#3440] opened 2016-08-20 12:03 UTC
### mpv version and platform
mpv git-cb31e72 - Win10-x64

### Reproduction steps
Random seeking will create error like  `[ffmpeg/video] hevc: Could not find ref with POC 159`
Latest mpv git produce less error than older version though.

### Expected behavior
No corrupted frame

### Actual behavior
Get this corrupted frame:
![mpv-shot0001](https://cloud.githubusercontent.com/assets/9623615/17830996/431c4b5a-6710-11e6-93cc-7e130f313bb5.jpg)

### Log files

[log.txt](https://github.com/mpv-player/mpv/files/428266/log.txt)

### Sample files

https://mega.nz/#!8NNCwAIB!6BGFIDxWEiEjQdq9CEAFUm3hgUKO6gkEXQowyhTWVTU
(will taken down later)

**Comment by shinchiro** [comment] 2016-08-20 13:19
Forgot to mention, the video is vfr. normal hevc file plays fine

**Comment by wm4** [comment] 2016-08-20 14:41
The error message (and the resulting artifacts) suggest that decoding is resumed at a point where reference frames are missing, which indicates broken muxing. I'm seeing this in mkvinfo:
```
| + [I frame for track 2, timecode 50040]
| + Block group at 4145893
|  + Block (track number 1, 1 frame(s), timecode 49.967s = 00:00:49.967) at 4145896
|   + Frame with size 813
|  + Reference block: -251.000000ms at 4146716
```
An I-frame with references doesn't make too much sense... it could be an I-frame followed by other packets that reference frames _before_ this I-frame, but I don't know if it applies in this situation. However, that also would mean that the I-frame flag (which is really a key-frame flag) is incorrect.

In theory this could be fixed by ignoring the key frame flag on packets which have "Reference block" elements, but this isn't necessarily a good idea and is essentially just guessing.

For some reason, vlc has no issues with seeking, and neither has mpv with hr-seek enabled (e.g. `--hr-seek=yes`). I'm not sure why that happens.

I'd report it as muxing bug.

VFR has nothing to do with this.

**Comment by shinchiro** [comment] 2016-08-21 03:21
Actually, using `--hr-seek=yes` also produce the same error.

IMO, this is also partly my fault after all, mistakenly forcing framerate to output file instead to the input file in ffmpeg

**Comment by wm4** [comment] 2016-08-21 10:32
This has absolutely NOTHING to do with framerates.

**Comment by shinchiro** [comment] 2016-08-23 13:16
lol yeah it still produce same error.

Is the error possibly caused by strange timecodes?

**Comment by wm4** [comment] 2016-08-23 13:21
No, it's caused by strange muxing, so report the bug to whatever did the muxing.

**Closed by wm4** 2016-08-23 13:21 UTC
Labels: info-needed

**Comment by bitingsock** [comment] 2018-08-20 12:18
I believe this is still relevant. @shinchiro do you remember if your file happened to be 12bit color? I am having the same isssue playing this clip http://0x0.st/sybs.mkv

It was remuxed this 12bit file with ffmpeg -c copy and in addition to the artifacting, mpv also can't seek to the beginning. 
log: http://0x0.st/sybK.txt

When I reencode using libx265 (default settings) I get this file http://0x0.st/sybz.mkv
Noticeably better but still some artifacts when seeking.
Sorry for the necro.
