### ISSUE TITLE
Glitch when playing fullscreen

### ISSUE THREAD

**Issue by newton108** [mpv-player/mpv#2447] opened 2015-11-04 19:17 UTC
I'm using macbook pro mid 2014 with El Capitan. Normally playing fullscreen video is smooth and won't cause any problem in other video player such as VLC. But in my case it's not smooth even playing 720p and sometime huge rectangle mosaic shows up when it glitches. The OS is fresh install and it works fine if it's played in 'window' instead of fullscreen. Someone suggest choose other sws-scaler, but it seems that none of them works.

**Comment by wm4** [comment] 2015-11-04 23:26
Maybe related to #2392.

>Someone suggest choose other sws-scaler, but it seems that none of them works.

Nonsense.

**Comment by newton108** [comment] 2015-11-05 14:59
Thanks. `fs-black-out-screens` solves my problem.

**Comment by pigoz** [comment] 2016-01-19 17:59
closing as duplicate of #2392

**Closed by pigoz** 2016-01-19 17:59 UTC
Labels: osx
