### ISSUE TITLE
Cannot build mpv with homebrew

### ISSUE THREAD

**Issue by fre123ber** [mpv-player/mpv#6660] opened 2019-04-23 10:05 UTC
### mpv version and platform
mpv HEAD 2019-04-23

### Reproduction steps
Using homebrew to build mpv in macOS 10.14.4 I get this message:

MacBook-Pro-di-Francesco:~ francesco$ brew install --HEAD mpv
==> Cloning https://github.com/mpv-player/mpv.git
Updating /Users/francesco/Library/Caches/Homebrew/mpv--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at edbc199 vo_gpu/hwdec_cuda: fixup compilation with vulkan disabled
==> ./bootstrap.py
==> python3 waf configure --prefix=/usr/local/Cellar/mpv/HEAD-edbc199_3 --enable
==> python3 waf install
Last 15 lines from /Users/francesco/Library/Logs/Homebrew/mpv/03.python3:
/private/tmp/mpv-20190423-13287-1e4wj9y/video/out/cocoa_cb_common.swift:256:29: warning: 'init(_:)' is deprecated: replaced by 'init(truncating:)'
        let lux = Int(ceil( Double((term4 + term3 + term2 + term1 - 0.19) as NSNumber)))
                            ^
/private/tmp/mpv-20190423-13287-1e4wj9y/video/out/cocoa_cb_common.swift:256:29: note: use 'init(truncating:)' instead
        let lux = Int(ceil( Double((term4 + term3 + term2 + term1 - 0.19) as NSNumber)))
                            ^
                                   truncating: 
/private/tmp/mpv-20190423-13287-1e4wj9y/video/out/cocoa_cb_common.swift:335:39: error: cannot call value of non-function type '[NSScreen]'
        let screens = NSScreen.screens()
                      ~~~~~~~~~~~~~~~~^~
                                      
Waf: Leaving directory `/private/tmp/mpv-20190423-13287-1e4wj9y/build'
Build failed
 -> task in 'osdep/macOS_swift.o,osdep/macOS_swift.h,osdep/macOS_swift.swiftmodule' failed with exit status 1 (run with -v to display more information)

**Comment by CounterPillow** [comment] 2019-04-23 10:56
Probably a duplicate of #6470, and the fourth at that.

**Comment by Akemi** [comment] 2019-04-23 16:15
yes, duplicate. download an older command line tools (for xcode 10.1) and use `xcode-select -s /Library/Developer/CommandLineTools` to change the dev path.

**Closed by Akemi** 2019-04-23 16:15 UTC
