### ISSUE TITLE
[Bug] Forced track are not selected

### ISSUE THREAD

**Issue by JeremieBergeron** [mpv-player/mpv#8593] opened 2021-02-22 17:50 UTC
### Important Information

Provide following Information:
- mpv version - 0.33.0 (i think, but I have the last one)
- Windows Version - Windows 10
- Source of the mpv binary - https://sourceforge.net/projects/mpv-player-windows/files/64bit/

### Reproduction steps

1. Open a mkv with forced subtitle via mpv.

### Expected behavior
Forced track are selected

### Actual behavior
Forced track are not selected

**Comment by Akemi** [comment] 2021-02-22 18:06
duplicate of #8396

**Closed by Akemi** 2021-02-22 18:06 UTC
Labels: os:win

**Comment by lon0** [comment] 2021-03-17 15:00
Maybe is not an ultimate solution, but you can add this in mpv.conf and the forced sub of your languages will be played, work fine when is the first sub track muxed because the first language will have the priority  
  
sub-forced-only  
slang=<languagecode[,languagecode,...]>
