### ISSUE TITLE
Invisible OSD

### ISSUE THREAD

**Issue by Revemohl** [mpv-player/mpv#2191] opened 2015-08-04 08:00 UTC
On the 2015-08-03 and 2015-07-30 32-bit Windows builds from https://mpv.srsfckn.biz/, I've noticed that most of the OSD isn't displayed at all. Videos and their subtitles still work, but the information text displayed by mpv and the box around the controls do not ([example](http://i.xomf.com/dgygs.jpg)). Going back to the 2015-07-26 build makes things work as they should once again. Changing the video output from opengl to direct3d doesn't change anything, and I don't know enough about configuring mpv to try checking if anything else could work.

This is a rather old machine running Windows XP, by the way.

**Comment by wm4** [comment] 2015-08-04 12:15
@lachs0r: any ideas? I was ready to blame the directwrite backend, but it's probably not available on XP.

**Comment by lachs0r** [comment] 2015-08-06 05:35
Nope, that’s not used on XP (I’ve already confirmed this). It’s still using the fonts branch though, starting with 2015-07-30, so maybe there’s a different issue with it.

**Comment by PapoyBanana** [comment] 2015-08-06 19:14
i'm using build 2015-08-03 on xp and having the same problem with the osd. any workaround?

**Comment by wm4** [comment] 2015-08-06 20:53
Must be caused by the libass font selection changes then, even though the same backend (fontconfig) as before is used.

**Comment by lachs0r** [comment] 2015-08-29 22:49
This should be fixed with the latest build.

**Closed by lachs0r** 2015-08-29 22:49 UTC

**Comment by PapoyBanana** [comment] 2015-09-01 15:15
yup the osd is back. thanks guys!
