### ISSUE TITLE
App flashes for a split second then disappears

### ISSUE THREAD

**Issue by computator1200** [mpv-player/mpv#12773] opened 2023-10-29 17:13 UTC
### Important Information

- mpv v0.36.0-506-g81dea9031d
- macOS Sonoma Version 14.0 (M2 MacBook Air)
- Source: git

### Expected behavior

The app should open up with the logo and message to load a file, or when clicking on a video file it should automatically open and play in mpv. 

### Actual behavior

The app flashes for a split second then quits (according to the log). 
The command line executable (./mpv) still works normally, it is the mpv.app which I am unable to access.

This happened after I updated to Sonoma.

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/13198704/mpv.log)

**Comment by Akemi** [comment] 2023-10-29 23:23
duplicate of #12116

**Closed by Akemi** 2023-10-29 23:23 UTC
Labels: os:mac
