### ISSUE TITLE
Media Keys Crash on MacOS Mojave 

### ISSUE THREAD

**Issue by meinhimmel** [mpv-player/mpv#6156] opened 2018-09-24 23:16 UTC
mpv 0.29.0-30-g6eb59fe (latest master) on MacOS Mojave 10.14.

### Reproduction steps
`./build/mpv a`

### Expected behavior
`[file] Cannot open file 'a' ...`

### Actual behavior
`Assertion failed: (self->_mk_tap_port != nil), function -[EventsResponder startMediaKeys]_block_invoke, file ../osdep/macosx_events.m, line 413.`

### Log file
http://0x0.st/s3VS.txt

### Workaround
Disable startMediaKeys in macosx_events.m, but that's not viable long term.

Latest MacOS requires accessibility permissions to access the media keys like this.

**Comment by jnozsc** [comment] 2018-09-25 03:12
in case someone upgrades to Mojave on day one, and does not want to build mpv by himself

Here is a temporary solution
add
```input-media-keys=no```
to your `mpv.conf` file 

It will at least make the mpv works, without media key support.

also look forward a long term solution

**Comment by Akemi** [comment] 2018-09-25 08:37
duplicate of #5908, fixed with #5953, another workaround https://github.com/mpv-player/mpv/issues/5908#issuecomment-424215013.

**Closed by Akemi** 2018-09-25 08:37 UTC
