### ISSUE TITLE
osd-overlay is not shown if the video is paused at the same time

### ISSUE THREAD

**Issue by occivink** [mpv-player/mpv#8821] opened 2021-05-09 13:44 UTC
### Important Information

```
mpv 0.33.0-150-gea89e813f7 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun May  9 15:10:23 CEST 2021
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: n4.4
```
built on arch linux. 

### Reproduction steps

Use the following script 
```
ov = mp.create_osd_overlay("ass-events")
ov.data = "{\\an5}{\\b1}hello world!"
local shown = false

mp.add_key_binding("k", function()
    if not shown then
        mp.set_property_bool("pause", true)
        ov:update()
    else
        mp.set_property_bool("pause", false)
        ov:remove()
    end
    shown = not shown
end)
```
with `mpv --no-config --script=test.lua somevideo`

Press k repeatedly to trigger the script.

### Expected behavior

When pressing k, the video is paused and the overlay 'hello world!' is shown immediately.

### Actual behavior

The overlay is only shown some of the time. Most of the time, the text does not appear until some other event refreshes the video (resize, mouse hover...).
Note that the same problem applies to image overlays made with the command `overlay-add`.

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/6447627/log.txt)

**Comment by avih** [comment] 2021-05-09 13:49
Duplicate of #8172 and #8350 .

**Closed by avih** 2021-05-09 13:49 UTC

**Comment by avih** [comment] 2021-05-09 13:59
For reference, it's not specific to `mp.create_osd_overlay`. It's a general issue with rendering any overlay (OSD, etc) while pause is toggled, e.g. with this binding at `input.cont`:
```
SPACE osd-msg cycle pause
```

If there's no video playing (e.g. `mpv --idle --force-window`) and you press space, then you'll see OSD message of both `pause: yes` and `pause: no`.

But if there is a video playing, then not all presses of space show a message. E.g. on my system it typically shows only `pause: no`.

It's probably a race condition between displaying a new OSD thing, while also changing the throttling of OSD overlays (immediate while paused, synced to the next video frame while playing).

**Comment by occivink** [comment] 2021-05-09 14:05
Thanks for the extra info. I've also noticed that with `video-sync=display-resample`, the OSD updates consistently as expected.

**Comment by avih** [comment] 2021-05-09 14:19
> I've also noticed that with video-sync=display-resample, the OSD updates consistently as expected.

Next time, when you open an issue which is not a duplicate, consider adding such info instead of keeping it to yourself.

You're a developer, so put your yourself in our shoes: wouldn't you think this kind of info is helpful in understanding what affects the issue? Wouldn't you prefer that the reported added such info if they new about it?

**Comment by occivink** [comment] 2021-05-09 14:21
Well, I only realized after I tried out your binding in my own config and could not reproduce it, whereas I could with `--no-config`. I didn't purposely hide anything.
