### ISSUE TITLE
interpolation mix behavior

### ISSUE THREAD

**Issue by sda89ha9** [mpv-player/mpv#3495] opened 2016-09-05 21:47 UTC
windows 10, git master
with d223959cda7ef816b95303c328f7a8ad0e35dbff, interpolations mix ratio changed
can't tell the difference visually, just curious as to which behavior is "more correct"
logs:
[Interpolation Mitchell with](http://sprunge.us/dEej) d223959cda7ef816b95303c328f7a8ad0e35dbff
[Interpolation Mitchell without](http://sprunge.us/EBdf) d223959cda7ef816b95303c328f7a8ad0e35dbff
[Interpolation Oversample with](http://sprunge.us/GaPU) d223959cda7ef816b95303c328f7a8ad0e35dbff
[Interpolation Oversample without](http://sprunge.us/BYDD) d223959cda7ef816b95303c328f7a8ad0e35dbff

display-fps 59.940, container-fps 23.976

```
old oversample
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.500000
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.000000
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.000000
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.000000
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.000000
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.500000
```

```
new oversample
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.606270
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.000000
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.106270
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.000000
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.000000
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.606270
```

**Comment by haasn** [comment] 2016-09-05 21:53
Old is definitely more correct here

**Comment by sda89ha9** [comment] 2016-09-06 00:35
video: https://www.youtube.com/watch?v=rql_F8H3h9E, formats:
**278**          webm       256x144    DASH video  125k , webm container, vp9, **15fps**, video only, 1.79MiB
**244**          webm       854x480    DASH video  938k , vp9, **30fps**, video only, 13.03MiB
**302**          webm       1280x720   DASH video 3132k , vp9, **60fps**, video only, 45.31MiB

builds: [lachs0r](https://mpv.srsfckn.biz/mpv-x86_64-20160826.7z), [rorgoroth](https://bitbucket.org/rorgoroth/mpv-for-windows/downloads/mpv-full-Win64.zip)
settings: --no-config --video-sync=display-resample --vo=opengl:interpolation:tscale=oversample --end 15
logs: https://0x0.st/ulF.zip

**Comment by haasn** [comment] 2016-09-06 00:44
I'm confused, didn't you say the video file was 24 fps?

**Comment by sda89ha9** [comment] 2016-09-06 01:02
well yeah, but it seems the "problem" is with every video
anyway [sample](https://0x0.st/uU-.mkv) of the 23.976 video file

--no-config --video-sync=display-resample --vo=opengl:interpolation:tscale=oversample
```
lachs0r
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.500000
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.000000
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.000000
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.000000
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.000000
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.500000
```
```
rorgoroth
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.606270
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.000000
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.106270
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.000000
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.000000
[vo/opengl] inter frame dur: 0.041707 vsync: 0.016683, mix: 0.606270
```

**Comment by sda89ha9** [comment] 2016-09-06 02:08
i created 60 FPS test files with ffmpeg
[ffmpeg -r 60000/1001 -f lavfi -i color=c=red -t 15 60.mkv](https://0x0.st/uUA.mkv)
[ffmpeg -r 60000/1001 -f lavfi -i color=c=red -t 15 60.mp4](https://0x0.st/uUm.mp4)

lachs0r
```
60.mkv
[vo/opengl] Assuming 59.940060 FPS for display sync.
[vd] Container reported FPS: 59.940060
...
[cplayer] s=1.000020 vsyncs=1 dur=0.016683 ratio=1.000000 err=0.00000000000003413936 (0.000000/0.000000)

60.mp4
[vo/opengl] Assuming 59.940060 FPS for display sync.
[vd] Container reported FPS: 59.940060
...
[cplayer] s=1.000020 vsyncs=1 dur=0.016683 ratio=1.000000 err=0.00000000000003418099 (0.000000/0.000000)
```
rorgoroth
```
60.mkv
[vo/opengl] Assuming 59.940060 FPS for display sync.
[vd] Container reported FPS: 59.940060
...
[cplayer] s=1.000020 vsyncs=1 dur=0.016683 ratio=0.931985 err=-0.00113469934632816002 (-0.068015/-0.068015)

60.mp4
[vo/opengl] Assuming 59.940060 FPS for display sync.
[vd] Container reported FPS: 59.940060
...
[cplayer] s=1.000020 vsyncs=1 dur=0.016683 ratio=1.000000 err=0.00000000233115243428 (0.000000/0.000000)
```

**Comment by haasn** [comment] 2016-09-06 03:20
@sda89ha9 Can confirm that behavior (the 0.6/0.1 thing) on that specific 24 Hz clip you posted. In other 24 Hz files (e.g. [this one](https://red.cachefly.net/learn/panning-24fps-180.mp4) it works fine for me (0.5/0.0). Can you confirm this on your end?

cc @wm4

**Comment by sda89ha9** [comment] 2016-09-06 03:54
[panning-24fps-180.mp4 Log](http://sprunge.us/hCVh)

some more tests
[monitor refresh rate 59 Hz, video frame rate 60000 / 1001](http://sprunge.us/HhKX)
[monitor refresh rate 60 Hz, video frame rate 60000 / 1001](http://sprunge.us/DFfW)
```
--- a/player/video.c
+++ b/player/video.c
@@ -1313,7 +1313,7 @@ static void calculate_frame_duration(struct MPContext *mpctx)
         // Note that even if each timestamp is within rounding tolerance, it
         // could literally not add up (e.g. if demuxer FPS is rounded itself).
         if (fabs(duration - demux_duration) < tolerance &&
-            fabs(total - demux_duration * num_dur) < tolerance && num_dur >= 16)
+            fabs(total - demux_duration * num_dur) < tolerance)
         {
             approx_duration = demux_duration;
         }
```
 && num_dur >= 16 removed 
[monitor refresh rate 59 Hz, video frame rate 60000 / 1001](http://sprunge.us/ZNRf)
[monitor refresh rate 60 Hz, video frame rate 60000 / 1001](http://sprunge.us/ILiY)

**Comment by sda89ha9** [comment] 2016-09-06 04:41
seems only mkv is affected?
```
ffmpeg -r 24 -f lavfi -i color=c=red -t 15 24.mkv
ffmpeg -r 24 -f lavfi -i color=c=red -t 15 24.mp4
```
[24FPS.mkv](https://0x0.st/uUO.mkv)
[24FPS.mp4](https://0x0.st/uUV.mp4)
```
24FPS.mkv
[vo/opengl] inter frame dur: 0.041708 vsync: 0.016683, mix: 0.624831
[vo/opengl] inter frame dur: 0.041708 vsync: 0.016683, mix: 0.000000
[vo/opengl] inter frame dur: 0.041708 vsync: 0.016683, mix: 0.124831
[vo/opengl] inter frame dur: 0.041708 vsync: 0.016683, mix: 0.000000
[vo/opengl] inter frame dur: 0.041708 vsync: 0.016683, mix: 0.000000
[vo/opengl] inter frame dur: 0.041708 vsync: 0.016683, mix: 0.624831
```
```
24FPS.mp4
[vo/opengl] inter frame dur: 0.041708 vsync: 0.016683, mix: 1.000000
[vo/opengl] inter frame dur: 0.041708 vsync: 0.016683, mix: 0.000000
[vo/opengl] inter frame dur: 0.041708 vsync: 0.016683, mix: 0.500000
[vo/opengl] inter frame dur: 0.041708 vsync: 0.016683, mix: 0.000000
[vo/opengl] inter frame dur: 0.041708 vsync: 0.016683, mix: 0.000000
[vo/opengl] inter frame dur: 0.041708 vsync: 0.016683, mix: 1.000000
```

**Comment by haasn** [comment] 2016-09-06 04:45
> seems only mkv is affected?

Matroska (mkv) has much worse timestamp precision than MP4, which is one of the few things I really hate about the standard.

Indeed the 24 Hz test files I were using where I said it worked fine were all MP4-based files. So it seems like some sort of regression in the matroska-specific timestamp un-fucking behavior.

**Comment by wm4** [comment] 2016-09-06 07:42
Is this only on start of playback, or always?

**Comment by haasn** [comment] 2016-09-06 09:00
@wm4 No, it's consistent throughout playback.

**Comment by wm4** [comment] 2016-09-06 10:57
Is your complaint just that it produces "uneven" mix values?

That is a known problem, and unavoidable. It's caused by uneven frame durations, which can for example happen if the file doesn't store exact values (yep, Matroska - but also mp4 transcoded/remuxed from mkv, .ts files, and so on). In this case, it's triggered by the weaker frame rate guessing heuristic. But note that the weaker heuristic is also needed to avoid worse by broken files, e.g. Matroska with incorrect framerate header (which is actually common).

The actual cause of this is that the uneven frame duration at the start of playback "unaligns" the  display_sync_error and vsync_offset values. Maybe something could be added that makes these values converge back to "aligned" values, but I don't currently have an idea how. Suggestions welcome.

Just removing the "num_dur >= 16" check could make it assume the wrong framerate for a few frames, which would lead to heavy mistiming and drift.

**Comment by haasn** [comment] 2016-09-06 11:33
I'm not really sure what this algorithm is doing or why it produces uneven values, but mpv manages to detect the right frame durations after a few frames, right? If so, maybe you could just recompute the timings once you have a good enough (3-4 frame window) estimate? Or maybe just look up those frames in advance before computing the first few timings?

**Comment by wm4** [comment] 2016-09-06 12:35
The problem exists just as much if the container framerate is broken, and in that case it'd never find the real framerate. And there's always drift.

**Comment by mpvOWNZ** [comment] 2016-09-08 18:48
I think the new mixing behavior is even more sound reason to set `tscale-clamp` by default when activating `interpolation`.

**Comment by sda89ha9** [comment] 2016-09-09 00:24
--no-config --video-sync=display-resample
```
[file] Opening mkv_60FPS.mkv
[vo/opengl] Assuming 59.940060 FPS for display sync.
[vd] Container reported FPS: 59.940060
...
[cplayer] s=1.000020 vsyncs=1 dur=0.016683 ratio=0.931985 err=-0.00113469934634768607 (-0.068015/-0.068015)
```
```
[file] Opening mp4_60FPS.mp4
[vo/opengl] Assuming 59.940060 FPS for display sync.
[vd] Container reported FPS: 59.940060
...
[cplayer] s=1.000020 vsyncs=1 dur=0.016683 ratio=1.000000 err=0.00000000233113120127 (0.000000/0.000000)
```
working as intended or not?
mkv_60FPS.mkv's display_sync_error value freaks me out

also unrelated bug
```
--- a/player/video.c
+++ b/player/video.c
@@ -982,7 +982,7 @@ double calc_average_frame_duration(struct MPContext *mpctx)
     double total = 0;
     int num = 0;
     for (int n = 0; n < mpctx->num_past_frames; n++) {
-        double dur = mpctx->past_frames[0].approx_duration;
+        double dur = mpctx->past_frames[n].approx_duration;
         if (dur <= 0)
             continue;
         total += dur;
```

**Comment by wm4** [comment] 2016-09-09 06:37
>working as intended or not?
>mkv_60FPS.mkv's ratio value freaks me out

Well, the timestamps are rounded to 60fps, so...

Thinking about it, it might be possible to "unround" the first timestamps, and only switch to not "unrounding" them if the container FPS turns out to be unreliable. But not sure how this can be done in a reliable way.

I still think adding something that lets the interpolation coefficient converge towards "clean" values is a better idea.

>also unrelated bug (not sure if bug)

Looks indeed like a very dumb bug. Can you post a git format-patch or a PR? (To include authorship info.)

**Comment by sda89ha9** [comment] 2016-09-09 17:10
@wm4 
[0001-player-fix-average-frame-duration-calculation.patch](https://0x0.st/S-5.patch)
is this ok? 0 experience with git

**Comment by wm4** [comment] 2016-09-09 17:18
That's perfect, applied. I'm assuming you agree with relicensing to LGPL once the time comes.

**Comment by sda89ha9** [comment] 2016-09-09 17:23
yep

**Comment by mpvOWNZ** [comment] 2016-10-01 16:56
@wm4 
Any chance this problem will be properly addressed/resolved before the next release by @lachs0r ?

**Comment by wm4** [comment] 2016-10-02 10:36
No.

**Comment by sda89ha9** [comment] 2016-11-25 02:50
ive concluded theres no bug, so im gonna close this

**Comment by wm4** [comment] 2016-11-25 08:52
Actually it's pretty clearly an issue.

**Comment by mpvOWNZ** [comment] 2017-03-10 02:42
@sda89ha9 
It would be nice of You if You could reopen this issue, since @wm4 himself said that this bug is still not resolved. Also it would make tracking any progress concerning this particular problem easier.
Thanks!

**Comment by mpvOWNZ** [comment] 2017-04-30 11:06
Dear @wm4,

for the sake of science I have been compiling & running mpv with "&& num_dur >= 16" removed for a while now.
So far I didn't notice any difference, until yesterday where AFTER having watched a whole movie (interestingly enough with a .mp4 extension) I saw in the terminal that mpv had detected heavy mistiming and drift (just what You had warned about) since the very beginning of the file.
But what really amazed me was that none of the possible consequences occured to me, i.e. there was still properly working interpolation (with tscale=sinc), no audio-video mismatch and properly placed subtitles!

One thing was new, however: A new value printed by mpv called "ct: 2.496" that I had never seen before.
I can only assume that the value of 2.496 is very close to the ideal of 2.500 that I would normally see with no mistiming & drift detected by mpv, so maybe that is why I couldn't notice anything wrong with the file being played...
Anyway, if You could enlighten me about that "ct: 2.496" value and could say a word or two about Your take on all this behavior of mpv, I would be very grateful.

Also a big thanks to @sda89ha9 for pointing out this problem with the interpolation mix ratio in the first place!

**Comment by wm4** [comment] 2017-05-02 17:01
`ct` is the "lost time" that should have been there, so it basically means audio/video drift that had to be compensated for. I guess it's close to 2.5 only by coincidence. It actually means that the video timestamps were off by 2.49 seconds.

I'm still not sure how to entirely fix this. Clearly, it should detect and remove a constant mix offset - this would help not only if the container framerate is correct, but also if it's incorrect. But I haven't come up with a robust way to do this yet.

**Comment by wm4** [comment] 2017-05-02 17:05
@mpvOWNZ to elaborate on your case, compensating to drift probably led to a few repeated or skipped frames to restore A/V sync. I guess there's no A/V desync because the actual video timestamps (which are used for A/V sync) are not changed.

**Comment by mpvOWNZ** [comment] 2017-05-05 02:35
@wm4 
Thanks a lot for the explanation and the invalueable work You do for mpv!
Also, I think that this bug report can safely get the "low-priority" label attached to it, since the majority doesn't seem to notice or care anyway, so don't worry about how to solve this particular problem too much.
As for myself, I can easily live with "&& num_dur >= 16" deleted, because even if mpv detects mistiming & drift, it still can play anything thrown at it without a hitch, which in my humble opinion speaks volumes for the great code quality it is written in (usually by You).
So, thanks again & keep up the amazing work!

**Comment by Dudemanguy** [comment] 2023-01-10 02:51
Closing mainly because it's ancient.

**Closed by Dudemanguy** 2023-01-10 02:51 UTC
Labels: core, core:video
