### ISSUE TITLE
In my osx project, some method will lead to no respond

### ISSUE THREAD

**Issue by skydreamever** [mpv-player/mpv#1980] opened 2015-05-25 02:45 UTC
In my osx project, I use the libmpv.dylib and client.h to include the mpv into my pj. 
It can play video, but when I use the method below,

mpv_set_property_string(mpv,"pause","yes")

There is no respond, I make sure I use it by cocoabasic.m
What should I do

**Comment by wm4** [comment] 2015-05-25 11:14
>mpv_set_property_string(mpv,"pause","yes")

This should work. I actually tried this exact line myself. And it works. To get some diagnostics, check the return value of the function call, and maybe enable logging to the terminal by calling this before ``mpv_initialize()``:

```
    mpv_set_option_string(mpv, "msg-level", "all=v");
    mpv_set_option_string(mpv, "terminal", "yes");
```

**Comment by skydreamever** [comment] 2015-05-26 01:04
I've tried many times.The same question. Also I've add these
    mpv_set_option_string(mpv, "msg-level", "all=v");
    mpv_set_option_string(mpv, "terminal", "yes");
and there is screenshot:
![screenshot](http://puu.sh/i0CtO/c7459513d6.png)

**Comment by skydreamever** [comment] 2015-05-26 01:05
It's not broken. It is just no respond, I pause it manually.

**Comment by wm4** [comment] 2015-05-26 12:04
>It's not broken. It is just no respond, I pause it manually.

What do you mean? If it's not broken, then does it works as intended? Then what's the problem?

Also, mpv_get_property_string returns a string that needs to be freed with mpv_free. For some properties, it also might return NULL in some situations.

**Comment by skydreamever** [comment] 2015-05-27 01:20
As you can see in the picture, when I run 
mpv_set_property_string(mpv,"pause","yes")
Then my application has no respond. So I manually click the pause button in Xcode. Only I want to show you is my application's stack to let you help me found the problem.

By the way, I'm sure about that mpv_get_property_string returns no or yes in my application.

**Comment by wm4** [comment] 2015-07-18 16:22
Well, can't help much with the information I have so far, so closing.

**Closed by wm4** 2015-07-18 16:22 UTC
Labels: info-needed, question
