### ISSUE TITLE
mpv displaying wrong colors (green tint) by default for videos

### ISSUE THREAD

**Issue by Rabcor** [mpv-player/mpv#9285] opened 2021-10-08 01:22 UTC
### Important Information

- mpv version: 0.33.1 and 0.33.0-360-gb3f3c3fec0 (git build 8th october 2021)
- Linux Distribution and Version: Manjaro (Kernel 5.14.7)
- Source of the mpv binary: official repos
- Window Manager and version: KwinFT 5.22.0
- GPU driver and version: Nvidia 470.63.01

I noticed that mpv was displaying wrong colors for videos, compared to in my browser.

The color difference is very subtle, but in mpv it looks like there's a slight green tint over everything.

The issue is present in most video files I tested (mostly files with pixel format yuv420p and hw decoded (nv12) files)  although I noticed that with image files the colors are correct compared to my image viewer (viewnior)

At first I thought the problem was `--video-output-levels=full` not being respected, but it turns out that it is in fact being respected (if I set it to limited the colors in all files will be washed out like there's a white overlay over everything).

I also tried manually setting an icc color profile but it didn't seem to affect the issue (didn't even seem to work, I tried various profiles but it always looked the same, which I'm pretty sure it shouldn't)

### Reproduction steps

1. Open a video in chromium that displays correct colors
2. Open the same file in mpv and see slightly off color (a very slight green tint to everything)

### Expected behavior

Correct colors (no green tint)

### Actual behavior

Wrong colors (green tint)

### Screenshots:

chromium (correct colors)
![Correct (chromium)](https://user-images.githubusercontent.com/5684325/136479541-e00f02c0-790e-4c91-91d9-9a29bca8026b.png)

`mpv --no-config --video-output-levels=full file.mp4` (incorrect colors/green tint)
![51c61a36cf4f8797f3543bdbdc15d2a7 (00:00:00 000) 0001](https://user-images.githubusercontent.com/5684325/136479564-5abfa16a-ef23-43b4-b99c-ec37fd038c9e.jpg)

`mpv --no-config --video-output-levels=full file.mp4` with info displayed
![51c61a36cf4f8797f3543bdbdc15d2a7 (00:00:00 000) 0002](https://user-images.githubusercontent.com/5684325/136479574-ee8939ea-01e0-4451-9933-388a458bced8.jpg)

### Workarounds

`--vf=colorbalance=rm=0.003:rs=0.003:rh=0.003:bm=0.003:bs=0.003:bh=0.003 ` removes the green tint but darkens the image a little. (It also creates artifacts when taking screenshots, not sure why, had to take a system screenshot for below pic or it would look wrong)

Note: If you're using other filters, such as `brightness` or `gamma` or `target-trc` you may need to set these values higher (possibly up to 0.01)

`mpv --no-config --vf=colorbalance=rm=0.003:rs=0.003:rh=0.003:bm=0.003:bs=0.003:bh=0.003 file.mp4 `
![Screenshot_20211008_084340](https://user-images.githubusercontent.com/5684325/136526529-f7ae1dc9-cf3d-48e0-a289-e030b816d0fc.png)

### Update

Logfile: https://gist.github.com/Rabcor/e2696e33d28db18aa18529c0a82ba130

Sample File: https://user-images.githubusercontent.com/5684325/136621376-e35c5186-e10e-4189-bb3e-8fb95cc1428e.mp4

I also feel it is prudent to mention that the artist who made the sample file goes by **GuiltyK**, given that it's not watermarked :)

-------------------------------------------

Further Investigation: The problem may run deeper than mpv, I tried running with `firefox`, `vlc`, `maui-clip`, `xine`, `xjadeo` and `pantheon-video`. Of these only the last one displayed a different image, but it was just desaturated compared to the rest.

Lastly I tried running it with `MPC` and `MS Photos` in a Windows VM, the result was the same as mpv there.

So now I'm curious, is it Chromium that's handling videos wrong? or is it everything else? How do I find out?

I did check to see if chromium is handling color wrong for image files, but it was the same as my image viewer, which is the same as mpv (at least for image files), so at least it's not mishandling colors in general.

**Comment by Rabcor** [comment] 2021-10-08 20:57
> Can you provide a log and sample file?

Updated OP, I also did a bit more digging too.

**Comment by haasn** [comment] 2021-10-09 08:49
> So now I'm curious, is it Chromium that's handling videos wrong? or is it everything else? How do I find out?

Computing the correct conversion explicitly using raw data:

```
$ ffmpeg -colorspace bt709 -i 136621376-e35c5186-e10e-4189-bb3e-8fb95cc1428e.mp4 -frames:v 1 -pix_fmt yuv444p raw.yuv
$ convert -depth 8 -interlace plane -size 1920x1080 -sampling-factor 4:4:4 rgb:raw.yuv -color-matrix "1.1644 0.0 1.79270 0.0, 0.0, -0.97294 1.1644 -0.21325 -0.53291 0.0, 0.0, 0.30148 1.1644 2.11240 0.0 0.0, 0.0, -1.13340 0.0 0.0 0.0 1.0, 0.0, 0.0 0.0 0.0 0.0 0.0, 1.0, 0.0 0.0 0.0 0.0 0.0, 0.0, 1.0" output-im.png
```

Results in this output for me:
![output-im.png](https://user-images.githubusercontent.com/1149047/136651092-9528d808-3dcb-4f5f-b63a-49fbe4d40495.png)

Flipping between this and the mpv screenshot I see no difference. I *do* see a difference between it and the chrome sample, though. By the way, I noticed your comparison images are a mix of jpg and png. Are you using the mpv built-in screenshot command, which bypasses the video output altogether? You should be taking all screenshots using the same mechanism.

Addendum: I copy-pasted the color matrix from [this post](https://stackoverflow.com/questions/56894629/converting-limited-range-yuv-to-srgb-using-imagemagick#comment100363654_56906843) but verified its correctness:

```c
#include <libplacebo/colorspace.h>

int main()
{
    struct pl_transform3x3 tr = pl_color_repr_decode(&(struct pl_color_repr) {
        .sys = PL_COLOR_SYSTEM_BT_709,
        .levels = PL_COLOR_LEVELS_LIMITED,
    }, NULL);
}
```

```
(gdb) print tr
$1 = {
  mat = {
    m = {{1.16438353, 0, 1.79274106}, {1.16438353, -0.213248596, -0.532909334}, {1.16438353, 2.11240172, 0}}
  },
  c = {-0.972945094, 0.301482648, -1.13340223}
}
```

**Comment by haasn** [comment] 2021-10-09 08:51
Going to close this as "working as intended". Feel free to re-open if you can demonstrate that mpv does not reproduce the same output in practice as an objectively correct conversion performed by above calculation.

**Closed by haasn** 2021-10-09 08:51 UTC
Labels: os:linux

**Comment by Rabcor** [comment] 2021-10-10 00:24
@haasn 

Were you looking at the correct screenshot? Because what you posted looks nothing like my screenshot (not like any one of them actually).

I can't really tell if the colors are the same or not because the gamma is different in your screenshot.

I was able to get a near exaact match to your screenshot, but it was with these settings:

`mpv --no-config --target-trc=srgb --gamma=4 ChillTracer.mp4 `
![ChillTracer 0001](https://user-images.githubusercontent.com/5684325/136677019-37ce0369-102c-45b6-9600-44f8897ecb4c.jpg)

**Comment by haasn** [comment] 2021-10-10 07:37
> Were you looking at the correct screenshot? Because what you posted looks nothing like my screenshot (not like any one of them actually).

I'm comparing the raw pixel values, without further color management on top, i.e. what would be sent to the display.

If you don't disable color management in your testing then it doesn't surprise me that you get wildly inconsistent outputs, because PNG, BT.709, JPEG etc. all have different gamma handling, and you are mixing different formats without taking into account the necessary conversions that would be required for this to be lossless.

**Comment by ValZapod** [comment] 2022-02-08 07:02
> for pngs and gifs it's srgb, for jpgs and all the various video format files it's almost always bt.1886.

No, what? JPEG also uses srgb by default. PNG can be tagged with gAMA chunk as being 2.4 gamm or 0.0002 gamma! Who cares.

> `--video-output-levels=full` not being respected

This should be autoapplied by linux itself and correct with what display does. You can misconfig this.

**Comment by ValZapod** [comment] 2022-02-08 07:06
> and yet the yuv444p files need the `target-trc=gamma2.2` to get the same results as `target-trc=srgb on yuv420p`, this is all confusing as shit and it's no wonder most software doesn't get it right out of the box.

Yes, most displays are only 2.2 gamma, not even srgb. This is pathetic as hell. It may be confusing, but...

Yes, when you display bt.709 movie (like you did) on gamma 2.2 display you should specify --target-trc=2.2, be ause your target is not bt.1886.

**Comment by ValZapod** [comment] 2022-02-08 07:15
> Chromium that's handling videos wrong?

There is a bug in chromium that decodes YCbCr slightly wrong. It is being fixed right now.
