### ISSUE TITLE
--no-keepaspect-window not working

### ISSUE THREAD

**Issue by qhzhang87** [mpv-player/mpv#5393] opened 2018-01-14 05:03 UTC
### mpv version and platform
mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Thu Dec  7 17:18:43 GMT 2017
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4.1

macOS Sierra

### Reproduction steps
mpv https://www.youtube.com/watch?v=hY7dQnVnqmQ
mpv --no-keepaspect-window https://www.youtube.com/watch?v=hY7dQnVnqmQ

### Expected behavior
with "--no-keepaspect-window", it should be able to resize the window

### Actual behavior
"--no-keepaspect-window" doesn't make any difference, the window is still locked to the ratio of the video.

### Log file
https://spit.mixtape.moe/view/raw/51dbc14d

**Comment by zc62** [comment] 2018-01-14 05:30
>Whether this actually works depends on the VO backend.

Try `--vo=gpu`?

**Comment by wm4** [comment] 2018-01-14 05:39
He's on OSX, so there's only 1 backend. Likely the OSX windowing code doesn't implement the option.

**Comment by Akemi** [comment] 2018-01-14 11:03
yeah that's not implemented on macOS. tbh i wasn't even aware that it was needed. also that being said `--keepaspect` doesn't work as intended either. it also affects fullscreen. for the latter i would have thought this is something the core would do and not something the backend has to decide. wonder what the other backends do.

**Comment by Akemi** [comment] 2018-01-14 15:18
this will be fixed with #4833.

**Comment by Akemi** [comment] 2018-02-12 12:53
fixed via c5e4538bc4b63f02bf89f62aa25a37b9eb0c0316.

**Closed by Akemi** 2018-02-12 12:53 UTC
Labels: osx
