### ISSUE TITLE
OSD text gets stuck when skipping chapters

### ISSUE THREAD

**Issue by SacredZenpie** [mpv-player/mpv#11425] opened 2023-03-08 01:56 UTC
mpv-x86_64-v3-20230305-git-291e05e

### Reproduction steps

Skip chapters with a keybind, the OSD text sometimes doesn't get updated 

### Expected behavior
It would be updated from chapter 3 to 1 in OSD text

### Actual behavior
Gets stuck showing chapter 3 in OSD text

### Log file
As you can see in the screenshot, the bar shows the correct chapter, but the OSD is stuck

![StuckOSD](https://user-images.githubusercontent.com/110957549/223599204-0e5a8774-104c-4a31-9c38-0a32065115e7.png)

**Comment by Dudemanguy** [comment] 2023-03-08 02:10
Needs a log file. In theory this should have been fixed a few days ago (can't reproduce).

**Comment by SacredZenpie** [comment] 2023-03-08 02:16
[log-file.txt](https://github.com/mpv-player/mpv/files/10915734/log-file.txt)
here is the log file

**Comment by Dudemanguy** [comment] 2023-03-08 02:28
Oh so you're not actually paused. Whatever this is must be something else then.

**Comment by Dudemanguy** [comment] 2023-10-22 03:00
Should have been fixed by https://github.com/mpv-player/mpv/pull/12444 actually.

**Closed by Dudemanguy** 2023-10-22 03:00 UTC
Labels: core:osd
