### ISSUE TITLE
Video Output OSD Bug: Needs Cooldown When Scrubbing To End of File

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#3911] opened 2016-12-16 18:53 UTC
### mpv version and platform

[cplayer] mpv 0.22.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sun Dec  4 03:53:53 CET 2016
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.34.100
[cplayer]    libavcodec      57.64.101
[cplayer]    libavformat     57.56.100
[cplayer]    libswscale      4.2.100
[cplayer]    libavfilter     6.65.100
[cplayer]    libswresample   2.3.100
[cplayer] ffmpeg version: 3.2.2

Platform: macOS Sierra

### Reproduction steps

1. Run mpv *.mkv in a folder, to make a playlist.
2. Click and drag on the scrub-bar, and drag the bar to the end of the file. Don't let go of the mouse button.
3. Mpv will advance to the next playlist item, but since you haven't yet let go of the scrub bar (left mouse button), it instantly advances the next file forwards to where your cursor is (instead of starting the new file at 00:00). 
4. Due to this, it's actually possible to kill a whole playlist by just clicking and holding once on the right-hand side of the first video; and whoooosh it'll just fly through all the videos, scrub each instantly to the end of the bar, and then quit.

### Expected behavior

Start every new file at 00:00. That's what people expect from a playlist. They don't expect to scrub *all* videos when they're trying to scrub *one* video.

### How to fix

Decouple the scrub-bar on a per-video basis:

1. In playlist-advance function: Check if mouse-button is held down on the scrub-bar at the moment the playlist is about to advance.
2. If so, set a variable which makes the GUI/OSD scrub-bar immune against mouse-movemen (mouse-scrubbing) of the upcoming playlist item until the user first lets go of the mouse button held down from the previous video. (Ie: Don't let the scrub bar react to the mouse whatsoever; no slider reactions when the cursor moves, _nothing_. It should be completely dead on the new video since the scrubbing the user did of the previous video has nothing to do with the new one.)
3. When the user lets go of the mouse button from the previous video, unset the variable so that it's now possible to click and drag on the new playlist item's own scrub-bar.

**Comment by SteveJobzniak** [comment] 2016-12-17 02:22
# Small test case:

Download this file:

http://jell.yfish.us/media/jellyfish-3-mbps-hd-h264.mkv

Run this command:

mpv jellyfish-3-mbps-hd-h264.mkv jellyfish-3-mbps-hd-h264.mkv jellyfish-3-mbps-hd-h264.mkv jellyfish-3-mbps-hd-h264.mkv --force-window --keep-open=yes

Now click and hold on the scrub-bar and drag to the end of the first video, and hold your mouse cursor there (at the end of the playback bar).

Now check with `>` and you will see that you are already on the last file of the playlist. It scrubbed through all of them.

**Comment by lachs0r** [comment] 2017-07-22 03:38
This should be fixed now. Also, duplicate of #1805.

**Comment by SteveJobzniak** [comment] 2017-07-22 12:10
@lachs0r Hi Martin! You're right. I ran a stock mpv build from a few weeks ago (`0.25.0-257-g3a3a0ac`) to do the test-case again and it seems fixed. Instead of instantly swiping through the entire playlist of all files in 0.0000001 seconds, the playlist-advancing instead offers some "resistance".

It seems like the fix is that the OSD scrub-bar is no longer allowed to scrub to the absolute end of the video anymore. When scrubbing all the way to the right, it stops here (maybe half a second before the end of the video):

![scrub](https://user-images.githubusercontent.com/22373193/28490973-22f90824-6ee7-11e7-9a26-10f5414f13af.png)

So the only way to get it to "eat" a playlist is if the video is playing while scrubbing, and you rest at the "end" (as far as the scrubbing will go) and while still holding down the mouse button (but holding it still) you let it proceed with its standard playback to the end of the file.

And since it stops scrubbing before the end of the file, there's enough time to react and avoid that situation.

Thanks to whoever fixed it. I can't find the commit that did it but yeah it certainly seems fixed.

**Comment by SteveJobzniak** [comment] 2017-07-22 12:24
@lachs0r Oh crap... no... It's not fixed. It's somehow fixed for the jellyfish video (perhaps seeking now jumps to keyframes or something), but with other videos I'm able to scroll to the absolute end pixel of the seek-bar and swipe the entire playlist in a fraction of a second.

**Comment by SteveJobzniak** [comment] 2017-07-22 13:29
@lachs0r Okay I am now using `mpv 0.26.0-9-g2378acc` the absolute latest version, and yes this issue still exists. It hasn't been fixed.

The jellyfish demo had some seek-issue (keyframe landing perhaps?) which made it _seem_ fixed, but it's definitely not fixed.

So let's reopen one of these tickets.

**Comment by lachs0r** [comment] 2017-07-22 14:42
Crap. Well, okay.

**Comment by SteveJobzniak** [comment] 2017-07-22 16:28
@lachs0r Indeed, that word was my reaction too. :-(

**Comment by haasn** [comment] 2017-07-22 16:54
It's worth pointing out that `mpv-progressbar`, which I personally greatly prefer over the horrible built-in OSC, does not have this issue.

So maybe your fix is as simple as just switching to mpv-progressbar ;)

**Comment by SteveJobzniak** [comment] 2017-07-22 17:11
@haasn https://github.com/torque/mpv-progressbar for those interested. I just tried it out and yeah it's very classy and nicely animated. Unfortunately it hasn't got click-and-drag to scrub as far as I can see so I'll skip it for that reason. :-\

**Comment by haasn** [comment] 2017-07-22 18:15
Oh, you're right. I didn't even notice that, no wonder it doesn't have this bug. :p

**Comment by Dudemanguy** [comment] 2022-01-18 17:28
Not sure if this was actually fixed but I don't seem to be able to reproduce. If I click and hold at the end on the default OSC, the playlist will only advance once and not through every video in the playlist. I'll close this for now since it seems very old.

**Closed by Dudemanguy** 2022-01-18 17:28 UTC
