### ISSUE TITLE
A more advanced GUI for mpv? [This is more discussion-centric, less so implementation-centric, but of course if someone has an implementation then that would be neat too]

### ISSUE THREAD

**Issue by rubyFeedback** [mpv-player/mpv#9487] opened 2021-11-20 02:10 UTC
### Expected behavior of the wanted feature

An extended, customisable GUI for mpv.

### Alternative behavior of the wanted feature

Default keep as-is (which is fine too, by the way. This issue is more about a DISCUSSION. I also
propose to keep this time limited, so e. g. not more than half a year or so as far as a discussion
is concerned.)

### Log file

Not needed.

------------------------------------------------------------------------------------------------------------------------------------------------------------------

So, let me talk a bit about the history first.

We kind of had mplayer - and it was great! \o/

Then we had mpv - and it was, or is, great too. It kind of keeps the commandline-first approach,
feels very UNIXy / LINUXy. I know people who prefer vlc, but I was always a mplayer guy and
then mpv. Anyway.

Most of the time I use mpv on the commandline and I don't even watch (most) movies, I just
let them play in the background a bit like how you play audio in the background.

This approach works well 99% of the time.

But!

There is also a time when I want a better GUI.

Now mpv as it is has a useful GUI, we can control a LOT of stuff via keys, such as "f" for
fullscreen and reversion to before-size, and many more keys.

But I am wondering ... would it not be nice to also, optionally, be able to use some key
combination, and/or commandline flag, to use a more advanced GUI?

What I am thinking is something along the lines of smplayer. Perhaps not have as many
features, but something where mpv could be used to "compete" against vlc too.

I don't refer to "turn mpv into vlc", no, the commandline-first focus should be retained
BUT it would be nice if optionally we could have and use mpv just as a drop-in replacement
and perhaps e. g. use an older computer that just is connected to a larger screen, and use
mpv to control that. I know we have other software, but I simply want to keep on using mpv.

I am not saying that "xyz should implement this and it takes a LOT of time" - I am more 
interested in the discussion, how many other people may think is would be useful or 
useless.

IF there is difficulty in choice in regards to which toolkit to use then an abstract toolkit
could be used, which could then have different implementations that share the same 
focus here, e. g. one gtk variant one qt variant, or, perhaps even simpler, pygobject and
ruby-gtk (although I myself have no idea how to easily embed mpv into a GUI ... I
tried via xid or however the name was, and it kind of works, but it was cumbersome to
use too so I dropped that).

I don't have a "set target end point" for this discussion, and again, it is perfectly fine
for people to have another opinion or point out that smplayer or other players already
offer that as a drop-in replacement. I am more interested in asking how the mpv 
core and hobby devs see that feature / functionality, e. g. a bit more competition
against vlc. (I know many windows people prefer vlc because of that. Personally I
use mpv on windows too, but I understand that this is not necessarily the number
#1 choice for windows users.)

**Comment by LaserEyess** [comment] 2021-11-20 02:14
Duplicate of https://github.com/mpv-player/mpv/issues/5500, basically.

**Comment by Dudemanguy** [comment] 2021-11-20 02:20
Duplicate as noted.

**Closed by Dudemanguy** 2021-11-20 02:20 UTC
Labels: meta:feature-request
