### ISSUE TITLE
Better scaletempo (on high speed x1.5-x3)

### ISSUE THREAD

**Issue by TiGR** [mpv-player/mpv#4418] opened 2017-05-11 20:48 UTC
I've been watching some talking videos on youtube and for the most time I've been doing this on x1.5 or x2. Then I've tried watching the same videos via mpv on the same speed, and I've noticed that youtube scaler produces much clearer result. There are no distortions, and you can clearly understand what is being said.

Then I've read what there is in man re scaletempo filter, and tried using some tricks that are there to increase the quality, but was unable to achieve similar quality result.

It would be really nice if we could really use high-speed viewing in mpv without distortions or similar effects.

**Comment by wiiaboo** [comment] 2017-05-11 20:54
Try rubberband.

**Comment by TiGR** [comment] 2017-05-11 21:01
Rubberband immediately creates echo chamber effect. It has some options, but it is really unclear what all these options do and how I could increase quality.

**Comment by wiiaboo** [comment] 2017-05-11 21:03
You're going to have to post some samples and exact software names and versions. Just "make it sound better" isn't reasonable.

**Comment by wiiaboo** [comment] 2017-05-11 21:14
Unless they've changed meanwhile, Firefox uses exactly the same SoundTouch algorithm (which mpv is also based/inspired on). Chrome uses their own NIH version of the same WSOLA technique. They shouldn't sound that drastically different from each other.

**Comment by TiGR** [comment] 2017-05-11 21:16
Lets take [this video](https://www.youtube.com/watch?v=ZnRAA0CeSIk). Play it in youtube (I was testing in chrome), try increasing speed to x2. Please use headphones. If you do the same with mpv and rubberband, well, it is still detailed and you can understand the speech and there are not distortions like with scaletempo, but you can hear that there is an echo as if it was recorded in pretty small room.

**Comment by wiiaboo** [comment] 2017-05-11 22:09
That "echo" you mention with rubberband can be configured. There are a lot of configurations available if you're unhappy with the defaults. They're different techniques of stretching/shrinking the playback rate without changing pitch.

Also, let's use a speech sample instead: https://i.fsbn.eu/pub/mpv-speed/
So what you want exactly is a port of Chrome's code to mpv, which sounds negligibly better, when you could just use rubberband and actually understand the speech.

**Comment by wm4** [comment] 2017-05-12 05:02
Feel free to port Firefox' implementation to mpv, since librubberband is a bit "annoying" in multiple aspects.

**Comment by TiGR** [comment] 2017-05-12 06:10
> That "echo" you mention with rubberband can be configured. There are a lot of configurations available if you're unhappy with the defaults. They're different techniques of stretching/shrinking the playback rate without changing pitch.

Yes, I know that, but there is no proper documentation in man file, and in help. Help really sounds like chinese without giving any explanation what each option means. So the only way to configure it is by poking random settings, testing the result and hoping for the best (and there are over 300 possible combinations of these options plus one option with floating number value).

> So what you want exactly is a port of Chrome's code to mpv, which sounds negligibly better, when you could just use rubberband and actually understand the speech.

No, what I want is to be able increase speed without experiencing any artifacts (such as echos, distortions, and so on).

**Comment by wiiaboo** [comment] 2017-05-12 10:51
> So the only way to configure it is by poking random settings, testing the result and hoping for the best (and there are over 1000 possible combinations of these options plus one option with floating number value).

http://breakfastquay.com/rubberband/code-doc/classRubberBand_1_1RubberBandStretcher.html

> No, what I want is to be able increase speed without experiencing any artifacts (such as echos, distortions, and so on).

Feel free to come up with a better and LGPL or freer algorithm then. If it's way better than SoundTouch and rubberband I'm sure other open source software would appreciate it too.

**Comment by garoto** [comment] 2017-05-12 17:27
[**@TiGR**](https://github.com/TiGR) commented on [May 11, 2017, 6:01 PM GMT-3](https://github.com/mpv-player/mpv/issues/4418#issuecomment-300915912 "2017-05-11T21:01:59Z - Replied by Github Reply Comments"):
> Rubberband immediately creates echo chamber effect. It has some options, but it is really unclear what all these options do and how I could increase quality.

When I started to mess with mpv's librubberband implementation, I was even struggling to get the right `--af` syntax for the filter, but once I figured that one out, the best I was able to come up with to get rid of the very prominent echo/ringing/phase distortion was this: 

`--af="rubberband=transients=smooth:pitch=quality:window=short"`

I'm satisfied how it sounds with these settings, give those a try I guess.

And for input.conf I have these binds setup:
```
[ af add "@rubber:rubberband=transients=smooth:pitch=quality:window=short" ; add speed -0.25
] af add "@rubber:rubberband=transients=smooth:pitch=quality:window=short" ; add speed +0.25
\ af del @rubber ; set speed 1.0```

**Comment by haasn** [comment] 2017-05-12 17:56
@wm4 Seems like we need “af enable/disable” commands to make @garoto's example less ugly?

Either way, shouldn't rubberband be a no-op for speed 1.0 already.

**Comment by wm4** [comment] 2017-05-12 18:17
We already have such commands.

**Comment by haasn** [comment] 2017-05-12 18:37
@wm4 Really? All I can see are:

1. set -> overrides the entire `af` string, and can't be used without parameters
2. add -> also can't be used without parameters
3. del -> completely removes the filter, can't be re-enabled afterwards again without parameters
4. clr -> completely nukes the list
5. toggle -> can only toggle on or off, not explicitly set the enabled state

I'm not sure what I'm missing.

**Comment by wm4** [comment] 2017-05-12 19:02
RTFM, search for ` @deband` for an example.

**Comment by garoto** [comment] 2017-05-12 19:13
[**@haasn**](https://github.com/haasn) commented on [May 12, 2017, 2:56 PM GMT-3](https://github.com/mpv-player/mpv/issues/4418#issuecomment-301144165 "2017-05-12T17:56:20Z - Replied by Github Reply Comments"):
> Either way, shouldn't rubberband be a no-op for speed 1.0 already.

Seems that `set speed 1.0` will not remove `rubberband` from the `af` filter chain (which seems reasonable if my poor logic is correct). If I remove the `af del @rubber` part, I need to manually clear the filter chain with `af set ""` to have audio play without distortion.

**Comment by wiiaboo** [comment] 2017-05-12 19:39
The fact that rubberband isn't no-op at speed=1 is a known issue since it was first added.

**Comment by TiGR** [comment] 2017-05-12 19:44
@garoto thanks, this is better, but still produces some sort of robotic sound.

So, I've compared Firefox, VLC, MPV (both rubberband and scaletempo in default and custom settings), Chrome and Chromium. Chrome and Chromium produce equal result, so I think that it should be open source. So, if I were to rate these, the rating would be:

1. Chromium (Chrome). Generally you hear the same sound, just faster, at x2 sometimes you can get singular momentary distortions, but asid from that, sound is perfect.
2. Firefox and VLC, these sound somewhat similar. There are minor distortions on some specific sounds, you get these frequently, but in general it is okay. These distortions happen where chromium works well and clear.
3. MPV. A lot of distortions/artifacts/echoes. You can clearly hear that sound changes.

I know nothing about the technologies being used or maybe specific tuning that was made in each project, I am just user here.

**Comment by aitte2** [comment] 2017-06-08 13:59
@garoto Thanks I will try your settings.

I also found this related ticket about rubberband::reset (to fix sound at 1.0 speed?) and getLatency (to fix mpv's desync when using rubberband):

https://github.com/mpv-player/mpv/issues/3928

**Comment by SteveJobzniak** [comment] 2017-06-13 18:58
@garoto @TiGR Those settings are bad. They seem to reduce the processing buffer size, which instead produces "warbling"/fluttering.

All I have in my mpv.conf is this: `af=rubberband=channels=together`.

That's the most important tweak. It tells rubberband to keep the left and right channels in sample-accurate sync. "channels=together" means "use the stereo-coherent phase mode". That's what gets rid of the phasiness. But it costs a LOT more CPU usage. So use it at your own risk.

**Comment by wm4** [comment] 2017-06-13 19:03
So we should change the defaults for this one?

**Comment by SteveJobzniak** [comment] 2017-06-13 19:08
@wm4 Rubberband defaults to "process each channel independently and spit them out whenever they're ready, even if that means they drift out of stereo sync", which creates a very weird phase/tunnel sound effect.

The problem with channels=together is that it increases Rubberband's CPU requirement quite a lot. I suppose it is some complex algorithm which syncs the two channels and their independent post-processed buffers.

You can try it out and check the CPU usage increase when scaling the video to a speed of 0.25 or something heavy like that. From memory, running Rubberband in channel-together mode increased the CPU usage quite a lot. But if you think the CPU usage is acceptable as a new default then sure go ahead and add channels=together as a default. It sounds much better. :-)

**Comment by wiiaboo** [comment] 2017-06-13 19:31
channels=together IS the default. Since https://github.com/mpv-player/mpv/commit/f504661852dbd7b8ff28013ffed069de75de1826.

**Comment by SteveJobzniak** [comment] 2017-06-13 21:07
@wiiaboo Nice discovery!

**Comment by wm4** [comment] 2017-06-13 21:16
It was done over half a year ago in f504661852dbd7b8ff28013ffed069de75de1826.

**Comment by stevenxed** [comment] 2018-01-25 20:55
@TiGR @wiiaboo 
I've fine tuned the settings a bit and this is what I got.
`af=scaletempo=stride=16:overlap=.68:search=8`
Sounds similar to chrome's implementation enough for me at x2 speed. Just posting this for others to test.

**Comment by wiiaboo** [comment] 2018-01-25 21:09
Doesn't `search` only affect performance?

**Comment by stevenxed** [comment] 2018-01-25 21:10
It also seems to have an effect on how robotic the audio sounds.

**Comment by TiGR** [comment] 2018-01-26 07:45
@stevenxed Cool. It is perfect on speech. However, it adds some strange distortions on some kind of music, for example, [here (first 28 seconds)](https://www.youtube.com/watch?v=bvBpDpYdfm8) on x2. Interestingly, default scaletempo plays it well. And yes, it requires some extra processing (around 4 extra percent points on my CPU. CPU usage increased from 17% to 21% on FullHD x2 playback).

**Comment by stevenxed** [comment] 2018-01-26 16:07
@TiGR 
Try this: `af=scaletempo=stride=22:overlap=.55:search=12` 
The music with only`scaletempo `on x2 speed sounds a tiny bit better/clearer than chrome's implementation. So yeah, you gotta compromise with music/speech. That should be good enough.

**Comment by christoph-heinrich** [comment] 2018-02-25 00:50
I've stumbled upon this discussion in the search for better scaletempo settings, so I came back to share what I found out. The best I was able to come up with over the past couple of days is this: `af=scaletempo=stride=28:overlap=.9:search=25`
So far I was not able to notice any artifacts or distortions with this setting while watching videos or listening to music (for the purpose of testing) at different speedups.

It's harder on the CPU compared to the settings you have proposed so far (6%-7% instead of 2%-3% while double speed music on my AMD 1100T), however for me that tradeoff is well worth it.

Also worth noting is that i have noticed a "rule" while testing different settings. Higher values for `search` are generally better, however `speed` >= `stride` * `overlap` leads to artifacts or distortions in some situations.

**Comment by smhmd** [comment] 2020-04-10 06:26
> So we should change the defaults for this one?

@wm4 Please, yes. I use increased playback speed almost every day and no proposed solution has been flawless. I couldn't tell you how much this matters.

**Comment by wm4** [comment] 2020-04-10 07:22
To what?

**Comment by smhmd** [comment] 2020-04-10 07:42
@wm4
One of the problems with solutions on this issue (e.g. `af=scaletempo=stride=28:overlap=.9:search=25`) is that they work for speeds of `x1.5`-`x1.7`, but they affect the clarity of `x1` and sound just as bad with `x2+`. 

Maybe Chromium's implementation? Artifacts are minimal regardless of what the playback speed is. (https://github.com/mpv-player/mpv/issues/6471#issuecomment-472608028 -- sadly, I'm no C developer.)

Most values for `af` have been produced by entering random numbers as stated. I think you'd have better luck.

**Comment by megapro17** [comment] 2020-05-28 14:44
when this will be fixed? chromium implementation is great

**Comment by wm4** [comment] 2020-05-28 14:50
Nobody is working on it.

**Comment by megapro17** [comment] 2020-05-28 14:52
one of the main features of player is broken, and nobody cares, great

**Comment by Akemi** [comment] 2020-05-28 14:58
great a volunteer, we are looking forward to you contribution of a new scaletempo filter.

**Comment by megapro17** [comment] 2020-05-28 15:17
Maybe I just a better player instead? if you can't fix it in three years. Mpc-be for example

**Comment by Akemi** [comment] 2020-05-28 15:28
that's a totally valid and we welcome your move into greener pastures. mpc-be is a great player for windows. thank you for your kind input and we hope you'll enjoy the experience mpc-be will provide you in the future.

**Comment by smhmd** [comment] 2020-05-29 14:52
@Akemi [This random commit](https://chromium.googlesource.com/chromium/src/+/ab98b39d38e0c5678a209c5e980a8974bd114eea%5E%21/) from Chromium suggests that they're using a certain [WSOLA algorithm](https://www.audiolabs-erlangen.de/content/05-fau/professor/00-mueller/01-students/2011_DriedgerJonathan_TSM_MasterThesis.pdf). And perhaps the source code for their implementation of the algorithm is [this header file](https://chromium.googlesource.com/chromium/chromium/+/51ed77e3f37a9a9b80d6d0a8259e84a8ca635259/media/filters/audio_renderer_algorithm.h) and [this C++ file](https://chromium.googlesource.com/chromium/chromium/+/51ed77e3f37a9a9b80d6d0a8259e84a8ca635259/media/filters/audio_renderer_algorithm.cc). (Again, I'm not a C/C++ dev)

**Comment by Akemi** [comment] 2020-05-29 17:10
it's probably the best to request this from ffmpeg, so not only mpv can benefit from it, tbh.

**Comment by megapro17** [comment] 2020-05-29 17:29
@Akemi ffmpeg already has wsola algorithm called atempo, sounds a bit worse than chromium https://ffmpeg.org/ffmpeg-filters.html#rubberband

**Comment by wm4** [comment] 2020-05-29 17:34
mpv's implementation is also WSOLA.
ffmpeg's implementation can't be used in mpv.

**Comment by megapro17** [comment] 2020-05-29 17:48
whatever they're both suck compared to chromium

**Comment by varenc** [comment] 2020-06-12 06:49
For 2.25x audio playback, the `atempo` filter is performing waaay better for me than `rubberband` and `scaletempo`.  (tried many different option settings)

I recommend folks give this a try! Though this comes with some serious caveats.

When using `--af=atempo=...` the mpv playback speed and atempo speed don't smartly synchronize like they do with rubberband and scaletempo.  They're completely independent, so atempo always desyncs the audio and playback position. And if there's also and mpv playback speed those end up getting multiplied.


For example...

- With `mpv --af=atempo=2 --speed=1` I get to experience atempo's near-Chrome quality speed up, but mpv isn't aware of the speed change and you'll finish listening to the audio when you're half way through the file.

- With `mpv --af=atempo=2 --speed=2`, the audio plays at 4x speed! I believe atempo applies's a 2x speed increase to the 2x scaletempo speed increase mpv already applied.

- Very confusingly, with `mpv --af=atempo --speed=2`, you don't get any of the atempo benefits since this just defaults to meaning `--af=atempo=1` and mpv using the default scaletempo to actually do the speedup.

I assume the root cause of this is that `atempo` is a libavfilter and not something built-in to MPV? [This note explains...](https://github.com/mpv-player/mpv/blame/master/DOCS/interface-changes.rst#L251):
> having libavfilter based filters after the scaletempo or rubberband
          filters is not supported anymore, and may desync if playback speed is
          changed (libavfilter does not support the metadata for playback speed)


This desyncing means atempo is useless for speeding up video playback... Though I found a hacky solution by doing `mpv --af=atempo=2 --vf=lavfi=[setpts=PTS/2]` which doubles video playback speed in a non-mpv-aware way.  It mostly works when the video starts but seeking instantly desyncs you.

Anyone have ideas for workarounds?  Anyway to sync up `atempo` with mpv/video playback speed?

**Comment by wm4** [comment] 2020-06-12 09:22
> Anyway to sync up atempo with mpv/video playback speed?

No, that's not possible. FFmpeg doesn't offer the required APIs.

**Comment by richardpl** [comment] 2020-06-12 09:50
What APIs are actually missing in FFmpeg?

**Comment by wm4** [comment] 2020-06-12 09:52
Audio speed & virtual PTS.

**Comment by richardpl** [comment] 2020-06-12 10:16
Isn't speed done with asetrate filter? What is virtual PTS?

**Comment by wm4** [comment] 2020-06-12 10:57
It PTS for speed changed audio that ffmpeg shitfuckery can't comprehend. Computed from virtual samplerate, which is real samplerate multiplied with fractional (well, float) speed value for maximum precision. Playback uses real samplerate, PTS calculations and A/V sync use virtual PTS.

**Comment by richardpl** [comment] 2020-06-12 14:48
I have patch that prove no additional APIs in libavfilter are required to get atempo filter working with mpv. I just cant get it to work with 1.5/or 1.3 tempo, nice numbers like 2.0 works fine.

**Comment by wm4** [comment] 2020-06-12 14:54
Patch is wrong.

**Comment by richardpl** [comment] 2020-06-12 19:29
i will send patch to fix mpv soon.

**Comment by wm4** [comment] 2020-06-12 19:37
FFmpeg is bug

**Comment by richardpl** [comment] 2020-06-12 19:50
Grow mushrooms.

**Comment by DorianRudolph** [comment] 2020-07-04 23:20
It would be great if someone could try out the code from my pull request.

**Comment by alopatindev** [comment] 2020-07-07 20:29
@DorianRudolph wow, thanks for your PR! I tested it with a few videos and it seems it works great to me!

**Comment by Syzygianinfern0** [comment] 2020-11-13 12:55
> It would be great if someone could try out the code from my pull request.

How can I use this?

**Comment by wiiaboo** [comment] 2020-11-13 14:16
Adding `--af=scaletempo2` should be enough (and `--speed N` like normal), but you need to be on a mpv build newer than the newest release for it to be available.

**Comment by smhmd** [comment] 2020-11-13 14:17
@DorianRudolph @alopatindev You think so? The more you increase the speed (`2.0-2.3`), it sounds like `mpv` is skipping some chunks of audio to keep in sync with the video. Instead of hearing the word "string" speed up, you hear "stg".

Can you compare with this profile:
```
[pitch]
af=scaletempo=stride=28:overlap=.9:search=25
```
`mpv --profile=pitch` and tell me it doesn't sound better than the PR in `2.5` range? (I think `1.5 - 1.8` is alright`.)

**Closed by wiiaboo** 2020-11-13 14:16 UTC
Labels: core:audio, filter, meta:feature-request

**Comment by AhmedThahir** [comment] 2021-01-25 13:08
Hi, it's not working for me.


The following is my mpv.conf

volume-max=100
border=no
save-position-on-quit
sub-delay=0
speed=2.5

#video
profile=gpu-hq
video-output-levels=full
target-trc=gamma2.2
target-peak=300
gamma-factor=1.2
hdr-compute-peak=no
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
video-sync=display-resample
interpolation
tscale=oversample
brightness = 0
contrast = 0
gamma = 0
hue = 0

#audio
af=scaletempo2
af=lavfi="dynaudnorm=m=5:n=0:g=15:f=250:p=0.9:r=0.5"



input.conf
a add speed -0.5 
r set speed 2.5
s add speed 0.5

WHEEL_UP add volume 10
WHEEL_DOWN add volume -10

Ctrl+RIGHT seek 60 
Ctrl+LEFT seek -60

up add volume 10
down add volume -10

**Comment by smhmd** [comment] 2021-01-25 13:10
@AhmedThahir Have you rebuilt MPV from `master` yourself?

**Comment by AhmedThahir** [comment] 2021-01-25 13:11
No.
I installed mpv from mpv.io website which sent me to sourceforge.
This was the download link (latest version)
https://liquidtelecom.dl.sourceforge.net/project/mpv-player-windows/64bit/mpv-x86_64-20210117-git-a3e440c.7z

**Comment by smhmd** [comment] 2021-01-25 13:15
You need to build mpv yourself as `scaletempo2` has yet to land on an official release. `scaletempo2` is not bad at all. It would be worth it. @AhmedThahir

**Comment by AhmedThahir** [comment] 2021-01-25 13:18
Could you send me a video demonstrating how to build it?

**Comment by Syzygianinfern0** [comment] 2021-01-25 13:21
> Could you send me a video demonstrating how to build it?
> Or could you build it for me and send it?

Check out https://github.com/mpv-player/mpv#compilation

**Comment by wiiaboo** [comment] 2021-01-25 13:24
> You need to build mpv yourself as `scaletempo2` has yet to land on an official release. `scaletempo2` is not bad at all. It'll be worthwhile. @AhmedThahir

It is in [master](https://mpv.io/manual/master/#audio-filters-scaletempo2[) already, and [0.33.0](https://mpv.io/manual/stable/#audio-filters-scaletempo2[):

You don't need any external libs for it to be available.

**Comment by smhmd** [comment] 2021-01-25 13:24
@AhmedThahir  I've never built it myself. I just ran [`yay -S mpv-git`](https://aur.archlinux.org/packages/mpv-git/) as I'm using Arch Linux which builds from git. You are on Windows. I wouldn't know where to start, unfortunately.

**Comment by gwarser** [comment] 2021-01-25 13:24
> #audio
> af=scaletempo2
> af=lavfi="dynaudnorm=m=5:n=0:g=15:f=250:p=0.9:r=0.5"

Your config overwrites scaletempo2 by lavfi filter. Use af-add.

**Comment by AhmedThahir** [comment] 2021-01-25 13:30
> > #audio
> > af=scaletempo2
> > af=lavfi="dynaudnorm=m=5:n=0:g=15:f=250:p=0.9:r=0.5"
> 
> Your config overwrites scaletempo2 by lavfi filter. Use af-add.

Oh wow ... Thank you so much. It works now!

**Comment by gwarser** [comment] 2021-01-25 13:32
You may need to check which one should be first. MPV printed warnings for me when dynaudnorm and scaletempo were swapped, but I don't remember the in what order they should be added.

**Comment by dmp1ce** [comment] 2021-02-10 18:15
I added to following to be able to understand speech at x3 speed like I can on most AntennaPod.

```
$ cat ~/.config/mpv/mpv.conf 
# Try to improve speed up audio playback
af-add=scaletempo2
```

**Comment by berndbb** [comment] 2021-04-02 15:35
I came in contact with the new filter scaletempo2 when updating mpv.

What I regularly do is revert "pal speed up" (meaning 24 fps movies are shown in 25fps which is the TV standard here by speeding up the playback speed). So I use very low speed values like --speed=24000/25025 when playing those TV recordings.

The new default gave me results worse than the old (=scaletempo without the "2") default: Speech was o.k, but background music sounds like being played from an old tape changing constantly its playback speed (so the pitch is altered constantly).

Is this filter not meant to be used with lower "--speed" values? Or does someone has a recommendation on how to set the options in scaletempo2 when using speed changes of about 4%?

**Comment by richardpl** [comment] 2021-04-02 20:36
You could try atempo lavfi filter, but there is not currently support for that in mpv.

**Comment by varenc** [comment] 2021-04-03 02:42
I agree with @berndbb that the new `scaletempo2` performs worse for minor speed changes, but I only switch it manually when I'm doing a very high rate playback speed change.  berndbb, instead of tweaking scaletempo2's settings, can't you just keep using the original `scaletempo` filter?  If there's no filters in the audio filter chain at all, then I believe it still uses scaletempo as then default. Then I just toggle scaletempo2 on and off with a shortcut.

**Comment by berndbb** [comment] 2021-04-03 11:56
I added scaletempo to my filter chain and the old behaviour seems to be back. Adding explicitly scaletempo2 to my filter chain reproduces the weird audio I experienced after my last update of mpv. 
I understood from the man page that scaletempo2 is now added by default when changing playback speed.

So since this new filter is so much praised here, I wondered if I can take its advantages for my setup too (meaning low playback speed change of about four percent). The default don't work for me at all, I would rather leave out pitch correction than using scaletempo2 so far. But even with the old scaletempo it is an open question for me which is the better option ...

Concerning atempo: As described [here](https://github.com/mpv-player/mpv/issues/4418#issuecomment-643099263), using atempo will sooner or later lead to audio/video not beeing in sync.

**Comment by DorianRudolph** [comment] 2021-04-04 13:29
@berndbb Wow that sounds really bad in places. For example the 0:40-0:50 in https://www.youtube.com/watch?v=XpFKPVquSeA at 0.96x. But the issue is reproducible in chromium, so it seems not be a bug in my implementation. Maybe someone can report this as a bug to chromium. If they fix it, I would be happy to port their fix. Unfortunately, I barely understand this algorithm enough to port it over from chromium, but I don't know how to tune it properly.

Depending on how the pal speedup was done, they might have just resampled the audio without any pitch correction. In that case, resampling is definitely the correct choice.

**Comment by richardpl** [comment] 2021-04-06 18:01
You should really use atempo. and fix mpv.

**Comment by varenc** [comment] 2021-04-07 21:59
I also just realized that scaletempo2 is now the default as of #8376. But sadly it's still noticeably worse on minor speed differences for me.   With the `scaletempo` default, the a x0.95 speed change was barely perceptible. But with scaletempo2 there's a noticeable stuttering effect.  It seems worse on 5.1 surround audio sources.  I don't think it should have been made the new default....

**Comment by DanOscarsson** [comment] 2021-04-09 10:22
I have tested atempo, scaletempo and scaletempo2 at different speeds and a few different audio tracks.
For me it is difficult to hear which is best. For slow 0.5-0.75 scaletempo2 is better then scaletempo.
At speed 2 and 3 I nearly think atempo is best and scaletempo2 worst. At least if you try to understand what people are saying (which is what is most important for me). But, for me, the differences are small. At 0.95-1.05 I do not know which is best.
My need is for higher speeds (like 2 or 3). I never use a speed below 1.5 except 1.
When I view a 25 Hz video on a 24 Hz (or 23,976 Hz) display I let mpv sync audio to video by resampling.
That way I get very good sound, the pitch change (or restored pitch) of about 4 % does not bother my and I think not most people.
To choose which is best I think several people with a good ear need to test all three filters at different speeds and sound.

**Comment by DorianRudolph** [comment] 2021-04-09 12:06
@DanOscarsson I understand that this highly subjective, but I am surprised that you prefer scaletempo over scalemtepo2 at 2x. For me scaletempo at 2x is unlistenable, which is why I wrote scaletempo2 in the first place. But maybe I just go used to it because of listening to youtube videos at 2x in chromium.

It seems nobody dislikes atempo, so maybe it would be worth it to get that to work in mpv to make everybody happy.
What changes would be necessary to get atempo to work? There should also be the option to just port atempo if ffmpeg does not  expose the interfaces we need.

**Comment by richardpl** [comment] 2021-04-11 17:54
Out of question, mpv broken behavior should be fixed first.

**Comment by Akemi** [comment] 2021-04-11 18:24
i would welcome if you could keep those unnecessary comments to yourself in the future. you already said that. please keep the comments to constructive contributions. 

since you mentioned having a patch for this already, which didn't work completely, it might be a good idea opening a PR and we could sort out the rest together?

**Comment by toprak** [comment] 2023-05-19 01:54
@TiGR How did you use scaletempo on chromium, I could not find a way to do it.

**Comment by TiGR** [comment] 2023-05-19 04:38
@toprak chromium has no scaletempo, it uses another engine that was ported to MPV as scaletempo2 (see previous comments here),

**Comment by toprak** [comment] 2023-08-18 14:51
@DorianRudolph I don't know if it's because I'm using [thorium](https://github.com/Alex313031/thorium) but the same video, same speed sounds cleaner in thorium, or rather it sounds even faster in mpv, maybe they threw an extra audio patch, do you have a chance to examine this when you have a chance/free ?
