### ISSUE TITLE
Wrap show-text output at window width

### ISSUE THREAD

**Issue by mustaqimM** [mpv-player/mpv#8115] opened 2020-09-24 08:02 UTC
### Expected behavior of the wanted feature
The output of `show-text` should not pass the current window width(it could be wrapped in a column of a specific width).

Currently if the output line is longer then the width of the screen, it looks like this: 
![image](https://user-images.githubusercontent.com/24436622/94117365-a69c2d00-fe3b-11ea-9292-9a513142129f.png)

**Comment by Akemi** [comment] 2020-09-24 09:32
duplicate of #2203. 
reported to libass https://github.com/libass/libass/issues/348 https://github.com/libass/libass/issues/360

**Closed by Akemi** 2020-09-24 09:32 UTC
Labels: meta:feature-request
