### ISSUE TITLE
The cursor stay hidden even when moving it

### ISSUE THREAD

**Issue by sCreami** [mpv-player/mpv#4174] opened 2017-02-20 19:17 UTC
The commit fffab30 introduced a new issue with the interface. The cursor can stay hidden even when moving it after changing of focused window.

### mpv version and platform
git-master
macOS 10.12.3

### Reproduction steps
Change the focused window while leaving mpv playing, return to mpv.

### Expected behavior
The cursor appears everytime it is moved.

### Actual behavior
It stays hidden.

### Log file
Nothing special in the log.

**Comment by Akemi** [comment] 2017-02-20 20:14
this is a bit dumb. seems like the out of focus window doesn't report any mouseDown/Up events. i could use the windowDidMove event, but that won't completely fix the issue that this is supposed to fix. it can trigger several times per windowWillMove.

**Comment by sCreami** [comment] 2017-02-20 20:37
How about making a relatively sized rectangular area in the center of the window where the cursor will always stay visible, and outside will be allowed to fade out?
https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/EventOverview/MouseTrackingEvents/MouseTrackingEvents.html

**Comment by Akemi** [comment] 2017-02-20 20:40
that doesn't fix the issue and sounds like very unexpected behaviour.

**Comment by sCreami** [comment] 2017-02-20 22:02
[cocoa_common.m#L951](https://github.com/mpv-player/mpv/blob/fffab30a3ef01dc6f34adadccb05617f4a3a528e/video/out/cocoa_common.m#L951)

This condition is really the root of this issue. Was this edit essential? I can't reproduce it.
Surely there's another condition that can be appended to make the cursor appears when the window is not being dragged.

**Comment by Akemi** [comment] 2017-02-20 23:21
i know what causes it and yes it is essential to the fix/commit. just read the commit message.

your are thinking into the wrong direction with your proposed fixes. no a condition to unhide the cursor won't fix it, because the problem is not unhidnig the cursor but rather that cocoa is in a state where it discards all mouse movements. the root is that not every windowWillMove has a corresponding windowDidMove or mouseUp event, leaving cocoa in a state of 'always dragging'.

**Comment by Akemi** [comment] 2017-02-21 17:05
feel free to test [this fix](https://github.com/Akemi/mpv/commit/c95bc1d94240edf776c1c5ed9183e5082250537c).

**Comment by sCreami** [comment] 2017-02-21 17:36
works good enough for me 👍

**Comment by Akemi** [comment] 2017-02-21 18:31
fixed via https://github.com/mpv-player/mpv/commit/c824a023c4f640dd72d4c5dc1511eb53055d7535

**Closed by Akemi** 2017-02-21 18:31 UTC
Labels: osx
