### ISSUE TITLE
multiple instance seperating volume control

### ISSUE THREAD

**Issue by phantomgz** [mpv-player/mpv#2577] opened 2015-12-10 11:25 UTC
I want to instance multiple video playing in a single application, follow the example of "qt_opengl" .
I open two mpv handle, all two videos is playing well, but when adjust volume of  one instance, the volume of other instance would be changed to same time.
I have try to set "softvol=yes", but strange, all sound mute at all.

my building and running environment is Window8.1 + QT 5.5.1 + mingw32

**Comment by wm4** [comment] 2015-12-10 18:10
Can you reproduce this with mpv CLI?

I don't know what's your problem with softvol=yes.

**Comment by phantomgz** [comment] 2015-12-11 01:40
I don't know how to create two mpv instance with CLI, could you help me?
I'm build with libmpv in QT, 
just forget softvol setting.

**Comment by phantomgz** [comment] 2015-12-11 03:01
I found the default ao use wasapi, when I just change "ao" to "dsound", the volume can control seperated.

**Comment by kevmitch** [comment] 2015-12-12 01:53
This is the way per-app volume control works. According to [msdn](https://msdn.microsoft.com/en-us/library/windows/desktop/dd370796%28v=vs.85%29.aspx), multiple audio streams created within the same process will by default share the same audio stream and therefore also share a windows mixer volume slider.

Dsound behaves differently because it implements an internal equivalent to softvol=yes.

It sounds like what you really want is softvol=yes. Are you saying that this prevents sound output? What are the values of the "mute" and "volume" properties.

**Comment by kevmitch** [comment] 2015-12-12 02:00
I tried generating a new session GUID for each IAudioClient_Initialize, which would also solve your immediate problem, but this creates a new session each time mpv reinits the audio chain leading to an undesirable proliferation of volume sliders in the windows mixer.

**Comment by kevmitch** [comment] 2015-12-12 02:21
Your softvol=yes issue may be fixed by 000285ee8e077f5b0cd391ffc30cc71e5a3c728d.

**Closed** 2016-12-25 09:09 UTC
Labels: info-needed, ms-windows
