### ISSUE TITLE
Tone Mapping vo=gpu vs gpu-next different

### ISSUE THREAD

**Issue by pillepalle1234** [mpv-player/mpv#9732] opened 2022-01-20 16:58 UTC
- mpv version: mpv-x86_64-20220116-git-1ba0547
- Platform and Version: Windows
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/

If i use Tone Mapping with the same algorithm with vo=gpu or gpu-next the picture is quite different.
Config used:
gpu-api=vulkan
target-peak=150
target-prim=dci-p3
target-trc=gamma2.2
hdr-compute-peak=yes
tone-mapping=bt.2390
tone-mapping-mode=auto

gpu (clouds especially dont look good):
https://ibb.co/pXws2hb

gpu-next (much better)
https://ibb.co/ftGQj6W

bt.2446a looks really bad in most scenes (really dim with a sort of grey fog over everything, but here it works quite good)
https://ibb.co/HCrYYnK

Why is it so differrent?
And why is bt.2446a recommended when it looks really bad in most circumstances?

### Expected behavior
Should look the same.

### Actual behavior
gpu-next looks much better

**Comment by epicfilmmaker93** [comment] 2022-01-22 19:50
I think #7984 is related

**Comment by ValZapod** [comment] 2022-01-25 14:34
> target-prim=dci-p3

This is wrong. No one uses dci-p3, use display-p3. Wow. Documentation update is needed.

**Comment by ValZapod** [comment] 2022-01-25 19:08
Anyway there is indeed off-by-one in vo gpu and vo gpu-next when converting from display-p3 image to dci-p3. Thag may be due to DCI white point change, I mean it is a hard math.

**Comment by ValZapod** [comment] 2022-01-25 19:12
Also gpu-next can see display-p3 image, while gpu cannot and requires --vf=format=primaries=display-p3 to work (I was using it to test off-by-one above).

**Comment by pillepalle1234** [comment] 2022-01-25 21:27
My movie rips are all in BT.2022 but only (99,5%) use the dci-p3 range of that. My JVC X7900 is calibrated to DCI-p3 aswell. (using a spectrometer referenced colormeter). 

Why would i use display p3?

Tone mapping converts every movie with pq Gamma to gamma 2.2 in my config.

Am i missing your point?

**Comment by ValZapod** [comment] 2022-01-25 23:24
> but only (99,5%) use the dci-p3 range of that.

No movie uses display-p3. They use all bt.2020 primaries.

> My JVC X7900 is calibrated to DCI-p3 aswell.

That uses DCI white point??

> Why would i use display p3?

Because D65 is what is used in BT.2020.

> every movie with pq Gamma to gamma 2.2 in my config.

Oh, okay, but you still want to use WCG (wide color gamut?)

**Comment by pillepalle1234** [comment] 2022-01-26 11:07
I am sorry i am quite new to the sphere of color reproduction etc...

I am slowly understanding what you say. 

> No movie uses display-p3. They use all bt.2020 primaries.

They use bt.2020 but not the whole thing, since 95% of displays cant display full bt.2020. So afaik most movies just use the DCI-P3 primaries. I´ve seen a lot of graphs about that on avsforum, but cant find the thread just now..


>Because D65 is what is used in BT.2020. But of course if your projector is really DCI whitepoint, then not needed, you target dci-p3.

No, im sorry, see my first sentence. I am using D65 whitepoint, so now i understand what you mean by Display P3 instead of DCI-P3.

> Oh, okay, but you still want to use WCG (wide color gamut?)
Yes, in the end it is SDR with WCG. (After tone mapping)

**Comment by ValZapod** [comment] 2022-01-26 21:25
> They use bt.2020 but not the whole thing, since 95% of displays cant display full bt.2020.

But cemaras can and Maya, and so do some Blu-ray even if mastered on Display P3 monitor! Example is Planet Earth 2 and 2 latest Star wars and animations like Lego Batman Movie and Spuderman: Into the spider-verse, etc. See video: https://youtu.be/0XTgz5Z1bhE and https://youtu.be/Hssiak8c4Js

Also games do have it, like Call of duty.

**Comment by Natural-Harmonia-Gropius** [comment] 2022-01-26 21:44
People call it rec2020_p3_limited.

**Comment by ValZapod** [comment] 2022-01-26 21:59
> rec2020_p3_limited

Dolby vision is rec2020_p3_full ;) Where is this name used?

**Comment by Natural-Harmonia-Gropius** [comment] 2022-01-26 22:18
> mastered on Display P3

this
and rec2020_p3_full doesn't existed.

**Comment by ValZapod** [comment] 2022-01-26 22:58
> this

So you came up with this name yourself? And yes, dolby vision uses full range.

**Comment by Natural-Harmonia-Gropius** [comment] 2022-01-26 23:22
> So you came up with this name yourself

Select it, Right click, Search on web. Boom!
stab something after google it pls, google show me 0 result about rec2020_p3_full, lol.

> dolby vision IPTPQc2 uses full range

You really need to distinguish between color space, primary, matrix, signal range. 
Ictcp or ycbcr is matrix. rec2020 or p3 is primary, a part of color space.

**Comment by ValZapod** [comment] 2022-01-27 01:22
> Ictcp

No, it is not using ICtCp, the IPTPQc2 matrix is different, for example it uses c = 2%, while ICtCp 4%. It also has rotation matrix multipled to allign skintones and other stuff.

**Comment by Natural-Harmonia-Gropius** [comment] 2022-01-27 01:38
> Why is it so differrent?

I think the difference comes from `hdr-compute-peak` or `tone-mapping-mode`.

> why is bt.2446a recommended when it looks really bad in most circumstances?

Because it's ITU's conversion method.

**Comment by ValZapod** [comment] 2022-01-27 02:00
> Because it's ITU's conversion method.

It is only supported by gpu-next though...

**Comment by ValZapod** [comment] 2022-01-27 05:47
> help them solve their problems

If only that was this simple! User may have AMD where nothing really works (for example 10 bit is actually 8 bit dithered there, true story), or like in this case user says he calibrated to DCI white point but actually did not (again, some money to LG, my LG C9 can be very simply calibrated to DCI whitepoint due to insane 33^3 3DLUT).

>If you are really full of knowledge,

That is @haasn.

**Comment by ValZapod** [comment] 2022-01-27 05:51
> About rec2020_p3_limited:
> https://professionalsupport.dolby.com/s/article/How-to-create-a-Rec2020-deliverable-from-a-P3-Dolby-Vision-master?language=en_US

 >not able to display the full Rec2020 gamut accurately,

This is false. SMPTE has such BT.2020 laser systems. Also QD-OLED from Samsung will be anle to 90% of it or something. May be a white point will be a little bluish (since with D65, warmer it is harder to rchive same gamit coverage due to jow blue the OLED/QD is, it is like 8000 K).

**Comment by Hrxn** [comment] 2022-01-28 10:44
You need to read the full quote.

> As current display technology used for reference monitors is not able to display the full Rec2020 gamut accurately

current = publication date of the article.

 So it's correct.

**Comment by ValZapod** [comment] 2022-01-28 10:47
> current = publication date of the article

SMPTE laser system was 2014.

**Comment by Hrxn** [comment] 2022-01-28 10:54
Well, I guess we can agree on that super-secret prototype systems hidden in some super-secret basement does not count as "available technology"

**Comment by ValZapod** [comment] 2022-01-28 12:10
> super-secret prototype systems hidden in some super-secret basement does not count as "available technology"

Also it was only P3. BT.2020 laser system were only made available in 2017.

**Comment by haasn** [comment] 2022-09-27 23:45
Closing since this seems to be a question about a highly subjective issue with no ultimate resolution.

**Closed by haasn** 2022-09-27 23:45 UTC
Labels: meta:question, vo:gpu-next

**Comment by damian101** [comment] 2023-02-21 18:29
This issue still exists, but is a duplicate of #9435 
Btw, I am highly certain that `vo=gpu` tone mapping is accurate, while `vo=gpu-next` tone mapping is very much inaccurate.
