### ISSUE TITLE
gpu-next best interpolation settings

### ISSUE THREAD

**Issue by lavilao** [mpv-player/mpv#9604] opened 2021-12-16 23:47 UTC
Hi guys small question:
now that mpv has a new renderer (vo=gpu-next) do anyone knows what are the best interpolation settings for it?
on vo=gpu after testing the best settings were
```
video-sync=display-resample
interpolation
blend-subtitles=yes
tscale-window=quadric
tscale-clamp=0.0
tscale=box
tscale-radius=1.025
```

on gpu-next you can't resize the filter ```[vo/gpu-next] Filter radius specified but filter 'box' is not resizable, ignoring``` and I also read on the manual about a new interpolation option ```interpolation-preserve``` those two things make me wonder if there is a new "best interpolation settings", so there is it or it is the same? will gpu-next sometime in the future get a  hardware accelerated motion interpolation feature like splash player (plead to mpv devs)? thanks in advice!

**Comment by haasn** [comment] 2021-12-17 01:19
Hrm, actually the issue is that this setup can't be recreated as-is because `quadratic` is not reiszable either.

I think I'll fix this by reimplementing the old `box` behavior (effectively making it different from `nearest`).

**Comment by lavilao** [comment] 2021-12-17 01:22
thanks

**Comment by aufkrawall** [comment] 2021-12-17 13:50
I found

```
tscale=sphinx
tscale-blur=0.65
```

to work well. With all the motion blur that is already contained in real world videos, you might even go as low as 0.6. Though that already looks a bit juddery with synthetic judder test videos.

**Comment by lavilao** [comment] 2021-12-17 13:58
@aufkrawall wow thanks for the suggestion, it looks really good and are a lot less (relatively speaking) lines of config

**Comment by yeezylife** [comment] 2021-12-20 13:52
I remember that hassn mentioned something like this for gpu-next: 
`tscale=sphinx`
`tscale-blur=0.6991556596428412`
Been using this ever since. And "0.6991556596428412" is so exatct! Is this the magical number?

**Comment by lavilao** [comment] 2021-12-20 13:55
that is a exact number xD

**Comment by laichiaheng** [comment] 2022-09-27 04:43
Does it work on `vo=gpu`?

**Comment by aufkrawall** [comment] 2022-09-27 17:09
As it doesn't print any warning with `gpu`, I haven't noticed any issue and nothing is mentioned on the https://github.com/mpv-player/mpv/wiki/GPU-Next-vs-GPU page, I see no reason to assume why it shouldn't work.

**Comment by haasn** [comment] 2022-09-27 23:39
Closing since this is a meta-discussion with no final answer, and a bug tracker is (IMO) not the right place for those.

**Closed by haasn** 2022-09-27 23:39 UTC
Labels: meta:question, vo:gpu-next

**Comment by ProxyVT** [comment] 2025-02-11 07:06
@veganomy thanks for suggesting `spline16` as alternative, but I have a question: by term "zero blur" do you mean `tscale-blur=0`? Because when I compared it to `oversample` tscale, to me it seems more blurry.
