### ISSUE TITLE
Vaapi cause to show strange artifacts on video

### ISSUE THREAD

**Issue by qarmin** [mpv-player/mpv#14057] opened 2024-05-04 08:07 UTC
### Important Information

Provide following Information:
- mpv from official ubuntu package - 
```
mpv 0.37.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
libplacebo version: v6.338.2
FFmpeg version: 6.1.1-3ubuntu5
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```
```
System:
  Host: rafal-komputer Kernel: 6.8.0-31-generic arch: x86_64 bits: 64
  Desktop: GNOME v: 46.0 Distro: Ubuntu 24.04 LTS (Noble Numbat)
CPU:
  Info: quad core model: Intel Core i7-4770 bits: 64 type: MT MCP cache:
    L2: 1024 KiB
  Speed (MHz): avg: 798 min/max: 800/3900 cores: 1: 798 2: 798 3: 798 4: 800
    5: 798 6: 798 7: 800 8: 798
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    driver: amdgpu v: kernel
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.6 driver: X:
    loaded: amdgpu unloaded: fbdev,modesetting,radeon,vesa dri: radeonsi
    gpu: amdgpu resolution: 1: 1920x1080~60Hz 2: 1920x1080~60Hz
  API: EGL v: 1.5 drivers: radeonsi,swrast platforms: x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.0.5-1ubuntu1
    renderer: AMD Radeon RX 570 Series (radeonsi polaris10 LLVM 17.0.6 DRM 3.57
    6.8.0-31-generic)
  API: Vulkan v: 1.3.275 drivers: N/A surfaces: xcb,xlib
```

Some videos, with vaapi(which is probably enabled by default) have strange stripes inside, which are not available with renderer, that is enabled with `--no-config` option

https://github.com/mpv-player/mpv/assets/41945903/b6880cad-86c8-482c-9a7a-62cf453e92ac

Problematic video(directly from phone)

[VID_20240504_095442.mp4.zip](https://github.com/mpv-player/mpv/files/15208446/VID_20240504_095442.mp4.zip)

Vlc works fine with this info
```
VLC media player 3.0.20 Vetinari (revision 3.0.20-0-g6f0d0ab126b)
[00005bcd13dbd5e0] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
Inconsistent value (1) for DRI_PRIME. Should be < 1 (GPU devices count). Using: 0
Inconsistent value (1) for DRI_PRIME. Should be < 1 (GPU devices count). Using: 0
libva info: VA-API version 1.20.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_20
Inconsistent value (1) for DRI_PRIME. Should be < 1 (GPU devices count). Using: 0
libva info: va_openDriver() returns 0
Inconsistent value (1) for DRI_PRIME. Should be < 1 (GPU devices count). Using: 0
Inconsistent value (1) for DRI_PRIME. Should be < 1 (GPU devices count). Using: 0
[00007f1550c0f3f0] avcodec decoder: Using G3DVL VDPAU Driver Shared Library version 1.0 for hardware decoding
[h264 @ 0x7f1550ce99c0] Failed setup for format vdpau: hwaccel initialisation returned error.
[00007f1550c0f3f0] avcodec decoder error: existing hardware acceleration cannot be reused
Inconsistent value (1) for DRI_PRIME. Should be < 1 (GPU devices count). Using: 0
libva info: VA-API version 1.20.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_20
Inconsistent value (1) for DRI_PRIME. Should be < 1 (GPU devices count). Using: 0
libva info: va_openDriver() returns 0
Inconsistent value (1) for DRI_PRIME. Should be < 1 (GPU devices count). Using: 0
```

**Comment by CounterPillow** [comment] 2024-05-04 10:57
> which is probably enabled by default

Only because Ubuntu overrides upstream mpv's decision and sets `hwdec=vaapi` in `/etc/mpv/mpv.conf`.

Report this to them, it's their fault.

**Comment by kasper93** [comment] 2024-05-04 11:03
Duplicate of https://github.com/mpv-player/mpv/issues/8223
Fixed by https://github.com/mpv-player/mpv/commit/27fb4c474f5ca850470cd07dfc789ba8bf94b35c

**Closed by kasper93** 2024-05-04 11:03 UTC
Labels: priority:ignored-issue-template, os:linux
