### ISSUE TITLE
Unknown Key Error

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#9750] opened 2022-01-23 15:35 UTC
### Important Information

Provide following Information:
- mpv version: 0.34.1
- Linux Distribution and Version: OS: Garuda Linux, Kernel: 5.16.2-zen1-1-zen, DE: Plasma 5.23.5, WM: KWin
- Source of the mpv binary: [Arch Community Repository](https://archlinux.org/packages/community/x86_64/mpv/)
- If known which version of mpv introduced the problem: 0.34
- Window Manager and version: kwin 5.23.5-1
- GPU driver and version
> Graphics:
  Device-1: Intel HD Graphics 5500 driver: i915 v: kernel
  Device-2: NVIDIA GM108M [GeForce 840M] driver: nvidia v: 495.46
  Device-3: Chicony HP Truevision HD camera type: USB driver: uvcvideo
  Display: x11 server: X.Org 1.21.1.3 driver: loaded: modesetting,nvidia
    resolution: 1920x1080~60Hz
  OpenGL: renderer: Mesa Intel HD Graphics 5500 (BDW GT2)
    v: 4.6 Mesa 21.3.4

- Possible screenshot or video of visual glitches: [https://imgur.com/a/AYzo5NR](https://imgur.com/a/AYzo5NR)

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior

Error free playback

### Actual behavior

Unknown key errors

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/7920762/log.txt)

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

### Sample files

the error is not caused by the content being played

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by LaserEyess** [comment] 2022-01-23 22:47
Please try with `--no-config`, or post your `input.conf`. That particular error only occurs when parsing `input.conf`

**Comment by lynoxy** [comment] 2022-01-23 23:05
First I renamed  mpv folder  as .mpv then I did the above steps. I don't know why log show there is input.conf file.
log file with --no-config [output.txt](https://github.com/mpv-player/mpv/files/7921638/output.txt)

**Comment by LaserEyess** [comment] 2022-01-23 23:11
You don't need to rename your config folder, `$HOME/.config/mpv` is correct, and that's what was in your logs. I have a hunch as to what is causing this though, can you try 1mpv-git` from the AUR? If that works it may be a packaging issue with xkbcommon.

**Comment by lynoxy** [comment] 2022-01-23 23:26
okay new one with mpv-git and --no-config
[output.txt](https://github.com/mpv-player/mpv/files/7921670/output.txt)
g

**Comment by LaserEyess** [comment] 2022-01-23 23:30
Not sure then, I can't reproduce this error at all.

**Comment by lynoxy** [comment] 2022-01-23 23:42
I recently encountered some errors on linux caused by locale (tr_TR). Does locale have any effect on mpv's input?

**Comment by t-8ch** [comment] 2022-09-23 10:02
During the normalization of keynames the uppercase "RIGHT" may be normalized to a lowercase i-without-dot under a TR locale.

Maybe try it under a different locale.

The key lookup logic using `strncasecmp()` under the hood which is actually unspecified if LC_CTYPE is not the posix locale.

**Comment by Dudemanguy** [comment] 2023-01-09 04:45
User is now a ghost, so I will close this. If someone else happens to have this problem, please open a new issue.

**Closed by Dudemanguy** 2023-01-09 04:45 UTC
Labels: os:linux
