### ISSUE TITLE
how to see spherical videos (360). Found qmplay2. Can we implement that

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#3541] opened 2016-09-18 13:24 UTC
I am using the 

```
mpv git-b1893d2 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on Sun Nov  8 16:37:08 UTC 2015
ffmpeg library versions:
   libavutil       54.31.100
   libavcodec      56.60.100
   libavformat     56.40.101
   libswscale      3.1.101
   libavfilter     5.40.101
   libswresample   1.2.101
ffmpeg version: 2.8.7
pv git-b1893d2 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on Sun Nov  8 16:37:08 UTC 2015
ffmpeg library versions:
   libavutil       54.31.100
   libavcodec      56.60.100
   libavformat     56.40.101
   libswscale      3.1.101
   libavfilter     5.40.101
   libswresample   1.2.101
ffmpeg version: 2.8.7

```

How to view 360 spherical videos.

Recently i installed QMplay2

I found the following features interesting for 360 playing
playback > video-filters > Spehrical View (Ctrl + 3)

**Comment by haasn** [comment] 2016-09-18 22:10
Duplicate of #2280.

**Closed** 2016-09-18 22:51 UTC
Labels: feature request
