### ISSUE TITLE
geometry - wrong starting position at 1920x3000 (vertical)

### ISSUE THREAD

**Issue by xvim64** [mpv-player/mpv#15053] opened 2024-10-11 17:03 UTC
### mpv Information

```bash
mpv-x86_64-v3-20241011-git-3b95c00.7z
```

### Other Information

```text
- Windows version: windows 11 24h2
- Source of mpv: mpv-x86_64-v3-20241011-git-3b95c00.7z
- Introduced in version: mpv-x86_64-v3-20241006-git-9791c6d.7z
```

### Reproduction Steps

In 4k screen

// mpv-x86_64-v3-20241005-git-493cab7.7z

mpv --no-config --geometry=1920x2000 TEST.mp4
![1005--1920x2000](https://github.com/user-attachments/assets/95acbcc4-350b-42ee-93d7-0601efde3533)

mpv --no-config --geometry=1920x2500 TEST.mp4
![1005--1920x2500](https://github.com/user-attachments/assets/dc4d3a35-4702-4016-959e-7ab7f7638f5c)

mpv --no-config --geometry=1920x3000 TEST.mp4
![1005--1920x3000](https://github.com/user-attachments/assets/ff085303-0ded-494d-9877-3187e183b714)

// mpv-x86_64-v3-20241011-git-3b95c00.7z

mpv --no-config --geometry=1920x2000 TEST.mp4
![1011--1920x2000](https://github.com/user-attachments/assets/d00a0ac0-60ab-4ed8-8a07-e64b2fdf8182)

mpv --no-config --geometry=1920x2500 TEST.mp4
![1011--1920x2500](https://github.com/user-attachments/assets/ac1c6b4b-5fb5-43ae-ab7f-2dd44f44a08d)

mpv --no-config --geometry=1920x3000 TEST.mp4
![1011--1920x3000](https://github.com/user-attachments/assets/a78fa231-13c2-4816-8721-7e89e5b451f3)

### Expected Behavior

Even if the mpv's height is greater than the screen height, the mpv's window should not exceed the screen.

### Actual Behavior

The mpv jumps up when the mpv's height is greater than the screen height.

### Log File

None

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by Dudemanguy** [comment] 2024-10-11 17:32
I think this is just a consequence of windows taking into account the taskbar when doing the centering.

**Comment by kasper93** [comment] 2024-10-11 17:36
Duplicate of #15049

**Closed by kasper93** 2024-10-11 17:36 UTC
Labels: os:win
