### ISSUE TITLE
0.28 build by lachs0r: schannel breaks YouTube live

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#5286] opened 2017-12-25 22:29 UTC
shinchiro already noticed it and changed to libressl, which fixes the issue:
https://github.com/mpv-player/mpv/issues/5121

It's not related to the latest commits by wm4 for buffer changes, I compiled latest git status and it still works with libressl.

**Comment by lachs0r** [comment] 2017-12-25 22:40
Can’t reproduce this on a fresh Windows 10 install. Something on your system must be messing with Windows’ TLS implementation.

**Comment by aufkrawall** [comment] 2017-12-25 22:57
I can instantly reproduce it with this URL:
https://youtu.be/PWsbAQVuHEA

I installed my Windows 10 (AU LTSB) yesterday and there are no additional network filters/drivers active.
Buffering always instantly stops with schannel, while it always works with libressl (tested each ten times).

To be extra sure, I'm going to compile it also with schannel, changing only that ffmpeg flag.

**Comment by lachs0r** [comment] 2017-12-25 22:58
Yeah I’ve been able to reproduce it. Didn’t trigger it the first time for whatever reason.

**Comment by aufkrawall** [comment] 2017-12-26 14:12
Is it to be expected that changing ffmpeg licence from nonfree to GPL leads to the same issue with libtls?
gnutls however works.

**Comment by lachs0r** [comment] 2017-12-26 14:15
How about fixing the issue with SChannel instead?

**Comment by shinchiro** [comment] 2017-12-26 15:12
My build on 14 oct did not have this issue, it starts after that. I would suspect FFmpeg/FFmpeg@858db4b which was merged on 20 oct, causing this issue

**Comment by chainikdn** [comment] 2017-12-27 16:42
my 2 cents: mpv built with ffmpeg-master hangs on playing simple HTTP (not HTTPS) HLS stream:

> [ffmpeg] Opening http://localhost:9900/stream.m3u8
> [ffmpeg] Mime-type: 'application/x-mpegurl; charset=utf-8'
> [cache] Cache size set to 20000 KiB (10000 KiB backbuffer)
> [cache] Cache is not responding - slow/stuck network connection?

The very same build using ffmpeg GIT_TAG 3.4 works fine.

**Comment by chainikdn** [comment] 2017-12-27 22:44
Found it. Indeed it's https://github.com/FFmpeg/FFmpeg/commit/858db4b, specifically libavformat/avio.c:
```
} else if (ret == AVERROR_EOF)
            return (len > 0) ? len : AVERROR_EOF;
        else if (ret < 0)
            return ret;
```
Changing 3rd line to
`        else if (ret <= 0)`
fixes the issue.

Someone should probably post this upstream :/

**Comment by jeeb** [comment] 2018-08-25 16:26
1. The EOF related stuff was fixed quite some time ago in FFmpeg for TLS protocol.
2. If someone gets to this issue because schannel TLS protocol with HLS works badly, try disabling persistent connections in the HLS demuxer. It seems like how it is implemented in the HLS demuxer breaks schannel (`--demuxer-lavf-o-set=http_persistent=0`)

**Closed by jeeb** 2018-08-25 16:26 UTC
Labels: ffmpeg-bug
