### ISSUE TITLE
Аfter upgrading to 0.29, there are problems in video decoding when using hwdec=vaapi and vo=gpu

### ISSUE THREAD

**Issue by Lourens-Rich** [mpv-player/mpv#6314] opened 2018-11-13 17:43 UTC
### mpv version and platform
**Software:** mpv 0.29-1 and above on Arch Linux.
**Hardware:** Intel(R) Celeron(R) CPU N3450 @ 1.10GHz with Intel(R) HD Graphics 500 (Broxton 2x6)
### Reproduction steps
Load your CPU properly (for example, start compiling the latest version of chromium) and run mpv with --hwdec=vaapi and -vo=gpu
### Expected behavior
MPV should work as it did before version 0.29
### Actual behavior
This problem has been partially described on this issue page: https://github.com/mpv-player/mpv/issues/6301

"Audio/Video desynchronisation detected! Possible reasons include too slow hardware, temporary CPU spikes, broken drivers, and broken files. Audio position will not match to the video (see A-V status field)."
### Log files
https://0x0.st/slUG.txt - 0.29.1-3 output file
https://0x0.st/slUv.txt - 0.28.2-* output file (* - rebuilt on the machine because of a new version of ffmpeg broke the stock package due to changing the paths of its libraries)
### Sample file and mediainfo
https://0x0.st/sll2.mkv - sample file
https://0x0.st/sll_.txt - the mediainfo of the sample file

**Comment by haasn** [comment] 2018-11-13 18:02
Both of your logs claim they're using software decoding?

**Comment by Lourens-Rich** [comment] 2018-11-13 18:09
I don't know why. But if I load the CPU up to 90% and above, the video on the 0.29 version will slow down, but at 0.28 it will be all right

**Comment by Lourens-Rich** [comment] 2018-11-13 18:15
> Both of your logs claim they're using software decoding?

[   0.628][v][vd] Trying hardware decoding via h264-vaapi. - 0.29
[   0.363][v][vd] Trying hardware decoding via h264-vaapi. - 0.28.2

**Comment by Lourens-Rich** [comment] 2018-11-13 18:30
0.28.2
![2018-11-13-212952_scrot](https://user-images.githubusercontent.com/22860367/48434628-4a6e1980-e78b-11e8-9802-b38176701840.png)

**Comment by haasn** [comment] 2018-11-13 18:41
Does `--vd-lavc-dr=no` help with v0.29?

**Comment by haasn** [comment] 2018-11-13 18:42
Also, judging by the logs, `--hwdec=vaapi` doesn't actually matter for your issue. `--hwdec=no` should have the same result. Can you confirm that's the case?

**Comment by Lourens-Rich** [comment] 2018-11-13 18:44
> Does `--vd-lavc-dr=no` help with v0.29?

Yes! 
![2018-11-13-214338_scrot](https://user-images.githubusercontent.com/22860367/48435307-3aefd000-e78d-11e8-971f-62dc719da796.png)

**Comment by Lourens-Rich** [comment] 2018-11-13 18:52
--hwdec=no and -vd-lavc-dr=no

https://0x0.st/sl0I.txt - log file for "--hwdec=no -vo=vaapi FLCL\ -\ 02\ \[BDRip\ 1440x1080\ x264\ FLAC\]v2.mkv --vd-lavc-dr=no"

![2018-11-13-214913_scrot](https://user-images.githubusercontent.com/22860367/48435625-0597b200-e78e-11e8-9123-16c09e2ccb4d.png)

**Comment by Lourens-Rich** [comment] 2018-11-13 19:00
@haasn, i made mistakes in my tests.  I'll recheck everything.

**Comment by Lourens-Rich** [comment] 2018-11-13 19:03
> Does --vd-lavc-dr=no help with v0.29?
Yes!
![2018-11-13-220124_scrot](https://user-images.githubusercontent.com/22860367/48436504-daae5d80-e78f-11e8-985f-b3692af23429.png)

**Comment by Lourens-Rich** [comment] 2018-11-13 19:06
By the way "--hwdec=vaapi" and "-vo=vaapi"  worked all this time

**Comment by haasn** [comment] 2018-11-13 19:07
Interesting. Well the short answer is that setting `vd-lavc-dr=no` should fix your regression. But it's also worth pointing out that even in v0.28 you were not actually using hardware decoding, so if that was the intent then there may be a separate issue here involving vaapi and your hardware.

The more annoying question is whether or not this affects anything about our decision to make `vd-lavc-dr` the default. I stand by the claim that this is significantly better for most modern systems, and can help with playback especially of large files (e.g. 4K). And honestly I'd consider it a bug in mesa to even support mapped buffers if too slow to be useful.

Maybe there's something we can do to detect systems where mapped buffers are too slow, and disable it for these. Any ideas? Otherwise, I guess we can close this issue if your problem is solved.

**Comment by haasn** [comment] 2018-11-13 19:11
Oh, indeed - according to your log the file you were experiencing issues with were yuv420p10, which is not supported by your hardware decoder. So all in all, there is no bug here; since `--vd-lavc-dr=no` solves the issue of slow 10-bit software decoding.

**Comment by Lourens-Rich** [comment] 2018-11-13 19:12
"--hwdec=no" and "-vo=gpu" do not load CPU but the video plays with the same lags (as is the case with "-hwdec=vaapi" and "-vo=gpu"

**Comment by Lourens-Rich** [comment] 2018-11-13 19:20
> And `--vd-lavc-dr` solves this, correct?
and in this case helps

https://0x0.st/sl07.txt

![2018-11-13-212421_scrot](https://user-images.githubusercontent.com/22860367/48437396-4db8d380-e792-11e8-9980-cddd00d6f1ae.png)

**Comment by Lourens-Rich** [comment] 2018-11-13 19:33
Thank you very much for your information and attention. (sorry for my corrections and terrible English) I just wanted to show the result after the update. Unfortunately, I don't know yet how to approach the question of sending my request to mesa-dev or 01.org (still keep using XF86-video-intel and it's a very terrible driver)

**Comment by haasn** [comment] 2018-11-13 20:30
I wonder, does this patch fix the slow performance with `--vd-lavc-dr`?

```diff
diff --git a/src/mesa/drivers/dri/i915/intel_buffer_objects.c b/src/mesa/drivers/dri/i915/intel_buffer_objects.c
index e676096490..40cd9ca73b 100644
--- a/src/mesa/drivers/dri/i915/intel_buffer_objects.c
+++ b/src/mesa/drivers/dri/i915/intel_buffer_objects.c
@@ -140,7 +140,8 @@ intel_bufferobj_data(struct gl_context * ctx,
       /* Stick VBOs in system memory, as we're always doing swtnl with their
        * contents anyway.
        */
-      if (target == GL_ARRAY_BUFFER || target == GL_ELEMENT_ARRAY_BUFFER) {
+      if (target == GL_ARRAY_BUFFER || target == GL_ELEMENT_ARRAY_BUFFER ||
+          storageFlags & GL_CLIENT_STORAGE_BIT) {
 	 intel_obj->sys_buffer =
             _mesa_align_malloc(size, ctx->Const.MinMapBufferAlignment);
 	 if (intel_obj->sys_buffer != NULL) {
```

**Comment by Lourens-Rich** [comment] 2018-11-13 20:38
which version to apply this patch 0.29.1 or master?

**Comment by haasn** [comment] 2018-11-13 20:39
That's a patch against mesa git master (i915 driver). (But it probably also applies to mesa 18.x, haven't tested)

**Closed** 2018-11-14 14:17 UTC

**Comment by haasn** [comment] 2018-11-16 12:54
That's odd. I would have thought that with that patch, it would be forced to go via malloc the same way it does currently when you disable `vd-lavc-dr`.

Maybe there's something else going on here. Probably an intel driver dev could do a better job of investigating. Anyway, that's all the ideas I had.

**Comment by Lourens-Rich** [comment] 2018-11-16 12:59
I'm grateful to you anyway. I was just interested in your theory.

**Comment by Jj0YzL5nvJ** [comment] 2018-11-16 22:40
@Lourens-Rich, can you try?:
`MESA_EXTENSION_OVERRIDE=-GL_ARB_buffer_storage mpv --no-config --hwdec=vaapi *`

**Comment by haasn** [comment] 2018-11-16 23:31
@Jj0YzL5nvJ That will just disable DR, same as `--vd-lavc-dr=no`.

**Comment by Lourens-Rich** [comment] 2018-11-17 02:18
> @Jj0YzL5nvJ That will just disable DR, same as `--vd-lavc-dr=no`.

Confirm. Will be the same result

**Comment by haasn** [comment] 2018-11-17 02:30
Although that does mean that using this string globally might be a good idea on GPUs from your generation. Who knows what else depends on mapped buffers being fast? (Like VLC, which also tries using `GL_ARB_buffer_storage` for DR - although it might not enable that codepath on your system. Is VLC also slow?)

**Comment by Jj0YzL5nvJ** [comment] 2018-11-17 21:20
"[Mesa quirk](https://bugs.freedesktop.org/show_bug.cgi?id=102204#c7)"
