### ISSUE TITLE
OSX app bundle: crashes when opening a new video if already running

### ISSUE THREAD

**Issue by vitorgalvao** [mpv-player/mpv#1418] opened 2015-01-03 01:32 UTC
Tangent to #1377. I very regularly start a new video before the previous one stopped playing, and in previous versions, the new video would just start (losing the position of the first one, as mentioned in #1377). However, in the latest versions (I think it started a few versions back), if I try to start a new video while another one is already playing, mpv simply crashes (giving the “mpv quit unexpectedly” message).

This only happens via the OS X app bundle (either by double clicking or using `open` on a file). Calling `mpv` on a file from the terminal works fine.

Currently on `mpv` version `0.7.2`, installed via `homebrew` with no specified flags, from [the official repo](https://github.com/mpv-player/homebrew-mpv). OS X Yosemite `10.10.1`.

**Comment by ChrisK2** [comment] 2015-01-03 01:40
Can't reproduce on master, but on 0.7.2. So this was probably fixed already (should be in the next release as well)

Crash report for reference:
```
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
Assertion failed: (!size), function ta_memdup, file ../ta/ta_utils.c, line 78.
 

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff898fd282 __pthread_kill + 10
1   libsystem_c.dylib             	0x00007fff919a7b73 abort + 129
2   libsystem_c.dylib             	0x00007fff9196fc59 __assert_rtn + 321
3   io.mpv                        	0x0000000101175207 ta_xmemdup + 119
4   io.mpv                        	0x0000000101173144 __36-[EventsResponder handleFilesArray:]_block_invoke + 116
5   com.apple.CoreFoundation      	0x00007fff82682516 __53-[__NSArrayI enumerateObjectsWithOptions:usingBlock:]_block_invoke + 70
6   com.apple.CoreFoundation      	0x00007fff82682449 -[__NSArrayI enumerateObjectsWithOptions:usingBlock:] + 297
7   io.mpv                        	0x00000001011730a3 -[EventsResponder handleFilesArray:] + 163
8   io.mpv                        	0x0000000101171077 -[Application application:openFiles:] + 375
9   com.apple.AppKit              	0x00007fff88737c88 -[NSApplication(NSAppleEventHandling) _openDocumentURLs:withCompletionHandler:] + 875
10  com.apple.AppKit              	0x00007fff88738709 __69-[NSApplication(NSAppleEventHandling) _handleAEOpenDocumentsForURLs:]_block_invoke + 917
11  com.apple.AppKit              	0x00007fff883f4e1b -[NSApplication _reopenWindowsAsNecessaryIncludingRestorableState:registeringAsReady:completionHandler:] + 128
12  com.apple.AppKit              	0x00007fff887382e5 -[NSApplication(NSAppleEventHandling) _handleAEOpenDocumentsForURLs:] + 306
13  com.apple.AppKit              	0x00007fff883f48b6 -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 757
14  com.apple.Foundation          	0x00007fff89eb5458 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 290
15  com.apple.Foundation          	0x00007fff89eb52c9 _NSAppleEventManagerGenericHandler + 102
16  com.apple.AE                  	0x00007fff8bd3999c aeDispatchAppleEvent(AEDesc const*, AEDesc*, unsigned int, unsigned char*) + 531
17  com.apple.AE                  	0x00007fff8bd39719 dispatchEventAndSendReply(AEDesc const*, AEDesc*) + 31
18  com.apple.AE                  	0x00007fff8bd39623 aeProcessAppleEvent + 295
19  com.apple.HIToolbox           	0x00007fff84a5837e AEProcessAppleEvent + 56
20  com.apple.AppKit              	0x00007fff883f0d76 _DPSNextEvent + 2665
21  com.apple.AppKit              	0x00007fff883efe80 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 194
22  com.apple.AppKit              	0x00007fff883e3e23 -[NSApplication run] + 594
23  io.mpv                        	0x00000001011713df cocoa_main + 271
24  libdyld.dylib                 	0x00007fff8e2a65c9 start + 1
```

**Comment by pigoz** [comment] 2015-01-03 09:10
Yep this is fixed in master.

**Closed by pigoz** 2015-01-03 09:10 UTC

**Comment by vitorgalvao** [comment] 2015-01-03 16:24
Great news. Thank you both.
