### ISSUE TITLE
Colors are corrupted after rotating videos in 0.37

### ISSUE THREAD

**Issue by seadra** [mpv-player/mpv#13245] opened 2024-01-08 02:20 UTC
### Important Information

Provide following Information:
- mpv version 0.37.0
- Linux Distribution and Version Arch Linux
- Source of the mpv binary Arch Linux repository
- If known which version of mpv introduced the problem 0.37.0
- Window Manager and version kwin 5.27.10
- GPU model, driver and version happens on both nvidia (nvidia 545.29.06) and Intel iGPU (mesa 23.3.2)
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Rotate any movie 90 degrees (using custom assigned keyboard shortcuts like "add video-rotate 90")

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior

Rotate without any corruption of the image

### Actual behavior

Colors are corrupted, plus a diagonal reddish stripe appears

### Log file

Make a log file made with -v -v or --log-file=output.txt, attach it to
the issue, and replace this text with a link to it.

Without the log file, this issue will be closed for ignoring the issue template.

In the case of a crash, please provide a backtrace.

### Sample files

Happens in any video file I tested

Sample files needed to reproduce this issue can be attached to the issue
(preferred), or be uploaded to https://0x0.st/ or similar sites.
(Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

Before rotation

![Bleach Opening 10 (720p_30fps_H264-192kbit_AAC) (00:00:29) 0002](https://github.com/mpv-player/mpv/assets/9574367/1b169885-2e3c-400e-8c96-a5aff01bbf21)

After rotation

![Bleach Opening 10 (720p_30fps_H264-192kbit_AAC) (00:00:29) 0003](https://github.com/mpv-player/mpv/assets/9574367/51196d64-7451-4fc4-b42a-f36fc48a30a8)

**Comment by hooke007** [comment] 2024-01-08 02:29
https://github.com/mpv-player/mpv/issues/8223

**Comment by seadra** [comment] 2024-01-08 03:20
> #8223

Why did you link to that issue? My issue didn't happen in 0.36 or prior versions, and happens without nv12, on non-radeon GPUs.

**Comment by hooke007** [comment] 2024-01-08 03:25
0.37 built conf was chaned
> builtin.conf: modernize internal profiles for higher quality rendering by default,
rename 'gpu-hq' profile to 'high-quality', add 'fast' profile

**Comment by seadra** [comment] 2024-01-08 03:32
I confirm adding `--cscale=bilinear` works as a workaround

**Comment by Dudemanguy** [comment] 2024-01-21 00:51
Duplicate of #8223.

**Closed by Dudemanguy** 2024-01-21 00:51 UTC
Labels: os:linux
