### ISSUE TITLE
Please considering remove `smb` from `X-KDE-Protocols` in desktop entry.

### ISSUE THREAD

**Issue by merrkry** [mpv-player/mpv#14124] opened 2024-05-12 11:30 UTC
Some distros don't include  --enable-libsmbclient in ffmpeg build. File managers like Dolphin will try use smb:// as target as mpv's current desktop entry includes smb in X-KDE-Protocols, and mpv crashes because local ffmpeg lacks smb support. As --enable-libsmbclient isn't listed as dependency here, I suggest smb should be removed from X-KDE-Protocols, to make the entry file universal on various distros.

References (may be more distros to be added here):

- [OpenSUSE Reddit](https://www.reddit.com/r/openSUSE/comments/szcfpk/libsmbclient_removed_from_ffmpeg/)
- [Archlinux Gitlab](https://gitlab.archlinux.org/archlinux/packaging/packages/mpv/-/issues/10)
- [Archlinux bug repot](https://bugs.archlinux.org/task/69798)

### Important Information

- mpv version: 0.38.0
- Linux Distribution and Version: Archlinux
- Source of the mpv binary: official Archlinux repo
- ~~If known which version of mpv introduced the problem~~
- Window Manager and version: kwin 6.0.4
- ~~GPU model, driver and version~~
- ~~Possible screenshot or video of visual glitches~~

### Reproduction steps

- Connect a samba server with Dolphin
- click to open a video with mpv
- mpv crashes

### Expected behavior

Target file should be provided with `kio-fuse` (under `/run/user/1000/kio-fuse-*/`) instead of using `smb://` directly.

### Actual behavior

Dolphin directly passes `smb://` link to mpv, and mpv crashes because local ffmpeg build doesn't support it.

### Log file

```
$ mpv smb://<blabla>
[ffmpeg] Protocol not found. Make sure FFmpeg is compiled with networking support.
Failed to open smb://<blabla>.
Exiting... (Errors when loading file)
```

### ~~Sample files~~

**Comment by sfan5** [comment] 2024-05-12 12:04
duplicate of #8731

**Comment by CounterPillow** [comment] 2024-05-13 17:06
>  and mpv crashes because local ffmpeg build doesn't support it.

As a note of correction, this is not a crash. mpv exits on its own volition.

**Closed** 2024-05-22 20:10 UTC
Labels: os:linux
