### ISSUE TITLE
No window decorations with --hwdec=vaapi --opengl-backend=wayland on Wayland

### ISSUE THREAD

**Issue by aalba6675** [mpv-player/mpv#4895] opened 2017-09-19 04:41 UTC
### mpv version and platform
0.26.0
Linux/x86_64
Intel Haswell i7-4770

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
mpv --hwdec=vaapi --opengl-backend=wayland my4kvideo.mp4

### Expected behavior
Video with border (resizable)

### Actual behavior
Video, no border

### Log file
https://file.io/ZMzzhM
### Sample files
http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_2160p_60fps_normal.mp4

Trying the Ubuntu 4k videos with low CPU HOWTO from here https://wiki.ubuntu.com/IntelQuickSyncVideo
Wayland is known to be problematic. Just want to verify that this behaviour is to be expected.

1. mpv --hwdec=vaapi --opengl-backend=wayland   --log-file=output.txt bbb_sunflower_2160p_60fps_normal.mp4
1. video plays correctly with < 10% CPU for 4k 60fps; however the video window has no window decorations
1. For comparison: vlc plays with low CPU and window decorations but penalizes gnome-shell to 50%
1. Gstreamer: gst-play-1.0 --videosink=glimagesink my4kvideo.mp4; has window decorations but takes a huge CPU hit (70% vs pure software render 200%+ vs mpv 5%)
1. mpv works flawlessly under Xorg with low CPU and window decorations

It seems that players which manage to add window decorations under Wayland suffer somehow. 

mpv works flawlessly except for window decorations under Wayland

**Comment by atomnuker** [comment] 2017-09-19 04:52
Duplicate of #3350, can't be fixed until either a protocol to make server-side decorations is written and standardized or we draw our own decorations. In the latter case we'd get bugs like "mpv has different window decorations compared to everything".
Window decorations are useless anyway.

**Closed by atomnuker** 2017-09-19 04:52 UTC

**Comment by mc4man** [comment] 2017-10-05 04:00
Well grab the latest git (with new wayland common) & you'll have 3 choices now
1. vaapi hwdec with no window deco
2. no vaapi hwdec with window deco
3. no vaapi hwdec with no window deco

So you can only have 1 "worthless" thing at a time though you may need to figure out what option give what.

**Comment by wm4** [comment] 2017-10-05 07:37
Run KDE instead of gnome.

**Comment by mc4man** [comment] 2017-10-06 15:52
It seems you can get deco with vaapi hwdec on gnome wayland if desired. One combo I didn't try with all these new options that would do that is
gpu-context=auto hwdec=vaapi

**Comment by CounterPillow** [comment] 2017-10-06 16:17
@mc4man then the other choice would be to convince the GNOME people that server-side decorations (or client-side-drawn server-supplied decorations) are a good idea.
