### ISSUE TITLE
No audio playback

### ISSUE THREAD

**Issue by naghus** [mpv-player/mpv#4215] opened 2017-03-10 15:46 UTC
### mpv version and platform
mpv 0.14.0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       54.31.100
   libavcodec      56.60.100
   libavformat     56.40.101
   libswscale      3.1.101
   libavfilter     5.40.101
   libswresample   1.2.101
ffmpeg version: 2.8.11-0ubuntu0.16.04.1

Ubuntu 16.04

### Reproduction steps
Try opening any video or audio file in any format.
(tested with .avi, .mkv, mp4 and .mp3)

### Expected behavior
I expect to hear something.

### Actual behavior
Neither videos files nor audio files reproduce any audio.
Every other source of audio (e.g. firefox) works.

### Log file

http://pastebin.com/qHbf7Bx9

**Comment by CounterPillow** [comment] 2017-03-10 15:49
>mpv 0.14.0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects

Outdated versions are not supported. If you want to stick with your ancient mpv version, report this as a bug to Ubuntu, not mpv.

**Comment by wm4** [comment] 2017-03-10 15:54
Indeed. Also could be a duplicate of #1173.

**Closed by wm4** 2017-03-10 15:54 UTC
Labels: invalid
