### ISSUE TITLE
mpv started minimized, but it still took focus.

### ISSUE THREAD

**Issue by SexySteak** [mpv-player/mpv#11530] opened 2023-03-30 23:24 UTC
### Important Information

Provide following Information:
- mpv version `0.35.0-335-g664f1977`
- Windows Version `Windows10 22H2`
- Source of the mpv binary `shinchiro`
- If known which version of mpv introduced the problem `?`
- Possible screenshot or video of visual glitches `It is hard to be explained by images`

### Reproduction steps

I started mpv through the command line and set "window-minimized" in the "mpv.conf" beforehand. mpv correctly started minimized, but it still took focus. You can see your cmd window (or your vscode windows if you use the cli of vscode) lose the focus clearly. After the mpv playback completed and automatically closed, the cmd window regain the focus.

### Expected behavior

I use AI-TTS to run mpv to playback the tts file through command line (More exactly, use child_process by node.js, to run mpv through command line). Like just starting in the background, I do not want it catch the focuses, because that will interrupt other work.

### Actual behavior

mpv correctly started minimized, but it still took focus.

### Log file

no log I think. It is not a fatal error or any other error like that

### Sample files

I do not think it needs a sample file...

**Comment by Dudemanguy** [comment] 2023-03-30 23:31
Duplicate of #9641.

**Closed by Dudemanguy** 2023-03-30 23:31 UTC
Labels: os:win
