### ISSUE TITLE
MPV display output performance significantly worse than Firefox on Youtube for same video

### ISSUE THREAD

**Issue by mlindner** [mpv-player/mpv#12638] opened 2023-10-15 02:40 UTC
### Important Information

Provide following Information:
- mpv version = v0.36.0-549-g78d43740f5
- macOS Version = 12.6.1
- Source of the mpv binary or bundle = git
- Computer = MacBook Air (M1, 2020)

### Reproduction steps

Play 4K 60fps video from source, either by downloading it with youtube-dl or playing directly from mpv with youtube-dl installed: https://www.youtube.com/watch?v=npIDMxrzm_o

### Expected behavior

Framedrop is zero as seen when playing the video on Firefox

### Actual behavior

Extremely high framedrop in video output of mpv unless playback speed is lowered to around 0.5 playback speed.

Additionally, I made sure that the rare bug where the display output can get reset into a lower refresh rate has not occurred by rebooting before doing the testing. This was also confirmed by playing a 1080p 60fps test file.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/12908462/output.txt)

**Comment by mlindner** [comment] 2023-10-15 02:45
I also attempted with --vo=gpu and --hwdec=auto and similar results were observed.

**Comment by llyyr** [comment] 2023-10-15 02:54
`[   0.003][v][cplayer] Setting option 'profile' = 'gpu-hq' (flags = 4)`

Of course it's significantly worse, you're not comparing with the exact same options. In particular, debanding is significantly expensive compared to anything Firefox might do to the video.

For a fairer comparison, you need to do `--profile=fast and --linear-downscaling=no`, and even then mpv is probably doing more things to render the video correctly in comparison to whatever web browser you're using.

**Comment by mlindner** [comment] 2023-10-15 03:31
Ok yes removing gpu-hq helps significantly but that doesn't explain why a couple simple video filters cause such horrible performance in just simple video output. This shouldn't be this slow. This is a very fast processor and very fast gpu.

**Comment by llyyr** [comment] 2023-10-15 03:59
That I have no clue about as I've never once owned a Mac in my life. I suppose you could build mpv from master and try the recently merged vulkan backend for Mac.

**Comment by mlindner** [comment] 2023-10-15 04:01
There are indeed unfortunate few mac users among the developers of mpv, which is unfortunate given its world-best status in terms of performance per watt. I'm already using mpv from master.

**Comment by llyyr** [comment] 2023-10-15 04:09
You could try enabling each `gpu-hq` (now called `high-quality`) option individually and see which one causes the performance hits. My bet would be on `deband=yes`.

**Comment by mlindner** [comment] 2023-10-15 05:02
I did some more testing and I'm still seeing substantial framedropping even with --no-config when using the Youtube URL directly. So lets get past the conversation about profiles.

**Comment by mlindner** [comment] 2023-10-15 05:11
Looking at system usage graphs, it appears my gpu usage is being pegged to 100% usage simply displaying this video, with substantial amounts of cpu usage still available (two cores almost idle). So there's something terribly inefficient going on with the gpu code for just displaying video. Again this is with --no-config.

**Comment by Isaacx123** [comment] 2023-10-15 05:13
>So lets get past the conversation about profiles.

`--no-config` uses the default profile that utilizes lanczos for upsampling the chroma and RGB planes and hermite for downsampling plus correct-downscaling which can be somewhat heavy on a laptop.

An oranges to oranges comparison against Firefox would be:
`--no-config --profile=fast --hwdec=auto`

**Comment by mlindner** [comment] 2023-10-15 05:20
> > So lets get past the conversation about profiles.
> 
> `--no-config` uses the default profile that utilizes lanczos for upsampling the chroma and RGB planes and hermite for downsampling plus correct-downscaling which can be somewhat heavy on a laptop.
> 
> An oranges to oranges comparison against Firefox would be: `--no-config --profile=fast --hwdec=auto`

I tried this and it drops GPU usage by half and cpu usage almost disappears (in fact so low that it dumps the load off to the efficiency cores rather than using the performance cores). Also again, this is a high power processor so shouldn't be thought of as just a "laptop". So something is very inefficient here.

**Comment by mlindner** [comment] 2023-10-15 05:24
I tried with just --no-config and --profile=fast but without --hwdec=auto and this actually *increased* gpu usage and caused frames to start dropping again. For some reason hwdec cuases lower gpu usage than not using it.

**Comment by mlindner** [comment] 2023-10-15 05:36
The culprit is probably libmpv which was a bad idea in the first place to create. I've ranted about libmpv many times however so there's no need to repeat it here again. OpenGL is long deprecated on the Mac and shouldn't still be being used.

**Comment by Jules-A** [comment] 2023-10-15 21:06
> OpenGL is long deprecated on the Mac and shouldn't still be being used.

Umm... Vulkan (MoltenVK) backend just got merged https://github.com/mpv-player/mpv/pull/7482 I guess you can try that?

**Comment by mlindner** [comment] 2023-10-15 21:15
> > OpenGL is long deprecated on the Mac and shouldn't still be being used.
> 
> Umm... Vulkan (MoltenVK) backend just got merged #7482 I guess you can try that?

Thanks for that. I'll wait a few days/weeks for any early bugs to get found and fixed before jumping on to it. It'd be better if they'd just used Metal natively, especially for something that's being newly implemented, rather than running everything through a compatibility layer (MoltenVK). It's always going to be worse performance than using Metal directly.

**Comment by low-batt** [comment] 2023-10-16 04:45
On this:
> For some reason hwdec causes lower gpu usage than not using it.

Video hardware decoding on Apple Silicon uses a dedicated [Media Engine](https://apple.fandom.com/wiki/Media_Engine).

I'm unaware of a way to see how active that part of the hardware is. I remember reading a post from someone who was exploring it by monitoring chip power usage. Can't find that post at the moment.

**Comment by CounterPillow** [comment] 2023-10-16 16:07
@mlindner you're an entitled twat complaining about shit without doing the work yourself. You're demanding people implement things precisely the way you want, without any payment. You seem to not have realised that whether you use mpv or not is no difference to the developers, or at best, it'd be of benefit to them if you stopped using mpv judging by your behaviour on this issue tracker.

**Comment by Akemi** [comment] 2023-11-23 01:22
i am going to close this specific issue
1. i can't reproduce this with libmpv/cocoa-cb nor with macvk vulkan backend
2. opengl on arm macs is probably a bad idea anyway because of the metal conversion layer
3. we have an alternative now with macvk, which is most likely preferred by now, i want to see how this ends up
4. opengl is a lost cause on mac, i don't really want to dig any further into this
5. i don't like how this issue ended up

**Closed by Akemi** 2023-11-23 01:22 UTC
Labels: os:mac
