### ISSUE TITLE
fullscreen doesn't work

### ISSUE THREAD

**Issue by lsnch** [mpv-player/mpv#5585] opened 2018-03-02 07:47 UTC
### mpv version and platform

git master, OS X 10.11.6

### Reproduction steps

Go fullscreen.

### Expected behavior

Should go fullscreen.

### Actual behavior

Crashes.
Going fs with double click produces either `illegal hardware instruction` or `segmentation fault` as part of the last line in terminal. `--fs` does the same except one time where mpv went fs and played video but was unresponsive afterwards.

### Log file

https://bpaste.net/raw/3ce51054c1ce

**Comment by Akemi** [comment] 2018-03-02 20:17
should be fixed with #5586.

**Comment by Akemi** [comment] 2018-03-03 00:04
the PR might have fixed this issue but the underlying problem isn't. i tested on 10.12.6 with Xcode8/SDK10.12/swift3.1 combo (probably similar to your setup) and Xcode9/SDK10.13/swift4.0.3, and it crashes with the former but not the latter. so this seems to be either a swift3 or an SDK bug. if this is true this is something i can't properly fix on older platforms and i consequential have to drop support of them, at least for building.

might be loosely related to https://bugs.swift.org/browse/SR-2563

**Comment by anticitizen4** [comment] 2018-03-03 08:56
Tested it a bit, crashed twice, at launch and at about 1s of playing, can't reproduce. Otherwise works well.

**Comment by Argon-** [comment] 2018-03-10 18:19
I updated my ~4 weeks old mpv today and now I also get these crashes occasionally (10.11). I only mention this because I didn't have them before. I can'r reliably make it crash so it's hard to debug or even bisect.

**Comment by Akemi** [comment] 2018-03-10 20:16
just to add additional information that i didn't mention before. the main culprit for this is https://github.com/mpv-player/mpv/commit/38d614d8d668f1255f092f825ac4223f774f5991 (specifically [line 389](https://github.com/mpv-player/mpv/commit/38d614d8d668f1255f092f825ac4223f774f5991#diff-2854dc1202f3397c7dbda181ae3beb31R389)). the previous commit (https://github.com/mpv-player/mpv/commit/938ad6ebc037ebb32b41619a31b15f8ade712867) should still work. though to test this you would also need this [fix](https://github.com/mpv-player/mpv/commit/3263f47d3355502e3c7d3744c9d5160cd2776c0c) on 10.11 (SDK 10.12). feel free to test and let me know. at least that's what i found out when bisecting with SDK10.12/swift3.x on either 10.12 or 10.11. also i am not able to reproduce any issue like this with SDK10.13/swift4.x still.

this at least should be the cause of this issue when entering fullscreen, if this happens in any other situation it might be related but is caused by something different. backtraces are appreciated for that.

on master it might help to comment [this](https://github.com/mpv-player/mpv/blob/master/video/out/cocoa-cb/window.swift#L307) line. though this will cause some minor bug at least when mpv is paused, but nothing unrecoverable. a redraw (like showing the OSC) will fix it.

i still suspect an SDK or compiler bug and the only real fix would be to drop support for compiling with SDK10.12/swift3.x and earlier, leaving just macOS 10.12 and newer. also keep in mind that doesn't mean mpv won't run on 10.12 and earlier anymore, just that you have to compile on 10.12 for older versions. though i really would like to avoid this.

**Comment by Akemi** [comment] 2018-04-13 13:27
i was wondering did the change in 965ba23303d980c239e2b0191488766cfa7b0f75 change anything?

**Comment by Argon-** [comment] 2018-04-13 14:09
Unfortunately I'm on 10.13 now on all of my machines for 2 weeks now. 
However, I must admit I completely forgot about this bug as it never happened again to me while I was still on 10.11, after I went back to the deprecated cocoa backend (except the single occurrence I mentioned above). Don't know if this was due to the backend or other changes in the meantime.

**Comment by Akemi** [comment] 2019-08-25 15:32
swift 3 support has been removed with PR #6703 and swift 5 support with ABI compatibility has been introduced. this most likely fixed this issue.

**Closed by Akemi** 2019-08-25 15:32 UTC
Labels: not our bug, osx
