### ISSUE TITLE
Framedrop in macOS after leaving mpv in the background

### ISSUE THREAD

**Issue by AirPort** [mpv-player/mpv#3978] opened 2017-01-01 21:07 UTC
### mpv version and platform
macOS 10.12.2
git master

### Reproduction steps
Open a video file, pause then go fullscreen and change space or put the windowed player on the background; then come back and start playing the file again.

### Expected behavior
Playback resumes normally.

### Actual behavior
Playback mostly works, but every now and then, at not-fixed intervals, mpv drops a bunch of frames (in my case usually 6 or 7). Seeking doesn't get rid of the problem, I need to reopen the video file again to stop the misbehaviour.

The issue has a bit of random factor to it, it doesn't show up always in the same way after a precise, measurable amount of time, but leaving mpv aside in fullscreen in another space for a couple of minutes triggers it quite reliably on my machine (although it doesn't seem to be related to the recent cocoa-related changes, since I already observed istances of it happening back in Os X 10.11 several months, and mpv versions, ago).

Maybe related: I noticed that after coming back to the paused and backgrounded player, the vo-performance/render-peak value sometimes is unusually high, but it quickly comes back to normal after resuming playback.

### Log file
(Very) verbose log: http://sprunge.us/ZKKT

**Comment by Akemi** [comment] 2017-01-01 21:21
does #3915 fix this?

**Comment by AirPort** [comment] 2017-01-01 21:48
Woah, actually with that PR applied it seems that I'm not able to reproduce it anymore.
I'd wait a bit to consider the issue fixed given its fickle nature, but as a matter of fact following the same steps I used before to produce the logfile doesn't trigger it right now. 
I'm going to give it an in-depth test in the next few days and I'll report back (by the way, there is something in particular that's keeping that PR from being merged? It would make testing easier having it in mainline mpv).

**Comment by AirPort** [comment] 2017-01-01 22:08
Nope, came back again in the end...

**Comment by AirPort** [comment] 2017-01-26 20:17
I managed to catch it again one of the random time it's happening, and I saw something new this time.
At playback start, the reported display fps (I don't use any display video-sync) was the "usual" 59.990; then I had to pause and change space for a minute and reply to a mail: when I came back it started to drop 6-7 frames every now and then like described, but I noticed that the reported display fps dropped to a value of 59.946. Seeking and chaging space again reverted it back to 59.990 agan, but it kept the occasional framedrop until I restarted playback.
Then I made some tests, and I noticed that very often, if I change space with mpv in fullscreen, the display-fps property changes a (I registered .991, .989, .978, .989, .964), altough most of the time no framedrop occurs.
Could this two things be related or they are completely different issues?

**Comment by wm4** [comment] 2017-01-26 20:26
It's normal that the display fps fluctuates a little bit. Check vsync-jitter and that delayed frames property.

**Comment by AirPort** [comment] 2017-01-26 20:40
I'm on `video-sync=audio`, they're unavailable.

**Comment by Akemi** [comment] 2017-01-26 21:52
i wonder if this ever worked on 10.12 or if it's just related to that big fullscreen regression and doublebuffering.

**Comment by AirPort** [comment] 2017-01-26 22:06
I'm sure it happened in El Capitan, so it could as well be, but regarding 10.10, the last versione without the double buffering issue, I can't honestly say anything because I was on different, infamous, hardware, and leaving the player idle in background would have caused a kernel panic.

**Comment by wm4** [comment] 2017-01-27 07:34
> I'm on video-sync=audio, they're unavailable.

I'm fairly sure estimated display FPS isn't available in this case either.

**Comment by AirPort** [comment] 2017-01-27 09:57
Yep, the fluctuating property in my case is display-fps, not estimated-display-fps.

**Comment by wm4** [comment] 2017-01-27 10:15
Well, that's even worse. It means cocoa_common.m is signaling display-fps changes all the time, even though this was supposed to happen rarely.

**Comment by Akemi** [comment] 2017-01-27 12:48
yeah cocoa definitely updates the display refresh rate in some unneeded cases since [windowDidChangeScreen](https://github.com/mpv-player/mpv/blob/master/video/out/cocoa/window.m#L167) doesn't exclusively triggers on screen change, but it definitely doesn't report a new refresh rate all the time. also the reported slight fluctuation in the display refresh rate is because we use  [CVDisplayLinkGetActualOutputVideoRefreshPeriod](https://github.com/mpv-player/mpv/blob/master/video/out/cocoa_common.m#L440) which recalculates the refresh rate from the displaylink callback. we could switch back to CVDisplayLinkGetNominalOutputVideoRefreshPeriod exclusively, it always reports the same/constant refresh rate but it might be slightly off.

unneeded cases (things that trigger windowDidChangeScreen) that come to mind are switching spaces and changing the colour profile.

i just assumed that a slight change in reported display refresh rate wouldn't hurt, since it doesn't happen constantly and only on certain events? also this shouldn't cause the reported problem that frame drops occur several times after the display refresh rate was updated

**Comment by wm4** [comment] 2017-01-27 13:39
> also the reported slight fluctuation in the display refresh rate is because we use CVDisplayLinkGetActualOutputVideoRefreshPeriod which recalculates the refresh rate from the displaylink callback. we could switch back to CVDisplayLinkGetNominalOutputVideoRefreshPeriod exclusively, it always reports the same/constant refresh rate but it might be slightly off.

We definitely want a "nominal" rate here. vo.c already computes the observed refresh rate itself.

Also note that vo.c refretches the rate from the backend only if VO_EVENT_WIN_STATE is set. So if the user can see it fluctuating, it must mean it's updated all the time.

**Comment by wm4** [comment] 2017-01-27 13:40
> We definitely want a "nominal" rate here.

And I forgot to add: I think we used to have problems with CVDisplayLinkGetNominalOutputVideoRefreshPeriod not reporting a useful rate, though I'm not sure. CC @pigoz

**Comment by Akemi** [comment] 2017-01-27 13:46
did you mean the problem mentioned [here](https://github.com/mpv-player/mpv/blob/46b74a38f11e9ff2808fc151a329a260d4ac8d90/video/out/cocoa_common.m#L412) with CVDisplayLinkGet**Actual**OutputVideoRefreshPeriod? or was there actually another problem with CVDisplayLinkGet**Nominal**OutputVideoRefreshPeriod?

**Comment by pigoz** [comment] 2017-01-27 14:08
`CVDisplayLinkGetNominalOutputVideoRefreshPeriod` returns `0` on all internal Apple displays (i.e.: laptop screens, imac screens)

**Comment by Akemi** [comment] 2017-01-27 14:23
> `CVDisplayLinkGetNominalOutputVideoRefreshPeriod` returns `0` on all internal Apple displays (i.e.: laptop screens, imac screens)

are you sure since it doesn't on my MBP? in the comment in the code (i linked above) it also mentions `CVDisplayLinkGetActualOutputVideoRefreshPeriod ` does that and not **Nominal**? and i am pretty sure i fixed the **Actual** refresh rate retrieval [with](https://github.com/mpv-player/mpv/commit/fb7c5804bbb6046472406f3fa8426784cbda4408).

**Comment by pigoz** [comment] 2017-01-27 14:35
Sorry, yeah it's the other way around `CVDisplayLinkGetActualOutputVideoRefreshPeriod` is the one that returns 0 on most hardware.

**Comment by Akemi** [comment] 2017-01-27 14:45
okay. i was planning to look at the event handling to optimise things and get rid of redundant calls anyway. though i would say it won't fix the problem reported here.

**Comment by markkuossi** [comment] 2017-02-20 05:28
> Open a video file, pause then go fullscreen and change space or put the windowed player on the background; then come back and start playing the file again.

I have this problem too. This has forced me to go back to VLC for the time being, hopefully this gets sorted soon.

It is very annoying to have frames drop this way.

**Comment by Akemi** [comment] 2017-04-30 18:04
since i couldn't reproduce this yet i am wondering if PR #4391 fixes this issue for you. other issue you may encounter can be reported on the PR.

**Comment by AirPort** [comment] 2017-04-30 23:50
I'll test for a couple of days, due to the unpredictable nature of the issue, and report back. Thank you for your hard work.

**Comment by Akemi** [comment] 2017-05-01 01:24
thx that is much appreciated.

**Comment by AirPort** [comment] 2017-05-03 18:01
In two days I couldn't reproduce the issue even once with cocoa_animation. I'd dare say that the issue seems to be solved.

**Comment by Akemi** [comment] 2017-05-03 18:36
that would be nice, too bad you have some performance problems with it.

**Closed** 2018-02-12 12:49 UTC
Labels: osx
