### ISSUE TITLE
Window is movable after toggling to fullscreen

### ISSUE THREAD

**Issue by Keith94** [mpv-player/mpv#4758] opened 2017-08-13 17:23 UTC
### mpv version and platform

* mpv 2017-07-18
* Windows 8

### Reproduction steps

1. Open the mpv.exe window with default settings
2. Double-click inside the window to enter fullscreen
3. After double-clicking, keep left mouse button held down and move the mouse in any direction

### Expected behavior

Window should stay full screen in the same position

### Actual behavior

Fullscreen window can be moved around the desktop

* Here's the issue reproduced: https://a.pomf.cat/cluvbi.mp4 (occurs with any video file, too)

### Log file

https://pastebin.com/dVucqGN4

**Comment by wiiaboo** [comment] 2017-08-13 17:29
Duplicate of #1921.

**Closed by wiiaboo** 2017-08-13 17:29 UTC
