### ISSUE TITLE
OSD/OSC: Clicking next crashes the OSD

### ISSUE THREAD

**Issue by hdak1945git** [mpv-player/mpv#3704] opened 2016-10-21 16:03 UTC
### mpv version and platform

~~~
[cplayer] mpv 0.21.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Thu Oct 20 08:19:09 CEST 2016
~~~

Arch Linux:
~~~
Name            : mpv
Version         : 1:0.21.0-1
Description     : a free, open source, and cross-platform media player
Architecture    : x86_64
~~~

### Reproduction steps

With the OSD/OSC popped up, click the next button to skip to the wanted position within an MKV video with delineated chapters.

### Expected behavior

Seek to the required position and resume watching the video.

### Actual behavior

OSD crashes. The video, however, keeps playing; hotkeys continue to work as expected.

### Log file

~~~
[osc] stack traceback:
[osc]   @osc.lua:677: in function 'limited_list'
[osc]   @osc.lua:705: in function 'get_chapterlist'
[osc]   @osc.lua:1566: in function '?'
[osc]   @osc.lua:2010: in function 'process_event'
[osc]   @osc.lua:2162: in function 'cb'
[osc]   mp.defaults:107: in function 'fn'
[osc]   mp.defaults:60: in function 'handler'
[osc]   mp.defaults:339: in function 'handler'
[osc]   mp.defaults:448: in function 'call_event_handlers'
[osc]   mp.defaults:485: in function 'dispatch_events'
[osc]   mp.defaults:441: in function <mp.defaults:440>
[osc]   [C]: in ?
[osc]   [C]: in ?
[osc] Lua error: @osc.lua:677: attempt to index local 'item' (a nil value)
~~~

Other observations:

This issue only appears to happen with MKV files exceeding **12** chapters. Tested files with: 6 chapters, 15 chapters and 17 chapters; the above stack trace appears only with the latter two files, with both traces being exactly the same.

Hotkeys can be used to skip past the twelfth chapter, however, if you attempt to use the OSD to skip to any chapter thereafter the OSD will immediately crash (again, with same stack trace as above). If you attempt to go back an chapter instead, a similar trace is presented with the line `@osc.lua:1566: in function '?'` replaced with `@osc.lua:1551: in function '?'` and no other changes.

Downgrading to 0.20.0 no longer presents this issue.

**Comment by wiiaboo** [comment] 2016-10-21 16:10
Duplicate of #3691

**Closed by wiiaboo** 2016-10-21 16:10 UTC
