### ISSUE TITLE
Wrong display resolution

### ISSUE THREAD

**Issue by erasmux** [mpv-player/mpv#6304] opened 2018-11-09 10:18 UTC
### mpv version and platform

Windows 7 x64
[mpv-x86_64-20181103-git-880c59d](https://sourceforge.net/projects/mpv-player-windows/files/64bit/) (first example also verified with [mpv-x86_64-20181002](https://mpv.srsfckn.biz/))

### Reproduction steps
Run mpv on specific video files (i.e. sample files attached below) with default config and no additional steps.

### Expected behavior
The display resolution should match the resolution of the video stream. Screenshots taken should be of the exact resolution of the input video.

### Actual behavior
The display resolution is almost the same but a few pixels off either in the width or the height.

For the [test.mkv](https://0x0.st/slNV.mkv) the actual video size is 1920x1040 (as confirmed by ffmpeg/ffprobe, mediainfo and the pixel width/height in the mpv log). The display resolution in the [mpv log](https://0x0.st/slNp.txt) is 1928x1040 and so is the inside of the mpv player window and the screenshots mpv produces.

For the [test2.mkv](https://0x0.st/slNy.mkv) the actual video size is 1280x688. The display resolution in the [mpv log](https://0x0.st/slNO.txt) is 1273x688. The mpv player windows size and the screenshots size is 1280x691 (a third different resolution?!).

Is there some logical explanation for this? Is this a mpv bug?

### Log file

https://0x0.st/slNp.txt (for test.mkv)
https://0x0.st/slNO.txt (for test2.mkv)

### Sample files
[test.mkv](https://0x0.st/slNV.mkv)
[test2.mkv](https://0x0.st/slNy.mkv)

**Comment by haasn** [comment] 2018-11-09 10:29
Can reproduce. Will investigate.

**Comment by haasn** [comment] 2018-11-09 10:46
Sample file 1 has a tagged PAR of 241:240. Given this, mpv is doing the correct thing.

Similarly, sample file 2 has a tagged PAR of 1273:1280. The only thing that's weird here is that mpv logs 1273x688 as the display resolution, when I would have expected 1280x691 here as well. Fortunately, both the VO and the screenshot code seem to be doing the right thing here, so I'm closing this as not a bug.

**Closed by haasn** 2018-11-09 10:46 UTC

**Comment by haasn** [comment] 2018-11-09 10:48
I should perhaps point out that if these are not your files and you don't want to bother retagging them, you can work around this by using `--video-aspect=no` to ignore the aspect ratio tags.

**Comment by erasmux** [comment] 2018-11-09 12:16
@haasn 
Thanks for looking into this, I see what you mean about the PAR so mpv adjustment of the display resolution seems correct.

What about taking screenshots? At least for my usage, I want a screenshot of the video source frame and not of the mpv display.
Could it be related to this: https://github.com/mpv-player/mpv/issues/5619

Btw the `--video-aspect=no` is indeed helpful for my case, so thanks. This also works around the screenshot issue (if indeed it is an issue).

**Comment by haasn** [comment] 2018-11-09 13:04
Yes, it is indeed very much related to that issue. In particular, that issue demonstrates that this is the preferred behavior. Anamorphic video is a thing and screenshots of anamorphic sources being scaled is what the normal user expects.

If you have a specific reason for wanting the ability to take "raw" screenshots of the source pixels of an anamorphic video, it might be worth adding some sort of option to the `screenshot` command which enables you to bypass aspect ratio correction for the screenshot. But this seems like a rather obscure use case so one could argue you'd be better off using e.g. ffmpeg or vo_image to grab frames in this case.

**Comment by erasmux** [comment] 2018-11-09 14:36
Yes, I am talking of taking "raw" screenshots of the source pixels. But I think you are right, a more natural tool for such extractions would be ffmpeg and such. I "abuse" mpv for this only out of convenience, as I can select the frame visually and generate a screenshot with a single stroke. For this the `--video-aspect=no` flag seems like a clean solution.
