### ISSUE TITLE
Stuttering during video playback

### ISSUE THREAD

**Issue by dokur0chan** [mpv-player/mpv#12699] opened 2023-10-21 01:51 UTC
### Important Information

Provide following Information:
```
mpv v0.36.0-608-gae908a70 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Oct 21 2023 01:14:57
libplacebo version: v6.338.0-38-gadc9d7f-dirty
FFmpeg version: N-112494-g393d1ee54
FFmpeg library versions:
   libavutil       58.27.100
   libavcodec      60.30.102
   libavformat     60.15.100
   libswscale      7.4.100
   libavfilter     9.11.100
   libswresample   4.11.100
```
- Windows 11 10.0.22621 Build 22621
- shinchiro mpv binaries
- Probably caused by this if I had to guess #12662

### Reproduction steps
1. Launch any video with `--no-config`
### Expected behavior
mpv is only broken on Windows 7.

### Actual behavior
mpv is broken on all versions of Windows.

### Log file
[ihatempv.log](https://github.com/mpv-player/mpv/files/13059541/ihatempv.log)

**Comment by Isaacx123** [comment] 2023-10-21 02:20
Can reproduce as well, constant stuttering when playing any video. 

Command used:
`mpv --no-config --log-file=mpv.log "GHOST IN THE SHELL 1.0_t02.mkv"`

[mpv.log](https://github.com/mpv-player/mpv/files/13059591/mpv.log)

**Comment by kasper93** [comment] 2023-10-21 02:44
Interesting, I don't see much issues with my local build. But with shinchiro's it is completely broken indeed. Use older build for now.

I have some local changes that likely will resolve the issue, but I will let @sfan5 decide what to do.

**Comment by Isaacx123** [comment] 2023-10-21 03:23
Using the artifacts build from [here](https://github.com/mpv-player/mpv/pull/12698#issuecomment-1773490028) and still get stutters during playback. 

[mpv.log](https://github.com/mpv-player/mpv/files/13059741/mpv.log)

Also happens with gpu-next:

[mpv.log](https://github.com/mpv-player/mpv/files/13059745/mpv.log)

**Comment by CharlesMengCA** [comment] 2023-10-21 04:38
Bug introduced between 9f147496b50e1d281b61e9659401d0abdfc97d3f and 3fb4eb2ba47fea78e69937971974f42cba82d1df

**Comment by dokur0chan** [comment] 2023-10-21 04:47
> try_lock change

I can still reproduce the issue with `--ao=openal`.

But it would interesting if it's build-dependent rather than an issue with the timer changes specifically.

**Comment by Jules-A** [comment] 2023-10-21 06:26
Oh so it wasn't just me, I went back to the previous shinchiro build which was fine. Was noticing only slightly increased frametimes (like 5%) but it was dropping frames quite often.

**Comment by sfan5** [comment] 2023-10-21 10:16
I can't reproduce this either, try this build and check: https://github.com/mpv-player/mpv/actions/runs/6596458157#artifacts

If you can still reproduce it please download [this ZIP](https://kitsunemimi.pw/tmp/mpv-timertest.zip) and test which executables exhibit the issue.
The revisions are as follows:
* `latest`: 490af95c10e15b33b1a3605ee16805b8e4bf73eb
* `latest-winpthreads`: 490af95c10e15b33b1a3605ee16805b8e4bf73eb with `-Dinternal-win32-pthreads=disabled`
* `new`: 3fb4eb2ba47fea78e69937971974f42cba82d1df
* `revert`: 9f147496b50e1d281b61e9659401d0abdfc97d3f
* `before`: 9a7291d48ea8ee9c661a7a1f70de1c75cad17336

> I have some local changes that likely will resolve the issue, but I will let @sfan5 decide what to do for now.

Do you have an idea what could cause this? If so, what is it?

**Comment by kasper93** [comment] 2023-10-21 12:56
> Do you have an idea what could cause this? If so, what is it?

``` diff
diff --git a/osdep/win32/pthread.c b/osdep/win32/pthread.c
index 9bc7f0057d..c9f581957e 100644
--- a/osdep/win32/pthread.c
+++ b/osdep/win32/pthread.c
@@ -119,7 +119,7 @@ int pthread_cond_timedwait(pthread_cond_t *restrict cond,
         timeout_ms = INFINITE;
     } else if (abstime->tv_sec >= ts.tv_sec) {
         int64_t msec = (abstime->tv_sec - ts.tv_sec) * INT64_C(1000) +
-            (abstime->tv_nsec - ts.tv_nsec) / INT64_C(10000000);
+            (abstime->tv_nsec - ts.tv_nsec) / INT64_C(1000000);
         if (msec > ULONG_MAX) {
             timeout_ms = INFINITE;
         } else if (msec > 0) {
```

**Comment by Isaacx123** [comment] 2023-10-21 13:43
>try this build and check: https://github.com/mpv-player/mpv/actions/runs/6596458157#artifacts

Still getting stutters and frames drops on that build:

[mpv.log](https://github.com/mpv-player/mpv/files/13060771/mpv.log)

PC Specs:

- Ryzen 7 5800x
- RTX 3060 Ti
- Windows 10 21H2

The file used is a H.264 8-bit video and is being read off a NVME SSD so there shouldn't be any bottleneck.

>If you can still reproduce it please download [this ZIP](https://kitsunemimi.pw/tmp/mpv-timertest.zip)

**Stutters and frame drops:**
[latest.log](https://github.com/mpv-player/mpv/files/13060788/latest.log)
[new.log](https://github.com/mpv-player/mpv/files/13060803/new.log)


**Running without any issues:**
[latest-winpthreads.log](https://github.com/mpv-player/mpv/files/13060801/latest-winpthreads.log)
[revert.log](https://github.com/mpv-player/mpv/files/13060819/revert.log)
[before.log](https://github.com/mpv-player/mpv/files/13060825/before.log)

I hope this helps @sfan5

**Comment by sfan5** [comment] 2023-10-21 13:58
@kasper93 oops.

Next time I will definitely type `1000 * 1000` into a calculator instead of doing it by hand.

@Isaacx123 should be fixed in https://github.com/mpv-player/mpv/actions/runs/6597777436 (as soon as it finishes)

**Closed** 2023-10-21 13:58 UTC
Labels: os:win

**Comment by kasper93** [comment] 2023-10-21 14:08
> Next time I will definitely type 1000 * 1000 into a calculator instead of doing it by hand.

We should be using new handy macros added recently `MP_TIME_MS_TO_NS(1)`, but I forgot they are merged already.

**Comment by Isaacx123** [comment] 2023-10-21 15:31
Can confirm the stutters and frame drops **are gone** on the latest zhongfly build:

[mpv.log](https://github.com/mpv-player/mpv/files/13061107/mpv.log)

**Comment by dokur0chan** [comment] 2023-10-22 01:08
Late to the party, but yes, the issue is fixed now.
