### ISSUE TITLE
Black flashes with display-resample interpolation and vo=gpu-next on specific video

### ISSUE THREAD

**Issue by q3cpma** [mpv-player/mpv#12150] opened 2023-08-13 13:48 UTC
### Important Information

Provide following Information:
- mpv version: 0.36.0
- liplacebo version: 6.292.1
- Linux Distribution and Version: gentoo
- Source of the mpv binary: vapoursynth portage tree (exactly the same build as mainline, with vapoursynth added)
- If known which version of mpv introduced the problem: unknown
- Window Manager and version: bspwm git
- GPU driver and version: mesa 21.1.3 (radv/radeonsi)
- Possible screenshot or video of visual glitches: no

### Reproduction steps

With
```
mpv --no-config --vo=gpu-next --video-sync=display-resample --interpolation vid.webm
```
I randomly get one or two black flashes after 1 second of starting or pause->play. When it happens, the `mistimed`/`delayed` count goes up, but `dropped` stays at 0. `DS` also fluctuates wildly before settling on 2.000.

Adding `--gpu-api=vulkan --tscale=catmull_rom` makes these way more reproducible (2 or 3 at the beginning).

These go away with `--vo=gpu`.

### Log file
Here's a log when it happens (two flashes) with the first command line: http://0x0.st/H_ng.log

### Sample files
Here's the **only** video on which it happens: http://0x0.st/H_nE.webm

**Comment by Dudemanguy** [comment] 2023-08-13 14:33
Duplicate of #11958 (without osd-bar, the screen stays black).

**Closed by Dudemanguy** 2023-08-13 14:33 UTC
Labels: os:linux
