### ISSUE TITLE
macOS HiDPI scaling regression since 7bddd3f (v0.25.0): --geometry wrongly scaled

### ISSUE THREAD

**Issue by zmwangx** [mpv-player/mpv#4357] opened 2017-04-23 17:55 UTC
This is a regression due to 7bddd3fb4cdb111b047965fe9884af765c0ad2bb (supposed to address #4194), which first appeared in v0.25.0.

Previously, on a Retina Mac with a scaled resolution, `--geometry` would respect the scaled resolution; for instance, if the 2880x1800 physical display is scaled to 1920x1200, then `--geometry=1920x1200` would fill the screen. However, since 7bddd3fb4cdb111b047965fe9884af765c0ad2bb, `--geometry=1920x1200` only fills a 960x600 area, and one has to use `--geometry=3840x2400` to fill the screen. This is extremely weird because the display doesn't even have that many physical pixels. Also, turning `--hidpi-window-scale` on or off doesn't make a difference here.

### mpv version and platform

`0.25.0-7-g809d160c1` (since `git-7bddd3fb4`) on macOS 10.12.4.

Hardware: MacBookPro11,5, aka MacBook Pro (Retina, 15-inch, Mid 2015).

### Reproduction steps

1. Set screen resolution of the built-in display to scaled 1920x1200. (System Preferences -> Displays -> Display -> Scaled -> More Space).
2. `mpv --geometry=1920x1200 <video>`. Note that `--hidpi-window-scale` and `--no-hidpi-window-scale` have no visible effect here.

### Expected behavior

Video fills the 1920x1200 screen.

### Actual behavior

Video only fills a 960x600 area.

### Log file

https://gist.githubusercontent.com/anonymous/6702d705a088449992fd238f00503aa0/raw/8bcb1ec56ce17cc26807ec06558ce0e9dbe7f656/mpv-geometry=1920x1200.log

### Sample files

Any file.

**Comment by zmwangx** [comment] 2017-04-23 18:01
Regarding the log file: there are some suspicious looking options from my `mpv.conf` (I thought using a different `$HOME` would stop `mpv` from loading that; apparently not) but they don't make a difference. Here's another log file without loading that `mpv.conf`.

https://gist.githubusercontent.com/anonymous/990a66cd5b981ced88f7090aa005b4c2/raw/f4d9112b2ef664493db38146761ea6123efbb6aa/mpv-geometry=1920x1200.log

**Comment by Akemi** [comment] 2017-04-23 18:04
duplicate of #4218.

**Comment by zmwangx** [comment] 2017-04-23 18:04
Sorry, didn't search...

**Closed by Akemi** 2017-04-23 18:04 UTC
