### ISSUE TITLE
cursor not restored following abort with vo=sixel

### ISSUE THREAD

**Issue by dankamongmen** [mpv-player/mpv#9144] opened 2021-08-19 20:39 UTC
### Important Information

Provide following Information:
- mpv 0.33.0-312-g3abb23d70f-dirty
- debian unstable
- git
- *If known which version of mpv introduced the problem*
- compiz 0.8.18
- nvidia 470.57.02
- *Possible screenshot or video of visual glitches*

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Use `-vo sixel` in a way that causes an abort. The cursor will not be restored, as it is on a normal exit.

```
[schwarzgerat](0) $ mpv -vo sixel glomp.mp4
 (+) Video --vid=1 (*) (h264 1920x1080 29.970fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
[autoconvert] Converting yuv420p -> rgb24
mpv: ../video/zimg.c:242: repack_entrypoint: Assertion `!(i & (mp_repack_get_align_y(r->repack) - 1))' failed.
mpv: ../video/zimg.c:242: repack_entrypoint: Assertion `!(i & (mp_repack_get_align_y(r->repack) - 1))' failed.
mpv: ../video/zimg.c:242: repack_entrypoint: Assertion `!(i & (mp_repack_get_align_y(r->repack) - 1))' failed.
mpv: ../video/zimg.c:242: repack_entrypoint: Assertion `!(i & (mp_repack_get_align_y(r->repack) - 1))' failed.
Aborted (core dumped)
[schwarzgerat](134) $ 
```

The cursor is invisible at this point.

### Expected behavior

The cursor ought be made visible again using `RESTORE_CURSOR`.

### Actual behavior

`RESTORE_CURSOR` is not emitted.

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/7017597/output.txt)

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by avih** [comment] 2021-08-19 20:45
This is not a problem of the sixel vo. If mpv aborts/segfault/crash then the sixel VO doesn't get a chance to clean up and restore the terminal to a sane state. Same as when any other terminal application crashes (while the cursor is hidden).

The problem here is that mpv aborts with an asserion. This shouldn't happen, and hopefully it can be fixed.

Please file a new issue about the assertion (and close this one), or, if you prefer, change this issue to describe the assirtion.

Regardless, this is unrelarted to the sixel VO.

**Comment by dankamongmen** [comment] 2021-08-19 20:52
well even if this is fixed, you agree hopefully that future asserts ought not leave the terminal in an invalid state if possible? in Notcurses apps we typically install a signal handler for sigabrt etc that ensures we reset such terminal.properties on a fatal signal.

**Comment by avih** [comment] 2021-08-19 21:00
> you agree hopefully that future asserts ought not leave the terminal in an invalid state if possible?

I agree that preferably the application gets a chance to clean up on any unintentional abort.

Unfortunately, this is not easy to do. I don't think it's worth spending more time on this, because it's not likley to happen. When an application crash then it's a bug somewhere. It shouldn't happen. Hopefully the bug can be fixed.

Now please follow my request and open a new issue or change this one. Thanks.

**Comment by tantei3** [comment] 2021-08-20 08:44
The assertion message seems to be similar to [#8433](https://github.com/mpv-player/mpv/issues/8433) and might be related to zimg version.

@avih I can spend some time on cleanup if you can help with the details.

**Closed** 2021-08-20 09:08 UTC
Labels: os:linux

**Comment by avih** [comment] 2021-08-20 10:12
@dankamongmen can you confirm that upgrading zimg fixes the issue?

**Comment by dankamongmen** [comment] 2021-08-20 10:15
> @dankamongmen can you confirm that upgrading zimg fixes the issue?

doesn't look like it `Version: 3.0.2+ds1-1`

**Comment by avih** [comment] 2021-08-20 10:18
> @avih I can spend some time on cleanup if you can help with the details.

No. An assertion means something unexpected happened. The safest thing to do in such case is to abort immediately. It's not worth the cleanup attempt, which can make things worse, especially for the sole reason of unhiding the cursor. The correct solution is to fix the assertion.

If indeed it depends on the zimg version, then maybe we should increase the minimum required version. Currently we require zimg >= 2.9, but maybe we should increase it to 3?

**Comment by avih** [comment] 2021-08-20 10:28
> doesn't look like it `Version: 3.0.2+ds1-1`

Thanks.

You seem to set quite a lot of options in your config. Can you help us with a minimal test case of the issue, preferably with an mpv invocation which starts with `--no-config` (and additional minimal set of options needed to trigger it)?

If you can reproduce it with zimg and without sixel it would be best, because, as far as I can tell, the sixel vo doesn't use zimg directly, and use scaling the same as any other VO which uses zimg for scaling, so it's _probably_ not sixel-specific.

If you can reproduce it without an external file, it would be best, e.g.
```
mpv --no-config  --zimg-WHATEVER... av://lavfi:testsrc=size=1920x1080
```

The point of all of this is to be able to reproduce exactly your issue without depending on specific config files etc, and preferably without depending on using sixel, if possible.

**Comment by avih** [comment] 2021-08-20 11:52
> doesn't look like it `Version: 3.0.2+ds1-1`

Well, I can reproduce an assertion at the same line with zimg 2.9.3, but not with zimg 3.0.2, with the following command:
```
$ mpv --no-config --vo=x11 av://lavfi:testsrc2=size=800x600
```

@dankamongmen Can you reproduce the assertion with the command above? Are you 100% sure mpv is using zimg 3.0.2?

Otherwise, we still need an exact command to reproduce the issue without depending on config files. If you can't reproduce it with `av://lavfi:testsrc2` (note the 2), then please upload a short clip which reproduces the issue, to be used with the command which you'd specify.

**Comment by avih** [comment] 2021-08-24 06:15
@dankamongmen ?
