### ISSUE TITLE
HLS MP4 Video seek freezes with invalid NAL unit size errors (Apple official example)

### ISSUE THREAD

**Issue by voronoff2803** [mpv-player/mpv#15184] opened 2024-10-26 16:10 UTC
### mpv Information

```bash
- Source of mpv: 0.39.0
```

### Other Information

```text
MacOS 15.0.1
```

### Reproduction Steps

1. Open MPV using the following command:

   ```bash
   mpv https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8
   ```

2. Attempt to seek forward to an area of the video that has not been preloaded.

3. Observe the terminal output and playback behavior.

**Observed Behavior:**

The video initially plays without issue. However, when seeking to an area that hasn't been preloaded, MPV produces multiple `[ffmpeg] NULL:` error messages similar to the following:

```
[ffmpeg] NULL: Invalid NAL unit size (-1137188433 > 32370).
[ffmpeg] NULL: missing picture in access unit with size 32374
[ffmpeg] NULL: Invalid NAL unit size (8257570 > 15009).    
[ffmpeg] NULL: missing picture in access unit with size 15013
[ffmpeg] NULL: Invalid NAL unit size (1258538193 > 18896). 
[ffmpeg] NULL: missing picture in access unit with size 18900
...
```

After these errors occur, the video freezes, and playback does not resume.

### Expected Behavior

When seeking to a different part of the video, the player should be able to buffer and resume playback smoothly without generating these error messages or freezing.

### Actual Behavior

The video initially plays without issue. However, when seeking to an area that hasn't been preloaded, MPV produces multiple `[ffmpeg] NULL:` error messages similar to the following:

```
[ffmpeg] NULL: Invalid NAL unit size (-1137188433 > 32370).
[ffmpeg] NULL: missing picture in access unit with size 32374
[ffmpeg] NULL: Invalid NAL unit size (8257570 > 15009).    
[ffmpeg] NULL: missing picture in access unit with size 15013
[ffmpeg] NULL: Invalid NAL unit size (1258538193 > 18896). 
[ffmpeg] NULL: missing picture in access unit with size 18900
...
```

After these errors occur, the video freezes, and playback does not resume.

### Log File

```
[ffmpeg] NULL: Invalid NAL unit size (-1137188433 > 32370).
[ffmpeg] NULL: missing picture in access unit with size 32374
[ffmpeg] NULL: Invalid NAL unit size (8257570 > 15009).    
[ffmpeg] NULL: missing picture in access unit with size 15013
[ffmpeg] NULL: Invalid NAL unit size (1258538193 > 18896). 
[ffmpeg] NULL: missing picture in access unit with size 18900
...
```

### Sample Files

https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by sfan5** [comment] 2024-10-26 16:13
This also happens with ffplay. You should report this bug directly to ffmpeg.

**Comment by llyyr** [comment] 2024-10-27 00:43
Duplicate of https://github.com/mpv-player/mpv/issues/13211

**Closed** 2024-10-27 00:49 UTC
Labels: down-upstream:ffmpeg
