### ISSUE TITLE
mpv CLI works in OS X Mojave but bundle crashed

### ISSUE THREAD

**Issue by vicdus** [mpv-player/mpv#6097] opened 2018-08-31 06:13 UTC
### mpv version and platform

macOS Mojave 10.14 Beta (18A377a)

Github master 
```
commit 91786fa99c15dc64d3bce4be413326ba2dbe59f7 (HEAD -> master, origin/master, origin/HEAD)
Author: Michael Hoang <enzime@users.noreply.github.com>
Date:   Thu Aug 16 11:30:02 2018 +1000

    Revert "ao_openal: enable building on OSX"
    
    This reverts commit af6126adbe61fb2b6cc780025246d33df93072e6. Apple's
    OpenAL support is ridiculously out of date, revert back to just using
    OpenAL Soft on macOS (fixes #4645).
```
### Reproduction steps

```
git clone https://github.com/mpv-player/mpv.git
cd mpv
./bootstrap.py
./waf configure
./waf
./waf install
TOOLS/osxbundle.py build/mpv
cp -r build/mpv.app /Applications/

build/mpv SOME_VIDEO_FILE.mkv # <--- this works
```
double click `SOME_VIDEO_FILE.mkv` use mpv.app in /Applications/, crashed

### Expected behavior
both mpv.app and build/mpv works

### Actual behavior
double click `SOME_VIDEO_FILE.mkv` use mpv.app in /Applications/, crashed

### Log file

no CLI log since CLI works

apple crash report:

https://0x0.st/stOY.log

**Comment by Akemi** [comment] 2018-08-31 09:27
duplicate of #5908, fixed with #5953.

**Closed by Akemi** 2018-08-31 09:27 UTC

**Comment by vicdus** [comment] 2018-09-02 17:15
checkout the PR and verified fixed.

Just curious why it is not merged into master?

```
git clone https://github.com/mpv-player/mpv.git
cd mpv
git pull origin pull/5953/head
./bootstrap.py
./waf configure
./waf
./waf install
TOOLS/osxbundle.py build/mpv
rm -rf /Applications/mpv.app
cp -r build/mpv.app /Applications/
```

**Comment by Akemi** [comment] 2018-09-02 17:36
lack of manpower i suppose. there are only a few people left with push/merge rights.
