### ISSUE TITLE
cocoa: OnTop in Fullscreen hides menubar after refactoring

### ISSUE THREAD

**Issue by SteveJobzniak** [mpv-player/mpv#3974] opened 2017-01-01 13:16 UTC
Steps to reproduce:

- Press `f` to enter the wonderful new native fullscreen
- Hover your mouse cursor at the top of the screen to make the fullscreen menubar appear
- (While the menubar is visible) Press `Shift+T` to toggle back and forth between ontop.

As you can see, the ontop video drawing surface is rendered higher than the macOS menubar.

**Proposed solution (if such a feature exists):**

Set the cocoa z-index to lower than the macOS menubar. So that it renders above all other windows but below the menubar. In that case, no fiddling with "always on top" will be needed.

**Another proposed solution** (which won't break any existing code or scripts that rely on the "ontop" property, such as https://github.com/yuzukin/mpv/blob/master/TOOLS/lua/ontop-playback.lua):

- When entering fullscreen mode, always set the Cocoa window to "not on top" regardless of the value of mpv's "ontop" property.
- In fullscreen mode, ignore any changes to mpv's "ontop" property. Do not propagate them to the Cocoa surface. Keep it as "not on top" to avoid hiding the menubar.
- When leaving fullscreen mode, apply the "ontop" value from mpv again. (In a way that doesn't cause "race conditions" in scripts that may be observing the fullscreen property and toggling "ontop" as soon as you leave fullscreen. Perhaps that risk of a race condition can be avoided by making the Cocoa surface first instantly set the ontop value for Cocoa when leaving fullscreen, and then immediately checking the mpv value afterwards to see if the mpv property has been changed again via some script.)

**Comment by Akemi** [comment] 2017-01-01 13:41
this is kinda related to #2376. i think first of all 'ontop' has to be defined properly, since there are different opinions about what 'ontop' exactly is. depending on the outcome this might be a wontfix.

**Comment by SteveJobzniak** [comment] 2017-01-01 14:24
@Akemi Ah, yes that issue is related! I was wondering why mpv obscures the dock.

Perhaps we should define "ontop" as "Sierra's always-on-top PIP"? In that case, ontop means "above everything _except_ the dock and menubar". Which seems like it's achieved with NSModalPanelWindowLevel ([there are lots of levels](http://stackoverflow.com/questions/4612422/making-a-window-topmost-within-an-application)).

**Comment by Akemi** [comment] 2017-01-01 14:29
#2377 probably fixes it, but like mentioned not everyone agrees on that behaviour. i personally think the current behaviour works as intended.

it might be a better idea to just write a lua script that observes the fullscreen property and toggles ontop?

**Comment by SteveJobzniak** [comment] 2017-01-01 18:14
@Akemi Yeah I just tried the linked patch. That patch fixes the behavior.

And sure, some people (maybe even me) might like that mpv obscures the menubar and dock. But it certainly _isn't_ intended behavior on macOS. Those are the topmost GUI elements and are always supposed to be accessible. Look at how Sierra's own Picture-in-Picture video player works. It overlays on top of everything _except_ the dock and menubar. That's the mac-like behavior.

How about adding an option

`cocoa-ontop-window-level=max (default)`

`cocoa-ontop-window-level=modal`

I would always run it with modal. Because I have an auto-hiding dock (like every professional I know), and therefore the dock is never in the way. And when I do need the dock I want it to be on top of the video (just like with Sierra's PIP player) so that I can actually click the dock icons. And likewise, I want to be able to use the menubar in fullscreen mode.

So there's certainly a need for a proper modal topmost mode. :)

**Comment by Akemi** [comment] 2017-01-01 18:34
i am not going to decide this, at least not with nearly no input of others.

personally i don't really like adding OS dependent options for every single thing. so i would like to avoid it.

the PiP mode though is independent (uses a different mechanism) from the window level and i was planning to add it at some point. so the ontop option should not work the same way as PiP does.

you could also argue to just not use ontop in combination with fs. it should be perfectly fine to circumvent that behaviour with a script and without changing the mpv source.

i kinda would like @pigoz and @ChrisK2 input on what they think how it should work on OSX and @wm4 input on how it works on other platforms to be consistent.

on a side note seems like i am a weirdo for not auto-hiding the dock.

**Comment by SteveJobzniak** [comment] 2017-01-01 18:41
@Akemi It would be easy to make a lua script to disable ontop in fullscreen, but I use "ontop-playback.lua" (linked at the top) so it'd take some work to get those two to play nicely.

And it seems like a weird thing to have to do just because of mpv's "overzealous z-index". ;)

Adding options for small things is bad, yeah. But then I suggest we make the default Modal so that it behaves like OS X apps should behave (because apps aren't meant to obscure the dock and menubar). Either that, or add an option.

By the way, why aren't you hiding your dock? It takes up 1/10th of the vertical real estate forever. Most windows maximize only to the dock and no further. That's nuts. Instead, make it auto-hide, and then just hover your mouse down there the few times you need the dock. ;)

**Comment by SteveJobzniak** [comment] 2017-01-01 19:01
@pigoz As far as I can see, Modal = on top of everything except the critical system controllers (dock and menubar). It properly sits on top of all apps I've seen so far.

**Comment by Akemi** [comment] 2017-01-01 19:02
changing the current behaviour is a no go. we wouldn't be able to get that behaviour back (which has some uses cases) without changing the source code again, whereas the problem in this issue could be easily mitigated with a script or by just not using ontop.

personally i think the "because OSX Apps behave like this" argument is a bit flat (though i probably used it myself too before). there are several things i dislike about the 'standard OSX behaviour' and i would like to change. also see my first point, we can't change something like that without having a way to reproduce the old behaviour, even less when the desired behaviour could be achieved with a script.

maybe we could add an OS independent option if those different behaviours can be applied to other platforms too? though if there is no interest and/or dev for integrating that option on other platforms, it would just be a OS dependent option again.

offtopic:
the dock only uses vertical space if you leave it at the bottom. if you work mostly in fs there is no dock anyway. i didn't feel the need for more space. i just got accustomed to the dock and i have two Apps that show me real-time data on the dock icon. i don't feel like discussing my dock preferences any further.

**Comment by SteveJobzniak** [comment] 2017-01-01 20:02
Well that conclusively means that there needs to be an option, because mpv is misbehaving according to macOS specs. In this case, misbehaving means obscuring the dock so that it cannot be clicked. Bad. ;)

**Comment by Akemi** [comment] 2017-01-01 22:24
yes i agree that an option for this would be a solution, but you kinda miss the point here with you arguing.

**there are only two things that need discussing here:**

1. it's questionable "what exactly does ontop mean". it's either ontop of everything or ontop of 'user initiated windows'. whichever it is should be default.
2. how should it be implemented that we don't lose any functionality.

**i would appreciate if we would keep it at that.**

since i said you kinda miss the point here my explanation.

you are wrong mpv is not misbehaving. since mpv by default doesn't use ontop and the user opts-in to make mpv behave like this. that's what options are for, to make a program behave 'out of the ordinary', to make it behave different from an expected or standard behaviour. 

also your quote is out of context and cut together. the second sentence is from the a paragraph that only mentions that you should not create windows that will overlap into the dock area. it has nothing to do with ontop or fullscreen windows that obviously overlap into that area. depending on how you interpret the first sentence, there is nothing wrong with mpv.

> Users expect the Dock ... to behave according to their preferences

the users preference is to use an ontop window that stays ontop of everything.  so the dock behaves according to the users preference, it stays behind the mpv window.

> Users expect the Dock to be always available...

since the users preferences takes priority over any human interface guidelines, mpv does the right thing.

> That's like if mpv on Windows obscured the taskbar so that people cannot open the Start menu.

quote of the ontop option.
> On Windows, if combined with fullscreen mode, this causes mpv to be treated as exclusive fullscreen window that bypasses the Desktop Window Manager.

so mpv exactly behaves like you think it shouldn't on windows i would say. since an exclusive fullscreen makes all system elements unavailable. basically how any game in fullscreen behaves.

**Comment by SteveJobzniak** [comment] 2017-01-02 03:26
@Akemi I don't mean fullscreen mode. I mean windowed mode.

In fullscreen it should obviously cover the whole screen and sit on top of everything (except the Apple menubar, which is hidden by defaulr but appears when the user hovers at the top).

In windowed mode it's supposed to overlap application windows so that we can always see mpv. Everyone agrees on that.

The disagreement is about whether it should be allowed to be so far "on top" that it even overlaps the Dock and makes the OS unusable without moving mpv's window out of the way.

Try making mpv windowed, on-top, and placing it in the bottom left like Sierra's PIP. It'll make the dock unusable.

So we arrive at a solution: An mpv flag to decide whether mpv is allowed to overlap OS control elements, or not.

**Comment by ChrisK2** [comment] 2017-01-02 03:32
I didn't read everything, but my case was something with multiple monitors. I think when you focused a window on a different screen the menu-bar on mpv's screen would show up again over the video would could be prevented using ontop ... HOWEVER this doesn't seem to be the case anymore (no menubar or dock with normal fullscreen) so from my side you can change the window-level to something reasonable again.

**Comment by SteveJobzniak** [comment] 2017-01-02 03:41
@ChrisK2 Oh yes you are right. I remember this from my own macOS development days. The old-school "fake fullscreen" meant that macOS ddn't know that an app like mpv was a fullscreen window, so it drew a system menubar (with a very high z-index) on top of mpv whenever you focused another desktop.

Now that mpv is being all lovely with macOS native fullscreen, there is no need for a window-level that overlaps the system control areas. Because the new, native fullscreen (thanks @Akemi for your hard work on that) never shows any Apple menubar unless the user intentionally hovers at the top of their screen to see it.

**Comment by Akemi** [comment] 2017-01-02 11:06
you are still missing the point with your arguing and it's not helping. you are basically trying to make a 'user error' a 'mpv error'.

like i said previously there are only two questions to answer and we know what you want.

**Comment by SteveJobzniak** [comment] 2017-01-02 15:39
@ChrisK2 ![mpv](https://cloud.githubusercontent.com/assets/22373193/21592029/07c34860-d10a-11e6-999d-5bce22d55fab.jpg)

**Comment by enoposix** [comment] 2017-01-02 17:37
**The current behaviour is how it should work.** If you don't want it to cover the dock, then make it not cover the dock by not putting the window over the dock. The 'normal Apple desktop behaviours' don't take priority over what users want (and I'm afraid you're one against many).

**Comment by ChrisK2** [comment] 2017-01-02 17:54
On Top is not needed anymore in fullscreen, so (internally) ignoring the ontop property while in FS to fix the menu-bar not being shown when it should be shown would be the course of action here.

The level for window mode still up for discussion then, but unless more people share their opinion we should just stick to the current behaviour or consider making it configurable if there is enough support for both variants.

**Comment by SteveJobzniak** [comment] 2017-01-03 07:12
@ChrisK2 Yes, making mpv ignore "ontop" in fullscreen mode is the bare minimum.

The other issues (covering dock and Sierra's Picture-in-Picture player) are up for debate. We know what Apple thinks. We know what a few mpv users think. So I vote for making it configurable via `cocoa-ontop-above-system=yes`.

**Comment by enoposix** [comment] 2017-01-03 10:57
>Since both sides have equal merits, I vote for making such unusual behavior configurable via `cocoa-ontop-above-system=yes`

If this does happen, the current behaviour would have to stay as the default.

**Comment by SteveJobzniak** [comment] 2017-01-03 14:00
@enoposix Yeah on second thought I agree with that, to avoid surprising people who are upgrading. ;-)

**Comment by Akemi** [comment] 2017-01-19 19:00
i want to tackle that problem and looked at the various window levels Apple defines. CGWindowLevelKey on the right can be ignored, they are basically just the keys for the window levels itself. CGWindowLevel are all pre-defined levels and NSWindowLevel are the ones which should be used with NSWindow, though all CGWindowLevels can be used too. since there are so many levels and not all are useful for us i eliminated everything that is not relevant.

first i eliminated the ones marked red. since we want an ontop window level everything below NSNormalWindowLevel is not useful for us (though having a full sized window on desktop level could be cool/useful as a video wallpaper). everything kCGAssistiveTechHighWindowLevel or higher should never be overlaid imo. NSDockWindowLevel is deprecated as stated in the header itself.

so far this only leaves us with 4 ontop window levels.
1. just above windows (NSFloatingWindowLevel)
2. above dock, below menubar (NSDockWindowLevel+1/NSMainMenuWindowLevel)
3. above menubar (NSMainMenuWindowLevel+1/NSStatusWindowLevel)
4. above screensaver ([NSScreenSaverWindowLevel+1](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/WinPanel/Concepts/WindowLevel.html))(in my tests screensaver was actual level 2002)

since we always deactivate the screensaver on playback, option 4 seems useless. options 2+3 could be merged, since there is probably no point in just overlaying the dock but not the menubar (though the menubar can't be overlaid anyway, in window, because our constrainFrameRect doesn't allow it).

so imo there are only 2 useful ontop options for our use case. just above windows and above 'system elements' (Dock, Menubar). this could also be easily applied to other platforms and also only needs a simple switch.

if we can agree on this, i would go forward and implement it like this.

![wlevel](https://cloud.githubusercontent.com/assets/680386/22120874/dd3f5d38-de81-11e6-9e2e-6dfdf2c54eed.png)

**Comment by Akemi** [comment] 2017-01-20 15:07
see PR #4051.

**Comment by Akemi** [comment] 2017-02-13 21:51
fixed via https://github.com/mpv-player/mpv/commit/64b0d81c32d90fe29485bdb218fb76608b9aa31b

**Closed by Akemi** 2017-02-13 21:51 UTC
Labels: low priority, osx

**Comment by fitipe** [comment] 2020-07-21 22:58
hi there!

i'm on a high sierra mac and running two simultaneous videos, one behind the other. i intent to use a --ontop-level info sent trough socket to switch between them automatically from time to time ( running a loop python script ).

but so far i just couldn't make it posible ... i've tried lots of different integer values and non did the job.
the window that appears in the front level is allways the last called / initialized, ignoring any values i put.

@Akemi - could you kindly help me with that?

what especific values can i play with?

thanks so far!
