### ISSUE TITLE
Option to prevent mpv from stealling focus when launched on macOS

### ISSUE THREAD

**Issue by zubieta** [mpv-player/mpv#7725] opened 2020-05-14 03:46 UTC
First, thanks for your amazing work.

### Expected behavior of the wanted feature
I would like to be able to launch mpv without stealing the focus in macOS, possibly through an optional `--no-focus` flag.

My use case is to play a playlist on mps-youtube in the background with mpv as the default player, and while I work have the video reproduce in small corner on top of the other windows (kind of picture-in-picture).

At the moment I can pass the flags `--no-osc --no-border --screen=0 --geometry=20%x20%+100%+100% --ontop` to mpv via mps-youtube to get most of that functionality but the focus is still stolen every time a new track plays, sending the keys that I was typing in other window to mpv.

I believe there was a similar request for windows #5724 but I couldn't find any solution for mac.
Another possibly related ticket might be #3612 but there is no mention of focus stealing only of window placement that is already solved.

I have only found a couple of resource that talk about preventing focus stealing. The [first one](https://stackoverflow.com/questions/46023769/how-to-show-a-window-without-stealing-focus-on-macos) seems like the most relevant for this. The [second one](https://www.cnet.com/news/keep-applications-from-stealing-focus-when-opening-in-os-x/) points to a flag that can be set in the `info.plist` file of an app, but I don't think that applies to mpv. In any case I'm not familiar with swift, nor cocoa development to know if this is really possible and if the linked resources are indeed relevant.

### Alternative behavior of the wanted feature

Any other mechanism to prevent focus stealing, (env var, config, etc.).

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/4625933/output.txt)

**Comment by Akemi** [comment] 2020-05-14 05:50
#5724 seems to be closed because of the minimizes and maximize properties, those area also supported by the cocoa-cb backend. though i think that's not what you want.

> but the focus is still stolen every time a new track plays

what do you mean? if it's a playlist and the next track is played mpv won't try to get focus and stays in the background, or is it just launching a new mpv instance?

it should be easily doable implementing that on launch with an option.

**Comment by zubieta** [comment] 2020-05-14 05:59
Yes @Akemi it does launch a new mpv instance every time.

**Comment by wm4** [comment] 2020-05-14 11:25
I don't think it's possible on x11. The protocol simply doesn't have anything for this - I think.

**Comment by zubieta** [comment] 2020-05-18 18:02
Sorry, @wm4 I don't understand why does this have to be implemented at the x11 level? I thought that this could be implemented with `cocoa-cb`.

**Comment by Akemi** [comment] 2020-05-18 18:35
as an additional info if implemented as a more generically used option (eg for more platforms/backends), or he just overlooked the macOS part.

**Comment by zubieta** [comment] 2020-05-18 19:00
I see, it certainly makes sense to try to implement it as generic as possible.

**Comment by wm4** [comment] 2020-05-18 19:22
@Akemi latter
I'd actually love no focus stealing on X11, but it just doesn't seem to be defined.

**Comment by zubieta** [comment] 2020-07-28 02:36
Hi @Akemi, I don't know if there has been any efforts regarding this feature request. Is there has been, is there a branch I can build and try? If not, is there any developer guidelines I can follow to try to give a stab at this? I have zero knowledge regarding cocoa development, but if my understanding is correct I think the change should be small enough that I may be able to try to implement it myself.

**Comment by Akemi** [comment] 2020-07-28 03:15
not atm, i am focused on the moltenvk backend and the generalisation of the code to make it easier for me. otherwise i would need to backport the fix which would be a pain to deal with.

**Comment by zubieta** [comment] 2020-07-28 16:55
Sounds fair, let me know when this can be implemented in the new code. Thanks!

**Comment by orbea** [comment] 2020-07-29 14:51
> I'd actually love no focus stealing on X11, but it just doesn't seem to be defined.

Fwiw I use the tiling wm called spectrwm which has this feature. From the man page:

```
NOFOCUSONMAP           Don't change focus to the window when it
                       first appears on the screen.  Has no effect
                       when focus_mode is set to follow.
```
https://github.com/conformal/spectrwm

**Comment by zubieta** [comment] 2020-07-29 18:21
Thanks @orbea, I have been able to solve it in linux with gnome but unfortunately I haven't being able to solve it in Mac. I guess it is just a matter of patience while mpv gets refactored.

**Comment by Akemi** [comment] 2020-08-03 17:42
i made the PR for the generalisation #7965 only. if this gets merged it shouldn't be much work to add this feature. though no promises when.

**Comment by Akemi** [comment] 2020-09-14 15:30
feel free to test #8087.

**Comment by zubieta** [comment] 2020-09-14 16:02
Hi @Akemi, sorry didn't answer before. Let me try it and I'll post my results later today. :-D

**Comment by zubieta** [comment] 2020-09-15 02:38
I just tried it, but it seems to continue stealing the focus. I'm running it in a tmux pane with this options `--no-focus --no-osc --no-border --screen=0 --geometry=20%x20%+100%+100% --ontop` under iTerm2.

I used this modified brew formula to build it with `brew install --build-from-source --head ./mpv.rb`
[mpv.txt](https://github.com/mpv-player/mpv/files/5222139/mpv.txt)

Here is also a log of a test execution with `mpv --no-osc --no-border --screen=0 --geometry=20%x20%+100%+100% --ontop --log-file=log.txt https://www.youtube.com/watch?v=LT7MOirwZdM`
[log.txt](https://github.com/mpv-player/mpv/files/5222136/log.txt)

**Comment by Akemi** [comment] 2020-09-15 09:32
works as expected here directly in the terminal. since i don't use tmux nor iterm2, maybe it's related to them. also try with --no-config.

**Comment by zubieta** [comment] 2020-09-15 15:31
Okay, let me try it with `--no-config`.

**Comment by Akemi** [comment] 2020-09-15 16:41
also try with the standard terminal without tmux. if you can still reproduce it, we'll need to find out what in your environment causes the problem.

**Comment by zubieta** [comment] 2020-09-17 05:21
Hi,

I had some time to try it again but I still cannot get it to work. I tried with the standard terminal app without tmux or anything special, using the command `mpv -v --no-config --no-osc --no-focus --no-border --ontop --geometry=20%x20%+100%+100% https://www.youtube.com/watch?v=LT7MOirwZdM` and it stills grabs the keyboard focus when the window opens.

I think I didn't mention it before, I'm using Catalina 10.15.6.

Do you have in mind anything else I can do to debug where and why is not working in my system? I don't know swift, but I can add some `log.sendError`  and re-compile it if that could be helpful for debugging 🤷.

**Comment by Akemi** [comment] 2020-09-17 09:38
would you mind making a screen recoding of it? maybe i can see something. otherwise i am still on 10.14.x, so i will try it on 10.15 soonish. i will let you know if i found something and you can try something new/else otherwise.

**Comment by zubieta** [comment] 2020-09-18 03:13
Here is one of what I'm seeing https://imgur.com/a/axAAlqJ Let me know if it is not too clear and I try to get a better one.

**Comment by Akemi** [comment] 2020-09-20 14:22
okay, i could reproduce it on 10.15. seems like they changed things there. which is quite a pain. i will see if this can be fixed.

**Comment by Akemi** [comment] 2020-09-20 18:14
i pushed a fix to my branch/PR. would you mind testing it again? something really weird happens on 10.15. like a process without a name is grabbing focus at some point, and that seems to be the problem why it can't return the focus properly. anyway, apparently since 10.15 you can't keep the focus anymore but you have to refocus the previously focused app. this in returns means that on 10.15 mpv will grab focus for a short time and then will refocus the previous focused app immediately. a bit sad, but so be it.

**Comment by zubieta** [comment] 2020-09-21 02:21
Hey @Akemi, I just tested it and it worked!!! 🎉 🎉  Just as you mentioned, it grabs the focus for a split second and then returns it to the previous process. I know it is not the ideal flow, but I'm super happy this is now possible 😄.

 Thank you so much for taking the time and putting the effort to make this possible. You and the other maintainers and contributors make this project rock!!

**Closed** 2020-09-25 14:48 UTC
Labels: meta:feature-request, os:mac

**Comment by Akemi** [comment] 2020-09-25 14:52
we renamed the option to --focus-on-open (--no-focus-on-open).
