### ISSUE TITLE
Can MPV play videos in a browser through webassembly?

### ISSUE THREAD

**Issue by Naylor55** [mpv-player/mpv#13575] opened 2024-02-26 07:42 UTC

**Comment by CounterPillow** [comment] 2024-02-26 10:08
God I hope not

**Comment by po5** [comment] 2024-02-26 18:35
Seems like a dupe of #13542.

**Comment by Naylor55** [comment] 2024-02-27 01:32
> God I hope not

why？Isn't it good to have MPV run in a browser?

**Comment by Naylor55** [comment] 2024-02-27 02:30
> Seems like a dupe of #13542.

But it doesn't help at all

**Comment by CounterPillow** [comment] 2024-02-27 13:09
> why？Isn't it good to have MPV run in a browser?

No, it's not. It's horrible even. Multimedia decoding relies on very well hand optimised hot paths, which a JIT translation from an architecture independent bytecode format will absolutely butcher in performance. That's why browsers don't implement their own decoders in wasm or JS, that's why they use native code.

But the web plebs demand that everything be done in a browser nowadays. God forbid any application exists that is not a web browser, it must all be Chromium. And then users will demand that they can do things outside of a tab in their browser, so you simply package a copy of Chromium with your frontend shitstack and call it a "desktop app".

Not to mention, once you have moved everything into the browser, every last application that exists retargeted at whatever Google deems to be an acceptable platform, people will turn some application that runs on top of the browser into yet another application platform and then layer things on top of that, because the brain disease that afflicts these kinds of people knows no bounds.

**Closed** 2024-02-27 22:45 UTC
Labels: meta:question

**Comment by Naylor55** [comment] 2024-03-07 03:32
> Maybe there will be a big guy smart enough to implement webgpu and webcodecs support, perfect for a GSoC task.

expect！！！

**Comment by Naylor55** [comment] 2024-03-07 03:33
> > why？Isn't it good to have MPV run in a browser?
> 
> No, it's not. It's horrible even. Multimedia decoding relies on very well hand optimised hot paths, which a JIT translation from an architecture independent bytecode format will absolutely butcher in performance. That's why browsers don't implement their own decoders in wasm or JS, that's why they use native code.
> 
> But the web plebs demand that everything be done in a browser nowadays. God forbid any application exists that is not a web browser, it must all be Chromium. And then users will demand that they can do things outside of a tab in their browser, so you simply package a copy of Chromium with your frontend shitstack and call it a "desktop app".
> 
> Not to mention, once you have moved everything into the browser, every last application that exists retargeted at whatever Google deems to be an acceptable platform, people will turn some application that runs on top of the browser into yet another application platform and then layer things on top of that, because the brain disease that afflicts these kinds of people knows no bounds.

You make sense！
