### ISSUE TITLE
Enabling -v and --log-file leaves Windows cmd prompt with black-on-black colors on exit

### ISSUE THREAD

**Issue by FichteFoll** [mpv-player/mpv#3857] opened 2016-12-01 17:57 UTC
### mpv version and platform

If you're not using git master or the latest release, update.

### Reproduction steps

1. open mpv with some video or url (via ytdl) and specify `-v --log-file=C:\mpv.log` (requires both)
2. close mpv
3. observe result

Reproducable 100% out of ~16 times.

### Expected behavior

Revert back to white on black text.

### Actual behavior

Text is black and cannot be seen. Running commands still functions properly.

Here's a video: https://7.lithi.io/DQFj5H.webm

What I ran after closing mpv:
```
echo "hi"
mpv.exe
cls
```

### Log file

[mpv_normal_log.txt](https://github.com/mpv-player/mpv/files/625383/mpv_normal_log.txt)

**Comment by eintw1ck** [comment] 2017-12-16 23:35
This bug still exists. It could potentially be fixed by just forcing new Windows terminal (Windows 10+) to accept ANSI escape codes. `ENABLE_VIRTUAL_TERMINAL_PROCESSING` is the relevant mode which can be set to enable ANSI escape codes. This of course would only be an option on Windows 10, but realistically, how many people are still on older versions?

**Comment by avih** [comment] 2021-05-07 19:26
Can't reproduce with current mpv master.

I tried `mpv -v --log-file=c:\mpv.log path/to/video.mkv`, and quit after 1-2 seconds of playback by pressing `q`. This resulted in:
```
[global] Failed to open log file 'C:\mpv.log'
```
But the video played normally, the console did show the `-v` messages (white, green, red, etc) and the terminal regained normal colors after I quit mpv.

I also tried the same but with `--log-file=d:\mpv.log`. The log file was saved normally without the log error, and everything else is the same as above (`-v` output shows at the console, terminal regains normal colors after quit).

If anyone thinks this is still an issue with current mpv-master, please request to re-open this issue, preferably with steps to reproduce which we can follow to observe the same issue.

Thanks.

**Closed by avih** 2021-05-07 19:26 UTC
Labels: os:win
