### ISSUE TITLE
Occasional warning backtrace (OSX)

### ISSUE THREAD

**Issue by Argon-** [mpv-player/mpv#2332] opened 2015-09-19 14:52 UTC
Occasionally this is printed: https://gist.github.com/Argon-/f6d375ba200ee97ccafa
When it happens the player is blocked/does not react for a few seconds.

A subsequent run can work just fine (without warning). In fact, most do but sometimes the message above is printed. As it's intermittent, I haven't been able to pin it down to certain options yet.
I'll update this once I have a more detailed log but maybe this already gives you a large enough hint about what might be happening.

mpv git-126367b, ffmpeg 2.8, Xcode 7 with accompanying CLI tools

**Comment by pigoz** [comment] 2015-09-19 15:30
Duplicate of #2048

**Closed by pigoz** 2015-09-19 15:30 UTC
