### ISSUE TITLE
Single instance mode

### ISSUE THREAD

**Issue by singleinstance-kun** [mpv-player/mpv#5467] opened 2018-01-30 18:38 UTC
There's a lot of issues talking about single instance... What about a file on TEMP/TMP?

On turn on 
if isSetToSingleInstance then
if someFileOnTempExists then
--Send msg to opened MPV to open the new file
--Close itself
else
--Create someFileOnTemp
--Just open the file
endif
endif

On turn off
if someFileOnTempExists then
--Delete someFileOnTemp
endif

You can switch the file on Temp with some verification on running processes.
This is so hard to implement? In my point of view it's easy, for like a 30 minutes or less work, but I don't know the way MPV works internally and don't have time now to analise it, so I can't say for sure. Does MPV have any command internal system that can be used? mpv_command maybe?

**Comment by wiiaboo** [comment] 2018-01-30 18:40
Opening another issue about it isn't going to make it be implemented faster.
Duplicate of https://github.com/mpv-player/mpv/issues/4954

**Closed by wiiaboo** 2018-01-30 18:40 UTC
