### ISSUE TITLE
libplacebo crash with gpu-api=vulkan and profile=gpu-hq on Nvidia latest driver

### ISSUE THREAD

**Issue by anor4k** [mpv-player/mpv#7750] opened 2020-05-23 02:13 UTC
### Important Information

Provide following Information:
- mpv version
0.32.0, git master (d62131d)
- Windows Version
Windows 10 1909, build 18363.836
- Source of the mpv binary
[shinchiro](https://sourceforge.net/projects/mpv-player-windows/files/)
git master built with msys2 as per [instructions](https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md)
- If known which version of mpv introduced the problem
don't know; bug introduced with Nvidia driver 445.87
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Use latest Nvidia driver (445.87, no issue on 442.74), GTX 970
Use `--gpu-api=vulkan`, `--profile=gpu-hq` or just `--scale=mitchell` or `--scale=spline36` (have not tested with other scale values)

Play included video sample, enable subtitles, skip to first chapter (~0:09), video completely stops after a few seconds (~0:13)

### Expected behavior
Video and subtitle are rendered normally
### Actual behavior
Video and subtitles completely stop playing (only audio continues). OSD stops as well.
### Log file
Attached logs for 0.32.0 and git-master (look identical at a glance)

[log-0.32.0.txt](https://github.com/mpv-player/mpv/files/4670991/log-0.32.0.txt)
[log-master.txt](https://github.com/mpv-player/mpv/files/4670992/log-master.txt)

### Sample files
Sample [here](https://x.anorak.dev/ShareX/2020/05/bug.mkv) (clip of Fruits Basket S02E01 by LostYears)

**Comment by haasn** [comment] 2020-05-23 07:17
The log verbosity isn't high enough to see the problem. My crystal pendulum says this may be a duplicate of #7743.

**Comment by anor4k** [comment] 2020-05-23 18:15
here's the log for 0.32.0 with `-v -v` https://x.anorak.dev/ShareX/2020/05/2020-05-15%2015.13.38.txt
might be related to that issue, although reproduced differently. how should I go about testing with the libplacebo fix?

**Comment by anor4k** [comment] 2020-05-23 18:24
Also: `--vulkan-async-transfer=no` doesn't help

**Comment by Dudemanguy** [comment] 2022-05-12 20:48
Does this still occur on the latest mpv?

**Closed** 2023-01-10 00:13 UTC
Labels: os:win, vo:gpu:vulkan
