### ISSUE TITLE
Treat subtitle tracks separatedly when adjusting their place in time

### ISSUE THREAD

**Issue by firewater2** [mpv-player/mpv#3732] opened 2016-10-26 23:34 UTC
(Maybe it's already been added, but last time I tried it didn't work)

If you have no subtitles for a video, and you download some to try them out and see if they fit, when you adjust one (delay it 5 seconds, for example), all subtitles you have will be delayed 5 seconds - not just the one you have selected. I remember this would be troublesome when I would give up on adjusting one, and I wanted to go back to another (which was still bad, but not as bad), but it was now even further out of sync.

I don't have a major problem with this since it doesn't present itself as a problem too often, but I believe it could be useful.

**Comment by Idlusen** [comment] 2016-10-29 11:40
As a workaround you could use a simple lua script which keeps track of independent delays.

For instance:
```
sub_delays = {}
function add_delay(delay)
    sub_index = mp.get_property('options/sid')
    if not sub_delays[sub_index] then
        sub_delays[sub_index] = 0
    end
    sub_delays[sub_index] = sub_delays[sub_index] + delay
    sub_delay = sub_delays[sub_index]
    mp.set_property('sub-delay', sub_delay)
    mp.osd_message('Sub delay ('..sub_index..'): '..(sub_delay*1000)..' ms')
end

mp.add_key_binding("x", function(_) add_delay(0.1) end)
mp.add_key_binding("z", function(_) add_delay(-0.1) end)
```
x and z being the default key bindings, overriden.

**Comment by lachs0r** [comment] 2017-07-22 00:27
Duplicate of #2629.

**Closed by lachs0r** 2017-07-22 00:27 UTC
