### ISSUE TITLE
Command-line playlist going back to first track after last song has finished playing

### ISSUE THREAD

**Issue by maxime-michel** [mpv-player/mpv#1429] opened 2015-01-06 13:25 UTC
As discussed on IRC, I use mpv to play music and I like to enqueue tracks to temporary playlists as I go along.

	mpv --idle --input-file=/tmp/mpv
	echo loadfile song1.flac append-play > /tmp/mpv
	# while song1.flac is playing:
	echo loadfile song2.flac append-play > /tmp/mpv

My problem is that I might want to resume playing music with the same mpv process running in the background long after song2.flac has ended, after my lunch break for instance. But when I do `echo loadfile song3.flac append-play > /tmp/mpv` after such a pause, mpv starts at song1.flac. It does enqueue song3.flac after song2.flac, but it starts the playlist all over again. The manual mentions this which didn't help me much:

	--loop=<N|inf|no>
		Loops  playback  N  times.  A  value  of  1  plays  it  one time
		(default), 2 two times, etc. inf means forever. no is  the  same
		as  1  and  disables  looping. If several files are specified on
		command line, the entire playlist is looped.

A workaround I've found is to remove `--idle` in the script I use. That way the temporary playlist is cleared when mpv's finished playing, and my script will start a fresh mpv instance for my new "DJing" session rather than enqueue and reproduce this issue.

**Comment by wm4** [comment] 2015-01-06 14:36
Thanks, will take a look later. I think I understand now what's the issue: if there's a playlist, and it enters idle mode, it will leave idle mode again (probably), leading to a loop. But haven't confirmed yet.

**Comment by wm4** [comment] 2015-01-07 14:19
Hm, I still can't reproduce yet. The playlist is left in place when using append-play, but it starts the correct file.

**Comment by wm4** [comment] 2015-01-08 16:37
Tried with Debian's mpv 0.7.2, and can't reproduce either.

**Comment by wm4** [comment] 2015-01-08 17:15
Turned out this was broken on 0.6.2, but fixed in any later version.

**Closed by wm4** 2015-01-08 17:15 UTC
