### ISSUE TITLE
scrub to end of file -> changes file while mouse button is still held down

### ISSUE THREAD

**Issue by pcordes** [mpv-player/mpv#1805] opened 2015-04-13 07:20 UTC
Using git master (HEAD ab2a27a), built with git master ffmpeg (HEAD 818e8897094d044f80d05eee7a83c9f80a4334a1), Ubuntu 14.10.

EDIT: The OSC breakage only happens with mp4 files that have the weird seek-past-EOF behaviour described in #1807
Dragging all the way to the right with multiple .mpg files in the playlist skips through all of them near-instantly.  (file loads, mouse is still held down past 100%, triggering another playlist_next.)

EDIT2: not quite true: apparently if the last keyframe is close enough to EOF, the OSC still breaks.  Even on files that don't have the scrub-while-paused can seek one-past-last-frame (#1807) bug.

Using the on-screen-controls seek-position slider with the mouse has some weird behaviour when you drag all the way to the right.

While playing a single file:
dragging all the way to the right exits the player.  Annoying if you were actually aiming for 1 min short of EOF, or something.

while playing multiple files:
dragging all the way to the right changes to the next stream, and breaks the OSD.

```
[osc]
[osc] stack traceback:
[osc]   @osc.lua:452: in function 'render_elements'
[osc]   @osc.lua:1775: in function 'render'
[osc]   @osc.lua:1903: in function 'tick'
[osc]   @osc.lua:1859: in function 'process_event'
[osc]   @osc.lua:1963: in function 'cb'
[osc]   mp.defaults:83: in function 'fn'
[osc]   mp.defaults:42: in function 'handler'
[osc]   mp.defaults:316: in function 'handler'
[osc]   mp.defaults:418: in function 'call_event_handlers'
[osc]   mp.defaults:454: in function 'dispatch_events'
[osc]   mp.defaults:411: in function <mp.defaults:410>
[osc]   [C]: in ?
[osc]   [C]: in ?
[osc] Lua error: @osc.lua:452: attempt to index field 'eventresponder' (a nil value)
```

After this, the OSC box is stuck displayed, and the slider won't slide.

Presumably just fixing the change-streams-on-drag-to-EOF behaviour is enough, if that was the only way for eventresponder to unexpectedly be nil there.

**Comment by wm4** [comment] 2015-04-13 08:11
I'm going to say WONTFIX, because the OSC can't just temporarily prevent EOF, and the player has no idea / doesn't care if you keep the mouse button pressed.

The OSC crash is a separate issue (CC @ChrisK2).

**Comment by pcordes** [comment] 2015-04-13 09:35
Can the OSC temporarily enable pause-at-EOF instead of next-file-at-EOF, while the mouse is held down?  It's very user-unfriendly to exit if your mouse slips while trying to seek somewhere near the end of a stream, or just scrubbing around looking at stuff, planning to move the mouse left again.

I guess as a workaround, the user can pause before scrubbing, since dragging all the way to the right doesn't trigger EOF behaviour (like switching streams).

oops, nvm, turns out that workaround doesn't always do the trick after all (e.g. not on .mpg).  Scrubbing all the way to the right while paused gives input-dependent behaviour.  See #1807

**Comment by pcordes** [comment] 2015-04-13 09:49
editted the original: the OSC breakage only happens with broken OSC seeking on some .mp4 files.  Seeking to the last keyframe, then having playback hit EOF while left mouse is still held down, doesn't break the OSC.  Neither does seek-triggered EOF on .mpg.

**Comment by pcordes** [comment] 2015-04-13 14:52
Can the OSC temporarily enable pause-at-EOF instead of next-file-at-EOF, while the mouse is held down?  It's very user-unfriendly to exit if your mouse slips while trying to seek somewhere near the end of a stream, or just scrubbing around looking at stuff, planning to move the mouse left again.

I guess as a workaround, the user can pause before scrubbing, since dragging all the way to the right doesn't do anything other than show the last frame.  (or in some cases, a gray or brokenly-decoded frame?  Looks like another bug...  Yeah, framestep-back from dragging all the way to the right shows the actual last frame, so the OSC is trying to seek to one past the end of the video, and other code is letting it!)

oops, nvm, turns out that workaround doesn't do the trick after all.  Scrubbing all the way to the right while paused gives input-dependent behaviour.  In mpg, it goes to the next file.  In some mp4 files, it goes to the last keyframe, and in others it goes to one-past-the-last-frame (which triggers the OSC problem).  Also, if the last keyframe is too close to EOF, the OSC problem happens.

Disabling playlist advance while scrubbing would solve all of that.

**Comment by wm4** [comment] 2015-04-13 15:11
Maybe it could. But this sounds hacky. And normally, with the command line player, not going to the last file when seeking past the EOF is the unwanted behavior (i.e. the opposite).

**Comment by pcordes** [comment] 2015-04-13 15:27
It would be great to have the option of "weak" seeks that wouldn't trigger a playlist jump.

The current behaviour when scrubbing off the end of an mpg, in a playlist of multiple mpg files is just horrible.  Like I said in my edit to the first post, since the mouse button is still held down, the next file will seek to the end and trigger a playlist_next.  This repeats until you run out of mpg files in your playlist.  (A mouse move event might be needed to trigger another playlist_next, but unless you were nudging your mouse one pixel at a time, the result is that mpv just exits as soon as you hit EOF on the first mpg.)

**Comment by lachs0r** [comment] 2017-07-21 20:29
Can’t reproduce this behavior anymore.

**Closed by lachs0r** 2017-07-21 20:29 UTC
Labels: feature request, stalled

**Comment by SteveJobzniak** [comment] 2017-07-22 12:17
Yes, certainly seems fixed: https://github.com/mpv-player/mpv/issues/3911#issuecomment-317179467

**Comment by SteveJobzniak** [comment] 2017-07-22 12:24
Sad Update: Nope it's not fixed... https://github.com/mpv-player/mpv/issues/3911#issuecomment-317180267
