### ISSUE TITLE
Subtitles stops playing subtitles once reaching address 0x8000

### ISSUE THREAD

**Issue by Beep6581** [mpv-player/mpv#4441] opened 2017-05-20 16:50 UTC
mpv stops showing subtitles at a certain point. I haven't found what these points across various video files have in common, but they seem to lie about halfway through the video.

Tested on Sabayon using mpv-0.22 and probably older versions. I cannot compile a higher version of mpv because of the libav-12 requirement.

Play a video with loaded subtitles, either directly from mpv or via smplayer. The subtitles stop at some point about halfway through the video. This point is not at the same timestamp nor at the same ratio (position/length) for various videos I reproduced this on.

Here are points at which the subtitles stop and the total video lengths:
```
24:38 / 47:10
24:23 / 52:24 
20:39 / 54:20 
28:14 / 58:27
```

[output.log](http://sprunge.us/OATZ)

Sample files:
https://filebin.net/isxofgf0erimarko

For example using `House.of.Cards.S03E04.720p.BluRay.x264.ShAaNiG_en.srt` the subtitles stop at `24:38` showing "I ag" from the line "I agree that tossing him".

If I load the subtitle which ends on "I ag" with a completely different video, it still ends at `24:38` showing "I ag". That indicates its a problem with the subtitle file. I checked them with a hex editor but I see nothing strange about the text at that point of the file.

-- Update

I found a pattern!

The pattern these points do have in common is that they lie on the `7FF0` - `8000` address. Every subtitle file stops playing once it reaches `0x8000`.

**Comment by lachs0r** [comment] 2017-05-20 16:52
Duplicate of #3882

**Closed by lachs0r** 2017-05-20 16:52 UTC
