### ISSUE TITLE
input.conf ignoring mouse wheel (MOUSE_BTN3/MOUSE_BTN4)

### ISSUE THREAD

**Issue by hhiru** [mpv-player/mpv#4649] opened 2017-07-23 15:50 UTC
### mpv version and platform

2017-07-18 - Windows 10 x64

### Reproduction steps

Add these lines in the input.conf
```
MOUSE_BTN3 add volume 2
MOUSE_BTN4 add volume -2
```

### Expected behavior
Changing volume with mouse wheel instead of going forward or backward in the video

### Actual behavior
mpv keeps the default behavior ignoring the input.conf file (only the MOUSE_BTN3/MOUSE_BTN4 part)

### Log file

https://pastebin.com/m4T9MPR4

### Sample files

Relevant part of the input.conf file

```
LEFT add chapter -1
RIGHT add chapter 1
UP add volume 2
DOWN add volume -2
MOUSE_BTN3 add volume 2
MOUSE_BTN4 add volume -2
```

**Comment by haasn** [comment] 2017-07-23 15:55
Try `AXIS_UP`/`AXIS_DOWN`.

**Comment by wiiaboo** [comment] 2017-07-23 15:55
Duplicate of https://github.com/mpv-player/mpv/issues/4623

**Closed by wiiaboo** 2017-07-23 15:55 UTC

**Comment by satnatantas** [comment] 2018-03-25 19:46
Where should the file be BTW? Placig it in home directory does not work for me.

**Comment by leewdch** [comment] 2018-03-25 19:51
~/.config/mpv/

**Comment by satnatantas** [comment] 2018-03-25 19:55
@leewdch nope! On windows it's ~\AppData\Roaming\mpv\ as I found with `procmon`.

**Comment by leewdch** [comment] 2018-03-25 19:58
not really. if you input %appdata% in Win+R you'll go to appdata/roaming. so the correct path is indeed %appdata%/mpv. if you need appdata/local instead you input %localappdata%
