### ISSUE TITLE
icc-3dlut-size hits ICC cache size limit

### ISSUE THREAD

**Issue by Norgerman** [mpv-player/mpv#12979] opened 2023-11-27 02:30 UTC
### Important Information

Provide following Information:
- mpv-x86_64-20231127-git-dea512e
- windows11 23h2
- shinchiro/mpv-winbuild-cmake
- Since: 
    - mpv-x86_64-20231120-git-6e161ff (the version will generate icc cache but not work)
    - mpv-x86_64-20231121-git-48455a9(the version won't generate icc cache)

### Reproduction steps
- play any video with icc-profile-auto=yes and icc-cache=yes

### Expected behavior
- icc cache generated & works.

### Log file
- [20231120-git-6e161ff.log](https://github.com/mpv-player/mpv/files/13469082/20231120-git-6e161ff.log)
- [20231121-git-48455a9.log](https://github.com/mpv-player/mpv/files/13469099/20231121-git-48455a9.log)
- [20231127-git-dea512e.log](https://github.com/mpv-player/mpv/files/13469107/20231127-git-dea512e.log)

**Comment by Traneptora** [comment] 2023-11-27 02:56
How do you know that cache isn't being used? Also, can you reproduce the issue with `mpv --no-config --icc-profile-auto=yes --icc-cache=yes`?

**Comment by Norgerman** [comment] 2023-11-27 03:01
after mpv-x86_64-20231121-git-48455a9, my configured cache-dir doesn't contains any icc cache.
at mpv-x86_64-20231120-git-6e161ff, icc lut re-generated ,even if the cache exists in cache-dir.

**Comment by Norgerman** [comment] 2023-11-27 03:17
- `--no-config --icc-profile-auto=yes --icc-cache=yes --icc-cache-dir="~~desktop/icc"`: works
- `--no-config --icc-profile-auto=yes --icc-cache=yes --vo=gpu-next --icc-cache-dir="~~desktop/icc"`:  works
- `--no-config --icc-profile-auto=yes --icc-cache=yes --vo=gpu-next --icc-cache-dir="~~desktop/icc" --icc-3dlut-size=64x64x64`: works
- `--no-config --icc-profile-auto=yes --icc-cache=yes --vo=gpu-next --icc-cache-dir="~~desktop/icc" --icc-3dlut-size=128x128x128` : works
- **`--no-config --icc-profile-auto=yes --icc-cache=yes --vo=gpu-next --icc-cache-dir="~~desktop/icc" --icc-3dlut-size=256x256x256`**:  **broken**

**Comment by Norgerman** [comment] 2023-11-27 03:45
Thanks, found the limit in log...

**Comment by Traneptora** [comment] 2023-11-28 13:24
It seems fairly undesirable though that the default options (plus icc-cache and icc-profile-auto) hit the cache size limit and invalidate the cache. Should we change the cache size because the default lut size is large?

**Comment by llyyr** [comment] 2023-11-28 14:01
> Should we change the cache size because the default lut size is large?

#12931 addresses this

**Comment by Dudemanguy** [comment] 2023-11-28 16:59
>It seems fairly undesirable though that the default options (plus icc-cache and icc-profile-auto) hit the cache size limit and invalidate the cache. Should we change the cache size because the default lut size is large?

Well specifically it's `--icc-3dlut-size=256x256x256` that is hitting the limit here which allegedly is an option you are not supposed to use.

**Comment by Norgerman** [comment] 2023-11-29 01:22
Surely, the `--icc-3dlut-size` other than `auto` is not supposed to use. Should the icc cache limit be large enough for the size `512x512x512` (according to the manual, the sizes may range from 2 to 512). The icc cache behavior has been changed after upgrade.

**Comment by kasper93** [comment] 2024-03-21 07:12
Fixed by https://github.com/mpv-player/mpv/pull/12931

**Closed by kasper93** 2024-03-21 07:12 UTC
Labels: os:win
