### ISSUE TITLE
Fullscreen in video is over the lock screen of Gnome3

### ISSUE THREAD

**Issue by latot** [mpv-player/mpv#3780] opened 2016-11-07 15:45 UTC
mpv git-7c9f326 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
Gentoo 64

### Reproduction steps
Open a video in fullscreen, now go to other app (maybe this don't is necessary, but i test this in this way), now close the notebook's lid, wait some time until the lock screen of gnome 3, open the notebook.

### Expected behavior
Don't show the video over the lock screen.

### Actual behavior
Next of the reproduction steps the video is showed over the wallpaper and the lock screen.

Thx. Cya.

**Comment by lachs0r** [comment] 2016-11-07 20:58
Pretty much a duplicate of #3779. Not our fault.

**Closed by lachs0r** 2016-11-07 20:58 UTC
