### ISSUE TITLE
Does not work anymore with zdf country limited videos

### ISSUE THREAD

**Issue by mowgli** [mpv-player/mpv#11637] opened 2023-04-28 16:58 UTC
Since few weeks I cannot play videos from zdf.de that are country limited (Example: https://www.zdf.de/dokumentation/zdfinfo-doku/containerschiffe-die-dunklen-geschaefte-der-reeder-100.html)

I currently HAVE a host in germany and using yt-dlp with --proxy works well with it. But in mpv, only the video url is fetched with yt-dlp but not the video itself. There IS a http proxy setting but I cannot test it as my proxy is only socks5.

Please implement a way to proxy also the video itself when using yt-dlp.

**Comment by guidocella** [comment] 2023-04-28 18:12
`yt-dlp -o - $url | mpv -`

**Comment by sfan5** [comment] 2023-04-29 12:13
Essentially a duplicate of #3373

**Closed by sfan5** 2023-04-29 12:13 UTC
