### ISSUE TITLE
Problems with sending filename with spaces through pipe

### ISSUE THREAD

**Issue by storeman** [mpv-player/mpv#4761] opened 2017-08-14 14:41 UTC
### mpv version and platform

mpv 0.26.0-9-g2378acc3b3 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sat Jul 22 10:52:57 UTC 2017

### Reproduction steps

On Windows CMD:
```
.\mpv.exe --input-ipc-server=\\.\pipe\mpvcontrol --idle
```

```
echo loadfile "D:\movie with spaces.mp4" > \\.\pipe\mpvcontrol
````

### Expected behavior
The file should be played

### Actual behavior
Nothing happens. When the file does not contain a space, everything is fine.

### Log file

Added two log files. One with single quotes and one with double quotes

[double-quotes.txt](https://github.com/mpv-player/mpv/files/1222531/double-quotes.txt)
[single-quotes.txt](https://github.com/mpv-player/mpv/files/1222527/single-quotes.txt)

**Comment by lachs0r** [comment] 2017-08-14 14:52
Possible duplicate of #4702. Backslashes need escaping (`\\`).

You didn’t mention the file name that works, so I’ll have to assume the path didn’t contain any backslashes.

**Comment by storeman** [comment] 2017-08-14 18:21
The problem is with the file name that should be loaded. This works fine:

```
echo loadfile D:\movie_without_spaces.mp4 > \\.\pipe\mpvcontrol
```

**Comment by rossy** [comment] 2017-08-15 03:53
This is because backslash escapes are only interpreted inside quotes, so ``D:\movie.mp4`` is fine, but if it's surrounded with quotes, it must be changed to ``"D:\\movie.mp4"``. These quoting rules are different to the ones that most Windows programs use on the command-line because in this case you are sending an input command to mpv, so you must use [mpv's input command syntax][1].

[1]: https://mpv.io/manual/master/#general-input-command-syntax

**Closed by rossy** 2017-08-15 03:53 UTC

**Comment by rossy** [comment] 2017-08-15 04:10
By the way, mpv's IPC protocol is mainly intended to allow other programs to talk to mpv, so it can be a bit unpleasant to use directly. Rather than sending the loadfile command directly, you could use a batch file like this:

```batch
@echo off
setlocal enabledelayedexpansion
set file=%~1
echo loadfile "!file:\=\\!" > \\.\pipe\mpvcontrol
```

Save it as something like ``mpv-loadfile.bat`` and you should be able to run ``mpv-loadfile "D:\movie with spaces.mp4"``.

**Comment by storeman** [comment] 2017-08-15 10:50
This is indeed quite confusing. But thanks for clearing this up for me, I tried all sorts of quote combinations, but not escaping the backslash. Works like a charm!
