### ISSUE TITLE
0.29 crashes on open on macOS 10.14 Mojave (build 18A336e)

### ISSUE THREAD

**Issue by noraa** [mpv-player/mpv#6011] opened 2018-07-23 23:06 UTC
### mpv version and platform

macOS version 0.29

### Reproduction steps

0.29 on immediately quits upon open on macOS 10.14 Mojave (build 18A336e)

### Expected behavior

For it to open as usual...

### Actual behavior

It crashes upon open :)

### Log file

The log file is very short (as it crashes almost immediately) - so just pasting the contents of it below:

[   0.037][v][cplayer] mpv 0.29.0 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
[   0.037][v][cplayer]  built on Mon Jul 23 00:29:04 CEST 2018
[   0.037][v][cplayer] ffmpeg library versions:
[   0.037][v][cplayer]    libavutil       56.14.100
[   0.037][v][cplayer]    libavcodec      58.18.100
[   0.037][v][cplayer]    libavformat     58.12.100
[   0.037][v][cplayer]    libswscale      5.1.100
[   0.037][v][cplayer]    libavfilter     7.16.100
[   0.037][v][cplayer]    libswresample   3.1.100
[   0.037][v][cplayer] ffmpeg version: 4.0.2
[   0.037][v][cplayer] 
[   0.037][v][cplayer] Configuration: waf configure --prefix=/Users/djinn/apps/homebrew/Cellar/mpv/0.29.0 --enable-libmpv-shared --enable-html-build --enable-lua --confdir=/Users/djinn/apps/homebrew/etc/mpv --datadir=/Users/djinn/apps/homebrew/Cellar/mpv/0.29.0/share/mpv --mandir=/Users/djinn/apps/homebrew/Cellar/mpv/0.29.0/share/man --docdir=/Users/djinn/apps/homebrew/Cellar/mpv/0.29.0/share/doc/mpv --enable-javascript --enable-zsh-comp --zshdir=/Users/djinn/apps/homebrew/Cellar/mpv/0.29.0/share/zsh/site-functions
[   0.037][v][cplayer] List of enabled features: 51deb apple-remote asm atomics bsd-fstatfs build-date cocoa coreaudio cplayer cplugins debug-build drmprime fchmod ffmpeg gl gl-cocoa glob glob-posix gnuc gpl iconv javascript jpeg lcms2 libaf libass libass-osd libav-any libavcodec libavdevice libdl libm libmpv-shared lua macos-cocoa-cb optimize osx-thread-name plain-gl posix posix-or-mingw posix-spawn posix-spawn-native pthreads rubberband stdatomic videotoolbox-gl videotoolbox-hwaccel zlib zsh-comp
[   0.037][d][osc] Loading lua script @osc.lua...
[   0.038][d][ytdl_hook] Loading lua script @ytdl_hook.lua...
[   0.038][d][stats] Loading lua script @stats.lua...
[   0.042][d][ytdl_hook] loading mp.defaults
[   0.042][d][osc] loading mp.defaults
[   0.042][d][stats] loading mp.defaults
[   0.044][d][stats] loading @stats.lua
[   0.045][d][ytdl_hook] loading @ytdl_hook.lua
[   0.045][d][osc] loading @osc.lua
[   0.048][d][stats] reading options for stats 
[   0.049][d][ytdl_hook] reading options for ytdl_hook 
[   0.049][v][stats] script-opts/stats.conf not found. 
[   0.049][v][stats] lua-settings/stats.conf not found. 
[   0.049][v][ytdl_hook] script-opts/ytdl_hook.conf not found. 
[   0.049][v][ytdl_hook] lua-settings/ytdl_hook.conf not found. 
[   0.053][d][osc] reading options for osc 
[   0.053][v][osc] script-opts/osc.conf not found. 
[   0.053][v][osc] lua-settings/osc.conf not found.

**Comment by Akemi** [comment] 2018-07-24 08:57
duplicate of #5908.

**Closed by Akemi** 2018-07-24 08:57 UTC

**Comment by sspilleman** [comment] 2018-07-30 12:32
You can install [iina](https://lhc70000.github.io/iina/) (brew cask install iina). Its mpv based and working on mojave without a flaw....
