### ISSUE TITLE
Dark (near black) areas have blue tint (gpu-next)

### ISSUE THREAD

**Issue by FCrane** [mpv-player/mpv#10844] opened 2022-11-10 22:08 UTC
- libmpv (06.11.2022)
- Win64 22H2
- mpv-dev-x86_64-v3-20221106-git-2590651.7z

gpu-next produces a blue-ish tint on near black (very dark) areas in HDR material. Old gpu does not show this issue for the same video material.

See the attached screenshots from Jurassic World:
1: gpu-next produces kind of oversaturated colors and dark areas are clearly blue instead of black.
2: gpu-next colors the dark parts of the black shirt and trousers blue.

You can clearly see the effect when you directly switch between the images with an image viewer.

Would be nice if this could be fixed, because it is quite dominant in many dark scenes...

Here is the mpf conf:

[1]
vo=gpu
hdr-compute-peak = yes
target-peak = auto
tone-mapping = auto

[2]
vo = gpu-next
hdr-compute-peak = yes
target-peak = 88
tone-mapping = auto

BTW: target-peak = auto is much too dark on my system, that's why I'm using "88", which roughly equaly "auto" of old gpu.
![1-gpu](https://user-images.githubusercontent.com/14123400/201216238-2e1b8237-cd86-4286-9538-ae4fa86a6ca6.jpg)
![1-gpu-next](https://user-images.githubusercontent.com/14123400/201216244-7d50e626-3cc6-421c-af63-308041a1118c.jpg)
![2-gpu](https://user-images.githubusercontent.com/14123400/201216249-7414c4ae-19db-46ae-8931-208d2a87caec.jpg)
![2-gpu-next](https://user-images.githubusercontent.com/14123400/201216251-38291acc-3794-499e-a67e-f84bc2c58785.jpg)

**Comment by Natural-Harmonia-Gropius** [comment] 2022-11-11 08:11
Try this, and remove `target-peak = 88` from conf.

[BT2100PQ_to_BT709.glsl](https://github.com/Natural-Harmonia-Gropius/mpv_config/blob/main/shaders/BT2100PQ_to_BT709.glsl)
```ini
[hdr]
profile-cond=get("video-params/sig-peak") > 1
profile-restore=copy
target-trc=pq
target-prim=bt.2020
glsl-shader=~~/shaders/BT2100PQ_to_BT709.glsl
```

**Comment by FCrane** [comment] 2022-11-11 08:36
This does seem to remove the blue, but the picture gets dark, washed out, pale, etc. All the HDR effect seems gone and it's not nice to watch...

![dull](https://user-images.githubusercontent.com/14123400/201299810-dedcf1ce-3fe5-4496-ad98-773a3e7a610f.jpg)

**Comment by Natural-Harmonia-Gropius** [comment] 2022-11-11 08:38
Do you downloaded that glsl and put it into `~~/shaders`?
If yes, press `shift+i` then press `2`, show me the screenshot.

**Comment by FCrane** [comment] 2022-11-11 08:47
I'm using my own player with libmpv. But the shader is active and the profile is set to the values you described. I checked by adding the shader only (which results in distorted colors), then added the target-* lines, etc.

**Comment by FCrane** [comment] 2022-11-11 08:56
I've installed the latest mpv. Same result:

 
![mpv](https://user-images.githubusercontent.com/14123400/201303766-1de81a22-743e-4b99-98e5-68db87ab6a41.jpg)

Looks like a dark and washed out SDR...

**Comment by Natural-Harmonia-Gropius** [comment] 2022-11-11 08:59
How about changing this line to 88? as you set `target-peak = 88`.
https://github.com/Natural-Harmonia-Gropius/mpv_config/blob/5d517e312ef631d693edbc2eeb002c9c71d5b66d/shaders/BT2100PQ_to_BT709.glsl#L58

**Comment by FCrane** [comment] 2022-11-11 09:09
Yes, this helps. Blue is reduced, brightness is better, but still the picture looks "dull" compared to the original "gpu-next". The contrast is significantly worse and the dark areas are brightened up, there's a gray "haze" over the picture:

Original:
![no shader](https://user-images.githubusercontent.com/14123400/201306155-92ad31b6-f09a-42cb-901e-4c3dff33d78d.jpg)

With Shader:
![with shader](https://user-images.githubusercontent.com/14123400/201306176-763e41e0-763c-4a23-964d-d065195e7432.jpg)

**Comment by FCrane** [comment] 2022-11-11 09:11
There simply seems to be a bug in gpu-next that causes dark areas to get a blue tint... Would be best if this could be fixed in the gpu-next code rather than correcting it with shaders, etc....

**Comment by FCrane** [comment] 2022-11-11 10:25
gpu-next also seems to over saturate quite a bit! At least using "saturation = -10" seems to be necessary to get relatively natural colors... Again, compared to old gpu.

**Comment by haasn** [comment] 2022-11-11 12:37
Can you try `--tone-mapping-mode=rgb` vs `--tone-maping-mode=luma`? Does only one of the two produce the oversaturated shadows?

**Comment by FCrane** [comment] 2022-11-11 14:46
Just tried both mapping modes and the result is the same!

After some more testing I think there simply is a general problem with the saturation in gpu-next and HDR material! When using

vo = gpu-next
hdr-compute-peak = yes
target-peak = 88
tone-mapping = auto
target-prim = auto
target-trc = auto
saturation = -25
contrast = 8
brightness = 0

I get pretty natural, bright results (comparable to the old vo=gpu). And the blue shadows also are reduced a lot. Seems the shadows in some HDR scenes do have a dominant blue component and when the saturation is too high, they can be noticed as blue instead of black...

Maxbe we should open a new issue "Over-saturated colors with gpu-next"? I think that's the culprit...

**Comment by haasn** [comment] 2022-11-11 15:18
Does setting just `--vo=gpu-next --target-prim=dci-p3` roughly match the desaturated effect you're looking for?

I think it might be due to a difference in how HDR metadata is applied. `--vo=gpu` ignores mastering metadata entirely and always stretches the full BT.2020 gamut down to the target display's capabilities. `--vo=gpu-next` goes the other way and only stretches the *indicated* part of the spectrum.

This results in more saturated colors overall, but the resulting increase in saturation is still a *decreased* relative to how it would look on a native BT.2020 (HDR) monitor.

**Comment by FCrane** [comment] 2022-11-11 23:01
No, --target-prim=dci-p3 is also visibly oversaturated. However, it just needs saturation=-13 instead of -25 to look the same (exactly the same, actually). 

There really is a saturation problem with gpu-.next...

**Comment by haasn** [comment] 2022-11-11 23:47
Link to source clip?

**Comment by FCrane** [comment] 2022-11-12 08:26
Here is a test clip that shows extremely oversaturated red colors. Turning saturation down -25 and turning contrast up +8 fixes it and produces a great picture (still with slight blueish tint of the black background, but maybe that's the source material). 

Actually, the oversaturation shows in every HDR material! And even in SDR... I now use  saturation-25 and contrast+8 for ALL material and it always looks good! leaving these at 0 causes completely oversaturaed colors in almost everything.

Also: target-peak = auto is much (!) too dark on all my systems! On my monitor (a UHD TV run in SDR mode) and my projector (UHD, also run in SDR mode) I need to use "88" instead of "auto" to get a bright and nice picture. with the old "gpu" I could use "auto" for correct brightness.

 
[TestClip-001.zip](https://github.com/mpv-player/mpv/files/9994520/TestClip-001.zip)

**Comment by Natural-Harmonia-Gropius** [comment] 2022-11-12 08:46
> Does setting just --vo=gpu-next --target-prim=dci-p3 roughly match the desaturated effect you're looking for?

--target-trc=hlg could.

**Comment by FCrane** [comment] 2022-11-12 09:16
> 

No, it's also completely oversaturated...

**Comment by Natural-Harmonia-Gropius** [comment] 2022-11-12 09:29
hlg much better for me, or --tone-mapping-mode=rgb (last screenshot).

![image](https://user-images.githubusercontent.com/50797982/201467717-0bf3d188-44af-4602-83e5-bae4ce9f8c0c.png)
![image](https://user-images.githubusercontent.com/50797982/201467722-ff83f593-4696-4447-b267-ec1f04d4bc79.png)
![image](https://user-images.githubusercontent.com/50797982/201467903-9cafce05-1251-45b5-9264-40403668fdcb.png)

**Comment by quietvoid** [comment] 2022-11-13 02:02
I just know this is partially caused by the default black point for 1:1000 contrast ratio.  
Even switching to 10k contrast ratio makes a significant improvement on saturation at lower brightness. Lowering the black point more causes some issues though.

Comparison: https://slow.pics/c/RFXCww5e

**Comment by FCrane** [comment] 2022-11-15 10:29
o is this over-saturation issue acknowledged by the developers or should I open a separate issue for it?

**Comment by FCrane** [comment] 2022-11-18 14:45
Anyone?

**Comment by haasn** [comment] 2022-11-18 14:58
> Here is a test clip that shows extremely oversaturated red colors. Turning saturation down -25 and turning contrast up +8 fixes it and produces a great picture (still with slight blueish tint of the black background, but maybe that's the source material).

Yeah, I see it. I'll have to look more closely at it but what almost appears to be going on is that BT.2446a tone-mapping is making the image significantly *brighter* than the source material.

If you look at `--tone-mapping=clip` (or `--tone-mapping=spline`) for comparison, it is not as oversaturated. I will try figuring out why BT.2246a is so aggressive in raising the brightness here, because it should IMO not be the case.

**Comment by FCrane** [comment] 2022-11-18 16:37
Thanks for looking into this! However, I really like the brightness - it looks fantastic compared to the dull dark picture. If I turn down the saturation, everything is perfect...

**Comment by haasn** [comment] 2022-11-18 17:20
It seems like there might be a mathematical error in our calculation of the desaturation (in `--tone-mapping-mode=luma/hybrid`). I'll look into it further in a bit.

**Comment by haasn** [comment] 2022-11-18 23:31
https://code.videolan.org/videolan/libplacebo/-/merge_requests/329 this fixes the bug in the desaturation logic, to make it pick the proper desaturation factor from BT.2446a. This is not quite extreme as `--saturation=-25`, but overall saturation should be significantly lower.

**Comment by haasn** [comment] 2022-11-18 23:35
Original (bugged, before the patch):
![mpv-shot0001](https://user-images.githubusercontent.com/1149047/202820332-5a04d2bf-7b44-4255-97d7-d193c0aa5c23.jpg)

Original with `--target-peak=88`:
![mpv-shot0002](https://user-images.githubusercontent.com/1149047/202820354-38cc077e-7cf5-40c5-ae8a-2f5be80ff8fe.jpg)

Original with `--target-peak=88 --saturation=-25`:
![mpv-shot0003](https://user-images.githubusercontent.com/1149047/202820368-df5bf326-a78d-46f7-97ef-a65c838e2412.jpg)

Fixed with `--target-peak=88`:
![mpv-shot0004](https://user-images.githubusercontent.com/1149047/202820382-67f310cd-adfa-432f-8626-42723b69ac4c.jpg)

Fixed with no settings: (default peak)
![mpv-shot0005](https://user-images.githubusercontent.com/1149047/202820405-90bb657c-5e13-42f6-9774-e1ce32715507.jpg)

You can clearly tell that it's desaturating a lot more when tone-mapping down to peak 88, as intended.

**Closed** 2022-11-18 23:39 UTC
Labels: os:win

**Comment by haasn** [comment] 2022-11-19 01:05
Oh, the new logic has a fatal flaw for more extreme tone-mapping ratios. A better function is needed.

**Comment by FCrane** [comment] 2022-11-19 08:46
"We're gonna need a bigger boat!" (quote from "Jaws") ;-)

Thanks for trying to fix this! Please update this thread when a fixed libmpv sinchiro build for Window is available so that I can test it.

Thanks!

**Comment by haasn** [comment] 2022-11-19 13:18
Maybe we should just expose the peak-dependent desaturation factor as a user control.

**Comment by FCrane** [comment] 2022-11-19 14:37
An "auto" setting is always preferrable - at least this should be applicable for all video material, so that the user does not have to adjust it for each and every video separately...

**Comment by dyphire** [comment] 2022-11-19 18:18
> Maybe we should just expose the peak-dependent desaturation factor as a user control.

This may be more appropriate. Make it adjustable to meet more preferences.

**Comment by FCrane** [comment] 2022-11-19 22:50
Adjustable sounds great! Every display seems to be different, everyone seems to have different preferences regarding colors, brightness, etc. so an adjustable option is the most flexible solution. As I mentioned before, I can not use "target-peak=auto", because this is much too dark on all my displays. A setting off 88 produces the best picture here, bright and without loosing detail in bright areas. So "auto" doe not seem to work best in all environments. Setting all values with user adjustable options is the way to go - however, as I mentioned before, it should not be necessary to adjust these settings for each video individually.

Thanks!

**Comment by FCrane** [comment] 2022-12-16 11:16
I've tested the latest shinchiro build and it still noticeably over-saturated. I need to use saturation = -10 to get reasonable colors. But even with that, red components are still over-saturated.

Also, I need to lower the target-peak from 88 to 70 to get an equally bright image as before. Auto still is extremely dark. Other than that, it seems to work well.

Is the peak-dependent desaturation option already implemented? I didn't find it in the options.

Regards!

**Comment by Natural-Harmonia-Gropius** [comment] 2022-12-16 11:51
Share some of clips?
`ffmpeg -ss 00:00:30.0 -i input.mp4 -c copy -t 00:00:10.0 output.mp4`
