### ISSUE TITLE
Why are these "shader cache v1" files in my portable_config?

### ISSUE THREAD

**Issue by Zabooby** [mpv-player/mpv#11917] opened 2023-07-12 13:20 UTC
I have updated to the latest shinchiro build for windows (11) (all my settings are the same before and after updating mpv and my full config can be found [here](https://github.com/Zabooby/mpv-config)) and now have these files generating when I use mpv:
![image](https://github.com/mpv-player/mpv/assets/78969986/4efa6443-78b6-4cd1-9b0f-6d28eba7fba7)

Contents:
![image](https://github.com/mpv-player/mpv/assets/78969986/69eb48ef-8543-4186-a5e5-4c8aa95ca9f4)

What are these files for and can I put them in a separate folder?

**Comment by N-R-K** [comment] 2023-07-12 13:27
Duplicate of https://github.com/mpv-player/mpv/issues/11898 (I think).

**Comment by Zabooby** [comment] 2023-07-12 13:38
> Duplicate of #11898 (I think).

Nah, I use vo=gpu.

**Comment by Dudemanguy** [comment] 2023-07-12 13:41
`vo_gpu` uses shader cache too. The same change caused this.

**Comment by Dudemanguy** [comment] 2023-07-12 13:49
We'll fight it out in #11898 (same underlying issue).

**Closed by Dudemanguy** 2023-07-12 13:49 UTC
Labels: meta:question
