### ISSUE TITLE
mpv is unresponsive

### ISSUE THREAD

**Issue by aesthicc** [mpv-player/mpv#5006] opened 2017-10-17 20:05 UTC
### mpv version and platform
mpv 0.27.0 On macOS High Sierra

### Reproduction steps
Open video file with mpv when mpv is already open (creates second instance)
### Expected behavior
I would like for mpv to just use the instance that is already open. However, I understand this is a "feature". 
### Actual behavior
Second instance of mpv is immediately unresponsive, keeps beachballing. User is unable to force quit this second instance. Reboot necessary.

**Comment by Akemi** [comment] 2017-10-17 22:13
fixed with 77021cf6fe6a1813b832c8927c288e958b6f6845. it's only in master, it will be in the next release.

duplicate of #5004 which i just closed 5 hours ago.

**Closed by Akemi** 2017-10-17 22:13 UTC
