### ISSUE TITLE
XYZ to rgb color space conversion issue

### ISSUE THREAD

**Issue by Cantar4** [mpv-player/mpv#4925] opened 2017-09-25 17:08 UTC
IINA 0.12 / Mac OS 10.12.5

the Jpeg2000  images opened by IINA (under the latest mdv version) suffer from a strong magenta cast.   An IINA developper asked me to send you my observations, here they are:
..
IINA converted (w/mdv)
![iina-xyz-to-rgb](https://user-images.githubusercontent.com/18612991/30821249-f3a064d4-a224-11e7-8065-03ee7aeca164.jpg)
..
VLC converted
![vlc-xyz-to-rgb](https://user-images.githubusercontent.com/18612991/30821221-db771fa6-a224-11e7-8a1a-26b0af80820e.jpg)

**Comment by haasn** [comment] 2017-09-25 17:13
Can you not ignore the issue template?

**Comment by Cantar4** [comment] 2017-09-25 21:26
I thought two pictures were worth two thousand words ;-)
I can only add that these images are displayed by IINA v0.12 and  VLC 3.0.0 running under
Mac OS 10.12.5 in a MacBookPro w/retina screen.

**Comment by Akemi** [comment] 2017-09-25 21:47
an example file would probably be worth even more. if you don't provide a(n easy) way to reproduce your issue no one will care to fix it. the issue template is not there to ignore it.

**Comment by Cantar4** [comment] 2017-09-26 09:57
@ haasn and Akemi,
I would if I could... but I only have access to the 270MB  j2c_xxxx .mxf  file found in a short DCP film... you would not be happy to receive such a massive attachment !
I don't know how to extract a single image from this .mxf file containing 
500 jpeg2000 images, would you tell me how ? 
And if I succeed, how can I get access to the files converted to the rgb color space
by IINA and VLC?

**Comment by CounterPillow** [comment] 2017-09-26 10:10
Not sure how the MXF container is structured, but with any luck, you can upload the first 100 MiB of the file like this from the terminal:

`cat yourfilehere.mxf | head -c 104857600 | curl -F "file=@-" https://0x0.st`

Then just copy and paste the url it spits out here.

**Comment by Cantar4** [comment] 2017-09-26 22:39
@CounterPillow  I extracted seven frames from an mp4 film, converted them to DCP
to get jpg2000 images in a much lighter mxf file of 5MB only.  Is it OK ?

[j2c_24d9f1b0-2492-4b88-8524-582a42775cff.mxf.zip](https://github.com/mpv-player/mpv/files/1335217/j2c_24d9f1b0-2492-4b88-8524-582a42775cff.mxf.zip)

**Comment by haasn** [comment] 2017-09-26 23:17
It seems like this is a whitepoint confusion issue. By default, mpv converts XYZ to RGB using relative colorimetric intent, with the source white point assumed as CIE xy {0.314, 0.351} as per SMPTE 428-1. Disabling this adaptation logic makes the result match VLC (at least more or less) for me.

I'm not sure what the proper fix is here. Is there some way of knowing what the correct white point is for this type of content? (e.g. perhaps some sort of metadata tag we could use)? Or should we just disable white point adaptation for XYZ content and call it a day? (Or make it customizable somehow?) Or should we always respect the tagged/guessed source primaries and use the white point from that?

P.s. In the past, mpv had special logic for converting XYZ directly to the target color space (via the ICC profile / 3DLUT, or using built-in xyz2rgb coefficients for `--target-prim`), but this logic got deleted for simplicity. Right now, mpv internally converts all XYZ to RGB right away and then treats it as normal, but this operation clips all values to the tagged colorspace (or BT.709 if untagged). It was decided that XYZ->RGB conversion was such an uncommon use case that putting any effort into it was unjustified. It's possible this logic could be made smarter again, if there would be a genuine benefit.

**Comment by haasn** [comment] 2017-09-26 23:23
For testing, you can disable whitepoint adaptation using this patch:

```diff
diff --git a/video/csputils.c b/video/csputils.c
index d9a5c29491..2aef1a5ba9 100644
--- a/video/csputils.c
+++ b/video/csputils.c
@@ -707,7 +707,7 @@ void mp_get_csp_matrix(struct mp_csp_params *params, struct mp_cmat *m)
         // The vo should probably not be using a matrix generated by this
         // function for XYZ sources, but if it does, let's just assume it
         // wants BT.709 with D65 white point (virtually all other content).
-        mp_get_xyz2rgb_coeffs(params, MP_INTENT_RELATIVE_COLORIMETRIC, m);
+        mp_get_xyz2rgb_coeffs(params, MP_INTENT_ABSOLUTE_COLORIMETRIC, m);
         levels_in = -1;
         break;
     }
```

**Comment by Cantar4** [comment] 2017-09-27 07:02
@haasn  Thank you indeed for your instant reaction to my question !
your thorough analysis of the issue lets me think the white point selection should be offered to the user by the front end application using your libraries, e.g. IINA.

**Comment by haasn** [comment] 2017-10-13 01:39
Also, I'm not confident in mpv'z XYZ->RGB conversion anymore. I've noticed a couple of quirks that could impact the quality of the result.

**Comment by Cantar4** [comment] 2017-10-13 04:23
@haasn  In http://dcpomatic.com/development there is [colour.pdf](https://github.com/mpv-player/mpv/files/1381375/colour.pdf) "colour processing done by dcpomatic" in which there is "4-Adjust the white point".
Could this Carl Hetherington publication be helpful?

**Comment by ValZapod** [comment] 2021-08-14 11:30
It is even now much worse now since it assumes BT.2020 PRIMARIES somehow and LInear (CARL!) transfer. LOL.

It is of course fixed by: 
mpv.com --vf=format=primaries=cie1931:gamma=gamma2.6 C:\Users\ZAQU\Downloads\j2c_24d9f1b0-2492-4b88-8524-582a42775cff.mxf

Of course the reference decoder libopenjpeg does not support RSIZ stuff yet too, sigh. jpeg2000 native decoder is recognizing it.

**Closed** 2023-03-02 14:37 UTC
Labels: core:color-management
