### ISSUE TITLE
Black flickering while resizing mpv window when `--gpu-api=vulkan` or `--d3d11-flip=no` is used

### ISSUE THREAD

**Issue by Sneakpeakcss** [mpv-player/mpv#12642] opened 2023-10-15 16:48 UTC
### Important Information

Provide following Information:
- mpv version: `v0.36.0-549-g78d43740`
- Windows Version: `WIN10 22H2`
- Source of the mpv binary: `https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/`
- If known which version of mpv introduced the problem: [d17db13](https://github.com/mpv-player/mpv/commit/d17db1367affa954f5c52c793840b667527d88d3)
- Possible screenshot or video of visual glitches:

https://github.com/mpv-player/mpv/assets/77424331/230679f2-a240-4cf4-b717-1e9503b64ef1

### Reproduction steps

- Launch any video with either:
a) `mpv.exe --no-config --d3d11-flip=no test.mp4`
b) `mpv.exe --no-config --gpu-api=vulkan test.mp4`
- resize the window (preferably while a video is playing)

### Expected behavior

Like previously video shouldn't flicker.

### Actual behavior

Constant black flickering/black screen while resizing mpv window.

### Log file
[vulkan.txt](https://github.com/mpv-player/mpv/files/12910119/vulkan.txt)
[d3d11flip.txt](https://github.com/mpv-player/mpv/files/12910120/d3d11flip.txt)

  ___

Additionally, in both cases resizing doesn't flicker when `border` is turned off.

**Comment by kasper93** [comment] 2023-10-16 03:45
https://github.com/mpv-player/mpv/pull/12646 will resolve the issue, you can try build with this change.

**Comment by dokur0chan** [comment] 2023-10-16 04:14
I'll reiterate what I said in the other issue, but I can't reproduce this on `vulkan`. However, `d3d11-flip=no` does actually cause this (I don't really see why you would want to disable flip-mode presentation though... kinda defeats the purpose of using `d3d11`). Probably some kind of driver related issue where `vulkan` doesn't benefit from windowed mode optimizations or something, if I had to guess.

I wonder how many of these issues could be solved by rendering `vulkan` surfaces on a DXGI swapchain, but I'm not sure if that would be a driver related nightmare as well.

**Comment by kasper93** [comment] 2023-10-16 08:53
> I'll reiterate what I said in the other issue, but I can't reproduce this on vulkan. However, d3d11-flip=no does actually cause this

No worries, there is no downside of doing the clear once, still will resolve the initial issue. I wanted to do that in the first place, but found it clearer to do without additional state.

> I wonder how many of these issues could be solved by rendering vulkan surfaces on a DXGI swapchain, but I'm not sure if that would be a driver related nightmare as well.

There are improvements to be done, but I'm not touching anything in swapchain code, until this is merged
https://code.videolan.org/videolan/libplacebo/-/merge_requests/507
https://github.com/mpv-player/mpv/pull/12431
and `ra` cleared/replaced with `pl` API. After that we can think about further improvements, but for now those are the changes that should be done first.

**Comment by Sneakpeakcss** [comment] 2023-10-16 09:32
> I'll reiterate what I said in the other issue, but I can't reproduce this on `vulkan`(...)
I wonder if this has anything to do with the Windows version difference or maybe just Polaris being left out in some driver department by AMD.

> (...)(I don't really see why you would want to disable flip-mode presentation though... kinda defeats the purpose of using `d3d11`).

I mentioned in the previous closed issue why i'm using it, but didn't want to go even more offtopic than i did:

> I would gladly use default d3d11, but that one has a very different problem for me that pushed me towards vulkan, whenever i have a mpv window on fullscreen on a secondary monitor, any explorer actions on my main monitor become stuttery/laggy. Folders opening or maximizing have a noticeable stutter, especially when moving a window close to the border between the two monitors, and whenever there's a maximized window on the primary monitor the problem magically dissapears.

> This doesn't seem to have anything to do with any hardware usage so technically you don't even need to play a video.
With a clean download and without any additional changes to the config, put mpv player on fullscreen on your secondary monitor and then start opening/minimizing->maximizing folders (it can be any window really) from desktop on your primary(...)

https://user-images.githubusercontent.com/77424331/273659339-7c62c557-4ff1-4596-bfc8-3309226c43c1.mp4

>Surprisingly shareX didn't catch the stutter on maximizing of the notepad window, but you can still see what happens when i circle it around close to the border between the monitor that has mpv (without anything playing) on fullscreen, the stutter stops the moment it crosses on top of the mpv player, and then a moment later when another window is maximized on primary there's no stutter at all no matter what i do.

> This is the only reason why i even used vulkan over the default d3d11.

I really have no idea why i'm having this issue. The only options that i found that get rid of it `vo=direct3d` `d3d11-flip=no` `d3d11-exclusive-fs=yes` all introduce negative side effects. Even Vulkan/d3d11-flip have issues where they show a "skeleton window" when going in/out of fullscreen or even cause weird aspect ratio changes trying to fit to the window again. So, this is basically a lesser evil type of situation for me.

@kasper93, if you have any clue why this is happening, i would be glad to have this fixed and not bother in this kind of workarounds. so If you would like to tackle this one, i can add a few additional tidbits from what i remember while trying to diagnose this. 

And for the testing i'm gonna need to wait for it to get merged and use one of the [autobuilders](https://github.com/shinchiro/mpv-winbuild-cmake/releases) since i didn't *yet* get to the point of building them myself.

**Comment by kasper93** [comment] 2023-10-16 10:06
> And for the testing i'm gonna need to wait for it to get merged and use one of the [autobuilders](https://github.com/shinchiro/mpv-winbuild-cmake/releases) since i didn't *yet* get to the point of building them myself.

Use artifacts from CI build.

**Comment by Sneakpeakcss** [comment] 2023-10-16 10:13
> > And for the testing i'm gonna need to wait for it to get merged and use one of the [autobuilders](https://github.com/shinchiro/mpv-winbuild-cmake/releases) since i didn't _yet_ get to the point of building them myself.
> 
> Use artifacts from CI build. https://github.com/mpv-player/mpv/actions/runs/6528738212

Works without issues in both cases, thanks for the fix.

**Comment by kasper93** [comment] 2023-10-16 12:40
> @kasper93, if you have any clue why this is happening, i would be glad to have this fixed and not bother in this kind of workarounds. so If you would like to tackle this one, i can add a few additional tidbits from what i remember while trying to diagnose this.

This is known Windows issue, when you have fullscreen application on second monitor compositor DWM will sync v-sync to this monitor and in general prioritize it, making the other monitor stuttery. Problem is more pronounced if monitors differ with refresh-rate. You can find similar issues with games, all over the internet. I'm not sure exactly what are possible solutions and if it differs between hardware and so on. I don't follow it, just seen similar issues already.

**Comment by Sneakpeakcss** [comment] 2023-10-16 14:21
> This is known Windows issue, when you have fullscreen application on second monitor compositor DWM will sync v-sync to this monitor and in general prioritize it, making the other monitor stuttery. Problem is more pronounced if monitors differ with refresh-rate. You can find similar issues with games, all over the internet. I'm not sure exactly what are possible solutions and if it differs between hardware and so on. I don't follow it, just seen similar issues already.

Yea, some time ago i went through the Windows route trying to find anything that could possibly fix it, i remember switching things like MPO, but without any results. 
Also, there's no other application/game that behaves this way on my system. I've tried with anything that i normally use, and even players like VLC or MPC-HC, and this problem is exclusive only to fullscreen MPV. 

 
> https://bugs.chromium.org/p/chromium/issues/detail?id=1456399

I've seen similar topics like that, but they usually focus on the mentioned difference in refresh rate, while both of my monitors are 60Hz, and the only thing that stutters are explorer animations while everything else stays completely smooth. 

Though this is the first topic i've seen that mentioned anything about "primary monitor", and this animation stutter only happens when MPV is in fullscreen on secondary screen, trying to switch it (fullscreen MPV on primary / explorer animations on secondary) works without issues, and of course making the other one the primary monitor just reverses the behaviour.

**Closed** 2023-10-18 15:22 UTC
Labels: os:win

**Comment by romangitz** [comment] 2024-01-30 13:11
Еще одна ошибка - при  d3d11-flip=no , hwdec=d3d11va   перестает работать HDR.
