### ISSUE TITLE
target-lut doesn't work in profiles

### ISSUE THREAD

**Issue by FoLLgoTT** [mpv-player/mpv#12752] opened 2023-10-26 07:50 UTC
### Important Information

Provide following Information:
- mpv version: nighlty build from 10/20/23
- Platform and Version: Windows 10
- Source of the mpv binary: https://github.com/zhongfly/mpv-winbuild/releases/

### Reproduction steps

Put a target-lut in a profile doesn't apply it. And switiching between profiles (e.g. by hotkey) doesn't do it either. LUT is only applied if it is not inside a profile.

### Expected behavior

Profile applies target-lut.

### Actual behavior

It doesn't.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/13174496/output.txt)

**Comment by llyyr** [comment] 2023-10-26 08:07
Duplicate of your own issue #9782, also probably #11518

**Comment by FoLLgoTT** [comment] 2023-10-26 08:29
Oh, that's really embarrasing. :-D

I close it.

**Closed** 2023-10-26 08:30 UTC
