### ISSUE TITLE
Wrong selection priority for forced video tracks

### ISSUE THREAD

**Issue by Neo-XP** [mpv-player/mpv#11913] opened 2023-07-11 15:23 UTC
### Important Information

For video tracks, mpv always select the forced tracks last and not first, as if the behavior is reversed.

Provide following Information:

- mpv version

mpv-x86_64-v3-20230709-git-ab30028.7z

- Windows Version

Windows 10 Pro 21H2

- Source of the mpv binary

https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/mpv-x86_64-v3-20230709-git-ab30028.7z/download

- If known which version of mpv introduced the problem

This bug was introduced in "mpv-x86_64-v3-20230626-git-945d7c1.7z": https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230626

Build "mpv-x86_64-v3-20230625-git-78285e9.7z" was working as expected: https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/mpv-x86_64-v3-20230625-git-78285e9.7z/download

### Reproduction steps

The issue is reproducible with --no-config:

- add several video tracks in an mkv file
- only set one track as forced track (e.g. with the "Forced display" flag of MKVToolNix )
- play this file with mpv

### Expected behavior

The forced track should be selected.

### Actual behavior

The forced track is never selected.

### Log file

[output_sample_track1_forced.txt](https://github.com/mpv-player/mpv/files/12054193/output_sample_track1_forced.txt)
[output_sample_track2_forced.txt](https://github.com/mpv-player/mpv/files/12054194/output_sample_track2_forced.txt)
[output_sample_track3_forced.txt](https://github.com/mpv-player/mpv/files/12054195/output_sample_track3_forced.txt)

### Sample files

Same file with 3 tracks: 

The video track 1 is forced in this sample: https://www.mediafire.com/file/z6vgwze2hlhba68/sample_track1_forced.mkv/file
But instead of playing track 1, track 2 is selected.

The video track 2 is forced in this sample: https://www.mediafire.com/file/zx3i4tne1t6dnd7/sample_track2_forced.mkv/file
But instead of playing track 2, track 1 is selected.

The video track 3 is forced in this sample: https://www.mediafire.com/file/rbzdukekhmf63ii/sample_track3_forced.mkv/file
But instead of playing track 3, track 1 is selected.

I also tried to force 2 video tracks out of the 3, and it's always the non-forced track that is selected.

I hope this can be fixed.

Thanks!

**Comment by hooke007** [comment] 2023-07-11 16:14
also see https://github.com/mpv-player/mpv/issues/11854

**Comment by Neo-XP** [comment] 2023-07-14 21:56
Logs added

**Comment by Dudemanguy** [comment] 2023-08-09 17:51
To my knowledge, I believe the forced flag is only supposed to be meaningful for subtitle tracks. Or at least that's what the [spec says](https://www.matroska.org/technical/elements.html). mpv still is wrong here because it should be a no-op with the default track selection, not an ignore. VLC appears to always select the forced track, but I don't think that's correct.

**Comment by Dudemanguy** [comment] 2023-08-28 18:49
So as of fbe8f9919428a7ed24a61899bfd85bbb7680e389, mpv will select the first video track in all of these samples. This is correct however as the forced flag is not meaningful for anything besides subtitle tracks. If you want to select a particular video track, you should instead tag it with the default flag instead. Closing this since it is working as intended.

**Closed by Dudemanguy** 2023-08-28 18:49 UTC
Labels: os:win
