### ISSUE TITLE
Got Error When Compile MPV in MacOS

### ISSUE THREAD

**Issue by waihwhh** [mpv-player/mpv#5899] opened 2018-06-08 12:54 UTC
When I compile mpv on MacOS 10.13.5,I got Error as follows:
<pre>
[ 37/461] Compiling DOCS/man/mpv.rst
- install /usr/local/etc/mpv/encoding-profiles.conf (from etc/encoding-profiles.conf)
+ install /usr/local/Cellar/mpv/HEAD-bca5951/share/mpv/applications/mpv.desktop (from etc/mpv.desktop)
+ install /usr/local/Cellar/mpv/HEAD-bca5951/share/mpv/icons/hicolor/16x16/apps/mpv.png (from etc/mpv-icon-8bit-16x16.png)
+ install /usr/local/Cellar/mpv/HEAD-bca5951/share/mpv/icons/hicolor/scalable/apps/mpv.svg (from etc/mpv-gradient.svg)
+ install /usr/local/Cellar/mpv/HEAD-bca5951/share/mpv/icons/hicolor/32x32/apps/mpv.png (from etc/mpv-icon-8bit-32x32.png)
+ install /usr/local/Cellar/mpv/HEAD-bca5951/share/mpv/icons/hicolor/64x64/apps/mpv.png (from etc/mpv-icon-8bit-64x64.png)
+ install /usr/local/Cellar/mpv/HEAD-bca5951/share/mpv/icons/hicolor/symbolic/apps/mpv-symbolic.svg (from etc/mpv-symbolic.svg)
+ install /usr/local/Cellar/mpv/HEAD-bca5951/lib/pkgconfig/mpv.pc (from build/libmpv/mpv.pc)
/private/tmp/mpv-20180608-77422-1bwqgj/video/out/cocoa-cb/video_layer.swift:90:51: error: binary operator '==' cannot be applied to operands of type 'CocoaCB.State' and '_'
        return mpv != nil && cocoaCB.backendState == .init
                             ~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~
/private/tmp/mpv-20180608-77422-1bwqgj/video/out/cocoa-cb/video_layer.swift:90:51: note: expected an argument list of type '(Self, Self)'
        return mpv != nil && cocoaCB.backendState == .init
                                                  ^
/private/tmp/mpv-20180608-77422-1bwqgj/video/out/cocoa_cb_common.swift:126:25: error: type 'CocoaCB.State' has no member 'init'
        backendState = .init
                        ^~~~
/private/tmp/mpv-20180608-77422-1bwqgj/video/out/cocoa_cb_common.swift:480:29: error: binary operator '==' cannot be applied to operands of type 'CocoaCB.State' and '_'
            if backendState == .init {
               ~~~~~~~~~~~~ ^  ~~~~~
/private/tmp/mpv-20180608-77422-1bwqgj/video/out/cocoa_cb_common.swift:480:29: note: expected an argument list of type '(Self, Self)'
            if backendState == .init {
                            ^

Waf: Leaving directory `/private/tmp/mpv-20180608-77422-1bwqgj/build'
Build failed
 -> task in 'osdep/macOS_swift.o osdep/macOS_swift.h osdep/macOS_swift.swiftmodule' failed with exit status 1 (run with -v to display more information)

==> Formula
Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mpv.rb
==> Configuration
</pre>


Can anyone help~~

**Comment by Akemi** [comment] 2018-06-08 15:45
i will have a look when the updates are done. it's probably an incompatibility with a new swift version. what's your swift (`swift -version`) and xcode version (`xcodebuild -version`)? the latter only if you have it installed. otherwise your `./waf configure` output might be helpful for me to reproduce the issue, if i can't right away.

**Comment by Tsukimeizi** [comment] 2018-06-08 18:18
same issue on 10.13.5 (17F77) with Command_Line_Tools_macOS_10.13_for_Xcode_10_Beta

$ swift -version
Apple Swift version 4.2 (swiftlang-1000.0.16.7 clang-1000.10.25.3)
Target: x86_64-apple-darwin17.6.0

$ xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

**Comment by waihwhh** [comment] 2018-06-09 00:16
swift -version
Apple Swift version 4.2 (swiftlang-1000.0.16.7 clang-1000.10.25.3)
Target: x86_64-apple-darwin17.6.0

xcodebuild -version
Xcode 9.4
Build version 9F1027a

**Comment by waihwhh** [comment] 2018-06-09 00:18
@Tsukimeizi 
#xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

U need to do this
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

**Comment by waihwhh** [comment] 2018-06-09 00:40
After I have done this,The Problem Solved!
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

**Comment by Akemi** [comment] 2018-06-09 08:46
yeah it's gone because you use swift 4.1 from xcode 9.4 now. before you used swift 4.2 from the beta command line tools. the issue is not solved you just work around the problem. once xcode 10 is released the issue will reappear.

**Comment by rcombs** [comment] 2018-06-09 17:21
This particular build failure is fixed with this patch:
```
diff --git a/video/out/cocoa-cb/video_layer.swift b/video/out/cocoa-cb/video_layer.swift
index 2e347ba22e..1f639ff954 100644
--- a/video/out/cocoa-cb/video_layer.swift
+++ b/video/out/cocoa-cb/video_layer.swift
@@ -87,7 +87,7 @@ class VideoLayer: CAOpenGLLayer {
         if inLiveResize == false {
             isAsynchronous = false
         }
-        return mpv != nil && cocoaCB.backendState == .init
+        return mpv != nil && cocoaCB.backendState == .`init`
     }
 
     override func draw(inCGLContext ctx: CGLContextObj,
diff --git a/video/out/cocoa_cb_common.swift b/video/out/cocoa_cb_common.swift
index 659f9f84ce..04ec7299ea 100644
--- a/video/out/cocoa_cb_common.swift
+++ b/video/out/cocoa_cb_common.swift
@@ -123,7 +123,7 @@ class CocoaCB: NSObject {
 
         initLightSensor()
         addDisplayReconfigureObserver()
-        backendState = .init
+        backendState = .`init`
     }
 
     func updateWindowSize() {
@@ -477,7 +477,7 @@ class CocoaCB: NSObject {
             }
             shutdown()
         case MPV_EVENT_PROPERTY_CHANGE:
-            if backendState == .init {
+            if backendState == .`init` {
                 handlePropertyChange(event)
             }
         default:
```

Not sure if this should be reported as a Swift compiler bug, though.

**Comment by Akemi** [comment] 2018-06-09 17:32
i would say, probably not. they are just being stricter. swift didn't [like](https://github.com/mpv-player/mpv/blob/master/video/out/cocoa_cb_common.swift#L36) using the "init" keyword anyway (it's reserved). i will probably just rename init to initialised. adding all those apostrophes looks a bit silly and caused more trouble than good.

in the first place i used it init since i was to lazy to type it out.

**Closed** 2018-06-11 22:59 UTC
Labels: osx

**Comment by mlindner** [comment] 2018-07-08 08:41
Seeing this same issue in 10.10 when building with hombrew --HEAD.

**Comment by Akemi** [comment] 2018-07-08 10:32
that's not even remotely the same issue. open a new issue. also add following info:

> what's your swift (swift -version) and xcode version (xcodebuild -version)? the latter only if you have it installed. otherwise your ./waf configure output might be helpful for me to reproduce the issue, if i can't right away.
