### ISSUE TITLE
Warnings with --reset-on-next-file=all (built-in actions?)

### ISSUE THREAD

**Issue by alindt** [mpv-player/mpv#3713] opened 2016-10-23 08:35 UTC
### mpv version and platform

```
$ mpv --version
mpv 0.21.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sun Oct 23 02:59:47 UTC 2016
ffmpeg library versions:
   libavutil       55.33.100
   libavcodec      57.63.103
   libavformat     57.53.100
   libswscale      4.1.100
   libavfilter     6.64.100
   libswresample   2.2.100
ffmpeg version: N-82090-g728ccae
```
```
$  uname -srmo
Linux 4.4.0-38-generic x86_64 GNU/Linux
```

### Reproduction steps
Use "--reset-on-next-file=all" option (command line or mpv.conf)
### Expected behavior
No warnings
### Actual behavior
```
$ mpv --reset-on-next-file=all video.mkv
Playing: video.mkv
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 (*) (ac3)
 (+) Subs  --sid=1 --slang=en 'video.srt' (subrip) (external)
libva info: VA-API version 0.39.2
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
AO: [pulse] 48000Hz 5.1(side) 6ch float
Using hardware decoding (vaapi).
VO: [opengl] 1280x718 vaapi
AV: 00:00:00 / 00:42:17 (0%) A-V:  0.000
Warning: option --vo-defaults is deprecated and might be removed in the future (deprecated, use global options).
Warning: option --heartbeat-cmd is deprecated and might be removed in the future (use Lua scripting instead).
Warning: option --softvol is deprecated and might be removed in the future (no replacement).
Warning: option --ao-defaults is deprecated and might be removed in the future (deprecated, use global options).
Warning: option --oss-device is deprecated and might be removed in the future (use --audio-device instead).
Warning: option --alsa-device is deprecated and might be removed in the future (use --audio-device instead).
Warning: option --pulse-sink is deprecated and might be removed in the future (use --audio-device instead).
mpv: ../player/command.c:319: mp_on_set_option: Assertion `type.type == co->opt->type' failed.
Aborted
$
```

**Comment by wiiaboo** [comment] 2016-10-23 12:04
Duplicate of #3708 and already fixed in https://github.com/mpv-player/mpv/commit/bf5c4c42fa4366b707234e8feb5036ca3c03f056.

**Closed by wiiaboo** 2016-10-23 12:04 UTC
