### ISSUE TITLE
MPV crashes when opening video URL's

### ISSUE THREAD

**Issue by tr1s** [mpv-player/mpv#5380] opened 2018-01-10 23:35 UTC
Easily my favourite video player, just found it last week. Just one issue, I can't open any video links. I have the latest update from here -->

<img width="997" alt="screen shot 2018-01-10 at 6 31 48 pm" src="https://user-images.githubusercontent.com/19172250/34801116-df193fc2-f634-11e7-9425-be11757e416a.png">

I've tried youtube and vimeo so far, but the app crashes immediately after. Is this expected behaviour?

Running macOS High Sierra 10.13.2 (latest)

**Comment by kevmitch** [comment] 2018-01-10 23:50
We're going to need logs, reproduction scenarios, etc as requested in the issue template to have any idea what's going on. Doesn't macos also print a backtrace to the console on crashes? Either way a backtrace would be immensely helpful.

**Comment by orbea** [comment] 2018-01-10 23:57
Not sure if this is the same issue, but I am getting this with bandcamp now. Youtube-dl by itself works.
```
$ mpv https://avantgardemusic.bandcamp.com/album/h-llenzwang-chronicles-of-perdition
Playing: https://avantgardemusic.bandcamp.com/album/h-llenzwang-chronicles-of-perdition
[ytdl_hook] 
[ytdl_hook] stack traceback:
[ytdl_hook] 	@ytdl_hook.lua:479: in function 'fn'
[ytdl_hook] 	mp.defaults:519: in function 'handler'
[ytdl_hook] 	mp.defaults:339: in function 'handler'
[ytdl_hook] 	mp.defaults:459: in function 'call_event_handlers'
[ytdl_hook] 	mp.defaults:496: in function 'dispatch_events'
[ytdl_hook] 	mp.defaults:452: in function <mp.defaults:451>
[ytdl_hook] 	[C]: ?
[ytdl_hook] 	[C]: ?
[ytdl_hook] Lua error: @ytdl_hook.lua:479: attempt to index local 'site' (a nil value)
Failed to recognize file format.
```

**Comment by orbea** [comment] 2018-01-11 00:56
Its fixed here, although I'm still not sure this was the same issue...
I presume this commit fixed it. https://github.com/mpv-player/mpv/commit/154ff98128f38ff9f7ac2139013e80004b2aeb8e

**Comment by tr1s** [comment] 2018-01-11 06:07
@kevmitch How do I get logs, backtraces, and reproduction scenarios? I wanted to provide info from the template but I didn't understand anything. Do I crash mpv and then run some code? I'm a jr dev so I would appreciate the explanation and help, thanks!

**Comment by CounterPillow** [comment] 2018-01-11 07:14
Run mpv from a terminal and check the output, or pass the parameter `--log-file=yourfilehere.txt` to creare a verbose log file with timestamps.

**Comment by tr1s** [comment] 2018-01-11 07:22
@CounterPillow I opened mpv by typing `open -a mpv`.. but I don't know what I'm supposed to do from there. How do I check the output? Where am I passing this parameter?

**Comment by Jj0YzL5nvJ** [comment] 2018-01-11 08:55
Open a Terminal and type: `mpv --log-file=yourfilehere.txt https://youtu.be/-Vl4rpZVA6I`

**Comment by Akemi** [comment] 2018-01-11 09:58
if your mpv binary is not in the $PATH, you have no clue where the binary is and you absolutely must use `open`, then you can also do:
 `open -a mpv --args "--log-file=~/Desktop/mpv.log" YOUR_URL`
creating a log file on your desktop.

**Comment by tr1s** [comment] 2018-01-11 20:03
@Jj0YzL5nvJ `command not found`

@Akemi That works. Here's my log. Does this help explain why MPV is crashing when I drop any URL on it?

[mpv.log](https://github.com/mpv-player/mpv/files/1623957/mpv.log)

**Comment by Akemi** [comment] 2018-01-11 22:52
i don't see it crash. it just exits normally because it can't play the URL. might be related to #5382 and also might already be fixed in master. @wiiaboo might know more.

**Comment by tr1s** [comment] 2018-01-11 22:59
@Akemi I guess that's a good point, macOS didn't actually show any crash log after, it just felt like it quit the application upon throwing the link in MPV. I just assumed it was crashing.

I have the latest version 0.28.0, is that the master? I assumed downloading the master files is for contributing, not actually using MPV. I don't see any applications in there. Where do I go from here?

@wiiaboo do you have some more insight? I only tried YouTube and Vimeo, cause I feel like that's what most people would use it for, to avoid ads on YouTube.

**Comment by wiiaboo** [comment] 2018-01-11 23:16
ytdl_hook usage shouldn't crash mpv at all, so I doubt it's related to that.

**Comment by Akemi** [comment] 2018-01-11 23:59
@tr1s you have to build it yourself or via brew with `--HEAD`.
@wiiaboo it doesn't actually crash though. there is nothing in the log that indicates a crash.

**Comment by wiiaboo** [comment] 2018-01-12 00:07
Yeah, seems to be the same as #5382 where the return code is probably non-zero for some reason, but when running youtube-dl on its own it works fine.

**Comment by tr1s** [comment] 2018-01-12 00:09
@Akemi @wiiaboo just to reiterate. I open a URL, or drag and drop, and I can see the link at the bottom of mpv for about 3 seconds (without anything playing), and then MPV just disappears. It's not in the macOS tray, and macOS does not indicate that the application crashed in any way. It's just gone.

Are you saying that this is fixed in the master, and that I need to install HomeBrew just to get this working? How come there's no updated zip download? Is 0.28.0 not the the most updated app?

**Comment by wiiaboo** [comment] 2018-01-12 00:12
It's not. It's 103 commits older than git master as of now.
What's your youtube-dl version? Run `youtube-dl --version`.

**Comment by tr1s** [comment] 2018-01-12 00:17
@wiiaboo `command not found.` What else am I supposed to type?

Is it normal behaviour for the master zip to be so far behind? Is HomeBrew something I need to look into in order to be actually up to date with mpv consistently?

You're underestimating my lack of knowledge in this area, but I appreciate the help I want to figure this out.

**Comment by wiiaboo** [comment] 2018-01-12 00:20
> Is it normal behaviour for the master zip to be so far behind? Is HomeBrew something I need to look into in order to be actually up to date with mpv consistently?

It would help.

> @wiiaboo `command not found.` What else am I supposed to type?

Well, wherever your youtube-dl executable resides, get me its version, please.

**Comment by tr1s** [comment] 2018-01-12 00:25
@wiiaboo I have no idea what that is. Is this supposed to be common knowledge to have this downloaded after I download MPV? Or is it bundled with MPV? I need some more information.

**Comment by wiiaboo** [comment] 2018-01-12 00:45
It's something you need installed in order for mpv to work with Youtube's and other non-direct URLs.

**Closed by wiiaboo** 2018-01-12 00:45 UTC
Labels: ignored issue template, info-needed

**Comment by tr1s** [comment] 2018-01-12 00:51
Yeah that was it, downloaded HomeBrew and then youtube-dl. It works. I would just assume that information would be in the main page of the docs.
