### ISSUE TITLE
pipewire: next audio file in queue is not played if sample rate differs

### ISSUE THREAD

**Issue by KookiesGH** [mpv-player/mpv#10441] opened 2022-07-23 22:07 UTC
### Important Information

Provide following Information:
- mpv version: mpv-git 0.34.0_376_g70fa9502f3-1 (built without X11)
- Linux Distribution and Version: Arch Linux N/A
- Source of the mpv binary: built from sources
- If known which version of mpv introduced the problem: Unknown
- Window Manager and version: sway 1.7
- GPU driver and version: Mesa 22.1.3
- Possible screenshot or video of visual glitches: N/A

### Reproduction steps

Play 2 or more audio files of different formats / containers (in my case, mp3 and opus webm) with mpv, using the ao=pipewire flag.

### Expected behavior
mpv continues to the next song in the queue without interruption, regardless of music container

### Actual behavior
mpv fails to continue to the next song in the queue if its container (mp3 -> webm & vice-versa, for example) is different from the previous song

### Log file

[pipewire-playlist-mpv.txt](https://github.com/mpv-player/mpv/files/9174736/pipewire-playlist-mpv.txt)
This logfile was generated with my normal config, but the issue persists with --no-config as well.

**Comment by philipl** [comment] 2022-07-23 23:33
Have you explicitly tried:
- The same files with a different `ao`?
- Playing files with the same sample rate? In your example here one is 44.1kHz and one is 48kHz

My trivial attempt to reproduce using two 44.1kHz files in different formats played fine, as did another attempt to play different sample rates in different formats.

**Comment by KookiesGH** [comment] 2022-07-26 00:15
I've performed the test again using --no-config, switching between the `pipewire` and `pulse` outputs; the issue still occurs under `pipewire`, but the files play fine under `pulse`. The issue seems to be with the sample rate, as converting the opus file to mp3 yielded the same results. I'm not sure why you are not able to reproduce the issue; one thing to note is that my files were downloaded with yt-dlp, one from Soundcloud and the other from YouTube. 

I've uploaded 2 logs with the different scenarios. The first one is using the `pulse` output, the second is using the `pipewire` output. My mpv version is now `0.34.0_384_gd2467f61be-1`.
[same-format-different-sample.txt](https://github.com/mpv-player/mpv/files/9185558/same-format-different-sample.txt)
[same-format-different-sample_pipewire.txt](https://github.com/mpv-player/mpv/files/9185559/same-format-different-sample_pipewire.txt)

**Comment by llyyr** [comment] 2022-07-26 05:49
Can you try 0.34.1 or git HEAD to see if you can reproduce the issue there?

**Comment by philipl** [comment] 2022-07-26 16:41
What version of pipewire are you using? I have 0.3.48 here and as I said, I cannot reproduce.

@t-8ch any thoughts?

**Comment by t-8ch** [comment] 2022-07-26 17:27
Also works for me with pipewire 0.3.56.

@KookiesGH 

Can you try to following steps:
```
$ sox -n -e float -r 44100 44k.wav synth 5 sine 500
$ sox -n -e float -r 48000 48k.wav synth 5 sine 500
$ mpv 44k.wav 48k.wav
```

Does it exhibit the same issue? (So we have identical test data)

Also I think there has been a fair amount of rework of samplerate handling in pipewire in the last few releases.
Maybe you got a broken one. Your version of pipewire would be very useful.

**Comment by philipl** [comment] 2022-07-26 18:34
@KookiesGH  Can you get us a repro case with files you can attach here?

**Comment by KookiesGH** [comment] 2022-07-26 18:51
Sure thing. I've attached an archive containing (presumably) royalty-free music which exhibits the behavior. My logs are also included, but I will attach them separately just in case.

[mpv-pipewire-repro.tar.gz](https://github.com/mpv-player/mpv/files/9192484/mpv-pipewire-repro.tar.gz)

[no-config.txt](https://github.com/mpv-player/mpv/files/9192530/no-config.txt)
[pipewire.txt](https://github.com/mpv-player/mpv/files/9192531/pipewire.txt)

**Comment by christoph-heinrich** [comment] 2022-07-26 21:45
Can reproduce. All i did was download that archive, extract to folder, run `mpv --no-config --ao=pipewire <path_to_folder>` and seek forward close to the end (two times arrow up should do it) and let it finish playing. This does not happen when I manually go to the next file using enter or seeking beyond the end.

```
[file] This is a directory - adding to playlist.

Playing: <path_to_folder>/Corporate Uplifting (DOWNLOAD -SEE DESCRIPTION) Royalty Free Music _ Business Motivation Background [855009658].mp3
(+) Audio --aid=1 (mp3 2ch 44100Hz)
AO: [pipewire] 44100Hz stereo 2ch floatp
A: 00:02:07 / 00:02:08 (100%)

Playing: <path_to_folder>/Mozart - Lacrimosa [k1-TrAvp_xs].webm
(+) Audio --aid=1 --alang=ita (*) (opus 2ch 48000Hz)
A: 00:02:07 / 00:02:08 (100%)
```
Note how the playback time stays the same after opening the next file.
Seeking or pause/unpause remedies that problem.

**Comment by t-8ch** [comment] 2022-07-26 22:18
Now I can also reproduce it.
It works when I use `--cache=yes --cache-secs=2` (or a larger value)

**Comment by t-8ch** [comment] 2022-07-26 22:36
Probably a duplicate of #10018.
Pull-based AOs seem to run into various issues.
I meant to rewrite the AO as a push-based on but did not yet find the time.

**Comment by philipl** [comment] 2022-07-26 22:55
Yeah. Looks like the same thing, Will close as a dupe.

**Closed by philipl** 2022-07-26 22:55 UTC
Labels: os:linux
