### ISSUE TITLE
mpv to show currently active keybindings in OSD

### ISSUE THREAD

**Issue by BurhanDanger** [mpv-player/mpv#4956] opened 2017-10-05 10:46 UTC
Is there a way that mpv will show active keybindings from input.conf as osd message. It's hard to remember rarely used keybindings. If there's a way to show them as osd , it'll be easier to see keybindings without opening input.conf

**Comment by Hrxn** [comment] 2017-10-06 04:26
mpv --input-test --force-window --idle

**Comment by BurhanDanger** [comment] 2017-10-06 05:42
I wanted list of all enabled keybindings.
> mpv --input-test --force-window --idle
May not be correct at times. Possibly for no-input-default-bindings in my mpv.conf

**Comment by Hrxn** [comment] 2017-10-06 05:49
Well, you could use the whole content of `input.conf` together with `show-text` or something..

With some unconeventional formatting, presumably. This is not a text editor. But you could probably bend something together with ASS codes, maybe.

**Comment by negativeions** [comment] 2017-10-06 06:04
or have a GUI for it like normal people.

**Comment by BurhanDanger** [comment] 2017-10-06 06:23
> or have a GUI for it like normal people.

I'm not sure what you mean

**Comment by negativeions** [comment] 2017-10-06 06:28
Of course you don't, if you're not typing the command then it's for babies, right? A GUI, GRAPHICAL USER INTERFACE? Tatoo it on your brain sometime. You know, so that humans can use this crap properly and see and edit hotkeys like humans.

**Comment by BurhanDanger** [comment] 2017-10-06 06:29
> you could use the whole content of input.conf together with show-text or something

I thought about that. It's not efficient. I have edit different portions separately.

**Comment by BurhanDanger** [comment] 2017-10-06 06:30
@negativeions mpv doesn't come with an official gui.

**Comment by negativeions** [comment] 2017-10-06 06:31
@BurhanDanger yes I know that. My point is it should.

**Comment by CounterPillow** [comment] 2017-10-06 12:17
@negativeions maybe a player like VLC is more the right choice for you.

Your luser opinion is not gospel.

**Comment by negativeions** [comment] 2017-10-07 04:19
My opinion on this matter is gospel. To normal people. Who actually use software. Not terminal faggots.

**Comment by lachs0r** [comment] 2017-10-07 04:38
@negativeions

HEY

MY OPINION > YOUR OPINION

AND I THINK YOU SHOULD GO SUCK A COCK

**Comment by lachs0r** [comment] 2017-10-07 04:38
Also, duplicate of #2590.

**Closed by lachs0r** 2017-10-07 04:38 UTC

**Comment by rr-** [comment] 2017-10-07 05:01
@negativeions use bomi or VLC and be done with it. Why the butthurt? Why do you even care?

**Comment by negativeions** [comment] 2017-10-07 17:44
I care because there is literally NO good video player for macOS and it's infuriating. VLC sucks even worse. For over two months ASS subtitles have just not worked. Some of their contributors need to be banned for for such ridiculous regressions. There is no Bomi for macOS. IINA is buggy. I'm at my wits end.

**Comment by CounterPillow** [comment] 2017-10-07 17:51
>if someone is willing to do a GUI, let 'em

that's why there are many GUI frontends on the wiki page to choose from.

Alternatively, maybe you should learn how to use a computer, you massive pleb.

**Comment by negativeions** [comment] 2017-10-07 17:54
You're the perfect example of a piece of shit dev with archaic dev philosophies. Learn to use a computer. Do you I need to learn how to operate a film/digital projector when I go to the theatre to watch a movie? Do I need to learn how to use dentist tools when I want to get my teeth checked? You dumb fuck. If you ever worked for me, I'd not only fire you, but I'd kick the shit out of you in the parking lot.

**Comment by CounterPillow** [comment] 2017-10-07 17:55
lol ok fight me 1v1 bitch I'll sock you in the mouth

**Comment by Hrxn** [comment] 2017-10-07 17:58
Okay, y'all need to cut the kindergarten crap in here..

**Comment by negativeions** [comment] 2017-10-07 17:58
macOS is buggy garbage? And windows is any better?

**Comment by garoto** [comment] 2017-10-07 17:59
Well, it seems by per using this issue tracker that Windows users are much less entitled, so there's that.

**Comment by negativeions** [comment] 2017-10-07 18:00
@garoto I guess you didn't read my post. There's no good player on mac.

**Comment by CounterPillow** [comment] 2017-10-07 18:00
but mpv is a good player :(

**Comment by garoto** [comment] 2017-10-07 18:03
My point being that we Windows users, know it's garbage. It's public knowledge for a very long time.

**Comment by negativeions** [comment] 2017-10-07 18:03
urgh.... ok, I double click on a file, by default the video is larger than the actual screen.. subtitles show too soon. Shortcut to increase delay? no clue. Click on the menu item 10x. How do I set preferences? Oh, forgot no GUi, you have to know archaic codes no nobody cares about. This isn't anything to do with the OS, it's retarded design.

**Comment by garoto** [comment] 2017-10-07 18:05
It's a fricking ASCII text file. The docs are pretty much excellent. You need to put a little bit more effort in it.

**Comment by Hrxn** [comment] 2017-10-07 18:06
> macOS is buggy garbage? And windows is any better?

Completely beside the point.

Okay, I give you that this is something the average end user usually can't know, so I'll explain it here in a concise variant:

The problem media players in general and mpv specifically have with macOS, and that is currently being worked on by many hard-working volunteers on this project on here, is that Apple decided to ditch their support for OpenGL, which means that users on macOS are stuck with an almost ancient version of that API. Which sucks, because it makes cross-platform support a really nasty pain in the ass..

**Comment by negativeions** [comment] 2017-10-07 18:06
Whatever, I don't have time for this, I just want to watch something in my spare time. Hopefully mpv gets better in the future and considers a GUI. That is all.

**Comment by negativeions** [comment] 2017-10-07 18:07
@Hrxn I agree, apple is idiots for doing this.

**Comment by CounterPillow** [comment] 2017-10-07 18:09
HALP HOW DO I USE ME MAC IT NO WORK

**Comment by Hrxn** [comment] 2017-10-07 18:11
Working hard on that "toxicity" in tech etc. pp. 🙄

**Comment by negativeions** [comment] 2017-10-07 18:16
You people just don't get it. How about your toxicity of not giving a shit about the end user experience? Look, whatever, the problems I mentioned have nothing to do with OpenGL. And CounterPillow is just trolling now. You speak of toxicity, look in the mirror.

**Comment by Hrxn** [comment] 2017-10-07 18:18
Hey, I was just trying to help..

**Comment by garoto** [comment] 2017-10-07 18:28
The dude arrived at the issue tracker with a very clear goal on his mind, judging by all his opened issues history. He never asked for help in resolving the hurdles he was facing as a end-user in a sensible manner. His whole thing seems to be the lack of a fricking GUI, wth really.

**Comment by Artoriuz** [comment] 2017-10-07 18:42
https://i.imgur.com/LNGJf4u.png

Not hard.

**Comment by jgreco** [comment] 2017-10-07 19:32
> Do you need to learn how to operate a film/digital projector when I go to the theatre to watch a movie? Do I need to learn how to use dentist tools when I want to get my teeth checked?

Maybe you should pay somebody to use mpv for you, like you do when you go to a movie theater or the dentist.

>You dumb fuck.

**Comment by garoto** [comment] 2017-10-07 19:57
I can be a mpv chauffeur, cheap hourly rates!

**Comment by rr-** [comment] 2017-10-07 20:30
@negativeions 
For me mpv is user friendly precisely because it has no GUI. No, I am serious.
I have one document which describes how to do everything, one file with config, one file with keybindings. I can edit the files however I want (gedit, vim, notepad.exe). I can search the documentation however I want. With GUI like mpc-hc I'd have to search through many tabs and checkboxes aimlessly until I find the option that interests me. That's not going to work in case of mpv because of sheer amount of its configuration parameters. (At very least you'd get a blob such as Miranda IM, whose GUI was a complete mess and I always lost half an hour there whenever I wanted to change something.)

For developers, it also means they can focus on important things, not needing to invest their time and energy into integrating UI toolkits such as GTK or QT / implementing hundreds of UI controls. Instead, they offer a well-designed config mechanism. They can also just offer the most important stuff (volume control, seek bar etc.) and OSD with libass.

I believe it's a very elegant solution. If mpv was to get menu bars and windows, I'd see them only as bloatware and be painfully aware how that GUI can't ever be capable of controlling even half of the config parameters due to their number.

I understand mpv is not for everyone, but really, why shitpost here? I seriously urge you to look something that fits your expectations more - be it VLC or one of the aforementioned frontends on the wiki (I didn't look through them). I don't know why you're saying VLC is so bad. mpv isn't some magical video player that will magically render your 240p video in 1080p quality. At its core, it's just an interface to your video card's OpenGL, just like VLC is. So I really don't know why you're saying "I want to use mpv but I can't". The reason why "you can't" use it is because you're not appreciating mpv's biggest feature, which is its simplicity of config, its simplicity of design. But if you dismiss that feature, what's left then? Why would *you* want to use it?

**Comment by garoto** [comment] 2017-10-07 20:45
@rr- post brings me back to 1997 when I bought my first Linux book and learned that pretty much all settings for programs in the *nix world were made by editing ASCII text files. You run a website that serves its contents with Apache and you need to change your a simple setting? Just edit you apache.conf file. A simple ASCII text files.

I was gobsmacked for life. It wasn't long before I read in the same book about RFCs...

**Comment by haasn** [comment] 2017-10-07 21:03
I have no idea what's going on in this thread; but if you want mpv to absolutely never implement a feature ever, this is the best way of accomplishing that.

**Comment by lachs0r** [comment] 2017-10-07 21:51
To be fair, this user interface concept is alien to users of operating systems like Windows or macOS. Those platforms are not first-class citizens to mpv, and likely never will be. Sure it might work just as well as on *nix, but it blatantly ignores platform user interface guidelines. Writing a GUI around mpv is not that hard, but there are still very, very few people with the skills and incentive to do so, and they’re clearly not part of the core mpv development team—which probably couldn’t design a friendly enough, tested UI to save their lives because they simply like mpv the way it is, so let’s leave that to people who would actually use such a thing.

**Comment by wm4** [comment] 2017-10-09 13:20
On a general note, we like to leave GUIs to other projects (which can embed libmpv) because we don't want to depend on big GUI frameworks, or deal with them, or even handle general UI programming issues.
