### ISSUE TITLE
Playlist fails to automatically play next file in sequence - sometimes.

### ISSUE THREAD

**Issue by therube** [mpv-player/mpv#8904] opened 2021-06-08 19:16 UTC
Playlist fails to automatically play next file in sequence - sometimes.

- mpv version
0.33
- Platform and Version
Win7 x64
- Source of the mpv binary
https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20210606-git-4989ccb.7z/download

> Try to reproduce your issue with --no-config first
Still fails.
mpv --no-config ..\..\triple2.m3u

> Describe the reproduction steps as precise as possible.
Playing a set of AUDIO files, from playlist, sometimes, the song fails to automatically start playback of the next song in sequence.

### Expected behavior
All the songs should play, in sequence, one after another.

### Actual behavior
Songs play, but at some point, you are apt to run into a situation where the "next" song fails to automatically start its playback.

### Log file
https://0x0.st/-_5m.LOG

### Sample files
https://0x0.st/-_5S.ZIP
Included are a playlist, the 3 songs in that playlist, some screenshots, & a readme.TXT.
readme deals with both mpv & mpv.net (a GUI front-end to mpv).
Both mpv & mpv.net fail with 0.33 version of mpv/mpv-1.dll.

### More
Thread at doom9, https://forum.doom9.org/showthread.php?p=1944469#post1944469
mpv 0.32 looks to work properly.
mpv 0.33 fails. not always, not with all files, but it will fail, at some point.
(Files provided should provide a fail condition. Does for me.)
I don't know, particularly, if any similar condition exists with video files?
Note that once you start play of the playlist, you do not want to interact with the player (or mpv.com).
Load the playlist, hit play (if necessary), then just let it do its thing.
(All audio files are < 1 min. each.)
What should happen, is that 1st file plays, 2nd file, not quit sure, but I believe it loads, & (it does) show:
A: 00:00:22 / 00:00:22 (99%), which I take to mean it has "played" fully ? where in fact it has not played at all.
Without some interaction, mouse movement or focus change & back or keystroke... it just sits there.
Once interaction is effected, at that point, playback (again) begins.

**Comment by therube** [comment] 2021-06-08 19:38
Oh, the log I posted above must have been through the fail point.
I had run all types of scenarios...
Here is a (should be) complete log, from a run prior, https://0x0.st/-_5x.LOG3.

**Comment by EzeKees** [comment] 2021-06-09 19:09
I think it may be due to [find_files]. Did you try disabling file search?

**Comment by therube** [comment] 2021-06-09 19:27
I'd be glad to try.
Could you give me a hint as to how to do it?
Neither https://mpv.io/manual/master/ nor mpv --help are cluing me in?

/If/ it is, --autoload-files=no, then that did not help.

**Comment by therube** [comment] 2021-06-09 19:33
Looks like I guessed correctly, but no, setting, --autoload-files=no, did not help.

**Comment by garoto** [comment] 2021-06-09 21:36
Can reproduce and reverting fce994bdc4 seems to fix it for me.

@therube give these binaries a try: https://0x0.st/-Li0.7z

**Comment by Dudemanguy** [comment] 2021-06-09 22:13
Is it not a wasapi issue? I mean I play playlists of audio files everyday (alsa) and haven't encountered this.

**Comment by garoto** [comment] 2021-06-09 22:43
> Is it not a wasapi issue? [...]

It could be, it could also be the way the mp3s provided in the OP were cut and their bitrate or samplerate could also play a role, I don't know. My troubleshooting abilities only go so far. All I know is that if I build mpv from master with a ffmpeg build from a month ago I can reproduce using the provided files, and reverting commit fce994bdc4 and building again it all works.

Here's a video that shows the behavior described and how altering the volume after each "stuck state" succesfully resumes playback: https://0x0.st/-L-p.mkv

**Comment by Dudemanguy** [comment] 2021-06-09 23:09
OP's samples work normally for me. I trust wm4 knew what he was doing by moving that function around, so I'm inclined to think this has something to do with wasapi.

**Comment by garoto** [comment] 2021-06-09 23:37
`[...] I'm fairly sure this is wrong, and my next commit should fix it
properly. I'm not really sure, though [...]
`

**Comment by Dudemanguy** [comment] 2021-06-09 23:59
Right, he reverted my commit and then followed it up with a new one (https://github.com/mpv-player/mpv/commit/3f7d3d5804ef3dd76eb1aa76210619f96244920d). I don't think reverting the revert is the answer. I think fixing whatever is up with wasapi is the correct approach unless someone can show this happens on another AO.

**Comment by garoto** [comment] 2021-06-10 00:44
I never suggested "reverting the revert" was the only and one proper solution. Just relaying my simple-man observations.

**Comment by jmdavis** [comment] 2021-06-12 13:32
I sometimes see behavior like this on FreeBSD when just giving mpv a list of files to play on the command line - usually with videos that I downloaded from youtube (some where I downloaded both the video and audio and some where I downloaded just the audio). I've also seen it by simply telling mpv to loop a video. However, I don't think I've ever seen it when passing mpv directories from my collection of .flac files which I ripped from CDs (certainly, if I do see it with them, it's rare enough that I don't remember it happening).

So, unless this is a separate issue from what I'm seeing but with similar symptoms, I would guess that this doesn't have anything to do with playlists specifically (just mpv having issues when moving to the next file in a list), and I doubt that it has anything to do with wasapi, since a quick search on that shows it to be a Windows thing.

That being said, I have not been able to reproduce the issue on FreeBSD with mpv 0.33.1 with either the playlist here or by playing the files on their own. So, I have no clue whether I'm actually seeing the same bug - just that it sure sounds like the same bug.

**Comment by kelciour** [comment] 2021-06-14 15:45
Maybe https://github.com/mpv-player/mpv/issues/8898 will be relevant here since I can reproduce the issue with the files provided by OP on Windows, for me it always stops after the first file but not the second, and adding `--gapless-audio=no` as a workaround seems to fix it for me.

**Comment by therube** [comment] 2021-06-15 15:35
> --gapless-audio=no as a workaround seems to fix it for me

Confirmed.
(As a workaround.)
(Confirmed on my simple playlist.)

**Comment by therube** [comment] 2021-06-15 15:46
--gapless-audio=yes, also looks to work.
(but the book says yes could result in lower sound quality)

Was there a change in --gapless-audio such that =weak, the default setting, is (now) causing issues?

(I'll have to throw =yes or =no to my extended playlist & see how that goes.)

**Comment by therube** [comment] 2021-06-15 15:49
> Was there a change in --gapless-audio such that =weak, the default setting, is (now) causing issues?

Seems not directly, at least not with the string "gap" in the description.
https://git.srsfckn.biz/mpv/log/?qt=range&q=v0.32.0..v0.33.0

**Comment by stax76** [comment] 2022-06-20 13:14
Here it hangs exactly every time when the sampling rate changes from the previous MP3 file having sampling rate 44.100 and the next MP3 file having sampling rate 48.000, what fixes it is:

`audio-samplerate=48000`

or 

`gapless-audio=no`

**Closed** 2022-08-09 17:31 UTC
