### ISSUE TITLE
gpu-next: glsl-shader: Tried binding unknown texture 'LOWRES'!

### ISSUE THREAD

**Issue by Silver-Fullbuster** [mpv-player/mpv#10246] opened 2022-05-29 14:04 UTC
### Important Information

Provide following Information:
- mpv version
```
mpv 0.34.0-302-gafe29026ed Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Sun May 29 12:41:10 2022
FFmpeg library versions:
   libavutil       57.25.100
   libavcodec      59.32.101
   libavformat     59.24.100
   libswscale      6.6.100
   libavfilter     8.39.100
   libswresample   4.6.100
FFmpeg version: git-2022-05-28-fab9130c
```
- Windows Version: Win 10 64-bit 21H2 Build 19044.1706
- Source of the mpv binary - Shinchiro Builds (Weekly release)

### Reproduction steps

`mpv --no-config --glsl-shader=D:\SSimSuperRes.glsl --vo=gpu-next --log-file=D:\mpv.log <480pvideofile>`
Use a 480p video on a 1080p screen (My setup, probably affects more than that)

### Expected behavior

Video plays without errors and the shaders working

### Actual behavior

An error shows up in log:
```
[vo/gpu-next] Tried binding unknown texture 'LOWRES'!
[vo/gpu-next] Failed executing hook, disabling
```
and GLSL shaders do not work

## Shader File

[SSimSuperRes.glsl.txt](https://github.com/mpv-player/mpv/files/8793458/SSimSuperRes.glsl.txt)
Can also be found here: https://gist.github.com/igv/2364ffa6e81540f29cb7ab4c9bc05b6b

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/8793470/mpv.log)

**Comment by igv** [comment] 2022-05-29 18:02
Looks like [the same bug](https://github.com/mpv-player/mpv/issues/9892#issuecomment-1050747181). Try to enable the shader with a key bind after resizing the player
`b cycle-values glsl-shaders "D:\SSimSuperRes.glsl" ""` (in input.conf)

**Comment by zhongfly** [comment] 2022-11-03 23:40
Same problem,this bug should be fixed.
Can you look at the bug, @haasn ?

**Comment by haasn** [comment] 2022-11-04 16:39
All of these examples so far work fine on my end. What could possibly be different for you?

Could it be an anamorphic source, maybe? I noticed that `SSimSuperRes` uses inconsistent conditionals - it checks the weight in one pass and the height in another, so for anamorphic sources those could evaluate differently...

**Comment by zhongfly** [comment] 2022-11-04 16:59
> All of these examples so far work fine on my end. What could possibly be different for you?
> 
> Could it be an anamorphic source, maybe? I noticed that `SSimSuperRes` uses inconsistent conditionals - it checks the weight in one pass and the height in another, so for anamorphic sources those could evaluate differently...

I find it is related to scale.
If I play a 1920*1080 video(`mpv --no-config --vo=gpu-next --glsl-shader=AMD-FSR.glsl --log-file=mpv.log <video file>`),works fine when diplay as 1920*1080.Then I scale the mpv widows to 1914x1077(or any value <= original resolution),problem happened.
[mpv.log](https://github.com/mpv-player/mpv/files/9940542/mpv.log)

**Comment by igv** [comment] 2022-11-04 17:04
SSSR is most likely due to anamorphic source, but not FSR. The RCAS pass doesn't have any conditions - it depends on the EASU pass.

> works fine when diplay as 1920*1080

No it doesn't.

**Comment by haasn** [comment] 2022-11-04 17:08
Oh, yeah, I see - basically what's happening is that the execution gets disabled by the `//!WHEN` conditional, and then the next sage (which tries using a texture that never got written) fails executing.

The reason it only errors in `--vo=gpu-next` is because `--vo=gpu` apparently never considered this a bug:

```c
        struct image bind_img;
        if (!saved_img_find(p, bind_name, &bind_img)) {
            // Clean up texture bindings and move on to the next hook
            MP_TRACE(p, "Skipping hook on %s due to no texture named %s.\n",
                     name, bind_name);
            p->num_pass_imgs -= t;
            return false;
        }
```

but in `--vo=gpu-next` this is treated as an error state.

I could change the logic to match the mpv code, but honestly, I think it would almost be more appropriate to adjust FSR to mirror the condition onto both passes.

**Comment by haasn** [comment] 2022-11-04 17:19
> I could change the logic to match the mpv code, but honestly, I think it would almost be more appropriate to adjust FSR to mirror the condition onto both passes.

I submitted a PR for this here: https://code.videolan.org/videolan/libplacebo/-/merge_requests/324

**Comment by zhongfly** [comment] 2022-11-05 05:47
> mpv --no-config --vo=gpu-next --glsl-shader=AMD-FSR.glsl --log-file=mpv.log

Thanks for your work.
I test with AMD-FSR.glsl again but get new error:
```
[   0.202][v][vo/gpu-next] Window size: 3840x2160 (Borders: l=0 t=0 r=0 b=0)
[   0.202][v][vo/gpu-next] Video source: 1920x1080 (1:1)
[   0.202][v][vo/gpu-next] Video display: (0, 0) 1920x1080 -> (0, 0) 3840x2160
[   0.202][v][vo/gpu-next] Video scale: 2.000000/2.000000
[   0.202][v][vo/gpu-next] OSD borders: l=0 t=0 r=0 b=0
[   0.202][v][vo/gpu-next] Video borders: l=0 t=0 r=0 b=0
[   0.204][v][vo/gpu-next] Window size: 2854x1605 (Borders: l=0 t=0 r=0 b=0)
[   0.204][v][vo/gpu-next] Video source: 1920x1080 (1:1)
[   0.204][v][vo/gpu-next] Video display: (0, 0) 1920x1080 -> (0, 0) 2854x1605
[   0.204][v][vo/gpu-next] Video scale: 1.486458/1.486111
[   0.204][v][vo/gpu-next] OSD borders: l=0 t=0 r=0 b=0
[   0.204][v][vo/gpu-next] Video borders: l=0 t=0 r=0 b=0
[   0.204][d][vo/gpu-next/libplacebo] (Re)creating 1920x1080x0 texture with format r16
[   0.301][d][vo/gpu-next/libplacebo] (Re)creating 960x540x0 texture with format r16
[   0.308][d][vo/gpu-next/libplacebo] (Re)creating 960x540x0 texture with format r16
[   0.309][d][vo/gpu-next/libplacebo] (Re)creating 2854x1605x0 texture with format rgba16hf
[   0.311][e][vo/gpu-next/libplacebo] Trying to dispatch shader with incompatible signature!
[   0.311][e][vo/gpu-next/libplacebo] Failed executing hook, disabling
```
[mpv.log](https://github.com/mpv-player/mpv/files/9943155/mpv.log)

**Closed** 2022-11-07 14:48 UTC
Labels: os:win

**Comment by haasn** [comment] 2022-11-07 14:50
> But when upscale 1920x1080 -> 2854x1605， I get new error:

Separate issue. I'll look into it

**Comment by haasn** [comment] 2022-11-07 14:57
> > But when upscale 1920x1080 -> 2854x1605， I get new error:
> 
> Separate issue. I'll look into it

Should be fixed

**Comment by zhongfly** [comment] 2022-11-07 15:39
> Should be fixed
Thanks!
Everything works fine.I can confirm it fixed.
