### ISSUE TITLE
Support for displaying colorful emojis in emoji title

### ISSUE THREAD

**Issue by soredake** [mpv-player/mpv#13810] opened 2024-04-02 19:24 UTC
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature
Displaying emojis in video title, colorfully.

Right now, emojis are not colorful:
![image](https://github.com/mpv-player/mpv/assets/5204968/b6deaa8d-76e5-446f-baa8-fbf487868cf6)

Example video: https://www.youtube.com/watch?v=iIYBC_SzOOo

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt,
attach it to the issue, and replace this text with a link to it.

**Comment by guidocella** [comment] 2024-04-02 19:25
https://github.com/libass/libass/issues/381

**Comment by GalaxySnail** [comment] 2024-04-15 06:03
duplicate of #9073

**Closed** 2024-04-15 06:36 UTC
Labels: meta:feature-request, down-upstream, down-upstream:libass
