### ISSUE TITLE
wayland: keyboard bindings with Shift don’t work

### ISSUE THREAD

**Issue by xHire** [mpv-player/mpv#13272] opened 2024-01-13 07:35 UTC
### Important Information

Provide following Information:
- mpv version: 0.37.0 (tested also 0.36.0)
- Linux Distribution and Version: Gentoo Linux
- Source of the mpv binary: built by package manager
- If known which version of mpv introduced the problem 0.36.0
- Window Manager and version: sway 1.8.1

### Reproduction steps

Press Shift and PgUp to seek by 10 minutes forward (or any other bindings with Shift).

### Expected behavior

Given the example above, to seek by 10 minutes forward. Or other outcomes as described in man page for given keyboard bindings with Shift.

### Actual behavior

Acts as if Shift wasn’t pressed at all.

### Additional notes

Ctrl or Alt seem to work fine.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/13927270/output.txt)

**Comment by sfan5** [comment] 2024-01-13 09:47
duplicate of #13176

**Comment by Dudemanguy** [comment] 2024-01-13 17:11
Fixed by #13275.

**Closed by Dudemanguy** 2024-01-13 17:11 UTC
Labels: os:linux
