### ISSUE TITLE
srt subs: inverted subtitle line order with successive same start/same end lines

### ISSUE THREAD

**Issue by cheweytoo** [mpv-player/mpv#8687] opened 2021-03-30 16:49 UTC
### Important Information

- mpv 0.33.0
- Linux Ubuntu 20.04.2 LTS
- https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests

### Reproduction steps
Use attached sub_line_order_test.srt file with any video.
Test file contains several successive subtitle lines with identical start and end times.
This is not a bug in the file, this is intentional and is used "in the wild" for multiline subs.

The display order of the subtitle lines will be inverted.

### Expected behavior
Show subs as
_First line
Second line
Third line
etc._

### Actual behavior
Shows sub lines as
_etc.
Third line
Second line
First line_

### Log file

[mpv_log.txt](https://github.com/mpv-player/mpv/files/6230727/mpv_log.txt)

### Sample files

Upload doesn't accept .srt file endings, so rename to .srt if necessary:
[sub_line_order_test.srt.txt](https://github.com/mpv-player/mpv/files/6230725/sub_line_order_test.srt.txt)

**Comment by sfan5** [comment] 2021-03-30 16:51
duplicate and <i>not a bug / won't fix</i>, see #7070

**Closed by sfan5** 2021-03-30 16:51 UTC
