### ISSUE TITLE
[MAC] Remove several versions MPV

### ISSUE THREAD

**Issue by asoksevil** [mpv-player/mpv#2653] opened 2015-12-30 14:24 UTC
Hey there,

I´ve been installing and updating them using homebrew and also downloaded compiled versions by @ChrisK2 but now I can´t get rid of the old ones (mpv 12)

![captura de pantalla 2015-12-30 a la s 15 21 51](https://cloud.githubusercontent.com/assets/739697/12051873/4d0a6328-af09-11e5-973e-f12828614f9b.png)

How can I just keep one version and update it so the old one gets removed and replaced?

Thanks!

Update. So after removing the 0.12 build my font got messed up:

![captura de pantalla 2015-12-30 a la s 16 47 49](https://cloud.githubusercontent.com/assets/739697/12053030/30200072-af15-11e5-9879-c03e94291988.png)

Update 2. Don't know why but if I double click to open it it won´t display the font but if I "right click" open with mpv, then it will display it properly.

**Comment by asoksevil** [comment] 2015-12-30 14:29
Nevermind, just figured its directory.

**Comment by tunnels** [comment] 2015-12-31 18:19
What did you do to remove it? You're supposed to do `brew cleanup mpv` to remove old version of mpv, or just `brew cleanup` to clean up all old homebrew programs.

**Comment by asoksevil** [comment] 2016-01-03 22:48
@tunnels 

Went to /usr/local/Cellar/mpv and removed the 0.12 version folder...

Just did the above commands but did not work.

**Comment by chyiz** [comment] 2016-01-11 03:00
@asoksevil regarding your font issue, try adding this line to your mpv.conf:
`osd-font='system'`

If this doesn't work, you may try other solutions in issue #2585 .

**Comment by franzf** [comment] 2016-01-17 14:49
The duplicate items on Open With menu is an OS X bug. Do `/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user` on the Terminal to reset it.

**Comment by pigoz** [comment] 2016-01-19 17:57
Font issue is a duplicate of #2585

For the multiple versions it looks like we can blame Apple (yay!)

**Closed by pigoz** 2016-01-19 17:57 UTC
Labels: osx, question
