### ISSUE TITLE
Why is the colormatrix of a Dolby Vision video BT.709?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#10573] opened 2022-08-25 15:26 UTC
Shouldn't the colormatrix of Dolby Vision video BT.2020?
However, it displays BT.709, and the Gamma is BT.1886.

By the way, I can't find the colormatrix in mediainfo for this video.
```
Format                                   : Matroska
Format version                           : Version 4
File size                                : 13.8 GiB
Duration                                 : 2 h 10 min
Overall bit rate                         : 15.1 Mb/s
Encoded date                             : UTC 2022-08-22 23:02:39
Writing application                      : mkvmerge v61.0.0 ('So') 64-bit
Writing library                          : libebml v1.4.2 + libmatroska v1.6.4

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5@High
HDR format                               : Dolby Vision, Version 1.0, dvhe.05.06, BL+RPU
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 2 h 10 min
Bit rate                                 : 14.1 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 024 pixels
Display aspect ratio                     : 1.897
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.075
Stream size                              : 12.8 GiB (93%)
Language                                 : English
Default                                  : Yes
Forced                                   : No
```

**Comment by quietvoid** [comment] 2022-08-25 15:28
The HEVC files themselves have undefined VUI values in the bitstream, so mpv probably defaults to BT.709 in that case.

**Comment by laichiaheng** [comment] 2022-08-25 15:30
> The HEVC files themselves have undefined VUI values in the bitstream, so mpv probably defaults to SDR in that case.

How can I fix it?

**Comment by quietvoid** [comment] 2022-08-25 15:39
You can't fix it. mpv has to be updated somehow to infer the video properties when Dolby Vision is present.

**Comment by laichiaheng** [comment] 2022-08-25 15:41
> You can't fix it. mpv has to be updated somehow to infer the video properties when Dolby Vision is present.

So it should be fine with other video players, right? Such as KODI on Android device.

**Comment by ZaquL** [comment] 2022-08-27 02:50
> Shouldn't the colormatrix of Dolby Vision video BT.2020?

No, Dolby Vision profile does not use BT.2020nc matrix. Can be closed.

**Comment by ZaquL** [comment] 2022-09-12 02:22
And anyway, this is a duplicate of https://github.com/mpv-player/mpv/issues/9761

**Comment by thebombzen** [comment] 2022-09-18 05:31
Duplicate of #9761

**Closed by thebombzen** 2022-09-18 05:31 UTC
Labels: meta:question
