### ISSUE TITLE
Frame drops on 0.22 with 24hz output

### ISSUE THREAD

**Issue by a4840639** [mpv-player/mpv#3837] opened 2016-11-24 09:00 UTC
### mpv version and platform

mpv 0.22 on macOS 10.12

### Reproduction steps

Play any 24fps video with the 24hz video output
I am using a 2014 15inch MBP and a 4K monitor

### Expected behavior

On 0.21, with the default video-sync option, there is virtually no frame drop with the same setting and the same video

### Actual behavior

Frame drops like crazy with the above mentioned setup (even if lowering the output resolution or using bilinear scale).
I have tried using other syncing option like display-vdrop. It can solve all my problem with 24fps videos. However, 30 fps videos become extremely choppy instead (This time lowering the output resolution or using bilinear scale did work though).

### Log file

Sorry, I have uninstalled 0.22 and switched back to 0.21

**Comment by Argon-** [comment] 2016-11-27 18:47
Out of curiosity, what happens when you use `--opengl-early-flush=no`?

**Comment by a4840639** [comment] 2016-11-28 02:47
> Just an idea: what happens when you use --opengl-early-flush=no?

It worked! I no longer have any problem with 24hz output anymore.

**Comment by Argon-** [comment] 2016-11-28 11:35
I had a similar problem (https://github.com/mpv-player/mpv/issues/3739). Huge amount of framedrops whenever the FPS of a movie is close or identical with the Hz of a display.
Now I'm wondering if the default value for `opengl-early-flush` is just bad for a few people or if it's bad for most OSX users with most not noticing it or assuming it's a performance problem (as the most likely FPS==Hz combination should be 60).

**Comment by bodayw** [comment] 2016-12-08 19:54
Just want to mention that most so-called 24 fps videos are actually of 23.976 (24000/1001) fps. AFAIK macOS doesn't have a 23.976 (23p) Hz video output option, so if you play a 23.976 fps video with 24 Hz output, you'll get one repeated frame for about every 1000/24 = 41.67 seconds, which could be annoying. To fix this you should use ``--video-sync=display-resample``.

On the same note, choppy playback of 30 fps videos with 24 Hz output should be expected.

Or if your hardware is capable enough, just set output refresh rate to the highest (e.g. 60 Hz) and use ``--video-sync=display-resample``, ``interpolation`` and ``tscale=oversample`` instead. In this way you don't need to switch between different refresh rate when playing different videos.

**Comment by Akemi** [comment] 2017-02-05 16:28
duplicate of #3739.

**Closed by Akemi** 2017-02-05 16:28 UTC
Labels: osx
