### ISSUE TITLE
vo_gpu_next/vulkan: cyan output from monob -> rgb444 conversion

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#14687] opened 2024-08-17 06:08 UTC
### mpv Information

```bash
mpv v0.38.0-706-ga3baf94a Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Aug 17 2024 01:05:12
libplacebo version: v7.349.0 (v7.349.0-5-g82bf46a-dirty)
FFmpeg version: N-116717-g817c6a676
FFmpeg library versions:
   libavcodec      61.11.100
   libavdevice     61.2.100
   libavfilter     10.2.102
   libavformat     61.5.101
   libavutil       59.34.100
   libswresample   5.2.100
   libswscale      8.2.100
```

### Other Information

- Windows version: 10.0.22631.4037
- GPU model, driver and version: AMD 24.7.1
- Source of mpv: zhongfly
- Introduced in version: dunno

### Reproduction Steps

```
--no-config --vo=gpu-next --gpu-api=vulkan original.png
```
Not reproducible on d3d11.
Not reproducible on vo_gpu since it prefers `monob -> gray`

### Expected Behavior

The hash pattern is black and white.

### Actual Behavior

The hash pattern is black and cyan.

![mpv-shot0001](https://github.com/user-attachments/assets/5d2f0960-0d4a-473e-ab93-08e313def570)

### Log File

[mpv.log](https://github.com/user-attachments/files/16643646/mpv.log)

### Sample Files

https://github.com/haasn/mpvhq-upscalers/blob/master/hash/original.png

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by guidocella** [comment] 2024-08-17 06:08
Duplicate of https://github.com/mpv-player/mpv/issues/13398

**Closed as not planned** 2024-08-17 06:09 UTC
Labels: os:win
