### ISSUE TITLE
MPV + Youtube : no audio, EDL parsing failed

### ISSUE THREAD

**Issue by Azuraell** [mpv-player/mpv#11448] opened 2023-03-13 21:12 UTC
This essentially prevents a program I use from working. I hope this issue contains enough information so that is may be solved, or that you can point me to an existing fix.
I asked several friends running Arch to try on their machine and it was reproduced every time.

### Important Information

Provide following Information:
- **mpv version** 0.35.1
- Manjaro Linux 22.0.4
- **Source of the mpv binary** : [Community repository (Arch)](https://archlinux.org/packages/community/x86_64/mpv/)
- **Window Manager**: KDE Plasma 5.26.5
- **GPU driver and version** : GLX version: 1.4
    Vendor: AMD (0x1002)
    Device: AMD Radeon Vega 10 Graphics (raven, LLVM 15.0.7, DRM 3.42, 5.15.94-1-MANJARO) (0x15d8)
    Version: 22.3.5

### Expected behavior

When the command `"mpv <YouTube URL>"` is launched, the video starts playing normally in MPV

### Actual behavior

When the command `"mpv <YouTube URL>"` is launched, either the video launches in MPV without any audio, or does not launch at all. Errors generally are : 
```
EDL specifies no segments.'
EDL parsing failed.
Error in EDL.
```

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/10961953/mpv.log)  (no audio)
[mpv2.log](https://github.com/mpv-player/mpv/files/10961954/mpv2.log)  (failure)

**Comment by llyyr** [comment] 2023-03-13 21:18
Duplicate of #11392. You can copy [ytdl_hook.lua](https://github.com/mpv-player/mpv/blob/master/player/lua/ytdl_hook.lua) to your scripts folder and run mpv with `--ytdl=no` or update to a newer enough version of mpv that has it fixed.

**Comment by Kunotyr** [comment] 2023-03-14 01:55
> Duplicate of #11392. You can copy [ytdl_hook.lua](https://github.com/mpv-player/mpv/blob/master/player/lua/ytdl_hook.lua) to your scripts folder and run mpv with `--ytdl=no` or update to a newer enough version of mpv that has it fixed.

Thanks solved the issue for me. 

But some videos still give the message when starting from terminal:

[ytdl_hook] EDL doesn't support fragmentswithout duration with MP4 DASH 
[ytdl_hook] EDL doesn't support fragmentswithout duration with MP4 DASH 

Using the mpv version from March 10 and yt-dlp March 4.

Sound and stream is fine though.

**Closed** 2023-03-14 02:38 UTC
Labels: os:linux

**Comment by markmark1** [comment] 2023-04-13 19:40
[ytdl_hook] 
[ytdl_hook] stack traceback:
[ytdl_hook] 	[C]: at 0x01010fe544
[ytdl_hook] Lua error: /mpv/scripts/ytdl_hook.lua:8: unexpected symbol near '<'
Failed to recognize file format.

**Comment by simurgh9** [comment] 2023-06-13 23:49
> copy ytdl_hook.lua to your scripts folder

Where might I find this scripts folder?

**Comment by Traneptora** [comment] 2023-06-14 16:02
It would be in `~/.config/mpv/scripts/`
