### ISSUE TITLE
--no-border option causes title to be duplicated in OSC

### ISSUE THREAD

**Issue by tonycpsu** [mpv-player/mpv#7508] opened 2020-03-05 13:41 UTC
### Important Information

Provide following Information:
- mpv version 8b24510
- macOS Version 10.13.6
- Source of the mpv binary or bundle git (Homebrew)
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

### Reproduction steps

See:

    $ MPV_HOME=/tmp mpv --script-opts=osc-visibility=always ~/Movies/Juno\ Jupiter\ Flyby.mp4

![image](https://user-images.githubusercontent.com/914142/75986839-cd553f00-5ebc-11ea-98c8-b7f6e12654a4.png)

vs.

    $ MPV_HOME=/tmp mpv --no-border --script-opts=osc-visibility=always ~/Movies/Juno\ Jupiter\ Flyby.mp4

![image](https://user-images.githubusercontent.com/914142/75986898-e78f1d00-5ebc-11ea-9e38-173b5d660794.png)

### Expected behavior

Title only appears in OSC, or perhaps an option to have it appear in OSC or at the top.

### Actual behavior

Title is duplicated, once at the top, once as part of the OSC bar.

**Comment by Dudemanguy** [comment] 2020-03-05 16:14
Not really a bug. By default, the windowcontrols is activated if `--no-border` is given which displays the title at the top. If you want to disable it, you could use `--script-opts=osc-windowcontrols=no`. Of course, maybe this is an argument for it to be possible to show the windowcontrols but without the extra title at the top.

**Comment by philipl** [comment] 2020-03-05 16:18
I thought about this when I wrote the code, but I decided not to - as it would require more special case code and it doesn't save any space. If you remove one of the names, you don't get any space back.

**Comment by tonycpsu** [comment] 2020-03-05 16:26
`--script-opts=osc-windowcontrols=no` seems to interfere with `--script-opts=osc-visibility=always`.  If I enable the former, I have to move the mouse to see the OSC, even though `--script-opts=osc-visibility=always` should keep it on at all times.

**Comment by tonycpsu** [comment] 2020-03-05 16:27
> doesn't save any space.   you remove one of the names, you don't get any space back.

Sure, but you also don't have two titles covering portions of your video for no good reason.

**Comment by Dudemanguy** [comment] 2020-03-05 16:46
>--script-opts=osc-windowcontrols=no seems to interfere with --script-opts=osc-visibility=always

It should be okay if you use `--script-opts=osc-windowcontrols=no,osc-visibility=always`.

**Comment by tonycpsu** [comment] 2020-03-05 16:51
That'll do.

**Comment by Akemi** [comment] 2020-03-05 16:51
duplicate of #7481.

**Closed by Akemi** 2020-03-05 16:51 UTC
Labels: os:mac

**Comment by avih** [comment] 2020-03-05 16:55
To summarize:
- Yes, Both the OSC shows the title by default, and the window controls show it.
- The window controls can be disabled if you don't want it to show up automatically when `--no-border` is used.
- The OSC title area can be modified to not include a title, if you prefer using the title osc option. It defaults to `${media-title}` and you can replace it with anything you want.
- When using multiple `script-opts` configurations, every one of them replaces (deletes) the previous one. If you want them to add up then you should either use several at the same option, or use `--script-opts-add`.

**Comment by tonycpsu** [comment] 2020-03-05 16:56
> The OSC title area can be modified to not include a title, if you prefer using the title osc option. It defaults to `${media-title}` and you can replace it with anything you want.

Thanks for this advice, and I'm totally with this ticket being closed now that I have a workaround, but just for the record, replacing the title option with an empty string doesn't work -- it just goes to the default.  This might be a useful change for anyone who wants to keep window controls when border is disabled but doesn't want title duplicated.

**Comment by garoto** [comment] 2020-03-05 17:26
> The OSC title area can be modified to not include a title, if you prefer using the title osc option.

`windowcontrols` title logic is shared with whatever one have decalred as `title=` in `osc.conf`.

**Comment by lpv11** [comment] 2022-01-26 00:23
As of today is this still not possible? I mean to have the borderless 'mode' without removing the top buttons or the title.
