### ISSUE TITLE
Specific font rendering larger in MPV compared to other players

### ISSUE THREAD

**Issue by ambiguousrocket** [mpv-player/mpv#7445] opened 2020-02-07 21:20 UTC
Windows 10 Pro 18363, using mpv-x86_64-20200202, downloaded https://sourceforge.net/projects/mpv-player-windows/files/

After muxing an .mkv with [InFormal_Style_Bold.zip](https://github.com/mpv-player/mpv/files/4172811/InFormal_Style_Bold.zip), the font appears roughly 10pt larger than what is visible in all other libass players I've tried (mplayer, mplayer2, Aegisub, VLC, Kodi, and avidemux). I believe it's isolated from libass, somehow.

But - this only occurs in the version I recently upgraded to above. 
[mpv.zip](https://github.com/mpv-player/mpv/files/4172831/mpv.zip) < I was using this version up until now, which _doesn't_ have this issue. I'm not sure of the version aside from that it's from 4th June 2017.

### Expected behavior
vlc
![vlc_2020-02-07_20-24-53](https://user-images.githubusercontent.com/42182755/74063308-10201600-49e8-11ea-9724-470a2de2897c.jpg)

### Actual behavior
mpv
![MoyaiSubs  Kiratto PriChan - 78  C4DE1CBB mkv_snapshot_00 01 04_ 2020 02 07_20 23 55](https://user-images.githubusercontent.com/42182755/74063321-18785100-49e8-11ea-8dcf-ce3f027e954e.jpg)

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/4172879/output.txt)

### Sample files
You can find the .mkv in question here: https://0x0.st/iip_.mkv

**Comment by rcombs** [comment] 2020-02-08 15:51
This is a dupe of https://github.com/libass/libass/issues/361. You can work around it by clearing the sTypoAscender, sTypoDescender, and sTypoLineGap fields in the font's OS/2 table (i.e. set them to zero), or by clearing bit 7 (USE_TYPO_METRICS) of the fsSelection field ("Really use Typo metrics" in FontForge).

**Closed** 2020-02-08 15:56 UTC
Labels: core:subtitle, os:win
