### ISSUE TITLE
Multichannel audio doesn't work above 16 channels

### ISSUE THREAD

**Issue by hmedia1** [mpv-player/mpv#6261] opened 2018-10-30 10:04 UTC
### mpv version and platform

- 865627d
- Mac OS X **10.13.1 High Sierra**
- Mac OS X **10.14 Mojave** 

### Reproduction steps
Launch a newly compiled (or very old version or anything in between) `mpv` with a multi channel audio file using the following command: 

`./mpv --audio-device=coreaudio/AppleUSBAudioEngine:KLARK TEKNIK:DN32-USB:0A9D35E6:1,2' --ad-lavc-downmix=no /Users/user/testmulti.wav --video=no --coreaudio-change-physical-format=yes --audio-channels=auto -v` 

### Expected behavior

Audio channels would be mapped 1:1 to the coreaudio inputs.

### Actual behavior

If the interface has more than 16 channels (any coreaudio interface - even virtual ones), it either downmixes to stereo, or fails.

Specific example below of a coreaudio hardware card that is switchable between 16 channel and 32 channel IO:

---

**When card is in 16 channel mode** ([Log File #1](https://0x0.st/sIrL.txt)): 

<img width="151" alt="image" src="https://user-images.githubusercontent.com/26698331/47709725-e36d4280-dc6b-11e8-9efb-ba8190b8b47d.png">

Playback is fine:

<img width="390" alt="screen shot 2018-10-30 at 5 01 46 pm" src="https://user-images.githubusercontent.com/26698331/47709427-2e3a8a80-dc6b-11e8-833d-d6416c9caf51.png">

---

**When card is in 32 channel mode** ([Log File #2](https://0x0.st/sIr9.txt)): 

<img width="148" alt="image" src="https://user-images.githubusercontent.com/26698331/47709741-f08a3180-dc6b-11e8-8628-a3da094da1dc.png">

Playback is stereo:

<img width="385" alt="screen shot 2018-10-30 at 5 16 33 pm" src="https://user-images.githubusercontent.com/26698331/47709415-267ae600-dc6b-11e8-9963-7cb760961ed1.png">

---

**When using a recompiled version of `mpv`** (changing `#define MP_NUM_CHANNELS 16` to `#define MP_NUM_CHANNELS 32` in `./audio/chmap.h`), in an attempt to fix ([Log File #3](https://0x0.st/sIrp.txt)): 

![image](https://user-images.githubusercontent.com/26698331/47709568-7c4f8e00-dc6b-11e8-847a-ac64f36160f0.png)

Playback fails:

```
[   0.086][i][cplayer] AO: [coreaudio] 48000Hz fl-fr-bl-br-fc-bc-wl-wr-na-na-na-na-na-na-na-na-na-na-na-na-na-na-na-na
[   0.086][v][cplayer] AO: Description: CoreAudio AudioUnit
[   0.086][v][autoconvert] inserting resampler
[   0.086][v][swresample] format change, reinitializing resampler
[   0.086][v][swresample] 48000Hz unknown16 s16 -> 48000Hz fl-fr-bl-br-fc-bc-wl-wr-na-na-na-na-na-na-na-na-na-na-na-na-na- s16
[   0.086][v][swresample] Remix: fl-fr-fc-lfe-bl-br-flc-frc-bc-sl-sr-tc-tfl-tfc-tfr-tbl -> fl-fr-fc-lfe-bl-br-flc-frc-bc-sl-sr-tc-tfl-tfc-tfr-tbl-tbc-tbr-
[   0.086][e][ffmpeg] SWR: Output channel layout '32 channels (FL+FR+FC+LFE+BL+BR+FLC+FRC+BC+SL+SR+TC+TFL+TFC+TFR+TBL+TBC+TBR+DL+DR+WL)' is not supported
[   0.086][e][swresample] Cannot open Libavresample context.
[   0.086][f][swresample] libswresample failed to initialize.
[   0.086][f][af] Cannot convert decoder/filter output to any format supported by the output.
[   0.086][v][af] filter output EOF
[   0.086][v][ad] Uninit decoder.
[   0.086][v][af] dropping frame due to pin disconnect
```

---

**Incidentally** - `afplay` works with the card in 32 channel mode just fine.

---

### Log file

Links above in behavior headings

### Sample files

https://0x0.st/sIr_.zip 16 channels of the same drum overhead mic
10 second file that looks like this:

```
Input #0, wav, from '/Users/user/testmulti.wav':
  Metadata:
    encoder         : Lavf58.19.102
  Duration: 00:00:10.00, bitrate: 12288 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, 16 channels, s16, 12288 kb/s
```

This issue is similar to #5042 which remains open - the detailed example here provides confirmation of the issue with some more detail and visuals.

All of the above behavior can be replicated using a virtual interface - i.e. Soundflower (64ch) plays as stereo, but recompiling it to Soundflower (16ch), plays fine.

**Comment by Akemi** [comment] 2018-10-30 12:09
duplicate of #5042. let me know if it isn't.

**Closed by Akemi** 2018-10-30 12:09 UTC

**Comment by Akemi** [comment] 2018-10-30 12:37
though it's the same end result, that +16 channels don't work. i mean you even removed the 16 channel limit to get that far. assuming that limit was set for a reason anything that breaks by removing that limit is part of that old issue, even if it breaks in different ways.

even with more information a new issue usually doesn't supersede an older one. the info can easily be posted there.

what do you mean labelled and acknowledged as a bug? every issue that is open is either an acknowledged bug (or similar) or was ignored. if you mean a github label i can add it, if that makes you happy.

**Comment by hmedia1** [comment] 2018-10-30 12:55
Thanks @Akemi - have appended #5042 with my info.  Yes I believe it's the bug label i was referring to 👍
