### ISSUE TITLE
Distorted audio with dvb-usb

### ISSUE THREAD

**Issue by mabod** [mpv-player/mpv#8367] opened 2020-12-06 09:03 UTC
### Important Information

Provide following Information:
- mpv version 
0.33
- Linux Distribution and Version 
EndeavourOS

- Source of the mpv binary
Arch official repo; package version 1:0.33.0-3

- If known which version of mpv introduced the problem
0.33

- GPU driver and version
AMD Radeon RX 5600 XT

I use mpv to watch TV with tvheadend 4.2.8-4 and a 'Technotrend TT Connect S2-3600':

`mpv --playlist=http://localhost:9981/playlist`

 mpv version 0.33 introduces distorted audio. I have to restart mpv several times or switch channels several times to make it work. Downgrading to the previous package version 1:0.32.0-6 solves the issue.

**Comment by olifre** [comment] 2020-12-06 13:27
Interesting! I think I observed this once with DVB tuning directly with `mpv`, but could not reproduce it on the next attempt... 
Since I am more expert for DVB and not for general audio, let me try a shot in the dark, though. Does:
```
cache=yes
cache-pause-initial=yes
cache-pause-wait=1
```
help (to enforce there is a bit of the stream buffered before playback starts and prevent a potential immediate queue underrun)? 
Also, a log would be useful...

**Comment by mabod** [comment] 2020-12-06 14:46
These settings did not help. Same distortion.
How can I create a log?

**Comment by jeeb** [comment] 2020-12-06 15:02
`--log-file=mpv_log.log`

**Comment by mabod** [comment] 2020-12-06 15:22
Here is the log file 

[mpv_log3.log.gz](https://github.com/mpv-player/mpv/files/5648997/mpv_log3.log.gz)

**Comment by olifre** [comment] 2020-12-06 20:32
There's nothing obvious in the logs, at least to my eyes, and I'm sadly unable to reproduce. 
A few general things to try: Does it also happen with `--no-config`? 
Have you also been using Pulseaudio AO with 0.32.0 with 48000 Hz (it might be that the default resampling of Pulseaudio is causing the distortion if your audio device only does 44100 Hz)? 
If nobody else has a better idea, your best bet would likely be to compare with a log from 0.32 on your system, or bisect to find which change caused it for you.

**Comment by mabod** [comment] 2020-12-08 06:29
The issue occurs always when I start mpv and the first channel is "Das Erste HD" (germany). When I switch to the next channel, "ZDF HD",  the audio is good. Switching back to "Das Erste HD" gives distorted audio again. Doing this several times fixes the issue.

**Comment by olifre** [comment] 2020-12-08 19:29
Can you also reproduce after recording with `--stream-record=test.ts` and playing back the resulting TS file?

**Comment by CounterPillow** [comment] 2020-12-08 21:25
Does the issue occur if you manually set a pulseaudio buffer size, such as `--pulse-buffer=100` for a (ridiculously large) 100ms audio buffer?

**Comment by mabod** [comment] 2020-12-09 06:51
> Can you also reproduce after recording with `--stream-record=test.ts` and playing back the resulting TS file?

This is very interesting.

When I add `--stream-record=test.ts` to the commandline the sound is good. When I then stop mpv and remove `--stream-record=test.ts` form the commandline the sound is distorted.  

I summary: Just adding  `--stream-record=test.ts` to the commandline fixes the issue.

**Comment by olifre** [comment] 2020-12-09 10:47
That's indeed strange. Can you please also try what @CounterPillow suggested? This might well be some audio buffer issue...

**Comment by mabod** [comment] 2020-12-09 11:42
`--pulse-buffer` is an unrecognized option with pulseaudio 14.0-1

**Comment by mabod** [comment] 2020-12-09 11:56
I investigated a bit more on pulseaudio buffer size and found the following Arch Troubleshooting page:

https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting#Setting_the_default_fragment_number_and_buffer_size_in_PulseAudio

They recommend to set

```
default-fragments = 3
default-fragment-size-msec = 5
```

or 

```
default-fragments = 5
default-fragment-size-msec = 2
```

to solve sound issues. I tested both and both are working. With either one of the proposals the distortions are gone.  So that is good.

But which one should I pick? Should I prefer one over the other?

**Comment by CounterPillow** [comment] 2020-12-09 16:03
@mabod `--pulse-buffer` is an mpv option, not a pulseaudio option.

**Comment by mabod** [comment] 2020-12-09 17:04
Ok. Makes sense ;-)

I tested with `--pulse-buffer=100` and `--pulse-buffer=1000` and it does not help. Only the pulseaudio options are helping.

**Comment by olifre** [comment] 2020-12-13 18:14
I wonder if #8393 is another incarnation of the same issue. Since I can't reproduce locally (still), the only path forward here is likely to bisect between 0.32 and 0.33.

**Comment by danburd** [comment] 2021-01-25 10:39
I experience this same issue streaming ATSC TV from tvheadend on two different Fedora PC's using mpv 0.33. Downgrading to mpv 0.32 resolves the issue.

**Comment by mabod** [comment] 2021-01-25 10:46
Please test if the pulseaudio settings I mentioned earlier  (https://github.com/mpv-player/mpv/issues/8367#issuecomment-741724885) are fixing the issue also for you.

I have the following in my `$HOME/.config/pulse/daemon.conf`:

```
default-fragments = 3
default-fragment-size-msec = 5
```
and no issue anymore with mpv 0.33

**Comment by danburd** [comment] 2021-01-25 11:13
Thank you for the potential fix -- however, I just tested it and it did not resolve the issue for me on mpv 0.33.

**Comment by olifre** [comment] 2021-01-25 19:18
@danburd Can you also reproduce with `--stream-record=test.ts`, or does it vanish then, as it did for @mabod ? 
What happens when you play back the recorded `test.ts` afterwards? 
Since I still can't reproduce locally, I wonder whether this really is `dvb` related.

**Comment by danburd** [comment] 2021-01-29 11:25
Sorry for the delay. I tested it out on mpv 33 and I still had audio device underruns with the stream-record flag enabled. When I played back the recording, neither the audio issues nor the console error (audio device underrun detected) presented themselves, or perhaps the audio issues were more subtle.

**Comment by olifre** [comment] 2021-01-30 19:15
I can't reproduce with any DVB cards I have available, so my assumption remains that this is another incarnation of what was also seen in #8393 for network streams. Sadly, I don't have any good ideas on where to start tracking this down, apart from recommending a bisection of the changes between 0.32 and 0.33 for anybody who can reproduce it reliably.

**Comment by sonic019** [comment] 2021-01-30 20:13
hmm i got this issues too

**Comment by olifre** [comment] 2021-02-08 19:45
Since nobody has provided a bisection yet (and I still fail to reproduce), another shot in the dark:
Does changing `tsched` as outlined here:
https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting#Glitches,_skips_or_crackling
together with the fragment settings (see also: https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting#Setting_the_default_fragment_number_and_buffer_size_in_PulseAudio ) change anything for any of you?

**Comment by mabod** [comment] 2021-02-09 06:41
I tested tsched=0 and it does not help.

I would love to help with a bisection by I am not a developer and I do not know how to do it. I would need a very detailed(!) tutorial to do it.

**Comment by mabod** [comment] 2021-02-09 06:57
I tried a bisection this morning but the compilation fails with the first commit.

```
git bisect start
git bisect good v0.32.0
git bisect bad v0.33.0
waf configure 
waf
```

testing ./build/mpv -> bad sound


```
49# git bisect bad
binäre Suche: danach noch 451 Commits zum Testen übrig (ungefähr 9 Schritte)
[0b09771ba9f5a54fe1c8c8612a04dd7a1f1672c6] vo_gpu: manually resolve user shader prefixes
```

the next compilation fails:

`waf clean && waf configure && waf`

```
07:52:42 runner ['/usr/bin/cc', '-D_ISOC99_SOURCE', '-D_GNU_SOURCE', '-D_FILE_OFFSET_BITS=64', '-Wall', '-std=c11', '-O2', '-g', '-Werror=implicit-function-declaration', '-Wno-error=deprecated-declarations', '-Wno-error=unused-function', '-Wempty-body', '-Wdisabled-optimization', '-Wstrict-prototypes', '-Wno-format-zero-length', '-Werror=format-security', '-Wno-redundant-decls', '-Wvla', '-Wno-format-truncation', '-Wimplicit-fallthrough', '-fno-math-errno', '-Wall', '-Wundef', '-Wmissing-prototypes', '-Wshadow', '-Wno-switch', '-Wparentheses', '-Wpointer-arith', '-Wno-pointer-sign', '-Wno-unused-result', '-pthread', '-pthread', '-I.', '-I..', '-I/usr/include/libxml2', '-I/usr/include/freetype2', '-I/usr/include/libpng16', '-I/usr/include/harfbuzz', '-I/usr/include/glib-2.0', '-I/usr/lib/glib-2.0/include', '-I/usr/include/fribidi', '-I/usr/include/libdrm', '-I/usr/include/uchardet', '-I/usr/include/lua5.2', '-D_REENTRANT', '../player/sub.c', '-c', '-o/home/matthias/src/mpv-bisect/mpv/build/player/sub.c.28.o']
../video/out/placebo/ra_pl.c: In Funktion »mppl_wrap_tex«:
../video/out/placebo/ra_pl.c:142:13: Warnung: »sample_mode« ist veraltet [-Wdeprecated-declarations]
  142 |             .src_linear = pltex->params.sample_mode == PL_TEX_SAMPLE_LINEAR,
      |             ^
In Datei, eingebunden von ../video/out/placebo/ra_pl.h:4,
                 von ../video/out/placebo/ra_pl.c:4:
/usr/include/libplacebo/gpu.h:352:29: Anmerkung: hier deklariert
  352 |     enum pl_tex_sample_mode sample_mode PL_DEPRECATED;
      |                             ^~~~~~~~~~~
../video/out/placebo/ra_pl.c:143:13: Warnung: »address_mode« ist veraltet [-Wdeprecated-declarations]
  143 |             .src_repeat = pltex->params.address_mode == PL_TEX_ADDRESS_REPEAT,
      |             ^
In Datei, eingebunden von ../video/out/placebo/ra_pl.h:4,
                 von ../video/out/placebo/ra_pl.c:4:
/usr/include/libplacebo/gpu.h:353:30: Anmerkung: hier deklariert
  353 |     enum pl_tex_address_mode address_mode PL_DEPRECATED;
      |                              ^~~~~~~~~~~~
../video/out/placebo/ra_pl.c: In Funktion »blit_pl«:
../video/out/placebo/ra_pl.c:351:5: Fehler: zu viele Argumente für Funktion »pl_tex_blit«
  351 |     pl_tex_blit(get_gpu(ra), dst->priv, src->priv, pldst, plsrc);
      |     ^~~~~~~~~~~
In Datei, eingebunden von ../video/out/placebo/ra_pl.h:4,
                 von ../video/out/placebo/ra_pl.c:4:
/usr/include/libplacebo/gpu.h:458:6: Anmerkung: hier deklariert
  458 | void pl_tex_blit(const struct pl_gpu *gpu,
      |      ^~~~~~~~~~~

Waf: Leaving directory `/home/matthias/src/mpv-bisect/mpv/build'
Build failed
 -> task in 'objects' failed with exit status 1: 
	{task 139950851440528: c ra_pl.c -> ra_pl.c.28.o}
['/usr/bin/cc', '-D_ISOC99_SOURCE', '-D_GNU_SOURCE', '-D_FILE_OFFSET_BITS=64', '-Wall', '-std=c11', '-O2', '-g', '-Werror=implicit-function-declaration', '-Wno-error=deprecated-declarations', '-Wno-error=unused-function', '-Wempty-body', '-Wdisabled-optimization', '-Wstrict-prototypes', '-Wno-format-zero-length', '-Werror=format-security', '-Wno-redundant-decls', '-Wvla', '-Wno-format-truncation', '-Wimplicit-fallthrough', '-fno-math-errno', '-Wall', '-Wundef', '-Wmissing-prototypes', '-Wshadow', '-Wno-switch', '-Wparentheses', '-Wpointer-arith', '-Wno-pointer-sign', '-Wno-unused-result', '-pthread', '-pthread', '-I.', '-I..', '-I/usr/include/libxml2', '-I/usr/include/freetype2', '-I/usr/include/libpng16', '-I/usr/include/harfbuzz', '-I/usr/include/glib-2.0', '-I/usr/lib/glib-2.0/include', '-I/usr/include/fribidi', '-I/usr/include/libdrm', '-I/usr/include/uchardet', '-I/usr/include/lua5.2', '-D_REENTRANT', '../video/out/placebo/ra_pl.c', '-c', '-o/home/matthias/src/mpv-bisect/mpv/build/video/out/placebo/ra_pl.c.28.o']
```

**Comment by olifre** [comment] 2021-02-09 21:40
> the next compilation fails:

This may happen at times, either if the commit which you are looking at is bad for other reasons (rarely happens) or you have installed a dependency on your system which is incompatible with the version of `mpv` you are building. In this case, it seems to be the latter, i.e. too new `libplacebo` for the "intermediate" `mpv` version you are building- 

`git bisect skip` helps if there is a single faulty commit (it basically means "use another commit, and don't record status of this one"). However, for the problem you have here, it seems `libplacebo` mismatches. 

It might be easiest to configure with `--disable-libplacebo` or downgrade temporarily — if you can still reproduce after using that.

**Comment by mabod** [comment] 2021-02-10 07:09
I downgraded libplacebo and finished a git bisect:


```
114# git bisect bad
47a5f868291349746caa681799fa0d332a6ceabf is the first bad commit
commit 47a5f868291349746caa681799fa0d332a6ceabf
Author: wm4 <wm4@nowhere>
Date:   Thu Aug 27 18:40:12 2020 +0200

    f_decoder_wrapper: pass through EOF after EOF
    
    It's relevant in some obscure corner cases (EDL file that has a segment
    without audio). Didn't test what's actually going on (is ad_lavc.c
    behaving wrong? is libavcodec behaving wrong or in an unexpected way? is
    lavc_process wrong?) and just patched it over with some bullshit, so the
    fix might be too complicated, and could be reworked at some later point.
    This sure is a real data flow fuckmess.

 filters/f_decoder_wrapper.c | 7 +++++++
 filters/f_decoder_wrapper.h | 1 +
 2 files changed, 8 insertions(+)
```

I did a second bisect to verify the result. I did a fresh git pull but then the git bisect was not going well. I had many comits where I had strange video stuttering with no audio at all. I did not know what to do with them: Skip them or mark them as bad? In the end I did not finish the second bisect.

**Comment by olifre** [comment] 2021-02-10 08:01
> I downgraded libplacebo and finished a git bisect:

While that commit does not seem to be the likely cause, could you please try with a checkout of `0.33.0`, and comment out these lines:
https://github.com/mpv-player/mpv/blob/0728b514980cccd13543eea53a8e23332e233a6c/filters/f_decoder_wrapper.c#L1296-L1297
which would effectively revert the commit? 


>  I want to mention that I see the following log messages in the console when the issue happens: [...]

This was not part of the log you attached here in one of the first comments. 
Was it also present then? Did something change on your system in between (e.g. Pulseaudio configuration / version)? 
That makes it look even more like #8393 , however, it would be good to understand why the device underruns did not show up for you in the earlier log.

**Comment by mabod** [comment] 2021-02-10 10:45
Commenting these two lines did not help. 

> This was not part of the log you attached here in one of the first comments.

The situation is weird. `mpv-1:0.33.0-4` from Arch is not showing the "Audio device underrun detected" messages. And the source from here https://github.com/mpv-player/mpv/releases/tag/v0.33.0 is not showing the messages either. But I see them during the git bisect excercise. 

Also weird: The mpv source from git is not compiling with `libplacebo 3.104.0-1`:

```
[ 83/265] Compiling misc/natural_sort.c
../video/out/placebo/ra_pl.c: In function 'mppl_wrap_tex':
../video/out/placebo/ra_pl.c:147:13: warning: 'sample_mode' is deprecated [-Wdeprecated-declarations]
  147 |             .src_linear = pltex->params.sample_mode == PL_TEX_SAMPLE_LINEAR,
      |             ^
In file included from ../video/out/placebo/ra_pl.h:4,
                 from ../video/out/placebo/ra_pl.c:4:
/usr/include/libplacebo/gpu.h:352:29: note: declared here
  352 |     enum pl_tex_sample_mode sample_mode PL_DEPRECATED;
      |                             ^~~~~~~~~~~
../video/out/placebo/ra_pl.c:148:13: warning: 'address_mode' is deprecated [-Wdeprecated-declarations]
  148 |             .src_repeat = pltex->params.address_mode == PL_TEX_ADDRESS_REPEAT,
      |             ^
In file included from ../video/out/placebo/ra_pl.h:4,
                 from ../video/out/placebo/ra_pl.c:4:
/usr/include/libplacebo/gpu.h:353:30: note: declared here
  353 |     enum pl_tex_address_mode address_mode PL_DEPRECATED;
      |                              ^~~~~~~~~~~~
../video/out/placebo/ra_pl.c: In function 'blit_pl':
../video/out/placebo/ra_pl.c:402:5: error: too many arguments to function 'pl_tex_blit'
  402 |     pl_tex_blit(get_gpu(ra), dst->priv, src->priv, pldst, plsrc);
      |     ^~~~~~~~~~~
In file included from ../video/out/placebo/ra_pl.h:4,
                 from ../video/out/placebo/ra_pl.c:4:
/usr/include/libplacebo/gpu.h:458:6: note: declared here
  458 | void pl_tex_blit(const struct pl_gpu *gpu,
      |      ^~~~~~~~~~~

Waf: Leaving directory `/home/matthias/src/mpv-bisect/mpv-0.33.0/build'
Build failed
 -> task in 'objects' failed with exit status 1 (run with -v to display more information)
```
I have to downgrade to `libplacebo-1.29.1-3` to compile mpv and do all the git bisect stuff.

While on the other hand the Arch `mpv 1:0.33.0-4` insists on `libplacebo 3.104.0-1`

**Comment by olifre** [comment] 2021-02-10 22:51
> Commenting these two lines did not help.

That at least confirms that the result of the bisect does not help :-(. 

> Also weird: The mpv source from git is not compiling with `libplacebo 3.104.0-1`:

That one's easy. 0.33.0 does not have https://github.com/mpv-player/mpv/commit/7c4465cefb27d4e0d07535d368febdf77b579566 yet. 
Archlinux seems to have preferred bumping `libplacebo` earlier than the next `mpv` release, so they pulled that commit from current `master` and apply it to their build of `mpv`:
https://github.com/archlinux/svntogit-community/commit/aea9f1bf85ca5c2ef58dded9aff806317e4f8e9c#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a
Insisting on the new `libplacebo` version in the list of dependencies of the package does not make sense, though, but I'm not an expert in Arch packaging. 

Sadly, this means I have no good idea on how to continue debugging — the related issue I linked likely has the same cause, and also seems to be without ideas :-(. So any ideas are welcome.

**Comment by olifre** [comment] 2021-11-20 20:11
@mabod A fix was merged just now, which could fix the audio corruption you observed (see the linked PR). Could you please check if that fixes things for you?

**Comment by mabod** [comment] 2021-11-21 08:11
This issue is a long time solved at my end.

With mpv 0.33.0 I fixed it with pulse settings 

```
default-fragments = 3
default-fragment-size-msec = 5

```
as mentioned in my comment https://github.com/mpv-player/mpv/issues/8367#issuecomment-741724885

And since mpv 1:0.33.0-4 (February 2021)  I do not even have these pulse settings anymore. 

Now I am at mpv 1:0.34.0-2 and this is running fine too.

**Comment by danburd** [comment] 2021-11-21 10:28
I continue to experience this issue on 0.34.0 (Flatpak). However, I'm not sure how to test the PR before it is pushed into a released version. I'd be happy to post results the here once that occurs.

**Comment by s0301132** [comment] 2021-12-15 17:29
Hi @mabod do you also change the `PulseAudio` config system wise? `/etc/pulse`, it's works for me but only in system wise config.

**Comment by Dudemanguy** [comment] 2023-08-09 00:23
Original reporter said he solved it (might be still an mpv bug somewhere but we'll close this for now).

**Closed by Dudemanguy** 2023-08-09 00:23 UTC
Labels: core:audio, os:linux, core:stream
