### ISSUE TITLE
MPV waf 1.9.8 issue

### ISSUE THREAD

**Issue by cpu82** [mpv-player/mpv#4360] opened 2017-04-24 09:26 UTC
### mpv version and platform
```
Mpv v0.25.0
FreeBSD 10.3-RELEASE/amd64
```
### Reproduction steps

`$ ./waf-light install`

### Expected behavior

Prevent `libmpv.so` from being created twice. Mpv installs fine using `waf 1.8.x` version.

See https://github.com/waf-project/waf/issues/1837 for further details.

### Actual behavior
```
Waf: Entering directory `/usr/ports/multimedia/mpv/work/mpv-0.25.0/build'
[  1/418] Compiling version.sh
13:19:40 runner ' sh ../version.sh --cwd="/usr/ports/multimedia/mpv/work/mpv-0.25.0" --versionh="version.h" '
+ install /usr/ports/multimedia/mpv/work/stage/usr/local/bin/mpv (from build/mpv)
+ install /usr/ports/multimedia/mpv/work/stage/usr/local/share/examples/mpv/input.conf (from etc/input.conf)
+ install /usr/ports/multimedia/mpv/work/stage/usr/local/share/examples/mpv/mpv.conf (from etc/mpv.conf)
+ install /usr/ports/multimedia/mpv/work/stage/usr/local/share/examples/mpv/mplayer-input.conf (from etc/mplayer-input.conf)
+ install /usr/ports/multimedia/mpv/work/stage/usr/local/share/examples/mpv/restore-old-bindings.conf (from etc/restore-old-bindings.conf)
+ symlink /usr/ports/multimedia/mpv/work/stage/usr/local/lib/libmpv.so (to libmpv.so.1.24.0)
+ symlink /usr/ports/multimedia/mpv/work/stage/usr/local/lib/libmpv.so.1 (to libmpv.so.1.24.0)
+ install /usr/ports/multimedia/mpv/work/stage/usr/local/include/mpv/client.h (from libmpv/client.h)
+ install /usr/ports/multimedia/mpv/work/stage/usr/local/include/mpv/qthelper.hpp (from libmpv/qthelper.hpp)
+ install /usr/ports/multimedia/mpv/work/stage/usr/local/include/mpv/opengl_cb.h (from libmpv/opengl_cb.h)
+ install /usr/ports/multimedia/mpv/work/stage/usr/local/include/mpv/stream_cb.h (from libmpv/stream_cb.h)
+ install /usr/ports/multimedia/mpv/work/stage/usr/local/libdata/pkgconfig/mpv.pc (from build/libmpv/mpv.pc)
+ install /usr/ports/multimedia/mpv/work/stage/usr/local/share/doc/mpv/html/mpv.html (from build/DOCS/man/mpv.html)
+ install /usr/ports/multimedia/mpv/work/stage/usr/local/man/man1/mpv.1 (from build/DOCS/man/mpv.1)
+ install /usr/ports/multimedia/mpv/work/stage/usr/local/share/applications/mpv.desktop (from etc/mpv.desktop)
+ install /usr/ports/multimedia/mpv/work/stage/usr/local/share/zsh/site-functions/_mpv (from build/etc/_mpv)
+ install /usr/ports/multimedia/mpv/work/stage/usr/local/etc/mpv/encoding-profiles.conf (from etc/encoding-profiles.conf)
+ install /usr/ports/multimedia/mpv/work/stage/usr/local/share/icons/hicolor/16x16/apps/mpv.png (from etc/mpv-icon-8bit-16x16.png)
+ install /usr/ports/multimedia/mpv/work/stage/usr/local/share/icons/hicolor/64x64/apps/mpv.png (from etc/mpv-icon-8bit-64x64.png)
+ install /usr/ports/multimedia/mpv/work/stage/usr/local/share/icons/hicolor/32x32/apps/mpv.png (from etc/mpv-icon-8bit-32x32.png)
+ install /usr/ports/multimedia/mpv/work/stage/usr/local/share/icons/hicolor/scalable/apps/mpv.svg (from etc/mpv-gradient.svg)
+ install /usr/ports/multimedia/mpv/work/stage/usr/local/share/icons/hicolor/symbolic/apps/mpv-symbolic.svg (from etc/mpv-symbolic.svg)
+ install /usr/ports/multimedia/mpv/work/stage/usr/local/lib/libmpv.so.1.24.0 (from build/libmpv.so)
* Node /usr/ports/multimedia/mpv/work/stage/usr/local/lib/libmpv.so is created more than once (full message on 'waf -v -v'). The task generators are:
  1. 'mpv' in /usr/ports/multimedia/mpv/work/mpv-0.25.0
  2. 'mpv' in /usr/ports/multimedia/mpv/work/mpv-0.25.0
If you think that this is an error, set no_errcheck_out on the task instance
Waf: Leaving directory `/usr/ports/multimedia/mpv/work/mpv-0.25.0/build'
'install' finished successfully (0.940s)
```
### Log file

http://sprunge.us/FbfF

**Comment by thebombzen** [comment] 2018-01-13 18:01
Use the version of waf that comes with mpv.

**Comment by jcowgill** [comment] 2018-01-15 00:21
I think 1.9.8 is the version of waf that mpv 0.25 uses.

I can reproduce a similar error against git master if I configure with `--enable-libmpv-shared`. You need to build using `waf -v`.
```
[468/468] Symlinking build/libmpv.so
* Node /home/jcowgill/deb-pkg/mpv/upstream/build/mpv.def is created more than once (full message on 'waf -v -v'). The task generators are:
  1. 'mpv' in /home/jcowgill/deb-pkg/mpv/upstream
  2. 'mpv' in /home/jcowgill/deb-pkg/mpv/upstream
If you think that this is an error, set no_errcheck_out on the task instance
Waf: Leaving directory `/home/jcowgill/deb-pkg/mpv/upstream/build'
```

And then when installing:
```
$ python3 ./waf -v install --destdir=out
Waf: Entering directory `/home/jcowgill/deb-pkg/mpv/upstream/build'
[1/1] Compiling version.sh
00:02:44 runner ' sh ../version.sh --cwd="/home/jcowgill/deb-pkg/mpv/upstream" --versionh="version.h" '
- install /home/jcowgill/deb-pkg/mpv/upstream/out/usr/local/share/doc/mpv/input.conf (from etc/input.conf)
- install /home/jcowgill/deb-pkg/mpv/upstream/out/usr/local/share/doc/mpv/mpv.conf (from etc/mpv.conf)
- install /home/jcowgill/deb-pkg/mpv/upstream/out/usr/local/share/doc/mpv/mplayer-input.conf (from etc/mplayer-input.conf)
- install /home/jcowgill/deb-pkg/mpv/upstream/out/usr/local/share/doc/mpv/restore-old-bindings.conf (from etc/restore-old-bindings.conf)
- symlink /home/jcowgill/deb-pkg/mpv/upstream/out/usr/local/lib/libmpv.so (to libmpv.so.1.26.0)
- symlink /home/jcowgill/deb-pkg/mpv/upstream/out/usr/local/lib/libmpv.so.1 (to libmpv.so.1.26.0)
- install /home/jcowgill/deb-pkg/mpv/upstream/out/usr/local/include/mpv/client.h (from libmpv/client.h)
- install /home/jcowgill/deb-pkg/mpv/upstream/out/usr/local/include/mpv/qthelper.hpp (from libmpv/qthelper.hpp)
- install /home/jcowgill/deb-pkg/mpv/upstream/out/usr/local/include/mpv/opengl_cb.h (from libmpv/opengl_cb.h)
- install /home/jcowgill/deb-pkg/mpv/upstream/out/usr/local/include/mpv/stream_cb.h (from libmpv/stream_cb.h)
- install /home/jcowgill/deb-pkg/mpv/upstream/out/usr/local/lib/pkgconfig/mpv.pc (from build/libmpv/mpv.pc)
- install /home/jcowgill/deb-pkg/mpv/upstream/out/usr/local/share/man/man1/mpv.1 (from build/DOCS/man/mpv.1)
- install /home/jcowgill/deb-pkg/mpv/upstream/out/usr/local/share/applications/mpv.desktop (from etc/mpv.desktop)
- install /home/jcowgill/deb-pkg/mpv/upstream/out/usr/local/etc/mpv/encoding-profiles.conf (from etc/encoding-profiles.conf)
- install /home/jcowgill/deb-pkg/mpv/upstream/out/usr/local/share/icons/hicolor/16x16/apps/mpv.png (from etc/mpv-icon-8bit-16x16.png)
- install /home/jcowgill/deb-pkg/mpv/upstream/out/usr/local/share/icons/hicolor/32x32/apps/mpv.png (from etc/mpv-icon-8bit-32x32.png)
- install /home/jcowgill/deb-pkg/mpv/upstream/out/usr/local/share/icons/hicolor/64x64/apps/mpv.png (from etc/mpv-icon-8bit-64x64.png)
- install /home/jcowgill/deb-pkg/mpv/upstream/out/usr/local/share/icons/hicolor/symbolic/apps/mpv-symbolic.svg (from etc/mpv-symbolic.svg)
- install /home/jcowgill/deb-pkg/mpv/upstream/out/usr/local/share/icons/hicolor/scalable/apps/mpv.svg (from etc/mpv-gradient.svg)
- install /home/jcowgill/deb-pkg/mpv/upstream/out/usr/local/lib/libmpv.so.1.26.0 (from build/libmpv.so)
- install /home/jcowgill/deb-pkg/mpv/upstream/out/usr/local/bin/mpv (from build/mpv)
* Node /home/jcowgill/deb-pkg/mpv/upstream/build/mpv.def is created more than once (full message on 'waf -v -v'). The task generators are:
  1. 'mpv' in /home/jcowgill/deb-pkg/mpv/upstream
  2. 'mpv' in /home/jcowgill/deb-pkg/mpv/upstream
If you think that this is an error, set no_errcheck_out on the task instance
* Node /home/jcowgill/deb-pkg/mpv/upstream/out/usr/local/lib/libmpv.so is created more than once (full message on 'waf -v -v'). The task generators are:
  1. 'mpv' in /home/jcowgill/deb-pkg/mpv/upstream
  2. 'mpv' in /home/jcowgill/deb-pkg/mpv/upstream
If you think that this is an error, set no_errcheck_out on the task instance
Waf: Leaving directory `/home/jcowgill/deb-pkg/mpv/upstream/build'
'install' finished successfully (1.377s)
```

**Comment by thebombzen** [comment] 2018-01-15 03:45
mpv 0.25.0 is not the latest version of mpv, so that doesn't matter. If it still doesn't work with the latest version, report back.

**Comment by jcowgill** [comment] 2018-01-15 08:11
Did you read what I wrote?

**Comment by thebombzen** [comment] 2018-01-15 08:48
Yes, but is this actually an issue? It's only reported in verbose mode, reports `'install' finished successfully` and tells you what to do "if you think this is an error."

**Comment by avih** [comment] 2018-01-15 09:16
This also sometimes happen on windows with `-v` but for `mpv.rc`. It looks like an error because it's printed in error colors - bold red. IIRC this also happens with latest waf (2.0.x), but not 100% sure.

Maybe there's some race condition which triggers with different timing of `-v` ?

**Comment by shengyang998** [comment] 2018-10-08 09:30
Same issue here with waf version `2.0.9` when using `./waf build --enable-libmpv-shared -v` in macOS Mojave.

**Comment by Akemi** [comment] 2018-10-08 09:51
> 1.9.8 is what bootstrap downloads with mpv git master.

nope it's [2.0.9](https://github.com/mpv-player/mpv/blob/master/bootstrap.py#L8).

**Comment by clort81** [comment] 2020-04-13 15:11
in case this helps anyone, i can avoid getting the error by not supplying --enable-libmpv-shared during waf configure

**Comment by Dudemanguy** [comment] 2023-01-15 16:56
Old + waf is now deprecated so closing.

**Closed by Dudemanguy** 2023-01-15 16:56 UTC
Labels: core:waf
