### ISSUE TITLE
With --vo=dmabuf-wayland subtitles over the black bars stay visible

### ISSUE THREAD

**Issue by eternal-sorrow** [mpv-player/mpv#13318] opened 2024-01-19 21:03 UTC
### Important Information

Provide following Information:
- mpv version **0.37.0**
- Linux Distribution and Version **Gentoo latest**
- Source of the mpv binary **built by portage**
- If known which version of mpv introduced the problem **don't know**
- Window Manager and version  **sway**
- GPU model, driver and version **AMD renoir APU**
- Possible screenshot or video of visual glitches
![2024-01-20-062628](https://github.com/mpv-player/mpv/assets/4847726/ea6cb653-85dc-4f75-b645-ec4ab97e9735)
The screenshot shows that the part of the subtitle that is shown over the video is not visible anymore (as it should), but the part below over the black bar is still visible.

### Reproduction steps
1. Play a video with subtitles. I tested only with SRT subtitles, don't know about ASS. Make sure you are using `vo=dmabuf-wayland`.
2. Set the window size so that there are black bars on the top and bottom of the window. Make sure that the subtitles are displayed (fully or partially) over the black bars.
3. Wait for a moment in the video when there is a gap between subtitles.

I was able to reproduce the issue with `--no-config --vo=dmabuf-wayland`, so I would say it's always reproducible. 

### Expected behavior
Subtitles are displayed for their time period and then not visible anymore when there is no subtitle.

### Actual behavior
Subtitles stay visible until there is a new subtitle to replace it. In fact triggering any OSD hides the subtitle (but then this OSD stays visible). Only a part of subtitles that is displayed over the black bars stays visible.

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/13994425/output.txt)

### Sample files
Any file with subtitles would do. For me it's an MKV file with built in SRT subtitles.

**Comment by Dudemanguy** [comment] 2024-01-20 06:19
I am not able to reproduce this with my attempts.

**Comment by ayushnix** [comment] 2024-01-23 16:47
I can reproduce this behavior along with blinking OSD when enabling `dmabuf-wayland` when using mpv 0.37.0 on sway window manager. For the latter behavior, all I need to do is click somewhere on the OSD, like changing the subtitle track, and when moving away the cursor from the OSD, the OSD starts blinking rapidly.

**Comment by llyyr** [comment] 2024-01-23 19:00
I can't reproduce this issue on sway master, would be interesting if OP is also on sway 1.8.1 as that would likely mean the issue is with sway/wlroots and has been fixed on master already

**Comment by eternal-sorrow** [comment] 2024-01-23 19:04
Yes, I use sway 1.8.1.

**Comment by Dudemanguy** [comment] 2024-01-23 19:08
FWIW I can't reproduce on 1.8.1 either.

**Comment by diederikdehaas** [comment] 2024-08-19 15:11
I've been able to reproduce the issue on sway 1.9 with videos with a 'non-standard' resolution.

F.e. grab the following video with a 1920x720 resolution:  
``yt-dlp https://www.youtube.com/watch?v=h9knc_OUe9Y``

And then when playing either ``I`` for video metadata or ``O`` for playing time makes the issue visible for me.

It's visible for me on a PineTab2 (arm64) with Mali-G52 MP2 GPU and a 1280x800 resolution.
But also on my normal PC (amd64) with Radeon RX Vega 64 GPU on a 24" monitor with 1920x1080 resolution.

**Comment by Dudemanguy** [comment] 2024-08-19 16:00
Okay I'm able to reproduce this in sway 1.9 but not sway master nor weston. So I think this is just a sway bug that is already fixed upstream.

**Comment by diederikdehaas** [comment] 2024-08-19 16:30
I hope in the not to distant future to test sway's 1.10 branch (with wlroots 0.18) and I'll report back my finding.
But good to know that it's (likely) fixed :-)

**Comment by diederikdehaas** [comment] 2024-08-25 23:03
> I hope in the not to distant future to test sway's 1.10 branch (with wlroots 0.18) and I'll report back my finding.

I can confirm that with Sway 1.10 (and wlroots 0.18) the problem is fixed \o/

**Comment by kasper93** [comment] 2024-08-25 23:07
Fixed upstream.

**Closed by kasper93** 2024-08-25 23:07 UTC
Labels: down-upstream, os:linux, vo:dmabuf-wayland
