### ISSUE TITLE
Fast forward and rewind don't work for S3M audio file

### ISSUE THREAD

**Issue by shmerl** [mpv-player/mpv#9176] opened 2021-09-02 17:15 UTC
### Important Information

mpv version: **0.32.0**
OS: Debian testing Linux, mpv from the repo.

### Reproduction steps

Playing an S3M audio file, fast forwarding and rewinding aren't working. It just jumps to the beginning every time you try to use either one.

Example file to test: 

* The Blue Valley: [page](https://modarchive.org/index.php?request=view_by_moduleid&query=37685), [download](https://api.modarchive.org/downloads.php?moduleid=37685#blue_val.s3m).

**Comment by ValZapod** [comment] 2021-09-09 03:06
It works here, dunno.

> It just jumps to the beginning every time you try to use either one.

Both forward and backward seeking works. Please note that libopenmpt is something that is just a wrapper in ffmpeg...  https://github.com/FFmpeg/FFmpeg/blob/25c8507818d8559a6654a5b30a0f8aae11a48181/libavformat/libopenmpt.c

You need latest version of it, etc.

**Comment by shmerl** [comment] 2021-09-09 03:07
Here is full info:

```
mpv --version
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.51.100 (runtime 56.70.100)
   libavcodec      58.91.100 (runtime 58.134.100)
   libavformat     58.45.100 (runtime 58.76.100)
   libswscale      5.7.100 (runtime 5.9.100)
   libavfilter     7.85.100 (runtime 7.110.100)
   libswresample   3.7.100 (runtime 3.9.100)
ffmpeg version: 4.4-5
```

**Comment by shmerl** [comment] 2021-09-09 03:08
I think this could be the same as #2931.

**Comment by ValZapod** [comment] 2021-09-09 03:10
Actually the problem is see EOF in  00:06:06 which is BS.

**Comment by ValZapod** [comment] 2021-09-09 03:12
> mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects

Too old. But yeah, there is a bug that it stops playing it in  00:06:06.

**Comment by ValZapod** [comment] 2021-09-09 03:18
> I think this could be the same as #2931.

Yes, that is that part of it.

>While precise seeking partially works, if I seek while the playback is above 50% with mod files, it will just skip to the end and play the next song (or stop playing).

Unfortunately, 

>Sounds like a ffmpeg issue too.

So an ffmpeg upstream issue. Alas.

**Comment by shmerl** [comment] 2021-09-09 03:20
Is there a bug for it in ffmpeg or I should open one?

**Comment by ValZapod** [comment] 2021-09-09 03:55
> Is there a bug for it in ffmpeg

Seek does not work in ffmpeg at all, as you can see in reference binaries from gyand: 

https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z

**Comment by ValZapod** [comment] 2021-09-11 13:32
@richardpl I mean in ffplay. Oogh.

**Comment by Dudemanguy** [comment] 2022-01-19 03:05
Seeking works fine with that file (0.32 is too old probably) on git master. The file not seeking past the 06:06 appears to be a legitimate bug but that's separate from the OP and is an ffmpeg issue. Closing.

**Closed by Dudemanguy** 2022-01-19 03:05 UTC
