### ISSUE TITLE
black screen on macOS 10.14 public beta

### ISSUE THREAD

**Issue by loricheung** [mpv-player/mpv#6099] opened 2018-09-01 05:24 UTC
### mpv version and platform

mpv 91786fa Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sat Sep  1 13:07:49 CST 2018
ffmpeg library versions:
   libavutil       56.14.100
   libavcodec      58.18.100
   libavformat     58.12.100
   libswscale      5.1.100
   libavfilter     7.16.100
   libswresample   3.1.100
ffmpeg version: 4.0.2

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Actual behavior
if open video file via mpv, it will be crashed immediately, 
if using mpv video/file/path in terminal, it's always black screen

### Log file
[mpv.txt](https://github.com/mpv-player/mpv/files/2342089/mpv.txt)

**Comment by Akemi** [comment] 2018-09-01 09:04
don't file two issue in one. the crash is a duplicate of #5908 and fixed with #5953. 

try with `--no-config` and post another log. your log is quite polluted with unnecessary things, like old and not needed plugins and what not. also you are using `vo=gpu` which is deprecated and not supported (it even gives you a warning on the command line and log), one of the things you should not set in your config because it was default before anyway.

**Closed** 2018-09-02 10:36 UTC
