### ISSUE TITLE
mpv with ordered chapters: mpv plays to much frames

### ISSUE THREAD

**Issue by mooooonbaby** [mpv-player/mpv#2264] opened 2015-08-30 06:29 UTC
hi,

the main reason i installed mpv on my htpc was that it can playback mkv with ordered chapters. now i've played my first file with oc and i've seen the first problem. mpv plays one (or a few) frame(s) to much as it should. this is how the first 3 chapters looks like (there is a normal version of that film first and after the final credits there are the alternatice scenes - the version i tried starts with alternatives screnes):

01:56:08.670 - 01:58:35.984
01:58:35.984 - 01:59:51.393
00:04:42.741 - 00:06:09.703

i have the problem when the plays jumps from 01:59:51.393 to 00:04:42.741. here mpv plays one or a few frames after timestamp 01:59:393 and than jumps to 00:04:42.741. i have this problem on windows and linux. on linux i use build from aug 21, on windows from aug 27. i can play the file with mpc-hc+lav and vlc on windows and with vlc on linux without problems. the frames at positions 01:59:51.393 and 00:04:42.741 are both i (or idr) frames (ffmpeg only shows my i frame, but maybe its idr).

i've tried option --chapter-merge-threshold=100, but doesn't work.

moonbaby

**Comment by wm4** [comment] 2015-08-30 10:37
Matroska doesn't really specify how chapters are to be merged, so it's possible that there are differences. Do you have a sample file that shows this issue better?

**Comment by mooooonbaby** [comment] 2015-08-30 15:50
i have a sample, but the file is 12gb big and i'm not sure if i can produce this behavior with an other file. i have more than 1 mkv with ordered chapters and at the moment this is the only file i found such an error.

i'll see if i can create a small sample.

**Comment by lachs0r** [comment] 2016-11-05 21:35
No sample, cannot reproduce it with my own files.

**Closed by lachs0r** 2016-11-05 21:35 UTC
Labels: info-needed
