### ISSUE TITLE
VideoToolbox based hwaccel decoder?

### ISSUE THREAD

**Issue by jjgod** [mpv-player/mpv#2039] opened 2015-06-11 13:04 UTC
From [OS X v10.11 release notes (pre-release)](https://developer.apple.com/library/prerelease/mac/releasenotes/MacOSX/WhatsNewInOSX/Articles/MacOSX10_11.html):

> The following frameworks are no longer part of the OS X SDK as of version 10.11: **VideoDecodeAcceleration**. Use `VideoToolbox.framework` instead.

Do we have a `VideoToolbox` based implementation as a replacement for current [vda implementation](https://github.com/mpv-player/mpv/blob/master/video/decode/vda.c)?

Looks like most of the changes is in ffmpeg/libav. I wonder how did [Sebastien Zwickert's patchset](http://ffmpeg.org/pipermail/ffmpeg-devel/2012-September/130716.html) go.

CC @pigoz, @dilaroga.

**Comment by wm4** [comment] 2015-06-11 13:10
Depends mostly on FFmpeg.

Someone in FFmpeg is actually working on updating these patches.

**Comment by jjgod** [comment] 2015-06-11 13:11
@wm4: cool, is there a new thread discussing it? or is it just you heard from someone :)

**Comment by wm4** [comment] 2015-06-11 13:25
ffmpeg IRC channel

**Comment by pigoz** [comment] 2015-06-11 13:51
@jjgod Thanks for the issue, I had no idea about the removal of VDA. I took a look at @dilaroga patchset  about one month ago and it doesn't look like it would take a lot of time to update it (I was considering posting some updated patches to libav). If someone else is doing it, all the better!

**Comment by jjgod** [comment] 2015-06-11 13:56
It's quite straightforward to update it seems. I just did a rebase at https://github.com/jjgod/FFmpeg/commit/b69c2878fc0f80c0b66a5ab1f4488016f3818353

I haven't tried to see if it actually works yet, I guess I will need to make something like current vda.c in mpv to test it.

**Comment by wm4** [comment] 2015-06-11 14:03
If you want to do anything, get in touch with ubitux on the FFmpeg IRC channel. I think he also did some steps into this direction.

**Comment by wm4** [comment] 2015-06-11 14:04
> FFmpeg IRC channel

Which is #ffmpeg-devel on http://chat.freenode.net.

**Comment by wm4** [comment] 2015-06-11 14:05
>http://chat.freenode.net.

Err, that's not a web server, just the IRC server. Edited it. (Though there's a web based access on https://webchat.freenode.net/)

**Comment by jjgod** [comment] 2015-06-11 14:16
We still have https://github.com/mpv-player/mpv/blob/master/video/out/gl_hwdec_vda.c which seems to be more actively maintained, wasn't that considered a better approach than using hwaccel from ffmpeg?

**Comment by pigoz** [comment] 2015-06-11 14:24
That file takes the output of the VDA hwaccel (CVPixelBufferRef) from ffmpeg and renders it to screen with no readback.

**Comment by jjgod** [comment] 2015-06-11 14:28
For VideoToolbox we seems to be getting a `CVImageBufferRef` instead.

**Comment by wm4** [comment] 2015-06-11 14:31
Not really.
```
<ubitux> > typedef CVImageBufferRef CVPixelBufferRef;
<ubitux> lol ok
```

**Comment by wm4** [comment] 2015-06-11 14:33
PS: and the problem is that the FFmpeg hwaccel API enables hw decoding by selecting the pixel format in the decoder get_format callback. Possible solutions:
- create a separate pixfmt even if the data representation is different (for the sake of being able to select the hwdec API)
- disable VDA compilation if VT is available (but makes it hard to create universal binaries)
- use the FFmpeg VDA API for VT, and transparent switch to VT under the hood if it's available

**Comment by pigoz** [comment] 2015-06-11 14:38
The old patch uses a separate fixfmt (`AV_PIX_FMT_VIDEOTOOLBOX_VLD `) even if you get out the same output (VDA is a wrapper of VideoToolbox from the times when VideoToolbox was a private API). That would make it ideal for libavcodec clients IMHO. For example in mpv we could use `gl_hwdec_vda.c` for both the VDA and VT hwaccels.

**Comment by jjgod** [comment] 2015-06-12 13:43
I'm a bit out of clue here, does it mean we don't need to define a corresponding `IMGFMT_VIDEOTOOLBOX` in mpv, and just use `IMGFMT_VDA` here?

**Comment by pigoz** [comment] 2015-06-12 14:05
I was thinking to just create a second struct and pointing it to the same functions in that file and define `imgfmt = IMGFMT_VIDEOTOOLBOX`.

**Comment by wm4** [comment] 2015-06-12 14:11
@pigoz: sounds like a good idea, if FFmpeg creates a second pixfmt.

Meanwhile, I heard the original author of the VT patches resumed working on them.

**Comment by jjgod** [comment] 2015-06-12 14:25
Cool. So basically I have implemented what we described above here: https://github.com/jjgod/mpv/commit/62479f8fb0b3ca9bdd63c6a7a8e995f80826d069

However when running `./build/mpv --hwdec=videotoolbox` with a sample H.264 video I got:

    Playing: /Users/jjgod/Downloads/712_hd_low_energy_high_performance_compression_and_accelerate.mp4
     (+) Video --vid=1 (*) (h264)
     (+) Audio --aid=1 --alang=und (*) (aac)
    Using hardware decoding.
    AO: [coreaudio] 44100Hz stereo 2ch float
    [ffmpeg/video] h264: get_buffer() failed
    [ffmpeg/video] h264: thread_get_buffer() failed
    [ffmpeg/video] h264: decode_slice_header error
    [ffmpeg/video] h264: get_buffer() failed
    [ffmpeg/video] h264: thread_get_buffer() failed
    [ffmpeg/video] h264: decode_slice_header error
    [ffmpeg/video] h264: get_buffer() failed
    [ffmpeg/video] h264: thread_get_buffer() failed
    [ffmpeg/video] h264: decode_slice_header error
    [ffmpeg/video] h264: get_buffer() failed
    [ffmpeg/video] h264: thread_get_buffer() failed
    [ffmpeg/video] h264: decode_slice_header error
    [ffmpeg/video] h264: no frame!
    Error while decoding frame!
    Hardware decoding failed, falling back to software decoding.
    VO: [opengl] 1280x720 yuv420p
    AV: 00:00:00 / 00:35:33 (0%) A-V:  0.000

Any idea what code might be missing?

**Comment by wm4** [comment] 2015-06-12 14:40
Most like the old VT patch still requires the user to set a get_buffer callback.

**Comment by pigoz** [comment] 2015-06-12 14:54
@wm4 Was that done defining `allocate_image` in our `gl_hwdec_driver`?

@jjgod see a9cb2dc1b86c0f3e12231abc776009fe0a8bcf0e

**Comment by jjgod** [comment] 2015-06-12 14:59
Thanks. I found https://github.com/FFmpeg/FFmpeg/commit/67afcefb35932b420998f6f3fda46c7c85848a3f but still don't have a clue about how this can be applied.

**Comment by wm4** [comment] 2015-06-12 15:02
vd_lavc_hwdec.allocate_image, yes. But I'm hoping that the VT patch keeps the simplicity of the current VDA API.

**Comment by jjgod** [comment] 2015-06-12 15:05
I am a bit confused here. Is allocate_image required by the new API or the
old one?

**Comment by pigoz** [comment] 2015-06-12 15:07
Hope so, the old API was so bad.

@jjgod to make your patch work you have to implement an allocate_image function in the mpv `gl_hwdec_driver ` struct, this is necessary is for the old hwaccel api (your rebased FFmpeg VideoTollbox patches use the old hwaccel API).

**Comment by dilaroga** [comment] 2015-06-14 16:37
FYI,
I rebased the videotoolbox patch for FFmpeg and updated it to target the new HWAccel API :)
https://github.com/dilaroga/mpv/commit/13ba0b529a14b800f904054e64d7674dd1442191

I forked mpv to add a development branch of videotoolbox to support ffmpeg haccel.
https://github.com/dilaroga/mpv/commit/13ba0b529a14b800f904054e64d7674dd1442191

@pigoz You're right, the gl_hwdec_vda.c is a good candidate to render frame buffer of videotoolbox. That's said I've encountered some difficulties to share the source between the vda-gl and the videotoolbox-gl in the build process. But I just discovered waf build system after cloning mpv ;)
Then in my dev steps I manually disabled VDA from my own FFmpeg build.

@jjgod Thanks for CC :)

@all Nice job, I'm really impressed by the ease of use of mpv.

**Comment by wm4** [comment] 2015-06-14 17:16
That's pretty awesome! I made some comments to the mpv part. We can merge it once the FFmpeg part lands.

I take it to plan to send patches to ffmpeg-devel?

**Comment by pigoz** [comment] 2015-06-14 18:05
@dilaroga great work! I added some minor comments for the mpv part.

**Comment by dilaroga** [comment] 2015-06-14 22:05
Thanks for review.

@vm4 I sent the patch to ffmpeg-devel with git send-mail but not yet received... I need to check my git send-mail configuration ;)

**Comment by wm4** [comment] 2015-06-16 08:22
>@vm4 I sent the patch to ffmpeg-devel with git send-mail but not yet received...

I don't see anything on the mailing list.

**Comment by pigoz** [comment] 2015-06-16 10:50
I think it maybe wasn't sent at all

**Comment by wm4** [comment] 2015-08-03 10:53
The ffmpeg patch was merged. Should we merge the mpv patch now?

**Comment by pigoz** [comment] 2015-08-03 12:36
It looks like our comments were addressed, so I guess we can merge it. I want to test the patch myself first though.

**Comment by pigoz** [comment] 2015-08-04 08:16
Patch works, we can merge whenever we want I guess. Anyone against?

**Comment by ottob** [comment] 2015-08-04 08:46
Nope, I have done some light testing on 10.10.4 and found no regression.

**Comment by pigoz** [comment] 2015-08-05 15:54
Pushed the patch to master. I changed it slightly to prefer VideoToolbox over VDA at runtime if both are available so it will be more widely tested.

@dilaroga Thanks a lot for your work both in mpv and libavcodec!

**Closed by pigoz** 2015-08-05 15:54 UTC
Labels: osx
