### ISSUE TITLE
Can't read the correct display fps in Gnome Wayland

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#4246] opened 2017-03-17 10:30 UTC
![2017-03-17 18-25-52](https://cloud.githubusercontent.com/assets/20014762/24039355/d122f326-0b3f-11e7-84a3-3a0b60861a1c.png)
### mpv version and platform

```
mpv git-076116a0e5 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Fri Mar 10 15:43:44 CST 2017
ffmpeg library versions:
   libavutil       55.34.101
   libavcodec      57.64.101
   libavformat     57.56.101
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.4
```

### Reproduction steps
Press Shift+i to show the stats
### Expected behavior
It shows the right display fps
### Actual behavior
It shows the wrong display fps
### Log file
```
[auto_profiles] Error evaluating: [string "profile Enable SVP condition"]:1: attempt to compare nil with number 
[auto_profiles] Error evaluating: [string "profile Below 540p condition"]:1: attempt to compare nil with number 
Playing: The Hateful Eight.mkv
[lavf] Using subtitle charset: utf-16le
 (+) Video --vid=1 (*) 'The.Hateful.Eight.2015.1080p.BluRay.x264.DTS-HD.MA.5.1-RARBG' (h264)
     Video --vid=2 [P] 'cover_land.jpg' (mjpeg)
     Video --vid=3 [P] 'small_cover.jpg' (mjpeg)
     Video --vid=4 [P] 'small_cover_land.jpg' (mjpeg)
     Video --vid=5 [P] 'cover.jpg' (mjpeg)
 (+) Audio --aid=1 --alang=eng (*) 'The.Hateful.Eight.2015.1080p.BluRay.x264.DTS-HD.MA.5.1-RARBG' (dts)
     Subs  --sid=1 --slang=eng (*) 'English-SDH-PGS' (hdmv_pgs_subtitle)
     Subs  --sid=2 --slang=spa 'Spanish-PGS' (hdmv_pgs_subtitle)
 (+) Subs  --sid=3 '.The Hateful Eight.srt' (subrip) (external)
File tags:
 Title: RARBG.COM - The.Hateful.Eight.2015.1080p.BluRay.x264.DTS-HD.MA.5.1-RARBG
[vo/opengl] retrieving framebuffer depth: OpenGL error INVALID_OPERATION.
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
AO: [pulse] 44100Hz stereo 2ch float
[auto_profiles] Applying profile Enable SVP 
[auto_profiles] Applying profile 704p 
Using hardware decoding (vaapi-copy).
VO: [opengl] 1920x704 nv12
AV: 00:00:00 / 02:47:44 (0%) A-V: -0.014 DS: 3.500/4 Dropped: 3
Opening video filter: [vapoursynth file=/home/laichiaheng/.local/share/SVP4/scripts/4e2722e8.py buffered-frames=4 concurrent-frames=7]
Using conversion filter.
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
AV: 00:00:00 / 02:47:44 (0%) A-V: -0.010 DS: 4.444/7 Dropped: 3
VO: [opengl] 1920x704 yuv420p
AV: 00:00:02 / 02:47:44 (0%) A-V: -0.081 DS: 2.090/15
[osd/libass] fontselect: Using default font family: (Source Sans Pro, 400, 0) -> /usr/share/fonts/noto/NotoSansCJK-Regular.ttc, 3, NotoSansCJKtc-Regular
[osd/libass] fontselect: Using default font family: (Source Sans Pro, 700, 0) -> /usr/share/fonts/noto/NotoSansCJK-Regular.ttc, 3, NotoSansCJKtc-Regular
AV: 00:00:12 / 02:47:44 (0%) A-V: -0.009 DS: 1.660/132 Dropped: 6
[vapoursynth] Filter error at frame 720: EOF or filter reinit/uninit
[vapoursynth] Filter error at frame 723: EOF or filter reinit/uninit
[vapoursynth] Filter error at frame 724: EOF or filter reinit/uninit
[vapoursynth] Filter error at frame 721: EOF or filter reinit/uninit
[vapoursynth] Filter error at frame 722: EOF or filter reinit/uninit
[vapoursynth] Filter error at frame 726: EOF or filter reinit/uninit
[vapoursynth] Filter error at frame 725: EOF or filter reinit/uninit
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 


Exiting... (Quit)

```

**Comment by atomnuker** [comment] 2017-03-17 10:47
Known bug, for now only video-sync=audio works with wayland.
That counter shows the frequency at which swaps happen.

**Comment by atomnuker** [comment] 2017-10-03 19:06
Duplicate of #3524

**Closed by atomnuker** 2017-10-03 19:06 UTC
Labels: wayland
