### ISSUE TITLE
pipewire (Linux): appears mpv does not flush the last samples

### ISSUE THREAD

**Issue by sta-c0000** [mpv-player/mpv#11974] opened 2023-07-20 12:16 UTC
### Important Information
mpv v0.35.1
Issue _specific_ to pipewire output on Linux.
pipewire 0.3.74 (wireplumber 0.4.14) (and previous)

### Problem
Appears mpv does not flush the last samples when using pipewire.
See: [pipewire gitlab issue - cuts off end of audio output when it is the only/last audio played](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3365)
Fix might also require: [pipewire gitlab commit - audioconvert: improve EMPTY flag on output buffers](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/ab1436fb3b880dbcb9ff709ac687d96e3545ccf4)

### Reproduction steps
Not really noticeable with small `pipewire-buffer` sizes, but more so the larger it is (or larger pipewire `default.clock.min-quantum`).  Make sure no other audio is being output (even if paused) on the system at the same time:
```
mpv --pipewire-buffer=100 /usr/share/sounds/sound-icons/percussion-10.wav # no sound
mpv --pipewire-buffer=100 /usr/share/sounds/sound-icons/percussion-12.wav # partial sound (first part only)
```
### Sample files
From: [speech-dispatcher sound icons](https://devel.freebsoft.org/pub/projects/sound-icons):
`percussion-10.wav` ("tok") ~ 30ms
`percussion-12.wav` ("tok"-"tik") ~ 130ms

**Comment by philipl** [comment] 2023-07-20 13:07
@t-8ch

**Comment by t-8ch** [comment] 2023-07-21 13:35
The Pipewire developer is taking a look.
I'll also try to reproduce it.

**Comment by llyyr** [comment] 2023-08-10 20:19
You also get glitchy output with a small enough buffer on mpv, like 1-10 which I can also reproduce glitchy output with `pw-play --latency {1-20} percussion-12.wav`

I can't reproduce the exact issue in this issue ticket with pw-play though, regardless of what latency I set

**Comment by sta-c0000** [comment] 2023-08-11 21:41
> I can't reproduce the exact issue in this issue ticket with pw-play though, regardless of what latency I set

With `pipewire 0.3.74` and lower?  `pipewire 0.3.75` and above include the fix for the drain issue with `pw-play`.

**Comment by llyyr** [comment] 2023-08-11 22:43
with pipewire 0.3.76, so that'd make sense

**Comment by Dudemanguy** [comment] 2024-01-21 04:07
Seems like it was fixed upstream? Closing. Feel free to reopen if I missed something.

**Closed by Dudemanguy** 2024-01-21 04:07 UTC
Labels: os:linux
