### ISSUE TITLE
vo=gpu-next still performs worse than vo=gpu + --gpu-api=vulkan with certain settings

### ISSUE THREAD

**Issue by Dudemanguy** [mpv-player/mpv#9479] opened 2021-11-19 17:05 UTC
### Important Information

- mpv version: e095bdb
- libplacebo version: [0bfc00b2](https://code.videolan.org/videolan/libplacebo/-/commit/0bfc00b2b0efcb3dcfcaa9b131c91cbb64f4acdb)
- Window Manager and version: Sway 1.6.1 (but it also happens in xorg with i3 4.20.1)
- GPU driver and version: RX 550 using amdgpu with mesa's radv (21.2.5)

### Reproduction steps

With the recent libplacebo + mpv changes, the performance has improved a bit on vo=gpu-next however it's still definitely behind vo=gpu on my machine with certain settings. When looking at the pass timers, the stats between the two are basically the same now (fresh frames and redraws) however vo=gpu-next drops frames much sooner so there's definitely something going on here. 

Like noted in the last issue, this issue only exists if you use `--video-sync=display-*` + `--interpolation=no` and watch a file with less FPS than your display (like a 24fps on a 60hz display). With that in mind, here's a bench profile for measuring since the pass timers must have some discrepancy.
```
[bench]
gpu-api=vulkan
audio=no
untimed=yes
wayland-disable-vsync=yes
video-sync=display-desync
vulkan-swap-mode=mailbox
#opengl-swapinterval=0
osd-msg1="FPS: ${estimated-display-fps}"
```

I'll do three scenarios here in addition to enabling the above bench profile:
- `profile=gpu-hq`
- `profile=gpu-hq` + `glsl-shaders-append="~~/shaders/FSRCNNX_x2_8-0-4-1.glsl"`
- `profile=gpu-hq` + `deband-iterations=16`

### Expected behavior

No significant difference.

### Actual behavior

These are all the same file of course (1080p upscaled to 4k).

`mpv --profile=bench --profile=gpu-hq`:
**vo=gpu**: Roughly around 227 fps.
**vo=gpu-next**: Roughly around 172 fps.

`mpv --profile=bench --profile=gpu-hq --glsl-shaders-append="~~/shaders/FSRCNNX_x2_8-0-4-1.glsl"`:
**vo=gpu**: Roughly around 88 fps.
**vo=gpu-next**: Roughly around 54 fps. Definitely under 60fps at this point.

`mpv --profile=bench --profile=gpu-hq --deband-iterationis=16`:
**vo=gpu**: Roughly around 50fps.
**vo=gpu-next**: Roughly around 30fps.

### Log file

Logs for the above cases in order.

Case 1:
[vo=gpu](https://0x0.st/-Rky.log)
[vo=gpu-next](https://0x0.st/-Rkt.log)

Case 2:
[vo=gpu](https://0x0.st/-Rkv.log)
[vo=gpu-next](https://0x0.st/-Rkw.log)

Case 3:
[vo=gpu](https://0x0.st/-Rkx.log)
[vo=gpu-next](https://0x0.st/-Rk3.log)

**Comment by haasn** [comment] 2021-11-19 20:44
And just to confirm, if you pick `--interpolation=yes --tscale=oversample` the performance numbers remain basically unchanged for `--vo=gpu` but increase for `--vo=gpu-next`?

**Comment by haasn** [comment] 2021-11-19 20:56
@Dudemanguy can you test with this patch applied to libplacebo?

```diff
diff --git a/src/renderer.c b/src/renderer.c
index 08975302..af690b44 100644
--- a/src/renderer.c
+++ b/src/renderer.c
@@ -2636,12 +2636,16 @@ bool pl_render_image_mix(pl_renderer rr, const struct pl_frame_mix *images,
         .info.stage = PL_RENDER_STAGE_BLEND,
     };
 
-    if (rr->disable_mixing || !FBOFMT(4))
+    if (rr->disable_mixing || !FBOFMT(4)) {
+        PL_WARN(rr, "bypassing cache: no fbos");
         goto fallback;
+    }
 
     bool single_frame = !params->frame_mixer || images->num_frames == 1;
-    if (single_frame && params->skip_caching_single_frame)
+    if (single_frame && params->skip_caching_single_frame) {
+        PL_WARN(rr, "bypassing cache: single frame");
         goto fallback;
+    }
 
     if (!pass_infer_state(&pass))
         return false;
```

It shouldn't show any warnings.

And also produce a log with `--msg-level=vo/gpu-next=trace` (probably add `--end=0:01` or something).

**Comment by Dudemanguy** [comment] 2021-11-19 20:59
>And just to confirm, if you pick --interpolation=yes --tscale=oversample the performance numbers remain basically unchanged for --vo=gpu but increase for --vo=gpu-next?

Not quite. Using `--tscale=oversample` always incurs a slight performance cost for me. Simply using the default `tscale` (mitchell) with interpolation, does not have notable difference with `--vo=gpu` and increases with `--vo=gpu-next`. tldr; yes but with `--tscale=mitchell` not `--tscale=oversample`. I'll try that patch in a second.

**Comment by Dudemanguy** [comment] 2021-11-19 21:10
@haasn:

>It shouldn't show any warnings.

I get that exact warning: "bypassing cache: single frame".
[trace log](https://0x0.st/-Rnq.log)

**Comment by haasn** [comment] 2021-11-19 21:18
@Dudemanguy and with this patch as well? (don't need trace verbosity anymore)

```diff
diff --git a/video/out/vo_gpu_next.c b/video/out/vo_gpu_next.c
index fca4165d03..d69d33bb3f 100644
--- a/video/out/vo_gpu_next.c
+++ b/video/out/vo_gpu_next.c
@@ -731,6 +731,7 @@ static void draw_frame(struct vo *vo, struct vo_frame *frame)
         }
     }
 
+    MP_WARN(vo, "DS: %d, num_vsyncs: %d, still: %d\n", frame->display_synced, frame->num_vsyncs, frame->still);
 #if PL_API_VER >= 179
     p->params.skip_caching_single_frame = !frame->display_synced || frame->num_vsyncs == 1;
 #endif
```

**Comment by haasn** [comment] 2021-11-19 21:22
Ah, nvm, I can reproduce on my end. Turns out I was testing wrong earlier (accidentally left --interpolation=yes on) when testing my previous commit.

Seems like mpv sometimes weirdly generates a frame pattern of 3:2:1:2:1:3:2:1:2:1 instead of the expected 3:2:3:2:3:2. This makes it seem very much like a bug somewhere in mpv - but I don't know what, why or where.

**Comment by Dudemanguy** [comment] 2021-11-19 21:24
>Seems like mpv sometimes weirdly generates a frame pattern of 3:2:1:2:1:3:2:1:2:1 instead of the expected 3:2:3:2:3:2.

Yup, that's the behavior I see here as well.

**Comment by haasn** [comment] 2021-11-19 21:37
Oh, I get it. The `num_vsyncs` means how many *more* vsyncs there will be of this frame. So for the display pattern 3:2:3:2, the first frame sees 3, 2, 1 redraws then the second frame sees 2, 1, then back to 3, 2, 1, etc.

What `--vo=gpu` does here is actually keep track of re-draws of the same frame using the unique ID. But it feels like a hack to reimplement that logic into `--vo=gpu-next`. I think the correct/elegant solution here is for libplacebo to always allow *reading* from the mixer cache, even with the bypass option enabled. (It would only bypass *writing* to it)

I'll fix it in libplacebo.

**Comment by haasn** [comment] 2021-11-19 22:17
@Dudemanguy should be fixed by https://code.videolan.org/videolan/libplacebo/-/merge_requests/201

**Comment by haasn** [comment] 2021-11-19 22:21
Note that `--vo=gpu-next` in this exact configuration will always remain *ever-so-slightly* slower than `--vo=gpu` (14.506 ms vs 14.359 ms in my test run), due to differences in design, that are described in 75ee35ce.

**Comment by Dudemanguy** [comment] 2021-11-19 22:39
Yeah that PR is a massive improvement. The benchmarks are now essentially the same in this case.

There is one, additional slight difference in behavior though. I imagine this is hard to reproduce though. In mpv with my usual settings, there is normally like a handful of mistimed/delayed frames at the very beginning during startup (like 4-5 frames). This quickly goes away though once things (I assume) "sync up". In `vo=gpu-next`, this brief period lasts quite a bit longer (more like 20ish-30 frames). After that, it settles on the correct fps and works normally. I am using `profile=gpu-hq`, `video-sync=display-resample`, and `glsl-shaders-append="~~/shaders/FSRCNNX_x2_8-0-4-1.glsl"` which is on the borderline of being playable for me with my GPU so that might be why I see this increased instability in this particular edge case.

**Comment by haasn** [comment] 2021-11-19 22:46
Something we could try doing to address that permanently is giving the vo a 'rev up' period on the first frame after a video reset, before we start timing. This is something I've long wished for the old vo as well.

But it will have to wait.

**Closed** 2021-11-19 22:46 UTC
Labels: os:linux
