### ISSUE TITLE
First subtitle track (PGS or SUB) is not working

### ISSUE THREAD

**Issue by FCrane** [mpv-player/mpv#12118] opened 2023-08-09 17:06 UTC
The latest 2 (at least) nightlies introduced a subtitle problem with mkv files: if the mkv contains subtitles in PGS or SUB format, the first subtitle stream is not displayed (even when explicitly selected). 2nd, 3rd, etc. subtitle streams are shown correctly, just first one is invisible.

Provide following Information:
- mpv version: libmpv latest nightly
- Windows Version: 11
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/
- If known which version of mpv introduced the problem: at least the 2 latest nightlies, maybe even further back (cannot test)

### Reproduction steps
play an mkv with subtitle streams (PGS or SUB format) -> selecting the first subtitle stream does not display it. The others seem to work. Only seems to affect PGS and SUB, SRT works fine.

### Expected behavior
Show the selected subtitle stream (as it always used to work)

### Actual behavior
First (if PGS or SUB) is not shown

**Comment by Traneptora** [comment] 2023-08-09 20:15
Can you please provide a log file? And perhaps a sample too, if possible.

**Comment by FCrane** [comment] 2023-08-09 21:38
It's libmpv used by a custom front-end, so I don't really know how to start it with --no-config.

I've also already deleted the new version because it was unusable, so it's hard to test. 

Sample is not really needed, because it occurs with all mpv files containing PGS or SUB subtitles. Old version plays all files correctly.

**Comment by Dudemanguy** [comment] 2023-08-09 23:37
I would greatly appreciate a sample file since I can't reproduce it on the one file I have.

**Comment by FCrane** [comment] 2023-08-10 21:39
Unfortunately, this is not reproducible reliably with small clips - sometimes it works, sometimes it doesn't. Sometimes it works after stopping the video and restarting it. Sometimes not. With the small (25MB) limit here, it's not possible to generate a clip long enough to show the effect reliably.

It's similar to a problem with the audio tracks, that has always existed in all versions of libmpv: when switching audio tracks, sometimes (very rarely) they are silent and I need to skip forward or back to make them audible again. But this doesn't happen very often. 

But the subtitle problem happens almost everytime for every mkv. If I use a libmpv that's a few months old, the subtitles always work perfectly. So there is definitely a problem in the newer versions, because nothing else has changed on my system.

**Comment by guahirah** [comment] 2023-08-11 05:59
The last build forces the default subtitle track to English, whereas in the MKV file default track is set to another language.

**Comment by llyyr** [comment] 2023-08-11 08:20
That's unrelated to this issue but it should be fixed by #12100

**Comment by FCrane** [comment] 2023-09-06 09:53
The problem seems to be gone with the latest nightly build! Thank goodness ;-)

**Closed** 2023-09-06 12:59 UTC
Labels: os:win, priority:ignored-issue-template
