### ISSUE TITLE
Video/audio loops/freezes on SIGTSTP/SIGCONT

### ISSUE THREAD

**Issue by forthrin** [mpv-player/mpv#12226] opened 2023-08-23 06:10 UTC
### Important Information

- mpv version: af9b53f3a
- macOS Version: 13.4.1
- Source of the mpv binary or bundle: Git
- If known which version of mpv introduced the problem: N/A
- Possible screenshot or video of visual glitches: N/A
- First mention: #11330

### Reproduction steps

1. `mpv --config=no --log-file=foo.log foo.mkv`
2. `Ctrl + Z`: The audio buffer loops. If also running Spotify, its audio will be warped.
4. `fg`: If wearing AirPods, video *or* audio is frozen. Fast forwarding actually works, yet frozen.

### Expected behaviour

- Audio should stop without noise (audio loop) when the app receives SIGTSTP.
- Video and audio should continue flawlessly when the app receives SIGCONT.

### Actual behavior

See 4 and 6 in reproduction.

### Log file

[foo.log](https://github.com/mpv-player/mpv/files/12415734/foo.log)

Note: No logging happens when the issue occurs.

### Sample files

Happens with many videos. Seems not related to content, but let me know if you need a sample.

**Comment by Akemi** [comment] 2024-10-14 13:51
is this still reproducible? it isn't on my end. in my case the `audio buffer loops` only does it twice/trice and not indefinitely, or is that what you meant? resuming with `fg` works as intended and without problems.

**Comment by forthrin** [comment] 2024-10-14 14:13
Tried this with a couple of videos and audio files.

- Buffer does not loop.
- Spotify does not interfer.
- Continue flawlessly.

Didn't test with AirPods.

By all accounts someone fixed this at some point. Great! Suggest closing this one.

**Comment by Akemi** [comment] 2024-10-14 14:52
closing it. if you encounter the problem again. feel free to let me know here and we can reopen this one, or open a new issue.

thank you.

**Closed by Akemi** 2024-10-14 14:52 UTC
Labels: os:mac
