### ISSUE TITLE
wayland-dmabuf: display is not damaged/rerended outside the content surface when OSD surfaces are hidden

### ISSUE THREAD

**Issue by nagisa** [mpv-player/mpv#14965] opened 2024-10-01 11:15 UTC
### mpv Information

```bash
mpv 0.39.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Jan  1 1980 00:00:00
libplacebo version: v7.349.0
FFmpeg version: 6.1.2
FFmpeg library versions:
   libavcodec      60.31.102
   libavdevice     60.3.100
   libavfilter     9.12.100
   libavformat     60.16.100
   libavutil       58.29.100
   libswresample   4.12.100
   libswscale      7.5.100
```

### Other Information

```text
- Linux version: NixOS
- Kernel Version: Linux * 6.10.10 #1-NixOS SMP PREEMPT_DYNAMIC Thu Sep 12 09:13:13 UTC 2024 x86_64 GNU/Linux
- GPU Model: Radeon RX 7700 XT / 7800 XT
- Mesa/GPU Driver Version: mesa-24.2.2
- Window Manager and Version: Sway 1.9
- Source mpv: NixOS package
- Introduced in version: Been present for a long time, including throughout 0.38.
```

### Reproduction Steps

0. Obtain media without subtitles that's not the same aspect ratio as the monitor (e.g. 16:9 content on 21:9 screens);
1. `mpv --no-config --vo=dmabuf-wayland $CONTENT`
2. `f`
3. `^O ^O` or `^P` and wait a sec.

### Expected Behavior

The OSD drawings are cleared completely once they are hidden.

### Actual Behavior

The parts of screen on which OSD was drawn but which is not covered by the media content are not damaged and redrawn once the OSD is hidden. This means that the OSD parts that were drawn on the "black bars" remains visible until something else damages that part of the window.

### Log File

[output.txt](https://github.com/user-attachments/files/17204055/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by nagisa** [comment] 2024-10-01 11:18
This ends up looking something like this: 
![20241001_14h16m50s_grim](https://github.com/user-attachments/assets/d86f90bf-4011-4f3c-b48e-65121aa675f4)
![20241001_14h17m28s_grim](https://github.com/user-attachments/assets/072fce89-8340-441c-9686-7ed69536ee70)

**Comment by llyyr** [comment] 2024-10-01 12:31
Can you try updating sway? I can't reproduce since the scene graph PR was merged

**Comment by nagisa** [comment] 2024-10-01 13:07
Not right now, but from the looks of it 1.10 is about to be released shortly, so I'm going to hold out until that comes out proper.

**Comment by kasper93** [comment] 2024-10-01 13:12
> - Window Manager and Version: Sway 1.9

Duplicate of https://github.com/mpv-player/mpv/issues/13318

**Closed by kasper93** 2024-10-01 13:12 UTC
Labels: os:linux
