### ISSUE TITLE
Playback is reset to the beginning whever I try to seek forward (4K 60FPS HEVC)

### ISSUE THREAD

**Issue by vorou** [mpv-player/mpv#10876] opened 2022-11-16 06:29 UTC
- mpv version: 0.35.0
- macOS Version: 12.6.1
- Source of the mpv: homebrew
- Sample video: https://0x0.st/oIjs.MOV
- Only happens with a 4K 60FPS video, can't repro with 4K 30FPS

### Reproduction steps

1. Open the sample video
```
mpv --no-config oljs.MOV
```
2. Press RIGHT to seek forward

### Expected behavior

The playback jumps to +5 seconds

### Actual behavior

The playback does jump to +5 seconds but then immediately jumps to the beginning of the file

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/10018712/output.txt)

### Sample files

https://0x0.st/oIjs.MOV

**Comment by CounterPillow** [comment] 2022-11-16 07:33
This looks to be an issue with the container. mpv by default does fast seeks for left/right arrow. You can test a precise seek by clicking on the seek bar at 5 seconds, and notice that it works fine. Furthermore, remuxing the file with `ffmpeg -i input.MOV -c copy output.mp4` fixes the problem in the file.

You can also adjust your input.conf to do precise seeks for left/right arrow, but they are slower.

**Comment by vorou** [comment] 2022-11-16 20:47
thanks for looking into this! can confirm remuxing and precise seeking fix it for me too.

that said, I'm confused about the statement

> This looks to be an issue with the container.

does it mean there's something wrong with the file itself? it sounds weird because:

1. I'm importing them directly from iPhone 12 with no alterations whatsoever
2. Previously they would fast seek just fine with mpv (don't remember the mpv version though, will check if I have it on another machine)

**Comment by vorou** [comment] 2023-05-27 04:33
still an issue in the 0.35.1, fast seek works fine for the same file in 0.34.1

─>$ mpv --version
mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Sat Jan 28 04:49:47 2023
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
FFmpeg version: 6.0

**Comment by vorou** [comment] 2023-06-18 01:02
for anyone else experiencing this, here's 0.34.1 binaries https://www.icloud.com/iclouddrive/05dEpLyOiz2gErW1x3r4iiNBQ#mpv-034-1

**Comment by Akemi** [comment] 2023-11-25 01:47
duplicate of #12047 and an ffmpeg issue https://trac.ffmpeg.org/ticket/10585

closing this even though it's the older one, because the other issue has a working sample and some more infos and insight.

**Closed by Akemi** 2023-11-25 01:47 UTC
Labels: os:mac
