### ISSUE TITLE
mpv 0.28.x crash when using lavfi-complex

### ISSUE THREAD

**Issue by AxelTerizaki** [mpv-player/mpv#5732] opened 2018-04-12 08:00 UTC
### mpv version and platform

```
mpv 0.28.0-432-gec625266c8 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sat Apr  7 23:47:32 UTC 2018
ffmpeg library versions:
   libavutil       56.13.100
   libavcodec      58.17.100
   libavformat     58.11.101
   libswscale      5.0.102
   libavfilter     7.14.100
   libswresample   3.0.101
ffmpeg version: N-45713-gc837918f50
```

*NOTE : This works fine on 0.27.0*

### Reproduction steps

Load a image file and apply a filter to it like that : 

```[   0.036][v][cplayer] Run command: loadfile, flags=0, args=[D:\perso\toyundamugen-app\app\temp\default.jpg, replace, lavfi-complex=movie=\'D:/perso/toyundamugen-app/app/temp/qrcode.png\'[logo];[logo][vid1]scale2ref=240:240[logo1][base];[base][logo1]overlay=36:19[vo]]```

### Expected behavior

This should display a picture like this (works on 0.27.0) : 

![default jpg - mpv_2018-04-12_10-01-18](https://user-images.githubusercontent.com/4531597/38663922-7fd277d0-3e38-11e8-83a1-019f8c81bb87.png)

### Actual behavior

mpv 0.28.0 crashes.

### Log file

Included as attached files here

* [mpv 0.27.0 log (works)](https://github.com/mpv-player/mpv/files/1901884/mpv.log)
* [mpv 0.28.0 log (crashes)](https://github.com/mpv-player/mpv/files/1901887/mpv-crash.log)

Note that I tried both available Windows builds on mpv's website and the latest ones both crash.

### Sample files

* [qrcode.png](https://user-images.githubusercontent.com/4531597/38663780-17e716e4-3e38-11e8-86be-328aadc87715.png)
* [default.jpg](https://user-images.githubusercontent.com/4531597/38663798-29113206-3e38-11e8-8d4a-271491a4d400.jpg)

Thank you for your help. I'm going to do additional tests on a 64 bit machine as soon as I can, too.

**Comment by Akemi** [comment] 2019-09-20 16:50
duplicate of #6608.

**Closed by Akemi** 2019-09-20 16:50 UTC
