### ISSUE TITLE
mpv ignores matroska video crop metadata

### ISSUE THREAD

**Issue by JoseHidalgo** [mpv-player/mpv#8037] opened 2020-08-29 14:27 UTC
Hi guys,
I have a mkv file with black bars on top and bottom (20 pixels each : 1920x1038 with bars -> 1920x998 without bars).
The mkv header has indeed the cropping info according to MKVtoolnix (see attached pic).
But MPV doesn't seem to recognize it, as the black bars are still there during playback.
I guess I have latest MPV version ( mpv-x86_64-20200823-git-b0f0be7 ).
Any hints ?

![2020 08 29 - 16 18 21](https://user-images.githubusercontent.com/10851603/91638975-98f9b000-ea13-11ea-8014-403df3f46ac7.png)

**Comment by thebombzen** [comment] 2020-08-29 14:39
Is mpv fullscreen? mpv will put black bars in the player output window if it's larger than the video to render. Try reducing the size of mpv's window and seeing if you can reproduce it

**Comment by wm4** [comment] 2020-08-29 14:47
mpv doesn't read Matroska cropping metadata. There are very few files that use it.

**Comment by thebombzen** [comment] 2020-08-29 15:01
We *do* respect H.264 cropping metadata though, is this because of ffh264?

**Comment by wm4** [comment] 2020-08-29 15:45
The decoder takes care of this, although I'm not sure it works with hardware decoding. (I think it won't.) I had a PoC branch for Matroska cropping, but didn't merge it because it didn't work with hardware decoding.

**Comment by JoseHidalgo** [comment] 2020-08-29 19:49
Hi guys. :) No, MPV is not fullscreen (my screen is 1440p). That's how I could easily see that MPV doesn't crop the black bars. The video window should be 1920x998 and it isn't. It's 1920x1038 and the two black bars are perfectly visible.

@wm4 : the fact that "very few files use Matroska metadata" isn't a reason for MPV not to read it. I guess Matroska metadata exists for a reason, so MPV could take advantage of it. I believe it would be fairly easy to at least read the cropping info and resize the window accordingly.

@thebombzen : the video is HEVC.

@wm4 : AFAIK I'm using 100% software decoding. I have an old Core i3 530 and no external GPU.

**Comment by thebombzen** [comment] 2020-08-29 20:47
mpv ignores crop metadata inside the matroska container. The fact that it's not being considered isn't a bug, it's just not a feature that mpv has. Crop metadata inside the bistream itself (which is supported by some bitstreams like h264 and hevc), that's handled by the libavcodec decoder, and won't work with some decoders (like those from hardware) and shouldn't be relied upon.

**Comment by thebombzen** [comment] 2020-08-29 20:49
Either way, I've left the issue open and classified it as a feature request, should we choose to add support for this later. But this is not a defect in the player's functionality - it was never added.

**Comment by Akemi** [comment] 2020-08-29 21:01
there was also this https://github.com/sbruder/mpv-matroska-crop

**Comment by JoseHidalgo** [comment] 2020-08-29 21:40
Yes, given the info I understand that it's not a bug but rather a feature request. I hope you can support it at some point in the future. In the meantime I'll take a look at mpv-matroska-crop (at least with software decoding). Thanks !

**Comment by JoseHidalgo** [comment] 2020-08-30 00:35
EDIT : FYI I have put the matroska_crop.lua script in my Windows "AppData\Roaming\mpv\scripts" folder.
Then I have played the same video file with MPV, but the black borders are still there. :(

**Comment by Akemi** [comment] 2020-08-30 09:10
great info. i hope that is not all you did and you properly read the the readme of the script. if yes and you did everything the script might be broken.

**Comment by wm4** [comment] 2020-08-30 10:12
Anyway, I think I'd rather not go through the trouble required adjust the renderer (vo_gpu) to perform the cropping. Maybe I'll look whether it's possible to not "proper" cropping and just using the relevant sub-rectangle of the video, even if it bleeds pixels from the cropped out region.

**Comment by wm4** [comment] 2020-08-30 10:20
If anyone wants to do this:
1. add crop_rect fields to mp_image_params (or maybe only crop_x/crop_y, and use width/height to handle bottom/right)
2. change aspect.c to restrict the src rectangle to the cropped rectangle, instead of the whole video frame
3. change win_state.c to make VOs use the cropped size as window size, instead of the whole video frame
4. change demux_mkv.c to read cropping parameters
5. chance vd_lavc.c to make libavcodec export cropping parameters and use the mkv cropping parameters
6. maybe change vo_gpu to crop "correctly" (optional)
7. fix screenshots when using cropped video

I don't think I feel like doing it.

**Comment by JoseHidalgo** [comment] 2020-08-30 10:55
> 
> 
> great info. i hope that is not all you did and you properly read the the readme of the script. if yes and you did everything the script might be broken.
First of all @Akemi , I hope you can stop being ironic for whatever reason.
Second, YES, I read the readme (twice) and I don't see what I could have done wrong (aside that in Windows the scripts folder seems to be "AppData\Roaming\mpv\scripts"). May I have misread it ? Of course. That's why I posted. But the readme looks quite straightforward to me. https://github.com/sbruder/mpv-matroska-crop/blob/master/README.md

**Comment by bitraid** [comment] 2020-08-30 11:06
You can use `--script=<filename>` to make sure the script is loaded.

**Comment by Akemi** [comment] 2020-08-30 11:28
no, i can't stop being >sarcastic<. how are we supposed to help in any way with such little information?

in the first place when you opened this issue you either ignored our issue template or for some reason were redirected to the "open new issue without any template" page that is hidden. either way, when opening an issue we ask for certain info to be provided so we can help, and that info would have been helpful. though i guess that is besides the point if you weren't even provided with that template. 

the readme explicitly states what is required for that script to work in the "Installation" section. if that tool/binary isn't in your PATH it won't work. since you mentioned you only put the script into you script folder, i assume you didn't put mkvmerge into your path. hence why i said i hope you read the readme properly.

> The only dependency is mkvmerge from mkvtoolnix.

**Comment by JoseHidalgo** [comment] 2020-08-30 14:38
You assume that everybody has a perfect knowledge of english nuances. How about we continue this discussion in spanish or french ? I'd love to see you struggling with things as futile as irony vs. sarcasm.

![Sarcasm 2](https://user-images.githubusercontent.com/10851603/91661727-1be73d00-eade-11ea-9c15-2a41bcdc59ec.jpg)

It's great that you want to help, but helping and at the same time lecturing others is not helpful at all. Less ego and more wisdom.

I don't remember seeing any template, otherwise I would have **gladly** completed it, like I always do in all other places. If I missed anything then sorry, and if and more info is needed I'd be happy to provide it, as long as it's asked _nicely_. That being said, in this case I don't think I need to provide a log or anything like that.

I understand your frustration as you've probably spent some time organizing and labeling topics, but there's no need to be unkind with somebody you don't know. Other people in this thread are being nice. Be like them instead of being _that guy_.

Last but not least, yes, I put "C:\Program Files\MKVtoolnix" (which is mkvmerge folder) into my Windows PATH. Well, actually I didn't : it was already there.

**Comment by Akemi** [comment] 2020-08-30 15:21
instead of just providing a log file you try to be smart and tell us (the ones who ask for one) that it's not necessary? a log could tell us if the script is actually loaded and if it throws any kind of errors. 

but i guess if you did put mkvmerge into your path, then that script is most likely broken. that would explain why it was archived.

i will just ignore the rest of the rambling.

**Comment by Akemi** [comment] 2020-08-30 15:39
i looked at the script and it doesn't work because of this line https://github.com/sbruder/mpv-matroska-crop/blob/master/matroska_crop.lua#L119. just change it to:

```
if mp.get_property('hwdec') == 'no' then
```

alternatively use `--script-opts=matroska_crop-dynamic_hwdec=yes` or the same option in the `script-opts` folder and the `matroska_crop.conf` file. 

otherwise the script still works as intended.

**Comment by JoseHidalgo** [comment] 2020-08-31 09:22
I am happy to report that the script works now. It was indeed broken because of the 'none' instead of 'no' in L119.
That's good enough for me. I don't need MPV to natively handle cropping if a script can do it.
So, thanks for that I guess. I am thankful for the help, not so much for the tone.

Turns out that if the script hadn't been broken, all this discussion wouldn't have taken place (see earlier posts).

Thus, I will just ignore big-headed remarks like "you try to be **smart** and tell us". Instead I will just say "thanks again for providing a script. Next time maybe check that it actually works before posting the link ?". That would actually be... what's the word ? Oh yes : **smart**.

Thanks to everybody involved in this topic. Good day !

**Comment by Akemi** [comment] 2020-08-31 13:54
great to hear and have a nice day.

**Comment by thebombzen** [comment] 2020-08-31 14:44
Would it really be necessary to modify the renderer to deal with the cropping and the like? If we did it by inserting a crop filter internally (perhaps e.g. via vf-add=lavfi="crop=foo"`) then a lot of the logic like screenshots and rendering would be dealt with immediately. We'd only have to modify `demux_mkv.c` to parse it, basically.

**Comment by Akemi** [comment] 2020-08-31 17:05
that wouldn't work with hwdec, same as that script(?). i suppose that's why wm4 proposed the above possible solution.

**Comment by Dudemanguy** [comment] 2021-07-21 19:24
Turns out this is actually a duplicate of #6017 (wm4's comment on how to implement it is useful for anyone who cares).

**Closed by Dudemanguy** 2021-07-21 19:24 UTC
Labels: core:mkv, meta:feature-request
