### ISSUE TITLE
Toggling hardware decoding on crops video

### ISSUE THREAD

**Issue by TempSpas** [mpv-player/mpv#6153] opened 2018-09-24 02:43 UTC
I originally posted this issue on IINA's issue tracker, which can be found [here](https://github.com/lhc70000/iina/issues/1603). I was directed to open an issue here because IINA implements mpv.

### mpv version and platform

mpv 0.28.2 (via IINA 0.0.15.1)
macOS 10.13.6

Also tested on mpv 0.29.0

### Reproduction steps

1. Open a compatible file with `hwdec=videotoolbox`
2. Observe video dimensions are altered.

Example video info screenshots:

<img width="566" alt="no_hwdec" src="https://user-images.githubusercontent.com/3801275/45936178-9c5fa380-bf81-11e8-955f-d6465f1f5822.png">

<img width="748" alt="hwdec" src="https://user-images.githubusercontent.com/3801275/45936180-9ec1fd80-bf81-11e8-9a12-aff9535b3e88.png">

### Expected behavior

Video should not be cropped when hardware decoding is enabled.

### Actual behavior

Opening a file with hardware decoding enabled via `hwdec=videotoolbox` results in cropped video and loss of visual information.

### Log file

Both of these logs were obtained on mpv 0.29.0:

Log with `hwdec=videotoolbox`: https://paste.ubuntu.com/p/kfYXQ4fNdW/

Log with `hwdec=no`: https://paste.ubuntu.com/p/RNHrVRnpZ7/

### Sample files

This issue happens consistently reliably with any files I throw at IINA that works with VideoToolbox, but if testers really can't reproduce it, I can upload a file.

**Comment by Akemi** [comment] 2018-11-07 15:40
i recently got hardware decoding on my hackintosh to work and tried to debug this issue. it's not an mpv issue, but rather a ffmpeg or videotoolbox one. though i couldn't replicate it in VLC, which is a bit unexpected. i could find something like this in the VLC logs:

```
main debug: original format sz 1920x1088, of (0,0), vsz 1920x1080, 4cc CVPN, sar 1:1, msk r0x0 g0x0 b0x0
```

seems like it also returned a frame with 8 more pixels, which would negate the cropping.

the problem is that both the [h264](https://github.com/FFmpeg/FFmpeg/blob/a0ac49e38ee1d1011c394d7be67d0f08b2281526/libavcodec/h264_ps.c#L512) and [hevc](https://github.com/FFmpeg/FFmpeg/blob/70d2bab80b38adf6d9a1430992c33dd2e3efa93f/libavcodec/hevc_ps.c#L939) parser return a 8px bottom crop. i also couldn't reproduce this with all files.

someone more knowledge of ffmpeg probably needs to look at this.

**Comment by Akemi** [comment] 2018-11-07 15:58
@jeeb mentioned mod16 resolutions and that seems to be it. i can only reproduce it with my 1080p samples, but not with 720p or 4k ones. OPs sample is also 360p which isn't mod16 either.

**Comment by Akemi** [comment] 2018-11-07 21:45
okay i bisected ffmpeg and found the commit that broke it. for h264 the last working commit is https://github.com/FFmpeg/FFmpeg/commit/6505e8cfd02b9112e24bb40c145d6c760f15d622 and the first broken one is https://github.com/FFmpeg/FFmpeg/commit/07596e45c5a0195b6e4e57597497ec7066817739.

with that being said https://github.com/FFmpeg/FFmpeg/commit/000fb61a71c6288c377167fea1541700aef3612d probably broke the hevc hw-decoding but i can't confirm it since videotoolbox only get hevc support a lot later.

https://github.com/FFmpeg/FFmpeg/commit/a9a6d51ca447be6364298a350336a25125f0af07 might have broken something for theora, but also untested.

https://github.com/FFmpeg/FFmpeg/commit/000fb61a71c6288c377167fea1541700aef3612d is the first commit that started changing the cropping mechanism.

a h264 test file https://0x0.st/sICQ.mkv and a hevc one https://0x0.st/sIC2.mkv.

i suspect this isn't just a videotoolbox problem. anyone can confirm this?

**Comment by Akemi** [comment] 2018-11-10 15:30
https://github.com/Akemi/FFmpeg/commit/c1c339c52912a09a892e53f04e1ef859dfc72698 this will fix the issue. it's basically cropping twice because videotoolbox returns an already cropped stream.

**Comment by Akemi** [comment] 2018-11-12 12:49
fixed with https://github.com/FFmpeg/FFmpeg/commit/233cd89056405c76f01cc6f5315aa566454132fa.

**Closed by Akemi** 2018-11-12 12:49 UTC
Labels: ffmpeg-bug, not our bug, osx
