### ISSUE TITLE
Make hidpi-window-scale=no as default

### ISSUE THREAD

**Issue by mlindner** [mpv-player/mpv#13465] opened 2024-02-12 11:01 UTC
It is almost never wanted that videos are blown up to twice their native image resolution and then have mpv play make believe that that is indeed the correct video resoltuion. hidpi means that the content rendered within that window is being rendered at a higher resolution than the native "dot size". Videos fundamentally don't do this however as you have to engage in upscaling so are not hidpi content.

Other problems this causes is for example when trying to window a 4k video on a 4k monitor being run as a hidpi "1080p" monitor they get blown up to effectively 8k in size because mpv thinks its a 1080p screen. Alternatively, playing a 1080p video on a 4k monitor with some window managers results in a "windowed" video that's still filling up the full screen instead of being a small window at only 1/4th the screen size.

This type of behavior is just never wanted.

### Expected behavior of the wanted feature
Restore previous default behavior where windows were naturally are the same size as the video content.

**Comment by Dudemanguy** [comment] 2024-02-12 15:00
I do actually prefer not doing hidpi scaling on mpv as well and find it annoying. This has been the default for a very long time though with relatively little complaining, so I assume a significant amount of people like it.

**Comment by Dudemanguy** [comment] 2024-02-12 17:50
I think macOS is the only odd one out here. Wayland used to be more like macOS with regards to scaling, but eventually all of that changed to be more like X11 and Windows.

**Comment by Akemi** [comment] 2024-02-12 18:36
just my personal preference. since the day i originally opened the PR and it was merged i use `--hidpi-window-scale=no`, because for me it's the only 'right' way to it. i didn't want my personal preference to interfere with the 'style guides and recommendations' from Apple. personally i wouldn't mind to default to `no`, though i can't and don't want to speak for other macOS users.

maybe on a side note, if we really want to do it properly i believe we need to kill this option and so something i suggested here https://github.com/mpv-player/mpv/issues/5688 i believe. we need to make all the geometry/size related options and features point aware.

**Comment by mlindner** [comment] 2024-02-13 21:37
I use on both MacOS and Linux. I complained about it the moment the functionality changed and got an angry reply from wm4 way back when I believe. It is absolutely absurd even on MacOS and the only reason it's different on Apple because Apple wraps all their video players with UI elements and they want the UI elements to be the same size across all systems. mpv doesn't have UI elements that need to be the same size so it makes no sense.

**Closed** 2024-02-24 20:31 UTC
Labels: meta:feature-request

**Comment by Dudemanguy** [comment] 2024-10-25 11:02
`--window-scale=1` is the default though.

**Comment by Akemi** [comment] 2024-10-25 15:40
btw i can also not confirm this behaviour on macOS. it works as intended on my end with `--hidpi-window-scale=no`. i am even the one who added this option, added it to macOS and made sure it works.

besides there are a lot of wrong informations in this wall of text and macOS.

if you have an issue open a new issue.
