### ISSUE TITLE
Doesn't load conditional auto profiles for external cover art images of audio files

### ISSUE THREAD

**Issue by jiangzhenjerry** [mpv-player/mpv#11130] opened 2023-01-11 22:12 UTC
### Important Information

- mpv version: [20230108-git-c8a9000](https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/mpv-x86_64-v3-20230108-git-c8a9000.7z/download)
- Platform and Version: Windows 11 x64
- Source of the mpv binary: [SourceForge](https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/)

### Reproduction steps

1. Set up `mpv.conf` like the followings. The basic idea is to enable all `hwdec` codecs except for `mjpeg`.
```
hwdec
hwdec-codecs=all

[mjpeg]
profile-cond=video_format=='mjpeg'
profile-restore=copy
hwdec=no
```

2. Make a folder structure like this: 
```
Cover.jpg
XYZ.flac (or whatever audio file)
```
where `Cover.jpg` is an external cover image of still `mjpeg` format (you can use the sample file at the end of the this post). `XYZ.flac` is whatever audio file without internally embedded album art.

3. Use mpv to play `XYZ.flac`. mpv should automatically pickup `Cover.jpg` and show it as the album art.

### Expected behavior

mpv should apply the conditional auto profile and disable hardware decoding.

### Actual behavior

mpv doesn't apply the conditional auto profile. `hwdec` is still on and generates some bad artifacts (that's another issue raised in #10967)

It used to work before. I cannot tell starting which commit it breaks.

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/10396303/output.txt)

### Sample file
![Cover](https://user-images.githubusercontent.com/9311082/211929041-b6fb0c32-ead5-4bad-ab18-70219cf87551.jpg)

**Comment by Dudemanguy** [comment] 2023-01-11 22:30
Without actually testing myself, I'm going to assume this is a race condition between mpv starting up and auto-profiles.

**Comment by jiangzhenjerry** [comment] 2023-01-11 22:37
@Dudemanguy Thanks. I forgot to mention that my other auto-profiles load without a problem. It may be related to indirect file opening - I'm not directly opening the image; I'm indirectly loading it by loading the audio file.

**Comment by Dudemanguy** [comment] 2023-01-11 22:43
>I'm not directly opening the image; I'm indirectly loading it by loading the audio file.

That's a good point. What happens if you do directly open the file?

**Comment by jiangzhenjerry** [comment] 2023-01-11 22:50
> What happens if you do directly open the file?

Just tried - it loads without a problem. The auto-profile is applied. So I guess it is indeed an indirect file opening issue...

**Comment by Dudemanguy** [comment] 2023-01-11 22:52
That's a good datapoint to have. Do you remember how far back it was when it used to work?

**Comment by garoto** [comment] 2023-01-11 23:55
> [...] I'm going to assume this is a race condition between mpv starting up and auto-profiles.

Most probably yes.

**Comment by jiangzhenjerry** [comment] 2023-01-12 00:04
> Do you remember how far back it was when it used to work?

Very hard to say, because even when it worked in the past, it didn't work perfectly - the auto profiles may or may not load, depending on my luck. So at that time, I had to repeatedly load the same file until suddenly `mpv` decided to load the auto profiles. Now it seems like I can never get the "luck" again. So maybe it has always been like this and never worked :s 

From this perspective, it does seem like a race condition as well....

**Comment by garoto** [comment] 2023-01-12 00:38
Every .lua script will face a race condition eventually, but that's no biggie I guess. `auto-profiles.lua` and `ytdl_hook.lua` are the most visible offenders.

**Comment by Dudemanguy** [comment] 2023-01-12 00:46
The log actually shows that hwdec is set to no. The problem is that it is "unapplied" after the image as already been loaded since the video_format property isn't available until then. It's not really ideal but if you workaround it by using the filename instead like:

```
[albumart]
profile-cond=string.match(filename, ".flac") ~= nil
profile-restore=copy
hwdec=no
```

It should do the trick. Of course, you would have to add an additional or for every audio extension you care about which could get ugly.

**Comment by jiangzhenjerry** [comment] 2023-01-12 01:09
Thank you for the hint - Your suggestion works well. Yeah it's ugly with a lot of `or` but I guess I can live with that :)

**Comment by Dudemanguy** [comment] 2023-01-12 01:46
Yeah unfortunately this one is just one of those ordering things. You can't know the format until mpv opens it and it opens it with hwdec on so that defeats the purpose. One of the reason why extensions are useful. Guess I'll close this.

**Closed by Dudemanguy** 2023-01-12 01:46 UTC
Labels: scripting:auto-profiles

**Comment by jiangzhenjerry** [comment] 2023-01-12 02:16
@Dudemanguy  More precisely speaking, I think auto profiles are loaded **after** loading the direct file, but **before** loading the indirect files. That explains why directly opening the album art picture will load the auto profiles without an issue. If one day the auto profiles are loaded after all relevant media files are loaded, this issue will be truly gone.

Thank you for your help today. I learned a lot.
