### ISSUE TITLE
[ytdl-hook] Doens't work with certain youtube video.

### ISSUE THREAD

**Issue by ficofabrid** [mpv-player/mpv#4781] opened 2017-08-18 15:08 UTC
```py
Playing: https://www.youtube.com/watch?v=HM7minqwaVY
[ytdl_hook] 
[ytdl_hook] stack traceback:
[ytdl_hook] 	[C]: in function 'len'
[ytdl_hook] 	@ytdl_hook.lua:71: in function 'edl_escape'
[ytdl_hook] 	@ytdl_hook.lua:139: in function 'edl_track_joined'
[ytdl_hook] 	@ytdl_hook.lua:171: in function 'add_single_video'
[ytdl_hook] 	@ytdl_hook.lua:454: in function 'fn'
[ytdl_hook] 	mp.defaults:518: in function 'handler'
[ytdl_hook] 	mp.defaults:339: in function 'handler'
[ytdl_hook] 	mp.defaults:458: in function 'call_event_handlers'
[ytdl_hook] 	mp.defaults:495: in function 'dispatch_events'
[ytdl_hook] 	mp.defaults:451: in function <mp.defaults:450>
[ytdl_hook] 	[C]: in ?
[ytdl_hook] 	[C]: in ?
[ytdl_hook] Lua error: @ytdl_hook.lua:71: bad argument #1 to 'len' (string expected, got nil)
[ffmpeg] tls: The TLS connection was non-properly terminated.
Failed to recognize file format.

```
### Log file

https://a.pomf.cat/xrjqgl.txt

### Sample files

https://www.youtube.com/watch?v=HM7minqwaVY

**Comment by wiiaboo** [comment] 2017-08-18 15:10
Duplicate of https://github.com/mpv-player/mpv/issues/4728. See https://github.com/mpv-player/mpv/issues/4728#issuecomment-320725058 for a workaround.

**Closed by wiiaboo** 2017-08-18 15:10 UTC
