### ISSUE TITLE
playback of video in RAR files doesnt work

### ISSUE THREAD

**Issue by jonny5alive1** [mpv-player/mpv#7317] opened 2020-01-03 17:50 UTC
Hello when I play back videos from RAR files like in VLC it doesn't seem to work?

Sorry I can't provide much detail, other than it seems to be stuck on seeking, but I have seen a few other reports on this around on the internet.

I am using version 0.30, and before updating everything worked perfectly?

Will this be fixed next release?

**Comment by CounterPillow** [comment] 2020-01-03 17:52
the old rar demuxer was removed because it is unmaintained boomer garbage, so now libarchive is used for RAR as well.

**Comment by jonny5alive1** [comment] 2020-01-03 18:23
Hi, thanks for the reply.

Hmm is the RAR format still under development then? reading a little around this it doesn't seem like it is?

The VLC developers suggest they have just kept in old unrar code for legacy functionality?

Wouldnt this be the better option? and dump libarchive, as videos in RAR's is a widespread thing, but no one is ZIP'ing or TAR'ing videos?

**Comment by CounterPillow** [comment] 2020-01-04 01:17
I've been told the internal RAR demuxer was actually never autoselected, so I'm closing this because it lacks even basic information to begin reproducing the issue (log file of the two different versions, sample files, no accurate description of the problem)

**Closed by CounterPillow** 2020-01-04 01:17 UTC
Labels: priority:ignored-issue-template

**Comment by wm4** [comment] 2020-01-04 11:58
>I've been told the internal RAR demuxer was actually never autoselected, 

Not true.
