### ISSUE TITLE
Linux kernel above 6.4.10 causes gpu and gpu-next to output glitched video

### ISSUE THREAD

**Issue by chitao1234** [mpv-player/mpv#12204] opened 2023-08-20 05:21 UTC
### Important Information

Provide following Information:
- mpv version
```
mpv 0.36.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Sun Jul 23 05:49:29 2023
libplacebo version: v5.264.1
FFmpeg version: n6.0
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
```
- Linux Distribution and Version
EndeavourOS(arch-based) rolling release
uname -a:
`Linux CHI-Endeavouros 6.4.11-arch2-1 #1 SMP PREEMPT_DYNAMIC Sat, 19 Aug 2023 15:38:34 +0000 x86_64 GNU/Linux`
- Source of the mpv binary
ArchLinux, [PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/mpv/-/blob/main/PKGBUILD)
- If known which version of mpv introduced the problem
Seems like all version are affected
- Window Manager and version
`kwin 5.27.7`
- GPU driver and version
`nvidia 535.98`
`i915 from kernel 6.4.11`
- Possible screenshot or video of visual glitches
[gpu-next](https://0x0.st/HLxX.png)
[gpu](https://0x0.st/HLxH.png)

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Launch mpv with
`mpv --no-config --vo=gpu --cscale=ewa_lanczossharp video.mp4` or
`mpv --no-config --vo=gpu-next --cscale=ewa_lanczos BigBuckBunny.mp4`

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior
Output normal video

### Actual behavior
Output glitched video

### Log file
[gpu-next](https://0x0.st/HLxP.txt)
[gpu](https://0x0.st/HLxZ.txt)

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

### Sample files
Any h264 or hevc video

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by sfan5** [comment] 2023-08-20 08:37
Are you sure this is due to a kernel update and not a Mesa update?
Either way since you've already determined that this is a regression elsewhere, we can't do anything for you.

**Comment by chitao1234** [comment] 2023-08-20 09:07
By switching to 6.4.9, I can confirm that the issue does not exist, so it should be a kernel problem.

**Comment by chitao1234** [comment] 2023-08-20 09:10
I will try to also post the issue on the kernel bugzilla.

**Comment by escalade** [comment] 2023-08-23 20:08
Same here on HEVC without any cscale. Rolling back to 6.4.9 fixes it.

**Comment by tm4ig** [comment] 2023-08-26 14:26
I have created same bug https://gitlab.freedesktop.org/drm/intel/-/issues/9118#note_2051613
please confirm

**Comment by tm4ig** [comment] 2023-08-26 14:29
I have created same bug https://gitlab.freedesktop.org/drm/intel/-/issues/9118
please confirm

**Comment by chitao1234** [comment] 2023-08-28 01:10
> I have created same bug https://gitlab.freedesktop.org/drm/intel/-/issues/9118 please confirm
Confirmed it few days ago and attached my logs

**Comment by stebotron** [comment] 2023-09-02 15:46
I have the same issue when playing 4k hevc videos on system with intel gpu. Rolling back to kernel 6.4.9 indeed solves the issue for now.

**Comment by jeeb** [comment] 2023-10-13 18:11
Closing as apparently with https://gitlab.freedesktop.org/drm/intel/-/issues/9118#note_2127262 this has now been handled upstream.

**Closed by jeeb** 2023-10-13 18:11 UTC
Labels: down-upstream:intel, os:linux
