### ISSUE TITLE
Double taps on touchscreen devices to fullscreen not hiding taskbar

### ISSUE THREAD

**Issue by tactidact** [mpv-player/mpv#4632] opened 2017-07-19 13:52 UTC
### mpv version and platform
mpv 0.26.0 lachs0r's builds for Windows dated 2017-07-18
Windows 10 on a Surface Pro 2017 and a Lenovo Y-50 laptop

### Reproduction steps
Double click to fullscreen and drag the cursor on the second click
For a touchscreen device use finger taps or stylus taps(very difficult to land second tap on same spot as first)

### Expected behavior
Fullscreen video with Windows taskbar hidden

### Actual behavior
Fullscreen video(sometimes not even that, window borders just disappear) with OSD obscured by Windows taskbar and the video frame offset in the direction of the drag on second click/second touchscreen tap. http://imgur.com/a/d81i5

This seems to be a result of mpv expecting the second click in either the exact same spot as the first click, or a very small area around it. When using a touchscreen device, it is exceptionally difficult to ensure that the second tap lands exactly where the first tap did. Thus some leniency with how far the second tap/click can be from the first might alleviate this.

**Comment by lachs0r** [comment] 2017-07-19 16:05
Duplicate of #1921.

**Closed by lachs0r** 2017-07-19 16:05 UTC
