### ISSUE TITLE
Optimize CPU Utlization

### ISSUE THREAD

**Issue by ksmuthucv** [mpv-player/mpv#9276] opened 2021-10-05 12:28 UTC
Hello Team,
I have machine with 2 GPU's of nvidia running Windows 10. I was trying to run the below commands (via a batch file, streams has the resolution of 1920x1080). the load had span between two gpu's and the contents were dsisplayed correctly. but for some reason the cpu load seems to be higher. is there any optimization reduce the cpu load/work (between 0.1-0.5%)?

@echo off
start mpv.exe "rtsp://127.0.0.1:3049/" --no-border --osc=no -hwdec=nvdec -vo=gpu --gpu-api=opengl --cuda-decode-device=0
timeout 2
start mpv.exe "rtsp://127.0.0.1:3050/" --no-border --osc=no -hwdec=nvdec -vo=gpu --gpu-api=opengl --cuda-decode-device=0
timeout 2
start mpv.exe "rtsp://127.0.0.1:3051/" --no-border --osc=no -hwdec=nvdec -vo=gpu --gpu-api=opengl --cuda-decode-device=1
timeout 2
start mpv.exe "rtsp://127.0.0.1:3052/" --no-border --osc=no -hwdec=nvdec -vo=gpu --gpu-api=opengl --cuda-decode-device=1
timeout 2

![image](https://user-images.githubusercontent.com/16358707/136022058-56612544-b2db-4583-b44a-217c1f863025.png)

Thanks,
Muthu

**Comment by CounterPillow** [comment] 2021-10-05 13:45
There's always some overhead, it's unavoidable.

You can try the vulkan API, other than that you'll need to actually do profiling to see which code path is taking the longest.

Thanks for ignoring the issue template though.

**Comment by ksmuthucv** [comment] 2021-10-05 16:02
My apologies for not following the issue template.

If the gpu api type is changed to vulkan, the all the (above) streams were decoded by gpu 0. Also, whenever the load is given to gpu 1 (with gpu api being opengl), mpv consumes more power% in cpu (please refer to the mock-up in original request).

**Comment by avih** [comment] 2021-10-05 16:36
Very generally, mpv is merely smart glue which connects different libraries to create the following chain (sometimes only parts of it):

Archive-extraction (libarchive)
Demux (ffmpeg)
Decoding (ffmpeg/gpu/drivers)
Rendering technology (OpenGL/Vulkan/Windows/etc and drivers)
Graphical overlays like OSD/GUI/subtitles (libass)
Output method (X11/wayland/D3D11/OSX/etc)
Display (gpu driver)

mpv itself, despite being a relatively big project, doesn't have a lot of performance-critical code.

Therefore, unless you have a solid reason to suspect that some mpv code needs optimization, then it's most likely that any optimization you want is outside of the control of mpv.

Do keep in mind that even when optimizations are possible, many times it's not worth the additional code complexity and maintnance burden. However, if there's room for optimizations then indeed it should at least be considered.

I'm closing this issue now, because so far there's nothing to suggest that it's an issue of unoptimized mpv code.

Feel free to open a new issue if you have reasons to suspect the fault is within mpv - and do follow the issue template, especially logs, steps to reproduce the issue, and any further info you think would help to diagnose the issue.

Thanks.

**Closed by avih** 2021-10-05 16:36 UTC

**Comment by haasn** [comment] 2021-10-05 23:55
> If the gpu api type is changed to vulkan, the all the (above) streams were decoded by gpu 0. 

You can affect this using `--vulkan-device`.

**Comment by ksmuthucv** [comment] 2021-10-06 03:34
> 
> 
> > If the gpu api type is changed to vulkan, the all the (above) streams were decoded by gpu 0.
> 
> You can affect this using `--vulkan-device`.

Thank you for your suggestion. Unfortunately nvidia GPUs are of same model and they the have the same name. When i had tried --vulkan-device="Quadro K1200", work load went to gpu-1. also i feel the configuration of gpu-1 has some issues. i will try to uninstall and install the latest drivers and check. with gpu-0, mpv works quite nicely under open-gl.

Available vulkan devices:
  'Quadro K1200' (GPU 0, ID 10de:13bc)
  'Quadro K1200' (GPU 1, ID 10de:13bc)

![image](https://user-images.githubusercontent.com/16358707/136136173-baaf4057-4709-48d2-8d45-cf50a9a29f60.png)
