### ISSUE TITLE
Playing content from network shares in macOS performs very poorly when launched from Finder

### ISSUE THREAD

**Issue by mikezila** [mpv-player/mpv#5511] opened 2018-02-10 22:22 UTC
### mpv version and platform

macOS High Sierra V10.13.3
mpv 0.28

### Reproduction steps

Associate mpv.app with your media, and launch mpv by opening a video from the Finder that is hosted on a network share.

### Expected behavior

Smooth playback.

### Actual behavior

Very jerky playback, as if you were streaming the file over a very slow connection.  The same file will play totally fine if you instead launch mpv from the terminal by opening the bundle and running the contained binary with command line options.  Opening files that are on the local machine works fine from either Finder or the Terminal.

### Log file

[bad-mpv.log](https://github.com/mpv-player/mpv/files/1713813/bad-mpv.log) is the log from opening the media from the Finder.  The window doesn't even respond to clicking the OSD, and video is output at a very low framerate, sound skips as well.

[fine-mpv.log](https://github.com/mpv-player/mpv/files/1713814/fine-mpv.log) is the log from opening the same media on the same share from the terminal.  I was able to seek around the file with no buffering or disruption.

**Comment by Akemi** [comment] 2018-02-10 22:48
maybe related to #5478. you could test what was suggested on that issue too.

**Comment by Akemi** [comment] 2018-02-10 23:04
can you bisect the problem?

**Comment by Akemi** [comment] 2018-02-10 23:28
also does it happen with `open PATH_TOP_MPV.app --args PATH_TO_FILE`?

**Comment by mikezila** [comment] 2018-02-11 00:12
Unlikely I can bisect it, as I've had this issue for a very long time and just been too lazy to report it, six months at least.  It does happen when using `open` in Terminal.

Can you be specific about what from that other issue you want me to try?  The thread ends with no satisfaction and the steps you asked him to take ended up being a mistake.

**Comment by Argon-** [comment] 2018-02-11 00:45
How is your network share mounted? SMB? Can you try AFP?

I have all of my content on an AFP-mounted network share and all of the stuff I watch comes exclusively from there. So far, I have not noticed any regressions in multiple years of watching stuff with mpv on a daily.  
OSX, especially the 'newer' versions, are known to have SMB problems and terrible performance with it. Using AFP I get a constant 110MB/s from my NAS while SMB only achieves around 1/3 of that (being on 10.11 I have an older implementation though).

**Comment by mikezila** [comment] 2018-02-11 01:00
AFP, it's the same via SMB.

**Comment by Akemi** [comment] 2018-02-11 01:36
> Unlikely I can bisect it, as I've had this issue for a very long time and just been too lazy to report it, six months at least.

i don't really want to guess what the problem is, since i can't reproduce it. so at least a proper starting point would be nice. i am too 'lazy' too.

> The thread ends with no satisfaction and the steps you asked him to take ended up being a mistake.

how does it end with no satisfaction if his problem was solved with the PR i suggested? the point is that you do the same steps and see if something works for you.

but to quote myself so you know what to do, if you can build yourself.

> tbh the only thing that would come to mind that is completely different from the bundle and also has an effect after mpv was started is the [redirection](https://github.com/mpv-player/mpv/blob/master/osdep/macosx_application.m#L235) of the output. since you build mpv yourself you could try commenting out [this line](https://github.com/mpv-player/mpv/blob/master/osdep/macosx_application.m#L288).

> ...comment [line 264-272](https://github.com/mpv-player/mpv/blob/master/osdep/macosx_application.m#L264). that leaves the needed parts in.

> also try with `--no-config`.


> then you could test this #4833. it has a completely different vo init routine. if the problem still persists it's most likely something else.
> 
> just make sure you use `--vo=opengl-cb` instead of the default one.

**Comment by aufkrawall** [comment] 2018-02-11 14:13
If a different player shows the same problem, my guess would be that it's related to macOS' way how to implement the virtual network filesystem.
It's similar on Linux, e.g. KIO sucks a*s compared to GVFS.

**Comment by mikezila** [comment] 2018-02-11 16:39
VLC and Quicktime both work fine when opening the same files via the Finder.

**Comment by dreness** [comment] 2018-03-24 18:31
@mikezila Try using the ```powermetrics``` tool to compare the quality of service stats between an mpv instance launched from the command line versus an mpv instance launched from Finder, as outlined here: 

https://developer.apple.com/library/content/documentation/Performance/Conceptual/power_efficiency_guidelines_osx/PrioritizeWorkAtTheTaskLevel.html#//apple_ref/doc/uid/TP40013929-CH35-SW10.

It's possible / likely that the QoS defaults are different depending on how a process is launched. If so, this should be fixable by mpv explicitly requesting the desired QoS class.

You can also try disabling the low priority IO throttle entirely by setting the ```debug.lowpri_throttle_enabled``` sysctl to zero - this should take effect immediately, but may have no (noticeable) impact on this particular workload.
```
sudo sysctl debug.lowpri_throttle_enabled=0
```
Set it back to 1 to re-enable the lowpri throttle.

**Comment by Akemi** [comment] 2021-04-29 22:09
this might be fixed by #8266. can anyone confirm this?

**Comment by dreness** [comment] 2021-05-02 03:42
I'm giving this a spin - here are my (somewhat inconclusive) findings.

### baseline
(no change except logging)
<details><summary>transcript</summary>
<p>

```
(py39) andre@boop mpv % df -t smbfs /Volumes/dre/Movies/Zappa.2020.mkv
Filesystem           512-blocks       Used Available Capacity   iused       ifree %iused  Mounted on
//dre@jeez.local/dre 6096691984 5983488224 113203760    99% 747936026    14150470   98%   /Volumes/dre

(py39) andre@boop mpv % sudo purge

(py39) andre@boop mpv % mpv --no-config /Volumes/dre/Movies/Zappa.2020.mkv
 (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) (eac3 6ch 48000Hz)
     Subs  --sid=1 --slang=eng (subrip)
     Subs  --sid=2 --slang=eng 'SDH' (subrip)
elapsed: 115.060000ms
AO: [coreaudio] 48000Hz stereo 2ch floatp
VO: [libmpv] 1920x1080 yuv420p
elapsed: 114.411000ms55 (0%) A-V:  0.000 Cache: 1.3s/331KB
elapsed: 19.460000ms
elapsed: 75.593000ms:55 (0%) A-V:  0.000 Cache: 4.6s/1MB
elapsed: 142.677000ms55 (0%) A-V:  0.017 Cache: 13s/2MB
elapsed: 122.360000ms55 (0%) A-V:  0.005 Cache: 19s/4MB
elapsed: 224.672000ms55 (0%) A-V:  0.000 Cache: 20s/7MB
elapsed: 187.370000ms55 (0%) A-V:  0.000 Cache: 25s/14MB
elapsed: 141.559000ms55 (0%) A-V:  0.000 Cache: 37s/30MB
elapsed: 137.629000ms55 (0%) A-V:  0.000 Cache: 81s/53MB
elapsed: 140.843000ms55 (0%) A-V:  0.000 Cache: 98s/77MB
elapsed: 123.837000ms55 (0%) A-V:  0.000 Cache: 127s/102MB
elapsed: 123.481000ms55 (0%) A-V:  0.000 Cache: 146s/126MB
elapsed: 164.360000ms55 (0%) A-V:  0.000 Cache: 152s/149MB
elapsed: 324.419000ms55 (1%) A-V:  0.000 Cache: 153s/149MB
AV: 00:01:00 / 02:07:55 (1%) A-V:  0.000 Cache: 150s/150MB

Exiting... (Quit)
```
</p>
</details>

### with f_nocache and disabled read-ahead
<details><summary>patch</summary>
<p>

```
diff --git a/stream/stream_file.c b/stream/stream_file.c
index 0ba12278ab..7357f062d5 100644
--- a/stream/stream_file.c
+++ b/stream/stream_file.c
@@ -103,7 +103,12 @@ static int fill_buffer(stream_t *s, void *buffer, int max_len)
 #endif
 
     for (int retries = 0; retries < MAX_RETRIES; retries++) {
+        clock_t begin = clock();
         int r = read(p->fd, buffer, max_len);
+        clock_t end = clock();
+        double time_spent = (double)(end - begin) / (CLOCKS_PER_SEC / 1000);
+        if (time_spent > 10)
+            printf("elapsed: %fms\n", time_spent);
         if (r > 0)
             return r;
 
@@ -305,6 +310,12 @@ static int open_f(stream_t *stream, const struct stream_open_args *args)
         p->close = true;
     }
 
+    if (fcntl(p->fd, F_NOCACHE, 1) < 0) {
+        MP_ERR(stream, "Cannot disable cache on file '%s': %s\n",
+               filename, mp_strerror(errno));
+        return STREAM_ERROR;
+    }
+
     struct stat st;
     if (fstat(p->fd, &st) == 0) {
         if (S_ISDIR(st.st_mode)) {
@@ -340,9 +351,18 @@ static int open_f(stream_t *stream, const struct stream_open_args *args)
     stream->get_size = get_size;
     stream->close = s_close;
 
-    if (check_stream_network(p->fd))
-        stream->streaming = true;
+    if (check_stream_network(p->fd)) {
+         stream->streaming = true;
+         
+ #if HAVE_COCOA
+         if (fcntl(p->fd, F_RDAHEAD, 0) < 0) {
+             MP_VERBOSE(stream, "Cannot disable read ahead on file '%s': %s\n",
+                     filename, mp_strerror(errno));
+         }
+ #endif
+
 
+     }
     p->orig_size = get_size(stream);
 
     p->cancel = mp_cancel_new(p);
```
</p>
</details>

<details><summary>transcript</summary>
<p>

```
(py39) andre@boop mpv % sudo purge                                        
(py39) andre@boop mpv % mpv --no-config /Volumes/dre/Movies/Zappa.2020.mkv
 (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) (eac3 6ch 48000Hz)
     Subs  --sid=1 --slang=eng (subrip)
     Subs  --sid=2 --slang=eng 'SDH' (subrip)
elapsed: 99.262000ms
AO: [coreaudio] 48000Hz stereo 2ch floatp
VO: [libmpv] 1920x1080 yuv420p
elapsed: 10.524000ms
elapsed: 21.838000ms:55 (0%) A-V:  0.000 Cache: 14s/2MB
elapsed: 11.137000ms
elapsed: 22.682000ms:55 (0%) A-V:  0.032 Cache: 20s/4MB
elapsed: 17.959000ms:55 (0%) A-V:  0.007 Cache: 22s/9MB
elapsed: 13.517000ms:55 (0%) A-V:  0.000 Cache: 28s/17MB
elapsed: 11.354000ms:55 (0%) A-V:  0.000 Cache: 31s/22MB
elapsed: 19.540000ms:55 (0%) A-V:  0.000 Cache: 31s/23MB
elapsed: 23.437000ms:55 (0%) A-V:  0.000 Cache: 38s/30MB
elapsed: 15.822000ms:55 (0%) A-V:  0.000 Cache: 39s/32MB
elapsed: 16.672000ms:55 (0%) A-V:  0.000 Cache: 43s/37MB
elapsed: 16.376000ms:55 (0%) A-V:  0.000 Cache: 48s/46MB
elapsed: 10.801000ms:55 (0%) A-V:  0.000 Cache: 154s/149MB
elapsed: 10.354000ms:55 (0%) A-V:  0.000 Cache: 152s/149MB
elapsed: 119.024000ms55 (0%) A-V:  0.000 Cache: 152s/149MB
elapsed: 14.887000ms
elapsed: 12.382000ms
elapsed: 18.959000ms
elapsed: 31.407000ms:55 (0%) A-V:  0.000 Cache: 153s/149MB
elapsed: 11.932000ms:55 (0%) A-V:  0.000 Cache: 153s/150MB
elapsed: 10.569000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 10.334000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 10.705000ms
elapsed: 10.105000ms
elapsed: 10.822000ms
elapsed: 10.276000ms
elapsed: 18.857000ms
elapsed: 10.969000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 12.165000ms
elapsed: 10.756000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 11.801000ms:55 (0%) A-V:  0.000 Cache: 155s/150MB
elapsed: 11.133000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 13.277000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 10.470000ms
elapsed: 13.405000ms
elapsed: 11.525000ms:55 (0%) A-V:  0.000 Cache: 155s/150MB
elapsed: 11.745000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 10.568000ms
elapsed: 15.236000ms
elapsed: 12.985000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 11.440000ms:55 (0%) A-V:  0.000 Cache: 155s/150MB
elapsed: 10.609000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 12.290000ms
elapsed: 14.416000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 10.114000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 16.357000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 13.912000ms:55 (0%) A-V:  0.000 Cache: 155s/150MB
elapsed: 11.040000ms
elapsed: 11.030000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 13.390000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 12.751000ms
elapsed: 11.608000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 14.522000ms:55 (0%) A-V:  0.000 Cache: 155s/150MB
elapsed: 13.118000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 185.321000ms55 (0%) A-V:  0.000 Cache: 154s/149MB
elapsed: 26.144000ms
elapsed: 68.532000ms
elapsed: 32.214000ms:55 (0%) A-V:  0.000 Cache: 154s/149MB
elapsed: 32.509000ms
elapsed: 10.958000ms
elapsed: 58.066000ms
elapsed: 60.591000ms
elapsed: 25.981000ms
elapsed: 44.623000ms:55 (0%) A-V:  0.000 Cache: 154s/149MB
elapsed: 122.084000ms55 (0%) A-V:  0.000 Cache: 154s/149MB
elapsed: 10.305000ms
elapsed: 50.527000ms
elapsed: 49.982000ms:55 (0%) A-V:  0.000 Cache: 154s/149MB
elapsed: 22.036000ms:55 (0%) A-V:  0.000 Cache: 155s/149MB
elapsed: 55.658000ms:55 (0%) A-V:  0.000 Cache: 155s/149MB
elapsed: 45.022000ms:55 (0%) A-V:  0.000 Cache: 155s/149MB
elapsed: 47.655000ms:55 (0%) A-V:  0.000 Cache: 154s/149MB
elapsed: 31.541000ms:55 (0%) A-V:  0.000 Cache: 155s/149MB
elapsed: 11.338000ms:55 (0%) A-V:  0.000 Cache: 155s/150MB
elapsed: 33.375000ms:55 (0%) A-V:  0.000 Cache: 155s/149MB
elapsed: 13.617000ms
elapsed: 43.816000ms:55 (0%) A-V:  0.000 Cache: 155s/149MB
elapsed: 62.969000ms:55 (0%) A-V:  0.000 Cache: 154s/149MB
elapsed: 51.137000ms
elapsed: 11.659000ms:55 (0%) A-V:  0.000 Cache: 155s/149MB
elapsed: 13.536000ms:55 (0%) A-V:  0.000 Cache: 155s/150MB
elapsed: 11.403000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 13.084000ms
elapsed: 15.071000ms
elapsed: 15.877000ms
elapsed: 13.745000ms:55 (0%) A-V:  0.000 Cache: 155s/150MB
elapsed: 12.551000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 11.770000ms
elapsed: 11.254000ms
elapsed: 12.685000ms:55 (0%) A-V:  0.000 Cache: 155s/150MB
elapsed: 13.564000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 12.466000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 12.821000ms
elapsed: 12.132000ms
elapsed: 13.971000ms
elapsed: 12.649000ms
elapsed: 13.823000ms
elapsed: 12.652000ms
elapsed: 15.567000ms
elapsed: 11.383000ms
elapsed: 12.929000ms
elapsed: 13.692000ms
elapsed: 11.571000ms:55 (0%) A-V:  0.000 Cache: 155s/150MB
elapsed: 10.879000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 10.385000ms:55 (0%) A-V:  0.000 Cache: 155s/150MB
elapsed: 13.021000ms
elapsed: 11.574000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 15.953000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 13.048000ms
elapsed: 13.180000ms
elapsed: 13.477000ms
elapsed: 10.884000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 10.325000ms
elapsed: 10.607000ms
elapsed: 11.988000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 14.026000ms
elapsed: 10.476000ms
elapsed: 14.171000ms
elapsed: 16.103000ms
elapsed: 12.539000ms
elapsed: 12.668000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 13.460000ms
elapsed: 13.848000ms
elapsed: 12.968000ms
elapsed: 14.630000ms:55 (0%) A-V:  0.000 Cache: 153s/150MB
elapsed: 12.952000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 15.073000ms
elapsed: 12.635000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 11.216000ms
elapsed: 12.364000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 11.799000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 12.025000ms:55 (0%) A-V:  0.000 Cache: 154s/150MB
elapsed: 12.102000ms:55 (1%) A-V:  0.000 Cache: 154s/150MB
elapsed: 11.204000ms:55 (1%) A-V:  0.000 Cache: 153s/150MB
elapsed: 10.759000ms
elapsed: 13.668000ms
elapsed: 11.130000ms
elapsed: 14.123000ms
elapsed: 10.070000ms:55 (1%) A-V:  0.000 Cache: 153s/150MB
elapsed: 11.985000ms
elapsed: 11.321000ms:55 (1%) A-V:  0.000 Cache: 153s/150MB
elapsed: 11.527000ms
```
</p>
</details>

I did several runs and the above data is quite representative. Of course these are all examples of launching `mpv` from a shell. I've built an app bundle from my source with these changes, but I'm not getting any of the custom logging about how fast the reads are happening... 

Anyway, it definitely looks like reads are faster with the change (because they are smaller), but I can't notice a difference around startup latency. On the other hand, with the change there are a lot *more* reads required to play a given amount of content. In both cases, the default amount of forward-buffer filled up in roughly the same amount of wall-clock time.

Also, is it fair to assume that `demuxer-readahead-secs` wouldn't help here?

... also I just now realized I only tested two out of the three cases in question. Sorry about that, but I'm out of time for now :)

**Comment by mikezila** [comment] 2021-05-02 03:47
I gave this a spin and don’t see any appreciable difference in the issue.

**Comment by Akemi** [comment] 2021-05-12 17:57
i think this and issue #7405 are the same. since a network share is used here it automatically activates the cache and causes the same behaviour like manually activating the cache on a local file. probably issue #4434 is another part of this problem, and the source of it are both those problems together.

it would be nice to know if PR #8826 and #8266 together (or even just the former) fixes this problem.

**Comment by Akemi** [comment] 2021-05-16 12:14
both fixes are now in master. so it might be easier to test now.

i also made a new mpv bundle with both fixed included. should work on 10.14+. on a side note it also includes vulkan/moltenvk support.

**Comment by mikezila** [comment] 2021-05-16 22:47
I tried the bundle you provided and the issue seems to be fixed. The cache indicator on the seek bar is still present but seeking seems to work fine.

**Comment by Akemi** [comment] 2021-05-16 22:57
i am not sure what you mean by "cache indicator on the seek bar is still present"? since it's a mounted network drive it automatically activates the cache, so that is expected.

since the issues has been fixed, i will close this. thank you for testing.

**Closed by Akemi** 2021-05-16 22:57 UTC
Labels: os:mac
