### ISSUE TITLE
mpv lags at the beginning when playing videos through samba on macOS

### ISSUE THREAD

**Issue by d25fe0be** [mpv-player/mpv#4434] opened 2017-05-17 18:30 UTC
### mpv version and platform

git master, macOS 10.12.5

### Reproduction steps

Play videos through samba on macOS 10.12.5, with a not-very-fast link speed (~100Mbps) and a relative high video bitrate (~30Mbps).

### Expected behavior

The video should be played fluently since the link can sustain a good enough transfer rate for the video.

### Actual behavior

Video lags several times at the beginning of the play / navigation. Cache is not filled with a ~constant speed, but rather bursty.

### Analysis

By adding some timing code into mpv's source, the lag should be caused by the call to `read` at `stream/fill_buffer.c:81`. 

At the beginning of the cache fill, each time `read` is called, the syscall uses ~2 times time as the previous call:

```
[file] elapsed: 1645.987000ms, size 65536
[file] elapsed: 3203.410000ms, size 65536
[file] elapsed: 6132.622000ms, size 65536
[file] elapsed: 14265.288000ms, size 65536
...
```

And finally stablized.

Since even when mpv is paused (Ctrl+Z in terminal) the network keeps transferring data, it should be the kernel doing some read ahead or other cache/buffer stuffs on behalf of mpv, presumably using a doubling algorithm (as the time usage doubles each time). And the kernel seems to do it in a poor way, as the buffering blocks the syscall from returning.

The system's behavior totally ruins how mpv tries to behave IMO -- mpv reads a 64K chunk each time, which IIUC intentionally tries to not block for too long.

### A naive fix

Since mpv is caching the video itself anyway, we might simply disable system's cache by `fcntl(fd, F_NOCACHE, 1)`. 

A naive fix might be (Apologize that I'm not familiar with mpv's source code, so this fix may break some other things..):

```
--- a/stream/stream_file.c
+++ b/stream/stream_file.c
@@ -275,6 +275,11 @@ static int open_f(stream_t *stream)
                    filename, mp_strerror(errno));
             return STREAM_ERROR;
         }
+        if (fcntl(p->fd, F_NOCACHE, 1) < 0) {
+            MP_ERR(stream, "Cannot disable cache on file '%s': %s\n",
+                   filename, mp_strerror(errno));
+            return STREAM_ERROR;
+        }
         struct stat st;
         if (fstat(p->fd, &st) == 0) {
             if (S_ISDIR(st.st_mode)) {
```

After applying this fix and recompiling, the cache is filled with a ~constant speed, and the lag at the beginning of the play / navigation disappears.

This patch also fixes the (sometimes) lag on exit (when play through samba on macOS), since the call to `read` is no longer blocked by kernel and returns more quickly. Previously mpv may get blocked by that call for several seconds when exiting.

**Comment by wm4** [comment] 2017-05-18 09:45
Well, I'm not sure about that.

Normally I'd say this should be fixed in the filesystem implementation, but I guess there's little chance Apple will do that.

Does it improve if you lower the amount of data read at once? Tune `stream->read_chunk`.

And then, `F_NOCACHE` seems entirely OSX-specific.

AFAIK we can detect this FS via `check_stream_network`, even on OSX. Is there something that could be done there, to reduce the amount of ifdefs and OS-specific hackery needed in portable code?

**Comment by d25fe0be** [comment] 2017-05-18 13:52
Yes, it should be an issue inside the filesystem / kernel.

Unfortunately reducing (or increasing) `stream->read_chunk` seems not to address the issue. (Tried read_chunk = 2K / 4K / 1M / 10M.)

What's interesting is that even built-in utilities such as `cp` seems to suffer from this as well. When copying a big file through samba, the lag between hitting Ctrl+C and returning to shell is noticeable.

I also tried to copy a (smaller) video (which also shows bursty read through samba) to local flash and play it, this time `read`'s behavior backs to normal -- the bursty transfer just disappears.

I think it should do the job to disable system's cache only when `check_stream_network(fd) == true`, as playing from local flash works fine. 

FWIW, after searching on the web I also found this: [FileRead() with F_NOCACHE doesn't jive with NFS on MacO](https://trac.videolan.org/vlc/ticket/8446). Despite its irrelevant title / description, VLC seems to have suffered the same problem, and uses a different technique to address this. They disabled OS's read-ahead by `fcntl (fd, F_RDAHEAD, 0);` (apparently OSX-specific as well.), which also results in a ~constant data transfer rate.

**Comment by tjolle** [comment] 2017-07-13 07:03
I've been having a lot of problems using mpv on macOS since I play media through Samba and the constant issue of sudden stops in playback thanks to the transfer rate. I used the "quick-n-dirty" patch posted in the first message and have been having no problems since, so I just wanted to throw my experience in the mix in hopes of a official solve.

**Comment by Akemi** [comment] 2020-11-17 22:25
can anyone test PR #8266? since i couldn't reproduce this.

**Closed** 2021-05-16 11:48 UTC
Labels: os:mac
