### ISSUE TITLE
Error when play bilibili video(have segments) in mpv 0.29

### ISSUE THREAD

**Issue by kesdoputr** [mpv-player/mpv#6033] opened 2018-07-29 03:25 UTC
### mpv version and platform
mpv version
```
Windows 7
version 0.29 64bit build on https://mpv.srsfckn.biz/
```
Youtube-dl version
Newest youtube-dl 2018.07.29

### Reproduction steps
**When i play bilibili video by mpv 0.29, if ther video has only one segment it can play normally,
but if i back to use mpv 0.28, it can play with these segments like chapter.**

> ex:
> https://www.bilibili.com/video/av27592976
> 
picture (left ver0.28　right ver0.29)
![default](https://user-images.githubusercontent.com/16981364/43362606-0fb9300e-9321-11e8-95e1-c60da6ac6aec.png)

**But if the video has some segments more than one, it cause error in 0.29**

> ex:
> https://www.bilibili.com/video/av18178195
>
picture (left ver0.28　right ver0.29)
![default](https://user-images.githubusercontent.com/16981364/43362629-abb70c42-9321-11e8-9899-3db3feb8060f.png)

The different is just mpv's version, youtube-dl's version is the same, 
what setting can i change with the new version? Thank you for your reply.

**Comment by mc4man** [comment] 2018-07-29 19:42
Probably from this commit 
https://github.com/mpv-player/mpv/commit/442ff936263e6e9f1da865cc53e8153f09e30702

**Comment by kesdoputr** [comment] 2018-07-30 10:46
@mc4man 
First thank you for you reply. But i use the compiled exe, how can i revert this commit?

**Comment by kesdoputr** [comment] 2018-07-30 11:13
Oh thank for your reply, i think i found the way
I get the newest ytdl_hook.lua from https://github.com/mpv-player/mpv/tree/master/player/lua
And just delete the line **and json.entries[1].protocol == "m3u8_native"**

Then i use --no-ytdl to play url, anything is seems ok now.
Is my step is right?

**Comment by mc4man** [comment] 2018-07-30 12:24
Idk, can't see how commenting or removing a line in ytdl_hook.lua and then not using ytdl would do anything..
At least here (linux) ytdl is needed for that url.
It does appear that commenting out that one line in ytdl_hook.lua does allow your url to play & also the url in bug report this commit was 'fixing'
For yourself do whatever seems to work but don't close this issue..

**Comment by wm4** [comment] 2019-10-25 11:32
I get 403 for all of these. Can't reproduce.

**Closed by wm4** 2019-10-25 11:32 UTC
Labels: scripting:ytdl-hook

**Comment by zc62** [comment] 2019-10-25 23:53
> I get 403 for all of these. Can't reproduce.

@wm4 Because the first video was deleted (by the uploader or the site).

I can give you a random link that works with mpv, for example https://www.bilibili.com/video/av73339596

**Comment by wm4** [comment] 2019-10-26 11:01
This gets me a simple flv stream, which seems to work.

**Comment by zc62** [comment] 2019-10-27 22:39
So this is still a valid issue?

**Comment by kesdoputr** [comment] 2020-02-23 14:22
Report for this issue, now i still need to delete the line
and json.entries[1].protocol == "m3u8_native"
and use --no-ytdl to play bilibili video who have multi segments

or i will just get the first segment

sample link
https://www.bilibili.com/video/av20562774

**Comment by wm4** [comment] 2020-02-23 14:29
The link you just posted works for me on git master and default settings. I get a 5 minutes flv stream.

**Comment by wm4** [comment] 2020-02-23 14:33
Ah, I think I get it. Those are indeed "fragments", but youtube-dl returns it as playlist. It triggers none of the fragmented video paths in our script. It goes through the code that is used with normal youtube playlists and such. So I think the problem is with youtube-dl's bilibili extractor, not mpv.

**Comment by kesdoputr** [comment] 2020-02-23 16:10
Thanks for the reply, now my method is put the modified ytdl_hook.lua in scripts
and add --no-ytdl let mpv use it, now it seems work for the fragments video.
