### ISSUE TITLE
mpv ignores whether a dma-buf format is advertised or not

### ISSUE THREAD

**Issue by jadahl** [mpv-player/mpv#7516] opened 2020-03-09 08:17 UTC
### Important Information

- mpv version: 0.32.0
- Linux Distribution and Version: Fedora 32
- Source of the mpv binary: Fedora repositories
- Window Manager and version: GNOME 3.36
- GPU driver and version: Intel (Linux 5.6.0, mesa 2.0.1)

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

1. Play video

Result:

```
[destroyed object]: error 7: failed to import supplied dmabufs: Unsupported buffer format 808669784
```

Some initial debug shows mpv is not compliant:

Compositor advertises the following dma-buf formats:
```
[2517914.764] zwp_linux_dmabuf_v1@17.format(875713089)
[2517914.770] zwp_linux_dmabuf_v1@17.modifier(875713089, 0, 0)
[2517914.783] zwp_linux_dmabuf_v1@17.modifier(875713089, 16777216, 1)
[2517914.797] zwp_linux_dmabuf_v1@17.modifier(875713089, 16777216, 2)
[2517914.810] zwp_linux_dmabuf_v1@17.modifier(875713089, 16777216, 4)
[2517914.823] zwp_linux_dmabuf_v1@17.format(875713112)
[2517914.830] zwp_linux_dmabuf_v1@17.modifier(875713112, 0, 0)
[2517914.843] zwp_linux_dmabuf_v1@17.modifier(875713112, 16777216, 1)
[2517914.857] zwp_linux_dmabuf_v1@17.modifier(875713112, 16777216, 2)
[2517914.873] zwp_linux_dmabuf_v1@17.modifier(875713112, 16777216, 4)
[2517914.896] zwp_linux_dmabuf_v1@17.format(808669761)
[2517914.911] zwp_linux_dmabuf_v1@17.modifier(808669761, 0, 0)
[2517914.932] zwp_linux_dmabuf_v1@17.modifier(808669761, 16777216, 1)
[2517914.951] zwp_linux_dmabuf_v1@17.modifier(808669761, 16777216, 2)
[2517914.973] zwp_linux_dmabuf_v1@17.format(909199186)
[2517914.984] zwp_linux_dmabuf_v1@17.modifier(909199186, 0, 0)
[2517915.001] zwp_linux_dmabuf_v1@17.modifier(909199186, 16777216, 1)
[2517915.055] zwp_linux_dmabuf_v1@17.modifier(909199186, 16777216, 2)
```

mpv then creates a buffer with another format

```
[2518099.372]  -> zwp_linux_buffer_params_v1@21.create_immed(new id wl_buffer@22, 1920, 1080, 808669784, 0)
```

which is a violation of the protocol in question.

**Comment by Dudemanguy** [comment] 2020-03-09 18:26
Hmm, gave this a whirl on GNOME 3.36 (also Intel) and it detected and picked 875713112 for me. This might be tricky to reproduce.

**Comment by jadahl** [comment] 2020-03-24 07:22
FWIW, this could be a bug in mesa: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/4294

**Comment by r3b311i0n** [comment] 2020-03-31 15:18
I'm getting the same error using Arch Linux with GNOME 3.36.1 and mesa 20.0.2. Downgrading mesa to 19.3.4 fixes it for me.

**Comment by Dudemanguy** [comment] 2020-03-31 19:09
Still works for me, but maybe I'm just lucky. Probably safe to consider this one a Mesa bug for now though.

**Comment by r3b311i0n** [comment] 2020-03-31 21:30
Yup. Forcing the old driver by using `MESA_LOADER_DRIVER_OVERRIDE=i965` fixes the issue.

**Comment by thedemz** [comment] 2020-04-01 18:13
> I'm getting the same error using Arch Linux with GNOME 3.36.1 and mesa 20.0.2. Downgrading mesa to 19.3.4 fixes it for me.

Same

**Comment by terzievk** [comment] 2020-04-02 11:29
> > I'm getting the same error using Arch Linux with GNOME 3.36.1 and mesa 20.0.2. Downgrading mesa to 19.3.4 fixes it for me.
> 
> Same

same

**Comment by pitlochry** [comment] 2020-04-14 07:34
> I'm getting the same error using Arch Linux with GNOME 3.36.1 and mesa 20.0.2. Downgrading mesa to 19.3.4 fixes it for me.

This is what I did, and it works. But this can only be a temporary fix. So, is this an mpv, wayland or mesa issue, and where will it be fixed?

**Comment by jadahl** [comment] 2020-04-14 07:35
> and where will it be fixed?

It should be fixed by the linked mesa merge request.

**Comment by Dudemanguy** [comment] 2020-04-29 21:13
The mesa MR was merged so that should fix this one. Feel free to reopen if it doesn't.

**Closed by Dudemanguy** 2020-04-29 21:13 UTC
Labels: os:linux, upstream:mesa, vo:gpu:wayland
