### ISSUE TITLE
compiler warnings, cc (gcc) 8.1.0 and clang 6.0.0

### ISSUE THREAD

**Issue by requiredregistration** [mpv-player/mpv#5821] opened 2018-05-13 15:34 UTC
git master

cc warnings
```
[ 94/244] Compiling common/common.c
../input/ipc-unix.c: In function ‘ipc_thread’:
../input/ipc-unix.c:327:5: warning: ‘strncpy’ specified bound 108 equals destination size [-Wstringop-truncation]
     strncpy(ipc_un.sun_path, arg->path, sizeof(ipc_un.sun_path));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
[128/244] Compiling demux/demux_playlist.c
../player/audio.c: In function ‘reinit_audio_filters_and_output’:
../player/audio.c:253:33: warning: ‘%s’ directive output may be truncated writing up to 127 bytes into a region of size between 66 and 76 [-Wformat-truncation=]
     snprintf(buf, buf_sz, "%dHz %s %dch %s", rate,
                                 ^~
              ch, channels.num, af_fmt_to_str(format));
              ~~                  
../player/audio.c:253:27: note: directive argument in the range [0, 255]
     snprintf(buf, buf_sz, "%dHz %s %dch %s", rate,
                           ^~~~~~~~~~~~~~~~~
../player/audio.c:253:5: note: ‘snprintf’ output 10 or more bytes (assuming 139) into a destination of size 80
     snprintf(buf, buf_sz, "%dHz %s %dch %s", rate,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              ch, channels.num, af_fmt_to_str(format));
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
[137/244] Compiling video/out/gpu/spirv.c
../video/out/gpu/spirv.c: In function ‘spirv_compiler_init’:
../video/out/gpu/spirv.c:68:9: warning: ‘strncpy’ specified bound 32 equals destination size [-Wstringop-truncation]
         strncpy(ctx->spirv->name, name, sizeof(ctx->spirv->name));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

clang warnings
```
../video/out/opengl/hwdec_drmprime_drm.c:141:36: warning: suggest braces around initialization of subobject [-Wmissing-braces]
    struct drm_frame next_frame = {0};
                                   ^
                                   {}
1 warning generated.
```
```
../player/command.c:4830:35: warning: suggest braces around initialization of subobject [-Wmissing-braces]
    struct mpv_node dummy_node = {0};
                                  ^
                                  {}
1 warning generated.
```
```
../video/decode/vd_lavc.c:714:38: warning: suggest braces around initialization of subobject [-Wmissing-braces]
    ctx->hwdec = (struct hwdec_info){0};
                                     ^
                                     {}
1 warning generated.
```
```
../video/out/gpu/video.c:997:34: warning: suggest braces around initialization of subobject [-Wmissing-braces]
    *vimg = (struct video_image){0};
                                 ^
                                 {}
../video/out/gpu/video.c:997:34: warning: suggest braces around initialization of subobject [-Wmissing-braces]
    *vimg = (struct video_image){0};
                                 ^
                                 {}
2 warnings generated.
```
```
../video/out/drm_common.c:453:30: warning: suggest braces around initialization of subobject [-Wmissing-braces]
    struct sigaction act = { 0 };
                             ^
                             {}
../video/out/drm_common.c:460:30: warning: suggest braces around initialization of subobject [-Wmissing-braces]
    struct sigaction act = { 0 };
                             ^
                             {}
2 warnings generated.
```
```
../video/out/gpu/shader_cache.c:924:43: warning: suggest braces around initialization of subobject [-Wmissing-braces]
            struct sc_cached_uniform u = {0};
                                          ^
                                          {}
../video/out/gpu/shader_cache.c:924:43: warning: suggest braces around initialization of subobject [-Wmissing-braces]
            struct sc_cached_uniform u = {0};
                                          ^
                                          {}
2 warnings generated.
```
```
../demux/demux_mkv.c:396:30: warning: suggest braces around initialization of subobject [-Wmissing-braces]
    struct ebml_info info = {0};
                             ^
                             {}
1 warning generated.
```
```
../video/out/vulkan/ra_vk.c:1739:41: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        VkClearColorValue clearColor = {0};
                                        ^
                                        {}
1 warning generated.
```
```
../video/out/gpu/utils.c:48:34: warning: suggest braces around initialization of subobject [-Wmissing-braces]
    *pool = (struct ra_buf_pool){0};
                                 ^
                                 {}
1 warning generated.
```

**Comment by jeeb** [comment] 2018-05-13 15:41
The clang ones are [well-known mis-warnings](https://bugs.llvm.org/show_bug.cgi?id=32156) that match C++, but not C. For C, if I recall correctly `{ }` isn't even correct for C(99) as opposed to C++.

**Comment by wm4** [comment] 2018-05-13 16:06
I have no idea why you're reporting these.

**Comment by requiredregistration** [comment] 2018-05-15 15:27
about the cc (gcc) warnings: all the previous times there were 0 warnings.

about the clang warnings: that was the first time i used clang for the compilation of mpv.

if the things that the compilers are warning the user about are not a problem, then maybe you should disable specific warnings.

**Comment by CounterPillow** [comment] 2018-05-16 06:05
The compilers aren't warning the users of mpv about things, they're warning the developers of mpv about them. Warnings are there to warn developers of potential bugs in the code.

Warnings still are useful to leave on even if they produce some false-positives; disabling them cannot be done on a per-instance basis but only on a per-type-of-warning basis. This would let actual bugs slip through more easily. As for the clang warnings, that's a clang problem, not an mpv problem.

Fixing warnings that are otherwise unoffensive is a great way to start contributing to a project! If you can find a correct solution that does not produce these gcc warnings, but functions as intended, a patch would likely be merged if it's not too hacky.

**Comment by requiredregistration** [comment] 2018-05-29 13:32
the compiler warnings are for everyone who uses compilers. the user can be informed that something is wrong and/or that something might be wrong. it is the same with warning and error messages during run-time.

i reported the warnings, because warnings can mean that something is wrong. since i am not a developer, i cannot say, in all cases, if something is wrong or not. if the things that it warns about are not an issue, then those warnings should be disabled.

there are many developers that have bad habits and that use very old versions. that is another reason i reported the warnings.

if i could fix these things myself, i would have created a pull request instead of an issue.

**Comment by requiredregistration** [comment] 2019-03-14 19:37
new ones.

clang 7.0.1

```
[ 92/237] Compiling player/client.c
../player/client.c:1029:34: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        cmd->result = (mpv_node){0};
                                 ^
                                 {}
../player/client.c:1106:30: warning: suggest braces around initialization of subobject [-Wmissing-braces]
    cmd->result = (mpv_node){0};
                             ^
                             {}
2 warnings generated.
```

**Comment by Argon-** [comment] 2019-03-14 20:33
Haven't you read what jeeb wrote above?

**Closed** 2019-09-20 17:16 UTC
