### ISSUE TITLE
Allow to stack secondary subtitles on bottom of screen

### ISSUE THREAD

**Issue by teohhanhui** [mpv-player/mpv#7622] opened 2020-04-15 18:15 UTC
### Expected behavior of the wanted feature

Being able to stack the secondary subtitles on top or below the primary subtitles, both at the bottom of the screen.

The effect should be like no. 5 in this blog post: https://www.raymond.cc/blog/playing-two-subtitles-at-the-same-time-in-dvd-player-and-computer/ but without having to merge multiple subtitles files into one.

This kind of multilingual display of subtitles is very common in Malaysia where I come from. In the cinema, an English movie would typically have Malay and Chinese subtitles at the same time, both displayed at the bottom of the screen. A non-English/Malay/Chinese movie might sometimes even have English, Malay and Chinese subtitles all at the same time.

Can't find a Malaysian example, but here's one from Hong Kong: https://www.scmp.com/magazines/hk-magazine/article/2037102/ask-mr-know-it-all-why-do-all-films-hong-kong-have-subtitles

### Alternative behavior of the wanted feature

N/A

### Log file

N/A

**Comment by link-webcreations** [comment] 2020-04-21 07:12
It would be lovely!

**Comment by wm4** [comment] 2020-04-21 17:44
Technically hard, because "secondary" subs are renderered completely separately. Both are renderered into the video without knowing about each other. To stack them you'd need to handle them by the same renderer, which may be significantly harder.

For now, you may need to write a script or so that produces a merged subtitle file.

**Comment by felagund** [comment] 2022-08-28 16:13
What about allowing the user to move the secondary subtitles manually? It would have a downside that with two one-line subtitles, there would be a gap, but still better than nothing.

**Comment by Asraelite** [comment] 2023-07-18 18:25
For anyone else looking to just be able to manually position secondary subtitles for now, I made a quick and dirty patch:

https://gist.github.com/Asraelite/17795f07f6f71d768a3206eed5e90119

Apply it with `git apply mpv_secondary_sub_position.diff` and build, then you can use the flag `--secondary-sub-pos=90`.

**Comment by kqvanity** [comment] 2024-07-23 06:09
It's been a while. I assume this optional positioning feature never come to dear light

**Comment by guidocella** [comment] 2024-07-23 06:15
Use `--secondary-sub-pos`.

**Comment by kqvanity** [comment] 2024-07-23 06:37
@guidocella oh thanks! Because the issue is it still open, and @Asraelite hasn't been marked as being 'merged' yet, I thought it's still not included.

One additional question. How can I do the exact same but with the embedded subtitles?

**Comment by guidocella** [comment] 2024-07-23 06:39
It makes no difference if subtitles are embedded for positioning as long as they're not hard subs.

**Comment by kqvanity** [comment] 2024-07-23 06:39
@guidocella oh thanks! Because the issue is it still open, and @Asraelite hasn't been marked as being 'merged' yet, I thought it's still not included.

**Comment by kqvanity** [comment] 2024-07-23 06:42
> It makes no difference if subtitles are embedded for positioning as long as they're not hard subs.

Just figured it out. It takes the `--sid` and `--secondary-sid` flags for the respective tracks. Thanks for pointing it all out. kept fighting with google trying to find a simple cli tool to merge subtitles, but everyone is recommending full-blown GUI apps, and chatgpt kept leading me astray

**Comment by Dudemanguy** [comment] 2024-07-23 14:13
`--secondary-sub-pos` was added in #13073.

**Closed by Dudemanguy** 2024-07-23 14:13 UTC
Labels: meta:feature-request, core:subtitle, core:option-param-conf

**Comment by zestyping** [comment] 2024-11-09 04:47
For future folks who come along looking for this feature — I ended up merging the two subtitle files into one file with https://subtitletools.com/merge-subtitles-online and the results were great!  It even lets you select an alternate colour for one of the files.
