### ISSUE TITLE
YouTube: [cplayer] Failed to recognize file format

### ISSUE THREAD

**Issue by sebma** [mpv-player/mpv#4775] opened 2017-08-17 17:06 UTC
### mpv version and platform

`mpv 0.25.0-7bfeb8b-amended on Ubuntu 14.04.5 LTS`

### Reproduction steps
`mpv http://www.youtube.com/watch?v=eemfgDg-LXw`
### Expected behavior
Playing the video
### Actual behavior
```
[ytdl_hook] Lua error: @ytdl_hook.lua:64: bad argument #1 to 'len' (string expected, got nil)
[ffmpeg] tls: A TLS packet with unexpected length was received.
Failed to recognize file format.
```
### Log file

```
$ $(which mpv) --no-config -v http://www.youtube.com/watch?v=eemfgDg-LXw
[cplayer] Command line options: '--no-config' '-v' 'http://www.youtube.com/watch?v=eemfgDg-LXw'
[cplayer] mpv 0.25.0-7bfeb8b-amended (C) 2000-2017 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Tue Jun 27 03:36:23 UTC 2017
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.66.100
[cplayer]    libavcodec      57.99.102
[cplayer]    libavformat     57.75.100
[cplayer]    libswscale      4.7.101
[cplayer]    libavfilter     6.94.100
[cplayer]    libswresample   2.8.100
[cplayer] ffmpeg version: git-2017-06-25-73ea2a0
[cplayer] 
[cplayer] Configuration: ./waf configure --enable-pdf-build --enable-dvbin --enable-dvdread --enable-dvdnav --prefix=/usr --confdir=/etc/mpv
[cplayer] List of enabled features: 52deb alsa asm atomics audio-input avutil-content-light-level avutil-imgcpy-uc build-date cplayer cplugins cuda-hwaccel debug-build dlopen drm dvbin dvdnav dvdread dvdread-common encoding fchmod gl gl-x11 glibc-thread-name glob gnuc iconv is_ffmpeg jack jpeg lcms2 libass libass-osd libav libavcodec libavdevice libbluray libdl libm librt libv4l2 linux-fstatfs lua nanosleep optimize oss-audio posix posix-or-mingw posix-spawn pthreads pulse rubberband shm subprocess termios tv tv-v4l2 uchardet vaapi vaapi-glx vaapi-hwaccel vaapi-x11 vdpau vdpau-gl-x11 vdpau-hwaccel videodev vt.h x11 xv zlib
[global] config path: '' -> '-'
[cplayer] Setting option 'config' = 'no' (flags = 8)
[cplayer] Setting option 'v' = '' (flags = 8)
[osc] Loading lua script @osc.lua...
[osc] loading mp.defaults
[osc] loading @osc.lua
[osc] lua-settings/osc.conf not found. 
[cplayer] Run command: define-section, flags=0, args=[showhide, mouse_move script-binding osc/__keybinding1
[cplayer] mouse_leave script-binding osc/__keybinding2
[cplayer] , force]
[cplayer] Run command: enable-section, flags=0, args=[showhide, allow-hide-cursor+allow-vo-dragging]
[cplayer] Run command: define-section, flags=0, args=[input, mouse_btn0 script-binding osc/__keybinding3
[cplayer] shift+mouse_btn0 script-binding osc/__keybinding4
[cplayer] mouse_btn2 script-binding osc/__keybinding5
[cplayer] mouse_btn3 script-binding osc/__keybinding6
[cplayer] mouse_btn4 script-binding osc/__keybinding7
[cplayer] axis_up script-binding osc/__keybinding8
[cplayer] axis_down script-binding osc/__keybinding9
[cplayer] mouse_btn0_dbl ignore
[cplayer] shift+mouse_btn0_dbl ignore
[cplayer] mouse_btn2_dbl ignore
[cplayer] , force]
[cplayer] Run command: enable-section, flags=0, args=[input, ]
[cplayer] Run command: define-section, flags=0, args=[input_osc, del script-binding osc/__keybinding10
[cplayer] , default]
[cplayer] Run command: enable-section, flags=0, args=[input_osc, allow-hide-cursor+allow-vo-dragging]
[cplayer] Run command: define-section, flags=0, args=[input_forced_osc, , force]
[cplayer] Run command: enable-section, flags=0, args=[input_forced_osc, allow-hide-cursor+allow-vo-dragging]
[cplayer] Done loading @osc.lua.
[ytdl_hook] Loading lua script @ytdl_hook.lua...
[ytdl_hook] loading mp.defaults
[cplayer] Run command: disable-section, flags=0, args=[input]
[osd/libass] Shaper: FriBidi 0.19.6 (SIMPLE) HarfBuzz-ng 1.0.1 (COMPLEX)
[osd/libass] Setting up fonts...
[ytdl_hook] loading @ytdl_hook.lua
[cplayer] Run command: hook-add, flags=0, args=[on_load, 1, 10]
[cplayer] Run command: hook-add, flags=0, args=[on_preloaded, 2, 10]
[cplayer] Done loading @ytdl_hook.lua.
[global] config path: 'watch_later' -> '-'
[global] config path: 'watch_later' -> '-'
[cplayer] Playing: http://www.youtube.com/watch?v=eemfgDg-LXw
[cplayer] Running hook: ytdl_hook/on_load
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[ytdl_hook] youtube-dl succeeded! 
[ytdl_hook] 
[ytdl_hook] stack traceback:
[ytdl_hook] 	[C]: in function 'len'
[ytdl_hook] 	@ytdl_hook.lua:64: in function 'edl_escape'
[ytdl_hook] 	@ytdl_hook.lua:110: in function 'edl_track_joined'
[ytdl_hook] 	@ytdl_hook.lua:142: in function 'add_single_video'
[ytdl_hook] 	@ytdl_hook.lua:414: in function 'fn'
[ytdl_hook] 	mp.defaults:518: in function 'handler'
[ytdl_hook] 	mp.defaults:339: in function 'handler'
[ytdl_hook] 	mp.defaults:458: in function 'call_event_handlers'
[ytdl_hook] 	mp.defaults:495: in function 'dispatch_events'
[ytdl_hook] 	mp.defaults:451: in function <mp.defaults:450>
[ytdl_hook] 	[C]: in ?
[ytdl_hook] 	[C]: in ?
[ytdl_hook] Lua error: @ytdl_hook.lua:64: bad argument #1 to 'len' (string expected, got nil)
[ytdl_hook] Exiting...
[ffmpeg] Opening http://www.youtube.com/watch?v=eemfgDg-LXw
[ffmpeg] Mime-type: 'text/html; charset=utf-8'
[ffmpeg] Stream opened successfully.
[cache] Cache size set to 150000 KiB (75000 KiB backbuffer)
[demux] Trying demuxers for level=normal.
[ffmpeg] tls: A TLS packet with unexpected length was received.
[cache] EOF reached.
[lavf] No format found, try lowering probescore or forcing the format.
[demux] Trying demuxers for level=unsafe.
[lavf] No format found, try lowering probescore or forcing the format.
[cache] Terminating cache...
[cache] Cache exiting...
[cplayer] Opening failed or was aborted: http://www.youtube.com/watch?v=eemfgDg-LXw
[cplayer] finished playback, unrecognized file format (reason 4)
[cplayer] Failed to recognize file format.
[cplayer] 
[cplayer] 
[cplayer] Exiting... (Errors when loading file)
[osc] Exiting...
$ echo $?
2
```

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by wiiaboo** [comment] 2017-08-17 17:09
Duplicate of https://github.com/mpv-player/mpv/issues/4728. See https://github.com/mpv-player/mpv/issues/4728#issuecomment-320725058 for a workaround.

**Closed by wiiaboo** 2017-08-17 17:09 UTC
