### ISSUE TITLE
Supporting Lua 5.4

### ISSUE THREAD

**Issue by sallyahaj** [mpv-player/mpv#9225] opened 2021-09-20 09:36 UTC
Hello there,
Due the new version of Lua, there is one of the new build package of 'mpv' was refused to work with Lua-5.4, which is available in the official fedora repo. Instead, 'mpv' asks for version 5.1 or 5.2.
So, I think it's a time to give mpv the support for Lua new version.

Thank you.

**Comment by avih** [comment] 2021-09-20 09:38
Duplicate of #5205

**Closed by avih** 2021-09-20 09:38 UTC
Labels: meta:feature-request

**Comment by leigh123linux** [comment] 2021-09-20 10:19
Maybe I will orphan mpv at rpmfusion then this bug tracker will be flooded with fedora issue!

**Comment by CounterPillow** [comment] 2021-09-20 10:57
We're shuddering in fear

**Comment by avih** [comment] 2021-09-20 11:39
@leigh123linux sticking to lua 5.1/5.2/jit is the best thing we can do right now. It's not great at all, and we're not claiming it is. We're aware of the issues this causes to maintainers, and we just don't have a good solution.

But read the faq entry and the linked issue.

Our options are sticking to specific version, or breaking user scripts whenever lua releases a new version, because that seem to be breaking backward compatibility for scripts, and the mainstream lua maintainers don't consider breaking scripts an issue, because it's supposed to be embedded and therefore not care about other versions.

mpv doesn't bundle 3rd party packages, because we can't maintain them, and even if we bundled lua 5.2 tarball, if there are issues with it then we can't fix them, or ensure it compiles on riscv or m1 etc.

It's a known problem, and we just don't have a solution.

If upstream lua decides to standardize the language in a way which future lua versions remain compatible with scripts which target this version (kinda like js 5.1 scripts are pretty much guaranteed to work the same even in ES2020 engine), then we can consider updating the lua support in mpv, but as long as upstream lua breaks scripts when they release a new version, we can't in good conscience keep chasing our tail with it.
