### ISSUE TITLE
Cleanup of default key bindings (second try)

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#973] opened 2014-07-31 22:39 UTC
This should be eventually done. But this time, my opinion is that we shouldn't gratuitously change bindings just because.

There are some things that _really_ should be changed and everyone agrees about, such as remapping `o`.

Some suggestions are controversial, like mapping `ESC` to exit fullscreen.

Anyway, let the bikeshedding begin.

**Comment by Wyatts** [comment] 2015-02-17 20:16
Okay, I can deal with all of this so far.  As far as where to put those other things, the vim user in me is thinking `u` is a good place for undoing things.  Looks like it's currently unbound?  In most usage scenarios I've seen, playlist stepping tends to be something that happens in bursts, but infrequently; maybe `ctrl+PGUP` and `ctrl+PGDWN`?  If they don't need to be adjacent, and simply being mnemonic is sufficient, `n` and `p` might work, though I don't really like that.

I've never intentionally used the brightness, saturation, and contrast controls.  Are they well-exercised by other users?  I have a sneaking suspicion that it'd be safe to just unbind them, or replace them with percentage-wise seeks (cf. Youtube).  Though that conflicts with volume on `9` and `0`... Hmm.

Come to think of it, are the function keys not allowed?  That's a whole dozen useful keys!  Also insert, delete, and backspace don't look to be mapped.

**Comment by wm4** [comment] 2015-02-18 23:47
>u

Undoing what?

>ctrl+PGUP

Nice idea, but apparently combinations with ctrl are a problem, on osx (they get caught by he system).

>brightness controls

Yeah, these could probably be replaced. But not sure if I want to "waste" them on percent-seeks.

>function keys

There was a problem with them too.. don't remember.

**Comment by Wyatts** [comment] 2015-02-19 13:27
> Undoing what?

I was referring to this:
> * integrate the seek undo command (`revert_seek`)

(Worth noting, I had no idea that was even a feature.) 
> combinations with ctrl are a problem, on osx

Ugh, why am I not surprised?  A bit unorthodox, but would it work to use a different modifier for the defaults on Mac?  i.e. everything would be the same only using... uh... what bucky bits do they have again?  There's "command", that silly squiggle thing, a "control" that actually behaves like meta (IIRC) and...?

> not sure if I want to "waste" them on percent-seeks.

I'm not amazingly fond of that myself, but I think they have a problem of signifying, otherwise.  Like right now they're bound in pairs, but those pairs are sort of arbitrary and you just have to remember what they do by rote.  It's pretty suboptimal.

I _could_ see them being used as toggles for boolean state of something, with the mnemonic being tied to their shifted form (cf. `=`/`-` and `9`/`0`).  But I'm not sure if a) there are enough desirable functions to bind this way, and b) if any of them could be sensibly associated with those symbols.

That's why I settled for percent seeking as an idea, as it's relatively intuitive and has precedent in a (terrible) player that everyone and their mother has used (granted, probably very few people know about that feature...).

**Comment by Hamuko** [comment] 2015-02-19 13:38
>Nice idea, but apparently combinations with ctrl are a problem, on osx (they get caught by he system).

What ctrl combinations are a problem on OS X? Because as far as I was aware, the only issue that was being discussed was combining ctrl and the right and left arrow keys, as those are by default bound to Mission Control and are active throughout the system.

Only other problematic ctrl combination that I can quickly think of is ctrl+mouse click, as that is an alternative way to perform right click on OS X.

**Comment by wm4** [comment] 2015-02-19 15:29
@Wyatts: ok. I don't overly like the idea for binding ``u`` on ``revert_seek`` - it's simply too much in the "nowhere" on the keyboard for something you'd press on impulse. Also, undo is usually on ``ctrl+z``.

@Hamuko: if that is so, then ctrl is probably free to go. But it still should be used for features that make sense with video only, because you can't use most ctrl combinations on the terminal.

**Comment by Kovensky** [comment] 2015-02-20 02:31
Ctrl+arrows on OS X are all bound by default (up for mission control, down for single app exposé, left/right for switching desktops), so those are out :(

Also, Ctrl+Mouse1 is identical to Mouse2. There probably are other system-wide Ctrl combinations too.

The remaining bucky bits are Shift, Command (Super/Win key) and Option (Alt); however, Option+(letter) or Shift+Option+(letter) actually send special characters / deadkey accents. I think it's possible to disable that Option key behavior for your window though (at least iTerm has an option to change how it behaves).

**Comment by wm4** [comment] 2015-02-20 09:59
So do we need an alias or something that maps to ctrl or alt on sane systems, and to command on OSX?

**Comment by wm4** [comment] 2015-05-10 18:12
Someone requested alt+enter to be mapped to playlist_prev.

**Comment by luke-jr** [comment] 2015-05-19 01:19
I recently updated from 0.3.11 to 0.8.3 and found Enter no longer closes MPV. Is this intentional?

**Comment by ChrisK2** [comment] 2015-05-19 05:09
Enter was just supposed to advance in the next file in the playlist and mpv exited when It was at the last file. This was changed since exit applications on enter is not really intuitive.

See https://github.com/mpv-player/mpv/blob/master/etc/restore-old-bindings.conf on how to restore the old behavior.

**Comment by felixq** [comment] 2015-07-20 13:32
I use intensively the brightness controls. contrast, ect. Not everyone watch videos in HD or YouTube.
I also use the speed controls '[ ] backspace'.

**Comment by wm4** [comment] 2015-07-20 17:41
We could keep them on more obscure key bindings.

**Comment by felixq** [comment] 2015-07-20 19:42
While not remove it's fine with me. I can put them back where they were.

**Comment by kevmitch** [comment] 2015-08-03 22:14
Toggling the framedrop with an unmodfied "d" seems kind of unnecessary given that the manpage suggests not to touch it. In contrast deinterlace toggling is far more commonly used and requires a SHIFT+"d". This should probably be inverted.

**Comment by wm4** [comment] 2015-08-03 23:12
Done. But I dropped cycling framedrop entirely. It's just entirely useless, because vo framedropping works well enough, and decoder framedropping barely works and is usually not needed. Those who really want it can add it to their custom config.

Next I want to do:

- unmap ``x`` and ``z`` (changing subtitle delay)
- map ``R`` and ``T`` to changing subtitle delay
- map ``ctrl+r`` and ``ctrl+t`` to ``sub-step``

Does anyone not like this?

**Comment by pigoz** [comment] 2015-08-04 06:31
> - unmap x and z (changing subtitle delay)
> - map R and T to changing subtitle delay

Why? Just to free up lowercase bindings?

**Comment by wm4** [comment] 2015-08-04 12:18
x/z make no sense on QWERTY keyboards. The new bindings would make sense on all QWERT keyboads.

Also, I thought it'd be a good idea to require at least a modifier for such keys which are not used that often, but are relatively disruptive to playback. Or maybe that doesn't apply here.

**Comment by felixq** [comment] 2015-08-04 12:30
Why do you say that the decoder framedrop is entirely useless? In my case it works better than vo. The vo discards entire blocks of frames while the decoder discards frames every so often, the result is visually more pleasing. I'm not saying do not change it, it's just a comment on framedrop.

On the other hand, as my native language is not English, I use subtitles constantly so it rare I find you put more difficult to use them. I do not understand this: 'x/z make no sense on QWERTY keyboards'.

**Comment by bodayw** [comment] 2015-08-04 12:33
>I do not understand this: 'x/z make no sense on QWERTY keyboards'.

I think he meant to say it makes no sense on QWERTZ keyboards.

**Comment by wm4** [comment] 2015-08-04 12:40
>Why do you say that the decoder framedrop is entirely useless? In my case it works better than vo. The vo discards entire blocks of frames while the decoder discards frames every so often, the result is visually more pleasing.

The decoder framedrop code doesn't make too much sense. For example, it still uses the container FPS, which can be wrong. And one old problem with this code was actually that it dropped too much in a row. (This also depends on how many frames are in the video streams which the decoder can safely drop.)

>I think he meant to say it makes no sense on QWERTZ keyboards.

Right. I edited it.

**Comment by 2vek** [comment] 2015-08-10 06:01
In mpv manual, `enter` key is described as 'go forward in the playlist'.

But,
1. When playing single file, `enter` exits mpv.
2. When playing two or more files or a playlist, `enter` play next file, but does not exit mpv on last file of that playlist.
This behavior is very confusing, especially when first time you encounter it.

I propose that `enter` key's behavior should be either one of these,
1. "play next or exit".
2. "play next only in playlist" and *never* exit.

Personally, I think second behavior will be consistent with manual but first one will be more convenient.

**Comment by wm4** [comment] 2015-08-10 07:18
I can't reproduce this behavior. "enter" never exits. Are you sure you don't have a non-working playlist entry? If the last entry doesn't contain a file that is playable, mpv will switch to it anyway, and then exit.

**Comment by 2vek** [comment] 2015-08-10 11:21
Oops, my mistake.

I upgraded my main laptop from debian stable to testing last week. That means mpv got upgraded from `0.6.2` to `0.9.2`. While other laptop is still on debain stable.

After testing with some files and playlist, looks like old mpv shows behavior 1 and new mpv show behavior 2. And I mixed them up because I was using both of them yesterday.

I should have verified first before posting.
Sorry.

**Comment by wm4** [comment] 2015-08-10 11:27
Yep, we intentionally changed this behavior.

**Comment by FichteFoll** [comment] 2016-09-29 21:38
As others have mentioned in https://github.com/mpv-player/mpv/issues/103 already, having the mouse wheel seek is really annoying and I'd rather have it control volume (like in other players) or do nothing instead.

The reason being that the mpv window might be active but the mouse pointer not on-top of it. Some applications (like web browsers) will not scroll when the mouse pointer is not within their window, which makes it a safe thing to do when your mouse is over a different window. For mpv, this is not the case and hitting the mouse wheel a few times will make you seek to a different part of a video and you don't know where you initially came from.

**Comment by rossy** [comment] 2016-09-30 01:45
> The reason being that the mpv window might be active but the mouse pointer not on-top of it. Some applications (like web browsers) will not scroll when the mouse pointer is not within their window, which makes it a safe thing to do when your mouse is over a different window. For mpv, this is not the case and hitting the mouse wheel a few times will make you seek to a different part of a video and you don't know where you initially came from.

As I said in #103, I totally agree with making the mouse wheel do nothing by default, though it's worth mentioning that this specific behaviour of scrolling the window with keyboard focus rather than the window under the mouse pointer is Windows-specific (X11 doesn't do it) and it differs between Windows versions. For a while, the Windows UX guidelines said to scroll the window under the mouse, but Windows itself dispatched scroll events to the window with keyboard focus. Web browsers and a few other big programs (like Office) have some code to reroute the scroll events back to the window under the mouse (if it's owned by them,) but smaller programs like mpv just handle all the scroll events that Windows gives them.

In Windows 10, Microsoft added a setting to dispatch scroll events to the window under the mouse for all programs (pictured below.) In the November update (I think,) they made it default, so mpv on Windows 10 no longer has this problem. We could probably fix it for Windows 7 as well by ignoring scroll events when the cursor is outside the window, but this would have the effect of disobeying the user's settings on Windows 10.
<img height="400" src="https://cloud.githubusercontent.com/assets/162837/18978074/f52855a2-8702-11e6-9e6a-76f123166043.png">

**Comment by mvhulten** [comment] 2017-08-16 13:10
It is great to see active development on a video player.  I am an *mplayer* user and starting/occasional *mpv* user.  I am probably expecting too much similarity between mpv and mplayer (as it is a *different* video player), and my critique comes a bit late, but I think that the following ideas may be worth putting into the discussion as mpv does not, it appears, stop being developed, which is a good thing!

Were there important reasons to remove keys for adjusting contrast, brightness and so on?  I have seen the statement that it is better to change it on the hardware, but that is not really an argument to remove the functionality.  If it resulted in less code to maintain, this is a good (but not sufficient) argument.

In general, my opinion is that there should be a very good reason for any change in the user interface, for any program.  In this sense I also do not understand why it was necessary to change the 'o' key binding (OSD), or the ←/→ from a 10 s to a 5 s change.  When any improvement is subjective or minor, I tend to respect the legacy.  Am I getting old?

**Comment by FichteFoll** [comment] 2017-08-16 13:56
Some things should be changed eventually to make them better. You'll never leave legacy or tech debth behind if you're resistant to change. While the whole key binding file could probably use an evaluation for each key, which would make adaption of that way easier (through a config option that uses the legacy bindings by default during some adaptation period, for example), some small band-aids are always nice if they don't hurt.

The bindings to cycle video, audio (and subtitle) tracks for example are kind of obscure. I can never remember audio.

**Comment by rossy** [comment] 2017-08-16 13:59
@mvhulten The bindings are gone, but the functionality is still there, so you can restore them if you want. mpv provides a sample input.conf file that restores some of MPlayer's bindings:
https://github.com/mpv-player/mpv/blob/master/etc/mplayer-input.conf

**Comment by AirPort** [comment] 2017-08-16 14:02
>Were there important reasons to remove keys for adjusting contrast, brightness and so on?

AFAIK they were not touched in the end. You can still change contrast, brightness and so on with 1-8 keys by default, and as far as I remember those were also the exact same keys used in mplayer.

**Comment by rossy** [comment] 2017-08-16 14:13
@AirPort Oh, you're right. I assumed they were gone because they were in ``mplayer-input.conf``, but it looks like they're mostly still there. I guess the hue controls were replaced with gamma controls.

**Comment by mvhulten** [comment] 2017-08-16 14:27
Thank you all for the useful comments, both on the more philosophical issue (@FichteFoll) and for the practical tip (@rossy).

@AirPort, you are right; I had the experience in the past that by default 0—8 don't do anything in mpv, but that is not the case now (mpv 0.14 on Ubuntu), so it's not an issue.

**Comment by wm4** [comment] 2017-08-16 14:28
> The bindings to cycle video, audio (and subtitle) tracks for example are kind of obscure. I can never remember audio. And some bindings would probably benefit from having their opposite action with a shift modified (like cycling subtitles).

The current state is not too bad, while changing the bindings would basically confuse every existing mpv user. But I'm still open for a redesign that makes the bindings significantly saner. But I feel like we can't just incrementally reassign individual keys over a couple of releases.

> I guess the hue controls were replaced with gamma controls.

Gamma was considered more useful.

**Comment by FichteFoll** [comment] 2017-08-16 16:05
>But I feel like we can't just incrementally reassign individual keys over a couple of releases.

Indeed, that would be awful.

I believe it has to be an "everything at once" approach with the deprecation periods known by other software. As in, you add the new feature but it's disabled by default. Later (or at the same time) you add deprecation notices so that people have time to adapt. Then you change the default but have the old option still for some users until it gets completely removed at a later time.

I still like the draft by @lachs0r in the other issue a lot: https://github.com/mpv-player/mpv/issues/103#issuecomment-30597806. This could definitely be used as a base.

(Btw, am I the only one who prefers their down key to seek foward and their up key to seek backward? Same for chapters on page up/down.)

**Comment by Tratoschek** [comment] 2017-11-01 21:07
Another suggestion: Since page down and page up was mapped to chapters (good mapping btw), on media files without chapters there are meaningless. What about (re)map page down and page up to 10 minutes seek, but only if there are no chapters present? So they can always be used to navigate quickly in the media.

**Comment by thebombzen** [comment] 2017-12-05 00:00
Is this still relevant at this point, or are the keybindings pretty stable as of now? I personally do not think they need to be changed at this point.

**Comment by Tratoschek** [comment] 2017-12-05 07:47
Do you refer to my post? This change does not force the user to change old behaviour, but instead provides more functionality in some cases, so I'd say this don't break any stable behaviour, but is simply a feature.

**Comment by kevmitch** [comment] 2017-12-05 08:28
> Do you refer to my post? This change does not force the user to change old behaviour, but instead provides more functionality in some cases, so I'd say this don't break any stable behaviour, but is simply a feature.

mpv doesn't currently offer a way to make state-dependent keybindings outside of scripts. I'm not sure if it should either beyond the current toggle / cycle functionality.

**Comment by FichteFoll** [comment] 2017-12-05 11:52
I thought that crossed my mind yesterday were key chords, where a sequence of keys could be assigned to an action much like vim bindings. I.e. `zs` to toggle subtitles, `za` to toggle audio, `zd` to toggle debanding. Furthermore, actions could be multiplied by pressing number keys before them, i.e. `10RIGHT` would invoke the action on the right key 10 times (precompute what would happen as opposed to actually seeking 10 times).

A problem with that might be that currently the number keys are already occupied. If modal bindings existed, comparable to i3wm, they could be grouped into an "adjustments" mode or similar. Except for volume, as that needs to remain accessible.

I know this is talking big as the implementation and the required changed to key bindings are considerably significant, but this is all about brainstorming imo. mpv just has a lot of commands and binding even a subset of that to a single set of keys seems difficult.

---

Regarding the current state of key bindings: I'm not too happy with the defaults, hence why my `input.conf` has many bindings to tweak them to my liking. I haven't overhauled the whole thing though and only iterate on it when I need a certain binding. Imo my ideas above would help with the jungle of bindings greatly.

**Comment by garoto** [comment] 2017-12-05 12:19
>[...] where a sequence of keys could be assigned to an action much like vim bindings. I.e. zs to toggle subtitles, za to toggle audio, zd to toggle debanding.

```
It's also possible to bind a command to a sequence of keys:
a-b-c show-text "command run after a, b, c have been pressed"
```

Already a feature no?

**Comment by FichteFoll** [comment] 2017-12-05 14:11
Indeed, it looks like it. This is great and probably something the default bindings could benefit from.

**Comment by ipatch** [comment] 2018-01-31 22:00
Am I the only one thinking that scroll up & scroll down on a touchpad should respectively raise & lower the volume 🔈 of the playback?

And that moving from left to right on the trackpad should scrub through the playback of whatever is being played with mpv?

As it currently stands with `mpv 0.28.0` scrolling  up & down scrubs through the playback, and scrolling left / right adjusts the volume of the playback.  ¯\_(ツ)_/¯

I am aware these settings can be changed in the `input.conf` file, but I strongly suggest my suggestions would make for a more sane 👩‍⚕️ overall **default experience**

Just harping 🎵 on that **attention to detail thing**.

**Comment by FichteFoll** [comment] 2018-02-01 00:43
FWIW, here are my bindings:

https://github.com/FichteFoll/dotfiles/blob/master/mpv/.config/mpv/input.conf

- Cycling fowards and backwards tracks uses a key that makes sense (i.e. `a` for audio, `v` for video, `e` for edition) and the same key with shift cycles backwards.
- Arrow down and page down seek *forward*, arrow up and page up seek *backward*.
- Volume on mouse wheel.
- I use `z-*` (where `*` is some other key) for toggling most things, including visibility of subtitles or debanding. Also for cycling some less commonly used properties like `tscale`.
- The rest is pretty uninteresting in the general sense and just some personal preferences.

**Comment by ipatch** [comment] 2018-02-01 00:58
@FichteFoll thanks for sharing.  I saw you remapped the scroll up / down to adjust the volume 👍  

However, I didn't see a scroll left / right?  I don't use a **mouse** per se as I am on a portable 💻  so I end up using the trackpad / touchpad 99% of the time, so being able to scrub the playback using two fingers ✌🏾 to the left or to right is crucial for my situation.

Thanks again for sharing.

cheers 🍻
Chris

**Comment by FichteFoll** [comment] 2018-02-01 02:02
I use this config primarily on my desktop, which has a standard mouse and is not capable of scrolling left and right. I could test if it works for my laptop, but I think I'd end up using the arrow keys to seek anyway.

**Comment by ipatch** [comment] 2018-02-01 02:40
@FichteFoll 

I now have my trackpad / touchpad setup to the way that seems sane 👩‍⚕️ to my liking. I ended up adding the below to my **input.conf**

```
AXIS_UP add volume 2
AXIS_DOWN add volume -2

AXIS_LEFT seek 5 exact
AXIS_RIGHT seek -5 exact
```

Not exactly sure why the `-5` scrubs the playback forward in time 🤔 but moving my two fingers to the right progresses forward in playback, and moving my two fingers to the left scrubs the playback back in time.

**Comment by kevmitch** [comment] 2018-02-06 07:17
There was a request over in #5466 for

    y sub-step +1 # immediately display next subtitle
    g sub-step -1 # immediately display previous subtitle

**Comment by wm4** [comment] 2018-02-06 12:31
These were removed once. If they're readded, I think they should use more logical keys.

**Comment by Asinin3** [comment] 2018-10-15 17:32
I would really like to see mouse side buttons skipping to next/previous chapters with the default bindings. Almost all other media players I've used do this by default or skip to the next file.

```MOUSE_BTN8 add chapter 1 # skip to next chapter
MOUSE_BTN7 add chapter -1 # skip to previous chapter```

**Comment by xantoz** [comment] 2018-12-06 21:16
From #6361:

Consider using = instead of (or perhaps in addition to) + in some places to avoid having to shift (e.g. on standard US QWERTY layout) for +.

E.g.
```
ctrl++ add audio-delay 0.100           # this changes audio/video sync
ctrl+= add audio-delay 0.100           # convenience, no stretching for shift
ctrl+- add audio-delay -0.100

Alt++     add video-zoom   0.1
Alt+=     add video-zoom   0.1
Alt+-     add video-zoom  -0.1
```

**Closed** 2023-05-08 09:46 UTC
Labels: meta:rfc
