### ISSUE TITLE
--on-all-workspaces not working on MacOS Ventura 13.1

### ISSUE THREAD

**Issue by ivanbartsov** [mpv-player/mpv#11108] opened 2023-01-08 14:23 UTC
- mpv version: 0.35.0
- macOS Version: Ventura 13.1
- Source of the mpv binary or bundle: binary, installed from brew

✅ If you're not using git master or the latest release, update.

### Reproduction steps

1. Have multiple workspaces (fullscreen chrome, terminal).
2. Launch mpv to run on top on all workspaces: [ the linked video is Rick Astley :) ]
```
mpv --no-config --ontop --ontop-level=window --on-all-workspaces --ytdl-format="bestvideo[height<=?360]+bestaudio/best" "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
```
3. Swipe between workspaces and observe the absence of mpv

### Expected behavior
mpv is visible above fullscreen window "workspaces"

### Actual behavior
mpv is visible only on the leftmost "freeform" workspace

### Log file

[https://0x0.st/o7H1.log](https://0x0.st/o7H1.log)

### Sample files

Not needed, any Youtube link or video file is sufficient to reproduce.

**Comment by Akemi** [comment] 2023-01-08 14:39
> ### Expected behavior
> mpv is visible above fullscreen window "workspaces"

that's not how it is supposed to work as per Apple. a window can only be on a space but not overlay a fullscreen window. what you would like is more like the PiP feature of Safari or similar. if Apple didn't change their stance on this feature this API is private and we can't use it.

closing this since it's a 'works as intended' and duplicate of #3612.

**Closed by Akemi** 2023-01-08 14:39 UTC
Labels: os:mac
