### ISSUE TITLE
Top bar is missing running mpv in Ubuntu Wayland.

### ISSUE THREAD

**Issue by corradoventu** [mpv-player/mpv#6730] opened 2019-05-21 07:19 UTC
### mpv version and platform
corrado@corrado-p7-ee-0507:~$ apt policy mpv
mpv:
  Installed: 0.29.1-1ubuntu1
  Candidate: 0.29.1-1ubuntu1
  Version table:
 *** 0.29.1-1ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu eoan/universe amd64 Packages
        100 /var/lib/dpkg/status
corrado@corrado-p7-ee-0507:~$ inxi -SCGx
System:    Host: corrado-p7-ee-0507 Kernel: 5.0.0-13-generic x86_64 bits: 64 compiler: gcc v: 8.3.0 
           Desktop: Gnome 3.32.1 Distro: Ubuntu 19.10 (Eoan Ermine) 
CPU:       Topology: Dual Core model: Intel Core i3-7100 bits: 64 type: MT MCP arch: Kaby Lake rev: 9 
           L2 cache: 3072 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 31296 
           Speed: 800 MHz min/max: 800/3900 MHz Core speeds (MHz): 1: 800 2: 800 3: 800 4: 800 
Graphics:  Device-1: Intel HD Graphics 630 vendor: ASRock driver: i915 v: kernel bus ID: 00:02.0 
           Display: wayland server: X.Org 1.20.4 driver: i915 resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 630 (Kaby Lake GT2) v: 4.5 Mesa 19.0.2 
           direct render: Yes 
corrado@corrado-p7-ee-0507:~$ 

### Reproduction steps
click on a video icon to open it

### Expected behavior
mpv window opend WITH a topbar

### Actual behavior
mpv window opend WITHout a topbar

I opened a bug: https://bugs.launchpad.net/ubuntu/+source/mpv/+bug/1829712
and they suggested me to raise the issue here
I know I can use Xorg login or keyboard/mouse commands to move/resize the window but I find that the lack of the bar is unacceptable for reasons of uniformity 
thanks

**Comment by CounterPillow** [comment] 2019-05-21 11:06
Not an mpv bug but a GNOME issue.

Duplicate of https://github.com/mpv-player/mpv/issues/139

**Closed** 2019-05-21 11:13 UTC
Labels: duplicate

**Comment by mc4man** [comment] 2019-05-21 23:38
For 19.04/19.10 to get deco for mpv in a wayland session you'd need to use 
 --gpu-context=x11egl
The above can also provide vaapi hwdec  but only  vaapi-copy
