### ISSUE TITLE
memory leak with AV1 video with grain synthesis (allocates ~2GiB/minute)

### ISSUE THREAD

**Issue by luziferius** [mpv-player/mpv#7233] opened 2019-12-08 00:40 UTC
### mpv version and platform

Platform: Linux (Kubuntu 19.10)
Version: `0.92.1` as provided by the Ubuntu 19.10 repository

(I wasn’t able to build mpv from sources and external builds failed, so I haven’t tried 0.30 yet. Maybe tomorrow.)

### Reproduction steps

- Get an AV1 video with grain synthesis enabled. See below.
- let mpv play the file

### Expected behavior

Normal playback

### Actual behavior

mpv plays the file without visual distortions, but steadily allocates more memory at a rate of about 2GiB per minute of video playback (at SD resolution).

If you play the sample file attached below, mpv uses about 1.8 GiB RAM at the end.

### Addional analysis

AV1 videos _without_ grain synthesis do not trigger this and work perfectly fine.
So if you remove `-denoise-noise-level 50` in the command lines below, the resulting video will work.

To test if it is related to a shared library, I ran some tests on my system:

- git builds of ffmpeg and libaom-av1 are unaffected.
 - tested `ffmpeg version N-95947-gb864af033d` with libaom-av1 `1.0.0-2742-gfb4e6e5dc`
 - `aomdec` (the libaom-av1 reference decoder) is unaffected
- VLC 3.0.8 and Firefox 70 are unaffected (so libdav1d should be fine)

### Log file

[mpv_log_output.txt](https://github.com/mpv-player/mpv/files/3935707/mpv_log_output.txt)

### Sample files

Create one yourself with:
```sh
ffmpeg -y -f lavfi -i smptebars=duration=60:size=720x576:rate=25  -c:v libaom-av1 -strict experimental -pix_fmt yuv420p10le -cpu-used 4 -crf 11 -frame-parallel 0 -threads 1 -auto-alt-ref 1 -lag-in-frames 16 -enable-cdef 1 -enable-global-motion 1 -enable-intrabc 1 -denoise-noise-level 50 -pass 1 -f matroska /dev/null
ffmpeg -f lavfi -i smptebars=duration=60:size=720x576:rate=25  -c:v libaom-av1 -strict experimental -pix_fmt yuv420p10le -cpu-used 4 -crf 11 -frame-parallel 0 -threads 1 -auto-alt-ref 1 -lag-in-frames 16 -enable-cdef 1 -enable-global-motion 1 -enable-intrabc 1 -denoise-noise-level 50 -pass 2 -f matroska video.mkv
```
[video.zip](https://github.com/mpv-player/mpv/files/3935706/video.zip)
The attached `video.zip` contains a video created using the parameters above.

**Comment by wm4** [comment] 2019-12-08 00:44
What makes you think this is a mpv problem rather than in ffmpeg or one of the decoder libs?

**Comment by luziferius** [comment] 2019-12-08 01:14
I tried multiple different programs to test the installed libraries.I can't completely rule out an issue in the used decoder library. It indeed sounds like it _is_ related to a library.As far as I know, mpv uses dav1d to decode AV1. Both Firefox and VLC do the same. But the latter two can decode the given video without a problem. Therefore I concluded that the culprit is mpv. It looks like it does not properly free a buffer allocated by the decoder if and only if grain synthesis is enabled.
null

**Comment by wm4** [comment] 2019-12-08 01:35
mpv doesn't use them directly, it uses libavcodec, which uses one of the libs.
Thus closing.

**Closed by wm4** 2019-12-08 01:35 UTC

**Comment by CounterPillow** [comment] 2019-12-08 03:04
Can't reproduce with a recent git version anyway.

AFAIK grain synthesis in AV1 can somehow be done by GPU side things but I'm not sure if mpv even uses that.

**Comment by luziferius** [comment] 2019-12-08 11:27
Sorry for the noise. I ran `valgrind` on `mpv`, which I should have done before reporting…
The libaom from Ubuntu is faulty.
