### ISSUE TITLE
Changing audio output while an MPV instance exists will screw the video

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [mpv-player/mpv#4361] opened 2017-04-24 10:23 UTC
To replicate, on Windows:

1. Open a video and pause it.
2. Run the AHK script below (it's a bunch of stuff merged into one, so don't pay attention to the code), and press _Windows Key + A_. This will change the audio output - in my case, from the speakers to the TV stereo (of course, you need the computer be connected to both). 
3. Now play the video. In my case it moves at slow frames and has no sound. 

Generally it fixes itself by switching the audio channel within the video (for example, English > audio: no) back and forth a couple of times, but it makes more sense if it's not there to begin with.

#SingleInstance force
#NoTrayIcon
#MaxHotkeysPerInterval 90000000000
Ctrl  & F11::SoundSet -1, Master
Ctrl  & F12::SoundSet +1, Master
Ctrl  & F10::SoundSet, +1, , mute
LWin  &  Z::Run "C:\Windows\System32\Magnify.exe"
LWin  & F1::Run "C:\Windows\Resources\Themes\Windows.theme"
LWin  & F2::Run "C:\Program Files (x86)\LiteStep\LiteStep.lnk"
LWin  & F3::Run "C:\Program Files (x86)\RK Launcher\RKLauncher.exe"
#IfWinActive ahk_class CabinetWClass
LWin & E::
    RegRead, HiddenFiles_Status, HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced, HideFileExt
    If HiddenFiles_Status = 1
        RegWrite, REG_DWORD, HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced, HideFileExt, 0
    Else
        RegWrite, REG_DWORD, HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced, HideFileExt, 1
    Send, {F5}
    Return
#IfWinActive
LWin & A::
Run,mmsys.cpl
WinWait,Sound
IfWinNotActive,Sound WinActivate,Sound
WinWaitActive,Sound
ControlSend,SysListView321,{PgUp}  
x := 1
ControlGet, isEnabled, Enabled,,&Set Default
ControlGet, max, List, Count, SysListView321
while (isEnabled AND x <= max) {
   ControlSend,SysListView321,{Down}  
   ControlGet, isEnabled, Enabled,,&Set Default
   x := x+1
}
if (x >= max) {
   x := 1
} else {
   x := x+1
}
sleep 50
ControlSend,SysListView321,{PgUp}  
while (x > 1) {
  sleep 50
  ControlSend,SysListView321,{Down}  
  x := x-1
}
ControlGet, Current, List, Selected, SysListView321
; msgbox %Current%
ControlClick,&Set Default
ControlClick,OK
SoundPlay *48

return

OnExit, ShowCursor
return

ShowCursor:
SystemCursor("On")
ExitApp

#c::SystemCursor("Toggle")  ; Win+C hotkey to toggle the cursor on and off.

SystemCursor(OnOff=1)   ; INIT = "I","Init"; OFF = 0,"Off"; TOGGLE = -1,"T","Toggle"; ON = others
{
    static AndMask, XorMask, $, h_cursor
        ,c0,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13 ; system cursors
        , b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,b11,b12,b13   ; blank cursors
        , h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11,h12,h13   ; handles of default cursors
    if (OnOff = "Init" or OnOff = "I" or $ = "")       ; init when requested or at first call
    {
        $ = h                                          ; active default cursors
        VarSetCapacity( h_cursor,4444, 1 )
        VarSetCapacity( AndMask, 32*4, 0xFF )
        VarSetCapacity( XorMask, 32*4, 0 )
        system_cursors = 32512,32513,32514,32515,32516,32642,32643,32644,32645,32646,32648,32649,32650
        StringSplit c, system_cursors, `,
        Loop %c0%
        {
            h_cursor   := DllCall( "LoadCursor", "uint",0, "uint",c%A_Index% )
            h%A_Index% := DllCall( "CopyImage",  "uint",h_cursor, "uint",2, "int",0, "int",0, "uint",0 )
            b%A_Index% := DllCall("CreateCursor","uint",0, "int",0, "int",0
                , "int",32, "int",32, "uint",&AndMask, "uint",&XorMask )
        }
    }
    if (OnOff = 0 or OnOff = "Off" or $ = "h" and (OnOff < 0 or OnOff = "Toggle" or OnOff = "T"))
        $ = b  ; use blank cursors
    else
        $ = h  ; use the saved cursors

    Loop %c0%
    {
        h_cursor := DllCall( "CopyImage", "uint",%$%%A_Index%, "uint",2, "int",0, "int",0, "uint",0 )
        DllCall( "SetSystemCursor", "uint",h_cursor, "uint",c%A_Index% )
    }
}

!+.::GoSub,CheckActiveWindow

CheckActiveWindow:
  ID := WinExist("A")
  WinGetClass,Class, ahk_id %ID%
  WClasses := "CabinetWClass ExploreWClass"
  IfInString, WClasses, %Class%
    GoSub, Toggle_HiddenFiles_Display
Return

Toggle_HiddenFiles_Display:
  RootKey = HKEY_CURRENT_USER
  SubKey  = Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced

  RegRead, HiddenFiles_Status, % RootKey, % SubKey, Hidden

  if HiddenFiles_Status = 2
      RegWrite, REG_DWORD, % RootKey, % SubKey, Hidden, 1 
  else 
      RegWrite, REG_DWORD, % RootKey, % SubKey, Hidden, 2
  PostMessage, 0x111, 41504,,, ahk_id %ID%
Return

**Comment by bitingsock** [comment] 2017-04-27 19:28
Does this happen for you if you change it manually (not with the ahk script)?

If all you need is to change mpv's audio device, try this scipt:
https://gist.github.com/bitingsock/ad58ee5da560ecb922fa4a867ac0ecfd

**Comment by firewater2** [comment] 2017-04-28 01:08
You know, I actually cannot tell you anymore because it hasn't happened for a while now, at least not with the video acceleration. What happens now is the audio goes mute, but it's fixed by just changing the audio track once. This happens on both AHK and normal.

I do need overall sound, actually', but thanks for the script. I will return once this happens with acceleration included so I can better recall what triggers the response.

**Comment by kevmitch** [comment] 2017-04-29 11:11
What would really help is a log.

**Comment by firewater2** [comment] 2017-04-29 22:12
How would I get that? On Windows.

**Comment by Jj0YzL5nvJ** [comment] 2017-04-30 04:56
> How would I get that? On Windows.
Launch mpv with `--log-file` parameter. Example:
`mpv --log-file=D:\log1.txt F:\asdf\video_file1.mkv`

I detected this "problem" a long time ago, but I saw it more as "it's just like Windows works" =P
It's easier to see the problem when you have headphones connected to the front and speakers on the back connection. When you disconnect the headphones, BOOM!, mpv crash... well, that happened when I detected it, I don't know now. I think this also happens when you only have the speakers and you disconnect it while mpv is working.
I don't have any Windows machine at the moment... I can try to replay it in a VM.

**Comment by Jj0YzL5nvJ** [comment] 2017-04-30 21:30
Well, I did more testing by trying the script offered by @bitingsock ...and actually everything is working properly, even without the script.
 When I "disconnect" the audio output and "reconnect" it, I can call the audio by pressing '#' on mpv.
http://sprunge.us/EDJS

 By the way, the script replaces "Shift + a" which by default changes the video-aspect. With "Ctrl + a" it should be more than enough.

**Comment by kevmitch** [comment] 2017-05-02 05:02
@Jj0YzL5nvJ it looks like you have no other candidate devices to fall back on when you disable "(Altavoces (Dispositivo de High Definition Audio))". mpv therefore turns off audio output altogether. The problem is that it's the WASAPI audio code that usually does the job of detecting audio device changes. Therefore, there's nothing listening when you reenable. 

We have developed [this script](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/ao-null-reload.lua) to work around this edge case.

@firewater2 does the same thing happen when you just manually change the output without the script? A log similar to what @Jj0YzL5nvJ provided would still be helpful.

**Comment by Jj0YzL5nvJ** [comment] 2017-05-02 07:49
Beautiful, the new script file works perfect in my case. I can make more testing on a real machine tomorrow.

**Comment by Jj0YzL5nvJ** [comment] 2017-05-03 07:41
I retract myself, it is nothing beautiful. Is a jealous and manipulative "girlfriend". The script `ao-null-reload.lua` once it is active, not let fall back and don't let you use others scripts until it encounter the same output/device again. And I see very few scenarios in which this could be useful...

 The @bitingsock 's  script do the thing.

http://sprunge.us/FdcI
http://sprunge.us/DHLI

 With this, I don't think that more logs will be necessary.

**Comment by kevmitch** [comment] 2017-05-04 04:25
I still need to see logs from @firewater2.

@Jj0YzL5nvJ your issue is distinct from the one originally reported. I'm pretty sure that your problem now lies entirely in the fact that cycle-adevice.lua is explicitly setting the `audio-device` property. So yes, it will only ever load the device that it sets. The solution would be for that script to to somehow unset the property when the device in question disappears.

**Comment by firewater2** [comment] 2017-05-06 00:21
Yeah it hasn't happened again, I promise to come back when it does.

**Comment by Dudemanguy** [comment] 2022-01-18 18:18
Seems like the problem is fixed?

**Closed by Dudemanguy** 2022-01-18 18:18 UTC
Labels: os:win, ao:wasapi
