### ISSUE TITLE
[feature request] Make 'mouse' input command generate clicks when --input-cursor=no

### ISSUE THREAD

**Issue by jdoe0** [mpv-player/mpv#2750] opened 2016-01-23 17:14 UTC
foo.conf:
```
MOUSE_BTN0 show-text "test"
c mouse 100 100 0 single
```

With --input-cursor=no:
```
$ mpv --force-window --idle --msg-level=input=trace --input-cursor=no --input-conf=foo.conf
⋮ (press 'c')
[input] release all
[input] key code=0x63 'c' down
[input] key 'c' -> 'mouse 100 100 0 single' in 'default'
[input] mouse move 100/100
[input] release all
```

With --input-cursor=yes:
```
$ mpv --force-window --idle --msg-level=input=trace --input-cursor=yes --input-conf=foo.conf
⋮ (press 'c')
[input] release all
[input] No key binding found for key 'MOUSE_ENTER'.
[input] key code=0x63 'c' down
[input] key 'c' -> 'mouse 100 100 0 single' in 'default'
[input] mouse move 100/100
[input] No key binding found for key 'MOUSE_MOVE'.
[input] key code=0xe000a0 'MOUSE_BTN0'
[input] key 'MOUSE_BTN0' -> 'show-text "test"' in 'default'
[input] release all
```

**Comment by wm4** [comment] 2016-01-23 17:15
That's by design.

**Comment by jdoe0** [comment] 2016-01-23 18:34
Please consider this a feature request then. I'm using `--input-cursor=no` to allow parent window to receive mouse events when embedding mpv. There's no other way to send mouse events to mpv while `--input-cursor=no` afaik.

**Comment by Frechdachs** [comment] 2016-02-04 19:11
I have to second this feature request now after trying to use window embedding on Linux.

It's currently impossibe to get the parent window to receive mouse events while still being able to use the OSC, since `--input-cursor=no` makes a command like `mouse 100 150` void.

A second problem is that while using `--input-cursor=yes` the application window that the window where mpv is embedded in belongs to will not get activated after a left click on the mpv part of the program. Of course this is easily fixed by using `--input-cursor=no`, but I would like to keep using the OSC.

On Windows everything works fine though, mpv does never get any mouse events, unless they are explicitly sent as a command.

**Closed** 2016-02-04 22:02 UTC
