### ISSUE TITLE
Startup stuck at [osd/libass] Setting up fonts... for 60 seconds

### ISSUE THREAD

**Issue by hyperknot** [mpv-player/mpv#2071] opened 2015-06-24 22:13 UTC
The startup is stuck **multiple times** on this very line:

```
[osd/libass] Setting up fonts...
```

Eventually it finishes in about 60 seconds. It does build up some kind of cache, because if I quit and start again it works instantly. But somehow this bug keeps happening again and again. It's like if the font cache directory is being cleaned or rebuilt every day or something. 

I have a top-of-the-range Retina MBP 15 with PCI-E SSD and i7 processor, waiting 60 seconds for an app startup should really not happen. I've tried both official latest release and ChrisK's latest build.

OS X 10.9.5.

**Comment by ChrisK2** [comment] 2015-06-24 22:40
Copy the ``fonts.conf`` in the .app-bundle (in ``Contents/Resources/``) to ``~/.mpv/``. If it still regularly caches and takes forever, something is messed up in your system.

**Comment by hyperknot** [comment] 2015-06-24 22:50
OK, I did the following:
1. Deleted .cache, no fonts.conf in .mpv
2. Start mpv
3. Now it starts very quickly, and it doesn't generate .cache at all!
It writes the following debug lines 3x times:
```
[global] search dirs: /Users/user/.mpv /Users/user/bin /usr/local/etc/mpv
[global] config path: 'fonts' -> '(NULL)'
[global] search dirs: /Users/user/.mpv /Users/user/bin /usr/local/etc/mpv
[global] config path: 'subfont.ttf' -> '(NULL)'
[global] search dirs: /Users/user/.mpv /Users/user/bin /usr/local/etc/mpv
[global] config path: 'fonts.conf' -> '(NULL)'
[osd/libass] Setting up fonts...
[osd/libass] Done.
```

4. Now I quit mpv. Copy fonts.conf into .mpv. It recognises the fonts.conf present and it generates a .cache/fontconfig folder, kind of quickly, 5 sec max.

I'll wait to see if the 60 second happens again with fonts.conf present. My mpv.conf is pretty much empty.

**Comment by wm4** [comment] 2015-06-25 07:53
This is a problem with libass using fontconfig. As soon as the native osx and win32 backends are merged, it won't have this problem anymore. Will probably take a few weeks.

**Closed by wm4** 2015-06-25 07:53 UTC
Labels: not our bug

**Comment by raawaa** [comment] 2016-01-09 13:40
Got the same problem as an Archlinux user. But finally, I found the cause is:
I **FORGOT TO SET THE CACHEDIR** in Fontconfig's configuration file.

After adding these two lines in `~/.confg/fontconfig/fonts.conf`, problem solved.

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<!-- $XDG_CONFIG_HOME/fontconfig/fonts.conf for per-user font configuration -->

<fontconfig>
...
  <cachedir>/var/cache/fontconfig</cachedir>
  <cachedir prefix="xdg">fontconfig</cachedir>
...
</fontconfig>
```

**Comment by daed-alus** [comment] 2019-02-09 12:11
i'm facing the same with basic subrip (srt) subtitles but on windows

```
[   0.766][v][sub/ass] Setting up fonts...
[  16.008][v][sub/ass] Using font provider directwrite
[  16.008][v][sub/ass] Done.
[  16.008][v][cplayer] Starting playback...
```

win 10 1809 x64
**mpv 0.29.1** and **mpv 0.29.0-118-gf2e7e81bda**
