### ISSUE TITLE
Windows taskbar progress incorrect at end of file

### ISSUE THREAD

**Issue by Smithy3** [mpv-player/mpv#5932] opened 2018-06-16 19:21 UTC
### mpv version and platform
Latest shinchiro build (mpv-x86_64-20180610-git-4d2b865.7z)
Windows 10

### Reproduction steps
Play a video to the end or skip to the end and look at the progress in the taskbar.
This is not a problem with the OSC ~~video progress, they both work as intended~~, it is just how the progress is displayed in the taskbar.

### Expected behavior
When end of file is reached, the taskbar progress is full to the end.
![mpchc-mitchell](https://user-images.githubusercontent.com/39540124/41501726-b057d53e-71a1-11e8-8601-27db4587a61a.png)

### Actual behavior
There is a slither of the progress bar not filled in, despite playback finishing.
![mpv-mitchell](https://user-images.githubusercontent.com/39540124/41501729-bfa26d1a-71a1-11e8-853e-95b56d1df5b6.png)

### Sample files
This happens with all video files, regardless of length.

**Comment by dnmTX** [comment] 2018-06-16 23:16
No such a problems here.Using the same build and OS.Looks like it's something on your end. 🤔

![osc](https://user-images.githubusercontent.com/34774426/41503136-584c4948-7191-11e8-9582-8945012e0e0d.PNG)

**Comment by Smithy3** [comment] 2018-06-17 00:17
I don't know what you're trying to convey with that image.
The images I posted show the problem is with the taskbar progress and not the OSC.
I've edited the issue to make this clearer.

**Comment by dnmTX** [comment] 2018-06-17 00:44
My image shows that there is **NO "slither of the progress bar not filled in, despite playback finishing"** and **"the taskbar progress is full to the end"**
Is that more conveying for ya?

**Comment by Smithy3** [comment] 2018-06-17 00:50
Are you blind?
The images are very clearly referring to the **Windows taskbar progress bar**.
Actually bother to read the issue before sounding like a snarky asshole.
I don't know how you want me to spell it out even more for you.

**Comment by dnmTX** [comment] 2018-06-17 00:58
Relax dude,sure i missed to read that part (Windows taskbar) after you edited.I actually got that feature disabled on my side and won't even bother reproducing it thanks to your attitude.Good luck(i don't mean that).

**Comment by Hrxn** [comment] 2018-06-17 01:00
If you play the same file from your original post in `CMD.exe` (or similar) to the end, what does the command line status info say in terms of file progress? For example, where does it stop, time and/or percentage wise?

**Comment by Keith94** [comment] 2018-06-17 01:11
I can confirm. I use `--keep-open`, and when playback ends, the command line status reads:
`(Paused) AV: 02:00:07 / 02:00:07 (99%) A-V:  0.000`

**Comment by Hrxn** [comment] 2018-06-17 01:15
Hmm.. 🤔 
So the progress displayed in the taskbar is 'technically' correct? 😄 
I can reproduce this as well here btw.

**Comment by Smithy3** [comment] 2018-06-17 01:17
@dnmTX 
The images were there before I edited in any additional information.
If you had any semblance of reading comprehension you would have understood that the first time.
Grow up a little will you?

@Hrxn @Keith94
This is likely the source of the problem. I've tested it with a few files and it only goes to 99% percent, skipping out a second, so it will never be complete, despite playback being "finished", and because the label view in Windows stretches the window button out quite wide, that slither will never be filled in.
I thought it might have something to do with `seekbarkeyframes` but testing reveals this is not the case.
It seems like its an issue with how mpv handles progress, and this taskbar issue is just a knock-on effect of it.

**Comment by Keith94** [comment] 2018-06-17 01:32
Possibly, but it seems like it's another side effect of the player's "paused state" at the end of playback. Still, you're welcome to make an issue for it.

**Comment by ValZapod** [comment] 2022-03-23 18:55
> So the progress displayed in the taskbar is 'technically' correct? 😄

Of course it is correct! It autocloses when you reach the end for images at least. Also video can have duration in container that allows for it to play for longer past the end (not supported in mpf in many cases).

**Comment by kasper93** [comment] 2024-06-03 08:43
At the end of the playback mpv returns last frame start time as current position. Previously the percentage position were not rounded, so it never reached 100%. This has actually been fixed by https://github.com/mpv-player/mpv/commit/d061f28397937f0eae8fc7ba3b13913bbf29a9b7, unless frame duration is longer than 0.5% of total duration of the media file, which is quite unlikely.

**Closed by kasper93** 2024-06-03 08:43 UTC
Labels: os:win
