### ISSUE TITLE
MPV 0.28 is almost impossible to play a live broadcast of youtube

### ISSUE THREAD

**Issue by EzeKees** [mpv-player/mpv#5335] opened 2018-01-01 18:54 UTC
### mpv version and platform

MPV 0.28 by lachs0r 
Windows 8.1

### Expected behavior
using libmpv I play a video from my PC and then I play a live YouTube broadcast. I should reproduce them without problems as in version 0.27.

### Actual behavior
The live broadcast does not start playing or it does it very slowly.

### Log file

[log.log](https://github.com/mpv-player/mpv/files/1596311/log.log)

### Sample files
https://www.youtube.com/watch?v=9h6Vz6ylIdE&feature=youtu.be

https://www.youtube.com/watch?v=NRJARz9L-CI
PD: I have 3 mb of internet, it is quite slow, but I do not understand why in the previous version of MPV I played it much faster.

Thank you in advance and congratulations for this huge multimedia player !!!
Greetings from Argentina!

**Comment by lachs0r** [comment] 2018-01-01 19:15
Duplicate of #5286.

**Closed by lachs0r** 2018-01-01 19:15 UTC

**Comment by EzeKees** [comment] 2018-01-01 21:08
Hello, thank you very much for the answer, but where can I download the compiled dll with the built-in solution that you put me above?
Since I use the compiled dll directly, I do not modify the code myself, since I have no idea of C language
