### ISSUE TITLE
TOOLS/autoload.lua: No longer loads videos in playlist when opening an image file

### ISSUE THREAD

**Issue by Jules-A** [mpv-player/mpv#14287] opened 2024-06-03 16:39 UTC
### mpv Information

```bash
[cplayer] Command line options: '--no-config' '-V' '-v' '--list-options'
[cplayer] mpv v0.38.0-388-g9fa81018 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Jun  2 2024 21:08:01
[cplayer] libplacebo version: v7.349.0 (v7.349.0-rc1-dirty)
[cplayer] FFmpeg version: N-115544-g6106177ad
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       59.21.100
[cplayer]    libavcodec      61.6.100
[cplayer]    libavformat     61.3.104
[cplayer]    libswscale      8.2.100
[cplayer]    libavfilter     10.2.102
[cplayer]    libswresample   5.2.100
```
Autoload version tested e95af5b
### Important Information

- Platform version: Windows 10 22H2 b19045.4474
- GPU model, driver and version: 6700XT, 24.5.1
- Source: zhongfly
- Introduced in version: Not sure, I was using a version that worked with directory_mode=ignore that's likely around 3-6 months old

### Reproduction Steps

Grab autoload.lua from master,
Set 
```   
 disabled = false,
    images = false,
    videos = true,
    audio = false,
    additional_image_exts = "",
    additional_video_exts = "",
    additional_audio_exts = "",
    ignore_hidden = true,
    same_type = false,
    directory_mode = "ignore",
    ignore_patterns = ""
````
or directory_mode="auto" but not sure what the expected behavior of auto is supposed to be.
Open an image such as an avif with video files in the same directory.

### Expected Behavior

Video files added to playlist

### Actual Behavior

No files are added to playlist

### Log File

[mpv.log](https://github.com/user-attachments/files/15536901/mpv.log)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by guidocella** [comment] 2024-06-03 16:44
Fixed by e95af5b607

**Comment by Jules-A** [comment] 2024-06-03 16:45
> Fixed by [e95af5b](https://github.com/mpv-player/mpv/commit/e95af5b6076c593dd53c42381611b4bceb9bfa10)

It's not, I just tried that version.

**Comment by kasper93** [comment] 2024-06-03 17:56
What is not working then?

**Comment by Jules-A** [comment] 2024-06-03 18:08
> What is not working then?

If I open an image file but have video set to add to playlist, I expect it to build a playlist of the videos in the current directory so I can navigate to them but ignore any other image files there.

**Comment by kasper93** [comment] 2024-06-03 18:30
Does this works for you?

https://raw.githubusercontent.com/kasper93/mpv/d8ef5f513f43071b2cf8e090c8212a9390640026/TOOLS/lua/autoload.lua

**Comment by Jules-A** [comment] 2024-06-03 19:34
> Does this works for you?

Unfortunately it didn't change anything.

**Comment by kasper93** [comment] 2024-06-03 23:25
I've tested and everything seems to work as expected. 

> The same_type = false with directory auto gathering every single file including exes seems like a bug but it's a separate issue

Cannot reproduce, instructions unclear.

> If I open an image file but have video set to add to playlist, I expect it to build a playlist of the videos in the current directory so I can navigate to them but ignore any other image files there.

Sorry, I don't understand. You are opening video or image? Could you explain in clear steps what to do and what would be expected result?

Either way, I think the original issue has already been fixed and now it is other issues?

**Comment by Jules-A** [comment] 2024-06-04 00:09
> Cannot reproduce, instructions unclear.

Separate issue but it looks like I was mistaken, the autoload you sent me fixes that.

> Sorry, I don't understand. You are opening video or image? Could you explain in clear steps what to do and what would be expected result?
> Either way, I think the original issue has already been fixed and now it is other issues?

The original issue is not solved.
Set options to the ones used in my OP,
Open an image in MPV in a directory that also has videos

It should build a playlist of the videos in that directory allowing to skip to next file but instead it doesn't and you can't navigate to the next file.

**Comment by kasper93** [comment] 2024-06-04 10:35
It is just confusing, because you report an issue as if it were regression for a future that is essentially feature request.

**Closed** 2024-06-04 13:39 UTC

**Comment by Jules-A** [comment] 2024-06-04 16:57
> It is just confusing, because you report an issue, as if it were regression, for a future that is essentially feature request.

It did work at one point unless I modified the code and forgot...?

**Comment by c02y** [comment] 2024-06-20 03:37
I suddenly noticed that autoload.lua doesn't create any playlist anymore when I open a video, even the file is in a directory containing multiple similar files such as TV series.
