### ISSUE TITLE
rounded corners on subtitle background 

### ISSUE THREAD

**Issue by tXJtqlb3bbeKD1yW8SV7** [mpv-player/mpv#11585] opened 2023-04-16 03:12 UTC
Is there a way to accomplish this? 

![brave_0xbkl9pR1q](https://user-images.githubusercontent.com/88219689/232264253-9083722b-a7ee-48ae-b73e-2eab53a718a7.png)

**Comment by Akemi** [comment] 2024-06-01 11:27
duplicate of #11853

**Closed by Akemi** 2024-06-01 11:27 UTC
Labels: meta:feature-request
