### ISSUE TITLE
macOS: fullscreen when opening from tmux broken

### ISSUE THREAD

**Issue by katosh** [mpv-player/mpv#4234] opened 2017-03-13 22:49 UTC
### mpv version and platform

```
~$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12.3
BuildVersion:   16D32

~$ mpv --version
mpv git-636675ece (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Mon Mar 13 23:08:07 CET 2017
ffmpeg library versions:
   libavutil       55.34.101
   libavcodec      57.64.101
   libavformat     57.56.101
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.4
```
I also tried the version build by homebrew:
```
~$ /usr/local/Cellar/mpv/0.24.0/bin/mpv --version
mpv 0.24.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sun Feb 12 01:42:57 GMT 2017
...
```

### Reproduction steps

Press `f` or use option `--fs`.
I also tried running `mpv --fs --no-config --no-osc --no-load-scripts test.mkv`.

### Expected behavior

Persistently display video in full screen mode.

### Actual behavior

Short flash of video in full screen (menu bar not hidden) and return to window mode with a system bell sound.

### Log file

[log](http://sprunge.us/XfBe)  I pressed `f` several times after reverting to window mode.

### Sample files

Any video.

**Comment by Akemi** [comment] 2017-03-13 22:57
are you saying the normal fullscreen is not working for you at all?

**Comment by katosh** [comment] 2017-03-13 22:58
Not any more. It use to work in an older version.

**Comment by Akemi** [comment] 2017-03-13 23:01
it works here and for many others. how are you opening mpv? can you make a screen recording? are you using SIMBL or any plugins/programs that could interfere with that?

**Comment by katosh** [comment] 2017-03-13 23:08
I am running it from [tmux](https://github.com/tmux/tmux) and just now tried doing outside of this terminal multiplexer. And it works! Thanks for the hint.
It would also be nice to be able to run it from my multiplexer as it is my normal working environment.

**Comment by Akemi** [comment] 2017-03-13 23:13
yeah, i can reproduce that.

**Comment by katosh** [comment] 2017-03-13 23:15
I guess we can make it a feature request then :)

**Comment by Akemi** [comment] 2017-03-13 23:20
a workaround from https://github.com/Microsoft/vscode/issues/12587. so far i have no clue what the cause of this is exactly.

```
brew install reattach-to-user-namespace
# add the following to ~/.tmux.conf:
# set-option -g default-command "reattach-to-user-namespace -l bash"
```

**Comment by katosh** [comment] 2017-03-13 23:30
Thank you, that works for now. Ideally of course, tmux would always run the current login shell (e.g. now I am not using bash).

**Comment by Akemi** [comment] 2017-03-13 23:37
maybe it could use $SHELL env variable? i have a feeling this can't be fixed within mpv from the explanations on [tmux-MacOSX-pasteboard](https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard).

**Comment by katosh** [comment] 2017-03-13 23:51
Yes `$SHELL` can be used even in the config file. But I will just use an alias for mpv instead `alias mpv='reattach-to-user-namespace mpv'` which also works for me.

**Closed** 2017-03-13 23:56 UTC
Labels: not our bug, osx

**Comment by avih** [comment] 2017-09-06 15:37
FWIW, I found an interesting workaround for this issue, without using `reattach-to-user-namespace`.

If one `ssh localhost` (and just work within an ssh session within tumx), then this issue is fixed and fullscreen works fine.

So if ssh is enabled, and if you can ssh localhost without password (after some setup), then it should be possible to configure tmux to ssh localhost instead of a plain shell for new pane. I haven't tried to automate it like so, but I did verify that via ssh (within or outside of tmux, or even from another host) the issue doesn't exist.
