### ISSUE TITLE
Lua Scripts fail due to incorrectly processed path.

### ISSUE THREAD

**Issue by tonkou-roi** [mpv-player/mpv#6424] opened 2019-01-05 08:46 UTC
### mpv version and platform
mpv 0.29.0-107-gd6d6da4711 from shinchiro mpv-x86_64-20181230-git-d6d6da4.7z
Windows 8.1

### Reproduction steps
Open any video.

### Expected behavior
Scripts located within %appdata%\mpv\scripts\ should load, video plays.

### Actual behavior
Any lua script cannot be found.
However, javascript works fine.

![mpv break](https://user-images.githubusercontent.com/35481312/50722213-1241e200-110f-11e9-9070-279e09b51dbd.png)

(I have removed profile name from screenshot, the error does not provide a blank space in place of the user directory.)

### Log file
[output.log](https://github.com/mpv-player/mpv/files/2729340/output.log)

**Comment by shinchiro** [comment] 2019-01-07 12:39
similar issue with #4903

**Comment by zc62** [comment] 2019-02-21 21:29
The best solution might be:

- Put `mpv.exe` in a directory that contains only English characters. `C:\mpv\` would just work fine.
- Move all the files and folders in `%APPDATA%\mpv\` to `C:\mpv\portable_config\`.

**Comment by zQueal** [comment] 2019-02-23 05:35
Experiencing this issue as well.

    C:\Users\zqueal>echo $MPV_HOME
    C:\Users\zqueal\.config\mpv

Scripts are in `$MPV_HOME/scripts`. They absolutely will not load regardless of what is done.

I also have `$MPV_HOME/mpv.conf` and `$MPV_HOME/script-opts/osc.conf` which both seem to work just fine without issue. I've confirmed them both working because I have a non-standard OSC as well as a custom screenshot folder, with a custom non-standard screenshot format which works just fine.

Any guidance, here? This is crazy.

**Comment by zc62** [comment] 2019-02-23 06:43
@zQueal Can't tell for sure if `zqueal` contains any non-ASCII characters or not. If it is English, then shouldn't be the case. If it is not, see https://github.com/mpv-player/mpv/issues/4903#issuecomment-466171122.

**Comment by Dudemanguy** [comment] 2021-07-21 17:28
In theory, this should be fixed by c258478.

**Closed by Dudemanguy** 2021-07-21 17:28 UTC
Labels: scripting:lua
