### ISSUE TITLE
Fullscreen on OSX 10.10.5 blocks cmd-tabbing

### ISSUE THREAD

**Issue by mlindner** [mpv-player/mpv#4180] opened 2017-02-23 08:14 UTC
### mpv version and platform
mpv git-992e582

### Reproduction steps

Go into fullscreen on any video on 10.10.5

### Expected behavior

You should be able to cmd-tab when the video is in full screen.

### Actual behavior

You cannot cmd-tab in full screen.

### Log file

Log file is of starting a video (with fs=on) and then going out of full screen, going back into full screen, and back out of full screen (and then back in I think) then exiting.

http://sprunge.us/FCWh

### Sample files

Any file will work.

**Comment by wm4** [comment] 2017-02-23 08:45
Duplicate of #4177.

**Closed by wm4** 2017-02-23 08:45 UTC
Labels: invalid

**Comment by mlindner** [comment] 2017-02-23 08:56
Don't close this bug. The other bug was closed because it had other issues that were duplicates. This one is not a duplicate.

**Comment by Argon-** [comment] 2017-02-23 10:48
mpv's fullscreen does not block alt+tab. Works here.
