### ISSUE TITLE
after hitting `f` to go fullscreen, mouse movement fails to restore visibility of autohidden mouse cursor

### ISSUE THREAD

**Issue by fjarlq** [mpv-player/mpv#6886] opened 2019-08-23 22:07 UTC
### mpv version and platform

mpv 0.29.1 installed on macOS 10.14.6 via Homebrew

### Reproduction steps

1. Run `mpv any-video.mp4`
2. Wait for the mouse cursor to become autohidden.
3. Press the `f` key to go fullscreen.
4. Move the mouse (in my case, via trackpad).

### Expected behavior

Mouse movement should cause the hidden mouse cursor to become visible.

### Actual behavior

The hidden mouse cursor remains invisible. This problem persists even after quitting mpv.

Workaround: continuously moving the mouse pointer while hitting `f` prevents the problem.

It seems like this bug only happens when going fullscreen while the mouse cursor is hidden. That could explain why the problem never seems to happen when using the mouse to go fullscreen (e.g. via doubleclicking the window or clicking the fullscreen OSD button).

### Log file

https://gist.github.com/fjarlq/0fb9415d22848dde24051e7a8c992d5b

**Comment by fjarlq** [comment] 2019-08-23 23:39
This problem still happens when I run `mpv --no-config any-video.mp4`
(And it's not mp4-specific, either.)

**Comment by Akemi** [comment] 2019-08-24 09:10
i can't reproduce it like this (neither on 0.29.1 nor master). you need to be more specific what you are doing exactly and what kind of setup you have (secondary monitor, resolution scaling, etc).

**Comment by fjarlq** [comment] 2019-09-02 06:43
@Akemi Okay, darn, thanks for trying.

- I'm using a MacBook Pro (Retina, 15-inch, Mid 2014) on macOS 10.14.6
- no secondary monitor, I'm just using the builtin display
- no resolution scaling, my resolution is "Default for display"
- I've made sure my Homebrew is up-to-date, and reinstalled mpv 0.29.1_3
- I've doublechecked the reproduction steps above, and I'm still seeing the bug as described

I can't seem to reproduce this on my older Mac Pro running 10.11.6.

**Comment by Akemi** [comment] 2019-09-02 18:11
the MBP mid 2014 has a native resolution of 2880x1800. your log indicates that the fullscreen window has a resolution of 3840x2160 (which is already a bit weird since that's not the correct aspect ratio). there is most likely scaling involved. "Default for display" doesn't mean your screen uses the native resolution or scaling of 1 (eg 1 px = 1px). usually/back in the days retina display used a 2 times scaling (1 pixel = 4 pixel), but that can be rather arbitrary now. for example 2 times scaling makes the UI on a 2880x1800 resolution display appear like 1440x900 resolution display.

in your case the UI will appear like on 1920x1080 resolution display, eg a bit smaller.

something isn't right in your log. please try mpv master instead of the outdated version from homebrew. a log with the newer version would also be appreciated.

i doubt it matters but i tried on 10.14.4 not 10.14.6.

**Comment by fjarlq** [comment] 2019-09-02 21:48
Huh, I can't explain the 3840x2160 window size. I wonder how that window size is being selected. This laptop happens to be my highest resolution display... I don't have anything 3840x2160.

Yes, "Default for display" on my 2014 MBP means a pixel doubled configuration in which I effectively have a 1440x900 display, with four physical pixels driving each apparent pixel. I've doublechecked that my display is running in this effective 1440x900 resolution.

Using the mpv project's mpv-build script, I've built what I believe is mpv master, and verified that the problem still exists. Here's the logfile:

https://gist.github.com/fjarlq/6ce137178588b7ab6237c0006cb72173

**Comment by Akemi** [comment] 2019-09-02 22:26
sry, looked at the wrong place. too much noise. also yeah that is the most recent version. the actual right place in the new log:
```
[   5.315][v][libmpv_render] Window size: 2880x1800
[   5.315][v][libmpv_render] Video source: 1920x1080 (1:1)
[   5.315][v][libmpv_render] Video display: (0, 0) 1920x1080 -> (0, 90) 2880x1620
```

when you start mpv the actual video window is a lot bigger than the actual desktop right? eg when you toggle into fullscreen it reduces the size of the window to fit the screen?

could you please test with `--hidpi-window-scale=no` (the window should stay smaller than the desktop) and see if it still happens?

**Comment by fjarlq** [comment] 2019-09-03 00:35
Yeah, my 1920x1080 test video is bigger than my 1440x900 display, and by default mpv is playing it in a 1920x1080 window, so when I go fullscreen it reduces the window to fit.

With `--hidpi-window-scale=no` the window starts out smaller than the desktop, but I can still reproduce the problem.

I can also reproduce the problem with a 1280x720 video, with and without `--hidpi-window-scale=no`.

**Comment by rubenfonseca** [comment] 2020-01-03 10:29
This is still a problem for me even on the latest 0.31.0 version.

**Comment by fjarlq** [comment] 2020-01-04 21:46
@rubenfonseca Can you be specific about your setup, what hardware you're using, etc?

**Comment by rubenfonseca** [comment] 2020-01-05 15:22
Sure it's a 2017 rMBP 15'' running Catalina 10.15.2. It happens both on internal screen and when using an external screen. I understand that the cursor disappears when the window goes full screen, but then it's very hard for the cursor to come back when I move the mouse again.

**Comment by ccmoore12** [comment] 2020-01-27 19:44
I've been experiencing this issue for as long as I can remember. I'm currently running macOS Mojave 10.14.6 am using mpv 0.29.1 (I've also tested that it happens on 0.31.0 as well). The issue also occurred on all previous Mojave versions that I've used and all previous mpv versions that I've used. Sorry I can't be more specific on those.

Another way to recreate the behavior is to do a three-finger swipe (or use shortcut keys—it doesn't seem to matter how you activate it) to another "space/desktop" while mpv is active and the cursor is currently being hidden. It doesn't matter if mpv is currently fullscreen or in windowed mode.

Two ways that I've found to unhide the cursor are to do a three-finger swipe up to activate "Mission Control" or to blindly navigate my cursor to the top of the screen and click on the top bar (I have a macro to do this quickly as a temporary fix).

I can also confirm that the issue can be avoided by continuously moving the mouse around so that the cursor is visible during the transition to and from fullscreen. The same method can be applied while moving between spaces.

The issue occurs on my MacBookPro15,3 native display as well as on my external monitor(s)—an LG 27UK850-W 27" and I also tested on my ASUS VG279Q 27" that I no longer use. Resolution settings don't seem to make a difference.

[log.txt](https://github.com/mpv-player/mpv/files/4118996/log.txt)

**Comment by Akemi** [comment] 2020-01-28 13:40
i am still unable to reproduce this with `--no-config`. so i made a debug build that outputs some relevant data to the terminal. it would be nice if someone who can reproduce this problem can run the following, reproduce the problem, paste me the terminal output and tell me where the problem happened (in the output).
```
/PATH/TO/mpv.app/Contents/MacOS/mpv test-file.mkv --no-config
```

output should look something like this:
```
windowDidBecomeKey08:03 (0%) A-V: -0.000
updateCusorVisibility cursorVisibilityWanted: false
setCursorVisiblility visibility: true canHideCursor: false cursorHidden: false
windowDidResignKey08:03 (0%) A-V:  0.000
setCursorVisiblility visibility: true canHideCursor: false cursorHidden: false
setCursorVisiblility visibility: true canHideCursor: false cursorHidden: false
setCursorVisiblility visibility: true canHideCursor: false cursorHidden: false
windowDidBecomeKey08:03 (0%) A-V:  0.000
updateCusorVisibility cursorVisibilityWanted: false
setCursorVisiblility visibility: false canHideCursor: true cursorHidden: false
```

https://0x0.st/isop.zip

**Comment by ccmoore12** [comment] 2020-01-30 23:51
Hi, sorry if this isn't cut down enough, but here's the terminal output while I'm replicating the issue.

I opened mpv, waited for the cursor to hide, changed spaces with a three finger swipe without moving the cursor (the cursor is now hidden globally), and then changed spaces back to the windowed mpv to exit. The continued to be hidden after exiting mpv until I did the open Mission Control trick to unhide it.

```
setCursorVisiblility visibility: true canHideCursor: false cursorHidden: false
AO: [coreaudio] 48000Hz stereo 2ch floatp
VO: [libmpv] 1920x1080 yuv420p10
windowDidBecomeKey23:35 (0%) A-V: -0.000
updateCusorVisibility cursorVisibilityWanted: false
setCursorVisiblility visibility: false canHideCursor: true cursorHidden: false
setCursorVisiblility hide
setCursorVisiblility visibility: true canHideCursor: true cursorHidden: true
setCursorVisiblility unhide
setCursorVisiblility visibility: false canHideCursor: true cursorHidden: false
setCursorVisiblility hide
windowDidResignKey23:35 (0%) A-V:  0.000
setCursorVisiblility visibility: true canHideCursor: false cursorHidden: true
setCursorVisiblility unhide
windowDidBecomeKey23:35 (0%) A-V:  0.000
updateCusorVisibility cursorVisibilityWanted: false
setCursorVisiblility visibility: false canHideCursor: true cursorHidden: false
setCursorVisiblility hide
setCursorVisiblility visibility: true canHideCursor: true cursorHidden: true
setCursorVisiblility unhide
AV: 00:00:04 / 00:23:35 (0%) A-V:  0.000


Exiting... (Quit)
windowDidResignKey
setCursorVisiblility visibility: true canHideCursor: false cursorHidden: false
setCursorVisiblility visibility: true canHideCursor: false cursorHidden: false
```

Thanks for looking into it.

**Comment by Akemi** [comment] 2020-01-31 10:47
i can only assume now, NSCursor has an internal count of hide and unhide calls. if they even out the cursor is visible (0). an App that hides the cursor must call unhide for every hide call. what we actually do and you logs also shows. what happens, it seems, is that one unhide call fails(?) and in the internal hide count doesn't even out anymore. which is a major pain in the ass because i can't get that internal count, hence why i keep count myself.

here you log with some comments from me.
```
// start of mpv, cursor is still visible no need to unhide
// mpv wants to hide, can't hide because canHideCursor
setCursorVisiblility visibility: true canHideCursor: false cursorHidden: false

// window was init and made key, update visibility with wanted state false
windowDidBecomeKey
updateCusorVisibility cursorVisibilityWanted: false
setCursorVisiblility visibility: false canHideCursor: true cursorHidden: false
setCursorVisiblility hide
// cursor was hiden
// hide = 1

// cursor was unhidden and hidden again, most likely cursor movement
setCursorVisiblility visibility: true canHideCursor: true cursorHidden: true
setCursorVisiblility unhide
// hide = 0
setCursorVisiblility visibility: false canHideCursor: true cursorHidden: false
setCursorVisiblility hide
// hide = 1
// cursor is hidden again


// changed spaces, window is not key anymore, cursor should unhide
windowDidResignKey
setCursorVisiblility visibility: true canHideCursor: false cursorHidden: true
setCursorVisiblility unhide
// assuming NSCursor.unhide() failed for whatever reason
// cursor was set unhidden but wasn't actually?
// hide = 1 (stays at 1 most likely, but should be 0)

// changes spaces back to mpv, cursor should hide again
windowDidBecomeKey
updateCusorVisibility cursorVisibilityWanted: false
setCursorVisiblility visibility: false canHideCursor: true cursorHidden: false
setCursorVisiblility hide
// hide = 2 (should be 0 beforehand, should be 1 now)
// cursor was hidden (should be unhidden) and was hidden again

// mouse movement
setCursorVisiblility visibility: true canHideCursor: true cursorHidden: true
setCursorVisiblility unhide
// hide = 1 (should be 1 beforehand, should be 0 now)


// Exiting... (Quit)
windowDidResignKey
setCursorVisiblility visibility: true canHideCursor: false cursorHidden: false
setCursorVisiblility visibility: true canHideCursor: false cursorHidden: false

// cursor was still hidden once more than unhidden, though should be the same
```

**Comment by ccmoore12** [comment] 2020-01-31 19:13
I set up a new user account on my computer and tested there using the same build of mpv and I could not recreate the bug, so I think it's pretty safe to say that there's something strange going on outside of mpv specific to my user account. 

For now, I have a sort of hacky fix using a macro to unhide my cursor when mpv deactivates. 

But I'll do what I can to try and pinpoint the problem even though I have my doubts that I'll be able to find it, since I'm not even sure where to look. At the very least I'll try closing out any apps that run in the background to see if those are causing problems and then go from there.

Worst case scenario I can reinstall the OS, but I'd really rather not do that.

**Comment by Akemi** [comment] 2020-02-01 12:13
please test my PR #7420. there is a download link for the bundle too. see my comments on the commit itself https://github.com/mpv-player/mpv/pull/7420/commits/b8ebc56c06510c23329bc1010e7be5d676c8ee63. if you find any problems let me know.

**Comment by Akemi** [comment] 2020-02-01 15:21
@ccmoore12 kinda missed your last comment. since it seems quite a common problem it would be nice to know why exactly but it should still be fixed within mpv to make it reliable (if possible).

**Comment by fjarlq** [comment] 2020-02-01 23:55
Yes, PR #7420 fixes this bug for me. Thanks!

Sorry @Akemi, I wasn't able to get back to you fast enough about your debug build. Please let me know if you would like me to run anything, because I can reproduce this bug easily for unknown reasons.

**Comment by ccmoore12** [comment] 2020-02-02 01:40
@Akemi Nice, the new bundle you provided has fixed the issue for me. Thanks.

**Comment by Akemi** [comment] 2020-02-02 10:58
great to hear. since the new attempt is less greedy as the previous one there may be cases the cursor is not hiding again when not moved before. if you happen to find such a case let me know and i will try to fix it.

@ccmoore12 otherwise if you happen to find the reason why the old method didn't work that would be nice for future reference.

@fjarlq no worries i took quite long too for looking at it.

**Closed** 2020-02-08 09:56 UTC
Labels: os:mac
