### ISSUE TITLE
fullscreen stutter (--ontop)

### ISSUE THREAD

**Issue by chrisbgp** [mpv-player/mpv#2713] opened 2016-01-13 16:16 UTC
Mac OSX 10.11.2 / mpv 0.14.0

"mpv --no-config --ontop --vo=opengl-hq" stutters and framedrops after going to fullscreen

Without --ontop there are no stutters after going fullscreen.

**Comment by Cpuroast** [comment] 2016-01-13 17:07
I can't seem to be able to replicate this.
the only thing known to cause a performance regression when using El Capitan in full screen is one of the "video-sync=display-*" modes

**Comment by chrisbgp** [comment] 2016-01-13 19:39
Hmm strange, I have tested this multiple times with and without an external screen attached.

It's not a big thing but I just found it strange. Btw, I tested this with a 4K (VP9) video (that's stuttering with the ontop flag in fullscreen). 1080p seems to look fine either way...Can you test with a 4K video?

**Comment by Cpuroast** [comment] 2016-01-13 19:57
Just tested a 4K H.264 video and I get dropped frames with or without --ontop, even without opengl-hq, I have a lower end 2.7 GHz i5-4570R with Iris Pro 5200 on this 21" iMac.

I had to enable --hwdec=videotoolbox to get smooth playback performance, it seems my non hyperthreaded quad-core i5 CPU isn't able to cope with with the 4K decoding in software.

Look at your CPU usage during playback.

Also, I'm pretty sure there are some full screen playback performance regressions in El Capitan, regardless of ontop or video-sync=display-*

What model of mac computer with what GPU?
4K video kinda still pushes any computer.

**Comment by wm4** [comment] 2016-01-13 20:23
You could try more threads (--vd-lavc-threads up to 16), and pbo in vo_opengl.

**Comment by Cpuroast** [comment] 2016-01-13 20:29
in my case --vd-lavc-threads=16 --vo=opengl:pbo does not help at all for software decoding, still get massive frame drop.

**Comment by AirPort** [comment] 2016-01-13 20:36
Does this help: https://github.com/mpv-player/mpv/issues/2392#issuecomment-147200047?

**Comment by chrisbgp** [comment] 2016-01-13 20:48
Some more tests, all in fullscreen:

mpv --no-config --vo=opengl-hq benchmark.webm
VO: [opengl-hq] 3840x2160 yuv420p
V: 00:00:19 / 00:00:20 (99%) Dropped: 37

mpv --no-config --ontop --vo=opengl-hq benchmark.webm
VO: [opengl-hq] 3840x2160 yuv420p
V: 00:00:19 / 00:00:20 (99%) Dropped: 216

mpv --no-config --ontop --vo=opengl-hq --vd-lavc-threads=16 benchmark.webm
VO: [opengl-hq] 3840x2160 yuv420p
V: 00:00:19 / 00:00:20 (99%) Dropped: 218

**Comment by chrisbgp** [comment] 2016-01-13 23:56
@AirPort 
That trick did work for me indeed:

mpv --no-config -fs --ontop --fs-black-out-screens --vo=opengl-hq benchmark.webm
VO: [opengl-hq] 3840x2160 yuv420p
V: 00:00:19 / 00:00:20 (99%) Dropped: 10

Still very confusing why --ontop (without --fs-black-out-screens) makes such a difference...

**Comment by personaone** [comment] 2016-03-07 16:02
I can confirm as well that this issue is present in 0.16 release on OS X, --fs-black-out-screens is the only way for me to have stutter-free fullscreen playback at the moment.

**Comment by kurisubrooks** [comment] 2016-04-28 09:23
I'm having this in 0.17 aswell. Exiting from fullscreen, then re-entering fullscreen seems to fix it for me.

**Comment by wm4** [comment] 2016-04-28 09:24
Most likely a duplicate of #2392.

**Comment by kurisubrooks** [comment] 2016-04-28 09:26
Possible. I too am on El Capitan.

**Comment by excelwang** [comment] 2016-08-16 13:14
This issue has disappeared since my MacBook Pro upgraded to macOS 11.2 public beta 6.

**Comment by Cpuroast** [comment] 2016-08-16 13:21
That's very encouraging, the news about sierra beta6 fixing the issue. Let's hope, it's not a fluke.

**Comment by Akemi** [comment] 2016-12-17 02:57
does this still happen?

**Comment by Akemi** [comment] 2017-01-13 03:02
closing since this is most likely 'fixed' by the DoubleBuffer change or by 10.12 which fixed at least one of the window manager problems. this is also most likely related to #2392 which we will keep open till the bug is properly fixed.

**Closed by Akemi** 2017-01-13 03:02 UTC
Labels: osx
