### ISSUE TITLE
dmabuf-wayland with hwdec=auto-safe results in washed out image

### ISSUE THREAD

**Issue by ralmachado** [mpv-player/mpv#14849] opened 2024-09-14 23:34 UTC
### mpv Information

```bash
mpv 0.37.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
libplacebo version: v6.338.2
FFmpeg version: 6.1.2
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```

### Other Information

```text
- Linux version: Fedora Linux
- Kernel Version: Linux sieger 6.10.9-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Sep  8 17:23:55 UTC 2024 x86_64 GNU/Linux
- GPU Model: Linux hostname 6.10.9-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Sep  8 17:23:55 UTC 2024 x86_64 GNU/Linux
- Mesa/GPU Driver Version: Mesa 24.1.7
- Window Manager and Version: hyprland 0.43.0
- Source mpv: @System fedora repo
- Introduced in version: N/A
```

### Reproduction Steps

1. Open file with `mpv --no-config --vo=dmabuf-wayland $file`
2. Toggle hwdec with Ctrl+h
3. See washed out image with hardware decoding set to vaapi

### Expected Behavior

No change in visual quality.

### Actual Behavior

Video surface gains a grey tint, washing out the image, visible even in screenshots.
Log shows autoconvert from yuv420p10 -> bgr0, which does not happen with vo=gpu.

Example screenshots (without and with hwdec, respectively):
![mpv-shot0001](https://github.com/user-attachments/assets/d1e14021-dc50-41f9-afa2-48e1ec038265)
![mpv-shot0002](https://github.com/user-attachments/assets/3f2f3d80-5a4f-4c25-8187-c04028f88761)

### Log File

[output.txt](https://github.com/user-attachments/files/17004081/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by Dudemanguy** [comment] 2024-09-14 23:40
You can try #14815 and see if anything is different, but it looks like to me the problem is simply that your compositor doesn't support the required format + modifier combination and mpv has to convert it.

**Comment by philipl** [comment] 2024-09-14 23:42
It's presumably hdr content that is being converted in a non hdr aware way. You can insert the vaapi tone map filter to do the conversion in hardware and this should produce a more correct result.

**Comment by Dudemanguy** [comment] 2024-09-14 23:45
I'm not sure if it is supposed to be hdr or not. If it is, I think we're just out of luck here seeing as the wayland protocols needed to communicate this are still lacking.

**Comment by kasper93** [comment] 2024-09-14 23:50
> mpv 0.37.0

You probably should retry with latest version if possible.

> 1920x1080 yuv420p10 bt.709/bt.709/bt.1886/limited/auto

Could you send short sample of this file, so we can try to reproduce?

As we know Hyprland supports only rgb input, because reasons, so we have to convert.

We have two cases swdec
```
[   2.090][i][autoconvert] HW-uploading to vaapi
[   2.090][i][autoconvert] Converting yuv420p10 -> bgr0
[   2.090][v][swscale] using 8 threads for scaling
[   2.105][v][swscale] Using zimg.
[   2.110][i][hwupload] upload bgr0 -> vaapi[bgr0]
```
We convert to bgr with zimg and it works fine.

2nd case is done by vaapi
```
[   4.772][v][hwupload] Hardware conversion: scale_vaapi -> bgr0
[   4.772][i][autoconvert] Converting vaapi[p010] -> vaapi[bgr0]
```
and this one fails, what looks like wrong levels? Either something is not tagged correctly, or just this conversion is broken on your platform, many points of failure here, so can't tell exactly. If you send a sample file, we can try to reproduce and gather more data points.

**Comment by llyyr** [comment] 2024-09-15 07:32
>  Log shows autoconvert from yuv420p10 -> bgr0, which does not happen with vo=gpu.
Because hyprland does not advertise drm modifier support, so we can't use p010 which we would like to use for this file.
```
[   0.219][v][vo/dmabuf-wayland/vaapi] Mapped surface with format p010; drm format 'P010(0000000000000000)' is not supported by compositor.
[   0.219][d][vo/dmabuf-wayland/vaapi] Unsupported format: p010
```

Either way, if the file is HDR then this is expected. dmabuf-wayland can't communicate the HDR metadata to the compositor until https://wayland.app/protocols/wayland-protocols/14, and even after that protocol is merged, the compositor needs to do the right things to actually display HDR correctly.

**Comment by ralmachado** [comment] 2024-09-15 10:30
I don't believe it is an HDR file, either way the issue only occurs with dmabuf, not with vo=gpu-next or vo=gpu

**Comment by ralmachado** [comment] 2024-09-15 10:34
> @ralachado: Are you able to test small patch?
> ``` diff
> diff --git a/filters/f_hwtransfer.c b/filters/f_hwtransfer.c
> index 1dbe0463c3..50105b1e4f 100644
> --- a/filters/f_hwtransfer.c
> +++ b/filters/f_hwtransfer.c
> @@ -597,7 +597,7 @@ struct mp_hwupload mp_hwupload_create(struct mp_filter *parent, int hw_imgfmt,
>              if (sw_imgfmt != u.selected_sw_imgfmt) {
>                  enum AVPixelFormat pixfmt = imgfmt2pixfmt(u.selected_sw_imgfmt);
>                  const char *avfmt_name = av_get_pix_fmt_name(pixfmt);
> -                char *args[] = {"format", (char *)avfmt_name, NULL};
> +                char *args[] = {"format", (char *)avfmt_name, "out_range", "full", NULL};
>                  MP_VERBOSE(f, "Hardware conversion: %s -> %s\n",
>                             p->conversion_filter_name, avfmt_name);
>                  struct mp_filter *sv =
> ```

Not until Monday, I'm afraid.
I thought useful to add that this conversion does not happen with gpu or gpu-next and vaapi.

**Comment by llyyr** [comment] 2024-09-15 10:48
> I thought useful to add that this conversion does not happen with gpu or gpu-next and vaapi.

This is irrelevant, dmabuf-wayland is a special VO that tries to use fixed function hardware for every step of the way.

**Comment by Dudemanguy** [comment] 2024-09-15 14:19
Seems like just a hyprland bug to me.

**Comment by llyyr** [comment] 2024-09-16 00:27
> also happens on kwin

Your issue is with HDR, OP is presumably _not_ using HDR. Please don't mix up issues

**Comment by kasper93** [comment] 2024-09-16 00:57
Yes, there is nothing HDR in this issue
```
Decoder format: 1920x1080 yuv420p10 bt.709/bt.709/bt.1886/limited/auto CL=mpeg2/4/h264 crop=1920x1080+0+0
```

I suspect we converting to different rgb levels that are set in the compositor, that's why we have washed out colors. Ultimately issue is similar, because it is all color management, but at least this issues, should be easier to fix, than whole HDR support.

**Comment by kasper93** [comment] 2024-09-30 00:35
For SDR, could you try ` -vf=scale_vaapi=out_range=full`?
For HDR, could you try `-vf=tonemap_vaapi`?

**Closed** 2024-10-03 22:06 UTC
Labels: os:linux, down-upstream:hyprland
