### ISSUE TITLE
problem when seeking on wasapi exclusive

### ISSUE THREAD

**Issue by blackarcher21** [mpv-player/mpv#2599] opened 2015-12-16 05:14 UTC
when try seeking many times, I feel that it sounds a little bit choppy compared to wasapi shared and dsound which sounds smooth.

**Comment by blackarcher21** [comment] 2015-12-16 17:18
I don't know if choppy is the right word to describe this or I could say a little rough sound on transition when seeking. tested on audio and video. I just hope a little improvement though it doesn't bother for overall playback. thanks.

**Comment by kevmitch** [comment] 2015-12-16 22:05
I doubt this can be improved further. Your description is a little vague, but it's possible you're just describing #2515. Windows shared mode probably implements some sort of mitigation of this, which obviously isn't used in exclusive mode.

**Comment by blackarcher21** [comment] 2015-12-17 05:09
yes, more or less I've got similar experience, but when seeking on wasapi exclusive mode. thanks for pointing to that issue. :)

**Comment by kevmitch** [comment] 2016-01-29 09:11
Closing this because it's a duplicate of #2515.

**Closed by kevmitch** 2016-01-29 09:11 UTC
Labels: info-needed, ms-windows
