### ISSUE TITLE
External shader files:

### ISSUE THREAD

**Issue by maimteve** [mpv-player/mpv#1660] opened 2015-03-07 07:03 UTC
Could mpv support the loading of external shader files? Video game emulator frontends can support several formats. They are less needed in media players, but they could have some use. Users can use the latest upscaling options instead of waiting for them to be added into the media player. 

There is also the question of what file format to support as there are several. 

https://github.com/libretro/common-shaders

**Comment by lachs0r** [comment] 2015-03-07 07:15
Duplicate of #568.

**Closed by lachs0r** 2015-03-07 07:15 UTC
