### ISSUE TITLE
none UTF-8 characters from metadata not displayin correctly.

### ISSUE THREAD

**Issue by taras133** [mpv-player/mpv#9238] opened 2021-09-24 09:05 UTC
garbled metadata when playing mp3 stream using mpv command.

mpv --metadata-codepage=auto http://eradio.cc.colocall.com:8000/eradio

mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Tue Dec  8 19:04:35 UTC 2020
FFmpeg library versions:
   libavutil       56.60.100
   libavcodec      58.112.103
   libavformat     58.64.100
   libswscale      5.8.100
   libavfilter     7.90.100
   libswresample   3.8.100
FFmpeg version: git-2020-11-22-9208b72

Ubuntu Impish Indri (development branch)
Release:	21.10

File tags:
 icy-title: Pianoboy - � ���� ���
A: 00:00:29 / 00:00:33 (88%) Cache: 3.8s/135KB

####
i tried setting --metadata-codepage=auto, tried changing different system encodings, have no affect, this issue is so annoying, 
please help,

**Comment by CounterPillow** [comment] 2021-09-24 09:18
duplicate of #8844

**Comment by Dudemanguy** [comment] 2022-01-19 03:10
Duplicate as noted.

**Closed by Dudemanguy** 2022-01-19 03:10 UTC
Labels: os:linux
