### ISSUE TITLE
sub-step skips over lines when paused

### ISSUE THREAD

**Issue by sqrtNOT** [mpv-player/mpv#11445] opened 2023-03-13 08:40 UTC
### Important Information

Provide following Information:
- mpv version
- Platform and Version
- Source of the mpv binary

Compiled from latest git master on Linux. 

### Reproduction steps

1. Create an srt file with content similar to this:
```1
00:00:01,000 --> 00:00:05,000
line 1

2
00:00:05,001 --> 00:00:10,000
line 2

3
00:00:10,000 --> 00:00:15,000
line 3
```
Note that line 2's ending timestamp is the same as line 3's starting timestamp: 00:00:10,000

2. Load that .srt file with dummy audio/video
3. Pause playback.
4. Use the sub-step hotkeys (default is ctrl+shift+left/right) to navigate to line 3
5. sub-step left once

### Expected behavior
Subtitle line 2 should show up.

### Actual behavior
Subtitle line 1 shows up; skipping over line 2.
### Log file

The log file from a --no-config --no-video run during the error is just a bunch of
`[d][cplayer] Run command: sub-step, flags=73, args=[skip="1", flags="primary"]`
so probably useless but here it is anyway: [logfile](https://github.com/mpv-player/mpv/files/10955101/substep.txt)

### Sample files
The example .srt file: [substep.srt](https://github.com/mpv-player/mpv/files/10955128/substep.srt.txt)

**Comment by Dudemanguy** [comment] 2023-10-02 01:05
I can't reproduce this at all. Actually not even on a commit from the date that this was reported. It's weird because I do vaguely recall this being an issue. Not sure what exactly fixed it, but I'll close it.

**Comment by Dudemanguy** [comment] 2023-10-02 01:07
Oops my mistake. It's the lines in the terminal that have this issue.

**Closed** 2023-11-06 23:12 UTC
Labels: core:subtitle
