### ISSUE TITLE
Playback window in wrong position

### ISSUE THREAD

**Issue by jimmy-1000** [mpv-player/mpv#8725] opened 2021-04-13 16:35 UTC
I know this is not a _critical issue_, but fix this would be very good for many of us.
In Windows 7 and 10 if you open a video with resolution equal or higher than your monitor, mpv put the playback window a little above where it should be and partially covers the buttons up, as you can see in the picture below.

- mpv version: tested on 032, 0.33 and 033.1
- Windows Version: Windows 7 64bits and Windows 10 64bits
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/64bit/
--no-config first: Same problem
  -Expected behavior:  mpv should calculate the exact position between the task bar from the bottom to the top of the screen like other players

**Playing with mpv**

![mpv](https://user-images.githubusercontent.com/78575427/114587832-41772000-9c43-11eb-8e73-58725921860d.jpg)

**Playing with MPC-HC**

![mpc](https://user-images.githubusercontent.com/78575427/114588049-7c795380-9c43-11eb-9ed9-3ae650061c18.jpg)

**Comment by avih** [comment] 2021-04-13 16:57
You didn't follow the issue template, and you know it's a duplicate of an open issue, because you commented on the other issue not long ago. Please behave.

Duplicate of #6695.

**Closed by avih** 2021-04-13 16:57 UTC
Labels: os:win

**Comment by jimmy-1000** [comment] 2021-04-13 18:47
> 
> 
> You didn't follow the issue template, and you know it's a duplicate of an open issue, because you commented on the other issue not long ago. Please behave.
> 
> Duplicate of #6695.


You closed an issue that **has not been solved** by the programmers. Autofit is not a _real solution_. You say duplicate not long ago, but that post is from 2019 !!

**Comment by avih** [comment] 2021-04-13 19:45
> but that post is from 2019

And it's not fixed yet, and you added a comment there 4 weeks ago. Duplicating an existing issue won't help, especially when the issue template instructs you to not open duplicate issues.

**Comment by jimmy-1000** [comment] 2021-05-03 04:28
If we use mpv with "no border" the problem is fixed.
