### ISSUE TITLE
Changing font on this video's subtitles

### ISSUE THREAD

**Issue by firewater2** [mpv-player/mpv#5922] opened 2018-06-13 20:10 UTC
### mpv version and platform

mpv-x86_64-20180610-git-4d2b865 / Windows 8

### Reproduction steps

Play the video, and use the following method for forcing subtitle style change, via input.conf:

`Ctrl+1 no-osd cycle_values sub-font "Helvetica" "Helvetica" "Helvetica"; no-osd cycle_values sub-border-size "2" "1" "0"; no-osd cycle_values sub-color "#dadada" "#dadada" "#dadada"; no-osd cycle_values sub-shadow-color "0.0/0.0/0.0/0.0" "0.0/0.0/0.0/0.0" "0.0/0.0/0.0/1"; no-osd cycle_values sub-shadow-offset "0" "0" "3"; no-osd cycle_values osd-font "Helvetica" "Helvetica" "Helvetica"; no-osd cycle_values osd-color "#dadada" "#dadada" "#dadada"; no-osd cycle_values osd-shadow-color "0.0/0.0/0.0/0.0" "0.0/0.0/0.0/0.0" "0.0/0.0/0.0/1"; no-osd cycle_values osd-border-size "2" "1" "0"; no-osd cycle_values osd-shadow-offset "0" "0" "3"; no-osd cycle_values sub-ass-style-override "force" "force" "force"`

### Expected behavior

Changes subtitle font.

### Actual behavior

Keeps font embedded with video (yet all other parameters do change).

### Sample files

https://mega.nz/#!LccBFQAZ!FwDgqX_KLb0a3wK9urfs6fMX6WXyH43YqNqNss3at6Q

---

Only ever happened with this video out of hundreds I've tried. Wondering why that is, and if there's any hope the style could be forced into whatever this video uses for that subtitle, someday.

**Comment by qmega** [comment] 2018-06-14 01:44
That file hardcodes the font with an `\fn` tag every single line. This is a duplicate of #5547.

You can use `--sub-ass-override=strip` to get rid of those and force your font, but that will break typesetting and even stuff like italics. AFAIK mpv doesn't have a way to strip only font tags.

**Comment by firewater2** [comment] 2018-06-14 18:48
JFC, why would anyone do that... thanks. I'm gonna leave it open just in case "stripping only the font" is considered a valid request.

**Comment by Jimmy-Z** [comment] 2018-07-07 08:36
Yeah, I would want that, I'm the creator of #5547 though, it might surprise you but this kind of stupid ass is rather common...

**Comment by Akemi** [comment] 2019-09-20 16:39
should should be brought up to libass.

**Closed by Akemi** 2019-09-20 16:39 UTC
Labels: libass

**Comment by pnotz17** [comment] 2020-05-11 17:26
hello sir i was wondering how to change the actual font in mpv ot the subtitle font if there is a way , i changged my default font in openbox ad now the font in mpv has changed i tried everything it wont go back to the default font it had for some reason.....tis hashappened to me in the past as well no biggie im just wondering how to set it to its default
