### ISSUE TITLE
An option in EDL to explicitly define the track layout of each file entry using track IDs

### ISSUE THREAD

**Issue by hedgehog90** [mpv-player/mpv#8149] opened 2020-10-06 15:00 UTC
A problem arose when I tried to play an edl which joined 2 videos and replacing the soundtrack:

```
# mpv EDL v0
start.mkv
end.mp4
!new_stream
music.flac,flags=default
```

However there's a silent audio track on start.mkv and end.mkv, and I guess the default track layout is that of the first input file, therefore the new audio stream (music.flac) was made audio track 2. I figured having 'flags=default' would make it so audio track 2 was selected by default, but it did not (for some reason I'm not aware of).
The only way around this was to remux start.mkv without the audio track.

A better way around this however would be to have a way to define what tracks are used from each file.

I propose we could use the 'layout' parameter to define precisely which track IDs you want included from each file, eg:

```
# mpv EDL v0
start.mkv,layout=0
end.mp4,layout=0
!new_stream
music.flac
```

This would select only the video stream from start.mkv and end.mp4, and the audio stream from main.flac would become the only (and default) audio track.

(Assuming the first file entry defines the layout, then specifying the layout for end.mp4 would not be necessary, but I'm not sure if the layout is defined by the first resulting concatenation or the first file entry, but either way this would result in the same output - a media with 1 video track and 1 audio track)

**Comment by Akemi** [comment] 2020-10-06 17:27
duplicate of #8148?

**Closed by Akemi** 2020-10-06 17:27 UTC
Labels: meta:feature-request

**Comment by hedgehog90** [comment] 2020-10-06 17:29
Github threw me an error when I tried posting it initially. Didn't realise I double posted, apologies.
