### ISSUE TITLE
mpv player volume up doesn't work

### ISSUE THREAD

**Issue by zhouxinghong** [mpv-player/mpv#14594] opened 2024-07-25 10:25 UTC
### mpv Information

```bash
mpv v0.38.0-637-g3c7b6db2 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Jul 25 2024 00:09:42
libplacebo version: v7.349.0 (v7.349.0-dirty)
FFmpeg version: N-116414-g896c22ef0
FFmpeg library versions:
   libavcodec      61.10.100
   libavdevice     61.2.100
   libavfilter     10.2.102
   libavformat     61.5.101
   libavutil       59.28.100
   libswresample   5.2.100
   libswscale      8.2.100
```

### Other Information

- Windows version: 10
- GPU model, driver and version:
- Source of mpv:
- Introduced in version:

### Reproduction Steps

mpv --no-config --volume=150 --volume-max=250 --log-file=output.txt "https://www.youtube.com/watch?v=gWI9uaLrhfc"

### Expected Behavior

Volume up to 150 by default, volume up to 250 at max.

### Actual Behavior

In fact, increasing the volume to 250% is no different from increasing the volume to 100%.

### Log File

[output.zip](https://github.com/user-attachments/files/16374372/output.zip)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [  ] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment] 2024-07-25 14:21
Your log file is incomplete

**Comment by zhouxinghong** [comment] 2024-07-26 08:39
You can try it yourself its volume performance behavior should be the same as mine. I just removed the duplicate log output.

**Comment by llyyr** [comment] 2024-07-26 10:04
> You can try the volume performance effect yourself.

I did and it works for me, we can close this then.

**Comment by zhouxinghong** [comment] 2024-07-26 11:57
`mpv --no-config --volume=150 --volume-max=250 --log-file=mp3.txt "https://ws.stream.qqmusic.qq.com/C400001bU5SR0arBDu.m4a?guid=162914&vkey=7A44D8E118C051BC5CBC0CC61F19BE660449CAEEE5AB5517CD41ED7FE7E6D48A3DA9AEA791A02F28E4007BD58068B1BFE3E3BE406F45BB76&uin=&fromtag=103032"`

**Comment by zhouxinghong** [comment] 2024-07-28 10:44
The following setting items also do not work:
--replaygain=<no|track|album>
--replaygain-preamp=<db>
--replaygain-clip=<yes|no>
--replaygain-fallback=<db>
--audio-delay=<sec>
...

**Comment by sfan5** [comment] 2024-08-07 13:27
Works for me.

**Closed by sfan5** 2024-08-07 13:27 UTC
Labels: os:win

**Comment by zhouxinghong** [comment] 2024-08-08 16:48
`Works for me.`
What operating system are you using?
What operating system CPU are you using?
What operating system graphics card are you using?
What MPV version are you using?

**Comment by sfan5** [comment] 2024-08-09 11:01
Arch Linux with Xfce (X11) and PipeWire for Audio.
mpv v0.38.0-682-g88885c0401 but I guarantee you it works on 0.38.0 too.

I would be very surprised if it's indeed broken on Windows.

**Comment by zhouxinghong** [comment] 2024-08-10 00:32
My environment:
![image](https://github.com/user-attachments/assets/6826c39e-370d-4987-a05a-27305031eb5e)

**Comment by llyyr** [comment] 2024-08-10 02:31
> You can actually try it in Windows 10 to see if the above settings work:

We literally have developers that use Windows, and many users that actively report issues that also use Windows. If such a basic thing like `--volume` wasn't working, we'd be getting bug reports on an hourly basis.

If it's not working then the problem is something about your system or drivers, not mpv.

**Comment by zhouxinghong** [comment] 2024-08-26 10:17
The volume percentage increased to 200%, but the volume level did not change. . . You can try it yourself in Windows 10. . .
