### ISSUE TITLE
OS X App prints malloc errors

### ISSUE THREAD

**Issue by basakil** [mpv-player/mpv#3026] opened 2016-04-06 01:15 UTC
In OS X 10.11.4 with mpv latest stable bundle, I see the following error printed on console about 30 times for each second -for each frame, I guess?-:

```
4/6/16 03:24:27.205 mpv[27036]: mpv(27036,0x700000841000) malloc: *** mach_vm_map(size=18446744073707057152) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug

```

App plays the video fine, but _"~/Library/Logs/mpv.log"_ file size increases ~1.5MB for each second. Also, CPU load rises to 70-100% if I leave the "console.app" open -due to console gui refresh caused by frequent errors, I guess-.

**Comment by wm4** [comment] 2016-04-06 19:03
>with mpv latest stable bundle, 

Which one?

Can't see anything wrong when running mpv git master on OSX 10.10.x. (Self-built.)

**Comment by basakil** [comment] 2016-04-07 15:08
I've installed the one in "_http://sva.wakku.to/~chris/mpv_builds/mpv_latest.zip_" regarding "_Using git master is recommended, although it may be slightly unstable at times._" in page "_https://mpv.io/installation/_".

**Comment by wm4** [comment] 2016-04-07 15:14
Ping @ChrisK2

**Comment by ChrisK2** [comment] 2016-04-07 23:29
Can't reproduce.

**Comment by basakil** [comment] 2016-04-19 18:59
As a -temporary?- solution:

1- I put the below lines on top of "~/.config/mpv/mpv.conf" to suppress -much of- stdout/stderr output:
```
--log-file=/dev/null
--quiet=yes
--really-quiet
--msg-level=all=error
--terminal=no
--no-term-osd=yes
```
2- I made a symbolic link to /dev/null for "~/Library/Logs/mpv.log":
`ln -sf /dev/null ~/Library/Logs/mpv.log`

3- I do not leave console.app open while mpv is running.

**Comment by basakil** [comment] 2016-04-19 19:24
I noticed a new release (0.17.0), dated 8 days ago on the [github page](https://github.com/mpv-player/mpv/releases/tag/v0.17.0). Neither the bundle in the [installation page](http://sva.wakku.to/~chris/mpv_builds/mpv_latest.zip) nor the [homebrew formula](https://github.com/Homebrew/legacy-homebrew/blob/master/Library/Formula/mpv.rb) was renewed, so I tried building from source:
I did not see any waf option for producing an app bundle, the output executable was just 2.2MB, and there was an empty mpv.app in the Tools directory. The executable also did not recognize the scripts (was probably relying on an installed lua, as config output said it could not find). 
Is there a convenient way/command to produce an app bundle (like the one in the [installation page](http://sva.wakku.to/~chris/mpv_builds/mpv_latest.zip)) that also finds/puts the missing libraries in the bundle (or links with them, as in a static build)?

**Comment by AirPort** [comment] 2016-04-19 19:29
The homebrew [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpv.rb) is up to date, they just recently changed the repo's structure and the URL is different.

**Comment by basakil** [comment] 2016-04-19 20:55
`brew info mpv` is showing version 0.16.0, that's why I skipped it, [yours](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpv.rb) is 0.17.0. Also I found in the brew formula is the bundling command I was looking for: 

`python ./TOOLS/osxbundle.py ./build/mpv`

The produced bundle is larger in size (35MB vs 25MB, has lots of libav* libraries now...), does not contain any `liblua.X.X.dylib` file in `lib` directory and some user scripts are somehow not working now: [stats](https://github.com/Argon-/mpv-stats/), [drc_control](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/drc-control.lua), ...

**Comment by Akemi** [comment] 2017-01-13 03:17
could you resolve your issues?

**Comment by basakil** [comment] 2017-01-13 08:08
In addition to the [temporary steps above](https://github.com/mpv-player/mpv/issues/3026#issuecomment-212069261), I use a [wrapper app](https://github.com/basakil/OpenWithMPV.app) that calls some suppressor methods before & after mpv initialization. It also opens a new window for each media-file I open and I can leave console.app open in the background now.

**Comment by Akemi** [comment] 2017-01-13 14:28
so you still get those errors? if yes, could you describe the steps to reproduce it?

**Comment by basakil** [comment] 2017-01-14 11:27
I am now on OS X 10.11.6 and -upgraded- mbp5.5, I did not test it with all media files I have, but whenever I open a media file from the console (without the above app) I still see malloc errors on the console. I tested it with the old 0.17 build above and the new 0.23 build (from binary installations page on mpv.io). Console prints aprox. 20-30 errors per seconds (for each frame, I guess?).

**Comment by basakil** [comment] 2017-01-14 13:50
My [~/.config/mpv](https://github.com/mpv-player/mpv/files/705968/mpv.zip) folder is attached.

**Comment by wm4** [comment] 2017-01-14 14:00
>4/6/16 03:24:27.205 mpv[27036]: mpv(27036,0x700000841000) malloc: *** mach_vm_map(size=18446744073707057152) failed (error code=3)

That's 2^64-2494464. Could be an overflow. You can't use a debugger?

**Comment by Akemi** [comment] 2017-01-14 15:13
`--osd-back-color=0.0/0.20` this line causes it. i just updated to git master of libass and it seems like [this](https://github.com/libass/libass/commit/dec079d312a2dcf73d20446bebd2935e8a6a9e41) fixed this issue. if you can confirm il will close this issue.

**Comment by basakil** [comment] 2017-01-14 19:28
It works!!. 10 months old issue.... 1 line...
By the way, I figured 25% increase in Energy impact /btw above builds (v0.17 vs v0.23). CPU shows 10% increase aprox. so GPU/mem. impact increase should be 30% (on Nvidia 9400m OpenGL 2.1 HW). 

- Is this normal?, configurable? (quality vs performance) ?
- or Should I ask this in another thread?

**Comment by Argon-** [comment] 2017-01-14 19:37
You didn't test with the same settings.
You are using a built in preset and it changed many times already.

**Comment by Akemi** [comment] 2017-01-14 19:38
it could be caused by several changes, maybe even default settings that changed. 
closing this since the issue got resolved.

**Closed by Akemi** 2017-01-14 19:38 UTC
Labels: info-needed, osx
