### ISSUE TITLE
vo_gpu-next: the brightness of subtitles look unnormal with hdr

### ISSUE THREAD

**Issue by dyphire** [mpv-player/mpv#9410] opened 2021-11-07 04:55 UTC
### Important Information

Provide following Information:
- mpv version
```
mpv 0.34.0-14-g662c793a55 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on Fri Nov  5 03:45:59 UTC 2021
FFmpeg library versions:
   libavutil       57.7.100
   libavcodec      59.12.100
   libavformat     59.8.100
   libswscale      6.1.100
   libavfilter     8.16.101
   libswresample   4.0.100
FFmpeg version: git-2021-11-04-f6ab103b
```
- Windows Version
   win11 beta
- Source of the mpv binary
   built based on shinchiro
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

### Reproduction steps

open the hdr video with external subtitles

### Expected behavior

The brightness of subs should be the same both in vo_gpu and vo_gpu-next

### Actual behavior

`--no-config  --vo=gpu`
![](https://cdn.jsdelivr.net/gh/dyphire/PicGo/img/2021/11/07/20211107122114.png)

`--no-config  --vo=gpu-next`
The brightness of subs look different
![](https://cdn.jsdelivr.net/gh/dyphire/PicGo/img/2021/11/07/20211107121802.png)

Subs on `vo=gpu-next` look like `--vo=gpu --blend-subtitles=video`
`--no-config  --vo=gpu --blend-subtitles=video`
![](https://cdn.jsdelivr.net/gh/dyphire/PicGo/img/2021/11/07/20211107122430.png)

### Log file
`--no-config  --vo=gpu-next`
[test.log](https://github.com/mpv-player/mpv/files/7491745/test.log)

**Comment by haasn** [comment] 2021-11-07 09:34
Effectively a duplicate of #9399

**Closed by haasn** 2021-11-07 09:34 UTC
Labels: os:win, vo:gpu-next
