### ISSUE TITLE
if source video is interlaced then use `deinterlace`

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#12414] opened 2023-09-17 15:14 UTC
There is a script from 6 years ago called [autodeint](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autodeint.lua) which supposed to answer my needs, but it's not "auto", I have to manually use a keybind (Ctrl+d) to use it, which defeats the purpose of "auto".

And since it was 6 years ago, I guess a lot have changed since then, so there might be a clever way to do it.
I remember seeing somewhere here, probably on one of the PRs, the addition of stats.lua "Picture Type: P" or "Picture Type: I", which is probably what I assume it means, if the video is interlaced or not, and could use that to determine if deinterlace or not.

**Comment by llyyr** [comment] 2023-09-17 15:19
Duplicate of #10358

**Closed as completed** 2023-09-17 15:21 UTC
Labels: meta:question
