### ISSUE TITLE
Different colors in HDR full screen/windowed mode with vo=gpu-next

### ISSUE THREAD

**Issue by antonchakley** [mpv-player/mpv#15175] opened 2024-10-25 18:15 UTC
### mpv Information

```bash
mpv v0.39.0-214-g165159fd Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Oct 23 2024 00:05:52
libplacebo version: v7.349.0 (v7.349.0-19-g118d810-dirty)
FFmpeg version: N-117623-g3565903c6
FFmpeg library versions:
   libavcodec      61.22.100
   libavdevice     61.4.100
   libavfilter     10.6.100
   libavformat     61.9.100
   libavutil       59.44.100
   libswresample   5.4.100
   libswscale      8.6.100
```

### Other Information

```text
- Windows version: Windows 11 23H2 22631.4317
- GPU model, driver and version: NVIDIA GeForce RTX 4080 SUPER  game ready driver  565.90
Monitor LG32GS95UE  OLED
- Source of mpv: https://github.com/shinchiro/mpv-winbuild-cmake/releases
- Introduced in version: no idea
```

### Reproduction Steps

colors slightly different in full screen and windowed mode 
highlights lose their brigthness and look more gray
difference is pretty noticeable 
in HDR windows mode  and HDR content with vo=gpu-next , target-colorspace-hint=yes

minimal config to reproduce

vo=gpu-next 
target-colorspace-hint=yes

no such issues with 
vo=gpu 
target-colorspace-hint=yes

### Expected Behavior

same image in full screen and windowed mode

### Actual Behavior

different image in full screen and windowed mode

### Log File

--gpu-debug -v -v > log.txt

[log.txt](https://github.com/user-attachments/files/17526080/log.txt)

### Sample Files

![Untitled](https://github.com/user-attachments/assets/3f43948d-3956-46a6-a517-2193dbcaf4a3)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by kasper93** [comment] 2024-10-31 03:58
In Windowed mode the HDR signal is tone-mapped by the compositor to common reference level for composition with other desktop elements. In full screen it attempts it pass-through the HDR untouched. This is expected behavior and how is designed in Windows currently.

**Comment by kasper93** [comment] 2024-10-31 17:04
Duplicate of https://github.com/mpv-player/mpv/issues/10628 and works as expected.

**Closed by kasper93** 2024-10-31 17:04 UTC
Labels: os:win

**Comment by laichiaheng** [comment] 2025-03-12 05:25
> In Windowed mode the HDR signal is tone-mapped by the compositor to common reference level for composition with other desktop elements. In full screen it attempts it pass-through the HDR untouched. This is expected behavior and how is designed in Windows currently.

How about on Linux? What does Linux do to this?
