### ISSUE TITLE
Sample rate shown as 192000Hz with Dolby TrueHD & DTS-HD

### ISSUE THREAD

**Issue by Emulle** [mpv-player/mpv#6419] opened 2019-01-02 22:48 UTC
Just checking in to see if this is normal or not.  
When playing back Dolby TrueHD & DTS-HD MA audio files mpv reports back a sample rate of 192000Hz/192kHz when the files are 48000Hz/48kHz. 

Log:
https://pastebin.com/q3bzqbs1

Important bits: 

> [mkv] | + a track...
[mkv] |  + Track number: 2
[mkv] |  + Name: Mission Impossible Fallout
[mkv] |  + Track type: Audio
[mkv] |  + Audio track
[mkv] |   + Sampling frequency: 48000.000000
[mkv] |   + Channels: 8
[mkv] |  + Codec ID: A_TRUEHD
[ad] Codec list:
[ad]     spdif_truehd (truehd) - libavformat/spdifenc audio pass-through decoder
[ad] Opening decoder spdif_truehd
[ad] Selected codec: spdif_truehd (libavformat/spdifenc audio pass-through decoder)
[af] User filter list:
[af]   scaletempo (scaletempo.00)
[af]   lavcac3enc (lavcac3enc.00)
Starting playback...
[ad] In: profile=-99 samplerate=48000
[af] [in] 192000Hz 7.1 8ch spdif-truehd
[af] [scaletempo] 192000Hz 7.1 8ch spdif-truehd
[autoconvert] inserting resampler
[swresample] format change, reinitializing resampler
[swresample] 192000Hz 7.1 spdif-truehd -> 192000Hz 7.1 s16
[swresample] unsupported conversion: spdif-truehd -> s16
[swresample] libswresample failed to initialize.
[af] Disabling filter scaletempo.00 because it has failed.
[af] [lavcac3enc] 192000Hz 7.1 8ch spdif-truehd
[autoconvert] inserting resampler
[swresample] format change, reinitializing resampler
[swresample] 192000Hz 7.1 spdif-truehd -> 48000Hz 5.1(side) floatp
[swresample] unsupported conversion: spdif-truehd -> floatp
[swresample] libswresample failed to initialize.
[af] Disabling filter lavcac3enc.00 because it has failed.
[af] [userspeed] 192000Hz 7.1 8ch spdif-truehd
[af] [userspeed] (disabled)
[af] [convert] 192000Hz 7.1 8ch spdif-truehd
[ao] Trying audio driver 'alsa'
[ao/alsa] requested format: 192000 Hz, 7.1 channels, spdif-truehd
[ao/alsa] using ALSA version: 1.1.7
[ao/alsa] opening device 'default' => 'default:AES0=6,AES1=130,AES2=0,AES3=14'
ALSA lib conf.c:5001:(snd_config_expand) Unknown parameters AES0=6,AES1=130,AES2=0,AES3=14
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM default:AES0=6,AES1=130,AES2=0,AES3=14
[ao/alsa] got error 'Invalid argument'; opening iec fallback device 'hdmi:AES0=6,AES1=130,AES2=0,AES3=14'
[ao/alsa] trying format s16/2
[ao/alsa] which we understand as: unknown8
[ao/alsa] using spdif passthrough; ignoring the channel map.
[ao/alsa] hw pausing supported: yes
[ao/alsa] buffersize: 19200 samples
[ao/alsa] period size: 4800 samples
[ao/alsa] device buffer: 19200 samples.
[ao/alsa] using soft-buffer of 38400 samples.
AO: [alsa] 192000Hz 7.1 8ch spdif-truehd
AO: Description: ALSA audio output
[af] [convert] (disabled)
[af] [out] 192000Hz 7.1 8ch spdif-truehd

**Comment by tomty89** [comment] 2019-01-03 12:42
duplicate of #6334

**Comment by Mitzsch01** [comment] 2019-01-03 18:45
This is because DTS-HD and TrueHD are sent with these parameters to the AVR. "8 Channel @ 192khz" and alsa only shows them. 
This does not refer to the source frequency of 48khz.

**Closed** 2019-10-25 10:44 UTC
Labels: core, core:audio, core:file
