### ISSUE TITLE
Weird rendering of GUI on OSX

### ISSUE THREAD

**Issue by Linuus** [mpv-player/mpv#2293] opened 2015-09-07 20:36 UTC
When I open mpv on OSX Yosemite the GUI looks weird. It looks like it renders multiple times or something. It's hard to explain so I attach an image.

Any ideas on how to solve it?
![skarmavbild 2015-09-07 kl 22 34 31](https://cloud.githubusercontent.com/assets/379823/9722642/eee92092-55b0-11e5-95b8-ca4abdc0dfed.png)

Version info from mpv --version
```
mpv 0.10.0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on Mon Sep  7 22:27:35 CEST 2015
ffmpeg library versions:
   libavutil       54.27.100
   libavcodec      56.41.100
   libavformat     56.36.100
   libswscale      3.1.101
   libavfilter     5.16.101
   libswresample   1.2.100
```

**Comment by wm4** [comment] 2015-09-07 20:53
Duplicate of #2287.

Certainly a libass problem.

**Closed** 2015-09-07 20:54 UTC
