### ISSUE TITLE
Mpv quit unexpectedly when closing a H265/HEVC video when setting vo to `gpu-next`.

### ISSUE THREAD

**Issue by RadioNoiseE** [mpv-player/mpv#15455] opened 2024-12-08 11:28 UTC
### mpv Information

```bash
mpv 8d20b72 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Dec  7 2024 13:29:38
libplacebo version: v7.349.0
FFmpeg version: 7.1
FFmpeg library versions:
   libavcodec      61.19.100
   libavdevice     61.3.100
   libavfilter     10.4.100
   libavformat     61.7.100
   libavutil       59.39.100
   libswresample   5.3.100
   libswscale      8.3.100
```

### Other Information

```text
- macOS version: macOS 15.1.1 (24B91)
- Source of mpv: nightly build from master
- Latest known working version: /
- Issue started after the following happened: `vo=gpu-next`
```

### Reproduction Steps

```bash
mpv --no-config --vo=gpu-next ~/Desktop/Yuru\ Camp\ Movie\ \[Ma10p_2160p_DoVi\]\[x265_flac\].mkv
```

### Expected Behavior

It should close normally.

### Actual Behavior

MacOS complains about `mpv quit unexpectedly` and when launched from the terminal, zsh complains about a bus error.

### Log File

[mpv-debug.log](https://github.com/user-attachments/files/18051804/mpv-debug.log)
[macos-crash.log](https://github.com/user-attachments/files/18051805/macos-crash.log)
[lldb.log](https://github.com/user-attachments/files/18051829/lldb.log)

### Sample Files

The file is probably too big to upload here (10.64 GB), but it can be downloaded [here](https://nyaa.land/view/1718110), and is located:

```
[VCB-Studio] Yuru Camp/
|   +[Airota&Nekomoe kissaten&VCB-Studio] Yuru Camp Movie [Ma10p_2160p]
    |   +[Airota&Nekomoe kissaten&VCB-Studio] Yuru Camp Movie [Ma10p_2160p_SDR][x265_flac].mkv (10.9 GiB)
```

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [ ] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by Akemi** [comment] 2024-12-08 11:42
is the `mpv-debug.log` from an actual crash run, eg it does crash with --no-config?
does it consistently crash every time?
i assume you mean the "DoVi" you initially mentioned and used in the log, and not the "SDR" file under "Sample Files"?

**Comment by RadioNoiseE** [comment] 2024-12-08 12:32
> is the `mpv-debug.log` from an actual crash run, eg it does crash with `--no-config`?

Yes, it is from an actual crash run. It does not crash with `--no-config`, and only when `--vo=gpu-next`.

> does it consistently crash every time?

Yes.

> i assume you mean the "DoVi" you initially mentioned and used in the log, and not the "SDR" file under "Sample Files"?

Ah yes, I made a mistake when copy-pasting the directory structure.

**Comment by Akemi** [comment] 2024-12-08 18:08
just tested it and could reproduce. even though this issue occurs without `--target-colorspace-hint=yes` it's a duplicate of #12666. the provided `libMoltenVK.dylib` in the comments of the other issue fixes this problem too. most likely because we copy over/pass the DoVi metadata?

anyway closing this, it will be fixed with the next MoltenVK release.

**Closed by Akemi** 2024-12-08 18:08 UTC
Labels: os:mac

**Comment by RadioNoiseE** [comment] 2024-12-08 23:41
Thanks for your investigation.
