### ISSUE TITLE
[macOS] Worse performance than QuickTime Player without macos-force-dedicated-gpu?

### ISSUE THREAD

**Issue by jasonhan-vassar** [mpv-player/mpv#8279] opened 2020-11-17 12:26 UTC
When playing a video in mpv with default settings, it seems that my system runs less smoothly compared to playing the same video in QuickTime Player. I test this by invoking Mission Control (three-finger swipe up on trackpad) and when a video is playing in mpv, the animations are significantly choppier. Other apps also take a performance hit. QuickTime Player doesn't seem to noticeably lag my system though.

When I enable `macos-force-dedicated-gpu`, mpv runs very smoothly and it appears to run as smooth as QuickTime Player. Unfortunately, my computer heats up like crazy and my GPU usage is consistently >80% with that option.

Can anyone reproduce? I'm currently on macOS 11 but this has happened with 10.15 as well. I know mpv has conservative defaults, so does anyone have any settings recommendations? If this is known but there isn't a solution, does anyone know why QuickTime works so well?

If these help, QuickTime usually runs with 8-10% CPU usage and 0% GPU usage. mpv uses around 25% CPU and >80% GPU (0% without `macos-force-dedicated-gpu`). I don't think comparing numbers is the best way to measure performance but I just wanted to leave these here in case someone notices something off about them.

Thanks in advance! This is the last roadblock for me to fully switch over to mpv, as I love pretty much all its other features.

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/5553309/mpv.log)

**Comment by Akemi** [comment] 2020-11-17 13:35
is this maybe related to #8273? for testing try with mpv 0.30, please.

**Comment by jasonhan-vassar** [comment] 2020-11-17 14:17
Just tried with 0.30 and 0.29 and it doesn't seem to be any better. Do those builds have the `macos-force-dedicated-gpu` or `cocoa-force-dedicated-gpu` option? I want to test those with the dedicated GPU to see if performance is as smooth as 0.32 with it.

**Comment by Akemi** [comment] 2020-11-17 16:23
only for the old deprecated backend. the option for the new backend is too new.

on a side note, since i don't know how quicktime does rendering but it's possible that it's faster because their rendering is optimised for macOS.

for testing you can try `--no-config` and the old backend with `--vo=gpu` and see if anything changes.

**Comment by jasonhan-vassar** [comment] 2020-11-17 16:58
`vo=gpu` doesn't seem to make a difference on either 0.29, 0.30, or 0.32. Have you experienced this slowness on macOS yourself?

**Comment by Akemi** [comment] 2020-11-17 18:09
i don't experience anything or at least can't really tell, since i only have a hackintosh with a dedicated beefy GPU (vega56).

iina and the new cocoa-cb backend use basically the same mechanism to render.

**Comment by topcat001** [comment] 2020-11-23 10:40
I wanted to just chime in here. Although I don't have a performance issue on my Macbook Pro 16" running macos 10.15.7, playing the same H.264 video using mpv, IINA, VLC, and Quicktime Player (all default settings, and latest versions, including mpv = 0.32.0) I see the following CPU and GPU usage:

mpv: 18% CPU, 10% GPU
IINA: Identical to mpv
VLC: 10% CPU, 5% GPU - VLC is consistently half of mpv in terms of resource usage.
Quicktime Player: 4-5% CPU 0% GPU - This is also consistently half of VLC's CPU usage, and I cannot get a measurable GPU usage.

I am able to reproduce the relative performance trend with other videos as well. QT player is much lower in terms of resource usage when it can play the video format. I understand there is some macos specific optimisation happening there which is very interesting.

However, it would be awesome if I can get mpv to match VLC in this case. Apologies if this is a bit off topic.

**Comment by Akemi** [comment] 2020-11-23 17:23
i am not sure what VLC uses, but if it isn't a CAOpenGLLayer it would explain a big chunk of this if not all. also at least quicktime will use hwdec, if possible.

**Comment by Akemi** [comment] 2020-11-23 17:27
also since you say iina is basically identically, that's kinda different from the OP.

**Comment by topcat001** [comment] 2020-11-23 18:48
I used the Intel integrated GPU UHD 630 for all these tests. The dedicated GPU was off. I'll check with mpv 0.30 which I don't have installed at the moment. My version 0.32 comes from Homebrew.

**Comment by Akemi** [comment] 2021-01-15 14:56
i will close this in favour of the #8461 issue, since this was only opened as a question.

**Closed by Akemi** 2021-01-15 14:56 UTC
Labels: meta:question

**Comment by Akemi** [comment] 2021-01-24 13:32
it would be nice to know if one of your issues is related to #8477, where updating the touch bar too often or updating it when invisible caused the performance regression. 

this can be tested with `--disable-macos-touchbar` when building mpv yourself.

**Comment by jasonhan-vassar** [comment] 2021-01-28 22:54
sure, I'll get to testing when I have the time @Akemi

**Comment by lonelykid** [comment] 2021-03-09 03:09
mpv always has a performance issue on my mac(iGPU). I barely use it even though I want to use an open source and command line based video player. As others commented, it consistently uses more cpu and gpu than alternatives. it might be ok for others with a newer mac. But for old macs(like my 2015 model) it's unusable.
In my case, playing a 1080p 30fps H264 video from youtube, mpv 30% cpu, 10% gpu; movist pro 10% cpu, no gpu. The backend are both ffmpeg.
