### ISSUE TITLE
double clicking on mpv window in wayland errors out.

### ISSUE THREAD

**Issue by LongChair** [mpv-player/mpv#5230] opened 2017-12-13 20:42 UTC
### mpv version and platform

mpv Github master @522bfe5be1212f356acbbd7d566092f8bd8d0748

### Reproduction steps

start mpv with ` mpv -v --alpha=yes --vo=gpu --gpu-api=opengl --no-audio --gpu-context=wayland <file>` in a weston environment. Video will start.
Now double click on the window

### Expected behavior
Window should maximize

### Actual behavior

mpv will error out and stop playback : got the following log : 
```[statusline] V: 00:00:04 / 01:19:24 (0%) Cache: 120s+73MB
[cplayer] Run command: cycle, flags=9, args=[fullscreen, (NULL)]
[vo/gpu] Resize: 1920x1080
[vo/gpu] Window size: 1920x1080
[vo/gpu] Video source: 1920x1080 (1:1)
[vo/gpu] Video display: (0, 0) 1920x1080 -> (0, 0) 1920x1080
[vo/gpu] Video scale: 1.000000/1.000000
[vo/gpu] OSD borders: l=0 t=0 r=0 b=0
[vo/gpu] Video borders: l=0 t=0 r=0 b=0
[vo/gpu] Reported display depth: 8
[cplayer] Set property: fullscreen -> 1
[vo/gpu/wayland] Resizing due to xdg from 1920x1080 to 3840x2160
[vo/gpu/wayland] Handling resize on the egl side
[vo/gpu] Resize: 3840x2160
[vo/gpu] Window size: 3840x2160
[vo/gpu] Video source: 1920x1080 (1:1)
[vo/gpu] Video display: (0, 0) 1920x1080 -> (0, 0) 3840x2160
[vo/gpu] Video scale: 2.000000/2.000000
[vo/gpu] OSD borders: l=0 t=0 r=0 b=0
[vo/gpu] Video borders: l=0 t=0 r=0 b=0
[vo/gpu] Reported display depth: 8
[vo/gpu/wayland] Error occurred on the display fd, closing
[cplayer] Run command: quit, flags=9, args=[0]
[cplayer] EOF code: 6  
[vo/gpu] Resize: 3840x2160
[vo/gpu] Window size: 3840x2160
[vo/gpu] Video source: 1920x1080 (1:1)
[vo/gpu] Video display: (0, 0) 1920x1080 -> (0, 0) 3840x2160
[vo/gpu] Video scale: 2.000000/2.000000
[vo/gpu] OSD borders: l=0 t=0 r=0 b=0
[vo/gpu] Video borders: l=0 t=0 r=0 b=0
[vo/gpu] Reported display depth: 8
[vd] Uninit video.
[cache] Terminating cache...
[cache] Cache exiting...
[cplayer] finished playback, success (reason 3)
[cplayer] 
[cplayer] 
[cplayer] Exiting... (Quit)
``

### Log file

https://pastebin.com/NJPtJuri

### Sample files

Any file should allow reproducing it :)

**Comment by Dudemanguy911** [comment] 2019-09-21 18:23
Can't reproduce. Probably fixed by something since this is so old. Someone can reopen this if they can reproduce on current master.

**Closed by Dudemanguy911** 2019-09-21 18:23 UTC
Labels: vo:gpu:opengl, vo:gpu:wayland
