### ISSUE TITLE
display-sync performance

### ISSUE THREAD

**Issue by Argon-** [mpv-player/mpv#2217] opened 2015-08-12 14:21 UTC
While it works just fine on my desktop it's dropping frames on my laptop (Intel Iris 6100).
I would've assumed the hardware is just too bad but people on IRC mentioned it should be better, therefore I'm reporting it (more like asking) to know for sure.
I was told when interpolation and real 60 fps videos work without frame drops then display-sync should too -- but it doesn't.

My laptop's display has 59.971589 fps, as detected by mpv. All following cases except the last one are with default video-sync (audio). 

Breakdown:
- real 60fps video with `opengl-hq:scaler-resizes-only` unscaled: no frame drops.
- real 60fps video with `opengl-hq:scaler-resizes-only` scaled to 2880x1800: drops a lot of frames when the OSD is visible (OSD progress bar) but basically no drop when I'm simply watching it.
- 24/1.001 video with `opengl-hq:scaler-resizes-only:interpolation` scaled to 2880x1800: occasionally drops 1-2 frames while I keep pressing a key printing text to the OSD, absolutely no drops when I'm just watching it (I confirmed the interpolation is indeed active).
- 24/1.001 video with `opengl:scaler-resizes-only` & `video-sync=display-resample` unscaled: drops constantly frames (log: https://gist.github.com/Argon-/3651ca1d75f2e83c7b61). Of course it gets worse when using `opengl-hq` and/or scaling. While the progress bar is visible it essentially turns into a slideshow (not included in the log).

Is this to be expected or unusual?

**Comment by wm4** [comment] 2015-08-12 20:07
Actually I'd expect interpolation and display sync with interpolation to have similar performance. The amount of work done should be the same.

From your log I'd just guess your GPU is slightly too slow for the workload.

**Comment by wiiaboo** [comment] 2015-08-12 21:08
I can confirm lots of VO dropped frames while showing something like stats.lua and I have a mid-high end GPU (AMD HD 7870). It's just while keeping the button pressed to show stats.lua or with OSC showing, not if I just press once.

**Comment by wm4** [comment] 2015-08-12 21:15
stats.lua puts a high load on libass, so rendering might take "too long". But the same problem should happen with interpolation. On the other hand, the frontend doesn't really care about the extra frames for interpolation, and doesn't additionally drop frames or adjust audio sync.

Though I would expect that interpolation actually drops frames (even if it's not displayed on the framedrop counter), which _should_ be visible if interpolation really does something.

**Comment by wm4** [comment] 2015-08-12 21:31
Also, please dump your GPU sepcs and driver versions. It's possible that mpv estimates the video position incorrectly, and then ruins sync by adjusting audio position etc. Bad/unexpected driver behavior can become more apparent.

**Comment by wm4** [comment] 2015-08-12 21:35
Also, try the display-resample-vdrop mode. It can actually be more robust against VO jitter.

**Comment by Argon-** [comment] 2015-08-12 21:57
>Though I would expect that interpolation actually drops frames (even if it's not displayed on the framedrop counter), which should be visible if interpolation really does something.

Is it somehow possible to verify this, maybe a higher log level?

>From your log I'd just guess your GPU is slightly too slow for the workload.

Could the workload be a little bit different? I'd assume a RAM-using iGPU has a worse bandwidth/texture fill rate than a GPU with dedicated memory and maybe display-sync has a higher bandwidth requirement?

>Also, please dump your GPU sepcs and driver versions. It's possible that mpv estimates the video position incorrectly, and then ruins sync by adjusting audio position etc. Bad/unexpected driver behavior can become more apparent.

Uh, that's OSX we're talking about. I'm not sure where to get any driver information, except OpenGL is at version 4.1 (Intel 10.6.31). It's about this [CPU and iGPU](http://ark.intel.com/products/84988/Intel-Core-i5-5287U-Processor-3M-Cache-up-to-3_30-GHz).

>Also, try the display-resample-vdrop mode. It can actually be more robust against VO jitter.

Looks a little bit better from the numbers. Around the same number of missed frames but less VO-dropped ones (for the same scene I used for the tests in my first post).

**Comment by Akemi** [comment] 2017-02-16 22:01
i wonder if this still happens since a lot of things have changed since it was initially reported?

**Comment by Argon-** [comment] 2017-02-21 19:27
I'll try to test this again this week. I can't give anecdotal information about how this changed over time because I usually don't use display-sync. Well, actually, since I have a desktop computer again I'm kinda starting to.

Reading this issue now makes me wonder if the (now fixed) general problems of display-sync on OSX might've been the culprit.

**Comment by Akemi** [comment] 2017-04-30 17:54
i don't know if you had time to test it again but PR #4391 changes quite a bit an potentially fixes this among a lot of other issues. feel free to test otherwise i will most likely close this issue when the PR gets merged.

**Comment by Argon-** [comment] 2017-04-30 18:52
I'm afraid I have not. These days I'm only using my laptop at work. However, feel free to close it, I'll just reopen in case I still experience this problem later on.

**Comment by Argon-** [comment] 2017-05-13 10:52
Actually, there's no way I can test this anymore as interpolation is no longer possible without display-sync. Additionally, I don't remember the original file I tested it with so I can't tell if display-sync get better (in terms of dropped frames) or if the file is just "easier" on my computer.

**Comment by Akemi** [comment] 2018-02-12 12:55
fixed via c5e4538bc4b63f02bf89f62aa25a37b9eb0c0316.

**Closed by Akemi** 2018-02-12 12:55 UTC
Labels: osx
