### ISSUE TITLE
Subtitles display outside of video frame.

### ISSUE THREAD

**Issue by iamevn** [mpv-player/mpv#1934] opened 2015-05-15 08:27 UTC
Parts of the subtitles display in the black bars that mpv adds when you resize to an aspect ratio different from the video's aspect ratio. Without a \clip tag on the line it displays as expected but if the \clip goes outside of the video's frame then this happens:
mpv: [1](http://puu.sh/hNXqx/7a56148977.jpg) [2](http://puu.sh/hNXqH/7f00227958.jpg)
expected: [1](http://puu.sh/hNXrI/51807ac2f7.png) [2](http://puu.sh/hNXsa/97a1a1d669.png)
[test.mkv](http://puu.sh/hNXBL/b04779258e.mkv) - just 5 seconds of blue at 720x200
[test.ass](http://puu.sh/hNXDC/d6192a6a90.ass) - ` {\an5\frz45\p1\clip(-80,-100,800,300)}m 0 0 l 600 0 600 600 0 600`

I can't reproduce this on my linux machine, mpv displays it as expected there. On my roommate's mac, this issue is present.

**Comment by AirPort** [comment] 2015-05-15 08:52
Os X here, cant' reproduce. It seems to reproduce it properly like in your reference images: http://a.pomf.se/wcfpgc.png

**Comment by wm4** [comment] 2015-05-15 08:59
I'm not seeing it clipped either.

Pretty sure this is a libass issue.

>I can't reproduce this on my linux machine, 

Is it running vo_xv?

**Comment by iamevn** [comment] 2015-05-15 09:25
>Is it running vo_xv?
Yeah, it is. I managed to reproduce this by switching vo to opengl or opengl-hq on linux. No matter which video output I choose on Windows (opengl, direct3d_shaders, direct3d, opengl-hq) I get this behavior.

**Comment by wm4** [comment] 2015-05-15 09:50
That explains it; vo_xv doesn't support rendering anything into the black borders at all.  It doesn't explain @AirPort's observation though.

**Comment by AirPort** [comment] 2015-05-15 09:56
Sorry, my fault: I didn't remeber I specified blend-subtitles in my conf. I made some other test and  without that option the problem is showing here too.

**Comment by wm4** [comment] 2015-05-16 19:32
I made a libass bug report (see above).

**Comment by wm4** [comment] 2015-05-16 19:32
And further discussion should go there too. Closing.

**Closed by wm4** 2015-05-16 19:32 UTC
Labels: not our bug
