### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Bilalh** [mpv-player/mpv#4219] opened 2017-03-10 23:59 UTC
I got a Segmentation fault when running mpv.  I even not sure this mpv fault, but here is the OS X crash log.

Log: http://sprunge.us/JZjg

command used `mpv --shuffle --geometry=480x270+0%+0% --loop=inf  --quiet --af=volume=-0.8 a.webm`

### mpv version and platform

```
OS X 10.11.6 (15G1217) on a MacBook Pro (Retina, Mid 2012)

mpv git-076116a (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Fri Mar 10 17:31:43 GMT 2017
ffmpeg library versions:
   libavutil       55.34.101
   libavcodec      57.64.101
   libavformat     57.56.101
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.4
```

### Reproduction steps
Not able to, but happened more then once

### Expected behaviour
Not crashing 

### Actual behaviour
Segmentation fault

**Comment by Akemi** [comment] 2017-03-11 00:12
does it segfault on start or while it is playing? any other options you use or does it also happen with `--no-config` and the options mentioned above?

**Comment by Bilalh** [comment] 2017-03-11 00:17
I can't reproduce it, but when it happens, it near the end of the video (but never after the video is finish playing).  It does seem to happen more often when looping a video.
 
It never happen when I tried --no-config

**Comment by Akemi** [comment] 2017-03-11 00:31
if it doesn't happen with `--no-config` and the options mentioned in your initial posts that would mean it is caused by one of the options in your config and not by the ones mentioned.

the segfault happens in a part of the code that is only executed when the window/video size is changed. if your example file doesn't change the resolution in-between the stream a resize should never happen while playing a video. or are you interacting with the player in some way?

**Comment by Bilalh** [comment] 2017-03-11 00:36
To be more specific I can't  determinedly reproduce it even with original
options I used, it happens randomly infrequently.  The only  interaction
that I did were either pausing the video or switching subtitle track
(loaded from external files).

**Comment by Bilalh** [comment] 2017-03-13 02:27
Also happens in `mpv 0.24.0`

**Comment by Akemi** [comment] 2018-10-02 18:59
closing this since it's a crash in the old deprecated backend.

**Closed by Akemi** 2018-10-02 18:59 UTC
Labels: info-needed, osx
