### ISSUE TITLE
Choppy playback when watching VP9 videos

### ISSUE THREAD

**Issue by james-jpeg** [mpv-player/mpv#8477] opened 2021-01-17 13:34 UTC
### Important Information

Provide following Information:
- mpv version: `a3e440c`
- macOS Version: `10.15.4 Catalina`
- Source of the mpv binary or bundle: `homebrew with --head flag`

### Reproduction steps

Play the video with `--no-config`

### Expected behavior
Video plays smoothly. The video plays fine when using `ffplay` or watching in either chrome or firefox. 

### Actual behavior
Video is choppy and dropping frames. 

### Log file

https://0x0.st/-iXh.txt

### Sample files

https://www.youtube.com/watch/mktAk4_MoDc

You can get the file with youtube-dl. 

The version I downloaded was:
`308          webm       2560x1440  1440p60 13345k , vp9, 60fps, video only, 770.95MiB`

I think this might be related to #8461

**Comment by james-jpeg** [comment] 2021-01-17 13:41
Sorry I just realised that might be too much for you to download. 

Here's a small sample of the file:

https://0x0.st/-i8z.mkv

**Comment by Akemi** [comment] 2021-01-17 14:07
then for now try all the things suggested in the outer issue (#8461) for now.

**Comment by james-jpeg** [comment] 2021-01-17 14:22
I tried  `--no-config --macos-force-dedicated-gpu --video-sync=display-resample`

It helps with the choppiness but then the video looks like it's being played in slow motion

**Comment by Akemi** [comment] 2021-01-17 14:43
in you initial log it already used you dedicated GPU (AMD Radeon R9 M370X), so `--macos-force-dedicated-gpu` shouldn't make a difference. does using `--video-sync=display-resample` only already exhibit that problem? also please log file of that slow motion case too.

**Comment by james-jpeg** [comment] 2021-01-17 16:14
> does using --video-sync=display-resample only already exhibit that problem? 

Are you referring to the slow motion? If so then yes, the slow motion only happens when video-sync is enabled. 

Slow motion log file: 

https://0x0.st/-iKe.txt

Am I correct in assuming this issue when playing VP9 videos doesn't happen for you?

**Comment by Akemi** [comment] 2021-01-17 19:11
yeah, that's what i meant. does the same slow motion effect appear with `mpv --no-config --vo=gpu --video-sync=display-resample`? 

yes, you are correct. i have no problems with the provided sample.

does this happen with videos in other formats and similar high resolutions? does `--opengl-pbo` help in any way?

also i would appreciate log files made with `--log-file=PATH` instead of `-v -v`, because i get some timing information with that.

**Comment by james-jpeg** [comment] 2021-01-17 22:19
> mpv --no-config --vo=gpu --video-sync=display-resample

Using this results in perfect playback for the original file downloaded with youtube-dl, however strangely this causes choppy playback for the sample file and files in other formats.

Original video log (perfect): https://0x0.st/-iNS.txt
Sample video log (choppy): https://0x0.st/-iNe.txt

> does this happen with videos in other formats and similar high resolutions?

Yes it happens in other video formats with similar resolutions. Like the other video these videos play smoothly in `ffplay`. 
I tried these videos with `--no-config --vo=gpu --video-sync=display-resample` but that results in choppy playback too. 

https://0x0.st/-iNv.txt

with `--no-config --video-sync=display-resample`:
https://0x0.st/-iNy.txt

> --opengl-pbo

This doesn't appear to make much of difference. Results in choppy video when used by itself or slow motion video when used with `--video-sync=display-resample`

> also i would appreciate log files made with --log-file=PATH instead of -v -v, because i get some timing information with that.

Sorry about that I thought they were interchangeable.

**Comment by Akemi** [comment] 2021-01-18 01:41
okay, the `vo=gpu` was just a test to possibly narrow the issue down. though for now you can forget it (it's rather broken and might result in weird behaviour).

the logs for the second file also report a video fps of 29.980013fps. different from the initial ~60fps video. in that case the `video-sync=display-resample` isn't so much necessary.

also is the playback just choppy or does mpv also report dropped frames? what does mpv report for the estimated display fps in the stats?

i would like to narrow down the reason of the slow motion problem, since this might be the source of the choppy playback. could you apply following patch and rebuild mpv. this adds a debug output on the normal console and i am interested what it outputs after a few seconds of playback, with  `--video-sync=display-resample` and without.

```
diff --git a/video/out/cocoa_cb_common.swift b/video/out/cocoa_cb_common.swift
index 8dd76f4bc5..07f8a50d2d 100644
--- a/video/out/cocoa_cb_common.swift
+++ b/video/out/cocoa_cb_common.swift
@@ -21,6 +21,8 @@ class CocoaCB: Common {
     var libmpv: LibmpvHelper
     var layer: GLLayer?
 
+    var lastTime: Double = 0
+
     @objc var isShuttingDown: Bool = false
 
     enum State {
@@ -106,6 +108,14 @@ class CocoaCB: Common {
                                           _ flagsIn: CVOptionFlags,
                                          _ flagsOut: UnsafeMutablePointer<CVOptionFlags>) -> CVReturn
     {
+        var timebase: mach_timebase_info = mach_timebase_info()
+        mach_timebase_info(&timebase)
+        var timebaseRatio = (Double(timebase.numer) / Double(timebase.denom)) / CVGetHostClockFrequency()
+        let currentTime = Double(mach_absolute_time())*timebaseRatio
+
+        print("\(currentTime-lastTime)")
+        lastTime = currentTime
+
         libmpv.reportRenderFlip()
         return kCVReturnSuccess
     }
```

**Comment by james-jpeg** [comment] 2021-01-18 12:19
I think I found the issue.

I accidentally added `--disable-macos-touchbar` to the build options and this resulted in perfectly smooth playback. 

Sure enough when I removed that option the choppy playback returned.  

Would you still like me to add any log files?

**Comment by Akemi** [comment] 2021-01-18 14:09
no, no log necessary.

so if is indeed what was mentioned here in the second section where i said it's most likely not the problem (https://github.com/mpv-player/mpv/issues/8461#issuecomment-761822786).

this is hilarious dumb, if the cause is really that NSLayoutConstraint warning, since i didn't find a way to fix it and it's most likely an Apple bug...

if you don't mind testing. does just removing the slider in the touch bar fix this problem too? does removing these lines (https://github.com/mpv-player/mpv/blob/master/osdep/macosx_touchbar.m#L32-L36) fix the problem?

**Comment by james-jpeg** [comment] 2021-01-18 15:22
Yeah commenting out those lines also fixes the problem.

**Comment by Akemi** [comment] 2021-01-18 21:55
thanks, then we have to fix that slider, implement our own scrubber or remove it entirely.

**Comment by james-jpeg** [comment] 2021-01-19 12:01
Ah okay, so should I close this issue now?

Thanks for the help.

**Comment by Akemi** [comment] 2021-01-19 13:12
no, leave it open please.

**Comment by Akemi** [comment] 2021-01-19 18:42
does #8486 fix this issue too and does the touch bar slider/seekbar still work properly for you?

**Comment by james-jpeg** [comment] 2021-01-19 22:11
No that doesn't fix it for me. Also I don't have a touchbar. 

I just saw that waf thought I had touch bar support, should it be doing that?

**Comment by Akemi** [comment] 2021-01-19 23:13
waf doesn't check for the physical availability of the touch bar, it just checks if the SDK supports touch bar APIs. so yeah, that's correct.

so the problem is at least not related to the constraints warning, that was fixed with that PR. though it's still related to the slider itself.

just to make sure, removing the lines from my comment (https://github.com/mpv-player/mpv/issues/8477#issuecomment-762274111) really fixed it? you didn't accidentally still had `--disable-macos-touchbar` in your configure?

does it help removing these lines https://github.com/mpv-player/mpv/blob/master/osdep/macosx_events.m#L155-L157?
does it help removing these lines https://github.com/mpv-player/mpv/blob/master/osdep/macosx_touchbar.m#L110-L127?
does it help removing these lines https://github.com/mpv-player/mpv/blob/master/osdep/macosx_touchbar.m#L134-L141?

sry to ask you to test so much.

**Comment by james-jpeg** [comment] 2021-01-20 00:00
> just to make sure, removing the lines from my comment (#8477 (comment)) really fixed it? you didn't accidentally still had --disable-macos-touchbar in your configure?

Yeah I just tried again, it really fixed it. 

Here's the log file:
https://0x0.st/-ipG.txt

`--disable-macos-touchbar` is not there. 

Commenting out only those lines fixed the issue every time. 

> sry to ask you to test so much.

No worries

**Comment by james-jpeg** [comment] 2021-01-20 10:45
> is it also fixed if you only remove this one line (observing the "time-pos" property) https://github.com/mpv-player/mpv/blob/master/osdep/macosx_events.m#L156?

> for a working build if you use --video-sync=display-resample, is the slow motion effect also gone?

Yes to both.

> for a broken build (with the slow motion effect) if you use --video-sync=display-resample, what does the estimated Display FPS report?
![display-fps](https://user-images.githubusercontent.com/18496844/105163803-47f66f80-5b0c-11eb-9380-a3ea336e7b44.png)

**Comment by Akemi** [comment] 2021-01-20 14:48
thank you very much. i think i found the problem. for now my assumption is that we update the touch bar (or rather the slider) too frequently and updating a slider has a big performance impact (hopefully it isn't a mpv core problem like my previous assumption). the time "time-pos" property is updated very frequently, several times per second, and it scales with the fps of the video.

on a side note if you were wondering. even if there is no physical touch bar, it is still there in software and the touch bar items are allocated. one can test this with xcode for example. open it and click on Window > Show Touch bar in the menu bar, it will show a virtual one. Apple also doesn't provide an api to check for the existence of a touch bar so that's is how it should be done, from the docs:

```
There is no need, and no API, for your app to know whether or not there is a Touch Bar available. Whether your app is running on a machine that supports the Touch Bar or not,...
```

i updated my PR #8486 with a test, to only update the touch bar when necessary. would mind testing it, hopefully a last time, please? if this test is successful i will try to also add a check to update the items only if they are actually visible.

**Comment by james-jpeg** [comment] 2021-01-20 15:11
Hurrah! 

It worked.

**Comment by Akemi** [comment] 2021-01-20 15:27
that's great. i will try to finalise everything soonish.

**Comment by james-jpeg** [comment] 2021-01-20 17:01
I think I may have spoken too soon. 

It's definitely an improvement however I noticed it's not perfect. As time goes on the playback gradually gets worse. 

I watched the video through to the same time on both builds, I noticed a few hiccups and it has more delayed. 

Your updated PR: 

![1](https://user-images.githubusercontent.com/18496844/105208200-5199ca80-5b40-11eb-85d9-45cd464eea28.png)

With `--disable-macos-touchbar`:

![2](https://user-images.githubusercontent.com/18496844/105208264-6a09e500-5b40-11eb-8686-ce129a736c26.png)

**Comment by Akemi** [comment] 2021-01-21 16:34
do you mean with 'gradually worse' that it's just accumulating more delayed frames (but the rate stays the same) or do you actually mean that delayed frames and hiccups get more for the same time interval (the rate of those errors get worse)?

i am still working on my changes to only update the touch bar items when they are or the actual touch bar visible. that should also fix the rest of the problem, hopefully. i am wondering if this is just a problem because you don't have a touch bar and we try to update it, or because it's hidden and if an actual touch bar was visible that those problems would be gone. you could possibly try with xcode and the virtual touch bar i mentioned earlier.

**Comment by james-jpeg** [comment] 2021-01-21 21:37
It plays perfectly now. All I did since the last time I checked was restart my computer and try the virtual touch bar. It plays fine even when I don't have the virtual touch bar open. I'm not sure if the issue last time was a fluke or if there really is a problem. 

FWIW, It seemed like the rate of the errors was getting worse. Like after one error showed up, a whole bunch of them showed up shortly after. But it took like 3 mins for the first error to show up, and I observed this twice.

**Comment by Akemi** [comment] 2021-01-22 14:49
this is weird indeed. i suspect something is wrong with the touch bar API itself that Apple has to properly fix.

anyway, i updated the PR now. it will only update the touch bar items now if the touch bar and the affected touch bar item is visible. so it should not affect your case (no touch bar) at all anymore.

let me know if everything still works as wanted, even if the problem is gone entirely now.

**Comment by james-jpeg** [comment] 2021-01-23 20:08
I just tried it, works great. 

Thanks for looking into this Akemi. I really appreciate it.

**Closed** 2021-02-13 14:51 UTC
Labels: os:mac
