### ISSUE TITLE
match decomposed/precomposed unicode strings with sub-auto=fuzzy

### ISSUE THREAD

**Issue by ParadiseDS** [mpv-player/mpv#4016] opened 2017-01-10 23:20 UTC
### mpv version and platform

macOS 10.12.2
mpv 0.23.0

### Reproduction steps

1. Set `sub-auto=fuzzy` in mpv.conf.

2. rename a video with the filename`[ぐ.mkv` and rename the corresponding subtitle file with `[ぐ.ass`. Both files are in the same directory.

3. open the `[ぐ.mkv` with terminal command `mpv \[ぐ.mkv`

### Expected behavior

Since the `sub-auto=fuzzy` is set, subtitle file with filename same to the video file should be loaded automatically when the video is opened.

### Actual behavior

mpv doesn't load the subtitle file automatically. ~~What is stranger, filename with single `ぐ` or single `[` doesn't trigger the problem. The bug occurs with `[` and `ぐ` both be present in the filename. ~~
**Update**
The `ぐ` character is to blame as far as I tested.

**Update**:
If mpv is defined as the default player and thus launched by double click the file in Finder, the subtitle file can be loaded normally. The bug only occurs under terminal launch.

### Log file

http://sprunge.us/WVGI

**Comment by wiiaboo** [comment] 2017-01-10 23:55
Must be some macOS-only bug, works fine in Windows.

**Comment by ParadiseDS** [comment] 2017-01-11 00:11
> Must be some macOS-only bug, works fine in Windows.

Do you try to open the video via terminal (maybe cmd in windows? I didn't try mpv in windows..)
I just found the problem was only triggered via terminal launch. Open the file in Finder is fine.

**Comment by Akemi** [comment] 2017-01-11 01:38
i can't reproduce this. it works via terminal and the bundle here. can you reproduce it with `--no-config --sub-auto=fuzzy`?

**Comment by wm4** [comment] 2017-01-11 04:32
Could be a unicode normalization issue, where the same filename can have multiple representations.

**Comment by ParadiseDS** [comment] 2017-01-11 08:51
Yes I can reproduce the problem with the options you mentioned. The log file is on http://sprunge.us/cNGI <http://sprunge.us/cNGI>
And by renaming the files to `[.mkv` and `[.ass` the problem is solved.

I just found `ぐ.mkv`+ `ぐ.ass` pair was broken as well, and so is any filename contains 'ぐ’. Filename containing some other Hiraganas seems to work well. 
(I remember it worked last night..maybe I opened the file via Finder by mistake?)

And my locale settings is as following, thought they may be related.

```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8”
```

**Comment by wm4** [comment] 2017-01-11 08:55
That's U+3050 HIRAGANA LETTER GU, which according to gucharmap is U+304F HIRAGANA LETTER KU + U+3099 COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK.

So it is a normalization issue, where OSX not only uses non-standard normalization, but also is inconsistent about which form it uses.

Likely a WONTFIX.

**Comment by ParadiseDS** [comment] 2017-01-11 09:11
> So it is a normalization issue, where OSX not only uses non-standard normalization, but also is inconsistent about which form it uses.
> 
> Likely a WONTFIX.

Sorry to hear that. 
Is there any work around for this issue? As launching mpv via bundle just works while iTerm2.app and terminal.app fail, can the terminal applications behave as Finder do?

**Comment by Akemi** [comment] 2017-01-11 12:19
i tested with the same mpv version and set the same locale as you. i am also on the same macOS version, and it still works here. i wonder what else could be different on your system.

**Comment by ParadiseDS** [comment] 2017-01-11 12:49
Here I asked one of my colleagues to test and he could exactly reproduce my problem, on the same macOS version.
I don't know if other system preference settings like area or lauguage matters. The prior language in `System Preferences > Language & Region` we choose here is Simplified Chinese.
 
From: Akemi
Date: 2017-01-11 20:20
To: mpv-player/mpv
CC: 小叶子; Author
Subject: Re: [mpv-player/mpv] mpv failed to load subtitle file with specific character pair in filename (#4016)
i tested with the same mpv version and set the same locale as you. i am also on the same macOS version, and it still works here. i wonder what else could be different on your system.

**Comment by Akemi** [comment] 2017-01-11 13:59
tested with that too and still works. here a [log](http://sprunge.us/BSXd). the only things i really noticed, when comparing the logs, is:
1. your libass is build with **harfbuzz**, which shouldn't make a difference
2. my mpv is build with **uchardet**, which might make the difference here

maybe give it a try and build mpv with uchardet. if you can't, try [this build](https://dl.dropboxusercontent.com/u/68772824/mpv.zip). if you want to start it from the terminal, right click the bundle and click "Show package Contents", navigate to Contents > MacOS and drag an drop the "mpv" binary into your terminal. in the terminal there should be the path to the binary now and just test it with --no-config and your options again.

**Comment by wiiaboo** [comment] 2017-01-11 14:01
I don't think uchardet works on filenames, just on subtitle data. @wm4?

**Comment by wm4** [comment] 2017-01-11 15:53
@wiiaboo that's correct.

**Comment by wm4** [comment] 2017-01-11 15:56
Since the video is opened via `mpv \[ぐ.mkv`, this probably happens if the terminal provides the string in a different normalization form than what the filesystem API (`opendir()` etc.) returns.

So it could depend on the terminal, or how you enter the string on the terminal.

**Comment by ParadiseDS** [comment] 2017-01-11 17:04
I tried both of the methods, rebuilding mpv with uchardet and using the build you provide in the link, and launched mpv with —no-config —sub-auto=fuzzy. However mpv still cannot load the subtitle automatically with ぐ in the filename.

**Comment by ParadiseDS** [comment] 2017-01-11 17:43
> So it could depend on the terminal, or how you enter the string on the terminal.

Inspired by your words I found something interesting. Just record what the filename looks like in terminal's perspective.

```
ls | grep mkv > unicode.txt
echo '[ぐ.mkv' > unicode2.txt
```

The content of unicode.txt is different from the text I typed to unicode2.txt.

the hex view of the two file is as following

```
// unicode.txt
00000000:  e381 8fe3 8299 2e6d 6b76 0a                                  :.......mkv.
//unicode2.txt
00000000:  e381 902e 6d6b 760a                                          :....mkv.
```

So it seems that terminal treats the filename in a different way as we thought.

**Comment by wiiaboo** [comment] 2017-01-11 19:09
One's just ぐ, the other's く and  ゙ . So, a normalization issue, like wm4 said at the start.

**Comment by ParadiseDS** [comment] 2017-01-12 05:46
> One's just ぐ, the other's く and ゙ . So, a normalization issue, like wm4 said at the start.

Yes I think that's the point so mpv seems to be innocent from this bug. Thanks for all you guys.

But as @Akemi said with the same locale setting and macOS version he couldn't reproduce the problem. So some other system settings / terminal settings may be related, which can affected the normalization. AFAIK all char encoding settings in my terminal is UTF-8, and I've tested with terminal and iTerm2 with their default settings. I wonder this is an issue for macOS for specific language or some settings I've changed accidentally.

**Comment by wm4** [comment] 2017-01-12 06:33
Both forms are UTF-8. Once you decode the UTF-8, they will still be in different normalization forms. It depends on you terminal in which form it'll be once you enter text. The filesystem/OS probably forces normalization on filenames stored on disk.

**Comment by Akemi** [comment] 2017-01-12 14:36
i am wondering if one of the suggestions [here](http://stackoverflow.com/questions/4606570/os-x-terminal-utf-8-issues) fixes it for you? especially the suggestion with:
```
set meta-flag on
set input-meta on
set output-meta on
set convert-meta off
```

anyway looked into it a bit more and there seems to be a 'proper' [fix](http://git.661346.n2.nabble.com/Git-Mac-OS-X-and-German-special-characters-tt6850556.html#a6851606) by [wrapping some filesystem](https://github.com/git/git/commit/76759c7dff53e8c84e975b88cb8245587c14c7ba) functions and do a NFD to NFC conversion. this is quite a lot of boilerplate because Apple made a bad design decision once.

some further information [here](https://www.j3e.de/linux/convmv/man/) under Description > Filesystem issues > HFS+ on OS X / Darwin

> Linux and (most?) other Unix-like operating systems use the so called normalization form C (NFC) for its UTF-8 encoding by default but do not enforce this. Darwin, the base of the Macintosh OS enforces normalization form D (NFD), where a few characters are encoded in a different way. On OS X it's not possible to create NFC UTF-8 filenames because this is prevented at filesystem layer. On HFS+ filenames are internally stored in UTF-16 and when converted back to UTF-8, for the underlying BSD system to be handable, NFD is created. See http://developer.apple.com/qa/qa2001/qa1173.html for defails. I think it was a very bad idea and breaks many things under OS X which expect a normal POSIX conforming system. Anywhere else convmv is able to convert files from NFC to NFD or vice versa which makes interoperability with such systems a lot easier.

**Comment by qmega** [comment] 2017-01-12 18:24
This is similar to #1027 (the reporter there even predicted this issue). I posted a wrapper script near the end of that issue that might work around this problem too, by converting mpv's command line arguments to the same form the filesystem will return. I don't have a Mac to actually try it, though.

**Comment by ParadiseDS** [comment] 2017-01-13 11:26
> i am wondering if one of the suggestions here fixes it for you

I'm afraid the case is different from the one we are talking about here. It's something corrupted by non UTF-8 encoding. Both NFC and NFD are legal unicode the representation, they just cannot be compatible with each other. And I've tried the suggestions, they didn't work as expected.

I'm curious about why the mpv on your Mac can handle this issue well, as it is a file system level problem and seems not be affected by any system configuration. That's why git has implemented an wrapper to handle this.

**Comment by ParadiseDS** [comment] 2017-01-13 11:38
> I posted a wrapper script near the end of that issue that might work around this problem too, by converting mpv's command line arguments to the same form the filesystem will return

I've tried the wrapper and it works like a charm. Thanks a lot!

**Comment by wm4** [comment] 2017-01-13 11:54
If there's a simple OSX API for converting this, we could as well do it ourselves to fix this specific case. main is already wrapped for weird OSX reasons. (On Windows, main() is also wrapped to get proper unicode command line.)

**Comment by ParadiseDS** [comment] 2017-01-13 13:08
> If there's a simple OSX API for converting this, we could as well do it ourselves to fix this specific case. main is already wrapped for weird OSX reasons. (On Windows, main() is also wrapped to get proper unicode command line.)

It' very nice of you guys.

But I think it should be terminal rather than a specific CLI application which should handle the conversion, or other apps may run into the same issue without enough knowledge about this. I'm not share other project maintainers are as nice as you guys.

I've done a little test to see how terminal apps deal with the filename.

+ terminal.app

  `ls` returns filename encoded with NFD representation
   Autocomplete by tab generate NFC representation char

+ iTerm2.app

  `ls` returns filename encoded with NFC representation
  Autocomplete by tab generate NFC representation char

Both terminal and iTerm2 can pass NFD representation filename as it is to shell, in which case mpv can correctly load the subtitle.

terminal apps should whenever convert unicode string input to NFD representation before pass it to shell, as file with NFC representation filename doesn't actually exists on the disk. It is consistent with how Finder behaves

I'll ask if iTerm2 maintainer would realize this idea, or some better ones. As for terminal, I think Apple would probably overlook it.

**Comment by Akemi** [comment] 2017-01-13 19:31
i pushed a fix to [this branch](https://github.com/Akemi/mpv/commit/b096ed7bfb364baa41353e16f529b6fbbb3b5521). let me know if this works for you.

**Comment by ParadiseDS** [comment] 2017-01-15 07:45
> i pushed a fix to this branch. let me know if this works for you.

Yes the build from this branch works for me like a charm!

**Comment by Akemi** [comment] 2017-01-16 15:58
sry i think this can't be solved properly like this. see my last comment on #4042.

like mentioned, it's probably best to adjust the fuzzy algorithm to search for precomposed and decomposed unicode.

**Comment by ParadiseDS** [comment] 2017-01-16 16:19
> sry i think this can't be solved properly like this. see my last comment on #4042.

I see that. Anyway thanks very much for your effort on this Akemi.
Agree that the best solution seems to be searching both decomposed and precomposed formats of the input filename in the current dir. Modification on the args is always risky.

**Comment by Akemi** [comment] 2017-01-20 13:39
i changed the title a bit since this is more like a feature request now.

**Comment by Akemi** [comment] 2017-01-25 20:12
#4067 another attempt to fix this. hopefully this time without any drawbacks.

**Comment by ParadiseDS** [comment] 2017-01-26 17:15
Thanks for your work Akemi!

**Comment by Akemi** [comment] 2017-01-29 18:55
just wondering, this worked for you as expected?

**Comment by ParadiseDS** [comment] 2017-01-30 02:09
Hello Akemi
I’ve tried building from cocoa_decompose_iconv and the build does fix the problem, loading external subs as expected here.

**Closed** 2017-02-02 15:21 UTC
Labels: feature request
