### ISSUE TITLE
mpv crashed when exitting

### ISSUE THREAD

**Issue by 191919** [mpv-player/mpv#1917] opened 2015-05-05 06:52 UTC
I received the following crash report when I pressed Cmd+Q to quit mpv.

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000

VM Regions Near 0:
--> 
    Kernel Alloc Once      0000000007d8f000-0000000007d90000 [    4K] rw-/rwx SM=PRV  

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_c.dylib             	0x00007fff8501c152 strlen + 18
1   io.mpv                        	0x0000000107dbe4de get_bind_section + 94 (bstr.h:61)
2   io.mpv                        	0x0000000107dbfed5 find_bind_for_key_section + 69 (input.c:369)
3   io.mpv                        	0x0000000107dbfdfa find_any_bind_for_key + 202 (input.c:423)
4   io.mpv                        	0x0000000107dbd699 update_mouse_section + 25 (input.c:484)
5   io.mpv                        	0x0000000107dbd55a mp_input_set_mouse_pos + 378 (input.c:726)
6   io.mpv                        	0x0000000107e233fc -[MpvCocoaAdapter signalMouseMovement:] + 60 (cocoa_common.m:822)
7   io.mpv                        	0x0000000107e20534 -[MpvEventsView signalMousePosition] + 564 (events_view.m:216)
8   com.apple.CoreFoundation      	0x00007fff8a25e45c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
9   com.apple.CoreFoundation      	0x00007fff8a14e634 _CFXNotificationPost + 3140
10  com.apple.Foundation          	0x00007fff82a279d1 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
11  com.apple.AppKit              	0x00007fff87f99086 -[NSWindow resignKeyWindow] + 738
12  com.apple.AppKit              	0x00007fff87fbf901 -[NSWindow _orderOutAndCalcKeyWithCounter:stillVisible:docWindow:] + 371
13  com.apple.AppKit              	0x00007fff87e75bc9 -[NSWindow _reallyDoOrderWindow:relativeTo:findKey:forCounter:force:isModal:] + 3550
14  com.apple.AppKit              	0x00007fff87e74897 -[NSWindow _doOrderWindow:relativeTo:findKey:forCounter:force:isModal:] + 829
15  com.apple.AppKit              	0x00007fff87e744eb -[NSWindow orderWindow:relativeTo:] + 159
16  com.apple.AppKit              	0x00007fff88599db4 __58-[NSView(NSFullScreenMode) exitFullScreenModeWithOptions:]_block_invoke + 227
17  com.apple.AppKit              	0x00007fff87e2aceb NSPerformWithScreenUpdatesDisabled + 65
18  com.apple.AppKit              	0x00007fff88599cb0 -[NSView(NSFullScreenMode) exitFullScreenModeWithOptions:] + 677
19  io.mpv                        	0x0000000107e21e06 __vo_cocoa_uninit_block_invoke + 182 (cocoa_common.m:293)
20  io.mpv                        	0x0000000107e23702 __with_cocoa_lock_on_main_thread_block_invoke + 34 (cocoa_common.m:99)
21  libdispatch.dylib             	0x00007fff8998e323 _dispatch_call_block_and_release + 12
22  libdispatch.dylib             	0x00007fff89989c13 _dispatch_client_callout + 8
23  libdispatch.dylib             	0x00007fff89995cbf _dispatch_main_queue_callback_4CF + 861
24  com.apple.CoreFoundation      	0x00007fff8a1f53f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
25  com.apple.CoreFoundation      	0x00007fff8a1b068f __CFRunLoopRun + 2159
26  com.apple.CoreFoundation      	0x00007fff8a1afbd8 CFRunLoopRunSpecific + 296
27  com.apple.HIToolbox           	0x00007fff823a656f RunCurrentEventLoopInMode + 235
28  com.apple.HIToolbox           	0x00007fff823a62ea ReceiveNextEventCommon + 431
29  com.apple.HIToolbox           	0x00007fff823a612b _BlockUntilNextEventMatchingListInModeWithFilter + 71
30  com.apple.AppKit              	0x00007fff87dcf9bb _DPSNextEvent + 978
31  com.apple.AppKit              	0x00007fff87dcef68 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
32  com.apple.AppKit              	0x00007fff87dc4bf3 -[NSApplication run] + 594
33  io.mpv                        	0x0000000107e3d811 cocoa_main + 833 (macosx_application.m:264)
34  libdyld.dylib                 	0x00007fff874f65c9 start + 1
```

Here is a workaround:

```
diff --git a/input/input.c b/input/input.c
index 2a108be..c792832 100644
--- a/input/input.c
+++ b/input/input.c
@@ -364,6 +364,7 @@ static void key_buf_add(int *buf, int code)
 static struct cmd_bind *find_bind_for_key_section(struct input_ctx *ictx,
                                                   char *section, int code)
 {
+       if (!section) return NULL;
     struct cmd_bind_section *bs = get_bind_section(ictx, bstr0(section));
 
     if (!bs->num_binds)
```

**Comment by rcombs** [comment] 2015-05-05 06:54
Dupe of #1903

**Comment by wm4** [comment] 2015-05-05 07:08
Yep, probably the same one. I'll try to fix it today.

**Comment by wm4** [comment] 2015-05-19 20:23
This is most likely fixed.

**Closed by wm4** 2015-05-19 20:23 UTC
Labels: osx
