### ISSUE TITLE
Mux wrong audio on encode

### ISSUE THREAD

**Issue by kokowang** [mpv-player/mpv#4111] opened 2017-02-04 13:32 UTC
Fairly straight forward, MPV (on mac) will mux the wrong audio if a .wav file happens to be the same name as the input video file and in the same working directory as mpv and the video file. 
To recreate: Make random .wav file
name it test.wav
make random video file with different audio of the same length
name it test.mp4
encode text.mp4 using mpv (mpv test.mp4 -o result.mp4).
result.mp4 will contain video from test.mp4 and audio from test.wav...

**Comment by wiiaboo** [comment] 2017-02-04 13:42
Duplicate of https://github.com/mpv-player/mpv/issues/3777

**Closed by wiiaboo** 2017-02-04 13:42 UTC
