### ISSUE TITLE
most cscale filters works terribly with "hwdec=auto-copy" in rotated videos

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#8572] opened 2021-02-17 13:46 UTC
### Important Information
RTX 2070 super (latest driver)
As is described in the title, but when playing the ratated video, every cscale filter works fine with "hwdec=no".
In my test, only "bilinear/bicubic_fast/oversample" work well both in hwaccel and no-hwaccel situation.

Provide following Information:
- mpv version
mpv-x86_64-20210214-git-93066ff
- Windows Version
20h2
- Source of the mpv binary
https://sourceforge.net/projects/mpv-player-windows/files/64bit/

### Reproduction steps
mpv.conf：--vo=gpu  --gpu-api=d3d11  --hwdec=auto-copy  --video-rotate=90

input.conf: --Ctrl+c cycle-values cscale "bilinear" "bicubic_fast" "oversample" "spline16" "spline36" "spline64" "sinc" "lanczos" "ginseng" "jinc" "ewa_lanczos" "ewa_hanning" "ewa_ginseng" "ewa_lanczossharp" "ewa_lanczossoft" "haasnsoft" "bicubic" "bcspline" "catmull_rom" "mitchell" "robidoux" "robidouxsharp" "ewa_robidoux" "ewa_robidouxsharp" "box" "nearest" "triangle" "gaussian"

To open the video and change the cscale filters.

### Expected behavior
![Snipaste_2021-02-17_21-37-59-ty](https://user-images.githubusercontent.com/41094733/108212446-d9d3b580-7168-11eb-8eb6-aeea9f0d2f90.jpg)

### Actual behavior
![Snipaste_2021-02-17_21-37-47-ty](https://user-images.githubusercontent.com/41094733/108212455-dccea600-7168-11eb-919d-b12b4080d59c.jpg)
![Snipaste_2021-02-17_21-37-31-ty](https://user-images.githubusercontent.com/41094733/108212466-e0622d00-7168-11eb-9193-7105d4025908.jpg)

### Log file
It's easy to reproduce, tell me if necessary I will upload.

**Comment by philipl** [comment] 2021-02-17 15:16
Almost certainly a dupe of #8223

**Closed** 2021-02-17 16:29 UTC
Labels: meta:duplicate, os:win
