### ISSUE TITLE
mpv hangs when resizing with vulkan+nvidia+shaders

### ISSUE THREAD

**Issue by jsravn** [mpv-player/mpv#8382] opened 2020-12-09 10:12 UTC
### Important Information

Provide following Information:
- mpv version: 0.32.0
- Linux Distribution and Version: Nixos 20.09
- Source of the mpv binary
- If known which version of mpv introduced the problem
- Window Manager and version: Gnome 3
- GPU driver and version: nvidia 455.38
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

```sh
mpv --no-config --gpu-api=vulkan --dither-depth=auto --dither=error-diffusion --error-diffusion=sierra-lite --log-file=mpv.log https://www.youtube.com/watch?v=1ITdex_JrBM
```

It seems to happen whenever I have a shader installed, either via gsls-shader, or with the error-diffusion dither as described above. If I disable all shaders, then resizing works fine.

### Expected behavior
mpv window should resize without freezing.

### Actual behavior
It can resize sometimes, including full screen. But if I resize multiple times, eventually the video hangs and the mpv process hangs. I have to kill -9 mpv to stop it. Audio continues to play however.

### Log file

https://0x0.st/ih4o.log

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by sfan5** [comment] 2020-12-09 11:10
duplicate of #8360

**Closed by sfan5** 2020-12-09 11:10 UTC
Labels: os:linux
