### ISSUE TITLE
youtube-dl web-source takes about 25 seconds to start

### ISSUE THREAD

**Issue by norpol** [mpv-player/mpv#1556] opened 2015-02-03 18:07 UTC
Hi folks, a friend of mine just notified me that http://tvthek.orf.at/ is starting really slow with mpv (which is compiled with ytdl support).
Just go there, http://tvthek.orf.at/ choose any of the links and run for example:
```mpv http://tvthek.orf.at/program/ZIB-1700/71284/ZIB-17/9194609/EU-Einigung-mit-Griechenland/9194611``` you'll get a `[cache] Cache is not responding - slow/stuck network connection?` notification for about 25 seconds.
`mpv  1.77s user 0.33s system 8% cpu 25.754 total`
When I'm using this one-liner `yt () mpv --quiet --fs $(youtube-dl -g "$1")` the playback starts almost instantly.

PS: I'm using mpv git-95fd83a269db6e2a04e40fe0c40cc02a051f316d

**Comment by wm4** [comment] 2015-02-03 18:37
Yeah, works here too, but takes a while to start. It's probably so slow because it opens every segment on start.

**Comment by norpol** [comment] 2015-02-04 03:05
Ah, thanks for your fast response. This explains it, shall we leave the issue open or do you prefer to close it due it works after a while? :)

**Comment by wm4** [comment] 2015-03-03 13:35
@ChrisK2: should we remove EDL usage? It's really not mode for things like this.

**Comment by ChrisK2** [comment] 2015-03-03 14:53
I'd like to keep it. This will be solved once youtube-dl reports proper playlist types.

**Comment by wm4** [comment] 2015-07-18 13:50
Duplicate of... something.

**Closed by wm4** 2015-07-18 13:50 UTC
