### ISSUE TITLE
Device selection for hwdec copy modes

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#4636] opened 2017-07-19 17:13 UTC
### mpv version and platform
0.26 Windows & Linux

### Reproduction steps
On Windows:
When you use hwdec=d3d11va-copy, mpv always uses the active GPU. Would it be possible to add an option to select a GPU with a different id? For example to use the IGP for decoding and the dGPU for rendering and output. This is possible on Linux with vaapi-copy.

On Linux:
vaapi-copy most likely can be used with both Intel and open-source Radeon drivers? If yes, how does vaapi-copy decide what GPU to use for decoding? I suppose a device selection option would also make sense here.

**Comment by kevmitch** [comment] 2017-07-29 02:22
This is a duplicate of #4320

**Closed by kevmitch** 2017-07-29 02:22 UTC
