### ISSUE TITLE
Encoding with vf=realtime sometimes fails with "no audio stream succeeded"

### ISSUE THREAD

**Issue by chainikdn** [mpv-player/mpv#5666] opened 2018-03-21 12:27 UTC
### mpv version and platform

Windows, shinchiro builds.
- before 20180126 - always works
- starting from 20180204 - fails most (!) times; always works w/o "--vf-realtime"

### Reproduction steps

mpv.com test.mkv --o=out.mp4 **--vf=realtime**

### Log file
```
15:13:29.730: (+) Video --vid=1 (*) (h264 1024x576 23.976fps)
15:13:29.730: (+) Audio --aid=1 --alang=rus (*) (aac 6ch 48000Hz)
15:13:29.730: Audio --aid=2 --alang=eng (aac 6ch 48000Hz)
15:13:29.730: Subs --sid=1 --slang=rus (subrip)
15:13:29.730: Subs --sid=2 --slang=eng (subrip)
15:13:29.730: [ffmpeg/video] h264: SEI type 56 size 384 truncated at 8
15:13:29.747: [ffmpeg/video] h264: SEI type 56 size 384 truncated at 8
15:13:32.256: VO: [lavc] 1024x576 yuv420p
15:13:32.257: [encode-lavc] Opening video encoder: libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 [libx264]
15:13:32.265: [encode-lavc] no audio stream succeeded - invalid codec?
15:13:32.270: [encode-lavc] vo-lavc: encoded 0 bytes
15:13:32.270: [encode-lavc] ao-lavc: encoded 0 bytes
15:13:32.270: [vo/lavc] NOTE: skipped initial video frame (probably because audio is not there yet)
15:13:32.355: Exiting... (Quit)
```

**Comment by wm4** [comment] 2018-03-21 13:28
Wtf is vf_realtime?

**Comment by wiiaboo** [comment] 2018-03-21 14:10
Like ffmpeg's `-re` (forces encoding to be as slow as input fps or something).

**Comment by wm4** [comment] 2018-03-21 14:47
What what I can see it just randomly sleeps() in the filter code, and thus is a terribly designed shit idea. Not on my lawn. Get out.

**Comment by chainikdn** [comment] 2018-03-21 19:11
Not so "randomly"... and it used to work before...
but if you have an idea how the "-re"-behavior should be implemented correctly - please :)
see #5292

**Comment by chainikdn** [comment] 2018-03-22 10:22
In fact in case of network streams it sometimes fails with the same error even **w/o any "realtime" filters**.
Obviously it's not a "realtime" filters fault but the audio+video initialization algorithm is a kind of dark magic (see #4917), which seems to got worse after some recent changes (?). vf_realtime is just a simplest method to illuminate the problem.

**Comment by TheAMM** [comment] 2018-03-25 02:35
I ran into this issue while encoding files from an sshfs mount, `vf=realtime` unrelated. #4917's `--cache-initial` works for the `realtime` example, but does nothing for my commands. Occasionally *any* encodes will fail, but I can raise my chances by adding a `colormatrix` filter which will (on my setup, on my network) fail around 60% of the time.
I'll see in a few days if git-bisect would mark a smaller commit instead of the VF glue rewrite (76276c92104c31ee936ba5c76a76072f09978c5f).

**Comment by TheAMM** [comment] 2018-03-25 15:17
Toyed with `git bisect`. The first bad commit is 6d36fad83c779936a012e85a1eb92ec94651c7c0, the previous eaced0ebb03a078394ed01bcbe641b5b7a4312aa is the latest good working one. The big vf glue rewrite commit was not the cause!

I made a [test file](https://0x0.st/sByX.mkv) with:
```console
$ ffmpeg -f lavfi -i testsrc=duration=5:size=1280x720:rate=24000/1001:decimals=3 -f lavfi -i sine=d=5 -t 20 -map 0:0 -map 1:0 -c:v libx264 -crf 20 -y test.mkv
```
and tested encoding with `mpv test.mkv --end=1 --vf-add=crop=640:480:0:0 --o test.webm --ovc=libvpx --ovcopts-add=crf=20` in an automated config/build script (using mpv-build).

Redundant log:
```bash
# bad:  [a04ac8204faabf73a696a5e1191063ff67722850] mpv.desktop: fix French translation consistency
# good: [edb4970ca8b9bee8e54222a1e119af9d355d451a] vo_gpu: check for RA_CAP_FRAGCOORD in dumb mode too
# bad:  [4a579ad16694da158c641514b39a1547fe6c7449] cocoa-cb: fix hwdec when drawing off-screen
# bad:  [4e7f4f10cef15d29f9e5093eff84e9e8168caf89] vo_gpu: correctly infer HDR peak detection support
# bad:  [c1b15ae437f70226ebf2d57f02467dbb8a80c256] vf_vapoursynth: fix obscure/impossible leak
# bad:  [e197ca3dd5d9f5e3f1ea89a35d0cb8de6cb36cf8] Copyright: fix missing word
# good: [eaced0ebb03a078394ed01bcbe641b5b7a4312aa] demux: add a per stream wakeup callback
# bad:  [76e7e78ce989aad546310b9808cf7f96f23a281f] audio: move to decoder wrapper
# bad:  [054c02ad64a62dd8393bde0fd73edeaa71048722] ao_null: add --ao-null-format option for debugging
# bad:  [6d36fad83c779936a012e85a1eb92ec94651c7c0] video: make decoder wrapper a filter
# first bad commit: [6d36fad83c779936a012e85a1eb92ec94651c7c0] video: make decoder wrapper a filter
```

**Comment by TheAMM** [comment] 2018-04-28 23:58
This should now be fixed, as https://github.com/mpv-player/mpv/pull/5750 is merged.

**Comment by Akemi** [comment] 2021-05-08 13:37
apparently fixed. if the issue still persist please open a new issue.

**Closed by Akemi** 2021-05-08 13:37 UTC
Labels: core:encoding
