### ISSUE TITLE
In Windows 11, using more than 8 glsl-shaders with vo=gpu-next crashes the player after displaying the first frame

### ISSUE THREAD

**Issue by SephirothFFKH** [mpv-player/mpv#10211] opened 2022-05-19 09:46 UTC
### Important Information

Provide following Information:
- mpv version: mpv 0.34.0-298-gf20dbcd620
- Windows Version: Windows 11 Home 21H2 22000.675
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/
- If known which version of mpv introduced the problem: Unknown but the issue only happens on vo=gpu-next
- Possible screenshot or video of visual glitches: N/A 

### Reproduction steps

Playing any 1920x1080p video on a 3840x2160p or higher screen with the config lines bellow will crash the player after displaying the first frame. Removing "vo=gpu-next" OR only 1 of the "glsl-shaders-append=..." arbitrarily will fix the issue. I have tested the issue on 3 different computer and it happens on all of them. I have not tried using any other shaders than these 9 though. You can find the necessary shaders here: https://github.com/bloc97/Anime4K and https://gist.github.com/igv

mpv.conf 

vo=gpu-next
glsl-shaders-append="~~/shaders/Anime4K_Clamp_Highlights.glsl"
glsl-shaders-append="~~/shaders/Anime4K_Restore_CNN_VL.glsl"
glsl-shaders-append="~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl"
glsl-shaders-append="~~/shaders/Anime4K_Restore_CNN_M.glsl"
glsl-shaders-append="~~/shaders/Anime4K_AutoDownscalePre_x2.glsl"
glsl-shaders-append="~~/shaders/Anime4K_AutoDownscalePre_x4.glsl"
glsl-shaders-append="~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl"
glsl-shaders-append="~~/shaders/KrigBilateral.glsl"
glsl-shaders-append="~~/shaders/adaptive-sharpen.glsl"
fullscreen
log-file="~~/logs.txt"
gpu-debug=yes
msg-level=all=trace

### Expected behavior

The video should play with all shaders working properly just like when removing "vo=gpu-next" from the config.

### Actual behavior

The player displays the first frame, freezes for half a second and the player closes.

### Log file

https://0x0.st/oacy.txt

### Sample files

Any 1920x1080p video file.

Thank you very much for this amazing player!

**Comment by amariami** [comment] 2022-05-19 13:50
it seem you put an adaptive sharpen right?
[look here](https://gist.github.com/igv/8a77e4eb8276753b54bb94c1c50c317e?permalink_comment_id=4113454#gistcomment-4113454)

**Comment by amariami** [comment] 2022-05-19 14:56
Maybe that crash caused by bloating Anime4K shaders with adaptive sharpen. I didn't see Anime4K could mix with another shader except [chroma shader Krigbilateral](https://github.com/bloc97/Anime4K/blob/master/md/GLSL_Instructions_Windows.md)

Sure with this config seem enough.
`--glsl-shaders="C:\Users\AnimePC\AppData\Roaming\mpv\shaders\Anime4K_Clamp_Highlights.glsl;C:\Users\AnimePC\AppData\Roaming\mpv\shaders\Anime4K_Restore_CNN_Soft_VL.glsl;C:\Users\AnimePC\AppData\Roaming\mpv\shaders\Anime4K_Upscale_CNN_x2_VL.glsl;C:\Users\AnimePC\AppData\Roaming\mpv\shaders\Anime4K_AutoDownscalePre_x2.glsl;C:\Users\AnimePC\AppData\Roaming\mpv\shaders\Anime4K_AutoDownscalePre_x4.glsl;C:\Users\AnimePC\AppData\Roaming\mpv\shaders\shaders/Anime4K_Restore_CNN_Soft_M.glsl;C:\Users\AnimePC\AppData\Roaming\mpv\shaders\shaders/Anime4K_Upscale_CNN_x2_M.glsl;C:\Users\AnimePC\AppData\Roaming\mpv\shaders\KrigBilateral.glsl"`

If your source less sharpen or might blurrier you could use [FSR or NVScaler by Agyild](https://gist.github.com/agyild) then change parameter
E.g [FSR](https://raw.githubusercontent.com/amariami/MPV-config-2022/main/shaders/AMD-FSR_PQ%200_(EASU_DERING-1_ANALYS-1_QUIT-EARLY-1)_(RCAS_PQ-0_DENOISE-0).glsl) `--glsl-shaders="C:\Users\AnimePC\AppData\Roaming\mpv\shaders\FSR.glsl;C:\Users\AnimePC\AppData\Roaming\mpv\shaders\KrigBilateral.glsl"`
or 
E.g [NVScaler](https://raw.githubusercontent.com/amariami/MPV-config-2022/main/shaders/NVIDIA-Scaler256_no-HDR.glsl) `--glsl-shaders="C:\Users\AnimePC\AppData\Roaming\mpv\shaders\NVScaler.glsl;C:\Users\AnimePC\AppData\Roaming\mpv\shaders\KrigBilateral.glsl"`

**Comment by SephirothFFKH** [comment] 2022-05-19 23:36
Thank you very much for your reply. Yes, you are right that this is definitely a lot of shaders and I also think that vo=gpu-next is actually working properly and enforcing a strict limit of 8 simultaneous shaders. The issue is probably with vo=gpu that was not properly checking if too many shaders are running at the same time and could become unstable for other users with lower end GPUs.

The crash definitely seems to be unrelated to codecs as I have tried h.264, h.265 and vp9 video and if they are 1920x1080p they will cause the crash if you need logs with any other codecs don't hesitate to ask.

Also a big thanks for the FSR and NVScaler shaders I will certainly give them a try! But for now, removing vo=gpu-next or replacing it with vo=gpu seems to stop the crashing so this seems like the easiest fix.

If it's confirmed that vo=gpu-next is designed with a limit of 8 simultaneous shaders I think we can close this issue and I will go ask if bloc97 can make a more compact version of the Anime4K shader that can run with fewer number of shaders.

**Comment by n-buna404** [comment] 2022-05-20 00:21
well u can try update mpv to latest daily build by shinchiro https://github.com/shinchiro/mpv-winbuild-cmake/releases
and try again since there maybe changes to gpu-next

**Comment by SephirothFFKH** [comment] 2022-05-20 02:24
Thank you for the link. I updated mpv to version 20220519 yesterday with "updater.bat" to run the previous tests above and I have updated to 20220520 today and the issue is still happening. But, I have to point that all these build are returning that they are based on the old mpv 0.34.0 when running "mpv --version". Yet, the newest release in the mpv repo is 0.34.1 https://github.com/mpv-player/mpv/releases/tag/v0.34.1 but, I can't find a Windows x64 complied binary of this version which could probably fix this issue.

**Comment by zhongfly** [comment] 2022-05-20 05:16
> Thank you for the link. I updated mpv to version 20220519 yesterday with "updater.bat" to run the previous tests above and I have updated to 20220520 today and the issue is still happening. But, I have to point that all these builds are returning that they are based on the old mpv 0.34.0 when running "mpv --version". Yet, the newest release in the mpv repo is 0.34.1 https://github.com/mpv-player/mpv/releases/tag/v0.34.1 but, I can't find a Windows x64 complied binary of this version which could probably fix this issue.

You totally misunderstood, for example the version number `mpv 0.34.0-298-gf20dbcd620`, does not mean based on 0.34.0, it should be noted that it is `gf20dbcd620`, it means that the build uses f20dbcd620 of the git branch which is newer than 0.34.0 Or 0.34.1.

**Comment by SephirothFFKH** [comment] 2022-05-20 06:26
Thank you so much for the clarifications! Then, I can confirm that even the latest git master branch still has this issue unless this is the intended limit on the number of shaders in gpu-next.

**Comment by kasper93** [comment] 2024-12-04 17:05
Likely fixed by #11619 report back if this still happens.

**Closed by kasper93** 2024-12-04 17:05 UTC
Labels: os:win
