### ISSUE TITLE
Drag window shortly after cycle fullscreen lead to wrong window behavior

### ISSUE THREAD

**Issue by FinnRaze** [mpv-player/mpv#11415] opened 2023-03-06 13:53 UTC
### Important Information

Provide following Information:
- mpv version:
- mpv 0.35.0-255-g16f0cd54 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Sun Feb 26 12:34:06 2023
libplacebo version: v5.229.1-293-gac45f21
FFmpeg version: N-109920-gac6eec1fc
FFmpeg library versions:
   libavutil       58.3.100
   libavcodec      60.4.100
   libavformat     60.4.100
   libswscale      7.2.100
   libavfilter     9.4.100
   libswresample   4.11.100
- Windows Version: Windows 8.1 pro
- Source of the mpv binary: shinchiro's build
- Possible screenshot or video of visual glitches

![mpv-shot0009](https://user-images.githubusercontent.com/84557113/223129160-d1d2cc1d-a5a1-459e-8e78-a81d00248d78.jpg)

![mpv-shot0010](https://user-images.githubusercontent.com/84557113/223129175-de76f4df-e1b9-4c08-9d70-2700716fafc6.jpg)

I didn't use no-border and it's in fullscreen(exit fullscreen the border would show up).And there is unexpected margin(16:9 video on 16:9 screen).

### Reproduction steps

1.open a media(not fullscreen,with border)
2.cycle fullscreen with MBTN_LEFT_DBL ,meanwhile drag swiftly
3.the mpv is in fullscreen but windowed

### Expected behavior
fullscreen
### Actual behavior
fullscreen mode in window
### Log file
[mpv_log.txt](https://github.com/mpv-player/mpv/files/10898730/mpv_log.txt)

**Comment by garoto** [comment] 2023-03-06 14:34
Possible dupe of: https://github.com/mpv-player/mpv/issues/1921

**Closed** 2023-03-06 22:48 UTC
Labels: os:win
