### ISSUE TITLE
youtube-dl failed to recognize file format

### ISSUE THREAD

**Issue by Keith94** [mpv-player/mpv#4744] opened 2017-08-08 18:12 UTC
>C:\mpv>mpv https://www.youtube.com/watch?v=7fx9FwWVLBA
Playing: https://www.youtube.com/watch?v=7fx9FwWVLBA
[ytdl_hook]
[ytdl_hook] stack traceback:
[ytdl_hook]     @ytdl_hook.lua:71: in function 'edl_escape'
[ytdl_hook]     @ytdl_hook.lua:139: in function 'edl_track_joined'
[ytdl_hook]     @ytdl_hook.lua:171: in function 'add_single_video'
[ytdl_hook]     @ytdl_hook.lua:454: in function 'fn'
[ytdl_hook]     mp.defaults:518: in function 'handler'
[ytdl_hook]     mp.defaults:339: in function 'handler'
[ytdl_hook]     mp.defaults:458: in function 'call_event_handlers'
[ytdl_hook]     mp.defaults:495: in function 'dispatch_events'
[ytdl_hook]     mp.defaults:451: in function <mp.defaults:450>
[ytdl_hook]     [C]: at 0x07f640fe06f0
[ytdl_hook]     [C]: at 0x07f640fdfcf0
[ytdl_hook] Lua error: @ytdl_hook.lua:71: bad argument #1 to 'len' (string expec
ted, got nil)
Failed to recognize file format.
Exiting... (Errors when loading file)

**Comment by CounterPillow** [comment] 2017-08-08 18:19
either update mpv to the current git version or downgrade youtube-dl

**Comment by wiiaboo** [comment] 2017-08-08 18:25
Duplicate of https://github.com/mpv-player/mpv/issues/4728. See https://github.com/mpv-player/mpv/issues/4728#issuecomment-320725058 for a workaround.

**Closed by wiiaboo** 2017-08-08 18:25 UTC
