### ISSUE TITLE
No vaapi for AMDGPU with libva-git, mesa-git, mpv-build-git from the AUR

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#5305] opened 2017-12-28 15:09 UTC
### mpv version and platform
```
mpv 0.28.0-44-gd9ca235c68 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.7.100
   libavcodec      58.9.100
   libavformat     58.3.100
   libswscale      5.0.101
   libavfilter     7.8.100
   libswresample   3.0.101
ffmpeg version: N-89646-gbe4dfbf7b7
```
### Reproduction steps
Install libva-git, mesa-git, mpv-build-git from AUR
### Expected behavior
VAAPI available for AMDGPU
### Actual behavior
no vaapi, only vaapi-copy works.
### Log file
[LOG.log.zip](https://github.com/mpv-player/mpv/files/1591440/LOG.log.zip)

**Comment by kevmitch** [comment] 2017-12-28 20:43
Does it work with `--gpu-context=x11egl`? There's #5298. but we might hold off on merging that until this gets into mesa and libva releases.

**Comment by Gusar321** [comment] 2017-12-29 00:03
You need to patch both libva-git and mesa-git if you want vaapi-egl interop on AMD

In libva-git, you need to bump the API version, change the minor version here to 1: https://github.com/01org/libva/blob/master/configure.ac#L30
In mesa, you need to apply this patch: https://lists.freedesktop.org/archives/mesa-dev/2017-December/178971.html

**Comment by JulianLai** [comment] 2017-12-29 13:56
@kevmitch No
@Gusar321 How to apply the patch for mesa-git?

**Comment by JulianLai** [comment] 2017-12-29 16:40
When will they release libva2.1? Does anybody know?

**Comment by pkerling** [comment] 2018-01-05 09:21
Is this actually supposed to work at the moment? I have libva from git and patched mesa, ffmpeg, and mpv from git (to remove the VA-API version check, might have been easier to bump the libva version but result is the same), but I only get garbled video display (see below). Hardware decoding does work in principle, but somehow showing the result isn't working out correctly. `--hwdec=vaapi-copy` instead of `--hwdec=vaapi` works. Using it with wayland+egl if that matters.

![screenshot from 2018-01-05 10-18-50](https://user-images.githubusercontent.com/4533697/34602931-ac52e62c-f1f9-11e7-872c-0634b87c0dd7.png)

**Comment by thebombzen** [comment] 2018-01-12 23:13
If you removed the VA-API version check to force it to work with a version marked as incompatible, you should not be surprised when it doesn't work.

**Comment by pkerling** [comment] 2018-01-13 11:12
@thebombzen With the current state of things there is no VA-API release or branch for which the version check holds true. Still, the code is there in mesa, ffmpeg, and mpv, because everyone *expects* `vaExportSurfaceHandle` to land in the next VA-API version to be released and expects that API version number to be 1.1.0 (current is 1.0.0). That said, with VA-API from git master (undefined post-1.0.0 version) you can either bump the version in `va_version.h` or remove the check on the mpv side. It's the exact same thing with the exact same code running. Since the code to support this is clearly there in mpv, I can at least ask if it should be working and see if someone wants to fix it, right?

**Comment by thebombzen** [comment] 2018-01-13 17:52
It sounds like something on your system is broken, because the VA-API check works here just fine.

**Comment by pkerling** [comment] 2018-01-13 17:56
@thebombzen Can you elaborate? What "VA-API check" do you mean?

**Comment by Gusar321** [comment] 2018-02-04 08:27
libva-git now has the correct API version, so I tried the new interface. I can only test Intel for now, and what I can report is that it works correctly. @pkerling try again with an unmodified libva-git/ffmpeg-git/mpv-git and this patch for mesa: https://lists.freedesktop.org/archives/mesa-dev/2017-December/178971.html. If it's still the same, it's a radeon driver bug.

**Comment by pkerling** [comment] 2018-02-09 19:24
@Gusar321 I tried but it does not change anything, which is unsurprising since the code that runs is effectively the same. Also the patch for mesa is upstream now.

And yes, it does work on intel, also for me. But it may not be a bug in mesa either, since it works correctly in Kodi.

**Comment by Gusar321** [comment] 2018-02-12 18:53
I got my hands on an AMD card. It's an older chipset, uses the r600 mesa driver. And well, it works.
vainfo: http://0x0.st/sTi2.log
mpv log: http://0x0.st/sTi_.log
screenshot:
![bbb](https://user-images.githubusercontent.com/10744281/36113598-a04aeeae-102d-11e8-81bb-1c073c7e9bd3.png)
That means I have Intel working and r600 working. So it's either a radeonsi bug or something specific to your setup. Anyone else here who uses the radeonsi driver that could test?

**Comment by pkerling** [comment] 2018-02-12 19:21
Finally found it - I had mesa compiled without `--enable-texture-float`. Works for me now.

**Comment by myfreeweb** [comment] 2018-03-06 21:09
Hi everyone!

I upgraded to mpv 0.28.2 and got VAAPI working on Wayland (`--vo gpu --gpu-context wayland --hwdec vaapi`, AMD Polaris, FreeBSD 12-CURRENT, Mesa 18.1-devel)

But on `x11egl` or `x11` it's not working:

```
[vaapi] libva: va_getDriverName() failed with unknown libva error,driver_name=(null)
Failed to open VDPAU backend Shared object "libvdpau_nvidia.so" not found, required by "mpv"
[vaapi] libva: va_getDriverName() failed with unknown libva error,driver_name=(null)
```

It's actually refreshing to see something work on Wayland but not X11, usually it's the other way around :D But why would the driver name not return on X11…

**Comment by pkerling** [comment] 2018-03-07 07:05
The problem is that Xwayland does not support DRI2, see https://github.com/intel/libva/issues/79
It should work if you set `LIBVA_DRIVER_NAME=radeonsi` to skip the misbehaving autodetection.

**Comment by laichiaheng** [comment] 2018-03-08 08:38
The VAAPI is still not working for my AMD RX460 in native Xorg (mpv-build-git from AUR, Mesa 18.1.0-devel, libva 2.1.0-1)
Does the --enable-texture-float must to be disabled to enable the vaapi hwdec?

**Comment by shmerl** [comment] 2018-12-13 05:43
I can confirm, that using this config works for me with Mesa 18.3.0 release candidates with AMD Vega 56:

```
vo=gpu
gpu-api=opengl
hwdec=vaapi
gpu-context=x11egl
```

I tried using gpu-api=vulkan, but [Debian still dind't package shaderc](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=890472), so I might try building it manually first.

What's recommended way to combine Vulkan and vaapi? I suppose EGL isn't relevant for such case?

**Comment by myfreeweb** [comment] 2018-12-13 16:11
Yes, EGL isn't relevant, Vulkan has its own WSI (Window System Interface).

`LIBVA_DRIVER_NAME=radeonsi mpv --gpu-context=waylandvk --hwdec=auto` works for me (on Wayland)

**Comment by kode54** [comment] 2018-12-17 01:16
@pkerling The garbled output you see is because the VAAPI patch for Chrome, and possibly VAAPI support in Totem, don't handle the RGBA10-10-10-0/2 formats that the AMDGPU driver enabled. Apparently, this isn't a problem for MPV, as it either supports this, or explicitly renders to an RGB-8-8-8 surface.

**Comment by pkerling** [comment] 2018-12-17 08:39
@kode54 Did you read https://github.com/mpv-player/mpv/issues/5305#issuecomment-365032632 ?

**Comment by kode54** [comment] 2018-12-17 09:42
Apparently, I was so quick to reply, I didn't read the entire thread. Sorry.

**Closed** 2019-09-19 19:55 UTC
Labels: not our bug
