### ISSUE TITLE
mpv wont load/pickup subtitles?

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv#13251] opened 2024-01-08 20:55 UTC
Provide following Information:
- mpv version
-mpv v0.37.0-112-g702b3eb956 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Dec 18 2023 11:49:17
libplacebo version: v6.338.0-62-g52314e0e
FFmpeg version: n6.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100

- Linux Distribution and Version
devuan 5.0 64bit

mpv 
built from source

with options
echo --enable-libx264 >> ffmpeg_options
echo --enable-vaapi >> ffmpeg_options
echo -Dvapoursynth=enabled >> mpv_options
echo -Dlibmpv=true >> mpv_options
echo --enable-nvdec >> ffmpeg_options

### Reproduction steps

i have downloaded several videos via yt-dlp with corresponding subtitles /subtitles as separate .vtt files,

issues is mpv does not recognize the subtitles altough they are in the same folder and have the same filename like in

A Hindu Temple Hidden Under Islamic University of Indonesia？  Candi Kimpulan Temple – Part 1 [50jN3QMI5u0].mp4
A Hindu Temple Hidden Under Islamic University of Indonesia？  Candi Kimpulan Temple – Part 1 [50jN3QMI5u0].en-US.vtt

mpv does not play subtitles automatically and does not pick up subtitles when pressing ¨j"on keyboard.

### Expected behavior

mpv should recognize subtitles , as vlc does on the same computer with same files

### Actual behavior

mpv does not play subtitles, maybe the compile was made without subtitle support?

### Log file

https://pastebin.ubuntu.com/p/c7wcTWj6CK/

### Sample files

![mpv-shot0001](https://github.com/mpv-player/mpv/assets/12947465/983d72d7-68d6-4633-a9f9-640b9439a808)
![Screenshot_2024-01-08_21-54-43](https://github.com/mpv-player/mpv/assets/12947465/2d806549-21b8-4c84-9f59-07f479c5ab25)

**Comment by guidocella** [comment] 2024-01-08 21:07
It seems that `Hidden Hindu Past of Indonesia  ｜  Candi Sambisari Temple.en.vtt` is loaded but not `Hidden Hindu Past of Indonesia  ｜  Candi Sambisari Temple.en-US.vtt`. Detection of regional locales should be probably be added.

**Comment by mrkapqa** [comment] 2024-01-09 10:20
hello , thanks for the fast respone; could you show please how to achieve it easily or need i recompile mpv?

**Comment by guidocella** [comment] 2024-01-09 10:24
It's not implemented.

**Comment by guidocella** [comment] 2024-02-12 09:54
Duplicate of https://github.com/mpv-player/mpv/issues/12372

**Closed** 2024-02-12 14:51 UTC
Labels: os:linux
