### ISSUE TITLE
Occasional deadlock on startup with nvdec

### ISSUE THREAD

**Issue by evanc577** [mpv-player/mpv#10109] opened 2022-04-18 06:21 UTC
On Linux, mpv will occasionally deadlock on startup when playing a video with `--hwdec=nvdec` and need to be force killed. Doesn't seem to occur when starting with `--hwdec=no` and toggling hardware decoding with ctrl+h.

### Important Information

Provide following Information:
- mpv version: 0.34.1 and master
- Linux Distribution and Version: Arch Linux
- Source of the mpv binary: Arch Linux repo (0.34.1) and AUR (master)
- If known which version of mpv introduced the problem: unknown
- Window Manager and version: KDE Plasma 5.24.4 (X11)
- GPU driver and version: nvidia 510.60.02-15
- Possible screenshot or video of visual glitches: mpv is completely unresponsive
![Screenshot_20220418_015559](https://user-images.githubusercontent.com/14303970/163762157-791cbfdc-bf28-420f-ab08-a04518bbf631.png)

### Reproduction steps

Enable nvdec and play video, quit and retry until mpv hangs on start.

```
mpv --no-config --hwdec=nvdec --vo=gpu video.mp4
```

### Expected behavior

mpv plays the video

### Actual behavior

mpv hangs and must be killed with `SIGKILL`. CPU usage is 100% of one core.

### Log file

[mpv log](https://github.com/mpv-player/mpv/files/8503850/log.txt)

### Backtrace:

```
#0  0x00007f85fe44615a in __futex_abstimed_wait_common () at /usr/lib/libc.so.6
#1  0x00007f85fe448960 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libc.so.6
#2  0x000055cc7dc8dbfc in mp_dispatch_run ()
#3  0x000055cc7dd08aa6 in vo_reconfig2 ()
#4  0x000055cc7dccbc67 in write_video ()
#5  0x000055cc7dcc779e in run_playloop ()
#6  0x000055cc7dcc0851 in  ()
#7  0x000055cc7dcc198a in mp_play_files ()
#8  0x000055cc7dcc27a9 in mpv_main ()
#9  0x00007f85fe3e9310 in __libc_start_call_main () at /usr/lib/libc.so.6
#10 0x00007f85fe3e93c1 in __libc_start_main_impl () at /usr/lib/libc.so.6
#11 0x000055cc7dc3b295 in _start ()
```

[full backtrace](https://github.com/mpv-player/mpv/files/8503877/gdb.txt)

**Comment by philipl** [comment] 2022-04-18 16:29
Duplicate of #9313. And I recommend the same work-around. Use Vulkan instead of OpenGL.

```
mpv --no-config --hwdec=nvdec --vo=gpu --gpu=api=vulkan
```

etc.

**Closed by philipl** 2022-04-18 16:29 UTC
Labels: os:linux
