### ISSUE TITLE
Play issues, blue traces & dots on the edge of image and subtitle

### ISSUE THREAD

**Issue by chenxi6623** [mpv-player/mpv#3578] opened 2016-09-24 09:45 UTC
### mpv version and platform

mpv 0.20.0, macOS Sierra
### Reproduction steps

mpv http://www.bilibili.com/video/av6272937/
or just open a mp4/mkv file.
### Expected behavior

normal playing 
### Actual behavior

There are many blue dots on the edge of figure and subtitle
### Log files

http://sprunge.us/dPQB
### Sample files

https://0x0.st/Qb1.png

**Comment by wm4** [comment] 2016-09-24 10:40
These look like underflows of some sort in the shader. Can you try with --no-config?

**Comment by chenxi6623** [comment] 2016-09-24 10:52
Yes, I have already tried --no-config and reinstall the mpv, but it doesn't work.
This problem occurs after I've updated my OS to Sierra. I wonder whether it caused the problem.

**Comment by lachs0r** [comment] 2016-12-25 09:53
I’ll close this since it’s probably a duplicate of #3626 (and that one has slightly more info).

**Closed by lachs0r** 2016-12-25 09:53 UTC
