### ISSUE TITLE
VP8 video plays at double speed with FreeSync and `video-sync=display-resample`

### ISSUE THREAD

**Issue by bakugo** [mpv-player/mpv#12338] opened 2023-09-04 11:01 UTC
### Important Information

- mpv version: v0.36.0-240-g67368ac5
- Windows Version: 11 21H2
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/

### Reproduction steps

Play a VP8 video with `video-sync=display-resample` on a monitor with FreeSync enabled.

`mpv --no-config --video-sync=display-resample video.webm`

### Expected behavior

Video plays at normal speed.

### Actual behavior

Video plays at double speed.
Stats overlay shows estimated display FPS as twice the actual refresh rate (340 instead of 170 in my case).
Disabling FreeSync on the monitor stops it from happening.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/12512734/output.txt)

### Sample files

https://files.catbox.moe/ytk9fx.webm

**Comment by llyyr** [comment] 2023-09-04 13:18
Can't reproduce and your logs also don't show this happening

```
[   0.136][v][vo/gpu/win32] display-fps: 170.001000
[   0.137][v][vo/gpu] Assuming 170.001000 FPS for display sync.
```

**Comment by CounterPillow** [comment] 2023-09-04 13:50
Don't combine display-resample with VRR such as FreeSync. It makes no sense and the two mechanisms usually race each other to either the top or bottom.

**Comment by bakugo** [comment] 2023-09-04 16:05
> Can't reproduce and your logs also don't show this happening

The overlay correctly shows the specified fps to be 170.001, it's the estimated fps that shows up as ~340 during playback. `override-display-fps` doesn't help, either.

> enable vsync in the GPU control panel

It's already enabled.

> Don't combine display-resample with VRR such as FreeSync. It makes no sense and the two mechanisms usually race each other to either the top or bottom.

It works correctly with all other codecs I've tried (VP9, AVC, HEVC, etc), the refresh rate stays fixed at 170 during playback.

Having it disabled causes the monitor's reported refresh rate during playback to either stay locked at 170 anyway even if it's not correct, or fluctuate wildly instead of settling on a fixed number, which is why I enabled it in the first place.

**Comment by llyyr** [comment] 2023-09-04 16:14
> The overlay correctly shows the specified fps to be 170.001, it's the estimated fps that shows up as ~340 during playback. override-display-fps doesn't help, either.

Can you provide a screenshot of the stats overlay when this happens?

> Having it disabled causes the monitor's reported refresh rate during playback to either stay locked at 170 anyway even if it's not correct, or fluctuate wildly instead of settling on a fixed number, which is why I enabled it in the first place.

display-resample shouldn't affect your display fps estimation at all, so this makes no sense. display-resample makes the video always run at your monitor's vsync, while disabling it with VRR would allow VRR to driver your monitor at a lower fps. You should _never_ use display-resample with VRR unless you want to not use VRR at all.

**Comment by bakugo** [comment] 2023-09-04 16:21
>Can you provide a screenshot of the stats overlay when this happens?

![image](https://github.com/mpv-player/mpv/assets/6014513/f3b95610-7247-4a57-af4c-c2c395f2dad3)

>You should _never_ use display-resample with VRR unless you want to not use VRR at all.

That's what I'm saying, I don't want to use VRR with mpv, I only really care about it for games.

>Which mode is it? Do not select a mode other than "On".

It's set to "on". It's an nvidia GPU btw.

**Comment by Jules-A** [comment] 2023-09-04 16:28
> It's set to "on". It's an nvidia GPU btw.

Lol, okay now I feel stupid, I was trying to replicate it on my AMD card but wasn't able to since I assumed you were using AMD as title mentions Freesync.

>Don't combine display-resample with VRR such as FreeSync. It makes no sense and the two mechanisms usually race each other to either the top or bottom.

It doesn't on AMD. It doesn't seem to improve things though either, however "Enhanced Sync" reduced my vsync jitter by 10x... I always had it enabled before in MPV but accidentally forgot to re-enable it after a DDU and thought the increase I was seeing was from MPV/libplacebo update...

**Comment by Jules-A** [comment] 2023-09-08 11:01
I managed to encounter this bug with MP4 (H264) so it probably has nothing to do with VP8. It occurred after switching to a game with MPV open (playing) and closing the game. It changed my estimated FPS to 300 when my monitor is 75hz...

**Comment by Traneptora** [comment] 2023-09-19 11:51
I'm going to close this issue as probably not VP8-related. Feel free to open another issue if you can reproduce it with other codecs.

**Closed by Traneptora** 2023-09-19 11:51 UTC
Labels: os:win

**Comment by Jules-A** [comment] 2023-09-19 11:57
> I'm going to close this issue as probably not VP8-related. Feel free to open another issue if you can reproduce it with other codecs.

Why not just change the name of the issue?

**Comment by bakugo** [comment] 2023-09-19 18:51
@Traneptora 

I don't get it, *you* think it's not VP8 related, but you want *me* to prove it?

Either way this isn't fixed, if you think it's not codec related, just change the name like @Jules-A suggested.

**Comment by Traneptora** [comment] 2023-09-20 07:58
Well so far the only things you described that you tested and couldn't reproduce the issue with hardware-decode by default. But you've already been told that display-resample makes no sense with VRR tools such as FreeSync.
