### ISSUE TITLE
mpv - youtube-dl - unrecognized file format

### ISSUE THREAD

**Issue by Adiqq** [mpv-player/mpv#4809] opened 2017-08-27 19:23 UTC
### mpv version and platform
Arch linux
mpv 0.26.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
built on Thu Jul 20 13:13:36 CEST 2017

### Reproduction steps
- Install [mpv](https://www.archlinux.org/packages/community/i686/mpv/)
- Install [youtube-dl](https://www.archlinux.org/packages/community/any/youtube-dl/)
- Execute `mpv https://youtu.be/_XmUKXZ03pA`

### Expected behavior
Open youtube stream and play video.

### Actual behavior
Crash with error, 

> finished playback, unrecognized file format (reason 4)

### Log file
https://pastebin.com/7hvfETsK

**Comment by wiiaboo** [comment] 2017-08-27 19:36
Duplicate of https://github.com/mpv-player/mpv/issues/4728. See https://github.com/mpv-player/mpv/issues/4728#issuecomment-320725058 for a workaround.

**Closed by wiiaboo** 2017-08-27 19:36 UTC
