### ISSUE TITLE
Libmpv cannot respond to mouse events using OpenGL rendering in Qt.

### ISSUE THREAD

**Issue by DSxiaolong** [mpv-player/mpv#12299] opened 2023-08-30 02:44 UTC
Using Qt+QOpenGL+libmpv to develop a player and embed calls to other software such as C # WPF, it is not possible to respond to mouse events in real-time during video playback. If window ID binding is used, the working effect is good. How should this be resolved? Or what is the reason for this problem? Is it WPF calling Qt conflicting? WPF uses D3D rendering, while Qt uses OpenGL rendering.

**Comment by DSxiaolong** [comment] 2023-08-30 02:48
qt_opengl
Shows how to use mpv's OpenGL video renderer in Qt. This uses the opengl-cb API for video. Since it does not rely on embedding "foreign" native Windows, it's usually more robust, potentially faster, and it's easier to control how your GUI interacts with the video. You can do your own OpenGL rendering on top of the video as well.

**Comment by Dudemanguy** [comment] 2023-08-30 02:48
Duplicate of #10952

**Closed by Dudemanguy** 2023-08-30 02:48 UTC
Labels: os:win
