### ISSUE TITLE
Fullscreen on OSX 10.10.5 blocks alt-tabbing and has other bugs

### ISSUE THREAD

**Issue by mlindner** [mpv-player/mpv#4177] opened 2017-02-22 10:10 UTC
### mpv version and platform
mpv git-992e582

### Reproduction steps

Go into fullscreen on any video on 10.10.5

### Expected behavior

You should be able to alt-tab when the video is in full screen.

The screen should not flash briefly after going into full screen.

The screen should not scroll sideways when going out of full screen or going into full screen.

### Actual behavior

You cannot alt-tab in full screen.

The screen does a brief flash to black after displaying the image about 1 second after it has finished going into full screen.

The screen does not scroll sideways when going INTO full screen but it scrolls sideways when going out of full screen.

### Log file

Log file is of starting a video (with fs=on) and then going out of full screen, going back into full screen, and back out of full screen (and then back in I think) then exiting.

http://sprunge.us/FCWh

### Sample files

Any file will work.

**Comment by Akemi** [comment] 2017-02-22 14:28
last two issues are a duplicate of #3944 and #4014 since it sounds like you want a none native fs. the last one can't be fixed because this is done in the Apple API. if you want to it gone send a request to Apple that you want to be able to deactivate all system animations.

Alt+Tab is not a standard keyboard shortcut so i just assume you mean CMD+Tab to switch Apps. that works as intended

**Closed by Akemi** 2017-02-22 14:28 UTC
Labels: osx

**Comment by mlindner** [comment] 2017-02-23 08:12
Please reopen this bug. Cmd+tab does NOT work.

**Comment by mlindner** [comment] 2017-02-23 08:14
Created new entry just regarding cmd+tab not working. https://github.com/mpv-player/mpv/issues/4180

**Comment by mlindner** [comment] 2017-02-23 09:13
Well seeing as we don't want to have good ticket management I guess I will discuss the bug in this issue.

This bug is indeed occurring on 10.10.5. When cmd+tabbing the application switcher window appears and acts normally, but if a different application is selected it does not switch to it fully. Keyboard actions still engage with the switched-to application, but the application's window is not visible. Mouse actions are still grabbed by mpv however.

**Comment by mlindner** [comment] 2017-02-23 09:14
I should also add that you must have some control over the third issue and it is not entirely an apple issue because the functionality on how that worked changed at some point recently as it used to do the apple animation on both entrance into full screen and exit out of full screen. It no longer does the animation on entrance to full screen.

**Comment by Akemi** [comment] 2017-02-23 14:27
we never officially supported a native fullscreen (with animations), the one which was remover before didn't have animation either, and before it was an overlay style fullscreen window that didn't occupy a space. both animations are still there, in and out, just that the in animation is hidden by the fullscreen window. that's also the reason why you get the black frame at some point. it was decided to remove, or hide the animation as much as possible because playback was choppy while animating.

CMD+Tab does work as intended on 10.12. i don't have a 10.10 system to test and it will deprecated by apple soonish. i assume it's an Apple bug, though you can try [this](https://github.com/Akemi/mpv/commit/3a5debf67c88a4c2ce8cb0639a0414b5f48ef7df) as a test, if it works we probably do something wrong, if it doesn't it's an Apple bug.

**Comment by mlindner** [comment] 2017-03-02 12:50
That was somewhat unclear. Are you suggesting I just cherry-pick that commit or that I should build your https://github.com/Akemi/mpv/commits/cocoa_ghosting cocoa_ghosting branch?

**Comment by Akemi** [comment] 2017-03-02 14:46
the whole branch pls.
