### ISSUE TITLE
Make secondary subtitle track style editable

### ISSUE THREAD

**Issue by GitHubUserer** [mpv-player/mpv#6441] opened 2019-01-15 09:56 UTC
Currently, as far as I know, secondary subtitle track is always on the top of video and hardcoded font style and size. Sorry if I am wrong.

Can we make the style be customizable? Or at least can change the font size? The size is too big for me. Particularly, it seems if there are too many characters, like if it was a sign translation or typeset, the video can only fit some of the text and the rest is cut off.

**Comment by GitHubUserer** [comment] 2019-02-11 10:01
Can you tell me where the default style for secondary subtitle track is defined so that I can change it myself?

**Comment by Akemi** [comment] 2021-05-08 13:18
basically a duplicate of #3022.

**Closed by Akemi** 2021-05-08 13:18 UTC
Labels: core:option-param-conf, core:subtitle, meta:feature-request

**Comment by barraIhsan** [comment] 2025-03-20 06:14
> basically a duplicate of [#3022](https://github.com/mpv-player/mpv/issues/3022).

Hey sorry for the very late reply but,

> Or at least can change the font size?

It's not *yet* implemented. And neither #3022 nor #13073 added this. It would be nice to have `--secondary-sub-font-size` option
