### ISSUE TITLE
fallback support of wl_shell

### ISSUE THREAD

**Issue by pumbur** [mpv-player/mpv#6577] opened 2019-03-21 04:49 UTC
xdg_shell is overcomplicated shit and versioning of wayland protocols is clusterfuck. see #6110.
please return support of wl_shell as a fallback in case wm_base fails.

**Comment by pumbur** [comment] 2019-03-21 04:54
(wrote this patch quite a while ago, havent look at history)
```
diff --git a/video/out/wayland_common.c b/video/out/wayland_common.c
index a929c2619e..59ca5c9079 100644
--- a/video/out/wayland_common.c
+++ b/video/out/wayland_common.c
@@ -124,8 +124,11 @@ static void pointer_handle_motion(void *data, struct wl_pointer *pointer,
 
 static void window_move(struct vo_wayland_state *wl, uint32_t serial)
 {
-    if (wl->xdg_toplevel)
+    if (wl->xdg_toplevel) {
         xdg_toplevel_move(wl->xdg_toplevel, wl->seat, serial);
+    } else if (wl->wl_shell) {
+        wl_shell_surface_move(wl->wl_surface, wl->seat, serial);
+    }
 }
 
 static void pointer_handle_button(void *data, struct wl_pointer *wl_pointer,
@@ -804,6 +807,10 @@ static void registry_handle_add(void *data, struct wl_registry *reg, uint32_t id
         wl_list_insert(&wl->output_list, &output->link);
     }
 
+    if (!strcmp(interface, wl_shell_interface.name) && found++) {
+        wl->wl_shell = wl_registry_bind(reg, id, &wl_shell_interface, 1);
+    }
+
     if (!strcmp(interface, xdg_wm_base_interface.name) && found++) {
         ver = MPMIN(ver, 2); /* We can use either 1 or 2 */
         wl->wm_base = wl_registry_bind(reg, id, &xdg_wm_base_interface, ver);
@@ -876,6 +883,30 @@ static const struct xdg_surface_listener xdg_surface_listener = {
     handle_surface_config,
 };
 
+
+static void wl_shell_surface_configure(void *data, struct wl_shell_surface *wl_shell_surface, uint32_t edges, int32_t width, int32_t height){
+  struct vo_wayland_state *wl = data;
+  if (width > 0 && height > 0) {
+        wl->window_size.x0 = 0;
+        wl->window_size.y0 = 0;
+        wl->window_size.x1 = width;
+        wl->window_size.y1 = height;
+        wl->geometry.x0 = 0;
+        wl->geometry.y0 = 0;
+        wl->geometry.x1 = width;
+        wl->geometry.y1 = height;
+  }
+  wl->pending_vo_events |= VO_EVENT_RESIZE;
+}
+static void wl_shell_surface_ping(void *data, struct wl_shell_surface *wl_shell_surface, uint32_t serial){
+    wl_shell_surface_pong(wl_shell_surface, serial);
+}
+static const struct wl_shell_surface_listener wl_shell_surface_listener = {
+    wl_shell_surface_ping,
+    wl_shell_surface_configure,
+    NULL
+};
+
 static void handle_toplevel_config(void *data, struct xdg_toplevel *toplevel,
                                    int32_t width, int32_t height, struct wl_array *states)
 {
@@ -968,6 +999,16 @@ static int create_xdg_surface(struct vo_wayland_state *wl)
     return 0;
 }
 
+static int create_wl_surface(struct vo_wayland_state *wl)
+{
+    wl->wl_surface = wl_shell_get_shell_surface(wl->wl_shell, wl->surface);
+    wl_shell_surface_set_toplevel(wl->wl_surface);
+    wl_shell_surface_add_listener(wl->wl_surface, &wl_shell_surface_listener, wl);
+    wl_shell_surface_set_title (wl->wl_surface, "mpv");
+    wl_shell_surface_set_class(wl->wl_surface, "mpv");
+    return 0;
+}
+
 static int set_border_decorations(struct vo_wayland_state *wl, int state)
 {
     if (!wl->xdg_toplevel_decoration)
@@ -1013,11 +1054,6 @@ int vo_wayland_init(struct vo *vo)
     /* Do a roundtrip to run the registry */
     wl_display_roundtrip(wl->display);
 
-    if (!wl->wm_base) {
-        MP_FATAL(wl, "Compositor doesn't support the required %s protocol!\n",
-                 xdg_wm_base_interface.name);
-        return false;
-    }
 
     if (!wl_list_length(&wl->output_list)) {
         MP_FATAL(wl, "No outputs found or compositor doesn't support %s (ver. 2)\n",
@@ -1025,9 +1061,17 @@ int vo_wayland_init(struct vo *vo)
         return false;
     }
 
-    /* Can't be initialized during registry due to multi-protocol dependence */
-    if (create_xdg_surface(wl))
+    if (wl->wm_base) {
+        /* Can't be initialized during registry due to multi-protocol dependence */
+        if (create_xdg_surface(wl))
+            return false;
+    }else if (wl->wl_shell) {
+        if (create_wl_surface(wl))
+            return false;
+    } else {
+        MP_FATAL(wl, "Compositor doesn't support any surface protocol!\n");
         return false;
+    }
 
     if (wl->dnd_devman) {
         wl->dnd_ddev = wl_data_device_manager_get_data_device(wl->dnd_devman, wl->seat);
@@ -1078,6 +1122,12 @@ void vo_wayland_uninit(struct vo *vo)
     if (wl->idle_inhibit_manager)
         zwp_idle_inhibit_manager_v1_destroy(wl->idle_inhibit_manager);
 
+    if (wl->wl_surface)
+        wl_shell_surface_destroy(wl->wl_surface);
+
+    if (wl->wl_shell)
+        wl_shell_destroy(wl->wl_shell);
+
     if (wl->wm_base)
         xdg_wm_base_destroy(wl->wm_base);
 
@@ -1175,8 +1225,10 @@ int vo_wayland_reconfig(struct vo *vo)
             wl->geometry.y0  = 0;
             wl->geometry.x1  = mp_rect_w(wl->current_output->geometry)/wl->scaling;
             wl->geometry.y1  = mp_rect_h(wl->current_output->geometry)/wl->scaling;
-        } else {
+        } else if (wl->wm_base) {
             xdg_toplevel_set_fullscreen(wl->xdg_toplevel, wl_out);
+        } else if (wl->wl_shell) {
+            wl_shell_surface_set_fullscreen(wl->wl_surface, WL_SHELL_SURFACE_FULLSCREEN_METHOD_FILL, 0, wl->current_output->output);
         }
     }
 
@@ -1213,12 +1265,23 @@ static int set_screensaver_inhibitor(struct vo_wayland_state *wl, int state)
 
 static int toggle_fullscreen(struct vo_wayland_state *wl)
 {
-    if (!wl->xdg_toplevel)
-        return VO_NOTAVAIL;
-    if (wl->fullscreen)
+    if (wl->wm_base) {
+      if (wl->fullscreen) {
         xdg_toplevel_unset_fullscreen(wl->xdg_toplevel);
-    else
+      }else{
         xdg_toplevel_set_fullscreen(wl->xdg_toplevel, NULL);
+      }
+    } else if (wl->wl_shell) {
+      if (wl->fullscreen) {
+        wl_shell_surface_set_toplevel(wl->wl_surface);
+        wl->fullscreen = false;
+      }else{
+        wl_shell_surface_set_fullscreen(wl->wl_surface, WL_SHELL_SURFACE_FULLSCREEN_METHOD_FILL, 0, wl->current_output->output);
+        wl->fullscreen = true;
+      }
+    }else{
+        return VO_NOTAVAIL;
+    }
     return VO_TRUE;
 }
 
diff --git a/video/out/wayland_common.h b/video/out/wayland_common.h
index 0648efa09a..c4aef287b5 100644
--- a/video/out/wayland_common.h
+++ b/video/out/wayland_common.h
@@ -70,6 +70,8 @@ struct vo_wayland_state {
 
     /* Shell */
     struct wl_surface       *surface;
+    struct wl_shell         *wl_shell;
+    struct wl_shell_surface *wl_surface;
     struct xdg_wm_base      *wm_base;
     struct xdg_toplevel     *xdg_toplevel;
     struct xdg_surface      *xdg_surface;
```

**Comment by linkmauve** [comment] 2019-03-21 12:27
With every compositor now supporting xdg-shell stable (Weston being the last one, in its 6.0 version released next Wednesday), there is really no reason to go as far back as wl_shell support today.

I recommend updating your compositor, and closing this issue.

**Comment by pumbur** [comment] 2019-03-21 13:02
i can patch stuff for myself, so its non-issue for me anyway. anyone, feel free to close if its non-critical.

however i would like to point that it's broken on reference implementation of wayland for about a year, and could be broken again on new versions. wl_shell /is stable/.

(i also could snark at your "every compositor", but whatever, its mostly wayland devs fault anyway)

**Closed** 2019-03-21 13:12 UTC

**Comment by ubone** [comment] 2019-04-28 06:34
it's broken in enlightenment (which is otherwise ok) but idk what the issue is there
