### ISSUE TITLE
ICC-profile-auto not loading

### ISSUE THREAD

**Issue by phydano** [mpv-player/mpv#3241] opened 2016-06-12 04:09 UTC
Hi,

After update mpv to the latest version `git-bb9aad0` on MAC OSX Capitan 10.11.5, my usual line in config file doesn't seem to work (`vo=opengl-hq:icc-profile-auto`). The color profile doesn't seem to load and I check the log for error but no errors. Is there anything change?

**Comment by haasn** [comment] 2016-06-16 07:36
Do you know which commit causes the regression?

**Comment by phydano** [comment] 2016-06-17 03:11
I don't know which one....I came from version `git-1944a34` which is in April.

**Comment by wm4** [comment] 2016-06-17 08:23
@haasn can you confirm that icc profile switching works on X11?

**Comment by haasn** [comment] 2016-06-17 09:03
Works fine for me. (Btw, is it intentional that mpv queries the ICC profile every single time you move the window?

```
[global] user path: '/tmp/mpv-icc' -> '/tmp/mpv-icc'
[vo/opengl-hq] Opening 3D LUT cache in file '/tmp/mpv-icc/8C357E215FD50BA92B6B14C9172616BF86F25E3ACFE797DF62DA22AC5771894A'.
[global] user path: '/tmp/mpv-icc/8C357E215FD50BA92B6B14C9172616BF86F25E3ACFE797DF62DA22AC5771894A' -> '/tmp/mpv-icc/8C357E215FD50BA92B6B14C9172616BF86F25E3ACFE797DF62DA22AC5771894A'
[ifo] Opening /tmp/mpv-icc/8C357E215FD50BA92B6B14C9172616BF86F25E3ACFE797DF62DA22AC5771894A
[ifo/dvdnav] Opening /tmp/mpv-icc/8C357E215FD50BA92B6B14C9172616BF86F25E3ACFE797DF62DA22AC5771894A
[file] Opening /tmp/mpv-icc/8C357E215FD50BA92B6B14C9172616BF86F25E3ACFE797DF62DA22AC5771894A
[file] Stream opened successfully.
[vo/opengl-hq] Dither to 10.
[vo/opengl-hq/x11] Current display FPS: 59.998457
[vo/opengl-hq] Querying ICC profile...
[vo/opengl-hq/x11] Retrieving ICC profile for display: 1
[vo/opengl-hq] Assuming 59.998457 FPS for display sync.
[statusline] AV: 00:00:17.039 / 00:03:45.698 (7%) A-V: -0.003 DS: 2.000/25 Dropped: 23
[vo/opengl-hq] Querying ICC profile...
[vo/opengl-hq/x11] Retrieving ICC profile for display: 1
[vo/opengl-hq] Create FBO: 2052x1154 (2304x1280)
[vo/opengl-hq] Querying ICC profile...
[vo/opengl-hq/x11] Retrieving ICC profile for display: 1
[statusline] AV: 00:00:17.080 / 00:03:45.698 (7%) A-V: -0.003 DS: 2.000/25 Dropped: 23
[vo/opengl-hq] Querying ICC profile...
[vo/opengl-hq/x11] Retrieving ICC profile for display: 1
[vo/opengl-hq] Create FBO: 2052x1154 (2304x1280)
[vo/opengl-hq] Querying ICC profile...
[vo/opengl-hq/x11] Retrieving ICC profile for display: 1
[statusline] AV: 00:00:17.120 / 00:03:45.698 (7%) A-V: -0.003 DS: 2.000/26 Dropped: 23
[vo/opengl-hq] Querying ICC profile...
[vo/opengl-hq/x11] Retrieving ICC profile for display: 1
...
```

(this is during continuous motion, starting from the point I moved it between displays)

**Comment by wm4** [comment] 2016-06-17 09:38
> Btw, is it intentional that mpv queries the ICC profile every single time you move the window?

If you look at vo_x11_update_geometry, it's quite dumb and doesn't check whether the screen changes. It could try being slightly more clever.

I'm more worried about the FBO message. If the ICC profile is the same, it should be doing nothing.

**Comment by Akemi** [comment] 2016-12-03 16:35
did you by chance also use `icc-cache-dir`? i had a similar problem and after deleting the cached files it worked again.

**Comment by haasn** [comment] 2016-12-03 23:03
The ICC cache file uses a unique name based on the hash of the configuration, version , video parameters and ICC profile. Removing the ICC cache file should never be necessary.

(Unless a bug was fixed in LittleCMS and you're linking against a newer version)

**Comment by wm4** [comment] 2016-12-03 23:17
We could even dump the LCMS version into the cache header.

But do we really need the cache anyway?

**Comment by Akemi** [comment] 2016-12-04 21:19
i found one bug in the cocoa code. in some circumstances it doesn't chose the colour profile of the currently active screen but always of the one it was launched on. this was also the problem i had and not the cached files like assumed before. though i don't really if this bug is related to this issue. i would need more informations for that.

**Comment by Akemi** [comment] 2017-01-20 01:31
can't reproduce and not enough info.

**Closed by Akemi** 2017-01-20 01:31 UTC
Labels: info-needed, osx

**Comment by phydano** [comment] 2017-01-20 02:15
Hi,

I just updated to the latest version of the commit (a35ab55). When I used icc-profile-auto it gives me [this](https://www.dropbox.com/s/xswyfh82mhe7zag/ICC-Profile-Auto%20failed.png?dl=0)  error message. Maybe its not that ICC profile auto is not loading but rather it is loaded but ended up revert back...my ICC profile is a default one that come with the MACbook.  

I also checked the log and search for "[e]" in case of an error but nothing is reported as error....

**Comment by Akemi** [comment] 2017-01-20 12:52
it is loading the ICC profile properly and this warning is expected.

the profiles shipped with any Mac are not calibrated to the display used but just generic. the display is setup so they look 'properly' when used with the standard profile. the problem here is that those profiles have a generic values set to peak brightness and the lowest black level, which results in a enormous and unreachable contrast. mpv detects that and sets a saner value. you can only avoid that in setting the mentioned option in the warning or by calibrating your display with a colorimeter or better.
