### ISSUE TITLE
HDR playback seems broken in Archlinux + Sway

### ISSUE THREAD

**Issue by ekk1** [mpv-player/mpv#12364] opened 2023-09-09 08:46 UTC
### Important Information

Provide following Information:
- mpv version:  0.36.0
- Linux Distribution and Version:  Archlinux with 6.4.12-arch1-1 kernel
- Source of the mpv binary:  Arch repo
- If known which version of mpv introduced the problem:   not sure
- Window Manager and version:   Sway 1.8.1
- GPU driver and version:   Intel iHD driver 23.3.1
- Possible screenshot or video of visual glitches
![20230909_16h15m58s_grim.png](https://s2.loli.net/2023/09/09/PEN5BjTJV4fk6Ax.png)

### Reproduction steps

Using a surface pro 8, i5 + 16GB model with bulitin display.
Install Archlinux with latest iso, and install mpv from the official repo, and play a HDR video.
My desktop environment is install with these packages:
pacman -S \
    sway swaybg swayidle swaylock foot dmenu gammastep \
    xorg-xwayland qt5-wayland qt6-wayland qt5ct \
    polkit pipewire-pulse pavucontrol \
    i3blocks i3status intel-gpu-tools \
    intel-media-driver mpv libva-utils \
    chromium firefox hyprland dolphin

Sway is started with `sway` command under tty, although I tried with gdm, and the result is the same.
Also, I tried with gdm + GNOME, and the result is also the same.
There are some grid patterns all over the video, and some frames will frozen and repeat on next frames. This behavior is only observed in HDR videos, SDR video seems fine.
I also tried with --no-config and --vo=gpu-next, and all kinds of tone-mapping methods, but all seems the same with this grid pattern and frozen frames.
VLC seems OK, but the color is not mapping correctly.

### Expected behavior

Normal playback

### Actual behavior

Some grid patterns and partially frozen frames that will last for a while

### Log file

https://0x0.st/HfSz.txt

### Sample files

Harry.Potter.and.the.Sorcerers.Stone.2001.2160p.UHD.BluRay.x265.10bit.HDR.DTS-X.7.1-RARBG.mkv

This is too big for upload, and i also tried other HDR videos, all present the same problem.

**Comment by llyyr** [comment] 2023-09-09 08:51
`I also tried with --no-config and --vo=gpu-next`

Can you upload that log instead? This current one has `hwdec=auto` which is highly likely to be the cause

**Comment by ekk1** [comment] 2023-09-09 08:57
thanks for the quick reply, new log is here

https://0x0.st/HfSo.txt

and hwdec seems not relevant, with --no-config, the problem is still present

**Comment by ekk1** [comment] 2023-09-09 08:58
sorry, the last one only has no-config, this one is with both options

https://0x0.st/HfSX.txt

**Comment by ekk1** [comment] 2023-09-09 09:03
Don't know if this helps, I've tried various combinations recently
With this same device, using Debian 12 + GNOME + mpv from debian official repo (0.35.1) , or Debian + Sway, these two works fine with HDR videos, and Archlinux with Sway or GNOME didn't.

**Comment by llyyr** [comment] 2023-09-09 09:10
Things to try: `--gpu-api-vulkan`, `--gpu-context=x11vk` / `x11egl`

**Comment by ekk1** [comment] 2023-09-09 09:21
thanks a lot, i presume --gpu-api-vulkan is the same as --gpu-api=vulkan ? the former one seems not present in Arch's mpv.

with `--gpu-api=vulkan` alone and `--gpu-context=x11vk` alone all seems working, the grid pattern is gone and playback seems normal, `--gpu-context=x11egl` alone will still cause the problem, all three tested with hwdec=auto and no, result is the same. 

vo seems to become wlshm, here are some logs from stdout

Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
[vo/vdpau] Error when calling vdp_device_create_x11: 1
[ffmpeg] AVHWDeviceContext: Cannot load libcuda.so.1
[ffmpeg] AVHWDeviceContext: Could not dynamically load CUDA
Using hardware decoding (vaapi-copy).
AO: [pipewire] 48000Hz 7.1 8ch s32p
VO: [wlshm] 3840x1600 p010

current solution seems acceptable now, again thanks very much

**Comment by llyyr** [comment] 2023-09-09 09:32
> i presume --gpu-api-vulkan is the same as --gpu-api=vulkan

Yes, it was a typo.

> with --gpu-api=vulkan alone and --gpu-context=x11vk alone all seems working

This would point to some kind of Mesa EGL issue, I'd recommend trying to see if you can reproduce this issue on Arch with mpv 0.35.1 or not and opening a Mesa ticket if you can reproduce it regardless of mpv version. Also try `--no-hidpi-window-scale` since you seem to have scale set to 2 in sway.

> vo seems to become wlshm

This shouldn't happen. What happens if you run `mpv --no-config --vo=gpu-next --gpu-api=vulkan [video]`?

**Comment by ekk1** [comment] 2023-09-09 09:39
with `mpv --no-config --vo=gpu-next --gpu-api=vulkan [video]`, mpv will exit with following error:
[vo/gpu-next] Failed initializing any suitable GPU context!
Error opening/initializing the selected video_out (--vo) device.
Video: no video

log file is here
https://0x0.st/HfSQ.txt

`--no-hidpi-window-scale` doesn't seems to cause any different

I will try older version mpv later and report back.

**Comment by llyyr** [comment] 2023-09-09 09:55
Vulkan doesn't work, EGL is broken... something seems very wrong with your Mesa install

```
[   0.024][v][vo/gpu-next/libplacebo] Failed creating instance: VK_ERROR_INCOMPATIBLE_DRIVER
[   0.024][v][vo/gpu-next/libplacebo] Failed initializing vulkan instance
```
Can you run `vulkaninfo`?

**Comment by ekk1** [comment] 2023-09-09 11:17
sorry for the delay, was out for a while.

>Can you run vulkaninfo? Either way, I'd be very very surprised if this was a mpv issue

you are right... vulkan driver is actually not installed, i wasn't aware of that at all...

ERROR: [Loader Message] Code 0 : vkCreateInstance: Found no drivers!                                                                                   
Cannot create Vulkan instance.                                                                                                                         
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.                    
ERROR at /usr/src/debug/vulkan-tools/Vulkan-Tools-1.3.255/vulkaninfo/vulkaninfo.h:676:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER           

after installing `vulkan-intel` , `--vo=gpu-next --gpu-api=vulkan` works well now, and the color also seems better now, especially in some anime 4k hdr videos.

running mpv without `--gpu-api=vulkan` is still not working though, but current option seems working quite well now. Thanks for the advice.

**Comment by Traneptora** [comment] 2023-09-09 13:08
If you don't explicitly set `--gpu-api=vulkan` it'll fall back to OpenGL, and you might not have those drivers installed either.

**Comment by ekk1** [comment] 2023-09-09 13:32
> If you don't explicitly set --gpu-api=vulkan it'll fall back to OpenGL, and you might not have those drivers installed either.

might be true, but i'm not sure about it
Arch wiki shows that installing `mesa` should be enough, and `eglinfo` didn't show any error.

Also I've reproduced this on another pc, with 13th gen Intel CPU and iGPU, and the vulkan workaround also worked, I think i may have some packages missing...

**Comment by aicynide** [comment] 2023-09-10 07:08
<details>
Imagine using sway
</details>

**Comment by flipflop133** [comment] 2023-09-18 18:49
I have the same issue on arch+i3, with an intel gpu (Intel TigerLake-LP GT2) and this:

> after installing `vulkan-intel` , `--vo=gpu-next --gpu-api=vulkan` works well now, and the color also seems better now, especially in some anime 4k hdr videos.

also fixed my issue.

**Comment by OSLDNKKfEUVTABDLiNgk** [comment] 2023-09-24 16:23
I have the same issue with HDR files. I tested HDR, HRD10, HDR10+, and Dolby Vision files encoded with av1 or HEVC. All exhibited the same bug. Celluloid and MPV are affected with and without hardware acceleration. Confirmed the files are fine by playing them in VLC.

Specs:
```
Fedora 38 (GNOME 44.5 + Wayland)
Kernel 6.4.15-200.fc38.x86_64 
12th Gen Intel i7-1280P (20) @ 4.700GHz 

MPV
[cplayer] mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
[cplayer]  built on UNKNOWN
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       58.2.100
[cplayer]    libavcodec      60.3.100
[cplayer]    libavformat     60.3.100
[cplayer]    libswscale      7.1.100
[cplayer]    libavfilter     9.3.100
[cplayer]    libswresample   4.10.100
[cplayer] FFmpeg version: 6.0
[cplayer] 
[cplayer] Configuration: /usr/bin/waf configure --prefix=/usr --bindir=/usr/bin --libdir=/usr/lib64 --mandir=/usr/share/man --docdir=/usr/share/doc/mpv --confdir=/etc/mpv --disable-build-date --enable-libmpv-shared --enable-sdl2 --enable-libarchive --enable-dvdnav --enable-cdda --enable-html-build --enable-dvbin --enable-gl-x11 --enable-wayland
[cplayer] List of enabled features: alsa asm av-channel-layout caca cdda cplayer cplugins cuda-hwaccel cuda-interop debug-build dmabuf-interop-gl dmabuf-interop-pl dmabuf-wayland drm drm-is-kms dvbin dvdnav egl egl-drm egl-helpers egl-x11 ffmpeg ffnvcodec gbm gbm.h gl gl-wayland gl-x11 glibc-thread-name glob glob-posix gpl iconv jack javascript jpeg jpegxl lcms2 libarchive libass libavdevice libbluray libdl libm libmpv-shared libplacebo libplacebo-next librt linux-fstatfs linux-input-event-codes lua lua_5_1 memfd_create optimize pipewire plain-gl posix posix-or-mingw pthreads pulse rubberband rubberband-3 sdl2 sdl2-audio sdl2-gamepad sdl2-video shaderc shaderc-shared stdatomic uchardet vaapi vaapi-drm vaapi-egl vaapi-libplacebo vaapi-wayland vaapi-x-egl vaapi-x11 vapoursynth vdpau vdpau-gl-x11 vector vt.h vulkan wayland wayland-protocols wayland-protocols-1-24 x11 xv zimg zlib
[cplayer] Reading config file /etc/mpv/encoding-profiles.conf
[cplayer] Applying profile 'default'...
[cplayer] Setting option 'v' = '' (flags = 8)
[cplayer] mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
[cplayer]  built on UNKNOWN
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       58.2.100
[cplayer]    libavcodec      60.3.100
[cplayer]    libavformat     60.3.100
[cplayer]    libswscale      7.1.100
[cplayer]    libavfilter     9.3.100
[cplayer]    libswresample   4.10.100
[cplayer] FFmpeg version: 6.0
[cplayer] 
[cplayer] Usage:   mpv [options] [url|path/]filename
[cplayer] 
[cplayer] Basic options:
[cplayer]  --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
[cplayer]  --no-audio        do not play sound
[cplayer]  --no-video        do not play video
[cplayer]  --fs              fullscreen playback
[cplayer]  --sub-file=<file> specify subtitle file to use
[cplayer]  --playlist=<file> specify playlist file
[cplayer] 
[cplayer]  --list-options    list all mpv options
[cplayer]  --h=<string>      print options which contain the given string in their name
[cplayer] 
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Set property: shared-script-properties -> 1
```

**Comment by Traneptora** [comment] 2023-09-25 01:09
Can you reproduce it with `--vo=gpu-next` as well?

**Comment by llyyr** [comment] 2023-09-25 01:38
It's possible there's some intel regression here, if it works with --gpu-api=vulkan for you as well but not with opengl

**Comment by llyyr** [comment] 2023-09-25 01:46
Yes, I can reproduce this issue with my Intel iGPU with the opengl api. Please report the bug to Mesa instead

**Comment by llyyr** [comment] 2023-09-25 02:33
It's already been reported upstream: https://gitlab.freedesktop.org/drm/intel/-/issues/9118

Related issue: #12204

**Comment by llyyr** [comment] 2023-10-13 18:09
Supposedly fixed upstream https://gitlab.freedesktop.org/drm/intel/-/issues/9118#note_2127262

**Comment by jeeb** [comment] 2023-10-13 18:10
Closing as apparently upstream has handled this.

**Closed by jeeb** 2023-10-13 18:10 UTC
Labels: down-upstream:intel, os:linux
