### ISSUE TITLE
10 bit VAAPI decoding with Vulkan GPU API fails on hwdec=vaapi, but works on hwdec=vaapi-copy

### ISSUE THREAD

**Issue by baybal** [mpv-player/mpv#8668] opened 2021-03-21 12:34 UTC
### Important Information

Provide following Information:
- mpv version git master latest 20.3.2020
- Linux Distribution and Version Gentoo Linux 2021
- Source of the mpv binary self compiled
- If known which version of mpv introduced the problem - 
- Window Manager and version xfwm4
- GPU driver and version mesa git, depth30 branch
- Possible screenshot or video of visual glitches
- ![image](https://user-images.githubusercontent.com/3344988/111904372-ed788180-8a70-11eb-8930-7dbc74d8af92.png)

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

1. Install linux kernel 5.11
2. Install depth30 branch of mesa from https://gitlab.freedesktop.org/haasn/mesa/-/tree/depth30
3. Install libva from git master
4. Install GMM lib from git master https://github.com/intel/gmmlib
5. Install intel-media driver from git master https://github.com/intel/media-driver
6. Set X11 video driver to modesetting
7. Set DefaultDepth    30 in X11 Screen settings
```
Section "Screen"
          Identifier    "Default Screen"
          Monitor        "Configured Monitor"
          Device         "Configured Video Device"
#        24 for 8-bit or 30 for 10-bit
          DefaultDepth    30
#        DefaultDepth    24
EndSection
```
8. Set config to
```
vo=gpu
hwdec=vaapi
gpu-api=vulkan
gpu-context=x11vk
```
9. Launch mpv to and play any vaapi decodable video
10. Get blue screen
11. Set config to
```
vo=gpu
hwdec=vaapi-copy
gpu-api=vulkan
gpu-context=x11vk
```
11. Launch mpv and play any vaapi decodable video
12. Video will play

### Expected behavior
Video plays

### Actual behavior
Video not playing, and error message is `[vo/gpu/vaapi-egl] unsupported VA image format p010`

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/6177379/mpv.log)

The issue will be closed for ignoring the issue template.

### Sample files

https://0x0.st/-NFs.mp4

**Comment by baybal** [comment] 2021-03-21 12:49
I also noted that setting `hwdec-image-format=rgb30` fixes the issue

**Comment by haasn** [comment] 2021-03-21 13:13
This should be completely unrelated to the `depth30` mesa patch. I'm not sure why that's in your reproducing instructions, but is it possible that you're effectively just observing the effects of comparing mesa's git master vs mesa's latest release? Can you confirm that this is a regression caused simply by updating mesa?

Also, according to your log, both `p010` and `rgb30` are not supported by `vaapi-egl`:
```
[vo/gpu/vaapi-egl] Supported formats:
[vo/gpu/vaapi-egl]  yuv420p
[vo/gpu/vaapi-egl]  rgba
[vo/gpu/vaapi-egl]  bgra
[vo/gpu/vaapi-egl]  rgb0
[vo/gpu/vaapi-egl]  argb
[vo/gpu/vaapi-egl]  abgr
```

So even with `--hwdec-image-format=rgb30` it should not be working for you. Can you post a log of it using rgb30? Are you sure it's not just falling back to software decoding in that case? And it seems like the real bug here is, in part, figuring out why it doesn't fall back to software decoding for p010 as well, but rather results in a blue screen.

(P.s., how come your logs are weirdly different from the normal mpv log format? It's missing timing information and message level, which makes it harder to find errors than it should be.)

**Comment by baybal** [comment] 2021-03-21 14:58
[mpv_30bit.log](https://github.com/mpv-player/mpv/files/6177653/mpv_30bit.log)

**Comment by baybal** [comment] 2021-03-21 15:00
[mpv_30bit_timestamps.log](https://github.com/mpv-player/mpv/files/6177659/mpv_30bit_timestamps.log)

**Comment by haasn** [comment] 2021-03-21 15:08
```
Error while decoding frame (hardware decoding)!
[vd] Falling back to software decoding.
```

So yeah, `rgb30` does not actually work. It just successfully falls back to swdec in this case.

(Also, in case it wasn't clear, using `--log-file` is what produces the log files in the format we expect them in.)

**Comment by baybal** [comment] 2021-03-21 15:12
> So yeah, rgb30 does not actually work. It just successfully falls back to swdec in this case.

`hwdec=vaapi-copy` works though

[mpv_vaapi_copy.log](https://github.com/mpv-player/mpv/files/6177673/mpv_vaapi_copy.log)

**Comment by haasn** [comment] 2021-03-21 15:22
Right, but that's `p010` and not `rgb30`. Anyway, the main question here is why `p010` is not accepted by vaapi<->vulkan bridge for you. It works on my end (amd/radv):

```
vo/gpu/vaapi-egl: Supported formats:
vo/gpu/vaapi-egl:  nv12
vo/gpu/vaapi-egl:  p010
vo/gpu/vaapi-egl:  bgra
vo/gpu/vaapi-egl:  rgba
vo/gpu/vaapi-egl:  bgr0
vo/gpu/vaapi-egl:  rgb0
```

So that means the bug must be intel-specific, probably somewhere inside the anv driver code.

**Comment by baybal** [comment] 2021-03-21 15:33
If I try with `hwdec-image-format=p010`

I see blue screen and 

`[vo/gpu/vaapi-egl] unsupported VA image format p010`

For every other format, it falls back to software decode

**Comment by baybal** [comment] 2021-03-21 15:36
I need more volunteers to test depth30 on Nvidia, and Intel

**Comment by baybal** [comment] 2021-03-21 15:38
@haasn by the way, how is depth30 merge progressing? We will surely have more people trying this if it will get into 21.0

**Comment by haasn** [comment] 2021-03-21 15:44
Unfortunately I can't really debug this without access to hardware I can reproduce it on. If you're comfortable using gdb, I basically need to explore this code path:

`(gdb) break try_format_pixfmt if pixfmt == AV_PIX_FMT_P010LE`
and then just keep stepping through that function, especially into the `try_format_map` call, to see where it fails.

> by the way, how is depth30 merge progressing? We will surely have more people trying this if it will get into 21.0. And it will get more attention from Intel.

I have no idea. Ask the mesa maintainers, I am not one of them. Also, that patch is entirely unrelated to this issue. The `depth30` branch you're referencing is about **30-bit *output***, but this bug is about **30-bit decoding**. The two have absolutely nothing to do with each other except that they both have something to do with 30 bit formats.

**Comment by baybal** [comment] 2021-03-21 16:43
> I have no idea. Ask the mesa maintainers, I am not one of them. Also, that patch is entirely unrelated to this issue. The depth30 branch you're referencing is about 30-bit output, but this bug is about 30-bit decoding. The two have absolutely nothing to do with each other except that they both have something to do with 30 bit formats.

Yes, but nobody can test 30 bit decoding on Intel with Vulkan, until mesa supports it.

**Comment by haasn** [comment] 2021-03-21 18:04
> Yes, but nobody can test 30 bit decoding on Intel with Vulkan, until mesa supports it.

This is just not true. You can use 30-bit decoding on an 8-bit display. You can also use 8-bit decoding on a 30-bit display. Again, the two have nothing to do with each other.

**Comment by philipl** [comment] 2021-03-21 18:19
Additionally, the logs actually show surface format mapping working - the actual decode is what fails:

```
[  0.123619] ffmpeg/video: hevc: Considering format 0x30313050 -> p010le.
[  0.123624] ffmpeg/video: hevc: Picked p010le (0x30313050) as best match for yuv420p10le.
[  0.123649]     ffmpeg: AVHWFramesContext: Created surface 0.
[  0.123659]     ffmpeg: AVHWFramesContext: Direct mapping possible.
[  0.123670]     ffmpeg: AVHWFramesContext: Created surface 0x1.
[  0.123677]     ffmpeg: AVHWFramesContext: Created surface 0x2.
[  0.123684]     ffmpeg: AVHWFramesContext: Created surface 0x3.
[  0.123690]     ffmpeg: AVHWFramesContext: Created surface 0x4.
[  0.123698]     ffmpeg: AVHWFramesContext: Created surface 0x5.
[  0.123705]     ffmpeg: AVHWFramesContext: Created surface 0x6.
[  0.123712]     ffmpeg: AVHWFramesContext: Created surface 0x7.
[  0.123721]     ffmpeg: AVHWFramesContext: Created surface 0x8.
[  0.123728]     ffmpeg: AVHWFramesContext: Created surface 0x9.
[  0.123735]     ffmpeg: AVHWFramesContext: Created surface 0xa.
[  0.123742]     ffmpeg: AVHWFramesContext: Created surface 0xb.
[  0.123748]     ffmpeg: AVHWFramesContext: Created surface 0xc.
[  0.123755]     ffmpeg: AVHWFramesContext: Created surface 0xd.
[  0.123761]     ffmpeg: AVHWFramesContext: Created surface 0xe.
[  0.123768]     ffmpeg: AVHWFramesContext: Created surface 0xf.
[  0.123774]     ffmpeg: AVHWFramesContext: Created surface 0x10.
[  0.123781]     ffmpeg: AVHWFramesContext: Created surface 0x11.
[  0.123789]     ffmpeg: AVHWFramesContext: Created surface 0x12.
[  0.123796]     ffmpeg: AVHWFramesContext: Created surface 0x13.
[  0.123804]     ffmpeg: AVHWFramesContext: Created surface 0x14.
[  0.123811]     ffmpeg: AVHWFramesContext: Created surface 0x15.
[  0.123818]         vd: Requesting pixfmt 'vaapi_vld' from decoder.
[  0.123821] ffmpeg/video: hevc: Format vaapi_vld chosen by get_format().
[  0.123824] ffmpeg/video: hevc: Format vaapi_vld requires hwaccel initialisation.
[  0.123832] ffmpeg/video: hevc: Considering format 0x30313050 -> p010le.
[  0.123835] ffmpeg/video: hevc: Picked p010le (0x30313050) as best match for yuv420p10le.
[  0.124224] ffmpeg/video: hevc: Decode context initialised: 0x16/0x10000000.
[  0.126108] ffmpeg/video: hevc: Output frame with POC 0.
[  0.126138] ffmpeg/video: hevc: Param buffer (type 0, 604 bytes) is 0.
[  0.126143] ffmpeg/video: hevc: Slice 0 param buffer (264 bytes) is 0x1.
[  0.126593] ffmpeg/video: hevc: Slice 0 data buffer (5073 bytes) is 0x2.
[  0.126600] ffmpeg/video: hevc: Decode to surface 0x15.
[  0.126635] ffmpeg/video: hevc: Failed to end picture decode issue: 18 (invalid parameter).
[  0.126642] ffmpeg/video: hevc: hardware accelerator failed to decode picture
[  0.126651]         vd: Error while decoding frame (hardware decoding)!
[  0.126685] ffmpeg/video: hevc: nal_unit_type: 1(TRAIL_R), nuh_layer_id: 0, temporal_id: 0
[  0.126734]       lavf: bytes=46112, read_more=0 prefetch_more=0, refresh_more=0
[  0.126929] ffmpeg/video: hevc: Could not find ref with POC 0
[  0.128439] ffmpeg/video: hevc: Output frame with POC 1.
[  0.128454] ffmpeg/video: hevc: Param buffer (type 0, 604 bytes) is 0x2.
[  0.128459] ffmpeg/video: hevc: Slice 0 param buffer (264 bytes) is 0x1.
[  0.128465] ffmpeg/video: hevc: Slice 0 data buffer (239 bytes) is 0.
[  0.128468] ffmpeg/video: hevc: Decode to surface 0x14.
[  0.128486] ffmpeg/video: hevc: Failed to end picture decode issue: 18 (invalid parameter).
[  0.128490] ffmpeg/video: hevc: hardware accelerator failed to decode picture
[  0.128496]         vd: Error while decoding frame (hardware decoding)!
```

You're using a bleeding edge vaapi driver and mesa. Maybe there's a bug.

**Comment by baybal** [comment] 2021-03-23 13:35
I still had it with 20.4.5 intel media driver

**Comment by baybal** [comment] 2021-03-23 14:27
> try_format_pixfmt

It doesn't seem to find try_format_pixfmt

**Comment by baybal** [comment] 2021-03-29 22:09
From `try_format_map`
![image](https://user-images.githubusercontent.com/3344988/112905101-aee76480-910b-11eb-8537-08b25dd751de.png)

**Comment by haasn** [comment] 2021-03-29 22:22
@baybal can you step from there into `vaapi_vk_map` and from there into `pl_tex_create`? If so, can you step into `vk_malloc_import`?

**Comment by laichiaheng** [comment] 2021-05-07 13:48
I always get blue screen while playing videos with Vulkan vaapi.
```
vainfo: VA-API version: 1.11 (libva 2.11.1)
vainfo: Driver version: Mesa Gallium driver 21.0.3 for Radeon RX 580 Series (POLARIS10, DRM 3.40.0, 5.12.1-arch1-1, LLVM 11.1.0)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
```

**Comment by laichiaheng** [comment] 2021-05-08 07:34
@Akemi Should I open a new issue or just comment in this issue?

**Comment by haasn** [comment] 2021-05-08 12:59
@laichiaheng I believe your issue may be fixed in libplacebo master already (also backported to v3.120.3)

**Comment by haasn** [comment] 2021-05-11 16:26
That seems like the correct behavior in this case (with drivers that don't support modifiers).

**Comment by baybal** [comment] 2021-05-12 06:19
Sorry for suddenly going missing. I don't have time these days to dive into it with a debugger, but I will try to at least check if this works on a newer libplacebo

**Comment by akarshanbiswas** [comment] 2021-05-13 06:07
@laichiaheng I have the same series GPU and I am getting the same blue screen and exactly the same error as well.
I think these drivers for these GPUs  don't support DRM modifiers.  :(

Can't wait for [Vulkan Video](https://www.khronos.org/blog/an-introduction-to-vulkan-video) enough !

**Comment by snizovtsev** [comment] 2021-07-11 12:44
I've caught this bug on my archlinux laptop with skylake graphics and GNOME/Wayland as compositor.

mpv 0.33.1 + 7c4465cefb27d4e0d07535d368febdf77b579566 [cherry-picked](https://github.com/archlinux/svntogit-community/blob/f5863347a75ed140ecc2c245d8a64646fc93c795/trunk/PKGBUILD#L40) by arch team
libplacebo 3.120.3-2

I've tried to build mpv manually from master and it starts working fine since 968faef (found by bisecting). Now I've cherry-picked both of the commits on top of 0.33.1 and the issue has gone from my hardware.

**Comment by Dudemanguy** [comment] 2021-07-21 20:08
Apparently it has been fixed.

**Closed by Dudemanguy** 2021-07-21 20:08 UTC
Labels: hwdec:vaapi, os:linux, vo:gpu:vulkan
