### ISSUE TITLE
(Windows) mpv not placing window properly on the screen

### ISSUE THREAD

**Issue by floppyD** [mpv-player/mpv#6695] opened 2019-05-05 22:04 UTC
### mpv version and platform
mpv 0.29.0-318-g71ad1e2f4c
Windows 7

### Reproduction steps
Open a video with the same aspect ratio, with an equal or higher resolution than your current desktop resolution

### Expected behavior
Window fits perfectly on the screen

### Actual behavior
Part of the window is outside of the screen area

That's how it looks like when you open a video (1440x1080 video on a monitor using a resolution of 1440x1080):
![image](https://user-images.githubusercontent.com/29208110/57200902-a14cf280-6f67-11e9-971f-d1ac073014ca.png)
And for the sake of comparison, that's how the same file looks when opened with Baka MPlayer (a media player based on libmpv):
![image](https://user-images.githubusercontent.com/29208110/57200967-72834c00-6f68-11e9-8422-c9923bf6b092.png)

**Comment by Akemi** [comment] 2019-05-05 22:08
`--autofit` or `--autofit-larger`.

**Comment by floppyD** [comment] 2019-05-05 22:15
I'm aware that this kinda works, but it's not perfect and not a fix. I myself have been using "autofit-larger=88%" for a while on my main machine, but I just noticed when I installed mpv on this machine that this bug is still around and thought it would be nice that it was fixed. It also doesn't seem to happen under many Linux distros I've tested so far, so it's probably just a Windows thing.

**Comment by Akemi** [comment] 2019-05-05 22:34
yes windowing is system specific. try with an up-to-date mpv. 0.29 is rather old already and not the latest release. also i am not sure if we even support window 7 anymore. if it is reproducible on windows 10 that would be another thing.

also this sounds like something already fixed with https://github.com/mpv-player/mpv/commit/edbe25f38a2d5867dec066288cb61adf6191f327. i will reopen this if the issue persist on the latest mpv (master).

**Comment by floppyD** [comment] 2019-05-05 23:03
How this is old? I'm using a recent build, based on g71ad1e2f4c, committed on April 25. And yes, this is reproducible on Windows 10.
![new](https://user-images.githubusercontent.com/29208110/57201549-9d719e00-6f70-11e9-8876-9c2c7bd3cab7.png)

**Comment by Akemi** [comment] 2019-05-06 05:28
may bad i only looked at the version and not at the commit hash.

**Comment by jimmy-1000** [comment] 2021-03-11 04:18
mpv 0.33 still has this problem, please fix.
Old players like MPC doesn't have this issue, it calculates exactly the center position between task bar and top of window.

**Comment by jimmy-1000** [comment] 2021-03-12 19:57
> 
> 
> may bad i only looked at the version and not at the commit hash.

mpv 0.33 still has this problem, please fix.
Old players like MPC doesn't have this issue, it calculates exactly the center position between task bar and top of window.

**Comment by avih** [comment] 2021-04-13 16:59
Have a look also at #7755, which suggests that autofit might help - as mentioned earlier here.

**Comment by jimmy-1000** [comment] 2021-04-13 23:59
> 
> 
> Have a look also at #7755, which suggests that autofit might help - as mentioned earlier here too.

No, autofit, autofit larger and geometry don't solve the issue, because you can take a vertical video 1080x1920 and calculate the exactly position between task bar and top of screen, but the problem is that this affects the rest of videos with different resolutions and horizontal videos too.

**Comment by avih** [comment] 2021-04-14 03:05
> but the problem is that this affects the rest of videos with different resolutions and horizontal videos too

If by "this" you mean the issue that the title bar is partially outside the screen, then it's the same issue. Yes, it's a but. No, it's not fixed yet.

If "this" refers to anything other than "title bar is partially outside the screen", then please open a new issue.

**Closed** 2021-04-23 07:46 UTC
Labels: os:win

**Comment by jimmy-1000** [comment] 2021-04-23 17:43
This mean it will fix in new mpv releases ?  🤔

**Comment by jimmy-1000** [comment] 2021-05-03 04:27
If we use mpv with "no border", the problem is fixed.
