### ISSUE TITLE
Hardware acceleration auto detection is broken in 0.27.2

### ISSUE THREAD

**Issue by flux242** [mpv-player/mpv#5798] opened 2018-05-05 08:03 UTC
If I use --hwdec=auto on the command line then autodetection works correctly (vaapi is detected in my case). Should I put 'hwdec=auto' into my mpv.conf then it fails to auto detect the HW and falls back to the SW rendering. If I remove the line 'hwdec=auto' from the conf file then it also works. This is obviously a regression in 0.27.2 because it was working in 0.26. 

Workaround is easy -remove that line from the conf file, still such non linearity rises question - how it is even possible?

### mpv version and platform
Ubuntu 18.04 LTS
mpv 0.27.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4.2-2

### Reproduction steps
Started without the 'hwdec=auto' line in the mpv.conf:
-------------------------------------------------------------------------------------------
[vo/opengl] Loading hwdec driver 'vaapi-egl'
[vo/opengl/vaapi-egl] Trying to open a x11 VA display...
[vo/opengl/vaapi-egl/vaapi] libva: VA-API version 1.1.0
[vo/opengl/vaapi-egl/vaapi] libva: va_getDriverName() returns 0
[vo/opengl/vaapi-egl/vaapi] libva: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
[vo/opengl/vaapi-egl/vaapi] libva: Found init function __vaDriverInit_1_1
[vo/opengl/vaapi-egl/vaapi] libva: va_openDriver() returns 0
[vo/opengl/vaapi-egl/vaapi] VA API version 1.1
[vo/opengl/vaapi-egl/vaapi] 9 image formats available:
[vo/opengl/vaapi-egl/vaapi]   YV12
[vo/opengl/vaapi-egl/vaapi]   I420
[vo/opengl/vaapi-egl/vaapi]   NV12
[vo/opengl/vaapi-egl/vaapi]   YUY2
[vo/opengl/vaapi-egl/vaapi]   UYVY
[vo/opengl/vaapi-egl/vaapi]   422H
[vo/opengl/vaapi-egl/vaapi]   RGBX
[vo/opengl/vaapi-egl/vaapi]   BGRX
[vo/opengl/vaapi-egl/vaapi]   P010
[ffmpeg] AVHWDeviceContext: Matched "Intel i965 driver for Intel(R) Broadwell - 2.1.0" as known driver "Intel i965 (Quick Sync)".
[vo/opengl/vaapi-egl] using VAAPI EGL interop
[vo/opengl/vaapi-egl] Supported formats:
[vo/opengl/vaapi-egl]  nv12
[vo/opengl/vaapi-egl]  p010
[vo/opengl] Reported display depth: 8
[vd] Container reported FPS: 23.976025
[vd] Codec list:
[vd]     h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[vd]     h264_crystalhd (h264) - CrystalHD H264 decoder
[vd]     h264_v4l2m2m (h264) - V4L2 mem2mem H.264 decoder wrapper
[vd]     h264_cuvid (h264) - Nvidia CUVID H264 decoder
[vd] Opening video decoder h264
[vd] Probing 'vaapi'...
[vd] Trying hardware decoding.
[vd] Selected video codec: h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)
[vo/opengl] Assuming 60.059067 FPS for display sync.
------------------------------------------------------------------------------------------------------------------

Started with the 'hwdec=auto' line in the mpv.conf:
-------------------------------------------------------------------------------------------------------------------
[vo/opengl] Loading hwdec driver 'vaapi-egl'
[vo/opengl/vaapi-egl] Trying to open a x11 VA display...
[vo/opengl/vaapi-egl/vaapi] libva: VA-API version 1.1.0
[vo/opengl/vaapi-egl/vaapi] libva: va_getDriverName() returns 0
[vo/opengl/vaapi-egl/vaapi] libva: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
[vo/opengl/vaapi-egl/vaapi] libva: Found init function __vaDriverInit_1_1
[vo/opengl/vaapi-egl/vaapi] libva: va_openDriver() returns 0
[vo/opengl/vaapi-egl/vaapi] VA API version 1.1
[vo/opengl/vaapi-egl/vaapi] 9 image formats available:
[vo/opengl/vaapi-egl/vaapi]   YV12
[vo/opengl/vaapi-egl/vaapi]   I420
[vo/opengl/vaapi-egl/vaapi]   NV12
[vo/opengl/vaapi-egl/vaapi]   YUY2
[vo/opengl/vaapi-egl/vaapi]   UYVY
[vo/opengl/vaapi-egl/vaapi]   422H
[vo/opengl/vaapi-egl/vaapi]   RGBX
[vo/opengl/vaapi-egl/vaapi]   BGRX
[vo/opengl/vaapi-egl/vaapi]   P010
[ffmpeg] AVHWDeviceContext: Matched "Intel i965 driver for Intel(R) Broadwell - 2.1.0" as known driver "Intel i965 (Quick Sync)".
[vo/opengl/vaapi-egl] using VAAPI EGL interop
[vo/opengl/vaapi-egl] Supported formats:
[vo/opengl/vaapi-egl]  nv12
[vo/opengl/vaapi-egl]  p010
[vo/opengl] Reported display depth: 8
[vd] Container reported FPS: 23.976025
[vd] Codec list:
[vd]     h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[vd]     h264_crystalhd (h264) - CrystalHD H264 decoder
[vd]     h264_v4l2m2m (h264) - V4L2 mem2mem H.264 decoder wrapper
[vd]     h264_cuvid (h264) - Nvidia CUVID H264 decoder
[vd] Opening video decoder h264
[vd] Probing 'vdpau'...
[vd] Probing 'cuda'...
[vd] Probing 'cuda-copy'...
[vd] Trying hardware decoding.
[vd] Using underlying hw-decoder 'h264_cuvid'
[ffmpeg] Cannot load libnvcuvid.so.1
[ffmpeg/video] h264_cuvid: Failed loading nvcuvid.
[vd] Could not open codec.
[vd] Falling back to software decoding.
----------------------------------------------------------------------------------------------------------------------

**Comment by leigh123linux** [comment] 2018-05-05 10:03
Looks like a duplicate of https://github.com/mpv-player/mpv/issues/4865

**Comment by sfan5** [comment] 2018-05-08 09:26
Indeed.

**Closed by sfan5** 2018-05-08 09:26 UTC
