### ISSUE TITLE
Building borked on macOS (python issues, possibly homebrew)

### ISSUE THREAD

**Issue by AirPort** [mpv-player/mpv#5600] opened 2018-03-05 20:50 UTC
### mpv version and platform

mpv master
macOS 10.13.3

### Reproduction steps

Just build mpv master on a system with up-to-date homebrew install with `./bootstrap.py && ./waf configure` (with options) `&& ./waf build`, then try to make a bundle with the TOOLS/osxbundle.py script.

### Expected behavior

Mpv is built regularly and an app bundle is made.

### Actual behavior

Build exits at linking phase with

> Undefined symbols for architecture x86_64:
>   "_av_codec_iterate", referenced from:
>       _add_codecs in av_common.c.20.o
>       _encode_lavc_showhelp in encode_lavc.c.20.o
>       _add_all_hwdec_methods in vd_lavc.c.20.o
>   "_av_demuxer_iterate", referenced from:
>       _mp_get_lavf_demuxers in av_common.c.20.o
>       _demux_open_lavf in demux_lavf.c.20.o
>   "_av_frame_new_side_data_from_buf", referenced from:
>       _mp_image_to_av_frame in mp_image.c.20.o
>   "_av_mallocz_array", referenced from:
>       _mp_aframe_pool_allocate in aframe.c.20.o
>   "_av_muxer_iterate", referenced from:
>       _encode_lavc_showhelp in encode_lavc.c.20.o
>   "_avcodec_get_hw_config", referenced from:
>       _add_all_hwdec_methods in vd_lavc.c.20.o
>   "_avcodec_get_hw_frames_parameters", referenced from:
>       _get_format_hwdec in vd_lavc.c.20.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)]

If I manage to compile mpv nonetheless (see below), running the osxbundle scripts fails with the following error

> $ TOOLS/osxbundle.py build/mpv
> Creating Mac OS X application bundle (version: 0.28.0-UNKNOWN)...
> > copying bundle skeleton
> > copying binary
> > create bundle symlink
> > generating Info.plist
> > bundling dependencies
> Traceback (most recent call last):
>   File "TOOLS/dylib-unhell.py", line 94, in <module>
>     main()
>   File "TOOLS/dylib-unhell.py", line 89, in main
>     libs = libraries(binary)
>   File "TOOLS/dylib-unhell.py", line 38, in libraries
>     result[objfile] = set(libs_list)
>   File "TOOLS/dylib-unhell.py", line 15, in is_user_lib
>     return not sys_re.match(libname) and \
> TypeError: cannot use a string pattern on a bytes-like object
> done.

I may be wrong, but I _strongly_ suspect this breakage is due to the fact that the homebrew package manager recently migrated to python3 as default, so now `python` is linked to homebrew's python 3.6.4 instead of the usual system's python 2.7.10: if I temporarily unlink the brew package the builds succeed ad usual. Also, using the `python2.7` command directly "solves" the waf issue, but not the osxbundle.py one (maybe because it automatically picks the default python version with env, unlike waf?).

**Comment by Akemi** [comment] 2018-03-05 21:57
did you try with `python2.7 TOOLS/osxbundle.py build/mpv`? prefixing the waf calls with another python should also work instead of unlinking with homebrew.

also this looks like two separate issues.

**Comment by AirPort** [comment] 2018-03-05 22:02
Yep, I did. Prefixing waf worked, as I said in the issue, it didn’t with the bundle script.

**Comment by Akemi** [comment] 2018-03-05 22:39
i can't reproduce the linking issue. here it works without problems with the same setup.

i can reproduce the bundling problem. in the bundling step it just uses the [system python ](https://github.com/mpv-player/mpv/blob/master/TOOLS/osxbundle.py#L83). we could probably either  try using the python version which the base script was invoked with, or try to fix the `dylib-unhell.py` script with python3.

**Comment by Akemi** [comment] 2018-03-05 22:40
sry i kinda misread the "using the python2.7 command directly" part.

**Comment by Akemi** [comment] 2018-03-06 12:25
this is also related to #3316. i started fixing this and got the same problem with python3.

**Comment by AirPort** [comment] 2018-03-06 12:40
Oh yes, the issue reminded me that I tried to change the shebang line to invoke python directly, and that made the script to comply when called with `python2.7 TOOLS/osxbundle.py build/mpv`.
Of course this could work as a quick fix, not so much as a proper solution.

(I'd honestly like to know the rationale behind overriding by default a key system component like that, but what can you do)

**Comment by Akemi** [comment] 2018-03-06 19:52
the bundle creation issue should be fixed with #5606.

**Closed** 2018-03-08 23:41 UTC
Labels: osx

**Comment by Akemi** [comment] 2018-03-09 00:02
if the linking issue still exists would you mind opening a new issue?

**Comment by AirPort** [comment] 2018-03-09 10:12
It seems that I'm not able to reproduce it anymore (it happened 100% of the time when I opened the issue), maybe a full rebuild of ffmpeg somehow solved it or something like that. If I happen to notice it again in the future I'll report in a new issue.
