### ISSUE TITLE
Wayland system suspension with open paused video leads to stuttering and 99% gpu usage upon resuming from sleep and continuing to play that same video

### ISSUE THREAD

**Issue by siyia2** [mpv-player/mpv#8946] opened 2021-06-22 10:58 UTC
### Important Information

Provide following Information:
- mpv latest stable
- Manjaro rolling
- Manjaro Repos
- All mpv versions the same problem
- SwayWM
- amdgpu

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
1) Open video file in swayWM with mpv, let it play a bit and then pause it.
2) Suspend and then Resume
3) Unpause the video after waking the PC
4) Video stutters and gpu usage always 99%

### Expected behavior
Paused video files should resume with no issue after waking from sleep
### Actual behavior
Video stutters and gpu usage always 99%
### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

###MY MPV CONFIG FILE
#General
vo=gpu
gpu-api=vulkan
spirv-compiler=shaderc
profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
video-sync=display-resample
interpolation
tscale=oversample
video-aspect-override=16:9
gpu-context=waylandvk
hwdec=vaapi
video-sync=display-resample
save-position-on-quit
geometry=800x600
sub-auto=fuzzy
sub-file-paths=/mnt/D/Firefox_Downloads/

**Comment by Dudemanguy** [comment] 2021-06-22 12:54
Assuming you're using swayidle to suspend, I can't reproduce.

**Comment by siyia2** [comment] 2021-06-22 14:06
didyou use my config? yes i use swayidle to suspend, very annoying problem!!! :(

**Comment by Dudemanguy** [comment] 2021-06-22 14:49
From your config file options, the only possible things that could be relevant are using vulkan and vaapi. I did a quick test using the following.
`swayidle -w timeout 5 'swaylock -f -c 000000' timeout 10 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' before-sleep 'swaylock -f -c 000000'`

I opened a video using vulkan, vaapi, and wayland, fullscreened it and then let the system lock and suspend. After that, I woke up my display, unlocked the screen, and resumed the video with no issues.

**Comment by siyia2** [comment] 2021-06-23 10:02
Did you check the gpu usage while that same video was playing its 99%?

**Comment by Dudemanguy** [comment] 2021-06-23 13:20
The gpu usage was not 99%.

**Comment by Dudemanguy** [comment] 2021-07-27 16:36
@siyia2: I think e2c24ad in git master might fix your issue. Appreciate it if you could give it a try.

**Comment by siyia2** [comment] 2021-07-27 17:43
thx dudemanguy i ll give it a try in the following days and post back

**Comment by siyia2** [comment] 2021-07-27 23:24
I used mpv 0.33.0-259-g743e1c1b15, and no the issue is still present after waking from suspend and resume any video gpu load is at 98-99% with mpv playing

**Comment by Dudemanguy** [comment] 2021-07-27 23:38
That's bizarre. I thought your issue might be related to #9016 (which I think is fixed now although I could be wrong). Maybe it's something else completely. Does it happen if you use opengl instead of vulkan?

**Comment by siyia2** [comment] 2021-07-27 23:46
It happens with with vulkan only

**Comment by Dudemanguy** [comment] 2021-07-27 23:57
Do you get the bug if you use vulkan and `--wayland-disable-vsync`? Of course, that option is for testing only and not something you'd normally use.

**Comment by siyia2** [comment] 2021-07-28 00:00
With wayland-disable-vsync=yes videos lag and have very high gpu usage either way

**Comment by Dudemanguy** [comment] 2021-07-28 00:24
Okay so your issue is truly completely unrelated then. It doesn't really make sense why simply resuming from DPMS would tax your GPU. We have absolutely zero knowledge of such suspended events in mpv. I can only assume a driver bug at this point.

**Comment by siyia2** [comment] 2021-07-28 00:32
Now that you mention it vulkan runninggames also suffer the same fate after waking from suspend, so it must be a radv bug.

**Comment by Dudemanguy** [comment] 2021-07-28 00:41
Maybe try reporting this to mesa?

**Comment by siyia2** [comment] 2021-07-28 08:43
yes i will

**Comment by siyia2** [comment] 2021-07-28 08:59
just did:
https://gitlab.freedesktop.org/mesa/mesa/-/issues/5133

**Comment by Dudemanguy** [comment] 2023-01-09 06:18
Upstream and I assume it was fixed by now.

**Closed by Dudemanguy** 2023-01-09 06:18 UTC
Labels: down-upstream, vo:gpu:wayland, os:linux
