### ISSUE TITLE
any invocation of mpv crashes in macos 12.5.1, M1

### ISSUE THREAD

**Issue by wmusial** [mpv-player/mpv#12054] opened 2023-07-30 15:49 UTC
any invocation of mpv crashes with a segmentation fault, even invocations without any arguments. 

### Important Information

mpv version:  0.35.0, 0.35.1, 0.36.0
macos version: 12.5.1, M1
mpv binary: official from brew (0.36.0), as well as compiled by hand (0.35.0, 0.35.1, 0.36.0)
do not know which version introduced the problem.

### Reproduction steps

run mpv on terminal, observe segmentation fault:

```
$ mpv
mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Fri Jul 28 10:39:32 2023
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
Segmentation fault: 11
```

```
$ mpv --no-cache --no-terminal -- fd://0
Segmentation fault: 11
```

### Expected behavior

does not crash.

### Actual behavior

crashes.

### Log file

```
[   0.003][v][cplayer] mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
[   0.003][v][cplayer]  built on Fri Jul 28 10:39:32 2023
[   0.003][v][cplayer] FFmpeg library versions:
[   0.003][v][cplayer]    libavutil       58.2.100
[   0.003][v][cplayer]    libavcodec      60.3.100
[   0.003][v][cplayer]    libavformat     60.3.100
[   0.003][v][cplayer]    libswscale      7.1.100
[   0.003][v][cplayer]    libavfilter     9.3.100
[   0.003][v][cplayer]    libswresample   4.10.100
[   0.003][v][cplayer] FFmpeg version: 6.0
[   0.003][v][cplayer] 
[   0.003][v][cplayer] Configuration: meson configure build -Dprefix=/opt/homebrew -Dbuildtype=debugoptimized -Doptimization=2
[   0.003][v][cplayer] List of enabled features: av-channel-layout bsd-fstatfs build-date cocoa coreaudio cplayer cplugins debug ffmpeg gl gl-cocoa glob glob-posix gpl iconv javascript jpeg jpegxl lcms2 libass libavdevice libbluray libdl libm luajit macos-cocoa-cb macos-media-player macos-touchbar osx-thread-name posix rubberband rubberband-3 stdatomic threads uchardet vapoursynth vector videotoolbox-gl zimg zlib
[   0.003][v][cplayer] Command line options: '--no-config' '--log-file=mpv.log'
[   0.003][v][cplayer] mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
[   0.003][v][cplayer]  built on Fri Jul 28 10:39:32 2023
[   0.003][v][cplayer] FFmpeg library versions:
[   0.003][v][cplayer]    libavutil       58.2.100
[   0.003][v][cplayer]    libavcodec      60.3.100
[   0.003][v][cplayer]    libavformat     60.3.100
[   0.003][v][cplayer]    libswscale      7.1.100
[   0.003][v][cplayer]    libavfilter     9.3.100
[   0.003][v][cplayer]    libswresample   4.10.100
[   0.003][v][cplayer] FFmpeg version: 6.0
[   0.003][v][cplayer] 
[   0.003][v][cplayer] Configuration: meson configure build -Dprefix=/opt/homebrew -Dbuildtype=debugoptimized -Doptimization=2
[   0.003][v][cplayer] List of enabled features: av-channel-layout bsd-fstatfs build-date cocoa coreaudio cplayer cplugins debug ffmpeg gl gl-cocoa glob glob-posix gpl iconv javascript jpeg jpegxl lcms2 libass libavdevice libbluray libdl libm luajit macos-cocoa-cb macos-media-player macos-touchbar osx-thread-name posix rubberband rubberband-3 stdatomic threads uchardet vapoursynth vector videotoolbox-gl zimg zlib
[   0.003][d][global] config path: '' -> '-'
[   0.003][d][global] user path: '~~home/' -> ''
[   0.003][d][global] user path: '~~old_home/' -> ''
[   0.003][v][cplayer] Setting option 'config' = 'no' (flags = 8)
[   0.003][v][cplayer] Setting option 'log-file' = 'mpv.log' (flags = 8)
[   0.009][d][global] user path: 'mpv.log' -> 'mpv.log'
[   0.009][d][osc] Loading lua script @osc.lua...
[   0.009][d][ytdl_hook] Loading lua script @ytdl_hook.lua...
[   0.009][d][stats] Loading lua script @stats.lua...
[   0.009][d][console] Loading lua script @console.lua...
[   0.009][d][auto_profiles] Loading lua script @auto_profiles.lua...
[   0.009][i][cplayer] mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
[   0.009][i][cplayer]  built on Fri Jul 28 10:39:32 2023
[   0.009][i][cplayer] FFmpeg library versions:
[   0.009][i][cplayer]    libavutil       58.2.100
[   0.009][i][cplayer]    libavcodec      60.3.100
[   0.009][i][cplayer]    libavformat     60.3.100
[   0.009][i][cplayer]    libswscale      7.1.100
[   0.009][i][cplayer]    libavfilter     9.3.100
[   0.009][i][cplayer]    libswresample   4.10.100
[   0.009][i][cplayer] FFmpeg version: 6.0
[   0.009][i][cplayer] 
[   0.009][i][cplayer] Usage:   mpv [options] [url|path/]filename
[   0.009][i][cplayer] 
[   0.009][i][cplayer] Basic options:
[   0.009][i][cplayer]  --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
[   0.009][i][cplayer]  --no-audio        do not play sound
[   0.009][i][cplayer]  --no-video        do not play video
[   0.009][i][cplayer]  --fs              fullscreen playback
[   0.009][i][cplayer]  --sub-file=<file> specify subtitle file to use
[   0.009][i][cplayer]  --playlist=<file> specify playlist file
[   0.009][i][cplayer] 
[   0.009][i][cplayer]  --list-options    list all mpv options
[   0.009][i][cplayer]  --h=<string>      print options which contain the given string in their name
[   0.009][i][cplayer] 
[   0.009][d][console] loading mp.defaults
[   0.009][d][auto_profiles] loading mp.defaults
[   0.009][d][osc] loading mp.defaults
[   0.010][d][stats] loading mp.defaults
[   0.010][d][ytdl_hook] loading mp.defaults
[   0.010][d][osc] loading @osc.lua
[   0.010][d][ytdl_hook] loading @ytdl_hook.lua
[   0.010][d][stats] loading @stats.lua
[   0.010][d][auto_profiles] loading @auto_profiles.lua
[   0.011][d][console] loading @console.lua
```

i tried compiling without lua, no cigar.

**Comment by sfan5** [comment] 2023-07-30 17:15
Try getting a backtrace using lldb?

**Comment by low-batt** [comment] 2023-08-02 01:57
When mpv crashes macOS should be generating a crash report. Please copy the entire report into a text file and post that file to this issue. There may still be a crash report from the last time you ran mpv.  Crash reports can be viewed in the macOS console utility as dicussed  [here](https://support.apple.com/guide/console/reports-cnsl664be99a/mac). 

The crash report, or a `lldb` backtrace, is critical to be able to figure out what is going wrong.

I have a M1 running macOS 13.5. All of these are working for me:
- 0.35.1, brew
- 0.36.0, stolendata
- master, local build

Does `mpv --no-config` crash as well?

**Comment by Akemi** [comment] 2023-11-24 19:04
i can't reproduce this either and without a backtrace probably impossible to know what happens.

closing this for now. if it happens more often we might need to investigate further.

**Closed by Akemi** 2023-11-24 19:04 UTC
Labels: os:mac
