### ISSUE TITLE
dts music plays too fast when bitstreaming

### ISSUE THREAD

**Issue by Doofussy2** [mpv-player/mpv#6651] opened 2019-04-21 02:00 UTC
### mpv version and platform
Windows 10
mpv 29.1 and latest git

### Reproduction steps
Play file with `--audio-spdif=dts`

### Expected behavior
Audio plays at correct speed

### Actual behavior
Audio plays slightly too fast. It plays correctly in VLC, and when using software decoding in mpv. 

### Log file
[Portable mpv log.txt](https://github.com/mpv-player/mpv/files/3100798/Portable.mpv.log.txt)

### Sample files
This is a link to the originally attached file in the Emby community (not mine, but I have downloaded it to test with)

https://emby.media/community/index.php?app=core&module=attach&section=attach&attach_id=54297

**Comment by Mitzsch01** [comment] 2019-04-21 18:37
It´s not necessarily related to DTS files. I've already seen something like this with Dolby Digital (AC3) files...
But only those with an encoding of 44.1kHz (and when using passthrough) are affected... 
(tested with Linux)

**Comment by 44vince44** [comment] 2019-05-01 16:45
I don't know if this can help: when I was using directshow with media player, the ac3/dts source of the LAV filters had this problem: time scale not ok when playing 44.100Hz files. BUT the ac3/dts source filter (called ac3 source) from AC3Filter (which is not under development anymore) did work perfectly. I'm not sure if this can help the developers...

**Comment by wm4** [comment] 2019-10-24 10:42
Trying to get the sample gives an error, plus the issue is pretty old -> closing.

**Closed by wm4** 2019-10-24 10:42 UTC
Labels: core:audio

**Comment by Doofussy2** [comment] 2019-10-24 21:42
It downloads just fine, for me. But here's a link to the thread in Emby, if you still want to try.

https://emby.media/community/index.php?/topic/72576-dts51-music-wav-format-playing-too-fast/page-1

**Comment by mitzsch** [comment] 2024-01-06 11:06
If anyone is still interested in that one... I tried to fix it... Here is a Windows build => https://drive.google.com/file/d/10-vVr4DkNdesFs1WO0SwrDyswGia2svi/view?usp=sharing

Let me know if that works! :)
