### ISSUE TITLE
File name text overflows off window due to limited wrappable characters

### ISSUE THREAD

**Issue by alystair** [mpv-player/mpv#4308] opened 2017-04-09 05:17 UTC
### mpv version and platform
2017-02-12 Windows

### Reproduction steps
Open video with a long file name with no spaces

### Expected behavior
File info text fits/wraps width of window

### Actual behavior
Name outsizes and overflows off screen

### Log file
Not necessary for repro

### Sample files
Not necessary for repro

**Comment by wiiaboo** [comment] 2017-04-09 12:28
What's a file info?

**Comment by Hrxn** [comment] 2017-04-09 12:29
Maybe add a screenshot?

**Comment by alystair** [comment] 2017-04-10 15:42
Ok looks like I was wrong - this isn't actually caused by portrait mode but due to filename not having spaces and lack of other allowed wrap characters. Here's a screenshot.
![mpv shot](https://cloud.githubusercontent.com/assets/159109/24869891/a1a947b6-1de2-11e7-9bc4-aa1c05e399ba.png)

**Comment by alystair** [comment] 2017-04-10 15:45
I think this is easily remedied by allowing all periods in filename other than the last one before the extension to wrap the text like the space character does. See concept below:
![wrap solution](https://cloud.githubusercontent.com/assets/159109/24870069/1eea5558-1de3-11e7-8f7b-d16e8b9ae423.png)

**Comment by wiiaboo** [comment] 2017-04-10 16:01
But the problem is libass doesn't support zero-width spaces. You'd have to replace every `[.-_]` by `{\\fscx0.1} {\\fscx100}` which could lead to huge ASS strings.

**Comment by astiob** [comment] 2017-12-26 23:30
Frankly, I don’t think long ASS strings would be a problem, not in the case of file names at least.

You can also shave off a few bytes by using `{\fscx0}␣␣{\fsc}` (with two spaces to work around libass/libass#185) (assuming libass/libass@fc13f5393a9f59ac17eff583881cc03bcd129ef2, libass 0.11.0 or newer) and even more by declaring a custom ASS style “X” that has ScaleX=0 and using `{\rX}␣␣{\r}` (if mpv has a separate libass pipeline for the OSD such that this won’t interfere with the rendering of any subtitles).

**Comment by Et0h** [comment] 2017-12-27 12:04
I tested `{\fscx0}  {\fscx100}` (with double space) through the Syncplay mpv lua script and it seemed to work okay, I just had to remember to ensure the character insertion was done in a Unicode-compatible way.

**Comment by Argon-** [comment] 2017-12-27 14:59
For proper wrapping, you also want to make sure that there are no superfluous space characters.
I've encountered this once. Default wrapping:
![Default wrapping](https://cloud.githubusercontent.com/assets/540920/8997592/6ef81cea-3723-11e5-835e-4bbb4c8a2e28.png)
With `\q2`:
![Wrapping disabled](https://cloud.githubusercontent.com/assets/540920/8997617/c1e0ae90-3723-11e5-8f0a-5ea215e029a0.png)
The culprit was a bunch of spaces in front of the wrapped line that were not rendered but somehow taking into account for line wrapping calculations, so this could be easily fixed: https://github.com/mpv-player/mpv/commit/76ae38a2d5bea6ee64b1c91f2bfc2ac484f6f53e

**Comment by alystair** [comment] 2018-04-29 03:13
Just following up, was this ever added? Please close it if it was done.

**Comment by wiiaboo** [comment] 2018-04-29 10:51
It wasn't.

**Comment by Akemi** [comment] 2019-09-21 11:16
duplicate of #2203.

**Closed by Akemi** 2019-09-21 11:16 UTC
Labels: info-needed, libass, not-our-bug, to-be-closed
