### ISSUE TITLE
youtube-dl mpeg dash segment unsupported

### ISSUE THREAD

**Issue by beew** [mpv-player/mpv#3534] opened 2016-09-16 03:44 UTC
mpv git-cf5c3fc (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Fri Sep 16 00:16:52 UTC 2016
ffmpeg library versions:
   libavutil       55.28.100
   libavcodec      57.51.102
   libavformat     57.46.101
   libswscale      4.1.100
   libavfilter     6.51.100
   libswresample   2.1.100
ffmpeg version: N-81335-g3a81775

OS is Ubuntu 16.04 64 bit. MPV fails to play some Youtube videos with the youtube-dl hook.  For example

```
 mpv --ytdl-format="bestvideo[width<=1920][height<=1080]+bestaudio[ext=m4a]/best[ext=mp4]/best" http://www.youtube.com/watch?v=VmuXeOYgNR0 
Auto-loading profile 'vo.vaapi'
'vo' auto profiles are deprecated.
Playing: http://www.youtube.com/watch?v=VmuXeOYgNR0
[ytdl_hook] MPEG-Dash Segments unsupported, add [protocol!=http_dash_segments] to your ytdl-format. 
[ffmpeg] tls: The TLS connection was non-properly terminated.
Failed to recognize file format.

Exiting... (Errors when loading file)
```
--ytdl-format="bestvideo+bestaudio" also didn't work
But with others also seem to be be dash mpeg it works fine, for example
```
mpv --ytdl-format="bestvideo[width<=1920][height<=1080]+bestaudio[ext=m4a]/best[ext=mp4]/best" http://www.youtube.com/watch?v=8Tgi-j56ueU 
Auto-loading profile 'vo.vaapi'
'vo' auto profiles are deprecated.
Playing: http://www.youtube.com/watch?v=8Tgi-j56ueU
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=und (*) 'DASH audio' (aac) (external)
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
AO: [pulse] 44100Hz stereo 2ch float
Using hardware decoding (vaapi).
VO: [vaapi] 1920x1080 vaapi
AV: 00:02:00 / 00:04:13 (47%) A-V:  0.000 Cache: 10s+52MB


Exiting... (Quit)
```
For the first one (that mpv+youtube-dl doesn't work)
```
youtube-dl -F http://www.youtube.com/watch?v=VmuXeOYgNR0
[youtube] VmuXeOYgNR0: Downloading webpage
[youtube] VmuXeOYgNR0: Downloading video info webpage
[youtube] VmuXeOYgNR0: Extracting video information
[youtube] VmuXeOYgNR0: Downloading MPD manifest
[youtube] VmuXeOYgNR0: Downloading MPD manifest
[info] Available formats for VmuXeOYgNR0:
format code  extension  resolution note
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k (44100Hz)
160          mp4        256x144    DASH video  108k , avc1.4d400b, 24fps, video only
133          mp4        426x240    DASH video  242k , avc1.4d400c, 24fps, video only
134          mp4        640x360    DASH video  605k , avc1.4d401e, 24fps, video only
135          mp4        854x480    DASH video 1155k , avc1.4d4014, 24fps, video only
136          mp4        1280x720   DASH video 2310k , avc1.4d4016, 24fps, video only
137          mp4        1920x1080  DASH video 4331k , avc1.64001e, 24fps, video only
17           3gp        176x144    small , mp4v.20.3,  mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3,  mp4a.40.2
43           webm       640x360    medium , vp8.0,  vorbis@128k
18           mp4        640x360    medium , avc1.42001E,  mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F,  mp4a.40.2@192k (best)
```

For the second one (mpv+youtube-dl does work)
```
youtube-dl -F http://www.youtube.com/watch?v=8Tgi-j56ueU 
[youtube] 8Tgi-j56ueU: Downloading webpage
[youtube] 8Tgi-j56ueU: Downloading video info webpage
[youtube] 8Tgi-j56ueU: Extracting video information
[youtube] 8Tgi-j56ueU: Downloading MPD manifest
[info] Available formats for 8Tgi-j56ueU:
format code  extension  resolution note
249          webm       audio only DASH audio   52k , opus @ 50k (48000Hz), 1.52MiB
250          webm       audio only DASH audio   72k , opus @ 70k (48000Hz), 2.02MiB
140          m4a        audio only DASH audio  129k , m4a_dash container, mp4a.40.2@128k (44100Hz), 3.89MiB
171          webm       audio only DASH audio  132k , vorbis@128k (44100Hz), 3.62MiB
251          webm       audio only DASH audio  143k , opus @160k (48000Hz), 3.99MiB
160          mp4        256x144    DASH video  110k , avc1.4d400c, 12fps, video only, 3.31MiB
278          webm       256x144    DASH video  113k , webm container, vp9, 12fps, video only, 2.94MiB
133          mp4        426x240    DASH video  247k , avc1.4d4015, 24fps, video only, 7.40MiB
242          webm       426x240    DASH video  256k , vp9, 24fps, video only, 6.70MiB
243          webm       640x360    DASH video  480k , vp9, 24fps, video only, 12.44MiB
134          mp4        640x360    DASH video  614k , avc1.4d401e, 24fps, video only, 15.22MiB
244          webm       854x480    DASH video  889k , vp9, 24fps, video only, 22.93MiB
135          mp4        854x480    DASH video 1123k , avc1.4d401e, 24fps, video only, 28.97MiB
247          webm       1280x720   DASH video 1809k , vp9, 24fps, video only, 45.23MiB
136          mp4        1280x720   DASH video 2237k , avc1.4d401f, 24fps, video only, 54.22MiB
248          webm       1920x1080  DASH video 3265k , vp9, 24fps, video only, 79.97MiB
137          mp4        1920x1080  DASH video 4155k , avc1.640028, 24fps, video only, 94.94MiB
17           3gp        176x144    small , mp4v.20.3,  mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3,  mp4a.40.2
43           webm       640x360    medium , vp8.0,  vorbis@128k
18           mp4        640x360    medium , avc1.42001E,  mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F,  mp4a.40.2@192k (best)
```

Thanks.

P.S. What does it mean by "'vo' auto profiles are deprecated" ? Does it mean my .config file
```
vo=vaapi
[vo.vaapi]
hwdec=vaapi
``` 
will no longer work soon?

**Comment by wiiaboo** [comment] 2016-09-16 11:28
Duplicate of https://github.com/mpv-player/mpv/issues/3388.

**Closed** 2016-09-16 11:48 UTC

**Comment by wiiaboo** [comment] 2016-09-16 12:31
>P.S. What does it mean by "'vo' auto profiles are deprecated" ? Does it mean my .config file
>```
vo=vaapi
[vo.vaapi]
hwdec=vaapi
```
will no longer work soon?

That's what deprecated means, yes. You can just use plain non-auto profiles:
```
profile=vaapi
[vaapi]
vo=vaapi
hwdec=vaapi
```

**Comment by wm4** [comment] 2016-09-16 12:56
That's correct. Or just do:
```
vo=vaapi
hwdec=vaapi
```
Also, ``vo=vaapi`` is not recommended at all.
