### ISSUE TITLE
OSD broken with opengl 2.1

### ISSUE THREAD

**Issue by Gusar321** [mpv-player/mpv#3303] opened 2016-07-02 22:52 UTC
In the current git version, doing anything that should make the osd appear, like pressing "o", makes the mpv window turn blue and the following appears in the console
```
[vo/opengl] fragment shader source:
[vo/opengl] [  1] #version 120
[vo/opengl] [  2] #define texture texture2D
[vo/opengl] [  3] varying vec2 texcoord;
[vo/opengl] [  4] varying vec4 ass_color;
[vo/opengl] [  5] uniform sampler2D osdtex;
[vo/opengl] [  6] #define LUT_POS(x, lut_size) mix(0.5 / (lut_size), 1.0 - 0.5 / (lut_size), (x))
[vo/opengl] [  7] void main() {
[vo/opengl] [  8] vec4 color = vec4(0.0, 0.0, 0.0, 1.0);
[vo/opengl] [  9] // OSD (libass)
[vo/opengl] [ 10] color = vec4(ass_color.rgb, ass_color.a * texture(osdtex, texcoord).r);
[vo/opengl] [ 11] // color management
[vo/opengl] [ 12] color.rgb = clamp(color.rgb, 0.0, 1.0);
[vo/opengl] [ 13] color.rgb = mix(color.rgb / vec3(12.92), pow((color.rgb + vec3(0.055))/vec3(1.055), vec3(2.4)), lessThan(vec3(0.04045), color.rgb));
[vo/opengl] [ 14] color.rgb = clamp(color.rgb, 0.0, 1.0);
[vo/opengl] [ 15] color.rgb = pow(color.rgb, vec3(1.0/2.4));
[vo/opengl] [ 16] gl_FragColor = color;
[vo/opengl] [ 17] }
[vo/opengl] fragment shader compile log (status=0):
[vo/opengl] 0:13(13): error: no matching function for call to `mix(vec3, vec3, bvec3)'; candidates are:
[vo/opengl] 0:13(13): error:    float mix(float, float, float)
[vo/opengl] 0:13(13): error:    vec2 mix(vec2, vec2, float)
[vo/opengl] 0:13(13): error:    vec3 mix(vec3, vec3, float)
[vo/opengl] 0:13(13): error:    vec4 mix(vec4, vec4, float)
[vo/opengl] 0:13(13): error:    vec2 mix(vec2, vec2, vec2)
[vo/opengl] 0:13(13): error:    vec3 mix(vec3, vec3, vec3)
[vo/opengl] 0:13(13): error:    vec4 mix(vec4, vec4, vec4)
[vo/opengl] 
[vo/opengl] shader link log (status=0): error: linking with uncompiled shader
```
Tried on two different machines, one with Intel Ironlake (gen5) graphics, the other with Intel GMA950 (gen3) graphics. What both of these GPUs have in common is that opengl 2.1 is the highest version they provide.

The 0.18 release works fine. The difference between the release and git is that the release doesn't have color management stuff in the OSD shader.

**Comment by haasn** [comment] 2016-07-02 22:57
Duplicate of #3293. Fix has already been written for linux, it just needs to be changed to also work on windows etc. before being merged..

**Closed** 2016-07-04 14:27 UTC
