### ISSUE TITLE
Mistimed with pulse audio output.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#9473] opened 2021-11-19 02:15 UTC
Maybe implementing native PipeWire support is a must?
### Important Information

Provide following Information:
- mpv version: mpv 0.34.0-dirty
- Linux Distribution and Version: Arch Linux
- Source of the mpv binary: mpv-pipewire in AUR
- If known which version of mpv introduced the problem: no
- Window Manager and version: Mutter 41.1
- GPU driver and version: Mesa Gallium driver 21.2.5 for AMD Radeon RX 580 Series (POLARIS10, DRM 3.42.0, 5.15.2-zen1-1-zen, LLVM 13.0.0)
- Possible screenshot or video of visual glitches
It is hard to take a screenshot for mistimed.

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
1. Play it with pulseaudio (pipewire-pulse)
`mpv --log-file=pulseaudio.txt --no-config --hwdec=vaapi --video-sync=display-resample --fs --ao=pulse 'video'`
I can see the mistimed increases, I also see vsync spikes, but it only happens in Gnome Shell, with pure Mutter, I can't see it.
2. Play it with pipewire patch.
`mpv --log-file=pipewire_patch.txt --no-config --hwdec=vaapi --video-sync=display-resample --fs --ao=pipewire 'video'`
I see no more vsync jitter and mistimed and delayed.
### Expected behavior
No increasing Vsync Jitter, Mistimed, Delayed.
### Actual behavior
Increasing Vsync Jitter, Mistimed, Delayed.
### Log file

[pulseaudio.txt](https://github.com/mpv-player/mpv/files/7567343/pulseaudio.txt)

[pipewire_patch.txt](https://github.com/mpv-player/mpv/files/7567344/pipewire_patch.txt)

The issue will be closed for ignoring the issue template.

### Sample files

Lots of videos.

**Comment by LaserEyess** [comment] 2021-11-19 04:57
Neither of these logs show any significant A/V desync or mistimed video. Can you elaborate exactly how this manifests as bad video? Is ``--hwdec=vaapi`` necessary to reproduce as well? What happens when you don't have that. Also, what on earth are you doing to call ``disabled-section`` so many times? That seems incredibly suspect.

**Comment by laichiaheng** [comment] 2021-11-19 05:38
@LaserEyess To play 4K videos smoothly, I need VAAPI to do it. I see the mistimed on MPV's status with Shift+I.
I noticed it because I could see some stutter while looking carefully, after trying the pipewire patch which was made by [Oschowa](https://github.com/Oschowa/mpv/commit/fddb143282fa74425a8a6f29c9566e51777759d0), all the problems are gone.

I don't know about the 'disabled-section' thing, should it appears when I play videos with `--no-config`?
By the way, here is my config file (I have renamed it to mpv.txt):
[mpv.txt](https://github.com/mpv-player/mpv/files/7568018/mpv.txt)

**Comment by LaserEyess** [comment] 2021-11-19 05:57
Don't test with 4k videos, test with something your CPU can reasonably handle. Performance issues with your hardware could be a part of this. How many mistimed frames do you see? Can you get a picture of stats.lua after ~5 seconds or playback or something?

Also, no I don't think `disabled-section` is normal, I don't really know what that is besides a command and I have no idea what it does. In theory it shouldn't affect anything but it seems very strange.

**Comment by laichiaheng** [comment] 2021-11-19 06:27
@LaserEyess 
With `--ao=pulse`:
![1](https://user-images.githubusercontent.com/9532105/142575473-32f93251-597a-42c1-822d-89ad23afbf16.png)
It rises in few seconds.

With --ao=pipewire:
![2](https://user-images.githubusercontent.com/9532105/142575543-390b23d3-0779-4232-bf9f-06c6e36b2779.png)
It keeps at the same mistimed and delayed for a much longer time, and I don't see it rises.

**Comment by Dudemanguy** [comment] 2021-11-19 14:28
I've experienced something like this before when pulseaudio was unknowingly installed on my system and thus I was using the pulseaudio-alsa emulation layer thing (the ao was set to alsa). I do not know if this indicates a deeper problem with mpv's audio code or not, but probably the best thing to do is to add a pipewire output since so many people use it.

**Comment by laichiaheng** [comment] 2021-11-19 16:31
OK, I need to take my words back, if I close the status info, the mistimed and delayed keeps rising, and vsync jitter also becomes higher, none of these happen to Plasma 5, it is also a Gnome issue.

**Comment by LaserEyess** [comment] 2021-11-19 16:47
Those screenshots really don't show any jitter or mistimed frames. Can you play the video **until it starts misbehaving** and then get a shot of stats.lua. Furthermore, you say this happens with pulse and pipewire-pulse. But what about pulse-alsa or pipewire-alsa? If this is truly an issue with `--ao=pulse` those should be unaffected. But in another issue you said pulse-alsa was bad as well.

**Comment by laichiaheng** [comment] 2021-11-20 10:19
> Those screenshots really don't show any jitter or mistimed frames. Can you play the video **until it starts misbehaving** and then get a shot of stats.lua. Furthermore, you say this happens with pulse and pipewire-pulse. But what about pulse-alsa or pipewire-alsa? If this is truly an issue with `--ao=pulse` those should be unaffected. But in another issue you said pulse-alsa was bad as well.

The mistimed of first picture is 29, and it was still going up, no matter there is vsync jitter or not.
The second one stays at 7

By the way, in Gnome Wayland, even `--ao=pipewire`, when I close the stats.lua, the vsync jitter and mistimed and delayed comes back, I don't see it in Plasma Wayland, neither does pure Mutter.

**Comment by Dudemanguy** [comment] 2022-01-18 14:03
Fixed by #9587 (native pipewire).

**Closed by Dudemanguy** 2022-01-18 14:03 UTC
Labels: os:linux
