### ISSUE TITLE
mpv doesn't support Meridian Lossless Packing?

### ISSUE THREAD

**Issue by filler56789** [mpv-player/mpv#5923] opened 2018-06-14 04:40 UTC
### mpv version and platform
mpv 0.28.0-583-gfae9d7744c — Windows 7, x64

### Reproduction steps
**mpv filename.mka**, where filename.mka contains MLP audio.

### Actual behavior
Error message below.

> [mkv] Unknown/unsupported audio codec ID 'A_MLP' for track 1 or missing/faulty
> [mkv] private codec data.
>  (+) Audio --aid=1 --alang=spa (*) ( 2ch 44100Hz)
> Failed to initialize a decoder for codec ''.
> Audio: no audio
> No video or audio streams selected.
>
>Exiting... (Errors when loading file)

### Log file

> [demux] Trying demuxers for level=normal.
> [mkv] Found the head...
> [mkv] + a segment...
> [mkv] Parsing seek head...
> [mkv] |+ segment information...
> [mkv] | + muxing app: libebml v1.3.0 + libmatroska v1.4.0
> [mkv] | + writing app: mkvmerge v5.8.0 ('No Sleep / Pillow') built on Sep 30 2012 10:57:14
> [mkv] | + timecode scale: 22674
> [mkv] | + duration: 216.112s
> [mkv] | + segment uid b3 6f 3e 64 59 11 11 de af 64 ce a0 8f 7a 0a 71
> [mkv] |+ segment tracks...
> [mkv] | + a track...
> [mkv] |  + Track number: 1
> [mkv] |  + Track type: Audio
> [mkv] |  + Audio track
> [mkv] |   + Sampling frequency: 44100.000000
> [mkv] |   + Channels: 2
> [mkv] |  + Codec ID: A_MLP
> [mkv] |  + Language: spa
> [mkv] |+ found cluster
> [mkv] Deferring reading cues.
> [mkv] All headers are parsed!
> [mkv] Unknown/unsupported audio codec ID 'A_MLP' for track 1 or missing/faulty
> [mkv] private codec data.
> [demux] Detected file format: Matroska
> [cplayer] Opening done: filename.mka
> [find_files] Loading external files in .
> [cplayer] Running hook: ytdl_hook/on_preloaded
> [mkv] select track 0
> [cplayer]  (+) Audio --aid=1 --alang=spa (*) ( 2ch 44100Hz)
> [ad] Codec list:
> [ad]     (no decoders)
> [ad] Failed to initialize a decoder for codec ''.
> [mkv] deselect track 0
> [cplayer] Audio: no audio
> [cplayer] No video or audio streams selected.
> [cplayer] finished playback, no audio or video data played (reason 4)
> [cplayer]
> [cplayer]
> [cplayer] Exiting... (Errors when loading file)
> [ytdl_hook] Exiting...
> [stats] Exiting...
> [osc] Exiting...

**Comment by qyot27** [comment] 2018-06-14 05:13
``--demuxer=lavf``

Matroska is one of a few (or the only?) container format that still has its own dedicated demuxer in mpv that's separate from libavformat's, and in the case of Matroska, it is that non-lavf mkv demuxer that's the default (likely because it supports ordered chapters and libavformat's Matroska demuxer doesn't).  The error about A_MLP not being recognized is coming from the mkv demuxer, so forcing lavf should fix it, provided FFmpeg/FFplay can open or play it correctly.

**Comment by CounterPillow** [comment] 2018-06-14 11:07
Do you have a sample file? Maybe it's as simple as the codec ID missing from mpv's list of mkv codec IDs.

**Comment by CounterPillow** [comment] 2018-06-14 11:16
Turns out ffmpeg even has an encoder for this that works, so I could create my own sample file, and confirmed it really just was a case of adding a tag to a list.

Thanks for reporting this!

**Comment by filler56789** [comment] 2018-06-18 00:20
Too bad the source-code still hasn't been updated accordingly.

**Comment by CounterPillow** [comment] 2018-06-18 12:12
What? Literally just pull in from my branch if you can't wait for it to be merged upstream.

**Comment by filler56789** [comment] 2018-06-18 16:48
https://github.com/CounterPillow/mpv has no binaries for Windows released,
thank you very-much for nothing.

**Comment by CounterPillow** [comment] 2018-06-18 17:31
Yes, why would I build binaries for Windows for a 1-liner development branch? You fucking piece of shit ingrate, maybe learn a thing or two about software development before you demand free work from people already doing free labour for you.

**Comment by Akemi** [comment] 2018-06-18 17:56
i am not going to defend @CounterPillow's lets call it 'straightforwardness', but @filler56789 you should really work on your attitude. anyway, comments closed since the issue has been nearly resolved and i am not willing to read any more of this.

**Closed** 2018-06-22 18:17 UTC
