### ISSUE TITLE
vo=dmabuf-wayland causes color shifting in fullscreen and affects OSC/OSD visibility

### ISSUE THREAD

**Issue by unaaagy** [mpv-player/mpv#15570] opened 2024-12-25 10:27 UTC
### mpv Information

```bash
mpv 0.39.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
libplacebo version: v7.349.0
FFmpeg version: 7.0.2
FFmpeg library versions:
   libavcodec      61.3.100
   libavdevice     61.1.100
   libavfilter     10.1.100
   libavformat     61.1.100
   libavutil       59.8.100
   libswresample   5.1.100
   libswscale      8.1.100
```

### Other Information

```text
- Linux version: Fedora Linux
- Kernel Version:Linux dell 6.12.5-200.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Dec 15 16:48:23 UTC 2024 x86_64 GNU/Linux
- GPU Model: Advanced Micro Devices, Inc. [AMD/ATI] Lucienne [1002:164c] (rev c2)
- Mesa/GPU Driver Version: 4.6 (Compatibility Profile) Mesa 24.2.8
- DE and Version: Gnome 47(wayland)
- Source of mpv: DNF and Flatpak
```

### Reproduction Steps

When vo=dmabuf-wayland is set, a subtle color shift happens when the OSC or OSD is shown. The color shifting is more visible on a colorful video.
I tried to record the issue with screen recording, but it doesn't show there.

### Reproduction steps:
- open this example file with the given flags `mpv --no-config --vo=dmabuf-wayland https://www.youtube.com/watch?v=3k6cHJn3eLE`
- toggle fullscreen mode
- show the OSC or OSD by either:
     - hovering the mouse and stopping with 1-2 second delay
     - toggle the subtitles by pressing v repeatedly with 1-2 second delay

Note: The color shifting is more visible when the video is paused

### Expected Behavior

- No color shifting
- OSD/OSC appearing without delay

### Actual Behavior

- Color shifting
- OSD doesn't appear sometimes
- OSC doesn't appear immediately when cursor is moved

### Log File

Output generated from a local mkv file.
[output.txt](https://github.com/user-attachments/files/18245450/output.txt)

Output from the reproduction.
[output.txt](https://github.com/user-attachments/files/18245463/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment] 2024-12-25 14:33
Duplicate of https://github.com/mpv-player/mpv/issues/14592

You need mpv master and your compositor needs to advertise support for xx-color-management.

**Closed** 2024-12-27 20:33 UTC
Labels: os:linux

**Comment by CounterPillow** [comment] 2024-12-27 20:50
As an aside note: it looks like your hwdec is failing, and you're then falling back to openh264, which is known to be buggy (AFAIK it's officially designed for constrained baseline H.264 only). Assuming this system is for private use, consider replacing both Mesa and FFmpeg with versions that have not been hacked up by Fedora's patent-paranoia and building mpv against those. vaapi to hardware decode H.264 on renoir should work, and upstream FFmpeg has its own better H.264 decoder.

**Comment by unaaagy** [comment] 2024-12-28 06:48
@CounterPillow thanks for the suggestion. I mainly use mpv flatpak to avoid the codec situation. I used the dnf version to make the bug report only.
