### ISSUE TITLE
Is smoothmotion working?

### ISSUE THREAD

**Issue by xylosper** [mpv-player/mpv#1584] opened 2015-02-14 04:08 UTC
When I played a video whose fps is ~24 with `mpv --msg-level=vo=debug --vo=opengl=smoothmotion`, I can see next logs:

```
...
[vo/opengl] inter frame ppts: 13853238, pts: 13895193, vsync: 13883640, mix: 0.409405
AV: 00:00:03 / 00:22:09 (0%) A-V:  0.000 Cache:  2s+21185KB
[vo/opengl] inter frame ppts: 13895193, pts: 13936151, vsync: 13933661, mix: 0.129985
AV: 00:00:03 / 00:22:09 (0%) A-V: -0.000 Cache:  2s+21185KB
[vo/opengl] inter frame ppts: 13936151, pts: 13978112, vsync: 13967000, mix: 0.400029
AV: 00:00:03 / 00:22:09 (0%) A-V: -0.000 Cache:  2s+21185KB
[vo/opengl] inter frame ppts: 13978112, pts: 14020142, vsync: 14016995, mix: 0.158835
AV: 00:00:03 / 00:22:09 (0%) A-V: -0.000 Cache:  2s+21185KB
[vo/opengl] inter frame ppts: 14020142, pts: 14061173, vsync: 14050325, mix: 0.394272
AV: 00:00:03 / 00:22:09 (0%) A-V: -0.000 Cache:  2s+21185KB
[vo/opengl] inter frame ppts: 14061173, pts: 14103195, vsync: 14083695, mix: 0.539180
AV: 00:00:03 / 00:22:09 (0%) A-V: -0.000 Cache:  2s+21053KB
[vo/opengl] inter frame ppts: 14103195, pts: 14145216, vsync: 14133671, mix: 0.409238
AV: 00:00:03 / 00:22:09 (0%) A-V:  0.000 Cache:  2s+21053KB
[vo/opengl] inter frame ppts: 14145216, pts: 14187232, vsync: 14183657, mix: 0.176622
AV: 00:00:03 / 00:22:09 (0%) A-V:  0.000 Cache:  2s+21053KB
[vo/opengl] inter frame ppts: 14187232, pts: 14228216, vsync: 14216995, mix: 0.402374
AV: 00:00:04 / 00:22:09 (0%) A-V:  0.000 Cache:  2s+21053KB
[vo/opengl] inter frame ppts: 14228216, pts: 14270199, vsync: 14266991, mix: 0.161417
AV: 00:00:04 / 00:22:09 (0%) A-V:  0.000 Cache:  2s+21053KB
[vo/opengl] inter frame ppts: 14270199, pts: 14312184, vsync: 14300334, mix: 0.415556
AV: 00:00:04 / 00:22:09 (0%) A-V:  0.000 Cache:  2s+21053KB
[vo/opengl] inter frame ppts: 14312184, pts: 14353169, vsync: 14333787, mix: 0.537672
AV: 00:00:04 / 00:22:09 (0%) A-V:  0.000 Cache:  2s+21053KB
[vo/opengl] inter frame ppts: 14353169, pts: 14395122, vsync: 14383657, mix: 0.407557
AV: 00:00:04 / 00:22:09 (0%) A-V:  0.000 Cache:  2s+21053KB
[vo/opengl] inter frame ppts: 14395122, pts: 14437081, vsync: 14433654, mix: 0.170557
AV: 00:00:04 / 00:22:09 (0%) A-V:  0.000 Cache:  2s+21053KB
[vo/opengl] inter frame ppts: 14437081, pts: 14479048, vsync: 14466971, mix: 0.420172
AV: 00:00:04 / 00:22:09 (0%) A-V: -0.000 Cache:  2s+21053KB
...
```

Assuming I'm understanding the source code correctly, the timeline for interpolation is like:
```
prev_pts < prev_vsync < next_vsync < pts
```
For my case, because the fps of video is 24fps and my monitor's refresh rate is 60Hz, so I expect to get 60/24=2.5 interpolated scenes whose vsyncs are different for one same pts frame.
But, the log says each interpolated scene has different frame pts and this makes me think smoothmotion is not working.

Does the each different pts for interpolated frame mean no additional interpolated scenes?
Maybe I'm not understanding smoothmotion mechanism correctly?

**Comment by pigoz** [comment] 2015-02-14 08:16
Every other 'real' frame is interpolated. With 24fps on 60hz you get: `A A B+A B B C C C+D D D E E E+F F F `. For those  `~0.1` mix coefficients, you should use `smoothmotion-threshold=0.2` if you prefer the image to be less blurry.

Keep in mind that I removed the debug print for the 'do not interpolate' case, so in the debug log you only see outputs for the interpolated frames.

**Comment by xylosper** [comment] 2015-02-14 08:28
Ah, I totally misunderstood the mechanism. I thought the result would be (for simplicty, assume fps=20):
```
A    (2A +B)/3    (A+2B)/3    B    (2B +C)/3    (B+2C)/3    C ...
```
but obviously, from your description, smoothmotion was not what I expected. Thank you for kind explanation.

**Comment by pigoz** [comment] 2015-02-14 08:46
No, only the boundary frame is interpolated. You can think of smoothmotion as an advanced form of 3:2 pulldown.

**Comment by haasn** [comment] 2015-02-14 09:23
For what it's worth, I still think this is a reasonable feature request - as I personally think it looks significantly smoother to linearly interpolate on every frame.

Also, for what it's worth, I'm not convinced the current smoothmotion logic behaves the way the topic (and theory) describes it.

**Comment by pigoz** [comment] 2015-02-14 10:28
> For what it's worth, I still think this is a reasonable feature request - as I personally think it looks significantly smoother to linearly interpolate on every frame.

This can be added easily, it should not be called smoothmotion.

> Also, for what it's worth, I'm not convinced the current smoothmotion logic behaves the way the topic (and theory) describes it.

How so?

**Comment by xylosper** [comment] 2015-02-14 10:54
> This can be added easily, it should not be called smoothmotion.

Oh, I would like to see it. Maybe motion interpolation or motion blending?
Since current interpolation is a linear interpolation without analyzation of motion vector and compensation, I think 'blending' is more proper.
Well, I don't think there's a standard definition for such terms, so maybe you can define what you want.

**Comment by haasn** [comment] 2015-02-14 10:58
I vote for “:frame-lerp”!

**Comment by pigoz** [comment] 2015-02-14 11:14
`:blurmotion` :)

**Comment by wm4** [comment] 2015-02-14 11:51
pigoz: +1

**Comment by xylosper** [comment] 2015-02-14 12:56
blurmotion sounds good.

**Comment by lvml** [comment] 2015-02-16 22:42
I think a mode that actually tried to interpolate motion without blurring - as most modern TV sets offer - would be more useful. Even if it was limited to h.264 material where the filter could re-use the motion vectors from the encoded data to skip the CPU intensive part of performing a motion estimation on its own.

**Comment by wm4** [comment] 2015-02-17 09:32
>I think a mode that actually tried to interpolate motion without blurring - as most modern TV sets offer

This would be something completely different and can (partially) be done with vapoursynth.

**Comment by haasn** [comment] 2015-02-17 23:19
It *should* be done with vapoursynth, at that. Motion prediction-based interpolation is sufficiently non-trivial enough to call it a video filter, which actively modifies the video in some way.

Smoothmotion is essentially a way of trying to accurately display a video on a monitor that doesn't match its refresh rate, which is semantically part of the renderer's job - replicating the source material as accurately as possible. (This is also the reason why things like color management exist. In effect, smoothmotion can be seen as a type of “refresh rate management” - we adapt 24 Hz content to a 60 Hz display while preserving end-to-end accuracy)

The main difference between the original smoothmotion and the proposed blurmotion is basically the response time characteristics we are simulating. The original smoothmotion simulates a display with a response time of 0ms, and the blurmotion simulates a display with a response time that's effectively equal to the source framerate.

Higher response time = smoother transitions, but blurrier details

**Comment by haasn** [comment] 2015-02-18 22:39
> How so?

I didn't realize the logic changed in the meantime. The new code still makes no sense to me, though.

```p->is_interpolated = prev_pts < t->pts;```
This still makes zero sense. If prev_pts refers to the pts of the previous frame in the file, ```prev_pts < t->pts`` should always hold true. If prev_pts refers to the last rendered pts, then this is basically equivalent to asking “is a new frame available since the last time we rendered?” which, given the current “blend frames into the past, not the future” logic sort of makes sense, but it makes me feel uneasy nonetheless.

```if (prev_pts < t->next_vsync && t->pts > t->next_vsync) {```
The first part of this seems pretty redundant. The second part doesn't seem to be consistent with the rest of the logic. If we are trying to blend frames after the transition, rather than before the transition; why would we only blend them if they still lie into the *future*? Unless you reworked that stuff, in which case you might also want to check to make sure it's not too far into the future.

```
double N = t->next_vsync - t->prev_vsync;
double P = t->pts - t->prev_vsync;
float ts = p->opts.smoothmotion_threshold;
inter_coeff = 1 - (N / P);
```
This is the part that's most worrisome. Why are you using N/P? ```t->next_vsync - t->prev_vsync``` refers to the time between individual rendered frames, which is pretty much constant. You are effectively using the *inverse* of the actual blending factor, which should be P/N.

Huh?

**Comment by pigoz** [comment] 2015-02-19 11:03
> `p->is_interpolated = prev_pts < t->pts;`
> This still makes zero sense. If prev_pts refers to the pts of the previous frame in the file, `prev_pts < t->pts` should always hold true. If prev_pts refers to the last rendered pts, then this is basically equivalent to asking “is a new frame available since the last time we rendered?” which, given the current “blend frames into the past, not the future” logic sort of makes sense, but it makes me feel uneasy nonetheless.

This is needed at start or VO reset after seek.

> `if (prev_pts < t->next_vsync && t->pts > t->next_vsync) {`
> The first part of this seems pretty redundant. The second part doesn't seem to be consistent with the > rest of the logic. If we are trying to blend frames after the transition, rather than before the transition; > why would we only blend them if they still lie into the future?

We are blending at the last vsync BETWEEN the previous vsync and the next pts. It makes no sense blend the frame after it's due pts has come, because at that moment, you want to display the whole new frame.

`prev_pts < t->next_vsync` can probably be removed. Actually the code is slightly broken there. To accomplish what I mentioned in the previous paragraph, the condition should be improved to make sure `t->pts - t->next_vsync < vsync_interval` (it makes no difference for 24fps on 60hz, but it will).

> This is the part that's most worrisome. Why are you using N/P? `t->next_vsync - t->prev_vsync` refers to the time between individual rendered frames, which is pretty much constant. You are effectively using the inverse of the actual blending factor, which should be P/N.

You may be right. During interpolation texture0 contains the new frame, texture1 the older frame. In glsl mix https://www.opengl.org/sdk/docs/man/html/mix.xhtml applies this `texture0×(1−inter_coeff)+texture1×inter_coeff` which equals to `new_frame×(1−inter_coeff)+old_frame×inter_coeff`.

Suppose we are in an ideal situation like 24fps -> 60hz (where a pts to be interpolated will be in the middle of next_pts and next_next_pts). So suppose `prev_vsync` is `0`, `next_vsync` is `1`,  and `next_pts` is `1.5` (`prev_pts` would be -1, I moved the origin to `prev_vsync` to make the math simple to follow).

The formula is indeed wrong and I think should be changed to (I also changed prev_vsync to next_vsync in P, I guess N should be  `t->next_next_vsync - t->next_vsync` but it doesn't make much of a difference in practice):

```
double N = t->next_vsync - t->prev_vsync; # 1
double P = t->pts - t->next_vsync; # 0.5
inter_coeff = P / N;
```

If the pts is slightly closer to the vsync, we should blend in more of the next frame:
```
double N = t->next_vsync - t->prev_vsync; # 1
double P = t->pts - t->next_vsync; # 0.4
inter_coeff = P / N; # 0.4;
glsl => new_frame×(1−0.4)+old_frame×0.4 # correctly blends more of the new frame
```

Please let me know if this makes sense.

> Also, on my machine, either of the smoothmotion options always break playback completely for sufficiently low fps, eg. --fps 1 --no-correct-pts, so this stuff is hard to test. (Works fine without smoothmotion)

Don't use `--no-correct-pts` when testing timing code, it has too many problems and special cases in the core of mpv, use `--speed`.

> Personally, I'm going to wait for blurmotion

I will not implement blurmotion, because I found out it requires additional modifications to `vo.c` timing code which is pointless for what is, imho, a useless feature.

**Comment by haasn** [comment] 2015-02-19 13:17
Okay, those comments help me figure out what's going on - when new-pts happens, texture0 gets moved to texture1 (the old texture), and texture0 is now the new one.

Furthermore, we don't necessarily want to blend *right* when a new frame is available, but possible only one frame or so into the future - I've changed the logic to account for this, but it's not perfect yet. Ideally, we want to “remember” which state we're in - if PTS is still into the future, then either the old texture is texture0, or texture1 (after the swap), and we want to set inter_coeff to 0.0 or 1.0 accordingly.

I have implemented an experimental version of this here: https://github.com/haasn/mpv/commit/8ff4a2329e5260700b72e45f3e55b12d7ecc424b

The logic I've committed right now only does this once, which seems to work fine in my testing, since new-pts always happens at most within one frame of the blend, but that doesn't make it less flawed.

I still have some printf debugging in my version of the code, which I've been carefully examining to make sure the logic itself is correct now. I'll give you an annotated sample of the output:

```
prev_pts=0 next_pts=10126451 next_vsync=10133536 vsync_interval=16667
     -> new_pts, texture0 is now texture1
     Frame: A (texture0)
     Note: This is the first frame, so interpolation is still disabled, and
           texture1 refers to nothing right now.
prev_pts=10126451 next_pts=10126451 next_vsync=10147183 vsync_interval=16667
     Frame: A (texture0)
prev_pts=10126451 next_pts=10126451 next_vsync=10159995 vsync_interval=16667
     Frame: A (texture0)
prev_pts=10126451 next_pts=10200137 next_vsync=10175131 vsync_interval=16667
     -> new_pts, texture0 (old A) is now texture1 (new A)
     Frame: A (texture1)
     Note: inter_coeff is set to 1.0 in this case. texture0 is now B
prev_pts=10200137 next_pts=10200137 next_vsync=10192049 vsync_interval=16667
     -> R=8088.000000 inter_coeff=0.485270
     Frame: A+B
     Note: The mix coefficient is approximately the theoretical 0.5
prev_pts=10200137 next_pts=10200137 next_vsync=10208519 vsync_interval=16667
     Frame: B (texture0)
prev_pts=10200137 next_pts=10241804 next_vsync=10225214 vsync_interval=16667
     -> new_pts, texture0 (old B) is now texture1 (new B)
     -> R=16590.000000 inter_coeff=0.995380
     Frame: B
     Note: We're still displaying B, the inter_coeff is nearly 1.0
prev_pts=10241804 next_pts=10241804 next_vsync=10241906 vsync_interval=16667
     Frame: C (texture0)
prev_pts=10241804 next_pts=10241804 next_vsync=10258526 vsync_interval=16667
     Frame: C (texture0)
prev_pts=10241804 next_pts=10283470 next_vsync=10275214 vsync_interval=16667
     -> new_pts, texture0 (old C) is now texture1 (new C)
     -> R=8256.000000 inter_coeff=0.495350
     Frame: C+D
prev_pts=10283470 next_pts=10283470 next_vsync=10291859 vsync_interval=16667
     Frame: D (texture0)
prev_pts=10283470 next_pts=10325137 next_vsync=10308534 vsync_interval=16667
     -> new_pts, texture0 (old D) is now texture1 (new D)
     -> R=16603.000000 inter_coeff=0.996160
     Frame: nearly D (texture1)
prev_pts=10325137 next_pts=10325137 next_vsync=10325212 vsync_interval=16667
     Frame: E (texture0)
prev_pts=10325137 next_pts=10325137 next_vsync=10341914 vsync_interval=16667
     Frame: E (texture0)
prev_pts=10325137 next_pts=10366804 next_vsync=10358542 vsync_interval=16667
     -> new_pts, texture0 (old E) is now texture1 (new E)
     -> R=8262.000000 inter_coeff=0.495710
     Frame: E+F
prev_pts=10366804 next_pts=10366804 next_vsync=10379064 vsync_interval=16667
     Frame: F (texture0)
prev_pts=10366804 next_pts=10408470 next_vsync=10391928 vsync_interval=16667
     -> new_pts, texture0 (old F) is now texture1 (new F)
     -> R=16542.000000 inter_coeff=0.992500
     Frame: nearly F (texture1)
...
```

As you can see, the overall frame pattern is:
A A A A A+B B B C C C+D D D E E E+F F F

The mixing is consistent once it gets going, but I'm not sure why frame A gets displayed two extra times right at the start. Maybe that's just benign and due to VO startup quirks, maybe it's important.

Also, I'm not sure why, but occasionally I still get flashing outputs - especially when decoding 1080p material which presumably takes longer to decode. Presumably, some of the frames haven't been updated by the time we need to mix them or something. There's obviously still some issue with the commit as-is, but at least the mixing logic is now right.

(For what it's worth: It also looks really, really smooth - when it's not distorted by flashing)

**Comment by haasn** [comment] 2015-02-19 13:31
Update: The edge case I referenced (what happens if new_pts is more than one frame before interpolation?) can be fixed easily by simply adding another condition: “new PTS is in the future, but too far way to blend”, which also eliminates the need for the extra logic in the new-pts case.

However, this is a bit trickier to pick an exact value for, since it's usually 1.0, except at the very beginning of playback (when texture1 is still empty, and it's actually texture0).

I think the easiest way to fix *that* particular corner case is to make sure texture0 *and* texture1 both hold the very first frame, at the start of playback. Is that easily doable?

Updated commit: https://github.com/haasn/mpv/commit/ef8049583bb1436e139b26fdd86d66f0d28af63c

**Comment by pigoz** [comment] 2015-02-19 13:37
The logic is ok (it's the same one I proposed, if I'm not mistaken). The red flashes are caused by the interpolation code running with a non 0 inter_coeff while texture1 is unbound.

**Comment by haasn** [comment] 2015-02-19 13:39
Apart from the red flashes, I experience a separate flashing issue when playing back [Coalgirls]_The_Borrower_Arrietty_v2_(1920x1038_Blu-Ray_FLAC)_[1E8A3AC8].mkv. It doesn't flash to red, but it flashes to black.

The only real difference between this file and the other test file I'm using is that it uses a higher bitrate, larger resolution and it's on a slower disk. I'm not sure which one of those in particular cause the flash to black issue, or where the black color is actually coming from.

**Comment by haasn** [comment] 2015-02-19 16:16
Ah, I figured out the cause of the flashing - a silly oversight on my part. The BindTexture stuff still needs to run for the other cases, otherwise there's no texture to blend!

I've squashed and rebased my commits, and the results are absolutely beautiful on my machine - pans no longer give me a headache. I could even see this replacing motion interpolation for my personal playback setup.

I would appreciate it if you could take a look at it and confirm that it's sane/fine: https://github.com/haasn/mpv/commit/34fb3637e690dc1759904b799ef50245c4a253a3

I'll merge it if I get positive feedback.

**Comment by haasn** [comment] 2015-02-20 03:54
Moved to PR #1611.

**Closed by haasn** 2015-02-20 03:54 UTC
