### ISSUE TITLE
Subtitles do not appear when switching between tracks and the video is paused

### ISSUE THREAD

**Issue by Darkmaster006** [mpv-player/mpv#12130] opened 2023-08-10 21:08 UTC
### Important Information

Provide following Information:
- [cplayer] mpv 0.35.0-579-gca4192e2 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
- Windows 10
- https://sourceforge.net/projects/mpv-player-windows/files/

### Reproduction steps

Reproduced with --no-config. Bug is still present.
Open any video with multiple subtitle tracks. Stop the video when a subtitle is shown; switch between that track and the next one.

### Expected behavior

I would expected the subtitles to be shown when I switch between tracks, while the video is paused, but this doesn't seem to be the case.

### Actual behavior

The subtitles disappear if I switch between tracks while the video is paused. They reappear when the video is played again.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/12317183/output.txt)

Thank you for any help.

**Comment by llyyr** [comment] 2023-08-10 21:14
#12123 should fix it

**Comment by Dudemanguy** [comment] 2023-08-10 23:17
Duplicate of #8311.

**Closed by Dudemanguy** 2023-08-10 23:17 UTC
Labels: os:win

**Comment by Darkmaster006** [comment] 2023-08-11 02:31
> #12123 should fix it

Thank you! Is it enough for me to update or should I update specifically by merging to master (when the pull is accepted, which it isn't at the moment, correct?). If so, how? I believe I did it a while ago but now I can't find the command I used and don't know how. Thank you.

**Comment by Dudemanguy** [comment] 2023-08-11 02:51
Since you are using windows, you just need to wait for it to be merged into the master branch and then update when a new build comes out (I presume you are using Shinchiro's builds). I think he has some update scripts or something, but I don't know the particulars.

**Comment by Darkmaster006** [comment] 2023-08-11 03:10
> Since you are using windows, you just need to wait for it to be merged into the master branch and then update when a new build comes out (I presume you are using Shinchiro's builds). I think he has some update scripts or something, but I don't know the particulars.

Alrighty! Yeah, there's an updater.bat in the folder. I do have a dual boot, though, so I'll have to update it in Linux too, but updating it there will do too. Thank you!
