### ISSUE TITLE
Clicking next rapidly on the osc breaks the osc

### ISSUE THREAD

**Issue by xnoreq** [mpv-player/mpv#3707] opened 2016-10-22 13:20 UTC
### mpv version and platform
lachs0r build mpv 0.21.0-git-e6b85c9

### Reproduction steps
Drag in a couple of videos. Rapidly click next.

### Actual behavior
After a bunch of clicks mpv goes into fullscreen (or at least the window flashes), then the osc is broken. It does not open anymore.

### Log file
```
...
[cplayer] finished playback, success (reason 2)
[cplayer]
[global] config path: 'watch_later' -> '-'
[cplayer] Playing: 00m.mkv
[cplayer] Running hook: ytdl_hook/on_load
[cplayer] Run command: hook-ack, flags=0, args=[on_load]
[osc]
[osc] stack traceback:
[osc]   @osc.lua:685: in function 'get_playlist'
[osc]   @osc.lua:1496: in function <@osc.lua:1494>
[osc]   @osc.lua:2010: in function 'process_event'
[osc]   @osc.lua:2162: in function 'cb'
[osc]   mp.defaults:107: in function 'fn'
[osc]   mp.defaults:60: in function 'handler'
[osc]   mp.defaults:339: in function 'handler'
[osc]   mp.defaults:448: in function 'call_event_handlers'
[osc]   mp.defaults:485: in function 'dispatch_events'
[osc]   mp.defaults:441: in function <mp.defaults:440>
[osc]   [C]: at 0x7ff7a983ccf0
[osc]   [C]: at 0x7ff7a983c2e0
[ifo] Opening 00n.mkv
[osc] Lua error: @osc.lua:677: attempt to index local 'item' (a nil value)
[cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding3]
...
```

**Comment by wiiaboo** [comment] 2016-10-22 13:27
Duplicate of #3691 
You can rebuild mpv with it or if using a release, grab the updated osc.lua to your scripts directory and add `no-osc` to your mpv.conf, at least until 0.21.1 gets released.

**Closed by wiiaboo** 2016-10-22 13:27 UTC
