### ISSUE TITLE
[dailymotion] Cannot play dailymotion videos when the chosen format_id is not hls

### ISSUE THREAD

**Issue by sebma** [mpv-player/mpv#6675] opened 2019-04-29 23:38 UTC
### mpv version and platform

mpv v0.29 on Ubuntu

### Reproduction steps
```
$(which mpv) --no-config --ytdl-format "http-380/best" https://www.dailymotion.com/video/x4i73yh
Playing: https://www.dailymotion.com/video/x4i73yh
[ffmpeg] https: HTTP error 403 Forbidden
Failed to open https://www.dailymotion.com/cdn/H264-512x384/video/x4i73yh.mp4?sec=8EZJXfjL9449Kw8fsikFvaNlPfOq8saEr61KfoBoTqHk1QDMgqSKzE-FhslJ76-0.


Exiting... (Errors when loading file)
```
### Expected behavior
mpv plays any dailymotion http video format (http-144, http-240, http-380, http-480, ...)
### Actual behavior
mpv fails to play any dailymotion http video format and cannot fallback to "best" (maybe because it is an http video format as well)

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/3129497/output.txt)

**Comment by zc62** [comment] 2019-04-30 19:25
There is no such thing as "http video format".

This is not a pure http video link. `youtube-dl`, along with the mpv built-in script `ytdl_hook.lua`, needs to extract the true http link for the video file to feed to mpv.

I can reproduce the error, and `youtube-dl` itself can correctly download the video. Something in `ytdl_hook.lua` I guess.

**Comment by sebma** [comment] 2019-04-30 20:29
@zc62 What I meant by **http video formats** was http video `format_id`s : 
```
$ youtube-dl -F https://www.dailymotion.com/video/x4i73yh | grep http
http-144     mp4        176x144    
http-240     mp4        320x240    
http-380     mp4        512x384    
http-480     mp4        848x480    (best)
```

**Comment by zc62** [comment] 2019-04-30 20:59
As long as the correct url is resolved by `youtube-dl` and `ytdl_hook.lua`, I don't think picking up http-380 or best will be a problem following that. Don't over-complicate this issue. This is simply "cannot play dailymotion videos", which can be easily reproduced by
```
mpv --no-config https://www.dailymotion.com/video/x4i73yh
```
I'm not sure if `ytdl_hook.lua` is supposed to support dailymotion, though.

**Comment by sebma** [comment] 2019-04-30 21:37
@zc62 `youtube-dl` does support dailymotion

**Comment by zc62** [comment] 2019-04-30 21:45
I know that... If you really read my first comment.

**Comment by sebma** [comment] 2019-04-30 22:24
Oh, I'm sorry.

**Comment by sebaro** [comment] 2019-05-04 19:47
It doesn't happen on all videos:
```
mpv --ytdl=yes https://www.dailymotion.com/video/x2ryxz5
Playing: https://www.dailymotion.com/video/x2ryxz5
 (+) Video --vid=1 (h264 960x544 29.970fps)
 (+) Audio --aid=1 (aac 2ch 44100Hz)
Using hardware decoding (vdpau).
VO: [vdpau] 960x544 vdpau[yuv420p]
AO: [alsa] 48000Hz stereo 2ch float
AV: 00:00:01 / 00:01:07 (2%) A-V:  0.000 Cache: 21s+5MB
```
```
mpv --ytdl=yes https://www.dailymotion.com/video/x4idiii
Playing: https://www.dailymotion.com/video/x4idiii
[ffmpeg] https: HTTP error 403 Forbidden
Failed to open https://www.dailymotion.com/cdn/H264-1920x1080/video/x4idiii.mp4?sec=e7zJ3fymWuXU9vIdoU84opXJkFGaC3IqrScEuFOWDV211aw9mUZm3uMbkeGbfqmU.
```

I also get 403 when getting the stream with a user script.

**Comment by sebma** [comment] 2019-05-04 23:16
@sebaro This issue does not happen for videos that don't have any `http` like `format_id` : 

```bash
$ youtube-dl --ignore-config --get-filename -o "%(format_id)s" https://www.dailymotion.com/video/x2ryxz5
hls-720-3
$ youtube-dl -F https://www.dailymotion.com/video/x2ryxz5
 | grep -v dailymotion
[info] Available formats for x2ryxz5:
format code  extension  resolution note
hls-144-0    mp4        192x112     105k , avc1.42000b, mp4a.40.5
hls-144-1    mp4        192x112     105k , avc1.42000b, mp4a.40.5
hls-144-2    mp4        192x112     105k , avc1.42000b, mp4a.40.5
hls-144-3    mp4        192x112     105k , avc1.42000b, mp4a.40.5
hls-240-0    mp4        320x184     246k , avc1.42000d, mp4a.40.5
hls-240-1    mp4        320x184     246k , avc1.42000d, mp4a.40.5
hls-240-2    mp4        320x184     246k , avc1.42000d, mp4a.40.5
hls-240-3    mp4        320x184     246k , avc1.42000d, mp4a.40.5
hls-380-0    mp4        512x288     460k , avc1.420016, mp4a.40.5
hls-380-1    mp4        512x288     460k , avc1.420016, mp4a.40.5
hls-380-2    mp4        512x288     460k , avc1.420016, mp4a.40.5
hls-380-3    mp4        512x288     460k , avc1.420016, mp4a.40.5
hls-480-0    mp4        848x480     836k , avc1.64001f, mp4a.40.2
hls-480-1    mp4        848x480     836k , avc1.64001f, mp4a.40.2
hls-480-2    mp4        848x480     836k , avc1.64001f, mp4a.40.2
hls-480-3    mp4        848x480     836k , avc1.64001f, mp4a.40.2
hls-720-0    mp4        952x544    2149k , avc1.64001f, mp4a.40.2
hls-720-1    mp4        952x544    2149k , avc1.64001f, mp4a.40.2
hls-720-2    mp4        952x544    2149k , avc1.64001f, mp4a.40.2
hls-720-3    mp4        952x544    2149k , avc1.64001f, mp4a.40.2 (best)
```

**Comment by sebaro** [comment] 2019-05-06 05:36
You are right, hls streams do work wth youtube-dl:
```
mpv --ytdl=yes --ytdl-format=hls-720-3 https://www.dailymotion.com/video/x4idiii
Playing: https://www.dailymotion.com/video/x4idiii
 (+) Video --vid=1 (h264 1280x720 24.000fps)
 (+) Audio --aid=1 (aac 1ch 44100Hz)
Using hardware decoding (vdpau).
AO: [alsa] 48000Hz mono 1ch float
VO: [vdpau] 1280x720 vdpau[yuv420p]
AV: 00:00:01 / 00:00:37 (3%) A-V: -0.000 Cache: 23s+6MB
```

But aren't working if I pass them from the video page source code:
```
mpv "https://www.dailymotion.com/cdn/manifest/video/x2ryxz5.m3u8?sec=Cehp8Gpp_AkvC8je0Wv1oKjMeFwrUmsjHwtd1XMt9W06POgM7r2XvBliy4Is75dHS1BHpITFDkHuHLkBvvtbEg&include=720"
Playing: https://www.dailymotion.com/cdn/manifest/video/x2ryxz5.m3u8?sec=Cehp8Gpp_AkvC8je0Wv1oKjMeFwrUmsjHwtd1XMt9W06POgM7r2XvBliy4Is75dHS1BHpITFDkHuHLkBvvtbEg&include=720
[ffmpeg] https: HTTP error 403 Forbidden
[lavf] avformat_open_input() failed
```
I assume it's a ffmpeg issue because ffplay doesn't play it either.
VLC does play this.

**Comment by sebma** [comment] 2019-05-06 09:36
@sebaro On my system, `ffmpeg` AND `vlc` cannot play it, there are both forbidden by the web server with a HTTP 403 error : 
```
$ ffplay -hide_banner "$(ytdl -gf best https://www.dailymotion.com/video/x4idiii)"
[https @ 0x7efbc8005fc0] HTTP error 403 Forbidden sq=    0B f=0/0   
https://www.dailymotion.com/cdn/H264-1920x1080/video/x4idiii.mp4?sec=e7zJ3fymWuXU9vIdoU84onwGE0RIXBLcSHwEDLm1hcIdq7EryWzSQ8zBFkSQL_2x: Server returned 403 Forbidden (access denied)

$ cvlc "$(ytdl -gf best https://www.dailymotion.com/video/x4idiii)"
VLC media player 2.2.8 Weatherwax (revision 2.2.7-14-g3cc1d8cba9)
[0000000002752398] core interface error: no suitable interface module
[00000000026072b8] core libvlc error: interface "pause_click,none" initialization failed
[000000000272b7f8] [http] lua interface: Lua HTTP interface
[0000000002752ed8] dummy interface: using the dummy interface module...
[00007efbd8000e98] http access error: error: HTTP/1.1 403 Forbidden
[00007efbd8000e98] http access error: error: HTTP/1.0 403 Forbidden
[00007efbdc025048] core input error: open of `https://www.dailymotion.com/cdn/H264-1920x1080/video/x4idiii.mp4?sec=e7zJ3fymWuXU9vIdoU84osNXInsivEUIKzNYTAfveQmijhfAEZUac0PqICfESqMK' failed
[00007efbdc025048] core input error: Your input can't be opened
[00007efbdc025048] core input error: VLC is unable to open the MRL 'https://www.dailymotion.com/cdn/H264-1920x1080/video/x4idiii.mp4?sec=e7zJ3fymWuXU9vIdoU84osNXInsivEUIKzNYTAfveQmijhfAEZUac0PqICfESqMK'. Check the log for details.
^C
```
But my web browser can : 
`$ palemoon "$(ytdl -gf best https://www.dailymotion.com/video/x4idiii)"`

Maybe this has something to do with the user agent ?

I downloaded the video and here it is : 
```
$ wget -nv -O x4idiii.mp4 "$(ytdl -gf best https://www.dailymotion.com/video/x4idiii)"
2019-05-06 11:33:15 URL:https://proxy-021.ix7.dailymotion.com/sec(xSAlbkkQ_fbrdttNcPRyDo408M37iy3_XcoBOz5UCsb_dMAO8m1ABxHLpihQnRvJquZzUKej2sWn0YTEfbwyOA)/video/413/827/272728314_mp4_h264_aac_fhd.mp4 [28452417/28452417] -> "x4idiii.mp4" [1]
$ ffprobe -hide_banner x4idiii.mp4
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'x4idiii.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.25.100
  Duration: 00:00:37.52, start: 0.000000, bitrate: 6065 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 5997 kb/s, 24 fps, 24 tbr, 12288 tbn, 48 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 80 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
```

Do you know where the vlc log is (their team never display its path in the output by default) ?

**Comment by sebma** [comment] 2019-05-06 10:21
@sebaro Are you sure the direct URL you're using is the one given by `hls-720-3` format : 
```
$ youtube-dl --ignore-config -gf hls-720-3 https://www.dailymotion.com/video/x4idiii
https://proxy-034.dc3.dailymotion.com/sec(vlh-KpwGb8HUr2KugsbYOZnOPT9ehsR88Q45fevAGUcUFtU54QS6OM8oKI97AS7L4C8TNZ2CI1nWU32lK7M-1uu1cmvpIT5Q0PMSJsgbJ3Y)/video/413/827/272728314_mp4_h264_aac_hd.m3u8
```

**Comment by sebaro** [comment] 2019-05-06 10:27
The hls in my comment is from the video page source code (my user scripts) not from youtube-dl.
```
"$(youtube-dl --ignore-config -gf best https://www.dailymotion.com/video/x4idiii)"
```
The command works for me with vlc and browser but not with mpv and ffplay.

VLC logs are in syslog if enabled in Preferences. Use -v, -vv.

**Comment by sebma** [comment] 2019-05-06 10:42
@sebaro I didn't know you would react so fast :)

Please ignore the comment regarding the best format I was talking , I just deleted it because on your video `https://www.dailymotion.com/video/x4idiii`, the best format is not hls, it's `http-1080`.

I wonder, why do you have implemented a user script instead of using `youtube-dl` in the first place ?

**Comment by sebma** [comment] 2019-05-06 10:52
@sebaro In your comment : https://github.com/mpv-player/mpv/issues/6675#issuecomment-489505142 ,

I first thought the direct URL you were giving : 
`https://www.dailymotion.com/cdn/manifest/video/x2ryxz5.m3u8?sec=Cehp8Gpp_AkvC8je0Wv1oKjMeFwrUmsjHwtd1XMt9W06POgM7r2XvBliy4Is75dHS1BHpITFDkHuHLkBvvtbEg&include=720`

was associated with the first video : `https://www.dailymotion.com/video/x4idiii`

that's why it had me completely confused, lol.

**Comment by sebma** [comment] 2019-05-06 11:07
@sebaro I tried to create a trac ffmpeg account one month ago to be able create issues.

I've never managed to get the ffmpeg verification email to unlock the permissions on my ffmpeg account : 

> Warning: Your permissions have been limited until you verify your email address.

Maybe there's something wrong with their trac SMTP server (down?, etc...)

Can you please create a ffmpeg issue for that ?

**Comment by sebaro** [comment] 2019-05-06 13:54
I think you should wait for a response from mpv developers, if they decide it's an ffmpeg issue then open a ticket there.

**Comment by jane1969** [comment] 2019-05-08 16:55
If it can help, opening a Dailymotion video in mpc-hc also using youtube-dl spawns a window with a security alert, saying "The informations of revocation of the certificate of security relative to this site are not available. Do you want to continue ?" (sorry if the translation is bad). Only if you click on "yes" can mpc-hc play the video.
With mpv or mpv+SMPlayer, this window is not displayed, and the load fails.

**Comment by remitamine** [comment] 2019-05-18 00:34
Duplicate of #6421, [reported upstream](https://trac.ffmpeg.org/ticket/7660), [patch available](https://patchwork.ffmpeg.org/patch/11685/) but not merged.

**Comment by sebma** [comment] 2019-05-23 09:25
@remitamine Congratulation on your work and patch to fix this bug.

Do we have to wait for `ffmpeg` to fix it or is there a workaround with `mpv` ?

**Comment by sebma** [comment] 2019-05-23 09:34
@remitamine Maybe you should increase the priority of the [ffmpeg bug # 7660](https://trac.ffmpeg.org/ticket/7660) you reported because many dailymotion videos  cannot be played when using the "best" format.

**Comment by remitamine** [comment] 2019-05-23 11:16
> Do we have to wait for the ffmpeg team to fix it or is there a workaround with mpv ?

the issue should be fixed in FFmpeg, however for some reason, the reviewers of the patch want to know why the fragment identifier is there in the URL(it's added by Dailymotion after redirect not by the user), which I don't really have an answer neither the person who sent the patch.
> Maybe you should increase the priority of the FFmpeg bug #7660 you reported because many dailymotion videos cannot be played when using the best format.

a higher priority is only assigned to critical issues or issues affecting lots of users (FFmpeg developers decision).

**Comment by Akemi** [comment] 2019-09-19 20:07
Duplicate of #6421

**Closed by Akemi** 2019-09-19 20:07 UTC
Labels: ytdl-hook
