### ISSUE TITLE
Irregular segmentation faults with mpv and nouveau

### ISSUE THREAD

**Issue by orbea** [mpv-player/mpv#2799] opened 2016-02-06 23:27 UTC
os: Slackware-current
```
$ mpv --version
mpv git-563b478 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sat Feb  6 12:19:47 PST 2016
ffmpeg library versions:
   libavutil       54.31.100
   libavcodec      56.60.100
   libavformat     56.40.101
   libswscale      3.1.101
   libavfilter     5.40.101
   libswresample   1.2.101
ffmpeg version: 2.8.6
```
mesa: ea7f64f_2016.02.03
xf86-video-nouveau: b824d36_2016.01.13
libdrm: 682eaa0_2016.01.29

I have been experiencing mpv segmentation faults for a while, but not at a regular rate so I compiled ffmpeg, mesa and libdrm with debug symbols and with patience got the following backtrace.
```
(gdb) run --playlist playlist
Starting program: /usr/bin/mpv --playlist playlist
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe4679700 (LWP 9991)]
[playlist] Reading plaintext playlist.
[Thread 0x7fffe4679700 (LWP 9991) exited]
[New Thread 0x7fffe4679700 (LWP 9992)]
[New Thread 0x7fffe8fc0700 (LWP 9993)]
[New Thread 0x7fffe87bf700 (LWP 9994)]
Playing: ./[ACX]Trinity_Blood_08_Silent_Noise_[SS_Alternative]_[3E0DABB8].mkv
[New Thread 0x7fffe7fbe700 (LWP 9995)]
[New Thread 0x7fffe77bd700 (LWP 9996)]
[Thread 0x7fffe7fbe700 (LWP 9995) exited]
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=eng (*) (vorbis)
     Audio --aid=2 --alang=jpn (vorbis)
 (+) Subs  --sid=1 --slang=eng (*) (ass)
File tags:
 Title: Trinity Blood 08 Silent Noise [AnimeCorpX]
[New Thread 0x7fffe7fbe700 (LWP 9997)]
[New Thread 0x7fffe6fbc700 (LWP 9998)]
[New Thread 0x7fffe67bb700 (LWP 9999)]
[New Thread 0x7fffe2a2d700 (LWP 10036)]
[New Thread 0x7fffe2114700 (LWP 10037)]
AO: [openal] 48000Hz stereo 2ch floatp
Using hardware decoding (vdpau).
VO: [opengl-hq] 720x480 => 768x480 vdpau
Mesa: User error: GL_INVALID_OPERATION in VDPAUFiniNV
[sub/ass] Neither PlayResX nor PlayResY defined. Assuming 384x288
AV: 00:00:00 / 00:23:43 (0%) A-V:  0.000 Cache:  9s+97MB
Program received signal SIGSEGV, Segmentation fault.
0x00007fffe503902c in pushbuf_kref ()
   from /usr/lib64/../lib64/libdrm_nouveau.so.2
(gdb) bt full
#0  0x00007fffe503902c in pushbuf_kref ()
   from /usr/lib64/../lib64/libdrm_nouveau.so.2
No symbol table info available.
#1  0x00007fffe50396c9 in pushbuf_validate ()
   from /usr/lib64/../lib64/libdrm_nouveau.so.2
No symbol table info available.
#2  0x00007fffe571e946 in PUSH_KICK (push=<optimized out>)
    at ./nouveau_winsys.h:59
No locals.
#3  nvc0_flush (pipe=0x7fffd85f9520, fence=<optimized out>, 
    flags=<optimized out>) at nvc0/nvc0_context.c:41
        screen = <optimized out>
#4  0x00007fffe47c2a75 in vlVdpVideoSurfaceClear (vlsurf=vlsurf@entry=0xfd7f00)
    at surface.c:392
        pipe = <optimized out>
        surfaces = 0xf46938
        i = <optimized out>
#5  0x00007fffe47c2c1e in vlVdpVideoSurfaceCreate (device=<optimized out>, 
    chroma_type=0, width=720, height=480, surface=0x7fffd85fe6f8)
    at surface.c:104
        pipe = 0x7fffd85f9520
        p_surf = 0xfd7f00
        ret = <optimized out>
        dev = 0x7fffd853e030
#6  0x000000000049d753 in ?? ()
No symbol table info available.
#7  0x00000000004a0bd2 in ?? ()
No symbol table info available.
#8  0x000000000049f914 in ?? ()
No symbol table info available.
#9  0x00007ffff625cc1f in get_buffer_internal (flags=1, frame=0x801720, 
    avctx=0x7ee680) at libavcodec/utils.c:1029
        hwaccel = 0x7ffff69be060 <ff_h264_vdpau_hwaccel>
        ret = <optimized out>
        override_dimensions = 0
#10 ff_get_buffer (avctx=avctx@entry=0x7ee680, frame=0x801720, 
    flags=flags@entry=1) at libavcodec/utils.c:1042
No locals.
#11 0x00007ffff618fc36 in thread_get_buffer_internal (flags=1, f=0x808bd8, 
    f@entry=0x599, avctx=0x7ee680) at libavcodec/pthread_frame.c:795
        p = 0x0
        err = <optimized out>
#12 ff_thread_get_buffer (avctx=0x7ee680, f=f@entry=0x808bd8, flags=1)
    at libavcodec/pthread_frame.c:880
No locals.
#13 0x00007ffff5f52e3c in alloc_picture (pic=0x808bd0, h=0x8066a0)
    at libavcodec/h264_slice.c:230
        i = <optimized out>
        ret = 0
#14 h264_frame_start (h=h@entry=0x8066a0) at libavcodec/h264_slice.c:613
        pic = 0x808bd0
        i = <optimized out>
        ret = <optimized out>
        pixel_shift = 0
---Type <return> to continue, or q <return> to quit---
        c = {128, 128, 128, -1}
#15 0x00007ffff5f5743c in ff_h264_decode_slice_header (h=h@entry=0x8066a0, 
    sl=sl@entry=0x7f42c0) at libavcodec/h264_slice.c:1654
        pps_id = <optimized out>
        ret = <optimized out>
        slice_type = 2
        tmp = <optimized out>
        i = <optimized out>
        j = <optimized out>
        last_pic_structure = 3
        last_pic_droppable = <optimized out>
        must_reinit = <optimized out>
        needs_reinit = <optimized out>
        field_pic_flag = <optimized out>
        bottom_field_flag = <optimized out>
        first_slice = <optimized out>
        frame_num = <optimized out>
        droppable = <optimized out>
        picture_structure = <optimized out>
        mb_aff_frame = <optimized out>
        last_mb_aff_frame = <optimized out>
        pps = <optimized out>
#16 0x00007ffff5f066f7 in decode_nal_units (parse_extradata=0, buf_size=479, 
    buf=0x7fffbc0097e0 "", h=0x8066a0) at libavcodec/h264.c:1521
        consumed = 219
        dst_length = 216
        bit_length = 1721
        err = 0
        ptr = <optimized out>
        nalsize = 219
        sl = 0x7f42c0
        context_count = 0
        nals_needed = <optimized out>
        idr_cleared = 0
        avctx = 0x7ee680
        nal_index = <optimized out>
        ret = <optimized out>
        buf_index = <optimized out>
        next_avc = <optimized out>
#17 h264_decode_frame (avctx=0x7ee680, data=0x7f2160, got_frame=0x7fffffffdc4c, 
    avpkt=<optimized out>) at libavcodec/h264.c:1829
        buf = 0x7fffbc0097e0 ""
        buf_size = 479
        h = 0x8066a0
        pict = 0x7f2160
        buf_index = 0
        out = <optimized out>
        i = <optimized out>
        out_idx = <optimized out>
        ret = <optimized out>
#18 0x00007ffff625e2f6 in avcodec_decode_video2 (avctx=0x7ee680, 
    picture=0x7f2160, got_picture_ptr=0x7fffffffdc4c, avpkt=0x7fffffffdc90)
    at libavcodec/utils.c:2447
        did_split = 0
---Type <return> to continue, or q <return> to quit---
        avci = 0x7eeb20
        ret = 0
        tmp = {buf = 0x7fffbc008fa0, pts = 4601940228833758151, 
          dts = 4601940228833758151, data = 0x7fffbc0097e0 "", size = 479, 
          stream_index = 0, flags = 0, side_data = 0x0, side_data_elems = 0, 
          duration = 0, destruct = 0x0, priv = 0x4000001, pos = -1, 
          convergence_duration = 0}
#19 0x00000000004a01e8 in ?? ()
No symbol table info available.
#20 0x00000000004a05f5 in ?? ()
No symbol table info available.
#21 0x000000000049ea8f in ?? ()
No symbol table info available.
#22 0x000000000049f6ab in ?? ()
No symbol table info available.
#23 0x0000000000478a8c in ?? ()
No symbol table info available.
#24 0x000000000047a180 in ?? ()
No symbol table info available.
#25 0x0000000000475e15 in ?? ()
No symbol table info available.
#26 0x000000000046d07b in ?? ()
No symbol table info available.
#27 0x000000000046ddcc in ?? ()
No symbol table info available.
#28 0x00007ffff16b36d0 in __libc_start_main () from /lib64/libc.so.6
No symbol table info available.
#29 0x0000000000412289 in ?? ()
No symbol table info available.
```
This may not be a mpv issue in particular, but I hope that mpv devs might at least have an idea why its occurring.

**Comment by kevmitch** [comment] 2016-02-07 04:41
duplicate of #2757

**Closed by kevmitch** 2016-02-07 04:41 UTC
