### ISSUE TITLE
Audio passthrough broken on newer builds >22.03.2024

### ISSUE THREAD

**Issue by mitzsch** [mpv-player/mpv#13794] opened 2024-03-30 09:49 UTC
### Important Information

Provide following Information:
- mpv version: latest working: mpv-x86_64-20240322-git-9cee441 | first broken: mpv-x86_64-20240325-git-a46ce9e
- Windows Version: Windows 10 22H2 / Windows 11 23H2
- Source of the mpv binary: shinchiro
- GPU model, driver and version: RTX 3060Ti/RTX 4060

### Reproduction steps

run `mpv.com file.mkv -audio-spdif=dts-hd,ac3,eac3,truehd -v` 
The mpv window will come up, but playback is stuck. In the log it prints

```
[ffmpeg] spdif: spdif muxer does not support any stream of type unknown
[ad] libavformat spdif initialization failed.
```

The latest working build is mpv-x86_64-20240322-git-9cee441, the first build that is broken - I can test - is build mpv-x86_64-20240325-git-a46ce9e. I suspect a build made on 23.03.2024 will show the issue, unfortunately, I don't have a build from that date. 
I suspect something on the ffmpeg side broke it. There have been some modifications made on the demuxer side. The question is, is it a bug introduced by ffmpeg and therefore needs a fix on their side or is it an API change, that needs an update on the mpv code...

Note this can also be checked with a system not capable of passing through audio* - the log output will be the same

### Expected behavior

mpv window comes up, playback is started, audio is passed through

### Actual behavior

mpv window comes up, playback is stopped/stuck

### Log file

Log says:

```
[ad] In: profile=60 samplerate=48000
[ffmpeg] spdif: spdif muxer does not support any stream of type unknown
[ad] libavformat spdif initialization failed.
```

-v -v does not yield anything more

**Comment by danbezerra** [comment] 2024-03-30 17:47
Confirmed same issue with my own private build from March 29th (Windows).

**Comment by mitzsch** [comment] 2024-03-31 09:49
Probably found the culprit:

This commit crashed it => https://github.com/FFmpeg/FFmpeg/commit/03b04eef72a5f23e30c2d7700b290d915c31d3a1
In combination with https://github.com/FFmpeg/FFmpeg/commit/a24bccc23859b37e03cbf395b3349cb4f707b3e0

Somehow it only gets Format_profile "unknown" back from the mpv(?) code...

Fix: https://github.com/mitzsch/FFmpeg/commit/907f8c7e25cf8d033d9d28c7eb6aeec3b483268f

I will let the FFmpeg devs know...

**Comment by FCrane** [comment] 2024-04-01 12:05
Confirming that bitstreaming audio does not work anymore. Hopefully this will be fixed quickly!

**Comment by mkver** [comment] 2024-04-01 15:09
Adding     stream->codecpar->codec_type = AVMEDIA_TYPE_AUDIO;
after https://github.com/mpv-player/mpv/blob/a140d2788c33e729c4a0867c69cfe596458653dc/audio/decode/ad_spdif.c#L199 should fix this.

**Comment by mitzsch** [comment] 2024-04-02 12:27
> Adding stream->codecpar->codec_type = AVMEDIA_TYPE_AUDIO; after
> 
> https://github.com/mpv-player/mpv/blob/a140d2788c33e729c4a0867c69cfe596458653dc/audio/decode/ad_spdif.c#L199
> 
> should fix this.

When applied it fails with the error:

```
[ad] In: profile=60 samplerate=48000
[ffmpeg] spdif: sample rate not set
[ad] libavformat spdif initialization failed.
```

**Comment by jeeb** [comment] 2024-04-02 15:44
Ah, so ctx to codecpar missing attributes. Thanks for the help @mkver :) .

Let's see if I can whip up a PR quickly for this.

**Comment by mitzsch** [comment] 2024-04-02 15:45
Currently compiling a version of mpv with these code snippets applied, and will report shortly. :)

**Comment by mitzsch** [comment] 2024-04-02 15:51
works!

**Comment by jeeb** [comment] 2024-04-02 15:56
For the record, I'm just checking the history here as the lack of setting media type or sample rate on the output shouldn't have really worked even before... (esp. since avctx to codecpar helpers were not being utilized)

So either it really did work for whatever reason, or some code that previously kept it working got removed.

**Comment by jeeb** [comment] 2024-04-02 16:04
Opened a PR with the media type and sample rate setting to the AVStream's codecpar. This should generate testable builds.

**Comment by jeeb** [comment] 2024-04-02 20:18
Got the x86_64 build and ran `mpv --no-config "PATH\TO\file.mkv"` from the `mpv-git-2024-04-02-3bae5c6-x86_64` directory I extracted it to and it worked. So the build does not seem to be borked at least :) .

**Comment by danbezerra** [comment] 2024-04-02 20:45
mpv --no-config <mkv> works. But when you force mpv.com file.mkv -audio-spdif=dts-hd,ac3,eac3,truehd -v, the playback never starts. I can manually scroll using the OSD, but it's always stuck in a single frame. 

No issues at all reported on the console.

**Comment by netExtra** [comment] 2024-04-02 22:03
> mpv --no-config works. But when you force mpv.com file.mkv -audio-spdif=dts-hd,ac3,eac3,truehd -v, the playback never starts. I can manually scroll using the OSD, but it's always stuck in a single frame.
> 
That's exactly what I have when using my default config with audio-spdif=dts-hd etc. But on my machine I couldn't even get it working woth --no-config which is strange.

**Comment by danbezerra** [comment] 2024-04-03 00:04
Just to clarify -no-config together with -audio-spdif doesn't work  - which makes sense since the problem is caused when you force bitstreaming. 

-no-config alone is OK (since the audio is decoded by MPV).

**Comment by mitzsch** [comment] 2024-04-03 08:31
Okay

The artifact build (https://github.com/mpv-player/mpv/pull/13809#issuecomment-2032506971) does indeed not work. As said above the play window comes up but nothing happens - playback is stuck.

However, as I said here => https://github.com/mpv-player/mpv/issues/13794#issuecomment-2032432974 the code works. I compiled a version with the patches mentioned here.

You can download it here => https://drive.google.com/file/d/1Pte3svtYeFzOXrKVBMtY5bki311UhSah/view?usp=sharing

The build is at https://github.com/mitzsch/mpv/commit/b40c24e7e0d7d05cd1173ff3ded5e48039d263a3

I know its modified, but the differences should not matter in this case. Just tried it on my HTPC and it works.
The difference in the code is just the order of the codecpar.

@jeeb 
```
    stream->codecpar->codec_type = AVMEDIA_TYPE_AUDIO;
    stream->codecpar->codec_id   = spdif_ctx->codec_id;
```

my applied patch:
```
    stream->codecpar->codec_id = spdif_ctx->codec_id;
    stream->codecpar->codec_type = AVMEDIA_TYPE_AUDIO;
```

**Comment by danbezerra** [comment] 2024-04-03 17:13
Confirmed that @mitzsch PR works.

**Comment by danbezerra** [comment] 2024-04-04 02:41
Yep, the new one works. Thanks @jeeb

**Comment by mitzsch** [comment] 2024-04-04 07:37
Jup, works. Thanks!

**Comment by kimj76** [comment] 2024-04-04 11:25
Confirmed that the patched "ad_spdif.c" is working on Linux build too. Thanks

**Comment by jeeb** [comment] 2024-04-04 14:04
Thanks for testing the PR build,  pulled the changes in :) .

**Closed** 2024-04-04 14:03 UTC
Labels: os:win

**Comment by cequalspid** [comment] 2024-04-17 06:18
Hello, I am wondering if this is fixed? I have mpv installed from Arch repo and used it for many years.
But I am struggling with this issue mentioned in this thread.

A video file will open but not play. Unless I switch the audio track to none, in which case it plays but only with no audio.

**Comment by kimj76** [comment] 2024-04-17 10:27
I build MPV on Ubuntu from git using the MPV-Build script https://github.com/mpv-player/mpv-build.git

Once the official patch went out the problem was solved with a fresh build.

I did note that under Ubuntu the change that happened in FFMPEG affected the MPV build shipped with Ubuntu.

**Comment by mitzsch** [comment] 2024-04-17 13:49
> Hello, I am wondering if this is fixed?

Yes, the issue has been fixed, maybe your build is broken due to a different issue. If building from scratch does not fix your issue you may want to open a new issue with a log.

**Comment by cequalspid** [comment] 2024-04-22 20:42
Thank you, it is working. I had to remove all pipewire for now, until i can pinpoint the issue in my install/config.
