### ISSUE TITLE
Cannot recognize embedded subtitle

### ISSUE THREAD

**Issue by njZhuMin** [mpv-player/mpv#4766] opened 2017-08-16 10:10 UTC
### Expected behavior
Could display embedded subtitle correctly, below is displayed by Quicktime
![image](https://user-images.githubusercontent.com/2182867/29357363-cafb001a-82a9-11e7-930a-538d987307b9.png)

### Actual behavior
Can't recognize embedded English subtitle.  Sure that it is NOT a encoding problem with subtitle, but not sure whether there is anything related to Apple HLS format.

This is a WWDC video, it is originally streamed m3u8 online, but I just downloaded it and it appears to be an h264 encoded mp4 file.

```bash
ffmpeg -i 703_sd_introducing_core_ml.mp4
ffmpeg version 3.3.3 Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 8.1.0 (clang-802.0.42)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.3.3 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --disable-lzma --enable-vda
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '703_sd_introducing_core_ml.mp4':
  Metadata:
    major_brand     : qt  
    minor_version   : 537199360
    compatible_brands: qt  
    creation_time   : 2017-06-14T18:52:42.000000Z
    com.apple.quicktime.player.movie.audio.gain: 1.000000
    com.apple.quicktime.player.movie.audio.treble: 0.000000
    com.apple.quicktime.player.movie.audio.bass: 0.000000
    com.apple.quicktime.player.movie.audio.balance: 0.000000
    com.apple.quicktime.player.movie.audio.pitchshift: 0.000000
    com.apple.quicktime.player.movie.audio.mute: 
    com.apple.quicktime.player.movie.visual.brightness: 0.000000
    com.apple.quicktime.player.movie.visual.color: 1.000000
    com.apple.quicktime.player.movie.visual.tint: 0.000000
    com.apple.quicktime.player.movie.visual.contrast: 1.000000
    com.apple.quicktime.player.version: 7.6.6 (7.6.6)
    com.apple.quicktime.version: 7.7.3 (2978.7) 0x7738000 (Mac OS X, 10.12.5, 16F73)
  Duration: 00:31:24.98, start: 0.000000, bitrate: 1066 kb/s
    Stream #0:0: Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 640x360 [SAR 1:1 DAR 16:9], 999 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2017-06-14T18:52:42.000000Z
      handler_name    : Apple Alias Data Handler
      encoder         : Elemental H.264
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 61 kb/s (default)
    Metadata:
      creation_time   : 2017-06-14T18:52:42.000000Z
      handler_name    : Apple Alias Data Handler
    Stream #0:2(eng): Subtitle: eia_608 (c608 / 0x38303663), 720x480, 0 kb/s, SAR 9709:8192 DAR 29127:16384 (default)
    Metadata:
      rotate          : 0
      creation_time   : 2017-06-14T18:52:42.000000Z
      handler_name    : Apple Alias Data Handler
```
![image](https://user-images.githubusercontent.com/2182867/29358210-c8c21d44-82ac-11e7-9048-e14d83576983.png)

### For testing, file is available [here](https://devstreaming-cdn.apple.com/videos/wwdc/2017/703muvahj3880222/703/703_sd_introducing_core_ml.mp4?dl=1).

**Comment by wiiaboo** [comment] 2017-08-16 10:12
Duplicate of https://github.com/mpv-player/mpv/issues/4493.

**Closed by wiiaboo** 2017-08-16 10:12 UTC
