### ISSUE TITLE
Hardware acceleration is not working when used with libmpv (0.28-master)

### ISSUE THREAD

**Issue by hmlkao** [mpv-player/mpv#5816] opened 2018-05-11 10:36 UTC
I am using an [MPV example](https://github.com/mpv-player/mpv-examples/tree/master/libmpv/qt_opengl) to show live view from IP camera via RTSP. Everything works like a charm but hardware acceleration.

mpv was build by [mpv-build tool](https://github.com/mpv-player/mpv-build).

It works well with the latest native stable mpv (for Fedora 24) 0.23.0.

### mpv version and platform

    # ./version.sh 
    0.28.0-565-ga645c6b

    # cat /etc/os-release
    NAME=Fedora
    VERSION="24 (Workstation Edition)"

    # dmidecode -t baseboard
    SMBIOS 2.8 present.
    Manufacturer: ASRock
    Product Name: J3160TM-ITX

### Reproduction steps
Use [MPV example](https://github.com/mpv-player/mpv-examples/tree/master/libmpv/qt_opengl) with set parameter hwdec=vaapi

### Expected behavior
libmpv should load VAAPI driver as mpv running from console do.

### Actual behavior
libmpv cannot load VAAPI driver (check full log bellow)

    [libmpv_render] Loading hwdec driver 'vaapi-egl'
    [libmpv_render] Loading failed.

mpv running from console (check full log bellow) works well

    [vo/gpu] Loading hwdec driver 'vaapi-egl'
    [vo/gpu/vaapi-egl] Trying to open a x11 VA display...
    [vo/gpu/vaapi-egl/vaapi] Initialized VAAPI: version 0.39
    [vo/gpu/vaapi-egl] using VAAPI EGL interop
    [vo/gpu/vaapi-egl] Supported formats:
    [vo/gpu/vaapi-egl]  nv12

### Log file
[libmpv log file](https://0x0.st/sjx7.log)
[console log file](https://0x0.st/sjxF.log)

**Comment by wm4** [comment] 2018-05-11 10:44
The example does provide any interop state for vaapi/x11.

**Comment by cmdrkotori** [comment] 2018-05-14 03:03
What you need to do is something like this.

https://github.com/cmdrkotori/mpc-qt/commit/e730a4f8570b9e3d96f0866888e21150169e50f1

It's not very elegant but it should get you started.

I agree to relicense this commit under the license terms of mpv-examples license.

**Comment by hmlkao** [comment] 2018-05-17 10:10
I found out that the the problem is already since version 0.24.0
I compiled versions 0.23.0 - 0.28.2 and the only version where hwdec works fine in libmpv is 0.23.0
I checked git log for some better informations but there were many changes about vaapi.

@cmdrkotori Thank you for example, I'll try to play with it.

**Comment by Akemi** [comment] 2019-09-20 14:56
duplicate of #6722

**Closed by Akemi** 2019-09-20 14:56 UTC
Labels: libmpv, vaapi
