### ISSUE TITLE
Flickering and blackscreen when profile=gpu-hq enabled

### ISSUE THREAD

**Issue by frnmz** [mpv-player/mpv#9579] opened 2021-12-09 11:14 UTC
### Important Information

Provide following Information:
- mpv version: **0.34**
- Linux Distribution and Version: **Fedora 35 Workstation**
- Source of the mpv binary: **Fedora repo**
- If known which version of mpv introduced the problem
- Window Manager and version: **mutter 41.1**
- GPU driver and version: **Sorry I don't know how to check for this, but I'm using Intel HD 620**
- Possible screenshot or video of visual glitches: **https://streamable.com/khfmwh**
### Reproduction steps

enable profile=gpu-hq from config files.

This is happened since yesterday, and these packages was updated the night before the flickering start to happened:
```
    Upgrade  cpp-11.2.1-7.fc35.x86_64                            @updates
    Upgraded cpp-11.2.1-1.fc35.x86_64                            @@System
    Upgrade  gcc-11.2.1-7.fc35.x86_64                            @updates
    Upgraded gcc-11.2.1-1.fc35.x86_64                            @@System
    Upgrade  gcc-c++-11.2.1-7.fc35.x86_64                        @updates
    Upgraded gcc-c++-11.2.1-1.fc35.x86_64                        @@System
    Upgrade  gcc-gdb-plugin-11.2.1-7.fc35.x86_64                 @updates
    Upgraded gcc-gdb-plugin-11.2.1-1.fc35.x86_64                 @@System
    Upgrade  gcc-gfortran-11.2.1-7.fc35.x86_64                   @updates
    Upgraded gcc-gfortran-11.2.1-1.fc35.x86_64                   @@System
    Upgrade  gtk-vnc2-1.3.0-1.fc35.x86_64                        @updates
    Upgraded gtk-vnc2-1.2.0-3.fc35.x86_64                        @@System
    Upgrade  gvnc-1.3.0-1.fc35.x86_64                            @updates
    Upgraded gvnc-1.2.0-3.fc35.x86_64                            @@System
    Upgrade  gvncpulse-1.3.0-1.fc35.x86_64                       @updates
    Upgraded gvncpulse-1.2.0-3.fc35.x86_64                       @@System
    Upgrade  hplip-3.21.2-15.fc35.x86_64                         @updates
    Upgraded hplip-3.21.2-13.fc35.x86_64                         @@System
    Upgrade  hplip-common-3.21.2-15.fc35.x86_64                  @updates
    Upgraded hplip-common-3.21.2-13.fc35.x86_64                  @@System
    Upgrade  hplip-libs-3.21.2-15.fc35.x86_64                    @updates
    Upgraded hplip-libs-3.21.2-13.fc35.x86_64                    @@System
    Upgrade  igt-gpu-tools-1.26-1.20211128gitbf11f87.fc35.x86_64 @updates
    Upgraded igt-gpu-tools-1.26-1.20211119git2e0355f.fc35.x86_64 @@System
    Upgrade  libgcc-11.2.1-7.fc35.i686                           @updates
    Upgraded libgcc-11.2.1-1.fc35.i686                           @@System
    Upgrade  libgcc-11.2.1-7.fc35.x86_64                         @updates
    Upgraded libgcc-11.2.1-1.fc35.x86_64                         @@System
    Upgrade  libgfortran-11.2.1-7.fc35.x86_64                    @updates
    Upgraded libgfortran-11.2.1-1.fc35.x86_64                    @@System
    Upgrade  libgomp-11.2.1-7.fc35.i686                          @updates
    Upgraded libgomp-11.2.1-1.fc35.i686                          @@System
    Upgrade  libgomp-11.2.1-7.fc35.x86_64                        @updates
    Upgraded libgomp-11.2.1-1.fc35.x86_64                        @@System
    Upgrade  libquadmath-11.2.1-7.fc35.x86_64                    @updates
    Upgraded libquadmath-11.2.1-1.fc35.x86_64                    @@System
    Upgrade  libquadmath-devel-11.2.1-7.fc35.x86_64              @updates
    Upgraded libquadmath-devel-11.2.1-1.fc35.x86_64              @@System
    Upgrade  libsane-hpaio-3.21.2-15.fc35.x86_64                 @updates
    Upgraded libsane-hpaio-3.21.2-13.fc35.x86_64                 @@System
    Upgrade  libspectre-0.2.9-5.fc35.x86_64                      @updates
    Upgraded libspectre-0.2.9-4.fc35.x86_64                      @@System
    Upgrade  libstdc++-11.2.1-7.fc35.i686                        @updates
    Upgraded libstdc++-11.2.1-1.fc35.i686                        @@System
    Upgrade  libstdc++-11.2.1-7.fc35.x86_64                      @updates
    Upgraded libstdc++-11.2.1-1.fc35.x86_64                      @@System
    Upgrade  libstdc++-devel-11.2.1-7.fc35.x86_64                @updates
    Upgraded libstdc++-devel-11.2.1-1.fc35.x86_64                @@System
    Upgrade  mesa-dri-drivers-21.3.1-2.fc35.i686                 @updates
    Upgraded mesa-dri-drivers-21.2.5-2.fc35.i686                 @@System
    Upgrade  mesa-dri-drivers-21.3.1-2.fc35.x86_64               @updates
    Upgraded mesa-dri-drivers-21.2.5-2.fc35.x86_64               @@System
    Upgrade  mesa-filesystem-21.3.1-2.fc35.i686                  @updates
    Upgraded mesa-filesystem-21.2.5-2.fc35.i686                  @@System
    Upgrade  mesa-filesystem-21.3.1-2.fc35.x86_64                @updates
    Upgraded mesa-filesystem-21.2.5-2.fc35.x86_64                @@System
    Upgrade  mesa-libEGL-21.3.1-2.fc35.i686                      @updates
    Upgraded mesa-libEGL-21.2.5-2.fc35.i686                      @@System
    Upgrade  mesa-libEGL-21.3.1-2.fc35.x86_64                    @updates
    Upgraded mesa-libEGL-21.2.5-2.fc35.x86_64                    @@System
    Upgrade  mesa-libGL-21.3.1-2.fc35.i686                       @updates
    Upgraded mesa-libGL-21.2.5-2.fc35.i686                       @@System
    Upgrade  mesa-libGL-21.3.1-2.fc35.x86_64                     @updates
    Upgraded mesa-libGL-21.2.5-2.fc35.x86_64                     @@System
    Upgrade  mesa-libOSMesa-21.3.1-2.fc35.i686                   @updates
    Upgraded mesa-libOSMesa-21.2.5-2.fc35.i686                   @@System
    Upgrade  mesa-libOSMesa-21.3.1-2.fc35.x86_64                 @updates
    Upgraded mesa-libOSMesa-21.2.5-2.fc35.x86_64                 @@System
    Upgrade  mesa-libgbm-21.3.1-2.fc35.i686                      @updates
    Upgraded mesa-libgbm-21.2.5-2.fc35.i686                      @@System
    Upgrade  mesa-libgbm-21.3.1-2.fc35.x86_64                    @updates
    Upgraded mesa-libgbm-21.2.5-2.fc35.x86_64                    @@System
    Upgrade  mesa-libglapi-21.3.1-2.fc35.i686                    @updates
    Upgraded mesa-libglapi-21.2.5-2.fc35.i686                    @@System
    Upgrade  mesa-libglapi-21.3.1-2.fc35.x86_64                  @updates
    Upgraded mesa-libglapi-21.2.5-2.fc35.x86_64                  @@System
    Upgrade  mesa-libxatracker-21.3.1-2.fc35.x86_64              @updates
    Upgraded mesa-libxatracker-21.2.5-2.fc35.x86_64              @@System
    Upgrade  mesa-vulkan-drivers-21.3.1-2.fc35.i686              @updates
    Upgraded mesa-vulkan-drivers-21.2.5-2.fc35.i686              @@System
    Upgrade  mesa-vulkan-drivers-21.3.1-2.fc35.x86_64            @updates
    Upgraded mesa-vulkan-drivers-21.2.5-2.fc35.x86_64            @@System
    Upgrade  perl-Mozilla-CA-20211001-1.fc35.noarch              @updates
    Upgraded perl-Mozilla-CA-20200520-6.fc35.noarch              @@System
    Upgrade  xxhash-libs-0.8.1-1.fc35.x86_64                     @updates
    Upgraded xxhash-libs-0.8.0-4.fc35.x86_64

```

### Expected behavior
No flickering and blackscreen.

### Actual behavior
Flickering and blackscreen when opening a video with profile=gpu-hq enabled.

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/7684569/log.txt)

### Sample files

This happened to all video files that I have

**Comment by haasn** [comment] 2021-12-09 13:46
Looks like a mesa regression. Does it still happen with `--gpu-api=opengl`?

**Comment by frnmz** [comment] 2021-12-09 14:00
Nope! It works perfectly with --gpu-api=opengl.
Using gpu-api=opengl instead of gpu-api=vulkan in the config file also fix the problem.

**Comment by lavilao** [comment] 2021-12-09 16:25
oh man dont tell me vulkan flickers again with 21.3... I waited a YEAR for it to be fixed! damn.

**Comment by lavilao** [comment] 2021-12-09 16:29
could you try with ```export ANV_QUEUE_THREAD_DISABLE=1```, this fixed it for me recently. Also does the osd flickers too?

**Comment by frnmz** [comment] 2021-12-09 16:59
> could you try with `export ANV_QUEUE_THREAD_DISABLE=1`, this fixed it for me recently.

how do i add `export ANV_QUEUE_THREAD_DISABLE=1`? in the config file or terminal?

> Also does the osd flickers too?

The osd flickers on `gpu-api=vulkan`, but not in `gpu-api=opengl`

Weirdly, Celluloid still have blackscreen eventhough I already use `gpu-api=opengl` in the config.
Disabling profile=gpu-hq solves the problem in Celluloid.

**Comment by lavilao** [comment] 2021-12-09 17:21
sorry for not being clear, open a terminal and type ```export ANV_QUEUE_THREAD_DISABLE=1``` then on the same terminal open a file on mpv with gpu-api=vulkan example:
```mpv -gpu-api=vulkan /path/to/file```

**Comment by frnmz** [comment] 2021-12-09 17:26
@lavilao still flickers...
https://streamable.com/rms0k0

**Comment by jbeich** [comment] 2021-12-11 21:27
If the regression appeared since https://github.com/mesa3d/mesa/commit/b996fa8efaa425 then https://github.com/haasn/libplacebo/commit/b4c65bc36160 may help.

**Comment by jbeich** [comment] 2021-12-11 21:38
Do you see similar flickering with other Vulkan applications? For example, try `GSK_RENDERER=vulkan gtk4-demo`. If so this maybe a Mesa bug.

**Comment by jbeich** [comment] 2021-12-11 21:48
Also, you can also try reverting https://github.com/mesa3d/mesa/commit/b996fa8efaa425 on `21.3` branch in order to confirm the regression (bisect otherwise). However, `main` branch (or the future `22.0`) refactored the code in https://github.com/mesa3d/mesa/commit/36ea90a3619f, so reverting is hard.

**Comment by frnmz** [comment] 2021-12-11 22:34
> Do you see similar flickering with other Vulkan applications?

I do game on Wine using DXVK and didn't see anything wrong.

> For example, try `GSK_RENDERER=vulkan gtk4-demo`. If so this maybe a Mesa bug.

`GSK_RENDERER=vulkan gtk4-demo` do not flicker in me.
But the terminal output is:
```
** Message: 05:28:35.719: For syntax highlighting, install the “highlight” program

(gtk4-demo:17280): Gsk-WARNING **: 05:28:35.740: Unrecognized renderer "vulkan". Try GSK_RENDERER=help

(gtk4-demo-application:17373): Gsk-WARNING **: 05:29:45.027: Unrecognized renderer "vulkan". Try GSK_RENDERER=help

```

**Comment by lavilao** [comment] 2021-12-11 22:59
the way thouse error presented me on other apps where that the app would freeze with console outputs of ```GPU hung on one of our command buffers (VK_ERROR_DEVICE_LOST)``` or just the ```VK_ERROR_DEVICE_LOST```, do you see any of this errors? (this presents only on heavy apps like games or mpv with shaders, it would happen with compute queues)

**Comment by lavilao** [comment] 2021-12-11 23:27
well congrats your bug is contained only on mpv, not sure why but meh, now if there was a way for you to test the lastest libplacebo... compiling it is not very hard nor tedious but to get mpv to build against a self-compiled libplacebo (is necessary for mpv to use the new one) is a pain at least in arch/manjaro and I have not used fedora to assist you, is there any mpv-dev flatpak?

**Comment by jbeich** [comment] 2021-12-11 23:53
@frnmz, can you reproduce with libplacebo snapshot?
```
$ cd /path/to/git/mpv
$ mkdir subprojects
$ git clone https://code.videolan.org/videolan/libplacebo.git subprojects/libplacebo
$ meson setup --force-fallback-for=libplacebo -Dlibplacebo:default_library=static -Dlibplacebo:demos=false _build
$ meson compile -C _build
```

> `GSK_RENDERER=vulkan gtk4-demo` do not flicker in me.
> (gtk4-demo-application:17373): Gsk-WARNING **: 05:29:45.027: Unrecognized renderer "vulkan". Try GSK_RENDERER=help

`GSK_RENDERER=vulkan` is not supported by your distro, see https://src.fedoraproject.org/rpms/gtk4/c/5338a753a3d4 and https://src.fedoraproject.org/rpms/gtk4/c/eaf1da5e7c55. If you still want to confirm rebuild gtk4 package with `-Dvulkan=enabled`.

Sorry, I don't know any other Vulkan app that regressed in Mesa >= 21.3 on Intel in a way similar to mpv.

**Comment by frnmz** [comment] 2021-12-12 01:13
>can you reproduce with libplacebo snapshot?

I'll try! Do I need to remove mpv and related packages (celluloid, libmpv, etc) before compiling libplacebo?

>If you still want to confirm rebuild gtk4 package with -Dvulkan=enabled.

I'll try this too.

**Comment by frnmz** [comment] 2021-12-12 14:08
It's not flickering, but now it's just blackscreen with sound: https://streamable.com/kqfwsl
There's this terminal output too:
`[vo/gpu/vulkan/libplacebo] Storable format 'bgr565' has no matching GLSL format qualifier but read/write without format is not supported.. disabling`
`[vo/gpu/vulkan/libplacebo] Storable format 'bgr5a1' has no matching GLSL format qualifier but read/write without format is not supported.. disabling
`
So libplacebo is not running I guess?

**Comment by lavilao** [comment] 2021-12-12 16:31
in a low res video the black screen persists or it comes back to the flickering?

**Comment by frnmz** [comment] 2021-12-13 06:05
> Please, attach mpv log to compare with the old one or find some clues.

[new&compiled.txt](https://github.com/mpv-player/mpv/files/7701328/new.compiled.txt)
[old.txt](https://github.com/mpv-player/mpv/files/7701329/old.txt)

Now that I look into old log, it seems mpv binary from fedora repo is already compiled with libplacebo, since the log mentions it a lot.

> Can you try an alternative workaround?

@jbeich What you see here https://github.com/mpv-player/mpv/issues/9579#issuecomment-991904996 is mpv + libplacebo that I build from source following your instructions.

> Learn how to build system packages from source in order to apply extra patches

What package do I need to build? If it's mesa then I think I cant, since It needs to replace currently installed mesa in my system. and I don't want to break my system...

> in a low res video the black screen persists or it comes back to the flickering?

@lavilao Yup. I tried downloading [this](https://www.youtube.com/watch?v=1LN5lmtR3hs) 360p video from youtube, and play it in both mpv from fedora repo, and mpv that I compiled myself, both are flickering.

**Comment by lavilao** [comment] 2021-12-13 15:50
@frnmz mpv is always compiled with libplacebo, is a hard dependency, what we were suggesting is to test mpv with a newer libplacebo, wich as I said before is a pain because mpv will always look for the system libplacebo not for the one you compiled. Also there is no need to recompile mesa, just downgrade mesa and test mpv, if it is fixed then is mesa fault, it will not fix the issue but it will give the guilty and if you did not gain anything from mesa 21.3 you could just stay on 21.2.5 until a new version comes.

**Comment by Akemi** [comment] 2021-12-13 18:10
> @frnmz mpv is always compiled with libplacebo, is a hard dependency,...

on a side note. it isn't.

**Comment by lavilao** [comment] 2021-12-13 18:35
@Akemi I guess one learns a new thing every day.

**Comment by lavilao** [comment] 2021-12-13 18:36
@frnmz Since you are using Fedora you should be using Gnome on the wayland session no? Try with the X11 session, it should remove the black screen issues and substitute the flickering for some weird Z form artifact, yes it sounds worse but if your gpu is powerfull enough (mine is not) it should be "good".

**Comment by frnmz** [comment] 2021-12-13 20:26
> Also there is no need to recompile mesa, just downgrade mesa and test mpv

It's definitely mesa fault. downgrading mesa 21.3 to these version solves the problem:
```
mesa-dri-drivers-21.2.5-2.fc35.i686.rpm
mesa-dri-drivers-21.2.5-2.fc35.x86_64.rpm
mesa-filesystem-21.2.5-2.fc35.i686.rpm
mesa-filesystem-21.2.5-2.fc35.x86_64.rpm
mesa-libEGL-21.2.5-2.fc35.i686.rpm
mesa-libEGL-21.2.5-2.fc35.x86_64.rpm
mesa-libgbm-21.2.5-2.fc35.i686.rpm
mesa-libgbm-21.2.5-2.fc35.x86_64.rpm
mesa-libGL-21.2.5-2.fc35.i686.rpm
mesa-libGL-21.2.5-2.fc35.x86_64.rpm
mesa-libglapi-21.2.5-2.fc35.i686.rpm
mesa-libglapi-21.2.5-2.fc35.x86_64.rpm
mesa-libOSMesa-21.2.5-2.fc35.i686.rpm
mesa-libOSMesa-21.2.5-2.fc35.x86_64.rpm
mesa-libxatracker-21.2.5-2.fc35.x86_64.rpm
mesa-vulkan-drivers-21.2.5-2.fc35.i686.rpm
mesa-vulkan-drivers-21.2.5-2.fc35.x86_64.rpm
```
see https://streamable.com/8cd1of
> Try with the X11 session, it should remove the black screen issues and substitute the flickering for some weird Z form artifact,

Flickering and blackscreen also happens in x11.

@jbeich before I'm downgrading mesa, I noticed that flickering also happened in Clapper. But in Clapper it's not only flickering, but also the frames is repeating and the audio is laggy. It's never happened before and it's also not happening after downgrading mesa.

**Comment by jbeich** [comment] 2021-12-13 21:05
@frnmz wrote in https://github.com/mpv-player/mpv/issues/9579#issuecomment-992137383:
> [   0.201][v][vo/gpu/x11] Display 0 (XWAYLAND0): [0, 0, 1366, 768] @ 59.798991 FPS

Your manually-built mpv lacks native Wayland support, so it may contribute to "just blackscreen" now. Re-try after installing `wayland-protocols` and any other development packages.

> What package do I need to build? If it's mesa then I think I cant,
> since It needs to replace currently installed mesa in my system.

Why not back up? Btrfs snapshots likely make it easy.

**Comment by jbeich** [comment] 2021-12-13 21:09
> I noticed that flickering also happened in Clapper

No clue. I haven't tested Clapper because FreeBSD still uses GStreamer 1.16.2. According to Clapper's README.md it uses OpenGL, so unlikely to be affected by Vulkan regressions.

**Comment by lavilao** [comment] 2021-12-13 21:15
@jbeich compiling mesa could break stuff, specially when fedora package it so divided, maybe compiling only the mesa-vulkan drivers would be a less intrusive approach, vulkan broken its a "ah ok lets reinstall a package" opengl broken its a "oh shit what have I done!"

**Comment by lavilao** [comment] 2021-12-13 21:21
no, it does not asks for wayland-protocols

**Comment by frnmz** [comment] 2021-12-13 21:26
> Your manually-built mpv lacks native Wayland support, so it may contribute to "just blackscreen" now. Re-try after installing wayland-protocols and any other development packages.

> should not mpv have asked him to install wayland protocols?

Sorry, I'm trying my best to install all dependencies that needed for compiling. Meson do not return to error after certain dependencies installation so I thought it's already ok to compile...
I'm gonna try to compile again after this.

@jbeich @lavilao Mesa documentation mentions this:  https://docs.mesa3d.org/install.html#running-against-a-local-build.
Would it be enough to test?

**Comment by lavilao** [comment] 2021-12-13 21:29
in theory yes, but if mpv looks for the system mesa then you are out of luck

**Comment by jbeich** [comment] 2021-12-13 21:31
> Would it be enough to test?

Sure if you can confirm manually-built 21.3.* is affected while manually-built 21.2.* is not. When changing build configuration it's important to ensure the regression isn't masked by something different from distro recipe (aka source package).

**Comment by jbeich** [comment] 2021-12-13 21:33
Also, once you're familar with how your distro builds packages you no longer need to learn all the shenanigans of upstream/vendor build like the numerious options Mesa provides.

**Comment by lavilao** [comment] 2021-12-13 21:39
OMG! I just installed mesa-21.3 and vulkan-intel-21.3 to test and WHAT HAVE THEY DONE! its even worse than before! I can only see a frame when the video is paused, my suggestion is stay on mesa 21.2.5 and block its updates until a newer version comes, like I said before if you did not gain anything from 21.3 then you will lose nothing by staying on 21.2. Thank goodness manjaro did  not ship 21.3 yet.

**Comment by frnmz** [comment] 2021-12-13 21:46
> OMG! I just installed mesa-21.3 and vulkan-intel-21.3 to test and WHAT HAVE THEY DONE! its even worse than before! I can only see a frame when the video is paused, my suggestion is stay on mesa 21.2.5 and block its updates until a newer version comes, like I said before if you did not gain anything from 21.3 then you will lose nothing by staying on 21.2. Thank goodness manjaro did not ship 21.3 yet.

Sorry it's not me that purposedly want to install mesa 21.3...
Fedora ship it to the default update repo.
And I was just updating my system with `sudo dnf up`.
I'm not even in testing repo...

I'll exclude mesa package in dnf config so dnf won't upgade it to 21.3

**Comment by lavilao** [comment] 2021-12-13 21:48
ok after some initial testing (and ranting) I have some good news and some bad news, the good ones is that with -vo=gpu-next the frame flickering is gone when using -profile=gpu-hq (tested with mpv -no-config -vo=gpu-next -gpu-api=vulkan -profile=gpu-hq on a 720p h264 video) the bad news is that now the osd (shift+i) flickers to the point where you cant see it until you pause the video and most importantly you would have to manually compile libplacebo 185 (the git version) and compile mpv against that libplacebo to have gpu-next as a vo.

**Comment by lavilao** [comment] 2021-12-13 22:16
@frnmz could you run this on terminal ```MESA_LOADER_DRIVER_OVERRIDE=zink glxgears``` how many fps does it gives you? am asking this because on 21.3 it gives me 3 fps while on 21.2.5 it runs at 60 fps (and more if vblank_mode=0), if you are also having this issue then this should be told to the mesa devs because it is clearly a bug on mesa.

**Comment by frnmz** [comment] 2021-12-14 00:50
@lavilao Mesa 21.2.5:
```
302 frames in 5.0 seconds = 60.316 FPS
299 frames in 5.0 seconds = 59.785 FPS
297 frames in 5.0 seconds = 59.393 FPS
```
Mesa 21.3:
```
89 frames in 5.0 seconds = 17.754 FPS
90 frames in 5.0 seconds = 17.963 FPS
90 frames in 5.0 seconds = 17.969 FPS
```

**Comment by lavilao** [comment] 2021-12-14 00:52
confirmed, it's a mesa bug

**Comment by frnmz** [comment] 2021-12-14 00:54
> confirmed, it's a mesa bug

Should I open a new issue in mesa github?

**Comment by lavilao** [comment] 2021-12-14 00:56
yes please

**Comment by frnmz** [comment] 2021-12-14 04:08
Posted! https://gitlab.freedesktop.org/mesa/mesa/-/issues/5744

**Comment by lavilao** [comment] 2021-12-14 12:28
@frnmz thanks new lets hope they fix it

**Comment by frnmz** [comment] 2021-12-15 08:27
Strangely, even without using any config, flickers still happens in Celluloid with Mesa 21.3.
It's not as bad as when using profile=gpu-hq and gpu-api=vulkan, but video, osd, and subs flickers still happens sometimes in Celluloid.
Is there any difference between mpv and Celluloid?

**Comment by LaserEyess** [comment] 2021-12-19 16:15
FYI this is (allegedly) fixed in mesa now. Can someone who can reproduce this test with mesa 21.3.2? Or test with https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/14237

**Comment by lavilao** [comment] 2021-12-19 17:05
tried 21.3.2 from arch testing repos... it straight up leave me without any vulkan suport xD
```
vulkaninfo | grep drm
ERROR: [Loader Message] Code 0 : /usr/lib/libvulkan_intel.so: undefined symbol: wl_proxy_marshal_flags
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at /build/vulkan-tools/src/Vulkan-Tools-1.2.199/vulkaninfo/vulkaninfo.h:687:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
```

**Comment by LaserEyess** [comment] 2021-12-19 18:16
Did you make sure to also update your vulkan drivers to the testing version?

**Comment by lavilao** [comment] 2021-12-19 18:21
downloaded all the mesa packages from testing and then ```sudo pacman -U mesa-21.3.2-1-x86_64.pkg.tar.zst lib32-mesa-21.3.2-1-x86_64.pkg.tar.zst vulkan-intel-21.3.2-1-x86_64.pkg.tar.zst lib32-vulkan-intel-21.3.2-1-x86_64.pkg.tar.zst```, after that no more vulkan and the opengl performance was horrible, here is the ppssppsdl log 
```
PPSSPPSDL                                            
VulkanMayBeAvailable: Device allowed ('SDL:Linux')
VulkanMayBeAvailable: Library loaded ('libvulkan.so')
VulkanMayBeAvailable: Enumerating instance extensions
VulkanMayBeAvailable: Instance extension count: 2
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_report (0000000a)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_utils (00000002)
Surface extension not found
DEBUG: Vulkan is not available, not using Vulkan.
libGL error: failed to create dri screen
libGL error: failed to load driver: zink
Info: We compiled against SDL version 2.0.16, but we are linking against SDL version 2.0.18., be aware that this can lead to unexpected behaviors
ThreadManager::Init(compute threads: 2, all: 6)
00:27:046 Core/Config.cpp:627 I[G3D]: Longest display side: -1 pixels. Choosing scale 1
00:27:103 Core/Config.cpp:1409 I[LOADER]: Loading controller config: /home/luis/.config/ppsspp/PSP/SYSTEM/controls.ini
00:27:225 Core/Config.cpp:1452 I[LOADER]: Config loaded: '/home/luis/.config/ppsspp/PSP/SYSTEM/ppsspp.ini'
00:27:344 Core/Config.cpp:1534 I[LOADER]: Config saved (got storage permission): '/home/luis/.config/ppsspp/PSP/SYSTEM/ppsspp.ini'
00:27:345 Core/Config.cpp:1547 I[LOADER]: Controller config saved: /home/luis/.config/ppsspp/PSP/SYSTEM/controls.ini
Pixels: 960 x 544
Virtual pixels: 960 x 544
00:27:429 Vulkan/VulkanLoader.cpp:468 I[G3D]: VulkanLoad: Found library 'libvulkan.so'
00:27:430 Vulkan/VulkanLoader.cpp:489 I[G3D]: VulkanLoad: Base functions loaded.
Vulkan init error 'Vulkan not loaded - no surface extension' - falling back to GL
OpenGL 2.0 or higher.
00:27:705 OpenGL/GLFeatures.cpp:188 W[G3D]: Unknown GL vendor: 'Mesa/X.org'
00:27:706 OpenGL/GLFeatures.cpp:195 I[G3D]: GPU Vendor : Mesa/X.org ; renderer: llvmpipe (LLVM 13.0.0, 128 bits) version str: 4.5 (Core Profile) Mesa 21.3.2 ; GLSL version str: 4.50
loading control pad mappings from gamecontrollerdb.txt: SUCCESS!
00:27:799 UI/NativeApp.cpp:904 I[SYSTEM]: NativeInitGraphics
00:27:799 Core/Core.cpp:198 I[G3D]: pixel_res: 1366x768. Calling NativeResized()
00:27:799 UI/NativeApp.cpp:1485 I[G3D]: NativeResized - setting flag
00:27:816 UI/NativeApp.cpp:973 I[SYSTEM]: NativeInitGraphics completed
00:28:017 OpenGL/GLRenderManager.cpp:237 I[G3D]: Running first frame (0)
00:28:494 SDL/SDLGLGraphicsContext.cpp:432 I[G3D]: SDL SwapInterval: 0
00:29:047 Core/Config.cpp:1534 I[LOADER]: Config saved (clearFailedGPUBackends): '/home/luis/.config/ppsspp/PSP/SYSTEM/ppsspp.ini'
00:29:048 Core/Config.cpp:1547 I[LOADER]: Controller config saved: /home/luis/.config/ppsspp/PSP/SYSTEM/controls.ini
00:38:935 Core/Config.cpp:1534 I[LOADER]: Config saved (GameSettingsScreen::onFinish): '/home/luis/.config/ppsspp/PSP/SYSTEM/ppsspp.ini'
00:38:936 Core/Config.cpp:1547 I[LOADER]: Controller config saved: /home/luis/.config/ppsspp/PSP/SYSTEM/controls.ini
00:40:686 Core/Config.cpp:1534 I[LOADER]: Config saved (MainScreen::OnExit): '/home/luis/.config/ppsspp/PSP/SYSTEM/ppsspp.ini'
00:40:687 Core/Config.cpp:1547 I[LOADER]: Controller config saved: /home/luis/.config/ppsspp/PSP/SYSTEM/controls.ini
00:41:029 OpenGL/GLRenderManager.cpp:266 I[G3D]: GL submission thread paused. Frame=0
00:41:029 UI/NativeApp.cpp:1023 I[SYSTEM]: NativeShutdownGraphics
00:41:030 UI/NativeApp.cpp:1063 I[SYSTEM]: NativeShutdownGraphics done
00:41:031 OpenGL/GLRenderManager.cpp:174 I[G3D]: ThreadEnd
00:41:057 Core/Config.cpp:1534 I[LOADER]: Config saved (NativeShutdown): '/home/luis/.config/ppsspp/PSP/SYSTEM/ppsspp.ini'
00:41:058 Core/Config.cpp:1547 I[LOADER]: Controller config saved: /home/luis/.config/ppsspp/PSP/SYSTEM/controls.ini
00:41:058 UI/NativeApp.cpp:1511 I[SYSTEM]: NativeShutdown called
Leaving main% 
```
after downgrading to 21.2.5 everything was working again

**Comment by lavilao** [comment] 2021-12-19 18:22
also zink did not work
```
glxgears                                                         ✔ 
libGL error: failed to create dri screen
libGL error: failed to load driver: zink
```

**Comment by LaserEyess** [comment] 2021-12-19 18:24
Well, if vulkan doesn't work zink won't work, obviously. Not exactly sure what the issue is but there are some hints:
```
Info: We compiled against SDL version 2.0.16, but we are linking against SDL version 2.0.18., be aware that this can lead to unexpected behaviors
```
Seems to me like there's some library mismatch. You may need to switch to testing completely. Your other alternative is to compile mesa with that patch applied to 21.2.5, since you know that works.

**Comment by lavilao** [comment] 2021-12-19 18:28
I am pretty sure is not sdl, after all vulkaninfo does not depend on sdl and the same ppssppsdl works fine on 21.2.5 and on 21.3.1. And it's impossible for me to switch to testing after all I am on manjaro, manjaro's testing is arch stable I think.

**Comment by LaserEyess** [comment] 2021-12-19 18:53
That wasn't my point, my point is by installing mesa without updating its dependencies, you may be breaking mesa such that vulkan cannot work. You may have to update **all** of mesa's deps to the testing version. I'm not sure, but the SDL warning is a hint that this *could* be the issue.

**Comment by lavilao** [comment] 2021-12-19 18:58
yeah, you're right, that dog already bite me once with beignet, where the package would install but the library itself would not work, however I can't update all of mesa deps to testing version sorry 🙇

**Comment by jbeich** [comment] 2021-12-19 19:08
> ERROR: [Loader Message] Code 0 : /usr/lib/libvulkan_intel.so: undefined symbol: wl_proxy_marshal_flags

Caused by to https://github.com/wayland-project/wayland/commit/0e0274af0c9f. Make sure `wayland` package is 1.20.0 or later.

**Comment by lavilao** [comment] 2021-12-19 19:12
yep, that is the issue, manjaro only has wayland-1.19.0-2

**Comment by frnmz** [comment] 2021-12-20 23:46
I can confirm the flickers are now solved on mpv with mesa 21.3.2.

But the flickers still happens in Celluloid (with the same config) and Clapper, which both do not have the problem in 21.2.5.

Also `MESA_LOADER_DRIVER_OVERRIDE=zink glxgears` still gives me:
```
87 frames in 5.0 seconds = 17.368 FPS
85 frames in 5.0 seconds = 16.865 FPS
86 frames in 5.0 seconds = 17.152 FPS
```

**Comment by lavilao** [comment] 2021-12-20 23:50
well I guess the mpv issue is solved, the zink issue appears to be other stuff and about clapper and cellulloid... it must have to do with the way they intercept the mpv window and redraw it on their own window, I cant say no more as I use smplayer for gui.

**Comment by haasn** [comment] 2022-09-27 23:36
Seems to be either solved or caused by upstream.

**Closed by haasn** 2022-09-27 23:36 UTC
Labels: os:linux, down-upstream:mesa, vo:gpu-next
