### ISSUE TITLE
On Windows OSC inserts line breaks or skips characters when \n is present in the file path

### ISSUE THREAD

**Issue by alexopus** [mpv-player/mpv#11275] opened 2023-02-06 13:18 UTC
- mpv **0.35.1**
- Windows 10
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/release/mpv-0.35.1-x86_64-v3.7z

### Reproduction steps

Play a file that contains `\n` or `\N` in the file path.

Examples:
file path: `L:\Videos\Music\nyan Cat - Copy.flv`
Shown in the OSC as:
![nyanCat](https://user-images.githubusercontent.com/25933468/216981152-ebc9a47d-c514-47ed-80d9-1db30181587f.png)

file path: `L:\Videos\Music\Nyan Cat.flv`
Shown in the OSC as:
![NyanCat2](https://user-images.githubusercontent.com/25933468/216981141-8a5631fb-e612-4cae-871b-0ddc69c91e2d.png)

### Expected behavior

file name in the OSC interface should show the path as it is, without line breaks or skipping characters, such as:
file path: `L:\Videos\Music\Cat - Copy.flv`
Shown in the OSC as:
![cat](https://user-images.githubusercontent.com/25933468/216981061-b5091a12-77f0-4ad7-98d1-e81cf992bb6b.png)

**Comment by sfan5** [comment] 2023-02-06 13:42
duplicate of #11209

**Closed by sfan5** 2023-02-06 13:42 UTC
Labels: os:win, meta:duplicate
