### ISSUE TITLE
Warnings with macOS 15 (malloc nano zone + IMK-subclasses)

### ISSUE THREAD

**Issue by forthrin** [mpv-player/mpv#14921] opened 2024-09-25 12:15 UTC
### mpv Information

```bash
mpv version: git-2024-09-24-2c5928e
System Version: macOS 15.0 (24A335)
Model Identifier: MacBookAir10,1
```

### Other Information

```text
mpv ... malloc: nano zone abandoned due to inability to reserve vm space.

... Dropped: 52024-09-25 14:08:06.793 mpv... +[IMKClient subclass]: chose IMKClient_Legacy
             ^^^^^
2024-09-25 14:08:06.793 mpv ... +[IMKInputSession subclass]: chose IMKInputSession_Legacy
```

### Reproduction Steps

1. Upgrade to macOS 15
2. Play any video

### Expected Behavior

Absence of warnings

### Actual Behavior

Three different warnings not present with macOS 14.

Not sure if the require attention by mpv, or must just wait for upstream fixes.

See https://duckduckgo.com/?q=malloc%3A+nano+zone+abandoned

Also notice the year overflow in the first timestamp.

### Log File

N/A (No relevant information contained)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by kasper93** [comment] 2024-09-25 12:18
Duplicate of: https://github.com/mpv-player/mpv/issues/14891

**Closed by kasper93** 2024-09-25 12:18 UTC
Labels: os:mac

**Comment by forthrin** [comment] 2024-09-25 12:21
Suspected as much. Didn't find the duplicate when searching.

**Comment by Akemi** [comment] 2024-09-25 15:07
regarding the nano zone warning. this is/was painfully needed see this commit (https://github.com/mpv-player/mpv/commit/9fbe000451140f0e6937db61a7bebc57faa4d69b) for an explanation. if apple changed anything on that part we might need to reinvestigate. though this is something completely out of hand on our side.
