### ISSUE TITLE
Disable macOS native full screen?

### ISSUE THREAD

**Issue by FatherOfAlways** [mpv-player/mpv#4014] opened 2017-01-10 18:28 UTC
Hi. I just updated to version v0.23.0. I have two displays and whenever I enter full screen since the update, mpv seems to use the native macOS full screen feature and dims out my second display. Is there a way to revert back to the old behaviour?

I'm using the latest El Capitan, fwiw. Any help would be much appreciated.

**Comment by Cpuroast** [comment] 2017-01-10 18:37
"System Preferences", "Mission Control", "Displays have separate spaces"

**Comment by Akemi** [comment] 2017-01-10 18:37
yes it uses the native fullscreen. no it shouldn't black out your second display, only if you deactivated "Displays have separate Spaces" in the System Preferences i believe. no atm there is no way to get a non-native fullscreen. since this point was raised before i will add this feature back eventually.

**Comment by FatherOfAlways** [comment] 2017-01-10 18:46
I did indeed disable "Displays have separate spaces". I don't remember the specific reason for doing so. I guess I'll turn it back on for now, but I would indeed appreciate it if you implemented something akin to the way it worked before.

Thank you for your answer.

**Comment by Argon-** [comment] 2017-01-10 19:36
> I did indeed disable "Displays have separate spaces". I don't remember the specific reason for doing so

It's the only way to prevent a menu bar on every screen.

**Comment by Cpuroast** [comment] 2017-01-11 02:27
Is it that big of a problem to have a menu bar on every screen? It dims when you aren't active on the screen.

**Comment by FatherOfAlways** [comment] 2017-01-11 12:05
@Cpuroast 
Right, I remember now. My Mac is pretty old and on one of the previous versions of the OS (Yosemite, I think) the menu bar process had a memory leak bug and it used to screw up my performance pretty badly if I didn't kill it in time. Disabling it on the other screen seemed to have mitigated it somewhat.
I'll turn separate spaces back on once I find the time.

**Comment by Argon-** [comment] 2017-01-11 13:43
> Is it that big of a problem to have a menu bar on every screen? It dims when you aren't active on the screen.

I can't configure my computer the way I want it to?

**Comment by Cpuroast** [comment] 2017-01-11 14:28
Are you going to ask every app developer that uses native full screen, chrome, Firefox, Apple, etc to re-implement non native full screen just because you don't like having the menu bar on all screens.

If not, your only way is Apple's way or the high way, that is for as long as you use a Mac.

On Jan 11, 2017, at 8:43 AM, Julian <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it that big of a problem to have a menu bar on every screen? It dims when you aren't active on the screen.

I can't configure my computer the way I want it to?

-

**Comment by phydano** [comment] 2017-01-20 02:19
> since this point was raised before i will add this feature back eventually

Yes please. I would love to get that feature back.

**Comment by markkuossi** [comment] 2017-02-20 05:25
Hopefully this feature is added back soon, I hate the native fullscreen functionality.

**Comment by WoLpH** [comment] 2017-03-18 15:12
For the time being the old version can be installed through homebrew fairly easy:
```
brew install 'https://raw.githubusercontent.com/Homebrew/homebrew-core/5c1ecfc85e12f4434d603ea0362915838fd21729/Formula/mpv.rb'
```

**Comment by zohozer** [comment] 2017-03-18 19:33
Yes. Please bring back the good old "fake" full-screen mode.

**Comment by wm4** [comment] 2017-03-18 19:42
But Apple doesn't want you to have this. Have you ever considered using Linux?

**Comment by Argon-** [comment] 2017-03-18 20:13
I don't really get this. Native fullscreen is what (nearly) every other application is using on OSX because that's what Apple mandates.
mpv used to work around that for various reasons and now that it is finally able to comply with Apple's guidlines this is supposed to be reversed? Does this also mean you don't want this kind of fullscreen for all other apps on your computer? If so, I encourage you to tell Apple about your disagreement with their design choices.

Don't get me wrong, I'm an OSX user myself and I dislike the native fullscreen as well. But it's really not mpv's fault here for doing what Apple wants them to do.

**Comment by WoLpH** [comment] 2017-03-18 20:29
The apple full screen system is generally considered annoying by power users (at least, that's what I've heard from many) 

I personally disable it anywhere and everywhere I can as the animations cannot be turned off and are pretty slow.

As always Apple cares more about the average user than the power users. Yes it sucks but we can work around it in many cases

**Comment by zohozer** [comment] 2017-03-18 20:36
Yes indeed, the OSX "native" full-screen is so annoying. It is much slower than the "fake" one and only irritates me.

**Comment by tonycpsu** [comment] 2017-03-25 18:04
I don't see anyone saying this is `mpv`'s fault, but none of us would be reading this bug report if Quicktime Player was sufficient for our needs.  When you choose to rely on a third party app, your goal is to gain functionality not provided by the apps packaged with the OS.

In this case, `mpv` had a superior fullscreen feature, and it was removed.  It does look like there were valid reasons for removing it, but that removal has led to a regression in functionality for some of us.  Asking for an option to retain the old fullscreen mechanism, or something resembling it, seems reasonable.  If the devs say no, well, them's the breaks, but it's a reasonable ask, and asking for it isn't assigning blame to the developers -- it's just a request.

**Comment by FatherOfAlways** [comment] 2017-03-25 23:51
I couldn't have said it better myself.

**Comment by WoLpH** [comment] 2017-03-26 00:07
The only thing that really saddens me about this bug report is that someone spent time and effort to implement it only to have people complain now... as a dev, I know how frustrating that can be

I do hope it the feature will not be completely reverted but simply be configurable through a toggle. Perhaps some people actually do like the apple fullscreen system.

**Comment by wm4** [comment] 2017-03-26 10:06
OSX must be th3e only system where people actually complain when an application behaves natively.

Go install Linux.

**Comment by WoLpH** [comment] 2017-03-26 13:03
@wm4 You've obviously never tried Windows 10 ;)
Take this "feature" for example: https://www.google.com/?q=disable lock screen windows 10 anniversary

**Comment by Forcer78** [comment] 2017-04-23 19:36
Adding my voice of support for this issue, since another mpv release has dropped without a fix.

**Comment by ms-89** [comment] 2017-04-23 22:56
...and one more. Wouldn't be so bad without the following bug but still would appreciate an option to disable native fullscreen like iTerm2 does it with it's optional overlay mode.

If you use a mouse instead of a trackpad (while working with an external monitor), it's not that easy to switch spaces. Now mpv is running in fullscreen, I switch back to the Desktop with CMD+Tab and open another video file while mpv is still running. mpv plays the new file and even gets the focus, but I still see the Desktop space and it doesn't switch back automatically. Now I have to press the key f two times to toggle fullscreen off and on so I can see the video again.

This gets really annoying if I wanna check a lot of video files in fullscreen and all the f-toggling and fullscreen-animation is taking longer than I would need to check and open the next video file. Alternatively I could end mpv every time, but this way all temporary settings like fullscreen, videofilters and soundvolume are reset (and the fullscreen-animation is still taking too long).

**Comment by tonycpsu** [comment] 2017-04-23 23:55
I can understand why this issue wouldn't be at the head of the developers' queue, but I do hope they get around to it.  I can't be the only one who's downloading older binary builds of 0.22.0 to make use of the "legacy" fullscreen support.

**Comment by WoLpH** [comment] 2017-04-24 00:07
You're not :)

If anyone prefers a homebrew my workaround still works:
```
brew install 'https://raw.githubusercontent.com/Homebrew/homebrew-core/5c1ecfc85e12f4434d603ea0362915838fd21729/Formula/mpv.rb'
```

**Comment by xanview** [comment] 2017-04-27 14:43
I am also downgrading to get legacy full screen, it have a much faster and more pleasant user experience than the native full screen. Having legacy full screen as a option would be much appreciated :)

**Comment by zohozer** [comment] 2017-04-30 20:48
@Akemi Thank you. I'm happy now. 👍

**Comment by Akemi** [comment] 2017-07-27 19:32
here you go. feel free to test and report bugs on the PR #4676. though i won't fix bugs inherent by the old way doing fullscreen used by the `--no-native-fs` option.

**Closed** 2017-08-06 20:48 UTC
Labels: feature request, osx
