### ISSUE TITLE
Frame drops on high bitrate parts

### ISSUE THREAD

**Issue by kokowang** [mpv-player/mpv#4080] opened 2017-01-28 07:50 UTC
MPV 0.18-0.24

When decoding & playing back h264 video, on both hardware decoder (VideoToolBox) and on Software decoder, MPV will drop frames on my MBP2015 when bitrate exceeds a few hundred mb/s. 
Would it be possible to implement a buffer in ram to stop this from happening? (I'm pretty sure the lag comes from not being able to read from storage fast enough). Does OpenGL support large buffers?
Here is a test video:
http://www.filedropper.com/sample_38
The average bitrate is only about 40mb/s, although sections of it exceeds several hundred (possibly over 1000) mb/s - I didn't check exact figures yet. You should see that MPV drops frames during white noise. On windows, I use a 60 frame buffer on my renderer in MPC and it plays this fine with no lag, even on a slower HDD.

**Comment by wm4** [comment] 2017-01-28 12:15
Try opengl-pbo.

**Comment by kokowang** [comment] 2017-01-28 16:59
[vo] Video output opengl-pbo not found!
Error opening/initializing the selected video_out (-vo) device.
Is there a specific flag I need to set when building?

**Comment by wm4** [comment] 2017-01-28 17:52
It's an option.

**Comment by struq** [comment] 2017-01-31 01:20
I think I might have encountered the same problem. With this test video I constantly get 118 dropped frames after the playback. 

I found this when I was testing mpv with a 4k 60fps video at http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_native_60fps_normal.mp4 . mpv is dropping frames throughout the playback and the video stutters painfully. But the cpu usage is only around 10%.

opengl-pbo does not help. However, --video-sync=display-resample mentioned in #2392  solves this, although it happens in either fullscreen or windowed mode here. 

software: mpv 0.23.0, macOS 10.12.3
hardware: 2.9 GHz Intel Core i5, 8 GB 1867 MHz DDR3 RAM, Intel Iris Graphics 6100 1536 MB

**Comment by Cpuroast** [comment] 2017-02-04 04:02
yeah as wm4 mentioned, it's not a vo.
it was a opengl vo sub-option in the past, but since all sub-options were converted into global options it's now simply:

opengl-pbo=yes

**Comment by Akemi** [comment] 2017-02-04 14:33
it could also be related to `opengl-early-flush` from issue #3837 and #3739. try setting `--opengl-early-flush=no`.

**Comment by Akemi** [comment] 2017-02-04 14:49
i tested all the sample files in this issue and #3739 and all drop frames like crazy if not used with `--opengl-early-flush=no` or `--video-sync=display-resample`. if either is used those videos play smooth, especially good to test on the pan at the beginning of BBB.

**Comment by Argon-** [comment] 2017-02-04 16:42
I have a range of mostly PAL TV recordigs (50 FPS, deinterlaced by the recording software) that exhibit the same phenomenon. They are absolutely unwatchable with mpv no matter the configuration. Except early-flush=no that makes these files play back nicely. As I have a few such files and never noticed a drawback I put this option in my config some time ago and had no such problem ever again.

**Comment by Akemi** [comment] 2017-02-05 16:28
i will treat this as a duplicate of #3739 for now if nothing is added to this issue.

**Closed by Akemi** 2017-02-05 16:28 UTC
