### ISSUE TITLE
Poor caching / big lag while watching online videos with MPV on Windows 8.1

### ISSUE THREAD

**Issue by startas** [mpv-player/mpv#6058] opened 2018-08-07 08:43 UTC
### mpv version and platform
MPV v0.29.0, newest youtube-dl, windows 8.1 x64, followed "Windows builds by lachs0r" instructions on mpv site.
PC - ryzen 2700x, gtx 1080, 300 mbps lan internet connection.

### Reproduction steps
Open cmd
Enter command "mpv twitch_live_stream_url"
or "mpv twitch_clip_url"
or "mpv youtube_url"

### Expected behavior
Stream/videos play nice and smooth, without any lag.

### Actual behavior
Stream/videos play for a few seconds, then stops caching and stops playing,
then after 5-20 seconds starts playing again for a few seconds,
then stops, and so on.

### Log file
http://s000.tinyupload.com/?file_id=53001762993824433211

### Sample files
Any youtube video or twitch stream/clip. Will provide examples later if really needed.
Log file was created by playing twitch stream https://www.twitch.tv/synderen

### Notes
MPV works just fine on linux (manjaro distro), no issues at all.
Also, the same videos play in firefox 61 browser just fine without any issues, both on windows and linux.
I noticed strange caching behaviour - MPV receives a few seconds of video, plays it, then pauses for some time until it receives a few seconds of video, then plays it again, it never gets constant stream of data.

**Comment by CounterPillow** [comment] 2018-08-08 04:44
@dnmTX BSOD are not mpv's fault as they are inherently operating system kernel crashes, I don't know why you're even posting in this unrelated issue.

**Comment by lachs0r** [comment] 2018-08-08 08:18
You should report this issue to your graphics driver vendor. mpv has nothing to do with these system crashes other than triggering driver bugs by coincidence, and it’s impossible to fix on our end. Especially with no means to reproduce this issue.

**Comment by aufkrawall** [comment] 2018-08-11 16:49
Do you have network tampering software like cFosSpeed installed? It caused issues for me with mpv and network streams.

**Comment by startas** [comment] 2018-08-12 15:29
No, i dont have any network tampering programs.

**Comment by dnmTX** [comment] 2018-08-12 22:46
I tracked down my issue to `--video-sync=display-resample` . Without it player is working just fine.Makes me wonder did i ever needed this and yet it's very much recommended using it in Reference Manual.
@CounterPillow @lachs0r  **"BIG THANK YOU"** for the **"PROVIDED HELP"**,you two are **"GREAT"** !!!

**Comment by lachs0r** [comment] 2018-08-13 00:41
That’s pure coincidence but whatever.

**Comment by garoto** [comment] 2018-08-13 16:36
Start investigating your ISP routes to the mentioned streaming services IP addresses resolved thru your configured DNS servers.

**Comment by startas** [comment] 2018-08-16 06:45
As i said, the internet is fine, all the browsers can play all the videos without any caching issues, also on linux mpv works good too, **the only issue is mpv + windows**.

**Comment by aufkrawall** [comment] 2018-08-16 15:38
It apparently works fine for most users.

**Comment by garoto** [comment] 2018-08-16 19:10
@startas: try the latest avaiable shinchiro build (https://sf.net/projects/mpv-player-windows/). There's indeed something funky going on with latests lach0r's builds regarding hls(?) streams:

https://0x0.st/sJQs.png

Not sure if potentially related with the all the `schannel` bugs cropping up for some time now.

**Comment by startas** [comment] 2018-08-18 07:05
Thanks, this version works ok. But still, it is caching a bit slow - playing 4k video from youtube, firefox never runs out of cache, while mpv already starts choking after ~30-60 seconds. It is always caching new data, but the download speed is a bit low, and i have to pause the video and wait for a minute to get more cache. Are there any command switches that could impact download speed ?

**Comment by aufkrawall** [comment] 2018-08-18 09:26
There is a ticket for the YT 4k problem, it's because Google limiting single connection speed since January.
Limiting max resolution to WQHD in youtube-dl is probably the only way to deal with it.

**Comment by wm4** [comment] 2019-10-25 11:29
Hm, I can close this, right?

**Closed by wm4** 2019-10-25 11:29 UTC
Labels: core, core:stream, scripting:ytdl-hook
