### ISSUE TITLE
BT.1886 slightly brighter and more banding with ICC profile vs. pre-generated 3D LUT

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#10442] opened 2022-07-23 22:34 UTC
mpv 0.34.0-378-g8ef744d1b7
recent libplacebo git-master

mpv config:

```
vo=gpu-next
gpu-api=vulkan

dither-depth=8

#icc-profile=profile.icm
#vf=format:gamma=bt.1886

image-lut=bt1886.cube

keep-open=yes
```

With mpv's own generated 3D LUT, especially dark shades are slightly brighter and show a bit more banding vs. BT.1886 3D LUT generated by DisplayCal.

mpv ICC:
![icc](https://user-images.githubusercontent.com/13510490/180624951-22d4ac37-9986-4968-afdf-71b7d32a149a.png)

DisplayCal 3D LUT:
![3dlut](https://user-images.githubusercontent.com/13510490/180624956-4309c295-fdd8-4d15-82db-b88a25484963.png)

Test image:
![orange](https://user-images.githubusercontent.com/13510490/180624967-a6850c08-4dd4-401f-9a03-f21bc2b7b62d.png)

Log:
[output.txt](https://github.com/mpv-player/mpv/files/9174771/output.txt)

My display's ICC profile and 3D LUT generated by DisplayCal (with latest stable version on Windows):
[icc3dlut.zip](https://github.com/mpv-player/mpv/files/9174773/icc3dlut.zip)

**Comment by haasn** [comment] 2022-07-23 23:02
The amount of banding in your screenshots seems roughly equal to me. But I do see that the mpv result is just a tiny bit brighter.

Can you test on a black clipping sample? (e.g. one with labelled steps from 0 to 16)

**Comment by aufkrawall** [comment] 2022-07-24 00:31
I was testing that, then I noticed this: With ICC correction applied, mpv elevates black. This also happens with `vf=format:gamma=gamma2.4`.

Black with ICC profile (same as the one linked above) correction in mpv:
![icc2 4](https://user-images.githubusercontent.com/13510490/180627204-9e521ea6-79b7-4ee5-8b70-92307cdce55e.png)

BT.1886 3D LUT by DisplayCal:
![3dlut](https://user-images.githubusercontent.com/13510490/180627208-1bf61257-d651-45da-bde0-8b274bc470d7.png)

"Source" (1 color black):
![black](https://user-images.githubusercontent.com/13510490/180627224-6505939a-7ef0-4685-8c14-49669350f34e.png)

I think that ICC profile should be fine and shouldn't make mpv assume elevated black level.

**Comment by aufkrawall** [comment] 2022-07-25 00:31
Can also confirm the issue on Windows with `--gpu-api=d3d11` and `--vo=gpu`. Can also confirm that mpv elevates black with an ICC profile in 3x curves format without included VCGT data, though then blacks are elevated a bit less. Also happens without any dithering.

**Comment by aufkrawall** [comment] 2022-07-29 22:44
This issue occurs (even more distinctively?) also with a sample video that represents normal video (i.e. rec709 bt1886 content):
[2022-07-30 00-27-21.zip](https://github.com/mpv-player/mpv/files/9223692/2022-07-30.00-27-21.zip)

Just press s (or capture screen) one time with and one time without ICC profile correction enabled in mpv. With it enabled, clearly black gets elevated when comparing the screenshots. Is also the case with `--vo=gpu` and `--icc-force-contrast=inf`.

Could you please take a look before next stable build is declared @haasn ? It looks to me like mpv ICC correction undesirably raises blacks and thus reduces contrast with an ICC profile. From what I can tell, it looks to be generic and shouldn't be limited to only my ICC profile, and apparently happens with any gamma setting/target.

**Comment by aufkrawall** [comment] 2022-07-29 23:26
Thanks, that's reassuring to know. I really wonder why I didn't notice this earlier. Perhaps because 100% black isn't a too common encounter in the wild?
Anyway, don't let me nag you. I'll gladly wait. :)

**Comment by haasn** [comment] 2022-08-04 11:43
> I really wonder why I didn't notice this earlier.

On my ICC profile the black raises from `(0,0,0)` to `(1,1,1)` after passing through the LUT. On your ICC profile, it gets raised to `(5,5,5)`.

**Comment by haasn** [comment] 2022-08-04 12:02
Logs from my ICC profile:
```
detected ICC black point: XYZ 0.000824 0.000854 0.0007050
detected ICC white point: XYZ 0.000000 89.975449 0.0000000
detected ICC black point: XYZ 0.000824 0.000854 0.000705
detected ICC contrast: 203.000000 : 0.173462 = 1170.285767 : 1
detected ICC gamma: 2.153214
transforming gray(0) -> 0 0 0
transforming gray(1) -> 0 0 0
transforming gray(2) -> 0 0 0
transforming gray(3) -> 0 0 0
transforming gray(4) -> 0 0 0
transforming gray(5) -> 0 0 0
transforming gray(6) -> 0 0 0
transforming gray(7) -> 0 0 0
transforming gray(8) -> 0 0 0
transforming gray(9) -> 10 11 9
transforming gray(10) -> 136 137 119
transforming gray(11) -> 409 409 348
transforming gray(12) -> 768 767 649
transforming gray(13) -> 1144 1143 972
```

Logs from yours:
```
detected ICC white point: XYZ 0.000000 94.100555 0.0000000
detected ICC black point: XYZ 0.000883 0.000916 0.000755
detected ICC contrast: 203.000000 : 0.185852 = 1092.266724 : 1
detected ICC gamma: 2.355127
transforming gray(0) -> 0 0 0
transforming gray(1) -> 0 0 0
transforming gray(2) -> 0 0 0
transforming gray(3) -> 0 0 0
transforming gray(4) -> 0 0 0
transforming gray(5) -> 0 0 0
transforming gray(6) -> 0 0 0
transforming gray(7) -> 0 0 0
transforming gray(8) -> 0 0 0
transforming gray(9) -> 0 0 0
transforming gray(10) -> 0 0 0
transforming gray(11) -> 0 0 0
transforming gray(12) -> 253 49 24
transforming gray(13) -> 694 1175 289
transforming gray(14) -> 1716 1507 1186
transforming gray(15) -> 2480 2478 2328
transforming gray(16) -> 3083 3056 2943
```

Tone mapping is based on the detected min luma value, i.e. 0.185852. This then gets normalized to `0.0009155270` and passed through the detected ICC gamma function of 1/2.355127, giving us `0.0512753` being indexed from the 3DLUT, corresponding to an index of roughly 13.07.

We can see that, somehow, this is too high. It's possible that the issue lies in a faulty black point detection logic.

**Comment by haasn** [comment] 2022-08-04 12:05
Indeed, if I manually override the black point by a value corresponding more closely to an index of 12 (which is where the true black point approximately lies, according to this 3DLUT), the black boost disappears.

So in conclusion, it appears that `cmsDetectDestinationBlackPoint` is not correctly estimating the black point of the ICC profile, and we probably want to write custom logic to do this instead (as we already do for the gamma detection).

**Comment by aufkrawall** [comment] 2022-08-04 12:09
Thanks for looking into this!

Is my layman guess correct that 100% black shouldn't be elevated at all, but only near-blacks with BT.1886? It seems to be what the BT.1886 3D LUT generated by DisplayCal does. I suppose this generally should also apply to results of HDR -> SDR conversion?

**Comment by haasn** [comment] 2022-08-05 10:58
> Is my layman guess correct that 100% black shouldn't be elevated at all

Yeah, fundamentally all tone curves are designed to map black to black after all.

**Comment by aufkrawall** [comment] 2022-08-05 17:46
Well, since this is the point of BT.1886 (and I think also SDR -> HDR tonemapping of mpv works similarly?), this makes sense to me if black still looks as black as the display can do. :)
On the other hand, when using something like `--vf=format:gamma=gamma2.4`, I'd expect the result to be clipped below the display's black point (e.g. when content has weirdly bad contrast with BT.1886).

**Comment by haasn** [comment] 2022-08-07 10:29
Hmm. I tried various other approaches but I'm always hitting the bottleneck that LittleCMS does not seem to support black point compensation with relative colorimetric intent at all. I might end up needing to split up the input encoding per-channel, the way we used to do it in mpv iirc.

**Comment by haasn** [comment] 2022-08-08 11:07
The author of Little-CMS [thinks your ICC profile is wrong](https://github.com/mm2/Little-CMS/issues/328#issuecomment-1207492591), which is why you're getting such bad results.

I'm not sure what to do with this information. I'm still waiting on his feedback before deciding how to change our pipeline. But in the meantime, you might wanna use `--icc-intent=0` to work around it.

**Comment by OrangeColaJuice** [comment] 2022-08-08 11:10
Sorry for interjecting but how does one get that log output for ICC information/generation of cube?

**Comment by aufkrawall** [comment] 2022-08-08 13:14
Thanks again for your efforts, haasn!

This sounds like bad news to me, as my profiles are created via the GUI of DisplayCal with common i1 DisplayPro with recommended spectral correction for most wide gamut monitors (LCD PFS Phosphor WLED) without  doing anything special. So probably lots of profiles out there would trigger this (to a different extent?). A bug in DisplayCal?

I can confirm that `--icc-intent=0` works. I've btw. checked color values of pixels in the screenshots, they are 100% black with `--icc-intent=0`.

**Comment by haasn** [comment] 2022-08-10 17:52
@aufkrawall something I noticed in my own testing is that enabling `--debanding` raises the black point in a strange and noticeable way - an encoded value of `16` (i.e. reference black) becomes a value slightly *above* black, while encoded values of `15` (or below) become true black.

I'll try investigating this further, but it's possible that you should disable debanding when testing for the time being.

In any case, I've pushed a branch here: https://code.videolan.org/videolan/libplacebo/-/merge_requests/272

You can give it a try and see what you think. This won't solve your issue out of the box (I suspect your profile is broken, cf. the linked Little-CMS discussion), but will make `--icc-intent=0` work correctly.

**Comment by aufkrawall** [comment] 2022-08-10 20:33
I've tested with this MR and both deband and dithering disabled, dark scenes are still a bit brighter with BT.1886 via mpv/libplacebo ICC correction than with 3D LUT generated by DisplayCal (same as above).

**Comment by haasn** [comment] 2022-08-11 11:03
@aufkrawall based on your OP settings, I believe you are applying the 3DLUT incorrectly.

A correct application would be `--lut=bt1886nocal.cube --lut-type=conversion`. This instructs mpv to use this LUT (instead of the ICC profile) for source->target gamut conversion. When I do this, I get identical results when using `--icc-intent=0`.

**Comment by aufkrawall** [comment] 2022-08-11 14:03
I comment out `icc-profile` when applying the 3D LUT. `lut-type=conversion` doesn't seem to make a difference with at least regard to bare eyes impression.
But I created the 3D LUT with DisplayCal's default intent, which is absolute colorimetric with white point scaling. So I tried with a 3D LUT generated with perceptual intent, but then for whatever weird reasons it seems BT.1886 was behaving like if there was no black point information available. I wonder if that all comes down to the same issue the little-cms dev thinks to be an issue of the ICC profile (and in return of DisplayCal?).

**Comment by haasn** [comment] 2022-08-11 14:19
In your OP settings you are using `--image-lut` instead of `--lut`, too.

**Comment by aufkrawall** [comment] 2022-08-11 14:38
The last two screenshots are from an actual video file. :) I think basically any very dark scene will do the trick, but I can also provide a few seconds split-off featuring that exact scene as a sample.

If I had to make a vague guess, I'd say it looks to me like that mpv's ICC BT.1886 perceptual intent treats the display's black point as slightly higher (thus boosts gamma more) than DisplayCal's BT.1886 3D LUT with absolute colorimetric intent.

**Comment by aufkrawall** [comment] 2022-08-16 23:18
libplacebo-git-4.208.0.76.g1d3ff4d-1
mpv 813164cc07124aabfbc4aa3b8f9fe33fe222c77c

```
vo=gpu-next
gpu-api=vulkan

icc-profile="G27q-20 #1 2022-05-25 22-12 D6500 2.4 M-S XYZLUT+MTX.icm"
icc-intent=0

#lut=bt1886nocal.cube
#lut-type=conversion

keep-open=yes
screenshot-format=png
```
![icc](https://user-images.githubusercontent.com/13510490/185000199-373ef0c8-570a-4501-ae75-bf001d7ca88a.png)


```
vo=gpu-next
gpu-api=vulkan

#icc-profile="G27q-20 #1 2022-05-25 22-12 D6500 2.4 M-S XYZLUT+MTX.icm"
#icc-intent=0

lut=bt1886nocal.cube
lut-type=conversion

keep-open=yes
screenshot-format=png
```
![3dlut](https://user-images.githubusercontent.com/13510490/185000298-e883eba9-2857-4278-9405-ae31fd0efed5.png)

I think configs should be correct that way and, as you can see, BT.1886 result with mpv's own generated 3D LUT from the ICC pofile is indeed a bit brigther than with DisplayCal's pre-generated 3D LUT from the same ICC profile:
![Screenshot_20220817_010915](https://user-images.githubusercontent.com/13510490/185000523-dadcad34-1d19-4551-9809-53748e8eb67b.png)
(same ICC profile and 3D LUT as used in my previous posts)

Sample video (I just used the last frame with `keep-open=yes`):
[sample.zip](https://github.com/mpv-player/mpv/files/9355188/sample.zip)

**Comment by haasn** [comment] 2022-08-16 23:26
Random thought: mpv assumes untagged BT.1886 sources have a contrast of `1000:1` by default. So we actually do tone-mapping of the black point. Might be related, but might be not.

Looking closely at the screenshots though it almost seems as though the black point is shifting color? I'll have to do more in-depth analysis again but it's possible that the black point compensation still isn't working as intended with this profile.

**Comment by Hrxn** [comment] 2022-08-17 10:26
BTW, DisplayCAL 3.9.6, is that some kind of beta version?

**Comment by aufkrawall** [comment] 2022-08-17 13:53
It's the fork with modernized Python used on Arch, original DisplayCal upstream seems to be abandonware these days.
But it doesn't matter, as I used original Windows version 3.8.9.3 both for calibration and generating 3D LUT.

**Comment by aufkrawall** [comment] 2022-08-17 15:51
@haasn Maybe it's interesting that DisplayCal's XYZ LUT profile type seems to contain something that looks like some kind of obligatory black point compensation, even though the checkbox is unticked?
XYZ:
![xyz](https://user-images.githubusercontent.com/13510490/185182183-5e38d535-0994-4688-95dd-e030cf05f361.png)

Curves:
![3xcurves](https://user-images.githubusercontent.com/13510490/185182204-f37eb139-d693-42c1-b323-8444c8ce65b1.png)


Developer of novideo_srgb mentioned this when some issues occurred, no idea if it perhaps can be helpful:
https://github.com/ledoge/novideo_srgb

I'm also not getting a noticeable brightness increase with mpv ICC vs. DisplayCal pre-generated 3D LUT with a profile that's 3x curves profile with black point compensation checkbox unticked (it's darker than the other screenshots as it doesn't contain a VCGT; my XYZ matrix profile contains a VCGT that sets display gamma to 2.4 instead of its native 2.2):
![Screenshot_20220817_173322](https://user-images.githubusercontent.com/13510490/185182786-11df2f16-a180-4ed9-91ee-e80dbf3a8f12.png)

![Screenshot_20220817_173429](https://user-images.githubusercontent.com/13510490/185182799-e1e5dd34-616f-4236-a06f-7c64585f866e.png)

With that profile, it also doesn't seem to make a difference if `--icc-intent=0` is set or not. But black isn't 100% black, but instead slightly (1/255?) above black (not noticeable with my relatively poor IPS black level though).

No idea if the missing luminance and black point data in DisplayCal's overview for the 3x curves profile with no VCGT is just some header data or if this has more relevance.

The 3x curves ICC profile without VCGT:
[G27q-20 #1 2022-05-25 16-04 D6500 S 3xCurve+MTX.zip](https://github.com/mpv-player/mpv/files/9364344/G27q-20.1.2022-05-25.16-04.D6500.S.3xCurve%2BMTX.zip)

**Comment by OrangeColaJuice** [comment] 2022-08-18 18:30
>Maybe it's interesting that DisplayCal's XYZ LUT profile type seems to contain something that looks like some kind of obligatory black point compensation
The default is to create colorimetric and perceptual tables.
I think perceptual is equal to relative color + black point compensation. If you manually check BPC on perceptual it does pretty much nothing.

Also for the other guy, DisplayCal official build should be enough, it's pretty much a GUI for Argyll CMS.

**Comment by aufkrawall** [comment] 2022-08-19 13:44
Re-ran calibration with gamma 2.4 VCGT in curves format, and indeed the brightness difference between mpv ICC and DisplayCal 3D LUT is still there.

**Comment by haasn** [comment] 2022-08-26 18:20
@aufkrawall I pushed https://code.videolan.org/videolan/libplacebo/-/merge_requests/281 which adds (optional, disabled by default) code to libplacebo to forcibly fix the black point by making the lower part of the ICC 3DLUT into a linear ramp.

This would fix your issue by brute force. Although in my own testing, I still didn't need it at all for your profile when using `--icc-intent=0`, since that already maps black to black. But give it a try.

You'll need to enable the feature manually to test it:
```diff
diff --git a/video/out/vo_gpu_next.c b/video/out/vo_gpu_next.c
index 8b2d783727..84d3684ecb 100644
--- a/video/out/vo_gpu_next.c
+++ b/video/out/vo_gpu_next.c
@@ -1532,6 +1532,7 @@ static void update_icc_opts(struct priv *p, const struct mp_icc_opts *opts)
     p->icc.size_r = s_r;
     p->icc.size_g = s_g;
     p->icc.size_b = s_b;
+    p->icc.force_bpc = true;
 
     if (!opts->profile || !opts->profile[0]) {
         // No profile enabled, un-load any existing profiles
```

**Comment by aufkrawall** [comment] 2022-08-27 02:11
With these patches applied to libplacebo and mpv

Both `--icc-intent=1`

![iccintent1](https://user-images.githubusercontent.com/13510490/187010108-8e264432-3d2c-4df6-a5c1-0e0926a8d8d2.png)

and `--icc-intent=3`
![iccintent3](https://user-images.githubusercontent.com/13510490/187010125-d27a806c-33b3-4cc3-8ddf-2cb65cbc5396.png)

get way darker than DisplayCal BT.1886 3D LUT (absolute colorimetric):
![3dcal](https://user-images.githubusercontent.com/13510490/187010161-11be71d6-94cc-4761-89de-7392a46d4213.png)

`--icc-intent=0` seems to be unchanged, i.e. slightly brighter than DisplayCal 3D LUT:
![iccintent0](https://user-images.githubusercontent.com/13510490/187010189-bf4c99ad-30f4-4939-aa47-f9442b7bf551.png)

**Comment by aufkrawall** [comment] 2022-08-28 00:00
As for 100% black: It is indeed now not elevated anymore, also not without `--icc-intent=0` (and can also confirm deband black elevation of `--vo=gpu-next` is fixed too by the other recent libplacebo commits).

So only the slight brightness difference between DisplayCal 3D LUT and mpv ICC remains.

**Comment by haasn** [comment] 2022-08-30 11:38
> So only the slight brightness difference between DisplayCal 3D LUT and mpv ICC remains.

That one might be taken care of by [libplacebo!284](https://code.videolan.org/videolan/libplacebo/-/merge_requests/284)?

So do you think we should merge [libplacebo!281](https://code.videolan.org/videolan/libplacebo/-/merge_requests/281)?

**Comment by aufkrawall** [comment] 2022-08-30 13:39
If libplacebo!281 doesn't have any bad side effects, I think it should be merged. As I think otherwise, there will elevated black for lots of users without transparent reason. I can't judge whether the ICC profile generated by DisplayCal is actually "bugged", but it's what most users use for calibration, and ideally things should just work as intended ootb. Hopefully this would also take care of some previous reports with ICC calibration in mpv, I suppose that's quite likely.

As for libplacebo!284 , I can't apply it after !281. :)

**Comment by haasn** [comment] 2022-08-30 15:40
@aufkrawall I was actually contemplating switching to perceptual intent by default.

**Comment by aufkrawall** [comment] 2022-08-30 20:20
Re-tested with libplacebo 0ce3fa4f28f41b20928476e6d7e09f5e611e7005 + MR 281 + mpv patch:

Solid black is not elevated with any `--icc-intent`.

A dark scene still shows differences vs. DisplayCal 3D LUT:

DisplayCal:
![3dlutdc](https://user-images.githubusercontent.com/13510490/187534456-697056df-d812-49ea-8e88-eeef07762389.png)

`--icc-intent=0` is still slightly brighter:
![0](https://user-images.githubusercontent.com/13510490/187534599-eea27488-7d9d-4e45-ad8e-1515b569369e.png)

`--icc-intent=1` is way darker:
![1](https://user-images.githubusercontent.com/13510490/187534681-80510001-3a25-4e05-a5d3-e8408f761297.png)

`--icc-intent=2` has similar brightness as `1`, but looks more saturated:
![2](https://user-images.githubusercontent.com/13510490/187534926-817ceb83-78d8-4d98-8dfc-921db5f6ca4b.png)

`--icc-intent=3` is once again way darker than DisplayCal 3D LUT:
![3](https://user-images.githubusercontent.com/13510490/187535068-5a619c71-e0f9-4708-8444-e361725acb97.png)

**Comment by aufkrawall** [comment] 2022-09-22 01:34
@haasn I wonder what your thoughts are about the forcibly linear ramp for the lower part of the ICC 3DLUT, like you described in [#issuecomment-1228788748](https://github.com/mpv-player/mpv/issues/10442#issuecomment-1228788748) ? Would only make sense behind an option, or not suitable at all? (Too late for mpv 0.35?)

**Comment by aufkrawall** [comment] 2022-10-01 02:35
> @aufkrawall I was actually contemplating switching to perceptual intent by default.

With `--icc-intent=0`, HDR gets much darker vs. current default intent setting (still same ICC profile as linked in the first post):
![Screenshot_20221001_043140](https://user-images.githubusercontent.com/13510490/193379728-e139ed5d-7b7c-4648-b77b-a2b0d20417fd.png)
![Screenshot_20221001_043121](https://user-images.githubusercontent.com/13510490/193379729-93d32bb1-a7a5-46ad-995b-226050754f1a.png)

This is with latest mpv and libplacebo git-master without any patches/MRs on top. Used with
```
tone-mapping=spline
tone-mapping-param=1.0
hdr-compute-peak=no
```

**Comment by haasn** [comment] 2022-10-10 06:28
@aufkrawall is that still happening with https://code.videolan.org/videolan/libplacebo/-/merge_requests/296 ?

**Comment by aufkrawall** [comment] 2022-10-10 13:49
Yes, mpv BT.1886 SDR is still a bit brighter than DisplayCal's absolute colorimetric with white point scaling 3D LUT with both `--icc-intent=0` and `1`, while HDR -> SDR still gets way darker with `0` vs. `1`.

**Comment by aufkrawall** [comment] 2022-10-10 14:14
With regard to pure black SDR: It is still elevated, i.e. visibly too bright without `--icc-intent=0`.

**Comment by haasn** [comment] 2022-10-13 05:58
I did end up deciding to merge the upstream `force_bpc` patch, if only because I literally can't think of a better work-around here at the time.

I'll close this issue when the option is exposed in mpv. (Should we default it on or off?)

**Comment by aufkrawall** [comment] 2022-10-13 06:30
Could you re-base the mpv patch in https://github.com/mpv-player/mpv/issues/10442#issuecomment-1228788748 ? It doesn't apply anymore.

I can't recall how the patch behaves with the default `--icc-intent=1`. If the result with the patch and `--icc-intent=1` achieves proper black level without making HDR video way darker (like `--icc-intent=0`does without the patch), I think it would be the best solution (and imho a good default).

For what it's worth, who knows if the 3D LUT generated by Display Cal actually is correct? When the tool dwm_lut still worked with recent Windows versions at that time, I tested some 3D LUTs generated by DisplayCal with its verification feature, and gamma curve deviation was not perfect.

What I can say thoguh is that the gamma correction done by novideo_srgb seems to be very good (and VCGT surprisingly bad), according to verification in DisplayCal: https://github.com/ledoge/novideo_srgb/issues/18#issuecomment-1265931793

Too bad we can't just simply feed it mpv's calibration for verification (or can we?).

**Comment by haasn** [comment] 2022-10-13 06:39
> Could you re-base the mpv patch in [#10442 (comment)](https://github.com/mpv-player/mpv/issues/10442#issuecomment-1228788748) ? It doesn't apply anymore.

```
diff --git a/video/out/vo_gpu_next.c b/video/out/vo_gpu_next.c
index 22950e0b6e..75c2561b6e 100644
--- a/video/out/vo_gpu_next.c
+++ b/video/out/vo_gpu_next.c
@@ -1628,6 +1628,9 @@ static void update_icc_opts(struct priv *p, const struct mp_icc_opts *opts)
     p->icc.cache_save = icc_save;
     p->icc.cache_load = icc_load;
 #endif
+#if PL_API_VER >= 288
+    p->icc.force_bpc = true;
+#endif
 
     if (!opts->profile || !opts->profile[0]) {
         // No profile enabled, un-load any existing profiles
```

**Comment by aufkrawall** [comment] 2022-10-13 06:57
Weird. Unlike previously https://github.com/mpv-player/mpv/issues/10442#issuecomment-1229341616 , now black is still elevated with that patch without `--icc-intent=0`.

**Comment by haasn** [comment] 2022-10-13 07:47
Oh, there is also a bug in libplacebo if you're using the icc cache dir option. I'll fix that as well.

**Comment by aufkrawall** [comment] 2022-10-13 07:59
Thanks!
No more elevated blacks with `--icc-intent=1` and HDR looks still has proper brightness too vs. `--icc-intent=0`. :)
So my 2 cents would be that this is the best deal when using ICC profiles created by DisplayCal/ArgyllCMS.

**Comment by haasn** [comment] 2022-10-14 04:51
I will also point out that my "well-calibrated" ICC profile does not visibly get altered by the patch because it's *already* a near-perfect pure power curve, so the patch (which basically forces the 3DLUT to be a perfect pure power curve near the black point) does nothing.

**Comment by aufkrawall** [comment] 2022-11-03 22:19
In the (loose) context of testing stuff with new Windows 11 color management APIs (ACM), I've re-calibrated with Curves + matrix ICC profile format and the brightness difference between DisplayCal BT.1886 absolute colorimetric with white point scaling + mpv ICC (default intent) has vanished. Ooph? I suppose this is related to some of the previous ICC management changes in libplacebo + the curves format instead of XYZ LUT + matrix (that apparently has inherent black point compensation force-enabled)?

Used DisplayCal settings:
![1](https://user-images.githubusercontent.com/13510490/199844932-5140ffff-0a31-40c9-95f5-73ce3633a742.png)
![2](https://user-images.githubusercontent.com/13510490/199844935-facaa831-8339-454b-b339-b55f420e8765.png)
![3](https://user-images.githubusercontent.com/13510490/199844937-b128dd7a-3725-494a-82ee-9fae66d8cb93.png)
![4](https://user-images.githubusercontent.com/13510490/199844938-d926a183-cc97-43e6-9488-3d82c8303ad0.png)





I'll try with my notebook display too.

**Comment by aufkrawall** [comment] 2022-11-04 16:28
Also works with the notebook display when using the above settings (raised black point with default icc-intent=1 naturally is also fixed with such profiles for both displays). 

Though I guess some users would still find that forced linear black point approximation option useful, e.g. when they don't have a colorimeter and only have access to a non-optimal XYZ LUT ICC profile. Perhaps also a note in the mpv manual could mention that curves + matrix format (black point compensation checkbox unticked) and perhaps also increased grayscale patches for profiling step (and calibrating to BT.1886?) should be ideal for mpv when creating a profile with DisplayCal.

I'll leave this open, feel free to close when you decide what to do with the aforementioned troublesome profiles.

**Comment by haasn** [comment] 2022-11-04 16:41
Upsteam has decided to close the bug with the claim that the profiles are broken. If it works for you after an update, it might really just have been a broken profile?

**Comment by aufkrawall** [comment] 2022-11-04 16:54
I don't think the profile was broken as in "a bug got fixed", since I haven't updated DisyplayCal/ArgyllCMS since then. But there is that forced black point compensation with XYZ LUT profiles, as described in https://github.com/mpv-player/mpv/issues/10442#issuecomment-1218203648 . And you made some changes to libplacebo's ICC profile handling since then, which might explain why curves + matrix format didn't yield perfect results for me in mpv at that time either, but apparently does now. Though this is speculative, I'd need to run some annoying extra calibrations and tests to be 100% sure.

Anyway, now it's perfect for me with recent libplacebo/mpv without any extra patching and the DisplayCal settings shown in the latest screenshots. And I guess this can make me sleep well enough. :)

I guess XYZ LUT profile format in DisplayCal should just be avoided at all costs, unless you only use 3D LUTs created directly by DisplayCal. Gamma/black point weirdness isn't worth the better handling of non-linearities that format offers, imho. Who knows for how many people it ruins results without them noticing in all kinds of color managed programs...

**Comment by haasn** [comment] 2022-11-04 17:01
It's worth pointing out that I use an XYZLUT+MTX profile and it works perfectly for me.

But anyway, I guess I'll close this for the time being unless somebody else notices issues 🤷🏻

**Closed by haasn** 2022-11-04 17:01 UTC

**Comment by aufkrawall** [comment] 2023-05-31 06:33
@haasn With recent libplacebo & mpv git-master, `icc-intent=0` doesn't work anymore to prevent black elevation with "faulty" profiles like this:
[LC133LF4L01 #1 2022-11-24 16-29 D6500 Rec. 1886 S 3xCurve+MTX.zip](https://github.com/mpv-player/mpv/files/11609440/LC133LF4L01.1.2022-11-24.16-29.D6500.Rec.1886.S.3xCurve%2BMTX.zip)
