### ISSUE TITLE
MPV not working with Ubuntu Core on Raspberry Pi

### ISSUE THREAD

**Issue by flrkli** [mpv-player/mpv#5988] opened 2018-07-14 12:02 UTC
Building MPV for raspberry pi on ubuntu core is working but MVP is running in a problem when trying to play a video. It would be great if you could support here, please. Thanks a lot

### mpv version and platform
MPV version 0.27, ffmpeg 3.2.4, Raspberry Pi with Ubuntu Core
MPV has been created as a snap:  [1]

### Reproduction steps

- Build snap on raspberry pi with snapcraft
- Connect framebuffer plug
- Execute mpv-casept.mpv TestVideoColorChange.mp4 --vo=opengl

### Expected behavior
Video should play on hdmi device 

### Actual behavior
Error message, no video is playing:
```
Fontconfig error: Cannot load default config file
[osd/libass] No usable fontconfig configuration file found, using fallback.
Fontconfig error: Cannot load default config file
Playing: TestVideoColorChange.mp4
 (+) Video --vid=1 (*) (h264 1280x720 25.000fps)
[vo/opengl/x11] couldn't open the X11 display ()!
[vo/opengl/x11] couldn't open the X11 display ()!
[vo/opengl/x11] couldn't open the X11 display ()!
[vo/opengl/wayland] failed to connect to a wayland server: check if a wayland compositor is running
[vo/opengl] VT_GETMODE failed: Inappropriate ioctl for device
[vo/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/opengl] Cannot open card "0": No such file or directory.
[vo/opengl] Failed to create KMS.
[vo/opengl] 'drm-egl' is deprecated, use 'drm' instead.
[vo/opengl] Can't handle VT release - signal already used
[vo/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/opengl] Cannot open card "0": No such file or directory.
[vo/opengl] Failed to create KMS.
[vo/opengl/x11] couldn't open the X11 display ()!
Error opening/initializing the selected video_out (--vo) device.
Video: no video
No video or audio streams selected.


Exiting... (Errors when loading file)
```

[1]
```
name: mpv-casept
version: '0.27.0'
summary: a free, open source, and cross-platform media player. Unofficial snap.
description: |
  mpv is a media player based on MPlayer and mplayer2.
  It supports a wide variety of video file formats,
  audio and video codecs, and subtitle types.
grade: devel
confinement: devmode

apps:
  mpv:
    command: usr/local/bin/mpv
    plugs: [framebuffer, x11, opengl, unity7, pulseaudio, home, network, removable-media, optical-drive]

parts:
  mpv:
    source: ./mpv-0.27.0.tar.gz
    plugin: waf
    prepare: |
     ./bootstrap.py
    stage-packages:
      - libasound2
      - libass5
      - libatomic1
      - libbluray1
      - libc6
      - libcdio-cdda1
      - libcdio-paranoia1
      - libcdio13
      - libdrm2
      - libdvdnav4
      - libdvdread4
      - libegl1-mesa
      - libgbm1
      - libgl1-mesa-glx
      - libjack-jackd2-0
      - libjpeg8
      - liblcms2-2
      - liblua5.2-0
      - libpulse0
      - librubberband2v5
      - libsdl2-2.0-0
      - libsmbclient
      - libsndio6.1
      - libuchardet0
      - libv4l-0
      - libva-drm1
      - libva-wayland1
      - libva-x11-1
      - libva1
      - libvdpau1
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1-mesa
      - libx11-6
      - libxext6
      - libxinerama1
      - libxkbcommon0
      - libxrandr2
      - libxss1
      - libxv1
      - zlib1g
    build-packages:
      - build-essential
      - libasound2-dev
      - libass-dev
      - libbluray-dev
      - libcdio-paranoia-dev
      - libdvdnav-dev
      - libdvdread-dev
      - libegl1-mesa-dev
      - libenca-dev
      - libgbm-dev
      - libgl1-mesa-dev
      - libguess-dev
      - libjack-dev
      - libjpeg-dev
      - liblcms2-dev
      - liblua5.2-dev
      - libpulse-dev
      - librubberband-dev
      - libsdl2-dev
      - libsmbclient-dev
      - libsndio-dev
      - libswscale-dev
      - libuchardet-dev
      - libv4l-dev
      - libva-dev
      - libvdpau-dev
      - libwayland-dev
      - libx11-dev
      - libxinerama-dev
      - libxkbcommon-dev
      - libxrandr-dev
      - libxss-dev
      - libxv-dev
      - pkg-config
      - python
      - python-docutils
    after: [ffmpeg]
  ffmpeg:
    source: git://source.ffmpeg.org/ffmpeg.git
    source-tag: n3.2.4
    plugin: autotools
    configflags:
      - --disable-ffprobe
      - --enable-gpl
      - --enable-libass
      - --enable-libfreetype
      - --enable-libmp3lame
      - --enable-libopus
      - --enable-libtheora
      - --enable-libvorbis
      - --enable-libvpx
      - --enable-libx264
      - --enable-libx265
      - --enable-nonfree
      - --enable-opengl
      - --enable-static
      - --enable-omx
      - --enable-omx-rpi
      - --enable-libxcb
      - --enable-libfreetype
      - --enable-gnutls
      - --disable-opencl
    build-packages:
      - autoconf
      - automake
      - build-essential
      - cmake
      - g++
      - git
      - libass-dev
      - libfreetype6-dev
      - libmp3lame-dev
      - libopus-dev
      - libsdl2-dev
      - libtheora-dev
      - libtool
      - libva-dev
      - libvdpau-dev
      - libvorbis-dev
      - libvpx-dev
      - libx264-dev
      - libx265-dev
      - libxcb-shm0-dev
      - libxcb-xfixes0-dev
      - libxcb1-dev
      - make
      - pkg-config
      - texinfo
      - yasm
      - zlib1g-dev
      - libluajit-5.1-dev
      - libfontconfig1-dev
      - libfribidi-dev
      - python-docutils
      - libjpeg-dev
      - libgnutls28-dev
      - libomxil-bellagio-dev
    stage-packages:
      - libssl-dev
    organize:
      usr/local/bin: usr/bin
```

**Comment by lachs0r** [comment] 2018-07-14 12:45
https://0x0.st/sOHz.mp4

**Comment by jeeb** [comment] 2018-07-14 12:56
@lachs0r 
The rpi part of this is probably the least problematic anyways, so while I understand your frustration with random people asking about help with the rpi, in this case there's enough issues past the rpi part.

* Even though it's in a snap, version 0.27.x is used with an old FFmpeg (git master is preferred, which should soon become 0.29)
* Rpi is crappy so you're going to end up with one of the video renderers that actually are usable under rpi.
  1. If you have the proprietary blobs, the only way to get most things you probably expect to work is to skip most of the nice things mpv has regarding video rendering, and just `--hwdec=mmal` and `--vo=gpu` or `--vo=rpi`.
  2. If you don't have the proprietary blobs, then probably DRM+the gpu renderer (what used to be called "opengl") which can be utilized with `--vo=gpu --gpu-context=drm` (just requires you to have access to the DRM gpu device).

**Comment by jeeb** [comment] 2018-07-14 13:06
Anyways, I would first test this on a PC, as the rpi is a special case, and most likely will not be utilizing the same video rendering components as desktop.

**Comment by mc4man** [comment] 2018-07-14 22:40
That snap , while outdated & long abandoned, does work in limited fashion on a pc. It defaults to a vo of opengl, an ao of pulse or alsa. There is no hwdec support.
If using a vo of drm video would work, audio no.
Generally worthless and the .yaml is also outdated.

**Comment by getty23** [comment] 2018-08-06 06:05
Thanks for your replies and sorry for not getting back earlier (I was away for a while).

Why I use an older mpv/ffmpeg version is because I thought this combination might work -> https://www.raspberrypi.org/forums/viewtopic.php?t=199775

I have now installed mir-kiosk for wayland support and updated my snap [1]. When I start playing a video (sudo mpv-casept.mpv SampleVideo.mp4 --vo=wayland --ao=alsa) I get further and see the first frame ;) but afterwards the video stops and in the logs I see the following:
`[vo/wayland/wayland] can't draw, back buffer is busy` 

I also tried to compile mpv with --enable-rpi but I was running in the following error:
`You manually enabled the feature 'rpi', but the autodetection check failed. Failed to run './waf configure --enable-rpi' for 'mpv': Exited with code 1. Verify that the part is using the correct parameters and try again.`

I am wondering if I need to follow up with the instructions in https://www.raspberrypi.org/forums/viewtopic.php?t=199775 and use the raspberry specific libGLESv2 and libEGL files + replace the wscript file.

Maybe you have some further thoughts on that.

Thanks a lot

[1]
```
name: mpv-casept
version: '0.27.0'
summary: a free, open source, and cross-platform media player. Unofficial snap.
description: |
  mpv is a media player based on MPlayer and mplayer2.
  It supports a wide variety of video file formats,
  audio and video codecs, and subtitle types.
grade: devel
confinement: devmode

apps:
  mpv:
    command: usr/local/bin/mpv
    environment:
      XDG_RUNTIME_DIR: $SNAP_DATA/wayland
      LIBGL_DRIVERS_PATH: $SNAP_DATA/usr/lib/arm-linux-gnueabihf/dri
      WAYLAND_SOCKET_DIR: $SNAP_DATA/wayland
    plugs: [framebuffer, x11, opengl, unity7, pulseaudio, home, network, removable-media, optical-drive, wayland, alsa]

plugs:
  wayland-socket-dir:
    content: wayland-socket-dir
    interface: content
    target: $SNAP_DATA/wayland
    default-provider: mir-kiosk:wayland-socket-dir

parts:
  mpv:
    source: https://github.com/mpv-player/mpv/archive/v0.27.0.tar.gz
    plugin: waf
    prepare: |
      ./bootstrap.py
    stage-packages:
      - libasound2
      - libass5
      - libatomic1
      - libbluray1
      - libc6
      - libcdio-cdda1
      - libcdio-paranoia1
      - libcdio13
      - libdrm2
      - libdvdnav4
      - libdvdread4
      - libegl1-mesa
      - libgbm1
      - libgl1-mesa-glx
      - libgles2-mesa-dev
      - libjack-jackd2-0
      - libjpeg8
      - liblcms2-2
      - liblua5.2-0
      - libpulse0
      - librubberband2v5
      - libsdl2-2.0-0
      - libsmbclient
      - libsndio6.1
      - libuchardet0
      - libv4l-0
      - libva-drm1
      - libva-wayland1
      - libva-x11-1
      - libva1
      - libvdpau1
      - libwayland-client0
      - libwayland-cursor0
     - libwayland-egl1-mesa
      - libx11-6
      - libxext6
      - libxinerama1
      - libxkbcommon0
      - libxrandr2
      - libxss1
      - libxv1
      - zlib1g
    build-packages:
      - build-essential
      - libasound2-dev
      - libass-dev
      - libbluray-dev
      - libcdio-paranoia-dev
      - libdvdnav-dev
      - libdvdread-dev
      - libegl1-mesa-dev
      - libenca-dev
      - libgbm-dev
      - libgl1-mesa-dev
      - libguess-dev
      - libjack-dev
      - libjpeg-dev
      - liblcms2-dev
      - liblua5.2-dev
      - libpulse-dev
      - librubberband-dev
      - libsdl2-dev
      - libsmbclient-dev
      - libsndio-dev
      - libswscale-dev
      - libuchardet-dev
      - libv4l-dev
      - libva-dev
      - libvdpau-dev
      - libwayland-dev
      - libx11-dev
      - libxinerama-dev
      - libxkbcommon-dev
      - libxrandr-dev
      - libxss-dev
      - libxv-dev
      - libgles2-mesa-dev
      - pkg-config
      - python
      - python-docutils
    after: [ffmpeg]
  ffmpeg:
    source: git://source.ffmpeg.org/ffmpeg.git
    source-tag: n3.2.4
    plugin: autotools
    configflags:
      - --disable-ffprobe
      - --enable-gpl
      - --enable-libass
      - --enable-libfreetype
      - --enable-libmp3lame
      - --enable-libopus
      - --enable-libtheora
      - --enable-libvorbis
      - --enable-libvpx
      - --enable-libx264
      - --enable-libx265
      - --enable-nonfree
      - --enable-opengl
      - --enable-static
      - --enable-omx
      - --enable-omx-rpi
      - --enable-libxcb
      - --enable-libfreetype
      - --enable-gnutls
      - --disable-opencl
    build-packages:
      - autoconf
      - automake
      - build-essential
      - cmake
      - g++
      - git
      - libass-dev
      - libfreetype6-dev
      - libmp3lame-dev
      - libopus-dev
      - libsdl2-dev
      - libtheora-dev
      - libtool
      - libva-dev
      - libvdpau-dev
      - libvorbis-dev
      - libvpx-dev
      - libx264-dev
      - libx265-dev
      - libxcb-shm0-dev
      - libxcb-xfixes0-dev
      - libxcb1-dev
      - make
      - pkg-config
      - texinfo
      - yasm
      - zlib1g-dev
      - libluajit-5.1-dev
      - libfontconfig1-dev
      - libfribidi-dev
      - python-docutils
      - libjpeg-dev
      - libgnutls28-dev
      - libomxil-bellagio-dev
    stage-packages:
      - libssl-dev
   organize:
      usr/local/bin: usr/bin
```

**Comment by CounterPillow** [comment] 2018-08-06 21:00
>    source: https://github.com/mpv-player/mpv/archive/v0.27.0.tar.gz

out of date mpv

**Comment by getty23** [comment] 2018-08-08 05:54
Do you think it is just because of the old version of mpv?
Over here https://www.raspberrypi.org/forums/viewtopic.php?t=199775 they get this version running with rpi.

**Comment by CounterPillow** [comment] 2018-08-09 13:46
I don't know, but nobody here will be inclined to help you fix an old version. The issue template says to use the latest version for a reason.

**Comment by getty23** [comment] 2018-08-14 17:53
Ok, I see your point. Though when I use the latest versions (mvp v0.29.0, ffmpeg n4.0.1)  I am able to build ffmpeg but mpv './waf configure' is running into the following problem:
```
Checking for Libav/FFmpeg library versions                           : ffmpeg not found 
Unable to find development files for some of the required FFmpeg/Libav libraries. Git master is recommended.
```

I have played with the version (also using the master of ffmpeg, latest ffmpeg version and master of mpv) but I am always running into the same problem. This was working before for the ffmpeg + mpv version combination stated above. 

The following is shown for my ffmpeg version:
```
ffmpeg version n4.0.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix= --disable-ffprobe --enable-gpl --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxcb --enable-nonfree --enable-opengl --enable-static --enable-omx --enable-omx-rpi --enable-mmal --enable-libxcb --enable-libfreetype --enable-gnutls --disable-opencl --extra-cflags='"-march=armv8-a+crc -mfpu=neon-fp-armv8 -mtune=cortex-a53"'
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
```
Would be great if you could give me a hint here. Thanks

**Comment by getty23** [comment] 2018-08-24 06:09
Any idea what my problem might be?

**Comment by tomty89** [comment] 2018-08-24 06:57
Probably the -dev package not installed

**Comment by CounterPillow** [comment] 2018-08-24 17:55
@tomty89 no

The problem is that your mpv build can't find your ffmpeg build. I recommend using mpv-build to have this done for you.

**Comment by tomty89** [comment] 2018-08-25 01:16
Meh there's PKG_CONFIG_PATH

**Closed** 2020-04-30 23:26 UTC
Labels: platform:rpi
