### ISSUE TITLE
Any type of seek while paused desynchronizes and starts playing the audio

### ISSUE THREAD

**Issue by Kerobyte** [mpv-player/mpv#9020] opened 2021-07-19 02:49 UTC
### Important Information

- Started on x86_64-20210718
- Windows 10 Pro 20H2
- Shinchiro's build, Sourceforge.

### Reproduction steps

Load a file with audio.
Pause.
Seek.

### Expected behavior

Any type of seek while paused keeps both the video and audio paused.

### Actual behavior

Any type of seek while paused starts playing the audio.
If the file is a video the video will be paused and the audio will desynchronize and start playing.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/6837557/output.txt)

**Comment by sfan5** [comment] 2021-07-19 07:49
duplicate of #9018. Already fixed, get a newer build.

**Closed by sfan5** 2021-07-19 07:49 UTC
Labels: os:win
