### ISSUE TITLE
dts-ma  96k 7.1 m2ts a/v desync

### ISSUE THREAD

**Issue by AndyFurniss** [mpv-player/mpv#2779] opened 2016-02-02 16:03 UTC
Since ffmpeg replaced their dts decoder I've done a few tests to see how players handle the change.

One sample I have has issues with mpv, but not mplayer or older mpv using previous dcadec.

It's only a short demo (from demo world) but I am 4 seconds out a/v by the end. Tried forcing cpus to perf/hwdecs/different vos but all are the same.

The demo 198 meg -

https://drive.google.com/file/d/0BxP5-S1t9VEETXQ2SGlfTnRZWlk/view?usp=sharing

**Comment by AndyFurniss** [comment] 2016-02-02 16:08
Hit send a bit soon - I am playing back through a stereo USB DAC/amp and AFAICT mpv is getting the downmix from the codec.

If you can't reproduce I will of course provide verbose output.

**Comment by wm4** [comment] 2016-02-02 16:28
I get see problems. Audio stays in sync.

**Comment by wm4** [comment] 2016-02-02 16:39
(Edited my fatal typo.)

**Comment by AndyFurniss** [comment] 2016-02-02 16:49
Hmm, I also tried with mobo sound both 7.1 and 2ch and it's the same.

Attached output.
[mpv-dtsma-sync-paste.txt](https://github.com/mpv-player/mpv/files/114291/mpv-dtsma-sync-paste.txt)

**Comment by wm4** [comment] 2016-02-02 17:07
What happens with ``--ao=null``?

**Comment by wm4** [comment] 2016-02-02 17:13
Also, you can still compile with libdcadec. You'll need to force the decoder with ``--ad``.

**Comment by AndyFurniss** [comment] 2016-02-02 17:16
With --ao=null it still reports desync

`AV: 00:00:01 / 00:00:49 (0%) A-V: -0.493 ct: -0.104

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:00:44 / 00:00:49 (94%) A-V:  0.000 ct: -4.442
[ao/null] buffer underrun
AV: 00:00:49 / 00:00:49 (99%) A-V:  0.000 ct: -4.442`

**Comment by AndyFurniss** [comment] 2016-02-02 17:53
I do have libdcadec installed but I am building with mpv-build and I can't seem to get 
--ad=libdcadec or --ad=dcadec to do anything.

I haven't used the lib with mpv before - is it expected to autodetect with mpv-build (I don't seem to have pkgconfig for it)

FWIW I did another test = build-mpv-release with build-ffmpeg-master and the issue is still there with that.

**Comment by AndyFurniss** [comment] 2016-02-02 18:03
Oh ignore the pkgconfig bit I do have  /usr/lib/pkgconfig/dcadec.pc - I just messed up find ...

**Comment by wm4** [comment] 2016-02-02 18:03
``--ad=lavc:libdcadec`` should make it pick it up if it's compiled in. But FFmpeg won't autodetect libdcadec and needs to be forced to use it.

**Comment by AndyFurniss** [comment] 2016-02-02 18:32
OK I made ffmpeg-options and it worked with mpv-build.

[ad] Selected audio codec: dcadec DCA decoder [lavc:libdcadec]

The desync is still there using libdcadec with masters but -

use-mpv-release + use-ffmpeg-release with libdcadec is good

**Comment by wm4** [comment] 2016-02-02 18:34
So it doesn't depend on the decoder, it's just a problem with git master?

**Comment by AndyFurniss** [comment] 2016-02-02 19:18
It seems to be a problem with ffmpeg master.

mpv master + ffmpeg release + libdcadec is also OK.

Maybe I'll try and see if I can find some difference using just ffmpeg.

But then mplayer built today is also using ffmpeg master OK (also just tested with -demuxer lavf)

**Comment by wm4** [comment] 2016-02-02 19:39
Can you retry FFmpeg git master from now? There was a commit that fixes a certain detail in the new DTS decoder.

**Comment by wm4** [comment] 2016-02-02 19:39
(This one: http://git.videolan.org/?p=ffmpeg.git;a=commit;h=0b1972d4096df5879038f0af776f87f41e90ebd4)

**Comment by AndyFurniss** [comment] 2016-02-02 20:08
Will try - doesn't seem to have propagated to github used by mpv-build yet.

Random question about ffmpeg cli - I see -request_channels has gone, this was how I used to be able to get a codec downmix when put before the -i ....

Do you happen know what replaced it? Trying -channel_layout stereo before -i ... doesn't work.

**Comment by wm4** [comment] 2016-02-02 20:17
Maybe `-request_channel_aylout`? Also note that the new decoder will refuse downmix if the DTS stream doesn't have embedded downmix coefficients.

**Comment by AndyFurniss** [comment] 2016-02-02 20:42
The commit is in now, but it doesn't help.

-request_channel_layout looks promising -  at least it's an input option will play around , thanks.

The parameters aren't obvious yet - as always with ffmpeg :-)

**Comment by wm4** [comment] 2016-02-02 20:57
Try if this patch on mpv works: http://sprunge.us/QhPR

**Comment by AndyFurniss** [comment] 2016-02-02 21:19
Patch doesn't help.

**Comment by AndyFurniss** [comment] 2016-02-02 22:08
I tested commits in ffmpeg using --ad=lavc:libdcadec and the bad is -

4608996 avcodec/dca: remove old decoder

I also tried building ffmpeg with --disable-asm and that didn't help.

**Comment by wm4** [comment] 2016-02-02 22:54
Some more questions:
- libdcadec on ffmpeg master is fine?
- what platform/OS are you on?
- how is CPU usage?
- what if you remux the audio with a weaker video (or use the file with --audio-file and a different file)

**Comment by AndyFurniss** [comment] 2016-02-02 23:29
libdcadec breaks on ffmpeg commit 4608996 avcodec/dca: remove old decoder

Recent Linux from scratch 64bit gcc 5.3.0

CPU usage is low  I can decode with ffmpeg to null at 8x, -vo null doesn't help.

Interesting, just -acodec copy -vcodec copy out.mkv produces a file without the issue

**Comment by AndyFurniss** [comment] 2016-02-02 23:52
Ok so I am now thinking this is something xorg related.

I have just tried out of X, two different ways = wayland/weston and directly from VT (fbcon) with drm-egl and the sync is OK.

**Comment by AndyFurniss** [comment] 2016-02-03 00:15
OK so Ignore the bit about X it's even stranger than that  and unfortunately nothing to do with mpv/ffmpeg so sorry.

It's just totally bizarre but this file is on and old ext3 partition and it seems that if I copy it else where it works OK. md5sums the same, but playing it from where it has lived since 2010 = broken, playing a copy is OK.

andy [mpv-build]$ md5sum /mnt/sda8/Demo-world/dts/hd_dts_living_world_of_audio_lossless.m2ts 

cfbc73da1cae37988e0e35325e604581  /mnt/sda8/Demo-world/dts/hd_dts_living_world_of_audio_lossless.m2ts
andy [mpv-build]$ 
andy [mpv-build]$ md5sum /home/andy/hd_dts_living_world_of_audio_lossless.m2ts 
cfbc73da1cae37988e0e35325e604581  /home/andy/hd_dts_living_world_of_audio_lossless.m2ts
andy [mpv-build]$ 
andy [mpv-build]$ 
andy [mpv-build]$ ./mpv/build/mpv --vo=null /home/andy/hd_dts_living_world_of_audio_lossless.m2ts
Playing: /home/andy/hd_dts_living_world_of_audio_lossless.m2ts
 (+) Video --vid=1 (h264)
 (+) Audio --aid=1 (dts)
AO: [alsa] 96000Hz stereo 2ch s32
VO: [null] 1920x1080 yuv420p
AV: 00:00:49 / 00:00:49 (99%) A-V:  0.000


Exiting... (End of file)
andy [mpv-build]$ ./mpv/build/mpv --vo=null /mnt/sda8/Demo-world/dts/hd_dts_living_world_of_audio_lossless.m2ts
Playing: /mnt/sda8/Demo-world/dts/hd_dts_living_world_of_audio_lossless.m2ts
 (+) Video --vid=1 (h264)
     Audio --aid=1 (dts)
 (+) Audio --aid=2 'hd_dts_living_world_of_audio_lossless.dts' (dts) (external)
AO: [alsa] 96000Hz stereo 2ch s32
VO: [null] 1920x1080 yuv420p
AV: 00:00:01 / 00:00:49 (0%) A-V: -0.487 ct: -0.100

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:00:49 / 00:00:49 (99%) A-V:  0.000 ct: -4.434


Exiting... (End of file)

**Comment by AndyFurniss** [comment] 2016-02-03 00:29
Well I am just baffled, I can copy from the old partition faster than the new copy.

The ffmpeg master vs release tests were all on the original (problem) file and gave consistent working/not working. mplayer and ffplay didn't show the issue on the problem file.

**Comment by AndyFurniss** [comment] 2016-02-03 00:59
Hmm, it's late, but maybe this is an"mpv thing" I did a diff between -v -v outputs of the working and problem files and it seems that the problem file may be "different" because it lives in a dir full of years old experiments which include files of the same name with different endings eg .dts for audio I extracted with ffmpeg - these are getting opened.

here's a snippet of git diff out-good out-bad

-[find_files] Loading external files in /mnt/ramdisk/
+[find_files] Loading external files in /mnt/sda8/Demo-world/dts/
+[find_files] Potential external file: "hd_thx_amazing_life_lossless.dts"  Priority: 0
+[find_files] Potential external file: "hd_dts_sfx_long_lossless.dts"  Priority: 0
+[find_files] Potential external file: "dts-71-check.dts"  Priority: 0
+[find_files] Potential external file: "hd_thx_cavalcade_lossless.dts"  Priority: 0
+[find_files] Potential external file: "hd_dts_living_world_of_audio_lossless.dts"  Priority: 3
+[find_files] Potential external file: "hd_dts_hd_master_audio_sound_check_7_1_lossless.dts"  Priority: 0
 [global] config path: 'sub/' -/-> '/home/andy/.config/mpv/sub/'
 [global] config path: 'sub/' -/-> '/home/andy/.mpv/sub/'
 [global] config path: 'sub/' -/-> '/usr/local/etc/mpv/sub/'
 [global] config path: 'audio/' -/-> '/home/andy/.config/mpv/audio/'
 [global] config path: 'audio/' -/-> '/home/andy/.mpv/audio/'
 [global] config path: 'audio/' -/-> '/usr/local/etc/mpv/audio/'
+[ifo] Opening /mnt/sda8/Demo-world/dts/hd_dts_living_world_of_audio_lossless.dts
+[ifo/dvdnav] Opening /mnt/sda8/Demo-world/dts/hd_dts_living_world_of_audio_lossless.dts
+[bdmv/bluray] Opening /mnt/sda8/Demo-world/dts/hd_dts_living_world_of_audio_lossless.dts
+[file] Opening /mnt/sda8/Demo-world/dts/hd_dts_living_world_of_audio_lossless.dts
+[file] Stream opened successfully.
+[demux] Trying demuxer: disc (force-level: normal)
+[demux] Trying demuxer: edl (force-level: normal)
+[demux] Trying demuxer: cue (force-level: normal)
+[demux] Trying demuxer: rawaudio (force-level: normal)
+[demux] Trying demuxer: rawvideo (force-level: normal)
+[demux] Trying demuxer: tv (force-level: normal)
+[demux] Trying demuxer: mkv (force-level: normal)
+[demux] Trying demuxer: rar (force-level: normal)
+[demux] Trying demuxer: lavf (force-level: normal)
+[ffmpeg] Probing mp3 score:1 size:2048
+[lavf] Found 'mp3' at score=1 size=2048.
+[ffmpeg] Probing mp3 score:1 size:4096
+[lavf] Found 'mp3' at score=1 size=4096.
+[ffmpeg] Probing mp3 score:1 size:8192
+[lavf] Found 'mp3' at score=1 size=8192.
+[ffmpeg] Probing dts score:51 size:16384
+[ffmpeg] Probing mp3 score:1 size:16384
+[lavf] Found 'dts' at score=51 size=16384.
+[ffmpeg/demuxer] dts: Before avformat_find_stream_info() pos: 0 bytes read:32768 seeks:0
+[ffmpeg/demuxer] dts: All info found
+[ffmpeg/demuxer] dts: 0: start_time: 0.000 duration: -9223372036854.775
+[ffmpeg/demuxer] dts: stream: start_time: 0.000 duration: -9223372036854.775 bitrate=0 kb/s
+[ffmpeg/demuxer] dts: After avformat_find_stream_info() pos: 107520 bytes read:131072 seeks:0 frames:50
+[lavf] avformat_find_stream_info() finished after 131072 bytes.
+[demux] Detected file format: dts (libavformat)
+[lavf] queuing seek to 0.000000
+[lavf] execute seek (to 0.000000 flags 9)
+[lavf] seek done
 [cplayer]  (+) Video --vid=1 (h264)
-[cplayer]  (+) Audio --aid=1 (dts)
+[cplayer]      Audio --aid=1 (dts)
+[cplayer]  (+) Audio --aid=2 'hd_dts_living_world_of_audio_lossless.dts' (dts) (external)

**Comment by wm4** [comment] 2016-02-03 08:10
Yeah, unfortunately mpv auto-loads external audio tracks as external files. It was a requested feature.

Does it only happen if the .dts file is played as external audio track? A/V desync still shouldn't happen, but at least the bug is getting less stranger.

**Comment by AndyFurniss** [comment] 2016-02-03 10:38
I should slap myself for not noticing earlier it was playing an external file. On the upside at least there's nothing wrong with my filesystems :-)

forcing internal with --aid=1 plays OK.

There is still a regression here since the old decoder was removed, as testing with libdcadec and ffmpeg on the commit before removal, still plays the external file, but sync is OK. 

Another test: as the external was extracted with old ffmpeg what about making a new .dts. Result it's the same and shows the issue.

This means you should be able to reproduce - put my sample in a folder then -

ffmpeg -i foo.m2ts -acodec copy foo.dts

I'll be AFK mostly today, so won't get to do much more.

**Comment by wm4** [comment] 2016-02-03 11:09
Indeed, I can reproduce it by playing with the extracted dts file.

**Comment by wm4** [comment] 2016-02-03 11:36
Some more investigation shows that it returns broken timestamps, so it's not surprising A/V sync got trashed. Apparently this is a consequence of the .dts demuxer considering only DTS core.

**Comment by mpvOWNZ** [comment] 2016-02-03 11:38
@wm4 
> Also note that the new decoder will refuse downmix if the DTS stream doesn't have embedded downmix coefficients.
Sorry for intervening, but this sounds like a regression to me...
Why was this changed from the status quo?

**Comment by wm4** [comment] 2016-02-03 11:43
Because it's not correct, and downmixing it this way can cause clipping. Making the API user downmix it with libswresample gives more flexibility about this.

**Comment by mpvOWNZ** [comment] 2016-02-03 11:49
@wm4 
Thanks for clearing that up!

**Comment by wm4** [comment] 2016-02-04 11:50
This was fixed in ffmpeg git master just now.

**Closed by wm4** 2016-02-04 11:50 UTC
Labels: ffmpeg-bug
