### ISSUE TITLE
Fullscreen mode of mpv in macOS 11 Big Sur shows distracting white seam on top and in all 4 edges and permanent window buttons

### ISSUE THREAD

**Issue by porg** [mpv-player/mpv#8507] opened 2021-01-23 23:54 UTC
### Important Information

- mpv 0.33.0
- macOS 11.1
- Installed via homebrew
- MacBook Pro Retina, 15" (Mid 2014)
  - CPU Intel 64bit (Quad-Core Intel Core i7)
  - iGPU Intel Iris Pro (Supported, Metal GPUFamily macOS 1)
  - dGPU NVIDIA GeForce GT 750M

### Reproduction

1. Open a video file, playback starts automatically (dunno whether by default, at least in my config, I like this)
2. Go info fullscreen mode by either of these interactions:
  a. Pressing shortcut "F" on the keyboard
  b. Double click anywhere on window content
  c. Hover on the top edge of the window, then the window bar appears. There click the maximize/fullscreen button (the rightmost of the 3 buttons, colored green in the default macOS color theme)

### Expected behavior
- You see only the video content and have a fully immersive experience
- Only when moving the mouse/trackpad the overlay controls appear

### Actual behavior

- In all variations of step 2 you get an ugly white seam on top and in all 4 edges:
![mpv in fullscreen mode with white background seam](https://user-images.githubusercontent.com/737143/105617116-1e279c00-5ddd-11eb-9294-08705c579bbd.jpg)
  - Feels like the Big Sur window with its rounded corners is displayed upon a white background which shines through on the top line and in all four edges.
- If you use variant 2c in particular, as an additional distraction you get the (translucent) window bar and its 3 buttons visible
![mpv in fullscreen mode with white background seam and window buttons](https://user-images.githubusercontent.com/737143/105617127-37304d00-5ddd-11eb-8099-52191cb4b653.jpg)
  - Not only on hover, but this stays permanent.
  - And this doesn't go away anymore.
  - Neither by moving the mouse away nor awaiting a timeout. You must quit the app and use 2a or 2b.

### Log file

- [mpv-0.33.0-macos-11.1.log](https://github.com/mpv-player/mpv/files/5861349/mpv-0.33.0-macos-11.1.log)

**Comment by Akemi** [comment] 2021-01-24 00:08
that doesn't look like a full log. it doesn't even attempt to go fullscreen.

try starting mpv from the command line and see of it outputs any warning. also try with `--no-config`. just for testing purpose, does it work with `--vo=gpu`?

**Comment by porg** [comment] 2021-01-26 12:39
@Akemi thanks for your answer!

I found the reason: `~/.config/mpv/mpv.conf`
```
[…]
native-fs=no # Yes: Uses macOS default fullscreen mechanism. No: Uses mpv's own fullscreen implementation.
[…]
```

The rendering glitch is caused by `native-fs=no`.
As an experiment I tried combining it with `vo=gpu`. Then fullscreen by "F" key is not working at all anymore.

When not setting `vo` at all and setting `native-fs=yes` then you get the normal native fullscreen behavior with only video content filling the screen. No more white seam which should not be.

But nevertheless it would be wonderful if mpv's own fullscreen implementation would work fine again on macOS Big Sur too, because it's instant as everything else in it's UI and UX. That native 1-2sec zoom-in/zoom-out animated transition is annoying for the film experience of true cineasts.

**Comment by Akemi** [comment] 2021-01-26 16:52
yeah that was my guess, but wasn't in the log. it's kinda a duplicate of #8490, though there it crashes (for whatever reason). it's most likely the same underlying problem.

tbh i think apple just killed this mechanism of going fullscreen and it won't be easy/fast to bring this back. i am more inclined to remove it altogether by now (at least from macOS 11 onwards).

`But nevertheless it would be wonderful if mpv's own fullscreen implementation would work fine again on macOS Big Sur too, because it's instant as everything else in it's UI and UX. That native 1-2sec zoom-in/zoom-out animated transition is annoying for the video experience.`

i am not sure what you mean, but the OSC has a fade-in/-out, which can't be considered instant for example. same goes for the current title bar. the animation should be 500ms long, that's the system default and is way less than 1-2sec you are referring to. you can also use `--macos-fs-animation-duration=0` to remove the animations mpv is responsible for (the system animation, the sliding to a new space, can't be deactivated). this effectively hides the sliding effect when going into fullscreen, though going out of fullscreen will still be visible.

**Closed by Akemi** 2021-01-26 16:52 UTC
Labels: os:mac

**Comment by porg** [comment] 2021-01-26 17:26
1) Sorry for the useless logfile. Was not meant to be rude. Had been my first issue filing to mpv-player. My initial logfile was only from an empty mpv startup session. Had not known and noticed that this is generated per each session. Should I file something again I will take care next time.

2) What I meant regarding timing is that mpv overally feels very snappy, and Apple's native fullscreen entry/exit animation feels somehow out of place in this UX. Slower, particularly if you have situations like a multiple monitor setup, or a iGPU/dGPU switch recently, or a high system load, then that animation can be be even more delayed. Hence feeling like 1-2secs, although technically maybe being around 500ms. Apple's fullscreen animation is good for the user's spatial orientation (content goes left, fullscreen starts right of it, opposite when exiting fullscreen). But for expert users, this is an unnecessarily distraction, I prefer an instant switch between fullscreen and windowed. Globally I like Apple's fullscreen UX but enjoyed that mpv offered an individual deviation to that norm. Catered very well to my usage preferences. But if that custom fullscreen mode has no future anymore I will have to settle with this.

3) Thanks for hinting to `macos-fs-animation-duration`. With 200ms it is now closer to my taste. But no matter how I tweak that variable, it seems to only affect the speed of "going to fullscreen" whereas "exiting fullscreen" has still the default (annoying) timing, where I consciously notice the background sliding in from the left, which distracts my personal cineast experience.

**Comment by Akemi** [comment] 2021-01-26 18:14
like i said, it is only for animations done by mpv itself, eg how fast the window switches to its full/windowed size:

> remove the animations mpv is responsible for (the system animation, the sliding to a new space, can't be deactivated). this effectively hides the sliding effect when going into fullscreen, though going out of fullscreen will still be visible.
