### ISSUE TITLE
Choppy 60fps video playback with --video-sync=audio on macOS

### ISSUE THREAD

**Issue by tmkk** [mpv-player/mpv#4201] opened 2017-03-03 14:57 UTC
### mpv version and platform
mpv 0.24.0, macOS 10.12.3

### Reproduction steps
Play this [sample file](https://0x0.st/JGd.mp4) with --video-sync=audio (default) option

### Expected behavior
Video playback is smooth.

### Actual behavior
Video playback is choppy.
With --video-sync=display-resample or other display-* options it plays fine.

### Sample files
https://0x0.st/JGd.mp4

**Comment by Akemi** [comment] 2017-03-03 15:10
`--video-sync=audio` is inherently more choppy than the `display-*` modes.

though since i don't know how choppy you mean. does it work with `--opengl-early-flush=no`, then it is a duplicate of #3739.

**Comment by AirPort** [comment] 2017-03-03 15:21
I can confirm, playing a 60fps file with `--video-sync=audio` and default settings drops a lot of frames even on a capable GPU, and the video is basically unwatchable. 
`--opengl-early-flush=no` indeed solves the issue.

**Comment by tmkk** [comment] 2017-03-03 15:21
Thanks, --opengl-early-flush=no makes it smooth. So it seems to be the same issue as #3739.

**Comment by Akemi** [comment] 2017-03-03 15:39
duplicate of #3739.

**Closed by Akemi** 2017-03-03 15:39 UTC
Labels: osx
