### ISSUE TITLE
opengl-pbo option on Mac OS 12.6.1 causes corruption of the OSD

### ISSUE THREAD

**Issue by mlindner** [mpv-player/mpv#12537] opened 2023-10-02 03:42 UTC
### Important Information

Provide following Information:
- mpv v0.36.0-465-g0a1e3d8685
- MacOS 12.6.1
- Compiled using meson with latest git

### Reproduction steps

The problem doesn't reproduce with --no-config. I narrowed the problematic config option down to opengl-pbo. It reproduces occasionally without needing to do the following, but is most visible when rapidly switching between showing the osd with 'o' and showing the video overlay with 'i'. If these are pressed repeatedly back and forth then obvious distortions show up.
![mpv-shot0002](https://github.com/mpv-player/mpv/assets/2280117/aabba4cf-1212-456a-9657-996b4902492e)

### Expected behavior
No OSD display corruption.

### Actual behavior
OSD display corruption.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/12779472/output.txt)

**Comment by mlindner** [comment] 2023-10-02 03:44
Note that I installed a custom libass build from master using homebrew, but it still happens with the default homebrew libass.

**Comment by Akemi** [comment] 2023-10-02 05:50
duplicate of #12537

**Closed by Akemi** 2023-10-02 05:50 UTC
Labels: os:mac

**Comment by mlindner** [comment] 2023-10-02 05:51
> duplicate of #12537

Did you typo, this is a link back to itself.

**Comment by Akemi** [comment] 2023-10-02 05:52
yeah, updated the issue link.
