### ISSUE TITLE
MPV very bad performance vs MPLAYER/VLC/FFPLAY

### ISSUE THREAD

**Issue by voxsoftware** [mpv-player/mpv#10284] opened 2022-06-11 22:08 UTC
Hi. I have a computer with this:

- Intel Q45 Chipset (4 cores, 4 threads)
- Opensuse tumbleweed 
- Kernel 5.18 
- mpv 0.34.1+git.20220203T182214.5d31c7310c-2.1
- mplayer 1.2
- vlc 3.0.17
- ffmpeg 5

When I play an H264 1280x720 video in MPV, MPV CPU usage is: 90-105% (showed in htop)
When I play same video in VLC, VLC CPU usage is 18-24% 
When I play same video in MPLAYER, MPLAYER CPU  usage is: 16-22%
When I play same video in FFPLAY, FFPLAY CPU  usage is: 16-22%

At first stage, i think maybe VLC is using hardware decoding and MPV software decoding, but after start vlc with verbose mode enabled, I see hardware decoding is not available for that video on my chipset Intel Q45 (vlc error message: Profile 7 not supported,  mpv error message: No support for codec h264 profile 77). So, all players (mpv, vlc, mplayer) are using software decoding. But the questions is, why MPV software decoding is very very times (4x - 5x) slower than competitors on my cpu? Is there any way to solve or this is expected?

**Comment by CounterPillow** [comment] 2022-06-11 22:46
if you are reporting an issue, you should:
1. use the issue appropriate for this template,
2. provide a log file that demonstrates the problem
3. try to reproduce with an up-to-date version of mpv, not 0.31

**Comment by monarc99** [comment] 2022-06-12 10:30
try  -profile=sw-fast

**Comment by CounterPillow** [comment] 2022-06-12 14:36
Before you try anything, try posting a log file because then we actually know what's going on on your system

**Comment by voxsoftware** [comment] 2022-06-13 04:24
> if you are reporting an issue, you should:
> 
> 1. use the template appropriate for this issue
> 2. provide a log file that demonstrates the problem
> 3. try to reproduce with an up-to-date version of mpv, not 0.31
> 
> My only guess right now is that you 3d acceleration is completely broken due to being from the dark age of Intel GPUs.

I am not sure if this is an issue, is why I mark as question. How I said, my question is: Is normal being 4x slower than other players on software decoding, or there is something bad with mpv on Intel Q45 Chipset?

**Comment by voxsoftware** [comment] 2022-06-13 04:34
Ok, I check my computer. The real version installed is 0.34.1+git.20220203T182214.5d31c7310c-2.1 , I assume is up to date.
I made a mistake in my report, confusing the "4" with "1", but in mpv 0.34.1 is present this problem.

I will test ```-profile=sw-fast``` and also I will try to get a log as sugested.

**Comment by voxsoftware** [comment] 2022-06-13 05:06
@CounterPillow 
> My only guess right now is that you 3d acceleration is completely broken due to being from the dark age of Intel GPUs.

It seems that your assumption is correct. Thanks because I never realized this.
Now I tested using ````-vo=x11``` and cpu goes to 60%-70% and with ```-vo=xv``` cpu goes to 22.5%-27%.
A more acceptable result, but still slower than the others. But the good news is that the problem is not related to software decoding.

Summary, results with ```-vo=xv```: 

Compared to VLC: about 3% more cpu usage on mpv
Compared to MPlayer about 7% more cpu usage on mpv
Compared to FFPLAY about 7% more cpu usage on mpv

```-profile=sw-fast``` doesn't make any effect.

**Comment by Akemi** [comment] 2022-06-13 11:58
> I am not sure if this is an issue, is why I mark as question. How I said, my question is: Is normal being 4x slower than other players on software decoding, or there is something bad with mpv on Intel Q45 Chipset?

no, it's not usual. any more specific answer can't be given because of the lack of information. since this is your question and it has been answered i am closing this.

**Closed by Akemi** 2022-06-13 11:58 UTC
Labels: meta:question

**Comment by voxsoftware** [comment] 2022-06-13 16:09
@Akemi if you read my post, you realize my question is why and how solve, you didn't answer my question.

In first stage I didn't make a issue because I think maybe with an specific configuration can improve perfomance on my chipset to same level of mplayer for example. In fact, still on  a new Intel chipset I see mplayer faster, however my question just now is for Intel Q45. If you dont know the answer, please let anyone maybe experienced the same to answer, but don't close the github issue without solve.

**Comment by Akemi** [comment] 2022-06-13 16:59
then it's an issue and not a question. you should provide what the issue template asks you to provide. yes, even the question template asks for a log.

if you need further assistance, open a new issue and provide the data we ask you to provide, like @CounterPillow already mentioned.
