### ISSUE TITLE
Volume/dock flickering regression on Mac

### ISSUE THREAD

**Issue by stps** [mpv-player/mpv#3746] opened 2016-10-30 01:04 UTC
### mpv version and platform

0.21.0 and current master (issue was not present in 0.20.0). Have been using release builds so not sure which commit it started on.
macOS 10.12
### Reproduction steps

Playing an MKV (h264 or HEVC) in full screen, and then triggering an OS volume change, or revealing the auto-hiding dock. Does not happen when playing an h264 MP4.
### Expected behavior

No flickering or artifacts.
### Actual behavior

When changing volume, the macOS volume overlay appears, then flickers between a black square as it disappears. When revealing the dock, similar issue as there is a flickering black bar artifact along the bottom. Neither of these issues happen if the video is paused, however.
### Log file

http://pastebin.com/JzaYkSQj
### Sample files

Seems to be anything in MKV container.

**Comment by Akemi** [comment] 2016-10-30 01:18
it's caused by commit 9f30cd8292b4b7bfe5d7db29fe31a07cc76dec2c which fixed one problem and partially fixed another sever issue. at the moment this can't be fixed since the problems are most likely Apple related. also reverting that commit at the moment isn't an option till we can find a better solution, if one exist at all, or Apple magical fixes the issue.

for this particular issue it appears only to happen on Intel and AMD GPUs, Nvidia GPUs don't have that issue. most likely a driver issue.

**Comment by stps** [comment] 2016-10-30 01:58
Do you mean the performance problem linked in that commit only happens on Intel and AMD, or my issue? I'm curious since I don't think I've ever experienced anything noticeable like that (though I haven't bothered profiling my GPU). And this flickering issue shows up whether I use Intel HD 4000 or Nvidia GT 650M.

**Comment by Akemi** [comment] 2016-10-30 13:57
the performance problem happens on all configurations it seems. on some less and on some more. sadly it isn't only one problem but a combination of several.

the flickering issue only happened on Intel or AMD GPUs so far. i don't get it on both my Nvidia setups. so it seems you are the first one to have it with an Nvidia GPU.

**Comment by bersrkr** [comment] 2016-10-30 17:44
Using `opengl-pbo` fixes all flickering for me. I've also done some testing and noticed that using `autofit-larger` might trigger it.

**Comment by AirPort** [comment] 2016-10-30 18:06
>Using `opengl-pbo` fixes all flickering for me.

Well that's actualy funny: as I said before in https://github.com/mpv-player/mpv/issues/2392#issuecomment-249419220 I had the flickering indicators' issue on my rMBP, but only with the AMD dGPU, while everything worked fine with the Intel iGPU (since by default the latter is chosen by the system when running mpv, it never bothered me that much). 
After your suggestion I tried the opposite for a quick test, commenting out `opengl-pbo` in my config file, and this fixed the issue on my machine even with the dGPU.

**Comment by stps** [comment] 2016-10-30 19:18
Using `opengl-pbo=yes` seems to fix it for both of my GPUs.

Thanks guys

**Comment by wm4** [comment] 2016-10-30 19:32
That's probably just a coincidence, like not stalling the GL pipeline or so. (Just guessing.)

Since glFlush actually does something now, and we have disabled double-buffering, I suspect what happens is that the OSX compositor simply samples the mpv framebuffer at a random moment. If the GL pipeline stalls, it could be more likely that GL does some incomplete work and then stops (waiting for the stall to be resolved). Then the mpv framebuffer would be more likely to be in an inconsistent state, and this inconsistent state would be sampled by the compositor, which would show as flicker.

The real solution would be enabling double-buffering, but this makes the performance regression appear. In theory we could possibly render to a FBO and then blit the result in one operation. But at least in theory this still doesn't guarantee consistency, and tearing could still happen. (Just like it could happen currently, I guess.)

**Comment by AirPort** [comment] 2016-11-01 11:48
Forget what I said in https://github.com/mpv-player/mpv/issues/3746#issuecomment-257167536: with further testing it seems that without `opengl-pbo` the issue with the AMD GPU is solved, but then the overlays start to flicker on the Intel. Re-enabling pbo fixes the Intel but again screws up the AMD.
But if it's of any use, I noticed that the overlays only flickers when the video is playing: if it's paused, everything works perfectly fine.

**Comment by gtm87x** [comment] 2016-11-01 15:46
Same here, I just want to add that every time the indicators flicker, mpv drops frames.

**Comment by AirPort** [comment] 2016-11-01 20:18
Just a quick note, since I don't want to further uselessy clog this issue: for a very short time after waking up the notebook from sleep, everything worked fine with no flicker no matter the configuration, but then the old pattern kicked in reliably (`opengl-pbo=yes` > Intel fine, AMD flicker, `opengl-pbo=no` > Intel flicker, AMD fine), so the whole matter may really be actually unrelated to that specific option.
Every new Os X version has its own crappy "mysterious" issue to deal with, I guess.

**Comment by stps** [comment] 2016-11-02 01:47
To follow up for me with more info, after a couple days of testing it seems turning on PBO seems to "reliably" fix it for me on Intel and Nvidia. And it comes back if I turn it off, except for MP4 files. Though from wm4's post this sounds like more of a symptom fix.

**Comment by Lord-Kamina** [comment] 2016-11-04 01:41
I was getting this issue using and AMD GPU (HD6670M) on 10.11; hadn't actually linked the behavior to volume changes or such, but it was happening only on fullscreen during playback. And, yes, openg-pbo=yes fixes it with the AMD GPU at least (I haven't really tried the intel GPU because it's an HD3000 and I rarely, if ever, use it.

**Comment by Akemi** [comment] 2017-04-30 18:00
since i couldn't reproduce this and still can't i would like to know if PR #4391 fixes this for everyone with both pbo enabled and disabled. other issue you may encounter can be reported on the PR.

**Comment by Lord-Kamina** [comment] 2017-04-30 18:12
I am in the middle of nowhere without the HDD holding my /opt folder and a 1mbps satellite internet. i.e. I cannot test this for at least another week. :P

**Comment by stps** [comment] 2017-04-30 19:35
@Akemi I just checked out your branch and it fixes it.

**Comment by anticitizen4** [comment] 2017-12-09 17:37
I've had this issue when using `interpolation` even with `opengl-pbo` enabled, when both OCR and system interface (dock, volume or space switching) were showing. Solved this by changing `video-sync=display-resample` to `audio`.

**Comment by Akemi** [comment] 2018-02-12 12:54
fixed via c5e4538bc4b63f02bf89f62aa25a37b9eb0c0316.

**Closed by Akemi** 2018-02-12 12:54 UTC
Labels: osx
