### ISSUE TITLE
Hardware decoding fails on HEVC encoded video even though FFmpeg supports it (videotoolbox)

### ISSUE THREAD

**Issue by spaghetti-** [mpv-player/mpv#4736] opened 2017-08-08 00:37 UTC
### mpv version and platform

mpv 12cafdc (C) 2000-2017 mpv/MPlayer/mplayer2 projects (HEAD as of now)
ffmpeg version: git-2017-08-07-1bef008

Platform: macOS 10.12.5

### Reproduction steps
Play any HEVC encoded video

### Expected behavior

Hardware decoding works

### Actual behavior

```
 vo/opengl: Loading hwdec driver 'videotoolbox'
 vo/opengl: Reported display depth: -1
 vo/opengl: Assuming 59.940061 FPS for display sync.
        vd: Container reported FPS: 23.976025
        vd: Codec list:
        vd:     hevc - HEVC (High Efficiency Video Coding)
        vd: Opening video decoder hevc
        vd: Probing 'videotoolbox'...
        vd: Trying hardware decoding.
        vd: Selected video codec: hevc (HEVC (High Efficiency Video Coding))
        ad: Codec list:
        ad:     eac3 - ATSC A/52B (AC-3, E-AC-3)
        ad:     eac3_at (eac3) - eac3 (AudioToolbox)
        ad: Opening audio decoder eac3
        ad: Requesting 1 threads for decoding.
        ad: Selected audio codec: eac3 (ATSC A/52B (AC-3, E-AC-3))
   cplayer: Starting playback...
       mkv: queuing seek to 216.591000
   cplayer: hr-seek, skipping to 216.591000
       mkv: execute seek (to 216.591000 flags 40)
     cache: Dropping cache at pos 80514398, cached range: 9072-48309104.
     cache: Seeking underlying stream: 48309104 -> 80514398
       mkv: seek done
        vd: Pixel formats supported by decoder: yuv420p10le
        vd: Codec profile: Main 10 (0x2)
        vd: Requesting pixfmt 'yuv420p10le' from decoder.
        vd: Falling back to software decoding.
        vd: Detected 8 logical cores.
        vd: Requesting 9 threads for decoding.
```
### Log file

http://bpaste.net/show/5cf3c33be8c9

**Comment by wm4** [comment] 2017-08-08 14:20
FFmpeg doesn't support HEVC + VT. Even if Apple supports it, they keep the API a secret, in their usual "fuck you" style.

**Comment by bodayw** [comment] 2017-08-10 20:09
I heard "native HEVC support" coming in macOS 10.13 (High Sierra) though...So does it mean that FFmpeg won't have HEVC hwdec support on macOS any time soon, even with capable hardware (say Kaby Lake integrated GPU)?

**Comment by wm4** [comment] 2017-08-11 07:16
Once the API is known, it'll probably be relatively easy to add support for ffmpeg.

Be reminded that OSX is the worst OS for multimedia - on Windows and Linux, all this stuff has been working for a while.

**Comment by galad87** [comment] 2017-08-17 06:32
HEVC acceleration requires 10.13. They added a new api call to create a CMVideoFormatDescriptionRef and that's it. https://developer.apple.com/documentation/coremedia/core_media_functions?changes=latest_minor&language=objc

**Comment by wm4** [comment] 2017-08-17 08:15
That looks very undocumented.

I sure am "impressed" by Apple engineering.

**Comment by galad87** [comment] 2017-08-17 08:18
There is some "documentation" in the actual header file, but it seems it did not make its way to the html documentation…

**Comment by pxia** [comment] 2017-09-15 21:04
Anyone knows what needs to be changed on the ffmpeg side? Can someone submit a PR to them? I'm willing to help if anyone can provide some pointers...

**Comment by wm4** [comment] 2017-09-18 18:59
Adding a hwdec requires an annoying number of small changes to some FFmpeg files, but most of the actual logic is in `libavcodec/videotoolbox.c`.

**Comment by tmm1** [comment] 2017-09-23 06:46
Here's a diff which shows some of the documentation for the new VideoToolbox api: https://github.com/xamarin/xamarin-macios/wiki/CoreMedia-iOS-xcode9-beta1

**Comment by tmm1** [comment] 2017-09-23 22:30
I haven't upgraded to macOS 10.13 yet to test this out, but something like this should work: http://github.com/tmm1/ffmpeg/commit/af620454283862e1bdea39f5f2d31cfcce56548c

**Comment by pxia** [comment] 2017-09-26 05:24
I installed the 10.13 today and tested your changed, it doesn't seem to work. Are there any changes needed on the mpv side as well?

**Comment by tmm1** [comment] 2017-09-26 18:32
Here's an updated patch which worked for me: https://github.com/FFmpeg/FFmpeg/compare/master...tmm1:vt-hevc.patch

I took some shortcuts so it may not work on some HEVC files. Let me know how it works for you.

**Comment by tmm1** [comment] 2017-09-27 01:09
@pxia helped me test my patch and confirmed it works. I have submitted it to ffmpeg-devel here: http://ffmpeg.org/pipermail/ffmpeg-devel/2017-September/216879.html

**Comment by Manouchehri** [comment] 2017-09-27 15:51
@tmm1 Do you have a brew package to test?

**Comment by tmm1** [comment] 2017-09-29 00:08
The hevc patches have been committed to ffmpeg, so you could `brew upgrade ffmpeg --HEAD`

**Comment by pxia** [comment] 2017-09-29 00:41
You also need to rebuild mpv: `brew install --build-from-source mpv`

**Comment by pxia** [comment] 2017-09-29 01:54
I just came through a video where some segments are complete gibberish of random color strips. It plays fine in software decoding and in quicktime (in quicktime the colors are washed out though). Any thoughts?

**Comment by spaghetti-** [comment] 2017-09-30 11:38
Thank you very much @tmm1 

I'll rebuild ffmpeg to test soon (i've some ROS stuff thats dependent on ffmpeg too)

**Comment by tmm1** [comment] 2017-10-02 06:44
@pxia If you can share the sample I can try to investigate.

**Comment by pxia** [comment] 2017-10-02 11:12
You can try this file: [hevc_sample_short.mp4.zip](https://github.com/mpv-player/mpv/files/1348695/hevc_sample_short.mp4.zip). You can see the badly decoded part by opening with `mpv -hwdec=videotoolbox`. You can also transcode with `ffmpeg -hwaccel videotoolbox` and the bad part will end up in the output file in whatever format (so it's a decoder issue not a gpu issue)

Thanks for looking into this.

**Comment by topjohnwu** [comment] 2017-10-05 07:54
@tmm1 I'm using latest High Sierra, and I'm testing with both ffmpeg and mpv built from HEAD, and here's what I got:
```
    vo/gpu: Probing for best GPU context.
vo/gpu/opengl: Initializing GPU context 'cocoa'
    vo/gpu: GL_VERSION='4.1 INTEL-10.28.26'
    vo/gpu: Detected desktop OpenGL 4.1.
    vo/gpu: GL_VENDOR='Intel Inc.'
    vo/gpu: GL_RENDERER='Intel(R) HD Graphics 5300'
    vo/gpu: GL_SHADING_LANGUAGE_VERSION='4.10'
    vo/gpu: Loaded extension GL_APPLE_rgb_422.
    vo/gpu: Testing FBO format rgba16
    vo/gpu: Resizing texture: 16x16
    vo/gpu: Using FBO format rgba16.
    vo/gpu: No advanced processing required. Enabling dumb mode.
    vo/gpu: Loading hwdec driver 'videotoolbox'
    vo/gpu: Assuming 59.948830 FPS for display sync.
        vd: Container reported FPS: 23.976404
        vd: Codec list:
        vd:     hevc - HEVC (High Efficiency Video Coding)
        vd: Opening video decoder hevc
        vd: Probing 'videotoolbox'...
        vd: Trying hardware decoding.
        vd: Selected video codec: hevc (HEVC (High Efficiency Video Coding))
   cplayer: Starting playback...
        vd: Pixel formats supported by decoder: videotoolbox_vld yuv420p10le
        vd: Codec profile: Main 10 (0x2)
        vd: Requesting pixfmt 'videotoolbox_vld' from decoder.
ffmpeg/video: hevc: Unknown VideoToolbox session creation error 4294954390
        vd: Pixel formats supported by decoder: yuv420p10le
        vd: Codec profile: Main 10 (0x2)
        vd: Requesting pixfmt 'yuv420p10le' from decoder.
        vd: Falling back to software decoding.
        vd: Detected 4 logical cores.
        vd: Requesting 5 threads for decoding.
        vd: Using software decoding.
        vd: Decoder format: 3840x1600 yuv420p10 bt.2020-ncl/bt.2020/pq/limited SP=10.000000 CL=unknown (auto 0.000000/0.000000/0.000000)
        vd: Using container aspect ratio.
```
The error from what I can see should be
`ffmpeg/video: hevc: Unknown VideoToolbox session creation error 4294954390`

**Comment by pxia** [comment] 2017-10-11 22:12
Any updates?

**Comment by tmm1** [comment] 2017-10-11 22:27
Sorry I ran out of time to work on this. I guess maybe your samples have more than one VPS or more than one SPS. Right now multiple PPS are passed into the decoder, but only one VPS/SPS. You could set a breakpoint here and try to change the SPS section to match the loops used for PPS.

https://github.com/FFmpeg/FFmpeg/blob/7d2882bf52a66f52f1d978782b378427a32221bd/libavcodec/videotoolbox.c#L255

**Comment by pxia** [comment] 2017-10-31 06:23
I've made the changes as you described: https://github.com/pxia/FFmpeg/commit/10d7a29d7a413af539d33baa3312df74b2af85e0

But it doesn't seem to fix the issue :(

**Comment by pxia** [comment] 2017-11-09 10:11
@tmm1 Do you have any other idea what might cause this glitch since handling multiple VPS/SPS does not seem to fix it? Or am I handling them wrong?

**Comment by tmm1** [comment] 2017-11-09 14:58
Your patch looks correct. Did you try printing out num_* to see how many vps/sps that sample has?

**Comment by tmm1** [comment] 2017-11-10 18:11
I upgraded to High Sierra today and tried your sample. I see the same problem.

I think the issue is probably related to SEI_PREFIX/SEI_SUFFIX NALUs, which are currently not passed to the VT decoder.

**Comment by tmm1** [comment] 2017-11-10 21:47
I was able to fix this bug as part of a larger VideoToolbox patchset I'm working on. It has been submitted to ffmpeg-devel here: http://ffmpeg.org/pipermail/ffmpeg-devel/2017-November/219573.html

**Comment by pxia** [comment] 2017-11-11 04:15
I compiled from your branch and got this error: 
```
[ffmpeg] Assertion (frame->private_ref && frame->private_ref->size == sizeof(Fra
meDecodeData)) || !(avctx->codec->capabilities & (1 << 1)) failed at libavcodec/
decode.c:621
```

**Comment by wm4** [comment] 2017-11-11 04:20
The branch probably misses this bit (didn't check): https://github.com/mpv-player/ffmpeg-mpv/blob/master/libavcodec/videotoolbox.c#L74

**Comment by tmm1** [comment] 2017-11-11 04:23
If you're trying to use it with mpv, better off applying the patchset to ffmpeg-mpv fork instead.

**Comment by pxia** [comment] 2017-11-11 04:29
Tested and can confirm it's working. Thanks!

**Comment by tmm1** [comment] 2017-11-13 22:45
The patchset was pushed to ffmpeg master.

**Comment by pxia** [comment] 2017-11-14 19:45
@wm4 Is mpv compiled against ffmpeg-mpv or upstream ffmpeg in the releases? Is there any easy way to compile mpv myself without installing both versions of ffmpeg?

**Comment by tmm1** [comment] 2017-11-14 19:53
You can compile using `./waf configure --enable-ffmpeg-upstream`

**Closed** 2017-12-01 01:53 UTC

**Comment by Manouchehri** [comment] 2018-01-20 13:24
For those who find this thread after running into visual glitches when playing 10-bit HEVC files, here's the tl;dr on what you need to run:

```bash
brew install nasm texi2html 
brew upgrade --HEAD ffmpeg
brew upgrade --HEAD mpv
```
