### ISSUE TITLE
`-vo sdl` stops playback until its window is drawn

### ISSUE THREAD

**Issue by l29ah** [mpv-player/mpv#5990] opened 2018-07-15 10:31 UTC
### mpv version and platform
0.28.0-633-g351c083487-dirty

### Reproduction steps
Ask your window manager to put mpv's window on another workspace. Run mpv on some video or audio+cover tracks.

### Expected behavior
mpv plays music/video as with other video output backends.

### Actual behavior
mpv waits for you to switch to the workspace with the window and then starts the playback. It does that every time the track switches from one without cover to one with.

### Log file
```
[vo/sdl] reconfig to 1024x683 yuv420p bt.601/bt.709/bt.1886/full/display SP=1.000000 CL=mpeg1/jpeg
[vo/sdl] Window size: 1024x683
[vo/sdl] Video source: 1024x683 (72:72)
[vo/sdl] Video display: (0, 0) 1024x683 -> (0, 0) 1024x683
[vo/sdl] Video scale: 1.000000/1.000000
[vo/sdl] OSD borders: l=0 t=0 r=0 b=0
[vo/sdl] Video borders: l=0 t=0 r=0 b=0
```
[stop]
```
[vo/sdl] Window size: 638x798
[vo/sdl] Video source: 1024x683 (72:72)
[vo/sdl] Video display: (0, 0) 1024x683 -> (0, 186) 638x425
[vo/sdl] Video scale: 0.623047/0.622255
[vo/sdl] OSD borders: l=0 t=186 r=0 b=187
[vo/sdl] Video borders: l=0 t=186 r=0 b=187
```

### Sample files
Any image file will do.

**Comment by Dudemanguy** [comment] 2022-01-18 18:49
Not able to reproduce this even on wayland where it could quite likely have this issue. Assuming it's been fixed in sdl.

**Closed by Dudemanguy** 2022-01-18 18:49 UTC
Labels: vo:sdl

**Comment by l29ah** [comment] 2022-01-18 20:11
reproduced now on mpv 0.34.0-144-g22b0bac28e-dirty and sdl 2.0.20

**Comment by Dudemanguy** [comment] 2022-01-18 20:24
How are you reproducing this? Perhaps I am doing it wrong. I opened up a playlist of files with video tracks and files without video tracks. I moved it to another workspace (invisible) and then advanced through the playlist. Everytime, sound played so I didn't see any issues.
