### ISSUE TITLE
add an argument to select chroma downscaler

### ISSUE THREAD

**Issue by gaitas13** [mpv-player/mpv#13313] opened 2024-01-18 19:58 UTC
The same way that for luma you can chose the upscaler (scale) and the downscale (dscale) , it would be nice if we got an argument to downscale chroma (cdscale) and cscale is keep for choosing the chroma upscaler

### Expected behavior of the wanted feature
The chroma downscaler works as intended 
### Alternative behavior of the wanted feature
N/A
### Log file
N/A

**Comment by Jules-A** [comment] 2024-01-18 22:06
> Chroma is not downscaled at any point during mpv's rendering, so being able to choose a chroma downscaler doesn't make sense.
> 
> See: https://github.com/mpv-player/mpv/wiki/Video-output---shader-stage-diagram

I really don't get what happens when you play a video with a resolution larger than output... It seems bugged to me...
It says that's it's upscaling chroma even in that scenario: 
![image](https://github.com/mpv-player/mpv/assets/1760158/7ce34585-d7c4-4544-85c8-5272646bf26d)

but even if you use a shader to increase Chroma res 2x it will still say it's upscaling chroma using built-in but really it should be downscaling to match luma res as indicated here: 
![image](https://github.com/mpv-player/mpv/assets/1760158/8a44e56d-707e-471a-b914-443d5fd76c0d)

**Comment by llyyr** [comment] 2024-01-18 22:13
> It says that's it's upscaling chroma even in that scenario:

If the video is 4:2:0 then it still needs to upscale chroma...

**Comment by Jules-A** [comment] 2024-01-18 22:21
Oh whoops, my bad, I didn't play a frame, it updates to say downscaling in the OSD if you play: 
![image](https://github.com/mpv-player/mpv/assets/1760158/433f9664-b5d9-4dff-bdfd-4e1c3baab40b)

**Comment by hooke007** [comment] 2024-01-19 01:02
I never heard about any video playera would downscale the chroma.

**Comment by Jules-A** [comment] 2024-01-19 01:32
> I never heard about any video playera would downscale the chroma.

It's not like there's many players that do Chroma scaling without also scaling Luma though?

**Comment by hooke007** [comment] 2024-01-19 01:44
I think you don't understand chroma downscale, right?
I do not know why luma scaling is mentioned here.

**Comment by Jules-A** [comment] 2024-01-19 03:32
> I think you don't understand chroma downscale, right? I do not know why luma scaling is mentioned here.

Not really, chroma confuses the hell out of me. I think I get it now, for some reason I was thinking that if the output window was < half the source res, chroma could be downscaled first to match luma's output res.

**Comment by hooke007** [comment] 2024-01-19 03:37
chroma plane's size is always smaller than luma for common videos. Two planes need to be align first. There is no steps to downscale the chroma.

**Comment by Jules-A** [comment] 2024-01-19 06:38
> chroma plane's size is always smaller than luma for common videos. Two planes need to be align first. There is no steps to downscale the chroma.

Then what is going on here when I specifically scale the chroma to 2x output?
https://github.com/mpv-player/mpv/issues/13313#issuecomment-1899313804

**Comment by hooke007** [comment] 2024-01-19 06:50
I do not see any chroma steps. The first line is `merging planes`. Then everythings works on RGB plane.

**Comment by Jules-A** [comment] 2024-01-19 07:01
> I do not see any chroma steps. The first line is `merging planes`. Then everything works on RGB plane.

Don't you see 2 lots of downscaling steps?

**Comment by hooke007** [comment] 2024-01-19 07:16
I have no idea what you actually did in the shader.

**Comment by Jules-A** [comment] 2024-01-19 07:26
> I have no idea what you actually did in the shader.

It's just the RGB version of the Ravu-Zoom shader but with this: 
```
//!DESC RAVU-Zoom-AR (rgb, r3)
//!HOOK CHROMA
//!BIND HOOKED
//!BIND ravu_zoom_lut3
//!BIND ravu_zoom_lut3_ar
//!WIDTH OUTPUT.w 2 *
//!HEIGHT OUTPUT.h 2 *
//!OFFSET ALIGN
```

**Comment by hooke007** [comment] 2024-01-19 07:34
I am not the expert of shader but I am sure you just mess up the hook...

**Comment by Jules-A** [comment] 2024-01-19 07:45
> I am not the expert of shader but I am sure you just mess up the hook...

You don't need to be an expert to copy and paste and try it yourself... I can assure you it works, though scaling 2x output is a lot worse than just scaling to output.
PSNR, DSSIM, MAE
<details>
  <summary>1x Output:</summary>
41.209, 0.129701, 169.42 (0.00258518)

![mpv-shot0001](https://github.com/mpv-player/mpv/assets/1760158/f8839568-c893-41e9-8846-d848b285f87d)

</details>

<details>
  <summary>2x Output:</summary>

40.8395,  0.129932, 179.417 (0.00273773)
![mpv-shot0002](https://github.com/mpv-player/mpv/assets/1760158/901e7340-d7bb-4dff-857a-5eeca152a108)

</details>


<details>
  <summary>EwaLanczosSharp</summary>

40.4248, 0.130374, 182.356 (0.00278257)
![mpv-shot0003](https://github.com/mpv-player/mpv/assets/1760158/ebb579ef-1dd3-4153-84a3-23eae42d8221)

</details>

**Comment by hooke007** [comment] 2024-01-19 07:57
As I said, check those real chroma shaders to learn the proper codes to handle chroma plane.

**Comment by Jules-A** [comment] 2024-01-19 08:00
> As I said, check those real chroma shaders to learn the proper codes to handle chroma plane.

You're making no sense.

**Comment by hooke007** [comment] 2024-01-19 08:03
You just mess up the chroma plane and tell me it became worse. Of course, how could it be better? You didn't know what chroma is hours ago...

**Comment by hooke007** [comment] 2024-01-19 08:10
It's not 1x 2x chroma... Jesus, you do not even know what you were doing.

**Comment by Jules-A** [comment] 2024-01-19 08:10
> It's not 1x 2x chroma... Jesus, you do not even know what you were doing.

I never said it was, I said it was 1x, 2x OUTPUT....

**Comment by hooke007** [comment] 2024-01-19 08:11
So that is why I am saying "you do not even know what you were doing."

**Comment by Jules-A** [comment] 2024-01-19 08:14
> So that is why I am saying "you do not even know what you were doing."

Why don't you just try it yourself then if you don't believe the tests I posted?  It's really not hard to copy and paste and test it yourself instead of arguing that it doesn't work without even trying.

**Comment by hooke007** [comment] 2024-01-19 08:16
You didn't even add any codes to handle the pixels out of range. Jesus, I cannot believe why you are so convident on the field you do not understand.

**Comment by Jules-A** [comment] 2024-01-19 08:36
> You didn't even add any codes to handle the pixels out of range. Jesus, I cannot believe why you are so convident on the field you do not understand.

I figured the AR clamping was enough and even adding that code to it doesn't seem to improve results much and I couldn't spot any major visual changes. 
I'm not confident that it's correct but I am confident that it is at least improving the result, I'm not blind (the automated tests also seem to agree). 

Besides, you are completely missing the point, I'm not trying to get a perfect chroma shader, it's just to test scaling chroma > luma to show that chroma downscaling is happening.

**Comment by hooke007** [comment] 2024-01-19 08:43
>Besides, you are completely missing the point, I'm not trying to get a perfect chroma shader

The key of this issue should be: Is there any pratical and valueable use case for mpv to add an option `dcsale`?
I do not see any useful msg from the comments before.

**Comment by Artoriuz** [comment] 2024-01-19 11:57
My only input to this is that the behaviour of `vo=gpu` and `vo=gpu-next` are different. I'm typing this from memory and it could be entirely wrong, but I think `vo=gpu-next` uses your `dscale` filter to downscale chroma while `vo=gpu` uses what you have set in `cscale`.

As @dokur0chan mentioned this is only ever possible if you use a custom shader to downscale luma below chroma resolution, so in any case I don't think it matters.

**Comment by NotMithical** [comment] 2024-01-19 19:56
Like everyone else has said I don't think there's any practical use for this, but I'm fairly certain you could specify the filter used for chroma downscaling with `--libplacebo-opts-append=plane_downscaler=`

**Comment by Jules-A** [comment] 2024-01-19 20:51
> Like everyone else has said I don't think there's any practical use for this, but I'm fairly certain you could specify the filter used for chroma downscaling with `--libplacebo-opts-append=plane_downscaler=`

Oh wow, the option already existed. I can confirm it works: 
![image](https://github.com/mpv-player/mpv/assets/1760158/740b0a64-c9f1-4fef-ae88-a1df744fd53f)

**Comment by Dudemanguy** [comment] 2024-01-21 00:37
Closing since said option does actually exist.

**Closed by Dudemanguy** 2024-01-21 00:37 UTC
Labels: meta:feature-request
