### ISSUE TITLE
Feature request: Manually reset HTTP stream when connection interrupted

### ISSUE THREAD

**Issue by Lesik** [mpv-player/mpv#3722] opened 2016-10-25 11:49 UTC
Currently, streaming media from the web breaks if the network connection is interrupted, for example by going into standby or switching from 3G to WiFi. It would be great if there was a way to tell mpv to stop playback, re-establish the stream and then resume at the same place playback was interrupted.

Other than that, I wanted to compliment everybody who's working on this great piece of software, without which the media experience on Linux would be really lacking.

**Comment by wiiaboo** [comment] 2016-10-25 12:24
I use this in input.conf:
`p    loadfile "${path}"`

**Comment by garoto** [comment] 2016-10-26 16:02
Wow, nice tip wiiaboo. My ISP seems to be closing my TCP connections to Youtube at random lately, this will sure come in handy.

But I don't think the "loadfile" alone would resume playback right? Will the line below work as I imagine? (can't test right now)

> p write-watch-later-config ; loadfile "${path}"

**Comment by wiiaboo** [comment] 2016-10-26 17:07
Yeah, the loadfile trick is more meant for streams. I think I've tried using watch-later and didn't manage to make it work. For that behavior it would probably be more reliable/easier to just script it in lua.

**Comment by wm4** [comment] 2016-10-26 17:16
Is this about the HTTP/TCP connection, or refreshing the youtube-dl link?

**Comment by paulguy** [comment] 2016-10-26 18:18
I use a script from this issue https://github.com/mpv-player/mpv/issues/2256

**Comment by garoto** [comment] 2016-10-26 19:23
> Yeah, the loadfile trick is more meant for streams. [...]

I guess you mean live streams right? Btw, just tested the `write-watch-later-config ; loadfile "${path}"` bind with a Youtube video and it seems to work fine. So yay!

> Is this about the HTTP/TCP connection, or refreshing the youtube-dl link?

Not sure, I guess I was just pigbacking on the original OP issue and wiiaboo's tip.

**Comment by lachs0r** [comment] 2017-12-09 01:40
Technically a duplicate of #1548

**Closed by lachs0r** 2017-12-09 01:40 UTC
Labels: feature request
