### ISSUE TITLE
gpu-next: saturation increases with Dolby Vision enabled

### ISSUE THREAD

**Issue by FoLLgoTT** [mpv-player/mpv#9831] opened 2022-02-05 08:26 UTC
### Important Information

On Dolby Vision movies the saturation increases with vo=gpu-next. If DV is disabled saturation is lower. With vo=gpu there is no change.

vf=format:dolbyvision=no:
![dv=no_klein](https://user-images.githubusercontent.com/95616074/152634408-419dd2c5-d588-4859-b6c6-36803200d996.jpg)

vf=format:dolbyvision=yes:
![dv=yes_klein](https://user-images.githubusercontent.com/95616074/152634412-e3a6b1af-b101-41f5-8301-6271110a8280.jpg)

### Reproduction steps

Play DV movie and deacitvate DV with vf=format:dolbyvision=no.

### Expected behavior
Saturation stays the same.

### Actual behavior
Saturation is higher.

### Log file

[dv_no.txt](https://github.com/mpv-player/mpv/files/8007644/dv_no.txt)
[dv_yes.txt](https://github.com/mpv-player/mpv/files/8007645/dv_yes.txt)

**Comment by ValZapod** [comment] 2022-02-05 16:35
This is not even Dolby Vision profile 5. is this some kind of blu-ray? Or is this hybrid?

**Comment by FoLLgoTT** [comment] 2022-02-05 17:26
> is this some kind of blu-ray?

Yes, a UHD Blu-ray. I guess they are downward compatible in some way, because every player must be able to play this.


> As a rule: just always watch/use profile 5.

I don't know much about the DV format. Where can I change the profile? Do you mean in the stream?

**Comment by ValZapod** [comment] 2022-02-05 18:01
> Do you mean in the stream?

No, you need contentlike that.

>Yes, a UHD Blu-ray.

They use MEL or FEL that we do not support yet. This should be printing as unsupported NAL 63. If it does not well again this is bad rip.

**Comment by quietvoid** [comment] 2022-02-05 23:13
The saturation difference comes from the Dolby Vision metadata being processed or not.

I don't think it's a bug, Dolby Vision isn't processed at all with `vo=gpu`.
I could verify this by removing the polynomial/MMR mapping, which then becomes identical to HDR10 even with `vf=format:dolbyvision=yes`.

Also, `libplacebo` always uses the mastering display from the Dolby Vision metadata when using `vf=format:dolbyvision=yes`.
So this can also affect the tone mapping algorithm and mode used, if the Dolby Vision mastering display brightness differs from what's in the HDR10 stream.

**Comment by ValZapod** [comment] 2022-02-05 23:17
> BT.2020+PQ, but it has dolby vision metadata attached

I am sorry? HLG + BT.2020 as in iPhone can also have dolby vision MMR attached. We do support it, do not we?

> Dolby Vision isn't processed at all with `vo=gpu`.

Yes, we know that. I do not think the author does not know that? Right?


> luminance is 4000 nits in Dolby Vision, and only 1000 in the HDR10 metadata.

Oh. That is nice LOL.

**Comment by FoLLgoTT** [comment] 2022-02-06 08:19
Thank you for your answers. I checked a few other Blu-ray with DV and they dind't show the problem. So it seems to be a problem of this movie only.

Maybe the media info gives more information?


Video
ID                                       : 1
ID in the original source medium         : 4113 (0x1011)
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@High
HDR format                               : Dolby Vision, Version 1.0, dvhe.07.06, BL+EL+RPU, Blu-ray compatible / SMPTE ST 2086, HDR10 compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 1 h 35 min
Bit rate                                 : 55,0 Mb/s
Width                                    : 3 840 Pixel
Height                                   : 2 160 Pixel
Display aspect ratio                     : 16:9
Frame rate mode                          : konstant
Frame rate                               : 23,976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.276
Stream size                              : 36,6 GiB (88%)
Default                                  : Ja
Forced                                   : Nein
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0010 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 1000 cd/m2
Maximum Frame-Average Light Level        : 999 cd/m2
Original source medium                   : Blu-ray

**Comment by quietvoid** [comment] 2022-02-06 14:32
> Thank you for your answers. I checked a few other Blu-ray with DV and they dind't show the problem. So it seems to be a problem of this movie only.

Unless you looked at the other movies' metadata (RPUs, using `dovi_tool`), this isn't really useful to know.

&nbsp;

Let's say we manually set every parameter, and only change the metadata within the Dolby Vision RPUs.
In my case I tested with `mpv --no-config --vo=gpu-next --hdr-compute-peak=yes --tone-mapping=bt.2390 --tone-mapping-param=1 --gamut-mapping-mode=clip --tone-mapping-mode=rgb`

Original metadata:
![01fulldovi](https://user-images.githubusercontent.com/39477805/152685510-5d06daf0-d354-4316-8dc7-b84221606567.jpg)

Here we see the saturation increase.
If we keep the MMR metadata, and only adjust the mastering display min/max luminance, we simply get a slight bump in near black brightness, since the reference black point is now lower.
Saturation stays the same.

Removed MMR metadata, and matched mastering display min/max:
![03removed-mmr-matched-mdl](https://user-images.githubusercontent.com/39477805/152685551-1ae25f9f-41da-4552-baea-07dd2e72b755.jpg)

We don't get the saturation increase.
This also looks identical to using `--vf=format:dolbyvision=no`

So, the conclusion is that the MMR mapping makes a difference here when applied to the chroma planes.

There's no easy way to validate the process, because it's entirely proprietary.
One possible option would be to use the Dolby Vision extension on Windows Movies & TV application, and tonemap to SDR with and without the metadata.

**Comment by ValZapod** [comment] 2022-02-06 20:10
> If we keep the MMR metadata, and

So is it up to MMR reshaping or due to different metadata in RPU level 6 metadata MAXCLL/MAXFALL? You are saying the first after all?

BTW, my issue with seeking and wrong colors after seek for a second is now fixed after latest nvidia driver. Strange, I know.

**Comment by quietvoid** [comment] 2022-02-06 21:27
> So is it up to MMR reshaping or due to different metadata in RPU level 6 metadata MAXCLL/MAXFALL? You are saying the first after all?

Like I said:
> So, the conclusion is that the MMR mapping makes a difference here when applied to the chroma planes.

**Comment by haasn** [comment] 2022-09-27 23:57
So, can this be closed? Is it working as intended, according to how the sample was authored?

**Comment by quietvoid** [comment] 2022-09-28 00:12
> So, can this be closed? Is it working as intended, according to how the sample was authored?

The intended behaviour requires complete Dolby Vision processing, as the sample here is profile 7 and has a meaningful enhancement layer.

So there's 2 ways to solve this issue:

- Ignoring the colour processing from the RPU for profile 7 files.
- Implementing the enhancement layer processing.

**Comment by haasn** [comment] 2022-09-28 00:24
@quietvoid I could easily disable DV reshaping if `!disable_residual_flag`. Do you think that's sufficient? It seems to map onto whether or not an EL is present in practice

**Comment by quietvoid** [comment] 2022-09-28 00:26
> @quietvoid I could easily disable DV reshaping if `!disable_residual_flag`. Do you think that's sufficient? It seems to map onto whether or not an EL is present in practice

Yea it should be fine.

**Closed** 2022-09-28 00:29 UTC
Labels: os:win, vo:gpu-next

**Comment by ZaquL** [comment] 2022-09-30 04:38
Can you at least add an option? Private API. The fact is partial decode is nore accurate, and of course I think we are just 2 or 3 steps away from porting FEL stuff. See https://github.com/erazortt/DoViBaker
