### ISSUE TITLE
Crashed when enable hwdec

### ISSUE THREAD

**Issue by rgbFrank** [mpv-player/mpv#7763] opened 2020-05-26 09:52 UTC
### mpv version and platform
mpv 0.32.0-521-gb1d16a2300 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Tue May 26 17:13:27 CST 2020
FFmpeg library versions:
   libavutil       56.49.100
   libavcodec      58.87.101
   libavformat     58.43.100
   libswscale      5.6.101
   libavfilter     7.83.100
   libswresample   3.6.100
FFmpeg version: N-97942-g731c775898

### Reproduction steps
Play this file in macOS using videotoolbox hwdec: 
链接:https://pan.baidu.com/s/1FX7UF-x1Jf1e3c0z9qtyqQ  密码:a18t

mpv 2019_0410_160925_008B.MP4 --hwdec=yes

### Expected behavior
It should play.

### Actual behavior
It crashed.
Other HEVC files work with videotoolbox hwdec. And it plays fine without hwdec.

### Log file

- Thread 2 Crashed:: mpv/mpv core
0   libsystem_kernel.dylib        	0x00007fff6d5357fa __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff6d5f2bc1 pthread_kill + 432
2   libsystem_c.dylib             	0x00007fff6d4bca1c abort + 120
3   libavcodec.58.dylib           	0x000000010c30d2d2 ff_h264_ref_picture + 178 (h264_picture.c:71)
4   libavcodec.58.dylib           	0x000000010c31f005 h264_frame_start + 693 (h264_slice.c:510)
5   libavcodec.58.dylib           	0x000000010c31a7a6 h264_field_start + 3030 (h264_slice.c:1651)
6   libavcodec.58.dylib           	0x000000010c318845 ff_h264_queue_decode_slice + 2037 (h264_slice.c:2174)
7   libavcodec.58.dylib           	0x000000010c32bee3 decode_nal_units + 931 (h264dec.c:649)
8   libavcodec.58.dylib           	0x000000010c32b160 h264_decode_frame + 576 (h264dec.c:1019)
9   libavcodec.58.dylib           	0x000000010c134b99 decode_simple_internal + 361 (decode.c:342)
10  libavcodec.58.dylib           	0x000000010c1349fd decode_simple_receive_frame + 61 (decode.c:538)
11  libavcodec.58.dylib           	0x000000010c13090c decode_receive_frame_internal + 172 (decode.c:556)
12  libavcodec.58.dylib           	0x000000010c13081c avcodec_send_packet + 364 (decode.c:614)
13  libmpv.dylib                  	0x00000001044af041 send_packet + 305 (vd_lavc.c:1017)
14  libmpv.dylib                  	0x000000010444588d lavc_process + 205 (f_decoder_wrapper.c:1284)
15  libmpv.dylib                  	0x000000010444ea00 mp_filter_graph_run + 416
16  libmpv.dylib                  	0x000000010444ee19 filter_recursive + 57 (filter.c:175)
17  libmpv.dylib                  	0x000000010444ebb7 mp_pin_out_request_data + 119 (filter.c:309)
18  libmpv.dylib                  	0x000000010446fdeb fill_audio_out_buffers + 331 (audio.c:823)
19  libmpv.dylib                  	0x00000001044933c2 run_playloop + 194 (playloop.c:1196)
20  libmpv.dylib                  	0x000000010448d737 mp_play_files + 7719 (loadfile.c:1637)
21  libmpv.dylib                  	0x000000010447260e core_thread + 62 (client.c:633)
22  libsystem_pthread.dylib       	0x00007fff6d5f2e65 _pthread_start + 148
23  libsystem_pthread.dylib       	0x00007fff6d5ee83b thread_start + 15

### Sample files
链接:https://pan.baidu.com/s/1FX7UF-x1Jf1e3c0z9qtyqQ  密码:a18t

**Comment by wm4** [comment] 2020-05-26 14:00
Can you post the terminal output? Looks like an assertion failure in ffmpeg.

**Comment by Akemi** [comment] 2020-05-26 15:15
please use a better file hoster. can't really download from this shit without an app and an account, and chinese none here can really read.

> [ffmpeg/video] h264: get_buffer() failed
> [ffmpeg] Assertion src->f->buf[0] failed at libavcodec/h264_picture.c:70
> Abort trap: 6

it's an ffmpeg problem.

**Comment by rgbFrank** [comment] 2020-05-26 16:58
Thanks for your imformation, the problem is appeared with latest ffmpeg version.  I rebuild ffmpeg-4.2.3, and it works now.

**Comment by Akemi** [comment] 2020-05-26 17:23
if the problem is in master you should definitely report this issue to ffmpeg.

**Comment by Akemi** [comment] 2020-06-06 12:45
did you report this to ffmpeg? if not could you please reupload the sample to https://0x0.st.

**Comment by LamJH** [comment] 2020-06-12 07:00
> did you report this to ffmpeg? if not could you please reupload the sample to https://0x0.st.

I happen to have an app and an account for that worst file host in the world. So I reuploaded it instead:
https://0x0.st/iVRm.MP4

**Comment by Akemi** [comment] 2020-06-12 13:21
i updated to the most recent ffmpeg and can't reproduce the crash anymore, it properly falls back to software decoding. vlc can't use videotoolbox for that sample either, neither does quicktime (it completely chokes on the file).

closing this issue because of this. if it still persists report it to ffmpeg.

**Closed by Akemi** 2020-06-12 13:21 UTC
Labels: hwdec:videotoolbox, os:mac, upstream:ffmpeg
