### ISSUE TITLE
Keybinding for rewind (speed -2.0)?

### ISSUE THREAD

**Issue by Carl-Robert** [mpv-player/mpv#5357] opened 2018-01-05 18:52 UTC
First of all, apologies for asking this in issues, but there doesn't seem to be any support forum for mpv.

So! How can I do a "rewind" keybinding? I prefer to use my videoplayer like a VCR instead of skipping with seeking. I can fastforward just fine with "multiply speed 2.0", but I have not figured a way to do the same but going backwards. Tried the same command with -2.0, but it just set the speed to slowest possible value instead of actually making it negative.

Using the latest git build for Windows 10 64-bit.

**Comment by wiiaboo** [comment] 2018-01-05 19:06
Duplicate of https://github.com/mpv-player/mpv/issues/4000

**Closed by wiiaboo** 2018-01-05 19:06 UTC

**Comment by Carl-Robert** [comment] 2018-01-05 19:16
Oh, seems I didn't try searching with proper keywords. Oh well, seems can't get everything, keep up the good work though!

**Comment by wm4** [comment] 2018-01-05 19:32
For your use case, just holding the backwards seek key down should have the same effect. We never saw a need to add a first class feature for this. Not sure if we should.

Real backwards playback is pretty different from this, and relatively hard to achieve in general with good performance.
