### ISSUE TITLE
Would it be possible to add support for .webvtt subtitles?

### ISSUE THREAD

**Issue by NomaanMalick** [mpv-player/mpv#10089] opened 2022-04-12 10:14 UTC
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature
I was streaming [this file](https://s4.gamesdrive.net/0:/The.Bad.Kids.2020.WEB-DL.1080p.H265.AAC-DanNi/The.Bad.Kids.2020.E01.WEB-DL.1080p.H265.AAC-DanNi.mkv) with mpv and despite the fact that it included three different subtitle tracks, mpv [didn't display](https://sendvid.com/ioe8z86e) any of them when selected. I learned that the included subtitles were in the ``.webvtt`` format and mpv doesn't support it. I would really appreciate if support for ``.webvtt`` subtitle format is added to mpv.

### Log file
https://www.toptal.com/developers/hastebin/raw/okuwebixoz

**Comment by Akemi** [comment] 2022-04-12 10:56
duplicate of or related to #10035 #10015 #7214

this is something that should be requested from ffmpeg. we use their subtitle parser and decoder.

**Closed by Akemi** 2022-04-12 10:56 UTC
Labels: meta:feature-request

**Comment by NomaanMalick** [comment] 2022-04-12 11:27
> duplicate of or related to #10035 #10015 #7214
> 
> this is something that should be requested from ffmpeg. we use their subtitle parser and decoder.

Thank you for your response! Would you happen to know where I could request support for ``.webvtt`` subtitle format from ffmpeg?

**Comment by dyphire** [comment] 2022-04-12 12:06
This is not even a issue of ffmpeg, it's just that the subtitles use the wrong file extension.
According to the W3C spec, the file extension of webvtt  should be `.vtt`.
> https://www.w3.org/TR/webvtt1/#iana-text-vtt

So I don't think you'll get a fix from ffmpeg. The correct approach is to try to fix all wrong files by yourself.

**Comment by NomaanMalick** [comment] 2022-04-13 13:06
> This is not even a issue of ffmpeg, it's just that the subtitles use the wrong file extension. According to the W3C spec, the file extension of webvtt should be `.vtt`.
> 
> > https://www.w3.org/TR/webvtt1/#iana-text-vtt
> 
> So I don't think you'll get a fix from ffmpeg. The correct approach is to try to fix all wrong files by yourself.

I hope it isn't too much of a hassle but can you tell me what I should do to fix this error?

![webtorrent-mpv-hook 4_13_2022 6_32_43 PM](https://user-images.githubusercontent.com/46681247/163186640-de2fa619-0bff-488a-a31d-be4281bbc929.png)
