### ISSUE TITLE
Build failed on macOS 10.14.4 "error: cannot call value of non-function type '[NSScreen]'"

### ISSUE THREAD

**Issue by valdotdev** [mpv-player/mpv#6639] opened 2019-04-15 14:33 UTC
### mpv version and platform
mpv HEAD
macOS 10.14.4
### Reproduction steps
Reinstall via Homebrew
`brew reinstall mpv`
### Expected behavior
build successful
### Actual behavior
build failed
not sure if related to #6621 but the log is attached FYR.
```
/private/tmp/mpv-20190415-12726-1t45ike/video/out/cocoa_cb_common.swift:335:39: error: cannot call value of non-function type '[NSScreen]'
        let screens = NSScreen.screens()
```
### Log file
https://0x0.st/zNyx.txt

**Comment by Akemi** [comment] 2019-04-15 15:44
duplicate of #6470, as all the other duplicates. downgrade your xcode or command line tools, and/or change the dec path with sudo `xcode-select -s PATH`.

**Closed by Akemi** 2019-04-15 15:44 UTC
