### ISSUE TITLE
Inconsistent subtitle layer flickering when using certain options on Vulkan using macOS

### ISSUE THREAD

**Issue by rcombs** [mpv-player/mpv#10709] opened 2022-10-02 19:48 UTC
This is on https://github.com/rcombs/mpv/commit/f0eecf2d3527fc3b46d7f48a197c73455b609259 (experimental version with support for gpu-next with hardware decoding, based off of https://github.com/mpv-player/mpv/pull/7482). macOS 12.6 (21G115) running on an M1 Max MBP16.

When using the following options, I get flickering in some subtitle layers, and occasional video tearing: `-video-sync=display-resample -linear-downscaling=yes -sigmoid-upscaling=yes`. This is when rendering a 1080p video at 4K. Yes, both the downscaling and upscaling args are necessary to repro reliably; I don't know why.

Flicker example: https://user-images.githubusercontent.com/819638/193473292-3e2247b5-435b-4264-80a7-b4e6f8904460.mov

Log: https://gist.github.com/80eda2a25d0d801f949da514f3ba7811
Example subtitle file: https://gist.github.com/2ebc34e6f33cd09d67b8f076a116e289

**Comment by Akemi** [comment] 2024-03-06 22:07
closing, since i can't reproduce this anymore. if it still happens we can reopen this or open a new issue.

**Closed by Akemi** 2024-03-06 22:07 UTC
Labels: os:mac, vo:gpu:macvk
