### ISSUE TITLE
Fullscreen glitch

### ISSUE THREAD

**Issue by lightonflux** [mpv-player/mpv#2697] opened 2016-01-08 07:02 UTC
Infos: 

Debian Stretch (testing at the moment) with Gnome Shell 3.18 and mpv 0.14.0-1 on a system with Intel HD4000.

The only options in the config: 

```
fs=yes
border=no
```

Video of the glitch: http://b.1339.cf/rdqsdpx.mp4

If i manually toggle fullscreen two times the glitch disappears.

**Comment by wm4** [comment] 2016-01-08 07:39
I suspect it's a Gnome bug and not a mpv issue, but nobody wants to debug this.

**Comment by lightonflux** [comment] 2016-01-08 07:55
Why do you suspect that? Anything i can do? Gnome bug report‽

**Comment by wm4** [comment] 2016-01-08 08:01
What triggers is is probably the fact that we manually set the fullscreen flag before mapping the window. This will make the window atomically show up the window as fullscreen with some window managers. I suspect Gnome gets confused by it. Whether what mpv does is allowed or not by the protocol is not entirely clear to me.

**Comment by lightonflux** [comment] 2016-01-08 08:25
In that case we should open a bug report and just ask the gnome folk.

**Comment by magcius** [comment] 2016-01-13 22:54
The bug report I got: https://bugzilla.gnome.org/show_bug.cgi?id=751585

Setting the fullscreen flag before mapping is OK (and is the only time you should set the fullscreen flag). We have pa hack to detect legacy fullscreen applications](https://git.gnome.org/browse/mutter/tree/src/x11/window-x11.c#n2014) (which map screen-sized), as I pointed out in the GNOME bug. One user reported that disabling legacy fullscreen made it work on their system. Another told me it isn't working for them.

**Comment by wm4** [comment] 2016-01-13 23:05
Is it possibly some sort of race condition?

**Comment by magcius** [comment] 2016-01-13 23:11
I don't know -- does mpv do anything after map that might be considered racy?

**Comment by wm4** [comment] 2016-01-13 23:25
It calls XChangeProperty, appending ``_NET_WM_STATE_FULLSCREEN`` to ``_NET_WM_STATE``. Then it calls XMapWindow. Then it sends a _NET_WM_STATE to set the fullscreen state (intended for WMs which don't check the attributes already set at map time).

Is this too naive?

**Comment by rtcm** [comment] 2016-01-14 17:34
Please see https://bugzilla.gnome.org/show_bug.cgi?id=751585#c13 for my analysis.

The issue I investigated there doesn't seem exactly the one reported in this video here so this might be a different issue that I couldn't reproduce.

**Comment by wm4** [comment] 2016-01-14 18:56
I think this triggers some code which attempts to restore the position after leaving fullscreen.

Immediately after sending the message to remove `_NET_WM_STATE_FULLSCREEN`, it calls XConfigureWindow() to force a proper window position/size. This was done to compensate for the behavior of some window managers. I don't remember which WMs are affected, but I could reproduce it with IceWM right now. I would say it's up to the WM what position/size the window will have once unfullscreened, but the WMs for which this hack exists did something unpleasant. IceWM makes the window almost as big as the screen.

I wonder what's a good way to handle this better? But it looks like it's not Mutter's fault.

**Comment by rtcm** [comment] 2016-01-14 19:07
Like I said in that comment, if you just leave the position unset in that XConfigureWindow() it should work fine. After all, I can understand that mpv tries to keep the window to full size of the video contents but the position should be left up  to the user and/or the WM.

**Comment by wm4** [comment] 2016-01-14 19:45
Seems to work at least with icewm and xfwm, but not with Mutter. (I didn't run a full gnome session, just Mutter - but that shouldn't matter.) In fact, even when commenting the XConfigureWindow call completely, I had to hit F 3 times to make it exit fullscreen. Did I misunderstand something?

Also, I think a XConfigureWindow which covers the screen area is not enough. Isn't it also required to remove decorations by using Motif hints?

**Comment by rtcm** [comment] 2016-01-14 20:39
Perhaps it's a different XConfigureWindow call? I can't dig into mpv's code right now, but I'm fairly sure that if you don't specify the position, mutter won't try to fullscreen the window again. When I investigated earlier, I intercepted the call inside mutter using gdb and replaced the position with what it would be if unspecified by mpv and it worked correctly.

Re. decorations: doesn't mpv already have a switch to control the usage of decorations? In any case, decorations shouldn't matter in this case.

**Comment by wm4** [comment] 2016-01-14 20:44
I'll have to check the mpv code for calls which can generate configure requests again to be sure.

**Comment by Paviluf** [comment] 2016-01-22 14:04
Any news on this ?
Thanks !

**Comment by phenest** [comment] 2016-02-14 16:29
Adding:
--geometry=0x0+0+0
seems to fix it.

**Comment by lightonflux** [comment] 2016-02-20 10:23
--geometry… works for me too.

**Comment by rtcm** [comment] 2016-04-15 14:09
Isn't this a duplicate of https://github.com/mpv-player/mpv/issues/2072 ?

**Comment by phenest** [comment] 2016-04-15 18:24
No. But the root cause might be the same for both.

**Comment by phenest** [comment] 2016-05-05 19:02
Based on a hunch, I had a look at the source code. There does not appear to be any default values for geometry.
The file options/options.c has some default values.
The structure .vo should have values for geometry: x, y, w, h should all be zero.
I haven't tested this yet.

**Comment by wm4** [comment] 2016-05-06 11:14
> The structure .vo should have values for geometry: x, y, w, h should all be zero.

They're default-initialized to 0.

**Comment by phenest** [comment] 2016-05-06 17:45
The latest Debian testing branch no longer has this problem. I've been using mpv from the repo without --geometry without issue.

**Comment by lightonflux** [comment] 2016-05-09 23:40
Can confirm that it works without the option in Debian Testing. 

Am i right assuming that the glitch was fixed by an update of another component and that the bug is not with `mpv` directly?

**Comment by phenest** [comment] 2016-05-10 17:07
The bug is not with mpv. Although I would like to know why the --geometry option corrected it. It might still be worth looking into.

**Comment by wm4** [comment] 2016-05-10 17:36
> The bug is not with mpv. 

That is not really clear. mpv does seem to be doing something sketchy, that upset mutter as it was previously described.

**Comment by phenest** [comment] 2016-05-10 18:37
The current version of mpv is 0.17 whereas the latest version in Debian Testing is 0.14. According to the Debian changelog, version 0.14 was uploaded December 2015 and is not patched. This issue was only corrected recently, so it must have been due to another package.
But, as I've already said, as that --geometry option corrected the issue before, it's still worth looking into.
Can someone point me to the source code where it shows the geometry structure being initialised please.

**Closed** 2016-11-05 22:44 UTC
Labels: not-yet-analyzed, stalled
