### ISSUE TITLE
Encoding audio completely non-functional in recent builds

### ISSUE THREAD

**Issue by hedgehog90** [mpv-player/mpv#7933] opened 2020-07-18 17:34 UTC
### Important Information

- mpv 0.32.0-579-g06033df715
- Windows 10, presumably Linux as well.

### Reproduction steps

Any command involving the --o argument produces thousands of errors and no video output.

I understand this argument is deprecated but I know @CounterPillow has offered to help maintain it (https://github.com/mpv-player/mpv/issues/7774#issuecomment-639442616).

I've tried various codecs and containers but it produces the same result...

`mpv --log-file=mpv.log --no-config --of=mpegts --ovc=libx264 --oac=aac --o=out.mkv "random-video-file.mp4"`

...Outputs a zero byte video file out.mkv and the following error...

`[ao/lavc] error encoding at ...`

...repeated in quick succession.

I tried using several older builds going as far back as mpv 0.32.0-563-gdc24a437fb, built 21st June 2020
They all had the same issue.
mpv 0.32.0-551-gc7fe4ae73a (June 11th) works.

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/4942126/mpv.log)

### Sample files

https://0x0.st/iv3_.mp4

Incidentally, I was using an older working version of mpv and this particular file was leading to the following error after playback finished and it tried to start the next file in a playlist...

`Application provided invalid, non monotonically increasing dts to muxer in stream 1: 2690689 >= 2690689`

...Which led me to test newer versions only to find it was no longer a working feature.
Anyway, that's for another issue once this is hopefully fixed.

**Comment by CounterPillow** [comment] 2020-07-18 17:38
Possibly a duplicate of #7909

**Comment by sfan5** [comment] 2020-07-18 17:40
I tested this myself and video encoding still does work so it's a duplicate indeed.

**Closed by sfan5** 2020-07-18 17:40 UTC
Labels: core:encoding
