### ISSUE TITLE
Add a config option to append media to playback queue instead of playing media instantly

### ISSUE THREAD

**Issue by GreyAsteroid** [mpv-player/mpv#8365] opened 2020-12-05 22:51 UTC
Howdy, this is a continuation of https://github.com/mpv-player/mpv/issues/2166 which was solved by allowing the use of the shift key in the gui when dropping media on the player to append instead of replace. 

What I am requesting is a config option to make this possible both via cli and when mpv is set as the default for one of its supported uri schemes through use of a config file.

**Comment by Akemi** [comment] 2020-12-05 22:59
duplicate of #3811. it's already possible for macOS and linux (umpv), and on that issue there is a script for window.

**Closed by Akemi** 2020-12-05 22:59 UTC
Labels: meta:feature-request

**Comment by GreyAsteroid** [comment] 2020-12-05 23:11
> duplicate of #3811. it's already possible for macOS and linux (umpv), and on that issue there is a script for window.

This is a request to have the feature built directly into mpv (like how it is for the gui) not a 3rd party script.

If the mpv project does not want to have this functionality built into mpv (like how it is for the gui) then please directly say so instead of what are imo bogus duplicate claims. I can try to figure it out and put in a pr but I'd like to know if it's a waste of time first.
