### ISSUE TITLE
Somehow "distorted" audio when playing on 2x speed.

### ISSUE THREAD

**Issue by zer09** [mpv-player/mpv#7664] opened 2020-04-27 06:58 UTC
### Important Information

Provide following Information:
- mpv version: mpv 0.29.1
- Linux Distribution and Version: Pop Os 19.10
- Source of the mpv binary: Pop Os distribution
- Window Manager and version: GNOME 3.34.2
- GPU driver and version: GP108M [GeForce MX150] v a1 and UHD Graphics 620 v 07

### Reproduction steps
This video I downloaded from udemy for offline use.

Just play the downloaded video and set the playback speed to 2x.

### Expected behavior
The audio should be fine like when the video is being played on browsers like Firefox or google chrome while setting the playback speed to 2x.

### Actual behavior
The audio is somehow distorted, or something robotic something high fetch or electronic. "I don't know what it called"

### Log file
https://0x0.st/ijhx.txt

### Sample files
https://0x0.st/ijhl.mp4

**Comment by mia-0** [comment] 2020-04-27 07:36
Duplicate of #4418

**Closed by mia-0** 2020-04-27 07:36 UTC
Labels: os:linux
