### ISSUE TITLE
JXL Screenshot Color is Wrong

### ISSUE THREAD

**Issue by CharlesMengCA** [mpv-player/mpv#11360] opened 2023-02-24 04:43 UTC
### Important Information

Provide following Information:
- mpv version
 https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20230223/mpv-x86_64-v3-20230222-git-985a253.7z

- Windows Version
Windows 10 22H2 19045.2673

### Reproduction steps
Play video https://www.demolandia.net/downloads.html?id=43254366
Take screenshot as JXL and JPG. The color of JXL is wrong comparing to the video played and the JPG screenshot

![mpv](https://user-images.githubusercontent.com/58993776/221059305-7ac57eb1-8482-4029-9b4e-77aa25e4d55b.PNG)

### Expected behavior
Same colour between jpg and jxl screenshots.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/10820732/output.txt)

### Sample files

[Screenshots.zip](https://github.com/mpv-player/mpv/files/10820747/Screenshots.zip)

**Comment by CharlesMengCA** [comment] 2023-02-24 04:49
May be related to commits between Feb 10 to Feb 23.

https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20230210/mpv-x86_64-v3-20230210-git-8ba7b8f.7z doesn't have this problem.

**Comment by thebombzen** [comment] 2023-02-24 14:08
This isn't related to JXL. You can reproduce this with PNG screenshots as well. I believe it's because JXL and PNG both support tagging the colorspace, and that somehow the Dolby Vision metadata isn't being passed correctly to the screenshotter, which is receiving data tagged as BT.709. @haasn thoughts?

**Comment by haasn** [comment] 2023-02-24 15:42
@thebombzen 

looks to me like the problem is an inconsistency between these two lines:

https://github.com/mpv-player/mpv/blob/master/video/out/vo_gpu_next.c#L1222
and
https://github.com/mpv-player/mpv/blob/master/video/out/vo_gpu_next.c#L1257

If `image.color` received overrides from e.g. Dolby Vision metadata, then `target.color` will be inconsistent with the color space the mpi gets tagged with. Possible solutions:

1. (Lazy) Use `mpi->params.color` + `mp_prim_to_pl`/`mp_trc_to_pl` to derive `target.color`, instead of setting it to `image.color`. This will technically fix the issue but resulting screenshots will be in the tagged csp, not the "DV" csp. May also have to strip DV metadata from `image`.
2. (Better) Define `mp_prim_from_pl`, `mp_trc_from_pl` and set `args->res->params.color` directly based on the effective `target.color` values. This would greatly simplify the logic, and also makes it more robust, as we could just drop this entire `if/else/else` branch.

In case it isn't obvious, I strongly prefer solution 2, but it comes at the downside of somebody needing to go through the colorspace enums and writing the corresponding inverse mapping tables.

**Closed** 2023-03-06 03:37 UTC
Labels: os:win
