### ISSUE TITLE
Caching slows down with time.

### ISSUE THREAD

**Issue by grappas** [mpv-player/mpv#12107] opened 2023-08-07 19:08 UTC
### Important Information

Provide following Information:
- mpv version : 0.36.0
- Platform and Version Arch Linux rolling
- Source of the mpv binary Main repo

### Reproduction steps

```
Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.
```
Done

### Expected behavior
Caching is consistent throughout all clip. Skipping is snappy.
### Actual behavior
Caching is slowing down with every minute cached. Skipping is getting more sluggish each second passed. Setting manually cache size in config doesn't do anything in the matter of experience.
### Log file
[tupa.txt](https://github.com/mpv-player/mpv/files/12284374/tupa.txt)

### Sample files

No matter the codec, size or container.

**Comment by christoph-heinrich** [comment] 2023-08-07 19:10
Duplicate of #12076

**Closed** 2023-08-07 19:14 UTC
