### ISSUE TITLE
Automatic DASH (4K, 2.5K, FullHD) Youtube playback

### ISSUE THREAD

**Issue by zsero** [mpv-player/mpv#1450] opened 2015-01-09 14:04 UTC
I've been using the following script to have the highest possible quality Youtube playback. Is it possible to have the same mechanism implemented now that youtube-dl is supported internally? Ideally it should only go for the highest resolution which the display resolution supports, for example no need to load and downsample the 4K stream on a FullHD monitor.

```
#!/bin/bash

video_url="$1"
youtube_dash_video_formats="138/266/264/137/136/22/135/134/133"
youtube_dash_audio_formats="141/172/140/171/139"
cache_settings="--cache=30000"

youtube_dash () {
  title_and_video=$(youtube-dl -g -e -f "$youtube_dash_video_formats" "$video_url" --no-playlist)
  audio=$(youtube-dl -g -f "$youtube_dash_audio_formats" "$video_url" --no-playlist)
  mpv $(echo "$title_and_video" | sed -n 2p) \
    --media-title="$(echo "$title_and_video" | sed -n 1p)" \
    --audio-file $audio \
    --demuxer-lavf-o=fflags=+ignidx \
    $cache_settings
}

normal_playback () {
  title_and_video=$(youtube-dl -g -e $video_url --no-playlist)
  mpv $(echo "$title_and_video" | sed -n 2p) \
    --media-title="$(echo "$title_and_video" | sed -n 1p)" \
    $cache_settings
}

if [[ "$1" =~ "www.youtube.com/" || "$1" =~ "youtu.be/" ]]; then
  youtube_dash
else
  normal_playback
fi
```

**Comment by wm4** [comment] 2015-01-09 14:06
Approximate duplicate of #1321.

**Closed by wm4** 2015-01-09 14:06 UTC
