### ISSUE TITLE
HDR signal peak luminance metadata not sent to the display

### ISSUE THREAD

**Issue by dechamps** [mpv-player/mpv#10129] opened 2022-04-24 10:27 UTC
- mpv version: 0.34.0
- Source of the mpv binary: [shinchiro Windows build](https://sourceforge.net/projects/mpv-player-windows/files/release/mpv-0.34.0-x86_64.7z/download)
- Windows Version: 11 21H2 22000.613 with HDR mode enabled
- GPU: NVidia 3080 Ti driver 512.15 (latest)
- Display: LG G1 via HDMI 2.1

### Reproduction steps

Play a video suitable for testing HDR metadata/tone mapping. 

I use the [Mehanik HDR10 test patterns](https://www.avsforum.com/threads/hdr10-test-patterns-set.2943380/), specifically `02. White_Color clipping\04. White_900-4000nits-MaxCLL-4000-MDL-4000.mp4`, which usually makes it obvious if the HDR metadata is being sent correctly or not.

### Expected behavior

The HDR metadata is sent correctly. In the case of the test video mentioned above, a peak luminance of 4000 nits should be sent to the display; as a result the display should apply the corresponding tone mapping curve resulting in proper gradation across the band.

### Actual behavior

The metadata appears to be sent incorrectly (i.e. the gradations disappear), even in full screen mode.

### Additional information

Note that, strangely, the issue is not always perfectly reproducible. Most of the time mpv won't be able to get the metadata across, but once in a blue moon it actually works. It's not clear to me what triggers it.

At first I thought it could be triggered by using mpv *after* using another HDR-capable player first (e.g. VLC or madVR), but that doesn't seem to always be the case.

This smells like a OS or GPU driver bug, but I will point out that **neither VLC nor madVR *ever* seem to get this wrong** (as long as they are in full screen mode) - as far as I can tell only mpv is affected.

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/8549426/log.txt)

**Comment by jeeb** [comment] 2022-04-24 12:03
Yes, I did not initially implement this in vo:gpu as I was focused on getting the general PQ stuff done (also I did not see with the test content I was utilizing in development major issues with this information missing on my specific screen).

So yes, vo=gpu with the d3d11 back-end will only set the swap chain to PQ+BT.2020 mode in 10 bit. Not pass through the HDR10 metadata.

As I have essentially rewritten [nev's changes](https://code.videolan.org/videolan/libplacebo/-/merge_requests/239) to libplacebo's d3d11 module regarding swap chain color space etc, I have a pretty good grasp on how the API works, but I think only the max brightness bit is available through the mpv interfaces right now in the location the metadata is being currently set (at swap chain creation). With that merge request's changes vo=gpu-next with `--target-colorspace-hint=yes` should set both the swap chain color space as well as the HDR10 metadata if the decoded frame has that information.

**Comment by dechamps** [comment] 2022-04-24 12:53
Thanks. A quick search reveals that the relevant API is [`IDXGISwapChain4::SetHDRMetaData`](https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_5/nf-dxgi1_5-idxgiswapchain4-sethdrmetadata). To be clear, are you saying mpv currently doesn't call this API but will in the future?

**Comment by Doofussy2** [comment] 2022-04-24 20:54
I eagerly await these updates!

**Comment by Andy2244** [comment] 2022-04-25 12:56
Out of curiosity what should i see in the test-pattern _(White_900-4000nits-MaxCLL-4000-)_ on a 1000 nits TV, with HDR on in WIn11? 
For all players (mpv, mpc-be, JRMC29) including the TV media app and Plex itself, i see the boxes merging at around 1600 nits. Yet via the Win11 Movies & TV app i see the full range?

**Comment by dechamps** [comment] 2022-04-25 13:29
> Out of curiosity what should i see in the test-pattern (White_900-4000nits-MaxCLL-4000-) on a 1000 nits TV, with HDR on in Win11?

If the full chain is working properly, i.e. assuming that the metadata is preserved throughout AND your display's HDR tone mapping is any good, you should in theory see the full range or most of it. For example, on my setup (Windows 11 21H2 22000.613 HDR ON, 3080 Ti driver 512.15, LG G1 firmware 03.20.16), I can see the difference up until 3500 nits or so using VLC and madVR, though they need to be full screen and I need to wait for about 10 seconds or so as the TV "fades" into the new metadata - it doesn't switch instantly. If I force the TV to assume 1000 nits using a hidden LG menu, the whole ramp disappears, which is exactly one what would expect and confirms that the TV is tone mapping at 4000 nits peak otherwise.

I just tested using the Windows 11 "Films & TV" app and the result seems incorrect - it's blending in at about 2500 nits or so.

Unfortunately I don't know of an easier way to diagnose HDR metadata issues - LG TVs will not tell you which peak luminance it's currently receiving over the HDMI link (not even in hidden service menus) and Windows/nvidia will not tell you what metadata it's sending, either. So basically one has no choice but to do this blind and take a guess at what's happening based on how test signals look like. AFAIK the only way to truly know what's actually happening over the HDMI connection is to use an analyser like [Dr HDMI](https://hdfury.com/product/dr-hdmi-8k/) but that's a lot of money just to confirm a single number :/

**Comment by dechamps** [comment] 2022-04-25 14:45
> yet VLC looks similar to mpv/JRMC for me, merges at around 1500 nits.

Then your setup is not tone mapping properly. Either because the component responsible for tone mapping (i.e. your display, if you're not tone mapping in the player) is bad, or because it's not getting correct metadata for some reason. Or there is something else going on which is unknowable without having direct access to your particular setup. Unfortunately this can be pretty tricky to troubleshoot given how opaque the various components tend to be in terms of diagnostics. Sadly one often find themselves fumbling in the dark when it comes to this stuff.

> If i set `target-peak = 1000` in mpv i see the full range _(no merging until last box)_ so i assume this is more "correct", since even my native TV's apps will merge at 1500 nits, so my TV has bad tonemapping?

I'm honestly not very familiar with mpv (I only started using it recently), so I'm not 100% sure what the `--target-peak=1000` option would do. Looking at the docs it seems like that would affect mpv's own tonemapping? But then that means you are tone mapping in mpv, not in your display? Does passing `--target-peak` automatically implies enabling tone mapping in mpv? Or did you enable mpv tone mapping manually as well? (Maybe someone more familiar with these options could clarify.)

To clarify: the context around my original bug report is a setup in which I want the display (i.e. my LG TV) to handle the entire tone mapping process - I don't want mpv to do any tone mapping and I want both pixel values and metadata to be passed through to the HDMI port unchanged.

> I assume for HDR10 content that's not a big issue, since most have static MaxCCL = 1000, yet Dolby Vision files usually target 4000 nits from what i have seen?

According to [this (admittedly old) post](https://liftgammagain.com/forum/index.php?threads/lg-oled-2019-pq-curve-upload-free-template-for-devicecontrol-interface.13237/page-3#post-133228), 4000-nit HDR10 movies are actually quite common:

![image](https://user-images.githubusercontent.com/866859/165111615-968cc879-e5e2-4a32-b2f7-16f6c5ce674b.png)

> So should i set `target-peak` manually and let mpv tonemap or does this also have some drawbacks?

If your display's tone mapping is bad/broken, then it might make sense to tone map in mpv instead. But the problem is, if you do that, then you have to make sure that your display's tone mapping is completely turned off (i.e. hard clipping) - you don't want tone mapping to be done twice, the results will be incorrect/bad. The way to do that depends on your particular setup and display.

**Comment by dechamps** [comment] 2022-04-25 17:19
I used 0.34.0 with all defaults, so I guess I'm using `gpu` (and the log I attached seems to confirm that).

I could try with `gpu-next`, but according to what @jeeb said above, proper HDR peak luminance metadata transmission is not implemented anywhere even in `gpu-next`, so I didn't bother.

**Comment by ValZapod** [comment] 2022-04-25 18:09
> need to wait for about 10 seconds or so as the TV "fades" into the new metadata - it doesn't switch instantly

That is a bug then. If must change every field in AVI Infoframe, previous signals for next. Gpu-next works correctly in HDR on mode of windows 11.

> Windows/nvidia will not tell you what metadata it's sending, either.

There is a small patch that allows it on windows side.

>yet Dolby Vision files usually target 4000 nits from what i have seen?

Not true. Files mastered on Pulsar sure. The problem is you need to look into RPU L6 metadata.

>Especially since this might not just affect luminance, but color gamut as well.

Yes, you are not supposed to show colors outside mastering display in specified mastering volume.

>clearly handles peaks/highlights differently/better than gpu-next which is visible in the

Dunno. I think not.

**Comment by dechamps** [comment] 2022-04-25 18:13
> That is a bug then. If must change every field in AVI Infoframe, previous signals for next.

I am pretty sure it's the TV that does this, presumably to avoid sudden/jarring luminance changes. The reason why I think it's the TV is because the same delay occurs if I override maxCLL/mastering peak in the TV hidden menu.

> > Windows/nvidia will not tell you what metadata it's sending, either.
> There is a small patch that allows it on windows side.

Oh? Picture me interested! Where can I find this patch?

**Comment by ValZapod** [comment] 2022-04-25 18:19
The patch is here: https://github.com/mpv-player/mpv/pull/9421#issuecomment-963362018

> presumably to avoid sudden/jarring luminance changes.

It must happen. For example apple 4k applies dynamic metadata of dolby vision that way in HDR10 mode: static meta changes to approximate dynamic. It is quite buggy, but if it happens on scene changes...

**Comment by dechamps** [comment] 2022-04-25 18:53
> The patch is here: [#9421 (comment)](https://github.com/mpv-player/mpv/pull/9421#issuecomment-963362018)

Ah, okay, but that's an mpv patch. I misunderstood; I thought you had a way of making the GPU driver (e.g. nvidia) indicate precisely which maxCLL it's sending down the HDMI wire at the hardware level. Knowing what maxCLL is at the output of mpv is nice I guess, but there's so much that can go wrong at the OS/driver level…

**Comment by ValZapod** [comment] 2022-04-25 19:06
> had a way of making the GPU driver (e.g. nvidia) indicate precisely which maxCLL it's currently sending

That is using the API that is documented to do precisely that.

**Comment by jeeb** [comment] 2022-04-25 19:44
> > had a way of making the GPU driver (e.g. nvidia) indicate precisely which maxCLL it's currently sending
> 
> That is using the API that is documented to do precisely that.

No it is not. The patch you are linked to is just verbose-logging what is being passed into the "please set this hint into the swap chain" API of libplacebo as part of the FFmpeg AVFrame (as haasn didn't feel like integrating the full CLL or mastering screen metadata into the mp_image structure itself).

There is no such API to my knowledge that returns exactly what the screen is currently configured to, unless it is vendor specific. And even in that case I do not know of such API.

Please stop, you are not being useful.

**Comment by jeeb** [comment] 2022-04-25 19:54
With a quick search there is an nvidia-specific API which might return the current configuration directly from the driver as a following struct: https://docs.nvidia.com/gameworks/content/gameworkslibrary/coresdk/nvapi/struct__NV__HDR__CAPABILITIES__V2.html .

(some pages mention `NvAPI_Disp_GetHdrCapabilities` being the function)

**Comment by dechamps** [comment] 2022-04-25 19:57
> With a quick search there is an nvidia-specific API which might return the current configuration directly from the driver as a following struct: https://docs.nvidia.com/gameworks/content/gameworkslibrary/coresdk/nvapi/struct__NV__HDR__CAPABILITIES__V2.html . (some pages mention `NvAPI_Disp_GetHdrCapabilities` being the function)

I suspect this will only return what the display is capable of (i.e. from its EDID), not the details of the signal it's being sent.

**Comment by jeeb** [comment] 2022-04-25 20:00
Right, quite possible. I was just doing a quick search. In that sense it would be similar to the Windows standard API that returns you the EDID information, and thus nvapi shenanigans wouldn't be required.

I did think of plugging that information into the mpv tone mapping output target brightness, but at least without the peak brightness metadata it just caused the image to lose brightness :) (although possibly if I would have set my tone mapping mode to clip it might have fared better)

**Comment by dechamps** [comment] 2022-04-25 20:04
Yeah another problem is that some displays don't populate this information in their EDID. For example my LG G1 doesn't have max luminance information in its EDID (which is a bit surprising since it's well-known to be about 750-800 nits - must have been an oversight from LG).

**Comment by ValZapod** [comment] 2022-04-25 20:48
> For example my LG G1 doesn't have max luminance information in its EDID

Yes, just like my C9. Only Sony have this meta, as you can see from EDID DB. There is one in Dolby Vision vendor block.

**Comment by ValZapod** [comment] 2022-04-26 02:43
>There is no such API to my knowledge that returns exactly what the screen is currently configured to, unless it is vendor specific. And even in that case I do not know of such API.

This is just rediculous. VK_EXT_hdr_metadata is mandated to behave correctly, WTF. It is used in games too after all. Anyway, why are we arguing if it is just a bug in LG C2 vs older models? LOL.

**Comment by Andy2244** [comment] 2022-04-26 14:18
@dechamps Quick update after fiddling with my setup last night. I did reset the TV and started with a fresh calibration and now i can see all boxes _(merges with last two)_ on the 4000 nits sample. This is with `gpu-next`, `target-colorspace-hint` and `hdr-compute-peak = no` on latest daily build.

**Comment by dechamps** [comment] 2022-04-26 18:19
> This is just rediculous. VK_EXT_hdr_metadata is mandated to behave correctly (same for dx12 and 11 counterparts), WTF. It is used in games too after all.

I would not trust HDR metadata APIs to behave correctly without double-checking on the final setup. OS have bugs. GPU drivers have bugs. Incorrect HDR metadata transmission can easily go unnoticed because its effect won't be obvious unless you know where to look.

There is also the more general problem that OSes can't blindly pass these calls through in general, because multiple applications could be running at the same time with different requirements (e.g. standard SDR apps vs a HDR video player) and the OS has to do its best to keep everyone happy. For example I noticed that with VLC and madVR, in general the metadata is only transmitted if the player is full screen. Which can lead to other potential problems e.g. the OS/driver not treating some app as full screen even though it is, and dropping its HDR metadata.

**Comment by ValZapod** [comment] 2022-04-27 07:16
> I still see the bug, that without explicitly setting `target-trc = pq` for `gpu-next` the colors are wrong, while in contrast i can omit this setting for `vo=gpu`

Yes, this is still not fixed. Same for target-prim. The swapchain requires those.

**Comment by dechamps** [comment] 2022-04-27 18:12
@Andy2244 Using your exact config, verbatim, with latest shinchiro build `mpv-x86_64-20220424-git-9d133eb`, I am still not getting proper gradation on Mehanik test sample `White_900-4000nits-MaxCLL-4000-MDL-4000.mp4`. [Here's the log.](https://github.com/mpv-player/mpv/files/8575391/log.txt)

**Comment by Andy2244** [comment] 2022-04-27 18:49
@dechamps yeah i also noticed that vlc has more pronounced boxes for the colored test sections.
The only way i could improve this test, was by also adding/changing those settings, via pre-tonemap to the target nits, while trying to preserve the dynamic range.

```
hdr-compute-peak = yes
target-peak = 1300

tone-mapping = bt.2390
tone-mapping-param=2.0
```

**Comment by jeeb** [comment] 2022-05-09 12:36
@dechamps FYI my MR into libplacebo got merged, so git master mpv  with libplacebo version >= 4.204.0 - when used with `--vo=gpu-next` and when enabling color space hints with `--target-colorspace-hint=yes` should now configure the values based on input.

**Comment by dechamps** [comment] 2022-06-11 19:34
@jeeb Sorry it took me a while to get around to testing your solution. I can confirm that, with the shinchiro 20220605 build, maxCLL metadata appears to be correctly transmitted using `--vo=gpu-next --target-colorspace-hint=yes`, as long as the player is fullscreen. Thanks!

**Closed** 2022-06-11 19:34 UTC
Labels: os:win

**Comment by dechamps** [comment] 2022-06-11 19:45
(I'll just mention in passing that it would be great if these "make it work the way it's supposed to" options could be enabled by default, instead of mpv users getting suboptimal HDR rendering out-of-the-box. Presumably it's only a question of time though.)
